### ISSUE TITLE
Import with url failed for some urls

### ISSUE THREAD

**Issue by aerogus** [Chocobozzz/PeerTube#1006]
PeerTube beta 11
Firefox 61.0.2
node v10.9.0

* **What is the expected behaviour?**
"Import with url" import the remote mp4 file into the peertube instance storage

* **What do you see instead?**
An error message 

* **Browser console log if useful:**

> Backend returned code 500, errorMessage is: Le serveur rencontre une erreur. Merci de réessayer plus tard.

* **Server log if useful (journalctl or /var/www/peertube/storage/logs):**

```
{"err":"SequelizeValidationError: Validation error: \"1\" is not a valid name.\n    at Promise.all.then (/var/www/peertube/versions/peertube-v1.0.0-beta.11/node_modules/sequelize/lib/instance-validator.js:77:15)\n    at tryCatcher (/var/www/peertube/versions/peertube-v1.0.0-beta.11/node_modules/bluebird/js/release/util.js:16:23)\n    at Promise._settlePromiseFromHandler (/var/www/peertube/versions/peertube-v1.0.0-beta.11/node_modules/bluebird/js/release/promise.js:512:31)\n    at Promise._settlePromise (/var/www/peertube/versions/peertube-v1.0.0-beta.11/node_modules/bluebird/js/release/promise.js:569:18)\n    at Promise._settlePromise0 (/var/www/peertube/versions/peertube-v1.0.0-beta.11/node_modules/bluebird/js/release/promise.js:614:10)\n    at Promise._settlePromises (/var/www/peertube/versions/peertube-v1.0.0-beta.11/node_modules/bluebird/js/release/promise.js:693:18)\n    at Promise._fulfill (/var/www/peertube/versions/peertube-v1.0.0-beta.11/node_modules/bluebird/js/release/promise.js:638:18)\n    at PromiseArray._resolve (/var/www/peertube/versions/peertube-v1.0.0-beta.11/node_modules/bluebird/js/release/promise_array.js:126:19)\n    at PromiseArray._promiseFulfilled (/var/www/peertube/versions/peertube-v1.0.0-beta.11/node_modules/bluebird/js/release/promise_array.js:144:14)\n    at Promise._settlePromise (/var/www/peertube/versions/peertube-v1.0.0-beta.11/node_modules/bluebird/js/release/promise.js:574:26)\n    at Promise._settlePromise0 (/var/www/peertube/versions/peertube-v1.0.0-beta.11/node_modules/bluebird/js/release/promise.js:614:10)\n    at Promise._settlePromises (/var/www/peertube/versions/peertube-v1.0.0-beta.11/node_modules/bluebird/js/release/promise.js:693:18)\n    at Promise._fulfill (/var/www/peertube/versions/peertube-v1.0.0-beta.11/node_modules/bluebird/js/release/promise.js:638:18)\n    at Promise._resolveCallback (/var/www/peertube/versions/peertube-v1.0.0-beta.11/node_modules/bluebird/js/release/promise.js:432:57)\n    at Promise._settlePromiseFromHandler (/var/www/peertube/versions/peertube-v1.0.0-beta.11/node_modules/bluebird/js/release/promise.js:524:17)\n    at Promise._settlePromise (/var/www/peertube/versions/peertube-v1.0.0-beta.11/node_modules/bluebird/js/release/promise.js:569:18)\n    at Promise._settlePromise0 (/var/www/peertube/versions/peertube-v1.0.0-beta.11/node_modules/bluebird/js/release/promise.js:614:10)\n    at Promise._settlePromises (/var/www/peertube/versions/peertube-v1.0.0-beta.11/node_modules/bluebird/js/release/promise.js:693:18)\n    at Promise._fulfill (/var/www/peertube/versions/peertube-v1.0.0-beta.11/node_modules/bluebird/js/release/promise.js:638:18)\n    at PromiseArray._resolve (/var/www/peertube/versions/peertube-v1.0.0-beta.11/node_modules/bluebird/js/release/promise_array.js:126:19)\n    at PromiseArray._promiseFulfilled (/var/www/peertube/versions/peertube-v1.0.0-beta.11/node_modules/bluebird/js/release/promise_array.js:144:14)\n    at Promise._settlePromise (/var/www/peertube/versions/peertube-v1.0.0-beta.11/node_modules/bluebird/js/release/promise.js:574:26)\n    at Promise._settlePromise0 (/var/www/peertube/versions/peertube-v1.0.0-beta.11/node_modules/bluebird/js/release/promise.js:614:10)\n    at Promise._settlePromises (/var/www/peertube/versions/peertube-v1.0.0-beta.11/node_modules/bluebird/js/release/promise.js:693:18)\n    at Promise._fulfill (/var/www/peertube/versions/peertube-v1.0.0-beta.11/node_modules/bluebird/js/release/promise.js:638:18)\n    at Promise._resolveCallback (/var/www/peertube/versions/peertube-v1.0.0-beta.11/node_modules/bluebird/js/release/promise.js:432:57)\n    at Promise._settlePromiseFromHandler (/var/www/peertube/versions/peertube-v1.0.0-beta.11/node_modules/bluebird/js/release/promise.js:524:17)\n    at Promise._settlePromise (/var/www/peertube/versions/peertube-v1.0.0-beta.11/node_modules/bluebird/js/release/promise.js:569:18)\n    at Promise._settlePromise0 (/var/www/peertube/versions/peertube-v1.0.0-beta.11/node_modules/bluebird/js/release/promise.js:614:10)\n    at Promise._settlePromises (/var/www/peertube/versions/peertube-v1.0.0-beta.11/node_modules/bluebird/js/release/promise.js:693:18)\n    at Promise._fulfill (/var/www/peertube/versions/peertube-v1.0.0-beta.11/node_modules/bluebird/js/release/promise.js:638:18)\n    at Promise._resolveCallback (/var/www/peertube/versions/peertube-v1.0.0-beta.11/node_modules/bluebird/js/release/promise.js:432:57)\n    at Promise._settlePromiseFromHandler (/var/www/peertube/versions/peertube-v1.0.0-beta.11/node_modules/bluebird/js/release/promise.js:524:17)\n    at Promise._settlePromise (/var/www/peertube/versions/peertube-v1.0.0-beta.11/node_modules/bluebird/js/release/promise.js:569:18)\n    at Promise._settlePromise0 (/var/www/peertube/versions/peertube-v1.0.0-beta.11/node_modules/bluebird/js/release/promise.js:614:10)\n    at Promise._settlePromises (/var/www/peertube/versions/peertube-v1.0.0-beta.11/node_modules/bluebird/js/release/promise.js:693:18)\n    at Promise._fulfill (/var/www/peertube/versions/peertube-v1.0.0-beta.11/node_modules/bluebird/js/release/promise.js:638:18)\n    at PromiseArray._resolve (/var/www/peertube/versions/peertube-v1.0.0-beta.11/node_modules/bluebird/js/release/promise_array.js:126:19)\n    at PromiseArray._promiseFulfilled (/var/www/peertube/versions/peertube-v1.0.0-beta.11/node_modules/bluebird/js/release/promise_array.js:144:14)\n    at Promise._settlePromise (/var/www/peertube/versions/peertube-v1.0.0-beta.11/node_modules/bluebird/js/release/promise.js:574:26)","level":"error","message":"Error in controller.","label":"videos.adhocmusic.com:443","timestamp":"2018-09-03T11:18:55.995Z"}
{"message":"195.221.138.38 - - [03/Sep/2018:11:18:55 +0000] \"POST /api/v1/videos/imports/ HTTP/1.0\" 500 - \"https://videos.adhocmusic.com/videos/upload\" \"Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:61.0) Gecko/20100101 Firefox/61.0\"\n","level":"info","label":"videos.adhocmusic.com:443","timestamp":"2018-09-03T11:18:55.997Z"}
```

The remote url to import is :
https://www.adhocmusic.com/media/video/2.mp4 (same bug with 1.mp4)

if I rename my remote file 2.mp4 with test.mp4, the import is ok

The bug seams to be when the basename is numeric.

**Comment by Chocobozzz** [comment]
Thanks, should be fixed by https://github.com/Chocobozzz/PeerTube/commit/5d112d0c3bff78546cfe9114499a76ac49a46a56
