### ISSUE TITLE
v1.0.0-beta.11 Error: Cannot find module '/dist/server'

### ISSUE THREAD

**Issue by h3zjp** [Chocobozzz/PeerTube#1035]
- PeerTube version:
   v1.0.0-beta.11 

- NodeJS version:
   v8.11.4

- What is the expected behaviour?
   The peertube instances normaly start and work.

- What do you see instead?
   Error: Cannot find module '/dist/server' is displayed and does not start.

- Server log if useful (Gist/Pastebin...):
```
Sep  9 11:55:33 nrm-gw systemd: Started PeerTube daemon.
Sep  9 11:55:33 nrm-gw systemd: Starting PeerTube daemon...
Sep  9 11:55:33 nrm-gw peertube: > peertube@1.0.0-beta.11 start /home/peertube/peertube-latest
Sep  9 11:55:33 nrm-gw peertube: > node dist/server
Sep  9 11:55:33 nrm-gw peertube: module.js:549
Sep  9 11:55:33 nrm-gw peertube: throw err;
Sep  9 11:55:33 nrm-gw peertube: ^
Sep  9 11:55:33 nrm-gw peertube: Error: Cannot find module '/home/peertube/peertube-latest/dist/server'
Sep  9 11:55:33 nrm-gw peertube: at Function.Module._resolveFilename (module.js:547:15)
Sep  9 11:55:33 nrm-gw peertube: at Function.Module._load (module.js:474:25)
Sep  9 11:55:33 nrm-gw peertube: at Function.Module.runMain (module.js:693:10)
Sep  9 11:55:33 nrm-gw peertube: at startup (bootstrap_node.js:191:16)
Sep  9 11:55:33 nrm-gw peertube: at bootstrap_node.js:612:3
Sep  9 11:55:33 nrm-gw peertube: npm ERR! code ELIFECYCLE
Sep  9 11:55:33 nrm-gw peertube: npm ERR! errno 1
Sep  9 11:55:33 nrm-gw peertube: npm ERR! peertube@1.0.0-beta.11 start: `node dist/server`
Sep  9 11:55:33 nrm-gw peertube: npm ERR! Exit status 1
Sep  9 11:55:33 nrm-gw peertube: npm ERR!
Sep  9 11:55:33 nrm-gw peertube: npm ERR! Failed at the peertube@1.0.0-beta.11 start script.
Sep  9 11:55:33 nrm-gw peertube: npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
Sep  9 11:55:33 nrm-gw peertube: npm ERR! A complete log of this run can be found in:
Sep  9 11:55:33 nrm-gw peertube: npm ERR!     /home/peertube/.npm/_logs/2018-09-09T02_55_33_507Z-debug.log
Sep  9 11:55:33 nrm-gw systemd: peertube.service: main process exited, code=exited, status=1/FAILURE
Sep  9 11:55:33 nrm-gw systemd: Unit peertube.service entered failed state.
Sep  9 11:55:33 nrm-gw systemd: peertube.service failed.
```

**Comment by Chocobozzz** [comment]
Did you follow the [installation guide](https://github.com/Chocobozzz/PeerTube/blob/develop/support/doc/production.md#installation)? What is the output of `ls -l /home/peertube` and `ls -l /home/peertube/peertube-latest`?

**Comment by h3zjp** [comment]
Following the procedure (downloading Releases .zip file without git clone), it started without any problems.
(Will not develop Branch start…?)
I will close this issue. I apologize to you for a fuss over.
