### ISSUE TITLE
Issue with peertube-upload.js

### ISSUE THREAD

**Issue by anoadragon453** [Chocobozzz/PeerTube#1098]
When trying to upload a video to my peertube instance **from the same box that it's running on**, I get the following error:

```
node dist/server/tools/peertube-upload.js -u https://peertube.myinstance.com -U root -p mypassword -n "SomeTitle" -l en -f /home/user/somecoolvid.mkv                                                                                   (node:19628) Warning: N-API is an experimental feature and could change at any time.
Uploading SomeTitle video...
Error: expected 200 "OK", got 400 "Bad Request"
    at Test._assertStatus (/home/ops/peertube/git/node_modules/supertest/lib/test.js:268:12)
    at Test._assertFunction (/home/ops/peertube/git/node_modules/supertest/lib/test.js:283:11)
    at Test.assert (/home/ops/peertube/git/node_modules/supertest/lib/test.js:173:18)              
    at assert (/home/ops/peertube/git/node_modules/supertest/lib/test.js:131:12)
    at /home/ops/peertube/git/node_modules/supertest/lib/test.js:128:5                             
    at Test.Request.callback (/home/ops/peertube/git/node_modules/superagent/lib/node/index.js:718:3)                                                                                             
    at parser (/home/ops/peertube/git/node_modules/superagent/lib/node/index.js:906:18)
    at IncomingMessage.res.on (/home/ops/peertube/git/node_modules/superagent/lib/node/parsers/json.js:19:7)                                                                                      at IncomingMessage.emit (events.js:185:15)
    at endReadableNT (_stream_readable.js:1106:12)
    at process._tickCallback (internal/process/next_tick.js:178:19)
^C
```

I do wonder why we're calling the test suite here, but alas. The process seems to hang after this. It *may* be uploading, but I left it for about 10m and there was no change. Is there supposed to be a progress indicator?

Thanks!

**Comment by Chocobozzz** [comment]
Hello,

Sorry but PeerTube does not support mkv upload.

**Comment by anoadragon453** [comment]
Apologies, but the same thing happens with an mp4 file.

```
node dist/server/tools/peertube-upload.js -u https://peertube.myinstance.com -U root -p password -n "SomeTitle" -l en -f /home/user/file.mp4
(node:21304) Warning: N-API is an experimental feature and could change at any time.
Uploading SomeTitle video...                             
Error: expected 200 "OK", got 400 "Bad Request"
    at Test._assertStatus (/home/ops/peertube/git/node_modules/supertest/lib/test.js:268:12)                          
    at Test._assertFunction (/home/ops/peertube/git/node_modules/supertest/lib/test.js:283:11)                        
    at Test.assert (/home/ops/peertube/git/node_modules/supertest/lib/test.js:173:18)                                 
    at assert (/home/ops/peertube/git/node_modules/supertest/lib/test.js:131:12)
    at /home/ops/peertube/git/node_modules/supertest/lib/test.js:128:5
    at Test.Request.callback (/home/ops/peertube/git/node_modules/superagent/lib/node/index.js:718:3)
    at parser (/home/ops/peertube/git/node_modules/superagent/lib/node/index.js:906:18)
    at IncomingMessage.res.on (/home/ops/peertube/git/node_modules/superagent/lib/node/parsers/json.js:19:7)
    at IncomingMessage.emit (events.js:185:15)
    at endReadableNT (_stream_readable.js:1106:12)
    at process._tickCallback (internal/process/next_tick.js:178:19)
^C
```

I've been able to successfully upload my videos to my instance using the following script: https://git.lecygnenoir.info/LecygneNoir/prismedia so the instance is working fine.

Any ideas?

**Comment by Chocobozzz** [comment]
Could you try with https://github.com/Chocobozzz/PeerTube/commit/542e73a26bac2bfea94b5db013bdebe0cb4d3917?

If it still do not work, I would need the server logs

**Comment by anoadragon453** [comment]
Same error I'm afraid. What logs do you need? The access logs don't seem too helpful:

```
IP - - [26/Sep/2018:15:49:07 +0200] "GET /api/v1/oauth-clients/local HTTP/1.1" 200 99 "-" "node-superagent/3.8.2"                                                                       
IP - - [26/Sep/2018:15:49:07 +0200] "POST /api/v1/users/token HTTP/1.1" 200 159 "-" "node-superagent/3.8.2"                                                                             
IP - - [26/Sep/2018:15:49:07 +0200] "GET /api/v1/users/me HTTP/1.1" 200 1822 "-" "node-superagent/3.8.2"                                                                                
IP - - [26/Sep/2018:15:49:14 +0200] "POST /api/v1/videos/upload HTTP/1.1" 400 109 "-" "node-superagent/3.8.2"
```

**Comment by Chocobozzz** [comment]
Arf, sorry: the `-l` parameter is for the licence. Use `-L en` for the language.

**Comment by anoadragon453** [comment]
Works now! A more helpful error is definitely needed to inattentive users like myself :)

Thanks!
