### ISSUE TITLE
BUG: Unable to create channel that already created before and removed now trying to recreate, but get error

### ISSUE THREAD

**Issue by FlatEarthTruther** [Chocobozzz/PeerTube#1167]
* **PeerTube version or URL:**
peertube-v1.0.0-beta.15

* **Browser name/version:**
Chrome

* **NodeJS version:**
v8.12.0

* **What is the expected behaviour?**
I expected to be able to create a channel for a user, the channel used to exist but then I deleted it and when trying to create a channel with the same name again it gives an error in the web interface frontend. 

* **What do you see instead?**
```
Server error. Please retry later.
```

* **Browser console log if useful:**
```
err:SequelizeUniqueConstraintError: Validation error
    at Query.formatError (/var/www/peertube/versions/peertube-v1.0.0-beta.15/node_modules/sequelize/lib/dialects/postgres/query.js:325:18)
    at query.catch.err (/var/www/peertube/versions/peertube-v1.0.0-beta.15/node_modules/sequelize/lib/dialects/postgres/query.js:86:18)
    at tryCatcher (/var/www/peertube/versions/peertube-v1.0.0-beta.15/node_modules/sequelize/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/var/www/peertube/versions/peertube-v1.0.0-beta.15/node_modules/sequelize/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/var/www/peertube/versions/peertube-v1.0.0-beta.15/node_modules/sequelize/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/var/www/peertube/versions/peertube-v1.0.0-beta.15/node_modules/sequelize/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/var/www/peertube/versions/peertube-v1.0.0-beta.15/node_modules/sequelize/node_modules/bluebird/js/release/promise.js:690:18)
    at _drainQueueStep (/var/www/peertube/versions/peertube-v1.0.0-beta.15/node_modules/sequelize/node_modules/bluebird/js/release/async.js:138:12)
    at _drainQueue (/var/www/peertube/versions/peertube-v1.0.0-beta.15/node_modules/sequelize/node_modules/bluebird/js/release/async.js:131:9)
    at Async._drainQueues (/var/www/peertube/versions/peertube-v1.0.0-beta.15/node_modules/sequelize/node_modules/bluebird/js/release/async.js:147:5)
    at Immediate.Async.drainQueues (/var/www/peertube/versions/peertube-v1.0.0-beta.15/node_modules/sequelize/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:810:20)
    at tryOnImmediate (timers.js:768:5)
    at processImmediate [as _immediateCallback] (timers.js:745:5) sql:INSERT INTO "actor" ("id","type","uuid","preferredUsername","url","publicKey","privateKey","followersCount","followingCount","inboxUrl","outboxUrl","sharedInboxUrl","followersUrl","followingUrl","createdAt","updatedAt") VALUES (DEFAULT,'Group','01d22ba1-d216-4ecc-befd-f947042d2800','removed','https://localhost/video-channels/removed',NULL,NULL,0,0,'https://localhost/video-channels/removed/inbox','https://localhost/video-channels/removed/outbox','https://localhost/inbox','https://localhost/video-channels/removed/followers','https://localhost/video-channels/removed/following','2018-10-02 13:52:44.452 +00:00','2018-10-02 13:52:44.452 +00:00') RETURNING *; level:error message:Error in controller. label:localhost:443 meta:err:SequelizeUniqueConstraintError: Validation error
    at Query.formatError (/var/www/peertube/versions/peertube-v1.0.0-beta.15/node_modules/sequelize/lib/dialects/postgres/query.js:325:18)
    at query.catch.err (/var/www/peertube/versions/peertube-v1.0.0-beta.15/node_modules/sequelize/lib/dialects/postgres/query.js:86:18)
    at tryCatcher (/var/www/peertube/versions/peertube-v1.0.0-beta.15/node_modules/sequelize/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/var/www/peertube/versions/peertube-v1.0.0-beta.15/node_modules/sequelize/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/var/www/peertube/versions/peertube-v1.0.0-beta.15/node_modules/sequelize/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/var/www/peertube/versions/peertube-v1.0.0-beta.15/node_modules/sequelize/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/var/www/peertube/versions/peertube-v1.0.0-beta.15/node_modules/sequelize/node_modules/bluebird/js/release/promise.js:690:18)
    at _drainQueueStep (/var/www/peertube/versions/peertube-v1.0.0-beta.15/node_modules/sequelize/node_modules/bluebird/js/release/async.js:138:12)
    at _drainQueue (/var/www/peertube/versions/peertube-v1.0.0-beta.15/node_modules/sequelize/node_modules/bluebird/js/release/async.js:131:9)
    at Async._drainQueues (/var/www/peertube/versions/peertube-v1.0.0-beta.15/node_modules/sequelize/node_modules/bluebird/js/release/async.js:147:5)
    at Immediate.Async.drainQueues (/var/www/peertube/versions/peertube-v1.0.0-beta.15/node_modules/sequelize/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:810:20)
    at tryOnImmediate (timers.js:768:5)
    at processImmediate [as _immediateCallback] (timers.js:745:5) meta:sql:INSERT INTO "actor" ("id","type","uuid","preferredUsername","url","publicKey","privateKey","followersCount","followingCount","inboxUrl","outboxUrl","sharedInboxUrl","followersUrl","followingUrl","createdAt","updatedAt") VALUES (DEFAULT,'Group','01d22ba1-d216-4ecc-befd-f947042d2800','removed','https://localhost/video-channels/removed',NULL,NULL,0,0,'https://localhost/video-channels/removed/inbox','https://localhost/video-channels/removed/outbox','https://localhost/inbox','https://localhost/video-channels/removed/followers','https://localhost/video-channels/removed/following','2018-10-02 13:52:44.452 +00:00','2018-10-02 13:52:44.452 +00:00') RETURNING *; timestamp:2018-10-02T13:52:44.491Z
```
* **Server log if useful (journalctl or /var/www/peertube/storage/logs):**

**Comment by FlatEarthTruther** [comment]
ah ok cool, thanks

**Comment by FlatEarthTruther** [comment]
I could see that the Group for the user still exists in the database even though it was removed from the frontend.

**Comment by Chocobozzz** [comment]
See https://github.com/Chocobozzz/PeerTube/issues/870#issuecomment-408814420
