### ISSUE TITLE
peertube on arm6

### ISSUE THREAD

**Issue by peertubearm** [Chocobozzz/PeerTube#1273]
Hi. Iam trying to install peertube on a raspberry 1 for a project. Iam stucked during installation of yarn. To be more precicse it is stucked while touching youtube-dl.

**What happened?**
Error during yarn install.
`peertube@raspberrypi:~/peertube-latest $ yarn install --production --pure-lockfile --network-timeout 100000000
yarn install v1.10.1
[1/5] Validating package.json...
[2/5] Resolving packages...
warning Resolution field "@types/bluebird@3.5.21" is incompatible with requested version "@types/bluebird@3.5.18"
[3/5] Fetching packages...
info fsevents@1.2.4: The platform "linux" is incompatible with this module.
info "fsevents@1.2.4" is an optional dependency and failed compatibility check. Excluding it from installation.
[4/5] Linking dependencies...
[5/5] Building fresh packages...
[1/7] ⠂ bcrypt
[7/7] ⠂ youtube-dl
[6/7] ⠂ deasync
[4/7] ⠂ rdf-canonize
error /var/www/peertube/versions/peertube-v1.0.0/node_modules/youtube-dl: Command failed.
Exit code: 1
Command: node ./scripts/download.js
Arguments: 
Directory: /var/www/peertube/versions/peertube-v1.0.0/node_modules/youtube-dl
Output:
/var/www/peertube/versions/peertube-v1.0.0/node_modules/youtube-dl/lib/downloader.js:20
        if (res.statusCode !== 302) {
                ^

TypeError: Cannot read property 'statusCode' of undefined
    at Request._callback (/var/www/peertube/versions/peertube-v1.0.0/node_modules/youtube-dl/lib/downloader.js:20:17)
    at self.callback (/var/www/peertube/versions/peertube-v1.0.0/node_modules/request/request.js:185:22)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at Request.onRequestError (/var/www/peertube/versions/peertube-v1.0.0/node_modules/request/request.js:881:8)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)`

**What do you expect to happen instead?**
Iam not expecting any error.

**Steps to reproduce:**

1. Follow the [Guide](https://github.com/Chocobozzz/PeerTube/blob/develop/support/doc/production.md)

2. Get Error during yarn command.

**Additional information**
Instead of `sudo -u peertube` iam using `su -l peertube`.
* PeerTube version or URL:
Latest Peertube version is v1.0.0
On my first try i got v1.0.0.-rc2. Second try i got v1.0.0. However, stucked with same error on both versions.
* Version:
`root@raspberrypi:/home/pi# dpkg -l | grep ffmpeg && dpkg -l | grep postgre && dpkg -l | grep redis && dpkg -l | grep yarn && dpkg -l | grep nginx
ii  ffmpeg                          7:3.2.10-1~deb9u1+rpt2            armhf        Tools for transcoding, streaming and playing of multimedia files
ii  postgresql                      9.6+181+deb9u2                    all          object-relational SQL database (supported version)
ii  postgresql-9.6                  9.6.10-0+deb9u1                   armhf        object-relational SQL database, version 9.6 server
ii  postgresql-client-9.6           9.6.10-0+deb9u1                   armhf        front-end programs for PostgreSQL 9.6
ii  postgresql-client-common        181+deb9u2                        all          manager for multiple PostgreSQL client versions
ii  postgresql-common               181+deb9u2                        all          PostgreSQL database-cluster manager
ii  postgresql-contrib-9.6          9.6.10-0+deb9u1                   armhf        additional facilities for PostgreSQL
ii  redis-server                    3:3.2.6-3+deb9u1                  armhf        Persistent key-value database with network interface
ii  redis-tools                     3:3.2.6-3+deb9u1                  armhf        Persistent key-value database with network interface (client)
ii  yarn                            1.10.1-1                          all          Fast, reliable, and secure dependency management.
ii  libnginx-mod-http-auth-pam      1.10.3-1+deb9u1                   armhf        PAM authentication module for Nginx
ii  libnginx-mod-http-dav-ext       1.10.3-1+deb9u1                   armhf        WebDAV missing commands support for Nginx
ii  libnginx-mod-http-echo          1.10.3-1+deb9u1                   armhf        Bring echo and more shell style goodies to Nginx
ii  libnginx-mod-http-geoip         1.10.3-1+deb9u1                   armhf        GeoIP HTTP module for Nginx
ii  libnginx-mod-http-image-filter  1.10.3-1+deb9u1                   armhf        HTTP image filter module for Nginx
ii  libnginx-mod-http-subs-filter   1.10.3-1+deb9u1                   armhf        Substitution filter module for Nginx
ii  libnginx-mod-http-upstream-fair 1.10.3-1+deb9u1                   armhf        Nginx Upstream Fair Proxy Load Balancer
ii  libnginx-mod-http-xslt-filter   1.10.3-1+deb9u1                   armhf        XSLT Transformation module for Nginx
ii  libnginx-mod-mail               1.10.3-1+deb9u1                   armhf        Mail module for Nginx
ii  libnginx-mod-stream             1.10.3-1+deb9u1                   armhf        Stream module for Nginx
ii  nginx                           1.10.3-1+deb9u1                   all          small, powerful, scalable web/proxy server
ii  nginx-common`
[Nodejs from Nodejs.org](https://nodejs.org/dist/v8.12.0/node-v8.12.0-linux-armv6l.tar.xz)

`root@raspberrypi:/home/pi# uname -a
Linux raspberrypi 4.14.71+ #1145 Fri Sep 21 15:06:38 BST 2018 armv6l GNU/Linux
root@raspberrypi:/home/pi# lsb_release -a
No LSB modules are available.
Distributor ID:	Raspbian
Description:	Raspbian GNU/Linux 9.4 (stretch)
Release:	9.4
Codename:	stretch`

**Comment by McFlat** [comment]
Seems like an issue with downloading youtube-dl, not peertube specifically. Maybe the connection gets dropped? or maybe your raspberry is out of space?

What happens when you create a new directory somewhere and do `npm init` select all the defaults and then do a `yarn add youtube-dl`?

**Comment by peertubearm** [comment]
I was not sure where to post. I decided to use this git, as the command is described in the guide.

```
pi@raspberrypi:~ $ mkdir test
pi@raspberrypi:~ $ cd test
pi@raspberrypi:~/test $ npm init
This utility will walk you through creating a package.json file.
It only covers the most common items, and tries to guess sensible defaults.

See `npm help json` for definitive documentation on these fields
and exactly what they do.

Use `npm install <pkg>` afterwards to install a package and
save it as a dependency in the package.json file.

Press ^C at any time to quit.
package name: (test) 
version: (1.0.0) 
description: 
entry point: (index.js) 
test command: 
git repository: 
keywords: 
author: 
license: (ISC) 
About to write to /home/pi/test/package.json:

{
  "name": "test",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC"
}


Is this OK? (yes) 
pi@raspberrypi:~/test $ yarn add youtube-dl
yarn add v1.10.1
info No lockfile found.
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
success Saved lockfile.
success Saved 52 new dependencies.
info Direct dependencies
└─ youtube-dl@1.12.2
info All dependencies
├─ ajv@5.5.2
├─ asn1@0.2.4
├─ asynckit@0.4.0
├─ aws-sign2@0.7.0
├─ aws4@1.8.0
├─ bcrypt-pbkdf@1.0.2
├─ caseless@0.12.0
├─ co@4.6.0
├─ combined-stream@1.0.7
├─ core-util-is@1.0.2
├─ dashdash@1.14.1
├─ ecc-jsbn@0.1.2
├─ extend@3.0.2
├─ extsprintf@1.3.0
├─ fast-deep-equal@1.1.0
├─ fast-json-stable-stringify@2.0.0
├─ forever-agent@0.6.1
├─ form-data@2.3.2
├─ getpass@0.1.7
├─ har-schema@2.0.0
├─ har-validator@5.1.0
├─ hashish@0.0.4
├─ hh-mm-ss@1.2.0
├─ http-signature@1.2.0
├─ is-typedarray@1.0.0
├─ isstream@0.1.2
├─ json-schema-traverse@0.3.1
├─ json-schema@0.2.3
├─ json-stringify-safe@5.0.1
├─ jsprim@1.4.1
├─ mime-db@1.36.0
├─ mime-types@2.1.20
├─ minimist@0.0.8
├─ mkdirp@0.5.1
├─ oauth-sign@0.9.0
├─ performance-now@2.1.0
├─ psl@1.1.29
├─ punycode@1.4.1
├─ qs@6.5.2
├─ request@2.88.0
├─ safe-buffer@5.1.2
├─ safer-buffer@2.1.2
├─ sshpk@1.15.1
├─ streamify@0.2.9
├─ tough-cookie@2.4.3
├─ traverse@0.6.6
├─ tunnel-agent@0.6.0
├─ tweetnacl@0.14.5
├─ uuid@3.3.2
├─ verror@1.10.0
├─ youtube-dl@1.12.2
└─ zero-fill@2.2.3
Done in 164.31s.
```

Timeout happend without `yarn--network-timeout 100000000`. I do not remember exactly when it happend, but somewhere around "linking dependencies". Using a big timeout is fine.

```
pi@raspberrypi:~/test $ df -h
Dateisystem    Größe Benutzt Verf. Verw% Eingehängt auf
/dev/root        15G    2,2G   12G   16% /
devtmpfs        213M       0  213M    0% /dev
tmpfs           217M    4,0K  217M    1% /dev/shm
tmpfs           217M    5,8M  211M    3% /run
tmpfs           5,0M    4,0K  5,0M    1% /run/lock
tmpfs           217M       0  217M    0% /sys/fs/cgroup
/dev/mmcblk0p1   43M     22M   21M   52% /boot
tmpfs            44M       0   44M    0% /run/user/1000
```

12gb should be enough, I think.
