### ISSUE TITLE
optimize-old-videos throws Error: Model not initialized

### ISSUE THREAD

**Issue by Nutomic** [Chocobozzz/PeerTube#1298]
I just updated my instance to develop (commit bcf21a376f1e26cb3e74236e4cc41909310d4c32), and tried to run the `optimize-old-videos` script. It looks like we missed something in the PR, because it immediately throws an error:

```
$ sudo -u peertube NODE_CONFIG_DIR=/var/www/peertube/config NODE_ENV=production npm run optimize-old-videos

> peertube@1.1.0-alpha.1 optimize-old-videos /var/www/peertube/versions/peertube-develop
> node ./dist/scripts/optimize-old-videos.js

{ Error: Model not initialized: "VideoModel" needs to be added to a Sequelize instance before "scope" can be called.
    at new ModelNotInitializedError (/var/www/peertube/versions/peertube-develop/node_modules/sequelize-typescript/lib/models/errors/ModelNotInitializedError.js:18:16)
    at checkInitialization (/var/www/peertube/versions/peertube-develop/node_modules/sequelize-typescript/lib/models/BaseModel.js:64:23)
    at Function._target.(anonymous function) [as scope] (/var/www/peertube/versions/peertube-develop/node_modules/sequelize-typescript/lib/models/BaseModel.js:34:21)
    at Function.listLocal (/var/www/peertube/versions/peertube-develop/dist/server/models/video/video.js:146:29)
    at /var/www/peertube/versions/peertube-develop/dist/scripts/optimize-old-videos.js:24:54
    at Generator.next (<anonymous>)
    at /var/www/peertube/versions/peertube-develop/dist/scripts/optimize-old-videos.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (/var/www/peertube/versions/peertube-develop/dist/scripts/optimize-old-videos.js:3:12)
    at run (/var/www/peertube/versions/peertube-develop/dist/scripts/optimize-old-videos.js:23:12)
    at Object.<anonymous> (/var/www/peertube/versions/peertube-develop/dist/scripts/optimize-old-videos.js:16:1)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Function.Module.runMain (module.js:694:10)
    at startup (bootstrap_node.js:204:16)
    at bootstrap_node.js:625:3
  message: 'Model not initialized: "VideoModel" needs to be added to a Sequelize instance before "scope" can be called.' }
```

**Comment by Chocobozzz** [comment]
> It looks like we missed something in the PR

Sorry, my bad. Should be fixed in https://github.com/Chocobozzz/PeerTube/commit/74cd011b6c089cac88a4b8aa76ad3be2ca4f1c15

(don't forget to backup your old video files :-) )
