### ISSUE TITLE
CLI tools fail on settings.remotes being undefined

### ISSUE THREAD

**Issue by Yetangitu** [Chocobozzz/PeerTube#1328]
**What happened?**

None of the CLI tools work, this even though the prerequisites (as listed in https://github.com/Chocobozzz/PeerTube/blob/develop/support/doc/tools.md) are fulfilled. Instead all tools complain in some way related to `settings.remotes` being undefined:

```
frank@example.org:/var/src/PeerTube$ node dist/server/tools/peertube.js auth add -u my.example.org -U frank
prompt: password:  (node:31674) Warning: N-API is an experimental feature and could change at any time.
*********

(node:31674) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'indexOf' of undefined
    at /var/src/PeerTube/dist/server/tools/peertube-auth.js:35:38
    at Generator.next (<anonymous>)
    at /var/src/PeerTube/dist/server/tools/peertube-auth.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (/var/src/PeerTube/dist/server/tools/peertube-auth.js:3:12)
    at cli_1.getSettings.then (/var/src/PeerTube/dist/server/tools/peertube-auth.js:34:37)
    at <anonymous>
...

( peertube-auth.js:35:38: if (settings.remotes.indexOf(url) === -1) { )
```

or:

```
frank@example.org:/var/src/PeerTube$ node dist/server/tools/peertube.js auth list
(node:8400) Warning: N-API is an experimental feature and could change at any time.
(node:8400) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'forEach' of undefined
    at cli_1.getSettings.then.settings (/var/src/PeerTube/dist/server/tools/peertube-auth.js:102:26)
    at <anonymous>

( peertube-auth.js:102:26: settings.remotes.forEach(element => { )
```

**What do you expect to happen instead?**

Well, it could work as intended, that'd be nice...

Given that I have not found any similar bug reports I guess this issue is either new or related to some idiosyncrasy of my installations (tried it on Debian (sid) on 32bit and 64bit servers).

**Steps to reproduce:**

1. follow the instructions at https://github.com/Chocobozzz/PeerTube/blob/develop/support/doc/tools.md to install the CLI tools

2. run any tool which tries to do anything worthwhile, e.g. anything which interacts with a PT instance

3. profit?

**Additional information**
* PeerTube version or URL:
  git
* NodeJS version:
  8.11.2

**Comment by Yetangitu** [comment]
Fixed by the above PR, please test and merge
