### ISSUE TITLE
Crash on job lock error

### ISSUE THREAD

**Issue by Tanami** [Chocobozzz/PeerTube#1353]
**What happened?**
[tube.efnet.rip:443] 2018-10-28 05:56:08.428 error: Error in job queue activitypub-http-fetcher. {
  "meta": {
    "err": {
      "stack": "Error: Missing lock for job 2 delayed\n    at Object.finishedErrors (/mnt/peertube/versions/peertube-v1.0.1/node_modules/bull/lib/scripts.js:182:16)\n    at /mnt/peertube/versions/peertube-v1.0.1/node_modules/bull/lib/job.js:263:31\n    at tryCatcher (/mnt/peertube/versions/peertube-v1.0.1/node_modules/bluebird/js/release/util.js:16:23)\n    at Promise._settlePromiseFromHandler (/mnt/peertube/versions/peertube-v1.0.1/node_modules/bluebird/js/release/promise.js:512:31)\n    at Promise._settlePromise (/mnt/peertube/versions/peertube-v1.0.1/node_modules/bluebird/js/release/promise.js:569:18)\n    at Promise._settlePromise0 (/mnt/peertube/versions/peertube-v1.0.1/node_modules/bluebird/js/release/promise.js:614:10)\n    at Promise._settlePromises (/mnt/peertube/versions/peertube-v1.0.1/node_modules/bluebird/js/release/promise.js:694:18)\n    at _drainQueueStep (/mnt/peertube/versions/peertube-v1.0.1/node_modules/bluebird/js/release/async.js:138:12)\n    at _drainQueue (/mnt/peertube/versions/peertube-v1.0.1/node_modules/bluebird/js/release/async.js:131:9)\n    at Async._drainQueues (/mnt/peertube/versions/peertube-v1.0.1/node_modules/bluebird/js/release/async.js:147:5)\n    at Immediate.Async.drainQueues [as _onImmediate] (/mnt/peertube/versions/peertube-v1.0.1/node_modules/bluebird/js/release/async.js:17:14)\n    at processImmediate (timers.js:632:19)",
      "message": "Missing lock for job 2 delayed"
    }
  }
}

**What do you expect to happen instead?**
I am not sure.

**Steps to reproduce:**
I am not sure.

**Additional information**
* PeerTube version or URL: v1.0.1
* Browser name/version: Chromium 71.0.3573.0
* NodeJS version: v11.0

* Link to browser console log if useful: n/a
* Link to server log if useful (journalctl or /var/www/peertube/storage/logs/):

**Comment by Tanami** [comment]
Also just FYI, this issue appeared to stop after I unfollowed a particular feed
