### ISSUE TITLE
Error: connect ECONNREFUSED 127.0.0.1:5432

### ISSUE THREAD

**Issue by anmol26s** [Chocobozzz/PeerTube#1369]
Hi
One of the Yunohost user is getting an error while running the Peertube instance. Can you please tell the cause of the error?

```
nov. 02 07:36:13 acab.ovh peertube[6323]: npm ERR!
nov. 02 07:36:13 acab.ovh peertube[6323]: npm ERR! Failed at the peertube@1.0.1 start script.
nov. 02 07:36:13 acab.ovh peertube[6323]: npm ERR! This is probably not aproblem with npm. There is likely additional logging output above.
nov. 02 07:36:13 acab.ovh systemd[1]: peertube.service: Main process exited, code=exited, status=255/n/a
nov. 02 07:36:13 acab.ovh systemd[1]: peertube.service: Unit entered failed state.
nov. 02 07:36:13 acab.ovh systemd[1]: peertube.service: Failed with result 'exit-code'.
nov. 02 07:36:13 acab.ovh systemd[1]: peertube.service: Service hold-off time over, scheduling restart.
nov. 02 07:36:13 acab.ovh systemd[1]: Stopped peertube daemon.
nov. 02 07:36:13 acab.ovh systemd[1]: Started peertube daemon.
nov. 02 07:36:14 acab.ovh peertube[6353]: > peertube@1.0.1 start /var/www/peertube
nov. 02 07:36:14 acab.ovh peertube[6353]: > node dist/server
nov. 02 07:36:16 acab.ovh peertube[6353]: [peertube.acab.ovh:443] 2018-11-02 07:36:16.469 error: Cannot start application. {
nov. 02 07:36:16 acab.ovh peertube[6353]:   "meta": {
nov. 02 07:36:16 acab.ovh peertube[6353]:     "err": {
nov. 02 07:36:16 acab.ovh peertube[6353]:       "stack": "SequelizeConnectionRefusedError: connect ECONNREFUSED 127.0.0.1:5432\n    at connection.connect.err (/var/www/peertube/node_modules/sequelize/lib/dialects/postgres/connection-manager.js:116:24)\n    at Connection.connectingErrorHandler (/var/www/peertube/node_modules/pg/lib/client.js:123:14)\n    at emitOne (events.js:116:13)\n    at Connection.emit (events.js:211:7)\n    at Socket.reportStreamError (/var/www/peertube/node_modules/pg/lib/connection.js:71:10)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at emitErrorNT (internal/streams/destroy.js:66:8)\n    at _combinedTickCallback (internal/process/next_tick.js:139:11)\n    at process._tickCallback (internal/process/next_tick.js:181:9)",
nov. 02 07:36:16 acab.ovh peertube[6353]:       "message": "connect ECONNREFUSED 127.0.0.1:5432",
nov. 02 07:36:16 acab.ovh peertube[6353]:       "name": "SequelizeConnectionRefusedError",
nov. 02 07:36:16 acab.ovh peertube[6353]:       "parent": {
nov. 02 07:36:16 acab.ovh peertube[6353]:         "stack": "Error: connect ECONNREFUSED 127.0.0.1:5432\n    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1191:14)",
nov. 02 07:36:16 acab.ovh peertube[6353]:         "message": "connect ECONNREFUSED 127.0.0.1:5432",
nov. 02 07:36:16 acab.ovh peertube[6353]:         "errno": "ECONNREFUSED",nov. 02 07:36:16 acab.ovh peertube[6353]:         "code": "ECONNREFUSED",
nov. 02 07:36:16 acab.ovh peertube[6353]:         "syscall": "connect",
nov. 02 07:36:16 acab.ovh peertube[6353]:         "address": "127.0.0.1",
nov. 02 07:36:16 acab.ovh peertube[6353]:         "port": 5432
nov. 02 07:36:16 acab.ovh peertube[6353]:       },
nov. 02 07:36:16 acab.ovh peertube[6353]:       "original": {
nov. 02 07:36:16 acab.ovh peertube[6353]:         "stack": "Error: connect ECONNREFUSED 127.0.0.1:5432\n    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1191:14)",
nov. 02 07:36:16 acab.ovh peertube[6353]:         "message": "connect ECONNREFUSED 127.0.0.1:5432",
nov. 02 07:36:16 acab.ovh peertube[6353]:         "errno": "ECONNREFUSED",nov. 02 07:36:16 acab.ovh peertube[6353]:         "code": "ECONNREFUSED",
nov. 02 07:36:16 acab.ovh peertube[6353]:         "syscall": "connect",
nov. 02 07:36:16 acab.ovh peertube[6353]:         "address": "127.0.0.1",
nov. 02 07:36:16 acab.ovh peertube[6353]:         "port": 5432
nov. 02 07:36:16 acab.ovh peertube[6353]:       }
nov. 02 07:36:16 acab.ovh peertube[6353]:     }
nov. 02 07:36:16 acab.ovh peertube[6353]:   },
nov. 02 07:36:16 acab.ovh peertube[6353]:   "err": {
nov. 02 07:36:16 acab.ovh peertube[6353]:     "stack": "SequelizeConnectionRefusedError: connect ECONNREFUSED 127.0.0.1:5432\n    at connection.connect.err (/var/www/peertube/node_modules/sequelize/lib/dialects/postgres/connection-manager.js:116:24)\n    at Connection.connectingErrorHandler (/var/www/peertube/node_modules/pg/lib/client.js:123:14)\n    at emitOne (events.js:116:13)\n    at Connection.emit (events.js:211:7)\n    at Socket.reportStreamError (/var/www/peertube/node_modules/pg/lib/connection.js:71:10)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at emitErrorNT (internal/streams/destroy.js:66:8)\n    at _combinedTickCallback (internal/process/next_tick.js:139:11)\n    at process._tickCallback (internal/process/next_tick.js:181:9)",
nov. 02 07:36:16 acab.ovh peertube[6353]:     "message": "connect ECONNREFUSED 127.0.0.1:5432",
nov. 02 07:36:16 acab.ovh peertube[6353]:     "name": "SequelizeConnectionRefusedError",
nov. 02 07:36:16 acab.ovh peertube[6353]:     "parent": {
nov. 02 07:36:16 acab.ovh peertube[6353]:       "stack": "Error: connect ECONNREFUSED 127.0.0.1:5432\n    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1191:14)",
nov. 02 07:36:16 acab.ovh peertube[6353]:       "message": "connect ECONNREFUSED 127.0.0.1:5432",
nov. 02 07:36:16 acab.ovh peertube[6353]:       "errno": "ECONNREFUSED",
nov. 02 07:36:16 acab.ovh peertube[6353]:       "code": "ECONNREFUSED",
nov. 02 07:36:16 acab.ovh peertube[6353]:       "syscall": "connect",
nov. 02 07:36:16 acab.ovh peertube[6353]:       "address": "127.0.0.1",
nov. 02 07:36:16 acab.ovh peertube[6353]:       "port": 5432
nov. 02 07:36:16 acab.ovh peertube[6353]:     },
nov. 02 07:36:16 acab.ovh peertube[6353]:     "original": {
nov. 02 07:36:16 acab.ovh peertube[6353]:       "stack": "Error: connect ECONNREFUSED 127.0.0.1:5432\n    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1191:14)",
nov. 02 07:36:16 acab.ovh peertube[6353]:       "message": "connect ECONNREFUSED 127.0.0.1:5432",
nov. 02 07:36:16 acab.ovh peertube[6353]:       "errno": "ECONNREFUSED",
nov. 02 07:36:16 acab.ovh peertube[6353]:       "code": "ECONNREFUSED",
nov. 02 07:36:16 acab.ovh peertube[6353]:       "syscall": "connect",
nov. 02 07:36:16 acab.ovh peertube[6353]:       "address": "127.0.0.1",
nov. 02 07:36:16 acab.ovh peertube[6353]:       "port": 5432
nov. 02 07:36:16 acab.ovh peertube[6353]:     }
nov. 02 07:36:16 acab.ovh peertube[6353]:   }
nov. 02 07:36:16 acab.ovh peertube[6353]: }
nov. 02 07:36:16 acab.ovh peertube[6353]: npm ERR! code ELIFECYCLE
nov. 02 07:36:16 acab.ovh peertube[6353]: npm ERR! errno 255
nov. 02 07:36:16 acab.ovh peertube[6353]: npm ERR! peertube@1.0.1 start: `node dist/server`
nov. 02 07:36:16 acab.ovh peertube[6353]: npm ERR! Exit status 255
nov. 02 07:36:16 acab.ovh peertube[6353]: npm ERR!
nov. 02 07:36:16 acab.ovh peertube[6353]: npm ERR! Failed at the peertube@1.0.1 start script.
nov. 02 07:36:16 acab.ovh peertube[6353]: npm ERR! This is probably not aproblem with npm. There is likely additional logging output above.
nov. 02 07:36:16 acab.ovh systemd[1]: peertube.service: Main process exited, code=exited, status=255/n/a
nov. 02 07:36:16 acab.ovh systemd[1]: peertube.service: Unit entered failed state.
nov. 02 07:36:16 acab.ovh systemd[1]: peertube.service: Failed with result 'exit-code'.
nov. 02 07:36:16 acab.ovh systemd[1]: peertube.service: Service hold-off time over, scheduling restart.
nov. 02 07:36:16 acab.ovh systemd[1]: Stopped peertube daemon.
nov. 02 07:36:16 acab.ovh systemd[1]: Started peertube daemon.
nov. 02 07:36:17 acab.ovh peertube[6383]: > peertube@1.0.1 start /var/www/peertube
nov. 02 07:36:17 acab.ovh peertube[6383]: > node dist/server
```

**Comment by ldidry** [comment]
5432 is PostgreSQL port. So PostgreSQL is not started, or login/password for the database are not good (or `pg_hba.conf` does not allow connections from 127.0.0.1, but I don't think, it would be weird since it's the default behavior of a newly installed PostgreSQL).

**Comment by anmol26s** [comment]
@ldidry 
Thanks for hinting the error from the debug. It solved the problem.
https://github.com/YunoHost-Apps/peertube_ynh/issues/56#issuecomment-435483859

**Comment by wly185** [comment]
for mine i realise i had set the field wrongly it should be postgres
also i did not install postgresql on my machine
and i had to go into pgadmin to test things out 

here's the deets:
config file > "dialect":"postgres"
not postgres

also $ psql to make sure postgres is running
if not download and set the path var C:\Program Files\PostgreSQL\"version"\bin, 
else find the path by going into C:\Program Files\
