### ISSUE TITLE
Import script fails

### ISSUE THREAD

**Issue by roipoussiere** [Chocobozzz/PeerTube#1453]
**What happened?**

After executing the import script like this:

    node dist/server/tools/peertube-import-videos.js -u "https://videosdulib.re/" -U "toulibre" --password "<PeerTube password>" -t "https://www.youtube.com/channel/UCceC8Q8hThsWwmhqkjclcZg"

It failed with this error:

```
Error: expected 200 "OK", got 404 "Not Found"
    at Test._assertStatus (<peertube path>/node_modules/supertest/lib/test.js:268:12)
    at Test._assertFunction (<peertube path>/node_modules/supertest/lib/test.js:283:11)
    at Test.assert (<peertube path>/node_modules/supertest/lib/test.js:173:18)
    at localAssert (<peertube path>/node_modules/supertest/lib/test.js:131:12)
    at <peertube path>/node_modules/supertest/lib/test.js:128:5
    at Test.Request.callback (<peertube path>/node_modules/superagent/lib/node/index.js:728:3)
    at IncomingMessage.parser (<peertube path>/node_modules/superagent/lib/node/index.js:916:18)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
    at process._tickCallback (internal/process/next_tick.js:181:9)
```

Note that:
- I verified the PeerTube url, user and password,
- youtube-dl can successfully download videos metadata for this channel with `youtube-dl -F https://www.youtube.com/channel/UCceC8Q8hThsWwmhqkjclcZg`

**What do you expect to happen instead?**

The script starts to import videos.

**Additional information**
* PeerTube version or URL: 1.0.1 - https://videosdulib.re (commit 06471769)
* Browser name/version: -
* NodeJS version: v8.14.0

**Comment by roipoussiere** [comment]
Problem solved.

Some suggestions to avoid similar issues:

- in the script, automatically remove the eventual trailing `/` at the end of urls;
- in the documentation, use `'` instead of `"` because passwords can contains special characters.

**Comment by HesioZ** [comment]
I'll edit the script to remove the eventual trailing / at the end of urls.
