### ISSUE TITLE
Server Crash when a user upload file without video stream

### ISSUE THREAD

**Issue by gegeweb** [Chocobozzz/PeerTube#1478]
**What happened?**
Serveur crash just after upload when the file doesn't have a video stream.
There is an unmanaged exception for that.

See this thread on the fediverse : 
https://stoneartprod.xyz/@gegeweb/101224220014253031

**Additional information**
* PeerTube version or URL: 1.1.0
* NodeJS version: 11.2

* Link to server log if useful (journalctl or /var/www/peertube/storage/logs/):

```
[peertube.gegeweb.eu:443] 2018-12-11 21:09:02.231 info: 83.159.46.16 - - [11/Dec/2018:20:09:02 +0000] "GET /client/fr_FR/validate.e3c1356d65f85bfcfefc.svg HTTP/1.0" 200 824 "https://peertube.gegeweb.eu/videos/upload" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/12.0.2 Safari/605.1.15"

[peertube.gegeweb.eu:443] 2018-12-11 21:09:04.481 error: uncaughtException: Cannot find video stream of /var/www/peertube/storage/videos/206b690e5210f9f4ff1f47fb8608c284.mp4
Error: Cannot find video stream of /var/www/peertube/storage/videos/206b690e5210f9f4ff1f47fb8608c284.mp4
    at ffmpeg.ffprobe (/var/www/peertube/versions/peertube-v1.1.0/dist/server/helpers/ffmpeg-utils.js:165:23)
    at handleCallback (/var/www/peertube/versions/peertube-v1.1.0/node_modules/fluent-ffmpeg/lib/ffprobe.js:106:9)
    at handleExit (/var/www/peertube/versions/peertube-v1.1.0/node_modules/fluent-ffmpeg/lib/ffprobe.js:223:11)
    at ChildProcess.<anonymous> (/var/www/peertube/versions/peertube-v1.1.0/node_modules/fluent-ffmpeg/lib/ffprobe.js:237:11)
    at ChildProcess.emit (events.js:182:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:254:12)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! peertube@1.1.0 start: `node dist/server`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the peertube@1.1.0 start script.
```

**Comment by Chocobozzz** [comment]
Thanks for the issue, it should be fixed by https://github.com/Chocobozzz/PeerTube/commit/9ecac97be024cf2277872986950d7eec85cbc76e
