### ISSUE TITLE
« Error: Missing lock for job xxx … »

### ISSUE THREAD

**Issue by gegeweb** [Chocobozzz/PeerTube#1485]
**What happened?**
This bug is related to #1475 and probably #1353.
#1475 have resolved the server chrash at this error, but not its origin.

I can't tell when it appeared, probably with the upgrade to 1.0.1, I was always on 1.0.1 under FreeBSD 11.1 and node 9.8 when I reported the #1475.

I had a lot of « Error: Missing lock for job [xxx] [status] » at the end of tasks. Status are finished or failed.

Mainly at the end of the encoding tasks but not exclusively as reported in the #1475 comments.

If I can help more, tell me what to look for in the logs.
This no longer seems to be a problem, except for finished tasks whose status is not updated and are always in the waiting or active queue even if ended.

* Link to server log if useful (journalctl or /var/www/peertube/storage/logs/):

In the task list on Peertube (client side, Admin section) :

**Active Task**
Job 197, acive, video-file, transcodage to 360p (the video is visible at this resolution) : 
```
Error: Missing lock for job 197 finished
    at Object.finishedErrors (/var/www/peertube/versions/peertube-v1.1.0/node_modules/bull/lib/scripts.js:187:16)
    at /var/www/peertube/versions/peertube-v1.1.0/node_modules/bull/lib/scripts.js:174:23
From previous event:
    at Object.moveToFinished (/var/www/peertube/versions/peertube-v1.1.0/node_modules/bull/lib/scripts.js:172:50)
    at Object.moveToCompleted (/var/www/peertube/versions/peertube-v1.1.0/node_modules/bull/lib/scripts.js:193:20)
    at Job.moveToCompleted (/var/www/peertube/versions/peertube-v1.1.0/node_modules/bull/lib/job.js:198:18)
    at handleCompleted (/var/www/peertube/versions/peertube-v1.1.0/node_modules/bull/lib/queue.js:1047:16)
From previous event:
    at Queue.processJob (/var/www/peertube/versions/peertube-v1.1.0/node_modules/bull/lib/queue.js:1086:8)
    at processImmediate (timers.js:632:19)
From previous event:
    at /var/www/peertube/versions/peertube-v1.1.0/node_modules/bull/lib/queue.js:979:14
    at process.internalTickCallback (internal/process/next_tick.js:77:7)
```
**Waiting task**
Job 195, video-file, initial encodage (from file import, video is visible at the good encodage) : 
```
Error: Missing lock for job 195 finished
    at Object.finishedErrors (/var/www/peertube/versions/peertube-v1.1.0/node_modules/bull/lib/scripts.js:187:16)
    at /var/www/peertube/versions/peertube-v1.1.0/node_modules/bull/lib/scripts.js:174:23
From previous event:
    at Object.moveToFinished (/var/www/peertube/versions/peertube-v1.1.0/node_modules/bull/lib/scripts.js:172:50)
    at Object.moveToCompleted (/var/www/peertube/versions/peertube-v1.1.0/node_modules/bull/lib/scripts.js:193:20)
    at Job.moveToCompleted (/var/www/peertube/versions/peertube-v1.1.0/node_modules/bull/lib/job.js:198:18)
    at handleCompleted (/var/www/peertube/versions/peertube-v1.1.0/node_modules/bull/lib/queue.js:1047:16)
From previous event:
    at Queue.processJob (/var/www/peertube/versions/peertube-v1.1.0/node_modules/bull/lib/queue.js:1086:8)
    at processImmediate (timers.js:632:19)
From previous event:
    at /var/www/peertube/versions/peertube-v1.1.0/node_modules/bull/lib/queue.js:979:14
    at process.internalTickCallback (internal/process/next_tick.js:77:7)
```

**Comment by gegeweb** [comment]
It is possible that the message, on the client side, about an unknown error that occurred after the post-upload processing phase that returns to the download page instead of handing in to validate the publication is caused by it.

**Comment by gegeweb** [comment]
I think there is a side effect caused by this bug.

I've now, about the video uuid `2f867e4e-98fa-479f-b5c4-c6527fb668a8` wich is available at all the resolutions (original, and below), on the list jobs:

**Active**
203 | video-file | active | Dec 14, 2018, 11:27:40 AM | Dec 15, 2018, 6:03:06 AM
```
{
  "videoUUID": "2f867e4e-98fa-479f-b5c4-c6527fb668a8",
  "resolution": 360
}

---

SequelizeUniqueConstraintError: Validation error
    at Query.formatError (/var/www/peertube/versions/peertube-v1.1.0/node_modules/sequelize/lib/dialects/postgres/query.js:325:18)
    at query.catch.err (/var/www/peertube/versions/peertube-v1.1.0/node_modules/sequelize/lib/dialects/postgres/query.js:86:18)
From previous event:
    at retryAsPromised (/var/www/peertube/versions/peertube-v1.1.0/node_modules/retry-as-promised/index.js:29:10)
    at Sequelize.query (/var/www/peertube/versions/peertube-v1.1.0/node_modules/sequelize/lib/sequelize.js:454:28)
    at QueryInterface.insert (/var/www/peertube/versions/peertube-v1.1.0/node_modules/sequelize/lib/query-interface.js:901:27)
    at Promise.try.then.then.then (/var/www/peertube/versions/peertube-v1.1.0/node_modules/sequelize/lib/model.js:3685:53)
    at processImmediate (timers.js:632:19)
```

**Failed**
With the same error about unique constraint (because already in the DB)

202 | video-file | failed | Dec 14, 2018, 3:20:41 AM | Dec 15, 2018, 1:52:18 AM | Dec 15, 2018, 3:07:00 AM
=> resolution 240

201 | video-file | failed | Dec 14, 2018, 3:20:41 AM | Dec 14, 2018, 11:19:13 PM | Dec 15, 2018, 1:52:18 AM
=> resolution 360

And job 197 mentioned above, with the 'missing lock' error.

197 | video-file | failed | Dec 14, 2018, 12:05:15 AM | Dec 14, 2018, 6:09:03 AM | Dec 14, 2018, 8:43:45 AM 
=> resolution 360

**Waiting**
an infinite loop?

Always for this same uuid : 
211 | video-file | waiting | Dec 14, 2018, 11:07:38 PM |   |  => 360
212 | video-file | waiting | Dec 14, 2018, 11:07:38 PM |   |  => 240
209 | video-file | waiting | Dec 14, 2018, 8:35:35 PM |   |  => 360
210 | video-file | waiting | Dec 14, 2018, 8:35:35 PM |   |  => 240
207 | video-file | waiting | Dec 14, 2018, 4:45:18 PM |   |  => 360
208 | video-file | waiting | Dec 14, 2018, 4:45:18 PM |   |  => 240
205 | video-file | waiting | Dec 14, 2018, 2:09:31 PM |   |  => 360
206 | video-file | waiting | Dec 14, 2018, 2:09:31 PM |   |  => 240
204 | video-file | waiting | Dec 14, 2018, 11:27:40 AM |  | => 240

Is there a way to cancel this waiting queue ? On the redis side ?
Because this launch encodage tasks with ffmpeg for nothing.

This video is good visible at all these resolutions.

**Comment by gegeweb** [comment]
204 is now, starting at Dec 15, 2018, 8:34:45 AM, in the active list.

And 203 in the failed list

203 | video-file | failed | Dec 14, 2018, 11:27:40 AM | Dec 15, 2018, 6:03:06 AM | Dec 15, 2018, 8:34:45 AM

```
{
  "videoUUID": "2f867e4e-98fa-479f-b5c4-c6527fb668a8",
  "resolution": 360
}

SequelizeUniqueConstraintError: Validation error
    at Query.formatError (/var/www/peertube/versions/peertube-v1.1.0/node_modules/sequelize/lib/dialects/postgres/query.js:325:18)
    at query.catch.err (/var/www/peertube/versions/peertube-v1.1.0/node_modules/sequelize/lib/dialects/postgres/query.js:86:18)
From previous event:
    at retryAsPromised (/var/www/peertube/versions/peertube-v1.1.0/node_modules/retry-as-promised/index.js:29:10)
    at Sequelize.query (/var/www/peertube/versions/peertube-v1.1.0/node_modules/sequelize/lib/sequelize.js:454:28)
    at QueryInterface.insert (/var/www/peertube/versions/peertube-v1.1.0/node_modules/sequelize/lib/query-interface.js:901:27)
    at Promise.try.then.then.then (/var/www/peertube/versions/peertube-v1.1.0/node_modules/sequelize/lib/model.js:3685:53)
    at processImmediate (timers.js:632:19)
```

**Comment by gegeweb** [comment]
If that help to understand whats happening, I've reimported this video with the file import command and re-encoded with the command too on the server side because the video first uploaded was encoded with an unsuported codec for my ffmpeg version (4.01), and encodages failed with this error from Peertube : 
```
Error: ffmpeg exited with code 1: Error while decoding stream #0:0: Invalid data found when processing input
Too many packets buffered for output stream 0:1.
Conversion failed!

    at ChildProcess.<anonymous> (/var/www/peertube/versions/peertube-v1.1.0/node_modules/fluent-ffmpeg/lib/processor.js:182:22)
    at ChildProcess.emit (events.js:182:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:254:12)
From previous event:
    at Queue.processJob (/var/www/peertube/versions/peertube-v1.1.0/node_modules/bull/lib/queue.js:1076:22)
    at processImmediate (timers.js:632:19)
From previous event:
    at /var/www/peertube/versions/peertube-v1.1.0/node_modules/bull/lib/queue.js:979:14
    at process.internalTickCallback (internal/process/next_tick.js:77:7)
```
Perhaps it wasen't a good idea?

**Comment by gegeweb** [comment]
I found that : 
https://github.com/OptimalBits/bull/issues/789

**Comment by rigelk** [comment]
@gegeweb seen that too. It seems unconclusive, and we already sandbox our processes

**Comment by gegeweb** [comment]
OK.
Good news, there is no infinite loop.
The queue of pending tasks about this famous video is now empty.
Probably actions on my side, combined with these lock problems.

I will now try to reproduce the download failure....

Otherwise, am I the only one with this bug?

**Comment by gegeweb** [comment]
No infinite loop, but if we have this error a new "duplicate" task is created instead of the original task finished.

At this time, in the active tasks : 

220 | video-file | active | Dec 16, 2018, 1:22:53 PM | Dec 17, 2018, 4:19:36 AM
```
{
  "videoUUID": "8b73d675-b811-4264-91c5-7adb1be14ac8",
  "isNewVideo": true
}

Error: Missing lock for job 220 finished
    at Object.finishedErrors (/var/www/peertube/versions/peertube-v1.1.0/node_modules/bull/lib/scripts.js:187:16)
    at /var/www/peertube/versions/peertube-v1.1.0/node_modules/bull/lib/scripts.js:174:23
From previous event:
    at Object.moveToFinished (/var/www/peertube/versions/peertube-v1.1.0/node_modules/bull/lib/scripts.js:172:50)
    at Object.moveToCompleted (/var/www/peertube/versions/peertube-v1.1.0/node_modules/bull/lib/scripts.js:193:20)
    at Job.moveToCompleted (/var/www/peertube/versions/peertube-v1.1.0/node_modules/bull/lib/job.js:198:18)
    at handleCompleted (/var/www/peertube/versions/peertube-v1.1.0/node_modules/bull/lib/queue.js:1047:16)
From previous event:
    at Queue.processJob (/var/www/peertube/versions/peertube-v1.1.0/node_modules/bull/lib/queue.js:1086:8)
    at processImmediate (timers.js:632:19)
From previous event:
    at /var/www/peertube/versions/peertube-v1.1.0/node_modules/bull/lib/queue.js:979:14
    at process.internalTickCallback (internal/process/next_tick.js:77:7)
```

And in the wainting tasks : 

222 | video-file | waiting | Dec 16, 2018, 8:37:27 PM
```
{
  "videoUUID": "ec274a93-9235-4dab-83c0-f2a71e13c5c8",
  "isNewVideo": true
}
```
And there is the encoding jobs for the other resolutions.

**Comment by gegeweb** [comment]
If that help, I found this issues : 
https://github.com/OptimalBits/bull/issues/700
https://github.com/OptimalBits/bull/issues/789

I had this error again, after the end of the first encoding of a new video.
This relaunches a new task for the same thing....

**Comment by gegeweb** [comment]
Since I moved the instance to a server with more resources (memory and CPU), these errors that have become almost systematic have (for the moment) disappeared.
It seems that, from what I have read and understood (see above), it would be due to a communication problem with Redis (but not sure).

**Comment by Chocobozzz** [comment]
Okay so closing for now. Maybe it's a Bull bug, or as you said a communication issue. But I'm not sure we can do anything on PeerTube side.

**Comment by ngotiendat-se** [comment]
I have the same error. I using queue#event and then I get this error. When I comment these event out. These error weren't happen again. Confused!
