### ISSUE TITLE
Docker build fails

### ISSUE THREAD

**Issue by sschimmel** [Chocobozzz/PeerTube#1529]
**What happened?**
Following the instructions here I'm building a docker image from the source code. The build fails at step 10/21 from the Dockerfile. Building node-sass and scripty both fail with the following error:

```
[4/4] Building fresh packages...
$ npm rebuild node-sass
npm WARN lifecycle The node binary used for scripts is /tmp/yarn--1546524425942-0.22759396600664128/node but npm is using /usr/local/bin/node itself. Use the `--scripts-prepend-node-path` option to include the path for the node binary npm was executed with.

> node-sass@4.10.0 install /app/client/node_modules/node-sass
> node scripts/install.js

node-sass build Binary found at /app/client/node_modules/node-sass/vendor/linux-x64-57/binding.node

> node-sass@4.10.0 postinstall /app/client/node_modules/node-sass
> node scripts/build.js

Binary found at /app/client/node_modules/node-sass/vendor/linux-x64-57/binding.node
Testing binary
Binary is fine
node-sass@4.10.0 /app/client/node_modules/node-sass
Done in 61.37s.
Done in 111.53s.

> peertube@1.1.0 build /app
> SCRIPTY_PARALLEL=true scripty

events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: spawn /app/scripts/build/client.sh ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:190:19)
    at onErrorNT (internal/child_process.js:362:16)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
    at process._tickCallback (internal/process/next_tick.js:181:9)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! peertube@1.1.0 build: `SCRIPTY_PARALLEL=true scripty`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the peertube@1.1.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/peertube/.npm/_logs/2019-01-03T14_07_18_804Z-debug.log
The command '/bin/sh -c yarn install --pure-lockfile     && npm run build     && rm -r ./node_modules ./client/node_modules     && yarn install --pure-lockfile --production     && yarn cache clean' returned a non-zero code: 1

```

**What do you expect to happen instead?**
I expected the build to complete successfully.

**Steps to reproduce:**

1. Clone the Peertube repository ` git clone https://github.com/chocobozzz/PeerTube`
2. cd into the directory created by git
3. Run `docker build . -f ./support/docker/production/Dockerfile.stretch` and wait for it to reach step 10 and install the npm packages.

**Comment by sschimmel** [comment]
Managed to fix the error for node-sass by adding `--scripts-prepend-node-path=true` to the  `postinstall` step in `client\package.json`.

Running ` SCRIPTY_PARALLEL=true scripty` still fails.

```
> peertube@1.1.0 build /app
> SCRIPTY_PARALLEL=true scripty

events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: spawn /app/scripts/build/client.sh ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:190:19)
    at onErrorNT (internal/child_process.js:362:16)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
    at process._tickCallback (internal/process/next_tick.js:181:9)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! peertube@1.1.0 build: `SCRIPTY_PARALLEL=true scripty`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the peertube@1.1.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/peertube/.npm/_logs/2019-01-03T14_51_43_340Z-debug.log
```

**Comment by sschimmel** [comment]
Running client.sh I got errors about the line endings. Switched those to LF (linux) and now something seems to not be a git repository:

```
> peertube@1.1.0 build /app
> SCRIPTY_PARALLEL=true scripty

fatal: Not a git repository (or any of the parent directories): .git
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: spawn /app/scripts/build/server.sh ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:190:19)
    at onErrorNT (internal/child_process.js:362:16)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
    at process._tickCallback (internal/process/next_tick.js:181:9)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! peertube@1.1.0 build: `SCRIPTY_PARALLEL=true scripty`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the peertube@1.1.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/peertube/.npm/_logs/2019-01-03T15_08_31_156Z-debug.log
The command '/bin/sh -c yarn install --pure-lockfile     && npm run build     && rm -r ./node_modules ./client/node_modules     && yarn install --pure-lockfile --production --scripts-prepend-node-path     && yarn cache clean' returned a non-zero code: 1
```

**Comment by sschimmel** [comment]
Fixed the error above, my last comment, by removing `.git` from the `.dockerignore` file so the .git directory is included in the build context.

The build seems to work now. It's further in the process. I do get a bunch of error messages about missing translations. Doesn't seem to matter as the build does continue.

If it finishes the build I'll make a pull request with my changes.

**Comment by Chocobozzz** [comment]
It's weird you don't have `/app/scripts/build/client.sh` in the docker context. Are you sure you built the image from a fresh peertube git clone?

Because I triggered a develop build yesterday on docker cloud, and everything went fine: https://hub.docker.com/r/chocobozzz/peertube/tags
