### ISSUE TITLE
Cannot import a video from youtube

### ISSUE THREAD

**Issue by 22decembre** [Chocobozzz/PeerTube#1531]
**What happened?**

I wish to import a video from youtube directly from the web-ui. The import failed and no error message is displayed. (You have no idea if the peertube instance tried to download or if it was cancelled for another reason.)

**What do you expect to happen instead?**

The import succeed and the video is proposed for tagging / language specification / etc.

Would be nice to have an error message if failing in such a way.

**Additional information**
* PeerTube version or URL: https://tube.22decembre.eu (v1.1.0)
* Browser name/version: Firefox 64.0 64 bits / Ubuntu
* NodeJS version: v10.11.0 (FreeBSD)

* Link to browser console log (/var/log/peertube/peertube.log - written by main npm daemon):

```
[tube.22decembre.eu:443] 2019-01-04 11:39:45.086 info: 2a06:: - - [04/Jan/2019:10:39:45 +0000] "POST /api/v1/videos/imports/ HTTP/1.0" - - "https://tube.22decembre.eu/videos/upload" "Firefox"

[tube.22decembre.eu:443] 2019-01-04 11:40:12.925 info: Receiving inbox requests for 1 activities by https://video.ploud.fr/accounts/peertube.
[tube.22decembre.eu:443] 2019-01-04 11:40:12.926 info: 51.38.19.137 - - [04/Jan/2019:10:40:12 +0000] "POST /inbox HTTP/1.0" 204 - "-" "-"

[tube.22decembre.eu:443] 2019-01-04 11:40:12.939 info: Processing AP refresher in job 25029.
[tube.22decembre.eu:443] 2019-01-04 11:40:33.293 info: Receiving inbox requests for 1 activities by https://peertube.fr/accounts/peertube.
[tube.22decembre.eu:443] 2019-01-04 11:40:33.294 info: 51.38.19.137 - - [04/Jan/2019:10:40:33 +0000] "POST /inbox HTTP/1.0" 204 - "-" "-"

[tube.22decembre.eu:443] 2019-01-04 11:40:33.307 info: Processing AP refresher in job 25030.
[tube.22decembre.eu:443] 2019-01-04 11:41:01.111 info: 2a06:: - - [04/Jan/2019:10:41:01 +0000] "GET / HTTP/1.0" 304 - "-" "Firefox"

[tube.22decembre.eu:443] 2019-01-04 11:41:02.021 info: 2a06:: - - [04/Jan/2019:10:41:02 +0000] "GET /client/assets/images/favicon.png HTTP/1.0" - - "-" "Firefox"

[tube.22decembre.eu:443] 2019-01-04 11:41:02.079 info: 2a06:: - - [04/Jan/2019:10:41:02 +0000] "GET /api/v1/oauth-clients/local HTTP/1.0" 200 99 "https://tube.22decembre.eu/" "Firefox"

[tube.22decembre.eu:443] 2019-01-04 11:41:02.121 info: 2a06:: - - [04/Jan/2019:10:41:02 +0000] "GET /api/v1/config/ HTTP/1.0" 304 - "https://tube.22decembre.eu/" "Firefox"

[tube.22decembre.eu:443] 2019-01-04 11:41:02.138 info: 2a06:: - - [04/Jan/2019:10:41:02 +0000] "GET /client/locales/fr-FR/server.json HTTP/1.0" 304 - "https://tube.22decembre.eu/" "Firefox"

[tube.22decembre.eu:443] 2019-01-04 11:41:02.157 info: 2a06:: - - [04/Jan/2019:10:41:02 +0000] "GET /api/v1/users/me HTTP/1.0" 304 - "https://tube.22decembre.eu/" "Firefox"

[tube.22decembre.eu:443] 2019-01-04 11:41:02.403 info: 2a06:: - - [04/Jan/2019:10:41:02 +0000] "GET /client/fr_FR/logo.d49da684ce4fa3755723.svg HTTP/1.0" 304 - "https://tube.22decembre.eu/" "Firefox"

[tube.22decembre.eu:443] 2019-01-04 11:41:02.405 info: 2a06:: - - [04/Jan/2019:10:41:02 +0000] "GET /client/fr_FR/search.38a00e184f76afd6e83c.svg HTTP/1.0" 304 - "https://tube.22decembre.eu/" "Firefox"

[tube.22decembre.eu:443] 2019-01-04 11:41:02.406 info: 2a06:: - - [04/Jan/2019:10:41:02 +0000] "GET /client/fr_FR/upload-white.d96ead8c7547475c4ae0.svg HTTP/1.0" 304 - "https://tube.22decembre.eu/" "Firefox"

[tube.22decembre.eu:443] 2019-01-04 11:41:02.407 info: 2a06:: - - [04/Jan/2019:10:41:02 +0000] "GET /client/fr_FR/subscriptions.614b71bafa18b7d9e1df.svg HTTP/1.0" 304 - "https://tube.22decembre.eu/" "Firefox"

[tube.22decembre.eu:443] 2019-01-04 11:41:02.454 info: 2a06:: - - [04/Jan/2019:10:41:02 +0000] "GET /client/fr_FR/globe.9a01e33020e1d17b9de0.svg HTTP/1.0" 304 - "https://tube.22decembre.eu/" "Firefox"

[tube.22decembre.eu:443] 2019-01-04 11:41:02.460 info: 2a06:: - - [04/Jan/2019:10:41:02 +0000] "GET /client/fr_FR/trending.603396b7f330aeb84f96.svg HTTP/1.0" 304 - "https://tube.22decembre.eu/" "Firefox"

[tube.22decembre.eu:443] 2019-01-04 11:41:02.463 info: 2a06:: - - [04/Jan/2019:10:41:02 +0000] "GET /client/fr_FR/recently-added.06377dc73bceffb3904c.svg HTTP/1.0" 304 - "https://tube.22decembre.eu/" "Firefox"

[tube.22decembre.eu:443] 2019-01-04 11:41:02.464 info: 2a06:: - - [04/Jan/2019:10:41:02 +0000] "GET /client/fr_FR/home.8a5d35643267fbce963b.svg HTTP/1.0" 304 - "https://tube.22decembre.eu/" "Firefox"

[tube.22decembre.eu:443] 2019-01-04 11:41:02.465 info: 2a06:: - - [04/Jan/2019:10:41:02 +0000] "GET /client/fr_FR/administration.14c467f99467fc061012.svg HTTP/1.0" 304 - "https://tube.22decembre.eu/" "Firefox"

[tube.22decembre.eu:443] 2019-01-04 11:41:02.466 info: 2a06:: - - [04/Jan/2019:10:41:02 +0000] "GET /client/fr_FR/about.a967cc0b27bbdd7ca7e8.svg HTTP/1.0" 304 - "https://tube.22decembre.eu/" "Firefox"

[tube.22decembre.eu:443] 2019-01-04 11:41:02.469 info: 2a06:: - - [04/Jan/2019:10:41:02 +0000] "GET /client/fr_FR/language.e569b5463ef1c0ef2b34.png HTTP/1.0" 304 - "https://tube.22decembre.eu/" "Firefox"

[tube.22decembre.eu:443] 2019-01-04 11:41:02.471 info: 2a06:: - - [04/Jan/2019:10:41:02 +0000] "GET /client/fr_FR/keyboard.7080cd0b933e5299cf70.png HTTP/1.0" 304 - "https://tube.22decembre.eu/" "Firefox"

[tube.22decembre.eu:443] 2019-01-04 11:41:02.472 info: 2a06:: - - [04/Jan/2019:10:41:02 +0000] "GET /client/fr_FR/moonsun.990cc829b859d6bbddc9.svg HTTP/1.0" 304 - "https://tube.22decembre.eu/" "Firefox"

[tube.22decembre.eu:443] 2019-01-04 11:41:02.605 info: 2a06:: - - [04/Jan/2019:10:41:02 +0000] "GET /client/fr_FR/syndication.b921fdf8cb5f1a272a29.svg HTTP/1.0" 304 - "https://tube.22decembre.eu/" "Firefox"

[tube.22decembre.eu:443] 2019-01-04 11:41:02.613 info: 2a06:: - - [04/Jan/2019:10:41:02 +0000] "GET /api/v1/videos/?start=0&count=20&sort=-trending HTTP/1.0" 200 31607 "https://tube.22decembre.eu/" "Firefox"

[tube.22decembre.eu:443] 2019-01-04 11:41:02.617 info: 2a06:: - - [04/Jan/2019:10:41:02 +0000] "GET /api/v1/videos/categories HTTP/1.0" 304 - "https://tube.22decembre.eu/" "Firefox"

[tube.22decembre.eu:443] 2019-01-04 11:41:02.621 info: 2a06:: - - [04/Jan/2019:10:41:02 +0000] "GET /api/v1/videos/languages HTTP/1.0" 304 - "https://tube.22decembre.eu/" "Firefox"

[tube.22decembre.eu:443] 2019-01-04 11:41:02.623 info: 2a06:: - - [04/Jan/2019:10:41:02 +0000] "GET /api/v1/videos/licences HTTP/1.0" 304 - "https://tube.22decembre.eu/" "Firefox"

[tube.22decembre.eu:443] 2019-01-04 11:41:02.625 info: 2a06:: - - [04/Jan/2019:10:41:02 +0000] "GET /api/v1/videos/privacies HTTP/1.0" 304 - "https://tube.22decembre.eu/" "Firefox"

[tube.22decembre.eu:443] 2019-01-04 11:41:05.540 info: 2a06:: - - [04/Jan/2019:10:41:05 +0000] "GET /api/v1/users/?start=0&count=10&sort=createdAt HTTP/1.0" 304 - "https://tube.22decembre.eu/admin/users/list" "Firefox"

[tube.22decembre.eu:443] 2019-01-04 11:41:06.833 info: 2a06:: - - [04/Jan/2019:10:41:06 +0000] "GET /api/v1/jobs/failed?start=0&count=10&sort=createdAt HTTP/1.0" 304 - "https://tube.22decembre.eu/admin/jobs/list" "Firefox"

[tube.22decembre.eu:443] 2019-01-04 11:41:15.071 error: Cannot execute addVideoImport with many retries. {
  "meta": {
    "err": {
      "stack": "SequelizeDatabaseError: null value in column \"id\" violates not-null constraint\n    at Query.formatError (/var/www/peertube/versions/peertube-v1.1.0/node_modules/sequelize/lib/dialects/postgres/query.js:363:16)\n    at query.catch.err (/var/www/peertube/versions/peertube-v1.1.0/node_modules/sequelize/lib/dialects/postgres/query.js:86:18)\nFrom previous event:\n    at retryAsPromised (/var/www/peertube/versions/peertube-v1.1.0/node_modules/retry-as-promised/index.js:29:10)\n    at Sequelize.query (/var/www/peertube/versions/peertube-v1.1.0/node_modules/sequelize/lib/sequelize.js:454:28)\n    at QueryInterface.insert (/var/www/peertube/versions/peertube-v1.1.0/node_modules/sequelize/lib/query-interface.js:901:27)\n    at Promise.try.then.then.then (/var/www/peertube/versions/peertube-v1.1.0/node_modules/sequelize/lib/model.js:3685:53)\n    at runCallback (timers.js:694:18)\n    at tryOnImmediate (timers.js:665:5)\n    at processImmediate (timers.js:647:5)",
      "message": "null value in column \"id\" violates not-null constraint",
      "name": "SequelizeDatabaseError",
      "parent": {
        "stack": "error: null value in column \"id\" violates not-null constraint\n    at Connection.parseE (/var/www/peertube/versions/peertube-v1.1.0/node_modules/pg/lib/connection.js:554:11)\n    at Connection.parseMessage (/var/www/peertube/versions/peertube-v1.1.0/node_modules/pg/lib/connection.js:379:19)\n    at Socket.<anonymous> (/var/www/peertube/versions/peertube-v1.1.0/node_modules/pg/lib/connection.js:119:22)\n    at Socket.emit (events.js:182:13)\n    at addChunk (_stream_readable.js:283:12)\n    at readableAddChunk (_stream_readable.js:264:11)\n    at Socket.Readable.push (_stream_readable.js:219:10)\n    at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)",
        "message": "null value in column \"id\" violates not-null constraint",
        "name": "error",
        "length": 303,
        "severity": "ERROR",
        "code": "23502",
        "detail": "Failing row contains (null, https://www.youtube.com/watch?v=OmOdmmkMKvc, null, null, 1, null, 2, 5027, 2019-01-04 10:41:15.059+00, 2019-01-04 10:41:15.059+00).",
        "schema": "public",
        "table": "videoImport",
        "column": "id",
        "file": "execMain.c",
        "line": "1731",
        "routine": "ExecConstraints",
        "sql": "INSERT INTO \"videoImport\" (\"id\",\"targetUrl\",\"magnetUri\",\"torrentName\",\"state\",\"error\",\"userId\",\"videoId\",\"createdAt\",\"updatedAt\") VALUES (DEFAULT,'https://www.youtube.com/watch?v=OmOdmmkMKvc',NULL,NULL,1,NULL,2,5027,'2019-01-04 10:41:15.059 +00:00','2019-01-04 10:41:15.059 +00:00') RETURNING *;"
      },
      "original": {
        "stack": "error: null value in column \"id\" violates not-null constraint\n    at Connection.parseE (/var/www/peertube/versions/peertube-v1.1.0/node_modules/pg/lib/connection.js:554:11)\n    at Connection.parseMessage (/var/www/peertube/versions/peertube-v1.1.0/node_modules/pg/lib/connection.js:379:19)\n    at Socket.<anonymous> (/var/www/peertube/versions/peertube-v1.1.0/node_modules/pg/lib/connection.js:119:22)\n    at Socket.emit (events.js:182:13)\n    at addChunk (_stream_readable.js:283:12)\n    at readableAddChunk (_stream_readable.js:264:11)\n    at Socket.Readable.push (_stream_readable.js:219:10)\n    at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)",
        "message": "null value in column \"id\" violates not-null constraint",
        "name": "error",
        "length": 303,
        "severity": "ERROR",
        "code": "23502",
        "detail": "Failing row contains (null, https://www.youtube.com/watch?v=OmOdmmkMKvc, null, null, 1, null, 2, 5027, 2019-01-04 10:41:15.059+00, 2019-01-04 10:41:15.059+00).",
        "schema": "public",
        "table": "videoImport",
        "column": "id",
        "file": "execMain.c",
        "line": "1731",
        "routine": "ExecConstraints",
        "sql": "INSERT INTO \"videoImport\" (\"id\",\"targetUrl\",\"magnetUri\",\"torrentName\",\"state\",\"error\",\"userId\",\"videoId\",\"createdAt\",\"updatedAt\") VALUES (DEFAULT,'https://www.youtube.com/watch?v=OmOdmmkMKvc',NULL,NULL,1,NULL,2,5027,'2019-01-04 10:41:15.059 +00:00','2019-01-04 10:41:15.059 +00:00') RETURNING *;"
      },
      "sql": "INSERT INTO \"videoImport\" (\"id\",\"targetUrl\",\"magnetUri\",\"torrentName\",\"state\",\"error\",\"userId\",\"videoId\",\"createdAt\",\"updatedAt\") VALUES (DEFAULT,'https://www.youtube.com/watch?v=OmOdmmkMKvc',NULL,NULL,1,NULL,2,5027,'2019-01-04 10:41:15.059 +00:00','2019-01-04 10:41:15.059 +00:00') RETURNING *;",
      "__stackCleaned__": true
    }
  },
  "err": {
    "stack": "SequelizeDatabaseError: null value in column \"id\" violates not-null constraint\n    at Query.formatError (/var/www/peertube/versions/peertube-v1.1.0/node_modules/sequelize/lib/dialects/postgres/query.js:363:16)\n    at query.catch.err (/var/www/peertube/versions/peertube-v1.1.0/node_modules/sequelize/lib/dialects/postgres/query.js:86:18)\nFrom previous event:\n    at retryAsPromised (/var/www/peertube/versions/peertube-v1.1.0/node_modules/retry-as-promised/index.js:29:10)\n    at Sequelize.query (/var/www/peertube/versions/peertube-v1.1.0/node_modules/sequelize/lib/sequelize.js:454:28)\n    at QueryInterface.insert (/var/www/peertube/versions/peertube-v1.1.0/node_modules/sequelize/lib/query-interface.js:901:27)\n    at Promise.try.then.then.then (/var/www/peertube/versions/peertube-v1.1.0/node_modules/sequelize/lib/model.js:3685:53)\n    at runCallback (timers.js:694:18)\n    at tryOnImmediate (timers.js:665:5)\n    at processImmediate (timers.js:647:5)",
    "message": "null value in column \"id\" violates not-null constraint",
    "name": "SequelizeDatabaseError",
    "parent": {
      "stack": "error: null value in column \"id\" violates not-null constraint\n    at Connection.parseE (/var/www/peertube/versions/peertube-v1.1.0/node_modules/pg/lib/connection.js:554:11)\n    at Connection.parseMessage (/var/www/peertube/versions/peertube-v1.1.0/node_modules/pg/lib/connection.js:379:19)\n    at Socket.<anonymous> (/var/www/peertube/versions/peertube-v1.1.0/node_modules/pg/lib/connection.js:119:22)\n    at Socket.emit (events.js:182:13)\n    at addChunk (_stream_readable.js:283:12)\n    at readableAddChunk (_stream_readable.js:264:11)\n    at Socket.Readable.push (_stream_readable.js:219:10)\n    at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)",
      "message": "null value in column \"id\" violates not-null constraint",
      "name": "error",
      "length": 303,
      "severity": "ERROR",
      "code": "23502",
      "detail": "Failing row contains (null, https://www.youtube.com/watch?v=OmOdmmkMKvc, null, null, 1, null, 2, 5027, 2019-01-04 10:41:15.059+00, 2019-01-04 10:41:15.059+00).",
      "schema": "public",
      "table": "videoImport",
      "column": "id",
      "file": "execMain.c",
      "line": "1731",
      "routine": "ExecConstraints",
      "sql": "INSERT INTO \"videoImport\" (\"id\",\"targetUrl\",\"magnetUri\",\"torrentName\",\"state\",\"error\",\"userId\",\"videoId\",\"createdAt\",\"updatedAt\") VALUES (DEFAULT,'https://www.youtube.com/watch?v=OmOdmmkMKvc',NULL,NULL,1,NULL,2,5027,'2019-01-04 10:41:15.059 +00:00','2019-01-04 10:41:15.059 +00:00') RETURNING *;"
    },
    "original": {
      "stack": "error: null value in column \"id\" violates not-null constraint\n    at Connection.parseE (/var/www/peertube/versions/peertube-v1.1.0/node_modules/pg/lib/connection.js:554:11)\n    at Connection.parseMessage (/var/www/peertube/versions/peertube-v1.1.0/node_modules/pg/lib/connection.js:379:19)\n    at Socket.<anonymous> (/var/www/peertube/versions/peertube-v1.1.0/node_modules/pg/lib/connection.js:119:22)\n    at Socket.emit (events.js:182:13)\n    at addChunk (_stream_readable.js:283:12)\n    at readableAddChunk (_stream_readable.js:264:11)\n    at Socket.Readable.push (_stream_readable.js:219:10)\n    at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)",
      "message": "null value in column \"id\" violates not-null constraint",
      "name": "error",
      "length": 303,
      "severity": "ERROR",
      "code": "23502",
      "detail": "Failing row contains (null, https://www.youtube.com/watch?v=OmOdmmkMKvc, null, null, 1, null, 2, 5027, 2019-01-04 10:41:15.059+00, 2019-01-04 10:41:15.059+00).",
      "schema": "public",
      "table": "videoImport",
      "column": "id",
      "file": "execMain.c",
      "line": "1731",
      "routine": "ExecConstraints",
      "sql": "INSERT INTO \"videoImport\" (\"id\",\"targetUrl\",\"magnetUri\",\"torrentName\",\"state\",\"error\",\"userId\",\"videoId\",\"createdAt\",\"updatedAt\") VALUES (DEFAULT,'https://www.youtube.com/watch?v=OmOdmmkMKvc',NULL,NULL,1,NULL,2,5027,'2019-01-04 10:41:15.059 +00:00','2019-01-04 10:41:15.059 +00:00') RETURNING *;"
    },
    "sql": "INSERT INTO \"videoImport\" (\"id\",\"targetUrl\",\"magnetUri\",\"torrentName\",\"state\",\"error\",\"userId\",\"videoId\",\"createdAt\",\"updatedAt\") VALUES (DEFAULT,'https://www.youtube.com/watch?v=OmOdmmkMKvc',NULL,NULL,1,NULL,2,5027,'2019-01-04 10:41:15.059 +00:00','2019-01-04 10:41:15.059 +00:00') RETURNING *;",
    "__stackCleaned__": true
  }
}
[tube.22decembre.eu:443] 2019-01-04 11:41:15.072 error: Error in controller. {
  "meta": {
    "err": "SequelizeDatabaseError: null value in column \"id\" violates not-null constraint\n    at Query.formatError (/var/www/peertube/versions/peertube-v1.1.0/node_modules/sequelize/lib/dialects/postgres/query.js:363:16)\n    at query.catch.err (/var/www/peertube/versions/peertube-v1.1.0/node_modules/sequelize/lib/dialects/postgres/query.js:86:18)\nFrom previous event:\n    at retryAsPromised (/var/www/peertube/versions/peertube-v1.1.0/node_modules/retry-as-promised/index.js:29:10)\n    at Sequelize.query (/var/www/peertube/versions/peertube-v1.1.0/node_modules/sequelize/lib/sequelize.js:454:28)\n    at QueryInterface.insert (/var/www/peertube/versions/peertube-v1.1.0/node_modules/sequelize/lib/query-interface.js:901:27)\n    at Promise.try.then.then.then (/var/www/peertube/versions/peertube-v1.1.0/node_modules/sequelize/lib/model.js:3685:53)\n    at runCallback (timers.js:694:18)\n    at tryOnImmediate (timers.js:665:5)\n    at processImmediate (timers.js:647:5)",
    "sql": "INSERT INTO \"videoImport\" (\"id\",\"targetUrl\",\"magnetUri\",\"torrentName\",\"state\",\"error\",\"userId\",\"videoId\",\"createdAt\",\"updatedAt\") VALUES (DEFAULT,'https://www.youtube.com/watch?v=OmOdmmkMKvc',NULL,NULL,1,NULL,2,5027,'2019-01-04 10:41:15.059 +00:00','2019-01-04 10:41:15.059 +00:00') RETURNING *;"
  },
  "err": "SequelizeDatabaseError: null value in column \"id\" violates not-null constraint\n    at Query.formatError (/var/www/peertube/versions/peertube-v1.1.0/node_modules/sequelize/lib/dialects/postgres/query.js:363:16)\n    at query.catch.err (/var/www/peertube/versions/peertube-v1.1.0/node_modules/sequelize/lib/dialects/postgres/query.js:86:18)\nFrom previous event:\n    at retryAsPromised (/var/www/peertube/versions/peertube-v1.1.0/node_modules/retry-as-promised/index.js:29:10)\n    at Sequelize.query (/var/www/peertube/versions/peertube-v1.1.0/node_modules/sequelize/lib/sequelize.js:454:28)\n    at QueryInterface.insert (/var/www/peertube/versions/peertube-v1.1.0/node_modules/sequelize/lib/query-interface.js:901:27)\n    at Promise.try.then.then.then (/var/www/peertube/versions/peertube-v1.1.0/node_modules/sequelize/lib/model.js:3685:53)\n    at runCallback (timers.js:694:18)\n    at tryOnImmediate (timers.js:665:5)\n    at processImmediate (timers.js:647:5)",
  "sql": "INSERT INTO \"videoImport\" (\"id\",\"targetUrl\",\"magnetUri\",\"torrentName\",\"state\",\"error\",\"userId\",\"videoId\",\"createdAt\",\"updatedAt\") VALUES (DEFAULT,'https://www.youtube.com/watch?v=OmOdmmkMKvc',NULL,NULL,1,NULL,2,5027,'2019-01-04 10:41:15.059 +00:00','2019-01-04 10:41:15.059 +00:00') RETURNING *;"
}
```

**Comment by Chocobozzz** [comment]
If you go inside your database, can you insert the row?

```
INSERT INTO "videoImport ("id","targetUrl","magnetUri","torrentName","state","error","userId","videoId","createdAt","updatedAt") VALUES (DEFAULT,'https://www.youtube.com/watch?v=OmOdmmkMKvc',NULL,NULL,1,NULL,2,5027,'2019-01-04 10:41:15.059 +00:00','2019-01-04 10:41:15.059 +00:00') RETURNING *;
```

**Comment by 22decembre** [comment]
```
[peertube@dina ~/storage/logs]$ psql -U peertube peertube_prod2 -c 'INSERT INTO "videoImport ("id","targetUrl","magnetUri","torrentName","state","error","userId","videoId","createdAt","updatedAt") VALUES (DEFAULT,'https://www.youtube.com/watch?v=OmOdmmkMKvc',NULL,NULL,1,NULL,2,5027,'2019-01-04 10:41:15.059 +00:00','2019-01-04 10:41:15.059 +00:00') RETURNING *; '
psql: warning: extra command-line argument "10:41:15.059" ignored
psql: warning: extra command-line argument "+00:00,2019-01-04" ignored
psql: warning: extra command-line argument "10:41:15.059" ignored
psql: warning: extra command-line argument "+00:00) RETURNING *;
" ignored
ERROR:  syntax error at or near "id"
LINE 1: INSERT INTO "videoImport ("id","targetUrl","magnetUri","torr...
                                   ^
```

I think it's a NO, if I did it right.

**Comment by Chocobozzz** [comment]
@22decembre I fixed the typo

**Comment by 22decembre** [comment]
I tried several times. Here is the whole serie.

```
psql -U peertube peertube_prod2 -c 'INSERT INTO "videoImport ("id","targetUrl","magnetUri","torrentName","state","error","userId","videoId","createdAt","updatedAt") VALUES (DEFAULT,'https://www.youtube.com/watch?v=OmOdmmkMKvc',NULL,NULL,1,NULL,2,5027,'2019-01-04 10:41:15.059 +00:00^C
[peertube@dina ~/storage/logs]$ psql -U peertube peertube_prod2 -c 'INSERT INTO "videoImport" ("id","targetUrl","magnetUri","torrentName","state","error","userId","videoId","createdAt","updatedAt") VALUES (DEFAULT,'https://www.youtube.com/watch?v=OmOdmmkMKvc',NULL,NULL,1,NULL,2,5027,'2019-01-04 10:41:15.059 +00:00','2019-01-04 10:41:15.059 +00:00') RETURNING *;'
psql: warning: extra command-line argument "10:41:15.059" ignored
psql: warning: extra command-line argument "+00:00,2019-01-04" ignored
psql: warning: extra command-line argument "10:41:15.059" ignored
psql: warning: extra command-line argument "+00:00) RETURNING *;" ignored
ERROR:  syntax error at or near ":"
LINE 1: ...Id","createdAt","updatedAt") VALUES (DEFAULT,https://www.you...
                                                             ^
```
Apparently it does not like double points in URL this way...

```
psql -U peertube peertube_prod2 -c 'INSERT INTO "videoImport" ("id","targetUrl","magnetUri","torrentName","state","error","userId","videoId","createdAt","updatedAt") VALUES (DEFAULT,"https://www.youtube.com/watch?v=OmOdmmkMKvc",NULL,NULL,1,NULL,2,5027,'2019-01-04 10:41:15.059 +00:00','2019-01-04 10:41:15.059 +00:00') RETURNING *;'
psql: warning: extra command-line argument "10:41:15.059" ignored
psql: warning: extra command-line argument "+00:00,2019-01-04" ignored
psql: warning: extra command-line argument "10:41:15.059" ignored
psql: warning: extra command-line argument "+00:00) RETURNING *;" ignored
ERROR:  syntax error at end of input
LINE 1: ....com/watch?v=OmOdmmkMKvc",NULL,NULL,1,NULL,2,5027,2019-01-04
                                                                       ^
```
I used "..." to enclose the URL, and it moves the issue to the date.

```
psql -U peertube peertube_prod2 -c 'INSERT INTO "videoImport" ("id","targetUrl","magnetUri","torrentName","state","error","userId","videoId","createdAt","updatedAt") VALUES (DEFAULT,"https://www.youtube.com/watch?v=OmOdmmkMKvc",NULL,NULL,1,NULL,2,5027,"2019-01-04 10:41:15.059 +00:00","2019-01-04 10:41:15.059 +00:00") RETURNING *;'
ERROR:  column "https://www.youtube.com/watch?v=OmOdmmkMKvc" does not exist
LINE 1: ...videoId","createdAt","updatedAt") VALUES (DEFAULT,"https://w...
                                                             ^
```

And back to the URL.

**Comment by 22decembre** [comment]
Probably something in my ssl conf', as I have "ssl_ecdh_curve secp384r1", which is not compatible with the import script apparently.

**Comment by Chocobozzz** [comment]
@22decembre The SQL command fails because you don't escape the ' that wrap the youtube URL. Just go inside your database and execute the SQL command, it will be simpler.

**Comment by 22decembre** [comment]
I am inside the DB now, here is the answer :

`peertube_prod2=> INSERT INTO "videoImport" ("id","targetUrl","magnetUri","torrentName","state","error","userId","videoId","createdAt","updatedAt") VALUES (DEFAULT,'https://www.youtube.com/watch?v=_knK1Wqp7eE',NULL,NULL,1,NULL,2,5027,'2019-01-04 10:41:15.059 +00:00','2019-01-04 10:41:15.059 +00:00') RETURNING *;   
ERROR:  null value in column "id" violates not-null constraint   
DETAIL:  Failing row contains (null, https://www.youtube.com/watch?v=_knK1Wqp7eE, null, null, 1, null, 2, 5027, 2019-01-04 11:41:15.059+01, 2019-01-04 11:41:15.059+01).`

**Comment by Chocobozzz** [comment]
Weird, it seems the id sequence does not work :thinking: 

What is the output of `\d` and `\d "videoImport"` (in psql)?

**Comment by 22decembre** [comment]
peertube_prod2=> \d
                     List of relations
 Schema |            Name            |   Type   |  Owner   
--------+----------------------------+----------+----------
 public | account                    | table    | peertube
 public | accountBlocklist           | table    | peertube
 public | accountBlocklist_id_seq    | sequence | peertube
 public | accountVideoRate           | table    | peertube
 public | accountVideoRate_id_seq    | sequence | peertube
 public | account_id_seq             | sequence | peertube
 public | actor                      | table    | peertube
 public | actorFollow                | table    | peertube
 public | actorFollow_id_seq         | sequence | peertube
 public | actor_id_seq               | sequence | peertube
 public | application                | table    | peertube
 public | application_id_seq         | sequence | peertube
 public | avatar                     | table    | peertube
 public | avatar_id_seq              | sequence | peertube
 public | oAuthClient                | table    | peertube
 public | oAuthClient_id_seq         | sequence | peertube
 public | oAuthToken                 | table    | peertube
 public | oAuthToken_id_seq          | sequence | peertube
 public | scheduleVideoUpdate        | table    | peertube
 public | scheduleVideoUpdate_id_seq | sequence | peertube
 public | server                     | table    | peertube
 public | serverBlocklist            | table    | peertube
 public | serverBlocklist_id_seq     | sequence | peertube
 public | server_id_seq              | sequence | peertube
 public | tag                        | table    | peertube
 public | tag_id_seq                 | sequence | peertube
 public | user                       | table    | peertube
 public | userVideoHistory           | table    | peertube
 public | userVideoHistory_id_seq    | sequence | peertube
 public | user_id_seq                | sequence | peertube
 public | video                      | table    | peertube
 public | videoAbuse                 | table    | peertube
 public | videoAbuse_id_seq          | sequence | peertube
 public | videoBlacklist             | table    | peertube
 public | videoBlacklist_id_seq      | sequence | peertube
 public | videoCaption               | table    | peertube
 public | videoChangeOwnership       | table    | peertube
 public | videoChannel               | table    | peertube
 public | videoChannel_id_seq        | sequence | peertube
 public | videoComment               | table    | peertube
 public | videoComment_id_seq        | sequence | peertube
peertube_prod2=> \d "videoImport"
                        Table "public.videoImport"
   Column    |           Type           |            Modifiers
-------------+--------------------------+---------------------------------
 id          | integer                  | not null
 targetUrl   | character varying(2000)  | default NULL::character varying
 magnetUri   | character varying(2000)  | default NULL::character varying
 torrentName | character varying(255)   | default NULL::character varying
 state       | integer                  | not null
 error       | text                     |
 userId      | integer                  | not null
 videoId     | integer                  |
 createdAt   | timestamp with time zone | not null
 updatedAt   | timestamp with time zone | not null
Indexes:
    "videoImport_pkey" PRIMARY KEY, btree (id)
    "video_import_video_id" UNIQUE, btree ("videoId")
    "video_import_user_id" btree ("userId")
Foreign-key constraints:
    "videoImport_userId_fkey" FOREIGN KEY ("userId") REFERENCES "user"(id) ON UPDATE CASCADE ON DELETE CASCADE
    "videoImport_videoId_fkey" FOREIGN KEY ("videoId") REFERENCES video(id) ON UPDATE CASCADE ON DELETE SET NULL

peertube_prod2=>

**Comment by Chocobozzz** [comment]
@22decembre Was this database initialized by peertube? Because the id column should not be just an integer. And I don't understand how it could happen.

Try https://stackoverflow.com/a/23578612 to fix it.

**Comment by 22decembre** [comment]
I have postgresql 9.6.10.

**Comment by 22decembre** [comment]
I have other errors after having altered the id (which I am not sure is done correctly).

**Comment by Chocobozzz** [comment]
Closing this issue. If you have other errors, please create a another one
