### ISSUE TITLE
Peertube cli: Invalid config source

### ISSUE THREAD

**Issue by buoyantair** [Chocobozzz/PeerTube#1532]
**What happened?**
Peertube cli asks for a configuration file to import videos

**What do you expect to happen instead?**
Usually the configuration is not needed to import videos into a server, so it should start importing

**Steps to reproduce:**

1. clone the directory, follow the instructions [here](https://github.com/Chocobozzz/PeerTube/blob/develop/support/doc/tools.md#installation) to setup the peertube cli

2. use `$ peertube import -u "https://peertube.social/" -U "USERNAME@DOMAIN" --password "PASSWORD" -t "https://www.youtube.com/channel/CHANNEL_NAME"` to start importing videos en mass.

3. You will hit an error like below:

```
WARNING: No configurations found in configuration directory:/home/smushypanda/Documents/projects/foss/PeerTube/dist/server/tools/config
WARNING: To disable this warning set SUPPRESS_NO_CONFIG_WARNING in the environment.
/home/smushypanda/Documents/projects/foss/PeerTube/dist/server/initializers/constants.js:651
        throw new Error('Invalid config source.');
        ^

Error: Invalid config source.
    at getLocalConfigFilePath (/home/smushypanda/Documents/projects/foss/PeerTube/dist/server/initializers/constants.js:651:15)
    at Object.<anonymous> (/home/smushypanda/Documents/projects/foss/PeerTube/dist/server/initializers/constants.js:141:18)
    at Module._compile (internal/modules/cjs/loader.js:721:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:732:10)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:560:12)
    at Function.Module._load (internal/modules/cjs/loader.js:552:3)
    at Module.require (internal/modules/cjs/loader.js:657:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/home/smushypanda/Documents/projects/foss/PeerTube/dist/server/initializers/index.js:6:10)
    at Module._compile (internal/modules/cjs/loader.js:721:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:732:10)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:560:12)
    at Function.Module._load (internal/modules/cjs/loader.js:552:3)
    at Module.require (internal/modules/cjs/loader.js:657:17)
```

This behaviour happens for all the subcommands of `peertube` (import, import-videos, upload to be specific)

**Additional information**
* PeerTube version or URL:  N/A
* Browser name/version: N/A
* NodeJS version: v11

* Link to server log if useful (journalctl or /var/www/peertube/storage/logs/): https://hastebin.com/uguzuvifih.cs

Previous record: #448

**Comment by Chocobozzz** [comment]
Thanks, it should be fixed by https://github.com/Chocobozzz/PeerTube/commit/bb8f7872f5a473c47a688b0c282ff34cd78a9835 (just update your alias command)
