### ISSUE TITLE
Unable to follow an instance (name changed : videos.pair2jeux.tube)

### ISSUE THREAD

**Issue by gegeweb** [Chocobozzz/PeerTube#1556]
since the instance videos.lecygnenoir.info changed its domain name, the federation with this instance no longer worked.
I've deleted videos.lecygnenoir.info from the followed instances and tryed to add videos.pair2jeux.tube.

The action fails as if the instance was already referenced : unique constraint violation.

So trying to follow videos.lecygnenoir.info doesn't works because that's a redirection to videos.pair2jeux.tube. 
And trying to follow videos.pair2jeux.tube doesn't works.

Is there a way to delete videos.pair2jeux.tube from the BD?

**Additional information**
* PeerTube version or URL: 1.2.0-rc1 (same issue with 1.1.0)

* Link to server log if useful (journalctl or /var/www/peertube/storage/logs/):

failed activitypub-follow job :

```

{
  "host": "videos.pair2jeux.tube:443",
  "name": "peertube",
  "followerActorId": 1
}
SequelizeUniqueConstraintError: Validation error
    at Query.formatError (/usr/local/www/peertube/versions/peertube-v1.2.0-rc.1/node_modules/sequelize/lib/dialects/postgres/query.js:325:18)
    at query.catch.then.then.queryResult (/usr/local/www/peertube/versions/peertube-v1.2.0-rc.1/node_modules/sequelize/lib/dialects/postgres/query.js:122:24)
    at tryCatcher (/usr/local/www/peertube/versions/peertube-v1.2.0-rc.1/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/usr/local/www/peertube/versions/peertube-v1.2.0-rc.1/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/usr/local/www/peertube/versions/peertube-v1.2.0-rc.1/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/usr/local/www/peertube/versions/peertube-v1.2.0-rc.1/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/usr/local/www/peertube/versions/peertube-v1.2.0-rc.1/node_modules/bluebird/js/release/promise.js:694:18)
    at _drainQueueStep (/usr/local/www/peertube/versions/peertube-v1.2.0-rc.1/node_modules/bluebird/js/release/async.js:138:12)
    at _drainQueue (/usr/local/www/peertube/versions/peertube-v1.2.0-rc.1/node_modules/bluebird/js/release/async.js:131:9)
    at Async._drainQueues (/usr/local/www/peertube/versions/peertube-v1.2.0-rc.1/node_modules/bluebird/js/release/async.js:147:5)
    at Immediate.Async.drainQueues [as _onImmediate] (/usr/local/www/peertube/versions/peertube-v1.2.0-rc.1/node_modules/bluebird/js/release/async.js:17:14)
    at processImmediate (timers.js:632:19)
```

**Comment by Chocobozzz** [comment]
Go inside the database and remove `videos.pair2jeux.tube` and `videos.lecygnenoir.info` from the `server` table

**Comment by LecygneNoir** [comment]
From the instance point of view I have noticed no problem, as numerous instance sucessfully floow the new URL

I ran the tool to update URL when I did the migration, but I do not masterize the Activity Pub protocol, perhaps I have missed something :-/

**Comment by gegeweb** [comment]
```
delete from server where host='videos.lecygnenoir.info';
DELETE 1
delete from server where host='videos.pair2jeux.tube';
DELETE 1
```

Now it works.

Thanks.

But I had deleted `videos.lecygnenoir.info` from the list of instances followed before the attempt to subscribe to `videos.pair2jeux.tube` that I didn't have in the list.
So, why the entries in the table were still present? Bug or not bug?

**Comment by Chocobozzz** [comment]
I'm not sure to understand, but the server table keeps entries even if you unfollow them.
