### ISSUE TITLE
Installation Behind Corporate proxy impossible (with docker or debian installation)

### ISSUE THREAD

**Issue by martiou** [Chocobozzz/PeerTube#1577]
**What happened?**
I have to mount a intranet instance of peertube version 1.1.0 in my company for the end of February. Internet access is behind a proxy.
Whether it is an installation directly on debian or with docker, in spite of having fixed the variables of environment http_proxy, https_proxy, no_proxy, launched the instructions
     npm config set proxy $http_proxy
     npm config set https-proxy $http_proxy
     yarn config set https-proxy $http_proxy
     yarn config set proxy $http_proxy
The installation blocks at step [5/5] Building fresh packages ..., especially on youtube-dl

**What do you expect to happen instead?**
The installation works fine behind a corporate proxy or an installation offline is possible.

**Steps to reproduce:**
1. git clone master peertube behind corporate proxy
2. do the install with procedure debian stable or docker stable
3. Result :
[5/5] Building fresh packages...
[1/7] ⢀ bcrypt
[7/7] ⢀ youtube-dl
[-/7] ⢀ waiting...
[4/7] ⢀ rdf-canonize
error /produits/peertube/versions/peertube-v1.1.0/node_modules/youtube-dl: Command failed.
Exit code: 1
Command: node ./scripts/download.js
Arguments:
Directory: /produits/peertube/versions/peertube-v1.1.0/node_modules/youtube-dl
Output:
/produits/peertube/versions/peertube-v1.1.0/node_modules/youtube-dl/lib/downloader.js:20
        if (res.statusCode !== 302) {
                ^
TypeError: Cannot read property 'statusCode' of undefined
    at Request._callback (/produits/peertube/versions/peertube-v1.1.0/node_modules/youtube-dl/lib/downloder.js:20:17)
    at self.callback (/produits/peertube/versions/peertube-v1.1.0/node_modules/request/request.js:185:22
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at Request.onRequestError (/produits/peertube/versions/peertube-v1.1.0/node_modules/request/request.s:881:8)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at ClientRequest.onConnect (/produits/peertube/versions/peertube-v1.1.0/node_modules/tunnel-agent/in

**Additional information**
* Debian : 9.6
* PeerTube version or URL: V1.1.0
* Browser name/version: Chrome or Firefox up to date
* NodeJS version: Same of Dockerfile.strech production support
* Docker version : 18.09.1
* Docker compose version : 1.22.0

**Comment by Chocobozzz** [comment]
Any news on this @martiou?
