### ISSUE TITLE
Cannot execute migration 0305 after v1.2.0 upgrade

### ISSUE THREAD

**Issue by gllmhyt** [Chocobozzz/PeerTube#1610]
**What happened?**

My PeerTube is "bootlooping" since I upgraded it to the v1.2.0, as it cannot execute migration 0305 after start.

**Additional information**
* PeerTube version: v1.2.0
* NodeJS version: v10.15.1
* logs:

```
févr. 06 16:20:48 ns3003126 systemd[1]: Started PeerTube daemon.
févr. 06 16:20:49 ns3003126 peertube[5132]: > peertube@1.2.0 start /var/www/peertube/versions/peertube-v1.2.0
févr. 06 16:20:49 ns3003126 peertube[5132]: > node dist/server
févr. 06 16:20:58 ns3003126 peertube[5132]: [tube.postblue.info:443] 2019-02-06 16:20:58.558 info: Begin migrations.
févr. 06 16:20:58 ns3003126 peertube[5132]: [tube.postblue.info:443] 2019-02-06 16:20:58.577 info: Executing 0305-fix-unfederated-videos.js migration script.
févr. 06 16:20:58 ns3003126 peertube[5132]: [tube.postblue.info:443] 2019-02-06 16:20:58.661 error: Cannot execute migration 0305. {
févr. 06 16:20:58 ns3003126 peertube[5132]:   "meta": {
févr. 06 16:20:58 ns3003126 peertube[5132]:     "err": {
févr. 06 16:20:58 ns3003126 peertube[5132]:       "stack": "SequelizeDatabaseError: erreur de syntaxe sur ou près de « ON »\n    at Query.formatError (/var/www/peertube/versions/peertube-v1.2.0/node_modules/sequelize/lib/dialects/postgres/query.js:363:16)\n    at query.catch.err (/var/www/peertube/versions/peertube-v1.2.0/node_modules/sequelize/lib/dialects/postgres/query.js:86:18)\n    at tryCatcher (/var/www/peertube/versions/peertube-v1.2.0/node_modules/bluebird/js/release/util.js:16:23)\n    at Promise._settlePromiseFromHandler (/var/www/peertube/versions/peertube-v1.2.0/node_modules/bluebird/js/release/promise.js:512:31)\n    at Promise._settlePromise (/var/www/peertube/versions/peertube-v1.2.0/node_modules/bluebird/js/release/promise.js:569:18)\n    at Promise._settlePromise0 (/var/www/peertube/versions/peertube-v1.2.0/node_modules/bluebird/js/release/promise.js:614:10)\n    at Promise._settlePromises (/var/www/peertube/versions/peertube-v1.2.0/node_modules/bluebird/js/release/promise.js:690:18)\n    at _drainQueueStep (/var/www/peertube/versions/peertube-v1.2.0/node_modules/bluebird/js/release/async.js:138:12)\n    at _drainQueue (/var/www/peertube/versions/peertube-v1.2.0/node_modules/bluebird/js/release/async.js:131:9)\n    at Async._drainQueues (/var/www/peertube/versions/peertube-v1.2.0/node_modules/bluebird/js/release/async.js:147:5)\n    at Immediate.Async.drainQueues [as _onImmediate] (/var/www/peertube/versions/peertube-v1.2.0/node_modules/bluebird/js/release/async.js:17:14)\n    at runCallback (timers.js:705:18)\n    at tryOnImmediate (timers.js:676:5)\n    at processImmediate (timers.js:658:5)",
févr. 06 16:20:58 ns3003126 peertube[5132]:       "message": "erreur de syntaxe sur ou près de « ON »",
févr. 06 16:20:58 ns3003126 peertube[5132]:       "name": "SequelizeDatabaseError",
févr. 06 16:20:58 ns3003126 peertube[5132]:       "parent": {
févr. 06 16:20:58 ns3003126 peertube[5132]:         "stack": "error: erreur de syntaxe sur ou près de « ON »\n    at Connection.parseE (/var/www/peertube/versions/peertube-v1.2.0/node_modules/pg/lib/connection.js:554:11)\n    at Connection.parseMessage (/var/www/peertube/versions/peertube-v1.2.0/node_modules/pg/lib/connection.js:379:19)\n    at Socket.<anonymous> (/var/www/peertube/versions/peertube-v1.2.0/node_modules/pg/lib/connection.js:119:22)\n    at Socket.emit (events.js:189:13)\n    at addChunk (_stream_readable.js:284:12)\n    at readableAddChunk (_stream_readable.js:265:11)\n    at Socket.Readable.push (_stream_readable.js:220:10)\n    at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)",
févr. 06 16:20:58 ns3003126 peertube[5132]:         "message": "erreur de syntaxe sur ou près de « ON »",
févr. 06 16:20:58 ns3003126 peertube[5132]:         "name": "error",
févr. 06 16:20:58 ns3003126 peertube[5132]:         "length": 100,
févr. 06 16:20:58 ns3003126 peertube[5132]:         "severity": "ERREUR",
févr. 06 16:20:58 ns3003126 peertube[5132]:         "code": "42601",
févr. 06 16:20:58 ns3003126 peertube[5132]:         "position": "425",
févr. 06 16:20:58 ns3003126 peertube[5132]:         "file": "scan.l",
févr. 06 16:20:58 ns3003126 peertube[5132]:         "line": "1067",
févr. 06 16:20:58 ns3003126 peertube[5132]:         "routine": "scanner_yyerror",
févr. 06 16:20:58 ns3003126 peertube[5132]:         "sql": "INSERT INTO \"videoShare\" (url, \"actorId\", \"videoId\", \"createdAt\", \"updatedAt\") (SELECT video.url || '/announces/' || \"videoChannel\".\"actorId\" as url, \"videoChannel\".\"actorId\" AS \"actorId\", \"video\".\"id\" AS \"videoId\", NOW() AS \"createdAt\", NOW() AS \"updatedAt\" FROM video INNER JOIN \"videoChannel\" ON \"video\".\"channelId\" = \"videoChannel\".\"id\" WHERE \"video\".\"remote\" = false AND \"video\".\"privacy\" != 3 AND \"video\".\"state\" = 1) ON CONFLICT DO NOTHING"
févr. 06 16:20:58 ns3003126 peertube[5132]:       },
févr. 06 16:20:58 ns3003126 peertube[5132]:       "original": {
févr. 06 16:20:58 ns3003126 peertube[5132]:         "stack": "error: erreur de syntaxe sur ou près de « ON »\n    at Connection.parseE (/var/www/peertube/versions/peertube-v1.2.0/node_modules/pg/lib/connection.js:554:11)\n    at Connection.parseMessage (/var/www/peertube/versions/peertube-v1.2.0/node_modules/pg/lib/connection.js:379:19)\n    at Socket.<anonymous> (/var/www/peertube/versions/peertube-v1.2.0/node_modules/pg/lib/connection.js:119:22)\n    at Socket.emit (events.js:189:13)\n    at addChunk (_stream_readable.js:284:12)\n    at readableAddChunk (_stream_readable.js:265:11)\n    at Socket.Readable.push (_stream_readable.js:220:10)\n    at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)",
févr. 06 16:20:58 ns3003126 peertube[5132]:         "message": "erreur de syntaxe sur ou près de « ON »",
févr. 06 16:20:58 ns3003126 peertube[5132]:         "name": "error",
févr. 06 16:20:58 ns3003126 peertube[5132]:         "length": 100,
févr. 06 16:20:58 ns3003126 peertube[5132]:         "severity": "ERREUR",
févr. 06 16:20:58 ns3003126 peertube[5132]:         "code": "42601",
févr. 06 16:20:58 ns3003126 peertube[5132]:         "position": "425",
févr. 06 16:20:58 ns3003126 peertube[5132]:         "file": "scan.l",
févr. 06 16:20:58 ns3003126 peertube[5132]:         "line": "1067",
févr. 06 16:20:58 ns3003126 peertube[5132]:         "routine": "scanner_yyerror",
févr. 06 16:20:58 ns3003126 peertube[5132]:         "sql": "INSERT INTO \"videoShare\" (url, \"actorId\", \"videoId\", \"createdAt\", \"updatedAt\") (SELECT video.url || '/announces/' || \"videoChannel\".\"actorId\" as url, \"videoChannel\".\"actorId\" AS \"actorId\", \"video\".\"id\" AS \"videoId\", NOW() AS \"createdAt\", NOW() AS \"updatedAt\" FROM video INNER JOIN \"videoChannel\" ON \"video\".\"channelId\" = \"videoChannel\".\"id\" WHERE \"video\".\"remote\" = false AND \"video\".\"privacy\" != 3 AND \"video\".\"state\" = 1) ON CONFLICT DO NOTHING"
févr. 06 16:20:58 ns3003126 peertube[5132]:       },
févr. 06 16:20:58 ns3003126 peertube[5132]:       "sql": "INSERT INTO \"videoShare\" (url, \"actorId\", \"videoId\", \"createdAt\", \"updatedAt\") (SELECT video.url || '/announces/' || \"videoChannel\".\"actorId\" as url, \"videoChannel\".\"actorId\" AS \"actorId\", \"video\".\"id\" AS \"videoId\", NOW() AS \"createdAt\", NOW() AS \"updatedAt\" FROM video INNER JOIN \"videoChannel\" ON \"video\".\"channelId\" = \"videoChannel\".\"id\" WHERE \"video\".\"remote\" = false AND \"video\".\"privacy\" != 3 AND \"video\".\"state\" = 1) ON CONFLICT DO NOTHING"
févr. 06 16:20:58 ns3003126 peertube[5132]:     }
févr. 06 16:20:58 ns3003126 peertube[5132]:   }
févr. 06 16:20:58 ns3003126 peertube[5132]: }
févr. 06 16:20:58 ns3003126 peertube[5132]: npm ERR! code ELIFECYCLE
févr. 06 16:20:58 ns3003126 peertube[5132]: npm ERR! errno 255
févr. 06 16:20:58 ns3003126 peertube[5132]: npm ERR! peertube@1.2.0 start: `node dist/server`
févr. 06 16:20:58 ns3003126 peertube[5132]: npm ERR! Exit status 255
févr. 06 16:20:58 ns3003126 peertube[5132]: npm ERR!
févr. 06 16:20:58 ns3003126 peertube[5132]: npm ERR! Failed at the peertube@1.2.0 start script.
févr. 06 16:20:58 ns3003126 peertube[5132]: npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
févr. 06 16:20:58 ns3003126 peertube[5132]: npm ERR! A complete log of this run can be found in:
févr. 06 16:20:58 ns3003126 peertube[5132]: npm ERR!     /var/www/peertube/.npm/_logs/2019-02-06T15_20_58_732Z-debug.log
févr. 06 16:20:58 ns3003126 systemd[1]: peertube.service: Main process exited, code=exited, status=255/n/a
févr. 06 16:20:58 ns3003126 systemd[1]: peertube.service: Unit entered failed state.
févr. 06 16:20:58 ns3003126 systemd[1]: peertube.service: Failed with result 'exit-code'.
févr. 06 16:20:58 ns3003126 systemd[1]: peertube.service: Service hold-off time over, scheduling restart.
févr. 06 16:20:58 ns3003126 systemd[1]: Stopped PeerTube daemon.
```

**Comment by tcitworld** [comment]
What's your PostgreSQL Version ?

**Comment by gllmhyt** [comment]
@tcitworld I'm realizing that my PostgreSQL installation is messed up (having 9.4 to 11 installed) and I don't know in which version is installed peertube... I will have to figure that out to answer you.

**Comment by gllmhyt** [comment]
I found out that the peertube_prod database was still in the PostgreSQL 9.4 cluster. Actually, I learned today how pg_upgradecluster works. Now that I pg_upgradecluster'd the 9.4 main cluster where peertube_prod still was, the database has been migrated to the 11 main cluster and working like a charm. Thank you @tcitworld for your question, it made me progress!
