### ISSUE TITLE
Make the server tools use Environment Variables

### ISSUE THREAD

**Issue by LecygneNoir** [Chocobozzz/PeerTube#1640]
Hello!

**What happened?**
I have tried to run tools scripts from https://github.com/Chocobozzz/PeerTube/blob/develop/support/doc/tools.md inside a docker instance.

Unfortunately it fails as some Peertube parameters are configured throug env variable through docker (postgres DB, redis, password, ...)

Thus it seems that tools use only the production.yaml file, and cannot connect to database as this is default values inside the file.

**What do you expect to happen instead?**
Dunno if this is even possible, but could the tools script use env variable the same way than the master process?  
I have seen nothing particular about env var in the [docker-entrypoint](https://github.com/Chocobozzz/PeerTube/blob/develop/support/docker/production/docker-entrypoint.sh) other than the copy of custom-environment-variables.yaml so my guess is they are used directly in the main Peertube process.

Could this be possible?

**Steps to reproduce:**

1. Launch a docker Peertube instance (default docker-compose will do), using env variable to pass postgres database name (use another name for postgres than the default "postgres" used in production.yaml)

2. run exec bash to go inside `docker exec -it DOCKER_NAME bash`

3. try to launch a tools, for example
```
 sudo -u peertube NODE_CONFIG_DIR=/config NODE_ENV=production npm run optimize-old-videos
```

It fails with an error like

```
{ SequelizeHostNotFoundError: getaddrinfo ENOTFOUND postgres postgres:5432
    at connection.connect.err (/app/node_modules/sequelize/lib/dialects/postgres/connection-manager.js:119:24)
    at Connection.connectingErrorHandler (/app/node_modules/pg/lib/client.js:140:14)
    at emitOne (events.js:116:13)
    at Connection.emit (events.js:211:7)
    at Socket.reportStreamError (/app/node_modules/pg/lib/connection.js:71:10)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:66:8)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
    at process._tickCallback (internal/process/next_tick.js:181:9)
  name: 'SequelizeHostNotFoundError',
  parent:
   { Error: getaddrinfo ENOTFOUND postgres postgres:5432
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:67:26)
     errno: 'ENOTFOUND',
     code: 'ENOTFOUND',
     syscall: 'getaddrinfo',
     hostname: 'postgres',
     host: 'postgres',
     port: 5432 },
  original:
   { Error: getaddrinfo ENOTFOUND postgres postgres:5432
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:67:26)
     errno: 'ENOTFOUND',
     code: 'ENOTFOUND',
     syscall: 'getaddrinfo',
     hostname: 'postgres',
     host: 'postgres',
     port: 5432 } }
```

I hope this is clearly explained, if not do not hesitate to ask! 🙏 

Thank you a lot.

Regards

**Comment by LecygneNoir** [comment]
Hello,

I have played around this error a little, and either because of new versions (I Use 1.4.1 now) or because I now use `-E` in sudo to grab all env variables, but I am able to run the script without problem:

```
sudo -E -u peertube NODE_CONFIG_DIR=/config/ NODE_ENV=production npm run optimize-old-videos
```

works perfectly well :+1: 

So I guess it may be closed, thanks! :hugs:
