### ISSUE TITLE
[DOC] Add python-dev install dependency in support/doc/dependencies.md ?

### ISSUE THREAD

**Issue by fallen** [Chocobozzz/PeerTube#1641]
**What happened?**
I tried to install PeerTube on Debian Stretch 9.8 amd64 on OVH Kimsufi KS-3 server.
It gave me the following error:

```bash
$ cd ./peertube-latest && sudo -H -u peertube yarn install --production --pure-lockfile
yarn install v1.13.0
[1/5] Validating package.json...
[2/5] Resolving packages...
warning Resolution field "@types/bluebird@3.5.21" is incompatible with requested version "@types/bluebird@3.5.18"
[3/5] Fetching packages...
info fsevents@1.2.4: The platform "linux" is incompatible with this module.
info "fsevents@1.2.4" is an optional dependency and failed compatibility check. Excluding it from installation.
[4/5] Linking dependencies...
[5/5] Building fresh packages...
[-/7] ⠄ waiting...
[7/7] ⠄ youtube-dl
[-/7] ⠄ waiting...
[4/7] ⠄ rdf-canonize
error /var/www/peertube/versions/peertube-v1.2.1/node_modules/rdf-canonize: Command failed.
Exit code: 1
Command: node-gyp rebuild
Arguments: 
Directory: /var/www/peertube/versions/peertube-v1.2.1/node_modules/rdf-canonize
Output:
gyp info it worked if it ends with ok
gyp info using node-gyp@3.8.0
gyp info using node@8.15.0 | linux | x64
gyp http GET https://nodejs.org/download/release/v8.15.0/node-v8.15.0-headers.tar.gz
gyp http 200 https://nodejs.org/download/release/v8.15.0/node-v8.15.0-headers.tar.gz
gyp http GET https://nodejs.org/download/release/v8.15.0/SHASUMS256.txt
gyp http 200 https://nodejs.org/download/release/v8.15.0/SHASUMS256.txt
gyp info spawn /usr/bin/python2
gyp info spawn args [ '/usr/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/var/www/peertube/versions/peertube-v1.2.1/node_modules/rdf-canonize/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/var/www/peertube/.node-gyp/8.15.0/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/var/www/peertube/.node-gyp/8.15.0',
gyp info spawn args   '-Dnode_gyp_dir=/usr/lib/node_modules/npm/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/var/www/peertube/.node-gyp/8.15.0/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/var/www/peertube/versions/peertube-v1.2.1/node_modules/rdf-canonize',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
Traceback (most recent call last):
  File "/usr/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py", line 13, in <module>
    import gyp
  File "/usr/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 8, in <module>
    import gyp.input
  File "/usr/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 5, in <module>
    from compiler.ast import Const
ImportError: No module named compiler.ast
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:345:16)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Linux 4.9.152-xxxx-std-ipv6-64
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /var/www/peertube/versions/peertube-v1.2.1/node_modules/rdf-canonize
```

**What do you expect to happen instead?**
Proper installation without error.

**Steps to reproduce:**
Follow this: https://github.com/Chocobozzz/PeerTube/blob/develop/support/doc/production.md

**Additional information**
* PeerTube version or URL: 1.2.1
* Browser name/version: Firefox 65.0
* NodeJS version: 8.15.0

**Proposed fix**

I fixed the issue by installing python-dev via 
```bash
$ sudo apt install python-dev
```

Maybe the production guide/dependency guide needs updating to add this info?

**Comment by Chocobozzz** [comment]
Yep please do a PR!
