### ISSUE TITLE
API crashes when creating channel with " in name

### ISSUE THREAD

**Issue by LecygneNoir** [Chocobozzz/PeerTube#1712]
Hello!

**What happened?**
I am using the API to create channel through `/api/v1/video-channels/`

When the name of the channel contains double quote `"`, the API return an error 400 and inside Peertube there is a stacktrace:

```
error: Error in controller. {
  "meta": {
    "err": "SyntaxError: Unexpected token t in JSON at position 73\n    at JSON.parse (<anonymous>)\n    at parse (/app/node_modules/body-parser/lib/types/json.js:89:19)\n    at /app/node_modules/body-parser/lib/read.js:121:18\n    at invokeCallback (/app/node_modules/raw-body/index.js:224:16)\n    at done (/app/node_modules/raw-body/index.js:213:7)\n    at IncomingMessage.onEnd (/app/node_modules/raw-body/index.js:273:7)\n    at emitNone (events.js:106:13)\n    at IncomingMessage.emit (events.js:208:7)\n    at endReadableNT (_stream_readable.js:1064:12)\n    at _combinedTickCallback (internal/process/next_tick.js:139:11)\n    at process._tickCallback (internal/process/next_tick.js:181:9)"
  },
  "err": "SyntaxError: Unexpected token t in JSON at position 73\n    at JSON.parse (<anonymous>)\n    at parse (/app/node_modules/body-parser/lib/types/json.js:89:19)\n    at /app/node_modules/body-parser/lib/read.js:121:18\n    at invokeCallback (/app/node_modules/raw-body/index.js:224:16)\n    at done (/app/node_modules/raw-body/index.js:213:7)\n    at IncomingMessage.onEnd (/app/node_modules/raw-body/index.js:273:7)\n    at emitNone (events.js:106:13)\n    at IncomingMessage.emit (events.js:208:7)\n    at endReadableNT (_stream_readable.js:1064:12)\n    at _combinedTickCallback (internal/process/next_tick.js:139:11)\n    at process._tickCallback (internal/process/next_tick.js:181:9)"
}
```
**Note**: when using the web interface, the error is not present and the channel is created.

**What do you expect to happen instead?**
The channel should be created like when using the web interface.

**Steps to reproduce:**

Try to create a channel named `this "test"` through the API using `peertube.url/api/v1/video-channels/`

The API returns 400 and error pops in Peertube logs

**Additional information**
* PeerTube version or URL: Peertube 1.2.1 on https://videos.pair2jeux.tube
* Browser name/version: Firefox 65
* NodeJS version: v8.15.0

Thank you!

**Comment by Chocobozzz** [comment]
Please paste the code you use to create the channel
