### ISSUE TITLE
error: Cannot execute migration 0005 

### ISSUE THREAD

**Issue by EBendinelli** [Chocobozzz/PeerTube#1736]
Getting the error Cannot execute migration 0005 similar to #1545 and #432
Posting console log for more clarity. 

`nodejs -v`: 10.15.3
`psql --version`: 9.6.11
PeerTube version or URL: v1.2.1
Debian Stretch 9.8

Fresh install. I followed the insctrutions and when I start Peertube I get this:

```
Mar 27 14:22:00 media systemd[1]: Started PeerTube daemon.
Mar 27 14:22:01 media peertube[24094]: > peertube@1.2.1 start /media/data/peertube/versions/peertube-v1.2.1
Mar 27 14:22:01 media peertube[24094]: > node dist/server
Mar 27 14:22:03 media peertube[24094]: [myhost:443] 2019-03-27 14:22:03.337 info: Begin migrations.
Mar 27 14:22:03 media peertube[24094]: [myhost:443] 2019-03-27 14:22:03.340 info: Executing 0005-email-pod.js migration script.
Mar 27 14:22:03 media peertube[24094]: [myhost:443] 2019-03-27 14:22:03.356 error: Cannot execute migration 0005. {
Mar 27 14:22:03 media peertube[24094]:   "meta": {
Mar 27 14:22:03 media peertube[24094]:     "err": {
Mar 27 14:22:03 media peertube[24094]:       "stack": "SequelizeDatabaseError: relation \"public.Pods\" does not exist\n    at Query.formatError (/media/data/peertube/versions/peertube-v1.2.1/node_modules/sequelize/lib/dialects/postgres/query.js:363:16)\n    at query.catch.err (/media/data/peertube/versions/peertube-v1.2.1/node_modules/sequelize/lib/dialects/postgres/query.js:86:18)\n    at tryCatcher (/media/data/peertube/versions/peertube-v1.2.1/node_modules/bluebird/js/release/util.js:16:23)\n    at Promise._settlePromiseFromHandler (/media/data/peertube/versions/peertube-v1.2.1/node_modules/bluebird/js/release/promise.js:512:31)\n    at Promise._settlePromise (/media/data/peertube/versions/peertube-v1.2.1/node_modules/bluebird/js/release/promise.js:569:18)\n    at Promise._settlePromise0 (/media/data/peertube/versions/peertube-v1.2.1/node_modules/bluebird/js/release/promise.js:614:10)\n    at Promise._settlePromises (/media/data/peertube/versions/peertube-v1.2.1/node_modules/bluebird/js/release/promise.js:690:18)\n    at _drainQueueStep (/media/data/peertube/versions/peertube-v1.2.1/node_modules/bluebird/js/release/async.js:138:12)\n    at _drainQueue (/media/data/peertube/versions/peertube-v1.2.1/node_modules/bluebird/js/release/async.js:131:9)\n    at Async._drainQueues (/media/data/peertube/versions/peertube-v1.2.1/node_modules/bluebird/js/release/async.js:147:5)\n    at Immediate.Async.drainQueues [as _onImmediate] (/media/data/peertube/versions/peertube-v1.2.1/node_modules/bluebird/js/release/async.js:17:14)\n    at runCallback (timers.js:705:18)\n    at tryOnImmediate (timers.js:676:5)\n    at processImmediate (timers.js:658:5)",
Mar 27 14:22:03 media peertube[24094]:       "message": "relation \"public.Pods\" does not exist",
Mar 27 14:22:03 media peertube[24094]:       "name": "SequelizeDatabaseError",
Mar 27 14:22:03 media peertube[24094]:       "parent": {
Mar 27 14:22:03 media peertube[24094]:         "stack": "error: relation \"public.Pods\" does not exist\n    at Connection.parseE (/media/data/peertube/versions/peertube-v1.2.1/node_modules/pg/lib/connection.js:601:11)\n    at Connection.parseMessage (/media/data/peertube/versions/peertube-v1.2.1/node_modules/pg/lib/connection.js:398:19)\n    at Socket.<anonymous> (/media/data/peertube/versions/peertube-v1.2.1/node_modules/pg/lib/connection.js:120:22)\n    at Socket.emit (events.js:189:13)\n    at addChunk (_stream_readable.js:284:12)\n    at readableAddChunk (_stream_readable.js:265:11)\n    at Socket.Readable.push (_stream_readable.js:220:10)\n    at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)",
Mar 27 14:22:03 media peertube[24094]:         "message": "relation \"public.Pods\" does not exist",
Mar 27 14:22:03 media peertube[24094]:         "name": "error",
Mar 27 14:22:03 media peertube[24094]:         "length": 109,
Mar 27 14:22:03 media systemd[1]: peertube.service: Main process exited, code=exited, status=255/n/a
Mar 27 14:22:03 media systemd[1]: peertube.service: Unit entered failed state.
Mar 27 14:22:03 media systemd[1]: peertube.service: Failed with result 'exit-code'.
Mar 27 14:22:03 media systemd[1]: peertube.service: Service hold-off time over, scheduling restart.
Mar 27 14:22:03 media systemd[1]: Stopped PeerTube daemon.
```

I've tried manually creating the Public.Pods table but that just led to more error when creating the DB entries. Haven't tried changing the dirs as suggested in #432 but I don't see how that could change anything.

**Comment by Chocobozzz** [comment]
Delete and recreate the database (with the postgresql extensions), use `debug` logs (https://github.com/Chocobozzz/PeerTube/blob/develop/config/production.yaml.example#L62), start peertube and paste the output please.

**Comment by EBendinelli** [comment]
Deleted the db, recreated, added the extensions, set peertube config to debug and here is the output:
```
Mar 27 15:49:36 media systemd[1]: Started PeerTube daemon.
Mar 27 15:49:37 media peertube[19298]: > peertube@1.2.1 start /media/data/peertube/versions/peertube-v1.2.1
Mar 27 15:49:37 media peertube[19298]: > node dist/server
Mar 27 15:49:39 media peertube[19298]: [myhost.org:443] 2019-03-27 15:49:39.335 info: Begin migrations.
Mar 27 15:49:39 media peertube[19298]: [myhost.org:443] 2019-03-27 15:49:39.338 info: Executing 0005-email-pod.js migration script.
Mar 27 15:49:39 media peertube[19298]: [myhost.org:443] 2019-03-27 15:49:39.353 error: Cannot execute migration 0005. {
Mar 27 15:49:39 media peertube[19298]:   "meta": {
Mar 27 15:49:39 media peertube[19298]:     "err": {
Mar 27 15:49:39 media peertube[19298]:       "stack": "SequelizeDatabaseError: relation \"public.Pods\" does not exist\n    at Query.formatError (/media/data/peertube/versions/peertube-v1.2.1/node_modules/sequelize/lib/dialects/postgres/query.js:363:16)\n    at query.catch.err (/media/data/peertube/versions/peertube-v1.2.1/node_modules/sequelize/lib/dialects/postgres/query.js:86:18)\n    at tryCatcher (/media/data/peertube/versions/peertube-v1.2.1/node_modules/bluebird/js/release/util.js:16:23)\n    at Promise._settlePromiseFromHandler (/media/data/peertube/versions/peertube-v1.2.1/node_modules/bluebird/js/release/promise.js:512:31)\n    at Promise._settlePromise (/media/data/peertube/versions/peertube-v1.2.1/node_modules/bluebird/js/release/promise.js:569:18)\n    at Promise._settlePromise0 (/media/data/peertube/versions/peertube-v1.2.1/node_modules/bluebird/js/release/promise.js:614:10)\n    at Promise._settlePromises (/media/data/peertube/versions/peertube-v1.2.1/node_modules/bluebird/js/release/promise.js:690:18)\n    at _drainQueueStep (/media/data/peertube/versions/peertube-v1.2.1/node_modules/bluebird/js/release/async.js:138:12)\n    at _drainQueue (/media/data/peertube/versions/peertube-v1.2.1/node_modules/bluebird/js/release/async.js:131:9)\n    at Async._drainQueues (/media/data/peertube/versions/peertube-v1.2.1/node_modules/bluebird/js/release/async.js:147:5)\n    at Immediate.Async.drainQueues [as _onImmediate] (/media/data/peertube/versions/peertube-v1.2.1/node_modules/bluebird/js/release/async.js:17:14)\n    at runCallback (timers.js:705:18)\n    at tryOnImmediate (timers.js:676:5)\n    at processImmediate (timers.js:658:5)",
Mar 27 15:49:39 media peertube[19298]:       "message": "relation \"public.Pods\" does not exist",
Mar 27 15:49:39 media peertube[19298]:       "name": "SequelizeDatabaseError",
Mar 27 15:49:39 media peertube[19298]:       "parent": {
Mar 27 15:49:39 media peertube[19298]:         "stack": "error: relation \"public.Pods\" does not exist\n    at Connection.parseE (/media/data/peertube/versions/peertube-v1.2.1/node_modules/pg/lib/connection.js:601:11)\n    at Connection.parseMessage (/media/data/peertube/versions/peertube-v1.2.1/node_modules/pg/lib/connection.js:398:19)\n    at Socket.<anonymous> (/media/data/peertube/versions/peertube-v1.2.1/node_modules/pg/lib/connection.js:120:22)\n    at Socket.emit (events.js:189:13)\n    at addChunk (_stream_readable.js:284:12)\n    at readableAddChunk (_stream_readable.js:265:11)\n    at Socket.Readable.push (_stream_readable.js:220:10)\n    at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)",
Mar 27 15:49:39 media peertube[19298]:         "message": "relation \"public.Pods\" does not exist",
Mar 27 15:49:39 media peertube[19298]:         "name": "error",
Mar 27 15:49:39 media peertube[19298]:         "length": 109,
Mar 27 15:49:39 media peertube[19298]:         "severity": "ERROR",
Mar 27 15:49:39 media peertube[19298]:         "code": "42P01",
Mar 27 15:49:39 media peertube[19298]:         "file": "namespace.c",
Mar 27 15:49:39 media peertube[19298]:         "line": "415",
Mar 27 15:49:39 media peertube[19298]:         "routine": "RangeVarGetRelidExtended",
Mar 27 15:49:39 media peertube[19298]:         "sql": "ALTER TABLE \"public\".\"Pods\" ADD COLUMN \"email\" VARCHAR(400) NOT NULL DEFAULT '';"
Mar 27 15:49:39 media peertube[19298]:       },
Mar 27 15:49:39 media peertube[19298]:       "original": {
Mar 27 15:49:39 media peertube[19298]:         "stack": "error: relation \"public.Pods\" does not exist\n    at Connection.parseE (/media/data/peertube/versions/peertube-v1.2.1/node_modules/pg/lib/connection.js:601:11)\n    at Connection.parseMessage (/media/data/peertube/versions/peertube-v1.2.1/node_modules/pg/lib/connection.js:398:19)\n    at Socket.<anonymous> (/media/data/peertube/versions/peertube-v1.2.1/node_modules/pg/lib/connection.js:120:22)\n    at Socket.emit (events.js:189:13)\n    at addChunk (_stream_readable.js:284:12)\n    at readableAddChunk (_stream_readable.js:265:11)\n    at Socket.Readable.push (_stream_readable.js:220:10)\n    at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)",
Mar 27 15:49:39 media peertube[19298]:         "message": "relation \"public.Pods\" does not exist",
Mar 27 15:49:39 media peertube[19298]:         "name": "error",
Mar 27 15:49:39 media peertube[19298]:         "length": 109,
Mar 27 15:49:39 media peertube[19298]:         "severity": "ERROR",
Mar 27 15:49:39 media peertube[19298]:         "code": "42P01",
Mar 27 15:49:39 media systemd[1]: peertube.service: Main process exited, code=exited, status=255/n/a
Mar 27 15:49:39 media systemd[1]: peertube.service: Unit entered failed state.
Mar 27 15:49:39 media systemd[1]: peertube.service: Failed with result 'exit-code'.
Mar 27 15:49:39 media systemd[1]: peertube.service: Service hold-off time over, scheduling restart.
Mar 27 15:49:39 media systemd[1]: Stopped PeerTube daemon.
```

**Comment by EBendinelli** [comment]
So to follow up on this. A colleague installed Peertube on Ubuntu without issue and sent me the DB to import. When doing so I was faced with this error message:
`psql: FATAL: Peer authentication failed for user “public”`

I fixed it by following [these instructions](https://gist.github.com/AtulKsol/4470d377b448e56468baef85af7fd614) which basically ask to change the connection method of postgresql from peer to md5 in /etc/postgresql/pg_hba.conf

Running peertube after doing this modification worked. I'm not sure if that means something has to be changed in the Peertube code or added to the doc but this info might be useful for others.

Anyway, thanks for your help!

**Comment by ChanoSan** [comment]
I'd just like to add a comment, in case this might help future users. I had this exact same issue, and changing postgresql's connection method to md5 also fixed it.

Please note, it was necessary to drop the peertube_prod db and recreate it, but once I did that and restarted all the services, it functioned perfectly. It might be worth adding a footnote in production.md or linking to these issues.

**Comment by Kleyment** [comment]
I have the same problem.
My config :

Debian 10
node -v v10.16.3
psql --version: 11.5

PeerTube version or URL: v1.4.1
