### ISSUE TITLE
peertube daemon stuck in startup loop, "SequelizeConnectionError: password authentication failed for user \"peertube\"

### ISSUE THREAD

**Issue by ChanoSan** [Chocobozzz/PeerTube#1740]
During production setup, inputting:
`$ sudo systemctl start peertube`
`$ sudo journalctl -feu peertube`

...causes the daemon to repeatedly loop between starting and shutting down.
journalctl logs show:
```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'start' ]
2 info using npm@6.4.1
3 info using node@v10.15.3
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle peertube@1.2.1~prestart: peertube@1.2.1
6 info lifecycle peertube@1.2.1~start: peertube@1.2.1
7 verbose lifecycle peertube@1.2.1~start: unsafe-perm in lifecycle true
8 verbose lifecycle peertube@1.2.1~start: PATH: /usr/lib/node_modules/npm/node_modules/npm-lifecycle$
9 verbose lifecycle peertube@1.2.1~start: CWD: /var/www/peertube/versions/peertube-v1.2.1
10 silly lifecycle peertube@1.2.1~start: Args: [ '-c', 'node dist/server' ]
11 silly lifecycle peertube@1.2.1~start: Returned: code: 255  signal: null
12 info lifecycle peertube@1.2.1~start: Failed to exec start script
13 verbose stack Error: peertube@1.2.1 start: `node dist/server`
13 verbose stack Exit status 255
13 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecyc$
13 verbose stack     at EventEmitter.emit (events.js:189:13)
13 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecyc$
13 verbose stack     at ChildProcess.emit (events.js:189:13)
13 verbose stack     at maybeClose (internal/child_process.js:970:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
14 verbose pkgid peertube@1.2.1
15 verbose cwd /var/www/peertube/versions/peertube-v1.2.1
16 verbose Linux 4.15.0-45-generic
17 verbose argv "/usr/bin/node" "/usr/bin/npm" "start"
18 verbose node v10.15.3
19 verbose npm  v6.4.1
20 error code ELIFECYCLE
21 error errno 255
22 error peertube@1.2.1 start: `node dist/server`
22 error Exit status 255
23 error Failed at the peertube@1.2.1 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 255, true ]
```
Consulting /var/www/peertube/storage/logs/peertube.log shows the following extremely long error message repeated dozens of times:
```
{"err":{"stack":"SequelizeConnectionError: password authentication failed for user \"peertube\"\n    at connection.connect.err (/var/www/peertube/versions/peertube-v1.2.1/node_modules/sequelize/lib/dialects/postgres/connection-manager.js:128:24)\n    at Connection.connectingErrorHandler (/var/www/peertube/versions/peertube-v1.2.1/node_modules/pg/lib/client.js:140:14)\n    at Connection.emit (events.js:189:13)\n    at Socket.<anonymous> (/var/www/peertube/versions/peertube-v1.2.1/node_modules/pg/lib/connection.js:124:12)\n    at Socket.emit (events.js:189:13)\n    at addChunk (_stream_readable.js:284:12)\n    at readableAddChunk (_stream_readable.js:265:11)\n    at Socket.Readable.push (_stream_readable.js:220:10)\n    at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)","message":"password authentication failed for user \"peertube\"","name":"SequelizeConnectionError","parent":{"stack":"error: password authentication failed for user \"peertube\"\n    at Connection.parseE (/var/www/peertube/versions/peertube-v1.2.1/node_modules/pg/lib/connection.js:554:11)\n    at Connection.parseMessage (/var/www/peertube/versions/peertube-v1.2.1/node_modules/pg/lib/connection.js:379:19)\n    at Socket.<anonymous> (/var/www/peertube/versions/peertube-v1.2.1/node_modules/pg/lib/connection.js:119:22)\n    at Socket.emit (events.js:189:13)\n    at addChunk (_stream_readable.js:284:12)\n    at readableAddChunk (_stream_readable.js:265:11)\n    at Socket.Readable.push (_stream_readable.js:220:10)\n    at TCP.onStreamRead (internal/stream_base_commons.js:94:17)","message":"password authentication failed for user \"peertube\"","name":"error","length":104,"severity":"FATAL","code":"28P01","file":"auth.c","line":"328","routine":"auth_failed"},"original":{"stack":"error: password authentication failed for user \"peertube\"\n    at Connection.parseE (/var/www/peertube/versions/peertube-v1.2.1/node_modules/pg/lib/connection.js:554:11)\n    at Connection.parseMessage (/var/www/peertube/versions/peertube-v1.2.1/node_modules/pg/lib/connection.js:379:19)\n    at Socket.<anonymous> (/var/www/peertube/versions/peertube-v1.2.1/node_modules/pg/lib/connection.js:119:22)\n    at Socket.emit (events.js:189:13)\n    at addChunk (_stream_readable.js:284:12)\n    at readableAddChunk (_stream_readable.js:265:11)\n    at Socket.Readable.push (_stream_readable.js:220:10)\n    at TCP.onStreamRead (internal/stream_base_commons.js:94:17)","message":"password authentication failed for user \"peertube\"","name":"error","length":104,"severity":"FATAL","code":"28P01","file":"auth.c","line":"328","routine":"auth_failed"}},"level":"error","message":"Cannot start application.","label":"anon-kenkai.com:443","meta":{"err":{"stack":"SequelizeConnectionError: password authentication failed for user \"peertube\"\n    at connection.connect.err (/var/www/peertube/versions/peertube-v1.2.1/node_modules/sequelize/lib/dialects/postgres/connection-manager.js:128:24)\n    at Connection.connectingErrorHandler (/var/www/peertube/versions/peertube-v1.2.1/node_modules/pg/lib/client.js:140:14)\n    at Connection.emit (events.js:189:13)\n    at Socket.<anonymous> (/var/www/peertube/versions/peertube-v1.2.1.1/node_modules/pg/lib/connection.js:124:12)\n    at Socket.emit (events.js:189:13)\n    at addChunk (_stream_readable.js:284:12)\n    at readableAddChunk (_stream_readable.js:265:11)\n    at Socket.Readable.push (_stream_readable.js:220:10)\n    at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)","message":"password authentication failed for user \"peertube\"","name":"SequelizeConnectionError","parent":{"stack":"error: password authenticentication failed for user \"peertube\"\n    at Connection.parseMessage (/var/www/peertube/versions/peertube-v1.2.1/node_modules/pg/lib/connection.js:379:19)\n    at Socket.<anonymous> (/var/www/peertube/versions/peertube-v1.2.1/node_modules/pg/lib/connection.js:119:22)\n    at Socket.emit (events.js:189:13)\n    at addChunk (_stream_readable.js:284:12)\n    at readableAddChunk (_stream_readable.js:265:11)\n    at Socket.Readable.push (_stream_readable.js:220:10)\n    at TCP.onStreamRead (internal/stream_base_commons.js:94:17)","message":"password authentication failed for user \"peertube\"","name":"error","length":104,"severity":"FATAL","code":"28P01","file":"auth.c","line":"328","routine":"auth_failed"},"original":{"stack":"error: password authentication failed for user \"peertube\"\n    at Connection.parseE (/var/www/peertube/versions/peertube-v1.2.1/node_modules/pg/lib/connection.js:554:11)\n    at Connection.parseMessage (/var/www/peertube/versions/peertube-v1.2.1/node_modules/pg/lib/connection.js:379:19)\n    at Socket.<anonymous> (/var/www/peertube/versions/peertube-v1.2.1/node_modules/pg/lib/connection.js:119:22)\n    at Socket.emit (events.js:189:13)\n    at addChunk (_stream_readable.js:284:12)\n    at readableAddChunk (_stream_readable.js:265:11)\n    at Socket.Readable.push (_stream_readable.js:220:10)\n    at TCP.onStreamRead (internal/stream_base_commons.js:94:17)","message":"password authentication failed for user \"peertube\"","name":"error","length":104,"severity":"FATAL","code":"28P01","file":"auth.c","line":"328","routine":"auth_failed"}}},"timestamp":"2019-03-28T08:23:29.086Z"}
```

Running `sudo service peertube status` shows the peertube process as active, but navigating to to the URL in browser results in a 502 error.

Seems very similar to #1433 but which has never resolved. Found similar issues posted on Framacolibri: https://framacolibri.org/t/soucis-a-linstall/3118  ...but not confident enough in French or machine translation to use information from there.

Any advice is greatly appreciated.

**Additional information**
* PeerTube version: 1.2.1
* Running on: Ubuntu 18.04
* NodeJS version: 10.15.3

**Comment by ChanoSan** [comment]
Discovered source of error: peertube user password in production.yaml was mistyped.
Closing this issue.

**Comment by NovaPhoenix** [comment]
I'm getting the same error after installing peertube, but the production.yaml file doesn't appear to contain a field for the user password. Where did you put it in?

**Comment by tcitworld** [comment]
@NovaPhoenix https://github.com/Chocobozzz/PeerTube/blob/c342726ad4ccbb90b8ff29f1cc1c89f9f7e8d98f/config/production.yaml.example#L33

**Comment by NovaPhoenix** [comment]
I assumed that would be the postgres password, but I tried both anyway to no avail. I think it might be an selinux issue now, though. I'll test when I get the chance.

**Comment by frankenstein91** [comment]
I am currently hanging in the same place after a system reboot
