### ISSUE TITLE
Unable to follow peertube account from mastodon

### ISSUE THREAD

**Issue by techknowlogick** [Chocobozzz/PeerTube#1792]
**What happened?**
Peertube Account is unable to be followed from a mastodon account. 

**What do you expect to happen instead?**
Account would be followed and will recieve new updates about new uploaded videos

**Steps to reproduce:**
1. Go to mastodon.social (and login)
2. Search for `@mike@play.jergefelt.se`
3. Attempt to follow account 
4. receive logs below

**Additional information**
* PeerTube version or URL: PeerTube v1.2.1 https://play.jergefelt.se (using official docker image)
* Postgres version: 10.1

* Logs:
```
[play.jergefelt.se:443] 2019-04-30 18:33:59.090 warn: Incorrect activity parameters. {
   "meta": {
     "activity": {
       "@context": "https://www.w3.org/ns/activitystreams",
       "id": "https://jergefelt.se/63764571-e3a1-4054-a5f6-5ebe3358f6cb",
       "type": "Follow",
       "actor": "https://jergefelt.se/users/mike",
       "object": "https://play.jergefelt.se/accounts/mike"
     }
   }
 }
```
also
```
[play.jergefelt.se:443] 2019-04-30 19:05:25.670 info: Fetching remote actor https://mastodon.social/users/tklk.
peertube_1  | [play.jergefelt.se:443] 2019-04-30 19:05:27.383 error: Cannot execute saveActorAndServerAndModelIfNotExist with many retries. {
peertube_1  |   "meta": {
peertube_1  |     "err": {
peertube_1  |       "stack": "SequelizeDatabaseError: value too long for type character varying(255)\n    at Query.formatError (/app/node_modules/sequelize/lib/dialects/postgres/query.js:363:16)\n    at query.catch.err (/app/node_modules/sequelize/lib/dialects/postgres/query.js:86:18)\n    at tryCatcher (/app/node_modules/bluebird/js/release/util.js:16:23)\n    at Promise._settlePromiseFromHandler (/app/node_modules/bluebird/js/release/promise.js:512:31)\n    at Promise._settlePromise (/app/node_modules/bluebird/js/release/promise.js:569:18)\n    at Promise._settlePromise0 (/app/node_modules/bluebird/js/release/promise.js:614:10)\n    at Promise._settlePromises (/app/node_modules/bluebird/js/release/promise.js:690:18)\n    at _drainQueueStep (/app/node_modules/bluebird/js/release/async.js:138:12)\n    at _drainQueue (/app/node_modules/bluebird/js/release/async.js:131:9)\n    at Async._drainQueues (/app/node_modules/bluebird/js/release/async.js:147:5)\n    at Immediate.Async.drainQueues (/app/node_modules/bluebird/js/release/async.js:17:14)\n    at runCallback (timers.js:810:20)\n    at tryOnImmediate (timers.js:768:5)\n    at processImmediate [as _immediateCallback] (timers.js:745:5)",
peertube_1  |       "message": "value too long for type character varying(255)",
peertube_1  |       "name": "SequelizeDatabaseError",
peertube_1  |       "parent": {
peertube_1  |         "stack": "error: value too long for type character varying(255)\n    at Connection.parseE (/app/node_modules/pg/lib/connection.js:554:11)\n    at Connection.parseMessage (/app/node_modules/pg/lib/connection.js:379:19)\n    at Socket.<anonymous> (/app/node_modules/pg/lib/connection.js:119:22)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at addChunk (_stream_readable.js:263:12)\n    at readableAddChunk (_stream_readable.js:250:11)\n    at Socket.Readable.push (_stream_readable.js:208:10)\n    at TCP.onread (net.js:601:20)",
peertube_1  |         "message": "value too long for type character varying(255)",
peertube_1  |         "name": "error",
peertube_1  |         "length": 654,
peertube_1  |         "severity": "ERROR",
peertube_1  |         "code": "22001",
peertube_1  |         "where": "SQL statement \"INSERT INTO \"account\" (\"id\",\"name\",\"description\",\"actorId\",\"createdAt\",\"updatedAt\") VALUES (DEFAULT,'techknowlogick','<p>Purveyor of artisanal <a href=\"https://mastodon.social/tags/pixelfed\" class=\"mention hashtag\" rel=\"tag\">#<span>PixelFed</span></a> hosting, and member of <a href=\"https://mastodon.social/tags/gitea\" class=\"mention hashtag\" rel=\"tag\">#<span>Gitea</span></a> dev team.</p>',11,'2019-04-30 19:05:27.375 +00:00','2019-04-30 19:05:27.375 +00:00') RETURNING *\"\nPL/pgSQL function pg_temp_5.testfunc() line 1 at SQL statement",
peertube_1  |         "file": "varchar.c",
peertube_1  |         "line": "624",
peertube_1  |         "routine": "varchar",
peertube_1  |         "sql": "CREATE OR REPLACE FUNCTION pg_temp.testfunc(OUT response \"account\", OUT sequelize_caught_exception text) RETURNS RECORD AS $func_b3c57365c9254d149d0d8bbb55dea579$ BEGIN INSERT INTO \"account\" (\"id\",\"name\",\"description\",\"actorId\",\"createdAt\",\"updatedAt\") VALUES (DEFAULT,'techknowlogick','<p>Purveyor of artisanal <a href=\"https://mastodon.social/tags/pixelfed\" class=\"mention hashtag\" rel=\"tag\">#<span>PixelFed</span></a> hosting, and member of <a href=\"https://mastodon.social/tags/gitea\" class=\"mention hashtag\" rel=\"tag\">#<span>Gitea</span></a> dev team.</p>',11,'2019-04-30 19:05:27.375 +00:00','2019-04-30 19:05:27.375 +00:00') RETURNING * INTO response; EXCEPTION WHEN unique_violation THEN GET STACKED DIAGNOSTICS sequelize_caught_exception = PG_EXCEPTION_DETAIL; END $func_b3c57365c9254d149d0d8bbb55dea579$ LANGUAGE plpgsql; SELECT (testfunc.response).*, testfunc.sequelize_caught_exception FROM pg_temp.testfunc(); DROP FUNCTION IF EXISTS pg_temp.testfunc();"
peertube_1  |       },
peertube_1  |       "original": {
peertube_1  |         "stack": "error: value too long for type character varying(255)\n    at Connection.parseE (/app/node_modules/pg/lib/connection.js:554:11)\n    at Connection.parseMessage (/app/node_modules/pg/lib/connection.js:379:19)\n    at Socket.<anonymous> (/app/node_modules/pg/lib/connection.js:119:22)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at addChunk (_stream_readable.js:263:12)\n    at readableAddChunk (_stream_readable.js:250:11)\n    at Socket.Readable.push (_stream_readable.js:208:10)\n    at TCP.onread (net.js:601:20)",
peertube_1  |         "message": "value too long for type character varying(255)",
peertube_1  |         "name": "error",
peertube_1  |         "length": 654,
peertube_1  |         "severity": "ERROR",
peertube_1  |         "code": "22001",
peertube_1  |         "where": "SQL statement \"INSERT INTO \"account\" (\"id\",\"name\",\"description\",\"actorId\",\"createdAt\",\"updatedAt\") VALUES (DEFAULT,'techknowlogick','<p>Purveyor of artisanal <a href=\"https://mastodon.social/tags/pixelfed\" class=\"mention hashtag\" rel=\"tag\">#<span>PixelFed</span></a> hosting, and member of <a href=\"https://mastodon.social/tags/gitea\" class=\"mention hashtag\" rel=\"tag\">#<span>Gitea</span></a> dev team.</p>',11,'2019-04-30 19:05:27.375 +00:00','2019-04-30 19:05:27.375 +00:00') RETURNING *\"\nPL/pgSQL function pg_temp_5.testfunc() line 1 at SQL statement",
peertube_1  |         "file": "varchar.c",
peertube_1  |         "line": "624",
peertube_1  |         "routine": "varchar",
peertube_1  |         "sql": "CREATE OR REPLACE FUNCTION pg_temp.testfunc(OUT response \"account\", OUT sequelize_caught_exception text) RETURNS RECORD AS $func_b3c57365c9254d149d0d8bbb55dea579$ BEGIN INSERT INTO \"account\" (\"id\",\"name\",\"description\",\"actorId\",\"createdAt\",\"updatedAt\") VALUES (DEFAULT,'techknowlogick','<p>Purveyor of artisanal <a href=\"https://mastodon.social/tags/pixelfed\" class=\"mention hashtag\" rel=\"tag\">#<span>PixelFed</span></a> hosting, and member of <a href=\"https://mastodon.social/tags/gitea\" class=\"mention hashtag\" rel=\"tag\">#<span>Gitea</span></a> dev team.</p>',11,'2019-04-30 19:05:27.375 +00:00','2019-04-30 19:05:27.375 +00:00') RETURNING * INTO response; EXCEPTION WHEN unique_violation THEN GET STACKED DIAGNOSTICS sequelize_caught_exception = PG_EXCEPTION_DETAIL; END $func_b3c57365c9254d149d0d8bbb55dea579$ LANGUAGE plpgsql; SELECT (testfunc.response).*, testfunc.sequelize_caught_exception FROM pg_temp.testfunc(); DROP FUNCTION IF EXISTS pg_temp.testfunc();"
peertube_1  |       },
peertube_1  |       "sql": "CREATE OR REPLACE FUNCTION pg_temp.testfunc(OUT response \"account\", OUT sequelize_caught_exception text) RETURNS RECORD AS $func_b3c57365c9254d149d0d8bbb55dea579$ BEGIN INSERT INTO \"account\" (\"id\",\"name\",\"description\",\"actorId\",\"createdAt\",\"updatedAt\") VALUES (DEFAULT,'techknowlogick','<p>Purveyor of artisanal <a href=\"https://mastodon.social/tags/pixelfed\" class=\"mention hashtag\" rel=\"tag\">#<span>PixelFed</span></a> hosting, and member of <a href=\"https://mastodon.social/tags/gitea\" class=\"mention hashtag\" rel=\"tag\">#<span>Gitea</span></a> dev team.</p>',11,'2019-04-30 19:05:27.375 +00:00','2019-04-30 19:05:27.375 +00:00') RETURNING * INTO response; EXCEPTION WHEN unique_violation THEN GET STACKED DIAGNOSTICS sequelize_caught_exception = PG_EXCEPTION_DETAIL; END $func_b3c57365c9254d149d0d8bbb55dea579$ LANGUAGE plpgsql; SELECT (testfunc.response).*, testfunc.sequelize_caught_exception FROM pg_temp.testfunc(); DROP FUNCTION IF EXISTS pg_temp.testfunc();"
peertube_1  |     }
peertube_1  |   },
peertube_1  |   "err": {
peertube_1  |     "stack": "SequelizeDatabaseError: value too long for type character varying(255)\n    at Query.formatError (/app/node_modules/sequelize/lib/dialects/postgres/query.js:363:16)\n    at query.catch.err (/app/node_modules/sequelize/lib/dialects/postgres/query.js:86:18)\n    at tryCatcher (/app/node_modules/bluebird/js/release/util.js:16:23)\n    at Promise._settlePromiseFromHandler (/app/node_modules/bluebird/js/release/promise.js:512:31)\n    at Promise._settlePromise (/app/node_modules/bluebird/js/release/promise.js:569:18)\n    at Promise._settlePromise0 (/app/node_modules/bluebird/js/release/promise.js:614:10)\n    at Promise._settlePromises (/app/node_modules/bluebird/js/release/promise.js:690:18)\n    at _drainQueueStep (/app/node_modules/bluebird/js/release/async.js:138:12)\n    at _drainQueue (/app/node_modules/bluebird/js/release/async.js:131:9)\n    at Async._drainQueues (/app/node_modules/bluebird/js/release/async.js:147:5)\n    at Immediate.Async.drainQueues (/app/node_modules/bluebird/js/release/async.js:17:14)\n    at runCallback (timers.js:810:20)\n    at tryOnImmediate (timers.js:768:5)\n    at processImmediate [as _immediateCallback] (timers.js:745:5)",
peertube_1  |     "message": "value too long for type character varying(255)",
peertube_1  |     "name": "SequelizeDatabaseError",
peertube_1  |     "parent": {
peertube_1  |       "stack": "error: value too long for type character varying(255)\n    at Connection.parseE (/app/node_modules/pg/lib/connection.js:554:11)\n    at Connection.parseMessage (/app/node_modules/pg/lib/connection.js:379:19)\n    at Socket.<anonymous> (/app/node_modules/pg/lib/connection.js:119:22)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at addChunk (_stream_readable.js:263:12)\n    at readableAddChunk (_stream_readable.js:250:11)\n    at Socket.Readable.push (_stream_readable.js:208:10)\n    at TCP.onread (net.js:601:20)",
peertube_1  |       "message": "value too long for type character varying(255)",
peertube_1  |       "name": "error",
peertube_1  |       "length": 654,
peertube_1  |       "severity": "ERROR",
peertube_1  |       "code": "22001",
peertube_1  |       "where": "SQL statement \"INSERT INTO \"account\" (\"id\",\"name\",\"description\",\"actorId\",\"createdAt\",\"updatedAt\") VALUES (DEFAULT,'techknowlogick','<p>Purveyor of artisanal <a href=\"https://mastodon.social/tags/pixelfed\" class=\"mention hashtag\" rel=\"tag\">#<span>PixelFed</span></a> hosting, and member of <a href=\"https://mastodon.social/tags/gitea\" class=\"mention hashtag\" rel=\"tag\">#<span>Gitea</span></a> dev team.</p>',11,'2019-04-30 19:05:27.375 +00:00','2019-04-30 19:05:27.375 +00:00') RETURNING *\"\nPL/pgSQL function pg_temp_5.testfunc() line 1 at SQL statement",
peertube_1  |       "file": "varchar.c",
peertube_1  |       "line": "624",
peertube_1  |       "routine": "varchar",
peertube_1  |       "sql": "CREATE OR REPLACE FUNCTION pg_temp.testfunc(OUT response \"account\", OUT sequelize_caught_exception text) RETURNS RECORD AS $func_b3c57365c9254d149d0d8bbb55dea579$ BEGIN INSERT INTO \"account\" (\"id\",\"name\",\"description\",\"actorId\",\"createdAt\",\"updatedAt\") VALUES (DEFAULT,'techknowlogick','<p>Purveyor of artisanal <a href=\"https://mastodon.social/tags/pixelfed\" class=\"mention hashtag\" rel=\"tag\">#<span>PixelFed</span></a> hosting, and member of <a href=\"https://mastodon.social/tags/gitea\" class=\"mention hashtag\" rel=\"tag\">#<span>Gitea</span></a> dev team.</p>',11,'2019-04-30 19:05:27.375 +00:00','2019-04-30 19:05:27.375 +00:00') RETURNING * INTO response; EXCEPTION WHEN unique_violation THEN GET STACKED DIAGNOSTICS sequelize_caught_exception = PG_EXCEPTION_DETAIL; END $func_b3c57365c9254d149d0d8bbb55dea579$ LANGUAGE plpgsql; SELECT (testfunc.response).*, testfunc.sequelize_caught_exception FROM pg_temp.testfunc(); DROP FUNCTION IF EXISTS pg_temp.testfunc();"
peertube_1  |     },
peertube_1  |     "original": {
peertube_1  |       "stack": "error: value too long for type character varying(255)\n    at Connection.parseE (/app/node_modules/pg/lib/connection.js:554:11)\n    at Connection.parseMessage (/app/node_modules/pg/lib/connection.js:379:19)\n    at Socket.<anonymous> (/app/node_modules/pg/lib/connection.js:119:22)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at addChunk (_stream_readable.js:263:12)\n    at readableAddChunk (_stream_readable.js:250:11)\n    at Socket.Readable.push (_stream_readable.js:208:10)\n    at TCP.onread (net.js:601:20)",
peertube_1  |       "message": "value too long for type character varying(255)",
peertube_1  |       "name": "error",
peertube_1  |       "length": 654,
peertube_1  |       "severity": "ERROR",
peertube_1  |       "code": "22001",
peertube_1  |       "where": "SQL statement \"INSERT INTO \"account\" (\"id\",\"name\",\"description\",\"actorId\",\"createdAt\",\"updatedAt\") VALUES (DEFAULT,'techknowlogick','<p>Purveyor of artisanal <a href=\"https://mastodon.social/tags/pixelfed\" class=\"mention hashtag\" rel=\"tag\">#<span>PixelFed</span></a> hosting, and member of <a href=\"https://mastodon.social/tags/gitea\" class=\"mention hashtag\" rel=\"tag\">#<span>Gitea</span></a> dev team.</p>',11,'2019-04-30 19:05:27.375 +00:00','2019-04-30 19:05:27.375 +00:00') RETURNING *\"\nPL/pgSQL function pg_temp_5.testfunc() line 1 at SQL statement",
peertube_1  |       "file": "varchar.c",
peertube_1  |       "line": "624",
peertube_1  |       "routine": "varchar",
peertube_1  |       "sql": "CREATE OR REPLACE FUNCTION pg_temp.testfunc(OUT response \"account\", OUT sequelize_caught_exception text) RETURNS RECORD AS $func_b3c57365c9254d149d0d8bbb55dea579$ BEGIN INSERT INTO \"account\" (\"id\",\"name\",\"description\",\"actorId\",\"createdAt\",\"updatedAt\") VALUES (DEFAULT,'techknowlogick','<p>Purveyor of artisanal <a href=\"https://mastodon.social/tags/pixelfed\" class=\"mention hashtag\" rel=\"tag\">#<span>PixelFed</span></a> hosting, and member of <a href=\"https://mastodon.social/tags/gitea\" class=\"mention hashtag\" rel=\"tag\">#<span>Gitea</span></a> dev team.</p>',11,'2019-04-30 19:05:27.375 +00:00','2019-04-30 19:05:27.375 +00:00') RETURNING * INTO response; EXCEPTION WHEN unique_violation THEN GET STACKED DIAGNOSTICS sequelize_caught_exception = PG_EXCEPTION_DETAIL; END $func_b3c57365c9254d149d0d8bbb55dea579$ LANGUAGE plpgsql; SELECT (testfunc.response).*, testfunc.sequelize_caught_exception FROM pg_temp.testfunc(); DROP FUNCTION IF EXISTS pg_temp.testfunc();"
peertube_1  |     },
peertube_1  |     "sql": "CREATE OR REPLACE FUNCTION pg_temp.testfunc(OUT response \"account\", OUT sequelize_caught_exception text) RETURNS RECORD AS $func_b3c57365c9254d149d0d8bbb55dea579$ BEGIN INSERT INTO \"account\" (\"id\",\"name\",\"description\",\"actorId\",\"createdAt\",\"updatedAt\") VALUES (DEFAULT,'techknowlogick','<p>Purveyor of artisanal <a href=\"https://mastodon.social/tags/pixelfed\" class=\"mention hashtag\" rel=\"tag\">#<span>PixelFed</span></a> hosting, and member of <a href=\"https://mastodon.social/tags/gitea\" class=\"mention hashtag\" rel=\"tag\">#<span>Gitea</span></a> dev team.</p>',11,'2019-04-30 19:05:27.375 +00:00','2019-04-30 19:05:27.375 +00:00') RETURNING * INTO response; EXCEPTION WHEN unique_violation THEN GET STACKED DIAGNOSTICS sequelize_caught_exception = PG_EXCEPTION_DETAIL; END $func_b3c57365c9254d149d0d8bbb55dea579$ LANGUAGE plpgsql; SELECT (testfunc.response).*, testfunc.sequelize_caught_exception FROM pg_temp.testfunc(); DROP FUNCTION IF EXISTS pg_temp.testfunc();"
peertube_1  |   }
peertube_1  | }
peertube_1  | [play.jergefelt.se:443] 2019-04-30 19:05:27.386 error: Error in ActivityPub signature checker. {
peertube_1  |   "meta": {
peertube_1  |     "stack": "SequelizeDatabaseError: value too long for type character varying(255)\n    at Query.formatError (/app/node_modules/sequelize/lib/dialects/postgres/query.js:363:16)\n    at query.catch.err (/app/node_modules/sequelize/lib/dialects/postgres/query.js:86:18)\n    at tryCatcher (/app/node_modules/bluebird/js/release/util.js:16:23)\n    at Promise._settlePromiseFromHandler (/app/node_modules/bluebird/js/release/promise.js:512:31)\n    at Promise._settlePromise (/app/node_modules/bluebird/js/release/promise.js:569:18)\n    at Promise._settlePromise0 (/app/node_modules/bluebird/js/release/promise.js:614:10)\n    at Promise._settlePromises (/app/node_modules/bluebird/js/release/promise.js:690:18)\n    at _drainQueueStep (/app/node_modules/bluebird/js/release/async.js:138:12)\n    at _drainQueue (/app/node_modules/bluebird/js/release/async.js:131:9)\n    at Async._drainQueues (/app/node_modules/bluebird/js/release/async.js:147:5)\n    at Immediate.Async.drainQueues (/app/node_modules/bluebird/js/release/async.js:17:14)\n    at runCallback (timers.js:810:20)\n    at tryOnImmediate (timers.js:768:5)\n    at processImmediate [as _immediateCallback] (timers.js:745:5)",
peertube_1  |     "message": "value too long for type character varying(255)",
peertube_1  |     "name": "SequelizeDatabaseError",
peertube_1  |     "parent": {
peertube_1  |       "stack": "error: value too long for type character varying(255)\n    at Connection.parseE (/app/node_modules/pg/lib/connection.js:554:11)\n    at Connection.parseMessage (/app/node_modules/pg/lib/connection.js:379:19)\n    at Socket.<anonymous> (/app/node_modules/pg/lib/connection.js:119:22)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at addChunk (_stream_readable.js:263:12)\n    at readableAddChunk (_stream_readable.js:250:11)\n    at Socket.Readable.push (_stream_readable.js:208:10)\n    at TCP.onread (net.js:601:20)",
peertube_1  |       "message": "value too long for type character varying(255)",
peertube_1  |       "name": "error",
peertube_1  |       "length": 654,
peertube_1  |       "severity": "ERROR",
peertube_1  |       "code": "22001",
peertube_1  |       "where": "SQL statement \"INSERT INTO \"account\" (\"id\",\"name\",\"description\",\"actorId\",\"createdAt\",\"updatedAt\") VALUES (DEFAULT,'techknowlogick','<p>Purveyor of artisanal <a href=\"https://mastodon.social/tags/pixelfed\" class=\"mention hashtag\" rel=\"tag\">#<span>PixelFed</span></a> hosting, and member of <a href=\"https://mastodon.social/tags/gitea\" class=\"mention hashtag\" rel=\"tag\">#<span>Gitea</span></a> dev team.</p>',11,'2019-04-30 19:05:27.375 +00:00','2019-04-30 19:05:27.375 +00:00') RETURNING *\"\nPL/pgSQL function pg_temp_5.testfunc() line 1 at SQL statement",
peertube_1  |       "file": "varchar.c",
peertube_1  |       "line": "624",
peertube_1  |       "routine": "varchar",
peertube_1  |       "sql": "CREATE OR REPLACE FUNCTION pg_temp.testfunc(OUT response \"account\", OUT sequelize_caught_exception text) RETURNS RECORD AS $func_b3c57365c9254d149d0d8bbb55dea579$ BEGIN INSERT INTO \"account\" (\"id\",\"name\",\"description\",\"actorId\",\"createdAt\",\"updatedAt\") VALUES (DEFAULT,'techknowlogick','<p>Purveyor of artisanal <a href=\"https://mastodon.social/tags/pixelfed\" class=\"mention hashtag\" rel=\"tag\">#<span>PixelFed</span></a> hosting, and member of <a href=\"https://mastodon.social/tags/gitea\" class=\"mention hashtag\" rel=\"tag\">#<span>Gitea</span></a> dev team.</p>',11,'2019-04-30 19:05:27.375 +00:00','2019-04-30 19:05:27.375 +00:00') RETURNING * INTO response; EXCEPTION WHEN unique_violation THEN GET STACKED DIAGNOSTICS sequelize_caught_exception = PG_EXCEPTION_DETAIL; END $func_b3c57365c9254d149d0d8bbb55dea579$ LANGUAGE plpgsql; SELECT (testfunc.response).*, testfunc.sequelize_caught_exception FROM pg_temp.testfunc(); DROP FUNCTION IF EXISTS pg_temp.testfunc();"
peertube_1  |     },
peertube_1  |     "original": {
peertube_1  |       "stack": "error: value too long for type character varying(255)\n    at Connection.parseE (/app/node_modules/pg/lib/connection.js:554:11)\n    at Connection.parseMessage (/app/node_modules/pg/lib/connection.js:379:19)\n    at Socket.<anonymous> (/app/node_modules/pg/lib/connection.js:119:22)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at addChunk (_stream_readable.js:263:12)\n    at readableAddChunk (_stream_readable.js:250:11)\n    at Socket.Readable.push (_stream_readable.js:208:10)\n    at TCP.onread (net.js:601:20)",
peertube_1  |       "message": "value too long for type character varying(255)",
peertube_1  |       "name": "error",
peertube_1  |       "length": 654,
peertube_1  |       "severity": "ERROR",
peertube_1  |       "code": "22001",
peertube_1  |       "where": "SQL statement \"INSERT INTO \"account\" (\"id\",\"name\",\"description\",\"actorId\",\"createdAt\",\"updatedAt\") VALUES (DEFAULT,'techknowlogick','<p>Purveyor of artisanal <a href=\"https://mastodon.social/tags/pixelfed\" class=\"mention hashtag\" rel=\"tag\">#<span>PixelFed</span></a> hosting, and member of <a href=\"https://mastodon.social/tags/gitea\" class=\"mention hashtag\" rel=\"tag\">#<span>Gitea</span></a> dev team.</p>',11,'2019-04-30 19:05:27.375 +00:00','2019-04-30 19:05:27.375 +00:00') RETURNING *\"\nPL/pgSQL function pg_temp_5.testfunc() line 1 at SQL statement",
peertube_1  |       "file": "varchar.c",
peertube_1  |       "line": "624",
peertube_1  |       "routine": "varchar",
peertube_1  |       "sql": "CREATE OR REPLACE FUNCTION pg_temp.testfunc(OUT response \"account\", OUT sequelize_caught_exception text) RETURNS RECORD AS $func_b3c57365c9254d149d0d8bbb55dea579$ BEGIN INSERT INTO \"account\" (\"id\",\"name\",\"description\",\"actorId\",\"createdAt\",\"updatedAt\") VALUES (DEFAULT,'techknowlogick','<p>Purveyor of artisanal <a href=\"https://mastodon.social/tags/pixelfed\" class=\"mention hashtag\" rel=\"tag\">#<span>PixelFed</span></a> hosting, and member of <a href=\"https://mastodon.social/tags/gitea\" class=\"mention hashtag\" rel=\"tag\">#<span>Gitea</span></a> dev team.</p>',11,'2019-04-30 19:05:27.375 +00:00','2019-04-30 19:05:27.375 +00:00') RETURNING * INTO response; EXCEPTION WHEN unique_violation THEN GET STACKED DIAGNOSTICS sequelize_caught_exception = PG_EXCEPTION_DETAIL; END $func_b3c57365c9254d149d0d8bbb55dea579$ LANGUAGE plpgsql; SELECT (testfunc.response).*, testfunc.sequelize_caught_exception FROM pg_temp.testfunc(); DROP FUNCTION IF EXISTS pg_temp.testfunc();"
peertube_1  |     },
peertube_1  |     "sql": "CREATE OR REPLACE FUNCTION pg_temp.testfunc(OUT response \"account\", OUT sequelize_caught_exception text) RETURNS RECORD AS $func_b3c57365c9254d149d0d8bbb55dea579$ BEGIN INSERT INTO \"account\" (\"id\",\"name\",\"description\",\"actorId\",\"createdAt\",\"updatedAt\") VALUES (DEFAULT,'techknowlogick','<p>Purveyor of artisanal <a href=\"https://mastodon.social/tags/pixelfed\" class=\"mention hashtag\" rel=\"tag\">#<span>PixelFed</span></a> hosting, and member of <a href=\"https://mastodon.social/tags/gitea\" class=\"mention hashtag\" rel=\"tag\">#<span>Gitea</span></a> dev team.</p>',11,'2019-04-30 19:05:27.375 +00:00','2019-04-30 19:05:27.375 +00:00') RETURNING * INTO response; EXCEPTION WHEN unique_violation THEN GET STACKED DIAGNOSTICS sequelize_caught_exception = PG_EXCEPTION_DETAIL; END $func_b3c57365c9254d149d0d8bbb55dea579$ LANGUAGE plpgsql; SELECT (testfunc.response).*, testfunc.sequelize_caught_exception FROM pg_temp.testfunc(); DROP FUNCTION IF EXISTS pg_temp.testfunc();"
peertube_1  |   },
peertube_1  |   "sql": "CREATE OR REPLACE FUNCTION pg_temp.testfunc(OUT response \"account\", OUT sequelize_caught_exception text) RETURNS RECORD AS $func_b3c57365c9254d149d0d8bbb55dea579$ BEGIN INSERT INTO \"account\" (\"id\",\"name\",\"description\",\"actorId\",\"createdAt\",\"updatedAt\") VALUES (DEFAULT,'techknowlogick','<p>Purveyor of artisanal <a href=\"https://mastodon.social/tags/pixelfed\" class=\"mention hashtag\" rel=\"tag\">#<span>PixelFed</span></a> hosting, and member of <a href=\"https://mastodon.social/tags/gitea\" class=\"mention hashtag\" rel=\"tag\">#<span>Gitea</span></a> dev team.</p>',11,'2019-04-30 19:05:27.375 +00:00','2019-04-30 19:05:27.375 +00:00') RETURNING * INTO response; EXCEPTION WHEN unique_violation THEN GET STACKED DIAGNOSTICS sequelize_caught_exception = PG_EXCEPTION_DETAIL; END $func_b3c57365c9254d149d0d8bbb55dea579$ LANGUAGE plpgsql; SELECT (testfunc.response).*, testfunc.sequelize_caught_exception FROM pg_temp.testfunc(); DROP FUNCTION IF EXISTS pg_temp.testfunc();"
peertube_1  | }
```

**Comment by Tr4sK** [comment]
Hey, I drop my [issue](https://github.com/Chocobozzz/PeerTube/issues/1796) here as it has been close for duplicate reason 
On my instance, I’m having a lot of failed job from 'activitypub-refresher'
Here is some failing account:
```
{
  "type": "actor",
  "url": "https://video.tedomum.net/accounts/nofear75"
}
```
```
{
  "type": "actor",
  "url": "https://peertube.social/accounts/fribbledom"
}
```
```
{
  "type": "actor",
  "url": "https://www.yiny.org/accounts/shore"
}
```

The full message here:

```
SequelizeDatabaseError: value too long for type character varying(255)
    at Query.formatError (/var/www/peertube/versions/peertube-v1.2.1/node_modules/sequelize/lib/dialects/postgres/query.js:363:16)
    at query.catch.err (/var/www/peertube/versions/peertube-v1.2.1/node_modules/sequelize/lib/dialects/postgres/query.js:86:18)
    at tryCatcher (/var/www/peertube/versions/peertube-v1.2.1/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/var/www/peertube/versions/peertube-v1.2.1/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/var/www/peertube/versions/peertube-v1.2.1/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/var/www/peertube/versions/peertube-v1.2.1/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/var/www/peertube/versions/peertube-v1.2.1/node_modules/bluebird/js/release/promise.js:690:18)
    at _drainQueueStep (/var/www/peertube/versions/peertube-v1.2.1/node_modules/bluebird/js/release/async.js:138:12)
    at _drainQueue (/var/www/peertube/versions/peertube-v1.2.1/node_modules/bluebird/js/release/async.js:131:9)
    at Async._drainQueues (/var/www/peertube/versions/peertube-v1.2.1/node_modules/bluebird/js/release/async.js:147:5)
    at Immediate.Async.drainQueues (/var/www/peertube/versions/peertube-v1.2.1/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:810:20)
    at tryOnImmediate (timers.js:768:5)
    at processImmediate [as _immediateCallback] (timers.js:745:5)
```

**Additional information**
* PeerTube version or URL: https://tube.tr4sk.me
* NodeJS version: v8.15.1

My guess is that the description field is not properly managed on my instance:

Original: https://video.tedomum.net/accounts/nofear75/about
What I see from my instance: https://tube.tr4sk.me/accounts/nofear75@video.tedomum.net/about

**Comment by Chocobozzz** [comment]
Thanks. I hope it will be fixed by https://github.com/Chocobozzz/PeerTube/commit/3db9fadca78ad1a59f92cb4abc37d63f517a073b & https://github.com/Chocobozzz/PeerTube/commit/241c3357d13ac2fb4c8ffca6469e575388c1fac5
