### ISSUE TITLE
[Crash] Cannot read property 'isOwned' of undefined

### ISSUE THREAD

**Issue by anoadragon453** [Chocobozzz/PeerTube#1852]
**What happened?**

Server crashed with the following logs:

```
2019-05-27 06:29:30.057 error: uncaughtException: Cannot read property 'isOwned' of undefined
TypeError: Cannot read property 'isOwned' of undefined
    at dispose (/var/www/peertube/versions/peertube-v1.3.0-rc.1/dist/server/lib/files-cache/abstract-video-static-file-cache.js:13:28)
    at Object.del (/var/www/peertube/versions/peertube-v1.3.0-rc.1/node_modules/memoizee/ext/dispose.js:16:10)
    at Object.emit (/var/www/peertube/versions/peertube-v1.3.0-rc.1/node_modules/event-emitter/index.js:89:10)
    at Object.<anonymous> (/var/www/peertube/versions/peertube-v1.3.0-rc.1/node_modules/memoizee/ext/promise.js:136:8)
    at Object.emit (/var/www/peertube/versions/peertube-v1.3.0-rc.1/node_modules/event-emitter/index.js:100:9)
    at Object.delete (/var/www/peertube/versions/peertube-v1.3.0-rc.1/node_modules/memoizee/lib/configure-map.js:124:30)
    at Timeout.<anonymous> (/var/www/peertube/versions/peertube-v1.3.0-rc.1/node_modules/memoizee/ext/max-age.js:28:54)
    at ontimeout (timers.js:466:11)
    at Timer.unrefdHandle (timers.js:578:5) {
  "error": {
    "stack": "TypeError: Cannot read property 'isOwned' of undefined\n    at dispose (/var/www/peertube/versions/peertube-v1.3.0-rc.1/dist/server/lib/files-cache/abstract-video-static-file-cache.js:13:28)\n    at
 Object.del (/var/www/peertube/versions/peertube-v1.3.0-rc.1/node_modules/memoizee/ext/dispose.js:16:10)\n    at Object.emit (/var/www/peertube/versions/peertube-v1.3.0-rc.1/node_modules/event-emitter/index.js:89
:10)\n    at Object.<anonymous> (/var/www/peertube/versions/peertube-v1.3.0-rc.1/node_modules/memoizee/ext/promise.js:136:8)\n    at Object.emit (/var/www/peertube/versions/peertube-v1.3.0-rc.1/node_modules/event
-emitter/index.js:100:9)\n    at Object.delete (/var/www/peertube/versions/peertube-v1.3.0-rc.1/node_modules/memoizee/lib/configure-map.js:124:30)\n    at Timeout.<anonymous> (/var/www/peertube/versions/peertube-
v1.3.0-rc.1/node_modules/memoizee/ext/max-age.js:28:54)\n    at ontimeout (timers.js:466:11)\n    at Timer.unrefdHandle (timers.js:578:5)",
    "message": "Cannot read property 'isOwned' of undefined"
  },
  "stack": "TypeError: Cannot read property 'isOwned' of undefined\n    at dispose (/var/www/peertube/versions/peertube-v1.3.0-rc.1/dist/server/lib/files-cache/abstract-video-static-file-cache.js:13:28)\n    at O
bject.del (/var/www/peertube/versions/peertube-v1.3.0-rc.1/node_modules/memoizee/ext/dispose.js:16:10)\n    at Object.emit (/var/www/peertube/versions/peertube-v1.3.0-rc.1/node_modules/event-emitter/index.js:89:1
0)\n    at Object.<anonymous> (/var/www/peertube/versions/peertube-v1.3.0-rc.1/node_modules/memoizee/ext/promise.js:136:8)\n    at Object.emit (/var/www/peertube/versions/peertube-v1.3.0-rc.1/node_modules/event-e
mitter/index.js:100:9)\n    at Object.delete (/var/www/peertube/versions/peertube-v1.3.0-rc.1/node_modules/memoizee/lib/configure-map.js:124:30)\n    at Timeout.<anonymous> (/var/www/peertube/versions/peertube-v1
.3.0-rc.1/node_modules/memoizee/ext/max-age.js:28:54)\n    at ontimeout (timers.js:466:11)\n    at Timer.unrefdHandle (timers.js:578:5)",
  "exception": true,
  "date": "Mon May 27 2019 06:29:30 GMT+0200 (CEST)",
  "process": {
    "pid": 16240,
    "uid": 0,
    "gid": 0,
    "cwd": "/var/www/peertube/versions/peertube-v1.3.0-rc.1",
    "execPath": "/usr/bin/node",
    "version": "v9.11.2",
    "argv": [
      "/usr/bin/node",
      "/var/www/peertube/versions/peertube-v1.3.0-rc.1/dist/server"
    ],
    "memoryUsage": {
      "rss": 166416384,
      "heapTotal": 92532736,
      "heapUsed": 74745080,
      "external": 616651
    }
  },
  "os": {
    "loadavg": [
      0.91796875,
      1.12060546875,
      1.1748046875
    ],
    "uptime": 5580006
  },
  "trace": [
    {
      "column": 28,
      "file": "/var/www/peertube/versions/peertube-v1.3.0-rc.1/dist/server/lib/files-cache/abstract-video-static-file-cache.js",
      "function": "dispose",
      "line": 13,
      "method": null,
      "native": false
    },
    {
      "column": 10,
      "file": "/var/www/peertube/versions/peertube-v1.3.0-rc.1/node_modules/memoizee/ext/dispose.js",
      "function": "Object.del",
      "line": 16,
      "method": "del",
      "native": false
    },
    {
      "column": 10,
      "file": "/var/www/peertube/versions/peertube-v1.3.0-rc.1/node_modules/event-emitter/index.js",
      "function": "Object.emit",
      "line": 89,
      "method": "emit",
      "native": false
    },
    {
      "column": 8,
      "file": "/var/www/peertube/versions/peertube-v1.3.0-rc.1/node_modules/memoizee/ext/promise.js",
      "function": null,
      "line": 136,
      "method": null,
      "native": false
    },
    {
      "column": 9,
      "file": "/var/www/peertube/versions/peertube-v1.3.0-rc.1/node_modules/event-emitter/index.js",
      "function": "Object.emit",
      "line": 100,
      "method": "emit",
      "native": false
    },
    {
      "column": 30,
      "file": "/var/www/peertube/versions/peertube-v1.3.0-rc.1/node_modules/memoizee/lib/configure-map.js",
      "function": "Object.delete",
      "line": 124,
      "method": "delete",
      "native": false
    },
    {
      "column": 54,
      "file": "/var/www/peertube/versions/peertube-v1.3.0-rc.1/node_modules/memoizee/ext/max-age.js",
      "function": null,
      "line": 28,
      "method": null,
      "native": false
    },
    {
      "column": 11,
      "file": "timers.js",
      "function": "ontimeout",
      "line": 466,
      "method": null,
      "native": false
    },
    {
      "column": 5,
      "file": "timers.js",
      "function": "Timer.unrefdHandle",
      "line": 578,
      "method": "unrefdHandle",
      "native": false
    }
  ]
}
[vault.mle.party:443] 2019-05-27 06:29:30.888 error: uncaughtException: Cannot read property 'isOwned' of undefined
TypeError: Cannot read property 'isOwned' of undefined
    at dispose (/var/www/peertube/versions/peertube-v1.3.0-rc.1/dist/server/lib/files-cache/abstract-video-static-file-cache.js:13:28)
    at Object.del (/var/www/peertube/versions/peertube-v1.3.0-rc.1/node_modules/memoizee/ext/dispose.js:16:10)
    at Object.emit (/var/www/peertube/versions/peertube-v1.3.0-rc.1/node_modules/event-emitter/index.js:89:10)
    at Object.<anonymous> (/var/www/peertube/versions/peertube-v1.3.0-rc.1/node_modules/memoizee/ext/promise.js:136:8)
    at Object.emit (/var/www/peertube/versions/peertube-v1.3.0-rc.1/node_modules/event-emitter/index.js:100:9)
    at Object.delete (/var/www/peertube/versions/peertube-v1.3.0-rc.1/node_modules/memoizee/lib/configure-map.js:124:30)
    at Timeout.<anonymous> (/var/www/peertube/versions/peertube-v1.3.0-rc.1/node_modules/memoizee/ext/max-age.js:28:54)
    at ontimeout (timers.js:466:11)
    at Timer.unrefdHandle (timers.js:578:5) {
  "error": {
    "stack": "TypeError: Cannot read property 'isOwned' of undefined\n    at dispose (/var/www/peertube/versions/peertube-v1.3.0-rc.1/dist/server/lib/files-cache/abstract-video-static-file-cache.js:13:28)\n    a$
 Object.del (/var/www/peertube/versions/peertube-v1.3.0-rc.1/node_modules/memoizee/ext/dispose.js:16:10)\n    at Object.emit (/var/www/peertube/versions/peertube-v1.3.0-rc.1/node_modules/event-emitter/index.js:8$
:10)\n    at Object.<anonymous> (/var/www/peertube/versions/peertube-v1.3.0-rc.1/node_modules/memoizee/ext/promise.js:136:8)\n    at Object.emit (/var/www/peertube/versions/peertube-v1.3.0-rc.1/node_modules/even$
-emitter/index.js:100:9)\n    at Object.delete (/var/www/peertube/versions/peertube-v1.3.0-rc.1/node_modules/memoizee/lib/configure-map.js:124:30)\n    at Timeout.<anonymous> (/var/www/peertube/versions/peertube$
v1.3.0-rc.1/node_modules/memoizee/ext/max-age.js:28:54)\n    at ontimeout (timers.js:466:11)\n    at Timer.unrefdHandle (timers.js:578:5)",
    "message": "Cannot read property 'isOwned' of undefined"
  },
  "stack": "TypeError: Cannot read property 'isOwned' of undefined\n    at dispose (/var/www/peertube/versions/peertube-v1.3.0-rc.1/dist/server/lib/files-cache/abstract-video-static-file-cache.js:13:28)\n    at $
bject.del (/var/www/peertube/versions/peertube-v1.3.0-rc.1/node_modules/memoizee/ext/dispose.js:16:10)\n    at Object.emit (/var/www/peertube/versions/peertube-v1.3.0-rc.1/node_modules/event-emitter/index.js:89:$
0)\n    at Object.<anonymous> (/var/www/peertube/versions/peertube-v1.3.0-rc.1/node_modules/memoizee/ext/promise.js:136:8)\n    at Object.emit (/var/www/peertube/versions/peertube-v1.3.0-rc.1/node_modules/event-$
mitter/index.js:100:9)\n    at Object.delete (/var/www/peertube/versions/peertube-v1.3.0-rc.1/node_modules/memoizee/lib/configure-map.js:124:30)\n    at Timeout.<anonymous> (/var/www/peertube/versions/peertube-v$
.3.0-rc.1/node_modules/memoizee/ext/max-age.js:28:54)\n    at ontimeout (timers.js:466:11)\n    at Timer.unrefdHandle (timers.js:578:5)",
  "exception": true,
  "date": "Mon May 27 2019 06:29:30 GMT+0200 (CEST)",
  "process": {                                                                                                                                                                                             [72/1816]
    "pid": 16240,
    "uid": 0,
    "gid": 0,
    "cwd": "/var/www/peertube/versions/peertube-v1.3.0-rc.1",
    "execPath": "/usr/bin/node",
    "version": "v9.11.2",
    "argv": [
      "/usr/bin/node",
      "/var/www/peertube/versions/peertube-v1.3.0-rc.1/dist/server"
    ],
    "memoryUsage": {
      "rss": 167116800,
      "heapTotal": 93057024,
      "heapUsed": 74345216,
      "external": 620999
    }
  },
  "os": {
    "loadavg": [
      0.91796875,
      1.12060546875,
      1.1748046875
    ],
    "uptime": 5580007
  },
  "trace": [
    {
      "column": 28,
      "file": "/var/www/peertube/versions/peertube-v1.3.0-rc.1/dist/server/lib/files-cache/abstract-video-static-file-cache.js",
      "function": "dispose",
      "line": 13,
      "method": null,
      "native": false
    },
    {
      "column": 10,
      "file": "/var/www/peertube/versions/peertube-v1.3.0-rc.1/node_modules/memoizee/ext/dispose.js",
      "function": "Object.del",
      "line": 16,
      "method": "del",
      "native": false
    },
    {
      "column": 10,
      "file": "/var/www/peertube/versions/peertube-v1.3.0-rc.1/node_modules/event-emitter/index.js",
      "function": "Object.emit",
      "line": 89,
      "method": "emit",
      "native": false
    },
    {
      "column": 8,
      "file": "/var/www/peertube/versions/peertube-v1.3.0-rc.1/node_modules/memoizee/ext/promise.js",
      "function": null,
      "line": 136,
      "method": null,
      "native": false
    },
    {
      "column": 9,
      "file": "/var/www/peertube/versions/peertube-v1.3.0-rc.1/node_modules/event-emitter/index.js",
      "function": "Object.emit",
      "line": 100,
      "method": "emit",
      "native": false
    },
    {
      "column": 30,
      "file": "/var/www/peertube/versions/peertube-v1.3.0-rc.1/node_modules/memoizee/lib/configure-map.js",
      "function": "Object.delete",
      "line": 124,
      "method": "delete",
      "native": false
    },
    {
      "column": 54,
      "file": "/var/www/peertube/versions/peertube-v1.3.0-rc.1/node_modules/memoizee/ext/max-age.js",
      "function": null,
      "line": 28,
      "method": null,
      "native": false
    },
      "method": "delete",                                                                                                                                                                                   [0/1816]
      "native": false
    },
    {
      "column": 54,
      "file": "/var/www/peertube/versions/peertube-v1.3.0-rc.1/node_modules/memoizee/ext/max-age.js",
      "function": null,
      "line": 28,
      "method": null,
      "native": false
    },
    {
      "column": 11,
      "file": "timers.js",
      "function": "ontimeout",
      "line": 466,
      "method": null,
      "native": false
    },
    {
      "column": 5,
      "file": "timers.js",
      "function": "Timer.unrefdHandle",
      "line": 578,
      "method": "unrefdHandle",
      "native": false
    }
  ]
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! peertube@1.3.0-rc.1 start: `node dist/server`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the peertube@1.3.0-rc.1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

**What do you expect to happen instead?**

The server not crashing.

**Additional information**

It ran for a couple hours and then crashed.

* PeerTube version or URL: v1.3.0-rc-1
* NodeJS version: v9.11.2

**Comment by Chocobozzz** [comment]
Thanks @anoadragon453, it should be fixed by https://github.com/Chocobozzz/PeerTube/commit/ff0bce13592da002a836caedf8daebcdd035260c
