### ISSUE TITLE
Error: Configuration property "email.body.signature" is not defined

### ISSUE THREAD

**Issue by swdee** [Chocobozzz/PeerTube#1875]
Using develop branch we get the error on npm start;
```
> peertube@1.3.0 start /home/peertube/versions/develop
> node dist/server

/home/peertube/versions/develop/node_modules/config/lib/config.js:203
    throw new Error('Configuration property "' + property + '" is not defined');
    ^

Error: Configuration property "email.body.signature" is not defined
    at Config.get (/home/peertube/versions/develop/node_modules/config/lib/config.js:203:11)
    at Object.<anonymous> (/home/peertube/versions/develop/dist/server/initializers/config.js:43:31)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/home/peertube/versions/develop/dist/server/helpers/logger.js:6:18)
```

This is due to merged https://github.com/Chocobozzz/PeerTube/pull/1789 that introduced the following new config fields;
```
email:
  body:
    signature: "PeerTube"
  object:
    prefix: "[PeerTube]"
```

These default fields were added to  config/default.yaml at
 https://github.com/Chocobozzz/PeerTube/pull/1789/files#diff-fe7044f2ecd69c76ce484ad03fabc12f but also need to be added to config/production.yaml.example so when someone following the installation instructions by copying the production example file it will have these new `email` config fields and avoid the above error.

**Comment by Chocobozzz** [comment]
Thanks for the issue @swdee 

Should be fixed by https://github.com/Chocobozzz/PeerTube/commit/dd2c2a52ccd07bcb2317dcc6ce45a2291e6bad62
