### ISSUE TITLE
Peertube Upload CLI not working.

### ISSUE THREAD

**Issue by shirshak55** [Chocobozzz/PeerTube#1882]
I ran peertube command
```
peertube auth add -u 'IP' -U 'username' --password 'realPassword' --default
```

And this is the output. I tried uploading test mp4 file `/home/desktop/test/VfE_html5.mp4`

And it gives error.

```
asd: peertube up /home/desktop/test/VfE_html5.mp4
(node:15351) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'url.com' of undefined
    at Object.getRemoteObjectOrDie (/home/desktop/PeerTube/dist/server/tools/cli.js:67:38)
    at cli_1.getSettings.then.settings (/home/desktop/PeerTube/dist/server/tools/peertube-upload.js:39:47)
    at <anonymous>
(node:15351) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:15351) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

url.com (in above error message) belongs to my real peertube url.

Hmm seems like it is code issue right?

It is using nodev8 and everything before this step seems to be done properly :)

**Comment by shirshak55** [comment]
@Chocobozzz let me know if u want something to me as recreating this issue is easy.

**Comment by Chocobozzz** [comment]
Thanks for the issue.

Should be fixed by https://github.com/Chocobozzz/PeerTube/commit/9f167f12aafbcdda2e2cd2f436ff996ea41986ba

**Comment by shirshak55** [comment]
thanks again.
