### ISSUE TITLE
Run tslint locally

### ISSUE THREAD

**Issue by NassimBounouas** [Chocobozzz/PeerTube#1883]
**What happened?**

I submitted a PR that has been rejeted by the tslint travis test. I fixed the different errors then I tried to run the ts lint. The output is different from the one provided by travis.  On the same code base travis result is [this one](https://travis-ci.org/Chocobozzz/PeerTube/jobs/543266314) and when I'm running `tslint "--project" "./tsconfig.json" "-c" "./tslint.json" "server.ts" "server/**/*.ts" "shared/**/*.ts"` locally the output is this one :

```
strict-type-predicates does not work without --strictNullChecks
The 'no-multi-spaces' rule threw an error in '/home/user/dev/PeerTube/server/helpers/core-utils.ts':
TypeError: Cannot read property 'kind' of undefined
    at NoMultiSpacesWalker.warn (/home/user/dev/PeerTube/node_modules/tslint-eslint-rules/dist/rules/noMultiSpacesRule.js:71:25)
    at /home/user/dev/PeerTube/node_modules/tslint-eslint-rules/dist/rules/noMultiSpacesRule.js:99:27
    at Array.forEach (<anonymous>)
    at NoMultiSpacesWalker.walkChildren (/home/user/dev/PeerTube/node_modules/tslint-eslint-rules/dist/rules/noMultiSpacesRule.js:96:26)
    at NoMultiSpacesWalker.SyntaxWalker.visitEndOfFileToken (/home/user/dev/PeerTube/node_modules/tslint/lib/language/walker/syntaxWalker.js:99:14)
    at NoMultiSpacesWalker.SyntaxWalker.visitNode (/home/user/dev/PeerTube/node_modules/tslint/lib/language/walker/syntaxWalker.js:350:22)
    at NoMultiSpacesWalker.walkChildren (/home/user/dev/PeerTube/node_modules/tslint-eslint-rules/dist/rules/noMultiSpacesRule.js:113:18)
    at NoMultiSpacesWalker.SyntaxWalker.visitNode (/home/user/dev/PeerTube/node_modules/tslint/lib/language/walker/syntaxWalker.js:530:22)
    at NoMultiSpacesWalker.SyntaxWalker.walk (/home/user/dev/PeerTube/node_modules/tslint/lib/language/walker/syntaxWalker.js:24:14)
    at Rule.AbstractRule.applyWithWalker (/home/user/dev/PeerTube/node_modules/tslint/lib/language/rule/abstractRule.js:31:16)

ERROR: /home/user/dev/PeerTube/server/tests/api/check-params/video-playlists.ts:477:39 - Multiple spaces found before 'playlistId'.
ERROR: /home/user/dev/PeerTube/server/tests/api/videos/video-playlists.ts:757:1 - Consecutive blank lines are forbidden
```

How can I run a tslint test locally before pushing some code to avoid adding commits that only add tslint corrections ?

**Additional information**
* NodeJS version: v11.15.0 (Travis is running on node 8 - maybe it's a lead - EDIT : I tried node 8.16 : same result)

**Comment by Chocobozzz** [comment]
Try `npm run travis -- lint`

**Comment by Chocobozzz** [comment]
Or `npm run lint` with https://github.com/Chocobozzz/PeerTube/commit/4c7f7761362224bb19573faa485b16a40eab0bc4
