### ISSUE TITLE
Constant errors from non-followed instance in logs

### ISSUE THREAD

**Issue by popindavibe** [Chocobozzz/PeerTube#1925]
**What happened?**
Enabling info logs after upgrading to v1.3.1, I am getting recurring errors in the logs, from an instance that I do not follow (renamed `unknownpeer.net` below):
```
Jun 20 14:22:05 peertube[20115]: [peertube.example.com:443] 2019-06-20 14:22:05.809 error: Error in ActivityPub signature checker.Validation error {
Jun 20 14:22:05 peertube[20115]:   "name": "SequelizeUniqueConstraintError",
Jun 20 14:22:05 peertube[20115]:   "errors": [
Jun 20 14:22:05 peertube[20115]:     {
Jun 20 14:22:05 peertube[20115]:       "message": "uuid must be unique",
Jun 20 14:22:05 peertube[20115]:       "type": "unique violation",
Jun 20 14:22:05 peertube[20115]:       "path": "uuid",
Jun 20 14:22:05 peertube[20115]:       "value": "520db9c0-6bfa-4947-9ac0-a4dd0be6d5ed",
Jun 20 14:22:05 peertube[20115]:       "origin": "DB",
Jun 20 14:22:05 peertube[20115]:       "instance": {
Jun 20 14:22:05 peertube[20115]:         "id": null,
Jun 20 14:22:05 peertube[20115]:         "type": "Person",
Jun 20 14:22:05 peertube[20115]:         "uuid": "520db9c0-6bfa-4947-9ac0-a4dd0be6d5ed",
Jun 20 14:22:05 peertube[20115]:         "preferredUsername": "peertube",
Jun 20 14:22:05 peertube[20115]:         "url": "https://unknownpeer.net/accounts/peertube",
Jun 20 14:22:05 peertube[20115]:         "publicKey": "-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAzzUIUqw6myIW7C9ILWhy\nyC5QipXZS4lIDPCJecih6Y8H4+lWRb5Cu52gxopQLXux43QRXUeOzYqLX/h2lgkT\njKeC14ab9vSd/2YKAFP7CiYZE3ctw7QXkTBM4uvPrSYyZeY3snYGVSRHAPSVDh8+\nFfjumf7CrbV/zMN1iuKTb2Ekc7Puqp06KyDQMpkbnd9F8e4xDCX1Zopg7iQi7nH4\n2DGvsIE1WzouX6arZeXdjowzMAdZIijLB/RvxQlumTaN0qoJFPHcBH7OZ9VlKh98\nRWmclIc77FAO3JB8rhKYVDHk4OicyiGxcYdGCcBW+Cgu+DmJ6XThl0SG4njzWOm8\nKwIDAQAB\n-----END PUBLIC KEY-----",
Jun 20 14:22:05 peertube[20115]:         "privateKey": null,
Jun 20 14:22:05 peertube[20115]:         "followersCount": 18,
Jun 20 14:22:05 peertube[20115]:         "followingCount": 11,
Jun 20 14:22:05 peertube[20115]:         "inboxUrl": "https://unknownpeer.net/accounts/peertube/inbox",
Jun 20 14:22:05 peertube[20115]:         "outboxUrl": "https://unknownpeer.net/accounts/peertube/outbox",
Jun 20 14:22:05 peertube[20115]:         "sharedInboxUrl": "https://unknownpeer.net/inbox",
Jun 20 14:22:05 peertube[20115]:         "followersUrl": "https://unknownpeer.net/accounts/peertube/followers",
Jun 20 14:22:05 peertube[20115]:         "followingUrl": "https://unknownpeer.net/accounts/peertube/following",
Jun 20 14:22:05 peertube[20115]:         "serverId": 584,
Jun 20 14:22:05 peertube[20115]:         "updatedAt": "2019-06-20T13:22:05.806Z",
Jun 20 14:22:05 peertube[20115]:         "createdAt": "2019-06-20T13:22:05.806Z"
Jun 20 14:22:05 peertube[20115]:       },
Jun 20 14:22:05 peertube[20115]:       "validatorKey": "not_unique",
Jun 20 14:22:05 peertube[20115]:       "validatorName": null,
Jun 20 14:22:05 peertube[20115]:       "validatorArgs": []
Jun 20 14:22:05 peertube[20115]:     }
Jun 20 14:22:05 peertube[20115]:   ],
Jun 20 14:22:05 peertube[20115]:   "fields": {
Jun 20 14:22:05 peertube[20115]:     "uuid": "520db9c0-6bfa-4947-9ac0-a4dd0be6d5ed"
Jun 20 14:22:05 peertube[20115]:   },
Jun 20 14:22:05 peertube[20115]:   "parent": {
Jun 20 14:22:05 peertube[20115]:     "code": "23505",
Jun 20 14:22:05 peertube[20115]:     "detail": "Key (uuid)=(520db9c0-6bfa-4947-9ac0-a4dd0be6d5ed) already exists."
Jun 20 14:22:05 peertube[20115]:   },
Jun 20 14:22:05 peertube[20115]:   "original": {
Jun 20 14:22:05 peertube[20115]:     "code": "23505",
Jun 20 14:22:05 peertube[20115]:     "detail": "Key (uuid)=(520db9c0-6bfa-4947-9ac0-a4dd0be6d5ed) already exists."
Jun 20 14:22:05 peertube[20115]:   },
Jun 20 14:22:05 peertube[20115]:   "stack": "SequelizeUniqueConstraintError: Validation error\n    at Query.formatError (/var/www/peertube/versions/peertube-v1.3.1/node_modules/sequelize/lib/dialects/postgres/query.js:312:18)\n    at query.catch.then.queryResult (/var/www/peertube/versions/peertube-v1.3.1/node_modules/sequelize/lib/dialects/postgres/query.js:101:24)\n    at tryCatcher (/var/www/peertube/versions/peertube-v1.3.1/node_modules/bluebird/js/release/util.js:16:23)\n    at Promise._settlePromiseFromHandler (/var/www/peertube/versions/peertube-v1.3.1/node_modules/bluebird/js/release/promise.js:512:31)\n    at Promise._settlePromise (/var/www/peertube/versions/peertube-v1.3.1/node_modules/bluebird/js/release/promise.js:569:18)\n    at Promise._settlePromise0 (/var/www/peertube/versions/peertube-v1.3.1/node_modules/bluebird/js/release/promise.js:614:10)\n    at Promise._settlePromises (/var/www/peertube/versions/peertube-v1.3.1/node_modules/bluebird/js/release/promise.js:694:18)\n    at _drainQueueStep (/var/www/peertube/versions/peertube-v1.3.1/node_modules/bluebird/js/release/async.js:138:12)\n    at _drainQueue (/var/www/peertube/versions/peertube-v1.3.1/node_modules/bluebird/js/release/async.js:131:9)\n    at Async._drainQueues (/var/www/peertube/versions/peertube-v1.3.1/node_modules/bluebird/js/release/async.js:147:5)\n    at Immediate.Async.drainQueues (/var/www/peertube/versions/peertube-v1.3.1/node_modules/bluebird/js/release/async.js:17:14)\n    at runCallback (timers.js:810:20)\n    at tryOnImmediate (timers.js:768:5)\n    at processImmediate [as _immediateCallback] (timers.js:745:5)"
Jun 20 14:22:05 hibiscus peertube[20115]: }
```

**What do you expect to happen instead?**
Trying to understand what those error messages mean, and how they are relevant to my instance / if that can be fixed.

**Steps to reproduce:**
It keeps happening.

**Additional information**
* PeerTube version or URL: v1.3.1

* Link to browser console log if useful:
* Link to server log if useful (journalctl or /var/www/peertube/storage/logs/):

**Comment by Chocobozzz** [comment]
We removed the `uuid` field of actor table in develop, so I think you should not have this error anymore in the next peertube version.

**Comment by popindavibe** [comment]
Not sure why I am getting this in the first place, but will be happy to see it 'fixed'. Setting the logs back to warning allowed me to prevent filling up the logs with this error for now.
