### ISSUE TITLE
Config Error on First Startup

### ISSUE THREAD

**Issue by JonQuan4** [Chocobozzz/PeerTube#1931]
Tried installing latest version of PeerTube (1.31) onto an Arch Box server. UFW is enabled. When I try to start peertube I get this error:
```
Jun 21 10:51:05 archserver systemd[1]: Started PeerTube daemon.
Jun 21 10:51:06 archserver peertube[27504]: > peertube@1.3.1 start /var/www/peertube/versions/peertube-v1.3.1
Jun 21 10:51:06 archserver peertube[27504]: > node dist/server
Jun 21 10:51:06 archserver peertube[27504]: WARNING: NODE_ENV value of 'production' did not match any deployment config file names.
Jun 21 10:51:06 archserver peertube[27504]: WARNING: See https://github.com/lorenwest/node-config/wiki/Strict-Mode
Jun 21 10:51:06 archserver peertube[27504]: WARNING: No configurations found in configuration directory:/var/www/peertube/config
Jun 21 10:51:06 archserver peertube[27504]: WARNING: To disable this warning set SUPPRESS_NO_CONFIG_WARNING in the environment.
Jun 21 10:51:06 archserver peertube[27504]: /var/www/peertube/versions/peertube-v1.3.1/dist/server/initializers/config.js:211
Jun 21 10:51:06 archserver peertube[27504]:         throw new Error('Invalid config source.');
Jun 21 10:51:06 archserver peertube[27504]:         ^
Jun 21 10:51:06 archserver peertube[27504]: Error: Invalid config source.
Jun 21 10:51:06 archserver peertube[27504]:     at getLocalConfigFilePath (/var/www/peertube/versions/peertube-v1.3.1/dist/server/initializers/config.js:211:15)
Jun 21 10:51:06 archserver peertube[27504]:     at Object.<anonymous> (/var/www/peertube/versions/peertube-v1.3.1/dist/server/initializers/config.js:9:18)
Jun 21 10:51:06 archserver peertube[27504]:     at Module._compile (internal/modules/cjs/loader.js:776:30)
Jun 21 10:51:06 archserver peertube[27504]:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
Jun 21 10:51:06 archserver peertube[27504]:     at Module.load (internal/modules/cjs/loader.js:653:32)
Jun 21 10:51:06 archserver peertube[27504]:     at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
Jun 21 10:51:06 archserver peertube[27504]:     at Function.Module._load (internal/modules/cjs/loader.js:585:3)
Jun 21 10:51:06 archserver peertube[27504]:     at Module.require (internal/modules/cjs/loader.js:690:17)
Jun 21 10:51:06 archserver peertube[27504]:     at require (internal/modules/cjs/helpers.js:25:18)
Jun 21 10:51:06 archserver peertube[27504]:     at Object.<anonymous> (/var/www/peertube/versions/peertube-v1.3.1/dist/server/helpers/logger.js:6:18)
Jun 21 10:51:06 archserver peertube[27504]: npm ERR! code ELIFECYCLE
Jun 21 10:51:06 archserver peertube[27504]: npm ERR! errno 1
Jun 21 10:51:06 archserver peertube[27504]: npm ERR! peertube@1.3.1 start: `node dist/server`
Jun 21 10:51:06 archserver peertube[27504]: npm ERR! Exit status 1
Jun 21 10:51:06 archserver peertube[27504]: npm ERR!
Jun 21 10:51:06 archserver peertube[27504]: npm ERR! Failed at the peertube@1.3.1 start script.
Jun 21 10:51:06 archserver peertube[27504]: npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
Jun 21 10:51:06 archserver peertube[27504]: npm ERR! A complete log of this run can be found in:
Jun 21 10:51:06 archserver peertube[27504]: npm ERR!     /var/www/peertube/.npm/_logs/2019-06-21T15_51_06_628Z-debug.log
Jun 21 10:51:06 archserver systemd[1]: peertube.service: Main process exited, code=exited, status=1/FAILURE
Jun 21 10:51:06 archserver systemd[1]: peertube.service: Failed with result 'exit-code'.
Jun 21 10:51:06 archserver systemd[1]: peertube.service: Service RestartSec=100ms expired, scheduling restart.
Jun 21 10:51:06 archserver systemd[1]: peertube.service: Scheduled restart job, restart counter is at 5.
Jun 21 10:51:06 archserver systemd[1]: Stopped PeerTube daemon.
Jun 21 10:51:06 archserver systemd[1]: peertube.service: Start request repeated too quickly.
Jun 21 10:51:06 archserver systemd[1]: peertube.service: Failed with result 'exit-code'.
Jun 21 10:51:06 archserver systemd[1]: Failed to start PeerTube daemon.
```

From what I can tell this is an issue with a nodejs config.

**Comment by Jorropo** [comment]
You could use \`\`\` to create a code block and makes your error more readable :).
Just put 3 of them then in next line your code then return to a new line again and again 3 of them to close the code region :
\`\`\`
your code here
\`\`\`
Extra tip you could also add color if that is some code :
\`\`\`typescript
your code here
\`\`\`
Its also import for \`\`\` to be alone in his line (except for code coloration).
### On your error now :
Its like your config file are missing. (peertube will not create a new example one, you need to take the one in [/config/production.yaml.example](https://github.com/Chocobozzz/PeerTube/blob/develop/config/production.yaml.example) (rename it production.yaml))
You may want take a look at the [install guide](https://github.com/Chocobozzz/PeerTube/blob/develop/support/doc/production.md#peertube-configuration) ? :)

**Comment by JonQuan4** [comment]
I have verified that the file /config/production.yaml is in there and it was. Could this be a permission error? What should the CHMOD value of the files be?

**Comment by Jorropo** [comment]
maybe, good catch, but in this case this is maybe with the folder you have to look, peertube need write and execute access on these (and read access on config but o is at r by default). (just chown to your peertube user, that way simpler)

**Comment by Chocobozzz** [comment]
Hi,

If you use systemd without the "official" peertube paths (`var/www/peertube...`), you need to update the paths in the systemd template (https://github.com/Chocobozzz/PeerTube/blob/develop/support/systemd/peertube.service).

Check the paths in nginx template too.
