### ISSUE TITLE
Arch linux is not working upload video

### ISSUE THREAD

**Issue by ne-vlezay80** [Chocobozzz/PeerTube#1965]
The download videos is not working.

The log:
```
error[13.07.2019, 04:37:06] Error in controller. { "err": "SequelizeValidationError: Validation error: \"https://pt.ne-vlezay80/videos/watch/ff77e104-2949-47b0-99ab-ea0ae36a8905\" is not a valid url.\n at Promise.all.then (/var/www/peertube/versions/peertube-v1.3.1/node_modules/sequelize/lib/instance-validator.js:74:15)\n at tryCatcher (/var/www/peertube/versions/peertube-v1.3.1/node_modules/bluebird/js/release/util.js:16:23)\n at Promise._settlePromiseFromHandler (/var/www/peertube/versions/peertube-v1.3.1/node_modules/bluebird/js/release/promise.js:512:31)\n at Promise._settlePromise (/var/www/peertube/versions/peertube-v1.3.1/node_modules/bluebird/js/release/promise.js:569:18)\n at Promise._settlePromise0 (/var/www/peertube/versions/peertube-v1.3.1/node_modules/bluebird/js/release/promise.js:614:10)\n at Promise._settlePromises (/var/www/peertube/versions/peertube-v1.3.1/node_modules/bluebird/js/release/promise.js:694:18)\n at Promise._fulfill (/var/www/peertube/versions/peertube-v1.3.1/node_modules/bluebird/js/release/promise.js:638:18)\n at PromiseArray._resolve (/var/www/peertube/versions/peertube-v1.3.1/node_modules/bluebird/js/release/promise_array.js:126:19)\n at PromiseArray._promiseFulfilled (/var/www/peertube/versions/peertube-v1.3.1/node_modules/bluebird/js/release/promise_array.js:144:14)\n at Promise._settlePromise (/var/www/peertube/versions/peertube-v1.3.1/node_modules/bluebird/js/release/promise.js:574:26)\n at Promise._settlePromise0 (/var/www/peertube/versions/peertube-v1.3.1/node_modules/bluebird/js/release/promise.js:614:10)\n at Promise._settlePromises (/var/www/peertube/versions/peertube-v1.3.1/node_modules/bluebird/js/release/promise.js:694:18)\n at Promise._fulfill (/var/www/peertube/versions/peertube-v1.3.1/node_modules/bluebird/js/release/promise.js:638:18)\n at Promise._resolveCallback (/var/www/peertube/versions/peertube-v1.3.1/node_modules/bluebird/js/release/promise.js:432:57)\n at Promise._settlePromiseFromHandler (/var/www/peertube/versions/peertube-v1.3.1/node_modules/bluebird/js/release/promise.js:524:17)\n at Promise._settlePromise (/var/www/peertube/versions/peertube-v1.3.1/node_modules/bluebird/js/release/promise.js:569:18)\n at Promise._settlePromise0 (/var/www/peertube/versions/peertube-v1.3.1/node_modules/bluebird/js/release/promise.js:614:10)\n at Promise._settlePromises (/var/www/peertube/versions/peertube-v1.3.1/node_modules/bluebird/js/release/promise.js:694:18)\n at Promise._fulfill (/var/www/peertube/versions/peertube-v1.3.1/node_modules/bluebird/js/release/promise.js:638:18)\n at PromiseArray._resolve (/var/www/peertube/versions/peertube-v1.3.1/node_modules/bluebird/js/release/promise_array.js:126:19)\n at PromiseArray._promiseFulfilled (/var/www/peertube/versions/peertube-v1.3.1/node_modules/bluebird/js/release/promise_array.js:144:14)\n at Promise._settlePromise (/var/www/peertube/versions/peertube-v1.3.1/node_modules/bluebird/js/release/promise.js:574:26)\n at Promise._settlePromise0 (/var/www/peertube/versions/peertube-v1.3.1/node_modules/bluebird/js/release/promise.js:614:10)\n at Promise._settlePromises (/var/www/peertube/versions/peertube-v1.3.1/node_modules/bluebird/js/release/promise.js:694:18)\n at Promise._fulfill (/var/www/peertube/versions/peertube-v1.3.1/node_modules/bluebird/js/release/promise.js:638:18)\n at Promise._resolveCallback (/var/www/peertube/versions/peertube-v1.3.1/node_modules/bluebird/js/release/promise.js:432:57)\n at Promise._settlePromiseFromHandler (/var/www/peertube/versions/peertube-v1.3.1/node_modules/bluebird/js/release/promise.js:524:17)\n at Promise._settlePromise (/var/www/peertube/versions/peertube-v1.3.1/node_modules/bluebird/js/release/promise.js:569:18)\n at Promise._settlePromise0 (/var/www/peertube/versions/peertube-v1.3.1/node_modules/bluebird/js/release/promise.js:614:10)\n at Promise._settlePromises (/var/www/peertube/versions/peertube-v1.3.1/node_modules/bluebird/js/release/promise.js:694:18)\n at Promise._fulfill (/var/www/peertube/versions/peertube-v1.3.1/node_modules/bluebird/js/release/promise.js:638:18)\n at Promise._resolveCallback (/var/www/peertube/versions/peertube-v1.3.1/node_modules/bluebird/js/release/promise.js:432:57)\n at Promise._settlePromiseFromHandler (/var/www/peertube/versions/peertube-v1.3.1/node_modules/bluebird/js/release/promise.js:524:17)\n at Promise._settlePromise (/var/www/peertube/versions/peertube-v1.3.1/node_modules/bluebird/js/release/promise.js:569:18)\n at Promise._settlePromise0 (/var/www/peertube/versions/peertube-v1.3.1/node_modules/bluebird/js/release/promise.js:614:10)\n at Promise._settlePromises (/var/www/peertube/versions/peertube-v1.3.1/node_modules/bluebird/js/release/promise.js:694:18)\n at Promise._fulfill (/var/www/peertube/versions/peertube-v1.3.1/node_modules/bluebird/js/release/promise.js:638:18)\n at PromiseArray._resolve (/var/www/peertube/versions/peertube-v1.3.1/node_modules/bluebird/js/release/promise_array.js:126:19)\n at PromiseArray._promiseFulfilled (/var/www/peertube/versions/peertube-v1.3.1/node_modules/bluebird/js/release/promise_array.js:144:14)\n at Promise._settlePromise (/var/www/peertube/versions/peertube-v1.3.1/node_modules/bluebird/js/release/promise.js:574:26)" } 
```

**Additional information**
* PeerTube version or URL: 1.3.1
* Browser name/version: 
* NodeJS version: 10.16.0

**Comment by Chocobozzz** [comment]
Hi, what is your instance URL?
