### ISSUE TITLE
Unable to start PeerTube in the peertube-dev Docker image / on Janitor

### ISSUE THREAD

**Issue by jankeromnes** [Chocobozzz/PeerTube#205]
* **PeerTube version or commit:** latest / b270ad07f13fa4125fbade6208596071329bc92f
* **Browser name/version:** any
* **NodeJS version:** node v8.9.4
* **PostgreSQL version:** psql 9.5.10

When I:

1. create a new PeerTube container on https://janitor.technology
2. then open the "IDE"
3. then right-click on the "Run" button, and choose "Start PeerTube"

I see the following error:

```
> peertube@0.0.11-alpha start /home/user/PeerTube
> node dist/server

(node:611) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): SequelizeConnectionRefusedError: connect ECONNREFUSED 127.0.0.1:5432
(node:611) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

* **What is the expected behaviour?**

It should start PeerTube, and the web preview should work.

**Comment by bnjbvr** [comment]
I've tried this image locally and observed the following:

- postgresql needs to be started: `$ sudo service postgresql start`
- then we need to create the database and psql user:
```
$ sudo -u postgres createuser -P peertube
Enter password for new role: peertube
$ sudo -u postgres createdb -O peertube peertube_dev
```
- then when running the application, I observe the following blocking error:

```
Cannot install application. SequelizeValidationError: Validation error: "http://localhost:9000/accounts/peertube" is not a valid url.,
Validation error: "http://localhost:9000/accounts/peertube/inbox" is not a valid inbox url.,
Validation error: "http://localhost:9000/accounts/peertube/outbox" is not a valid outbox url.,
Validation error: "http://localhost:9000/inbox" is not a valid shared inbox url.,
Validation error: "http://localhost:9000/accounts/peertube/followers" is not a valid followers url.,
Validation error: "http://localhost:9000/accounts/peertube/following" is not a valid following url.
    at Promise.all.then (/home/user/PeerTube/node_modules/sequelize/lib/instance-validator.js:77:15)
    at tryCatcher (/home/user/PeerTube/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/user/PeerTube/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/home/user/PeerTube/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/home/user/PeerTube/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/home/user/PeerTube/node_modules/bluebird/js/release/promise.js:693:18)
    at Promise._fulfill (/home/user/PeerTube/node_modules/bluebird/js/release/promise.js:638:18)
    at PromiseArray._resolve (/home/user/PeerTube/node_modules/bluebird/js/release/promise_array.js:126:19)
    at PromiseArray._promiseFulfilled (/home/user/PeerTube/node_modules/bluebird/js/release/promise_array.js:144:14)
    at Promise._settlePromise (/home/user/PeerTube/node_modules/bluebird/js/release/promise.js:574:26)
    at Promise._settlePromise0 (/home/user/PeerTube/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/home/user/PeerTube/node_modules/bluebird/js/release/promise.js:693:18)
    at Promise._fulfill (/home/user/PeerTube/node_modules/bluebird/js/release/promise.js:638:18)
    at Promise._resolveCallback (/home/user/PeerTube/node_modules/bluebird/js/release/promise.js:432:57)
    at Promise._settlePromiseFromHandler (/home/user/PeerTube/node_modules/bluebird/js/release/promise.js:524:17)
    at Promise._settlePromise (/home/user/PeerTube/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/home/user/PeerTube/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/home/user/PeerTube/node_modules/bluebird/js/release/promise.js:693:18)
    at Promise._fulfill (/home/user/PeerTube/node_modules/bluebird/js/release/promise.js:638:18)
    at PromiseArray._resolve (/home/user/PeerTube/node_modules/bluebird/js/release/promise_array.js:126:19)
    at PromiseArray._promiseFulfilled (/home/user/PeerTube/node_modules/bluebird/js/release/promise_array.js:144:14)
    at Promise._settlePromise (/home/user/PeerTube/node_modules/bluebird/js/release/promise.js:574:26)
    at Promise._settlePromise0 (/home/user/PeerTube/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/home/user/PeerTube/node_modules/bluebird/js/release/promise.js:693:18)
    at Promise._fulfill (/home/user/PeerTube/node_modules/bluebird/js/release/promise.js:638:18)
    at Promise._resolveCallback (/home/user/PeerTube/node_modules/bluebird/js/release/promise.js:432:57)
    at Promise._settlePromiseFromHandler (/home/user/PeerTube/node_modules/bluebird/js/release/promise.js:524:17)
    at Promise._settlePromise (/home/user/PeerTube/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/home/user/PeerTube/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/home/user/PeerTube/node_modules/bluebird/js/release/promise.js:693:18)
    at Promise._fulfill (/home/user/PeerTube/node_modules/bluebird/js/release/promise.js:638:18)
    at Promise._resolveCallback (/home/user/PeerTube/node_modules/bluebird/js/release/promise.js:432:57)
    at Promise._settlePromiseFromHandler (/home/user/PeerTube/node_modules/bluebird/js/release/promise.js:524:17)
    at Promise._settlePromise (/home/user/PeerTube/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/home/user/PeerTube/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/home/user/PeerTube/node_modules/bluebird/js/release/promise.js:693:18)
    at Promise._fulfill (/home/user/PeerTube/node_modules/bluebird/js/release/promise.js:638:18)
    at PromiseArray._resolve (/home/user/PeerTube/node_modules/bluebird/js/release/promise_array.js:126:19)
    at PromiseArray._promiseFulfilled (/home/user/PeerTube/node_modules/bluebird/js/release/promise_array.js:144:14)
    at Promise._settlePromise (/home/user/PeerTube/node_modules/bluebird/js/release/promise.js:574:26)
```

**Comment by bnjbvr** [comment]
I think I got it: peertube must run in production mode and not in dev mode, thus localhost is not authorized in URLs.
