### ISSUE TITLE
Manually installing plug-in from local directory

### ISSUE THREAD

**Issue by CorpulentBrony** [Chocobozzz/PeerTube#2112]
I feel like I am duplicating #2101 , but I can't get the CLI command to work and install my plug-in.  I continuously receive an error message stating there is no license field in my package.json, which I have been sure to go back and add.

The plug-in's package.json:

```json
{
	"name": "peertube-plugin-ponytube",
	"version": "1.0",
	"description": "Custom PeerTube plugin for the Pony.Tube site.",
	"license": "UNLICENSED",
	"engine": { "peertube": ">=1.3.0" },
	"keywords": ["peertube", "plugin"],
	"homepage": "https://pony.tube/",
	"bugs": "https://pony.tube",
	"author": "Corpulent Brony",
	"library": "./main.js",
	"staticDirs": { "images": "images" },
	"css": ["css/main.css"],
	"clientScripts": [
		{ "scopes": ["common"], "script": "client/common-client-plugin.js" },
		{ "scopes": ["video-watch"], "script": "client/video-watch-client-plugin.js" }
	]
}
```

```
corpubro@pony.tube:/var/www/peertube/peertube-latest$ NODE_CONFIG_DIR=/var/www/peertube/config NODE_ENV=production npm run plugin:install -- --plugin-path /home/corpubro/peertube-plugin-ponytube

> peertube@1.4.0 plugin:install /var/www/peertube/versions/peertube-v1.4.0
> node ./dist/scripts/plugin/install.js "--plugin-path" "/home/corpubro/peertube-plugin-ponytube"

[pony.tube:443] 2019-09-05 21:13:27.385 info: Installing plugin /home/corpubro/peertube-plugin-ponytube.
[pony.tube:443] 2019-09-05 21:13:27.758 error: Cannot install plugin /home/corpubro/peertube-plugin-ponytube, removing it... {
  "err": {
    "err": {
      "stack": "Error: Command failed: yarn add file:/home/corpubro/peertube-plugin-ponytube\nwarning package.json: No license field\nwarning No license field\nerror Can't add \"peertube-plugin-ponytube\": invalid package version \"1.0\".\n\n    at ChildProcess.exithandler (child_process.js:299:12)\n    at ChildProcess.emit (events.js:193:13)\n    at maybeClose (internal/child_process.js:999:16)\n    at Process.ChildProcess._handle.onexit (internal/child_process.js:266:5)",
      "message": "Command failed: yarn add file:/home/corpubro/peertube-plugin-ponytube\nwarning package.json: No license field\nwarning No license field\nerror Can't add \"peertube-plugin-ponytube\": invalid package version \"1.0\".\n",
      "killed": false,
      "code": 1,
      "signal": null,
      "cmd": "yarn add file:/home/corpubro/peertube-plugin-ponytube"
    },
    "stdout": "yarn add v1.17.3\n[1/4] Resolving packages...\ninfo Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.\n",
    "stderr": "warning package.json: No license field\nwarning No license field\nerror Can't add \"peertube-plugin-ponytube\": invalid package version \"1.0\".\n"
  }
}
[pony.tube:443] 2019-09-05 21:13:27.759 error: Cannot remove plugin /home/corpubro/peertube-plugin-ponytube after failed installation. {
  "err": {
    "stack": "Error: Invalid NPM plugin name to install\n    at checkNpmPluginNameOrThrow (/var/www/peertube/versions/peertube-v1.4.0/dist/server/lib/plugins/yarn.js:61:15)\n    at Object.<anonymous> (/var/www/peertube/versions/peertube-v1.4.0/dist/server/lib/plugins/yarn.js:38:9)\n    at Generator.next (<anonymous>)\n    at /var/www/peertube/versions/peertube-v1.4.0/dist/server/lib/plugins/yarn.js:7:71\n    at new Promise (<anonymous>)\n    at __awaiter (/var/www/peertube/versions/peertube-v1.4.0/dist/server/lib/plugins/yarn.js:3:12)\n    at Object.removeNpmPlugin (/var/www/peertube/versions/peertube-v1.4.0/dist/server/lib/plugins/yarn.js:37:12)\n    at PluginManager.<anonymous> (/var/www/peertube/versions/peertube-v1.4.0/dist/server/lib/plugins/plugin-manager.js:153:34)\n    at Generator.throw (<anonymous>)\n    at rejected (/var/www/peertube/versions/peertube-v1.4.0/dist/server/lib/plugins/plugin-manager.js:5:65)\n    at processTicksAndRejections (internal/process/task_queues.js:86:5)",
    "message": "Invalid NPM plugin name to install"
  }
}
{ err:
   { Error: Command failed: yarn add file:/home/corpubro/peertube-plugin-ponytube
   warning package.json: No license field
   warning No license field
   error Can't add "peertube-plugin-ponytube": invalid package version "1.0".

       at ChildProcess.exithandler (child_process.js:299:12)
       at ChildProcess.emit (events.js:193:13)
       at maybeClose (internal/child_process.js:999:16)
       at Process.ChildProcess._handle.onexit (internal/child_process.js:266:5)
     killed: false,
     code: 1,
     signal: null,
     cmd: 'yarn add file:/home/corpubro/peertube-plugin-ponytube' },
  stdout:
   'yarn add v1.17.3\n[1/4] Resolving packages...\ninfo Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.\n',
  stderr:
   `warning package.json: No license field\nwarning No license field\nerror Can't add "peertube-plugin-ponytube": invalid package version "1.0".\n` }
npm ERR! code ELIFECYCLE
npm ERR! errno 255
npm ERR! peertube@1.4.0 plugin:install: `node ./dist/scripts/plugin/install.js "--plugin-path" "/home/corpubro/peertube-plugin-ponytube"`
npm ERR! Exit status 255
npm ERR!
npm ERR! Failed at the peertube@1.4.0 plugin:install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/corpubro/.npm/_logs/2019-09-05T21_13_27_780Z-debug.log
```

**Comment by Chocobozzz** [comment]
The error is ` invalid package version \"1.0\"`. Your package version should be `1.0.0`

**Comment by CorpulentBrony** [comment]
Fixed, but the error about invalid license persists:

```
corpubro@pony.tube:/var/www/peertube/peertube-latest$ NODE_CONFIG_DIR=/var/www/peertube/config NODE_ENV=production npm run plugin:install -- --plugin-path /home/corpubro/peertube-plugin-ponytube

> peertube@1.4.0 plugin:install /var/www/peertube/versions/peertube-v1.4.0
> node ./dist/scripts/plugin/install.js "--plugin-path" "/home/corpubro/peertube-plugin-ponytube"

[pony.tube:443] 2019-09-07 04:40:18.713 info: Installing plugin /home/corpubro/peertube-plugin-ponytube.
[pony.tube:443] 2019-09-07 04:40:19.074 error: Cannot install plugin /home/corpubro/peertube-plugin-ponytube, removing it... {
  "err": {
    "err": {
      "stack": "Error: Command failed: yarn add file:/home/corpubro/peertube-plugin-ponytube\nwarning package.json: No license field\nwarning No license field\nerror Could not write file \"/var/www/peertube/storage/plugins/yarn-error.log\": \"EACCES: permission denied, open '/var/www/peertube/storage/plugins/yarn-error.log'\"\nerror An unexpected error occurred: \"EACCES: permission denied, unlink '/var/www/peertube/storage/plugins/node_modules/.yarn-integrity'\".\n\n    at ChildProcess.exithandler (child_process.js:299:12)\n    at ChildProcess.emit (events.js:193:13)\n    at maybeClose (internal/child_process.js:999:16)\n    at Process.ChildProcess._handle.onexit (internal/child_process.js:266:5)",
      "message": "Command failed: yarn add file:/home/corpubro/peertube-plugin-ponytube\nwarning package.json: No license field\nwarning No license field\nerror Could not write file \"/var/www/peertube/storage/plugins/yarn-error.log\": \"EACCES: permission denied, open '/var/www/peertube/storage/plugins/yarn-error.log'\"\nerror An unexpected error occurred: \"EACCES: permission denied, unlink '/var/www/peertube/storage/plugins/node_modules/.yarn-integrity'\".\n",
      "killed": false,
      "code": 1,
      "signal": null,
      "cmd": "yarn add file:/home/corpubro/peertube-plugin-ponytube"
    },
    "stdout": "yarn add v1.17.3\n[1/4] Resolving packages...\n[2/4] Fetching packages...\ninfo Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.\n",
    "stderr": "warning package.json: No license field\nwarning No license field\nerror Could not write file \"/var/www/peertube/storage/plugins/yarn-error.log\": \"EACCES: permission denied, open '/var/www/peertube/storage/plugins/yarn-error.log'\"\nerror An unexpected error occurred: \"EACCES: permission denied, unlink '/var/www/peertube/storage/plugins/node_modules/.yarn-integrity'\".\n"
  }
}
[pony.tube:443] 2019-09-07 04:40:19.075 error: Cannot remove plugin /home/corpubro/peertube-plugin-ponytube after failed installation. {
  "err": {
    "stack": "Error: Invalid NPM plugin name to install\n    at checkNpmPluginNameOrThrow (/var/www/peertube/versions/peertube-v1.4.0/dist/server/lib/plugins/yarn.js:61:15)\n    at Object.<anonymous> (/var/www/peertube/versions/peertube-v1.4.0/dist/server/lib/plugins/yarn.js:38:9)\n    at Generator.next (<anonymous>)\n    at /var/www/peertube/versions/peertube-v1.4.0/dist/server/lib/plugins/yarn.js:7:71\n    at new Promise (<anonymous>)\n    at __awaiter (/var/www/peertube/versions/peertube-v1.4.0/dist/server/lib/plugins/yarn.js:3:12)\n    at Object.removeNpmPlugin (/var/www/peertube/versions/peertube-v1.4.0/dist/server/lib/plugins/yarn.js:37:12)\n    at PluginManager.<anonymous> (/var/www/peertube/versions/peertube-v1.4.0/dist/server/lib/plugins/plugin-manager.js:153:34)\n    at Generator.throw (<anonymous>)\n    at rejected (/var/www/peertube/versions/peertube-v1.4.0/dist/server/lib/plugins/plugin-manager.js:5:65)\n    at processTicksAndRejections (internal/process/task_queues.js:86:5)",
    "message": "Invalid NPM plugin name to install"
  }
}
{ err:
   { Error: Command failed: yarn add file:/home/corpubro/peertube-plugin-ponytube
   warning package.json: No license field
   warning No license field
   error Could not write file "/var/www/peertube/storage/plugins/yarn-error.log": "EACCES: permission denied, open '/var/www/peertube/storage/plugins/yarn-error.log'"
   error An unexpected error occurred: "EACCES: permission denied, unlink '/var/www/peertube/storage/plugins/node_modules/.yarn-integrity'".

       at ChildProcess.exithandler (child_process.js:299:12)
       at ChildProcess.emit (events.js:193:13)
       at maybeClose (internal/child_process.js:999:16)
       at Process.ChildProcess._handle.onexit (internal/child_process.js:266:5)
     killed: false,
     code: 1,
     signal: null,
     cmd: 'yarn add file:/home/corpubro/peertube-plugin-ponytube' },
  stdout:
   'yarn add v1.17.3\n[1/4] Resolving packages...\n[2/4] Fetching packages...\ninfo Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.\n',
  stderr:
   `warning package.json: No license field\nwarning No license field\nerror Could not write file "/var/www/peertube/storage/plugins/yarn-error.log": "EACCES: permission denied, open '/var/www/peertube/storage/plugins/yarn-error.log'"\nerror An unexpected error occurred: "EACCES: permission denied, unlink '/var/www/peertube/storage/plugins/node_modules/.yarn-integrity'".\n` }
npm ERR! code ELIFECYCLE
npm ERR! errno 255
npm ERR! peertube@1.4.0 plugin:install: `node ./dist/scripts/plugin/install.js "--plugin-path" "/home/corpubro/peertube-plugin-ponytube"`
npm ERR! Exit status 255
npm ERR!
npm ERR! Failed at the peertube@1.4.0 plugin:install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/corpubro/.npm/_logs/2019-09-07T04_40_19_096Z-debug.log

```

**Comment by Chocobozzz** [comment]
Add `private: true` and `"translations": {}` in your package.json. Error logs should be better with https://github.com/Chocobozzz/PeerTube/commit/9157d5981f6840bfa06652ad8fd16754c6fd679d
