### ISSUE TITLE
Migration issue

### ISSUE THREAD

**Issue by PhieF** [Chocobozzz/PeerTube#2117]
Hi

I'm having a problem to upgrade from an old peertube version

```
Sep 08 13:20:21 ns3354912 anormallostpod[20219]:     "message": "column \"extname_old\" of relation \"videoFile\" already exists",
Sep 08 13:20:21 ns3354912 anormallostpod[20219]:     "name": "SequelizeDatabaseError",
Sep 08 13:20:21 ns3354912 anormallostpod[20219]:     "parent": {
Sep 08 13:20:21 ns3354912 anormallostpod[20219]:       "stack": "error: column \"extname_old\" of relation \"videoFile\" already exists\n    at Connection.parseE (/var/www/anormallostpod/versions/peertube-v1.4.0/node_modules/pg/lib/connection.js:602:11)\n    at Connection.parseMessage (/var/www/anormallostpod/versions/peertube-v1.4.0/node_modules/pg/lib/connection.js:399:19)\n    at Socket.<anonymous> (/var/www/anormallostpod/versions/peertube-v1.4.0/node_modules/pg/lib/connection.js:121:22)\n    at Socket.emit (events.js:198:13)\n    at addChunk (_stream_readable.js:288:12)\n    at readableAddChunk (_stream_readable.js:269:11)\n    at Socket.Readable.push (_stream_readable.js:224:10)\n    at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)",
Sep 08 13:20:21 ns3354912 anormallostpod[20219]:       "message": "column \"extname_old\" of relation \"videoFile\" already exists",
Sep 08 13:20:21 ns3354912 anormallostpod[20219]:       "name": "error",
Sep 08 13:20:21 ns3354912 anormallostpod[20219]:       "length": 139,
Sep 08 13:20:21 ns3354912 anormallostpod[20219]:       "severity": "ERROR",
Sep 08 13:20:21 ns3354912 anormallostpod[20219]:       "code": "42701",
Sep 08 13:20:21 ns3354912 anormallostpod[20219]:       "file": "tablecmds.c",
Sep 08 13:20:21 ns3354912 anormallostpod[20219]:       "line": "5552",
Sep 08 13:20:21 ns3354912 anormallostpod[20219]:       "routine": "check_for_column_name_collision",
Sep 08 13:20:21 ns3354912 anormallostpod[20219]:       "sql": "ALTER TABLE \"videoFile\" RENAME COLUMN \"extname\" TO \"extname_old\";"
Sep 08 13:20:21 ns3354912 anormallostpod[20219]:     },
Sep 08 13:20:21 ns3354912 anormallostpod[20219]:     "original": {
Sep 08 13:20:21 ns3354912 anormallostpod[20219]:       "stack": "error: column \"extname_old\" of relation \"videoFile\" already exists\n    at Connection.parseE (/var/www/anormallostpod/versions/peertube-v1.4.0/node_modules/pg/lib/connection.js:602:11)\n    at Connection.parseMessage (/var/www/anormallostpod/versions/peertube-v1.4.0/node_modules/pg/lib/connection.js:399:19)\n    at Socket.<anonymous> (/var/www/anormallostpod/versions/peertube-v1.4.0/node_modules/pg/lib/connection.js:121:22)\n    at Socket.emit (events.js:198:13)\n    at addChunk (_stream_readable.js:288:12)\n    at readableAddChunk (_stream_readable.js:269:11)\n    at Socket.Readable.push (_stream_readable.js:224:10)\n    at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)",
Sep 08 13:20:21 ns3354912 anormallostpod[20219]:       "message": "column \"extname_old\" of relation \"videoFile\" already exists",
Sep 08 13:20:21 ns3354912 anormallostpod[20219]:       "name": "error",
Sep 08 13:20:21 ns3354912 anormallostpod[20219]:       "length": 139,
Sep 08 13:20:21 ns3354912 anormallostpod[20219]:       "severity": "ERROR",
Sep 08 13:20:21 ns3354912 anormallostpod[20219]:       "code": "42701",
Sep 08 13:20:21 ns3354912 anormallostpod[20219]:       "file": "tablecmds.c",
Sep 08 13:20:21 ns3354912 anormallostpod[20219]:       "line": "5552",
Sep 08 13:20:21 ns3354912 anormallostpod[20219]:       "routine": "check_for_column_name_collision",
Sep 08 13:20:21 ns3354912 anormallostpod[20219]:       "sql": "ALTER TABLE \"videoFile\" RENAME COLUMN \"extname\" TO \"extname_old\";"
Sep 08 13:20:21 ns3354912 anormallostpod[20219]:     },
Sep 08 13:20:21 ns3354912 anormallostpod[20219]:     "sql": "ALTER TABLE \"videoFile\" RENAME COLUMN \"extname\" TO \"extname_old\";"
Sep 08 13:20:21 ns3354912 anormallostpod[20219]:   }
Sep 08 13:20:21 ns3354912 anormallostpod[20219]: }

```

I'm trying to get the latest version, using postgresql 10
I'm wondering if it's because the first trial failed due to a bad version of nodejs
any ideas ?
I've tried

```
ALTER TABLE "videoFile" DROP COLUMN "extname";
ALTER TABLE "videoFile" RENAME COLUMN "extname_old" TO "extname";
```
It wasn't enough
Thanks :)

**Comment by PhieF** [comment]
Well, I don't know why, now it works

Sorry <3
