### ISSUE TITLE
Error when running CLI tools: Cannot find module '../../tsconfig.json'

### ISSUE THREAD

**Issue by aldatsa** [Chocobozzz/PeerTube#2199]
**What happened?**
I followed the installation instructions of the CLI tools guide (https://framagit.org/framasoft/peertube/PeerTube/blob/develop/support/doc/tools.md#installation) on an Ubuntu 16.04.

When I ran peertube -v, I got this error message:

internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module '../../tsconfig.json'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/home/PeerTube/dist/server/helpers/register-ts-paths.js:5:18)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)

**What do you expect to happen instead?**
It should run the command peertube without errors.

**Steps to reproduce:**

1. git clone https://github.com/Chocobozzz/PeerTube.git

2. $ CLONE="$(pwd)/PeerTube"

3. $ cd ${CLONE}

4. NOCLIENT=1 yarn install --pure-lockfile

5. npm run setup:cli

6. Add `alias peertube="cd /your/peertube/directory/ && node ./dist/server/tools/peertube.js"` to your .bashrc

7. source ~/.bashrc

8. peertube -v

**Additional information**
* PeerTube version or URL: Latest on the develop branch: 18c9772876d0e36a4f404d914140f3d24d6037e1
* Browser name/version:
* NodeJS version: v10.17.0

* Link to browser console log if useful:
* Link to server log if useful (journalctl or /var/www/peertube/storage/logs/):

**Possible fix**
I changed this line in the file dist/server/helpers/register-ts-paths.js from:

`const tsConfig = require('../../tsconfig.json');`

to 

`const tsConfig = require('../../../tsconfig.json');`

and it worked as expected.

**Comment by Chocobozzz** [comment]
Arf sorry my bad. Should be fixed by https://github.com/Chocobozzz/PeerTube/commit/a0e6d267598839c8a5508a65876ce0e07d1b3d74.

**Comment by klodner** [comment]
I have the same error with v. 3.4.1 Node 16.11.1 with the same solution
