### ISSUE TITLE
How to import multiple resolution video from local ?

### ISSUE THREAD

**Issue by layarkaca21** [Chocobozzz/PeerTube#2218]
I use the latest version of PeerTube ( 1.40 ).
I have multiple resolution of video downloaded from youtube.
How to import those files to peertube without doing transcoding anymore ?
I already use create-import-video-file-job to add resolution for existing video,
but it doesn't work

**Comment by Chocobozzz** [comment]
> but it doesn't work

Using `create-import-video-file-job` does not work? What do you mean? The additional resolution is not added?

**Comment by layarkaca21** [comment]
yes sir, the additional resolution not added
```
peertube@Peer2:~$ ls
config  PeerTube  peertube-latest  storage  versions
peertube@Peer2:~$ peertube up -f /tmp/720p.mp4 -n test
Uploading test video...
Video test uploaded.
```

get UUID = https://node1.faststream.me/videos/watch/e11090e0-9b91-454c-914b-877b54b55abf

```
peertube@Peer2:~/PeerTube$ cd
peertube@Peer2:~$ cd peertube-latest
peertube@Peer2:~/peertube-latest$ NODE_CONFIG_DIR=/var/www/peertube/config NODE_ENV=production npm run create-import-video-file-job -- -v e11090e0-9b91-454c-914b-877b54b55abf -i /tmp/360p.mp4

> peertube@1.4.1 create-import-video-file-job /var/www/peertube/versions/peertube-v1.4.1
> node ./dist/scripts/create-import-video-file-job.js "-v" "e11090e0-9b91-454c-914b-877b54b55abf" "-i" "/tmp/360p.mp4"

Import job for video e11090e0-9b91-454c-914b-877b54b55abf created.
```

Then i access the url, no 360p quality and when i access storage/videos no 360 video

**Comment by Chocobozzz** [comment]
Please check in the "jobs" tab in the admin panel what happened with this job, and paste server logs to see if there are some errors

**Comment by layarkaca21** [comment]
Here the result of "jobs" failed tab sir :

```
{
  "videoUUID": "e11090e0-9b91-454c-914b-877b54b55abf",
  "filePath": "/tmp/360p.mp4"
}
Error: ffprobe exited with code 1
ffprobe version 3.4.6-0ubuntu0.18.04.1 Copyright (c) 2007-2019 the FFmpeg developers
  built with gcc 7 (Ubuntu 7.3.0-16ubuntu3)
  configuration: --prefix=/usr --extra-version=0ubuntu0.18.04.1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --enable-gpl --disable-stripping --enable-avresample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librubberband --enable-librsvg --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-omx --enable-openal --enable-opengl --enable-sdl2 --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libopencv --enable-libx264 --enable-shared
  libavutil      55. 78.100 / 55. 78.100
  libavcodec     57.107.100 / 57.107.100
  libavformat    57. 83.100 / 57. 83.100
  libavdevice    57. 10.100 / 57. 10.100
  libavfilter     6.107.100 /  6.107.100
  libavresample   3.  7.  0 /  3.  7.  0
  libswscale      4.  8.100 /  4.  8.100
  libswresample   2.  9.100 /  2.  9.100
  libpostproc    54.  7.100 / 54.  7.100
/tmp/360p.mp4: No such file or directory

    at ChildProcess.<anonymous> (/var/www/peertube/versions/peertube-v1.4.1/node_modules/fluent-ffmpeg/lib/ffprobe.js:233:22)
    at ChildProcess.emit (events.js:198:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
```
No such file or directory.
But when i check it the file is exist : 
```
root@Peer2 ~ # cd /tmp/
root@Peer2 /tmp # ls
360p.mp4
720p.mp4
```

**Comment by layarkaca21** [comment]
Done sir.
I have to move .mp4 to peertube-latest directory.
Thank you for your help
