### ISSUE TITLE
import from url broken for vimeo ?

### ISSUE THREAD

**Issue by mrflos** [Chocobozzz/PeerTube#2220]
**What happened?**
Uploading video from vimeo from UI seems broken : i get "Cannot fetch remote information of this URL" error popup
Youtube video seems to work

**What do you expect to happen instead?**
Video should be uploaded

**Steps to reproduce:**

1. log as user or admin with enought space and go to "upload video" button > tab "From url..."

2. use this url https://vimeo.com/366272827 to import from url in peertube

3. get error 

**Additional information**
* PeerTube version or URL: 1.4.1 https://video.colibris-outilslibres.org
* Browser name/version: firefox  70.0.1
* NodeJS version: 10

* Link to browser console log if useful:
```
Backend returned code 400, errorMessage is: Cannot fetch remote information of this URL. main-es2015.6eb00b0537c29cac07e6.js:1:553709
    handleError https://video.colibris-outilslibres.org/client/fr_FR/main-es2015.6eb00b0537c29cac07e6.js:1
    importVideoUrl https://video.colibris-outilslibres.org/client/fr_FR/main-es2015.6eb00b0537c29cac07e6.js:1
    error https://video.colibris-outilslibres.org/client/fr_FR/main-es2015.6eb00b0537c29cac07e6.js:1
    _error https://video.colibris-outilslibres.org/client/fr_FR/main-es2015.6eb00b0537c29cac07e6.js:1
    error https://video.colibris-outilslibres.org/client/fr_FR/main-es2015.6eb00b0537c29cac07e6.js:1
    _error https://video.colibris-outilslibres.org/client/fr_FR/main-es2015.6eb00b0537c29cac07e6.js:1
    error https://video.colibris-outilslibres.org/client/fr_FR/main-es2015.6eb00b0537c29cac07e6.js:1
    notifyError https://video.colibris-outilslibres.org/client/fr_FR/main-es2015.6eb00b0537c29cac07e6.js:1
    _error https://video.colibris-outilslibres.org/client/fr_FR/main-es2015.6eb00b0537c29cac07e6.js:1
    error https://video.colibris-outilslibres.org/client/fr_FR/main-es2015.6eb00b0537c29cac07e6.js:1
    notifyError https://video.colibris-outilslibres.org/client/fr_FR/main-es2015.6eb00b0537c29cac07e6.js:1
    _error https://video.colibris-outilslibres.org/client/fr_FR/main-es2015.6eb00b0537c29cac07e6.js:1
    error https://video.colibris-outilslibres.org/client/fr_FR/main-es2015.6eb00b0537c29cac07e6.js:1
    o https://video.colibris-outilslibres.org/client/fr_FR/main-es2015.6eb00b0537c29cac07e6.js:1
    _trySubscribe https://video.colibris-outilslibres.org/client/fr_FR/main-es2015.6eb00b0537c29cac07e6.js:1
    subscribe https://video.colibris-outilslibres.org/client/fr_FR/main-es2015.6eb00b0537c29cac07e6.js:1
    s https://video.colibris-outilslibres.org/client/fr_FR/main-es2015.6eb00b0537c29cac07e6.js:1
    error https://video.colibris-outilslibres.org/client/fr_FR/main-es2015.6eb00b0537c29cac07e6.js:1
    s https://video.colibris-outilslibres.org/client/fr_FR/main-es2015.6eb00b0537c29cac07e6.js:1
    invokeTask https://video.colibris-outilslibres.org/client/fr_FR/polyfills-es2015.0d17989025e8fe280b70.js:1
    onInvokeTask https://video.colibris-outilslibres.org/client/fr_FR/main-es2015.6eb00b0537c29cac07e6.js:1
    invokeTask https://video.colibris-outilslibres.org/client/fr_FR/polyfills-es2015.0d17989025e8fe280b70.js:1
    runTask https://video.colibris-outilslibres.org/client/fr_FR/polyfills-es2015.0d17989025e8fe280b70.js:1
    invokeTask https://video.colibris-outilslibres.org/client/fr_FR/polyfills-es2015.0d17989025e8fe280b70.js:1
    v https://video.colibris-outilslibres.org/client/fr_FR/polyfills-es2015.0d17989025e8fe280b70.js:1
    b https://video.colibris-outilslibres.org/client/fr_FR/polyfills-es2015.0d17989025e8fe280b70.js:1

```
* Link to server log if useful (journalctl or /var/www/peertube/storage/logs/):

**Comment by mrflos** [comment]
For your information, i couldn't test on another instance, so i don't know if it is instance related or not.. Thanks!

**Comment by tcitworld** [comment]
Server logs would be nice.

**Comment by mrflos** [comment]
hello @tcitworld ! Are you not over-buzy with mobilizon ?
Was hard to find in the logs but:
```
{"level":"info","message":"Cannot fetch information from import for URL https://vimeo.com/366272827.","label":"video.colibris-outilslibres.org:443","err":{"stack":"Error: Command failed: /var/www/peertube/versions/peertube-v1.4.1/node_modules/youtube-dl/bin/youtube-dl --dump-json -f best -j --flat-playlist -- https://vimeo.com/366272827\nERROR: Unable to download webpage: HTTP Error 403: Forbidden (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.\n\n    at ChildProcess.exithandler (child_process.js:294:12)\n    at ChildProcess.emit (events.js:198:13)\n    at maybeClose (internal/child_process.js:982:16)\n    at Socket.stream.socket.on (internal/child_process.js:389:11)\n    at Socket.emit (events.js:198:13)\n    at Pipe._handle.close (net.js:606:12)","message":"Command failed: /var/www/peertube/versions/peertube-v1.4.1/node_modules/youtube-dl/bin/youtube-dl --dump-json -f best -j --flat-playlist -- https://vimeo.com/366272827\nERROR: Unable to download webpage: HTTP Error 403: Forbidden (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.\n","killed":false,"code":1,"signal":null,"cmd":"/var/www/peertube/versions/peertube-v1.4.1/node_modules/youtube-dl/bin/youtube-dl --dump-json -f best -j --flat-playlist -- https://vimeo.com/366272827"},"timestamp":"2019-11-04T15:12:19.980Z"}
```

**Comment by Chocobozzz** [comment]
Hi @mrflos :)

It seems Vimeo blacklisted your server IP. Did you import many videos today?

**Comment by mrflos** [comment]
no, it was a collegue who tried today, and told me that it doesn't work, so i tried again several times, but no more then 13 entries in today's log if i grep vimeo

**Comment by mrflos** [comment]
i made massive imports, but quite a while ago, maybe it's retroactive? ;-)

**Comment by Chocobozzz** [comment]
I don't really know. I tried to import your video on peertube2.cpy.re and it worked. So maybe try again another day :)

**Comment by mrflos** [comment]
thanks @Chocobozzz i guess i should have told my collegues to first import to vimeo, then to peertube using url...

Will try antoher time or import from scratch the file!  

Cheers
