### ISSUE TITLE
System Job Error : Converting circular structure to JSON

### ISSUE THREAD

**Issue by grondinm** [Chocobozzz/PeerTube#2223]
I host my own instance(https://video.gcfam.net)

Looking at the failed jobs i see many activitypub-http-fetcher jobs that are failing. Most are of type video-likes and all seem to fail with the following:

```
TypeError: Converting circular structure to JSON
    at JSON.stringify (<anonymous>)
    at Printf.winston.format.printf.info [as template] (/srv/peertube/versions/peertube-v1.4.1/dist/server/helpers/logger.js:29:17)
    at Printf.transform (/srv/peertube/versions/peertube-v1.4.1/node_modules/logform/printf.js:11:26)
    at Format.info [as transform] (/srv/peertube/versions/peertube-v1.4.1/node_modules/logform/combine.js:20:24)
    at File._write (/srv/peertube/versions/peertube-v1.4.1/node_modules/winston-transport/index.js:90:33)
    at doWrite (/srv/peertube/versions/peertube-v1.4.1/node_modules/readable-stream/lib/_stream_writable.js:428:64)
    at writeOrBuffer (/srv/peertube/versions/peertube-v1.4.1/node_modules/readable-stream/lib/_stream_writable.js:417:5)
    at File.Writable.write (/srv/peertube/versions/peertube-v1.4.1/node_modules/readable-stream/lib/_stream_writable.js:334:11)
    at DerivedLogger.ondata (/srv/peertube/versions/peertube-v1.4.1/node_modules/winston/node_modules/readable-stream/lib/_stream_readable.js:662:20)
    at DerivedLogger.emit (events.js:203:15)
    at addChunk (/srv/peertube/versions/peertube-v1.4.1/node_modules/winston/node_modules/readable-stream/lib/_stream_readable.js:297:12)
    at readableAddChunk (/srv/peertube/versions/peertube-v1.4.1/node_modules/winston/node_modules/readable-stream/lib/_stream_readable.js:279:11)
    at DerivedLogger.Readable.push (/srv/peertube/versions/peertube-v1.4.1/node_modules/winston/node_modules/readable-stream/lib/_stream_readable.js:240:10)
    at DerivedLogger.Transform.push (/srv/peertube/versions/peertube-v1.4.1/node_modules/winston/node_modules/readable-stream/lib/_stream_transform.js:139:32)
    at DerivedLogger._transform (/srv/peertube/versions/peertube-v1.4.1/node_modules/winston/lib/winston/logger.js:305:12)
    at DerivedLogger.Transform._read (/srv/peertube/versions/peertube-v1.4.1/node_modules/winston/node_modules/readable-stream/lib/_stream_transform.js:177:10)
    at DerivedLogger.Transform._write (/srv/peertube/versions/peertube-v1.4.1/node_modules/winston/node_modules/readable-stream/lib/_stream_transform.js:164:83)
    at doWrite (/srv/peertube/versions/peertube-v1.4.1/node_modules/winston/node_modules/readable-stream/lib/_stream_writable.js:405:139)
    at writeOrBuffer (/srv/peertube/versions/peertube-v1.4.1/node_modules/winston/node_modules/readable-stream/lib/_stream_writable.js:394:5)
    at DerivedLogger.Writable.write (/srv/peertube/versions/peertube-v1.4.1/node_modules/winston/node_modules/readable-stream/lib/_stream_writable.js:303:11)
    at DerivedLogger.log (/srv/peertube/versions/peertube-v1.4.1/node_modules/winston/lib/winston/logger.js:249:10)
    at DerivedLogger.(anonymous function) [as warn] (/srv/peertube/versions/peertube-v1.4.1/node_modules/winston/lib/winston/create-logger.js:95:19)
    at Object.<anonymous> (/srv/peertube/versions/peertube-v1.4.1/dist/server/lib/activitypub/video-rates.js:52:33)
    at Generator.throw (<anonymous>)
    at rejected (/srv/peertube/versions/peertube-v1.4.1/dist/server/lib/activitypub/video-rates.js:5:65)
```
Should i be concerned? Is this because i am running 1.4.1 and the instances hosting the videos these errors refer to are not(running 1.3.1) or is something wrong with my instance?

Thank you

**Comment by Chocobozzz** [comment]
Thanks, should be fixed in https://github.com/Chocobozzz/PeerTube/commit/959dbbd7bf655e9a36a310838dae75b9909f0096
