### ISSUE TITLE
unable to download a peertube video using youtube-dl 

### ISSUE THREAD

**Issue by shirishag75** [Chocobozzz/PeerTube#2243]
I expected a peertube video to be downloaded using youtube-dl . 

My youtube-dl is the latest - 

```
$ youtube-dl --version
2019.11.05
```

Sharing the experience of the download or how it went. 

```
$ youtube-dl -c -f 720p --verbose "https://peertube.social/videos/watch/a5965381-6218-4313-9457-d8b2292a9a2e"
[debug] System config: []
[debug] User config: [u'-f', u'bestvideo[height<=720]+bestaudio/best[height<=720]']
[debug] Custom config: []
[debug] Command-line args: [u'-c', u'-f', u'720p', u'--verbose', u'https://peertube.social/videos/watch/a5965381-6218-4313-9457-d8b2292a9a2e']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.11.05
[debug] Python version 2.7.17 (CPython) - Linux-5.2.0-3-amd64-x86_64-with-debian-bullseye-sid
[debug] exe versions: ffmpeg 4.2.1-2, ffprobe 4.2.1-2, phantomjs 2.1.1, rtmpdump 2.4
[debug] Proxy map: {}
[PeerTube] a5965381-6218-4313-9457-d8b2292a9a2e: Downloading JSON metadata
[debug] Invoking downloader on u'https://share.tube/static/webseed/a5965381-6218-4313-9457-d8b2292a9a2e-720.mp4'
[download] Resuming download at byte 1537409
[download] Destination: YouTube vs PeerTube - thoughts on PeerTube as a competitor to YouTube-a5965381-6218-4313-9457-d8b2292a9a2e.mp4
[download]   0.5% of 309.38MiB at 109.97KiB/s ETA 47:47[download] Got server HTTP error: Downloaded 1569791 bytes, expected 324411839 bytes. Retrying (attempt 1 of 10)...
[download] Destination: YouTube vs PeerTube - thoughts on PeerTube as a competitor to YouTube-a5965381-6218-4313-9457-d8b2292a9a2e.mp4
[download]   0.5% of 309.38MiB at 107.29KiB/s ETA 48:58[download] Got server HTTP error: Downloaded 1602173 bytes, expected 324411839 bytes. Retrying (attempt 2 of 10)...
[download] Destination: YouTube vs PeerTube - thoughts on PeerTube as a competitor to YouTube-a5965381-6218-4313-9457-d8b2292a9a2e.mp4
[download]   0.5% of 309.38MiB at 106.30KiB/s ETA 49:25[download] Got server HTTP error: Downloaded 1634555 bytes, expected 324411839 bytes. Retrying (attempt 3 of 10)...
[download] Destination: YouTube vs PeerTube - thoughts on PeerTube as a competitor to YouTube-a5965381-6218-4313-9457-d8b2292a9a2e.mp4
[download]   0.5% of 309.38MiB at 108.72KiB/s ETA 48:19[download] Got server HTTP error: Downloaded 1666937 bytes, expected 324411839 bytes. Retrying (attempt 4 of 10)...
[download] Destination: YouTube vs PeerTube - thoughts on PeerTube as a competitor to YouTube-a5965381-6218-4313-9457-d8b2292a9a2e.mp4
[download]   0.5% of 309.38MiB at 104.55KiB/s ETA 50:14[download] Got server HTTP error: Downloaded 1699319 bytes, expected 324411839 bytes. Retrying (attempt 5 of 10)...
[download] Destination: YouTube vs PeerTube - thoughts on PeerTube as a competitor to YouTube-a5965381-6218-4313-9457-d8b2292a9a2e.mp4
[download]   0.5% of 309.38MiB at 108.49KiB/s ETA 48:24[download] Got server HTTP error: Downloaded 1731701 bytes, expected 324411839 bytes. Retrying (attempt 6 of 10)...
[download] Destination: YouTube vs PeerTube - thoughts on PeerTube as a competitor to YouTube-a5965381-6218-4313-9457-d8b2292a9a2e.mp4
[download]   0.5% of 309.38MiB at 110.08KiB/s ETA 47:42[download] Got server HTTP error: Downloaded 1764083 bytes, expected 324411839 bytes. Retrying (attempt 7 of 10)...
[download] Destination: YouTube vs PeerTube - thoughts on PeerTube as a competitor to YouTube-a5965381-6218-4313-9457-d8b2292a9a2e.mp4
[download]   0.6% of 309.38MiB at 112.53KiB/s ETA 46:39[download] Got server HTTP error: Downloaded 1796465 bytes, expected 324411839 bytes. Retrying (attempt 8 of 10)...
[download] Destination: YouTube vs PeerTube - thoughts on PeerTube as a competitor to YouTube-a5965381-6218-4313-9457-d8b2292a9a2e.mp4
[download]   0.6% of 309.38MiB at 103.97KiB/s ETA 50:30[download] Got server HTTP error: Downloaded 1828847 bytes, expected 324411839 bytes. Retrying (attempt 9 of 10)...
[download] Destination: YouTube vs PeerTube - thoughts on PeerTube as a competitor to YouTube-a5965381-6218-4313-9457-d8b2292a9a2e.mp4
[download]   0.6% of 309.38MiB at 109.77KiB/s ETA 47:49[download] Got server HTTP error: Downloaded 1861229 bytes, expected 324411839 bytes. Retrying (attempt 10 of 10)...
[download] Destination: YouTube vs PeerTube - thoughts on PeerTube as a competitor to YouTube-a5965381-6218-4313-9457-d8b2292a9a2e.mp4
[download]   0.6% of 309.38MiB at 103.56KiB/s ETA 50:41ERROR: giving up after 10 retries
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/http.py", line 342, in real_download
    return download()
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/http.py", line 320, in download
    retry(err)
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/http.py", line 225, in retry
    raise RetryDownload(e)
RetryDownload
```

Looking forward to know what went wrong. From youtube I'm able to download the same video without any difficulty :(

**Comment by shirishag75** [comment]
also see http://paste.debian.net/1116103/

**Comment by alcalyn** [comment]
Just tried the same command with the dockerized version of youtube-dl, it seems to work:

```
$> docker run --rm -u $(id -u):$(id -g) -v $PWD:/data vimagyoutube-dl --version
2019.11.05

$> docker run --rm -u $(id -u):$(id -g) -v $PWD:/data vimagick/youtube-dl  -c -f 720p --verbose https://peertube.social/videos/watch/a5965381-6218-4313-9457-d8b2292a9a2e
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-c', '-f', '720p', '--verbose', 'https://peertube.social/videos/watch/a5965381-6218-4313-9457-d8b2292a9a2e']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.11.05
[debug] Python version 3.7.5 (CPython) - Linux-4.15.0-66-generic-x86_64-with
[debug] exe versions: ffmpeg 4.1.4, ffprobe 4.1.4
[debug] Proxy map: {}
[PeerTube] a5965381-6218-4313-9457-d8b2292a9a2e: Downloading JSON metadata
[debug] Invoking downloader on 'https://share.tube/static/webseed/a5965381-6218-4313-9457-d8b2292a9a2e-720.mp4'
[download] Resuming download at byte 79327247
[download] Destination: YouTube vs PeerTube - thoughts on PeerTube as a competitor to YouTube-a5965381-6218-4313-9457-d8b2292a9a2e.mp4
[download]  57.0% of 309.38MiB at 460.05KiB/s ETA 05:06
```

**Comment by Findus23** [comment]
It is also working fine for me. Are you sure the server you were downloading from didn't just have connection issues at that moment?
Because I think with the default nginx config `https://share.tube/static/webseed/a5965381-6218-4313-9457-d8b2292a9a2e-720.mp4` never reaches peertube, but is just served directly by nginx.

**Comment by alcalyn** [comment]
Maybe try with the dockerized version, it uses different versions (like python 3 instead of python 2)

**Comment by shirishag75** [comment]
That will happen soon by itself as python2 is removed from Debian https://wiki.debian.org/Python/2Removal

**Comment by Vertux** [comment]
For me it is working:
```
youtube-dl -c -f 720p --verbose "https://peertube.social/videos/watch/a5965381-6218-4313-9457-d8b2292a9a2e"
[debug] youtube-dl version 2019.11.05 
[debug] Python version 2.7.16 (CPython)
```

**Comment by Chocobozzz** [comment]
Hi,

It does not seem to be a peertube issue. Please try to update youtube-dl, or test with another peertube instance.
