### ISSUE TITLE
subtitle file uploaded but not usable.

### ISSUE THREAD

**Issue by 22decembre** [Chocobozzz/PeerTube#2296]
**When uploading a subtitle file (srt) on a video, it failed.**

```
info[30/11/2019 à 11:48:18] Creating job to update video https://tube.22decembre.eu/videos/watch/092f048f-dfa2-44b2-aaed-70504b1f588f.
info[30/11/2019 à 11:48:18] Video with name Jodorowsky's Dune - 2013 and uuid 092f048f-dfa2-44b2-aaed-70504b1f588f updated.
info[30/11/2019 à 11:48:18] Processing ActivityPub broadcast in job 140.
info[30/11/2019 à 11:48:18] 2a06:: - - [30/Nov/2019:10:48:18 +0000] "PUT /api/v1/videos/5357 HTTP/1.0" 204 - "https://tube.22decembre.eu/videos/update/092f048f-dfa2-44b2-aaed-70504b1f588f" "Firefox"
error[30/11/2019 à 11:48:19] Cannot execute addVideoCaption with many retries. { "err": { "stack": "Error: Source and destination must not be the same.\n at getStats (/var/www/peertube/versions/peertube-v1.4.1/node_modules/fs-extra/lib/util/stat.js:80:17)\n at fs.stat (/var/www/peertube/versions/peertube-v1.4.1/node_modules/fs-extra/lib/util/stat.js:38:16)\n at callback (/var/www/peertube/versions/peertube-v1.4.1/node_modules/graceful-fs/polyfills.js:289:20)\n at FSReqWrap.oncomplete (fs.js:154:5)", "message": "Source and destination must not be the same." } }
error[30/11/2019 à 11:48:19] Error in controller. { "err": "Error: Source and destination must not be the same.\n at getStats (/var/www/peertube/versions/peertube-v1.4.1/node_modules/fs-extra/lib/util/stat.js:80:17)\n at fs.stat (/var/www/peertube/versions/peertube-v1.4.1/node_modules/fs-extra/lib/util/stat.js:38:16)\n at callback (/var/www/peertube/versions/peertube-v1.4.1/node_modules/graceful-fs/polyfills.js:289:20)\n at FSReqWrap.oncomplete (fs.js:154:5)" }
info[30/11/2019 à 11:48:19] 2a06:: - - [30/Nov/2019:10:48:19 +0000] "PUT /api/v1/videos/5357/captions/fr HTTP/1.0" 500 - "https://tube.22decembre.eu/videos/update/092f048f-dfa2-44b2-aaed-70504b1f588f" "Firefox" 
```

**That the file uploaded and can be read while the video is played.**

Whe looking at it, I see the file is indeed uploaded in the captions folder with the uid.lang.vtt scheme.

But at first, one think there was a mistake.

And anyway, the video does not allow subtitles later while playing.

**Additional information**
* PeerTube version or URL: OpenBSD, 1.4.1, https://tube.22decembre.eu
* Browser name/version: Firefox 70 Linux
* NodeJS version: node-10.16.3

**Comment by Chocobozzz** [comment]
Thanks, it should be fixed by https://github.com/Chocobozzz/PeerTube/commit/3f6b7aa1cfa28ee02eec8c8ab16b623f2bbab928
