### ISSUE TITLE
Unique constraint violation after instance follow

### ISSUE THREAD

**Issue by karthanistyr** [Chocobozzz/PeerTube#2307]
*Edit: I initially stated "PK" where I really meant "unique", my bad.*

**What happened?**
Logs spit out repeated errors about unique constraint violation after I established an instance follow.

**What do you expect to happen instead?**
I assume there should never be unique constraint violations, so I suspect a bug.

**Steps to reproduce:**
Unclear at this point. I added an instance follow for `share.tube` from mine and the errors started filling the logs.
Note that I have never prior to this point tried to follow this instance.

**Additional information**
* PeerTube version or URL: video.barbed.fr (2.0.0, freshly installed via docker)
* Browser name/version: Firefox (latest)
* NodeJS version: from docker image (2.0.0)

* Server log if useful:
```
[video.barbed.fr:443] 2019-12-04 18:42:41.661 ESC[31merrorESC[39m: Cannot execute saveActorAndServerAndModelIfNotExist with many retries. {
  "err": {
    "stack": "SequelizeUniqueConstraintError: Validation error\n    at Query.formatError (/app/node_modules/sequelize/lib/dialects/postgres/query.js:324:18)\n    at query.catch.then.queryResult (/app/node_modules/sequelize/lib/dialects/postgres/query.js:113:24)\n    at tryCatcher (/app/node_modules/bluebird/js/release/util.js:16:23)\n    at Promise._settlePromiseFromHandler (/app/node_modules/bluebird/js/release/promise.js:547:31)\n    at Promise._settlePromise (/app/node_modules/bluebird/js/release/promise.js:604:18)\n    at Promise._settlePromise0 (/app/node_modules/bluebird/js/release/promise.js:649:10)\n    at Promise._settlePromises (/app/node_modules/bluebird/js/release/promise.js:729:18)\n    at _drainQueueStep (/app/node_modules/bluebird/js/release/async.js:93:12)\n    at _drainQueue (/app/node_modules/bluebird/js/release/async.js:86:9)\n    at Async._drainQueues (/app/node_modules/bluebird/js/release/async.js:102:5)\n    at Immediate.Async.drainQueues [as _onImmediate] (/app/node_modules/bluebird/js/release/async.js:15:14)\n    at runCallback (timers.js:705:18)\n    at tryOnImmediate (timers.js:676:5)\n    at processImmediate (timers.js:658:5)",
    "message": "Validation error",
    "name": "SequelizeUniqueConstraintError",
    "errors": [
      {
        "message": "preferredUsername must be unique",
        "type": "unique violation",
        "path": "preferredUsername",
        "value": "ziix",
        "origin": "DB",
        "instance": {
          "id": null,
          "type": "Group",
          "preferredUsername": "ziix",
          "url": "https://share.tube/video-channels/ziix",
          "publicKey": "-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAsBSSI3+RljgOV/iX/TQw\nhsqiIcLE704MjRAy0Xdu7A5ZZ0p8HfmBiphfK0O9csmk27u6X6egL7LV5pVRFbus\n8ZVIrEZLlVwYgDLg+RFbiMnmcEspV5M3RTXyvyZAqLYjtJFCVIgQSghbT5DJ2/Qk\nCyLGS1soz1YrofVdwNflM+C1vM6JubuxdAFQQN42wdfHQCOwzENTfAbKSvoTCgdk\nN1lIcCY3BrMbHJwMFI3SGDqzW8FDMb3gHXog0rWvFkyb1cooiBILuZEg1jzKxuga\n/yqHDaxecT8kSvWvcRPzyzJt8j0WBN9L6iRTu6UmK16/StMibgg7GRv9oJJ/4AJQ\nJQIDAQAB\n-----END PUBLIC KEY-----",
          "privateKey": null,
          "followersCount": 0,
          "followingCount": 0,
          "inboxUrl": "https://share.tube/video-channels/ziix/inbox",
          "outboxUrl": "https://share.tube/video-channels/ziix/outbox",
          "followersUrl": "https://share.tube/video-channels/ziix/followers",
          "followingUrl": "https://share.tube/video-channels/ziix/following",
          "sharedInboxUrl": "https://share.tube/inbox",
          "serverId": 143,
          "updatedAt": "2019-12-04T18:42:41.654Z",
          "createdAt": "2019-12-04T18:42:41.654Z"
        },
        "validatorKey": "not_unique",
        "validatorName": null,
        "validatorArgs": []
      },
      {
        "message": "serverId must be unique",
        "type": "unique violation",
        "path": "serverId",
        "value": "143",
        "origin": "DB",
        "instance": {
          "id": null,
          "type": "Group",
          "preferredUsername": "ziix",
          "url": "https://share.tube/video-channels/ziix",
          "publicKey": "-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAsBSSI3+RljgOV/iX/TQw\nhsqiIcLE704MjRAy0Xdu7A5ZZ0p8HfmBiphfK0O9csmk27u6X6egL7LV5pVRFbus\n8ZVIrEZLlVwYgDLg+RFbiMnmcEspV5M3RTXyvyZAqLYjtJFCVIgQSghbT5DJ2/Qk\nCyLGS1soz1YrofVdwNflM+C1vM6JubuxdAFQQN42wdfHQCOwzENTfAbKSvoTCgdk\nN1lIcCY3BrMbHJwMFI3SGDqzW8FDMb3gHXog0rWvFkyb1cooiBILuZEg1jzKxuga\n/yqHDaxecT8kSvWvcRPzyzJt8j0WBN9L6iRTu6UmK16/StMibgg7GRv9oJJ/4AJQ\nJQIDAQAB\n-----END PUBLIC KEY-----",
          "privateKey": null,
          "followersCount": 0,
          "followingCount": 0,
          "inboxUrl": "https://share.tube/video-channels/ziix/inbox",
          "outboxUrl": "https://share.tube/video-channels/ziix/outbox",
          "followersUrl": "https://share.tube/video-channels/ziix/followers",
          "followingUrl": "https://share.tube/video-channels/ziix/following",
          "sharedInboxUrl": "https://share.tube/inbox",
          "serverId": 143,
          "updatedAt": "2019-12-04T18:42:41.654Z",
          "createdAt": "2019-12-04T18:42:41.654Z"
        },
        "validatorKey": "not_unique",
        "validatorName": null,
        "validatorArgs": []
      }
    ],
    "fields": {
      "preferredUsername": "ziix",
      "serverId": "143"
    },
    "parent": {
      "code": "23505",
      "detail": "Key (\"preferredUsername\", \"serverId\")=(ziix, 143) already exists."
    }
  }
}
```
Another occurrence:
```
[video.barbed.fr:443] 2019-12-04 18:52:57.277 ESC[31merrorESC[39m: Cannot execute saveActorAndServerAndModelIfNotExist with many retries. {
  "err": {
    "stack": "SequelizeUniqueConstraintError: Validation error\n    at Query.formatError (/app/node_modules/sequelize/lib/dialects/postgres/query.js:324:18)\n    at query.catch.then.queryResult (/app/node_modules/sequelize/lib/dialects/postgres/query.js:113:24)\n    at tryCatcher (/app/node_modules/bluebird/js/release/util.js:16:23)\n    at Promise._settlePromiseFromHandler (/app/node_modules/bluebird/js/release/promise.js:547:31)\n    at Promise._settlePromise (/app/node_modules/bluebird/js/release/promise.js:604:18)\n    at Promise._settlePromise0 (/app/node_modules/bluebird/js/release/promise.js:649:10)\n    at Promise._settlePromises (/app/node_modules/bluebird/js/release/promise.js:729:18)\n    at _drainQueueStep (/app/node_modules/bluebird/js/release/async.js:93:12)\n    at _drainQueue (/app/node_modules/bluebird/js/release/async.js:86:9)\n    at Async._drainQueues (/app/node_modules/bluebird/js/release/async.js:102:5)\n    at Immediate.Async.drainQueues [as _onImmediate] (/app/node_modules/bluebird/js/release/async.js:15:14)\n    at runCallback (timers.js:705:18)\n    at tryOnImmediate (timers.js:676:5)\n    at processImmediate (timers.js:658:5)",
    "message": "Validation error",
    "name": "SequelizeUniqueConstraintError",
    "errors": [
      {
        "message": "preferredUsername must be unique",
        "type": "unique violation",
        "path": "preferredUsername",
        "value": "hexdsl",
        "origin": "DB",
        "instance": {
          "id": null,
          "type": "Group",
          "preferredUsername": "hexdsl",
          "url": "https://share.tube/video-channels/hexdsl",
          "publicKey": "-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA3DhDLA+8D8Wvz3PWbzYA\ns69S6fDg/0wDAIttCcdYXkhAYxnn6ElM0qJJgg2d8gWDBXWZxf8kpK5Pw7KBujS0\nzDatwDdgY2Vi5m9Z8JNCJx3W2YE1MpkRHOtczDvq4XBY4NBydDbMR1UAUxCLAsog\nOHmqsm7c8dZMdI06isqmelkO+KViL6OhvJu7bPDr4bDGt12+tnt6cZdFNaYJ8c3f\n/Q3u1/APmvc+QpSskkHIztiNcaxBgZlbM4aQuWizc/FRHaTvCPFB9mUo2q2NjO6V\nke89cisSqnhPyhRwQeZ1PP2t4c/02aSxbbeGve1Yeydpcjw8WXTQ6qB+WNeAIp+3\n4wIDAQAB\n-----END PUBLIC KEY-----",
          "privateKey": null,
          "followersCount": 2,
          "followingCount": 0,
          "inboxUrl": "https://share.tube/video-channels/hexdsl/inbox",
          "outboxUrl": "https://share.tube/video-channels/hexdsl/outbox",
          "followersUrl": "https://share.tube/video-channels/hexdsl/followers",
          "followingUrl": "https://share.tube/video-channels/hexdsl/following",
          "sharedInboxUrl": "https://share.tube/inbox",
          "serverId": 143,
          "avatarId": 2075,
          "updatedAt": "2019-12-04T18:52:57.273Z",
          "createdAt": "2019-12-04T18:52:57.273Z"
        },
        "validatorKey": "not_unique",
        "validatorName": null,
        "validatorArgs": []
      },
      {
        "message": "serverId must be unique",
        "type": "unique violation",
        "path": "serverId",
        "value": "143",
        "origin": "DB",
        "instance": {
          "id": null,
          "type": "Group",
          "preferredUsername": "hexdsl",
          "url": "https://share.tube/video-channels/hexdsl",
          "publicKey": "-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA3DhDLA+8D8Wvz3PWbzYA\ns69S6fDg/0wDAIttCcdYXkhAYxnn6ElM0qJJgg2d8gWDBXWZxf8kpK5Pw7KBujS0\nzDatwDdgY2Vi5m9Z8JNCJx3W2YE1MpkRHOtczDvq4XBY4NBydDbMR1UAUxCLAsog\nOHmqsm7c8dZMdI06isqmelkO+KViL6OhvJu7bPDr4bDGt12+tnt6cZdFNaYJ8c3f\n/Q3u1/APmvc+QpSskkHIztiNcaxBgZlbM4aQuWizc/FRHaTvCPFB9mUo2q2NjO6V\nke89cisSqnhPyhRwQeZ1PP2t4c/02aSxbbeGve1Yeydpcjw8WXTQ6qB+WNeAIp+3\n4wIDAQAB\n-----END PUBLIC KEY-----",
          "privateKey": null,
          "followersCount": 2,
          "followingCount": 0,
          "inboxUrl": "https://share.tube/video-channels/hexdsl/inbox",
          "outboxUrl": "https://share.tube/video-channels/hexdsl/outbox",
          "followersUrl": "https://share.tube/video-channels/hexdsl/followers",
          "followingUrl": "https://share.tube/video-channels/hexdsl/following",
          "sharedInboxUrl": "https://share.tube/inbox",
          "serverId": 143,
          "avatarId": 2075,
          "updatedAt": "2019-12-04T18:52:57.273Z",
          "createdAt": "2019-12-04T18:52:57.273Z"
        },
        "validatorKey": "not_unique",
        "validatorName": null,
        "validatorArgs": []
      }
    ],
    "fields": {
      "preferredUsername": "hexdsl",
      "serverId": "143"
    },
    "parent": {
      "code": "23505",
      "detail": "Key (\"preferredUsername\", \"serverId\")=(hexdsl, 143) already exists."
    }
  }
}
```
```

**Comment by Chocobozzz** [comment]
Could you paste the output of the following SQL query?

```
select url from actor where "serverId" = 143 and "preferredUsername" = 'hexdsl';
```

**Comment by karthanistyr** [comment]
```
peertube=# select url from actor where "serverId" = 143 and "preferredUsername" = 'hexdsl';
                url                 
------------------------------------
 https://share.tube/accounts/hexdsl
(1 row)
```

**Comment by Chocobozzz** [comment]
It seems the share.tube instance did something wrong in the database: this actor was previously an account and now it's a channel :thinking:

**Comment by karthanistyr** [comment]
Both exist, though: account and channel.

https://share.tube/accounts/hexdsl/
https://share.tube/video-channels/hexdsl/

**Comment by Chocobozzz** [comment]
Oh okay I understand now. It was an old bug we fixed. It requires manual action by admins to fix this. [This patch](https://github.com/Chocobozzz/PeerTube/commit/77e0851758595de2642b405cff8960f02ced60eb) will force them to fix their database.

Thanks for this issue.
