### ISSUE TITLE
Cannot follow anymore intances

### ISSUE THREAD

**Issue by grondinm** [Chocobozzz/PeerTube#2321]
**What happened?**

I am trying to follow another instance. This used to work. Last instance i followed was on Nov 22nd but now the job(s) fails.

Log shows:

error[12/10/2019, 2:12:05 PM] Cannot execute job 5085 in queue activitypub-http-fetcher. { "payload": { "uri": "https://video.gafamfree.party/accounts/peertube/outbox", "type": "activity" }, "err": { "stack": "Error: ESOCKETTIMEDOUT\n at ClientRequest.<anonymous> (/srv/peertube/versions/peertube-v2.0.0/node_modules/request/request.js:816:19)\n at Object.onceWrapper (events.js:286:20)\n at ClientRequest.emit (events.js:198:13)\n at TLSSocket.emitRequestTimeout (_http_client.js:662:40)\n at Object.onceWrapper (events.js:286:20)\n at TLSSocket.emit (events.js:198:13)\n at TLSSocket.Socket._onTimeout (net.js:443:8)\n at ontimeout (timers.js:436:11)\n at tryOnTimeout (timers.js:300:5)\n at listOnTimeout (timers.js:263:5)\n at Timer.processTimers (timers.js:223:10)", "message": "ESOCKETTIMEDOUT", "code": "ESOCKETTIMEDOUT", "connect": false } } 

**Additional information**
* PeerTube version or URL: v2.0.0 https://video.gcfam.net

* NodeJS version:  10.17.0

Running Arch linux and apache as the webserver. 

Everything else seems to be fine with my instance. I'm not 100% sure when this would have stopped working. Upgrade to V2.0.0 was done on Nov14th. I have not tried adding many instances but i have tried 2 different ones with the same results.

If i curl https://video.gafamfree.party/accounts/peertube/outbox from my server i get a response. It does take about 5 seconds but get a response.

The job stays under delayed for a while but then just fails.

Seems its a simple connection timeout issue...how can i make peertube wait a little longer before timing out? Pardon the stupid question i feel this is.

**Comment by grondinm** [comment]
Well i'll be. It does seem to have sorted itself out...could have just been extra high latency on either side. Guess i'll be more patient next time.
