### ISSUE TITLE
Peertube 2.x upload video is not working

### ISSUE THREAD

**Issue by ne-vlezay80** [Chocobozzz/PeerTube#2364]
**What happened?**

Upload video is not working

**What do you expect to happen instead?**

**Steps to reproduce:**

1. Upload new video from local instance

2.

3.

**Additional information**
* PeerTube version or URL: 2.0.0.0
* Browser name/version: Firefox 67
* NodeJS version: v10.18.0

* Link to browser console log if useful:
* Link to server log if useful (journalctl or /var/www/peertube/storage/logs/):
```
 "err": "SequelizeValidationError: Validation error: \"http://www.peertube.ne-vlezay80/videos/watch/f6f6d006-c395-48e0-8133-05ea2d3b14d6\" is not a valid url.\n    at Promise.all.then (/srv/http/peertube/versions/peertube-v2.0.0/node_modules/sequelize/lib/instance-validator.js:74:15)\n    at tryCatcher (/srv/http/peertube/versions/peertube-v2.0.0/node_modules/bluebird/js/release/util.js:16:23)\n    at Promise._settlePromiseFromHandler (/srv/http/peertube/versions/peertube-v2.0.0/node_modules/bluebird/js/release/promise.js:547:31)\n    at Promise._settlePromise (/srv/http/peertube/versions/peertube-v2.0.0/node_modules/bluebird/js/release/promise.js:604:18)\n    at Promise._settlePromise0 (/srv/http/peertube/versions/peertube-v2.0.0/node_modules/bluebird/js/release/promise.js:649:10)\n    at Promise._settlePromises (/srv/http/peertube/versions/peertube-v2.0.0/node_modules/bluebird/js/release/promise.js:729:18)\n    at Promise._fulfill (/srv/http/peertube/versions/peertube-v2.0.0/node_modules/bluebird/js/release/promise.js:673:18)\n    at PromiseArray._resolve (/srv/http/peertube/versions/peertube-v2.0.0/node_modules/bluebird/js/release/promise_array.js:127:19)\n    at PromiseArray._promiseFulfilled (/srv/http/peertube/versions/peertube-v2.0.0/node_modules/bluebird/js/release/promise_array.js:145:14)\n    at Promise._settlePromise (/srv/http/peertube/versions/peertube-v2.0.0/node_modules/bluebird/js/release/promise.js:609:26)\n    at Promise._settlePromise0 (/srv/http/peertube/versions/peertube-v2.0.0/node_modules/bluebird/js/release/promise.js:649:10)\n    at Promise._settlePromises (/srv/http/peertube/versions/peertube-v2.0.0/node_modules/bluebird/js/release/promise.js:729:18)\n    at Promise._fulfill (/srv/http/peertube/versions/peertube-v2.0.0/node_modules/bluebird/js/release/promise.js:673:18)\n    at Promise._resolveCallback (/srv/http/peertube/versions/peertube-v2.0.0/node_modules/bluebird/js/release/promise.js:466:57)\n    at Promise._settlePromiseFromHandler (/srv/http/peertube/versions/peertube-v2.0.0/node_modules/bluebird/js/release/promise.js:559:17)\n    at Promise._settlePromise (/srv/http/peertube/versions/peertube-v2.0.0/node_modules/bluebird/js/release/promise.js:604:18)\n    at Promise._settlePromise0 (/srv/http/peertube/versions/peertube-v2.0.0/node_modules/bluebird/js/release/promise.js:649:10)\n    at Promise._settlePromises (/srv/http/peertube/versions/peertube-v2.0.0/node_modules/bluebird/js/release/promise.js:729:18)\n    at Promise._fulfill (/srv/http/peertube/versions/peertube-v2.0.0/node_modules/bluebird/js/release/promise.js:673:18)\n    at PromiseArray._resolve (/srv/http/peertube/versions/peertube-v2.0.0/node_modules/bluebird/js/release/promise_array.js:127:19)\n    at PromiseArray._promiseFulfilled (/srv/http/peertube/versions/peertube-v2.0.0/node_modules/bluebird/js/release/promise_array.js:145:14)\n    at Promise._settlePromise (/srv/http/peertube/versions/peertube-v2.0.0/node_modules/bluebird/js/release/promise.js:609:26)\n    at Promise._settlePromise0 (/srv/http/peertube/versions/peertube-v2.0.0/node_modules/bluebird/js/release/promise.js:649:10)\n    at Promise._settlePromises (/srv/http/peertube/versions/peertube-v2.0.0/node_modules/bluebird/js/release/promise.js:729:18)\n    at Promise._fulfill (/srv/http/peertube/versions/peertube-v2.0.0/node_modules/bluebird/js/release/promise.js:673:18)\n    at Promise._resolveCallback (/srv/http/peertube/versions/peertube-v2.0.0/node_modules/bluebird/js/release/promise.js:466:57)\n    at Promise._settlePromiseFromHandler (/srv/http/peertube/versions/peertube-v2.0.0/node_modules/bluebird/js/release/promise.js:559:17)\n    at Promise._settlePromise (/srv/http/peertube/versions/peertube-v2.0.0/node_modules/bluebird/js/release/promise.js:604:18)\n    at Promise._settlePromise0 (/srv/http/peertube/versions/peertube-v2.0.0/node_modules/bluebird/js/release/promise.js:649:10)\n    at Promise._settlePromises (/srv/http/peertube/versions/peertube-v2.0.0/node_modules/bluebird/js/release/promise.js:729:18)\n    at Promise._fulfill (/srv/http/peertube/versions/peertube-v2.0.0/node_modules/bluebird/js/release/promise.js:673:18)\n    at Promise._resolveCallback (/srv/http/peertube/versions/peertube-v2.0.0/node_modules/bluebird/js/release/promise.js:466:57)\n    at Promise._settlePromiseFromHandler (/srv/http/peertube/versions/peertube-v2.0.0/node_modules/bluebird/js/release/promise.js:559:17)\n    at Promise._settlePromise (/srv/http/peertube/versions/peertube-v2.0.0/node_modules/bluebird/js/release/promise.js:604:18)\n    at Promise._settlePromise0 (/srv/http/peertube/versions/peertube-v2.0.0/node_modules/bluebird/js/release/promise.js:649:10)\n    at Promise._settlePromises (/srv/http/peertube/versions/peertube-v2.0.0/node_modules/bluebird/js/release/promise.js:729:18)\n    at Promise._fulfill (/srv/http/peertube/versions/peertube-v2.0.0/node_modules/bluebird/js/release/promise.js:673:18)\n    at PromiseArray._resolve (/srv/http/peertube/versions/peertube-v2.0.0/node_modules/bluebird/js/release/promise_array.js:127:19)\n    at PromiseArray._promiseFulfilled (/srv/http/peertube/versions/peertube-v2.0.0/node_modules/bluebird/js/release/promise_array.js:145:14)\n    at Promise._settlePromise (/srv/http/peertube/versions/peertube-v2.0.0/node_modules/bluebird/js/release/promise.js:609:26)",
  "level": "error",
  "message": "Error in controller.",
  "label": "www.peertube.ne-vlezay80:80",
  "timestamp": "2019-12-28T20:57:18.047Z"
}
{
  "message": "2a01:d0:c353:82::10 - - [28/Dec/2019:20:57:18 +0000] \"POST /api/v1/videos/upload HTTP/1.0\" 500 - \"http://www.peertube.ne-vlezay80/videos/upload\" \"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:69.0) Gecko/20100101 Firefox/69.0\"\n",
```

**Comment by Chocobozzz** [comment]
It seems `ne-vlezay80` is not a valid TLD from our validator library perspective: https://github.com/validatorjs/validator.js/blob/master/lib/isFQDN.js#L40
