### ISSUE TITLE
Service wont start after update.

### ISSUE THREAD

**Issue by ReK2Fernandez** [Chocobozzz/PeerTube#241]
```
 peertube.service - PeerTube daemon
   Loaded: loaded (/etc/systemd/system/peertube.service; disabled; vendor preset: enabled)
   Active: inactive (dead)

Jan 24 21:17:45 video peertube[18280]: npm ERR! This is probably not a problem with npm. There is likely additional logging output abov
Jan 24 21:17:45 video peertube[18280]: npm ERR! A complete log of this run can be found in:
Jan 24 21:17:45 video peertube[18280]: npm ERR!     /home/peertube/.npm/_logs/2018-01-24T21_17_45_444Z-debug.log
Jan 24 21:17:45 video systemd[1]: peertube.service: Main process exited, code=exited, status=1/FAILURE
Jan 24 21:17:45 video systemd[1]: peertube.service: Unit entered failed state.
Jan 24 21:17:45 video systemd[1]: peertube.service: Failed with result 'exit-code'.
Jan 24 21:17:45 video systemd[1]: peertube.service: Service hold-off time over, scheduling restart.
Jan 24 21:17:45 video systemd[1]: Stopped PeerTube daemon.
Jan 24 21:17:45 video systemd[1]: peertube.service: Start request repeated too quickly.
Jan 24 21:17:45 video systemd[1]: Failed to start PeerTube daemon.
```
and /home/peertube/.npm/_logs/2018-01-24T21_17_45_444Z-debug.log

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'start' ]
2 info using npm@5.6.0
3 info using node@v8.9.4
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle peertube@0.0.15-alpha~prestart: peertube@0.0.15-alpha
6 info lifecycle peertube@0.0.15-alpha~start: peertube@0.0.15-alpha
7 verbose lifecycle peertube@0.0.15-alpha~start: unsafe-perm in lifecycle true
8 verbose lifecycle peertube@0.0.15-alpha~start: PATH: /usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/var/www/PeerTube/versions/peertube-v0.0.15-alpha/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
9 verbose lifecycle peertube@0.0.15-alpha~start: CWD: /var/www/PeerTube/versions/peertube-v0.0.15-alpha
10 silly lifecycle peertube@0.0.15-alpha~start: Args: [ '-c', 'node dist/server' ]
11 silly lifecycle peertube@0.0.15-alpha~start: Returned: code: 1  signal: null
12 info lifecycle peertube@0.0.15-alpha~start: Failed to exec start script
13 verbose stack Error: peertube@0.0.15-alpha start: `node dist/server`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:285:16)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at EventEmitter.emit (events.js:214:7)
13 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at ChildProcess.emit (events.js:214:7)
13 verbose stack     at maybeClose (internal/child_process.js:925:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
14 verbose pkgid peertube@0.0.15-alpha
15 verbose cwd /var/www/PeerTube/versions/peertube-v0.0.15-alpha
16 verbose Linux 4.4.0-104-generic
17 verbose argv "/usr/bin/node" "/usr/bin/npm" "start"
18 verbose node v8.9.4
19 verbose npm  v5.6.0
20 error code ELIFECYCLE
21 error errno 1
22 error peertube@0.0.15-alpha start: `node dist/server`
22 error Exit status 1
23 error Failed at the peertube@0.0.15-alpha start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

Im not familiar with npm so not sure whats the issue.. do note my folder name is PeerTube not peertube but I did obviously change this on the update command :) 

reverting to older version works.
```
● peertube.service - PeerTube daemon
   Loaded: loaded (/etc/systemd/system/peertube.service; disabled; vendor preset: enabled)
   Active: active (running) since Wed 2018-01-24 21:24:40 UTC; 8s ago
 Main PID: 18446 (npm)
    Tasks: 21
   Memory: 121.3M
      CPU: 3.389s
   CGroup: /system.slice/peertube.service
           ├─18446 npm                    
           ├─18459 sh -c node dist/server
           └─18460 peertube        

Jan 24 21:24:46 video peertube[18446]: debug: [video.hispagatos.org:443] Executing (default): SELECT i.relname AS name, ix.indisprimary
Jan 24 21:24:46 video peertube[18446]: debug: [video.hispagatos.org:443] Executing (default): CREATE TABLE IF NOT EXISTS "videoComment"
Jan 24 21:24:46 video peertube[18446]: debug: [video.hispagatos.org:443] Executing (default): SELECT i.relname AS name, ix.indisprimary
Jan 24 21:24:46 video peertube[18446]: debug: [video.hispagatos.org:443] Executing (default): SELECT count(*) AS "count" FROM "applicat
Jan 24 21:24:46 video peertube[18446]: debug: [video.hispagatos.org:443] Executing (default): SELECT count(*) AS "count" FROM "oAuthCli
Jan 24 21:24:46 video peertube[18446]: debug: [video.hispagatos.org:443] Executing (default): SELECT count(*) AS "count" FROM "user" AS
Jan 24 21:24:46 video peertube[18446]: info: [video.hispagatos.org:443] Jobs scheduler activitypub-http activated.
Jan 24 21:24:46 video peertube[18446]: info: [video.hispagatos.org:443] Jobs scheduler transcoding activated.
Jan 24 21:24:46 video peertube[18446]: info: [video.hispagatos.org:443] Server listening on port 9000
Jan 24 21:24:46 video peertube[18446]: info: [video.hispagatos.org:443] Web server: https://video.hispagatos.org
```

**Comment by DimitriGilbert** [comment]
I think you need to update your dependencies, I had the same issue, resolved with a `yarn install --pure-lockfile`

**Comment by ReK2Fernandez** [comment]
@DimitriGilbert This may be it! going to run and report back.

**Comment by DimitriGilbert** [comment]
I'm fairly new to contributing here so I'm not sure I can be of much more help except for the usual culprit : dependencies and permissions. 
Looking for the 'unsafe-perm in lifecycle true' first error, usually people go at it by removing the node_modules folder, cleaning their dependency cache and reinstalling dependencies from scratch
Hope it helps :)

**Comment by Chocobozzz** [comment]
@ReK2Fernandez npm debugs are not very useful, please give us the peertube logs (`journalctl -eu peertube`)

**Comment by ReK2Fernandez** [comment]
@Chocobozzz true forgot about jourlnalctl :)  ill run it after work thanks

**Comment by ReK2Fernandez** [comment]
@Chocobozzz @DimitriGilbert 
```
peertube@video:~/PeerTube/peertube-latest$ sudo journalctl -n 200  -eu peertube 
Jan 26 22:21:13 video peertube[9575]:     at Object.<anonymous> (/var/www/PeerTube/versions/peertube-v0.0.15-alpha/dist/server/initializers/constants.js:112:23)
Jan 26 22:21:13 video peertube[9575]:     at Module._compile (module.js:643:30)
Jan 26 22:21:13 video peertube[9575]:     at Object.Module._extensions..js (module.js:654:10)
Jan 26 22:21:13 video peertube[9575]:     at Module.load (module.js:556:32)
Jan 26 22:21:13 video peertube[9575]:     at tryModuleLoad (module.js:499:12)
Jan 26 22:21:13 video peertube[9575]:     at Function.Module._load (module.js:491:3)
Jan 26 22:21:13 video peertube[9575]:     at Module.require (module.js:587:17)
Jan 26 22:21:13 video peertube[9575]:     at require (internal/module.js:11:18)
Jan 26 22:21:13 video peertube[9575]:     at Object.<anonymous> (/var/www/PeerTube/versions/peertube-v0.0.15-alpha/dist/server/initializers/index.js:7:10)
Jan 26 22:21:13 video peertube[9575]:     at Module._compile (module.js:643:30)
Jan 26 22:21:13 video peertube[9575]:     at Object.Module._extensions..js (module.js:654:10)
Jan 26 22:21:13 video peertube[9575]:     at Module.load (module.js:556:32)
Jan 26 22:21:13 video peertube[9575]:     at tryModuleLoad (module.js:499:12)
Jan 26 22:21:13 video peertube[9575]:     at Function.Module._load (module.js:491:3)
Jan 26 22:21:13 video peertube[9575]:     at Module.require (module.js:587:17)
Jan 26 22:21:13 video peertube[9575]:     at require (internal/module.js:11:18)
Jan 26 22:21:13 video peertube[9575]:     at Object.<anonymous> (/var/www/PeerTube/versions/peertube-v0.0.15-alpha/dist/server/helpers/custom-validators/users.js:6:24)
Jan 26 22:21:13 video peertube[9575]:     at Module._compile (module.js:643:30)
Jan 26 22:21:13 video peertube[9575]:     at Object.Module._extensions..js (module.js:654:10)
Jan 26 22:21:13 video peertube[9575]:     at Module.load (module.js:556:32)
Jan 26 22:21:13 video peertube[9575]:     at tryModuleLoad (module.js:499:12)
Jan 26 22:21:13 video peertube[9575]: npm ERR! code ELIFECYCLE
Jan 26 22:21:13 video peertube[9575]: npm ERR! errno 1
Jan 26 22:21:13 video peertube[9575]: npm ERR! peertube@0.0.15-alpha start: `node dist/server`
Jan 26 22:21:13 video peertube[9575]: npm ERR! Exit status 1
Jan 26 22:21:13 video peertube[9575]: npm ERR!
Jan 26 22:21:13 video peertube[9575]: npm ERR! Failed at the peertube@0.0.15-alpha start script.
Jan 26 22:21:13 video peertube[9575]: npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
Jan 26 22:21:13 video peertube[9575]: npm ERR! A complete log of this run can be found in:
Jan 26 22:21:13 video peertube[9575]: npm ERR!     /home/peertube/.npm/_logs/2018-01-26T22_21_13_149Z-debug.log
Jan 26 22:21:13 video systemd[1]: peertube.service: Main process exited, code=exited, status=1/FAILURE
Jan 26 22:21:13 video systemd[1]: peertube.service: Unit entered failed state.
Jan 26 22:21:13 video systemd[1]: peertube.service: Failed with result 'exit-code'.
Jan 26 22:21:13 video systemd[1]: peertube.service: Service hold-off time over, scheduling restart.
Jan 26 22:21:13 video systemd[1]: Stopped PeerTube daemon.
Jan 26 22:21:13 video systemd[1]: peertube.service: Start request repeated too quickly.
Jan 26 22:21:13 video systemd[1]: Failed to start PeerTube daemon.
```

**Comment by ReK2Fernandez** [comment]
@Chocobozzz @DimitriGilbert sorry to re-ask but im eager to try the new things, any idea on what issues it pop above? seem JS stuff?

**Comment by Chocobozzz** [comment]
Your cut the stack trace of your logs. Please copy paste more lines

**Comment by ReK2Fernandez** [comment]
@Chocobozzz hmm sorry about that I though I pasted the whole thing.. but not much was missing..
```
Jan 30 05:32:50 video systemd[1]: Stopped PeerTube daemon.
Jan 30 05:32:50 video systemd[1]: Started PeerTube daemon.
Jan 30 05:32:50 video peertube[10355]: > peertube@0.0.15-alpha start /var/www/PeerTube/versions/peertube-v0.0.15-alpha
Jan 30 05:32:50 video peertube[10355]: > node dist/server
Jan 30 05:32:51 video peertube[10355]: /var/www/PeerTube/versions/peertube-v0.0.15-alpha/node_modules/config/lib/config.js:181
Jan 30 05:32:51 video peertube[10355]:     throw new Error('Configuration property "' + property + '" is not defined');
Jan 30 05:32:51 video peertube[10355]:     ^
Jan 30 05:32:51 video peertube[10355]: Error: Configuration property "log.level" is not defined
Jan 30 05:32:51 video peertube[10355]:     at Config.get (/var/www/PeerTube/versions/peertube-v0.0.15-alpha/node_modules/config/lib/config.js:181:11)
Jan 30 05:32:51 video peertube[10355]:     at Object.<anonymous> (/var/www/PeerTube/versions/peertube-v0.0.15-alpha/dist/server/initializers/constants.js:112:23)
Jan 30 05:32:51 video peertube[10355]:     at Module._compile (module.js:643:30)
Jan 30 05:32:51 video peertube[10355]:     at Object.Module._extensions..js (module.js:654:10)
Jan 30 05:32:51 video peertube[10355]:     at Module.load (module.js:556:32)
Jan 30 05:32:51 video peertube[10355]:     at tryModuleLoad (module.js:499:12)
Jan 30 05:32:51 video peertube[10355]:     at Function.Module._load (module.js:491:3)
Jan 30 05:32:51 video peertube[10355]:     at Module.require (module.js:587:17)
Jan 30 05:32:51 video peertube[10355]:     at require (internal/module.js:11:18)
Jan 30 05:32:51 video peertube[10355]:     at Object.<anonymous> (/var/www/PeerTube/versions/peertube-v0.0.15-alpha/dist/server/initializers/index.js:7:10)
Jan 30 05:32:51 video peertube[10355]:     at Module._compile (module.js:643:30)
Jan 30 05:32:51 video peertube[10355]:     at Object.Module._extensions..js (module.js:654:10)
Jan 30 05:32:51 video peertube[10355]:     at Module.load (module.js:556:32)
Jan 30 05:32:51 video peertube[10355]:     at tryModuleLoad (module.js:499:12)
Jan 30 05:32:51 video peertube[10355]:     at Function.Module._load (module.js:491:3)
Jan 30 05:32:51 video peertube[10355]:     at Module.require (module.js:587:17)
Jan 30 05:32:51 video peertube[10355]:     at require (internal/module.js:11:18)
Jan 30 05:32:51 video peertube[10355]:     at Object.<anonymous> (/var/www/PeerTube/versions/peertube-v0.0.15-alpha/dist/server/helpers/custom-validators/users.js:6:24)
Jan 30 05:32:51 video peertube[10355]:     at Module._compile (module.js:643:30)
Jan 30 05:32:51 video peertube[10355]:     at Object.Module._extensions..js (module.js:654:10)
Jan 30 05:32:51 video peertube[10355]:     at Module.load (module.js:556:32)
Jan 30 05:32:51 video peertube[10355]:     at tryModuleLoad (module.js:499:12)
Jan 30 05:32:51 video peertube[10355]: npm ERR! code ELIFECYCLE
Jan 30 05:32:51 video peertube[10355]: npm ERR! errno 1
Jan 30 05:32:51 video peertube[10355]: npm ERR! peertube@0.0.15-alpha start: `node dist/server`
Jan 30 05:32:51 video peertube[10355]: npm ERR! Exit status 1
Jan 30 05:32:51 video peertube[10355]: npm ERR!
Jan 30 05:32:51 video peertube[10355]: npm ERR! Failed at the peertube@0.0.15-alpha start script.
Jan 30 05:32:51 video peertube[10355]: npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
Jan 30 05:32:51 video peertube[10355]: npm ERR! A complete log of this run can be found in:
Jan 30 05:32:51 video peertube[10355]: npm ERR!     /home/peertube/.npm/_logs/2018-01-30T05_32_51_812Z-debug.log
Jan 30 05:32:51 video systemd[1]: peertube.service: Main process exited, code=exited, status=1/FAILURE
Jan 30 05:32:51 video systemd[1]: peertube.service: Unit entered failed state.
Jan 30 05:32:51 video systemd[1]: peertube.service: Failed with result 'exit-code'.
```
seems like a java script issue

**Comment by ReK2Fernandez** [comment]
ok LOL LOL nevermind turns out the fix is right but did not respect .yml formatting ... I added the right formatting and now it works.!  closing this, thanks for the help.
