### ISSUE TITLE
Failure to reset the password for root

### ISSUE THREAD

**Issue by tcitworld** [Chocobozzz/PeerTube#243]
Environment : 
* Node v8.9.4
* Peertube v0.0.15

```
cd /var/www/peertube/peertube-latest && NODE_CONFIG_DIR=/var/www/peertube/config NODE_ENV=production npm run reset-password -- -u root
```

```
> peertube@0.0.15-alpha reset-password /var/www/peertube/versions/peertube-v0.0.15-alpha
> ts-node ./scripts/reset-password.ts "-u" "root"

[videos.tcit.fr:443] 2018-01-03 22:44:14.726 error: uncaughtException: ⨯ Unable to compile TypeScript
server/helpers/custom-validators/videos.ts (71,63): Namespace 'global.Express' has no exported member 'Multer'. (2694)
server/helpers/custom-validators/videos.ts (71,89): Namespace 'global.Express' has no exported member 'Multer'. (2694)
TSError: ⨯ Unable to compile TypeScript
server/helpers/custom-validators/videos.ts (71,63): Namespace 'global.Express' has no exported member 'Multer'. (2694)
server/helpers/custom-validators/videos.ts (71,89): Namespace 'global.Express' has no exported member 'Multer'. (2694)
    at getOutput (/var/www/peertube/versions/peertube-v0.0.15-alpha/node_modules/ts-node/src/index.ts:307:15)
    at /var/www/peertube/versions/peertube-v0.0.15-alpha/node_modules/ts-node/src/index.ts:336:16
    at Object.compile (/var/www/peertube/versions/peertube-v0.0.15-alpha/node_modules/ts-node/src/index.ts:498:11)
    at Module.m._compile (/var/www/peertube/versions/peertube-v0.0.15-alpha/node_modules/ts-node/src/index.ts:392:43)
    at Module._extensions..js (module.js:654:10)
    at Object.require.extensions.(anonymous function) [as .ts] (/var/www/peertube/versions/peertube-v0.0.15-alpha/node_modules/ts-node/src/index.ts:395:12)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/var/www/peertube/versions/peertube-v0.0.15-alpha/server/models/video/video.ts:18:1)
    at Module._compile (module.js:643:30)
    at Module.m._compile (/var/www/peertube/versions/peertube-v0.0.15-alpha/node_modules/ts-node/src/index.ts:392:23)
    at Module._extensions..js (module.js:654:10)
    at Object.require.extensions.(anonymous function) [as .ts] (/var/www/peertube/versions/peertube-v0.0.15-alpha/node_modules/ts-node/src/index.ts:395:12)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/var/www/peertube/versions/peertube-v0.0.15-alpha/server/models/video/video-channel.ts:12:1) {
```

**Comment by tcitworld** [comment]
Related to https://github.com/Chocobozzz/PeerTube/issues/189

**Comment by Chocobozzz** [comment]
Should be fixed in the next release: https://github.com/Chocobozzz/PeerTube/commit/f96d1df32927844ce1412e0e1a522ecc02a719f6
