### ISSUE TITLE
v2.1.0-rc1 upgrade: SequelizeDatabaseError: column videoFile.videoStreamingPlaylistId does not exist

### ISSUE THREAD

**Issue by anoadragon453** [Chocobozzz/PeerTube#2453]
**What happened?**

I received the following error when running the script recommended by the [v2.1.0-rc1 upgrade notes](https://github.com/Chocobozzz/PeerTube/releases/tag/v2.1.0-rc.1):

```
# cd /var/www/peertube/peertube-latest && sudo -H -u peertube NODE_CONFIG_DIR=/var/www/peertube/config NODE_ENV=production node dist/scripts/migrations/peertube-2.1.js
[vault.mle.party:443] 2020-02-04 14:34:46.587 info: Creating torrents and updating database for HSL files.
{ SequelizeDatabaseError: column videoFile.videoStreamingPlaylistId does not exist
    at Query.formatError (/var/www/peertube/versions/peertube-v2.1.0-rc.1/node_modules/sequelize/lib/dialects/postgres/query.js:366:16)
    at query.catch.err (/var/www/peertube/versions/peertube-v2.1.0-rc.1/node_modules/sequelize/lib/dialects/postgres/query.js:72:18)
    at tryCatcher (/var/www/peertube/versions/peertube-v2.1.0-rc.1/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/var/www/peertube/versions/peertube-v2.1.0-rc.1/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (/var/www/peertube/versions/peertube-v2.1.0-rc.1/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (/var/www/peertube/versions/peertube-v2.1.0-rc.1/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/var/www/peertube/versions/peertube-v2.1.0-rc.1/node_modules/bluebird/js/release/promise.js:725:18)
    at _drainQueueStep (/var/www/peertube/versions/peertube-v2.1.0-rc.1/node_modules/bluebird/js/release/async.js:93:12)
    at _drainQueue (/var/www/peertube/versions/peertube-v2.1.0-rc.1/node_modules/bluebird/js/release/async.js:86:9)
    at Async._drainQueues (/var/www/peertube/versions/peertube-v2.1.0-rc.1/node_modules/bluebird/js/release/async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (/var/www/peertube/versions/peertube-v2.1.0-rc.1/node_modules/bluebird/js/release/async.js:15:14)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
  name: 'SequelizeDatabaseError',
  parent:
   { error: column videoFile.videoStreamingPlaylistId does not exist
       at Connection.parseE (/var/www/peertube/versions/peertube-v2.1.0-rc.1/node_modules/pg/lib/connection.js:604:13)
       at Connection.parseMessage (/var/www/peertube/versions/peertube-v2.1.0-rc.1/node_modules/pg/lib/connection.js:403:19)
       at Socket.<anonymous> (/var/www/peertube/versions/peertube-v2.1.0-rc.1/node_modules/pg/lib/connection.js:123:22)
       at Socket.emit (events.js:198:13)
       at addChunk (_stream_readable.js:288:12)
       at readableAddChunk (_stream_readable.js:269:11)
       at Socket.Readable.push (_stream_readable.js:224:10)
       at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
     name: 'error',
     length: 133,
     severity: 'ERROR',
     code: '42703',
     detail: undefined,
     hint: undefined,
     position: '175',
     internalPosition: undefined,
     internalQuery: undefined,
     where: undefined,
     schema: undefined,
     table: undefined,
     column: undefined,
     dataType: undefined,
     constraint: undefined,
     file: 'parse_relation.c',
     line: '3293',
     routine: 'errorMissingColumn',
     sql:
      'select "videoFile".id as id, "videoFile".resolution as resolution, "video".uuid as uuid from "videoFile" inner join "videoStreamingPlaylist" ON "videoStreamingPlaylist".id = "videoFile"."videoStreamingPlaylistId" inner join video ON video.id = "videoStreamingPlaylist"."videoId" WHERE video.remote IS FALSE',
     parameters: undefined },
  original:
   { error: column videoFile.videoStreamingPlaylistId does not exist
       at Connection.parseE (/var/www/peertube/versions/peertube-v2.1.0-rc.1/node_modules/pg/lib/connection.js:604:13)
       at Connection.parseMessage (/var/www/peertube/versions/peertube-v2.1.0-rc.1/node_modules/pg/lib/connection.js:403:19)
       at Socket.<anonymous> (/var/www/peertube/versions/peertube-v2.1.0-rc.1/node_modules/pg/lib/connection.js:123:22)
       at Socket.emit (events.js:198:13)
       at addChunk (_stream_readable.js:288:12)
       at readableAddChunk (_stream_readable.js:269:11)
       at Socket.Readable.push (_stream_readable.js:224:10)
       at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
     name: 'error',
     length: 133,
     severity: 'ERROR',
     code: '42703',
     detail: undefined,
     hint: undefined,
     position: '175',
     internalPosition: undefined,
     internalQuery: undefined,
     where: undefined,
     schema: undefined,
     table: undefined,
     column: undefined,
     dataType: undefined,
     constraint: undefined,
     file: 'parse_relation.c',
     line: '3293',
     routine: 'errorMissingColumn',
     sql:
      'select "videoFile".id as id, "videoFile".resolution as resolution, "video".uuid as uuid from "videoFile" inner join "videoStreamingPlaylist" ON "videoStreamingPlaylist".id = "videoFile"."videoStreamingPlaylistId" inner join video ON video.id = "videoStreamingPlaylist"."videoId" WHERE video.remote IS FALSE',
     parameters: undefined },
  sql:
   'select "videoFile".id as id, "videoFile".resolution as resolution, "video".uuid as uuid from "videoFile" inner join "videoStreamingPlaylist" ON "videoStreamingPlaylist".id = "videoFile"."videoStreamingPlaylistId" inner join video ON video.id = "videoStreamingPlaylist"."videoId" WHERE video.remote IS FALSE',
  parameters: undefined }
```

**What do you expect to happen instead?**

The script to not fail :) Looking at the traceback, perhaps I missed a DB migration step somewhere?

**Steps to reproduce:**

1. Run auto-upgrade script from v2.0.0 to v2.1.0-rc1 (no issues). Don't restart Peertube.

2. Run the suggested HLS video torrent commands

3. Receive error

**Additional information**
* PeerTube version or URL: v2.1.0-rc1
* Browser name/version: N/A
* NodeJS version: v10.18.1

* Link to browser console log if useful:
* Link to server log if useful (journalctl or /var/www/peertube/storage/logs/):

**Comment by Chocobozzz** [comment]
> Don't restart Peertube.

You need to restart peertube :)

**Comment by anoadragon453** [comment]
Indeed, that worked :) Thank you!
