### ISSUE TITLE
Import from URL broken on Docker with 2.1.0

### ISSUE THREAD

**Issue by Nutomic** [Chocobozzz/PeerTube#2512]
Trying to import any URL (eg youtube, or raw video file) results in the following error in the server log:
```
peertube_1  | [peertube.social:443] 2020-02-20 09:10:57.945 info: Cannot fetch information from import for URL https://video.fosdem.org/2020/AW1.125/ada_spunky.webm. {
peertube_1  |   "err": {
peertube_1  |     "stack": "Error: Command failed with exit code 127: /app/node_modules/youtube-dl/bin/youtube-dl --dump-json -f best -j --flat-playlist -- https://video.fosdem.org/2020/AW1.125/ada_spunky.webm\n    at makeError (/app/node_modules/youtube-dl/node_modules/execa/lib/error.js:56:11)\n    at handlePromise (/app/node_modules/youtube-dl/node_modules/execa/index.js:114:26)\n    at process._tickCallback (internal/process/next_tick.js:68:7)",
peertube_1  |     "message": "Command failed with exit code 127: /app/node_modules/youtube-dl/bin/youtube-dl --dump-json -f best -j --flat-playlist -- https://video.fosdem.org/2020/AW1.125/ada_spunky.webm",
peertube_1  |     "command": "/app/node_modules/youtube-dl/bin/youtube-dl --dump-json -f best -j --flat-playlist -- https://video.fosdem.org/2020/AW1.125/ada_spunky.webm",
peertube_1  |     "exitCode": 127,
peertube_1  |     "stdout": "",
peertube_1  |     "stderr": "/usr/bin/env: 'python': No such file or directory",
peertube_1  |     "failed": true,
peertube_1  |     "timedOut": false,
peertube_1  |     "isCanceled": false,
peertube_1  |     "killed": false
peertube_1  |   }
peertube_1  | }
```

This is with the image `chocobozzz/peertube:v2.1.0-buster`.

**Comment by Chocobozzz** [comment]
Duplicate with https://github.com/Chocobozzz/PeerTube/issues/2491

**Comment by Nutomic** [comment]
Sorry I forgot to search. Are you gonna make a new release with the fix?

**Comment by Chocobozzz** [comment]
Yes, but I don't really know when (next week or after the next week).
