### ISSUE TITLE
Certain types of videos don't upload/transcode properly

### ISSUE THREAD

**Issue by Casuallynoted** [Chocobozzz/PeerTube#2529]
**What happened?**
I'm having issue getting peertube to upload certain videos. I've noticed that once it finishes uploading it says an error has occurred and then returns to the video uploading screen.
I checked the logs, and this is the output:
```
Job: 3Type: video-transcodingProcessed on Mar 1, 2020, 8:20:34 PMFinished on Mar 1, 2020, 8:20:59 PM{  "type": "new-resolution",  "videoUUID": "83799e68-6acf-4e09-9cf5-b543cf361ea4",  "resolution": 480}SequelizeForeignKeyConstraintError: insert or update on table "videoFile" violates foreign key constraint "videoFile_videoId_fkey"    at Query.formatError (/var/www/peertube/versions/peertube-v2.1.1/node_modules/sequelize/lib/dialects/postgres/query.js:295:16)    at query.catch.err (/var/www/peertube/versions/peertube-v2.1.1/node_modules/sequelize/lib/dialects/postgres/query.js:72:18)    at tryCatcher (/var/www/peertube/versions/peertube-v2.1.1/node_modules/bluebird/js/release/util.js:16:23)    at Promise._settlePromiseFromHandler (/var/www/peertube/versions/peertube-v2.1.1/node_modules/bluebird/js/release/promise.js:547:31)    at Promise._settlePromise (/var/www/peertube/versions/peertube-v2.1.1/node_modules/bluebird/js/release/promise.js:604:18)    at Promise._settlePromise0 (/var/www/peertube/versions/peertube-v2.1.1/node_modules/bluebird/js/release/promise.js:649:10)    at Promise._settlePromises (/var/www/peertube/versions/peertube-v2.1.1/node_modules/bluebird/js/release/promise.js:725:18)    at _drainQueueStep (/var/www/peertube/versions/peertube-v2.1.1/node_modules/bluebird/js/release/async.js:93:12)    at _drainQueue (/var/www/peertube/versions/peertube-v2.1.1/node_modules/bluebird/js/release/async.js:86:9)    at Async._drainQueues (/var/www/peertube/versions/peertube-v2.1.1/node_modules/bluebird/js/release/async.js:102:5)    at Immediate.Async.drainQueues [as _onImmediate] (/var/www/peertube/versions/peertube-v2.1.1/node_modules/bluebird/js/release/async.js:15:14)    at runCallback (timers.js:705:18)    at tryOnImmediate (timers.js:676:5)    at processImmediate (timers.js:658:5)
```

**What do you expect to happen instead?**

I would expect it to properly transcode and create a new video entry on the Peertube instance for that video.

**Steps to reproduce:**

1. Upload mp4

2. Let it load all the way through the upload

3. Watch an error come up that it has failed, resets to video upload screen

**Additional information**
* PeerTube version or URL: videos.casually.cat
* Browser name/version: Firefox
* NodeJS version:

* Link to browser console log if useful:
* Link to server log if useful (journalctl or /var/www/peertube/storage/logs/):

**Comment by Chocobozzz** [comment]
Please enable debug logs, reproduce your issue and send me your logile by email (in my github profile).
