### ISSUE TITLE
500 on adding recently uploaded video to playlist (without a thumbnail yet)

### ISSUE THREAD

**Issue by stefanor** [Chocobozzz/PeerTube#2566]
**What happened?**

Using [these tools](https://salsa.debian.org/debconf-video-team/peertube) I uploaded a video and added it to a playlist. The add to playlist 500s, although it added.

This seems to happen a lot to some sets of videos, and not at all to others. Not sure if that's related to the video format or server load.

**What do you expect to happen instead?**

No errors.

**Steps to reproduce:**

1. Import video
1. Add it to a playlist, immediately.

Client output (without -v):

```
10:17/0 stefanor@elgar ~/git/debian/debconf-video/peertube$ ve/bin/python tools/upload_peertube.py metadata/2018/minidebconf-curitiba.yml upload.log 
INFO:client.video:Importing Assinatura de chaves: introdução to 28 from https://meetings-archive.debian.net/pub/debian-meetings/2018/mini-debconf-curitiba/02-assinatura-de-chaves-introducao.webm
INFO:client.playlist:Adding b32bf404-d732-42a3-aae4-ecbb76675e11 to playlist 83e9adc3-85b9-4b57-9134-fd11a9a4f6a6
Traceback (most recent call last):
  File "tools/upload_peertube.py", line 72, in <module>
    main()
  File "tools/upload_peertube.py", line 65, in main
    post_peertube(video, args.log)
  File "tools/upload_peertube.py", line 34, in post_peertube
    Playlist.get(playlist).add(video)
  File "/home/stefanor/git/debian/debconf-video/peertube/tools/client/playlist.py", line 37, in add
    data=data)
  File "/home/stefanor/git/debian/debconf-video/peertube/ve/lib/python3.7/site-packages/requests/sessions.py", line 578, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/home/stefanor/git/debian/debconf-video/peertube/tools/client/peertube.py", line 97, in request
    r.content or 'HTTP %i' % r.status_code, r.status_code)
client.errors.PeerTubeError: HTTP 500
```

Server log:

```
Mar 18 18:18:40 peertube peertube[28540]: [peertube.debian.social:443] 2020-03-18 18:18:40.693 info: 192.168.122.1 - - [18/Mar/2020:17:18:40 +0000] "POST /api/v1/videos/imports HTTP/1.1" 200 2685 "-" "python-requests/2.23.0"
Mar 18 18:18:40 peertube peertube[28540]: [peertube.debian.social:443] 2020-03-18 18:18:40.694 info: Processing youtubeDL video import in job 1081.
Mar 18 18:18:40 peertube peertube[28540]: [peertube.debian.social:443] 2020-03-18 18:18:40.713 info: Importing youtubeDL video https://meetings-archive.debian.net/pub/debian-meetings/2018/mini-debconf-curitiba/02-assinatura-de-chaves-introducao.webm
Mar 18 18:18:40 peertube peertube[28540]: [peertube.debian.social:443] 2020-03-18 18:18:40.895 info: 192.168.122.1 - - [18/Mar/2020:17:18:40 +0000] "GET /api/v1/video-playlists/83e9adc3-85b9-4b57-9134-fd11a9a4f6a6 HTTP/1.1" 200 1161 "-" "python-requests/2.23.0"
Mar 18 18:18:41 peertube peertube[28540]: [peertube.debian.social:443] 2020-03-18 18:18:41.153 info: Generating default thumbnail to playlist https://peertube.debian.social/video-playlists/83e9adc3-85b9-4b57-9134-fd11a9a4f6a6.
Mar 18 18:18:41 peertube peertube[28540]: [peertube.debian.social:443] 2020-03-18 18:18:41.154 error: Cannot execute addVideoInPlaylist with many retries. {
Mar 18 18:18:41 peertube peertube[28540]:   "err": {
Mar 18 18:18:41 peertube peertube[28540]:     "stack": "TypeError: Cannot read property 'filename' of undefined\n    at /srv/www/peertube/versions/peertube-v2.1.1/dist/server/controllers/api/video-playlist.js:313:99\n    at Generator.next (<anonymous>)\n    at /srv/www/peertube/versions/peertube-v2.1.1/dist/server/controllers/api/video-playlist.js:8:71\n    at new Promise (<anonymous>)\n    at __awaiter (/srv/www/peertube/versions/peertube-v2.1.1/dist/server/controllers/api/video-playlist.js:4:12)\n    at generateThumbnailForPlaylist (/srv/www/peertube/versions/peertube-v2.1.1/dist/server/controllers/api/video-playlist.js:311:12)\n    at /srv/www/peertube/versions/peertube-v2.1.1/dist/server/controllers/api/video-playlist.js:200:19\n    at Generator.next (<anonymous>)\n    at fulfilled (/srv/www/peertube/versions/peertube-v2.1.1/dist/server/controllers/api/video-playlist.js:5:58)",
Mar 18 18:18:41 peertube peertube[28540]:     "message": "Cannot read property 'filename' of undefined"
Mar 18 18:18:41 peertube peertube[28540]:   }
Mar 18 18:18:41 peertube peertube[28540]: }
Mar 18 18:18:41 peertube peertube[28540]: [peertube.debian.social:443] 2020-03-18 18:18:41.154 error: Error in controller. {
Mar 18 18:18:41 peertube peertube[28540]:   "err": "TypeError: Cannot read property 'filename' of undefined\n    at /srv/www/peertube/versions/peertube-v2.1.1/dist/server/controllers/api/video-playlist.js:313:99\n    at Generator.next (<anonymous>)\n    at /srv/www/peertube/versions/peertube-v2.1.1/dist/server/controllers/api/video-playlist.js:8:71\n    at new Promise (<anonymous>)\n    at __awaiter (/srv/www/peertube/versions/peertube-v2.1.1/dist/server/controllers/api/video-playlist.js:4:12)\n    at generateThumbnailForPlaylist (/srv/www/peertube/versions/peertube-v2.1.1/dist/server/controllers/api/video-playlist.js:311:12)\n    at /srv/www/peertube/versions/peertube-v2.1.1/dist/server/controllers/api/video-playlist.js:200:19\n    at Generator.next (<anonymous>)\n    at fulfilled (/srv/www/peertube/versions/peertube-v2.1.1/dist/server/controllers/api/video-playlist.js:5:58)"
Mar 18 18:18:41 peertube peertube[28540]: }
Mar 18 18:18:41 peertube peertube[28540]: [peertube.debian.social:443] 2020-03-18 18:18:41.155 info: 192.168.122.1 - - [18/Mar/2020:17:18:41 +0000] "POST /api/v1/video-playlists/83e9adc3-85b9-4b57-9134-fd11a9a4f6a6/videos HTTP/1.1" 500 - "-" "python-requests/2.23.0"
Mar 18 18:18:43 peertube peertube[28540]: [peertube.debian.social:443] 2020-03-18 18:18:43.218 info: Updating 35 good actor follows and 1 bad actor follows scores in cache.
```

**Additional information**
* PeerTube version or URL: https://peertube.debian.social/ (2.1.1)
* Browser name/version: Irrelevant.
* NodeJS version: 13.7.0

**Comment by stefanor** [comment]
Hrm, reading that traceback, it seems to be about the playlist not having a thumbnail yet.
Usually I create one for the playlist.

**Comment by Chocobozzz** [comment]
Thanks, should be fixed by https://github.com/Chocobozzz/PeerTube/commit/eb11373f9373bdeca5a1e7868f868d9ec3b2c7b6

We could not generate an auto thumbnail for the playlist because your video import was not finished yet.
