### ISSUE TITLE
Question about the REPL script

### ISSUE THREAD

**Issue by JohnXLivingston** [Chocobozzz/PeerTube#2610]
What is the purpose of this line, which add the context in the context:
https://github.com/Chocobozzz/PeerTube/blob/8323c435c19ac6ed1656ee8436b175bce7bd2c82/server/tools/peertube-repl.ts#L31

I think it just creates a circular reference. I don't understand the purpose.

**Comment by Chocobozzz** [comment]
I don't know, I did not create this script. If you think it's useless, please do a PR.

**Comment by JohnXLivingston** [comment]
I think it's useless and confusing, but I have a doubt. @rigelk , did you write this code?

**Comment by JohnXLivingston** [comment]
Another point: I think that the 'on("reset")' is not working. If it is supposed to reset the context, it does not.
And I don't understand what's the point of writing '.clean' when calling .reset or .r.

**Comment by rigelk** [comment]
@JohnXLivingston git blame should answer your question, and GitHub shows this functionality. I didn't.

**Comment by JohnXLivingston** [comment]
> @JohnXLivingston git blame should answer your question, and GitHub shows this functionality. I didn't.

Oops Sorry. I saw your name in the file contributor list. Probably because you merged the PR.

@McFlat , it seems that you add the REPL script. Can you answer to my above questions?

**Comment by McFlat** [comment]
I wrote the REPL script. currently it seems to be broken in version 2.1.1 the context holds all the data accessible in the REPL, line 60 uses the context

**Comment by McFlat** [comment]
Not sure how it's broken, I left it in a working state when I wrote it. I'll have to take some time to fix these errors, even in 2.0.0 the repl was broken :( 

here's the errors I'm seeing
```
[localhost:9000] 2020-04-08 18:25:26.091 error: uncaughtException: Cannot find module '@server/helpers/core-utils'
Error: Cannot find module '@server/helpers/core-utils'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/VideosTank/DataDS/troo.tube/PeerTube/dist/server/helpers/custom-validators/activitypub/actor.js:8:22)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/VideosTank/DataDS/troo.tube/PeerTube/dist/server/models/activitypub/actor.js:17:17)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/VideosTank/DataDS/troo.tube/PeerTube/dist/server/lib/activitypub/send/utils.js:13:17)
    at Module._compile (internal/modules/cjs/loader.js:778:30) {
  "error": {
    "stack": "Error: Cannot find module '@server/helpers/core-utils'\n    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)\n    at Function.Module._load (internal/modules/cjs/loader.js:562:25)\n    at Module.require (internal/modules/cjs/loader.js:692:17)\n    at require (internal/modules/cjs/helpers.js:25:18)\n    at Object.<anonymous> (/VideosTank/DataDS/troo.tube/PeerTube/dist/server/helpers/custom-validators/activitypub/actor.js:8:22)\n    at Module._compile (internal/modules/cjs/loader.js:778:30)\n    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)\n    at Module.load (internal/modules/cjs/loader.js:653:32)\n    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)\n    at Function.Module._load (internal/modules/cjs/loader.js:585:3)\n    at Module.require (internal/modules/cjs/loader.js:692:17)\n    at require (internal/modules/cjs/helpers.js:25:18)\n    at Object.<anonymous> (/VideosTank/DataDS/troo.tube/PeerTube/dist/server/models/activitypub/actor.js:17:17)\n    at Module._compile (internal/modules/cjs/loader.js:778:30)\n    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)\n    at Module.load (internal/modules/cjs/loader.js:653:32)\n    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)\n    at Function.Module._load (internal/modules/cjs/loader.js:585:3)\n    at Module.require (internal/modules/cjs/loader.js:692:17)\n    at require (internal/modules/cjs/helpers.js:25:18)\n    at Object.<anonymous> (/VideosTank/DataDS/troo.tube/PeerTube/dist/server/lib/activitypub/send/utils.js:13:17)\n    at Module._compile (internal/modules/cjs/loader.js:778:30)",
    "message": "Cannot find module '@server/helpers/core-utils'",
    "code": "MODULE_NOT_FOUND"
  },
  "stack": "Error: Cannot find module '@server/helpers/core-utils'\n    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)\n    at Function.Module._load (internal/modules/cjs/loader.js:562:25)\n    at Module.require (internal/modules/cjs/loader.js:692:17)\n    at require (internal/modules/cjs/helpers.js:25:18)\n    at Object.<anonymous> (/VideosTank/DataDS/troo.tube/PeerTube/dist/server/helpers/custom-validators/activitypub/actor.js:8:22)\n    at Module._compile (internal/modules/cjs/loader.js:77
      "function": null,
      "line": 8,
      "method": null,
      "native": false
    },
    {
      "column": 30,
      "file": "internal/modules/cjs/loader.js",
      "function": "Module._compile",
      "line": 778,
      "method": "_compile",
      "native": false
    },
    {
      "column": 10,
      "file": "internal/modules/cjs/loader.js",
      "function": "Module._extensions..js",
      "line": 789,
      "method": ".js",
      "native": false
    },
    {
      "column": 32,
      "file": "internal/modules/cjs/loader.js",
      "function": "Module.load",
      "line": 653,
      "method": "load",
      "native": false
    },
    {
      "column": 12,
      "file": "internal/modules/cjs/loader.js",
      "function": "tryModuleLoad",
      "line": 593,
      "method": null,
      "native": false
    },
    {
      "column": 3,
      "file": "internal/modules/cjs/loader.js",
      "function": "Module._load",
      "line": 585,
      "method": "_load",
      "native": false
    },
    {
      "column": 17,
      "file": "internal/modules/cjs/loader.js",
      "function": "Module.require",
      "line": 692,
      "method": "require",
      "native": false
    },
    {
      "column": 18,
      "file": "internal/modules/cjs/helpers.js",
      "function": "requir
      "file": "internal/modules/cjs/loader.js",
      "function": "Module.load",
      "line": 653,
      "method": "load",
      "native": false
    },
    {
      "column": 12,
      "file": "internal/modules/cjs/loader.js",
      "function": "tryModuleLoad",
      "line": 593,
      "method": null,
      "native": false
    },
    {
      "column": 3,
      "file": "internal/modules/cjs/loader.js",
      "function": "Module._load",
      "line": 585,
      "method": "_load",
      "native": false
    },
    {
      "column": 17,
      "file": "internal/modules/cjs/loader.js",
      "function": "Module.require",
      "line": 692,
      "method": "require",
      "native": false
    },
    {
      "column": 18,
      "file": "internal/modules/cjs/helpers.js",
      "function": "require",
      "line": 25,
      "method": null,
      "native": false
    },
    {
      "column": 17,
      "file": "/VideosTank/DataDS/troo.tube/PeerTube/dist/server/lib/activitypub/send/utils.js",
      "function": null,
      "line": 13,
      "method": null,
      "native": false
    },
    {
      "column": 30,
      "file": "internal/modules/cjs/loader.js",
      "function": "Module._compile",
      "line": 778,
      "method": "_compile",
      "native": false
    }
  ]
}
```

**Comment by Chocobozzz** [comment]
My bad, I fixed this crash in https://github.com/Chocobozzz/PeerTube/commit/00c228363f0db1d181d546eebb0c7ec3eb487976

**Comment by JohnXLivingston** [comment]
> I wrote the REPL script. currently it seems to be broken in version 2.1.1 the context holds all the data accessible in the REPL, line 60 uses the context

My point is that the context on line 31 makes the line 60 adding the context into itself.
The resulting object will be like:
`{
  context: {
    context: { ... },
    repl: ...,
    ...
  },
  repl: ...,
  ...
`

**Comment by Chocobozzz** [comment]
@JohnXLivingston Circular references in JSON objects in nodejs are correctly handled. So it should not hurt.

**Comment by JohnXLivingston** [comment]
No, you are right, it should not hurt. I just try to understand if it is useful for something.
