### ISSUE TITLE
Unable to create new account

### ISSUE THREAD

**Issue by aerogus** [Chocobozzz/PeerTube#2620]
**What happened?**

I am unable to create any new account in my instance with an administrator account in the back office nor with the public form. (My instance allow new subscriber)

**What do you expect to happen instead?**

A new account to be created, with front form or with the tool for admin.

**Steps to reproduce:**

1. Go https://videos.adhocmusic.com/signup

2. Fil the form step 1 and 2

3. Constat the error message: "Le serveur rencontre une erreur. Merci de réessayer plus tard."

It seems there is an SQL error

My instance has started with early Peertube versions (<v1) and has done migrations regularly through the time.

* Link to browser console log if useful:

`Backend returned code 500, errorMessage is: Le serveur rencontre une erreur. Merci de réessayer plus tard.`

**Additional information**
* PeerTube version or URL: 2.1.1
* Browser name/version: Firefox 75
* NodeJS version: v10.19.0

* Link to server log if useful (journalctl or /var/www/peertube/storage/logs/):

```
{"message":"x.x.x.x - - [09/Apr/2020:19:16:19 +0000] \"POST /api/v1/users/register HTTP/1.0\" 500 - \"https://videos.adhocmusic.com/signup\" \"Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:74.0) Gecko/20100101 Firefox/74.0\"\n","level":"info","label":"videos.adhocmusic.com:443","timestamp":"2020-04-09T19:16:19.095Z"}
{"err":{"stack":"SequelizeDatabaseError: une valeur NULL viole la contrainte NOT NULL de la colonne « id »\n    at Query.formatError (/var/www/peertube/versions/peertube-v2.1.1/node_modules/sequelize/lib/dialects/postgres/query.js:366:16)\n    at query.catch.err (/var/www/peertube/versions/peertube-v2.1.1/node_modules/sequelize/lib/dialects/postgres/query.js:72:18)\n    at tryCatcher (/var/www/peertube/versions/peertube-v2.1.1/node_modules/bluebird/js/release/util.js:16:23)\n    at Promise._settlePromiseFromHandler (/var/www/peertube/versions/peertube-v2.1.1/node_modules/bluebird/js/release/promise.js:547:31)\n    at Promise._settlePromise (/var/www/peertube/versions/peertube-v2.1.1/node_modules/bluebird/js/release/promise.js:604:18)\n    at Promise._settlePromise0 (/var/www/peertube/versions/peertube-v2.1.1/node_modules/bluebird/js/release/promise.js:649:10)\n    at Promise._settlePromises (/var/www/peertube/versions/peertube-v2.1.1/node_modules/bluebird/js/release/promise.js:725:18)\n    at _drainQueueStep (/var/www/peertube/versions/peertube-v2.1.1/node_modules/bluebird/js/release/async.js:93:12)\n    at _drainQueue (/var/www/peertube/versions/peertube-v2.1.1/node_modules/bluebird/js/release/async.js:86:9)\n    at Async._drainQueues (/var/www/peertube/versions/peertube-v2.1.1/node_modules/bluebird/js/release/async.js:102:5)\n    at Immediate.Async.drainQueues [as _onImmediate] (/var/www/peertube/versions/peertube-v2.1.1/node_modules/bluebird/js/release/async.js:15:14)\n    at runCallback (timers.js:705:18)\n    at tryOnImmediate (timers.js:676:5)\n    at processImmediate (timers.js:658:5)","message":"une valeur NULL viole la contrainte NOT NULL de la colonne « id »","name":"SequelizeDatabaseError","parent":{"stack":"error: une valeur NULL viole la contrainte NOT NULL de la colonne « id »\n    at Connection.parseE (/var/www/peertube/versions/peertube-v2.1.1/node_modules/pg/lib/connection.js:604:13)\n    at Connection.parseMessage (/var/www/peertube/versions/peertube-v2.1.1/node_modules/pg/lib/connection.js:403:19)\n    at Socket.<anonymous> (/var/www/peertube/versions/peertube-v2.1.1/node_modules/pg/lib/connection.js:123:22)\n    at Socket.emit (events.js:198:13)\n    at addChunk (_stream_readable.js:288:12)\n    at readableAddChunk (_stream_readable.js:269:11)\n    at Socket.Readable.push (_stream_readable.js:224:10)\n    at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)","message":"une valeur NULL viole la contrainte NOT NULL de la colonne « id »","name":"error","length":300,"severity":"ERREUR","code":"23502","detail":"La ligne en échec contient (null, 1, 1, 3, 3, 1, 1, 1, 1, 1, 38, 2020-04-09 19:57:15.149+00, 2020-04-09 19:57:15.149+00, 3, 1, 1)","schema":"public","table":"userNotificationSetting","column":"id","file":"execMain.c","line":"1736","routine":"ExecConstraints","sql":"INSERT INTO \"userNotificationSetting\" (\"id\",\"newVideoFromSubscription\",\"newCommentOnMyVideo\",\"videoAbuseAsModerator\",\"videoAutoBlacklistAsModerator\",\"blacklistOnMyVideo\",\"myVideoPublished\",\"myVideoImportFinished\",\"newUserRegistration\",\"newInstanceFollower\",\"autoInstanceFollowing\",\"newFollow\",\"commentMention\",\"userId\",\"createdAt\",\"updatedAt\") VALUES (DEFAULT,$1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15) RETURNING *;","parameters":[1,1,3,3,3,1,1,1,1,1,1,1,38,"2020-04-09 19:57:15.149 +00:00","2020-04-09 19:57:15.149 +00:00"]},"sql":"INSERT INTO \"userNotificationSetting\" (\"id\",\"newVideoFromSubscription\",\"newCommentOnMyVideo\",\"videoAbuseAsModerator\",\"videoAutoBlacklistAsModerator\",\"blacklistOnMyVideo\",\"myVideoPublished\",\"myVideoImportFinished\",\"newUserRegistration\",\"newInstanceFollower\",\"autoInstanceFollowing\",\"newFollow\",\"commentMention\",\"userId\",\"createdAt\",\"updatedAt\") VALUES (DEFAULT,$1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15) RETURNING *;"},"level":"error","message":"Cannot execute registerUser with many retries.","label":"videos.adhocmusic.com:443","timestamp":"2020-04-09T19:57:15.171Z"}
{"err":"SequelizeDatabaseError: une valeur NULL viole la contrainte NOT NULL de la colonne « id »\n    at Query.formatError (/var/www/peertube/versions/peertube-v2.1.1/node_modules/sequelize/lib/dialects/postgres/query.js:366:16)\n    at query.catch.err (/var/www/peertube/versions/peertube-v2.1.1/node_modules/sequelize/lib/dialects/postgres/query.js:72:18)\n    at tryCatcher (/var/www/peertube/versions/peertube-v2.1.1/node_modules/bluebird/js/release/util.js:16:23)\n    at Promise._settlePromiseFromHandler (/var/www/peertube/versions/peertube-v2.1.1/node_modules/bluebird/js/release/promise.js:547:31)\n    at Promise._settlePromise (/var/www/peertube/versions/peertube-v2.1.1/node_modules/bluebird/js/release/promise.js:604:18)\n    at Promise._settlePromise0 (/var/www/peertube/versions/peertube-v2.1.1/node_modules/bluebird/js/release/promise.js:649:10)\n    at Promise._settlePromises (/var/www/peertube/versions/peertube-v2.1.1/node_modules/bluebird/js/release/promise.js:725:18)\n    at _drainQueueStep (/var/www/peertube/versions/peertube-v2.1.1/node_modules/bluebird/js/release/async.js:93:12)\n    at _drainQueue (/var/www/peertube/versions/peertube-v2.1.1/node_modules/bluebird/js/release/async.js:86:9)\n    at Async._drainQueues (/var/www/peertube/versions/peertube-v2.1.1/node_modules/bluebird/js/release/async.js:102:5)\n    at Immediate.Async.drainQueues [as _onImmediate] (/var/www/peertube/versions/peertube-v2.1.1/node_modules/bluebird/js/release/async.js:15:14)\n    at runCallback (timers.js:705:18)\n    at tryOnImmediate (timers.js:676:5)\n    at processImmediate (timers.js:658:5)","sql":"INSERT INTO \"userNotificationSetting\" (\"id\",\"newVideoFromSubscription\",\"newCommentOnMyVideo\",\"videoAbuseAsModerator\",\"videoAutoBlacklistAsModerator\",\"blacklistOnMyVideo\",\"myVideoPublished\",\"myVideoImportFinished\",\"newUserRegistration\",\"newInstanceFollower\",\"autoInstanceFollowing\",\"newFollow\",\"commentMention\",\"userId\",\"createdAt\",\"updatedAt\") VALUES (DEFAULT,$1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15) RETURNING *;","level":"error","message":"Error in controller.","label":"videos.adhocmusic.com:443","timestamp":"2020-04-09T19:57:15.177Z"}

```

**Comment by Chocobozzz** [comment]
What is your postgresql version?

And could you run `\d "user";` using `sudo -u postgres psql peertube_prod`  please?

**Comment by aerogus** [comment]
Here you are :

```
# /usr/lib/postgresql/9.6/bin/postgres -V
postgres (PostgreSQL) 9.6.17
```

```

peertube_prod=# \d "user";

                                                Table « public.user »
           Colonne            |           Type           |                       Modificateurs
------------------------------+--------------------------+------------------------------------------------------------
 id                           | integer                  | non NULL Par défaut, nextval('user_id_seq'::regclass)
 password                     | character varying(255)   | non NULL
 username                     | character varying(255)   | non NULL
 email                        | character varying(400)   | non NULL
 nsfwPolicy                   | "enum_user_nsfwPolicy"   | non NULL
 autoPlayVideo                | boolean                  | non NULL Par défaut, true
 blocked                      | boolean                  | non NULL Par défaut, false
 blockedReason                | character varying(255)   | Par défaut, NULL::character varying
 role                         | integer                  | non NULL
 videoQuota                   | bigint                   | non NULL
 createdAt                    | timestamp with time zone | non NULL
 updatedAt                    | timestamp with time zone | non NULL
 videoQuotaDaily              | bigint                   | non NULL Par défaut, '-1'::integer
 emailVerified                | boolean                  |
 webTorrentEnabled            | boolean                  | non NULL Par défaut, true
 videosHistoryEnabled         | boolean                  | non NULL Par défaut, true
 adminFlags                   | integer                  | non NULL
 pendingEmail                 | character varying(400)   | Par défaut, NULL::character varying
 videoLanguages               | character varying(255)[] | Par défaut, NULL::character varying[]
 theme                        | character varying(255)   | non NULL Par défaut, 'instance-default'::character varying
 noInstanceConfigWarningModal | boolean                  | non NULL Par défaut, false
 noWelcomeModal               | boolean                  | non NULL Par défaut, false
 autoPlayNextVideo            | boolean                  | non NULL Par défaut, false
 autoPlayNextVideoPlaylist    | boolean                  | non NULL Par défaut, true
Index :
    "user_pkey" PRIMARY KEY, btree (id)
    "user_email" UNIQUE, btree (email)
    "user_username" UNIQUE, btree (username)
Référencé par :
    TABLE "account" CONSTRAINT "account_userId_fkey" FOREIGN KEY ("userId") REFERENCES "user"(id) ON UPDATE CASCADE ON DELETE CASCADE
    TABLE ""oAuthToken"" CONSTRAINT "oAuthToken_userId_fkey" FOREIGN KEY ("userId") REFERENCES "user"(id) ON UPDATE CASCADE ON DELETE CASCADE
    TABLE ""userNotificationSetting"" CONSTRAINT "userNotificationSetting_userId_fkey" FOREIGN KEY ("userId") REFERENCES "user"(id) ON UPDATE CASCADE ON
 DELETE CASCADE
    TABLE ""userNotification"" CONSTRAINT "userNotification_userId_fkey" FOREIGN KEY ("userId") REFERENCES "user"(id) ON UPDATE CASCADE ON DELETE CASCADE
    TABLE ""userVideoHistory"" CONSTRAINT "userVideoHistory_userId_fkey" FOREIGN KEY ("userId") REFERENCES "user"(id) ON UPDATE CASCADE ON DELETE CASCADE
    TABLE ""videoImport"" CONSTRAINT "videoImport_userId_fkey" FOREIGN KEY ("userId") REFERENCES "user"(id) ON UPDATE CASCADE ON DELETE CASCADE

```

**Comment by Chocobozzz** [comment]
And `\d "userNotificationSetting"`?

**Comment by aerogus** [comment]
```
psql (9.6.17)
Saisissez « help » pour l'aide.

peertube_prod=#  \d "userNotificationSetting"
                 Table « public.userNotificationSetting »
            Colonne            |           Type           | Modificateurs
-------------------------------+--------------------------+---------------
 id                            | integer                  | non NULL
 newVideoFromSubscription      | integer                  | non NULL
 newCommentOnMyVideo           | integer                  | non NULL
 videoAbuseAsModerator         | integer                  | non NULL
 blacklistOnMyVideo            | integer                  | non NULL
 myVideoPublished              | integer                  | non NULL
 myVideoImportFinished         | integer                  | non NULL
 newUserRegistration           | integer                  | non NULL
 newFollow                     | integer                  | non NULL
 commentMention                | integer                  | non NULL
 userId                        | integer                  |
 createdAt                     | timestamp with time zone | non NULL
 updatedAt                     | timestamp with time zone | non NULL
 videoAutoBlacklistAsModerator | integer                  | non NULL
 newInstanceFollower           | integer                  | non NULL
 autoInstanceFollowing         | integer                  | non NULL
Index :
    "userNotificationSetting_pkey" PRIMARY KEY, btree (id)
    "user_notification_setting_user_id" UNIQUE, btree ("userId")
Contraintes de clés étrangères :
    "userNotificationSetting_userId_fkey" FOREIGN KEY ("userId") REFERENCES "user"(id) ON UPDATE CASCADE ON DELETE CASCADE

```

**Comment by Chocobozzz** [comment]
Weirdly, the table has not been created correctly: https://github.com/Chocobozzz/PeerTube/blob/develop/server/initializers/migrations/0315-user-notifications.ts#L11

Try to rename this table, then recreate it using the SQL command from the file above, and copy data from the old table to the new table.

**Comment by aerogus** [comment]
Ok but what about the following fields videoAutoBlacklistAsModerator, newInstanceFollower, autoInstanceFollowing, are they deprecated ? they are no more in the CREATE TABLE query, resulting error like "{"err":"SequelizeDatabaseError: la colonne NotificationSetting.videoAutoBlacklistAsModerator n'existe pas\n"

I did the trick, rename the table, create the new table, import data but without theses 3 last fields.
Still an error

I have only 3 records in userNotificationSetting (one by user)

I'm at migrationVersion 470 in the application table, is that normal ? (for PeerTube v2.1.1)

I also did an upgrade.sh script to try to have a "clean" up to date version. Restarted peertube and postgresql.

`
{"err":"SequelizeUniqueConstraintError: la valeur d'une clé dupliquée rompt la contrainte unique « userNotificationSetting_pkey »\n    at Query.formatError (/var/www/peertube/versions/peertube-v2.1.1/node_modules/sequelize/lib/dialects/postgres/query.js:327:16)\n    at query.catch.err (/var/www/peertube/versions/peertube-v2.1.1/node_modules/sequelize/lib/dialects/postgres/query.js:72:18)\n    at tryCatcher (/var/www/peertube/versions/peertube-v2.1.1/node_modules/bluebird/js/release/util.js:16:23)\n    at Promise._settlePromiseFromHandler (/var/www/peertube/versions/peertube-v2.1.1/node_modules/bluebird/js/release/promise.js:547:31)\n    at Promise._settlePromise (/var/www/peertube/versions/peertube-v2.1.1/node_modules/bluebird/js/release/promise.js:604:18)\n    at Promise._settlePromise0 (/var/www/peertube/versions/peertube-v2.1.1/node_modules/bluebird/js/release/promise.js:649:10)\n    at Promise._settlePromises (/var/www/peertube/versions/peertube-v2.1.1/node_modules/bluebird/js/release/promise.js:725:18)\n    at _drainQueueStep (/var/www/peertube/versions/peertube-v2.1.1/node_modules/bluebird/js/release/async.js:93:12)\n    at _drainQueue (/var/www/peertube/versions/peertube-v2.1.1/node_modules/bluebird/js/release/async.js:86:9)\n    at Async._drainQueues (/var/www/peertube/versions/peertube-v2.1.1/node_modules/bluebird/js/release/async.js:102:5)\n    at Immediate.Async.drainQueues [as _onImmediate] (/var/www/peertube/versions/peertube-v2.1.1/node_modules/bluebird/js/release/async.js:15:14)\n    at runCallback (timers.js:705:18)\n    at tryOnImmediate (timers.js:676:5)\n    at processImmediate (timers.js:658:5)","sql":"INSERT INTO \"userNotificationSetting\" (\"id\",\"newVideoFromSubscription\",\"newCommentOnMyVideo\",\"videoAbuseAsModerator\",\"videoAutoBlacklistAsModerator\",\"blacklistOnMyVideo\",\"myVideoPublished\",\"myVideoImportFinished\",\"newUserRegistration\",\"newInstanceFollower\",\"autoInstanceFollowing\",\"newFollow\",\"commentMention\",\"userId\",\"createdAt\",\"updatedAt\") VALUES (DEFAULT,$1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15) RETURNING *;","level":"error","message":"Error in controller.","label":"videos.adhocmusic.com:443","timestamp":"2020-04-10T10:23:08.954Z"}`

**Comment by Chocobozzz** [comment]
Sorry, I forgot we added these columns. Redo the process using:

```
CREATE TABLE IF NOT EXISTS "userNotificationSetting" ("id" SERIAL,
"newVideoFromSubscription" INTEGER NOT NULL DEFAULT NULL,
"newCommentOnMyVideo" INTEGER NOT NULL DEFAULT NULL,
"videoAbuseAsModerator" INTEGER NOT NULL DEFAULT NULL,
"blacklistOnMyVideo" INTEGER NOT NULL DEFAULT NULL,
"myVideoPublished" INTEGER NOT NULL DEFAULT NULL,
"myVideoImportFinished" INTEGER NOT NULL DEFAULT NULL,
"newUserRegistration" INTEGER NOT NULL DEFAULT NULL,
"newFollow" INTEGER NOT NULL DEFAULT NULL,
"commentMention" INTEGER NOT NULL DEFAULT NULL,
"userId" INTEGER REFERENCES "user" ("id") ON DELETE CASCADE ON UPDATE CASCADE,
"createdAt" TIMESTAMP WITH TIME ZONE NOT NULL,
"updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL,
"videoAutoBlacklistAsModerator" INTEGER NOT NULL DEFAULT NULL,
"newInstanceFollower" INTEGER NOT NULL DEFAULT NULL,
"autoInstanceFollowing" INTEGER NOT NULL DEFAULT NULL,
PRIMARY KEY ("id"))
```

**Comment by aerogus** [comment]
Same error :( I have manually modified the next value for sequence "userNotificationSetting_id_seq" (+1) and it worked now !  Very strange... (but i'm not an expert with Postgresql :).
Issue closed for me. Thx for all.
