### ISSUE TITLE
Problem importing videos with tools

### ISSUE THREAD

**Issue by McFlat** [Chocobozzz/PeerTube#2641]
**What happened?**
Tryong to import videos from a youtube channel using the tools documentation page and I'm getting an error.

**What do you expect to happen instead?**
I expect it to import all the videos from the last 6 days

**Steps to reproduce:**

1. run command from tools.md page to see if crontab task would work
note the path to this peertube isnt the one that being served by the nginx web server which has frontend resources built, this peertube is in a separate path

2. /usr/bin/node /PATH/TO/PEERTUBE/dist/server/tools/peertube-import-videos.js -u '__PEERTUBE_URL__' -U '__USER__' --password '__PASSWORD__' --target-url 'https://www.youtube.com/channel/___CHANNEL__' --since $(date --date="-6 days" +%Y-%m-%d)

3. get error below:

```
[troo.tube:443] 2020-04-15 18:01:41.847 error: uncaughtException: Cannot find module '@server/helpers/core-utils'
Error: Cannot find module '@server/helpers/core-utils'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._resolveFilename (/PATH/TO/PEERTUBE/node_modules/tsconfig-paths/lib/register.js:75:40)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/PATH/TO/PEERTUBE/dist/server/helpers/custom-validators/activitypub/actor.js:8:22)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/PATH/TO/PEERTUBE/dist/server/models/activitypub/actor.js:17:17)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/PATH/TO/PEERTUBE/dist/server/lib/activitypub/send/utils.js:13:17) {
  "error": {
    "stack": "Error: Cannot find module '@server/helpers/core-utils'\n    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)\n    at Function.Module._resolveFilename (/PATH/TO/PEERTUBE/node_modules/tsconfig-paths/lib/register.js:75:40)\n    at Function.Module._load (internal/modules/cjs/loader.js:562:25)\n    at Module.require (internal/modules/cjs/loader.js:692:17)\n    at require (internal/modules/cjs/helpers.js:25:18)\n    at Object.<anonymous> (/PATH/TO/PEERTUBE/dist/server/helpers/custom-validators/activitypub/actor.js:8:22)\n    at Module._compile (internal/modules/cjs/loader.js:778:30)\n    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)\n    at Module.load (internal/modules/cjs/loader.js:653:32)\n    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)\n    at Function.Module._load (internal/modules/cjs/loader.js:585:3)\n    at Module.require (internal/modules/cjs/loader.js:692:17)\n    at require (internal/modules/cjs/helpers.js:25:18)\n    at Object.<anonymous> (/PATH/TO/PEERTUBE/dist/server/models/activitypub/actor.js:17:17)\n    at Module._compile (internal/modules/cjs/loader.js:778:30)\n    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)\n    at Module.load (internal/modules/cjs/loader.js:653:32)\n    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)\n    at Function.Module._load (internal/modules/cjs/loader.js:585:3)\n    at Module.require (internal/modules/cjs/loader.js:692:17)\n    at require (internal/modules/cjs/helpers.js:25:18)\n    at Object.<anonymous> (/VideosTank/DataDS/troo.tube/PeerTube/dist/server/lib/activitypub/send/utils.js:13:17)",
    "message": "Cannot find module '@server/helpers/core-utils'",
    "code": "MODULE_NOT_FOUND"
  },
  "stack": "Error: Cannot find module '@server/helpers/core-utils'\n    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)\n    at Function.Module._resolveFilename (/PATH/TO/PEERTUBE/node_modules/tsconfig-paths/lib/register.js:75:40)\n    at Function.Module._load (internal/modules/cjs/loader.js:562:25)\n    at Module.require (internal/modules/cjs
      "function": "Module._resolveFilename",
      "line": 75,
      "method": "_resolveFilename",
      "native": false
    },
    {
      "column": 25,
      "file": "internal/modules/cjs/loader.js",
      "function": "Module._load",
      "line": 562,
      "method": "_load",
      "native": false
    },
    {
      "column": 17,
      "file": "internal/modules/cjs/loader.js",
      "function": "Module.require",
      "line": 692,
      "method": "require",
      "native": false
    },
    {
      "column": 18,
      "file": "internal/modules/cjs/helpers.js",
      "function": "require",
      "line": 25,
      "method": null,
      "native": false
    },
    {
      "column": 22,
      "file": "/PATH/TO/PEERTUBE/dist/server/helpers/custom-validators/activitypub/actor.js",
      "function": null,
      "line": 8,
      "method": null,
      "native": false
    },
    {
      "column": 30,
      "file": "internal/modules/cjs/loader.js",
      "function": "Module._compile",
      "line": 778,
      "method": "_compile",
      "native": false
    },
    {
      "column": 10,
      "file": "internal/modules/cjs/loader.js",
      "function": "Module._extensions..js",
      "line": 789,
      "method": ".js",
      "native": false
    },
    {
      "column": 32,
      "file": "internal/modules/cjs/loader.js",
      "function": "Module.load",
      "line": 653,
    
    {
      "column": 10,
      "file": "internal/modules/cjs/loader.js",
      "function": "Module._extensions..js",
      "line": 789,
      "method": ".js",
      "native": false
    },
    {
      "column": 32,
      "file": "internal/modules/cjs/loader.js",
      "function": "Module.load",
      "line": 653,
      "method": "load",
      "native": false
    },
    {
      "column": 12,
      "file": "internal/modules/cjs/loader.js",
      "function": "tryModuleLoad",
      "line": 593,
      "method": null,
      "native": false
    },
    {
      "column": 3,
      "file": "internal/modules/cjs/loader.js",
      "function": "Module._load",
      "line": 585,
      "method": "_load",
      "native": false
    },
    {
      "column": 17,
      "file": "internal/modules/cjs/loader.js",
      "function": "Module.require",
      "line": 692,
      "method": "require",
      "native": false
    },
    {
      "column": 18,
      "file": "internal/modules/cjs/helpers.js",
      "function": "require",
      "line": 25,
      "method": null,
      "native": false
    },
    {
      "column": 17,
      "file": "/PATH/TO/PEERTUBE/dist/server/lib/activitypub/send/utils.js",
      "function": null,
      "line": 13,
      "method": null,
      "native": false
    }
  ]
}
```

**Additional information**
* PeerTube version or URL: 2.1.1
* Browser name/version: N/A
* NodeJS version: v10.20.1

* Link to browser console log if useful:
* Link to server log if useful (journalctl or /var/www/peertube/storage/logs/):

**Comment by Chocobozzz** [comment]
Update to the latest develop (see https://docs.joinpeertube.org/#/maintain-tools?id=installation)
