### ISSUE TITLE
Import youtube videos failed

### ISSUE THREAD

**Issue by pat971** [Chocobozzz/PeerTube#2655]
Until last week it worked.
Now, when i upload a video, i've got an error message in the job system log : 
```
Error: Command failed with exit code 1: /var/www/peertube/versions/peertube-v2.1.1/node_modules/youtube-dl/bin/youtube-dl -f bestvideo[ext=mp4]+bestaudio[ext=m4a]/best -o /var/www/peertube/storage/tmp/5546bfa3a0045e61d9f8421b3d6046cddba87720a7d6b01f8ec69d4c977ab911-import.mp4 http://www.youtube.com/watch?v=foo
    at makeError (/var/www/peertube/versions/peertube-v2.1.1/node_modules/execa/lib/error.js:56:11)
    at handlePromise (/var/www/peertube/versions/peertube-v2.1.1/node_modules/execa/index.js:114:26)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Additional information**
* PeerTube version or URL:  **Peertube 2.1.1**
* Browser name/version: **All browsers**
* NodeJS version: **v10.20.1**

I read the #2591 issue :
- I can run the youtube-dl command wihout any errors
- I removed node_modules and reinstalled it
- the output of `sudo -u peertube /usr/bin/env python --version` is `Python 2.7.16`

**Comment by Chocobozzz** [comment]
Please check the job error log in admin

**Comment by pat971** [comment]
> Please check the job error log in admin

```
error[17/04/2020 à 22:40:58] Cannot execute job 61 in queue video-import.

{
  "payload": {
    "type": "youtube-dl",
    "videoImportId": 61,
    "thumbnailUrl": "https://i.ytimg.com/vi/Z1H8cQqpXb8/maxresdefault.jpg",
    "downloadThumbnail": true,
    "downloadPreview": true
  },
  "err": {
    "stack": "Error: Command failed with exit code 1: /var/www/peertube/versions/peertube-v2.1.1/node_modules/youtube-dl/bin/youtube-dl -f bestvideo[ext=mp4]+bestaudio[ext=m4a]/best -o /var/www/peertube/storage/tmp/5546bfa3a0045e61d9f8421b3d6046cddba87720a7d6b01f8ec69d4c977ab911-import.mp4 http://www.youtube.com/watch?v=Z1H8cQqpXb8\n    at makeError (/var/www/peertube/versions/peertube-v2.1.1/node_modules/execa/lib/error.js:56:11)\n    at handlePromise (/var/www/peertube/versions/peertube-v2.1.1/node_modules/execa/index.js:114:26)\n    at process._tickCallback (internal/process/next_tick.js:68:7)",
    "message": "Command failed with exit code 1: /var/www/peertube/versions/peertube-v2.1.1/node_modules/youtube-dl/bin/youtube-dl -f bestvideo[ext=mp4]+bestaudio[ext=m4a]/best -o /var/www/peertube/storage/tmp/5546bfa3a0045e61d9f8421b3d6046cddba87720a7d6b01f8ec69d4c977ab911-import.mp4 http://www.youtube.com/watch?v=Z1H8cQqpXb8",
    "command": "/var/www/peertube/versions/peertube-v2.1.1/node_modules/youtube-dl/bin/youtube-dl -f bestvideo[ext=mp4]+bestaudio[ext=m4a]/best -o /var/www/peertube/storage/tmp/5546bfa3a0045e61d9f8421b3d6046cddba87720a7d6b01f8ec69d4c977ab911-import.mp4 http://www.youtube.com/watch?v=Z1H8cQqpXb8",
    "exitCode": 1,
    "stdout": "[youtube] Z1H8cQqpXb8: Downloading webpage\n[download] Destination: /var/www/peertube/storage/tmp/5546bfa3a0045e61d9f8421b3d6046cddba87720a7d6b01f8ec69d4c977ab911-import.f137.mp4\n\r[download]   0.0% of 58.44MiB at 331.80KiB/s ETA 03:02\r[download]   0.0% of 58.44MiB at 907.99KiB/s ETA 01:06\r[download]   0.0% of 58.44MiB at  1.94MiB/s ETA 00:30\r[download]   0.0% of 58.44MiB at  3.93MiB/s ETA 00:14\r[download]   0.1% of 58.44MiB at  1.85MiB/s ETA 00:31\r[download]   0.1% of 58.44MiB at  2.10MiB/s ETA 00:27\r[download]   0.2% of 58.44MiB at  2.82MiB/s ETA 00:20\r[download]   0.4% of 58.44MiB at  4.22MiB/s ETA 00:13\r[download]   0.9% of 58.44MiB at  6.78MiB/s ETA 00:08\r[download]   1.7% of 58.44MiB at 11.16MiB/s ETA 00:05\r[download]   3.4% of 58.44MiB at 19.33MiB/s ETA 00:02\r[download]   6.8% of 58.44MiB at 10.28MiB/s ETA 00:05\r[download]  13.7% of 58.44MiB at 13.89MiB/s ETA 00:03\r[download]  16.3% of 58.44MiB at 14.37MiB/s ETA 00:03\r[download]  16.3% of 58.44MiB at 300.93KiB/s ETA 02:47\r[download]  16.3% of 58.44MiB at 807.53KiB/s ETA 01:02\r[download]  16.4% of 58.44MiB at  1.71MiB/s ETA 00:28\r[download]  16.4% of 58.44MiB at  3.44MiB/s ETA 00:14\r[download]  16.4% of 58.44MiB at  1.81MiB/s ETA 00:27\r[download]  16.4% of 58.44MiB at  2.09MiB/s ETA 00:23\r[download]  16.6% of 58.44MiB at  2.86MiB/s ETA 00:17\r[download]  16.8% of 58.44MiB at  4.29MiB/s ETA 00:11\r[download]  17.2% of 58.44MiB at  4.37MiB/s ETA 00:11\r[download]  18.0% of 58.44MiB at  7.75MiB/s ETA 00:06\r[download]  19.8% of 58.44MiB at 13.62MiB/s ETA 00:03\r[download]  23.2% of 58.44MiB at 23.29MiB/s ETA 00:01\r[download]  30.0% of 58.44MiB at 27.95MiB/s ETA 00:01\r[download]  32.6% of 58.44MiB at 28.91MiB/s ETA 00:01\r[download]  32.6% of 58.44MiB at 306.65KiB/s ETA 02:12\r[download]  32.6% of 58.44MiB at 813.01KiB/s ETA 00:49\r[download]  32.7% of 58.44MiB at  1.66MiB/s ETA 00:23\r[download]  32.7% of 58.44MiB at  3.28MiB/s ETA 00:12\r[download]  32.7% of 58.44MiB at  1.81MiB/s ETA 00:21\r[download]  32.7% of 58.44MiB at  2.09MiB/s ETA 00:18\r[download]  32.9% of 58.44MiB at  2.82MiB/s ETA 00:13\r[download]  33.1% of 58.44MiB at  4.23MiB/s ETA 00:09\r[download]  33.5% of 58.44MiB at  6.85MiB/s ETA 00:05\r[download]  34.3% of 58.44MiB at  9.62MiB/s ETA 00:03\r[download]  36.1% of 58.44MiB at 16.64MiB/s ETA 00:02\r[download]  39.5% of 58.44MiB at 13.08MiB/s ETA 00:02\r[download]  46.3% of 58.44MiB at 20.50MiB/s ETA 00:01\r[download]  49.7% of 58.44MiB at 23.13MiB/s ETA 00:01\r[download]  49.7% of 58.44MiB at 305.15KiB/s ETA 01:39\r[download]  49.7% of 58.44MiB at 827.55KiB/s ETA 00:36\r[download]  49.7% of 58.44MiB at  1.75MiB/s ETA 00:16\r[download]  49.7% of 58.44MiB at  3.47MiB/s ETA 00:08\r[download]  49.7% of 58.44MiB at  1.79MiB/s ETA 00:16\r[download]  49.8% of 58.44MiB at  2.07MiB/s ETA 00:14\r[download]  49.9% of 58.44MiB at  2.80MiB/s ETA 00:10\r[download]  50.1% of 58.44MiB at  4.21MiB/s ETA 00:06\r[download]  50.5% of 58.44MiB at  6.80MiB/s ETA 00:04\r[download]  51.4% of 58.44MiB at 11.03MiB/s ETA 00:02\r[download]  53.1% of 58.44MiB at 18.83MiB/s ETA 00:01\r[download]  56.5% of 58.44MiB at  9.79MiB/s ETA 00:02\r[download]  63.3% of 58.44MiB at 12.48MiB/s ETA 00:01\r[download]  66.3% of 58.44MiB at 14.50MiB/s ETA 00:01\r[download]  66.3% of 58.44MiB at 302.58KiB/s ETA 01:07\r[download]  66.3% of 58.44MiB at 821.93KiB/s ETA 00:24\r[download]  66.3% of 58.44MiB at  1.73MiB/s ETA 00:11\r[download]  66.3% of 58.44MiB at 497.21KiB/s ETA 00:40\r[download]  66.3% of 58.44MiB at 1007.25KiB/s ETA 00:20\r[download]  66.4% of 58.44MiB at  1.32MiB/s ETA 00:14\r[download]  66.5% of 58.44MiB at  1.97MiB/s ETA 00:09\r[download]  66.7% of 58.44MiB at  3.05MiB/s ETA 00:06\r[download]  67.1% of 58.44MiB at  4.97MiB/s ETA 00:03\r[download]  68.0% of 58.44MiB at  8.62MiB/s ETA 00:02\r[download]  69.7% of 58.44MiB at 12.97MiB/s ETA 00:01\r[download]  73.1% of 58.44MiB at 12.22MiB/s ETA 00:01\r[download]  80.0% of 58.44MiB at 18.86MiB/s ETA 00:00\r[download]  82.6% of 58.44MiB at 17.85MiB/s ETA 00:00\r[download]  82.6% of 58.44MiB at 310.07KiB/s ETA 00:33\r[download]  82.6% of 58.44MiB at 841.05KiB/s ETA 00:12\r[download]  82.6% of 58.44MiB at  1.78MiB/s ETA 00:05\r[download]  82.6% of 58.44MiB at  3.56MiB/s ETA 00:02\r[download]  82.7% of 58.44MiB at  1.83MiB/s ETA 00:05\r[download]  82.7% of 58.44MiB at  2.12MiB/s ETA 00:04\r[download]  82.8% of 58.44MiB at  2.86MiB/s ETA 00:03\r[download]  83.0% of 58.44MiB at  4.30MiB/s ETA 00:02\r[download]  83.5% of 58.44MiB at  6.95MiB/s ETA 00:01\r[download]  84.3% of 58.44MiB at 11.47MiB/s ETA 00:00\r[download]  86.0% of 58.44MiB at 19.62MiB/s ETA 00:00\r[download]  89.5% of 58.44MiB at 24.06MiB/s ETA 00:00\r[download]  96.3% of 58.44MiB at 27.09MiB/s ETA 00:00\r[download]  99.7% of 58.44MiB at 18.72MiB/s ETA 00:00\r[download]  99.7% of 58.44MiB at 310.37KiB/s ETA 00:00\r[download]  99.7% of 58.44MiB at 824.41KiB/s ETA 00:00\r[download]  99.7% of 58.44MiB at  1.74MiB/s ETA 00:00\r[download]  99.7% of 58.44MiB at  3.50MiB/s ETA 00:00\r[download]  99.7% of 58.44MiB at  1.82MiB/s ETA 00:00\r[download]  99.8% of 58.44MiB at  2.09MiB/s ETA 00:00\r[download]  99.9% of 58.44MiB at  2.87MiB/s ETA 00:00\r[download] 100.0% of 58.44MiB at  3.69MiB/s ETA 00:00\r[download] 100% of 58.44MiB in 00:04",
    "stderr": "ERROR: unable to download video data: HTTP Error 403: Forbidden",
    "failed": true,
    "timedOut": false,
    "isCanceled": false,
    "killed": false
  }
}
```

**Comment by pat971** [comment]
After remove the cache dir it worked. In my case :
`sudo rm -r /var/www/peertube/.cache/youtube-dl`
