### ISSUE TITLE
Database migration from PeerTube v2.1.1 to v.2.2.0-rc1 / docker image

### ISSUE THREAD

**Issue by kimsible** [Chocobozzz/PeerTube#2777]
Hi, 

Is there any tool to migrate database breaking changes ?

I tried to migrate a test instance from PeerTube v2.1.1 to v2.2.0-rc1 and I got some `SequelizeDatabaseError`.

On the watch / edit / delete video view : 
```
"err": "SequelizeDatabaseError: column VideoFileModel.metadataUrl does not exist\n    at Query.formatError (/app/node_modules/sequelize/lib/dialects/postgres/query.js:366:16)\n    at query.catch.err (/app/node_modules/sequelize/lib/dialects/postgres/query.js:72:18)\n    at tryCatcher (/app/node_modules/bluebird/js/release/util.js:16:23)\n    at Promise._settlePromiseFromHandler (/app/node_modules/bluebird/js/release/promise.js:547:31)\n    at Promise._settlePromise (/app/node_modules/bluebird/js/release/promise.js:604:18)\n    at Promise._settlePromise0 (/app/node_modules/bluebird/js/release/promise.js:649:10)\n    at Promise._settlePromises (/app/node_modules/bluebird/js/release/promise.js:725:18)\n    at _drainQueueStep (/app/node_modules/bluebird/js/release/async.js:93:12)\n    at _drainQueue (/app/node_modules/bluebird/js/release/async.js:86:9)\n    at Async._drainQueues (/app/node_modules/bluebird/js/release/async.js:102:5)\n    at Immediate.Async.drainQueues [as _onImmediate] (/app/node_modules/bluebird/js/release/async.js:15:14)\n    at runCallback (timers.js:705:18)\n    at tryOnImmediate (timers.js:676:5)\n    at processImmediate (timers.js:658:5)"
```

On video upload : 
```
 "err": "SequelizeDatabaseError: column \"metadata\" of relation \"videoFile\" does not exist\n    at Query.formatError (/app/node_modules/sequelize/lib/dialects/postgres/query.js:366:16)\n    at query.catch.err (/app/node_modules/sequelize/lib/dialects/postgres/query.js:72:18)\n    at tryCatcher (/app/node_modules/bluebird/js/release/util.js:16:23)\n    at Promise._settlePromiseFromHandler (/app/node_modules/bluebird/js/release/promise.js:547:31)\n    at Promise._settlePromise (/app/node_modules/bluebird/js/release/promise.js:604:18)\n    at Promise._settlePromise0 (/app/node_modules/bluebird/js/release/promise.js:649:10)\n    at Promise._settlePromises (/app/node_modules/bluebird/js/release/promise.js:725:18)\n    at _drainQueueStep (/app/node_modules/bluebird/js/release/async.js:93:12)\n    at _drainQueue (/app/node_modules/bluebird/js/release/async.js:86:9)\n    at Async._drainQueues (/app/node_modules/bluebird/js/release/async.js:102:5)\n    at Immediate.Async.drainQueues [as _onImmediate] (/app/node_modules/bluebird/js/release/async.js:15:14)\n    at runCallback (timers.js:705:18)\n    at tryOnImmediate (timers.js:676:5)\n    at processImmediate (timers.js:658:5)"
```

**Comment by kimsible** [comment]
Ok I found the migration (0485) : https://github.com/Chocobozzz/PeerTube/blob/develop/server/initializers/migrations/0485-video-file-metadata.ts

Hmm, do we have to run it manually ?

**Comment by rigelk** [comment]
@kimsible yes, and the last migration number to execute in the `server/initializers/constants.ts`.

**Comment by kimsible** [comment]
Thanks @rigelk but it seems 0485 migration is not run, but it should be, the `LAST_MIGRATION_VERSION` on v2.1.1 was `470` and it's now `505` on v2.2.0-rc1. Hmm weird.

**Comment by kimsible** [comment]
Ok it seems the migration `0485` does not exist on the tag `v2.2.0-rc1` and docker image built : https://github.com/Chocobozzz/PeerTube/tree/v2.2.0-rc.1/server/initializers/migrations

The commit about this migration has been pushed just after the tag by @Chocobozzz  : https://github.com/Chocobozzz/PeerTube/commit/51539e95d954867d5c4561ac56843105253db79c.

**Comment by Chocobozzz** [comment]
Thanks @kimsible, I completely forgot to fix the docker build.

Should be fixed by https://github.com/Chocobozzz/PeerTube/commit/d2a5c4e15003d1e8904b389810d78e26db2cebfc

**Comment by kimsible** [comment]
Thanks @Chocobozzz.
