### ISSUE TITLE
v2.2 Cannot open comment replies (local?)

### ISSUE THREAD

**Issue by grinapo** [Chocobozzz/PeerTube#2825]
**What happened?**
```
2020-06-03_15:49:21.08773 [tube.grin.hu:443] 2020-06-03 17:49:21.087 error: Error in controller. {
2020-06-03_15:49:21.08778   "err": "TypeError: Cannot read property 'shift' of undefined\n    at Object.buildFormattedCommentTree (/var/www/peertube/versions/peertube-v2.2.0/dist/server/lib/video-comment.js:43:30)\n    at /var/www/peertube/versions/peertube-v2.2.0/dist/server/controllers/api/videos/comment.js:77:41\n    at Generator.next (<anonymous>)\n    at fulfilled (/var/www/peertube/versions/peertube-v2.2.0/dist/server/controllers/api/videos/comment.js:5:58)"
2020-06-03_15:49:21.08780 }
```
Tried to open a reply to a comment on https://tube.grin.hu/videos/watch/b9991c48-1754-458d-899e-cd960d68ae21

**What do you expect to happen instead?**
No error, comment visible instead of spinning forever.

**Steps to reproduce:**
- Goto video
- Click on "show reply"
- Wait for the spinner... wait...

**Additional information**
* PeerTube version or URL: v2.2
* Browser name/version: FF nightly
* NodeJS version:  10.19.0~dfsg1-1  (Debian)

**Comment by Chocobozzz** [comment]
Hello,

It seems I can't reproduce anymore on your video. Could you confirm that?

**Comment by grinapo** [comment]
Yes, unfortunately it have healed itself. My bets are on updates arriving through the net in the meantime, which could mean some cases are not handled well, but I can't put a name on it.
Close at will, and thanks.
