### ISSUE TITLE
preferredUsername must be unique since 2.2.0

### ISSUE THREAD

**Issue by pokapow** [Chocobozzz/PeerTube#2840]
Since upgrade to 2.2.0, I got a crash due to "preferredUsername must be unique" in a field

```
Jun  7 17:45:55 sd-162802 systemd[1]: Stopped PeerTube daemon.
Jun  7 17:45:55 sd-162802 systemd[1]: Started PeerTube daemon.
Jun  7 17:45:56 sd-162802 peertube[4213]: > peertube@2.2.0 start /var/www/peertube/versions/peertube-v2.2.0
Jun  7 17:45:56 sd-162802 peertube[4213]: > node dist/server
Jun  7 17:46:09 sd-162802 peertube[4213]: [tube.p2p.legal:443] 2020-06-07 17:46:09.752 #033[31merror#033[39m: Cannot install application. {
Jun  7 17:46:09 sd-162802 peertube[4213]:   "err": {
Jun  7 17:46:09 sd-162802 peertube[4213]:     "stack": "SequelizeUniqueConstraintError: Validation error\n    at Query.formatError (/var/www/peertube/versions/peertube-v2.2.0/node_modules/sequelize/lib/dialects/postgres/query.js:324:18)\n    at query.catch.err (/var/www/peertube/versions/peertube-v2.2.0/node_modules/sequelize/lib/dialects/postgres/query.js:72:18)\n    at tryCatcher (/var/www/peertube/versions/peertube-v2.2.0/node_modules/bluebird/js/release/util.js:16:23)\n    at Promise._settlePromiseFromHandler (/var/www/peertube/versions/peertube-v2.2.0/node_modules/bluebird/js/release/promise.js:547:31)\n    at Promise._settlePromise (/var/www/peertube/versions/peertube-v2.2.0/node_modules/bluebird/js/release/promise.js:604:18)\n    at Promise._settlePromise0 (/var/www/peertube/versions/peertube-v2.2.0/node_modules/bluebird/js/release/promise.js:649:10)\n    at Promise._settlePromises (/var/www/peertube/versions/peertube-v2.2.0/node_modules/bluebird/js/release/promise.js:725:18)\n    at _drainQueueStep (/var/www/peertube/versions/peertube-v2.2.0/node_modules/bluebird/js/release/async.js:93:12)\n    at _drainQueue (/var/www/peertube/versions/peertube-v2.2.0/node_modules/bluebird/js/release/async.js:86:9)\n    at Async._drainQueues (/var/www/peertube/versions/peertube-v2.2.0/node_modules/bluebird/js/release/async.js:102:5)\n    at Immediate.Async.drainQueues [as _onImmediate] (/var/www/peertube/versions/peertube-v2.2.0/node_modules/bluebird/js/release/async.js:15:14)\n    at runCallback (timers.js:705:18)\n    at tryOnImmediate (timers.js:676:5)\n    at processImmediate (timers.js:658:5)",
Jun  7 17:46:09 sd-162802 peertube[4213]:     "message": "Validation error",
Jun  7 17:46:09 sd-162802 peertube[4213]:     "name": "SequelizeUniqueConstraintError",
Jun  7 17:46:09 sd-162802 peertube[4213]:     "errors": [
Jun  7 17:46:09 sd-162802 peertube[4213]:       {
Jun  7 17:46:09 sd-162802 peertube[4213]:         "message": "preferredUsername must be unique",
Jun  7 17:46:09 sd-162802 peertube[4213]:         "type": "unique violation",
Jun  7 17:46:09 sd-162802 peertube[4213]:         "path": "preferredUsername",
Jun  7 17:46:09 sd-162802 peertube[4213]:         "value": "elois",
Jun  7 17:46:09 sd-162802 peertube[4213]:         "origin": "DB",
Jun  7 17:46:09 sd-162802 peertube[4213]:         "instance": null,
Jun  7 17:46:09 sd-162802 peertube[4213]:         "validatorKey": "not_unique",
Jun  7 17:46:09 sd-162802 peertube[4213]:         "validatorName": null,
Jun  7 17:46:09 sd-162802 peertube[4213]:         "validatorArgs": []
Jun  7 17:46:09 sd-162802 peertube[4213]:       }
Jun  7 17:46:09 sd-162802 peertube[4213]:     ],
Jun  7 17:46:09 sd-162802 peertube[4213]:     "fields": {
Jun  7 17:46:09 sd-162802 peertube[4213]:       "preferredUsername": "elois"
Jun  7 17:46:09 sd-162802 peertube[4213]:     },
Jun  7 17:46:09 sd-162802 peertube[4213]:     "parent": {
Jun  7 17:46:09 sd-162802 peertube[4213]:       "stack": "error: could not create unique index \"actor_preferred_username\"\n    at Connection.parseE (/var/www/peertube/versions/peertube-v2.2.0/node_modules/pg/lib/connection.js:614:13)\n    at Connection.parseMessage (/var/www/peertube/versions/peertube-v2.2.0/node_modules/pg/lib/connection.js:413:19)\n    at Socket.<anonymous> (/var/www/peertube/versions/peertube-v2.2.0/node_modules/pg/lib/connection.js:129:22)\n    at Socket.emit (events.js:198:13)\n    at addChunk (_stream_readable.js:288:12)\n    at readableAddChunk (_stream_readable.js:269:11)\n    at Socket.Readable.push (_stream_readable.js:224:10)\n    at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)",
Jun  7 17:46:09 sd-162802 peertube[4213]:       "message": "could not create unique index \"actor_preferred_username\"",
Jun  7 17:46:09 sd-162802 peertube[4213]:       "name": "error",
Jun  7 17:46:09 sd-162802 peertube[4213]:       "length": 218,
Jun  7 17:46:09 sd-162802 peertube[4213]:       "severity": "ERROR",
Jun  7 17:46:09 sd-162802 peertube[4213]:       "code": "23505",
Jun  7 17:46:09 sd-162802 peertube[4213]:       "detail": "Key (\"preferredUsername\")=(elois) is duplicated.",
Jun  7 17:46:09 sd-162802 peertube[4213]:       "schema": "public",
Jun  7 17:46:09 sd-162802 peertube[4213]:       "table": "actor",
Jun  7 17:46:09 sd-162802 peertube[4213]:       "constraint": "actor_preferred_username",
Jun  7 17:46:09 sd-162802 peertube[4213]:       "file": "tuplesort.c",
Jun  7 17:46:09 sd-162802 peertube[4213]:       "line": "4056",
Jun  7 17:46:09 sd-162802 peertube[4213]:       "routine": "comparetup_index_btree",
Jun  7 17:46:09 sd-162802 peertube[4213]:       "sql": "CREATE UNIQUE INDEX \"actor_preferred_username\" ON \"actor\" (\"preferredUsername\") WHERE \"serverId\" IS NULL"
Jun  7 17:46:09 sd-162802 peertube[4213]:     },
Jun  7 17:46:09 sd-162802 peertube[4213]:     "sql": "CREATE UNIQUE INDEX \"actor_preferred_username\" ON \"actor\" (\"preferredUsername\") WHERE \"serverId\" IS NULL"
Jun  7 17:46:09 sd-162802 peertube[4213]:   }
Jun  7 17:46:09 sd-162802 peertube[4213]: }
Jun  7 17:46:09 sd-162802 peertube[4213]: npm ERR! code ELIFECYCLE
Jun  7 17:46:09 sd-162802 peertube[4213]: npm ERR! errno 255
Jun  7 17:46:09 sd-162802 peertube[4213]: npm ERR! peertube@2.2.0 start: `node dist/server`
Jun  7 17:46:09 sd-162802 peertube[4213]: npm ERR! Exit status 255
Jun  7 17:46:09 sd-162802 peertube[4213]: npm ERR!
Jun  7 17:46:09 sd-162802 peertube[4213]: npm ERR! Failed at the peertube@2.2.0 start script.
Jun  7 17:46:09 sd-162802 peertube[4213]: npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
Jun  7 17:46:09 sd-162802 peertube[4213]: npm ERR! A complete log of this run can be found in:
Jun  7 17:46:09 sd-162802 peertube[4213]: npm ERR!     /var/www/peertube/.npm/_logs/2020-06-07T15_46_09_827Z-debug.log
Jun  7 17:46:09 sd-162802 systemd[1]: peertube.service: Main process exited, code=exited, status=255/EXCEPTION
Jun  7 17:46:09 sd-162802 systemd[1]: peertube.service: Failed with result 'exit-code'.
Jun  7 17:46:10 sd-162802 systemd[1]: peertube.service: Service RestartSec=100ms expired, scheduling restart.
Jun  7 17:46:10 sd-162802 systemd[1]: peertube.service: Scheduled restart job, restart counter is at 25.
```

I don't understand what to do...

**Comment by tcitworld** [comment]
See the section on top of the release notes:
https://github.com/Chocobozzz/PeerTube/releases/tag/v2.2.0

**Comment by pokapow** [comment]
Ok thank you, actually I have one duplicate entry.
Can you help to change de name of this actor, I try this with errors:
`UPDATE actor SET preferredUsername = elois2 where "serverId" is null group by "preferredUsername" having count(*) > 1;`

**Comment by Chocobozzz** [comment]
First find the `id` of the actor to update:

```
select "id", "preferredUsername" from actor where "serverId" is null and "preferredUsername" = 'elois';
```

Then update the actor (**don't forget the WHERE clause**)
```
UPDATE actor SET "preferredUsername" = 'elois2' where "id" = ...
```
