### ISSUE TITLE
Error: Follower is the same as target actor.

### ISSUE THREAD

**Issue by takking168** [Chocobozzz/PeerTube#2864]
Hello Sir.
I have setup a peertube server, then clone it to be a redundant server. When I add a follower on redundant server, it showed the error: Follower is the same as target actor. Two server IP and host name are different. Do you have any idea to fix the issue? Thanks.
**Error log**:
Error: Follower is the same as target actor.
    at /var/www/peertube/versions/peertube-v2.2.0/dist/server/lib/job-queue/handlers/activitypub-follow.js:49:19
    at Generator.next (<anonymous>)
    at /var/www/peertube/versions/peertube-v2.2.0/dist/server/lib/job-queue/handlers/activitypub-follow.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/var/www/peertube/versions/peertube-v2.2.0/dist/server/lib/job-queue/handlers/activitypub-follow.js:4:12)
    at follow (/var/www/peertube/versions/peertube-v2.2.0/dist/server/lib/job-queue/handlers/activitypub-follow.js:47:12)
    at /var/www/peertube/versions/peertube-v2.2.0/dist/server/helpers/database-utils.js:7:25
    at retryAttempt (/var/www/peertube/versions/peertube-v2.2.0/node_modules/async/retry.js:132:9)
    at retry (/var/www/peertube/versions/peertube-v2.2.0/node_modules/async/retry.js:142:5)
    at /var/www/peertube/versions/peertube-v2.2.0/dist/server/helpers/database-utils.js:19:9
    at new Promise (<anonymous>)
    at transactionRetryer (/var/www/peertube/versions/peertube-v2.2.0/dist/server/helpers/database-utils.js:18:12)
    at Object.retryTransactionWrapper (/var/www/peertube/versions/peertube-v2.2.0/dist/server/helpers/database-utils.js:6:12)
    at Queue.<anonymous> (/var/www/peertube/versions/peertube-v2.2.0/dist/server/lib/job-queue/handlers/activitypub-follow.js:42:33)
    at Generator.next (<anonymous>)
    at fulfilled (/var/www/peertube/versions/peertube-v2.2.0/dist/server/lib/job-queue/handlers/activitypub-follow.js:5:58)

Peertube version: v2.2.0
OS: ubuntu-18.04.4

**Comment by Chocobozzz** [comment]
Please follow [fill the template](https://github.com/Chocobozzz/PeerTube/blob/develop/.github/ISSUE_TEMPLATE.md) so I can reproduce the issue. Also could you give me the instance URL that will duplicate the remote video + the instance URL that will be duplicated?
