### ISSUE TITLE
Mail send fails with docker postfix

### ISSUE THREAD

**Issue by kimsible** [Chocobozzz/PeerTube#2867]
Hello,

I have this message since the upgrade of PeerTube 2.2 and mails are not sent anymore, that's weird, Postfix seems ok.

```
[queermotion.org:443] 2020-06-11 16:00:27.550 error: Send Error: Message failed: 451 4.7.1 Service unavailable - try again later {
peertube_1       |   "component": "mail",
peertube_1       |   "err": {
peertube_1       |     "stack": "Error: Message failed: 451 4.7.1 Service unavailable - try again later\n    at SMTPConnection._formatError (/app/node_modules/nodemailer/lib/smtp-connection
/index.js:784:19)\n    at SMTPConnection._actionSMTPStream (/app/node_modules/nodemailer/lib/smtp-connection/index.js:1661:34)\n    at SMTPConnection._responseActions.push.str (/app/node_modules/nodemailer/lib/smtp-connection/index.js:1146:22)\n    at SMTPConnection._processResponse (/app/node_modules/nodemailer/lib/smtp-connection/index.js:942:20)\n    at SMTPConnection._onData (/app/node_modules/nodemailer/lib/smtp-connection/index.js:749:14)\n    at Socket.SMTPConnection._onSocketData.chunk (/app/node_modules/nodemailer/lib/smtp-connection/index.js:195:44)\n    at Socket.emit (events.js:198:13)\n    at addChunk (_stream_readable.js:288:12)\n    at readableAddChunk (_stream_readable.js:269:11)\n    at Socket.Readable.push (_stream_readable.js:224:10)\n    at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)",
peertube_1       |     "message": "Message failed: 451 4.7.1 Service unavailable - try again later",
peertube_1       |     "code": "EMESSAGE",
peertube_1       |     "response": "451 4.7.1 Service unavailable - try again later",
peertube_1       |     "responseCode": 451,
peertube_1       |     "command": "DATA"
peertube_1       |   },
peertube_1       |   "tnx": "transport",
peertube_1       |   "action": "send"
peertube_1       | }
```

**Comment by kimsible** [comment]
It was a known issue from the postfix docker image : https://github.com/wader/postfix-relay/pull/18

I just add `OPENDKIM_RequireSafeKeys=no` to `.env` and the tag `omwader/postfix-relay:opendkim-conf` in `docker-compose.yml` until the PR is merged to master branch of `wader/postfix-relay` repo.
