### ISSUE TITLE
It always says sh: scripty: command not found

### ISSUE THREAD

**Issue by myveb** [Chocobozzz/PeerTube#29]
Hello,
I'm using Debian Jessie to install it.
when I run the command npm run build
it always says that 
sh: scripty: command not found

**Comment by Chocobozzz** [comment]
Hi,

What is the output of `ls -l node_modules | grep scripty`

**Comment by myveb** [comment]
Thank you for your answer
When I run the command you gave me, it says
`drwxr-xr-x  8 root root  4096 Jan 14 21:47 scripty`

I have tested it on three servers, the OS are Debian Wheezy(kernel 3.2.0-4-amd64), Debian Jessie (kernel 4.9), Ubuntu 14.04, and run the commands as the readme.md guide exactly, there were simillor errors on all three servers.
when I run "npm install build".
first it says it can not find webpack scripty
then I run 
`npm install webpack scripty`
under the directory /root/PeerTube, it's successfully.
Then I run "npm run build" again, it shows another error:
```
> peertube@0.0.1 build /root/PeerTube
> npm run build:client:prod


> peertube@0.0.1 build:client:prod /root/PeerTube
> scripty


> peertube-client@0.0.1 webpack /root/PeerTube/client
> webpack "--config" "config/webpack.prod.js" "--progress" "--profile" "--bail"

root directory: /root/PeerTube/client

module.js:472
    throw err;
    ^

Error: Cannot find module 'webpack-merge'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/root/PeerTube/client/config/webpack.prod.js:6:22)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)

npm ERR! Linux 3.2.0-4-amd64
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "webpack" "--" "--config" "config/webpack.prod.js" "--progress" "--profile" "--bail"
npm ERR! node v7.4.0
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! peertube-client@0.0.1 webpack: `webpack "--config" "config/webpack.prod.js" "--progress" "--profile" "--bail"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the peertube-client@0.0.1 webpack script 'webpack "--config" "config/webpack.prod.js" "--progress" "--profile" "--bail"'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the peertube-client package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     webpack "--config" "config/webpack.prod.js" "--progress" "--profile" "--bail"
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs peertube-client
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls peertube-client
npm ERR! There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! Please include the following file with any support request:
npm ERR!     /root/PeerTube/client/npm-debug.log
/root/PeerTube/node_modules/scripty/cli.js:38
    if (er) { throw er }
              ^

Error: Error: scripty - script "fail" failed by exiting with a non-zero code (1).
    at ChildProcess.<anonymous> (/root/PeerTube/node_modules/scripty/lib/run/spawn-script.js:11:10)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:885:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)

npm ERR! Linux 3.2.0-4-amd64
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "build:client:prod"
npm ERR! node v7.4.0
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! peertube@0.0.1 build:client:prod: `scripty`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the peertube@0.0.1 build:client:prod script 'scripty'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the peertube package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     scripty
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs peertube
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls peertube
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /root/PeerTube/npm-debug.log

npm ERR! Linux 3.2.0-4-amd64
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "build"
npm ERR! node v7.4.0
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! peertube@0.0.1 build: `npm run build:client:prod`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the peertube@0.0.1 build script 'npm run build:client:prod'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the peertube package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run build:client:prod
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs peertube
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls peertube
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /root/PeerTube/npm-debug.log
```

Then I run "npm install webpack-merge", it's successfully.
When I run "npm run build" again, it says another error
```
> peertube@0.0.1 build /root/PeerTube
> npm run build:client:prod


> peertube@0.0.1 build:client:prod /root/PeerTube
> scripty


> peertube-client@0.0.1 webpack /root/PeerTube/client
> webpack "--config" "config/webpack.prod.js" "--progress" "--profile" "--bail"

root directory: /root/PeerTube/client

module.js:472
    throw err;
    ^

Error: Cannot find module 'copy-webpack-plugin'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/root/PeerTube/client/config/webpack.common.js:8:27)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)

npm ERR! Linux 3.2.0-4-amd64
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "webpack" "--" "-                                                                                                                                                             -config" "config/webpack.prod.js" "--progress" "--profile" "--bail"
npm ERR! node v7.4.0
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! peertube-client@0.0.1 webpack: `webpack "--config" "config/webpack.prod                                                                                                                                                             .js" "--progress" "--profile" "--bail"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the peertube-client@0.0.1 webpack script 'webpack "--config"                                                                                                                                                              "config/webpack.prod.js" "--progress" "--profile" "--bail"'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the peertube-client packa                                                                                                                                                             ge,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     webpack "--config" "config/webpack.prod.js" "--progress" "--profile                                                                                                                                                             " "--bail"
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs peertube-client
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls peertube-client
npm ERR! There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to in                                                                                                                                                             stall?

npm ERR! Please include the following file with any support request:
npm ERR!     /root/PeerTube/client/npm-debug.log
/root/PeerTube/node_modules/scripty/cli.js:38
    if (er) { throw er }
              ^

Error: Error: scripty - script "fail" failed by exiting with a non-zero code (1)                                                                                                                                                             .
    at ChildProcess.<anonymous> (/root/PeerTube/node_modules/scripty/lib/run/spa                                                                                                                                                             wn-script.js:11:10)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:885:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)

npm ERR! Linux 3.2.0-4-amd64
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "build:client:pro                                                                                                                                                             d"
npm ERR! node v7.4.0
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! peertube@0.0.1 build:client:prod: `scripty`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the peertube@0.0.1 build:client:prod script 'scripty'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the peertube package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     scripty
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs peertube
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls peertube
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /root/PeerTube/npm-debug.log

npm ERR! Linux 3.2.0-4-amd64
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "build"
npm ERR! node v7.4.0
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! peertube@0.0.1 build: `npm run build:client:prod`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the peertube@0.0.1 build script 'npm run build:client:prod'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the peertube package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run build:client:prod
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs peertube
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls peertube
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /root/PeerTube/npm-debug.log
```

when I install copy-webpack-plugin, there will be another error like this again.

**Comment by myveb** [comment]
If you need, I will send you my server's IP and login key.

**Comment by Chocobozzz** [comment]
@myveb If you are root check https://github.com/Chocobozzz/PeerTube#sources. You need to make `npm install --unsafe-perm` instead of `npm install`.

**Comment by myveb** [comment]
@Chocobozzz Thank you very much! I run it on Debian Wheezy(kernel 3.2.0-4-amd64)
Will it be a good idea now if run PeerTube for production ?

**Comment by Chocobozzz** [comment]
Not yet :) But I hope that I will be able to release an alpha version in a few months.

Currently, PeerTube works well on production but upgrades can be difficult since I do big changes sometimes (for example I moved from MongoDB to PostgreSQL some days ago).

**Comment by myveb** [comment]
@Chocobozzz I see, Thank you very much , I will be waiting for your alpha version.
