### ISSUE TITLE
not a valid following url

### ISSUE THREAD

**Issue by ValorNaram** [Chocobozzz/PeerTube#2949]
**What happened?**
I filled in the environment variables, started PeerTube with docker-compose which sets up and starts
- production_peertube
- production_postfix
- production_postgres
- production_redis
.
It prints me tones of error lines. All share the same scheme like

```bash
peertube_1  |       {
peertube_1  |         "message": "\"http://peert:8080/accounts/peertube/following\" is not a valid following url.",
peertube_1  |         "type": "Validation error",
peertube_1  |         "path": "followingUrl",
peertube_1  |         "value": "http://peert:8080/accounts/peertube/following",
peertube_1  |         "origin": "FUNCTION",
peertube_1  |         "instance": {
peertube_1  |           "id": null,
peertube_1  |           "type": "Application",
peertube_1  |           "url": "http://peert:8080/accounts/peertube",
peertube_1  |           "preferredUsername": "peertube",
peertube_1  |           "publicKey": null,
peertube_1  |           "privateKey": null,
peertube_1  |           "followersCount": 0,
peertube_1  |           "followingCount": 0,
peertube_1  |           "inboxUrl": "http://peert:8080/accounts/peertube/inbox",
peertube_1  |           "outboxUrl": "http://peert:8080/accounts/peertube/outbox",
peertube_1  |           "sharedInboxUrl": "http://peert:8080/inbox",
peertube_1  |           "followersUrl": "http://peert:8080/accounts/peertube/followers",
peertube_1  |           "followingUrl": "http://peert:8080/accounts/peertube/following",
peertube_1  |           "updatedAt": "2020-07-11T09:26:50.732Z",
peertube_1  |           "createdAt": "2020-07-11T09:26:50.732Z"
peertube_1  |         },
peertube_1  |         "validatorKey": "isActorFollowingUrl",
peertube_1  |         "validatorName": null,
peertube_1  |         "validatorArgs": [],
peertube_1  |         "original": {
peertube_1  |           "stack": "Error: \"http://peert:8080/accounts/peertube/following\" is not a valid following url.\n    at Object.throwIfNotValid (/app/dist/server/models/utils.js:83:15)\n    at ActorModel.sequelize_typescript_1.Is.value (/app/dist/server/models/activitypub/actor.js:418:69)\n    at Promise.try (/app/node_modules/sequelize/lib/instance-validator.js:269:28)\n    at tryCatcher (/app/node_modules/bluebird/js/release/util.js:16:23)\n    at Function.Promise.attempt.Promise.try (/app/node_modules/bluebird/js/release/method.js:39:29)\n    at InstanceValidator._invokeCustomValidator (/app/node_modules/sequelize/lib/instance-validator.js:269:11)\n    at _.forIn (/app/node_modules/sequelize/lib/instance-validator.js:208:30)\n    at /app/node_modules/lodash/lodash.js:4905:15\n    at Function.forIn (/app/node_modules/lodash/lodash.js:12950:11)\n    at InstanceValidator._singleAttrValidate (/app/node_modules/sequelize/lib/instance-validator.js:193:7)\n    at _.forIn (/app/node_modules/sequelize/lib/instance-validator.js:142:30)\n    at /app/node_modules/lodash/lodash.js:4905:15\n    at Function.forIn (/app/node_modules/lodash/lodash.js:12950:11)\n    at InstanceValidator._perAttributeValidators (/app/node_modules/sequelize/lib/instance-validator.js:125:7)\n    at InstanceValidator._validate (/app/node_modules/sequelize/lib/instance-validator.js:70:12)\n    at runHooks.then (/app/node_modules/sequelize/lib/instance-validator.js:107:14)\n    at tryCatcher (/app/node_modules/bluebird/js/release/util.js:16:23)\n    at Promise._settlePromiseFromHandler (/app/node_modules/bluebird/js/release/promise.js:547:31)\n    at Promise._settlePromise (/app/node_modules/bluebird/js/release/promise.js:604:18)\n    at Promise._settlePromise0 (/app/node_modules/bluebird/js/release/promise.js:649:10)\n    at Promise._settlePromises (/app/node_modules/bluebird/js/release/promise.js:729:18)\n    at _drainQueueStep (/app/node_modules/bluebird/js/release/async.js:93:12)\n    at _drainQueue (/app/node_modules/bluebird/js/release/async.js:86:9)\n    at Async._drainQueues (/app/node_modules/bluebird/js/release/async.js:102:5)\n    at Immediate.Async.drainQueues [as _onImmediate] (/app/node_modules/bluebird/js/release/async.js:15:14)\n    at runCallback (timers.js:705:18)\n    at tryOnImmediate (timers.js:676:5)\n    at processImmediate (timers.js:658:5)",
peertube_1  |           "message": "\"http://peert:8080/accounts/peertube/following\" is not a valid following url."
peertube_1  |         }
peertube_1  |       }
peertube_1  |     ]
peertube_1  |   }
peertube_1  | }
peertube_1  | npm ERR! code ELIFECYCLE
peertube_1  | npm ERR! errno 255
peertube_1  | npm ERR! peertube@2.2.0 start: `node dist/server`
peertube_1  | npm ERR! Exit status 255
peertube_1  | npm ERR! 
peertube_1  | npm ERR! Failed at the peertube@2.2.0 start script.
peertube_1  | npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
peertube_1  | 
peertube_1  | npm ERR! A complete log of this run can be found in:
peertube_1  | npm ERR!     /home/peertube/.npm/_logs/2020-07-11T09_26_50_800Z-debug.log
```

**What do you expect to happen instead?**
PeerTube starts and gives me access to its interface

**Steps to reproduce:**

1. Modify the environment variables in file `env` to suit your needs

2. Start with `docker-compose up`

**Additional information**
* PeerTube version or URL: 2.2.0
* Browser name/version:
* NodeJS version:

**Comment by Chocobozzz** [comment]
Set `PEERTUBE_WEBSERVER_HTTPS` to `true` (https://github.com/Chocobozzz/PeerTube/blob/develop/support/docker/production/.env#L18)

**Comment by ValorNaram** [comment]
Thanks, it helped but now I receive the same error message again. 

```bash
peertube_1  | [peert:8080] 2020-07-20 13:24:28.397 error: Cannot install application. {
peertube_1  |   "err": {
peertube_1  |     "stack": "SequelizeValidationError: Validation error: \"https://peert:8080/accounts/peertube\" is not a valid url.,\nValidation error: \"https://peert:8080/accounts/peertube/inbox\" is not a valid inbox url.,\nValidation error: \"https://peert:8080/accounts/peertube/outbox\" is not a valid outbox url.,\nValidation error: \"https://peert:8080/inbox\" is not a valid shared inbox url.,\nValidation error: \"https://peert:8080/accounts/peertube/followers\" is not a valid followers url.,\nValidation error: \"https://peert:8080/accounts/peertube/following\" is not a valid following url.\n    at Promise.all.then (/app/node_modules/sequelize/lib/instance-validator.js:74:15)\n    at tryCatcher (/app/node_modules/bluebird/js/release/util.js:16:23)\n    at Promise._settlePromiseFromHandler (/app/node_modules/bluebird/js/release/promise.js:547:31)\n    at Promise._settlePromise (/app/node_modules/bluebird/js/release/promise.js:604:18)\n    at Promise._settlePromise0 (/app/node_modules/bluebird/js/release/promise.js:649:10)\n    at Promise._settlePromises (/app/node_modules/bluebird/js/release/promise.js:729:18)\n    at Promise._fulfill (/app/node_modules/bluebird/js/release/promise.js:673:18)\n    at PromiseArray._resolve (/app/node_modules/bluebird/js/release/promise_array.js:127:19)\n    at PromiseArray._promiseFulfilled (/app/node_modules/bluebird/js/release/promise_array.js:145:14)\n    at Promise._settlePromise (/app/node_modules/bluebird/js/release/promise.js:609:26)\n    at Promise._settlePromise0 (/app/node_modules/bluebird/js/release/promise.js:649:10)\n    at Promise._settlePromises (/app/node_modules/bluebird/js/release/promise.js:729:18)\n    at Promise._fulfill (/app/node_modules/bluebird/js/release/promise.js:673:18)\n    at Promise._resolveCallback (/app/node_modules/bluebird/js/release/promise.js:466:57)\n    at Promise._settlePromiseFromHandler (/app/node_modules/bluebird/js/release/promise.js:559:17)\n    at Promise._settlePromise (/app/node_modules/bluebird/js/release/promise.js:604:18)\n    at Promise._settlePromise0 (/app/node_modules/bluebird/js/release/promise.js:649:10)\n    at Promise._settlePromises (/app/node_modules/bluebird/js/release/promise.js:729:18)\n    at Promise._fulfill (/app/node_modules/bluebird/js/release/promise.js:673:18)\n    at PromiseArray._resolve (/app/node_modules/bluebird/js/release/promise_array.js:127:19)\n    at PromiseArray._promiseFulfilled (/app/node_modules/bluebird/js/release/promise_array.js:145:14)\n    at Promise._settlePromise (/app/node_modules/bluebird/js/release/promise.js:609:26)\n    at Promise._settlePromise0 (/app/node_modules/bluebird/js/release/promise.js:649:10)\n    at Promise._settlePromises (/app/node_modules/bluebird/js/release/promise.js:729:18)\n    at Promise._fulfill (/app/node_modules/bluebird/js/release/promise.js:673:18)\n    at Promise._resolveCallback (/app/node_modules/bluebird/js/release/promise.js:466:57)\n    at Promise._settlePromiseFromHandler (/app/node_modules/bluebird/js/release/promise.js:559:17)\n    at Promise._settlePromise (/app/node_modules/bluebird/js/release/promise.js:604:18)\n    at Promise._settlePromise0 (/app/node_modules/bluebird/js/release/promise.js:649:10)\n    at Promise._settlePromises (/app/node_modules/bluebird/js/release/promise.js:729:18)\n    at Promise._fulfill (/app/node_modules/bluebird/js/release/promise.js:673:18)\n    at Promise._resolveCallback (/app/node_modules/bluebird/js/release/promise.js:466:57)\n    at Promise._settlePromiseFromHandler (/app/node_modules/bluebird/js/release/promise.js:559:17)\n    at Promise._settlePromise (/app/node_modules/bluebird/js/release/promise.js:604:18)",
peertube_1  |     "message": "Validation error: \"https://peert:8080/accounts/peertube\" is not a valid url.,\nValidation error: \"https://peert:8080/accounts/peertube/inbox\" is not a valid inbox url.,\nValidation error: \"https://peert:8080/accounts/peertube/outbox\" is not a valid outbox url.,\nValidation error: \"https://peert:8080/inbox\" is not a valid shared inbox url.,\nValidation error: \"https://peert:8080/accounts/peertube/followers\" is not a valid followers url.,\nValidation error: \"https://peert:8080/accounts/peertube/following\" is not a valid following url.",
peertube_1  |     "name": "SequelizeValidationError",
peertube_1  |     "errors": [
peertube_1  |       {
peertube_1  |         "message": "\"https://peert:8080/accounts/peertube\" is not a valid url.",
peertube_1  |         "type": "Validation error",
peertube_1  |         "path": "url",
peertube_1  |         "value": "https://peert:8080/accounts/peertube",
peertube_1  |         "origin": "FUNCTION",
peertube_1  |         "instance": {
peertube_1  |           "id": null,
peertube_1  |           "type": "Application",
peertube_1  |           "url": "https://peert:8080/accounts/peertube",
peertube_1  |           "preferredUsername": "peertube",
peertube_1  |           "publicKey": null,
peertube_1  |           "privateKey": null,
peertube_1  |           "followersCount": 0,
peertube_1  |           "followingCount": 0,
peertube_1  |           "inboxUrl": "https://peert:8080/accounts/peertube/inbox",
peertube_1  |           "outboxUrl": "https://peert:8080/accounts/peertube/outbox",
peertube_1  |           "sharedInboxUrl": "https://peert:8080/inbox",
peertube_1  |           "followersUrl": "https://peert:8080/accounts/peertube/followers",
peertube_1  |           "followingUrl": "https://peert:8080/accounts/peertube/following",
peertube_1  |           "updatedAt": "2020-07-20T13:24:28.390Z",
peertube_1  |           "createdAt": "2020-07-20T13:24:28.390Z"
peertube_1  |         },
peertube_1  |         "validatorKey": "isActorUrl",
peertube_1  |         "validatorName": null,
peertube_1  |         "validatorArgs": [],
peertube_1  |         "original": {
peertube_1  |           "stack": "Error: \"https://peert:8080/accounts/peertube\" is not a valid url.\n    at Object.throwIfNotValid (/app/dist/server/models/utils.js:83:15)\n    at ActorModel.sequelize_typescript_1.Is.value (/app/dist/server/models/activitypub/actor.js:364:60)\n    at Promise.try (/app/node_modules/sequelize/lib/instance-validator.js:269:28)\n    at tryCatcher (/app/node_modules/bluebird/js/release/util.js:16:23)\n    at Function.Promise.attempt.Promise.try (/app/node_modules/bluebird/js/release/method.js:39:29)\n    at InstanceValidator._invokeCustomValidator (/app/node_modules/sequelize/lib/instance-validator.js:269:11)\n    at _.forIn (/app/node_modules/sequelize/lib/instance-validator.js:208:30)\n    at /app/node_modules/lodash/lodash.js:4905:15\n    at Function.forIn (/app/node_modules/lodash/lodash.js:12950:11)\n    at InstanceValidator._singleAttrValidate (/app/node_modules/sequelize/lib/instance-validator.js:193:7)\n    at _.forIn (/app/node_modules/sequelize/lib/instance-validator.js:142:30)\n    at /app/node_modules/lodash/lodash.js:4905:15\n    at Function.forIn (/app/node_modules/lodash/lodash.js:12950:11)\n    at InstanceValidator._perAttributeValidators (/app/node_modules/sequelize/lib/instance-validator.js:125:7)\n    at InstanceValidator._validate (/app/node_modules/sequelize/lib/instance-validator.js:70:12)\n    at runHooks.then (/app/node_modules/sequelize/lib/instance-validator.js:107:14)\n    at tryCatcher (/app/node_modules/bluebird/js/release/util.js:16:23)\n    at Promise._settlePromiseFromHandler (/app/node_modules/bluebird/js/release/promise.js:547:31)\n    at Promise._settlePromise (/app/node_modules/bluebird/js/release/promise.js:604:18)\n    at Promise._settlePromise0 (/app/node_modules/bluebird/js/release/promise.js:649:10)\n    at Promise._settlePromises (/app/node_modules/bluebird/js/release/promise.js:729:18)\n    at _drainQueueStep (/app/node_modules/bluebird/js/release/async.js:93:12)\n    at _drainQueue (/app/node_modules/bluebird/js/release/async.js:86:9)\n    at Async._drainQueues (/app/node_modules/bluebird/js/release/async.js:102:5)\n    at Immediate.Async.drainQueues [as _onImmediate] (/app/node_modules/bluebird/js/release/async.js:15:14)\n    at runCallback (timers.js:705:18)\n    at tryOnImmediate (timers.js:676:5)\n    at processImmediate (timers.js:658:5)",
peertube_1  |           "message": "\"https://peert:8080/accounts/peertube\" is not a valid url."
peertube_1  |         }
peertube_1  |       },

```

**Comment by Chocobozzz** [comment]
Because `peert:8080` is not a valid domain. It should be `peert.com` or `peert.org` etc

**Comment by ValorNaram** [comment]
Thank you :)
