### ISSUE TITLE
[Plugin] peertubeHelpers.translate seems not usable

### ISSUE THREAD

**Issue by ZeroAurora** [Chocobozzz/PeerTube#3014]
**What happened?**
The plugin API reference says that `peertubeHelpers.translate()` returns a Promise. To simply my work, I used a function to work around it.
```javascript
function translate (string) {
  peertubeHelpers.translate(string)
    .then(result => result, () => string)
}
let a = translate('foo')
let b = translate('bar')
```
However, when I loaded the plugin, PeerTube kept warning me that `peertubeHelpers.translate is not a function`. Thinking I might have done something wrong, I rewrited the function into:
```javascript
function translate (string) {
  peertubeHelpers.translate(string)
    .then(result => console.log(result))
}
translate('foo')
translate('bar')
```
Then I loaded the plugin, but it still told me that "peertubeHelpers.translate is not a function".
Am I doing something wrong? If so, what should I do?
**What do you expect to happen instead?**
Strings should be translated. At least, they should be logged into the console.

**Additional information**
* PeerTube version or URL: a949f67
* NodeJS version: v10.22.0

<details><summary>Logs</summary>

```
[localhost:9000] 2020-07-28 20:55:18.643 error: Cannot register plugin peertube-plugin-<hide>. {
  "err": {
    "stack": "TypeError: peertubeHelpers.translate is not a function\n    at translate (/home/zeroaurora/repos/ZeroAurora/PeerTube/storage/plugins/node_modules/peertube-plugin-<hide>/main.js:6:21)\n    at Object.register (/home/zeroaurora/repos/ZeroAurora/PeerTube/storage/plugins/node_modules/peertube-plugin-<hide>/main.js:27:11)\n    at PluginManager.<anonymous> (/home/zeroaurora/repos/ZeroAurora/PeerTube/dist/server/lib/plugins/plugin-manager.js:301:21)\n    at Generator.next (<anonymous>)\n    at /home/zeroaurora/repos/ZeroAurora/PeerTube/node_modules/tslib/tslib.js:114:75\n    at new Promise (<anonymous>)\n    at Object.__awaiter (/home/zeroaurora/repos/ZeroAurora/PeerTube/node_modules/tslib/tslib.js:110:16)\n    at PluginManager.registerPlugin (/home/zeroaurora/repos/ZeroAurora/PeerTube/dist/server/lib/plugins/plugin-manager.js:292:24)\n    at PluginManager.<anonymous> (/home/zeroaurora/repos/ZeroAurora/PeerTube/dist/server/lib/plugins/plugin-manager.js:266:43)\n    at Generator.next (<anonymous>)\n    at fulfilled (/home/zeroaurora/repos/ZeroAurora/PeerTube/node_modules/tslib/tslib.js:111:62)",
    "message": "peertubeHelpers.translate is not a function"
  }
}
```
</details>

**Comment by rigelk** [comment]
How did you import peertubeHelpers?

**Comment by ZeroAurora** [comment]
In the register function of `main.js`:
```javascript
async function register ({
  (others),
  peertubeHelpers
}) {
  function translate (string) {
    peertubeHelpers.translate(string)
      .then(result => console.log(result))
  }
  // ...
}
```

**Comment by ZeroAurora** [comment]
Oh I see, I may use `translate` in a wrong place. I should call it in client's plugin file, not the server's. Sorry for disturbing!
