### ISSUE TITLE
YouTube Import Fails On Certain Videos - (node:7985) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '1' of null

### ISSUE THREAD

**Issue by own3mall** [Chocobozzz/PeerTube#3049]
**What happened?**

Some YouTube videos fail to import.

**What do you expect to happen instead?**

All YouTube videos should be importable.

**Steps to reproduce:**

1.  Try to import this video to any PeerTube instance.  https://www.youtube.com/watch?v=QI5IaILWaXs

2.  Nothing happens in the Web UI.

3.  Log shows:  

`Aug 07 16:04:33 videos peertube[7964]: (node:7985) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '1' of null
Aug 07 16:04:33 videos peertube[7964]:     at files.reduce ({PATH_TO_PEERTUBE_INSTANCE}/versions/peertube-v2.2.0/dist/server/helpers/youtube-dl.js:57:32)
Aug 07 16:04:33 videos peertube[7964]:     at Array.reduce (<anonymous>)
Aug 07 16:04:33 videos peertube[7964]:     at youtubeDL.getSubs ({PATH_TO_PEERTUBE_INSTANCE}/versions/peertube-v2.2.0/dist/server/helpers/youtube-dl.js:55:41)
Aug 07 16:04:33 videos peertube[7964]:     at {PATH_TO_PEERTUBE_INSTANCE}/versions/peertube-v2.2.0/node_modules/youtube-dl/lib/youtube-dl.js:298:12
Aug 07 16:04:33 videos peertube[7964]:     at done ({PATH_TO_PEERTUBE_INSTANCE}/versions/peertube-v2.2.0/node_modules/youtube-dl/lib/youtube-dl.js:25:12)
Aug 07 16:04:33 videos peertube[7964]:     at fn.apply.then.r ({PATH_TO_PEERTUBE_INSTANCE}/versions/peertube-v2.2.0/node_modules/youtube-dl/node_modules/universalify/index.js:23:46)
Aug 07 16:04:33 videos peertube[7964]:     at process._tickCallback (internal/process/next_tick.js:68:7)
Aug 07 16:04:33 videos peertube[7964]: (node:7985) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 29)`

**Additional information**
* PeerTube version or URL:  2.2.0
* Browser name/version:  Firefox Latest
* NodeJS version:   v10.22.0

**Comment by own3mall** [comment]
Never mind, it works in the latest version of PeerTube (2.3.0).  I guess I didn't see a release email this time.
