### ISSUE TITLE
I can't run it for production

### ISSUE THREAD

**Issue by myveb** [Chocobozzz/PeerTube#31]
Hello,
I have installed it successfully, but I can't run it for production.
I have built a new database, and have setup the nginx conf file and the production.yaml file under the guide, but I haven't setup the Systemd tempete, I don't know how to do it.
Then when I run "NODE_ENV=production npm start" under peertube directory, it shows the bellow error:
```
> peertube@0.0.1 start /root/PeerTube
> node server

info: [tube.xxx.net:80] Database is ready.
error: [tube.xxx.net:80] uncaughtException: type "json" does not exist
{ date: 'Wed Jan 18 2017 14:38:22 GMT+0800 (CST)',
  process:
   { pid: 4536,
     uid: 0,
     gid: 0,
     cwd: '/root/PeerTube',
     execPath: '/usr/local/bin/node',
     version: 'v7.4.0',
     argv: [ '/usr/local/bin/node', '/root/PeerTube/server' ],
     memoryUsage:
      { rss: 81862656,
        heapTotal: 76152832,
        heapUsed: 43398880,
        external: 62284 } },
  os:
   { loadavg: [ 0.14306640625, 0.13330078125, 0.2197265625 ],
     uptime: 2689054 },
  trace:
   [ { column: 14,
       file: '/root/PeerTube/node_modules/sequelize/lib/dialects/postgres/query.js',
       function: 'Query.formatError',
       line: 357,
       method: 'formatError',
       native: false },
     { column: 19,
       file: '/root/PeerTube/node_modules/sequelize/lib/dialects/postgres/query.js',
       function: '',
       line: 88,
       method: null,
       native: false },
     { column: 13,
       file: 'events.js',
       function: 'emitOne',
       line: 96,
       method: null,
       native: false },
     { column: 7,
       file: 'events.js',
       function: 'Query.emit',
       line: 188,
       method: 'emit',
       native: false },
     { column: 8,
       file: '/root/PeerTube/node_modules/pg/lib/query.js',
       function: 'Query.handleError',
       line: 131,
       method: 'handleError',
       native: false },
     { column: 26,
       file: '/root/PeerTube/node_modules/pg/lib/client.js',
       function: '',
       line: 180,
       method: null,
       native: false },
     { column: 13,
       file: 'events.js',
       function: 'emitOne',
       line: 96,
       method: null,
       native: false },
     { column: 7,
       file: 'events.js',
       function: 'Connection.emit',
       line: 188,
       method: 'emit',
       native: false },
     { column: 12,
       file: '/root/PeerTube/node_modules/pg/lib/connection.js',
       function: '',
       line: 121,
       method: null,
       native: false },
     { column: 13,
       file: 'events.js',
       function: 'emitOne',
       line: 96,
       method: null,
       native: false },
     { column: 7,
       file: 'events.js',
       function: 'Socket.emit',
       line: 188,
       method: 'emit',
       native: false },
     { column: 18,
       file: '_stream_readable.js',
       function: 'readableAddChunk',
       line: 176,
       method: null,
       native: false },
     { column: 10,
       file: '_stream_readable.js',
       function: 'Socket.Readable.push',
       line: 134,
       method: 'Readable.push',
       native: false },
     { column: 20,
       file: 'net.js',
       function: 'TCP.onread',
       line: 551,
       method: 'onread',
       native: false } ],
  stack:
   [ 'SequelizeBaseError: type "json" does not exist',
     '    at Query.formatError (/root/PeerTube/node_modules/sequelize/lib/dialects/postgres/query.js:357:14)',
     '    at Query.<anonymous> (/root/PeerTube/node_modules/sequelize/lib/dialects/postgres/query.js:88:19)',
     '    at emitOne (events.js:96:13)',
     '    at Query.emit (events.js:188:7)',
     '    at Query.handleError (/root/PeerTube/node_modules/pg/lib/query.js:131:8)',
     '    at Connection.<anonymous> (/root/PeerTube/node_modules/pg/lib/client.js:180:26)',
     '    at emitOne (events.js:96:13)',
     '    at Connection.emit (events.js:188:7)',
     '    at Socket.<anonymous> (/root/PeerTube/node_modules/pg/lib/connection.js:121:12)',
     '    at emitOne (events.js:96:13)',
     '    at Socket.emit (events.js:188:7)',
     '    at readableAddChunk (_stream_readable.js:176:18)',
     '    at Socket.Readable.push (_stream_readable.js:134:10)',
     '    at TCP.onread (net.js:551:20)' ] }

npm ERR! Linux 3.2.0-4-amd64
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "start"
npm ERR! node v7.4.0
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! peertube@0.0.1 start: `node server`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the peertube@0.0.1 start script 'node server'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the peertube package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node server
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs peertube
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls peertube
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /root/PeerTube/npm-debug.log
```

Then I run "NODE_ENV=production npm run check", it says:
```
Checking server is up (http://tube.xxx.net:80/api/v1/ping)...
FAIL.
Checking CORS headers for the torrent (http://tube.xxx.net:80/static/torrents/test.torrent)...
access-control-allow-origin is not present.
access-control-allow-methods is not present.
access-control-allow-headers is not present.
FAIL.
Checking CORS headers for the video (http://tube.xxx.net:80/static/webseed/test.mp4)...
access-control-allow-origin is not present.
access-control-allow-methods is not present.
access-control-allow-headers is not present.
FAIL.
Checking tracker websocket (ws://tube.xxx.net:80:80/tracker/socket)...
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: unexpected server response (502)
    at ClientRequest.response (/root/PeerTube/node_modules/ws/lib/WebSocket.js:719:15)
    at Object.onceWrapper (events.js:290:19)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:473:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:99:23)
    at Socket.socketOnData (_http_client.js:362:20)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
/root/PeerTube/node_modules/scripty/cli.js:38
    if (er) { throw er }
              ^

Error: Error: scripty - script "fail" failed by exiting with a non-zero code (1).
    at ChildProcess.<anonymous> (/root/PeerTube/node_modules/scripty/lib/run/spawn-script.js:11:10)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:885:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)

npm ERR! Linux 3.2.0-4-amd64
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "check"
npm ERR! node v7.4.0
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! peertube@0.0.1 check: `scripty`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the peertube@0.0.1 check script 'scripty'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the peertube package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     scripty
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs peertube
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls peertube
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /root/PeerTube/npm-debug.log
```

The content of file /root/PeerTube/npm-debug.log is:
```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'run', 'check' ]
2 info using npm@3.10.10
3 info using node@v7.4.0
4 verbose run-script [ 'precheck', 'check', 'postcheck' ]
5 info lifecycle peertube@0.0.1~precheck: peertube@0.0.1
6 silly lifecycle peertube@0.0.1~precheck: no script for precheck, continuing
7 info lifecycle peertube@0.0.1~check: peertube@0.0.1
8 verbose lifecycle peertube@0.0.1~check: unsafe-perm in lifecycle true
9 verbose lifecycle peertube@0.0.1~check: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/root/PeerTube/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
10 verbose lifecycle peertube@0.0.1~check: CWD: /root/PeerTube
11 silly lifecycle peertube@0.0.1~check: Args: [ '-c', 'scripty' ]
12 silly lifecycle peertube@0.0.1~check: Returned: code: 1  signal: null
13 info lifecycle peertube@0.0.1~check: Failed to exec check script
14 verbose stack Error: peertube@0.0.1 check: `scripty`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:255:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:885:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid peertube@0.0.1
16 verbose cwd /root/PeerTube
17 error Linux 3.2.0-4-amd64
18 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "check"
19 error node v7.4.0
20 error npm  v3.10.10
21 error code ELIFECYCLE
22 error peertube@0.0.1 check: `scripty`
22 error Exit status 1
23 error Failed at the peertube@0.0.1 check script 'scripty'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the peertube package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     scripty
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs peertube
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls peertube
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by Chocobozzz** [comment]
What is your PostgreSQL version?

**Comment by myveb** [comment]
@Chocobozzz 
Hello,
it's psql (PostgreSQL) 9.1.24
When I tried to install postgresql-9.4 before, it shows some errors, so I run "apt-get install postgresql".

**Comment by myveb** [comment]
I run peertube on Debian 8 (kernel 4.9) succeffuly, the postgresql version is 9.3.
but I can't visit the website, whatever I visit, it will be blank.their source code are all like this:
```
<!DOCTYPE html>
<html>
  <head>
    <title>PeerTube</title>

    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- The following comment is used by the server to prerender OpenGraph tags -->
    <!-- opengraph tags -->
    <!-- Do not remove it! -->

    <link rel="icon" type="image/png" href="/client/assets/favicon.png" />

    <!-- TODO: bundle it with webpack when https://github.com/webpack/webpack/pull/1931 will be merged -->
    <script src="/client/assets/webtorrent/webtorrent.min.js"></script>

    <!-- base url -->
    <base href="/">
  </head>

  <!-- 3. Display the application -->
  <body>

    <my-app>
    </my-app>

  <script type="text/javascript" src="/client/polyfills.363a0881c6f5d41562bb.bundle.js" defer></script><script type="text/javascript" src="/client/vendor.a9e58f694e3e5fcca025.bundle.js" defer></script><script type="text/javascript" src="/client/main.5e4e489d4a835fa513b0.bundle.js" defer></script></body>
</html>

```

**Comment by myveb** [comment]
When I try to visit the js file like "http://xxx.com/client/polyfills.363a0881c6f5d41562bb.bundle.js" or "http://xxx.com/polyfills.363a0881c6f5d41562bb.bundle.js", it shows 404 error.

**Comment by Chocobozzz** [comment]
Make `npm run build` and try to clean your website cache.

**Comment by myveb** [comment]
@Chocobozzz Yes, I have run the command and cleaned the cache, it's still blank.

**Comment by myveb** [comment]
@Chocobozzz Can you please help me to install it ? I will be glad to pay some money for this.

**Comment by Chocobozzz** [comment]
No need for money, thanks :)

What is the output of your `npm run build` command, the content of your resulting `index.html` and the content of your `client/dist` directory?

**Comment by myveb** [comment]
Hello,
Thank you for your reply. this is the content after I run the command `npm run build`
```
> peertube@0.0.1 build /root/PeerTube
> npm run build:client:prod


> peertube@0.0.1 build:client:prod /root/PeerTube
> scripty


> peertube-client@0.0.1 webpack /root/PeerTube/client
> webpack "--config" "config/webpack.prod.js" "--progress" "--profile" "--bail"
             11289ms building modules    4ms a6990m1ms c941ms asset44ms emitting                                                                                                                                                             Hash: 34b0f06d3a4c482d28d0                                                                                                                                                                                                                   Version: webpack 2.1.0-beta.25
Time: 20181ms
                                   Asset     Size  Chunks             Chunk Name                                                                                                                                                             s
polyfills.363a0881c6f5d41562bb.bundle.js   172 kB       2  [emitted]  polyfills
    f4769f9bdb7466be65088239c12046d1.eot  20.1 kB          [emitted]
    e18bbf611f2a2e43afc071aa2f4e1512.ttf  45.4 kB          [emitted]
    00103e881a36640a08f869ff6888f0fd.eot   5.9 kB          [emitted]
   fa2772327f55d8198301fdb8bcfc8158.woff  23.4 kB          [emitted]
  448c34a56d699c29117adc64c43affeb.woff2    18 kB          [emitted]
   vendor.a9e58f694e3e5fcca025.bundle.js  1.44 MB       0  [emitted]  vendor
     main.5e4e489d4a835fa513b0.bundle.js   103 kB       1  [emitted]  main
    89889688147bd7575d6327160d64e760.svg   109 kB          [emitted]
                      assets/favicon.png  2.33 kB          [emitted]
     assets/webtorrent/webtorrent.min.js   263 kB          [emitted]
            assets/video-js/video.min.js   256 kB          [emitted]
        assets/video-js/video-js.min.css  39.3 kB          [emitted]
     assets/video-js/videojs-dock.min.js  4.25 kB          [emitted]
        assets/video-js/videojs-dock.css  1.56 kB          [emitted]
            standalone/videos/embed.html   3.7 kB          [emitted]
                              index.html     1 kB          [emitted]
 [479] ./src async 160 bytes {0} [built]
       [] -> factory:4ms building:0ms = 4ms
    + 906 hidden modules
Child html-webpack-plugin for "index.html":
        + 4 hidden modules
```

**Comment by myveb** [comment]
Hello,
Thank you for your reply. this is the content after I run the command `npm run build`
```
> peertube@0.0.1 build /root/PeerTube
> npm run build:client:prod


> peertube@0.0.1 build:client:prod /root/PeerTube
> scripty


> peertube-client@0.0.1 webpack /root/PeerTube/client
> webpack "--config" "config/webpack.prod.js" "--progress" "--profile" "--bail"
             11289ms building modules    4ms a6990m1ms c941ms asset44ms emitting                                                                                                                                                             Hash: 34b0f06d3a4c482d28d0                                                                                                                                                                                                                   Version: webpack 2.1.0-beta.25
Time: 20181ms
                                   Asset     Size  Chunks             Chunk Name                                                                                                                                                             s
polyfills.363a0881c6f5d41562bb.bundle.js   172 kB       2  [emitted]  polyfills
    f4769f9bdb7466be65088239c12046d1.eot  20.1 kB          [emitted]
    e18bbf611f2a2e43afc071aa2f4e1512.ttf  45.4 kB          [emitted]
    00103e881a36640a08f869ff6888f0fd.eot   5.9 kB          [emitted]
   fa2772327f55d8198301fdb8bcfc8158.woff  23.4 kB          [emitted]
  448c34a56d699c29117adc64c43affeb.woff2    18 kB          [emitted]
   vendor.a9e58f694e3e5fcca025.bundle.js  1.44 MB       0  [emitted]  vendor
     main.5e4e489d4a835fa513b0.bundle.js   103 kB       1  [emitted]  main
    89889688147bd7575d6327160d64e760.svg   109 kB          [emitted]
                      assets/favicon.png  2.33 kB          [emitted]
     assets/webtorrent/webtorrent.min.js   263 kB          [emitted]
            assets/video-js/video.min.js   256 kB          [emitted]
        assets/video-js/video-js.min.css  39.3 kB          [emitted]
     assets/video-js/videojs-dock.min.js  4.25 kB          [emitted]
        assets/video-js/videojs-dock.css  1.56 kB          [emitted]
            standalone/videos/embed.html   3.7 kB          [emitted]
                              index.html     1 kB          [emitted]
 [479] ./src async 160 bytes {0} [built]
       [] -> factory:4ms building:0ms = 4ms
    + 906 hidden modules
Child html-webpack-plugin for "index.html":
        + 4 hidden modules
```

**Comment by myveb** [comment]
This is the content of the file index.html which is under dist directory
```
<!DOCTYPE html>
<html>
  <head>
    <title>PeerTube</title>

    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- The following comment is used by the server to prerender OpenGraph tags -->
    <!-- opengraph tags -->
    <!-- Do not remove it! -->

    <link rel="icon" type="image/png" href="/client/assets/favicon.png" />

    <!-- TODO: bundle it with webpack when https://github.com/webpack/webpack/pull/1931 will be merged -->
    <script src="/client/assets/webtorrent/webtorrent.min.js"></script>

    <!-- base url -->
    <base href="/">
  </head>

  <!-- 3. Display the application -->
  <body>

    <my-app>
    </my-app>

  <script type="text/javascript" src="/client/polyfills.935c029f74ebd1a1ac9e.bundle.js" defer></script><script type="text/javascript" src="/client/vendor.d337d20295ccf0ee292a.bundle.js" defer></script><script type="text/javascript" src="/client/main.516f291298b5e90677d0.bundle.js" defer></script></body>
</html>
```

**Comment by myveb** [comment]
And this is the content of the client/dist directory
```
total 1932
-rw-r--r-- 1 root root    5900 Jan 19 12:09 00103e881a36640a08f869ff6888f0fd.eot
-rw-r--r-- 1 root root   18028 Jan 19 12:09 448c34a56d699c29117adc64c43affeb.woff2
-rw-r--r-- 1 root root  108738 Jan 19 12:09 89889688147bd7575d6327160d64e760.svg
drwxr-xr-x 4 root root    4096 Jan 18 20:32 assets
-rw-r--r-- 1 root root       3 Jan 18 21:34 a.txt
-rw-r--r-- 1 root root   45404 Jan 19 12:09 e18bbf611f2a2e43afc071aa2f4e1512.ttf
-rw-r--r-- 1 root root   20127 Jan 19 12:09 f4769f9bdb7466be65088239c12046d1.eot
-rw-r--r-- 1 root root   23424 Jan 19 12:09 fa2772327f55d8198301fdb8bcfc8158.woff
-rw-r--r-- 1 root root    1005 Jan 19 12:09 index.html
-rw-r--r-- 1 root root  103096 Jan 19 12:09 main.5e4e489d4a835fa513b0.bundle.js
-rw-r--r-- 1 root root  174352 Jan 19 12:09 polyfills.363a0881c6f5d41562bb.bundle.js
drwxr-xr-x 3 root root    4096 Jan 18 20:32 standalone
-rw-r--r-- 1 root root 1441308 Jan 19 12:09 vendor.a9e58f694e3e5fcca025.bundle.js
-rw-r--r-- 1 root root     235 Jan 19 12:09 webpack-assets.json
```

**Comment by Chocobozzz** [comment]
> This is the content of the file index.html which is under dist directory

You mean `client/dist` directory? If yes, please contact me by [email](https://github.com/chocobozzz/).

**Comment by Chocobozzz** [comment]
The source of the bug was a bad Nginx configuration

**Comment by hersche** [comment]
hey, i am not shure if it's about the same, but i can imagine, it's kind of a setup-error..

when i do

    NODE_ENV=production npm start

it crashes (i tried this because of the first post here).

but when i do, like in the production-howto (service peertube start is my method), and do a

    ssh -L 9000:localhost:9000 user@server

i can access it via localhost:9000 relative good (there's a message about unfinished oauth-configuration, but the gui appears).

if i try to access via the wanted domain and nginx, i have a blank page and 0 bytes transmitted.

first, i had nginx-errors about a invalid proxy-url (connection refused and ipv6-format - now 127.0.0.1), but they are gone and new entrys only appear in the access-log now.

i also created a new database to be shure it take the right domain..

most of the configs are copied and only little edited. maybe you have a idea what it can be?
