### ISSUE TITLE
folder .dist no found and peertube is running perfect

### ISSUE THREAD

**Issue by AnonymousWebHacker** [Chocobozzz/PeerTube#3187]
```
peertube@streamer:~$ pwd
/var/www/peertube
peertube@streamer:~$ node .dist/server/tools/peertube-import-videos.js
internal/modules/cjs/loader.js:968
  throw err;
  ^

Error: Cannot find module '/var/www/peertube/.dist/server/tools/peertube-import-videos.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:965:15)
    at Function.Module._load (internal/modules/cjs/loader.js:841:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
peertube@streamer:~$

```

**Comment by rigelk** [comment]
The folder is called "dist", not ".dist".
