### ISSUE TITLE
Videos are paused on Firefox 81

### ISSUE THREAD

**Issue by AnonymousWebHacker** [Chocobozzz/PeerTube#3192]
It happens to me that in my instance, the users who have a Firefox browser, the videos are cut (it plays up to a certain part and they stay on stop). While chrome does not happen that. Why is this happening in Mozilla Firefox? And how can I solve it? Do most of my users use firefox?The version is the last, 81.0.1

**Comment by Chocobozzz** [comment]
Please correctly fill the template.

**Comment by AnonymousWebHacker** [comment]
**Additional information**
* PeerTube version and URL: v 2.4.0 URL: (whitout internet on localhost)
* Browser name and version: MozillaFirefox
* NodeJS version: v12.19.0
Logs
All rigth on logs

**Comment by Chocobozzz** [comment]
I'm sorry but without a public URL to reproduce and investigate I can't help

**Comment by AnonymousWebHacker** [comment]
Well, what can you recommend me, so that I can investigate the possible causes?

**Comment by Chocobozzz** [comment]
Did you enable transcoding? WebTorrent? HLS?

**Comment by AnonymousWebHacker** [comment]
Yes
![peertube](https://user-images.githubusercontent.com/43164089/97340295-fc5c5e80-1859-11eb-8ec3-aea775aea2bd.png)

, of course, transcoding is enabled, it is in automatic

**Comment by Chocobozzz** [comment]
Do you have errors in your web browser console logs?

**Comment by AnonymousWebHacker** [comment]
These are the most frequently repeated errors.
OS: Ubuntu Server  4 CPU , 4 GB RAM
```
**error[28/10/2020 13:09:39] Error in controller.**
{
  "err": "Error: ENOENT: no such file or directory, stat '/var/www/peertube/storage/avatars/cd77066c-f67f-4afa-aec8-747aa1ce9d17.jpg'"
}
**error[28/10/2020 13:11:09] Cannot execute processUndoDislike with many retries.**
{
  "err": {
    "stack": "Error: Unknown dislike by account 44 for video 676.\n    at /var/www/peertube/versions/peertube-v2.4.0/dist/server/lib/activitypub/process/process-undo.js:74:23\n    at Generator.next (<anonymous>)\n    at fulfilled (/var/www/peertube/versions/peertube-v2.4.0/node_modules/tslib/tslib.js:111:62)",
    "message": "Unknown dislike by account 44 for video 676."
  }
}
**error[28/10/2020 13:40:53] Receiving request in INBOX by ourselves!**
{
  "id": "https://peertube.azeroth.cu/accounts/peertube/likes/602",
  "type": "View",
  "actor": "https://peertube.azeroth.cu/accounts/peertube",
  "object": "https://peertube.azeroth.website/videos/watch/a201ab86-4018-4a2d-bfd4-619bc7582603",
  "to": [
    "https://www.w3.org/ns/activitystreams#Public",
    "https://peertube.azeroth.cu/accounts/peertube/followers",
    "https://peertube.azeroth.cu/video-channels/j.frost_photoshop/followers",
    "https://peertube.azeroth.cu/accounts/johnnyfrost/followers"
  ],
  "cc": [],
  "@context": [
    "https://www.w3.org/ns/activitystreams",
    "https://w3id.org/security/v1",
    {
      "RsaSignature2017": "https://w3id.org/security#RsaSignature2017"
    }
  ],
  "signature": {
    "type": "RsaSignature2017",
    "creator": "https://peertube.azeroth.cu/accounts/peertube",
    "created": "2020-10-28T17:40:53.634Z",
    "signatureValue": "Xs2IqD5c63eh2jh2t0h7RQ6oXxea0wix317FH8F4U1y0epJcOX90DN+fymo+G4eHHiu1B6m0iFYNqO9VdtX3aglfuk5ED2mR38sO5AtrEOvSNNwjQ2CgwUraiqovZZ8afeDB+CHftH2plaX/bj9WzLBt8B4aSvaZubYqcFsgAvMWR+2MfdIasJuqYPgTXL0T6YULRXexYYwB2sVzXIjnllDrLUz7/pT4FHFe4TiKgAylGJMlAhX4BbJFuaA0k5EmC7jLe/vXZkQFTGAZeis+USRm3ZR8evxwMphqFDGvGCegf77LG7zqlVvtDLvSt4KjABYgjfu+MM19v2307QKC3g=="
  }
}
**error[28/10/2020 14:03:51] Cannot execute onVideoFileOptimizerSuccess with many retries.**
{
  "err": {
    "stack": "TypeError: Cannot destructure property 'videoDatabase' of '(intermediate value)' as it is undefined.\n    at /var/www/peertube/versions/peertube-v2.4.0/dist/server/lib/job-queue/handlers/video-transcoding.js:70:17\n    at Generator.next (<anonymous>)\n    at fulfilled (/var/www/peertube/versions/peertube-v2.4.0/node_modules/tslib/tslib.js:111:62)",
    "message": "Cannot destructure property 'videoDatabase' of '(intermediate value)' as it is undefined."
  }
}
**error[23/10/2020 14:03:51] Cannot execute job 110 in queue video-transcoding.**
{
  "payload": {
    "type": "optimize",
    "videoUUID": "175437ac-a5bd-4ef9-8be7-beee3b7c6d79",
    "isNewVideo": true
  },
  "err": {
    "stack": "TypeError: Cannot destructure property 'videoDatabase' of '(intermediate value)' as it is undefined.\n    at /var/www/peertube/versions/peertube-v2.4.0/dist/server/lib/job-queue/handlers/video-transcoding.js:70:17\n    at Generator.next (<anonymous>)\n    at fulfilled (/var/www/peertube/versions/peertube-v2.4.0/node_modules/tslib/tslib.js:111:62)",
    "message": "Cannot destructure property 'videoDatabase' of '(intermediate value)' as it is undefined."
  }
}
**error[23/10/2020 16:31:49] Cannot update youtube-dl.**
{
  "err": {
    "stack": "Error: write EPROTO 140447808280448:error:14094417:SSL routines:ssl3_read_bytes:sslv3 alert illegal parameter:../deps/openssl/openssl/ssl/record/rec_layer_s3.c:1544:SSL alert number 47\n\n    at WriteWrap.onWriteComplete [as oncomplete] (internal/stream_base_commons.js:94:16)",
    "message": "write EPROTO 140447808280448:error:14094417:SSL routines:ssl3_read_bytes:sslv3 alert illegal parameter:../deps/openssl/openssl/ssl/record/rec_layer_s3.c:1544:SSL alert number 47\n",
    "errno": "EPROTO",
    "code": "EPROTO",
    "syscall": "write"
  }
}
**error[23/10/2020 19:39:57] Error in controller.**
{
  "err": "TypeError [ERR_INVALID_URL]: Invalid URL: \n    at onParseError (internal/url.js:257:9)\n    at new URL (internal/url.js:333:5)\n    at Object.sanitizeUrl (/var/www/peertube/versions/peertube-v2.4.0/dist/server/helpers/core-utils.js:106:23)\n    at /var/www/peertube/versions/peertube-v2.4.0/dist/server/controllers/api/search.js:127:34\n    at Generator.next (<anonymous>)\n    at fulfilled (/var/www/peertube/versions/peertube-v2.4.0/node_modules/tslib/tslib.js:111:62)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (internal/process/task_queues.js:97:5)"
}
**error[24/10/2020 22:18:35] Cannot execute job 157 in queue video-transcoding.**
{
  "payload": {
    "type": "new-resolution",
    "videoUUID": "03e0dbd7-b087-4789-aab5-8c95a58dce3f",
    "resolution": 240,
    "isPortraitMode": false
  },
  "err": {
    "stack": "SequelizeForeignKeyConstraintError: insert or update on table \"videoFile\" violates foreign key constraint \"videoFile_videoId_fkey\"\n    at Query.formatError (/var/www/peertube/versions/peertube-v2.4.0/node_modules/sequelize/lib/dialects/postgres/query.js:295:16)\n    at /var/www/peertube/versions/peertube-v2.4.0/node_modules/sequelize/lib/dialects/postgres/query.js:72:18\n    at tryCatcher (/var/www/peertube/versions/peertube-v2.4.0/node_modules/bluebird/js/release/util.js:16:23)\n    at Promise._settlePromiseFromHandler (/var/www/peertube/versions/peertube-v2.4.0/node_modules/bluebird/js/release/promise.js:547:31)\n    at Promise._settlePromise (/var/www/peertube/versions/peertube-v2.4.0/node_modules/bluebird/js/release/promise.js:604:18)\n    at Promise._settlePromise0 (/var/www/peertube/versions/peertube-v2.4.0/node_modules/bluebird/js/release/promise.js:649:10)\n    at Promise._settlePromises (/var/www/peertube/versions/peertube-v2.4.0/node_modules/bluebird/js/release/promise.js:725:18)\n    at _drainQueueStep (/var/www/peertube/versions/peertube-v2.4.0/node_modules/bluebird/js/release/async.js:93:12)\n    at _drainQueue (/var/www/peertube/versions/peertube-v2.4.0/node_modules/bluebird/js/release/async.js:86:9)\n    at Async._drainQueues (/var/www/peertube/versions/peertube-v2.4.0/node_modules/bluebird/js/release/async.js:102:5)\n    at Immediate.Async.drainQueues [as _onImmediate] (/var/www/peertube/versions/peertube-v2.4.0/node_modules/bluebird/js/release/async.js:15:14)\n    at processImmediate (internal/timers.js:461:21)",
    "message": "insert or update on table \"videoFile\" violates foreign key constraint \"videoFile_videoId_fkey\"",
    "name": "SequelizeForeignKeyConstraintError",
    "parent": {
      "stack": "error: insert or update on table \"videoFile\" violates foreign key constraint \"videoFile_videoId_fkey\"\n    at Parser.parseErrorMessage (/var/www/peertube/versions/peertube-v2.4.0/node_modules/pg-protocol/dist/parser.js:278:15)\n    at Parser.handlePacket (/var/www/peertube/versions/peertube-v2.4.0/node_modules/pg-protocol/dist/parser.js:126:29)\n    at Parser.parse (/var/www/peertube/versions/peertube-v2.4.0/node_modules/pg-protocol/dist/parser.js:39:38)\n    at Socket.<anonymous> (/var/www/peertube/versions/peertube-v2.4.0/node_modules/pg-protocol/dist/index.js:8:42)\n    at Socket.emit (events.js:314:20)\n    at addChunk (_stream_readable.js:298:12)\n    at readableAddChunk (_stream_readable.js:273:9)\n    at Socket.Readable.push (_stream_readable.js:214:10)\n    at TCP.onStreamRead (internal/stream_base_commons.js:188:23)",
      "message": "insert or update on table \"videoFile\" violates foreign key constraint \"videoFile_videoId_fkey\"",
      "length": 260,
      "name": "error",
      "severity": "ERROR",
      "code": "23503",
      "detail": "Key (videoId)=(536) is not present in table \"video\".",
      "schema": "public",
      "table": "videoFile",
      "constraint": "videoFile_videoId_fkey",
      "file": "ri_triggers.c",
      "line": "3266",
      "routine": "ri_ReportViolation",
      "sql": "INSERT INTO \"videoFile\" (\"id\",\"resolution\",\"size\",\"extname\",\"infoHash\",\"fps\",\"metadata\",\"videoId\",\"createdAt\",\"updatedAt\") VALUES (DEFAULT,$1,$2,$3,$4,$5,$6,$7,$8,$9) RETURNING *;",
      "parameters": [
        240,
        33455643,
        ".mp4",
        "3547061b1fedfa2ccef6f567c80bce271aea3b1b",
        30,
        "{\"chapters\":[],\"format\":{\"nb_streams\":2,\"nb_programs\":0,\"format_name\":\"mov,mp4,m4a,3gp,3g2,mj2\",\"format_long_name\":\"QuickTime / MOV\",\"start_time\":0,\"duration\":745.64,\"size\":33455643,\"bit_rate\":358946,\"probe_score\":100,\"tags\":{\"major_brand\":\"isom\",\"minor_version\":\"512\",\"compatible_brands\":\"isomiso2avc1mp41\",\"encoder\":\"Lavf57.83.100\"}},\"streams\":[{\"index\":0,\"codec_name\":\"h264\",\"codec_long_name\":\"H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10\",\"profile\":\"High\",\"codec_type\":\"video\",\"codec_time_base\":\"1/60\",\"codec_tag_string\":\"avc1\",\"codec_tag\":\"0x31637661\",\"width\":426,\"height\":240,\"coded_width\":426,\"coded_height\":240,\"has_b_frames\":2,\"sample_aspect_ratio\":\"640:639\",\"display_aspect_ratio\":\"16:9\",\"pix_fmt\":\"yuv420p\",\"level\":31,\"color_range\":\"unknown\",\"color_space\":\"unknown\",\"color_transfer\":\"unknown\",\"color_primaries\":\"unknown\",\"chroma_location\":\"left\",\"field_order\":\"unknown\",\"timecode\":\"N/A\",\"refs\":1,\"is_avc\":\"true\",\"nal_length_size\":4,\"id\":\"N/A\",\"r_frame_rate\":\"30/1\",\"avg_frame_rate\":\"30/1\",\"time_base\":\"1/15360\",\"start_pts\":0,\"start_time\":0,\"duration_ts\":11452416,\"duration\":745.6,\"bit_rate\":222150,\"max_bit_rate\":\"N/A\",\"bits_per_raw_sample\":8,\"nb_frames\":22368,\"nb_read_frames\":\"N/A\",\"nb_read_packets\":\"N/A\",\"tags\":{\"language\":\"und\",\"handler_name\":\"VideoHandler\"},\"disposition\":{\"default\":1,\"dub\":0,\"original\":0,\"comment\":0,\"lyrics\":0,\"karaoke\":0,\"forced\":0,\"hearing_impaired\":0,\"visual_impaired\":0,\"clean_effects\":0,\"attached_pic\":0,\"timed_thumbnails\":0}},{\"index\":1,\"codec_name\":\"aac\",\"codec_long_name\":\"AAC (Advanced Audio Coding)\",\"profile\":\"LC\",\"codec_type\":\"audio\",\"codec_time_base\":\"1/44100\",\"codec_tag_string\":\"mp4a\",\"codec_tag\":\"0x6134706d\",\"sample_fmt\":\"fltp\",\"sample_rate\":44100,\"channels\":2,\"channel_layout\":\"stereo\",\"bits_per_sample\":0,\"id\":\"N/A\",\"r_frame_rate\":\"0/0\",\"avg_frame_rate\":\"0/0\",\"time_base\":\"1/44100\",\"start_pts\":0,\"start_time\":0,\"duration_ts\":32881666,\"duration\":745.616009,\"bit_rate\":128559,\"max_bit_rate\":128559,\"bits_per_raw_sample\":\"N/A\",\"nb_frames\":32112,\"nb_read_frames\":\"N/A\",\"nb_read_packets\":\"N/A\",\"tags\":{\"language\":\"und\",\"handler_name\":\"SoundHandler\"},\"disposition\":{\"default\":1,\"dub\":0,\"original\":0,\"comment\":0,\"lyrics\":0,\"karaoke\":0,\"forced\":0,\"hearing_impaired\":0,\"visual_impaired\":0,\"clean_effects\":0,\"attached_pic\":0,\"timed_thumbnails\":0}}]}",
        536,
        "2020-10-25 02:18:34.837 +00:00",
        "2020-10-25 02:18:34.837 +00:00"
      ]
    },
    "sql": "INSERT INTO \"videoFile\" (\"id\",\"resolution\",\"size\",\"extname\",\"infoHash\",\"fps\",\"metadata\",\"videoId\",\"createdAt\",\"updatedAt\") VALUES (DEFAULT,$1,$2,$3,$4,$5,$6,$7,$8,$9) RETURNING *;",
    "fields": null,
    "table": "videoFile",
    "index": "videoFile_videoId_fkey"
  }
}
**error[25/10/2020 2:04:32] Error in transcoding job.**
{
  "stdout": "",
  "stderr": "ffmpeg version 3.4.8-0ubuntu0.2 Copyright (c) 2000-2020 the FFmpeg developers\n  built with gcc 7 (Ubuntu 7.5.0-3ubuntu1~18.04)\n  configuration: --prefix=/usr --extra-version=0ubuntu0.2 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --enable-gpl --disable-stripping --enable-avresample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librubberband --enable-librsvg --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-omx --enable-openal --enable-opengl --enable-sdl2 --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libopencv --enable-libx264 --enable-shared\n  libavutil      55. 78.100 / 55. 78.100\n  libavcodec     57.107.100 / 57.107.100\n  libavformat    57. 83.100 / 57. 83.100\n  libavdevice    57. 10.100 / 57. 10.100\n  libavfilter     6.107.100 /  6.107.100\n  libavresample   3.  7.  0 /  3.  7.  0\n  libswscale      4.  8.100 /  4.  8.100\n  libswresample   2.  9.100 /  2.  9.100\n  libpostproc    54.  7.100 / 54.  7.100\nInput #0, mov,mp4,m4a,3gp,3g2,mj2, from '/var/www/peertube/storage/videos/c473de96-fa1e-454a-afc5-bb338c53ce79-720.mp4':\n  Metadata:\n    major_brand     : isom\n    minor_version   : 512\n    compatible_brands: isomiso2mp41\n    encoder         : Lavf57.83.100\n  Duration: 00:02:06.11, start: 0.000000, bitrate: 687 kb/s\n    Stream #0:0(und): Video: av1 (av01 / 0x31307661), none, 1280x720, 553 kb/s, 30 fps, 30 tbr, 15360 tbn, 15360 tbc (default)\n    Metadata:\n      handler_name    : VideoHandler\n    Stream #0:1(eng): Audio: aac (LC) (mp4a / 0x6134706D), 44100 Hz, stereo, fltp, 128 kb/s (default)\n    Metadata:\n      handler_name    : SoundHandler\nStream mapping:\n  Stream #0:0 -> #0:0 (? (?) -> h264 (libx264))\n  Stream #0:1 -> #0:1 (aac (native) -> aac (native))\nDecoder (codec av1) not found for input stream #0:0\n"
}
```

**Comment by Chocobozzz** [comment]
> Decoder (codec av1) not found for input stream #0:0

Your transcoding job does not work: try to update your ffmpeg or try to upload a non av1 video.

**Comment by AnonymousWebHacker** [comment]
@Chocobozzz What packages does peertube use to transcode apart from ffmpeg?
that is, what other packages do I have to have installed?

**Comment by rigelk** [comment]
@AnonymousWebHacker no other package is required for transcoding, bit your distribution might have flavours of ffmpeg

**Comment by AnonymousWebHacker** [comment]
I am using the default of the ubuntu repositories, I am going to try directly from the ffmpeg repositories and tell them if it solves me.
Thanks for the answers.

**Comment by AnonymousWebHacker** [comment]
I installed ffmpeg version 4.2.4 And I have done something better, but the videos are still sticking
