### ISSUE TITLE
There is no speed to watch video

### ISSUE THREAD

**Issue by myveb** [Chocobozzz/PeerTube#32]
Hello,
I have installed PeerTube successfully, and uploaded some videos to test, but I can't watch the videos, there is no speed.
I have checked the videos, they are do in the directory "/root/PeerTube/videos" of server, and they are all mp4 type files, and on the videos list page, there are right snapshots of these videos, but when I opened one of them, there was no download speed, and no upload speed.

**Comment by Chocobozzz** [comment]
Please open the browser console and pastebin the errors (console errors or network errors).

**Comment by myveb** [comment]
Hello,
Thank you for you reply, the browser console says that "GET http://tube.60miao.club/static/webseed/ae9b4b3d-f461-4806-95c9-d9e450a5a230.mp4 403 (Forbidden)"

**Comment by myveb** [comment]
@Chocobozzz I really need help for this, please help me.

**Comment by Chocobozzz** [comment]
@myveb Please check this line in your Nginx configuration https://github.com/Chocobozzz/PeerTube/blob/develop/support/nginx/peertube#L33 corresponds to your videos directory on your file system. 

Check the directory rights too (readable by `www-data`).

**Comment by myveb** [comment]
@Chocobozzz Thank you very much, I will check it.

**Comment by myveb** [comment]
@Chocobozzz I have reinstalled the whole OS and peertube, it shows new error when I run command "npm run build" under PeerTube directory. I'm using Debian 8 with kernel 4.9
The postgresql version is 9.4, the nodejs version is 4.7, the npm version is 3.10
```
> peertube@0.0.1 build /root/PeerTube
> npm run build:client:prod


> peertube@0.0.1 build:client:prod /root/PeerTube
> scripty


> peertube-client@0.0.1 webpack /root/PeerTube/client
> webpack "--config" "config/webpack.prod.js" "--progress" "--profile" "--bail"

SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/root/PeerTube/client/node_modules/awesome-typescript-loader/src/entry.ts:2:18)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/root/PeerTube/client/config/webpack.common.js:13:23)
    at Module._compile (module.js:409:26)

npm ERR! Linux 4.9.0-040900rc8-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "webpack" "--" "--config" "config/webpack.prod.js" "--progress" "--profile" "--bail"
npm ERR! node v4.7.3
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! peertube-client@0.0.1 webpack: `webpack "--config" "config/webpack.prod.js" "--progress" "--profile" "--bail"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the peertube-client@0.0.1 webpack script 'webpack "--config" "config/webpack.prod.js" "--progress" "--profile" "--bail"'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the peertube-client package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     webpack "--config" "config/webpack.prod.js" "--progress" "--profile" "--bail"
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs peertube-client
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls peertube-client
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /root/PeerTube/client/npm-debug.log
/root/PeerTube/node_modules/scripty/cli.js:38
    if (er) { throw er }
              ^

Error: Error: scripty - script "fail" failed by exiting with a non-zero code (1).
    at ChildProcess.<anonymous> (/root/PeerTube/node_modules/scripty/lib/run/spawn-script.js:11:10)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at maybeClose (internal/child_process.js:854:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:222:5)

npm ERR! Linux 4.9.0-040900rc8-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "build:client:prod"
npm ERR! node v4.7.3
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! peertube@0.0.1 build:client:prod: `scripty`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the peertube@0.0.1 build:client:prod script 'scripty'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the peertube package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     scripty
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs peertube
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls peertube
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /root/PeerTube/npm-debug.log

npm ERR! Linux 4.9.0-040900rc8-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "build"
npm ERR! node v4.7.3
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! peertube@0.0.1 build: `npm run build:client:prod`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the peertube@0.0.1 build script 'npm run build:client:prod'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the peertube package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run build:client:prod
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs peertube
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls peertube
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /root/PeerTube/npm-debug.log
```

**Comment by Chocobozzz** [comment]
Sorry @myveb, a node dependency broke the build.

Should be fixed now.

**Comment by myveb** [comment]
@Chocobozzz Thank you! it's fixed now.
I have checked the video directory, and it's correct, it's "/root/PeerTube/videos", I have set the directory rights to 777, but it's still the same error in the browser console, it's 

`GET http://xxx.com/static/webseed/ae9b4b3d-f461-4806-95c9-d9e450a5a230.mp4 403 (Forbidden).`

**Comment by Chocobozzz** [comment]
Do not install PeerTube as root or in the root directory. It's the reason why nginx can't access to your static files.

Please create a peertube user and put the project in a standard directory (`var/www` for example).

**Comment by myveb** [comment]
@Chocobozzz Hello, I have installed it with user peertube, it shows some error when I run command "npm run build" under "/home/wwwroot/PeerTube" directory
```
sh-4.2$ npm install
npm WARN enoent ENOENT: no such file or directory, open '/home/wwwroot/PeerTube/package.json'
npm WARN PeerTube No description
npm WARN PeerTube No repository field.
npm WARN PeerTube No README data
npm WARN PeerTube No license field.
sh-4.2$ npm run build
npm ERR! Linux 3.2.0-4-amd64
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "build"
npm ERR! node v7.4.0
npm ERR! npm  v3.10.10
npm ERR! path /home/wwwroot/PeerTube/package.json
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall open

npm ERR! enoent ENOENT: no such file or directory, open '/home/wwwroot/PeerTube/package.json'
npm ERR! enoent ENOENT: no such file or directory, open '/home/wwwroot/PeerTube/package.json'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! Please include the following file with any support request:
npm ERR!     /home/wwwroot/PeerTube/npm-debug.log
```

**Comment by myveb** [comment]
Is it right that I run the command `npm run build` as root user, and run the command `NODE_ENV=production npm start` as peertube user ? the nginx run as www user.

**Comment by Chocobozzz** [comment]
@myveb Take example of the Dockerfile https://github.com/Chocobozzz/PeerTube-Docker/blob/master/Dockerfile#L17

Create a user, clone the repo and execute the install commands.

**Comment by myveb** [comment]
@Chocobozzz Thank you for your guide, I will do it, I have prepared new server to run this project, there are hundreds people will use it, I can send you their feedback to help this project.

**Comment by Chocobozzz** [comment]
Sure, do not hesitate to contact me by email.
