### ISSUE TITLE
Admin config page broken for the last 4-5  updates

### ISSUE THREAD

**Issue by ReK2Fernandez** [Chocobozzz/PeerTube#320]
Hey! <3 just wanted to give the heads ups in case this is just not my issue before the software released 1.0 that already for a couple versions I updated our server the UI config page is broken.. I get an error 
and comes out empty... is not a big deal since everything seems to be working and nothing really got deleted etc... but a FYI

https://video.hispagatos.org/admin/config/edit-custom

Thanks

**Comment by rigelk** [comment]
Hi @ReK2Fernandez ! Since we cannot look at guarded routes from your instance, could you could you look at the logs of peertube when accessing this page?

**Comment by ReK2Fernandez** [comment]
@rigelk sure, will do when I get home tonight or tomorrow night at the latest. thank you.

**Comment by ReK2Fernandez** [comment]
@rigelk here finally had time to get this.
```
Mar 06 21:22:37 video peertube[9708]: [video.hispagatos.org:443] 2018-03-02 21:22:37.919 error: Error in controller. {
Mar 06 21:22:37 video peertube[9708]:   "error": "Error: Configuration property \"instance.default_client_route\" is not defined\n    at Config.get (/var/www/PeerTube/versions/peertube-v1.0.0-alpha.4/node_modules/config/lib/config.js:194:11)\n    at Object.get DEFAULT_CLIENT_ROUTE [as DEFAULT_CLIENT_ROUTE] (/var/www/PeerTube/versions/peertube-v1.0.0-alpha.4/dist/server/initializers/constants.js:156:52)\n    at customConfig (/var/www/PeerTube/versions/peertube-v1.0.0-alpha.4/dist/server/controllers/api/config.js:118:64)\n    at /var/www/PeerTube/versions/peertube-v1.0.0-alpha.4/dist/server/controllers/api/config.js:84:22\n    at Generator.next (<anonymous>)\n    at /var/www/PeerTube/versions/peertube-v1.0.0-alpha.4/dist/server/controllers/api/config.js:7:71\n    at new Promise (<anonymous>)\n    at __awaiter (/var/www/PeerTube/versions/peertube-v1.0.0-alpha.4/dist/server/controllers/api/config.js:3:12)\n    at getCustomConfig (/var/www/PeerTube/versions/peertube-v1.0.0-alpha.4/dist/server/controllers/api/config.js:83:12)\n    at /var/www/PeerTube/versions/peertube-v1.0.0-alpha.4/dist/server/middlewares/async.js:12:32\n    at Layer.handle [as handle_request] (/var/www/PeerTube/versions/peertube-v1.0.0-alpha.4/node_modules/express/lib/router/layer.js:95:5)\n    at next (/var/www/PeerTube/versions/peertube-v1.0.0-alpha.4/node_modules/express/lib/router/route.js:137:13)\n    at /var/www/PeerTube/versions/peertube-v1.0.0-alpha.4/dist/server/middlewares/user-right.js:18:16\n    at Layer.handle [as handle_request] (/var/www/PeerTube/versions/peertube-v1.0.0-alpha.4/node_modules/express/lib/router/layer.js:95:5)\n    at next (/var/www/PeerTube/versions/peertube-v1.0.0-alpha.4/node_modules/express/lib/router/route.js:137:13)\n    at oAuthServer.authenticate.err (/var/www/PeerTube/versions/peertube-v1.0.0-alpha.4/dist/server/middlewares/oauth.js:22:16)\n    at ExpressOAuthServer.<anonymous> (/var/www/PeerTube/versions/peertube-v1.0.0-alpha.4/node_modules/express-oauth-server/index.js:54:9)\n    at PassThroughHandlerContext.finallyHandler (/var/www/PeerTube/vers
Mar 06 21:22:37 video peertube[9708]: ions/peertube-v1.0.0-alpha.4/node_modules/bluebird/js/release/finally.js:57:23)\n    at PassThroughHandlerContext.tryCatcher (/var/www/PeerTube/versions/peertube-v1.0.0-alpha.4/node_modules/bluebird/js/release/util.js:16:23)\n    at Promise._settlePromiseFromHandler (/var/www/PeerTube/versions/peertube-v1.0.0-alpha.4/node_modules/bluebird/js/release/promise.js:512:31)\n    at Promise._settlePromise (/var/www/PeerTube/versions/peertube-v1.0.0-alpha.4/node_modules/bluebird/js/release/promise.js:569:18)\n    at Promise._settlePromise0 (/var/www/PeerTube/versions/peertube-v1.0.0-alpha.4/node_modules/bluebird/js/release/promise.js:614:10)\n    at Promise._settlePromises (/var/www/PeerTube/versions/peertube-v1.0.0-alpha.4/node_modules/bluebird/js/release/promise.js:693:18)\n    at Async._drainQueue (/var/www/PeerTube/versions/peertube-v1.0.0-alpha.4/node_modules/bluebird/js/release/async.js:133:16)\n    at Async._drainQueues (/var/www/PeerTube/versions/peertube-v1.0.0-alpha.4/node_modules/bluebird/js/release/async.js:143:10)\n    at Immediate.Async.drainQueues (/var/www/PeerTube/versions/peertube-v1.0.0-alpha.4/node_modules/bluebird/js/release/async.js:17:14)\n    at runCallback (timers.js:763:18)\n    at tryOnImmediate (timers.js:734:5)\n    at processImmediate (timers.js:716:5)"
Mar 06 21:22:37 video peertube[9708]: }
```

and

```
Mar 06 21:22:52 video peertube[9708]: [video.hispagatos.org:443] 2018-03-02 21:22:52.736 error: Error in controller. {
Mar 06 21:22:52 video peertube[9708]:   "error": "Error: Configuration property \"instance.default_client_route\" is not defined\n    at Config.get (/var/www/PeerTube/versions/peertube-v1.0.0-alpha.4/node_modules/config/lib/config.js:194:11)\n    at Object.get DEFAULT_CLIENT_ROUTE [as DEFAULT_CLIENT_ROUTE] (/var/www/PeerTube/versions/peertube-v1.0.0-alpha.4/dist/server/initializers/constants.js:156:52)\n    at /var/www/PeerTube/versions/peertube-v1.0.0-alpha.4/dist/server/controllers/api/config.js:36:68\n    at Generator.next (<anonymous>)\n    at fulfilled (/var/www/PeerTube/versions/peertube-v1.0.0-alpha.4/dist/server/controllers/api/config.js:4:58)\n    at <anonymous>\n    at process._tickCallback (internal/process/next_tick.js:118:7)"
Mar 06 21:22:52 video peertube[9708]: }
```

hope this helps. thanks.

**Comment by ReK2Fernandez** [comment]
must be that.. because the new configs do include that and I am missing it
```
peertube-latest/config/production.yaml.example:  default_client_route: '/videos/trending'
peertube-latest/config/default.yaml:  default_client_route: '/videos/trending'
```

will add this open in case is something else going on.

**Comment by Chocobozzz** [comment]
@ReK2Fernandez When you upgrade peertube you should copy the `default.yaml` file too. See the command of the production file: https://github.com/Chocobozzz/PeerTube/blob/develop/support/doc/production.md#upgrade  -> `sudo -u peertube cp /var/www/peertube/versions/peertube-${VERSION}/config/default.yaml /var/www/peertube/config/default.yaml`

**Comment by ReK2Fernandez** [comment]
@Chocobozzz like always you are right... I was using the first version of the update script and never updated it as you guys have updated the wiki.. is working now. thanks <3
