### ISSUE TITLE
Cannot set an avatar

### ISSUE THREAD

**Issue by Roki100** [Chocobozzz/PeerTube#3207]
**What happened?**
So 2 of my friends have got an issue where after uploading an avatar it just failed and set their avatar to 404, reuploading also fails

**What do you expect to happen instead?**
I expect avatars to change

**Steps to reproduce:**
I am not sure how to reproduce it but go to account settings and change the avatar

**Additional information**
* PeerTube version and URL: 2.4.0
* Browser name and version: Chrome/Opera GX (both were used)
* NodeJS version: 12.16.1

* Link to browser console log if useful:
* Link to server log if useful (`journalctl` or `/var/www/peertube/storage/logs/`):
```
2020-10-19 22:00:13.200 info: Updating 1 good actor follows and 0 bad actor follows scores in cache.
2020-10-19 22:00:13.239 info: Removing avatar file a55fcda7-02ae-4856-ac48-032edbce0d81.jpg.
2020-10-19 22:00:13.246 info: Remote account https://xxx/accounts/xxx updated
2020-10-19 22:00:13.537 info: xx.xx.xx.xxx - - [19/Oct/2020:20:00:13 +0000] "GET /lazy-static/avatars/a55fcda7-02ae-4856-ac48-032edbce0d81.jpg HTTP/1.0" 404 9 "https://xxx/my-account/settings" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.121 Safari/537.36 OPR/71.0.3770.234"
2020-10-19 22:00:22.430 info: xx.xx.xx.xxx - - [19/Oct/2020:20:00:22 +0000] "GET /api/v1/config/ HTTP/1.0" 304 - "https://xxx/my-account/settings" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.121 Safari/537.36 OPR/71.0.3770.234"
2020-10-19 22:00:22.434 info: xx.xx.xx.xxx - - [19/Oct/2020:20:00:22 +0000] "GET /api/v1/oauth-clients/local HTTP/1.0" 304 - "https://xxx/my-account/settings" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.121 Safari/537.36 OPR/71.0.3770.234"
2020-10-19 22:00:22.441 info: xx.xx.xx.xxx - - [19/Oct/2020:20:00:22 +0000] "GET /api/v1/users/me HTTP/1.0" 200 1874 "https://xxx/my-account/settings" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.121 Safari/537.36 OPR/71.0.3770.234"
2020-10-19 22:00:22.510 info: xx.xx.xx.xxx - - [19/Oct/2020:20:00:22 +0000] "GET /api/v1/videos/languages HTTP/1.0" 304 - "https://xxx/my-account/settings" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.121 Safari/537.36 OPR/71.0.3770.234"
2020-10-19 22:00:22.645 info: xx.xx.xx.xxx - - [19/Oct/2020:20:00:22 +0000] "GET /api/v1/users/me/video-quota-used HTTP/1.0" 304 - "https://xxx/my-account/settings" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.121 Safari/537.36 OPR/71.0.3770.234"
2020-10-19 22:00:22.756 info: xx.xx.xx.xxx - - [19/Oct/2020:20:00:22 +0000] "GET /api/v1/users/me/notifications?start=0&count=0&unread=true HTTP/1.0" 304 - "https://xxx/my-account/settings" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.121 Safari/537.36 OPR/71.0.3770.234"
2020-10-19 22:00:22.935 info: xx.xx.xx.xxx - - [19/Oct/2020:20:00:22 +0000] "GET /api/v1/plugins/peertube-plugin-bittube-logo-favicon/public-settings HTTP/1.0" 304 - "https://xxx/my-account/settings" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.121 Safari/537.36 OPR/71.0.3770.234"
2020-10-19 22:00:23.123 info: Lazy serve remote avatar image https://xxx/lazy-static/avatars/a55fcda7-02ae-4856-ac48-032edbce0d81.jpg.
2020-10-19 22:00:23.145 info: <it seems there is my instance IP> - - [19/Oct/2020:20:00:23 +0000] "GET /lazy-static/avatars/a55fcda7-02ae-4856-ac48-032edbce0d81.jpg HTTP/1.0" 404 9 "-" "PeerTube/2.4.0 (+https://xxx)"
2020-10-19 22:00:23.212 error: Error in ffmpeg webp convert process. {
Oct 19 22:00:23  peertube[7168]:   "stdout": "",
Oct 19 22:00:23  peertube[7168]:   "stderr": "ffmpeg version 4.3-2~16.04.york1 Copyright (c) 2000-2020 the FFmpeg developers\n  built with gcc 5.4.0 (Ubuntu 5.4.0-6ubuntu1~16.04.12) 20160609\n  configuration: --prefix=/usr --extra-version='2~16.04.york1' --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-avresample --disable-filter=resample --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librabbitmq --enable-librsvg --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --enable-pocketsphinx --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared\n  libavutil      56. 51.100 / 56. 51.100\n  libavcodec     58. 91.100 / 58. 91.100\n  libavformat    58. 45.100 / 58. 45.100\n  libavdevice    58. 10.100 / 58. 10.100\n  libavfilter     7. 85.100 /  7. 85.100\n  libavresample   4.  0.  0 /  4.  0.  0\n  libswscale      5.  7.100 /  5.  7.100\n  libswresample   3.  7.100 /  3.  7.100\n  libpostproc    55.  7.100 / 55.  7.100\n[mjpeg @ 0x55bb6a25d400] No JPEG data found in image\n[image2 @ 0x55bb6a25b880] decoding for stream 0 failed\n[image2 @ 0x55bb6a25b880] Could not find codec parameters for stream 0 (Video: mjpeg, none(bt470bg/unknown/unknown)): unspecified size\
Oct 19 22:00:23  peertube[7168]: nConsider increasing the value for the 'analyzeduration' and 'probesize' options\nInput #0, image2, from '/var/www/peertube/storage/tmp/pending-40f25e82-7797-4c6f-a29e-0f5b30e4cb53.jpg':\n  Duration: 00:00:00.04, start: 0.000000, bitrate: 1 kb/s\n    Stream #0:0: Video: mjpeg, none(bt470bg/unknown/unknown), 25 tbr, 25 tbn, 25 tbc\nStream mapping:\n  Stream #0:0 -> #0:0 (mjpeg (native) -> mjpeg (native))\nPress [q] to stop, [?] for help\n[mjpeg @ 0x55bb6a25db40] No JPEG data found in image\nError while decoding stream #0:0: Invalid data found when processing input\nCannot determine format of input stream 0:0 after EOF\nError marking filters as finished\nConversion failed!\n"
Oct 19 22:00:23  peertube[7168]: }
Oct 19 22:00:23  peertube[7168]: [xxx:443] 2020-10-19 22:00:23.213 warn: Cannot process remote avatar https://xxx/lazy-static/avatars/a55fcda7-02ae-4856-ac48-032edbce0d81.jpg. {
Oct 19 22:00:23  peertube[7168]:   "err": {
Oct 19 22:00:23  peertube[7168]:     "stack": "Error: ffmpeg exited with code 1: Error while decoding stream #0:0: Invalid data found when processing input\nCannot determine format of input stream 0:0 after EOF\nError marking filters as finished\nConversion failed!\n\n    at ChildProcess.<anonymous> (/var/www/peertube/versions/peertube-v2.4.0/node_modules/fluent-ffmpeg/lib/processor.js:182:22)\n    at ChildProcess.emit (events.js:311:20)\n    at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)",
Oct 19 22:00:23  peertube[7168]:     "message": "ffmpeg exited with code 1: Error while decoding stream #0:0: Invalid data found when processing input\nCannot determine format of input stream 0:0 after EOF\nError marking filters as finished\nConversion failed!\n"
Oct 19 22:00:23  peertube[7168]:   }
Oct 19 22:00:23  peertube[7168]: }
Oct 19 22:00:23  peertube[7168]: [xxx:443] 2020-10-19 22:00:23.214 info: xx.xx.xx.xxx - - [19/Oct/2020:20:00:23 +0000] "GET /lazy-static/avatars/40f25e82-7797-4c6f-a29e-0f5b30e4cb53.jpg HTTP/1.0" 404 9 "https://xxx/my-account/settings" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.121 Safari/537.36 OPR/71.0.3770.234"
```

**Comment by Roki100** [comment]
I am not sure if anyone will reproduce but there is the image that seemed to fail for me 3rd time, and i cant change the pfp from 404 at all 
![93d2ff580f493cc74aa2220c9a8a2fed](https://user-images.githubusercontent.com/35699619/96642993-37750400-1327-11eb-815f-df62ba4a465c.png)

**Comment by Chocobozzz** [comment]
What is the origin avatar URL that ffmpeg fails to process?

**Comment by Roki100** [comment]
I changed my instance URL with use of update-host script, and after that i tried to upload an avatar again, and it worked.
The avatar url was linking to a 404 not found.
In database the avatar id was linking to this 404, and onDisk was f, so i think ffmpeg was trying to process 404.
I think the issue can be closed for now as update-host seem to have fixed it (atleast for now).

**Comment by JasXSL** [comment]
Just leaving a note here that I had the same issue after switching from cloudflare SSL to letsencrypt SSL. And running the update-host script resolved it.
