### ISSUE TITLE
Peertube - 502 bad gateway after failed upgrade : duplicate entries

### ISSUE THREAD

**Issue by tomdereub** [Chocobozzz/PeerTube#3209]
**What happened?**

Peertube upgrade from 2.3 to 2.4 failed, and pre-upgrade backup restoration failed too, because of a GPG error about yarndpkg repository.

I tried this command :  `curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -`, then restore again, and restoration has worked, but with some warnings like : 
```
2020-10-20 12:19:34,356: WARNING - ERREUR:  n'a pas pu créer l'index unique « actor_preferred_username_server_id »
2020-10-20 12:19:34,357: WARNING - DÉTAIL : La clé ("preferredUsername", "serverId")=(flossome__orthodontics, 378) est dupliquée.
```
Then I had a 502 bad gateway error when trying to access peertube.
I tried to upgrade, it has worked but I'm still with 502 bad gateway. The problem seems to be caused by duplicate entries in the database. I tried to remove them, but I'm blocked with an error for some entries : "ERREUR: UPDATE ou DELETE sur la table "videoChannel" viole la contrainte de clé étrangère". And I don't know how many duplicate entries there are.

**What do you expect to happen instead?**
Get back a working instance. And eventually understand what went wrong.

**Additional information**
* PeerTube version and URL: peertube 2.3, https://tube.plaf.fr, installed on yunohost s4.0.8
* Browser name and version:
* NodeJS version: 

* Link to server log if useful (`journalctl` or `/var/www/peertube/storage/logs/`):
First upgrade : https://paste.yunohost.org/raw/arobasefuv
Failed restore : https://paste.yunohost.org/raw/zicutumenu
Successful restore, but 502 bad gateway error : https://paste.yunohost.org/raw/cofijoqoqa
Upgrade : https://paste.yunohost.org/raw/pasujumudo

**Comment by Chocobozzz** [comment]
Hello,

See https://github.com/Chocobozzz/PeerTube/blob/develop/CHANGELOG.md#important-notes-2 (first bullet)

**Comment by tomdereub** [comment]
Hi, I tried and got this:

```
root@lamo:/home/admin# sudo -u postgres psql peertube_prod
psql: FATAL:  la base de données « peertube_prod » n'existe pas
root@lamo:/home/admin# sudo -u postgres psql peertube_peertube
psql (11.9 (Debian 11.9-0+deb10u1))
Saisissez « help » pour l'aide.

peertube_peertube=# select "preferredUsername" from actor where "serverId" is null group by "preferredUsername" having count(*) > 1;
 preferredUsername
-------------------
(0 ligne)
```

I find this kind of thing in the logs : 
```

oct. 21 10:38:26 peertube[25705]: [tube.plaf.fr:443] 2020-10-21 10:38:26.944 error: Cannot install application. {
oct. 21 10:38:26 peertube[25705]:   "err": {
oct. 21 10:38:26 peertube[25705]:     "stack": "SequelizeUniqueConstraintError: n'a pas pu créer l'index unique « actor_url »\n    at Query.formatError (/var/www/peertube/node_modules/sequelize/lib/dialects/postgres/query.js:327:16)\n    at /var/www/peertube/node_modules/sequelize/lib/dialects/postgres/query.js:72:18\n    at tryCatcher (/var/www/peertube/node_modules/bluebird/js/release/util.js:16:23)\n    at Promise._settlePromiseFromHandler (/var/www/peertube/node_modules/bluebird/js/release/promise.js:547:31)\n    at Promise._settlePromise (/var/www/peertube/node_modules/bluebird/js/release/promise.js:604:18)\n    at Promise._settlePromise0 (/var/www/peertube/node_modules/bluebird/js/release/promise.js:649:10)\n    at Promise._settlePromises (/var/www/peertube/node_modules/bluebird/js/release/promise.js:725:18)\n    at _drainQueueStep (/var/www/peertube/node_modules/bluebird/js/release/async.js:93:12)\n    at _drainQueue (/var/www/peertube/node_modules/bluebird/js/release/async.js:86:9)\n    at Async._drainQueues (/var/www/peertube/node_modules/bluebird/js/release/async.js:102:5)\n    at Immediate.Async.drainQueues [as _onImmediate] (/var/www/peertube/node_modules/bluebird/js/release/async.js:15:14)\n    at processImmediate (internal/timers.js:461:21)",
oct. 21 10:38:26 peertube[25705]:     "message": "n'a pas pu créer l'index unique « actor_url »",
oct. 21 10:38:26 peertube[25705]:     "name": "SequelizeUniqueConstraintError",
oct. 21 10:38:26 peertube[25705]:     "errors": {},
oct. 21 10:38:26 peertube[25705]:     "parent": {
oct. 21 10:38:26 peertube[25705]:       "stack": "error: n'a pas pu créer l'index unique « actor_url »\n    at Parser.parseErrorMessage (/var/www/peertube/node_modules/pg-protocol/dist/parser.js:241:15)\n    at Parser.handlePacket (/var/www/peertube/node_modules/pg-protocol/dist/parser.js:89:29)\n    at Parser.parse (/var/www/peertube/node_modules/pg-protocol/dist/parser.js:41:38)\n    at Socket.<anonymous> (/var/www/peertube/node_modules/pg-protocol/dist/index.js:8:42)\n    at Socket.emit (events.js:314:20)\n    at addChunk (_stream_readable.js:298:12)\n    at readableAddChunk (_stream_readable.js:273:9)\n    at Socket.Readable.push (_stream_readable.js:214:10)\n    at TCP.onStreamRead (internal/stream_base_commons.js:188:23)",
oct. 21 10:38:26 peertube[25705]:       "message": "n'a pas pu créer l'index unique « actor_url »",
oct. 21 10:38:26 peertube[25705]:       "length": 240,
oct. 21 10:38:26 peertube[25705]:       "name": "error",
oct. 21 10:38:26 peertube[25705]:       "severity": "ERREUR",
oct. 21 10:38:26 peertube[25705]:       "code": "23505",
oct. 21 10:38:26 peertube[25705]:       "detail": "La clé (url)=(https://video.nobodyhasthe.biz/video-channels/murdochmurdoch) est dupliquée.",
oct. 21 10:38:26 peertube[25705]:       "schema": "public",
oct. 21 10:38:26 peertube[25705]:       "table": "actor",
oct. 21 10:38:26 peertube[25705]:       "constraint": "actor_url",
oct. 21 10:38:26 peertube[25705]:       "file": "tuplesort.c",
oct. 21 10:38:26 peertube[25705]:       "line": "4056",
oct. 21 10:38:26 peertube[25705]:       "routine": "comparetup_index_btree",
oct. 21 10:38:26 peertube[25705]:       "sql": "CREATE UNIQUE INDEX \"actor_url\" ON \"actor\" (\"url\")"
oct. 21 10:38:26 peertube[25705]:     },
oct. 21 10:38:26 peertube[25705]:     "sql": "CREATE UNIQUE INDEX \"actor_url\" ON \"actor\" (\"url\")"
oct. 21 10:38:26 peertube[25705]:   }
oct. 21 10:38:26 peertube[25705]: }
```

**Comment by tomdereub** [comment]
I found this now : 

```
peertube_peertube=# select "url" from actor group by "url" having count(*) > 1;
                              url
---------------------------------------------------------------
 https://videos.cemea.org/video-channels/videos_equipe
 https://vault.mle.party/video-channels/shercloppones
 https://peertube.su/video-channels/flossome__orthodontics
 https://peertube.uno/video-channels/video_lezioni
 https://vault.mle.party/video-channels/sherclop_pones
 https://video.nobodyhasthe.biz/video-channels/murdoch_murdoch
 https://peertube.fr/video-channels/norzfunny
 https://video.ploud.fr/video-channels/kawayou_studio
 https://bittube.video/accounts/johndoe
 https://peertube.su/video-channels/mancia__ortho_dontics
 https://video.nobodyhasthe.biz/video-channels/murdochmurdoch
(11 lignes)
```

I don't know if it helps...

**Comment by tomdereub** [comment]
I tried some things, like searching this 11 url in the database (via adminer), and then : 
- delete one of the duplicate entries : for most of them I get an error because of "clés étrangères"
- change url and/or preferredUsername (adding a "2" at the end), and then restart peertube. I get new errors about duplicated tag names, and there are a lot of them, so impossible to change it by hand.

If there a way to "delete" federation of my instance, like keeping only local users and videos, to start again clearly ? Or an other way to clear this database ?

**Comment by Chocobozzz** [comment]
> If there a way to "delete" federation of my instance, like keeping only local users and videos, to start again clearly ? Or an other way to clear this database ?

No sorry, but removing this 11 actors in your database should work
