### ISSUE TITLE
Error in Peertube service due to npm?

### ISSUE THREAD

**Issue by AnonymousWebHacker** [Chocobozzz/PeerTube#3256]
**What happened?**

It was working perfect, until for the moment it stopped loading, and I realize when I look at the service that the npm is missing, it only works when I restart it. It's happened to me twice

**What do you expect to happen instead?**
#ALL THAT RIGHT WHEN RESTART SERVICE PEERTUBE
```
proxmox@streamer:~$ systemctl status peertube.service
? peertube.service - PeerTube daemon
     Loaded: loaded (/etc/systemd/system/peertube.service; enabled; vendor preset: enabled)
     Active: active (running) since Thu 2020-11-05 12:32:56 CST; 5min ago
   Main PID: 128403 (node)
      Tasks: 34 (limit: 2891)
     Memory: 261.8M
     CGroup: /system.slice/peertube.service
             +-128403 npm
             +-128431 /usr/bin/node /usr/lib/node_modules/npm/node_modules/update-notifier/check.js {"pkg":{"name":"npm","version":"6.14.8"}}
             +-128440 sh -c node dist/server
             +-128441 peertube

```
2 HOURS LATER THE PROCESS [npm] NO RUNING
```
proxmox@streamer:~$ systemctl status peertube.service
? peertube.service - PeerTube daemon
     Loaded: loaded (/etc/systemd/system/peertube.service; enabled; vendor preset: enabled)
     Active: active (running) since Thu 2020-11-05 12:32:56 CST; 2h 46min ago
   Main PID: 128403 (node)
      Tasks: 24 (limit: 2891)
     Memory: 608.1M
     CGroup: /system.slice/peertube.service
             +-128403 npm
             +-128440 sh -c node dist/server
             +-128441 peertube

```
**Steps to reproduce:**

**Additional information** ffmpeg version 4.2.4-1ubuntu0.1 Copyright (c) 2000-2020 the FFmpeg developers
* PeerTube version and URL: 2.4.0
* Browser name and version: (No internet, in SNET)
* NodeJS version: 12.19.0

* Link to browser console log if useful:
* Link to server log if useful (`journalctl` or `/var/www/peertube/storage/logs/`):
========================================================
#COMUN ERROR
```
warn[5/11/2020 21:34:46] Cannot process remote avatar https://peertube.azeroth.website/lazy-static/avatars/8decedc5-e044-4351-a9d6-7feacc0d17f9.jpg.
{
  "err": {
    "stack": "Error: ffmpeg exited with code 1: Error while decoding stream #0:0: Invalid data found when processing input\nCannot determine format of input stream 0:0 after EOF\nError marking filters as finished\nConversion failed!\n\n    at ChildProcess.<anonymous> (/var/www/peertube/versions/peertube-v2.4.0/node_modules/fluent-ffmpeg/lib/processor.js:182:22)\n    at ChildProcess.emit (events.js:314:20)\n    at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)",
    "message": "ffmpeg exited with code 1: Error while decoding stream #0:0: Invalid data found when processing input\nCannot determine format of input stream 0:0 after EOF\nError marking filters as finished\nConversion failed!\n"
  }
}
```
========================================================
```
error[5/11/2020 21:34:46] Error in ffmpeg webp convert process.
{
  "stdout": "",
  "stderr": "ffmpeg version 4.2.4-1ubuntu0.1 Copyright (c) 2000-2020 the FFmpeg developers\n  built with gcc 9 (Ubuntu 9.3.0-10ubuntu2)\n  configuration: --prefix=/usr --extra-version=1ubuntu0.1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-avresample --disable-filter=resample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librsvg --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-nvenc --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared\n  libavutil      56. 31.100 / 56. 31.100\n  libavcodec     58. 54.100 / 58. 54.100\n  libavformat    58. 29.100 / 58. 29.100\n  libavdevice    58.  8.100 / 58.  8.100\n  libavfilter     7. 57.100 /  7. 57.100\n  libavresample   4.  0.  0 /  4.  0.  0\n  libswscale      5.  5.100 /  5.  5.100\n  libswresample   3.  5.100 /  3.  5.100\n  libpostproc    55.  5.100 / 55.  5.100\n[mjpeg @ 0x55b67bdf3700] No JPEG data found in image\n[image2 @ 0x55b67bdf1700] decoding for stream 0 failed\n[image2 @ 0x55b67bdf1700] Could not find codec parameters for stream 0 (Video: mjpeg, none(bt470bg/unknown/unknown)): unspecified size\nConsider increasing the value for the 'analyzeduration' and 'probesize' options\nInput #0, image2, from '/var/www/peertube/storage/tmp/pending-bc34fd28-d0d8-40bd-9bac-66d5f3651f5e.jpg':\n  Duration: 00:00:00.04, start: 0.000000, bitrate: 1 kb/s\n    Stream #0:0: Video: mjpeg, none(bt470bg/unknown/unknown), 25 tbr, 25 tbn, 25 tbc\nStream mapping:\n  Stream #0:0 -> #0:0 (mjpeg (native) -> mjpeg (native))\nPress [q] to stop, [?] for help\n[mjpeg @ 0x55b67bdf4d00] No JPEG data found in image\nError while decoding stream #0:0: Invalid data found when processing input\nCannot determine format of input stream 0:0 after EOF\nError marking filters as finished\nConversion failed!\n"
}
```
========================================================
```
error[5/11/2020 21:39:22] Cannot execute job 4474 in queue activitypub-http-broadcast.
{
  "payload": {
    "uris": [
      "https://peertube.azeroth.website/inbox"
    ],
    "signatureActorId": 1,
    "body": {
      "id": "https://peertube.azeroth.cu/accounts/peertube/likes/743",
      "type": "View",
      "actor": "https://peertube.azeroth.cu/accounts/peertube",
      "object": "https://peertube.azeroth.website/videos/watch/7cbbd47a-8084-420f-ab29-1dce03de603d",
      "to": [
        "https://www.w3.org/ns/activitystreams#Public",
        "https://peertube.azeroth.cu/accounts/peertube/followers",
        "https://peertube.azeroth.website/video-channels/mi/followers",
        "https://peertube.azeroth.website/accounts/zirox/followers"
      ],
      "cc": []
    },
    "contextType": "View"
  },
  "err": {
  "stack": "jsonld.InvalidUrl: Dereferencing a URL did not result in a valid JSON-LD object. Possible causes are an inaccessible URL perhaps due to a same-origin policy (ensure the server uses CORS if you are using client-side JavaScript), too many redirects, a non-JSON response, or more than one HTTP Link Header was provided for a remote context.\n    at ContextResolver._fetchContext (/var/www/peertube/versions/peertube-v2.4.0/node_modules/jsonld/lib/ContextResolver.js:173:13)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (internal/process/task_queues.js:97:5)",
    "message": "Dereferencing a URL did not result in a valid JSON-LD object. Possible causes are an inaccessible URL perhaps due to a same-origin policy (ensure the server uses CORS if you are using client-side JavaScript), too many redirects, a non-JSON response, or more than one HTTP Link Header was provided for a remote context.",
    "name": "jsonld.InvalidUrl",
    "details": {
      "code": "loading remote context failed",
      "url": "https://www.w3.org/ns/activitystreams",
      "cause": {
        "stack": "jsonld.LoadDocumentError: URL could not be dereferenced, an error occurred.\n    at loadDocument (/var/www/peertube/versions/peertube-v2.4.0/node_modules/jsonld/lib/documentLoaders/node.js:74:13)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (internal/process/task_queues.js:97:5)",
        "message": "URL could not be dereferenced, an error occurred.",
        "name": "jsonld.LoadDocumentError",
        "details": {
          "code": "loading document failed",
          "url": "https://www.w3.org/ns/activitystreams",
          "cause": {
            "stack": "Error: write EPROTO 140104558094208:error:14094417:SSL routines:ssl3_read_bytes:sslv3 alert illegal parameter:../deps/openssl/openssl/ssl/record/rec_layer_s3.c:1544:SSL alert number 47\n\n    at WriteWrap.onWriteComplete [as oncomplete] (internal/stream_base_commons.js:94:16)",
            "message": "write EPROTO 140104558094208:error:14094417:SSL routines:ssl3_read_bytes:sslv3 alert illegal parameter:../deps/openssl/openssl/ssl/record/rec_layer_s3.c:1544:SSL alert number 47\n",
            "errno": "EPROTO",
            "code": "EPROTO",
            "syscall": "write"
          }
        }
      }
    }
  }
```
}

**Comment by rigelk** [comment]
hi @AnonymousWebHacker,

> I realize when I look at the service that the npm is missing

Could you be more specific?

The error logs shouldn't prevent the PeerTube service from running: they are job errors and are isolated from the main runtime.

**Comment by AnonymousWebHacker** [comment]
**fixed,** 
The problem is that in the peertube documentation, it says that it requires node 10. * and yarn approx 1.22 stable.
I was using direct repos, example I had updated to node 15. * and yarn more updated.

**solution**
on the same server, do the migration process,
1 - Backup
2 - Purge all packages related to that
3- Install everything from 0

I hope this helps someone who has the same problem

**Comment by rigelk** [comment]
@AnonymousWebHacker I'm surprised that yarn doesn't respect the engine restriction we put in the package.json.
