### ISSUE TITLE
Fall import URL external

### ISSUE THREAD

**Issue by AnonymousWebHacker** [Chocobozzz/PeerTube#3278]
```
Nov  9 05:30:32 streamer connmand[778]: Skipping server 144.100.3.5 KoD code INIT
Nov  9 05:30:36 streamer peertube[115607]: [peertube.azeroth.website:443] 2020-11-09 05:30:36.180 #033[32minfo#033[39m: Cannot fetch information from import for URL https://gametube.azeroth.website/upload/videos/2020/11/ynzRJc64gRxeEJOboUWK_05_c7d41168b0edfed332fc8f6746baae47_video.mp4. {
Nov  9 05:30:36 streamer peertube[115607]:   "err": {
Nov  9 05:30:36 streamer peertube[115607]:     "stack": "Error: Command failed with ENOENT: /var/www/peertube/versions/peertube-v2.4.0/node_modules/youtube-dl/bin/youtube-dl --dump-json -f best -j --flat-playlist -- https://gametube.azeroth.website/upload/videos/2020/11/ynzRJc64gRxeEJOboUWK_05_c7d41168b0edfed332fc8f6746baae47_video.mp4\nspawn /var/www/peertube/versions/peertube-v2.4.0/node_modules/youtube-dl/bin/youtube-dl ENOENT\n    at Process.ChildProcess._handle.onexit (internal/child_process.js:240:19)\n    at onErrorNT (internal/child_process.js:415:16)\n    at process._tickCallback (internal/process/next_tick.js:63:19)",
Nov  9 05:30:36 streamer peertube[115607]:     "message": "Command failed with ENOENT: /var/www/peertube/versions/peertube-v2.4.0/node_modules/youtube-dl/bin/youtube-dl --dump-json -f best -j --flat-playlist -- https://gametube.azeroth.website/upload/videos/2020/11/ynzRJc64gRxeEJOboUWK_05_c7d41168b0edfed332fc8f6746baae47_video.mp4\nspawn /var/www/peertube/versions/peertube-v2.4.0/node_modules/youtube-dl/bin/youtube-dl ENOENT",
Nov  9 05:30:36 streamer peertube[115607]:     "errno": "ENOENT",
Nov  9 05:30:36 streamer peertube[115607]:     "code": "ENOENT",
Nov  9 05:30:36 streamer peertube[115607]:     "syscall": "spawn /var/www/peertube/versions/peertube-v2.4.0/node_modules/youtube-dl/bin/youtube-dl",
Nov  9 05:30:36 streamer peertube[115607]:     "path": "/var/www/peertube/versions/peertube-v2.4.0/node_modules/youtube-dl/bin/youtube-dl",
Nov  9 05:30:36 streamer peertube[115607]:     "spawnargs": [
Nov  9 05:30:36 streamer peertube[115607]:       "--dump-json",
Nov  9 05:30:36 streamer peertube[115607]:       "-f",
Nov  9 05:30:36 streamer peertube[115607]:       "best",
Nov  9 05:30:36 streamer peertube[115607]:       "-j",
Nov  9 05:30:36 streamer peertube[115607]:       "--flat-playlist",
Nov  9 05:30:36 streamer peertube[115607]:       "--",
Nov  9 05:30:36 streamer peertube[115607]:       "https://gametube.azeroth.website/upload/videos/2020/11/ynzRJc64gRxeEJOboUWK_05_c7d41168b0edfed332fc8f6746baae47_video.mp4"
Nov  9 05:30:36 streamer peertube[115607]:     ],
Nov  9 05:30:36 streamer peertube[115607]:     "originalMessage": "spawn /var/www/peertube/versions/peertube-v2.4.0/node_modules/youtube-dl/bin/youtube-dl ENOENT",
Nov  9 05:30:36 streamer peertube[115607]:     "command": "/var/www/peertube/versions/peertube-v2.4.0/node_modules/youtube-dl/bin/youtube-dl --dump-json -f best -j --flat-playlist -- https://gametube.azeroth.website/upload/videos/2020/11/ynzRJc64gRxeEJOboUWK_05_c7d41168b0edfed332fc8f6746baae47_video.mp4",
Nov  9 05:30:36 streamer peertube[115607]:     "stdout": "",
Nov  9 05:30:36 streamer peertube[115607]:     "stderr": "",
Nov  9 05:30:36 streamer peertube[115607]:     "failed": true,
Nov  9 05:30:36 streamer peertube[115607]:     "timedOut": false,
Nov  9 05:30:36 streamer peertube[115607]:     "isCanceled": false,
Nov  9 05:30:36 streamer peertube[115607]:     "killed": false
Nov  9 05:30:36 streamer peertube[115607]:   }
Nov  9 05:30:36 streamer peertube[115607]: }
Nov  9 05:30:36 streamer peertube[115607]: [peertube.azeroth.website:443] 2020-11-09 05:30:36.185 #033[32minfo#033[39m: 144.100.1.244 - - [09/Nov/2020:10:30:36 +0000] "POST /api/v1/videos/imports/ HTTP/1.0" 400 56 "https://peertube.azeroth.website/videos/upload" "Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.183 Safari/537.36"
Nov  9 05:30:36 streamer connmand[778]: Failed to send DNS response to 26: Bad file descriptor
Nov  9 05:30:37 streamer connmand[778]: Skipping server 144.100.3.5 KoD code INIT

```

**Comment by JohnXLivingston** [comment]
Your url is wrong. https://gametube.azeroth.website/ does not exist.

**Comment by AnonymousWebHacker** [comment]
Hmm, the logs say it doesn't exist, thank you very much for that. But actually if there is that link, by the way, the site is mine too.
that is, the site exists and there is the link of the video to import.

on the other hand I started looking and it seems that it is not installed 
```
proxmox@streamer:/var/www/peertube/versions/peertube-v2.4.0/node_modules/youtube-dl/bin$ ls
details
```

**Comment by JohnXLivingston** [comment]
I can assure you that I can't connect to https://gametube.azeroth.website/ from my connection. There must be a network, firewall or DNS problem.
![image](https://user-images.githubusercontent.com/38844060/98584808-af02d700-22c6-11eb-88ea-32ebecfb119e.png)

**Comment by AnonymousWebHacker** [comment]
hahaha, sorry for not telling you, my network is a SNET, (street network), you won't get to it
![Captura de pantalla (92)](https://user-images.githubusercontent.com/43164089/98626105-41c86380-2311-11eb-8fb6-c0eb7942290a.png)

**Comment by Chocobozzz** [comment]
@AnonymousWebHacker Reinstall server node modules: `rm -rf node_modules && yarn install --pure-lockfile`. If the youtube-dl binary is not there, check errors in the output

**Comment by JohnXLivingston** [comment]
> hahaha, sorry for not telling you, my network is a SNET, (street network), you won't get to it

Is your peertube server on the SNET? And is the server sending request on the correct network interface?

**Comment by AnonymousWebHacker** [comment]
```
> rm -rf node_modules && yarn install --pure-lockfile

peertube@streamer:~$ ls
config  node_modules  package-lock.json  peertube-latest  peertube-v2.4.0  peertube-v2.4.0.zip  storage  versions
peertube@streamer:~$ rm -rf node_modules && yarn install --pure-lockfile
yarn install v1.22.5
info No lockfile found.
warning package-lock.json found. Your project contains lock files generated by tools other than Yarn. It is advised not to mix package managers in order to avoid resolution inconsistencies caused by unsynchronized lock files. To clear this warning, remove package-lock.json.
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
Done in 0.26s.
peertube@streamer:~$

```

**Comment by JohnXLivingston** [comment]
What are your server network interfaces? Is your server accessible only on the SNET? Your server has to have access to the internet for downloading the youtube-dl binary, but at the same time to your SNET to access gametube.azeroth.website. Make sure your network configuration is ok.

**Comment by AnonymousWebHacker** [comment]
> What are your server network interfaces? Is your server accessible only on the SNET? Your server has to have access to the internet for downloading the youtube-dl binary, but at the same time to your SNET to access gametube.azeroth.website. Make sure your network configuration is ok.

My server has a single network interface, esn32, which is perfectly accessible from SNET for everyone. In the case of npm and ..etc, which is installed from repos on the internet, if I give that interface access to the internet to install the packages

**Comment by AnonymousWebHacker** [comment]
Finaly i reinstall :)
