### ISSUE TITLE
520 Error after reboot

### ISSUE THREAD

**Issue by dislive** [Chocobozzz/PeerTube#3304]
I install peertube at yunohost.

1. After install - Peertube ОК
2. Reeboot server
3. Got error 502 (log)

**Additional information**
```
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   '/opt/node_n/n/versions/node/12.19.0/bin/node',
1 verbose cli   '/opt/node_n/n/versions/node/12/bin/npm',
1 verbose cli   'start'
1 verbose cli ]
2 info using npm@6.14.8
3 info using node@v12.19.0
4 verbose config Skipping project config: /var/www/peertube/.npmrc. (matches userconfig)
5 verbose run-script [ 'prestart', 'start', 'poststart' ]
6 info lifecycle peertube@2.4.0~prestart: peertube@2.4.0
7 info lifecycle peertube@2.4.0~start: peertube@2.4.0
8 verbose lifecycle peertube@2.4.0~start: unsafe-perm in lifecycle true
9 verbose lifecycle peertube@2.4.0~start: PATH: /opt/node_n/n/versions/node/12.19.0/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/var/www/peertube/node_modules/.bin:/opt/node_n/n/versions/node/12/bin:/opt/node_n/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
10 verbose lifecycle peertube@2.4.0~start: CWD: /var/www/peertube
11 silly lifecycle peertube@2.4.0~start: Args: [ '-c', 'node dist/server' ]
12 silly lifecycle peertube@2.4.0~start: Returned: code: 1  signal: null
13 info lifecycle peertube@2.4.0~start: Failed to exec start script
14 verbose stack Error: peertube@2.4.0 start: `node dist/server`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/opt/node_n/n/versions/node/12.19.0/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
14 verbose stack     at EventEmitter.emit (events.js:314:20)
14 verbose stack     at ChildProcess.<anonymous> (/opt/node_n/n/versions/node/12.19.0/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
14 verbose stack     at ChildProcess.emit (events.js:314:20)
14 verbose stack     at maybeClose (internal/child_process.js:1021:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
15 verbose pkgid peertube@2.4.0
16 verbose cwd /var/www/peertube
17 verbose Linux 4.19.0-12-cloud-amd64
18 verbose argv "/opt/node_n/n/versions/node/12.19.0/bin/node" "/opt/node_n/n/versions/node/12/bin/npm" "start"
19 verbose node v12.19.0
20 verbose npm  v6.14.8
21 error code ELIFECYCLE
22 error errno 1
23 error peertube@2.4.0 start: `node dist/server`
23 error Exit status 1
24 error Failed at the peertube@2.4.0 start script.
24 error This is probably not a problem with npm. There is likely additional logging output above.
25 verbose exit [ 1, true ]
```

* PeerTube instance:
  * URL:
  * version: 2.4.0~ynh1
  * NodeJS version: v10.21.0
  * Ffmpeg version:

* Browser name, version and platforms on which you could reproduce the bug:
* Link to browser console log if relevant:
* Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`):

**Comment by rigelk** [comment]
Hi @dislive,

It seems you are using a community-made packaging of PeerTube, namely https://github.com/YunoHost-Apps/peertube_ynh. Please reach out to them with logs at https://github.com/YunoHost-Apps/peertube_ynh/issues/ for further support. In case it doesn't work, you can always fall back to the production guide install which is the only one we can fully support here.
