### ISSUE TITLE
Enhance notification when exceeding playlist field size limit

### ISSUE THREAD

**Issue by pprw** [Chocobozzz/PeerTube#3350]
When editing a playlist description, there is no explicit message when exceeding 255 characters. There is only an error when saving.

Log shows "valeur trop longue pour le type character varying(255)" but the user is not really informed of that. 

A more explicit message would be great.

```
error[20/11/2020 à 11:44:36] Cannot execute updateVideoPlaylist with many retries.

{
  "err": {
    "stack": "SequelizeDatabaseError: valeur trop longue pour le type character varying(255)\n    at Query.formatError (/var/www/peertube/versions/peertube-v2.1.1/node_modules/sequelize/lib/dialects/postgres/query.js:366:16)\n    at query.catch.err (/var/www/peertube/versions/peertube-v2.1.1/node_modules/sequelize/lib/dialects/postgres/query.js:72:18)\n    at tryCatcher (/var/www/peertube/versions/peertube-v2.1.1/node_modules/bluebird/js/release/util.js:16:23)\n    at Promise._settlePromiseFromHandler (/var/www/peertube/versions/peertube-v2.1.1/node_modules/bluebird/js/release/promise.js:547:31)\n    at Promise._settlePromise (/var/www/peertube/versions/peertube-v2.1.1/node_modules/bluebird/js/release/promise.js:604:18)\n    at Promise._settlePromise0 (/var/www/peertube/versions/peertube-v2.1.1/node_modules/bluebird/js/release/promise.js:649:10)\n    at Promise._settlePromises (/var/www/peertube/versions/peertube-v2.1.1/node_modules/bluebird/js/release/promise.js:725:18)\n    at _drainQueueStep (/var/www/peertube/versions/peertube-v2.1.1/node_modules/bluebird/js/release/async.js:93:12)\n    at _drainQueue (/var/www/peertube/versions/peertube-v2.1.1/node_modules/bluebird/js/release/async.js:86:9)\n    at Async._drainQueues (/var/www/peertube/versions/peertube-v2.1.1/node_modules/bluebird/js/release/async.js:102:5)\n    at Immediate.Async.drainQueues [as _onImmediate] (/var/www/peertube/versions/peertube-v2.1.1/node_modules/bluebird/js/release/async.js:15:14)\n    at runCallback (timers.js:705:18)\n    at tryOnImmediate (timers.js:676:5)\n    at processImmediate (timers.js:658:5)",
    "message": "valeur trop longue pour le type character varying(255)",
    "name": "SequelizeDatabaseError",
    "parent": {
      "stack": "error: valeur trop longue pour le type character varying(255)\n    at Connection.parseE (/var/www/peertube/versions/peertube-v2.1.1/node_modules/pg/lib/connection.js:604:13)\n    at Connection.parseMessage (/var/www/peertube/versions/peertube-v2.1.1/node_modules/pg/lib/connection.js:403:19)\n    at Socket.<anonymous> (/var/www/peertube/versions/peertube-v2.1.1/node_modules/pg/lib/connection.js:123:22)\n    at Socket.emit (events.js:198:13)\n    at addChunk (_stream_readable.js:288:12)\n    at readableAddChunk (_stream_readable.js:269:11)\n    at Socket.Readable.push (_stream_readable.js:224:10)\n    at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)",
      "message": "valeur trop longue pour le type character varying(255)",
      "name": "error",
      "length": 108,
      "severity": "ERREUR",
      "code": "22001",
      "file": "varchar.c",
      "line": "624",
      "routine": "varchar",
      "sql": "UPDATE \"videoPlaylist\" SET \"description\"=$1,\"updatedAt\"=$2 WHERE \"id\" = $3",
      "parameters": [
        "Le séminaire a pour vocation principale de présenter les recherches en cours des chercheurs strasbourgeois des Archives Henri-Poincaré ou des chercheurs de passage à Strasbourg travaillant sur  des  thématiques  proches.  Les  thématiques  abordées  sont  en  lien  avec  les  recherches\r\ninterdisciplinaires sur les sciences et les technologies.",
        "2020-11-20 10:44:36.880 +00:00",
        36
      ]
    },
    "sql": "UPDATE \"videoPlaylist\" SET \"description\"=$1,\"updatedAt\"=$2 WHERE \"id\" = $3"
  }
}
```

**Comment by Chocobozzz** [comment]
Please fill the template: what is your peertube version/URL?

**Comment by pprw** [comment]
> Please fill the template: what is your peertube version/URL?

Sorry. 2.1.1 / https://videos.ahp-numerique.fr

**Comment by Chocobozzz** [comment]
Then please upgrade to 2.4 as it should fix your issue.
