### ISSUE TITLE
Migration vs Domain Change

### ISSUE THREAD

**Issue by AnonymousWebHacker** [Chocobozzz/PeerTube#3355]
**Describe the problem**
My server's operating system had problems, so I had to start the migration process. Reinstall the OS and from there, start the migration process.
The old peertube instance had this domain [peertube.azeroth.cu], and in the new instance, I did a domain change [peertube.azeroth.website]

**Steps**
1 - Configure nginx for the new domain
2  -Copy of config and video storage of the old instance peertube.azeroth.cu and BD postgresql
3 - Change the domain name in the configuration.

**Results**
The peertube instance was recovered, with a new domain, and all the data as was.

**The problem**
It turns out that there are errors:
1 - There is avatar of accounts that do not even load, or return to change the photos, they do not load
2 - As a result of this, there are also transcoding errors.

**Additional information**
Example Logs

```
error[5/11/2020 21:39:22] Cannot execute job 4474 in queue activitypub-http-broadcast.
{
  "payload": {
    "uris": [
      "https://peertube.azeroth.website/inbox"
    ],
    "signatureActorId": 1,
    "body": {
      "id": "https://peertube.azeroth.cu/accounts/peertube/likes/743",
      "type": "View",
      "actor": "https://peertube.azeroth.cu/accounts/peertube",
      "object": "https://peertube.azeroth.website/videos/watch/7cbbd47a-8084-420f-ab29-1dce03de603d",
      "to": [
        "https://www.w3.org/ns/activitystreams#Public",
        "https://peertube.azeroth.cu/accounts/peertube/followers",
        "https://peertube.azeroth.website/video-channels/mi/followers",
        "https://peertube.azeroth.website/accounts/zirox/followers"
      ],
      "cc": []
```
It calls links with domain azeroth.cu, when my current domain is azeroth.website. In the configurations there is no anda de .cu.
It gives me to think that it may be that these .cu routes are inside the postgresql DB

Any way to repair this?

**Comment by Chocobozzz** [comment]
Use https://docs.joinpeertube.org/#/maintain-tools?id=update-hostjs

**Comment by AnonymousWebHacker** [comment]
Logs From  `sudo -u peertube NODE_CONFIG_DIR=/var/www/peertube/config NODE_ENV=production npm run update-host`

```
 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'run', 'update-host' ]
2 info using npm@6.14.8
3 info using node@v10.23.0
4 verbose run-script [ 'preupdate-host', 'update-host', 'postupdate-host' ]
5 info lifecycle peertube@2.4.0~preupdate-host: peertube@2.4.0
6 info lifecycle peertube@2.4.0~update-host: peertube@2.4.0
7 verbose lifecycle peertube@2.4.0~update-host: unsafe-perm in lifecycle true
8 verbose lifecycle peertube@2.4.0~update-host: PATH: /usr/lib/node_modules/npm/node_modules/npm-li>
9 verbose lifecycle peertube@2.4.0~update-host: CWD: /var/www/peertube/config
10 silly lifecycle peertube@2.4.0~update-host: Args: [ '-c', 'node ./dist/scripts/update-host.js' ]
11 silly lifecycle peertube@2.4.0~update-host: Returned: code: 1  signal: null
12 info lifecycle peertube@2.4.0~update-host: Failed to exec update-host script
13 verbose stack Error: peertube@2.4.0 update-host: `node ./dist/scripts/update-host.js`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecy>
13 verbose stack     at EventEmitter.emit (events.js:198:13)
13 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecy>
13 verbose stack     at ChildProcess.emit (events.js:198:13)
13 verbose stack     at maybeClose (internal/child_process.js:982:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
14 verbose pkgid peertube@2.4.0
15 verbose cwd /var/www/peertube/config
16 verbose Linux 5.4.0-53-generic
17 verbose argv "/usr/bin/node" "/usr/bin/npm" "run" "update-host"
18 verbose node v10.23.0
19 verbose npm  v6.14.8
20 error code ELIFECYCLE
21 error errno 1
22 error peertube@2.4.0 update-host: `node ./dist/scripts/update-host.js`
22 error Exit status 1
23 error Failed at the peertube@2.4.0 update-host script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

```

**Comment by AnonymousWebHacker** [comment]
`sudo -u peertube NODE_CONFIG_DIR=/var/www/peertube/config NODE_ENV=production npm run update-host`
 It makes use of ~ / config / package.json.
Is there any way to rebuild it?
I made a Host change and now checking, that file does not exist.
Copy the existing package.json in /versions/package.json

Is there any way to rebuild it?
