### ISSUE TITLE
Can't start PeerTube

### ISSUE THREAD

**Issue by alxlg** [Chocobozzz/PeerTube#3426]
Hi,

I installed PeerTube on a DigitalOcean droplet. Everything seems fine until I try to run PeerTube with this command:

`sudo systemctl start peertube`

It says the error log is in this file: `/var/www/peertube/.npm/_logs/2020-12-08T10_10_26_251Z-debug.log` and here there is the content:

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'start' ]
2 info using npm@6.14.8
3 info using node@v12.20.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle peertube@2.4.0~prestart: peertube@2.4.0
6 info lifecycle peertube@2.4.0~start: peertube@2.4.0
7 verbose lifecycle peertube@2.4.0~start: unsafe-perm in lifecycle true
8 verbose lifecycle peertube@2.4.0~start: PATH: /usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/var/www/peertube/versions/peertube-v2.4.0/node_modules/.bin:/usr/>
9 verbose lifecycle peertube@2.4.0~start: CWD: /var/www/peertube/versions/peertube-v2.4.0
10 silly lifecycle peertube@2.4.0~start: Args: [ '-c', 'node dist/server' ]
11 silly lifecycle peertube@2.4.0~start: Returned: code: 255  signal: null
12 info lifecycle peertube@2.4.0~start: Failed to exec start script
13 verbose stack Error: peertube@2.4.0 start: `node dist/server`
13 verbose stack Exit status 255
13 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:314:20)
13 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:314:20)
13 verbose stack     at maybeClose (internal/child_process.js:1022:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:287:5)
14 verbose pkgid peertube@2.4.0
15 verbose cwd /var/www/peertube/versions/peertube-v2.4.0
16 verbose Linux 5.4.0-51-generic
17 verbose argv "/usr/bin/node" "/usr/bin/npm" "start"
18 verbose node v12.20.0
19 verbose npm  v6.14.8
20 error code ELIFECYCLE
21 error errno 255
22 error peertube@2.4.0 start: `node dist/server`
22 error Exit status 255
23 error Failed at the peertube@2.4.0 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 255, true ]
```

**Additional information**

* PeerTube instance:
  * version: 2.4.0
  * NodeJS version: 12.20.0
  * Ffmpeg version: 4.2.4
  * Redis version: 5.0.7
  * PostgreSQL version: 12+214ubuntu0.1

**Comment by kontrollanten** [comment]
PeerTube [requires NodeJS 10](https://docs.joinpeertube.org/#/dependencies) until #2700 is solved.

**Comment by rigelk** [comment]
@kontrollanten no: 10, 11 and 12.x are supported.

**Comment by alxlg** [comment]
Thank you very much for the quick reply, I downgraded to Node 10 but the error looks the same.

**Comment by Chocobozzz** [comment]
Hello,

Please run manually peertube to see what happens: 

```
su peertube
cd /var/www/peertube/peertube-latest && NODE_ENV=production NODE_CONFIG_DIR=/var/www/peertube/config node dist/server
```

**Comment by alxlg** [comment]
@Chocobozzz hi, here there is the error:

```
2020-12-08 10:43:20.131 error: Unable to connect to PostgreSQL database. {
  "err": {
    "stack": "SequelizeConnectionError: password authentication failed for user \"peertube\"\n    at Client.connection.connect.err [as _connectionCallback] (/var/www/peertube/versions/peertube-v2.4.0/node_modules/sequelize/lib/dialects/postgres/connection-manager.js:182:24)\n    at Client._handleErrorWhileConnecting (/var/www/peertube/versions/peertube-v2.4.0/node_modules/pg/lib/client.js:296:19)\n    at Client._handleErrorMessage (/var/www/peertube/versions/peertube-v2.4.0/node_modules/pg/lib/client.js:316:19)\n    at Connection.emit (events.js:198:13)\n    at parse (/var/www/peertube/versions/peertube-v2.4.0/node_modules/pg/lib/connection.js:109:12)\n    at Parser.parse (/var/www/peertube/versions/peertube-v2.4.0/node_modules/pg-protocol/dist/parser.js:40:17)\n    at Socket.stream.on (/var/www/peertube/versions/peertube-v2.4.0/node_modules/pg-protocol/dist/index.js:8:42)\n    at Socket.emit (events.js:198:13)\n    at addChunk (_stream_readable.js:288:12)\n    at readableAddChunk (_stream_readable.js:269:11)\n    at Socket.Readable.push (_stream_readable.js:224:10)\n    at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)",
    "message": "password authentication failed for user \"peertube\"",
    "name": "SequelizeConnectionError",
    "parent": {
      "stack": "error: password authentication failed for user \"peertube\"\n    at Parser.parseErrorMessage (/var/www/peertube/versions/peertube-v2.4.0/node_modules/pg-protocol/dist/parser.js:278:15)\n    at Parser.handlePacket (/var/www/peertube/versions/peertube-v2.4.0/node_modules/pg-protocol/dist/parser.js:126:29)\n    at Parser.parse (/var/www/peertube/versions/peertube-v2.4.0/node_modules/pg-protocol/dist/parser.js:39:38)\n    at Socket.stream.on (/var/www/peertube/versions/peertube-v2.4.0/node_modules/pg-protocol/dist/index.js:8:42)\n    at Socket.emit (events.js:198:13)\n    at addChunk (_stream_readable.js:288:12)\n    at readableAddChunk (_stream_readable.js:269:11)\n    at Socket.Readable.push (_stream_readable.js:224:10)\n    at TCP.onStreamRead (internal/stream_base_commons.js:94:17)",
      "message": "password authentication failed for user \"peertube\"",
      "length": 104,
      "name": "error",
      "severity": "FATAL",
      "code": "28P01",
      "file": "auth.c",
      "line": "330",
      "routine": "auth_failed"
    }
  }
}
```

Where can I check the password for the database is correct? I carefully edited the files during the installation as mentioned in the documentation, I don't know if I made any mistake...

**Comment by Chocobozzz** [comment]
This is a PostgreSQL credentials issue. Check your config: https://github.com/Chocobozzz/PeerTube/blob/develop/config/production.yaml.example#L41

**Comment by alxlg** [comment]
@Chocobozzz thank you, it connects to the database now. It just says `Cannot use SMTP server because of lack of configuration. PeerTube will not be able to send mails!` but visiting the website still show Nginx's homepage, am I supposed to fix SMTP before having the Web interface working?

**Comment by rigelk** [comment]
@alxlg you should have a functioning SMTP configuration, yes

**Comment by alxlg** [comment]
@rigelk maybe this is obvious, but am I supposed to setup a SMTP server on the same/another machine? Am I missing something in PeerTube's installation instructions? I checked all the documentation and I don't see a mention about the email stuff

**Comment by alxlg** [comment]
@rigelk sorry I really don't understand. I tried to edit the SMTP section in production.yaml with smtp credentials of an email account of mine like I would do with a native email app but it doesn't work. Is there any resource I can check? How do others know how to edit production.yaml in general?

**Comment by alxlg** [comment]
Now it seems it connects to SMTP:

`2020-12-08 17:46:12.084 info: Successfully connected to SMTP server.`

but just after that it gives the error:

```
2020-12-08 17:46:12.161 error: uncaughtException: listen EADDRINUSE: address already in use 127.0.0.1:9000
Error: listen EADDRINUSE: address already in use 127.0.0.1:9000
    at Server.setupListenHandle [as _listen2] (net.js:1280:14)
    at listenInCluster (net.js:1328:12)
    at GetAddrInfoReqWrap.doListen [as callback] (net.js:1461:7)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:61:10) {
  "error": {
    "stack": "Error: listen EADDRINUSE: address already in use 127.0.0.1:9000\n    at Server.setupListenHandle [as _listen2] (net.js:1280:14)\n    at listenInCluster (net.js:1328:12)\n    at GetAddrInfoReqWrap.doListen [as callback] (net.js:1461:7)\n    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:61:10)",
    "message": "listen EADDRINUSE: address already in use 127.0.0.1:9000",
    "code": "EADDRINUSE",
    "errno": "EADDRINUSE",
    "syscall": "listen",
    "address": "127.0.0.1",
    "port": 9000
  },
  "stack": "Error: listen EADDRINUSE: address already in use 127.0.0.1:9000\n    at Server.setupListenHandle [as _listen2] (net.js:1280:14)\n    at listenInCluster (net.js:1328:12)\n    at GetAddrInfoReqWrap.doListen [as callback] (net.js:1461:7)\n    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:61:10)",
  "exception": true,
  "date": "Tue Dec 08 2020 17:46:12 GMT+0000 (Coordinated Universal Time)",
  "process": {
    "pid": 176862,
    "uid": 1001,
    "gid": 1001,
    "cwd": "/var/www/peertube/versions/peertube-v2.4.0",
    "execPath": "/usr/bin/node",
    "version": "v10.23.0",
    "argv": [
      "/usr/bin/node",
      "/var/www/peertube/versions/peertube-v2.4.0/dist/server"
    ],
    "memoryUsage": {
      "rss": 163528704,
      "heapTotal": 128565248,
      "heapUsed": 97700656,
      "external": 1151835
    }
  },
  "os": {
    "loadavg": [
      0.25146484375,
      0.42578125,
      0.9306640625
    ],
    "uptime": 30691
  },
  "trace": [
    {
      "column": 14,
      "file": "net.js",
      "function": "Server.setupListenHandle [as _listen2]",
      "line": 1280,
      "method": "setupListenHandle [as _listen2]",
      "native": false
    },
    {
      "column": 12,
      "file": "net.js",
      "function": "listenInCluster",
      "line": 1328,
      "method": null,
      "native": false
    },
    {
      "column": 7,
      "file": "net.js",
      "function": "GetAddrInfoReqWrap.doListen [as callback]",
      "line": 1461,
      "method": "doListen [as callback]",
      "native": false
    },
    {
      "column": 10,
      "file": "dns.js",
      "function": "GetAddrInfoReqWrap.onlookup [as oncomplete]",
      "line": 61,
      "method": "onlookup [as oncomplete]",
      "native": false
    }
  ]
}

```

**Comment by JohnXLivingston** [comment]
> Edit: sorry I needed to stop PeerTube from systemd before starting it manually. Now it doesn't give any error but the web page still show just Nginx welcome page..

Have you other websites served by your nginx? If not, try to delete the default nginx website (sudo rm /etc/nginx/sites-enabled/default )

**Comment by alxlg** [comment]
@JohnXLivingston this did the trick thank you very much! For reference I deleted that folder and used `sudo systemctl reload nginx`

Feel free to close this if you prefer but I think the doc could be improved here and there according to this experience

**Comment by JohnXLivingston** [comment]
> @JohnXLivingston this did the trick thank you very much! For reference I deleted that folder and used `sudo systemctl reload nginx`

I have a friend that had the same issue yesterday. But I don't understand, it should have worked even with the default site enabled.
