### ISSUE TITLE
Successful PUT videos/{id} doesn't update thumbnail

### ISSUE THREAD

**Issue by sunknudsen** [Chocobozzz/PeerTube#3465]
**Describe the current behavior**

My understanding is that the following code should update the thumbnail, but somehow it doesn't although the request is successful (title is updated for example).

In the following code, `video` equals the following JSON parsed to an object and `thumbnail` is a valid path to a JPEG file.

```json
{
  "id": "uJBgb8XJoA8",
  "peerTubeUuid": "db71b05a-f648-4bdf-a037-6f91827ed0f3",
  "publishedAt": "2020-04-19T22:35:54Z",
  "title": "How to configure macOS for privacy",
  "description": "This is the first episode of the privacy guides series.\n\nIn this episode, we explore how to configure macOS for privacy.",
  "tags": ["Privacy", "Security", "macOS"],
  "categoryId": "27",
  "sections": [],
  "suggestedVideos": ["video.brGLX_92F5o"],
  "links": [],
  "credits": [],
  "affiliateLinks": [],
  "footnotes": []
}
```

```typescript
const form = new formData()
form.append("name", video.title)
form.append("description", description(config, dataset, "peertube", video))
form.append("privacy", getPrivacy(privacyStatus))
video.tags.slice(0, 5).forEach(function (tag, index) {
  form.append(`tags[${index}]`, tag)
})
form.append("thumbnailfile", await readFileAsync(thumbnail))
// See https://docs.joinpeertube.org/api-rest-reference.html#tag/Video/paths/~1videos~1{id}/put
await peertube.got.put(`videos/${video.peerTubeUuid}`, {
  headers: {
    "Content-Type": `multipart/form-data; boundary=${form.getBoundary()}`,
  },
  body: await getStream(form),
})
console.log(
  `Published video to ${config.props.peertube.channelWatchUrl}${video.peerTubeUuid}`
)
```

I am likely missing some part of the puzzle. Thanks for your help!

**Describe the expected behavior**

The thumbnail should be updated.

**Additional information**

* PeerTube instance:
  * URL: https://peertube.sunknudsen.com/
  * version: `2.4.0`

**Comment by sunknudsen** [comment]
When using `createReadStream(thumbnail)` (as suggested [here](https://www.npmjs.com/package/form-data#usage)) vs `await readFileAsync(thumbnail)`, the API returns status code `500`.

**Comment by Chocobozzz** [comment]
Hello,

I don't know your script does not work. But you can use our script: https://docs.joinpeertube.org/#/maintain-tools?id=peertube-uploadjs

We don't use `from-data` module but `supertest`: https://github.com/Chocobozzz/PeerTube/blob/develop/shared/extra-utils/videos/videos.ts#L405

**Comment by sunknudsen** [comment]
Thanks for the follow-up @Chocobozzz.

What is the best approach to troubleshooting why I am betting a 500 error?

Response body is empty.

**Comment by Chocobozzz** [comment]
> What is the best approach to troubleshooting why I am betting a 500 error?

Check the server logs :)

**Comment by sunknudsen** [comment]
Thanks @Chocobozzz. I didn't know about `journalctl -fu peertube`. Looks like `ffmpeg` is not able to read the image. Investigating...

```shell
Dec 14 09:59:45 sunknudsen-peertube peertube[506]:   "err": "Error: ffmpeg exited with code 1: Error while decoding stream #0:0: Invalid data found when processing input\nCannot determine format of input stream 0:0 after EOF\nError marking filters as finished\nConversion failed!\n\n    at ChildProcess.<anonymous> (/var/www/peertube/versions/peertube-v2.4.0/node_modules/fluent-ffmpeg/lib/processor.js:182:22)\n    at ChildProcess.emit (events.js:315:20)\n    at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)"
Dec 14 09:59:45 sunknudsen-peertube peertube[506]: }
Dec 14 09:59:45 sunknudsen-peertube peertube[506]: [peertube.sunknudsen.com:443] 2020-12-14 09:59:45.517 info: 185.112.144.208 - - [14/Dec/2020:14:59:45 +0000] "PUT /api/v1/videos/db71b05a-f648-4bdf-a037-6f91827ed0f3 HTTP/1.0" 500 - "-" "got (https://github.com/sindresorhus/got)"
```

**Comment by sunknudsen** [comment]
Thanks @Chocobozzz. I didn't know about `journalctl -fu peertube`. Looks like `ffmpeg` is not able to read the image. Investigating...

```shell
$ journalctl -fu peertube
Dec 14 10:02:27 sunknudsen-peertube peertube[506]: [peertube.sunknudsen.com:443] 2020-12-14 10:02:27.991 error: Error in ffmpeg webp convert process. {
Dec 14 10:02:27 sunknudsen-peertube peertube[506]:   "stdout": "",
Dec 14 10:02:27 sunknudsen-peertube peertube[506]:   "stderr": "ffmpeg version 4.1.4-1~deb10u1 Copyright (c) 2000-2019 the FFmpeg developers\n  built with gcc 8 (Debian 8.3.0-6)\n  configuration: --prefix=/usr --extra-version='1~deb10u1' --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-avresample --disable-filter=resample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librsvg --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opengl --enable-sdl2 --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared\n  libavutil      56. 22.100 / 56. 22.100\n  libavcodec     58. 35.100 / 58. 35.100\n  libavformat    58. 20.100 / 58. 20.100\n  libavdevice    58.  5.100 / 58.  5.100\n  libavfilter     7. 40.101 /  7. 40.101\n  libavresample   4.  0.  0 /  4.  0.  0\n  libswscale      5.  3.100 /  5.  3.100\n  libswresample   3.  3.100 /  3.  3.100\n  libpostproc    55.  3.100 / 55.  3.100\n[mjpeg @ 0x55e5ea4d6740] No JPEG data found in image\n[image2 @ 0x55e5ea4d4800] decoding for stream 0 failed\n[image2 @ 0x55e5ea4d4800] Could not find codec parameters for stream 0 (Video: mjpeg, none(bt470bg/unknown/unknown)): unspecified size\nConsider increasing the value for the 'analyzeduration' and 'probesize' options\nInput #0, image2, from '/var/www/peertube/storage/tmp/c550c9721699965beee6ee10c8315cae.jpg':\n  Duration: 00:00:00.04, start: 0.000000, bitrate: 140028 kb/s\n    Stream #0:0: Video: mjpeg, none(bt470bg/unknown/unknown), 25 tbr, 25 tbn, 25 tbc\nStream mapping:\n  Stream #0:0 -> #0:0 (mjpeg (native) -> mjpeg (native))\nPress [q] to stop, [?] for help\n[mjpeg @ 0x55e5ea4d7e00] No JPEG data found in image\nError while decoding stream #0:0: Invalid data found when processing input\nCannot determine format of input stream 0:0 after EOF\nError marking filters as finished\nConversion failed!\n"
Dec 14 10:02:27 sunknudsen-peertube peertube[506]: }
```

**Comment by sunknudsen** [comment]
Hey @Chocobozzz, I've been at this bug for over 3 hours... the request goes trough and `thumbnailfile` is set... but the thumbnail isn't updated on the server (which returns `204`).

Do you have any ideas to share about how I could troubleshoot this edge case? Nothing in the logs... the thumbnails is silently not updated.

**Comment by sunknudsen** [comment]
The following form data (`thumbnailfile` has been truncated) looks fine to me.

```shell
----------------------------976496071404206312962220
Content-Disposition: form-data; name="name"

How to configure macOS for privacy
----------------------------976496071404206312962220
Content-Disposition: form-data; name="description"

This is the first episode of the privacy guides series.

In this episode, we explore how to configure macOS for privacy.

==============================
SUGGESTED
==============================
Why Macs equipped with the new T2 chip are shitty for hackers 👉 https://www.youtube.com/watch?v=brGLX_92F5o
----------------------------976496071404206312962220
Content-Disposition: form-data; name="privacy"

1
----------------------------976496071404206312962220
Content-Disposition: form-data; name="tags[0]"

Privacy
----------------------------976496071404206312962220
Content-Disposition: form-data; name="tags[1]"

Security
----------------------------976496071404206312962220
Content-Disposition: form-data; name="tags[2]"

macOS
----------------------------976496071404206312962220
Content-Disposition: form-data; name="thumbnailfile"
Content-Type: image/jpeg

ÿØÿàJFIFddÿìDuckyPÿîAdobedÀÿÛ

























































ÿ8ÿÄÞ

!1AQa"qð¡±Á2ÑáñR#b	r3Ó$%ÒCU¢²ÂS³4´Ô5u&6'7csTe¥ÅVvGW(£Dt¤Äµ¶âdEFfÕ¦8!1AQa"2qÁBR±Ñá¡#ð¢3$ÿÚ
                          ?þ*LÀ@#é+\
é'æ0'Õ©ÃQkÚtºD
=XplVmÝl~¥kÒàíUJ¯«gfk¶Vxwn( ÍÆc B?TÔ:_(Eªcz÷´ I@¯
jÄ{'åk­¿3¡Àà¥³Að¤fÚU!´Wö}ëe^ZL¢z$
                                        *LIªÄÐ ÊBBJÉ'(Ië.ÖÔp ËDË×s­D3iM-ùUpWI`;âÏ*Â($40¶U~ÁIpüEÄÕv�àæá8[Ö Ï?Æ'
À
----------------------------976496071404206312962220--
```

**Comment by sunknudsen** [comment]
Not sure if this can help, but looks like an encoding issue.

`uJBgb8XJoA8.jpg` is the original and `661b5fc693dcda3060b14ffed648262a.jpg` is what's on the server.

```console
$ head /Users/sunknudsen/Desktop/uJBgb8XJoA8.jpg
����JFIFdd��DuckyP��Adobed����

$ head -n 10 /Users/sunknudsen/Desktop/661b5fc693dcda3060b14ffed648262a.jpg
ÿØÿàJFIFddÿìDuckyPÿîAdobedÀÿÛ
```

**Comment by sunknudsen** [comment]
I believe the issue was caused by [get-stream](https://www.npmjs.com/package/get-stream) which was likely converting the `binary` encoding of `thumbnailfile` to `utf8`.

I ended up using the following [approach](https://github.com/sindresorhus/got/discussions/1513#discussioncomment-187413).

**Comment by sunknudsen** [comment]
Actually... I just wasted so much time... PeerTube works differently than YouTube... we can upload both a `previewfile` and a `thumbnailfile` which is not the same asset. This explains why this felt like an edge case... I was updating `thumbnailfile` while looking at `previewfile`.
