### ISSUE TITLE
create-transcoding-job replaces HLS files even after failure

### ISSUE THREAD

**Issue by kontrollanten** [Chocobozzz/PeerTube#3471]
**Describe the current behavior**
When running `create-transcoding-job` and the job fails, the streaming playlists are replaced anyway which causes the video to stop working. 

**Steps to reproduce:**

1. `npm run create-import-video-file-job -- -v 3bd44582-3f08-4d27-98eb-c65f000b79b6 -i /home/ubuntu/video.mkv`
1. `npm run create-transcoding-job -- --generate-hls -v 3bd44582-3f08-4d27-98eb-c65f000b79b6`

**Describe the expected behavior**
No files should be replaced upon transcoding failure.

**Additional information**
This is how the `streaming-playlists/hls/3bd44582-3f08-4d27-98eb-c65f000b79b6` folder look like after the transcoding jobs has failed. The original files was uploaded December 11 and the failing jobs where running December 16.

Name | Type | Last modified | Size
---------|--------|-------------------|--------
segments-sha256.json | json | December 11, 2020, 12:05 (UTC+01:00) | 393.0 KB
master.m3u8 | m3u8 | December 11, 2020, 12:05 (UTC+01:00) | 535.0 B
720.m3u8 | m3u8 | December 16, 2020, 08:06 (UTC+01:00) | 97.6 KB
480.m3u8 | m3u8 | December 16, 2020, 07:42 (UTC+01:00) | 97.4 KB
3bd44582-3f08-4d27-98eb-c65f000b79b6-720-fragmented.mp4 | mp4 | December 16, 2020, 08:06 (UTC+01:00) | 385.9 MB
3bd44582-3f08-4d27-98eb-c65f000b79b6-480-fragmented.mp4 | mp4 | December 16, 2020, 07:42 (UTC+01:00) | 229.6 MB
3bd44582-3f08-4d27-98eb-c65f000b79b6-360-fragmented.mp4 | mp4 | December 16, 2020, 07:48 (UTC+01:00) | 167.8 MB
3bd44582-3f08-4d27-98eb-c65f000b79b6-240-fragmented.mp4 | mp4 | December 16, 2020, 07:52 (UTC+01:00) | 114.5 MB
3bd44582-3f08-4d27-98eb-c65f000b79b6-0-fragmented.mp4 | mp4 | December 16, 2020, 07:33 (UTC+01:00) | 0 B
360.m3u8 | m3u8 | December 16, 2020, 07:48 (UTC+01:00) | 97.3 KB
240.m3u8 | m3u8 | December 16, 2020, 07:52 (UTC+01:00) | 97.0 KB
0.m3u8 | m3u8 | December 11, 2020, 11:40 (UTC+01:00) | 94.1 KB

* PeerTube instance:
  * version: 2.4.0
  * NodeJS version: 12.20.0
  * Ffmpeg version: 4.2.4

* Link to browser console log if relevant:
The browser (Brave) crashes due to a loop of the following message. I saw that the segment validation has changed since 2.4.0 so I won't fill an issue for that.
```
Uncaught (in promise) Error: Unknown segment name 3bd44582-3f08-4d27-98eb-c65f000b79b6-480-fragmented.mp4/1331-424900 in segment validator
```

* Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`):
```
Job: 28
Type: video-transcoding
Processed on Dec 16, 2020, 7:52:46 AM
Finished on Dec 16, 2020, 8:07:35 AM
{
  "type": "hls",
  "videoUUID": "3bd44582-3f08-4d27-98eb-c65f000b79b6",
  "resolution": 720,
  "isPortraitMode": false,
  "copyCodecs": false
}
Error: ffprobe exited with code 1
ffprobe version 4.2.4-1ubuntu0.1 Copyright (c) 2007-2020 the FFmpeg developers
  built with gcc 9 (Ubuntu 9.3.0-10ubuntu2)
  configuration: --prefix=/usr --extra-version=1ubuntu0.1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-avresample --disable-filter=resample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librsvg --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-nvenc --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared
  libavutil      56. 31.100 / 56. 31.100
  libavcodec     58. 54.100 / 58. 54.100
  libavformat    58. 29.100 / 58. 29.100
  libavdevice    58.  8.100 / 58.  8.100
  libavfilter     7. 57.100 /  7. 57.100
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  5.100 /  5.  5.100
  libswresample   3.  5.100 /  3.  5.100
  libpostproc    55.  5.100 / 55.  5.100
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x55cfd96fff00] Format mov,mp4,m4a,3gp,3g2,mj2 detected only with low score of 1, misdetection possible!
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x55cfd96fff00] moov atom not found
/var/www/peertube/storage/streaming-playlists/hls/3bd44582-3f08-4d27-98eb-c65f000b79b6/3bd44582-3f08-4d27-98eb-c65f000b79b6-0-fragmented.mp4: Invalid data found when processing input

    at ChildProcess.<anonymous> (/var/www/peertube/versions/peertube-v2.4.0/node_modules/fluent-ffmpeg/lib/ffprobe.js:233:22)
    at ChildProcess.emit (events.js:314:20)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:276:12)




Job: 27
Type: video-transcoding
Processed on Dec 16, 2020, 7:48:26 AM
Finished on Dec 16, 2020, 7:52:46 AM
{
  "type": "hls",
  "videoUUID": "3bd44582-3f08-4d27-98eb-c65f000b79b6",
  "resolution": 240,
  "isPortraitMode": false,
  "copyCodecs": false
}
Error: ffprobe exited with code 1
ffprobe version 4.2.4-1ubuntu0.1 Copyright (c) 2007-2020 the FFmpeg developers
  built with gcc 9 (Ubuntu 9.3.0-10ubuntu2)
  configuration: --prefix=/usr --extra-version=1ubuntu0.1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-avresample --disable-filter=resample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librsvg --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-nvenc --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared
  libavutil      56. 31.100 / 56. 31.100
  libavcodec     58. 54.100 / 58. 54.100
  libavformat    58. 29.100 / 58. 29.100
  libavdevice    58.  8.100 / 58.  8.100
  libavfilter     7. 57.100 /  7. 57.100
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  5.100 /  5.  5.100
  libswresample   3.  5.100 /  3.  5.100
  libpostproc    55.  5.100 / 55.  5.100
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x5641f8b93f00] Format mov,mp4,m4a,3gp,3g2,mj2 detected only with low score of 1, misdetection possible!
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x5641f8b93f00] moov atom not found
/var/www/peertube/storage/streaming-playlists/hls/3bd44582-3f08-4d27-98eb-c65f000b79b6/3bd44582-3f08-4d27-98eb-c65f000b79b6-0-fragmented.mp4: Invalid data found when processing input

    at ChildProcess.<anonymous> (/var/www/peertube/versions/peertube-v2.4.0/node_modules/fluent-ffmpeg/lib/ffprobe.js:233:22)
    at ChildProcess.emit (events.js:314:20)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:276:12)





Job: 26
Type: video-transcoding
Processed on Dec 16, 2020, 7:42:23 AM
Finished on Dec 16, 2020, 7:48:26 AM
{
  "type": "hls",
  "videoUUID": "3bd44582-3f08-4d27-98eb-c65f000b79b6",
  "resolution": 360,
  "isPortraitMode": false,
  "copyCodecs": false
}
Error: ffprobe exited with code 1
ffprobe version 4.2.4-1ubuntu0.1 Copyright (c) 2007-2020 the FFmpeg developers
  built with gcc 9 (Ubuntu 9.3.0-10ubuntu2)
  configuration: --prefix=/usr --extra-version=1ubuntu0.1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-avresample --disable-filter=resample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librsvg --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-nvenc --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared
  libavutil      56. 31.100 / 56. 31.100
  libavcodec     58. 54.100 / 58. 54.100
  libavformat    58. 29.100 / 58. 29.100
  libavdevice    58.  8.100 / 58.  8.100
  libavfilter     7. 57.100 /  7. 57.100
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  5.100 /  5.  5.100
  libswresample   3.  5.100 /  3.  5.100
  libpostproc    55.  5.100 / 55.  5.100
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x560c377caf00] Format mov,mp4,m4a,3gp,3g2,mj2 detected only with low score of 1, misdetection possible!
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x560c377caf00] moov atom not found
/var/www/peertube/storage/streaming-playlists/hls/3bd44582-3f08-4d27-98eb-c65f000b79b6/3bd44582-3f08-4d27-98eb-c65f000b79b6-0-fragmented.mp4: Invalid data found when processing input

    at ChildProcess.<anonymous> (/var/www/peertube/versions/peertube-v2.4.0/node_modules/fluent-ffmpeg/lib/ffprobe.js:233:22)
    at ChildProcess.emit (events.js:314:20)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:276:12)



Job: 25
Type: video-transcoding
Processed on Dec 16, 2020, 7:33:39 AM
Finished on Dec 16, 2020, 7:42:23 AM
{
  "type": "hls",
  "videoUUID": "3bd44582-3f08-4d27-98eb-c65f000b79b6",
  "resolution": 480,
  "isPortraitMode": false,
  "copyCodecs": false
}
Error: ffprobe exited with code 1
ffprobe version 4.2.4-1ubuntu0.1 Copyright (c) 2007-2020 the FFmpeg developers
  built with gcc 9 (Ubuntu 9.3.0-10ubuntu2)
  configuration: --prefix=/usr --extra-version=1ubuntu0.1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-avresample --disable-filter=resample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librsvg --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-nvenc --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared
  libavutil      56. 31.100 / 56. 31.100
  libavcodec     58. 54.100 / 58. 54.100
  libavformat    58. 29.100 / 58. 29.100
  libavdevice    58.  8.100 / 58.  8.100
  libavfilter     7. 57.100 /  7. 57.100
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  5.100 /  5.  5.100
  libswresample   3.  5.100 /  3.  5.100
  libpostproc    55.  5.100 / 55.  5.100
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x55d226ae2f00] Format mov,mp4,m4a,3gp,3g2,mj2 detected only with low score of 1, misdetection possible!
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x55d226ae2f00] moov atom not found
/var/www/peertube/storage/streaming-playlists/hls/3bd44582-3f08-4d27-98eb-c65f000b79b6/3bd44582-3f08-4d27-98eb-c65f000b79b6-0-fragmented.mp4: Invalid data found when processing input

    at ChildProcess.<anonymous> (/var/www/peertube/versions/peertube-v2.4.0/node_modules/fluent-ffmpeg/lib/ffprobe.js:233:22)
    at ChildProcess.emit (events.js:314:20)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:276:12)
    
    

Job: 24
Type: video-transcoding
Processed on Dec 16, 2020, 7:33:35 AM
Finished on Dec 16, 2020, 7:33:39 AM
{
  "type": "hls",
  "videoUUID": "3bd44582-3f08-4d27-98eb-c65f000b79b6",
  "resolution": 0,
  "isPortraitMode": false,
  "copyCodecs": false
}
Error: ffmpeg exited with code 1: 
    at ChildProcess.<anonymous> (/var/www/peertube/versions/peertube-v2.4.0/node_modules/fluent-ffmpeg/lib/processor.js:182:22)
    at ChildProcess.emit (events.js:314:20)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:276:12)
```

**Comment by Chocobozzz** [comment]
Merging this issue in https://github.com/Chocobozzz/PeerTube/issues/3596
