### ISSUE TITLE
【solved】There are errors when run command "npm install"

### ISSUE THREAD

**Issue by myveb** [Chocobozzz/PeerTube#35]
Hello,
I run `npm install` under /home/peertube/PeerTube directory as user peertube, there are some warns:
```
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules/webpack/node_modules/watchpack/node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.0.17: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN bootstrap-loader@2.0.0-beta.18 requires a peer of webpack@^2.1.0-beta but none was installed.
npm WARN extract-text-webpack-plugin@2.0.0-rc.3 requires a peer of webpack@^2.2.0 but none was installed.
npm WARN ng2-smart-table@0.5.2-1 requires a peer of @angular/common@2.4.4 but none was installed.
npm WARN ng2-smart-table@0.5.2-1 requires a peer of @angular/compiler@2.4.4 but none was installed.
npm WARN ng2-smart-table@0.5.2-1 requires a peer of @angular/core@2.4.4 but none was installed.
npm WARN ng2-smart-table@0.5.2-1 requires a peer of @angular/forms@2.4.4 but none was installed.
npm WARN script-ext-html-webpack-plugin@1.6.2 requires a peer of webpack@1 || ^2.2.0 but none was installed.
npm WARN string-replace-loader@1.0.5 requires a peer of webpack@1 || 2 || ^2.0.0-beta || ^2.1.0-beta but none was installed.

```

Then when I run `npm run build` under the same directory, it shows more errors, the errors are from `Starting compilation using the angular compiler.`
:
```
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls peertube-client
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/peertube/PeerTube/client/npm-debug.log
/home/peertube/PeerTube/node_modules/scripty/cli.js:38
    if (er) { throw er }
              ^

Error: Error: scripty - script "fail" failed by exiting with a non-zero code (1).
    at ChildProcess.<anonymous> (/home/peertube/PeerTube/node_modules/scripty/lib/run/spawn-script.js:11:10)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at maybeClose (internal/child_process.js:854:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:222:5)

npm ERR! Linux 3.16.0-4-amd64
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "build:client:prod"
npm ERR! node v4.7.3
npm ERR! npm  v4.1.2
npm ERR! code ELIFECYCLE
npm ERR! peertube@0.0.1 build:client:prod: `scripty`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the peertube@0.0.1 build:client:prod script 'scripty'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the peertube package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     scripty
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs peertube
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls peertube
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/peertube/PeerTube/npm-debug.log

npm ERR! Linux 3.16.0-4-amd64
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "build"
npm ERR! node v4.7.3
npm ERR! npm  v4.1.2
npm ERR! code ELIFECYCLE
npm ERR! peertube@0.0.1 build: `npm run build:client:prod`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the peertube@0.0.1 build script 'npm run build:client:prod'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the peertube package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run build:client:prod
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs peertube
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls peertube
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/peertube/PeerTube/npm-debug.log
```

This is the content of the file npm-debug.log
```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/nodejs', '/usr/bin/npm', 'run', 'build' ]
2 info using npm@3.10.10
3 info using node@v4.7.3
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle peertube@0.0.1~prebuild: peertube@0.0.1
6 silly lifecycle peertube@0.0.1~prebuild: no script for prebuild, continuing
7 info lifecycle peertube@0.0.1~build: peertube@0.0.1
8 verbose lifecycle peertube@0.0.1~build: unsafe-perm in lifecycle true
9 verbose lifecycle peertube@0.0.1~build: PATH: /usr/lib/node_modules/npm/bin/node-gyp-bin:/home/peertube/PeerTube/node_modules/.bin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games
10 verbose lifecycle peertube@0.0.1~build: CWD: /home/peertube/PeerTube
11 silly lifecycle peertube@0.0.1~build: Args: [ '-c', 'npm run build:client:prod' ]
12 silly lifecycle peertube@0.0.1~build: Returned: code: 1  signal: null
13 info lifecycle peertube@0.0.1~build: Failed to exec build script
14 verbose stack Error: peertube@0.0.1 build: `npm run build:client:prod`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/lib/utils/lifecycle.js:255:16)
14 verbose stack     at emitTwo (events.js:87:13)
14 verbose stack     at EventEmitter.emit (events.js:172:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/lib/utils/spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:87:13)
14 verbose stack     at ChildProcess.emit (events.js:172:7)
14 verbose stack     at maybeClose (internal/child_process.js:854:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:222:5)
15 verbose pkgid peertube@0.0.1
16 verbose cwd /home/peertube/PeerTube
17 error Linux 3.16.0-4-amd64
18 error argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "build"
19 error node v4.7.3
20 error npm  v3.10.10
21 error code ELIFECYCLE
22 error peertube@0.0.1 build: `npm run build:client:prod`
22 error Exit status 1
23 error Failed at the peertube@0.0.1 build script 'npm run build:client:prod'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the peertube package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     npm run build:client:prod
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs peertube
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls peertube
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by myveb** [comment]
@Chocobozzz I have reinstalled the server and reinstalled peertube, when I run `npm install`,they show some errors:
```
node-pre-gyp ERR! Tried to download(404): https://github.com/kelektiv/node.bcrypt.js/releases/download/v1.0.2/bcrypt_lib-v1.0.2-node-v46-linux-x64.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for bcrypt@1.0.2 and node@4.7.3 (node-v46 ABI) (falling back to source compile with node-gyp)
```

**Comment by myveb** [comment]
It has been solved, I don't know why, there are so many errors above, but I can run it now successfully anyway. there is still another error, I will open another issue to talk about it.
