### ISSUE TITLE
Node error when trying to sync videos from yt to peertube

### ISSUE THREAD

**Issue by moeC137** [Chocobozzz/PeerTube#3530]
**Describe the current behavior**

node:1730480) UnhandledPromiseRejectionWarning: Error: expected "Content-Type" matching /json/, got "text/html; charset=utf-8"
    at Test._assertHeader (/home/moe/PeerTube/node_modules/supertest/lib/test.js:247:14)
    at Test._assertFunction (/home/moe/PeerTube/node_modules/supertest/lib/test.js:285:11)
    at Test.assert (/home/moe/PeerTube/node_modules/supertest/lib/test.js:175:21)
    at localAssert (/home/moe/PeerTube/node_modules/supertest/lib/test.js:133:12)
    at /home/moe/PeerTube/node_modules/supertest/lib/test.js:130:5
    at Test.Request.callback (/home/moe/PeerTube/node_modules/superagent/lib/node/index.js:894:12)
    at IncomingMessage.<anonymous> (/home/moe/PeerTube/node_modules/superagent/lib/node/index.js:1127:20)
    at Stream.emit (events.js:314:20)
    at Unzip.<anonymous> (/home/moe/PeerTube/node_modules/superagent/lib/node/unzip.js:53:12)
    at Unzip.emit (events.js:326:22)
    at endReadableNT (_stream_readable.js:1223:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
(node:1730480) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:1730480) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Steps to reproduce:**

1.
2.
3.

**Describe the expected behavior**

**Additional information**

* PeerTube instance: diode.zone
  * URL: https://diode.zone/
  * version:
  * NodeJS version:
  * Ffmpeg version:

* Browser name, version and platforms on which you could reproduce the bug:
* Link to browser console log if relevant:
* Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`):

**Comment by moeC137** [comment]
fixed. it way my fault.
i put the wrong url. righ url is: https://diode.zone/
