### ISSUE TITLE
ffmpeg getting killed on transcoding

### ISSUE THREAD

**Issue by nliechti** [Chocobozzz/PeerTube#3539]
I installed peertube for testing on an digitalocean droplet, according to this https://docs.joinpeertube.org/install-docker?id=production installtion manual.

Everything works perfect except when the video needs transcoding. I did not find anyone having the same problem.

**Steps to reproduce:**

1. Upload any (not limited to) mkv video.
2. The transcoder is getting started and crashes immediatelly.

**Describe the expected behavior**

**Additional information**

***Peertube log***
```
error[04/01/2021, 11:49:48] Error in transcoding job.
{
  "stdout": "",
  "stderr": "ffmpeg version 4.1.6-1~deb10u1 Copyright (c) 2000-2020 the FFmpeg developers\n  built with gcc 8 (Debian 8.3.0-6)\n  configuration: --prefix=/usr --extra-version='1~deb10u1' --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-avresample --disable-filter=resample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librsvg --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opengl --enable-sdl2 --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared\n  libavutil      56. 22.100 / 56. 22.100\n  libavcodec     58. 35.100 / 58. 35.100\n  libavformat    58. 20.100 / 58. 20.100\n  libavdevice    58.  5.100 / 58.  5.100\n  libavfilter     7. 40.101 /  7. 40.101\n  libavresample   4.  0.  0 /  4.  0.  0\n  libswscale      5.  3.100 /  5.  3.100\n  libswresample   3.  3.100 /  3.  3.100\n  libpostproc    55.  3.100 / 55.  3.100\nInput #0, mov,mp4,m4a,3gp,3g2,mj2, from '/data/videos/ad84a740-b8e8-4443-8e33-ef4068aa1f76-2160.mov':\n  Metadata:\n    major_brand     : qt  \n    minor_version   : 0\n    compatible_brands: qt  \n    creation_time   : 2017-07-16T15:15:43.000000Z\n  Duration: 00:05:22.76, start: 0.000000, bitrate: 8318 kb/s\n    Stream #0:0(und): Video: hevc (Main 10) (hvc1 / 0x31637668), yuv420p10le(tv, bt709), 3840x2160 [SAR 1:1 DAR 16:9], 8315 kb/s, 29.97 fps, 29.97 tbr, 30k tbn, 30k tbc (default)\n    Metadata:\n      creation_time   : 2017-07-16T21:28:04.000000Z\n      handler_name    : Core Media Video\n      encoder         : H.265\nStream mapping:\n  Stream #0:0 -> #0:0 (hevc (native) -> h264 (libx264))\nPress [q] to stop, [?] for help\n[libx264 @ 0x557fc7a61580] using SAR=1/1\n[libx264 @ 0x557fc7a61580] frame MB size (240x135) > level limit (3600)\n[libx264 @ 0x557fc7a61580] DPB size (4 frames, 129600 mbs) > level limit (0 frames, 18000 mbs)\n[libx264 @ 0x557fc7a61580] VBV bitrate (22000) > level limit (17500)\n[libx264 @ 0x557fc7a61580] VBV buffer (44000) > level limit (17500)\n[libx264 @ 0x557fc7a61580] MB rate (972000) > level limit (108000)\n[libx264 @ 0x557fc7a61580] using cpu capabilities: MMX2 SSE2Fast SSSE3 SSE4.2 AVX FMA3 BMI2 AVX2\n[libx264 @ 0x557fc7a61580] profile High, level 3.1\n[libx264 @ 0x557fc7a61580] 264 - core 155 r2917 0a84d98 - H.264/MPEG-4 AVC codec - Copyleft 2003-2018 - http://www.videolan.org/x264.html - options: cabac=1 ref=1 deblock=1:0:0 analyse=0x3:0x113 me=hex subme=7 psy=1 psy_rd=1.00:0.00 mixed_ref=0 me_range=16 chroma_me=1 trellis=1 8x8dct=1 cqm=0 deadzone=21,11 fast_pskip=1 chroma_qp_offset=-2 threads=3 lookahead_threads=1 sliced_threads=0 nr=0 decimate=1 interlaced=0 bluray_compat=0 constrained_intra=0 bframes=16 b_pyramid=2 b_adapt=1 b_bias=0 direct=1 weightb=1 open_gop=0 weightp=2 keyint=60 keyint_min=6 scenecut=40 intra_refresh=0 rc_lookahead=40 rc=crf mbtree=1 crf=23.0 qcomp=0.60 qpmin=0 qpmax=69 qpstep=4 vbv_maxrate=22000 vbv_bufsize=44000 crf_max=0.0 nal_hrd=none filler=0 ip_ratio=1.40 aq=1:1.00\nOutput #0, mp4, to '/data/tmp/8-transcoded.mp4':\n  Metadata:\n    encoder         : Lavf58.20.100\n    Stream #0:0: Video: h264 (libx264) (avc1 / 0x31637661), yuv420p, 3840x2160 [SAR 1:1 DAR 16:9], q=-1--1, 30 fps, 15360 tbn, 30 tbc (default)\n    Metadata:\n      encoder         : Lavc58.35.100 libx264\n    Side data:\n      cpb: bitrate max/min/avg: 22000000/0/0 buffer size: 44000000 vbv_delay: -1\nframe=    2 fps=0.0 q=0.0 size=       0kB time=00:00:00.00 bitrate=N/A speed=   0x    \nframe=   14 fps= 14 q=0.0 size=       0kB time=00:00:00.00 bitrate=N/A speed=   0x    \nframe=   23 fps= 15 q=0.0 size=       0kB time=00:00:00.00 bitrate=N/A speed=   0x    \nframe=   31 fps= 15 q=0.0 size=       0kB time=00:00:00.00 bitrate=N/A speed=   0x    \n"
}
error[04/01/2021, 11:49:48] Cannot execute job 8 in queue video-transcoding.
{
  "payload": {
    "type": "optimize",
    "videoUUID": "ad84a740-b8e8-4443-8e33-ef4068aa1f76",
    "isNewVideo": true
  },
  "err": {
    "stack": "Error: ffmpeg was killed with signal SIGKILL\n    at ChildProcess.<anonymous> (/app/node_modules/fluent-ffmpeg/lib/processor.js:180:22)\n    at ChildProcess.emit (events.js:198:13)\n    at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)",
    "message": "ffmpeg was killed with signal SIGKILL"
  }
}
```

* PeerTube instance:
  * version: 2.4.0
  * NodeJS version: v10.22.0
  * Ffmpeg version: 4.1.6-1~deb10u1

**Comment by nliechti** [comment]
Got presumably fixed with v 3.0.0

**Comment by nliechti** [comment]
Strange, it worked once. After that, the same error occurred again.

```
error[07/01/2021, 16:21:28] Error in transcoding job.
{
  "stdout": "",
  "stderr": "ffmpeg version 4.1.6-1~deb10u1 Copyright (c) 2000-2020 the FFmpeg developers\n  built with gcc 8 (Debian 8.3.0-6)\n  configuration: --prefix=/usr --extra-version='1~deb10u1' --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-avresample --disable-filter=resample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librsvg --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opengl --enable-sdl2 --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared\n  libavutil      56. 22.100 / 56. 22.100\n  libavcodec     58. 35.100 / 58. 35.100\n  libavformat    58. 20.100 / 58. 20.100\n  libavdevice    58.  5.100 / 58.  5.100\n  libavfilter     7. 40.101 /  7. 40.101\n  libavresample   4.  0.  0 /  4.  0.  0\n  libswscale      5.  3.100 /  5.  3.100\n  libswresample   3.  3.100 /  3.  3.100\n  libpostproc    55.  3.100 / 55.  3.100\nInput #0, mov,mp4,m4a,3gp,3g2,mj2, from '/data/videos/9bafd150-17de-40ed-8a3d-c8affe909650-2160.mov':\n  Metadata:\n    major_brand     : qt  \n    minor_version   : 0\n    compatible_brands: qt  \n    creation_time   : 2017-07-16T15:15:43.000000Z\n  Duration: 00:05:22.76, start: 0.000000, bitrate: 8318 kb/s\n    Stream #0:0(und): Video: hevc (Main 10) (hvc1 / 0x31637668), yuv420p10le(tv, bt709), 3840x2160 [SAR 1:1 DAR 16:9], 8315 kb/s, 29.97 fps, 29.97 tbr, 30k tbn, 30k tbc (default)\n    Metadata:\n      creation_time   : 2017-07-16T21:28:04.000000Z\n      handler_name    : Core Media Video\n      encoder         : H.265\nStream mapping:\n  Stream #0:0 -> #0:0 (hevc (native) -> h264 (libx264))\nPress [q] to stop, [?] for help\n[libx264 @ 0x557028af40c0] using SAR=1/1\n[libx264 @ 0x557028af40c0] frame MB size (240x135) > level limit (3600)\n[libx264 @ 0x557028af40c0] DPB size (4 frames, 129600 mbs) > level limit (0 frames, 18000 mbs)\n[libx264 @ 0x557028af40c0] MB rate (972000) > level limit (108000)\n[libx264 @ 0x557028af40c0] using cpu capabilities: MMX2 SSE2Fast SSSE3 SSE4.2 AVX FMA3 BMI2 AVX2\n[libx264 @ 0x557028af40c0] profile High, level 3.1\n[libx264 @ 0x557028af40c0] 264 - core 155 r2917 0a84d98 - H.264/MPEG-4 AVC codec - Copyleft 2003-2018 - http://www.videolan.org/x264.html - options: cabac=1 ref=1 deblock=1:0:0 analyse=0x3:0x113 me=hex subme=7 psy=1 psy_rd=1.00:0.00 mixed_ref=0 me_range=16 chroma_me=1 trellis=1 8x8dct=1 cqm=0 deadzone=21,11 fast_pskip=1 chroma_qp_offset=-2 threads=3 lookahead_threads=1 sliced_threads=0 nr=0 decimate=1 interlaced=0 bluray_compat=0 constrained_intra=0 bframes=16 b_pyramid=2 b_adapt=1 b_bias=0 direct=1 weightb=1 open_gop=0 weightp=2 keyint=60 keyint_min=6 scenecut=40 intra_refresh=0 rc_lookahead=40 rc=crf mbtree=1 crf=23.0 qcomp=0.60 qpmin=0 qpmax=69 qpstep=4 vbv_maxrate=8318 vbv_bufsize=16637 crf_max=0.0 nal_hrd=none filler=0 ip_ratio=1.40 aq=1:1.00\nOutput #0, mp4, to '/data/tmp/9-transcoded.mp4':\n  Metadata:\n    encoder         : Lavf58.20.100\n    Stream #0:0: Video: h264 (libx264) (avc1 / 0x31637661), yuv420p, 3840x2160 [SAR 1:1 DAR 16:9], q=-1--1, 30 fps, 15360 tbn, 30 tbc (default)\n    Metadata:\n      encoder         : Lavc58.35.100 libx264\n    Side data:\n      cpb: bitrate max/min/avg: 8318000/0/0 buffer size: 16637000 vbv_delay: -1\nframe=    2 fps=0.0 q=0.0 size=       0kB time=00:00:00.00 bitrate=N/A speed=   0x    \nframe=   10 fps=9.0 q=0.0 size=       0kB time=00:00:00.00 bitrate=N/A speed=   0x    \nframe=   17 fps= 10 q=0.0 size=       0kB time=00:00:00.00 bitrate=N/A speed=   0x    \nframe=   24 fps= 11 q=0.0 size=       0kB time=00:00:00.00 bitrate=N/A speed=   0x    \nframe=   30 fps= 11 q=0.0 size=       0kB time=00:00:00.00 bitrate=N/A speed=   0x    \nframe=   36 fps= 11 q=0.0 size=       0kB time=00:00:00.00 bitrate=N/A speed=   0x    \n"
}
error[07/01/2021, 16:21:28] Cannot execute job 9 in queue video-transcoding.
{
  "payload": {
    "type": "optimize",
    "videoUUID": "9bafd150-17de-40ed-8a3d-c8affe909650",
    "isNewVideo": true
  },
  "err": {
    "stack": "Error: ffmpeg was killed with signal SIGKILL\n    at ChildProcess.<anonymous> (/app/node_modules/fluent-ffmpeg/lib/processor.js:180:22)\n    at ChildProcess.emit (events.js:198:13)\n    at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)",
    "message": "ffmpeg was killed with signal SIGKILL"
  }
}
```

**Comment by Chocobozzz** [comment]
After how long the task is killed?

**Comment by Ranjeetvit453** [comment]
## Server Configuration
- **Instance:** `t2.2xlarge`
- **vCPUs:** 8
- **Memory:** 32 GB

If you're deploying an application on EC2 using this instance, ensure that you configure resources and optimize `ffmpeg` usage to leverage the available hardware. Make sure ffmpeg is tuned for multi-threading to fully utilize the 8 vCPUs and ensure that the instance's 32 GB memory is effectively managed during video processing.

For more details on ffmpeg video conversion, refer to the repository below:

### Related GitHub Repository:
[h264-video-conversion-ffmpeg](https://github.com/ranjeetvit2012/h264-video-conversion-ffmpeg/blob/master/README.md)
