### ISSUE TITLE
Missing column url after upgrade to v3

### ISSUE THREAD

**Issue by c0xc** [Chocobozzz/PeerTube#3555]
**Describe the problem**

After installing version 3 and updating the config files to use the existing tables created by version 2, the application fails to start because it's missing some columns which didn't exist in version 2:
```
debug: Executing (default): CREATE UNIQUE INDEX "actor_follow_url" ON "actorFollow" ("url")
error: Cannot install application. {
  "err": {
    "stack": "SequelizeDatabaseError: column \"url\" does not exist\n    at Query.formatError (.../versions/peertube-v3.0.0/node_modules/sequelize/lib/dialects/postgres/query.js:386:16)\n    at Query.run (.../versions/peertube-v3.0.0/node_modules/sequelize/lib/dialects/postgres/query.js:87:18)\n    at process._tickCallback (internal/process/next_tick.js:68:7)",
    "message": "column \"url\" does not exist",
    "name": "SequelizeDatabaseError",
```
No automatic migration is happening prior to that and there does not seem to be a manual migration script either.

Further points, related:
- adding that column (just curious) allows the application to start but there are more missing columns
- gui login fails but running browser session still usable (though 503 "token is invalid" errors appear)
- videos missing under "local"

Even though the last point is probably caused by the previous errors, I've noted it because it made me think that it would be great to have a video export feature, to be able to restore all videos from that backup archive in a new instance.

**Provide the exact sequence of commands / steps that you executed before running into the problem**
**Additional information**

When the instance was installed with version 2, a db schema was created for the Peertube user, so it created all tables and everything within that schema. Before starting version 3, everything worked perfectly fine. Now, it seems like Peertube expects some things in the schema named "public"?

* PeerTube instance:
  * version: 2.4.0 + 3.0.0
  * NodeJS version: v10.21.0
  * Ffmpeg version: 4.2.4
  * Redis version: 6.0.9
  * PostgreSQL version: PostgreSQL 12.4

**Comment by rigelk** [comment]
hi @c0xc,

Do you confirm you were running a PeerTube v2.4.0 before updating it to 3.0.0?

**Comment by c0xc** [comment]
Yes, that's correct. And I guess I can also confirm the suspicion that some migration / startup routine expects the schema name "public" because when I imported the schema in a new db and renamed it there, it worked. I saw a query to public, but I haven't checked yet where it's coming from.
