### ISSUE TITLE
Validation error: \"\" is not a valid description

### ISSUE THREAD

**Issue by karthanistyr** [Chocobozzz/PeerTube#3566]
**Describe the current behavior**
My instance's journal logs hundreds of these (a handful to a dozen per hour)
```
error[09/01/2021 à 12:43:21] Cannot execute saveActorAndServerAndModelIfNotExist with many retries.

{
  "err": {
    "stack": "SequelizeValidationError: Validation error: \"\" is not a valid description.\n    at InstanceValidator._validate (/app/node_modules/sequelize/lib/instance-validator.js:78:13)\n    at process._tickCallback (internal/process/next_tick.js:68:7)",
    "message": "Validation error: \"\" is not a valid description.",
    "name": "SequelizeValidationError",
    "errors": [
      {
        "message": "\"\" is not a valid description.",
        "type": "Validation error",
        "path": "description",
        "value": "",
        "origin": "FUNCTION",
        "instance": {
          "id": null,
          "name": "Anaesthete",
          "description": "",
          "actorId": 10567,
          "updatedAt": "2021-01-09T11:43:21.907Z",
          "createdAt": "2021-01-09T11:43:21.907Z"
        },
        "validatorKey": "isAccountDescription",
        "validatorName": null,
        "validatorArgs": [],
        "original": {
          "stack": "Error: \"\" is not a valid description.\n    at Object.throwIfNotValid (/app/dist/server/models/utils.js:92:15)\n    at AccountModel.tslib_1.__decorate.sequelize_typescript_1.Is.value (/app/dist/server/models/account/account.js:235:70)\n    at InstanceValidator._invokeCustomValidator (/app/node_modules/sequelize/lib/instance-validator.js:277:30)\n    at _.forIn (/app/node_modules/sequelize/lib/instance-validator.js:213:30)\n    at /app/node_modules/lodash/lodash.js:4925:15\n    at Function.forIn (/app/node_modules/lodash/lodash.js:12976:11)\n    at InstanceValidator._singleAttrValidate (/app/node_modules/sequelize/lib/instance-validator.js:198:7)\n    at _.forIn (/app/node_modules/sequelize/lib/instance-validator.js:148:30)\n    at /app/node_modules/lodash/lodash.js:4925:15\n    at Function.forIn (/app/node_modules/lodash/lodash.js:12976:11)\n    at InstanceValidator._perAttributeValidators (/app/node_modules/sequelize/lib/instance-validator.js:131:7)\n    at InstanceValidator._validate (/app/node_modules/sequelize/lib/instance-validator.js:73:12)\n    at InstanceValidator._validateAndRunHooks (/app/node_modules/sequelize/lib/instance-validator.js:111:18)\n    at process._tickCallback (internal/process/next_tick.js:68:7)",
          "message": "\"\" is not a valid description."
        }
      }
    ]
  }
}
```

**Steps to reproduce:**
No real idea how to reproduce, these logs are generated in the background. My instance sits mostly idle and I browse it from time to time...

**Describe the expected behavior**
This looks like some other AP software that sends a field in an unexpected way -- is it worth rejecting actors on that basis?

**Additional information**

* PeerTube instance:
  * URL: video.barbed.fr
  * version: 3.0.0 (docker)
  * NodeJS version: docker
  * Ffmpeg version: docker

* Browser name, version and platforms on which you could reproduce the bug: N/A
* Link to browser console log if relevant: N/A (server-side logs)
* Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`): https://gist.github.com/karthanistyr/f87bec0eac103e7d5084639718b38ec1

**Comment by Chocobozzz** [comment]
> is it worth rejecting actors on that basis?

No you're right. Fixed in https://github.com/Chocobozzz/PeerTube/commit/b3fa96eea0c6842459f978385a6b424a0beee4fa
