### ISSUE TITLE
Handle 413 “Payload Too Large” when importing videos using CLI

### ISSUE THREAD

**Issue by frntn** [Chocobozzz/PeerTube#3586]
**Describe the current behavior**

_CLI crashes when trying to upload a big video file_

Here is the big file :
```bash
$ ls -lh /srv/tmp/videos/020709ab-7392-4fbc-88c6-8ca586c96eb6-720.mp4
-rw-r--r-- 1 root root 1.6G Dec 16 16:13 /srv/tmp/videos/020709ab-7392-4fbc-88c6-8ca586c96eb6-720.mp4
```

And here is how the upload fails
```
$ node ./dist/server/tools/peertube.js up -u http://tube.private.instance -U "$PT_UPLOAD_USER" -p "$PT_UPLOAD_PASS" -f /srv/tmp/videos/020709ab-7392-4fbc-88c6-8ca586c96eb6-720.mp4 -n Import
Uploading Import video...
Error: expected 200 "OK", got 413 "Payload Too Large"
    at Test._assertStatus (/srv/tmp/peertube-cli/node_modules/supertest/lib/test.js:270:12)
    at Test._assertFunction (/srv/tmp/peertube-cli/node_modules/supertest/lib/test.js:285:11)
    at Test.assert (/srv/tmp/peertube-cli/node_modules/supertest/lib/test.js:175:21)
    at localAssert (/srv/tmp/peertube-cli/node_modules/supertest/lib/test.js:133:12)
    at /srv/tmp/peertube-cli/node_modules/supertest/lib/test.js:130:5
    at Test.Request.callback (/srv/tmp/peertube-cli/node_modules/superagent/lib/node/index.js:905:3)
    at /srv/tmp/peertube-cli/node_modules/superagent/lib/node/index.js:1127:20
    at IncomingMessage.<anonymous> (/srv/tmp/peertube-cli/node_modules/superagent/lib/node/parsers/json.js:22:7)
    at IncomingMessage.emit (events.js:203:15)
    at endReadableNT (_stream_readable.js:1145:12)

$ docker logs peertube_peertube_1
[tube.private.instance:443] 2021-01-12 01:31:13.517 info: 172.18.0.1 - - [12/Jan/2021:01:31:13 +0000] "GET /api/v1/oauth-clients/local HTTP/1.1" 200 99 "-" "-"
[tube.private.instance:443] 2021-01-12 01:31:13.657 info: 172.18.0.1 - - [12/Jan/2021:01:31:13 +0000] "POST /api/v1/users/token HTTP/1.1" 200 159 "-" "-"
[tube.private.instance:443] 2021-01-12 01:31:13.702 info: 172.18.0.1 - - [12/Jan/2021:01:31:13 +0000] "GET /api/v1/users/me HTTP/1.1" 200 1738 "-" "-"
[tube.private.instance:443] 2021-01-12 01:31:17.297 info: 172.18.0.1 - - [12/Jan/2021:01:31:17 +0000] "POST /api/v1/videos/upload HTTP/1.1" 413 61 "-" "-"

$  git branch
* (HEAD detached at v3.0.0)
  develop
```

While the url points directly to Peertube via loopback interface (If you wonder I use haproxy on the host to forward traffic to backend server 127.0.0.1:80)
```
# DNS resolve to 127.0.0.1
$ grep tube.private.instance /etc/hosts
127.0.0.1 tube.private.instance
$ ping -c 1 tube.private.instance
PING tube.private.instance (127.0.0.1) 56(84) bytes of data.
64 bytes from localhost (127.0.0.1): icmp_seq=1 ttl=64 time=0.054 ms

# Port 80 is not a reverse-proxy
$ docker ps
CONTAINER ID   IMAGE                                   COMMAND                  CREATED          STATUS          PORTS                              NAMES
6f01cd2458b4   chocobozzz/peertube:production-buster   "/usr/local/bin/entr…"   33 minutes ago   Up 33 minutes   1935/tcp, 127.0.0.1:80->9000/tcp   peertube_peertube_1
3830e7e9b0f0   mwader/postfix-relay                    "/root/run"              33 minutes ago   Up 33 minutes   25/tcp                             peertube_postfix_1
12acf8e549fb   postgres:10-alpine                      "docker-entrypoint.s…"   33 minutes ago   Up 33 minutes   5432/tcp                           peertube_postgres_1
a499134ea1e9   redis:4-alpine                          "docker-entrypoint.s…"   33 minutes ago   Up 33 minutes   6379/tcp                           peertube_redis_1
```

**Important Note** : 
The whole instance installation process is automated (base os + peertube + import validation)
This setup was still working just some days agos.
I _suspect_ (!) the peertube docker image has been updated with this issue.

I use `production-buster` :
```
docker images
REPOSITORY             TAG                 IMAGE ID       CREATED        SIZE
mwader/postfix-relay   latest              b94081c9b86b   35 hours ago   120MB
chocobozzz/peertube    production-buster   ca92894f4214   4 days ago     1.06GB
postgres               10-alpine           bcf7ff6fcd84   13 days ago    72.4MB
redis                  4-alpine            e3dd0e49bca5   8 months ago   20.4MB
```

**Steps to reproduce:**

1. Spinup a peertube instance using docker image `production-buster`
2. Install the peertube cli helper
3. Try to upload a big video

**Describe the expected behavior**

No 4xx failure

**Additional information**

* PeerTube instance:
  * URL: not available, this is private instance
  * version: cli `v3.0.0` / app `production-buster`
  * NodeJS version: `v10.23.1` (app `production-buster`)
  * Ffmpeg version: `7:4.1.6-1~deb10u1` (app `production-buster`)

* Browser name, version and platforms on which you could reproduce the bug:
* Link to browser console log if relevant: not relevant
* Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`):

**Comment by frntn** [comment]
Same error experience as in #3210
But I don't use the reverse-proxy for cli upload

**Comment by frntn** [comment]
Well.... in order to add some relevant informations in this issue I have updated the production.yaml (set debug log) et restart the containers (compose down/up)

And now everythings alright 🤦 
I guess we'll never know what happened here 😏 

Thanks for all your work and efforts in this project.
And GG for RTMP support you rocks 💪

**Comment by frntn** [comment]
Ok found out what caused the behavior 
One last command for future readers ( hello you 👋😆  )

My automation used to create the user using the API with this payload
```json
{ "username": "$PT_UPLOAD_USER", "password": "$PT_UPLOAD_PASS", "email": "$PT_UPLOAD_MAIL", "videoQuota": 0, "videoQuotaDaily": 0, "role": 0}
```

I had to fix it with this one
```json
{ "username": "$PT_UPLOAD_USER", "password": "$PT_UPLOAD_PASS", "email": "$PT_UPLOAD_MAIL", "videoQuota": -1, "videoQuotaDaily": -1, "role": 0}
```

I reopen the issue
Maybe be the CLI could handle the error nicely (no crash + a suggestion about a possible user limit inside the app...)

**Comment by Chocobozzz** [comment]
Fixed in https://github.com/Chocobozzz/PeerTube/commit/743dab5517d4501f6b35cfc795de6c8b6f41ebb3
