### ISSUE TITLE
Live will not start. 

### ISSUE THREAD

**Issue by brazda** [Chocobozzz/PeerTube#3590]
**Describe the current behavior**
Trying to go live it never connects. OBS will connect for about 4 seconds and then it will start reconnecting. Peertube never shows up as it went active. 

**Steps to reproduce:**

1. Start stream on peertube V3.0.1 
2.  Setup OBS to stream bitrate 15000 Kbps, encoder software x264 audio bit rate 160
3.  start stream

**Describe the expected behavior**

**Additional information**
When it connects I get this in syslog. 

 Jan 12 17:59:02 jbserver peertube[11649]: [peertube.linuxrocks.online:443] 2021-01-12 17:59:01.999 #033[32minfo#033[39m: 77.38.219.91 - - [12/Jan/2021:17:59:01 +0000] "GET /accounts/peertube HTTP/1.0" 200 2818 "-" "-"
Jan 12 17:59:03 jbserver peertube[11649]: [peertube.linuxrocks.online:443] 2021-01-12 17:59:03.654 #033[32minfo#033[39m: Will mux/transcode live video of original resolution 720. {
Jan 12 17:59:03 jbserver peertube[11649]:   "allResolutions": [
Jan 12 17:59:03 jbserver peertube[11649]:     480,
Jan 12 17:59:03 jbserver peertube[11649]:     360,
Jan 12 17:59:03 jbserver peertube[11649]:     240,
Jan 12 17:59:03 jbserver peertube[11649]:     720
Jan 12 17:59:03 jbserver peertube[11649]:   ]
Jan 12 17:59:03 jbserver peertube[11649]: }
Jan 12 17:59:05 jbserver peertube[11649]: [peertube.linuxrocks.online:443] 2021-01-12 17:59:05.524 #033[32minfo#033[39m: Running live muxing/transcoding for 9734cd9a-0097-4bae-a08c-7a287c16dc6f.
Jan 12 17:59:05 jbserver peertube[11649]: [peertube.linuxrocks.online:443] 2021-01-12 17:59:05.780 #033[32minfo#033[39m: RTMP transmuxing for video rtmp://127.0.0.1:1935/live/XXXXXXXXXXXXXXXXXX ended. Scheduling cleanup
Jan 12 17:59:05 jbserver peertube[11649]: [peertube.linuxrocks.online:443] 2021-01-12 17:59:05.782 #033[31merror#033[39m: Live transcoding error. {
Jan 12 17:59:05 jbserver peertube[11649]:   "err": {
Jan 12 17:59:05 jbserver peertube[11649]:     "stack": "Error: ffmpeg exited with code 1: Unrecognized option 'master_pl_name'.\nError splitting the argument list: Option not found\n\n    at ChildProcess.<anonymous> (/var/www/peertube/versions/peertube-v3.0.1/node_modules/fluent-ffmpeg/lib/processor.js:182:22)\n    at ChildProcess.emit (events.js:198:13)\n    at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)",
Jan 12 17:59:05 jbserver peertube[11649]:     "message": "ffmpeg exited with code 1: Unrecognized option 'master_pl_name'.\nError splitting the argument list: Option not found\n"
Jan 12 17:59:05 jbserver peertube[11649]:   },
Jan 12 17:59:05 jbserver peertube[11649]:   "stdout": "",
Jan 12 17:59:05 jbserver peertube[11649]:   "stderr": "ffmpeg version 3.4.8-0ubuntu0.2 Copyright (c) 2000-2020 the FFmpeg developers\n  built with gcc 7 (Ubuntu 7.5.0-3ubuntu1~18.04)\n  configuration: --prefix=/usr --extra-version=0ubuntu0.2 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --enable-gpl --disable-stripping --enable-avresample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librubberband --enable-librsvg --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-omx --enable-openal --enable-opengl --enable-sdl2 --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libopencv --enable-libx264 --enable-shared\n  libavutil      55. 78.100 / 55. 78.100\n  libavcodec     57.107.100 / 57.107.100\n  libavformat    57. 83.100 / 57. 83.100\n  libavdevice    57. 10.100 / 57. 10.100\n  libavfilter     6.107.100 /  6.107.100\n  libavresample   3.  7.  0 /  3.  7.  0\n  libswscale      4.  8.100 /  4.  8.100\n  libswresample   2.  9.100 /  2.  9.100\n  libpostproc    54.  7.100 / 54.  7.100\nUnrecognized option 'master_pl_name'.\nError splitting the argument list: Option not found\n"
Jan 12 17:59:05 jbserver peertube[11649]: }
Jan 12 17:59:05 jbserver peertube[11649]: [peertube.linuxrocks.online:443] 2021-01-12 17:59:05.784 #033[32minfo#033[39m: Live session ended. {

----

{"err":{"stack":"Error: ffmpeg exited with code 1: Unrecognized option 'master_pl_name'.\nError splitting the argument list: Option not found\n\n    at ChildProcess.<anonymous> (/var/www/peertube/versions/peertube-v3.0.1/node_modules/fluent-ffmpeg/lib/processor.js:182:22)\n    at ChildProcess.emit (events.js:198:13)\n    at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)","message":"ffmpeg exited with code 1: Unrecognized option 'master_pl_name'.\nError splitting the argument list: Option not found\n"},"stdout":"","stderr":"ffmpeg version 3.4.8-0ubuntu0.2 Copyright (c) 2000-2020 the FFmpeg developers\n  built with gcc 7 (Ubuntu 7.5.0-3ubuntu1~18.04)\n  configuration: --prefix=/usr --extra-version=0ubuntu0.2 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --enable-gpl --disable-stripping --enable-avresample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librubberband --enable-librsvg --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-omx --enable-openal --enable-opengl --enable-sdl2 --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libopencv --enable-libx264 --enable-shared\n  libavutil      55. 78.100 / 55. 78.100\n  libavcodec     57.107.100 / 57.107.100\n  libavformat    57. 83.100 / 57. 83.100\n  libavdevice    57. 10.100 / 57. 10.100\n  libavfilter     6.107.100 /  6.107.100\n  libavresample   3.  7.  0 /  3.  7.  0\n  libswscale      4.  8.100 /  4.  8.100\n  libswresample   2.  9.100 /  2.  9.100\n  libpostproc    54.  7.100 / 54.  7.100\nUnrecognized option 'master_pl_name'.\nError splitting the argument list: Option not found\n","level":"error","message":"Live transcoding error.","label":"peertube.linuxrocks.online:443","timestamp":"2021-01-12T18:11:58.498Z"}

* PeerTube instance:
  * URL: peertube.linuxrocks.online
  * version: 3.0.1
  * NodeJS version:  v10.23.1
  * Ffmpeg version: version 3.4.8-0ubuntu0.2

* Browser name, version and platforms on which you could reproduce the bug:
* Link to browser console log if relevant:
* Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`):

**Comment by brazda** [comment]
Nevermind. In filling this out I realized that ffmpeg version was to low. Updated and it works fine.
