### ISSUE TITLE
Cannot get client token for host and Invalid Client errors

### ISSUE THREAD

**Issue by multim234** [Chocobozzz/PeerTube#3608]
**Describe the problem**
I always have the error on my instance `Cannot retrieve OAuth Client credentials: undefined. Ensure you have correctly configured PeerTube (config/ directory), in particular the "webserver" section.`
We I try to log in I get `Invalid client: client is invalid`.
Also on some request the message `Getting client tokens for host localhost.local is forbidden` appear.

**Additional information**
I run PeerTube on Archlinux from the Aur package. The goal of this instance is only to be on LAN.

* PeerTube instance:
  * version: 3.0.1
  * NodeJS version: v10.23.1
  * Ffmpeg version: n4.3.1
  * Redis version: 6.0.10-1
  * PostgreSQL version: 13.1-3

`/etc/peertube/production.yaml` :
```yaml
listen:
  hostname: 'localhost'
  port: 9000                                                                                   

webserver:
  https: true
  hostname: localhost.local
  port: 433

trust_proxy:                                                                                   
  - 'loopback'

<-->
```

```nginx
server {
  listen 80;
  listen [::]:80;
  server_name localhost.local;

  location / { return 301 https://$host$request_uri; }
}

upstream backend {
  server 127.0.0.1:9000;
}

server {
  listen 443 ssl http2;
  listen [::]:443 ssl http2;
  server_name localhost.local;

  access_log /var/log/nginx/peertube.access.log; # reduce I/0 with buffer=10m flush=5m
  error_log  /var/log/nginx/peertube.error.log;

  ssl_certificate     /etc/nginx/sites-available/peertube.crt;
  ssl_certificate_key /etc/nginx/sites-available/peertube.key;

  ssl_protocols             TLSv1.2 TLSv1.3;
  ssl_prefer_server_ciphers on;
  ssl_ciphers               ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA256; # add ECDHE-RSA-AES256-SHA if you want compatibility with Android 4
  ssl_session_timeout       1d; # defaults to 5m
  ssl_session_cache         shared:SSL:10m; # estimated to 40k sessions
  ssl_session_tickets       off;
  ssl_stapling              on;
  ssl_stapling_verify       on;
  add_header Strict-Transport-Security "max-age=63072000; includeSubDomains";

  location @api {
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header Host            $host;
    proxy_set_header X-Real-IP       $remote_addr;

    client_max_body_size  100k; # default is 1M

    proxy_connect_timeout 10m;
    proxy_send_timeout    10m;
    proxy_read_timeout    10m;
    send_timeout          10m;

    proxy_pass http://backend;
  }

  location / {
    try_files /dev/null @api;
  }

  location = /api/v1/users/me/avatar/pick {
    limit_except POST HEAD { deny all; }

    client_max_body_size                      2M; # default is 1M
    add_header            X-File-Maximum-Size 2M always; # inform backend of the set value in bytes

    try_files /dev/null @api;
  }

  location = /api/v1/videos/upload {
    limit_except POST HEAD { deny all; }
    client_max_body_size                      8G; # default is 1M
    add_header            X-File-Maximum-Size 8G always; # inform backend of the set value in bytes

    try_files /dev/null @api;
  }

  location @api_websocket {
    proxy_http_version 1.1;
    proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header   Host            $host;
    proxy_set_header   X-Real-IP       $remote_addr;
    proxy_set_header   Upgrade         $http_upgrade;
    proxy_set_header   Connection      "upgrade";


    proxy_pass http://backend;
  }

  location /socket.io {
    try_files /dev/null @api_websocket;
  }

  location /tracker/socket {
    proxy_read_timeout 15m; # default is 60s

    try_files /dev/null @api_websocket;
  }

  root /var/lib/peertube/storage;

  gzip              on;
  gzip_vary         on;
  gzip_types        # text/html is always compressed by HttpGzipModule
                    text/css
                    application/javascript
                    font/truetype
                    font/opentype
                    application/vnd.ms-fontobject
                    image/svg+xml;
  gzip_min_length   1000; # default is 20 bytes
  gzip_buffers      16 8k;
  gzip_comp_level   2; # default is 1

  client_body_timeout       30s; # default is 60
  client_header_timeout     10s; # default is 60
  send_timeout              10s; # default is 60
  keepalive_timeout         10s; # default is 75
  resolver_timeout          10s; # default is 30
  reset_timedout_connection on;

  tcp_nopush                on; # send headers in one piece
  tcp_nodelay               on; # don't buffer data sent, good for small data bursts in real time

  location ~ ^/client/(assets/images/(icons/icon-36x36\.png|icons/icon-48x48\.png|icons/icon-72x72\.png|icons/icon-96x96\.png|icons/icon-144x144\.png|icons/icon-192x192\.png|icons/icon-512x512\.png|logo\.svg|favicon\.png))$ {
    add_header Cache-Control "public, max-age=31536000, immutable"; # Cache 1 year

    root /var/lib/peertube;

    try_files /storage/client-overrides/$1 peertube-latest/client/dist/$1 @api;
  }

  location ~ ^/client/(.*\.(js|css|png|svg|woff2|otf|ttf|woff|eot))$ {
    add_header Cache-Control "public, max-age=31536000, immutable"; # Cache 1 year

    alias /var/lib/peertube/peertube-latest/client/dist/$1;
  }

  location ~ ^/static/(thumbnails|avatars)/ {
    if ($request_method = 'OPTIONS') {
      add_header Access-Control-Allow-Origin  '*';
      add_header Access-Control-Allow-Methods 'GET, OPTIONS';
      add_header Access-Control-Allow-Headers 'Range,DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type';
      add_header Access-Control-Max-Age       1728000; # Preflight request can be cached 20 days
      add_header Content-Type                 'text/plain charset=UTF-8';
      add_header Content-Length               0;
      return 204;
    }

    add_header Access-Control-Allow-Origin    '*';
    add_header Access-Control-Allow-Methods   'GET, OPTIONS';
    add_header Access-Control-Allow-Headers   'Range,DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type';
    add_header Cache-Control                  "public, max-age=7200"; # Cache response 2 hours

    rewrite ^/static/(.*)$ /$1 break;

    try_files $uri @api;
  }

  location ~ ^/static/(webseed|redundancy|streaming-playlists)/ {
    limit_rate_after            5M;

    set $peertube_limit_rate    800k;

    if ($request_uri ~ -fragmented.mp4$) {
      set $peertube_limit_rate  5M;
    }

    # Use this line with nginx >= 1.17.0
    #limit_rate $peertube_limit_rate;
    # Or this line if your nginx < 1.17.0
    set $limit_rate $peertube_limit_rate;

    if ($request_method = 'OPTIONS') {
      add_header Access-Control-Allow-Origin  '*';
      add_header Access-Control-Allow-Methods 'GET, OPTIONS';
      add_header Access-Control-Allow-Headers 'Range,DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type';
      add_header Access-Control-Max-Age       1728000; # Preflight request can be cached 20 days
      add_header Content-Type                 'text/plain charset=UTF-8';
      add_header Content-Length               0;
      return 204;
    }

    if ($request_method = 'GET') {
      add_header Access-Control-Allow-Origin  '*';
      add_header Access-Control-Allow-Methods 'GET, OPTIONS';
      add_header Access-Control-Allow-Headers 'Range,DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type';

      access_log off;
    }


    sendfile on;
    sendfile_max_chunk 1M; # prevent one fast connection from entirely occupying the worker process. should be > 800k.
    aio threads;

    
    rewrite ^/static/webseed/(.*)$ /videos/$1 break;
    rewrite ^/static/(.*)$         /$1        break;

    try_files $uri @api;
  }
}
```
```
[localhost.local:433] 2021-01-16 11:03:15.465 info: HTTP server listening on localhost:9000
[localhost.local:433] 2021-01-16 11:03:15.465 info: Web server: https://localhost.local:433
[localhost.local:433] 2021-01-16 11:05:10.069 info: 127.0.0.1 - - [16/Jan/2021:10:05:10 +0000] "GET /login HTTP/1.0" 200 4137 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.141 Safari/537.36"
[localhost.local:433] 2021-01-16 11:05:10.360 info: Getting client tokens for host localhost.local is forbidden (expected localhost.local:433).
[localhost.local:433] 2021-01-16 11:05:10.361 info: 127.0.0.1 - - [16/Jan/2021:10:05:10 +0000] "GET /api/v1/oauth-clients/local HTTP/1.0" 403 - "https://localhost.local/login" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.141 Safari/537.36"
[localhost.local:433] 2021-01-16 11:05:10.365 info: 127.0.0.1 - - [16/Jan/2021:10:05:10 +0000] "GET /api/v1/config/ HTTP/1.0" 200 1961 "https://localhost.local/login" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.141 Safari/537.36"
[localhost.local:433] 2021-01-16 11:05:10.375 info: 127.0.0.1 - - [16/Jan/2021:10:05:10 +0000] "GET /api/v1/videos/languages HTTP/1.0" 200 3242 "https://localhost.local/login" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.141 Safari/537.36"
[localhost.local:433] 2021-01-16 11:05:10.410 info: 127.0.0.1 - - [16/Jan/2021:10:05:10 +0000] "GET /client/assets/images/logo.svg?1385eb03c10f14af3deeddd7e66be60236761729 HTTP/1.0" 200 501 "https://localhost.local/login" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.141 Safari/537.36"
[localhost.local:433] 2021-01-16 11:05:10.520 info: 127.0.0.1 - - [16/Jan/2021:10:05:10 +0000] "GET /api/v1/config/about HTTP/1.0" 200 458 "https://localhost.local/login" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.141 Safari/537.36"
[localhost.local:433] 2021-01-16 11:05:10.560 info: 127.0.0.1 - - [16/Jan/2021:10:05:10 +0000] "GET /client/assets/images/favicon.png?3abd804b84d357cad8fe74c9d241a429a243ba6f HTTP/1.0" 200 746 "https://localhost.local/login" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.141 Safari/537.36"
[localhost.local:433] 2021-01-16 11:11:38.067 info: 127.0.0.1 - - [16/Jan/2021:10:11:38 +0000] "GET /about/instance HTTP/1.0" 200 4137 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:84.0) Gecko/20100101 Firefox/84.0"
[localhost.local:433] 2021-01-16 11:11:38.250 info: 127.0.0.1 - - [16/Jan/2021:10:11:38 +0000] "GET /client/assets/images/logo.svg?1385eb03c10f14af3deeddd7e66be60236761729 HTTP/1.0" 200 501 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:84.0) Gecko/20100101 Firefox/84.0"
[localhost.local:433] 2021-01-16 11:11:38.678 info: 127.0.0.1 - - [16/Jan/2021:10:11:38 +0000] "GET /api/v1/config/ HTTP/1.0" 200 1961 "https://localhost.local/about/instance" "Mozilla/5.0 (X11; Linux x86_64; rv:84.0) Gecko/20100101 Firefox/84.0"
[localhost.local:433] 2021-01-16 11:11:38.697 info: Getting client tokens for host localhost.local is forbidden (expected localhost.local:433).
[localhost.local:433] 2021-01-16 11:11:38.697 info: 127.0.0.1 - - [16/Jan/2021:10:11:38 +0000] "GET /api/v1/oauth-clients/local HTTP/1.0" 403 - "https://localhost.local/about/instance" "Mozilla/5.0 (X11; Linux x86_64; rv:84.0) Gecko/20100101 Firefox/84.0"
[localhost.local:433] 2021-01-16 11:11:38.718 info: 127.0.0.1 - - [16/Jan/2021:10:11:38 +0000] "GET /api/v1/videos/languages HTTP/1.0" 200 3242 "https://localhost.local/about/instance" "Mozilla/5.0 (X11; Linux x86_64; rv:84.0) Gecko/20100101 Firefox/84.0"
[localhost.local:433] 2021-01-16 11:11:38.799 info: 127.0.0.1 - - [16/Jan/2021:10:11:38 +0000] "GET /client/assets/images/logo.svg?1385eb03c10f14af3deeddd7e66be60236761729 HTTP/1.0" 200 501 "https://localhost.local/about/instance" "Mozilla/5.0 (X11; Linux x86_64; rv:84.0) Gecko/20100101 Firefox/84.0"
[localhost.local:433] 2021-01-16 11:11:38.828 info: 127.0.0.1 - - [16/Jan/2021:10:11:38 +0000] "GET /client/assets/images/icons/icon-192x192.png HTTP/1.0" 200 2926 "https://localhost.local/about/instance" "Mozilla/5.0 (X11; Linux x86_64; rv:84.0) Gecko/20100101 Firefox/84.0"
[localhost.local:433] 2021-01-16 11:11:38.829 info: 127.0.0.1 - - [16/Jan/2021:10:11:38 +0000] "GET /client/assets/images/favicon.png?3abd804b84d357cad8fe74c9d241a429a243ba6f HTTP/1.0" 200 746 "https://localhost.local/about/instance" "Mozilla/5.0 (X11; Linux x86_64; rv:84.0) Gecko/20100101 Firefox/84.0"
[localhost.local:433] 2021-01-16 11:11:38.844 info: 127.0.0.1 - - [16/Jan/2021:10:11:38 +0000] "GET /api/v1/config/about HTTP/1.0" 304 - "https://localhost.local/about/instance" "Mozilla/5.0 (X11; Linux x86_64; rv:84.0) Gecko/20100101 Firefox/84.0"
[localhost.local:433] 2021-01-16 11:11:38.992 info: 127.0.0.1 - - [16/Jan/2021:10:11:38 +0000] "GET /api/v1/videos/categories HTTP/1.0" 304 - "https://localhost.local/about/instance" "Mozilla/5.0 (X11; Linux x86_64; rv:84.0) Gecko/20100101 Firefox/84.0"
[localhost.local:433] 2021-01-16 11:13:10.844 info: 127.0.0.1 - - [16/Jan/2021:10:13:10 +0000] "GET /api/v1/overviews/videos?page=1 HTTP/1.0" 200 41 "https://localhost.local/videos/overview" "Mozilla/5.0 (X11; Linux x86_64; rv:84.0) Gecko/20100101 Firefox/84.0"
[localhost.local:433] 2021-01-16 11:13:12.853 info: 127.0.0.1 - - [16/Jan/2021:10:13:12 +0000] "GET /api/v1/config/about HTTP/1.0" 304 - "https://localhost.local/login" "Mozilla/5.0 (X11; Linux x86_64; rv:84.0) Gecko/20100101 Firefox/84.0"
[localhost.local:433] 2021-01-16 11:13:16.132 warn: Login error. {
  "err": {
    "statusCode": 400,
    "status": 400,
    "code": 400,
    "message": "Invalid client: client is invalid",
    "name": "invalid_client",
    "stack": "invalid_client: Invalid client: client is invalid\n    at new InvalidClientError (/usr/share/webapps/peertube/node_modules/oauth2-server/lib/errors/invalid-client-error.js:26:14)\n    at /usr/share/webapps/peertube/node_modules/oauth2-server/lib/handlers/token-handler.js:141:15\n    at tryCatcher (/usr/share/webapps/peertube/node_modules/bluebird/js/release/util.js:16:23)\n    at Promise._settlePromiseFromHandler (/usr/share/webapps/peertube/node_modules/bluebird/js/release/promise.js:547:31)\n    at Promise._settlePromise (/usr/share/webapps/peertube/node_modules/bluebird/js/release/promise.js:604:18)\n    at Promise._settlePromise0 (/usr/share/webapps/peertube/node_modules/bluebird/js/release/promise.js:649:10)\n    at Promise._settlePromises (/usr/share/webapps/peertube/node_modules/bluebird/js/release/promise.js:729:18)\n    at _drainQueueStep (/usr/share/webapps/peertube/node_modules/bluebird/js/release/async.js:93:12)\n    at _drainQueue (/usr/share/webapps/peertube/node_modules/bluebird/js/release/async.js:86:9)\n    at Async._drainQueues (/usr/share/webapps/peertube/node_modules/bluebird/js/release/async.js:102:5)\n    at Immediate.Async.drainQueues [as _onImmediate] (/usr/share/webapps/peertube/node_modules/bluebird/js/release/async.js:15:14)\n    at runCallback (timers.js:705:18)\n    at tryOnImmediate (timers.js:676:5)\n    at processImmediate (timers.js:658:5)"
  }
}
[localhost.local:433] 2021-01-16 11:13:16.133 info: 127.0.0.1 - - [16/Jan/2021:10:13:16 +0000] "POST /api/v1/users/token HTTP/1.0" 400 69 "https://localhost.local/login" "Mozilla/5.0 (X11; Linux x86_64; rv:84.0) Gecko/20100101 Firefox/84.0"
```

**Comment by multim234** [comment]
I don't know if it's the best but I found something which works.
For `location @api`, just add `:433` in the following line: 
```nginx
proxy_set_header Host $host:433;
```
