### ISSUE TITLE
File transcoding problem

### ISSUE THREAD

**Issue by Alterak** [Chocobozzz/PeerTube#3655]
* PeerTube instance:
  * URL: https://peervideo.ru
  * version: PeerTube v.3.0.1
  * NodeJS version: 12.20.1
  * Ffmpeg version: 4.1.6-1~deb10u1
  * Yarn version: 1.22.5
  * OS: Debian 10.5
  * G++: 8.3.0 (Debian 8.3.0-6)

Browser: Google Chrome 87.0.4280.141 (64 bit)

**Describe the current behavior**
Instance settings enable transcoding of other formats.
![Screenshot_1](https://user-images.githubusercontent.com/11453567/106136499-74e4fb00-617a-11eb-9ed7-e7fabbcc92b3.png)

Sometimes this function works well, but sometimes the downloaded files (.avi .mkv) are not displayed.
There are a lot of such files and you have to recode them with other programs. It is very uncomfortable.

**Steps to reproduce:**
1. I add a video file that has the extension .avi
2. I'm waiting for the file to be added to the instance.
3. After full download, I try to play the downloaded video

For example, this video https://peervideo.ru/videos/watch/b6617010-7077-4023-bacc-7bb81eb80939

If you look at the browser log, you can see the following errors:
```
b6617010-7077-4023-bacc-7bb81eb80939:1 Unchecked runtime.lastError: The message port closed before a response was received.
main-es2015.01e83f0516ea82556b2e.js:3 Injecting 1 themes.
main-es2015.01e83f0516ea82556b2e.js:3 Client credentials loaded.
main-es2015.01e83f0516ea82556b2e.js:3 Enabling default theme.
main-es2015.01e83f0516ea82556b2e.js:3 Loading script /plugins/player-watermark/0.0.1/client-scripts/client/video-watch-client-plugin-out.js of plugin player-watermark.
main-es2015.01e83f0516ea82556b2e.js:3 Loading script /plugins/video-annotation/0.0.5/client-scripts/dist/video-watch-client-plugin.js of plugin video-annotation.
main-es2015.01e83f0516ea82556b2e.js:3 Running hook action:video-watch.video.loaded of plugin player-watermark.
main-es2015.01e83f0516ea82556b2e.js:3 Running hook action:video-watch.player.loaded of plugin video-annotation.
main-es2015.01e83f0516ea82556b2e.js:3 Running hook action:video-watch.player.loaded of plugin player-watermark.
video-watch-client-plugin-out.js:1 https://peervideo.ru/pv.png null
32-es2015.b7805a86685f2e116120.js:1 HLS.js error: mediaError - fatal: false - bufferAppendingError
_onError @ 32-es2015.b7805a86685f2e116120.js:1
(anonymous) @ 32-es2015.b7805a86685f2e116120.js:1
d.emit @ 32-es2015.b7805a86685f2e116120.js:1
i.trigger @ 32-es2015.b7805a86685f2e116120.js:1
r._onSBUpdateError @ 32-es2015.b7805a86685f2e116120.js:1
invokeTask @ polyfills-es2015.975f8cb1db6890c2fcf7.js:1
runTask @ polyfills-es2015.975f8cb1db6890c2fcf7.js:1
invokeTask @ polyfills-es2015.975f8cb1db6890c2fcf7.js:1
l @ polyfills-es2015.975f8cb1db6890c2fcf7.js:1
p @ polyfills-es2015.975f8cb1db6890c2fcf7.js:1
error (async)
x @ polyfills-es2015.975f8cb1db6890c2fcf7.js:1
scheduleTask @ polyfills-es2015.975f8cb1db6890c2fcf7.js:1
scheduleTask @ polyfills-es2015.975f8cb1db6890c2fcf7.js:1
scheduleEventTask @ polyfills-es2015.975f8cb1db6890c2fcf7.js:1
(anonymous) @ polyfills-es2015.975f8cb1db6890c2fcf7.js:1
a.createSourceBuffers @ 32-es2015.b7805a86685f2e116120.js:1
a.checkPendingTracks @ 32-es2015.b7805a86685f2e116120.js:1
a.onBufferCodecs @ 32-es2015.b7805a86685f2e116120.js:1
t.onEventGeneric @ 32-es2015.b7805a86685f2e116120.js:1
t.onEvent @ 32-es2015.b7805a86685f2e116120.js:1
d.emit @ 32-es2015.b7805a86685f2e116120.js:1
i.trigger @ 32-es2015.b7805a86685f2e116120.js:1
u.onFragParsingInitSegment @ 32-es2015.b7805a86685f2e116120.js:1
t.onEventGeneric @ 32-es2015.b7805a86685f2e116120.js:1
t.onEvent @ 32-es2015.b7805a86685f2e116120.js:1
d.emit @ 32-es2015.b7805a86685f2e116120.js:1
i.trigger @ 32-es2015.b7805a86685f2e116120.js:1
t.onWorkerMessage @ 32-es2015.b7805a86685f2e116120.js:1
invokeTask @ polyfills-es2015.975f8cb1db6890c2fcf7.js:1
runTask @ polyfills-es2015.975f8cb1db6890c2fcf7.js:1
invokeTask @ polyfills-es2015.975f8cb1db6890c2fcf7.js:1
l @ polyfills-es2015.975f8cb1db6890c2fcf7.js:1
p @ polyfills-es2015.975f8cb1db6890c2fcf7.js:1
polyfills-es2015.975f8cb1db6890c2fcf7.js:1 Uncaught DOMException: Failed to read the 'buffered' property from 'SourceBuffer': This SourceBuffer has been removed from the parent media source.
    at SourceBuffer.r._onSBUpdateEnd (https://peervideo.ru/client/ru-RU/32-es2015.b7805a86685f2e116120.js:1:147997)
    at u.invokeTask (https://peervideo.ru/client/ru-RU/polyfills-es2015.975f8cb1db6890c2fcf7.js:1:28781)
    at a.runTask (https://peervideo.ru/client/ru-RU/polyfills-es2015.975f8cb1db6890c2fcf7.js:1:24190)
    at f.invokeTask [as invoke] (https://peervideo.ru/client/ru-RU/polyfills-es2015.975f8cb1db6890c2fcf7.js:1:29831)
    at l (https://peervideo.ru/client/ru-RU/polyfills-es2015.975f8cb1db6890c2fcf7.js:1:41768)
    at SourceBuffer.p (https://peervideo.ru/client/ru-RU/polyfills-es2015.975f8cb1db6890c2fcf7.js:1:42013)
runTask @ polyfills-es2015.975f8cb1db6890c2fcf7.js:1
invokeTask @ polyfills-es2015.975f8cb1db6890c2fcf7.js:1
l @ polyfills-es2015.975f8cb1db6890c2fcf7.js:1
p @ polyfills-es2015.975f8cb1db6890c2fcf7.js:1
24-es2015.42ef4036ccaeebdf6e15.js:1 VIDEOJS: ERROR: (CODE:4 MEDIA_ERR_SRC_NOT_SUPPORTED) The media could not be loaded, either because the server or network failed or because the format is not supported. ke {code: 4, message: "The media could not be loaded, either because the …rk failed or because the format is not supported."}
(anonymous) @ 24-es2015.42ef4036ccaeebdf6e15.js:1
r.error @ 24-es2015.42ef4036ccaeebdf6e15.js:1
n.error @ 24-es2015.42ef4036ccaeebdf6e15.js:1
n.handleTechError_ @ 24-es2015.42ef4036ccaeebdf6e15.js:1
i.dispatcher.i.dispatcher @ 24-es2015.42ef4036ccaeebdf6e15.js:1
invokeTask @ polyfills-es2015.975f8cb1db6890c2fcf7.js:1
runTask @ polyfills-es2015.975f8cb1db6890c2fcf7.js:1
invokeTask @ polyfills-es2015.975f8cb1db6890c2fcf7.js:1
l @ polyfills-es2015.975f8cb1db6890c2fcf7.js:1
p @ polyfills-es2015.975f8cb1db6890c2fcf7.js:1
error (async)
x @ polyfills-es2015.975f8cb1db6890c2fcf7.js:1
scheduleTask @ polyfills-es2015.975f8cb1db6890c2fcf7.js:1
scheduleTask @ polyfills-es2015.975f8cb1db6890c2fcf7.js:1
scheduleEventTask @ polyfills-es2015.975f8cb1db6890c2fcf7.js:1
(anonymous) @ polyfills-es2015.975f8cb1db6890c2fcf7.js:1
yt @ 24-es2015.42ef4036ccaeebdf6e15.js:1
Rt @ 24-es2015.42ef4036ccaeebdf6e15.js:1
on @ 24-es2015.42ef4036ccaeebdf6e15.js:1
Rt @ 24-es2015.42ef4036ccaeebdf6e15.js:1
on @ 24-es2015.42ef4036ccaeebdf6e15.js:1
n.loadTech_ @ 24-es2015.42ef4036ccaeebdf6e15.js:1
e @ 24-es2015.42ef4036ccaeebdf6e15.js:1
e.addChild @ 24-es2015.42ef4036ccaeebdf6e15.js:1
(anonymous) @ 24-es2015.42ef4036ccaeebdf6e15.js:1
e.initChildren @ 24-es2015.42ef4036ccaeebdf6e15.js:1
e @ 24-es2015.42ef4036ccaeebdf6e15.js:1
io @ 24-es2015.42ef4036ccaeebdf6e15.js:1
(anonymous) @ 24-es2015.42ef4036ccaeebdf6e15.js:1
I @ polyfills-es2015.975f8cb1db6890c2fcf7.js:1
(anonymous) @ 24-es2015.42ef4036ccaeebdf6e15.js:1
s @ main-es2015.01e83f0516ea82556b2e.js:3
invoke @ polyfills-es2015.975f8cb1db6890c2fcf7.js:1
run @ polyfills-es2015.975f8cb1db6890c2fcf7.js:1
(anonymous) @ polyfills-es2015.975f8cb1db6890c2fcf7.js:1
invokeTask @ polyfills-es2015.975f8cb1db6890c2fcf7.js:1
runTask @ polyfills-es2015.975f8cb1db6890c2fcf7.js:1
v @ polyfills-es2015.975f8cb1db6890c2fcf7.js:1
Promise.then (async)
b @ polyfills-es2015.975f8cb1db6890c2fcf7.js:1
scheduleTask @ polyfills-es2015.975f8cb1db6890c2fcf7.js:1
scheduleTask @ polyfills-es2015.975f8cb1db6890c2fcf7.js:1
scheduleMicroTask @ polyfills-es2015.975f8cb1db6890c2fcf7.js:1
O @ polyfills-es2015.975f8cb1db6890c2fcf7.js:1
k @ polyfills-es2015.975f8cb1db6890c2fcf7.js:1
(anonymous) @ polyfills-es2015.975f8cb1db6890c2fcf7.js:1
Promise.then (async)
(anonymous) @ polyfills-es2015.975f8cb1db6890c2fcf7.js:1
I @ polyfills-es2015.975f8cb1db6890c2fcf7.js:1
D.t.then @ polyfills-es2015.975f8cb1db6890c2fcf7.js:1
k @ polyfills-es2015.975f8cb1db6890c2fcf7.js:1
(anonymous) @ polyfills-es2015.975f8cb1db6890c2fcf7.js:1
invokeTask @ polyfills-es2015.975f8cb1db6890c2fcf7.js:1
runTask @ polyfills-es2015.975f8cb1db6890c2fcf7.js:1
v @ polyfills-es2015.975f8cb1db6890c2fcf7.js:1
Promise.then (async)
b @ polyfills-es2015.975f8cb1db6890c2fcf7.js:1
scheduleTask @ polyfills-es2015.975f8cb1db6890c2fcf7.js:1
scheduleTask @ polyfills-es2015.975f8cb1db6890c2fcf7.js:1
scheduleMicroTask @ polyfills-es2015.975f8cb1db6890c2fcf7.js:1
O @ polyfills-es2015.975f8cb1db6890c2fcf7.js:1
k @ polyfills-es2015.975f8cb1db6890c2fcf7.js:1
(anonymous) @ polyfills-es2015.975f8cb1db6890c2fcf7.js:1
Promise.then (async)
(anonymous) @ polyfills-es2015.975f8cb1db6890c2fcf7.js:1
I @ polyfills-es2015.975f8cb1db6890c2fcf7.js:1
D.t.then @ polyfills-es2015.975f8cb1db6890c2fcf7.js:1
loadLocaleInVideoJS @ 24-es2015.42ef4036ccaeebdf6e15.js:1
(anonymous) @ 24-es2015.42ef4036ccaeebdf6e15.js:1
s @ main-es2015.01e83f0516ea82556b2e.js:3
invoke @ polyfills-es2015.975f8cb1db6890c2fcf7.js:1
run @ polyfills-es2015.975f8cb1db6890c2fcf7.js:1
(anonymous) @ polyfills-es2015.975f8cb1db6890c2fcf7.js:1
invokeTask @ polyfills-es2015.975f8cb1db6890c2fcf7.js:1
runTask @ polyfills-es2015.975f8cb1db6890c2fcf7.js:1
v @ polyfills-es2015.975f8cb1db6890c2fcf7.js:1
Promise.then (async)
b @ polyfills-es2015.975f8cb1db6890c2fcf7.js:1
scheduleTask @ polyfills-es2015.975f8cb1db6890c2fcf7.js:1
scheduleTask @ polyfills-es2015.975f8cb1db6890c2fcf7.js:1
scheduleMicroTask @ polyfills-es2015.975f8cb1db6890c2fcf7.js:1
O @ polyfills-es2015.975f8cb1db6890c2fcf7.js:1
k @ polyfills-es2015.975f8cb1db6890c2fcf7.js:1
(anonymous) @ polyfills-es2015.975f8cb1db6890c2fcf7.js:1
r @ runtime-es2015.ef7eb9b5caf29e63e78c.js:1
(anonymous) @ 32-es2015.b7805a86685f2e116120.js:1
24-es2015.42ef4036ccaeebdf6e15.js:1 Fallback to webtorrent.
7-es2015.19889028d3049aff782d.js:1 WebSocket connection to 'wss://peervideo.ru/tracker/socket' failed: WebSocket is closed before the connection is established.
_destroy @ 7-es2015.19889028d3049aff782d.js:1
destroy @ 7-es2015.19889028d3049aff782d.js:1
i @ 7-es2015.19889028d3049aff782d.js:1
destroy @ 7-es2015.19889028d3049aff782d.js:1
(anonymous) @ 7-es2015.19889028d3049aff782d.js:1
(anonymous) @ 7-es2015.19889028d3049aff782d.js:1
e.exports @ 7-es2015.19889028d3049aff782d.js:1
destroy @ 7-es2015.19889028d3049aff782d.js:1
destroy @ 13-es2015.c234bbde3f1e48ff9751.js:1
destroy @ 13-es2015.c234bbde3f1e48ff9751.js:1
destroy @ 13-es2015.c234bbde3f1e48ff9751.js:1
destroy @ 13-es2015.c234bbde3f1e48ff9751.js:1
(anonymous) @ 13-es2015.c234bbde3f1e48ff9751.js:1
d.emit @ 32-es2015.b7805a86685f2e116120.js:1
i.trigger @ 32-es2015.b7805a86685f2e116120.js:1
a.destroy @ 32-es2015.b7805a86685f2e116120.js:1
dispose @ 32-es2015.b7805a86685f2e116120.js:1
i.dispatcher.i.dispatcher @ 24-es2015.42ef4036ccaeebdf6e15.js:1
Ct @ 24-es2015.42ef4036ccaeebdf6e15.js:1
trigger @ 24-es2015.42ef4036ccaeebdf6e15.js:1
n.dispose @ 24-es2015.42ef4036ccaeebdf6e15.js:1
(anonymous) @ 24-es2015.42ef4036ccaeebdf6e15.js:1
(anonymous) @ main-es2015.01e83f0516ea82556b2e.js:3
I @ polyfills-es2015.975f8cb1db6890c2fcf7.js:1
s @ main-es2015.01e83f0516ea82556b2e.js:3
maybeFallbackToWebTorrent @ 24-es2015.42ef4036ccaeebdf6e15.js:1
(anonymous) @ 24-es2015.42ef4036ccaeebdf6e15.js:1
i @ 24-es2015.42ef4036ccaeebdf6e15.js:1
i.dispatcher.i.dispatcher @ 24-es2015.42ef4036ccaeebdf6e15.js:1
Ct @ 24-es2015.42ef4036ccaeebdf6e15.js:1
trigger @ 24-es2015.42ef4036ccaeebdf6e15.js:1
n.error @ 24-es2015.42ef4036ccaeebdf6e15.js:1
n.handleTechError_ @ 24-es2015.42ef4036ccaeebdf6e15.js:1
i.dispatcher.i.dispatcher @ 24-es2015.42ef4036ccaeebdf6e15.js:1
invokeTask @ polyfills-es2015.975f8cb1db6890c2fcf7.js:1
runTask @ polyfills-es2015.975f8cb1db6890c2fcf7.js:1
invokeTask @ polyfills-es2015.975f8cb1db6890c2fcf7.js:1
l @ polyfills-es2015.975f8cb1db6890c2fcf7.js:1
p @ polyfills-es2015.975f8cb1db6890c2fcf7.js:1
error (async)
x @ polyfills-es2015.975f8cb1db6890c2fcf7.js:1
scheduleTask @ polyfills-es2015.975f8cb1db6890c2fcf7.js:1
scheduleTask @ polyfills-es2015.975f8cb1db6890c2fcf7.js:1
scheduleEventTask @ polyfills-es2015.975f8cb1db6890c2fcf7.js:1
(anonymous) @ polyfills-es2015.975f8cb1db6890c2fcf7.js:1
yt @ 24-es2015.42ef4036ccaeebdf6e15.js:1
Rt @ 24-es2015.42ef4036ccaeebdf6e15.js:1
on @ 24-es2015.42ef4036ccaeebdf6e15.js:1
Rt @ 24-es2015.42ef4036ccaeebdf6e15.js:1
on @ 24-es2015.42ef4036ccaeebdf6e15.js:1
n.loadTech_ @ 24-es2015.42ef4036ccaeebdf6e15.js:1
e @ 24-es2015.42ef4036ccaeebdf6e15.js:1
e.addChild @ 24-es2015.42ef4036ccaeebdf6e15.js:1
(anonymous) @ 24-es2015.42ef4036ccaeebdf6e15.js:1
e.initChildren @ 24-es2015.42ef4036ccaeebdf6e15.js:1
e @ 24-es2015.42ef4036ccaeebdf6e15.js:1
io @ 24-es2015.42ef4036ccaeebdf6e15.js:1
(anonymous) @ 24-es2015.42ef4036ccaeebdf6e15.js:1
I @ polyfills-es2015.975f8cb1db6890c2fcf7.js:1
(anonymous) @ 24-es2015.42ef4036ccaeebdf6e15.js:1
s @ main-es2015.01e83f0516ea82556b2e.js:3
invoke @ polyfills-es2015.975f8cb1db6890c2fcf7.js:1
run @ polyfills-es2015.975f8cb1db6890c2fcf7.js:1
(anonymous) @ polyfills-es2015.975f8cb1db6890c2fcf7.js:1
invokeTask @ polyfills-es2015.975f8cb1db6890c2fcf7.js:1
runTask @ polyfills-es2015.975f8cb1db6890c2fcf7.js:1
v @ polyfills-es2015.975f8cb1db6890c2fcf7.js:1
Promise.then (async)
b @ polyfills-es2015.975f8cb1db6890c2fcf7.js:1
scheduleTask @ polyfills-es2015.975f8cb1db6890c2fcf7.js:1
scheduleTask @ polyfills-es2015.975f8cb1db6890c2fcf7.js:1
scheduleMicroTask @ polyfills-es2015.975f8cb1db6890c2fcf7.js:1
O @ polyfills-es2015.975f8cb1db6890c2fcf7.js:1
k @ polyfills-es2015.975f8cb1db6890c2fcf7.js:1
(anonymous) @ polyfills-es2015.975f8cb1db6890c2fcf7.js:1
Promise.then (async)
(anonymous) @ polyfills-es2015.975f8cb1db6890c2fcf7.js:1
I @ polyfills-es2015.975f8cb1db6890c2fcf7.js:1
D.t.then @ polyfills-es2015.975f8cb1db6890c2fcf7.js:1
k @ polyfills-es2015.975f8cb1db6890c2fcf7.js:1
(anonymous) @ polyfills-es2015.975f8cb1db6890c2fcf7.js:1
invokeTask @ polyfills-es2015.975f8cb1db6890c2fcf7.js:1
runTask @ polyfills-es2015.975f8cb1db6890c2fcf7.js:1
v @ polyfills-es2015.975f8cb1db6890c2fcf7.js:1
Promise.then (async)
b @ polyfills-es2015.975f8cb1db6890c2fcf7.js:1
scheduleTask @ polyfills-es2015.975f8cb1db6890c2fcf7.js:1
scheduleTask @ polyfills-es2015.975f8cb1db6890c2fcf7.js:1
scheduleMicroTask @ polyfills-es2015.975f8cb1db6890c2fcf7.js:1
O @ polyfills-es2015.975f8cb1db6890c2fcf7.js:1
k @ polyfills-es2015.975f8cb1db6890c2fcf7.js:1
(anonymous) @ polyfills-es2015.975f8cb1db6890c2fcf7.js:1
Promise.then (async)
(anonymous) @ polyfills-es2015.975f8cb1db6890c2fcf7.js:1
I @ polyfills-es2015.975f8cb1db6890c2fcf7.js:1
D.t.then @ polyfills-es2015.975f8cb1db6890c2fcf7.js:1
loadLocaleInVideoJS @ 24-es2015.42ef4036ccaeebdf6e15.js:1
(anonymous) @ 24-es2015.42ef4036ccaeebdf6e15.js:1
s @ main-es2015.01e83f0516ea82556b2e.js:3
invoke @ polyfills-es2015.975f8cb1db6890c2fcf7.js:1
run @ polyfills-es2015.975f8cb1db6890c2fcf7.js:1
(anonymous) @ polyfills-es2015.975f8cb1db6890c2fcf7.js:1
invokeTask @ polyfills-es2015.975f8cb1db6890c2fcf7.js:1
runTask @ polyfills-es2015.975f8cb1db6890c2fcf7.js:1
v @ polyfills-es2015.975f8cb1db6890c2fcf7.js:1
Promise.then (async)
b @ polyfills-es2015.975f8cb1db6890c2fcf7.js:1
scheduleTask @ polyfills-es2015.975f8cb1db6890c2fcf7.js:1
scheduleTask @ polyfills-es2015.975f8cb1db6890c2fcf7.js:1
scheduleMicroTask @ polyfills-es2015.975f8cb1db6890c2fcf7.js:1
O @ polyfills-es2015.975f8cb1db6890c2fcf7.js:1
k @ polyfills-es2015.975f8cb1db6890c2fcf7.js:1
(anonymous) @ polyfills-es2015.975f8cb1db6890c2fcf7.js:1
r @ runtime-es2015.ef7eb9b5caf29e63e78c.js:1
(anonymous) @ 32-es2015.b7805a86685f2e116120.js:1
Show 9 more frames
polyfills-es2015.975f8cb1db6890c2fcf7.js:1 Uncaught TypeError: Cannot read property 'code' of null
    at HTMLVideoElement.<anonymous> (32-es2015.b7805a86685f2e116120.js:1)
    at u.invokeTask (polyfills-es2015.975f8cb1db6890c2fcf7.js:1)
    at a.runTask (polyfills-es2015.975f8cb1db6890c2fcf7.js:1)
    at f.invokeTask [as invoke] (polyfills-es2015.975f8cb1db6890c2fcf7.js:1)
    at l (polyfills-es2015.975f8cb1db6890c2fcf7.js:1)
    at HTMLVideoElement.p (polyfills-es2015.975f8cb1db6890c2fcf7.js:1)
(anonymous) @ 32-es2015.b7805a86685f2e116120.js:1
invokeTask @ polyfills-es2015.975f8cb1db6890c2fcf7.js:1
runTask @ polyfills-es2015.975f8cb1db6890c2fcf7.js:1
invokeTask @ polyfills-es2015.975f8cb1db6890c2fcf7.js:1
l @ polyfills-es2015.975f8cb1db6890c2fcf7.js:1
p @ polyfills-es2015.975f8cb1db6890c2fcf7.js:1
error (async)
x @ polyfills-es2015.975f8cb1db6890c2fcf7.js:1
scheduleTask @ polyfills-es2015.975f8cb1db6890c2fcf7.js:1
scheduleTask @ polyfills-es2015.975f8cb1db6890c2fcf7.js:1
scheduleEventTask @ polyfills-es2015.975f8cb1db6890c2fcf7.js:1
(anonymous) @ polyfills-es2015.975f8cb1db6890c2fcf7.js:1
yt @ 24-es2015.42ef4036ccaeebdf6e15.js:1
Rt @ 24-es2015.42ef4036ccaeebdf6e15.js:1
on @ 24-es2015.42ef4036ccaeebdf6e15.js:1
Rt @ 24-es2015.42ef4036ccaeebdf6e15.js:1
on @ 24-es2015.42ef4036ccaeebdf6e15.js:1
n.loadTech_ @ 24-es2015.42ef4036ccaeebdf6e15.js:1
e @ 24-es2015.42ef4036ccaeebdf6e15.js:1
e.addChild @ 24-es2015.42ef4036ccaeebdf6e15.js:1
(anonymous) @ 24-es2015.42ef4036ccaeebdf6e15.js:1
e.initChildren @ 24-es2015.42ef4036ccaeebdf6e15.js:1
e @ 24-es2015.42ef4036ccaeebdf6e15.js:1
io @ 24-es2015.42ef4036ccaeebdf6e15.js:1
(anonymous) @ 24-es2015.42ef4036ccaeebdf6e15.js:1
I @ polyfills-es2015.975f8cb1db6890c2fcf7.js:1
(anonymous) @ 24-es2015.42ef4036ccaeebdf6e15.js:1
s @ main-es2015.01e83f0516ea82556b2e.js:3
invoke @ polyfills-es2015.975f8cb1db6890c2fcf7.js:1
run @ polyfills-es2015.975f8cb1db6890c2fcf7.js:1
(anonymous) @ polyfills-es2015.975f8cb1db6890c2fcf7.js:1
invokeTask @ polyfills-es2015.975f8cb1db6890c2fcf7.js:1
runTask @ polyfills-es2015.975f8cb1db6890c2fcf7.js:1
v @ polyfills-es2015.975f8cb1db6890c2fcf7.js:1
Promise.then (async)
b @ polyfills-es2015.975f8cb1db6890c2fcf7.js:1
scheduleTask @ polyfills-es2015.975f8cb1db6890c2fcf7.js:1
scheduleTask @ polyfills-es2015.975f8cb1db6890c2fcf7.js:1
scheduleMicroTask @ polyfills-es2015.975f8cb1db6890c2fcf7.js:1
O @ polyfills-es2015.975f8cb1db6890c2fcf7.js:1
k @ polyfills-es2015.975f8cb1db6890c2fcf7.js:1
(anonymous) @ polyfills-es2015.975f8cb1db6890c2fcf7.js:1
Promise.then (async)
(anonymous) @ polyfills-es2015.975f8cb1db6890c2fcf7.js:1
I @ polyfills-es2015.975f8cb1db6890c2fcf7.js:1
D.t.then @ polyfills-es2015.975f8cb1db6890c2fcf7.js:1
k @ polyfills-es2015.975f8cb1db6890c2fcf7.js:1
(anonymous) @ polyfills-es2015.975f8cb1db6890c2fcf7.js:1
invokeTask @ polyfills-es2015.975f8cb1db6890c2fcf7.js:1
runTask @ polyfills-es2015.975f8cb1db6890c2fcf7.js:1
v @ polyfills-es2015.975f8cb1db6890c2fcf7.js:1
Promise.then (async)
b @ polyfills-es2015.975f8cb1db6890c2fcf7.js:1
scheduleTask @ polyfills-es2015.975f8cb1db6890c2fcf7.js:1
scheduleTask @ polyfills-es2015.975f8cb1db6890c2fcf7.js:1
scheduleMicroTask @ polyfills-es2015.975f8cb1db6890c2fcf7.js:1
O @ polyfills-es2015.975f8cb1db6890c2fcf7.js:1
k @ polyfills-es2015.975f8cb1db6890c2fcf7.js:1
(anonymous) @ polyfills-es2015.975f8cb1db6890c2fcf7.js:1
Promise.then (async)
(anonymous) @ polyfills-es2015.975f8cb1db6890c2fcf7.js:1
I @ polyfills-es2015.975f8cb1db6890c2fcf7.js:1
D.t.then @ polyfills-es2015.975f8cb1db6890c2fcf7.js:1
loadLocaleInVideoJS @ 24-es2015.42ef4036ccaeebdf6e15.js:1
(anonymous) @ 24-es2015.42ef4036ccaeebdf6e15.js:1
s @ main-es2015.01e83f0516ea82556b2e.js:3
invoke @ polyfills-es2015.975f8cb1db6890c2fcf7.js:1
run @ polyfills-es2015.975f8cb1db6890c2fcf7.js:1
(anonymous) @ polyfills-es2015.975f8cb1db6890c2fcf7.js:1
invokeTask @ polyfills-es2015.975f8cb1db6890c2fcf7.js:1
runTask @ polyfills-es2015.975f8cb1db6890c2fcf7.js:1
v @ polyfills-es2015.975f8cb1db6890c2fcf7.js:1
Promise.then (async)
b @ polyfills-es2015.975f8cb1db6890c2fcf7.js:1
scheduleTask @ polyfills-es2015.975f8cb1db6890c2fcf7.js:1
scheduleTask @ polyfills-es2015.975f8cb1db6890c2fcf7.js:1
scheduleMicroTask @ polyfills-es2015.975f8cb1db6890c2fcf7.js:1
O @ polyfills-es2015.975f8cb1db6890c2fcf7.js:1
k @ polyfills-es2015.975f8cb1db6890c2fcf7.js:1
(anonymous) @ polyfills-es2015.975f8cb1db6890c2fcf7.js:1
r @ runtime-es2015.ef7eb9b5caf29e63e78c.js:1
(anonymous) @ 32-es2015.b7805a86685f2e116120.js:1
polyfills-es2015.975f8cb1db6890c2fcf7.js:1 Uncaught TypeError: Cannot read property 'classList' of undefined
    at video-watch-client-plugin-out.js:1
    at u.invokeTask (polyfills-es2015.975f8cb1db6890c2fcf7.js:1)
    at a.runTask (polyfills-es2015.975f8cb1db6890c2fcf7.js:1)
    at invokeTask (polyfills-es2015.975f8cb1db6890c2fcf7.js:1)
    at invoke (polyfills-es2015.975f8cb1db6890c2fcf7.js:1)
    at n.args.<computed> (polyfills-es2015.975f8cb1db6890c2fcf7.js:1)
```

**Comment by Chocobozzz** [comment]
Please fill the template: what is your ffmpeg version?

**Comment by Alterak** [comment]
> Please fill the template: what is your ffmpeg version?

Sorry, I completely forgot to indicate. I have updated the theme.

**Comment by Chocobozzz** [comment]
You reproduce this issue with the same file every time you upload it?

**Comment by Alterak** [comment]
> You reproduce this issue with the same file every time you upload it?

Now I specifically tried to download the same file again. The error is repeated.
https://peervideo.ru/videos/watch/590432b0-0f71-461e-accb-ae06a2a6bcd7

**Comment by Chocobozzz** [comment]
Okay thanks, should be fixed by https://github.com/Chocobozzz/PeerTube/commit/d8ba4921191ee2b3dda976c3c3d5cf4b9dd17619
