### ISSUE TITLE
Errors caused by linked instances: \"@id\" value must a string.

### ISSUE THREAD

**Issue by c0xc** [Chocobozzz/PeerTube#3683]
**Describe the current behavior**

Sometimes, linked instances appear to misbehave, causing errors. One of them is:

```error: Cannot execute job 46770 in queue activitypub-http-unicast. {
  "payload": {
    "uri": ".../accounts/peertube/inbox",
    "signatureActorId": 1,
    "body": {
      "type": "Accept",
      "id": ".../accepts/follows/46/1",
      "actor": ".../accounts/peertube",
      "object": {
        "type": "Follow",
        "id": null,
        "actor": ".../accounts/peertube",
        "object": ".../accounts/peertube"
      }
    }
  },
  "err": {
    "stack": "jsonld.SyntaxError: Invalid JSON-LD syntax; \"@id\" value must a string.\n    at _expandObject (.../node_modules/jsonld/lib/expand.js:481:17)\n    at process._tickCallback (internal/process/next_tick.js:68:7)",
    "message": "Invalid JSON-LD syntax; \"@id\" value must a string.",
    "name": "jsonld.SyntaxError",
    "details": {
      "code": "invalid @id value",
      "value": null
    }
  }
}
```

It sounds like a linked instance (running version 2.4.0) is sending bad json data.

Another one:
```
    "message": "Validation error: \"\" is not a valid description.",
    "name": "SequelizeValidationError",
    "errors": [
      {
        "message": "\"\" is not a valid description.",
        "type": "Validation error",
        "path": "description",
        "value": "",
        "origin": "FUNCTION",
        "instance": {
          "id": null,
          "name": "...",
          "description": "",
          "actorId": 44,
          "updatedAt": "2020-12-09T04:07:19.181Z",
          "createdAt": "2020-12-09T04:07:19.181Z"
        },
        "validatorKey": "isAccountDescription",
        "validatorName": null,
        "validatorArgs": [],
        "original": {
          "stack": "Error: \"\" is not a valid description.\n    at Object.throwIfNotValid (/var/www/peertube/versions/peertube-v2.4.0/dist/server/models/utils.js:84:15)\n    at AccountModel.tslib_1.__decorate.sequelize_typescript_1.Is.value (/var/www/peertube/versions/peertube-v2.4.0/dist/server/models/account/account.js:232:70)\n    at Promise.try (/var/www/peertube/versions/peertube-v2.4.0/node_modules/sequelize/lib/instance-validator.js:269:28)\n    at tryCatcher (/var/www/peertube/versions/peertube-v2.4.0/node_modules/bluebird/js/release/util.js:16:23)\n    at Function.Promise.attempt.Promise.try (/var/www/peertube/versions/peertube-v2.4.0/node_modules/bluebird/js/release/method.js:39:29)\n    at InstanceValidator._invokeCustomValidator (/var/www/peertube/versions/peertube-v2.4.0/node_modules/sequelize/lib/instance-validator.js:269:11)\n    at _.forIn (/var/www/peertube/versions/peertube-v2.4.0/node_modules/sequelize/lib/instance-validator.js:208:30)\n    at /var/www/peertube/versions/peertube-v2.4.0/node_modules/lodash/lodash.js:4925:15\n    at Function.forIn (/var/www/peertube/versions/peertube-v2.4.0/node_modules/lodash/lodash.js:12976:11)\n    at InstanceValidator._singleAttrValidate (/var/www/peertube/versions/peertube-v2.4.0/node_modules/sequelize/lib/instance-validator.js:193:7)\n    at _.forIn (/var/www/peertube/versions/peertube-v2.4.0/node_modules/sequelize/lib/instance-validator.js:142:30)\n    at /var/www/peertube/versions/peertube-v2.4.0/node_modules/lodash/lodash.js:4925:15\n    at Function.forIn (/var/www/peertube/versions/peertube-v2.4.0/node_modules/lodash/lodash.js:12976:11)\n    at InstanceValidator._perAttributeValidators (/var/www/peertube/versions/peertube-v2.4.0/node_modules/sequelize/lib/instance-validator.js:125:7)\n    at InstanceValidator._validate (/var/www/peertube/versions/peertube-v2.4.0/node_modules/sequelize/lib/instance-validator.js:70:12)\n    at runHooks.then (/var/www/peertube/versions/peertube-v2.4.0/node_modules/sequelize/lib/instance-validator.js:107:14)\n    at tryCatcher (/var/www/peertube/versions/peertube-v2.4.0/node_modules/bluebird/js/release/util.js:16:23)\n    at Promise._settlePromiseFromHandler (/var/www/peertube/versions/peertube-v2.4.0/node_modules/bluebird/js/release/promise.js:547:31)\n    at Promise._settlePromise (/var/www/peertube/versions/peertube-v2.4.0/node_modules/bluebird/js/release/promise.js:604:18)\n    at Promise._settlePromise0 (/var/www/peertube/versions/peertube-v2.4.0/node_modules/bluebird/js/release/promise.js:649:10)\n    at Promise._settlePromises (/var/www/peertube/versions/peertube-v2.4.0/node_modules/bluebird/js/release/promise.js:729:18)\n    at _drainQueueStep (/var/www/peertube/versions/peertube-v2.4.0/node_modules/bluebird/js/release/async.js:93:12)\n    at _drainQueue (/var/www/peertube/versions/peertube-v2.4.0/node_modules/bluebird/js/release/async.js:86:9)\n    at Async._drainQueues (/var/www/peertube/versions/peertube-v2.4.0/node_modules/bluebird/js/release/async.js:102:5)\n    at Immediate.Async.drainQueues [as _onImmediate] (/var/www/peertube/versions/peertube-v2.4.0/node_modules/bluebird/js/release/async.js:15:14)\n    at runCallback (timers.js:705:18)\n    at tryOnImmediate (timers.js:676:5)\n    at processImmediate (timers.js:658:5)",
          "message": "\"\" is not a valid description."
```

It's unclear how serious it is but it sounds like some user input wasn't validated before making it into the database of the other instance and now into that of this instance (unless this is really just an empty description field in which case I wonder why there's such a constraint on it).

If this was a "warning" message after bad data has been received from another instance, I wouldn't care. But being logged as "error", I assume that something in the inter-instance communication isn't working.

**Steps to reproduce:**

Don't know.

**Describe the expected behavior**

If another instance is sending bad data which is ignored because it doesn't break anything, it might be an idea to log it as a warning to make that event visible in the logs but make it obvious that it doesn't impact the functionality.

**Additional information**

* PeerTube instance:
  * version: 2.4.0
  * NodeJS version: v10.21.0
  * Ffmpeg version: 4.3.1

**Comment by Chocobozzz** [comment]
Hello,

Please upgrade to peertube v3 to see if there are still these issues
