### ISSUE TITLE
transcoding error:  SequelizeUniqueConstraintError: la valeur d'une clé dupliquée rompt la contrainte unique 

### ISSUE THREAD

**Issue by pprw** [Chocobozzz/PeerTube#3714]
The transcode CLI command gives me the following error when trying to (re)transcode a HLS video (to HLS). I don't have it when launching the same command to a older and webtorrent encoded video. I am running peertube 3.0.1.
```
error[07/02/2021 à 17:43:18] Cannot execute job 1304 in queue video-transcoding.

{
  "payload": {
    "type": "optimize",
    "videoUUID": "94729d7a-e9e3-4a25-97ef-0683f3581feb",
    "isNewVideo": false
  },
  "err": {
    "stack": "SequelizeUniqueConstraintError: la valeur d'une clé dupliquée rompt la contrainte unique « video_file_video_streaming_playlist_id_resolution_fps »\n    at Query.formatError (/var/www/peertube/versions/peertube-v3.0.1/node_modules/sequelize/lib/dialects/postgres/query.js:347:16)\n    at Query.run (/var/www/peertube/versions/peertube-v3.0.1/node_modules/sequelize/lib/dialects/postgres/query.js:87:18)\n    at process._tickCallback (internal/process/next_tick.js:68:7)",
    "message": "la valeur d'une clé dupliquée rompt la contrainte unique « video_file_video_streaming_playlist_id_resolution_fps »",
    "name": "SequelizeUniqueConstraintError",
    "errors": {},
    "parent": {
      "stack": "error: la valeur d'une clé dupliquée rompt la contrainte unique « video_file_video_streaming_playlist_id_resolution_fps »\n    at Parser.parseErrorMessage (/var/www/peertube/versions/peertube-v3.0.1/node_modules/pg-protocol/dist/parser.js:278:15)\n    at Parser.handlePacket (/var/www/peertube/versions/peertube-v3.0.1/node_modules/pg-protocol/dist/parser.js:126:29)\n    at Parser.parse (/var/www/peertube/versions/peertube-v3.0.1/node_modules/pg-protocol/dist/parser.js:39:38)\n    at Socket.stream.on (/var/www/peertube/versions/peertube-v3.0.1/node_modules/pg-protocol/dist/index.js:10:42)\n    at Socket.emit (events.js:198:13)\n    at addChunk (_stream_readable.js:288:12)\n    at readableAddChunk (_stream_readable.js:269:11)\n    at Socket.Readable.push (_stream_readable.js:224:10)\n    at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)",
      "message": "la valeur d'une clé dupliquée rompt la contrainte unique « video_file_video_streaming_playlist_id_resolution_fps »",
      "length": 349,
      "name": "error",
      "severity": "ERREUR",
      "code": "23505",
      "detail": "La clé « (\"videoStreamingPlaylistId\", resolution, fps)=(194, 1080, 25) » existe déjà.",
      "schema": "public",
      "table": "videoFile",
      "constraint": "video_file_video_streaming_playlist_id_resolution_fps",
      "file": "nbtinsert.c",
      "line": "534",
      "routine": "_bt_check_unique",
      "sql": "UPDATE \"videoFile\" SET \"size\"=$1,\"infoHash\"=$2,\"videoStreamingPlaylistId\"=$3,\"metadata\"=$4,\"updatedAt\"=$5 WHERE \"id\" = $6",
      "parameters": [
        4693830,
        "b3d870ab2a9d768806a816807fd4f4b37f60acda",
        194,
        "{\"chapters\":[],\"format\":{\"nb_streams\":2,\"nb_programs\":0,\"format_name\":\"mov,mp4,m4a,3gp,3g2,mj2\",\"format_long_name\":\"QuickTime / MOV\",\"start_time\":0,\"duration\":294.88,\"size\":4693830,\"bit_rate\":127342,\"probe_score\":100,\"tags\":{\"major_brand\":\"isom\",\"minor_version\":\"512\",\"compatible_brands\":\"isomiso2avc1mp41\",\"encoder\":\"Lavf58.20.100\"}},\"streams\":[{\"index\":0,\"codec_name\":\"h264\",\"codec_long_name\":\"H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10\",\"profile\":\"High\",\"codec_type\":\"video\",\"codec_time_base\":\"1/50\",\"codec_tag_string\":\"avc1\",\"codec_tag\":\"0x31637661\",\"width\":1920,\"height\":1080,\"coded_width\":1920,\"coded_height\":1088,\"has_b_frames\":0,\"sample_aspect_ratio\":\"N/A\",\"display_aspect_ratio\":\"N/A\",\"pix_fmt\":\"yuv420p\",\"level\":50,\"color_range\":\"unknown\",\"color_space\":\"unknown\",\"color_transfer\":\"unknown\",\"color_primaries\":\"unknown\",\"chroma_location\":\"left\",\"field_order\":\"unknown\",\"timecode\":\"N/A\",\"refs\":1,\"is_avc\":\"true\",\"nal_length_size\":4,\"id\":\"N/A\",\"r_frame_rate\":\"25/1\",\"avg_frame_rate\":\"25/1\",\"time_base\":\"1/30000\",\"start_pts\":0,\"start_time\":0,\"duration_ts\":8846400,\"duration\":294.88,\"bit_rate\":69605,\"max_bit_rate\":\"N/A\",\"bits_per_raw_sample\":8,\"nb_frames\":7372,\"nb_read_frames\":\"N/A\",\"nb_read_packets\":\"N/A\",\"tags\":{\"language\":\"und\",\"handler_name\":\"VideoHandler\"},\"disposition\":{\"default\":1,\"dub\":0,\"original\":0,\"comment\":0,\"lyrics\":0,\"karaoke\":0,\"forced\":0,\"hearing_impaired\":0,\"visual_impaired\":0,\"clean_effects\":0,\"attached_pic\":0,\"timed_thumbnails\":0}},{\"index\":1,\"codec_name\":\"aac\",\"codec_long_name\":\"AAC (Advanced Audio Coding)\",\"profile\":\"LC\",\"codec_type\":\"audio\",\"codec_time_base\":\"1/32000\",\"codec_tag_string\":\"mp4a\",\"codec_tag\":\"0x6134706d\",\"sample_fmt\":\"fltp\",\"sample_rate\":32000,\"channels\":1,\"channel_layout\":\"mono\",\"bits_per_sample\":0,\"id\":\"N/A\",\"r_frame_rate\":\"0/0\",\"avg_frame_rate\":\"0/0\",\"time_base\":\"1/32000\",\"start_pts\":0,\"start_time\":0,\"duration_ts\":9431040,\"duration\":294.72,\"bit_rate\":53129,\"max_bit_rate\":53388,\"bits_per_raw_sample\":\"N/A\",\"nb_frames\":9210,\"nb_read_frames\":\"N/A\",\"nb_read_packets\":\"N/A\",\"tags\":{\"language\":\"und\",\"handler_name\":\"SoundHandler\"},\"disposition\":{\"default\":1,\"dub\":0,\"original\":0,\"comment\":0,\"lyrics\":0,\"karaoke\":0,\"forced\":0,\"hearing_impaired\":0,\"visual_impaired\":0,\"clean_effects\":0,\"attached_pic\":0,\"timed_thumbnails\":0}}]}",
        "2021-02-07 16:43:18.834 +00:00",
        1023
      ]
    },
    "sql": "UPDATE \"videoFile\" SET \"size\"=$1,\"infoHash\"=$2,\"videoStreamingPlaylistId\"=$3,\"metadata\"=$4,\"updatedAt\"=$5 WHERE \"id\" = $6"
  }
}
```

**Comment by Chocobozzz** [comment]
Hi,

Could you go into the DB and do:

```
SELECT * FROM "videoFile" WHERE "videoStreamingPlaylistId" = 194 AND resolution = 1080 AND fps = 25
```

**Comment by Chocobozzz** [comment]
Should be fixed by https://github.com/Chocobozzz/PeerTube/commit/20eb3a5be018dc207253a54bac2e971cbf2c25ce
