### ISSUE TITLE
SequelizeDatabaseError: syntaxe en entrée invalide pour le type uuid

### ISSUE THREAD

**Issue by pprw** [Chocobozzz/PeerTube#3715]
Importing a new file for an existing video generate this error on my peertube instance (3.0.1)

```

$ sudo -u peertube NODE_CONFIG_DIR=/var/www/peertube/config NODE_ENV=production npm run create-import-video-file-job -- -v "9673a7f-8e7b-46fa-ab07-fd7275f6cd8f" -i /var/www/peertube/BORITCHEV_DinG-presentation.mp4


> peertube@3.0.1 create-import-video-file-job /var/www/peertube/versions/peertube-v3.0.1
> node ./dist/scripts/create-import-video-file-job.js "-v" "9673a7f-8e7b-46fa-ab07-fd7275f6cd8f" "-i" "/var/www/peertube/presentation.mp4"

{ SequelizeDatabaseError: syntaxe en entrée invalide pour le type uuid : « 9673a7f-8e7b-46fa-ab07-fd7275f6cd8f »
    at Query.formatError (/var/www/peertube/versions/peertube-v3.0.1/node_modules/sequelize/lib/dialects/postgres/query.js:386:16)
    at Query.run (/var/www/peertube/versions/peertube-v3.0.1/node_modules/sequelize/lib/dialects/postgres/query.js:87:18)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  name: 'SequelizeDatabaseError',
  parent:
   { error: syntaxe en entrée invalide pour le type uuid : « 9673a7f-8e7b-46fa-ab07-fd7275f6cd8f »
       at Parser.parseErrorMessage (/var/www/peertube/versions/peertube-v3.0.1/node_modules/pg-protocol/dist/parser.js:278:15)
       at Parser.handlePacket (/var/www/peertube/versions/peertube-v3.0.1/node_modules/pg-protocol/dist/parser.js:126:29)
       at Parser.parse (/var/www/peertube/versions/peertube-v3.0.1/node_modules/pg-protocol/dist/parser.js:39:38)
       at Socket.stream.on (/var/www/peertube/versions/peertube-v3.0.1/node_modules/pg-protocol/dist/index.js:10:42)
       at Socket.emit (events.js:198:13)
       at addChunk (_stream_readable.js:288:12)
       at readableAddChunk (_stream_readable.js:269:11)
       at Socket.Readable.push (_stream_readable.js:224:10)
       at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
     length: 153,
     name: 'error',
     severity: 'ERREUR',
     code: '22P02',
     detail: undefined,
     hint: undefined,
     position: '1308',
     internalPosition: undefined,
     internalQuery: undefined,
     where: undefined,
     schema: undefined,
     table: undefined,
     column: undefined,
     dataType: undefined,
     constraint: undefined,
     file: 'uuid.c',
     line: '137',
     routine: 'string_to_uuid',
     sql:
      'SELECT "VideoModel".*, "Thumbnails"."id" AS "Thumbnails.id", "Thumbnails"."filename" AS "Thumbnails.filename", "Thumbnails"."height" AS "Thumbnails.height", "Thumbnails"."width" AS "Thumbnails.width", "Thumbnails"."type" AS "Thumbnails.type", "Thumbnails"."fileUrl" AS "Thumbnails.fileUrl", "Thumbnails"."automaticallyGenerated" AS "Thumbnails.automaticallyGenerated", "Thumbnails"."videoId" AS "Thumbnails.videoId", "Thumbnails"."videoPlaylistId" AS "Thumbnails.videoPlaylistId", "Thumbnails"."createdAt" AS "Thumbnails.createdAt", "Thumbnails"."updatedAt" AS "Thumbnails.updatedAt" FROM (SELECT "VideoModel"."id", "VideoModel"."uuid", "VideoModel"."name", "VideoModel"."category", "VideoModel"."licence", "VideoModel"."language", "VideoModel"."privacy", "VideoModel"."nsfw", "VideoModel"."description", "VideoModel"."support", "VideoModel"."duration", "VideoModel"."views", "VideoModel"."likes", "VideoModel"."dislikes", "VideoModel"."remote", "VideoModel"."isLive", "VideoModel"."url", "VideoModel"."commentsEnabled", "VideoModel"."downloadEnabled", "VideoModel"."waitTranscoding", "VideoModel"."state", "VideoModel"."publishedAt", "VideoModel"."originallyPublishedAt", "VideoModel"."channelId", "VideoModel"."createdAt", "VideoModel"."updatedAt" FROM "video" AS "VideoModel" WHERE "VideoModel"."uuid" = \'9673a7f-8e7b-46fa-ab07-fd7275f6cd8f\' LIMIT 1) AS "VideoModel" LEFT OUTER JOIN "thumbnail" AS "Thumbnails" ON "VideoModel"."id" = "Thumbnails"."videoId";',
     parameters: undefined },
  original:
   { error: syntaxe en entrée invalide pour le type uuid : « 9673a7f-8e7b-46fa-ab07-fd7275f6cd8f »
       at Parser.parseErrorMessage (/var/www/peertube/versions/peertube-v3.0.1/node_modules/pg-protocol/dist/parser.js:278:15)
       at Parser.handlePacket (/var/www/peertube/versions/peertube-v3.0.1/node_modules/pg-protocol/dist/parser.js:126:29)
       at Parser.parse (/var/www/peertube/versions/peertube-v3.0.1/node_modules/pg-protocol/dist/parser.js:39:38)
       at Socket.stream.on (/var/www/peertube/versions/peertube-v3.0.1/node_modules/pg-protocol/dist/index.js:10:42)
       at Socket.emit (events.js:198:13)
       at addChunk (_stream_readable.js:288:12)
       at readableAddChunk (_stream_readable.js:269:11)
       at Socket.Readable.push (_stream_readable.js:224:10)
       at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
     length: 153,
     name: 'error',
     severity: 'ERREUR',
     code: '22P02',
     detail: undefined,
     hint: undefined,
     position: '1308',
     internalPosition: undefined,
     internalQuery: undefined,
     where: undefined,
     schema: undefined,
     table: undefined,
     column: undefined,
     dataType: undefined,
     constraint: undefined,
     file: 'uuid.c',
     line: '137',
     routine: 'string_to_uuid',
     sql:
      'SELECT "VideoModel".*, "Thumbnails"."id" AS "Thumbnails.id", "Thumbnails"."filename" AS "Thumbnails.filename", "Thumbnails"."height" AS "Thumbnails.height", "Thumbnails"."width" AS "Thumbnails.width", "Thumbnails"."type" AS "Thumbnails.type", "Thumbnails"."fileUrl" AS "Thumbnails.fileUrl", "Thumbnails"."automaticallyGenerated" AS "Thumbnails.automaticallyGenerated", "Thumbnails"."videoId" AS "Thumbnails.videoId", "Thumbnails"."videoPlaylistId" AS "Thumbnails.videoPlaylistId", "Thumbnails"."createdAt" AS "Thumbnails.createdAt", "Thumbnails"."updatedAt" AS "Thumbnails.updatedAt" FROM (SELECT "VideoModel"."id", "VideoModel"."uuid", "VideoModel"."name", "VideoModel"."category", "VideoModel"."licence", "VideoModel"."language", "VideoModel"."privacy", "VideoModel"."nsfw", "VideoModel"."description", "VideoModel"."support", "VideoModel"."duration", "VideoModel"."views", "VideoModel"."likes", "VideoModel"."dislikes", "VideoModel"."remote", "VideoModel"."isLive", "VideoModel"."url", "VideoModel"."commentsEnabled", "VideoModel"."downloadEnabled", "VideoModel"."waitTranscoding", "VideoModel"."state", "VideoModel"."publishedAt", "VideoModel"."originallyPublishedAt", "VideoModel"."channelId", "VideoModel"."createdAt", "VideoModel"."updatedAt" FROM "video" AS "VideoModel" WHERE "VideoModel"."uuid" = \'9673a7f-8e7b-46fa-ab07-fd7275f6cd8f\' LIMIT 1) AS "VideoModel" LEFT OUTER JOIN "thumbnail" AS "Thumbnails" ON "VideoModel"."id" = "Thumbnails"."videoId";',
     parameters: undefined },
  sql:
   'SELECT "VideoModel".*, "Thumbnails"."id" AS "Thumbnails.id", "Thumbnails"."filename" AS "Thumbnails.filename", "Thumbnails"."height" AS "Thumbnails.height", "Thumbnails"."width" AS "Thumbnails.width", "Thumbnails"."type" AS "Thumbnails.type", "Thumbnails"."fileUrl" AS "Thumbnails.fileUrl", "Thumbnails"."automaticallyGenerated" AS "Thumbnails.automaticallyGenerated", "Thumbnails"."videoId" AS "Thumbnails.videoId", "Thumbnails"."videoPlaylistId" AS "Thumbnails.videoPlaylistId", "Thumbnails"."createdAt" AS "Thumbnails.createdAt", "Thumbnails"."updatedAt" AS "Thumbnails.updatedAt" FROM (SELECT "VideoModel"."id", "VideoModel"."uuid", "VideoModel"."name", "VideoModel"."category", "VideoModel"."licence", "VideoModel"."language", "VideoModel"."privacy", "VideoModel"."nsfw", "VideoModel"."description", "VideoModel"."support", "VideoModel"."duration", "VideoModel"."views", "VideoModel"."likes", "VideoModel"."dislikes", "VideoModel"."remote", "VideoModel"."isLive", "VideoModel"."url", "VideoModel"."commentsEnabled", "VideoModel"."downloadEnabled", "VideoModel"."waitTranscoding", "VideoModel"."state", "VideoModel"."publishedAt", "VideoModel"."originallyPublishedAt", "VideoModel"."channelId", "VideoModel"."createdAt", "VideoModel"."updatedAt" FROM "video" AS "VideoModel" WHERE "VideoModel"."uuid" = \'9673a7f-8e7b-46fa-ab07-fd7275f6cd8f\' LIMIT 1) AS "VideoModel" LEFT OUTER JOIN "thumbnail" AS "Thumbnails" ON "VideoModel"."id" = "Thumbnails"."videoId";',
  parameters: undefined }
npm ERR! code ELIFECYCLE
npm ERR! errno 255
npm ERR! peertube@3.0.1 create-import-video-file-job: `node ./dist/scripts/create-import-video-file-job.js "-v" "9673a7f-8e7b-46fa-ab07-fd7275f6cd8f" "-i" "/var/www/peertube/presentation.mp4"`
npm ERR! Exit status 255
npm ERR! 
npm ERR! Failed at the peertube@3.0.1 create-import-video-file-job script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /var/www/peertube/.npm/_logs/2021-02-07T17_14_28_540Z-debug.log
```

**Comment by Chocobozzz** [comment]
Hello,

`9673a7f-8e7b-46fa-ab07-fd7275f6cd8f` is not a valid UUID. It seems you made a typo. I added a check in https://github.com/Chocobozzz/PeerTube/commit/9aeef9aafa009762e128046bfb2f3cec3252e181

**Comment by pprw** [comment]
> `9673a7f-8e7b-46fa-ab07-fd7275f6cd8f` is not a valid UUID. It seems you made a typo.

Indeed! Sorry for that.
