### ISSUE TITLE
Database connection fails

### ISSUE THREAD

**Issue by rogorido** [Chocobozzz/PeerTube#3748]
**Describe the current behavior**

Peertube starts with systemd but it is not accessible on the webpage (404 error). In .npm/_logs I have a lot of files with the following text: 

```0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'start' ]
2 info using npm@6.14.8
3 info using node@v12.18.2
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle peertube@3.0.1~prestart: peertube@3.0.1
6 info lifecycle peertube@3.0.1~start: peertube@3.0.1
7 verbose lifecycle peertube@3.0.1~start: unsafe-perm in lifecycle true
8 verbose lifecycle peertube@3.0.1~start: PATH: /usr/share/npm/node_modules/npm-
lifecycle/node-gyp-bin:/var/www/peertube/versions/peertube-v3.0.1/node_modules/.
bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin
9 verbose lifecycle peertube@3.0.1~start: CWD: /var/www/peertube/versions/peertu
be-v3.0.1
10 silly lifecycle peertube@3.0.1~start: Args: [ '-c', 'node dist/server' ]
11 silly lifecycle peertube@3.0.1~start: Returned: code: 1  signal: null
12 info lifecycle peertube@3.0.1~start: Failed to exec start script
13 verbose stack Error: peertube@3.0.1 start: `node dist/server`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/share/npm/node_modules/np
m-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:315:20)
13 verbose stack     at ChildProcess.<anonymous> (/usr/share/npm/node_modules/np
m-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:315:20)
13 verbose stack     at maybeClose (internal/child_process.js:1021:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_proc
ess.js:286:5)
14 verbose pkgid peertube@3.0.1
15 verbose cwd /var/www/peertube/versions/peertube-v3.0.1
16 verbose Linux 5.8.0-43-generic
17 verbose argv "/usr/bin/node" "/usr/bin/npm" "start"
18 verbose node v12.18.2
19 verbose npm  v6.14.8
20 error code ELIFECYCLE
21 error errno 1
22 error peertube@3.0.1 start: `node dist/server`
22 error Exit status 1
23 error Failed at the peertube@3.0.1 start script.
23 error This is probably not a problem with npm. There is likely additional log
ging output above.
24 verbose exit [ 1, true ]
```

**Additional information**

* PeerTube instance:
  * URL: own private instance 
  * version: 3.0.1
  * NodeJS version: 12.18.2

I'm using ubuntu 20.04.

**Comment by Chocobozzz** [comment]
Please try to run peertube manually using the same env variable defined in your systemd service

**Comment by rogorido** [comment]
@Chocobozzz thanks for your answer (and for the beautiful piece of software!).

I get the following:

```
NODE_CONFIG_DIR=/var/www/peertube/config NODE_ENV=production sudo -u peertube npm start

> peertube@3.0.1 start /var/www/peertube/versions/peertube-v3.0.1
> node dist/server

[localhost:9000] 2021-02-18 10:13:35.663 warn: Emailer is disabled so the contact form will not work.
[localhost:9000] 2021-02-18 10:13:36.271 error: Unable to connect to PostgreSQL database. {
  "err": {
    "stack": "SequelizeConnectionError: password authentication failed for user \"peertube\"\n    at Client._connectionCallback (/var/www/peertube/versions/peertube-v3.0.1/node_modules/sequelize/lib/dialects/postgres/connection-manager.js:184:24)\n    at Client._handleErrorWhileConnecting (/var/www/peertube/versions/peertube-v3.0.1/node_modules/pg/lib/client.js:305:19)\n    at Client._handleErrorMessage (/var/www/peertube/versions/peertube-v3.0.1/node_modules/pg/lib/client.js:325:19)\n    at Connection.emit (events.js:315:20)\n    at /var/www/peertube/versions/peertube-v3.0.1/node_modules/pg/lib/connection.js:115:12\n    at Parser.parse (/var/www/peertube/versions/peertube-v3.0.1/node_modules/pg-protocol/dist/parser.js:40:17)\n    at Socket.<anonymous> (/var/www/peertube/versions/peertube-v3.0.1/node_modules/pg-protocol/dist/index.js:10:42)\n    at Socket.emit (events.js:315:20)\n    at addChunk (_stream_readable.js:295:12)\n    at readableAddChunk (_stream_readable.js:271:9)\n    at Socket.Readable.push (_stream_readable.js:212:10)\n    at TCP.onStreamRead (internal/stream_base_commons.js:186:23)",
    "message": "password authentication failed for user \"peertube\"",
    "name": "SequelizeConnectionError",
    "parent": {
      "stack": "error: password authentication failed for user \"peertube\"\n    at Parser.parseErrorMessage (/var/www/peertube/versions/peertube-v3.0.1/node_modules/pg-protocol/dist/parser.js:278:15)\n    at Parser.handlePacket (/var/www/peertube/versions/peertube-v3.0.1/node_modules/pg-protocol/dist/parser.js:126:29)\n    at Parser.parse (/var/www/peertube/versions/peertube-v3.0.1/node_modules/pg-protocol/dist/parser.js:39:38)\n    at Socket.<anonymous> (/var/www/peertube/versions/peertube-v3.0.1/node_modules/pg-protocol/dist/index.js:10:42)\n    at Socket.emit (events.js:315:20)\n    at addChunk (_stream_readable.js:295:12)\n    at readableAddChunk (_stream_readable.js:271:9)\n    at Socket.Readable.push (_stream_readable.js:212:10)\n    at TCP.onStreamRead (internal/stream_base_commons.js:186:23)",
      "message": "password authentication failed for user \"peertube\"",
      "length": 104,
      "name": "error",
      "severity": "FATAL",
      "code": "28P01",
      "file": "auth.c",
      "line": "330",
      "routine": "auth_failed"
    }
  }
}
npm ERR! code ELIFECYCLE
npm ERR! errno 255
npm ERR! peertube@3.0.1 start: `node dist/server`
npm ERR! Exit status 255
npm ERR! 
npm ERR! Failed at the peertube@3.0.1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /var/www/peertube/.npm/_logs/2021-02-18T10_13_36_296Z-debug.log
```

It seems a stupid error with the password, but I checked 1000 times production.yaml, I can connect with psql to the database with the peertube (database) user,... I also removed and reinstalled node modules...

Sorry, I am sure it is a stupid configuration problem, but I am lost at the moment. Maybe any hint in which direction I could search?

**Comment by rogorido** [comment]
well, installing the modules I get this error/warning, but I do not think this is related to my issue:

```
> youtube-dl@3.1.0 postinstall /var/www/peertube/versions/peertube-v3.0.1/node_modules/youtube-dl
> node ./scripts/download.js

Error [ERR_TLS_CERT_ALTNAME_INVALID]: Hostname/IP does not match certificate's altnames: Host: yt-dl.org. is not in the cert's altnames: DNS:*.aries.uberspace.de, DNS:aries.uberspace.de
    at Object.checkServerIdentity (tls.js:287:12)
    at TLSSocket.onConnectSecure (_tls_wrap.js:1511:27)
    at TLSSocket.emit (events.js:315:20)
    at TLSSocket._finishInit (_tls_wrap.js:936:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:710:12) {
  reason: "Host: yt-dl.org. is not in the cert's altnames: DNS:*.aries.uberspace.de, DNS:aries.uberspace.de",
  host: 'yt-dl.org',
  cert: {
    subject: [Object: null prototype] {
      OU: 'Domain Control Validated',
      CN: '*.aries.uberspace.de'
    },
    issuer: [Object: null prototype] {
      C: 'BE',
      O: 'GlobalSign nv-sa',
      CN: 'AlphaSSL CA - SHA256 - G2'
    },
    subjectaltname: 'DNS:*.aries.uberspace.de, DNS:aries.uberspace.de',
    infoAccess: [Object: null prototype] {
      'CA Issuers - URI': [Array],
      'OCSP - URI': [Array]
    },
```

**Comment by Chocobozzz** [comment]
Reinstalling node modules won't help. Regarding the postinstall issue, it seems that youtube-dl has a broken website.

How do you run `psql`? Using `psql -h localhost -U peertube -W peertube_prod`?

**Comment by rogorido** [comment]
yes, without problem:

```
psql -d peertube_prod -U peertube -W -h localhost
Password: 
psql (12.6 (Ubuntu 12.6-0ubuntu0.20.10.1))
SSL connection (protocol: TLSv1.3, cipher: TLS_AES_256_GCM_SHA384, bits: 256, compression: off)
Type "help" for help.

peertube_prod=> 
```
I modified the permissions in pg_hba.conf to md5, etc. But no chance. Very strange. I also tried ssl: true in production.yaml. But no chance.

**Comment by Chocobozzz** [comment]
Try to debug the connection using node interactive shell and https://node-postgres.com/features/connecting scripts in `peertube-latest` directory

**Comment by rogorido** [comment]
Ok, thanks! I will try it!

**Comment by OrnithOrtion** [comment]
I think I have the exact same error.
I can connect to the database using `psql -h localhost -U peertube -W peertube_prod`.
I have set the password in productions.yml.
But I still have problems to connect to postgres when trying to launch peertube using `sudo  npm start` in /var/www/peertube/peertube-latest.

Here are the error logs : 
##### /root/.npm/_logs/2021-02-20T07_51_00_363Z-debug.log

```bash
0 info it worked if it ends with ok
1 warn npm npm does not support Node.js v10.23.1
2 warn npm You should probably upgrade to a newer version of node as we
3 warn npm can't make any promises that npm will work with this version.
4 warn npm Supported releases of Node.js are the latest release of 4, 6, 7, 8, 9.
5 warn npm You can find the latest version at https://nodejs.org/
6 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'start' ]
7 info using npm@5.8.0
8 info using node@v10.23.1
9 verbose run-script [ 'prestart', 'start', 'poststart' ]
10 info lifecycle peertube@3.0.1~prestart: peertube@3.0.1
11 info lifecycle peertube@3.0.1~start: peertube@3.0.1
12 verbose lifecycle peertube@3.0.1~start: unsafe-perm in lifecycle true
13 verbose lifecycle peertube@3.0.1~start: PATH: /usr/share/npm/node_modules/npm-lifecycle/node-gyp-bin:/var/www/tube.ortion.xyz/versions/peertube-v3.0.1/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
14 verbose lifecycle peertube@3.0.1~start: CWD: /var/www/tube.ortion.xyz/versions/peertube-v3.0.1
15 silly lifecycle peertube@3.0.1~start: Args: [ '-c', 'node dist/server' ]
16 silly lifecycle peertube@3.0.1~start: Returned: code: 255  signal: null
17 info lifecycle peertube@3.0.1~start: Failed to exec start script
18 verbose stack Error: peertube@3.0.1 start: `node dist/server`
18 verbose stack Exit status 255
18 verbose stack     at EventEmitter.<anonymous> (/usr/share/npm/node_modules/npm-lifecycle/index.js:283:16)
18 verbose stack     at EventEmitter.emit (events.js:198:13)
18 verbose stack     at ChildProcess.<anonymous> (/usr/share/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
18 verbose stack     at ChildProcess.emit (events.js:198:13)
18 verbose stack     at maybeClose (internal/child_process.js:982:16)
18 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
19 verbose pkgid peertube@3.0.1
20 verbose cwd /var/www/tube.ortion.xyz/versions/peertube-v3.0.1
21 verbose Linux 4.19.0-14-cloud-amd64
22 verbose argv "/usr/bin/node" "/usr/bin/npm" "start"
23 verbose node v10.23.1
24 verbose npm  v5.8.0
25 error code ELIFECYCLE
26 error errno 255
27 error peertube@3.0.1 start: `node dist/server`
27 error Exit status 255
28 error Failed at the peertube@3.0.1 start script.
28 error This is probably not a problem with npm. There is likely additional logging output above.
29 verbose exit [ 255, true ]
```

##### Erreur lors de l'éxecution de `sudo npm start`

```bash
[localhost:9000] 2021-02-20 08:31:12.909 warn: Emailer is disabled so the contact form will not work.
[localhost:9000] 2021-02-20 08:31:13.650 error: Unable to connect to PostgreSQL database. {
  "err": {
    "stack": "SequelizeConnectionError: password authentication failed for user \"peertube\"\n    at Client.connection.connect.err [as _connectionCallback] (/var/www/tube.ortion.xyz/versions/peertube-v3.0.1/node_modules/sequelize/lib/dialects/postgres/connection-manager.js:184:24)\n    at Client._handleErrorWhileConnecting (/var/www/tube.ortion.xyz/versions/peertube-v3.0.1/node_modules/pg/lib/client.js:305:19)\n    at Client._handleErrorMessage (/var/www/tube.ortion.xyz/versions/peertube-v3.0.1/node_modules/pg/lib/client.js:325:19)\n    at Connection.emit (events.js:198:13)\n    at parse (/var/www/tube.ortion.xyz/versions/peertube-v3.0.1/node_modules/pg/lib/connection.js:115:12)\n    at Parser.parse (/var/www/tube.ortion.xyz/versions/peertube-v3.0.1/node_modules/pg-protocol/dist/parser.js:40:17)\n    at Socket.stream.on (/var/www/tube.ortion.xyz/versions/peertube-v3.0.1/node_modules/pg-protocol/dist/index.js:10:42)\n    at Socket.emit (events.js:198:13)\n    at addChunk (_stream_readable.js:288:12)\n    at readableAddChunk (_stream_readable.js:269:11)\n    at Socket.Readable.push (_stream_readable.js:224:10)\n    at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)",
    "message": "password authentication failed for user \"peertube\"",
    "name": "SequelizeConnectionError",
    "parent": {
      "stack": "error: password authentication failed for user \"peertube\"\n    at Parser.parseErrorMessage (/var/www/tube.ortion.xyz/versions/peertube-v3.0.1/node_modules/pg-protocol/dist/parser.js:278:15)\n    at Parser.handlePacket (/var/www/tube.ortion.xyz/versions/peertube-v3.0.1/node_modules/pg-protocol/dist/parser.js:126:29)\n    at Parser.parse (/var/www/tube.ortion.xyz/versions/peertube-v3.0.1/node_modules/pg-protocol/dist/parser.js:39:38)\n    at Socket.stream.on (/var/www/tube.ortion.xyz/versions/peertube-v3.0.1/node_modules/pg-protocol/dist/index.js:10:42)\n    at Socket.emit (events.js:198:13)\n    at addChunk (_stream_readable.js:288:12)\n    at readableAddChunk (_stream_readable.js:269:11)\n    at Socket.Readable.push (_stream_readable.js:224:10)\n    at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)",
      "message": "password authentication failed for user \"peertube\"",
      "length": 104,
      "name": "error",
      "severity": "FATAL",
      "code": "28P01",
      "file": "auth.c",
      "line": "337",
      "routine": "auth_failed"
    }
  }
}
npm ERR! code 255
npm ERR! path /var/www/tube.ortion.xyz/versions/peertube-v3.0.1
npm ERR! command failed
npm ERR! command sh -c node dist/server

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-02-20T08_31_13_686Z-debug.log
```

##### After drop and recreate database and peertube user

```bash

> peertube@3.0.1 start
> node dist/server

[localhost:9000] 2021-02-20 08:37:30.440 warn: Emailer is disabled so the contact form will not work.
[localhost:9000] 2021-02-20 08:37:31.143 error: Unable to connect to PostgreSQL database. {
  "err": {
    "stack": "SequelizeConnectionError: password authentication failed for user \"peertube\"\n    at Client.connection.connect.err [as _connectionCallback] (/var/www/tube.ortion.xyz/versions/peertube-v3.0.1/node_modules/sequelize/lib/dialects/postgres/connection-manager.js:184:24)\n    at Client._handleErrorWhileConnecting (/var/www/tube.ortion.xyz/versions/peertube-v3.0.1/node_modules/pg/lib/client.js:305:19)\n    at Client._handleErrorMessage (/var/www/tube.ortion.xyz/versions/peertube-v3.0.1/node_modules/pg/lib/client.js:325:19)\n    at Connection.emit (events.js:198:13)\n    at parse (/var/www/tube.ortion.xyz/versions/peertube-v3.0.1/node_modules/pg/lib/connection.js:115:12)\n    at Parser.parse (/var/www/tube.ortion.xyz/versions/peertube-v3.0.1/node_modules/pg-protocol/dist/parser.js:40:17)\n    at Socket.stream.on (/var/www/tube.ortion.xyz/versions/peertube-v3.0.1/node_modules/pg-protocol/dist/index.js:10:42)\n    at Socket.emit (events.js:198:13)\n    at addChunk (_stream_readable.js:288:12)\n    at readableAddChunk (_stream_readable.js:269:11)\n    at Socket.Readable.push (_stream_readable.js:224:10)\n    at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)",
    "message": "password authentication failed for user \"peertube\"",
    "name": "SequelizeConnectionError",
    "parent": {
      "stack": "error: password authentication failed for user \"peertube\"\n    at Parser.parseErrorMessage (/var/www/tube.ortion.xyz/versions/peertube-v3.0.1/node_modules/pg-protocol/dist/parser.js:278:15)\n    at Parser.handlePacket (/var/www/tube.ortion.xyz/versions/peertube-v3.0.1/node_modules/pg-protocol/dist/parser.js:126:29)\n    at Parser.parse (/var/www/tube.ortion.xyz/versions/peertube-v3.0.1/node_modules/pg-protocol/dist/parser.js:39:38)\n    at Socket.stream.on (/var/www/tube.ortion.xyz/versions/peertube-v3.0.1/node_modules/pg-protocol/dist/index.js:10:42)\n    at Socket.emit (events.js:198:13)\n    at addChunk (_stream_readable.js:288:12)\n    at readableAddChunk (_stream_readable.js:269:11)\n    at Socket.Readable.push (_stream_readable.js:224:10)\n    at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)",
      "message": "password authentication failed for user \"peertube\"",
      "length": 104,
      "name": "error",
      "severity": "FATAL",
      "code": "28P01",
      "file": "auth.c",
      "line": "337",
      "routine": "auth_failed"
    }
  }
}
npm ERR! code 255
npm ERR! path /var/www/tube.ortion.xyz/versions/peertube-v3.0.1
npm ERR! command failed
npm ERR! command sh -c node dist/server

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-02-20T08_37_31_170Z-debug.log
```

**Comment by rasos** [comment]
Same here. Fresh manual install, postgres password again set manually and have it in production.yaml. Using nodejs 15 (and needed to patch package.json and yarn.lock https://github.com/Chocobozzz/PeerTube/commit/9162476fe9fe022ff24bd42ff828aca7c68129ef) on Debian buster.

**Comment by rasos** [comment]
Issue solved here. Problem was that I tried to start peertube manually, but it seems from the wrong directory, so it took the `default.yaml` of `peertube-latest/config` and not `production.yaml` from the `config` dir.

To get the [systemd option](https://github.com/Chocobozzz/PeerTube/blob/develop/support/doc/production.md#systemd) working I had to make it executable `chmod uga+x /etc/init.d/peertube` . Then I could start it as `systemctl start peertube` as intended.


Had applied this test script to test PostGres DB connection, if anybody needs to test as well:

```
const { Pool, Client } = require('pg')
// pools will use environment variables
// for connection information
const pool = new Pool()
pool.query('SELECT NOW()', (err, res) => {
  console.log(err, res)
  pool.end()
})
```
Launch as peertube user

`peertube@bridge2server:~/peertube-latest$ PGUSER=peertube PGDATABASE=peertube_prod PGPASSWORD=watchMyPW node pgtestscript.js`

Yes, I can connect to the DB: 

```
undefined Result {
  command: 'SELECT',
  rowCount: 1,
  oid: null,
  rows: [ { now: 2021-02-21T17:08:17.288Z } ],
  fields: [
    Field {
      name: 'now',
      tableID: 0,
      columnID: 0,
      dataTypeID: 1184,
      dataTypeSize: 8,
      dataTypeModifier: -1,
      format: 'text'
    }
  ],
  _parsers: [ [Function: parseDate] ],
  _types: TypeOverrides {
    _types: {
      getTypeParser: [Function: getTypeParser],
      setTypeParser: [Function: setTypeParser],
      arrayParser: [Object],
      builtins: [Object]
    },
    text: {},
    binary: {}
  },
  RowCtor: null,
  rowAsArray: false
}
```

**Comment by rogorido** [comment]
@rasos  Thanks for your script. I can also connect with it to the db without problems. But I do not understand the path you're using for systemd. In the docs there is /etc/systemd/system/ and not /etc/init.d... And besides this, is it really necessary to make it executable? As far as I see, some services which are working are not executable...

How were you starting manually peertube? From which directory?

**Comment by rasos** [comment]
I am starting now on Debian 10 with 

        systemctl start peertube

When copying the peertube init script as described here https://github.com/Chocobozzz/PeerTube/blob/develop/support/doc/production.md#openrc it is missing to make it executable. Just compare with other scripts in `/etc/init.d/` . all are executable.

**Comment by Chocobozzz** [comment]
@rogorido are you sure you set the db password in `/var/www/peertube/config/production.yaml`?

**Comment by rogorido** [comment]
@rasos thanks. 

@Chocobozzz yes, but I'm a little bit confused with users and permissions. If I run the script by rasos like this
```
PGUSER=peertube PGDATABASE=peertube_prod PGPASSWORD=R7QzhAMhMlTvMsyQE60bv7XK node pgtest.js
```
that means with my own normal user, it works perfectly.

But if I do 
```
PGUSER=peertube PGDATABASE=peertube_prod PGPASSWORD=R7QzhAMhMlTvMsyQE60bv7XK sudo -u peertube node pgtest.js
```
I get the same error authentication failed. 

All files in /var/www/peertube are owned by the user peertube. Why should it works with my own user but not with the peertube (system) user?

**Comment by Chocobozzz** [comment]
Try `sudo -u peertube PGUSER=peertube PGDATABASE=peertube_prod PGPASSWORD=passwd node pgtest.js`

**Comment by rogorido** [comment]
@Chocobozzz thanks again. Both work... and now it is also working with the system unit. Why, I do not know. I can not remember having changed anything... Sorry for the noise. 

I still get an 404 error (but nginx logs do not report it at error...),  but this is probably another issue and should not be dealt here. But just one question: if I have port 9000 used by php-fpm, I just have to  change the port number in production.yaml to 9001 and in nginx config file. Or am I wrong?

**Comment by Chocobozzz** [comment]
> I just have to change the port number in production.yaml to 9001 and in nginx config file

No you're right :+1:
