### ISSUE TITLE
create-import-video-file-job are not working with HLS

### ISSUE THREAD

**Issue by kontrollanten** [Chocobozzz/PeerTube#3765]
**Describe the current behavior**
When running [create-import-video-file-job](https://github.com/Chocobozzz/PeerTube/blob/develop/support/doc/tools.md#create-import-video-file-jobjs) with a HLS video an import job are created, which completes successfully, but then the transcoding job failes due to "WHERE parameter "uuid" has invalid "undefined" value".

**Steps to reproduce:**

1. Create a HLS video.
2. Run `sudo -u peertube NODE_CONFIG_DIR=/var/www/peertube/config NODE_ENV=production npm run create-import-video-file-job -- -v [videoUUID] -i [videoFile]`
3. Wait for the video-transcoding job to get started.

**Describe the expected behavior**
Transcoding should succeed.

**Additional information**
Jobs:

```

Job: 5 Type: video-file-import Processed on Feb 22, 2021, 10:10:06 AM Finished on Feb 22, 2021, 10:10:10 AM
--
{
   "videoUUID": "2d7bd76c-89b6-4cca-ab6c-73108e56cc46",
   "filePath": "/var/www/peertube/versions/peertube-v3.2.2-c/big_buck_bunny_720p_10mb.mp4" 
}


Job: 294 Type: video-transcoding Processed on Feb 22, 2021, 10:10:10 AM Finished on Feb 22, 2021, 10:10:10 AM
--
{
   "type": "hls",
   "copyCodecs": true
}

Error: WHERE parameter "uuid" has invalid "undefined" value
     at PostgresQueryGenerator.whereItemQuery (/var/www/peertube/versions/peertube-v3.2.2-c/node_modules/sequelize/lib/dialects/abstract/query-generator.js:2258:13)
     at /var/www/peertube/versions/peertube-v3.2.2-c/node_modules/sequelize/lib/dialects/abstract/query-generator.js:2247:25     at Array.forEach (<anonymous>)
     at PostgresQueryGenerator.whereItemsQuery (/var/www/peertube/versions/peertube-v3.2.2-c/node_modules/sequelize/lib/dialects/abstract/query-generator.js:2245:35)
     at PostgresQueryGenerator.getWhereConditions (/var/www/peertube/versions/peertube-v3.2.2-c/node_modules/sequelize/lib/dialects/abstract/query-generator.js:2663:19)
     at PostgresQueryGenerator.selectQuery (/var/www/peertube/versions/peertube-v3.2.2-c/node_modules/sequelize/lib/dialects/abstract/query-generator.js:1316:28)
     at PostgresQueryInterface.select (/var/www/peertube/versions/peertube-v3.2.2-c/node_modules/sequelize/lib/dialects/abstract/query-interface.js:939:27)
     at Function.findAll (/var/www/peertube/versions/peertube-v3.2.2-c/node_modules/sequelize/lib/model.js:1753:47)
     at runMicrotasks (<anonymous>)
     at processTicksAndRejections (internal/process/task_queues.js:97:5)
     at async Function.findOne (/var/www/peertube/versions/peertube-v3.2.2-c/node_modules/sequelize/lib/model.js:1917:12)
```

* PeerTube instance:
  * version: 3.2.2-c (custom)
  * NodeJS version: v12.20.2
  * Ffmpeg version: 4.2.4

**Comment by Chocobozzz** [comment]
Please could you retry with https://github.com/Chocobozzz/PeerTube/commit/70243d7a3575402dee00669da5c0d00a4b27dba4?

**Comment by kontrollanten** [comment]
I tried to cherry-pick that commit, but it lead to a lot of other dependent commits. Are you planning to do a new release soon?

**Comment by Chocobozzz** [comment]
I released a a rc version (stable planned for late March). Please comment if it does not fix this issue.

**Comment by kontrollanten** [comment]
It seems not to have been solved;

```
sudo -u peertube NODE_CONFIG_DIR=/var/www/peertube/config NODE_ENV=production npm run create-import-video-file-job -- -v 39642dfa-2612-442a-a94e-0a56ae43e974 -i /tmp/915496a3-ea94-4239-99c6-60f43ab7d0ba-360-fragmented.mp4
```

```
Apr 21 14:46:41 test-www2 peertube[18218]: [test:443] 2021-04-21 14:46:41.174 error: Cannot execute job 348 in queue video-transcoding. {
Apr 21 14:46:41 test-www2 peertube[18218]:   "payload": {
Apr 21 14:46:41 test-www2 peertube[18218]:     "type": "new-resolution-to-hls",
Apr 21 14:46:41 test-www2 peertube[18218]:     "videoUUID": "39642dfa-2612-442a-a94e-0a56ae43e974",
Apr 21 14:46:41 test-www2 peertube[18218]:     "resolution": 360,
Apr 21 14:46:41 test-www2 peertube[18218]:     "isPortraitMode": false,
Apr 21 14:46:41 test-www2 peertube[18218]:     "copyCodecs": true,
Apr 21 14:46:41 test-www2 peertube[18218]:     "isMaxQuality": false
Apr 21 14:46:41 test-www2 peertube[18218]:   },
Apr 21 14:46:41 test-www2 peertube[18218]:   "err": {
Apr 21 14:46:41 test-www2 peertube[18218]:     "stack": "SequelizeUniqueConstraintError: Validation error\n    at Query.formatError (/var/www/peertube/versions/peertube-v3.3.0-c/node_modules/sequelize/lib/dialects/postgres/query.js:344:18)\n    at Query.run (/var/www/peertube/versions/peertube-v3.3.0-c/node_modules/sequelize/lib/dialects/postgres/query.js:87:18)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (internal/process/task_queues.js:97:5)",
Apr 21 14:46:41 test-www2 peertube[18218]:     "message": "Validation error",
Apr 21 14:46:41 test-www2 peertube[18218]:     "name": "SequelizeUniqueConstraintError",
Apr 21 14:46:41 test-www2 peertube[18218]:     "errors": [
Apr 21 14:46:41 test-www2 peertube[18218]:       {
Apr 21 14:46:41 test-www2 peertube[18218]:         "message": "torrentFilename must be unique",
Apr 21 14:46:41 test-www2 peertube[18218]:         "type": "unique violation",
Apr 21 14:46:41 test-www2 peertube[18218]:         "path": "torrentFilename",
Apr 21 14:46:41 test-www2 peertube[18218]:         "value": "39642dfa-2612-442a-a94e-0a56ae43e974-360-hls.torrent",
Apr 21 14:46:41 test-www2 peertube[18218]:         "origin": "DB",
Apr 21 14:46:41 test-www2 peertube[18218]:         "instance": {
Apr 21 14:46:41 test-www2 peertube[18218]:           "id": null,
Apr 21 14:46:41 test-www2 peertube[18218]:           "resolution": 360,
Apr 21 14:46:41 test-www2 peertube[18218]:           "extname": ".mp4",
Apr 21 14:46:41 test-www2 peertube[18218]:           "size": 48915995,
Apr 21 14:46:41 test-www2 peertube[18218]:           "filename": "39642dfa-2612-442a-a94e-0a56ae43e974-360-fragmented.mp4",
Apr 21 14:46:41 test-www2 peertube[18218]:           "fps": 25,
Apr 21 14:46:41 test-www2 peertube[18218]:           "videoStreamingPlaylistId": 15,
Apr 21 14:46:41 test-www2 peertube[18218]:           "metadata": {
Apr 21 14:46:41 test-www2 peertube[18218]:             "chapters": [],
Apr 21 14:46:41 test-www2 peertube[18218]:             "format": {
Apr 21 14:46:41 test-www2 peertube[18218]:               "nb_streams": 2,
Apr 21 14:46:41 test-www2 peertube[18218]:               "nb_programs": 0,
Apr 21 14:46:41 test-www2 peertube[18218]:               "format_name": "mov,mp4,m4a,3gp,3g2,mj2",
Apr 21 14:46:41 test-www2 peertube[18218]:               "format_long_name": "QuickTime / MOV",
Apr 21 14:46:41 test-www2 peertube[18218]:               "start_time": 0.16,
Apr 21 14:46:41 test-www2 peertube[18218]:               "duration": 886.28,
Apr 21 14:46:41 test-www2 peertube[18218]:               "size": 48915995,
Apr 21 14:46:41 test-www2 peertube[18218]:               "bit_rate": 441539,
Apr 21 14:46:41 test-www2 peertube[18218]:               "probe_score": 100,
Apr 21 14:46:41 test-www2 peertube[18218]:               "tags": {
Apr 21 14:46:41 test-www2 peertube[18218]:                 "major_brand": "iso5",
Apr 21 14:46:41 test-www2 peertube[18218]:                 "minor_version": "512",
Apr 21 14:46:41 test-www2 peertube[18218]:                 "compatible_brands": "iso6mp41",
Apr 21 14:46:41 test-www2 peertube[18218]:                 "encoder": "Lavf58.29.100"
Apr 21 14:46:41 test-www2 peertube[18218]:               }
Apr 21 14:46:41 test-www2 peertube[18218]:             },
Apr 21 14:46:41 test-www2 peertube[18218]:             "streams": [
Apr 21 14:46:41 test-www2 peertube[18218]:               {
Apr 21 14:46:41 test-www2 peertube[18218]:                 "index": 0,
Apr 21 14:46:41 test-www2 peertube[18218]:                 "codec_name": "h264",
Apr 21 14:46:41 test-www2 peertube[18218]:                 "codec_long_name": "H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10",
Apr 21 14:46:41 test-www2 peertube[18218]:                 "profile": "High",
Apr 21 14:46:41 test-www2 peertube[18218]:                 "codec_type": "video",
Apr 21 14:46:41 test-www2 peertube[18218]:                 "codec_time_base": "1/50",
Apr 21 14:46:41 test-www2 peertube[18218]:                 "codec_tag_string": "avc1",
Apr 21 14:46:41 test-www2 peertube[18218]:                 "codec_tag": "0x31637661",
Apr 21 14:46:41 test-www2 peertube[18218]:                 "width": 640,
Apr 21 14:46:41 test-www2 peertube[18218]:                 "height": 360,
Apr 21 14:46:41 test-www2 peertube[18218]:                 "coded_width": 640,
Apr 21 14:46:41 test-www2 peertube[18218]:                 "coded_height": 368,
Apr 21 14:46:41 test-www2 peertube[18218]:                 "has_b_frames": 2,
Apr 21 14:46:41 test-www2 peertube[18218]:                 "sample_aspect_ratio": "N/A",
Apr 21 14:46:41 test-www2 peertube[18218]:                 "display_aspect_ratio": "N/A",
Apr 21 14:46:41 test-www2 peertube[18218]:                 "pix_fmt": "yuv420p",
Apr 21 14:46:41 test-www2 peertube[18218]:                 "level": 31,
Apr 21 14:46:41 test-www2 peertube[18218]:                 "color_range": "unknown",
Apr 21 14:46:41 test-www2 peertube[18218]:                 "color_space": "unknown",
Apr 21 14:46:41 test-www2 peertube[18218]:                 "color_transfer": "unknown",
Apr 21 14:46:41 test-www2 peertube[18218]:                 "color_primaries": "unknown",
Apr 21 14:46:41 test-www2 peertube[18218]:                 "chroma_location": "left",
Apr 21 14:46:41 test-www2 peertube[18218]:                 "field_order": "unknown",
Apr 21 14:46:41 test-www2 peertube[18218]:                 "timecode": "N/A",
Apr 21 14:46:41 test-www2 peertube[18218]:                 "refs": 1,
Apr 21 14:46:41 test-www2 peertube[18218]:                 "is_avc": "true",
Apr 21 14:46:41 test-www2 peertube[18218]:                 "nal_length_size": 4,
Apr 21 14:46:41 test-www2 peertube[18218]:                 "id": "N/A",
Apr 21 14:46:41 test-www2 peertube[18218]:                 "r_frame_rate": "25/1",
Apr 21 14:46:41 test-www2 peertube[18218]:                 "avg_frame_rate": "25/1",
Apr 21 14:46:41 test-www2 peertube[18218]:                 "time_base": "1/12800",
Apr 21 14:46:41 test-www2 peertube[18218]:                 "start_pts": 2048,
Apr 21 14:46:41 test-www2 peertube[18218]:                 "start_time": 0.16,
Apr 21 14:46:41 test-www2 peertube[18218]:                 "duration_ts": 11344384,
Apr 21 14:46:41 test-www2 peertube[18218]:                 "duration": 886.28,
Apr 21 14:46:41 test-www2 peertube[18218]:                 "bit_rate": 183357,
Apr 21 14:46:41 test-www2 peertube[18218]:                 "max_bit_rate": "N/A",
Apr 21 14:46:41 test-www2 peertube[18218]:                 "bits_per_raw_sample": 8,
Apr 21 14:46:41 test-www2 peertube[18218]:                 "nb_frames": "N/A",
Apr 21 14:46:41 test-www2 peertube[18218]:                 "nb_read_frames": "N/A",
Apr 21 14:46:41 test-www2 peertube[18218]:                 "nb_read_packets": "N/A",
Apr 21 14:46:41 test-www2 peertube[18218]:                 "tags": {
Apr 21 14:46:41 test-www2 peertube[18218]:                   "language": "und",
Apr 21 14:46:41 test-www2 peertube[18218]:                   "handler_name": "VideoHandler"
Apr 21 14:46:41 test-www2 peertube[18218]:                 },
Apr 21 14:46:41 test-www2 peertube[18218]:                 "disposition": {
Apr 21 14:46:41 test-www2 peertube[18218]:                   "default": 1,
Apr 21 14:46:41 test-www2 peertube[18218]:                   "dub": 0,
Apr 21 14:46:41 test-www2 peertube[18218]:                   "original": 0,
Apr 21 14:46:41 test-www2 peertube[18218]:                   "comment": 0,
Apr 21 14:46:41 test-www2 peertube[18218]:                   "lyrics": 0,
Apr 21 14:46:41 test-www2 peertube[18218]:                   "karaoke": 0,
Apr 21 14:46:41 test-www2 peertube[18218]:                   "forced": 0,
Apr 21 14:46:41 test-www2 peertube[18218]:                   "hearing_impaired": 0,
Apr 21 14:46:41 test-www2 peertube[18218]:                   "visual_impaired": 0,
Apr 21 14:46:41 test-www2 peertube[18218]:                   "clean_effects": 0,
Apr 21 14:46:41 test-www2 peertube[18218]:                   "attached_pic": 0,
Apr 21 14:46:41 test-www2 peertube[18218]:                   "timed_thumbnails": 0
Apr 21 14:46:41 test-www2 peertube[18218]:                 }
Apr 21 14:46:41 test-www2 peertube[18218]:               },
Apr 21 14:46:41 test-www2 peertube[18218]:               {
Apr 21 14:46:41 test-www2 peertube[18218]:                 "index": 1,
Apr 21 14:46:41 test-www2 peertube[18218]:                 "codec_name": "aac",
Apr 21 14:46:41 test-www2 peertube[18218]:                 "codec_long_name": "AAC (Advanced Audio Coding)",
Apr 21 14:46:41 test-www2 peertube[18218]:                 "profile": "LC",
Apr 21 14:46:41 test-www2 peertube[18218]:                 "codec_type": "audio",
Apr 21 14:46:41 test-www2 peertube[18218]:                 "codec_time_base": "1/48000",
Apr 21 14:46:41 test-www2 peertube[18218]:                 "codec_tag_string": "mp4a",
Apr 21 14:46:41 test-www2 peertube[18218]:                 "codec_tag": "0x6134706d",
Apr 21 14:46:41 test-www2 peertube[18218]:                 "sample_fmt": "fltp",
Apr 21 14:46:41 test-www2 peertube[18218]:                 "sample_rate": 48000,
Apr 21 14:46:41 test-www2 peertube[18218]:                 "channels": 2,
Apr 21 14:46:41 test-www2 peertube[18218]:                 "channel_layout": "stereo",
Apr 21 14:46:41 test-www2 peertube[18218]:                 "bits_per_sample": 0,
Apr 21 14:46:41 test-www2 peertube[18218]:                 "id": "N/A",
Apr 21 14:46:41 test-www2 peertube[18218]:                 "r_frame_rate": "0/0",
Apr 21 14:46:41 test-www2 peertube[18218]:                 "avg_frame_rate": "0/0",
Apr 21 14:46:41 test-www2 peertube[18218]:                 "time_base": "1/48000",
Apr 21 14:46:41 test-www2 peertube[18218]:                 "start_pts": 7680,
Apr 21 14:46:41 test-www2 peertube[18218]:                 "start_time": 0.16,
Apr 21 14:46:41 test-www2 peertube[18218]:                 "duration_ts": 42489600,
Apr 21 14:46:41 test-www2 peertube[18218]:                 "duration": 885.2,
Apr 21 14:46:41 test-www2 peertube[18218]:                 "bit_rate": 253352,
Apr 21 14:46:41 test-www2 peertube[18218]:                 "max_bit_rate": 253352,
Apr 21 14:46:41 test-www2 peertube[18218]:                 "bits_per_raw_sample": "N/A",
Apr 21 14:46:41 test-www2 peertube[18218]:                 "nb_frames": "N/A",
Apr 21 14:46:41 test-www2 peertube[18218]:                 "nb_read_frames": "N/A",
Apr 21 14:46:41 test-www2 peertube[18218]:                 "nb_read_packets": "N/A",
Apr 21 14:46:41 test-www2 peertube[18218]:                 "tags": {
Apr 21 14:46:41 test-www2 peertube[18218]:                   "language": "und",
Apr 21 14:46:41 test-www2 peertube[18218]:                   "handler_name": "SoundHandler"
Apr 21 14:46:41 test-www2 peertube[18218]:                 },
Apr 21 14:46:41 test-www2 peertube[18218]:                 "disposition": {
Apr 21 14:46:41 test-www2 peertube[18218]:                   "default": 1,
Apr 21 14:46:41 test-www2 peertube[18218]:                   "dub": 0,
Apr 21 14:46:41 test-www2 peertube[18218]:                   "original": 0,
Apr 21 14:46:41 test-www2 peertube[18218]:                   "comment": 0,
Apr 21 14:46:41 test-www2 peertube[18218]:                   "lyrics": 0,
Apr 21 14:46:41 test-www2 peertube[18218]:                   "karaoke": 0,
Apr 21 14:46:41 test-www2 peertube[18218]:                   "forced": 0,
Apr 21 14:46:41 test-www2 peertube[18218]:                   "hearing_impaired": 0,
Apr 21 14:46:41 test-www2 peertube[18218]:                   "visual_impaired": 0,
Apr 21 14:46:41 test-www2 peertube[18218]:                   "clean_effects": 0,
Apr 21 14:46:41 test-www2 peertube[18218]:                   "attached_pic": 0,
Apr 21 14:46:41 test-www2 peertube[18218]:                   "timed_thumbnails": 0
Apr 21 14:46:41 test-www2 peertube[18218]:                 }
Apr 21 14:46:41 test-www2 peertube[18218]:               }
Apr 21 14:46:41 test-www2 peertube[18218]:             ]
Apr 21 14:46:41 test-www2 peertube[18218]:           },
Apr 21 14:46:41 test-www2 peertube[18218]:           "infoHash": "3cacd755e48dd35b7eea90a0c972d5f73b16aa18",
Apr 21 14:46:41 test-www2 peertube[18218]:           "torrentFilename": "39642dfa-2612-442a-a94e-0a56ae43e974-360-hls.torrent",
Apr 21 14:46:41 test-www2 peertube[18218]:           "updatedAt": "2021-04-21T14:46:41.165Z",
Apr 21 14:46:41 test-www2 peertube[18218]:           "createdAt": "2021-04-21T14:46:41.165Z"
Apr 21 14:46:41 test-www2 peertube[18218]:         },
Apr 21 14:46:41 test-www2 peertube[18218]:         "validatorKey": "not_unique",
Apr 21 14:46:41 test-www2 peertube[18218]:         "validatorName": null,
Apr 21 14:46:41 test-www2 peertube[18218]:         "validatorArgs": []
Apr 21 14:46:41 test-www2 peertube[18218]:       }
Apr 21 14:46:41 test-www2 peertube[18218]:     ],
Apr 21 14:46:41 test-www2 peertube[18218]:     "fields": {
Apr 21 14:46:41 test-www2 peertube[18218]:       "torrentFilename": "39642dfa-2612-442a-a94e-0a56ae43e974-360-hls.torrent"
Apr 21 14:46:41 test-www2 peertube[18218]:     },
```

**Comment by kontrollanten** [comment]
It's working in 3.2.0 Thanks.
