### ISSUE TITLE
TypeError: Cannot read property 'actor' of undefined (fetching remote video failed)

### ISSUE THREAD

**Issue by gegeweb** [Chocobozzz/PeerTube#380]
* **PeerTube version or URL:** 1.0.0-beta.1
* **NodeJS version:** v9.8.0

Found this error in the peertube logs (today at 19:40).
Instance always up after this error, but nothing in the logs after.
I had to restart the service to get back the logs. (I'm on FreeBSD)

* **Server log if useful (Gist/Pastebin...):**
```
[peertube.gegeweb.eu:443] 2018-03-21 18:40:07.659 info: fd40:ce22:4c6d::200 - - [21/Mar/2018:18:40:07 +0000] "GET /services/oembed?url=https%3A%2F%2Fpeertube.gegeweb.eu%2Fvideos%2Fwatch%2Fbffa14e2-c52a-4708-9117-c91363f616c0&format=json HTTP/1.1" 200 511 "-" "Mozilla/5.0 (compatible; ruby-oembed/0.12.0)"

TypeError: Cannot read property 'actor' of undefined
    at /var/www/peertube/versions/peertube-v1.0.0-beta.1/dist/server/lib/activitypub/videos.js:249:35
    at Generator.next (<anonymous>)
    at fulfilled (/var/www/peertube/versions/peertube-v1.0.0-beta.1/dist/server/lib/activitypub/videos.js:4:58)
    at <anonymous>
Error: Cannot fetch remote video
    at Object.<anonymous> (/var/www/peertube/versions/peertube-v1.0.0-beta.1/dist/server/lib/activitypub/videos.js:180:23)
    at Generator.next (<anonymous>)
    at fulfilled (/var/www/peertube/versions/peertube-v1.0.0-beta.1/dist/server/lib/activitypub/videos.js:4:58)
    at <anonymous>
Error: Cannot fetch remote video
    at Object.<anonymous> (/var/www/peertube/versions/peertube-v1.0.0-beta.1/dist/server/lib/activitypub/videos.js:180:23)
    at Generator.next (<anonymous>)
    at fulfilled (/var/www/peertube/versions/peertube-v1.0.0-beta.1/dist/server/lib/activitypub/videos.js:4:58)
    at <anonymous>
Error: Cannot fetch remote video
    at Object.<anonymous> (/var/www/peertube/versions/peertube-v1.0.0-beta.1/dist/server/lib/activitypub/videos.js:180:23)
    at Generator.next (<anonymous>)
    at fulfilled (/var/www/peertube/versions/peertube-v1.0.0-beta.1/dist/server/lib/activitypub/videos.js:4:58)
    at <anonymous>
```

**Comment by Chocobozzz** [comment]
This is just your instance cannot access to a remote resource (maybe the remote server is down?). I improved logging: https://github.com/Chocobozzz/PeerTube/commit/8e8234abba7b64767e9ffb6dc38758a62b1ea16c

Don't hesitate to reopen if with these new logs you notice potential bugs.
