### ISSUE TITLE
Sync another instance video comments fail

### ISSUE THREAD

**Issue by meredith2u** [Chocobozzz/PeerTube#3850]
**Describe the current behavior**
Here is 3 types of sync comments for another instance video error, it's cause stop sync comments, so I can't see full comments on my instance search result.

**Steps to reproduce:**

1. Search such as ```https://peertube.cpy.re/videos/watch/e8a1af4e-414a-4d58-bfe6-2146eed06d10``` or ```https://wiwi.video/videos/watch/520117bc-f93d-4f9c-b165-314bf71aded1``` on my instance.
2. Click search result video.
3. Wait a few seconds to sync video comments, and reload page.
4. The comments will show nothing or not showing full comments.

**Describe the expected behavior**
Success showing full comments.

**Additional information**

* PeerTube instance:
  * URL: mtube.mooo.com
  * version: v3.1.0-rc.1
  * NodeJS version: v15.11.0
  * Ffmpeg version: v4.3.2

* Browser name, version and platforms on which you could reproduce the bug: ```Firefox``` or ```Chrome```
* Link to browser console log if relevant:
* Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`):

```
error[2021/3/10 上午9:51:12] Cannot execute job 108 in queue activitypub-http-fetcher.

{
  "payload": {
    "uri": "https://peertube.cpy.re/videos/watch/e8a1af4e-414a-4d58-bfe6-2146eed06d10/comments",
    "videoId": 122,
    "type": "video-comments"
  },
  "err": {
    "stack": "Error: Remote video comment JSON https://framapiaf.org/users/framasky/statuses/99366773999850055 is not valid:{\"error\":\"Not Found\"}\n    at /var/www/peertube/versions/peertube-v3.1.0-rc.1/dist/server/lib/activitypub/video-comments.js:109:19\n    at Generator.next (<anonymous>)\n    at fulfilled (/var/www/peertube/versions/peertube-v3.1.0-rc.1/node_modules/tslib/tslib.js:114:62)",
    "message": "Remote video comment JSON https://framapiaf.org/users/framasky/statuses/99366773999850055 is not valid:{\"error\":\"Not Found\"}"
  }
}
```
```
error[2021/3/10 上午9:16:06] Cannot execute job 5 in queue activitypub-http-fetcher.

{
  "payload": {
    "uri": "https://wiwi.video/videos/watch/520117bc-f93d-4f9c-b165-314bf71aded1/comments",
    "videoId": 121,
    "type": "video-comments"
  },
  "err": {
    "stack": "Error: getaddrinfo ENOTFOUND mtube.zapto.org\n    at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:69:26)",
    "message": "getaddrinfo ENOTFOUND mtube.zapto.org",
    "errno": -3007,
    "code": "ENOTFOUND",
    "syscall": "getaddrinfo",
    "hostname": "mtube.zapto.org"
  }
}
```
```
error[2021/3/10 上午9:01:04] Cannot execute job 5 in queue activitypub-http-fetcher.

{
  "payload": {
    "uri": "https://wiwi.video/videos/watch/520117bc-f93d-4f9c-b165-314bf71aded1/comments",
    "videoId": 121,
    "type": "video-comments"
  },
  "err": {
    "stack": "Error [ERR_TLS_CERT_ALTNAME_INVALID]: Hostname/IP does not match certificate's altnames: Host: mtube.zapto.org. is not in the cert's altnames: DNS:mtube.mooo.com\n    at new NodeError (node:internal/errors:329:5)\n    at Object.checkServerIdentity (node:tls:315:12)\n    at TLSSocket.onConnectSecure (node:_tls_wrap:1541:27)\n    at TLSSocket.emit (node:events:378:20)\n    at TLSSocket._finishInit (node:_tls_wrap:945:8)\n    at TLSWrap.ssl.onhandshakedone (node:_tls_wrap:719:12)",
    "reason": "Host: mtube.zapto.org. is not in the cert's altnames: DNS:mtube.mooo.com",
    "host": "mtube.zapto.org",
    "cert": "Replaced by the logger to avoid large log message",
    "message": "Hostname/IP does not match certificate's altnames: Host: mtube.zapto.org. is not in the cert's altnames: DNS:mtube.mooo.com",
    "code": "ERR_TLS_CERT_ALTNAME_INVALID"
  }
}
```

**Comment by Chocobozzz** [comment]
Hello,

It's because some instances can still store comments (that were removed, from instances that do not exist anymore etc). We introduced an option in 3.1 allowing admins to clean up entries that do not exist anymore.

However PeerTube shouldn't stop to process all threads because of 1 thread error. Updated in https://github.com/Chocobozzz/PeerTube/commit/5177e892a22c9d6ce94906af8ae9dc70da91f3ff
