### ISSUE TITLE
blank screen when trying to load with cookies disabled

### ISSUE THREAD

**Issue by maxlath** [Chocobozzz/PeerTube#386]
* **PeerTube version or URL:** https://peertube.cpy.re
* **Browser name/version:** Firefox 59.0.1 or Chromium 64.0.3282.167 (Ubuntu 16.04)
* **NodeJS version:** N/A

* **What is the expected behaviour?** Should at least show a message asking to activate cookies
* **What do you see instead?** A blank screen

* **Browser console log if useful (Gist/Pastebin...):**
```
main.50dbea649000019ed7c0.bundle.js:1 ERROR DOMException: Failed to read the 'localStorage' property from 'Window': Access is denied for this document.
    at Function.e.load (https://peertube.cpy.re/client/main.50dbea649000019ed7c0.bundle.js:1:261950)
    at new t (https://peertube.cpy.re/client/main.50dbea649000019ed7c0.bundle.js:1:612521)
    at https://peertube.cpy.re/client/main.50dbea649000019ed7c0.bundle.js:1:377645
    at No (https://peertube.cpy.re/client/main.50dbea649000019ed7c0.bundle.js:1:377686)
    at Io (https://peertube.cpy.re/client/main.50dbea649000019ed7c0.bundle.js:1:377272)
    at t.get (https://peertube.cpy.re/client/main.50dbea649000019ed7c0.bundle.js:1:388046)
    at Ei (https://peertube.cpy.re/client/main.50dbea649000019ed7c0.bundle.js:1:391916)
    at Ci (https://peertube.cpy.re/client/main.50dbea649000019ed7c0.bundle.js:1:391041)
    at yi (https://peertube.cpy.re/client/main.50dbea649000019ed7c0.bundle.js:1:389915)
    at $i (https://peertube.cpy.re/client/main.50dbea649000019ed7c0.bundle.js:1:401311)
xt @ main.50dbea649000019ed7c0.bundle.js:1
```
* **Server log if useful (Gist/Pastebin...):** N/A

* **Comment**: As it's not the cookies themselves but localStorage that crashes, a work-around could be to check for localStorage accessibility, and replace it with an in-memory polyfill if not usable, see [our implementation](https://github.com/inventaire/inventaire-client/blob/45bac5c/app/lib/local_storage.coffee#L2-L18)

**Comment by Chocobozzz** [comment]
Thanks, should be fixed: https://github.com/Chocobozzz/PeerTube/commit/0bd78bf30b2ae159791bdc90d17ed18e0327f621
