### ISSUE TITLE
Docker build failed

### ISSUE THREAD

**Issue by MikaXII** [Chocobozzz/PeerTube#388]
Hello,
From a `docker build -f Dockerfile.stretch -t myOwnPeertube .`
```
Step 8/13 : RUN cp /app/config/default.yaml /app/support/docker/production/config/default.yaml
 ---> Running in a8929cdd34c3
cp: cannot create regular file '/app/support/docker/production/config/default.yaml': Permission denied
```
I'll just add : `RUN chown peertube:peertube -R /app` before `USER peertube` to avoid this issue.

Currently I try to make a rancher template to use it on rancher host :)

**Comment by Chocobozzz** [comment]
Please retry

**Comment by MikaXII** [comment]
Fixed :)

**Comment by Chocobozzz** [comment]
Thanks @Angristan :+1:

**Comment by MikaXII** [comment]
Maybe we need to reopen this issue : 
```

Error: EACCES: permission denied, mkdir '/data/logs'
    at Object.fs.mkdirSync (fs.js:885:18)
    at Function.sync (/app/node_modules/mkdirp/index.js:71:13)
    at Object.<anonymous> (/app/dist/server/helpers/logger.js:10:8)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/app/dist/server/initializers/database.js:13:18)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/app/dist/server/initializers/index.js:8:10)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
```
This error is throw after lauching the container.
I don't know but maybe do : 
```
RUN mkdir /data
[...]
RUN chown peertube:peertube -R /data
```
I'll try this anyway :)

**Comment by Chocobozzz** [comment]
See the documentation https://github.com/Chocobozzz/PeerTube/blob/develop/support/doc/docker.md :)

**Comment by MikaXII** [comment]
my bad... thx :)
