### ISSUE TITLE
Upgrade to 3.1.0 breaks webtorrent video

### ISSUE THREAD

**Issue by kontrollanten** [Chocobozzz/PeerTube#3895]
**Describe the current behavior**
After upgrade from [3.2.2-c](https://github.com/kontrollanten/PeerTube/releases/tag/v3.2.2-c) (which should be equivalent to 3.0.1 regarding relevant parts in this case) to 3.1.0, via the `upgrade` script, a webtorrent video breaks. After visiting the video after upgrade the API returns 500.

**Steps to reproduce:**

1. Import our backup of the 3.2.2-c version.
2. Run `script/upgrade.sh`.
3. Restart server.
4. Visit webtorrent video.

**Additional information**

* PeerTube instance:
  * URL: Private
  * version: 3.1.0
  * NodeJS version: v12.21.0

* Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`):

```
Mar 29 06:10:40 test-www peertube[15246]: [] 2021-03-29 06:10:40.555 error: Error in controller. {
Mar 29 06:10:40 test-www peertube[15246]:   "err": "TypeError [ERR_INVALID_ARG_TYPE]:
The \"path\" argument must be of type string. Received null\n    
at validateString (internal/validators.js:120:11)\n    
at Object.join (path.js:1039:7)\n    
at VideoFileModel.getFileStaticPath (/var/www/peertube/versions/peertube-v3.1.0/dist/server/models/video/video-file.js:188:23)\n    
at VideoFileModel.getFileUrl (/var/www/peertube/versions/peertube-v3.1.0/dist/server/models/video/video-file.js:182:53)\n    
at /var/www/peertube/versions/peertube-v3.1.0/dist/server/models/video/video-format-utils.js:158:32\n    
at Array.map (<anonymous>)\n    at videoFilesModelToFormattedJSON (/var/www/peertube/versions/peertube-v3.1.0/dist/server/models/video/video-format-utils.js:144:10)\n    
at Object.videoModelToFormattedDetailsJSON (/var/www/peertube/versions/peertube-v3.1.0/dist/server/models/video/video-format-utils.js:107:25)\n    
at self.toFormattedDetailsJSON (/var/www/peertube/versions/peertube-v3.1.0/dist/server/models/video/video.js:998:37)\n    
at /var/www/peertube/versions/peertube-v3.1.0/dist/server/controllers/api/videos/index.js:290:31\n    
at Generator.next (<anonymous>)\n    at fulfilled (/var/www/peertube/versions/peertube-v3.1.0/node_modules/tslib/tslib.js:114:62)\n    at processTicksAndRejections (internal/process/task_queues.js:97:5)"
```

**Comment by Chocobozzz** [comment]
It's weird, the migration script should have updated the `filename` column https://github.com/Chocobozzz/PeerTube/blob/develop/server/initializers/migrations/0585-video-file-names.ts#L25

**Comment by kontrollanten** [comment]
In the database (prior 3.1.0) there filename column is `null` for the webtorrent video.

**Comment by Chocobozzz** [comment]
I don't understand, the `videoFile` `filename` column does not exist in 3.0: https://github.com/Chocobozzz/PeerTube/blob/develop/server/initializers/migrations/0585-video-file-names.ts#L9

**Comment by kontrollanten** [comment]
Strange, then we've must installed the nightly build previously so that was causing the error.
