### ISSUE TITLE
When the import script encounter an error, it raise an unmanaged exceptions and stay stuck

### ISSUE THREAD

**Issue by okhin** [Chocobozzz/PeerTube#391]
* **PeerTube version or URL:**
latest
https://tbs.okhin.fr/
* **Browser name/version:**
CLI
* **NodeJS version:**
9.9.0

* **What is the expected behaviour?**
When launching the script dist/server/tools/import-videos.js and the script raises an error, it should display the error (and ideally the URL called) on the console and return with a non-zero value.

* **What do you see instead?**
The scripts stay stuck, not ending, with the following error messages.

Uploading on PeerTube video "أغنية ساقط ساقط يا بشار قاشوش جرجناز رائد الحامض".
(node:23421) UnhandledPromiseRejectionWarning: Error: expected 200 "OK", got 500 "Internal Server Error"
    at Test._assertStatus (/home/okhin/PeerTube/node_modules/supertest/lib/test.js:266:12)
    at Test._assertFunction (/home/okhin/PeerTube/node_modules/supertest/lib/test.js:281:11)
    at Test.assert (/home/okhin/PeerTube/node_modules/supertest/lib/test.js:171:18)
    at assert (/home/okhin/PeerTube/node_modules/supertest/lib/test.js:131:12)
    at /home/okhin/PeerTube/node_modules/supertest/lib/test.js:128:5
    at Test.Request.callback (/home/okhin/PeerTube/node_modules/superagent/lib/node/index.js:718:3)
    at IncomingMessage.parser (/home/okhin/PeerTube/node_modules/superagent/lib/node/index.js:906:18)
    at IncomingMessage.emit (events.js:185:15)
    at endReadableNT (_stream_readable.js:1101:12)
    at process._tickCallback (internal/process/next_tick.js:114:19)
(node:23421) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:23421) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

* **Browser console log if useful (Gist/Pastebin...):**
* **Server log if useful (Gist/Pastebin...):**

**Comment by okhin** [comment]
Did a quick fix to get rid on the uncatched exception.

Basically, it now display the error in the console, and gracefully exit the process, with a non-zero state, which will allow for the OS to know that things gone bad.
