### ISSUE TITLE
import-video.js (youtube): TypeError: Cannot read property 'status' of undefined

### ISSUE THREAD

**Issue by poka-IT** [Chocobozzz/PeerTube#395]
* **PeerTube version or URL:** Beta-1
* **Browser name/version:** Firefox 59
* **NodeJS version:** 8.9.4

* **What is the expected behaviour?** Import youtube videos
* **What do you see instead?** Error: TypeError: Cannot read property 'status' of undefined

* **Browser console log if useful (Gist/Pastebin...):** https://paste.ofcode.org/ZPJQQgBGzj5NVY9zd5DeE2
------------------

When I try to use the plugin import-video.js, I got this error.
Is it something known ?

**Comment by floSoX** [comment]
Hi!
I tried with your modifications but I have the same problem.
I installed PeerTube v1.0.0-beta.3 in Docker with your docker-compose.yml.

The entier message is:
```
TypeError: Cannot read property 'status' of undefined
    at Test._assertStatus (/app/node_modules/supertest/lib/test.js:263:11)
    at Test._assertFunction (/app/node_modules/supertest/lib/test.js:281:11)
    at Test.assert (/app/node_modules/supertest/lib/test.js:171:18)
    at assert (/app/node_modules/supertest/lib/test.js:131:12)
    at /app/node_modules/supertest/lib/test.js:128:5
    at Test.Request.callback (/app/node_modules/superagent/lib/node/index.js:718:3)
    at ClientRequest.req.once.err (/app/node_modules/superagent/lib/node/index.js:646:10)
    at Object.onceWrapper (events.js:315:30)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at TLSSocket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at TLSSocket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

**Comment by Chocobozzz** [comment]
@floSoX Please copy paste the CLI you use (with the instance URL).

**Comment by floSoX** [comment]
`PWD=/app`
```ruby
node dist/server/tools/import-videos.js -u "https://qtg.peertube.fr" -U "u" --password "p" -t "https://www.youtube.com/c/QuestcequetuGEEKes"
```

**Comment by bootlicker** [comment]
I am getting this error as well. I also get a similar error on upload.js

**Comment by Chocobozzz** [comment]
@bootlicker Please copy paste the CLI you use (with the instance URL).

**Comment by bootlicker** [comment]
`node dist/server/tools/upload.js -u "https://localhost:9000" -U "root" -p "####" -f "####/00 December/Introduction_Day_1_-_Tuesday_16_December_2014-7snoaDaEdXo.mp4" -n "Introduction Day 1 - Tuesday 16 December 2014" `

and

`sudo node dist/server/tools/upload.js -u "https://tube.bootlicker.party" -U "root" -p "#####" -f "/#####/2014/00 December/Introduction_Day_1_-_Tuesday_16_December_2014-7snoaDaEdXo.mp4" -n "Introduction Day 1 - Tuesday 16 December 2014"`

both give different undefined errors
