### ISSUE TITLE
PeerTube cannot send e-mails using the sendmail method: Error: write EPIPE

### ISSUE THREAD

**Issue by pprw** [Chocobozzz/PeerTube#3969]
It is (I think) a different bug than https://github.com/Chocobozzz/PeerTube/issues/3640.

I just installed a fresh 3.1.0 peertube instance and have the following error when trying to send an email from peertube (lost password, contact form).

Sendmail works on the server (I receive email send wit mailx/mail).

I tried to replace server/lib/emailer.js by the one in the nightly build of 2021-04-15 https://builds.joinpeertube.org/nightly/. Same issue.

```
error[01/04/2021 à 20:33:38] Error in email sender.

{
  "err": {
    "stack": "Error: write EPIPE\n    at afterWriteDispatched (internal/stream_base_commons.js:156:25)\n    at writeGeneric (internal/stream_base_commons.js:147:3)\n    at Socket._writeGeneric (net.js:787:11)\n    at Socket._write (net.js:799:8)\n    at doWrite (_stream_writable.js:403:12)\n    at writeOrBuffer (_stream_writable.js:387:5)\n    at Socket.Writable.write (_stream_writable.js:318:11)\n    at LeWindows.ondata (_stream_readable.js:718:22)\n    at LeWindows.emit (events.js:314:20)\n    at addChunk (_stream_readable.js:297:12)\n    at readableAddChunk (_stream_readable.js:272:9)\n    at LeWindows.Readable.push (_stream_readable.js:213:10)\n    at LeWindows.Transform.push (_stream_transform.js:152:32)\n    at LeWindows._transform (/var/www/peertube/versions/peertube-v3.1.0/node_modules/nodemailer/lib/sendmail-transport/le-unix.js:30:22)\n    at LeWindows.Transform._read (_stream_transform.js:191:10)\n    at LeWindows.Transform._write (_stream_transform.js:179:12)\n    at doWrite (_stream_writable.js:403:12)\n    at writeOrBuffer (_stream_writable.js:387:5)\n    at LeWindows.Writable.write (_stream_writable.js:318:11)\n    at LastNewline.ondata (_stream_readable.js:718:22)\n    at LastNewline.emit (events.js:314:20)\n    at addChunk (_stream_readable.js:297:12)\n    at readableAddChunk (_stream_readable.js:272:9)\n    at LastNewline.Readable.push (_stream_readable.js:213:10)\n    at LastNewline.Transform.push (_stream_transform.js:152:32)\n    at LastNewline._transform (/var/www/peertube/versions/peertube-v3.1.0/node_modules/nodemailer/lib/mime-node/last-newline.js:16:14)\n    at LastNewline.Transform._read (_stream_transform.js:191:10)\n    at LastNewline.Transform._write (_stream_transform.js:179:12)",
    "message": "write EPIPE",
    "errno": "EPIPE",
    "code": "EPIPE",
    "syscall": "write"
  }
}
```

production.yaml:

```
  hostname: hpstube.fr
  port: 465 # If you use StartTLS: 587
  username: null
  password: null
  tls: true # If you use StartTLS: false
  disable_starttls: false
  ca_file: null # Used for self signed certificates
  from_address: 'xxxxxxxx' (removed for github)

```

**Comment by Chocobozzz** [comment]
Hi,

I'm not sure to understand. You talk about sendmail but in your config I don't see the `transport: sendmail` and `sendmail: /usr/...` configuration keys

**Comment by pprw** [comment]
> Hi,
> 
> I'm not sure to understand. You talk about sendmail but in your config I don't see the `transport: sendmail` and `sendmail: /usr/...` configuration keys

Sorry, I partially pasted the relevant section of production.yaml. I have the two lines about sendmail correctly filled:

```

  # smtp or sendmail
  transport: sendmail
  # Path to sendmail command. Required if you use sendmail transport
  sendmail: /usr/sbin/sendmail
  hostname: hpstube.fr
  port: 465 # If you use StartTLS: 587
  username: null
  password: null
  tls: true # If you use StartTLS: false
  disable_starttls: false
  ca_file: null # Used for self signed certificates
  from_address: 'xxxxxxxx' (removed for github)

```

**Comment by Chocobozzz** [comment]
I'm sorry but I can't reproduce so I can't really help you. It's weird that nodemailer can't write in the sendmail process stdin. You could try reproduce [this commit](https://github.com/Chocobozzz/PeerTube/commit/b7a27f2860982db2322048441d85b7143862d3b7) to add some logs in the sendmail transport
