### ISSUE TITLE
BUSY Redis is busy running a script

### ISSUE THREAD

**Issue by pokapow** [Chocobozzz/PeerTube#3971]
Since last update of peertube (3.1.0), I got this error which crash [my peertube instance](https://tube.p2p.legal/about/instance), every 2 or 3 days.

In `/etc/redis/redis.conf` I have:
`lua-time-limit 5000`

Should I increase it ?

I found this old issue closed without solutions: https://github.com/Chocobozzz/PeerTube/issues/1222

I'm not in dev mode, i'm in production.

I'm on Debian 10, 4Go RAM, 2 CPU.

**Comment by rigelk** [comment]
What is your version of Redis?

**Comment by pokapow** [comment]
Redis server v=5.0.3

**Comment by Chocobozzz** [comment]
Please paste the error

**Comment by pokapow** [comment]
Sure, sorry I forgot:

```
{
  "level": "error",
  "message": "Error in job queue activitypub-http-unicast.",
  "label": "tube.p2p.legal:443",
  "err": {
    "stack": "ReplyError: BUSY Redis is busy running a script. You can only call SCRIPT KILL or SHUTDOWN NOSAVE.\n    at parseError (/var/www/peertube/versions/peertube-v3.1.0/node_modules/redis-parser/lib/parser.js:179:12)\n    at parseType (/var/www/peertube/versions/peertube-v3.1.0/node_modules/redis-parser/lib/parser.js:302:14)",
    "message": "BUSY Redis is busy running a script. You can only call SCRIPT KILL or SHUTDOWN NOSAVE.",
    "command": {
      "name": "evalsha",
      "args": [
        "8b912cdc5b4c20108ef73d952464fba3a7470d7b",
        "6",
        "bull-tube.p2p.legal:activitypub-http-unicast:delayed",
        "bull-tube.p2p.legal:activitypub-http-unicast:active",
        "bull-tube.p2p.legal:activitypub-http-unicast:wait",
        "bull-tube.p2p.legal:activitypub-http-unicast:priority",
        "bull-tube.p2p.legal:activitypub-http-unicast:paused",
        "bull-tube.p2p.legal:activitypub-http-unicast:meta-paused",
        "bull-tube.p2p.legal:activitypub-http-unicast:",
        "1618557877494",
        "6024db66-34bb-47ec-bb5d-b8400eedc44d"
      ]
    }
  },
  "timestamp": "2021-04-16T07:24:46.363Z"
}

```

**Comment by pokapow** [comment]
Crash again.

I just made a script to restart PT if HS, until I find a solution.

```
#!/bin/bash

log="/tmp/monit-peertube.log"
date=$(date '+%d-%m-%y | %H:%M')

echo "MONIT PEERTUBE --- $date" >> $log

# Check if Peertube is HS
if [[ $(ps -aux | grep "peertube" | grep -v "grep peertube" | grep -v "monit_peertube") == "" ]]; then
#  ps -aux | grep "peertube" | grep -v "grep peertube" | grep -v "monit_peertube"
  # Kill peertube to be sure
  sleep 0.5
  killall peertube 2>/dev/null
  echo "Peertube is HS so we start it" >> $log
  tail /var/www/peertube/storage/logs/peertube.log -n100 >> $log
  echo "---"
  sleep 0.5

  # Start Peertube
  cd /var/www/peertube/peertube-latest && sudo -u peertube NODE_CONFIG_DIR=/var/www/peertube/config NODE_ENV=production /usr/bin/npm start > /var/www/peertube/storage/logs/peertube.log 2>&1 &
fi
```

Increasing `lua-time-limit` didn't fix the problem.

**Comment by Chocobozzz** [comment]
Do you have other services on your server that use Redis?

**Comment by pokapow** [comment]
No

**Comment by Chocobozzz** [comment]
Okay please try to enable slowlog so we can find which script is too slow:
 * `slowlog-log-slower-than: ...` (choose the appropriate value)
 * Paste `slowlog get 10` using `redis-cli`

**Comment by pokapow** [comment]
Actualy I have `slowlog-log-slower-than 10000`

I keep it ?

Actualy this is the 10 last slowlog:

```
# redis-cli slowlog get 10
 1) 1) (integer) 2184
    2) (integer) 1618830627
    3) (integer) 61686
    4)  1) "evalsha"
        2) "7825e9dfe2d12df8d37533bad1bfbfacd98c46ea"
        3) "3"
        4) "bull-tube.p2p.legal:activitypub-refresher:completed"
        5) "bull-tube.p2p.legal:activitypub-refresher:priority"
        6) "bull-tube.p2p.legal:activitypub-refresher:limiter"
        7) "bull-tube.p2p.legal:activitypub-refresher:"
        8) "1618657827222"
        9) "0"
       10) "completed"
    5) "127.0.0.1:39640"
    6) "bull-tube.p2p.legal:YWN0aXZpdHlwdWItcmVmcmVzaGVy"
 2) 1) (integer) 2183
    2) (integer) 1618829417
    3) (integer) 33456
    4) 1) "sadd"
       2) "redis-tube.p2p.legal-videos-view-h12"
       3) "217555"
    5) "127.0.0.1:39608"
    6) ""
 3) 1) (integer) 2182
    2) (integer) 1618827027
    3) (integer) 71077
    4)  1) "evalsha"
        2) "7825e9dfe2d12df8d37533bad1bfbfacd98c46ea"
        3) "3"
        4) "bull-tube.p2p.legal:activitypub-refresher:completed"
        5) "bull-tube.p2p.legal:activitypub-refresher:priority"
        6) "bull-tube.p2p.legal:activitypub-refresher:limiter"
        7) "bull-tube.p2p.legal:activitypub-refresher:"
        8) "1618654227299"
        9) "0"
       10) "completed"
    5) "127.0.0.1:39640"
    6) "bull-tube.p2p.legal:YWN0aXZpdHlwdWItcmVmcmVzaGVy"
 4) 1) (integer) 2181
    2) (integer) 1618827027
    3) (integer) 76029
    4)  1) "evalsha"
        2) "7825e9dfe2d12df8d37533bad1bfbfacd98c46ea"
        3) "3"
        4) "bull-tube.p2p.legal:videos-views:completed"
        5) "bull-tube.p2p.legal:videos-views:priority"
        6) "bull-tube.p2p.legal:videos-views:limiter"
        7) "bull-tube.p2p.legal:videos-views:"
        8) "1618654227212"
        9) "0"
       10) "completed"
    5) "127.0.0.1:39638"
    6) "bull-tube.p2p.legal:dmlkZW9zLXZpZXdz"
 5) 1) (integer) 2180
    2) (integer) 1618823427
    3) (integer) 69891
    4)  1) "evalsha"
        2) "7825e9dfe2d12df8d37533bad1bfbfacd98c46ea"
        3) "3"
        4) "bull-tube.p2p.legal:activitypub-refresher:completed"
        5) "bull-tube.p2p.legal:activitypub-refresher:priority"
        6) "bull-tube.p2p.legal:activitypub-refresher:limiter"
        7) "bull-tube.p2p.legal:activitypub-refresher:"
        8) "1618650627220"
        9) "0"
       10) "completed"
    5) "127.0.0.1:39640"
    6) "bull-tube.p2p.legal:YWN0aXZpdHlwdWItcmVmcmVzaGVy"
 6) 1) (integer) 2179
    2) (integer) 1618823427
    3) (integer) 11716
    4)  1) "evalsha"
        2) "7825e9dfe2d12df8d37533bad1bfbfacd98c46ea"
        3) "3"
        4) "bull-tube.p2p.legal:videos-views:completed"
        5) "bull-tube.p2p.legal:videos-views:priority"
        6) "bull-tube.p2p.legal:videos-views:limiter"
        7) "bull-tube.p2p.legal:videos-views:"
        8) "1618650627206"
        9) "0"
       10) "completed"
    5) "127.0.0.1:39638"
    6) "bull-tube.p2p.legal:dmlkZW9zLXZpZXdz"
 7) 1) (integer) 2178
    2) (integer) 1618822738
    3) (integer) 24108
    4)  1) "evalsha"
        2) "8f55ae4a3be429c6d38c5d5db3e80edf89197b64"
        3) "6"
        4) "bull-tube.p2p.legal:activitypub-http-unicast:wait"
        5) "bull-tube.p2p.legal:activitypub-http-unicast:paused"
        6) "bull-tube.p2p.legal:activitypub-http-unicast:meta-paused"
        7) "bull-tube.p2p.legal:activitypub-http-unicast:id"
        8) "bull-tube.p2p.legal:activitypub-http-unicast:delayed"
        9) "bull-tube.p2p.legal:activitypub-http-unicast:priority"
       10) "bull-tube.p2p.legal:activitypub-http-unicast:"
       11) ""
       12) "__default__"
       13) "{\"uri\":\"https://yunopeertube.myddns.me/inbox\",\"signatureActorId\":1,\"body\":{\"id\":\"https://tube.p2p.legal/accounts/peertube/views/... (468 more bytes)"
       14) "{\"backoff\":{\"delay\":60000,\"type\":\"exponential\"},\"attempts\":5,\"timeout\":600000,\"delay\":0,\"timestamp\":1618822738404}"
       15) "1618822738404"
       16) "0"
       17) "0"
       18) "0"
       19) "LPUSH"
       20) "8f2b4bee-f415-425a-951e-57bf1ac5cf90"
    5) "127.0.0.1:39622"
    6) "bull-tube.p2p.legal:YWN0aXZpdHlwdWItaHR0cC11bmljYXN0"
 8) 1) (integer) 2177
    2) (integer) 1618822738
    3) (integer) 23617
    4) 1) "INCR"
       2) "bull-tube.p2p.legal:activitypub-http-unicast:id"
    5) "?:0"
    6) ""
 9) 1) (integer) 2176
    2) (integer) 1618819828
    3) (integer) 494322
    4)  1) "evalsha"
        2) "7825e9dfe2d12df8d37533bad1bfbfacd98c46ea"
        3) "3"
        4) "bull-tube.p2p.legal:activitypub-refresher:completed"
        5) "bull-tube.p2p.legal:activitypub-refresher:priority"
        6) "bull-tube.p2p.legal:activitypub-refresher:limiter"
        7) "bull-tube.p2p.legal:activitypub-refresher:"
        8) "1618647027743"
        9) "0"
       10) "completed"
    5) "127.0.0.1:39640"
    6) "bull-tube.p2p.legal:YWN0aXZpdHlwdWItcmVmcmVzaGVy"
10) 1) (integer) 2175
    2) (integer) 1618819827
    3) (integer) 99475
    4) 1) "ZREM"
       2) "bull-tube.p2p.legal:activitypub-refresher:completed"
       3) "800352"
    5) "?:0"
    6) ""

But didn't crash since last time I said.

```

**Comment by Chocobozzz** [comment]
> Actualy I have slowlog-log-slower-than 10000

Maybe to a bigger value, something like `2500000` (so 2.5 seconds since `lua-time-limit` is 5 seconds)

**Comment by pokapow** [comment]
Done.
No bugs since, I will tell you if that's happend again.

**Comment by Chocobozzz** [comment]
Closing, please comment if it happens again.
