### ISSUE TITLE
Live streaming ends after an hour or so

### ISSUE THREAD

**Issue by TROMsite** [Chocobozzz/PeerTube#3978]
**Describe the current behavior**
For the past 3 weeks we have 2 live streams. Both stopped at around 1h and 18 minutes. I could then start a new one to finish our podcast. But it is weird. Our server is in a very good shape, we exceed no RAM or CPU. We have no limits to our account.
This is one of the errors I caught:
```
error[4/17/2021, 8:19:10 PM] Cannot save/federate new video state of live streaming of video id 67261.

{
  "err": {
    "stack": "TypeError: Cannot read property 'map' of undefined\n    at self.getTrackerUrls (/var/www/peertube/dist/server/models/video/video.js:1119:30)\n    at addVideoFilesInAPAcc (/var/www/peertube/dist/server/models/video/video-format-utils.js:166:31)\n    at Object.videoModelToActivityPubObject (/var/www/peertube/dist/server/models/video/video-format-utils.js:236:5)\n    at self.toActivityPubObject (/var/www/peertube/dist/server/models/video/video.js:1013:37)\n    at Object.<anonymous> (/var/www/peertube/dist/server/lib/activitypub/send/send-update.js:24:35)\n    at Generator.next (<anonymous>)\n    at /var/www/peertube/node_modules/tslib/tslib.js:117:75\n    at new Promise (<anonymous>)\n    at Object.__awaiter (/var/www/peertube/node_modules/tslib/tslib.js:113:16)\n    at Object.sendUpdateVideo (/var/www/peertube/dist/server/lib/activitypub/send/send-update.js:14:20)\n    at Object.<anonymous> (/var/www/peertube/dist/server/lib/activitypub/videos.js:59:30)\n    at Generator.next (<anonymous>)\n    at fulfilled (/var/www/peertube/node_modules/tslib/tslib.js:114:62)\n    at processTicksAndRejections (internal/process/task_queues.js:93:5)",
    "message": "Cannot read property 'map' of undefined"
  }
}
```
This started to happen after we upgraded to 3.1.0 from what I can tell. Before it worked to make streams that were 3-4 hours long.

* PeerTube instance: https://videos.trom.tf
  * URL: https://videos.trom.tf
  * version: 3.1.0

* Browser name, version and platforms on which you could reproduce the bug: Firefox

**Comment by Chocobozzz** [comment]
Hello,

Please check ffmpeg related error in your log, that should be below the error your pasted.

**Comment by TROMsite** [comment]
Unfortunately bellow it I cannot see the ffmpeg error only a lot or mcaptchas errors. I can provide admin access to our instance if you want to have a closer look. Let me know.

**Comment by Chocobozzz** [comment]
> Unfortunately bellow it I cannot see the ffmpeg error only a lot of mcaptchas errors. I can provide admin access to our instance if you want to have a closer look. Let me know.

My mistake,  I meant to say above

**Comment by TROMsite** [comment]
Ok this is what I have above that:
```
error[4/17/2021, 8:18:54 PM] uncaughtException: Unexpected token u in JSON at position 0 SyntaxError: Unexpected token u in JSON at position 0 at JSON.parse (<anonymous>) at /home/yunohost.app/peertube/storage/plugins/node_modules/peertube-plugin-mtcaptcha/main.js:55:17 at f (/home/yunohost.app/peertube/storage/plugins/node_modules/once/once.js:25:25) at ClientRequest.<anonymous> (/home/yunohost.app/peertube/storage/plugins/node_modules/simple-get/index.js:63:5) at Object.onceWrapper (events.js:422:26) at ClientRequest.emit (events.js:315:20) at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:641:27) at HTTPParser.parserOnHeadersComplete (_http_common.js:126:17) at TLSSocket.socketOnData (_http_client.js:509:22) at TLSSocket.emit (events.js:315:20) at addChunk (internal/streams/readable.js:309:12) at readableAddChunk (internal/streams/readable.js:284:9) at TLSSocket.Readable.push (internal/streams/readable.js:223:10) at TLSWrap.onStreamRead (internal/stream_base_commons.js:188:23)

{
  "error": {
    "stack": "SyntaxError: Unexpected token u in JSON at position 0\n    at JSON.parse (<anonymous>)\n    at /home/yunohost.app/peertube/storage/plugins/node_modules/peertube-plugin-mtcaptcha/main.js:55:17\n    at f (/home/yunohost.app/peertube/storage/plugins/node_modules/once/once.js:25:25)\n    at ClientRequest.<anonymous> (/home/yunohost.app/peertube/storage/plugins/node_modules/simple-get/index.js:63:5)\n    at Object.onceWrapper (events.js:422:26)\n    at ClientRequest.emit (events.js:315:20)\n    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:641:27)\n    at HTTPParser.parserOnHeadersComplete (_http_common.js:126:17)\n    at TLSSocket.socketOnData (_http_client.js:509:22)\n    at TLSSocket.emit (events.js:315:20)\n    at addChunk (internal/streams/readable.js:309:12)\n    at readableAddChunk (internal/streams/readable.js:284:9)\n    at TLSSocket.Readable.push (internal/streams/readable.js:223:10)\n    at TLSWrap.onStreamRead (internal/stream_base_commons.js:188:23)",
    "message": "Unexpected token u in JSON at position 0"
  },
  "stack": "SyntaxError: Unexpected token u in JSON at position 0\n    at JSON.parse (<anonymous>)\n    at /home/yunohost.app/peertube/storage/plugins/node_modules/peertube-plugin-mtcaptcha/main.js:55:17\n    at f (/home/yunohost.app/peertube/storage/plugins/node_modules/once/once.js:25:25)\n    at ClientRequest.<anonymous> (/home/yunohost.app/peertube/storage/plugins/node_modules/simple-get/index.js:63:5)\n    at Object.onceWrapper (events.js:422:26)\n    at ClientRequest.emit (events.js:315:20)\n    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:641:27)\n    at HTTPParser.parserOnHeadersComplete (_http_common.js:126:17)\n    at TLSSocket.socketOnData (_http_client.js:509:22)\n    at TLSSocket.emit (events.js:315:20)\n    at addChunk (internal/streams/readable.js:309:12)\n    at readableAddChunk (internal/streams/readable.js:284:9)\n    at TLSSocket.Readable.push (internal/streams/readable.js:223:10)\n    at TLSWrap.onStreamRead (internal/stream_base_commons.js:188:23)",
  "exception": true,
  "date": "Sat Apr 17 2021 20:18:54 GMT+0200 (Central European Summer Time)",
  "process": {
    "pid": 26607,
    "uid": 985,
    "gid": 985,
    "cwd": "/var/www/peertube",
    "execPath": "/opt/node_n/n/versions/node/14.16.1/bin/node",
    "version": "v14.16.1",
    "argv": [
      "/opt/node_n/n/versions/node/14.16.1/bin/node",
      "/var/www/peertube/dist/server"
    ],
    "memoryUsage": {
      "rss": 295346176,
      "heapTotal": 133259264,
      "heapUsed": 92460752,
      "external": 20210476,
      "arrayBuffers": 18474205
    }
  },
  "os": {
    "loadavg": [
      7.8,
      8.74,
      8.53
    ],
    "uptime": 856144
  },
  "trace": [
    {
      "column": null,
      "file": null,
      "function": "JSON.parse",
      "line": null,
      "method": "parse",
      "native": false
    },
    {
      "column": 17,
      "file": "/home/yunohost.app/peertube/storage/plugins/node_modules/peertube-plugin-mtcaptcha/main.js",
      "function": null,
      "line": 55,
      "method": null,
      "native": false
    },
    {
      "column": 25,
      "file": "/home/yunohost.app/peertube/storage/plugins/node_modules/once/once.js",
      "function": "f",
      "line": 25,
      "method": null,
      "native": false
    },
    {
      "column": 5,
      "file": "/home/yunohost.app/peertube/storage/plugins/node_modules/simple-get/index.js",
      "function": null,
      "line": 63,
      "method": null,
      "native": false
    },
    {
      "column": 26,
      "file": "events.js",
      "function": "Object.onceWrapper",
      "line": 422,
      "method": "onceWrapper",
      "native": false
    },
    {
      "column": 20,
      "file": "events.js",
      "function": "ClientRequest.emit",
      "line": 315,
      "method": "emit",
      "native": false
    },
    {
      "column": 27,
      "file": "_http_client.js",
      "function": "HTTPParser.parserOnIncomingClient [as onIncoming]",
      "line": 641,
      "method": "parserOnIncomingClient [as onIncoming]",
      "native": false
    },
    {
      "column": 17,
      "file": "_http_common.js",
      "function": "HTTPParser.parserOnHeadersComplete",
      "line": 126,
      "method": "parserOnHeadersComplete",
      "native": false
    },
    {
      "column": 22,
      "file": "_http_client.js",
      "function": "TLSSocket.socketOnData",
      "line": 509,
      "method": "socketOnData",
      "native": false
    },
    {
      "column": 20,
      "file": "events.js",
      "function": "TLSSocket.emit",
      "line": 315,
      "method": "emit",
      "native": false
    },
    {
      "column": 12,
      "file": "internal/streams/readable.js",
      "function": "addChunk",
      "line": 309,
      "method": null,
      "native": false
    },
    {
      "column": 9,
      "file": "internal/streams/readable.js",
      "function": "readableAddChunk",
      "line": 284,
      "method": null,
      "native": false
    },
    {
      "column": 10,
      "file": "internal/streams/readable.js",
      "function": "TLSSocket.Readable.push",
      "line": 223,
      "method": "push",
      "native": false
    },
    {
      "column": 23,
      "file": "internal/stream_base_commons.js",
      "function": "TLSWrap.onStreamRead",
      "line": 188,
      "method": "onStreamRead",
      "native": false
    }
  ]
}

error[4/17/2021, 8:19:10 PM] Cannot save/federate new video state of live streaming of video id 67261.

{
  "err": {
    "stack": "TypeError: Cannot read property 'map' of undefined\n    at self.getTrackerUrls (/var/www/peertube/dist/server/models/video/video.js:1119:30)\n    at addVideoFilesInAPAcc (/var/www/peertube/dist/server/models/video/video-format-utils.js:166:31)\n    at Object.videoModelToActivityPubObject (/var/www/peertube/dist/server/models/video/video-format-utils.js:236:5)\n    at self.toActivityPubObject (/var/www/peertube/dist/server/models/video/video.js:1013:37)\n    at Object.<anonymous> (/var/www/peertube/dist/server/lib/activitypub/send/send-update.js:24:35)\n    at Generator.next (<anonymous>)\n    at /var/www/peertube/node_modules/tslib/tslib.js:117:75\n    at new Promise (<anonymous>)\n    at Object.__awaiter (/var/www/peertube/node_modules/tslib/tslib.js:113:16)\n    at Object.sendUpdateVideo (/var/www/peertube/dist/server/lib/activitypub/send/send-update.js:14:20)\n    at Object.<anonymous> (/var/www/peertube/dist/server/lib/activitypub/videos.js:59:30)\n    at Generator.next (<anonymous>)\n    at fulfilled (/var/www/peertube/node_modules/tslib/tslib.js:114:62)\n    at processTicksAndRejections (internal/process/task_queues.js:93:5)",
    "message": "Cannot read property 'map' of undefined"
  }
}
```

**Comment by Chocobozzz** [comment]
Then please try to uninstall the captcha plugin and try to reproduce

**Comment by TROMsite** [comment]
I will but before that, what has that plugin to do with the live streaming? I wonder

**Comment by TROMsite** [comment]
Please don't close this I didn't have the time to test it. I will do so these days. If this is indeed a bug, it is a big one since it interrupts the livestreaming.

**Comment by TROMsite** [comment]
Ok so I did as you suggested and this are the errors I am seeing:
```
warn[5/6/2021, 2:26:17 PM] Cannot authenticate.

{
  "err": {
    "statusCode": 401,
    "status": 401,
    "code": 401,
    "message": "Invalid token: access token has expired",
    "name": "invalid_token",
    "stack": "invalid_token: Invalid token: access token has expired\n    at new InvalidTokenError (/var/www/peertube/node_modules/oauth2-server/lib/errors/invalid-token-error.js:25:14)\n    at AuthenticateHandler.validateAccessToken (/var/www/peertube/node_modules/oauth2-server/lib/handlers/authenticate-handler.js:227:11)\n    at AuthenticateHandler.<anonymous> (/var/www/peertube/node_modules/oauth2-server/lib/handlers/authenticate-handler.js:77:19)\n    at PassThroughHandlerContext.finallyHandler (/var/www/peertube/node_modules/bluebird/js/release/finally.js:57:23)\n    at PassThroughHandlerContext.tryCatcher (/var/www/peertube/node_modules/bluebird/js/release/util.js:16:23)\n    at Promise._settlePromiseFromHandler (/var/www/peertube/node_modules/bluebird/js/release/promise.js:547:31)\n    at Promise._settlePromise (/var/www/peertube/node_modules/bluebird/js/release/promise.js:604:18)\n    at Promise._settlePromise0 (/var/www/peertube/node_modules/bluebird/js/release/promise.js:649:10)\n    at Promise._settlePromises (/var/www/peertube/node_modules/bluebird/js/release/promise.js:729:18)\n    at _drainQueueStep (/var/www/peertube/node_modules/bluebird/js/release/async.js:93:12)\n    at _drainQueue (/var/www/peertube/node_modules/bluebird/js/release/async.js:86:9)\n    at Async._drainQueues (/var/www/peertube/node_modules/bluebird/js/release/async.js:102:5)\n    at Immediate.Async.drainQueues [as _onImmediate] (/var/www/peertube/node_modules/bluebird/js/release/async.js:15:14)\n    at processImmediate (internal/timers.js:461:21)"
  }
}

error[5/6/2021, 2:28:27 PM] Cannot run hook action:api.video.updated of plugin chapters.

{
  "err": {
    "stack": "ReferenceError: webVttstorageManager is not defined\n    at handler (/home/yunohost.app/peertube/storage/plugins/node_modules/peertube-plugin-chapters/main.js:32:9)\n    at Object.<anonymous> (/var/www/peertube/dist/shared/core-utils/plugins/hooks.js:25:23)\n    at Generator.next (<anonymous>)\n    at /var/www/peertube/node_modules/tslib/tslib.js:117:75\n    at new Promise (<anonymous>)\n    at Object.__awaiter (/var/www/peertube/node_modules/tslib/tslib.js:113:16)\n    at Object.internalRunHook (/var/www/peertube/dist/shared/core-utils/plugins/hooks.js:15:20)\n    at PluginManager.<anonymous> (/var/www/peertube/dist/server/lib/plugins/plugin-manager.js:145:40)\n    at Generator.next (<anonymous>)\n    at /var/www/peertube/node_modules/tslib/tslib.js:117:75\n    at new Promise (<anonymous>)\n    at Object.__awaiter (/var/www/peertube/node_modules/tslib/tslib.js:113:16)\n    at PluginManager.runHook (/var/www/peertube/dist/server/lib/plugins/plugin-manager.js:139:24)\n    at Object.runAction (/var/www/peertube/dist/server/lib/plugins/hooks.js:20:49)\n    at /var/www/peertube/dist/server/controllers/api/videos/index.js:272:27\n    at Generator.next (<anonymous>)\n    at fulfilled (/var/www/peertube/node_modules/tslib/tslib.js:114:62)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (internal/process/task_queues.js:93:5)",
    "message": "webVttstorageManager is not defined"
  }
}

error[5/6/2021, 2:30:07 PM] Too much data in client socket stream (ffmpeg is too slow to transcode the video). Stopping session of video 50f782f5-ca90-4611-90c1-c01defb9567e.

error[5/6/2021, 2:30:08 PM] Too much data in client socket stream (ffmpeg is too slow to transcode the video). Stopping session of video 50f782f5-ca90-4611-90c1-c01defb9567e.

warn[5/6/2021, 2:30:18 PM] Unknown live video with stream key 37029590-69f9-4293-9ea3-e0597f1a832d.

warn[5/6/2021, 2:30:30 PM] Unknown live video with stream key 37029590-69f9-4293-9ea3-e0597f1a832d.

error[5/6/2021, 2:30:39 PM] Cannot add comments of video ba9768ae-19bc-442e-9e54-1d10f22d573e.

{
  "err": {
    "stack": "Error: Remote video comment JSON https://tube.blob.cat/videos/watch/ba9768ae-19bc-442e-9e54-1d10f22d573e/comments/17530 is not valid:\"<html>\\r\\n<head><title>502 Bad Gateway</title></head>\\r\\n<body bgcolor=\\\"white\\\">\\r\\n<center><h1>502 Bad Gateway</h1></center>\\r\\n<hr><center>nginx/1.14.0 (Ubuntu)</center>\\r\\n</body>\\r\\n</html>\\r\\n\"\n    at /var/www/peertube/dist/server/lib/activitypub/video-comments.js:109:19\n    at Generator.next (<anonymous>)\n    at fulfilled (/var/www/peertube/node_modules/tslib/tslib.js:114:62)",
    "message": "Remote video comment JSON https://tube.blob.cat/videos/watch/ba9768ae-19bc-442e-9e54-1d10f22d573e/comments/17530 is not valid:\"<html>\\r\\n<head><title>502 Bad Gateway</title></head>\\r\\n<body bgcolor=\\\"white\\\">\\r\\n<center><h1>502 Bad Gateway</h1></center>\\r\\n<hr><center>nginx/1.14.0 (Ubuntu)</center>\\r\\n</body>\\r\\n</html>\\r\\n\""
  },
  "rootUrl": "https://videos.lukesmith.xyz/videos/watch/ba9768ae-19bc-442e-9e54-1d10f22d573e/comments"
}

warn[5/6/2021, 2:30:42 PM] Unknown live video with stream key 37029590-69f9-4293-9ea3-e0597f1a832d. 
```

**Comment by Chocobozzz** [comment]
Then the error is:

```
Too much data in client socket stream (ffmpeg is too slow to transcode the video). Stopping session of video
```

Increase live ffmpeg threads or remove some resolutions to avoid this

**Comment by TROMsite** [comment]
Ok. However it worked perfectly fine before the latest upgrade. Plus I already have 8 threads for a 10 core cpu server. And I kept an eye on the server's performance and it won't exceed 30-50% of its CPU capacity. So are we 100% sure it is a problem with the config?

**Comment by TROMsite** [comment]
We use an AMD EPYC 7282 16-Core Processor, 10 cores assigned to us. 60GB RAM, and 1.6TB SSD. If livestreams cannot perform well on this machine it means you really need a beast. So I am thinking maybe it is not a hardware failure, but something with Peertube.

**Comment by TROMsite** [comment]
Can "Transcoding jobs concurrency" be at fault if say there are fewer jobs than there are required? Say we have 3 Transcoding jobs concurrency  and there are 10 videos uploaded then one live, maybe Peertube tries to transcode the uploaded videos and the stream interrupts since it cannot transcode it anymore?

**Comment by TROMsite** [comment]
I tested many other options. Even just enabling 1 conversion type in the live transcoding. That also failed. Only works without transcoding for the live. Now I wonder....is our server's hardware not capable of this? The CPU never went over 50% for this entire time. So....what is happening?

**Comment by Chocobozzz** [comment]
How many threads have you configured for live transcoding?

**Comment by TROMsite** [comment]
> How many threads have you configured for live transcoding?

8 threads out of 10 that we have

**Comment by tio-trom** [comment]
I think we have to reopen this issue because it persists despite upgrading to the latest Peertube.

```
warn[8/10/2021, 5:48:07 AM] Unknown live video with stream key 6eb050f4-f2ce-40b2-9da6-ec74ada69c99.

{
  "tags": [
    "live",
    "IK2AZKO8"
  ]
}

warn[8/10/2021, 5:48:19 AM] Unknown live video with stream key 6eb050f4-f2ce-40b2-9da6-ec74ada69c99.

{
  "tags": [
    "live",
    "D4POH54T"
  ]
}

error[8/10/2021, 5:48:26 AM] Cannot run hook filter:api.user.signup.allowed.result of plugin mtcaptcha.

{
  "err": {
    "stack": "TypeError: Cannot read property 'mtcaptcha-response' of undefined\n    at verifyCaptcha (/home/yunohost.app/peertube/storage/plugins/node_modules/peertube-plugin-mtcaptcha/main.js:40:19)\n    at handler (/home/yunohost.app/peertube/storage/plugins/node_modules/peertube-plugin-mtcaptcha/main.js:24:34)\n    at Object.<anonymous> (/var/www/peertube/dist/shared/core-utils/plugins/hooks.js:18:27)\n    at Generator.next (<anonymous>)\n    at /var/www/peertube/node_modules/tslib/tslib.js:117:75\n    at new Promise (<anonymous>)\n    at Object.__awaiter (/var/www/peertube/node_modules/tslib/tslib.js:113:16)\n    at Object.internalRunHook (/var/www/peertube/dist/shared/core-utils/plugins/hooks.js:15:20)\n    at PluginManager.<anonymous> (/var/www/peertube/dist/server/lib/plugins/plugin-manager.js:149:40)\n    at Generator.next (<anonymous>)\n    at /var/www/peertube/node_modules/tslib/tslib.js:117:75\n    at new Promise (<anonymous>)\n    at Object.__awaiter (/var/www/peertube/node_modules/tslib/tslib.js:113:16)\n    at PluginManager.runHook (/var/www/peertube/dist/server/lib/plugins/plugin-manager.js:143:24)\n    at /var/www/peertube/dist/server/lib/plugins/hooks.js:13:56\n    at Generator.next (<anonymous>)\n    at fulfilled (/var/www/peertube/node_modules/tslib/tslib.js:114:62)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (internal/process/task_queues.js:95:5)",
    "message": "Cannot read property 'mtcaptcha-response' of undefined"
  }
}

warn[8/10/2021, 5:48:32 AM] Unknown live video with stream key 6eb050f4-f2ce-40b2-9da6-ec74ada69c99.

{
  "tags": [
    "live",
    "QWKJESKK"
  ]
}

error[8/10/2021, 5:48:33 AM] Cannot run hook filter:api.user.signup.allowed.result of plugin mtcaptcha.

{
  "err": {
    "stack": "TypeError: Cannot read property 'mtcaptcha-response' of undefined\n    at verifyCaptcha (/home/yunohost.app/peertube/storage/plugins/node_modules/peertube-plugin-mtcaptcha/main.js:40:19)\n    at handler (/home/yunohost.app/peertube/storage/plugins/node_modules/peertube-plugin-mtcaptcha/main.js:24:34)\n    at Object.<anonymous> (/var/www/peertube/dist/shared/core-utils/plugins/hooks.js:18:27)\n    at Generator.next (<anonymous>)\n    at /var/www/peertube/node_modules/tslib/tslib.js:117:75\n    at new Promise (<anonymous>)\n    at Object.__awaiter (/var/www/peertube/node_modules/tslib/tslib.js:113:16)\n    at Object.internalRunHook (/var/www/peertube/dist/shared/core-utils/plugins/hooks.js:15:20)\n    at PluginManager.<anonymous> (/var/www/peertube/dist/server/lib/plugins/plugin-manager.js:149:40)\n    at Generator.next (<anonymous>)\n    at /var/www/peertube/node_modules/tslib/tslib.js:117:75\n    at new Promise (<anonymous>)\n    at Object.__awaiter (/var/www/peertube/node_modules/tslib/tslib.js:113:16)\n    at PluginManager.runHook (/var/www/peertube/dist/server/lib/plugins/plugin-manager.js:143:24)\n    at /var/www/peertube/dist/server/lib/plugins/hooks.js:13:56\n    at Generator.next (<anonymous>)\n    at fulfilled (/var/www/peertube/node_modules/tslib/tslib.js:114:62)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (internal/process/task_queues.js:95:5)",
    "message": "Cannot read property 'mtcaptcha-response' of undefined"
  }
}

warn[8/10/2021, 5:48:45 AM] Unknown live video with stream key 6eb050f4-f2ce-40b2-9da6-ec74ada69c99.

{
  "tags": [
    "live",
    "R6DJOSQI"
  ]
}

warn[8/10/2021, 5:48:52 AM] Warning in tracker.

{
  "err": {
    "stack": "Error: Unknown infoHash 2a911c18f3a879f8b1298ff82a85c50ddc955ca5 requested by ip 2603:6081:8a00:a0:a960:fd20:4de9:66f7\n    at Server.<anonymous> (/var/www/peertube/dist/server/controllers/tracker.js:53:20)\n    at Generator.next (<anonymous>)\n    at fulfilled (/var/www/peertube/node_modules/tslib/tslib.js:114:62)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (internal/process/task_queues.js:95:5)",
    "message": "Unknown infoHash 2a911c18f3a879f8b1298ff82a85c50ddc955ca5 requested by ip 2603:6081:8a00:a0:a960:fd20:4de9:66f7"
  }
}
```
Fails almost exactly after 1h of streaming....
