### ISSUE TITLE
Add element in playlist: dependencies among transactions

### ISSUE THREAD

**Issue by kontrollanten** [Chocobozzz/PeerTube#3998]
**Describe the current behavior**
I've written a script to bulk add videos to playlists. It reads a CSV where the rows is the video uuid and the columns are names of playlists. All the operations are done via the REST API. When the script adds the videos to different playlists (https://framagit.org/kontrollanten/peertube-bulk-set-playlists/-/blob/master/main.js#L143-155) the following error occurs.

```
[pt.local.se:9000] 2021-04-22 10:20:06.589 error: Cannot execute addVideoInPlaylist with many retries. {
  "err": {
    "stack": "SequelizeDatabaseError: could not serialize access due to read/write dependencies among transactions\n    at Query.formatError (/var/code/PeerTube/node_modules/sequelize/lib/dialects/postgres/query.js:386:16)\n    at Query.run (/var/code/PeerTube/node_modules/sequelize/lib/dialects/postgres/query.js:87:18)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (internal/process/task_queues.js:93:5)",
    "message": "could not serialize access due to read/write dependencies among transactions",
    "name": "SequelizeDatabaseError",
    "parent": {
      "stack": "error: could not serialize access due to read/write dependencies among transactions\n    at Parser.parseErrorMessage (/var/code/PeerTube/node_modules/pg-protocol/dist/parser.js:278:15)\n    at Parser.handlePacket (/var/code/PeerTube/node_modules/pg-protocol/dist/parser.js:126:29)\n    at Parser.parse (/var/code/PeerTube/node_modules/pg-protocol/dist/parser.js:39:38)\n    at Socket.<anonymous> (/var/code/PeerTube/node_modules/pg-protocol/dist/index.js:10:42)\n    at Socket.emit (events.js:210:5)\n    at Socket.EventEmitter.emit (domain.js:475:20)\n    at addChunk (_stream_readable.js:309:12)\n    at readableAddChunk (_stream_readable.js:290:11)\n    at Socket.Readable.push (_stream_readable.js:224:10)\n    at TCP.onStreamRead (internal/stream_base_commons.js:182:23)",
      "message": "could not serialize access due to read/write dependencies among transactions",
      "length": 274,
      "name": "error",
      "severity": "ERROR",
      "code": "40001",
      "detail": "Reason code: Canceled on identification as a pivot, during write.",
      "hint": "The transaction might succeed if retried.",
      "file": "predicate.c",
      "line": "4875",
      "routine": "OnConflict_CheckForSerializationFailure",
      "sql": "INSERT INTO \"videoPlaylistElement\" (\"id\",\"position\",\"startTimestamp\",\"stopTimestamp\",\"videoPlaylistId\",\"videoId\",\"createdAt\",\"updatedAt\") VALUES (DEFAULT,$1,$2,$3,$4,$5,$6,$7) RETURNING \"id\",\"url\",\"position\",\"startTimestamp\",\"stopTimestamp\",\"videoPlaylistId\",\"videoId\",\"createdAt\",\"updatedAt\";",
      "parameters": [
        54,
        null,
        null,
        6278,
        881,
        "2021-04-22 08:20:06.586 +00:00",
        "2021-04-22 08:20:06.586 +00:00"
      ]
    },
    "sql": "INSERT INTO \"videoPlaylistElement\" (\"id\",\"position\",\"startTimestamp\",\"stopTimestamp\",\"videoPlaylistId\",\"videoId\",\"createdAt\",\"updatedAt\") VALUES (DEFAULT,$1,$2,$3,$4,$5,$6,$7) RETURNING \"id\",\"url\",\"position\",\"startTimestamp\",\"stopTimestamp\",\"videoPlaylistId\",\"videoId\",\"createdAt\",\"updatedAt\";"
  }
}
[pt.local.se:9000] 2021-04-22 10:20:06.590 error: Cannot execute addVideoInPlaylist with many retries. {
  "err": {
    "stack": "SequelizeDatabaseError: could not serialize access due to read/write dependencies among transactions\n    at Query.formatError (/var/code/PeerTube/node_modules/sequelize/lib/dialects/postgres/query.js:386:16)\n    at Query.run (/var/code/PeerTube/node_modules/sequelize/lib/dialects/postgres/query.js:87:18)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (internal/process/task_queues.js:93:5)",
    "message": "could not serialize access due to read/write dependencies among transactions",
    "name": "SequelizeDatabaseError",
    "parent": {
      "stack": "error: could not serialize access due to read/write dependencies among transactions\n    at Parser.parseErrorMessage (/var/code/PeerTube/node_modules/pg-protocol/dist/parser.js:278:15)\n    at Parser.handlePacket (/var/code/PeerTube/node_modules/pg-protocol/dist/parser.js:126:29)\n    at Parser.parse (/var/code/PeerTube/node_modules/pg-protocol/dist/parser.js:39:38)\n    at Socket.<anonymous> (/var/code/PeerTube/node_modules/pg-protocol/dist/index.js:10:42)\n    at Socket.emit (events.js:210:5)\n    at Socket.EventEmitter.emit (domain.js:475:20)\n    at addChunk (_stream_readable.js:309:12)\n    at readableAddChunk (_stream_readable.js:290:11)\n    at Socket.Readable.push (_stream_readable.js:224:10)\n    at TCP.onStreamRead (internal/stream_base_commons.js:182:23)",
      "message": "could not serialize access due to read/write dependencies among transactions",
      "length": 274,
      "name": "error",
      "severity": "ERROR",
      "code": "40001",
      "detail": "Reason code: Canceled on identification as a pivot, during write.",
      "hint": "The transaction might succeed if retried.",
      "file": "predicate.c",
      "line": "4875",
      "routine": "OnConflict_CheckForSerializationFailure",
      "sql": "INSERT INTO \"videoPlaylistElement\" (\"id\",\"position\",\"startTimestamp\",\"stopTimestamp\",\"videoPlaylistId\",\"videoId\",\"createdAt\",\"updatedAt\") VALUES (DEFAULT,$1,$2,$3,$4,$5,$6,$7) RETURNING \"id\",\"url\",\"position\",\"startTimestamp\",\"stopTimestamp\",\"videoPlaylistId\",\"videoId\",\"createdAt\",\"updatedAt\";",
      "parameters": [
        54,
        null,
        null,
        6278,
        49,
        "2021-04-22 08:20:06.587 +00:00",
        "2021-04-22 08:20:06.587 +00:00"
      ]
    },
    "sql": "INSERT INTO \"videoPlaylistElement\" (\"id\",\"position\",\"startTimestamp\",\"stopTimestamp\",\"videoPlaylistId\",\"videoId\",\"createdAt\",\"updatedAt\") VALUES (DEFAULT,$1,$2,$3,$4,$5,$6,$7) RETURNING \"id\",\"url\",\"position\",\"startTimestamp\",\"stopTimestamp\",\"videoPlaylistId\",\"videoId\",\"createdAt\",\"updatedAt\";"
  }
}
[pt.local.se:9000] 2021-04-22 10:20:06.591 error: Error in controller. {
  "err": "SequelizeDatabaseError: could not serialize access due to read/write dependencies among transactions\n    at Query.formatError (/var/code/PeerTube/node_modules/sequelize/lib/dialects/postgres/query.js:386:16)\n    at Query.run (/var/code/PeerTube/node_modules/sequelize/lib/dialects/postgres/query.js:87:18)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (internal/process/task_queues.js:93:5)"
} - INSERT INTO "videoPlaylistElement" ("id","position","startTimestamp","stopTimestamp","videoPlaylistId","videoId","createdAt","updatedAt") VALUES (DEFAULT,$1,$2,$3,$4,$5,$6,$7) RETURNING "id","url","position","startTimestamp","stopTimestamp","videoPlaylistId","videoId","createdAt","updatedAt";
[pt.local.se:9000] 2021-04-22 10:20:06.591 info: 127.0.0.1 - - [22/Apr/2021:08:20:06 +0000] "POST /api/v1/video-playlists/6278/videos HTTP/1.1" 500 - "-" "node-fetch/1.0 (+https://github.com/bitinn/node-fetch)"
```

**Steps to reproduce:**
1. Set `rates_limit.api.max` to 5000 and `window` to `10 seconds`.
1. Run https://framagit.org/kontrollanten/peertube-bulk-set-playlists with CSV file containing ~700 videos and ~15 playlists.

**Describe the expected behavior**
It should just work.

**Additional information**

* PeerTube instance:
  * version: Latest develop

**Comment by Chocobozzz** [comment]
You can't add in parallel 700 videos in playlists, just process them one by one to avoid transaction dependency issues. When you add a video in the playlist, PeerTube needs to read the DB to find the next playlist `position`. Then it inserts the element. So if you insert another element there is a conflict.

PeerTube catches this kind of error to retry the transaction, but if there are too many insertions it will reach the max retry limit.
