### ISSUE TITLE
Unexpected start

### ISSUE THREAD

**Issue by lan894734188** [Chocobozzz/PeerTube#400]
* **PeerTube version or URL:**
* **Browser name/version:**Chrome
* **NodeJS version:**8.10.0

* **What is the expected behaviour?**
i run yarn start or npm start

* **What do you see instead?**
> peertube@1.0.0-beta.1 start /data/wwwroot/peertube/peertube-latest
> node dist/server

(node:65089) UnhandledPromiseRejectionWarning: SequelizeHostNotFoundError: getaddrinfo ENOTFOUND localhost localhost:5432
    at connection.connect.err (/data/wwwroot/peertube/peertube-latest/node_modules/sequelize/lib/dialects/postgres/connection-manager.js:119:24)
    at Connection.connectingErrorHandler (/data/wwwroot/peertube/peertube-latest/node_modules/pg/lib/client.js:123:14)
    at emitOne (events.js:116:13)
    at Connection.emit (events.js:211:7)
    at Socket.reportStreamError (/data/wwwroot/peertube/peertube-latest/node_modules/pg/lib/connection.js:71:10)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
(node:65089) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:65089) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:65089) UnhandledPromiseRejectionWarning: Error: Unknown codec libx264 in FFmpeg.
    at Object.<anonymous> (/data/wwwroot/peertube/peertube-latest/dist/server/initializers/checker.js:60:23)
    at Generator.next (<anonymous>)
    at fulfilled (/data/wwwroot/peertube/peertube-latest/dist/server/initializers/checker.js:4:58)
    at <anonymous>
(node:65089) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)

* **Browser console log if useful (Gist/Pastebin...):**
* **Server log if useful (Gist/Pastebin...):**

> peertube@1.0.0-beta.1 start /data/wwwroot/peertube/peertube-latest
> node dist/server

(node:65089) UnhandledPromiseRejectionWarning: SequelizeHostNotFoundError: getaddrinfo ENOTFOUND localhost localhost:5432
    at connection.connect.err (/data/wwwroot/peertube/peertube-latest/node_modules/sequelize/lib/dialects/postgres/connection-manager.js:119:24)
    at Connection.connectingErrorHandler (/data/wwwroot/peertube/peertube-latest/node_modules/pg/lib/client.js:123:14)
    at emitOne (events.js:116:13)
    at Connection.emit (events.js:211:7)
    at Socket.reportStreamError (/data/wwwroot/peertube/peertube-latest/node_modules/pg/lib/connection.js:71:10)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
(node:65089) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:65089) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:65089) UnhandledPromiseRejectionWarning: Error: Unknown codec libx264 in FFmpeg.
    at Object.<anonymous> (/data/wwwroot/peertube/peertube-latest/dist/server/initializers/checker.js:60:23)
    at Generator.next (<anonymous>)
    at fulfilled (/data/wwwroot/peertube/peertube-latest/dist/server/initializers/checker.js:4:58)
    at <anonymous>
(node:65089) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)

**Comment by rigelk** [comment]
Your PostgreSQL database doesn't answer on `localhost:5432` apparently. Please verify the service is running.

**Comment by lan894734188** [comment]
@rigelk But I have set up a database connection 127.0.0.1
Still showing error localhost in log
Where should production.yaml be placed in the directory?

**Comment by Chocobozzz** [comment]
It should be in `/var/www/peertube/config/production.yaml`

Try to check if PostgreSQL is running first: |sudo -u postgres psql postgres`

**Comment by lan894734188** [comment]
@Chocobozzz 
now in run "NODE_ENV=production npm start"
i have this log 
> peertube@1.0.0-beta.1 start /data/wwwroot/peertube/peertube-latest
> node dist/server

(node:44648) UnhandledPromiseRejectionWarning: Error: Unknown codec libx264 in FFmpeg.
    at Object.<anonymous> (/data/wwwroot/peertube/peertube-latest/dist/server/initializers/checker.js:60:23)
    at Generator.next (<anonymous>)
    at fulfilled (/data/wwwroot/peertube/peertube-latest/dist/server/initializers/checker.js:4:58)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
(node:44648) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:44648) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[peertube.bydisk.com:80] 2018-03-26 21:37:04.183 info: Database peertube_prod is ready.
[peertube.bydisk.com:80] 2018-03-26 21:37:05.210 error: Cannot install application. {
  "name": "SequelizeDatabaseError",
  "parent": {
    "name": "error",
    "length": 83,
    "severity": "ERROR",
    "code": "42601",
    "position": "51",
    "file": "scan.l",
    "line": "911",
    "routine": "base_yyerror",
    "sql": "SELECT t.typname enum_name, array_agg(e.enumlabel ORDER BY enumsortorder) enum_value FROM pg_type t JOIN pg_enum e ON t.oid = e.enumtypid JOIN pg_catalog.pg_namespace n ON n.oid = t.typnamespace WHERE n.nspname = 'public' AND t.typname='enum_actor_type' GROUP BY 1"
  },
  "original": {
    "name": "error",
    "length": 83,
    "severity": "ERROR",
    "code": "42601",
    "position": "51",
    "file": "scan.l",
    "line": "911",
    "routine": "base_yyerror",
    "sql": "SELECT t.typname enum_name, array_agg(e.enumlabel ORDER BY enumsortorder) enum_value FROM pg_type t JOIN pg_enum e ON t.oid = e.enumtypid JOIN pg_catalog.pg_namespace n ON n.oid = t.typnamespace WHERE n.nspname = 'public' AND t.typname='enum_actor_type' GROUP BY 1"
  },
  "sql": "SELECT t.typname enum_name, array_agg(e.enumlabel ORDER BY enumsortorder) enum_value FROM pg_type t JOIN pg_enum e ON t.oid = e.enumtypid JOIN pg_catalog.pg_namespace n ON n.oid = t.typnamespace WHERE n.nspname = 'public' AND t.typname='enum_actor_type' GROUP BY 1"
}
npm ERR! code ELIFECYCLE
npm ERR! errno 255
npm ERR! peertube@1.0.0-beta.1 start: `node dist/server`
npm ERR! Exit status 255
npm ERR! 
npm ERR! Failed at the peertube@1.0.0-beta.1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-03-26T13_37_05_227Z-debug.log

**Comment by Chocobozzz** [comment]
You ffmpeg lacks support of x264
