### ISSUE TITLE
Cannot read property 'res' of undefined" error when trying to log in

### ISSUE THREAD

**Issue by mothguib** [Chocobozzz/PeerTube#4059]
**Describe the current behavior**

I have the "Cannot read property 'res' of undefined" error when I try to log in with any user.

**Steps to reproduce:**

* Upgrading PeerTube from version 2.4 to 3.0

**Additional information**

* PostgreSQL version: 11

* PeerTube instance:
  * URL:
  * version: 3.1
  * NodeJS version: 10.22
  * Ffmpeg version:  4.1.6-1~deb10u1

* Browser name, version and platforms on which you could reproduce the bug: Firefox, Chromium

* Server logs if relevant (`journalctl` or `/var/www/peertube/storage/logs/`):

```
May 09 20:16:51  peertube[26518]: [<myhost>:443] 2021-05-09 20:16:51.152 warn: Login error. {
May 09 20:16:51 peertube[26518]:   "err": {
May 09 20:16:51 peertube[26518]:     "statusCode": 503,
May 09 20:16:51 peertube[26518]:     "status": 503,
May 09 20:16:51 peertube[26518]:     "code": 503,
May 09 20:16:51 peertube[26518]:     "message": "Cannot read property 'res' of undefined",
May 09 20:16:51 peertube[26518]:     "name": "server_error",
May 09 20:16:51 peertube[26518]:     "inner": {
May 09 20:16:51 peertube[26518]:       "stack": "TypeError: Cannot read property 'res' of undefined\n    at Object.<anonymous> (/var/www/peertube/versions/peertube-v3.1.0/dist/server/lib/oauth-model.js:89:34)\n    at Generator.next (<anonymous>)\n    at /var/www/peertube/versions/peertube-v3.1.0/node_modules/tslib/tslib.js:117:75\n    at new Promise (<anonymous>)\n    at Object.__awaiter (/var/www/peertube/versions/peertube-v3.1.0/node_modules/tslib/tslib.js:113:16)\n    at Object.getUser (/var/www/peertube/versions/peertube-v3.1.0/dist/server/lib/oauth-model.js:88:20)\n    at Object.tryCatcher (/var/www/peertube/versions/peertube-v3.1.0/node_modules/express-oauth-server/node_modules/oauth2-server/node_modules/bluebird/js/release/util.js:16:23)\n    at Object.<anonymous> (/var/www/peertube/versions/peertube-v3.1.0/node_modules/express-oauth-server/node_modules/oauth2-server/node_modules/bluebird/js/release/method.js:15:34)\n    at PasswordGrantType.getUser (/var/www/peertube/versions/peertube-v3.1.0/node_modules/express-oauth-server/node_modules/oauth2-server/lib/grant-types/password-grant-type.js:91:43)\n    at PasswordGrantType.<anonymous> (/var/www/peertube/versions/peertube-v3.1.0/node_modules/express-oauth-server/node_modules/oauth2-server/lib/grant-types/password-grant-type.js:63:19)\n    at PasswordGrantType.tryCatcher (/var/www/peertube/versions/peertube-v3.1.0/node_modules/express-oauth-server/node_modules/oauth2-server/node_modules/bluebird/js/release/util.js:16:23)\n    at Promise._settlePromiseFromHandler (/var/www/peertube/versions/peertube-v3.1.0/node_modules/express-oauth-server/node_modules/oauth2-server/node_modules/bluebird/js/release/promise.js:512:31)\n    at Promise._settlePromise (/var/www/peertube/versions/peertube-v3.1.0/node_modules/express-oauth-server/node_modules/oauth2-server/node_modules/bluebird/js/release/promise.js:569:18)\n    at Promise._settlePromiseCtx (/var/www/peertube/versions/peertube-v3.1.0/node_modules/express-oauth-server/node_modules/oauth2-server/node_modules/bluebird/js/release/promise.js:606:10)\n    at Async._drainQueue (/var/www/peertube/versions/peertube-v3.1.0/node_modules/express-oauth-server/node_modules/oauth2-server/node_modules/bluebird/js/release/async.js:138:12)\n    at Async._drainQueues (/var/www/peertube/versions/peertube-v3.1.0/node_modules/express-oauth-server/node_modules/oauth2-server/node_modules/bluebird/js/release/async.js:143:10)\n    at Immediate.Async.drainQueues (/var/www/peertube/versions/peertube-v3.1.0/node_modules/express-oauth-server/node_modules/oauth2-server/node_modules/bluebird/js/release/async.js:17:14)\n    at runCallback (timers.js:705:18)\n    at tryOnImmediate (timers.js:676:5)\n    at processImmediate (timers.js:658:5)",
May 09 20:16:51 peertube[26518]:       "message": "Cannot read property 'res' of undefined"
May 09 20:16:51 peertube[26518]:     },
May 09 20:16:51 peertube[26518]:     "stack": "server_error: Cannot read property 'res' of undefined\n    at new ServerError (/var/www/peertube/versions/peertube-v3.1.0/node_modules/express-oauth-server/node_modules/oauth2-server/lib/errors/server-error.js:25:14)\n    at TokenHandler.<anonymous> (/var/www/peertube/versions/peertube-v3.1.0/node_modules/express-oauth-server/node_modules/oauth2-server/lib/handlers/token-handler.js:102:13)\n    at TokenHandler.tryCatcher (/var/www/peertube/versions/peertube-v3.1.0/node_modules/express-oauth-server/node_modules/oauth2-server/node_modules/bluebird/js/release/util.js:16:23)\n    at Promise._settlePromiseFromHandler (/var/www/peertube/versions/peertube-v3.1.0/node_modules/express-oauth-server/node_modules/oauth2-server/node_modules/bluebird/js/release/promise.js:512:31)\n    at Promise._settlePromise (/var/www/peertube/versions/peertube-v3.1.0/node_modules/express-oauth-server/node_modules/oauth2-server/node_modules/bluebird/js/release/promise.js:569:18)\n    at Promise._settlePromise0 (/var/www/peertube/versions/peertube-v3.1.0/node_modules/express-oauth-server/node_modules/oauth2-server/node_modules/bluebird/js/release/promise.js:614:10)\n    at Promise._settlePromises (/var/www/peertube/versions/peertube-v3.1.0/node_modules/express-oauth-server/node_modules/oauth2-server/node_modules/bluebird/js/release/promise.js:689:18)\n    at Async._drainQueue (/var/www/peertube/versions/peertube-v3.1.0/node_modules/express-oauth-server/node_modules/oauth2-server/node_modules/bluebird/js/release/async.js:133:16)\n    at Async._drainQueues (/var/www/peertube/versions/peertube-v3.1.0/node_modules/express-oauth-server/node_modules/oauth2-server/node_modules/bluebird/js/release/async.js:143:10)\n    at Immediate.Async.drainQueues [as _onImmediate] (/var/www/peertube/versions/peertube-v3.1.0/node_modules/express-oauth-server/node_modules/oauth2-server/node_modules/bluebird/js/release/async.js:17:14)\n    at runCallback (timers.js:705:18)\n    at tryOnImmediate (timers.js:676:5)\n    at processImmediate (timers.js:658:5)"
```

**Comment by mothguib** [comment]
Thank you for your answer.

Actually I was wrong in my description, I well installed version **3.1**, and **not 3.0**. 

I also used `npm` instead of `yarn` for the installation because it did not work, but it worked perfectly with `npm`.

**Comment by Chocobozzz** [comment]
You must not use `npm` because it won't respect our yarn lockfile. Seems to be the cause of your issue. Try to reinstall PeerTube, and use `yarn` as stated in the documentation. If you have a problem with the yarn command, please paste the error.
