### ISSUE TITLE
Error with Self-Signed Certificate when using SMTP/Postfix to send emails

### ISSUE THREAD

**Issue by DeadSuperHero** [Chocobozzz/PeerTube#4060]
Trying to set up PeerTube to use SMTP to send emails. My current test workflow is to visit the login page, and attempt to sent a Forgotten Password email. I'm using Ubuntu 20.04, with Nginx and Postfix. My configuration currently has STARTTLS enabled.

First, here's the configuration file I currently have (truncated, of course):
```
# SMTP server to send emails
smtp:
  # smtp or sendmail
  transport: smtp
  # Path to sendmail command. Required if you use sendmail transport
  sendmail: null
  hostname: spectra.video
  port: 25
  username: null
  password: null
  tls: false
  disable_starttls: false
  ca_file: null # Used for self signed certificates
  from_address: 'broadcast@spectra.video'
```

Here's the log output I'm currently getting:
```
May 10 00:18:54 spectra.video peertube[909149]:   "component": "smtp-connection",
May 10 00:18:54 spectra.video peertube[909149]:   "sid": "e75iBq6vL8g",
May 10 00:18:54 spectra.video peertube[909149]:   "tnx": "network",
May 10 00:18:54 spectra.video peertube[909149]:   "localAddress": "xx.xx.xx.xx",
May 10 00:18:54 spectra.video peertube[909149]:   "localPort": 51786,
May 10 00:18:54 spectra.video peertube[909149]:   "remoteAddress": "(same as local)",
May 10 00:18:54 spectra.video peertube[909149]:   "remotePort": 25
May 10 00:18:54 spectra.video peertube[909149]: }
May 10 00:18:54 spectra.video peertube[909149]: [spectra.video:443] 2021-05-10 00:18:54.093 error: self signed certificate {
May 10 00:18:54 spectra.video peertube[909149]:   "component": "smtp-connection",
May 10 00:18:54 spectra.video peertube[909149]:   "sid": "e75iBq6vL8g"
May 10 00:18:54 spectra.video peertube[909149]: }
May 10 00:18:54 spectra.video peertube[909149]: [spectra.video:443] 2021-05-10 00:18:54.094 error: Send Error: self signed certificate {
May 10 00:18:54 spectra.video peertube[909149]:   "component": "mail",
May 10 00:18:54 spectra.video peertube[909149]:   "err": {
May 10 00:18:54 spectra.video peertube[909149]:     "stack": "Error: self signed certificate\n    at TLSSocket.onConnectSecure (_tls_wrap.js:1260:34)\n    at TLSSocket.emit (events.js:196:13)\n    at TLSSocket._finishInit (_tls_wrap.js:737:8)\n    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:569:12)",
May 10 00:18:54 spectra.video peertube[909149]:     "message": "self signed certificate",
May 10 00:18:54 spectra.video peertube[909149]:     "code": "ESOCKET",
May 10 00:18:54 spectra.video peertube[909149]:     "command": "CONN"
May 10 00:18:54 spectra.video peertube[909149]:   },
May 10 00:18:54 spectra.video peertube[909149]:   "tnx": "transport",
May 10 00:18:54 spectra.video peertube[909149]:   "action": "send"
May 10 00:18:54 spectra.video peertube[909149]: }
May 10 00:18:54 spectra.video peertube[909149]: [spectra.video:443] 2021-05-10 00:18:54.095 error: Error in email sender. {
May 10 00:18:54 spectra.video peertube[909149]:   "err": {
May 10 00:18:54 spectra.video peertube[909149]:     "stack": "Error: self signed certificate\n    at TLSSocket.onConnectSecure (_tls_wrap.js:1260:34)\n    at TLSSocket.emit (events.js:196:13)\n    at TLSSocket._finishInit (_tls_wrap.js:737:8)\n    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:569:12)",
May 10 00:18:54 spectra.video peertube[909149]:     "message": "self signed certificate",
May 10 00:18:54 spectra.video peertube[909149]:     "code": "ESOCKET",
May 10 00:18:54 spectra.video peertube[909149]:     "command": "CONN"
May 10 00:18:54 spectra.video peertube[909149]:   }
May 10 00:18:54 spectra.video peertube[909149]: }
May 10 00:18:54 spectra.video peertube[909149]: [spectra.video:443] 2021-05-10 00:18:54.096 info: Connection closed {
May 10 00:18:54 spectra.video peertube[909149]:   "component": "smtp-connection",
May 10 00:18:54 spectra.video peertube[909149]:   "sid": "e75iBq6vL8g",
May 10 00:18:54 spectra.video peertube[909149]:   "tnx": "network"
May 10 00:18:54 spectra.video peertube[909149]: }
May 10 00:18:54 spectra.video peertube[909149]: [spectra.video:443] 2021-05-10 00:18:54.097 info: Connection closed {
May 10 00:18:54 spectra.video peertube[909149]:   "component": "smtp-connection",
May 10 00:18:54 spectra.video peertube[909149]:   "sid": "e75iBq6vL8g",
May 10 00:18:54 spectra.video peertube[909149]:   "tnx": "network"
May 10 00:18:54 spectra.video peertube[909149]: }
```

I'm currently at a loss on how to move forward with this. What do I need to do?

**Comment by DeadSuperHero** [comment]
This is what I get if I instead try to disable STARTTLS and instead use the "TLS" option:

```
May 10 04:24:49 spectra.video peertube[915113]:  {
May 10 04:24:49 spectra.video peertube[915113]:   "component": "mail",
May 10 04:24:49 spectra.video peertube[915113]:   "err": {
May 10 04:24:49 spectra.video peertube[915113]:     "stack": "Error: 140082499636096:error:1408F10B:SSL routines:ssl3_get_record:wrong version number:../deps/openssl/openssl/ssl/record/ssl3_record.c:332:\n",
May 10 04:24:49 spectra.video peertube[915113]:     "message": "140082499636096:error:1408F10B:SSL routines:ssl3_get_record:wrong version number:../deps/openssl/openssl/ssl/record/ssl3_record.c:332:\n",
May 10 04:24:49 spectra.video peertube[915113]:     "library": "SSL routines",
May 10 04:24:49 spectra.video peertube[915113]:     "function": "ssl3_get_record",
May 10 04:24:49 spectra.video peertube[915113]:     "reason": "wrong version number",
May 10 04:24:49 spectra.video peertube[915113]:     "code": "ESOCKET",
May 10 04:24:49 spectra.video peertube[915113]:     "command": "CONN"
May 10 04:24:49 spectra.video peertube[915113]:   },
May 10 04:24:49 spectra.video peertube[915113]:   "tnx": "transport",
May 10 04:24:49 spectra.video peertube[915113]:   "action": "send"
May 10 04:24:49 spectra.video peertube[915113]: }
May 10 04:24:49 spectra.video peertube[915113]: [spectra.video:443] 2021-05-10 04:24:49.341 error: Error in email sender. {
May 10 04:24:49 spectra.video peertube[915113]:   "err": {
May 10 04:24:49 spectra.video peertube[915113]:     "stack": "Error: 140082499636096:error:1408F10B:SSL routines:ssl3_get_record:wrong version number:../deps/openssl/openssl/ssl/record/ssl3_record.c:332:\n",
May 10 04:24:49 spectra.video peertube[915113]:     "message": "140082499636096:error:1408F10B:SSL routines:ssl3_get_record:wrong version number:../deps/openssl/openssl/ssl/record/ssl3_record.c:332:\n",
May 10 04:24:49 spectra.video peertube[915113]:     "library": "SSL routines",
May 10 04:24:49 spectra.video peertube[915113]:     "function": "ssl3_get_record",
May 10 04:24:49 spectra.video peertube[915113]:     "reason": "wrong version number",
May 10 04:24:49 spectra.video peertube[915113]:     "code": "ESOCKET",
May 10 04:24:49 spectra.video peertube[915113]:     "command": "CONN"
May 10 04:24:49 spectra.video peertube[915113]:   }
May 10 04:24:49 spectra.video peertube[915113]: }
```

**Comment by Chocobozzz** [comment]
Hello,

If you use a self signed certificate your need to fill the `ca_file` config key

**Comment by DeadSuperHero** [comment]
Hey @Chocobozzz, thanks for following up! 

I'm a little curious as to what the ca_file is supposed to be, and how I'm supposed to make it. Would something like this be an acceptable way to do it? https://www.digitalocean.com/community/tutorials/how-to-set-up-and-configure-a-certificate-authority-ca-on-ubuntu-20-04

**Comment by DeadSuperHero** [comment]
> @DeadSuperHero you better use a real SMTP to send mails from your PeerTube Instance.
> Sending mails from your PeerTube IP could be passed as a SPAM or REJECTED from a lot of mail providers Microsoft in first.
> You should use the SMTP you get from your ISP, your own personnal mail, your domain provider etc...
> 
> Exemple if you have an outlook.com address, go on google and type SMTP settings outlook.com and you will get the details to fill in your PeerTube settings.
> 
> You won't get trouble in the future with that.

With respect - I get what you're trying to say in terms of going after a reliable, reputable SMTP provider for mail distribution. I understand the nature of that beast. But, it isn't actually a helpful answer for what I'm trying to do. I'm trying to get the thing to send mail in the first place, without having to tie in some walled-garden corporate service.

**Comment by Chocobozzz** [comment]
> I'm a little curious as to what the ca_file is supposed to be

It should be the file containing the certificate of your SMTP self signed certificate
