### ISSUE TITLE
Plugin failing when NodeJS is upgraded

### ISSUE THREAD

**Issue by JohnXLivingston** [Chocobozzz/PeerTube#4139]
**Describe the current behavior**

Peertube 3.2.0 is out. It requires node 12. Debian buster comes with node 10. So I had to upgrade node before installing Peertube 3.2.0.

On my server, it brokes an old plugin that I made : https://framagit.org/Livingston/peertube-plugin-georegister

With following errors:
```
error[30/05/2021 à 20:37:32] Cannot register plugin georegister, skipping.

{
  "err": {
    "stack": "/var/www/peertube/storage/plugins/node_modules/whois/index.js:1\n(function (exports, require, module, __filename, __dirname) { #!/usr/bin/env node\n                                                              ^\n\nSyntaxError: Invalid or unexpected token\n    at new Script (vm.js:88:7)\n    at createScript (vm.js:261:10)\n    at Object.runInThisContext (vm.js:309:10)\n    at wrapSafe (internal/modules/cjs/loader.js:902:15)\n    at Module._compile (internal/modules/cjs/loader.js:963:27)\n    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)\n    at Module.load (internal/modules/cjs/loader.js:863:32)\n    at Function.Module._load (internal/modules/cjs/loader.js:708:14)\n    at Module.require (internal/modules/cjs/loader.js:887:19)\n    at require (internal/modules/cjs/helpers.js:74:18)\n    at Object.<anonymous> (/var/www/peertube/storage/plugins/node_modules/whois-json/index.js:2:10)\n    at Module._compile (internal/modules/cjs/loader.js:999:30)\n    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)\n    at Module.load (internal/modules/cjs/loader.js:863:32)\n    at Function.Module._load (internal/modules/cjs/loader.js:708:14)\n    at Module.require (internal/modules/cjs/loader.js:887:19)\n    at require (internal/modules/cjs/helpers.js:74:18)\n    at Object.<anonymous> (/var/www/peertube/storage/plugins/node_modules/peertube-plugin-georegister/main.js:1:77)\n    at Module._compile (internal/modules/cjs/loader.js:999:30)\n    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)\n    at Module.load (internal/modules/cjs/loader.js:863:32)\n    at Function.Module._load (internal/modules/cjs/loader.js:708:14)\n    at Module.require (internal/modules/cjs/loader.js:887:19)\n    at require (internal/modules/cjs/helpers.js:74:18)\n    at PluginManager.<anonymous> (/var/www/peertube/versions/peertube-v3.2.0/dist/server/lib/plugins/plugin-manager.js:312:29)\n    at Generator.next (<anonymous>)\n    at /var/www/peertube/versions/peertube-v3.2.0/node_modules/tslib/tslib.js:117:75\n    at new Promise (<anonymous>)",
    "message": "Invalid or unexpected token"
  }
}
```

I think this error is caused by the node upgrade. To fix it, I simply had to uninstall and then install again the plugin.

I assume that some plugin dependencies need to be rebuild when changing node version.

**Steps to reproduce:**

1. node 10 + Peertube 3.1.0 + plugin https://framagit.org/Livingston/peertube-plugin-georegister
2. upgrade to node 12 (in my case, I also upgraded to Peertube 3.2.0, but I think it can be reproduced without)
3. start Peertube: the plugin startup failed.

**Describe the expected behavior**

I don't know if Peertube could do something automatically? Launch yarn install in the plugins directory at startup? Detect node version changes on startup, and run yarn install if needed?

**Additional information**

* PeerTube instance:
  * version: 3.1.0 / 3.2.0
  * NodeJS version: 10 / 12

**Comment by Chocobozzz** [comment]
Should be implemented by https://github.com/Chocobozzz/PeerTube/commit/c795e19663a93c24908a7318975f820bac63164f
