### ISSUE TITLE
ffmpeg: height not divisible by 2

### ISSUE THREAD

**Issue by verymilan** [Chocobozzz/PeerTube#4155]
A user just raised the following ffmpeg error with their upload:

````
[libx264 @ 0x55efac651400] height not divisible by 2 (1164x767)
Error initializing output stream 0:0 -- Error while opening encoder for output stream #0:0 - maybe incorrect parameters such as bit_rate, rate, width or height
[aac @ 0x55efac649e80] Qavg: 64859.430
[aac @ 0x55efac649e80] 2 frames left in the queue on closing
Conversion failed!
````

They say a previously working upload was created with the same settings as this failed one. Uploading to YouTube was working. A quick search found that in theory, different ffmpeg settings could work [(source)](https://stackoverflow.com/questions/20847674/ffmpeg-libx264-height-not-divisible-by-2), so i thought creating this issue might be a good idea...

running peertube on the latest release with ffmpeg `4.1.6-1~deb10u1`

**Comment by BiLachner** [comment]
Additional Information: The Video was recorded with VokoscreenNG on a OpenSuse-Linux System.

**Comment by Chocobozzz** [comment]
Please paste logs above this error so I can understand the context

**Comment by verymilan** [comment]
Alright, here is the complete output:

````
error[3.6.2021, 10:29:22] Error in ffmpeg.

{
  "stdout": "",
  "stderr": "ffmpeg version 4.1.6-1~deb10u1 Copyright (c) 2000-2020 the FFmpeg developers\n  built with gcc 8 (Debian 8.3.0-6)\n  configuration: --prefix=/usr --extra-version='1~deb10u1' --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-avresample --disable-filter=resample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librsvg --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opengl --enable-sdl2 --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared\n  libavutil      56. 22.100 / 56. 22.100\n  libavcodec     58. 35.100 / 58. 35.100\n  libavformat    58. 20.100 / 58. 20.100\n  libavdevice    58.  5.100 / 58.  5.100\n  libavfilter     7. 40.101 /  7. 40.101\n  libavresample   4.  0.  0 /  4.  0.  0\n  libswscale      5.  3.100 /  5.  3.100\n  libswresample   3.  3.100 /  3.  3.100\n  libpostproc    55.  3.100 / 55.  3.100\nInput #0, matroska,webm, from 'peertube/storage/videos/37aec4ab-9f3d-41e6-beda-bd7c34a3956a-767.mkv':\n  Metadata:\n    encoder         : GStreamer matroskamux version 1.16.3\n    creation_time   : 2021-06-03T07:21:39.000000Z\n  Duration: 00:06:21.16, start: 0.000000, bitrate: 412 kb/s\n    Stream #0:0(eng): Video: vp8, yuv420p(tv, bt709, progressive), 1164x767, SAR 1:1 DAR 1164:767, 25 fps, 25 tbr, 1k tbn, 1k tbc (default)\n    Metadata:\n      title           : Video\n    Stream #0:1(eng): Audio: vorbis, 44100 Hz, stereo, fltp (default)\n    Metadata:\n      title           : Audio\nStream mapping:\n  Stream #0:0 -> #0:0 (vp8 (native) -> h264 (libx264))\n  Stream #0:1 -> #0:1 (vorbis (native) -> aac (native))\nPress [q] to stop, [?] for help\n[libx264 @ 0x55efac651400] height not divisible by 2 (1164x767)\nError initializing output stream 0:0 -- Error while opening encoder for output stream #0:0 - maybe incorrect parameters such as bit_rate, rate, width or height\n[aac @ 0x55efac649e80] Qavg: 64859.430\n[aac @ 0x55efac649e80] 2 frames left in the queue on closing\nConversion failed!\n"
}

error[3.6.2021, 10:29:22] Cannot execute job 10500 in queue video-transcoding.

{
  "payload": {
    "type": "optimize-to-webtorrent",
    "videoUUID": "37aec4ab-9f3d-41e6-beda-bd7c34a3956a",
    "isNewVideo": true
  },
  "err": {
    "stack": "Error: ffmpeg exited with code 1: Conversion failed!\n\n    at ChildProcess.<anonymous> (peertube/versions/peertube-v3.2.1/node_modules/fluent-ffmpeg/lib/processor.js:182:22)\n    at ChildProcess.emit (events.js:314:20)\n    at ChildProcess.EventEmitter.emit (domain.js:483:12)\n    at Process.ChildProcess._handle.onexit (internal/child_process.js:276:12)",
    "message": "ffmpeg exited with code 1: Conversion failed!\n"
  }
}
````

**Comment by Chocobozzz** [comment]
Thanks, should be fixed by https://github.com/Chocobozzz/PeerTube/commit/318b0bd0c2ff575f35d51d97327f77abfecd6b86
