### ISSUE TITLE
Suddenly Unable to Upload on Update (v3.2.0 to v3.2.1)

### ISSUE THREAD

**Issue by ChanoSan** [Chocobozzz/PeerTube#4171]
**Describe the current behavior**
Following an update to v3.2.1, I was suddenly unable to upload videos from file via the browser as usual. Instead an error message popped up, and the file upload failed (screenshot included below). 

![image](https://user-images.githubusercontent.com/48997871/121052784-a8edbe00-c7f5-11eb-9771-f2a105be3621.png)

Rolling back to v3.2.0 did not resolve the issue, so this may be unrelated to the update, but I was able to successfully upload while the instance was at v3.2.0 before, and this failure only occurred after updating to v3.2.1 so I cannot rule out a connection.

Behavior persists with different files, so it does not appear to be an error with specific file format. Nothing in the logs indicates any kind of failure that I can see, or if it does I am unable to find/understand it.

All other PeerTube functionality is the same as usual. I can log in, and view videos normally. Only uploading appears to be affected.

**Steps to reproduce:**

1. Update to v3.2.1
2. Attempt to upload video file
3. Error message appears

**Describe the expected behavior**
Able to upload videos successfully

**Additional information**

* PeerTube instance: アノニマスの見解
  * URL: peertube.anon-kenkai.com
  * version: v3.2.0 (rolled back from v3.2.1)
  * NodeJS version: v12.18.0
  * Ffmpeg version:  v4.2.4

* Browser name, version and platforms on which you could reproduce the bug: Firefox 89.0 (64 bit, Linux)
* Link to browser console log if relevant:
* Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`):

**Comment by rigelk** [comment]
Do you have logs?

**Comment by ChanoSan** [comment]
Additional: attempted to upload from mobile (LineageOS, Icecat). Same error occurred, all other functionality normal as above.

While scanning journalctl during upload attempts, the following error seemed to occur at roughly the same time. I am uncertain whether it is related to the issue, but will include for the sake of being thorough:

```
Jun 07 16:11:36 anon-kenkai peertube[893]:   "err": {
Jun 07 16:11:36 anon-kenkai peertube[893]:     "stack": "HTTPError: Response code 403 (Forbidden)\n    at Request.<anonymous> (/var/www/peertube/versions/peertube-v3.2.0/node_modules/got/dist/source/as-promise/index.js:117:42)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (internal/process/task_queues.js:97:5)",
Jun 07 16:11:36 anon-kenkai peertube[893]:     "message": "Response code 403 (Forbidden)",
Jun 07 16:11:36 anon-kenkai peertube[893]:     "name": "HTTPError",
Jun 07 16:11:36 anon-kenkai peertube[893]:     "responseBody": {
Jun 07 16:11:36 anon-kenkai peertube[893]:       "error": "Forbidden"
Jun 07 16:11:36 anon-kenkai peertube[893]:     },
Jun 07 16:11:36 anon-kenkai peertube[893]:     "statusCode": 403
Jun 07 16:11:36 anon-kenkai peertube[893]:   }
Jun 07 16:11:36 anon-kenkai peertube[893]: }
```

**Comment by ChanoSan** [comment]
> Do you have logs?

I could provide some, I'm just not certain exactly where to find anything useful. I can see a recent error log in the Admin page, but I'm not sure if this is relevant either:

```
error[6/8/2021, 1:09:12 AM] Error in controller.

{
  "err": "RequestError: connect ETIMEDOUT 5.39.74.86:443\n    at ClientRequest.<anonymous> (/var/www/peertube/versions/peertube-v3.2.0/node_modules/got/dist/source/core/index.js:956:111)\n    at Object.onceWrapper (events.js:422:26)\n    at ClientRequest.emit (events.js:327:22)\n    at ClientRequest.EventEmitter.emit (domain.js:482:12)\n    at ClientRequest.origin.emit (/var/www/peertube/versions/peertube-v3.2.0/node_modules/@szmarczak/http-timer/dist/source/index.js:39:20)\n    at TLSSocket.socketErrorListener (_http_client.js:426:9)\n    at TLSSocket.emit (events.js:315:20)\n    at TLSSocket.EventEmitter.emit (domain.js:482:12)\n    at emitErrorNT (internal/streams/destroy.js:92:8)\n    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)\n    at processTicksAndRejections (internal/process/task_queues.js:84:21)\n    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1141:16)"
}
```

**Comment by ChanoSan** [comment]
Correction: I was mistaken. I had not uploaded following v3.2.0 update. And I recall at the time of updating having to update my nginx files with the upload_resume endpoint. I may have caused my own error here, will attempt to resolve and report back.

**Comment by ChanoSan** [comment]
I appear to have discovered the source of the error, although I find it somewhat confusing.

During the update to v3.2.0, there were instructions to edit the peertube config in /etc/nginx/sites-available with the "upload-resumable" endpoint ( https://github.com/Chocobozzz/PeerTube/blob/develop/support/nginx/peertube#L81 )

During this step, I discovered that I had been using quite an old nginx config file for a long time, that bore almost no resemblance to the example in /var/www/peertube/versions/peertube-v3.2.1/support/nginx

In my confusion, I attempted to append the new line into the existing nginx config, and everything seemed to work on reload. However, when I commented out the upload-resumable endpoint and reloaded nginx, I am now able to upload again.

I did attempt to copy the new example peertube nginx config file over and edit it to include the relevant information, but doing so resulted in the peertube page no longer being able to load in the browser. This in spite of both the peertube and nginx services running with no error, and other services on the same machine using nginx working fine.

I am at a loss for what to do now... not adding the upload-resumable endpoint as instructed seems like it will cause problems in the future and is a bad idea, but removing it restores full functionality to my peertube instance. I would like to update my nginx configuration files to resemble the latest examples, but I do not have the technical skills to be able to do so successfully without assistance.

I can provide logs of any relevant information upon request.

**Comment by rigelk** [comment]
> I am at a loss for what to do now... not adding the upload-resumable endpoint as instructed seems like it will cause problems in the future and is a bad idea, but removing it restores full functionality to my peertube instance. I would like to update my nginx configuration files to resemble the latest examples, but I do not have the technical skills to be able to do so successfully without assistance.
> 
> I can provide logs of any relevant information upon request.

I see. Could you share with us your current nginx config, and the one you ended up with trying to update it?

**Comment by ChanoSan** [comment]
> I see. Could you share with us your current nginx config, and the one you ended up with trying to update it?

Here is my current working nginx config. The upload-resumable section was added during the update to v3.2.0, and commenting it out as it is here allowed uploading to work again:

```
server {
    if ($host = peertube.anon-kenkai.com) {
        return 301 https://$host$request_uri;
    } # managed by Certbot


  listen 80;
  listen [::]:80;
  server_name peertube.anon-kenkai.com;

  access_log /var/log/nginx/peertube.anon-kenkai.com.access.log;
  error_log /var/log/nginx/peertube.anon-kenkai.com.error.log;

  location /.well-known/acme-challenge/ {
    default_type "text/plain";
    root /var/www/certbot;
  }
  location / { return 301 https://$host$request_uri; }


}

server {
  listen 443 ssl http2;
  listen [::]:443 ssl http2;
  server_name peertube.anon-kenkai.com;

  # For example with certbot (you need a certificate to run https)
    ssl_certificate /etc/letsencrypt/live/peertube.anon-kenkai.com/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/peertube.anon-kenkai.com/privkey.pem; # managed by Certbot

  # Security hardening (as of 11/02/2018)
  ssl_protocols TLSv1.2; # TLSv1.3, TLSv1.2 if nginx >= 1.13.0
  ssl_prefer_server_ciphers on;
  # Remove ECDHE-RSA-AES256-SHA if you don't want compatibility with Android 4
  ssl_ciphers 'ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA256:ECDHE-RSA-AES256-SHA';
  # ssl_ecdh_curve secp384r1; # Requires nginx >= 1.1.0, not compatible with import-videos script
  ssl_session_timeout  10m;
  ssl_session_cache shared:SSL:10m;
  ssl_session_tickets off; # Requires nginx >= 1.5.9
  ssl_stapling on; # Requires nginx >= 1.3.7
  ssl_stapling_verify on; # Requires nginx => 1.3.7

  # Configure with your resolvers
  # resolver $DNS-IP-1 $DNS-IP-2 valid=300s;
  # resolver_timeout 5s;

  # Enable compression for JS/CSS/HTML bundle, for improved client load times.
  # It might be nice to compress JSON, but leaving that out to protect against potential
  # compression+encryption information leak attacks like BREACH.
  gzip on;
  gzip_types text/css application/javascript;
  gzip_vary on;

  # If you have a small /var/lib partition, it could be interesting to store temp nginx uploads in a different place
  # See https://nginx.org/en/docs/http/ngx_http_core_module.html#client_body_temp_path
  # client_body_temp_path /var/www/peertube/storage/nginx/;

  # Enable HSTS
  # Tells browsers to stick with HTTPS and never visit the insecure HTTP
  # version. Once a browser sees this header, it will only visit the site over
  # HTTPS for the next 2 years: (read more on hstspreload.org)
  #add_header Strict-Transport-Security "max-age=63072000; includeSubDomains";

  access_log /var/log/nginx/peertube.anon-kenkai.com.access.log;
  error_log /var/log/nginx/peertube.anon-kenkai.com.error.log;

  location ^~ '/.well-known/acme-challenge' {
    default_type "text/plain";
    root /var/www/certbot;
  }

  # Bypass PeerTube for performance reasons. Could be removed
  location ~ ^/client/(.*\.(js|css|png|svg|woff2|otf|ttf|woff|eot))$ {
    add_header Cache-Control "public, max-age=31536000, immutable";

    alias /var/www/peertube/peertube-latest/client/dist/$1;
  }

  # Bypass PeerTube for performance reasons. Could be removed
  location ~ ^/static/(thumbnails|avatars)/ {
    if ($request_method = 'OPTIONS') {
      add_header 'Access-Control-Allow-Origin' '*';
      add_header 'Access-Control-Allow-Methods' 'GET, OPTIONS';
      add_header 'Access-Control-Allow-Headers' 'Range,DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type';
      add_header 'Access-Control-Max-Age' 1728000;
      add_header 'Content-Type' 'text/plain charset=UTF-8';
      add_header 'Content-Length' 0;
      return 204;
    }

    add_header 'Access-Control-Allow-Origin' '*';
    add_header 'Access-Control-Allow-Methods' 'GET, OPTIONS';
    add_header 'Access-Control-Allow-Headers' 'Range,DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type';

    # Cache 2 hours
    add_header Cache-Control "public, max-age=7200";

    root /var/www/peertube/storage;

    rewrite ^/static/(thumbnails|avatars)/(.*)$ /$1/$2 break;
    try_files $uri /;
  }

  location / {
    proxy_pass http://127.0.0.1:9000;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header Host $host;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

    # This is the maximum upload size, which roughly matches the maximum size of a video file
    # you can send via the API or the web interface. By default this is 8GB, but administrators
    # can increase or decrease the limit. Currently there's no way to communicate this limit
    # to users automatically, so you may want to leave a note in your instance 'about' page if
    # you change this.
    #
    # Note that temporary space is needed equal to the total size of all concurrent uploads.
    # This data gets stored in /var/lib/nginx by default, so you may want to put this directory
    # on a dedicated filesystem.
    #
    client_max_body_size 8G;

    proxy_connect_timeout       600;
    proxy_send_timeout          600;
    proxy_read_timeout          600;
    send_timeout                600;
  }

  # Bypass PeerTube for performance reasons. Could be removed
  location ~ ^/static/(webseed|redundancy|streaming-playlists)/ {
    # Clients usually have 4 simultaneous webseed connections, so the real limit is 3MB/s per client
    set $peertube_limit_rate 800k;

    # Increase rate limit in HLS mode, because we don't have multiple simultaneous connections
    if ($request_uri ~ -fragmented.mp4$) {
      set $peertube_limit_rate 5000k;
    }

    # Use this with nginx >= 1.17.0
    # limit_rate $peertube_limit_rate;
    # Or this if your nginx < 1.17.0
    set $limit_rate $peertube_limit_rate;
    limit_rate_after 5000k;

    if ($request_method = 'OPTIONS') {
      add_header 'Access-Control-Allow-Origin' '*';
      add_header 'Access-Control-Allow-Methods' 'GET, OPTIONS';
      add_header 'Access-Control-Allow-Headers' 'Range,DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type';
      add_header 'Access-Control-Max-Age' 1728000;
      add_header 'Content-Type' 'text/plain charset=UTF-8';
      add_header 'Content-Length' 0;
      return 204;
    }

    if ($request_method = 'GET') {
      add_header 'Access-Control-Allow-Origin' '*';
      add_header 'Access-Control-Allow-Methods' 'GET, OPTIONS';
      add_header 'Access-Control-Allow-Headers' 'Range,DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type';

      # Don't spam access log file with byte range requests
      access_log off;
    }

    root /var/www/peertube/storage;

    rewrite ^/static/webseed/(.*)$ /videos/$1 break;
    rewrite ^/static/redundancy/(.*)$ /redundancy/$1 break;
    rewrite ^/static/streaming-playlists/(.*)$ /streaming-playlists/$1 break;

    try_files $uri /;
  }

  # Websocket tracker
  location /tracker/socket {
    # Peers send a message to the tracker every 15 minutes
    # Don't close the websocket before this time
    proxy_read_timeout 1200s;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
    proxy_http_version 1.1;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header Host $host;
    proxy_pass http://127.0.0.1:9000;
  }

#  location = /api/v1/videos/upload-resumable {
#    client_max_body_size    0;
#    proxy_request_buffering off;
#
#    try_files /dev/null @api;
#  }


  location /socket.io {
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header Host $host;

    proxy_pass http://127.0.0.1:9000;

    # enable WebSockets
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
  }

    ssl_certificate /etc/letsencrypt/live/peertube.anon-kenkai.com/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/peertube.anon-kenkai.com/privkey.pem; # managed by Certbot

}
```
Here is my attempt to edit the example nginx conf file from /var/www/peertube/versions/peertube-v3.2.1/support/nginx for my instance. Reloading nginx with this config and attempting to access the instance resulted in a browser error where it was unable to resolve the page, although both peertube and nginx services were running successfully on the server itself:

```
# Minimum Nginx version required:  1.13.0 (released Apr 25, 2017)
# Please check your Nginx installation features the following modules via 'nginx -V':
# STANDARD HTTP MODULES: Core, Proxy, Rewrite, Access, Gzip, Headers, HTTP/2, Log, Real IP, SSL, Thread Pool, Upstream, AIO Multithreading.
# THIRD PARTY MODULES:   None.

server {
  listen 80;
  listen [::]:80;
  server_name peertube.anon-kenkai.com;

  location /.well-known/acme-challenge/ {
    default_type "text/plain";
    root /var/www/certbot;
  }
  location / { return 301 https://$host$request_uri; }
}

upstream backend {
  server peertube.anon-kenkai.com;
}

server {
  listen 443 ssl http2;
  listen [::]:443 ssl http2;
  server_name peertube.anon-kenkai.com;

  access_log /var/log/nginx/peertube.access.log; # reduce I/0 with buffer=10m flush=5m
  error_log  /var/log/nginx/peertube.error.log;

  ##
  # Certificates
  # you need a certificate to run in production. see https://letsencrypt.org/
  ##
  ssl_certificate     /etc/letsencrypt/live/peertube.anon-kenkai.com/fullchain.pem;
  ssl_certificate_key /etc/letsencrypt/live/peertube.anon-kenkai.com/privkey.pem;

  location ^~ '/.well-known/acme-challenge' {
    default_type "text/plain";
    root /var/www/certbot;
  }

  ##
  # Security hardening (as of Nov 15, 2020)
  # based on Mozilla Guideline v5.6
  ##

  ssl_protocols             TLSv1.2 TLSv1.3;
  ssl_prefer_server_ciphers on;
  ssl_ciphers               ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA256; # add ECDHE-RSA-AES256-SHA if you want compatibility with Android 4
  ssl_session_timeout       1d; # defaults to 5m
  ssl_session_cache         shared:SSL:10m; # estimated to 40k sessions
  ssl_session_tickets       off;
  ssl_stapling              on;
  ssl_stapling_verify       on;
  # HSTS (https://hstspreload.org), requires to be copied in 'location' sections that have add_header directives
  #add_header Strict-Transport-Security "max-age=63072000; includeSubDomains";

  ##
  # Application
  ##

  location @api {
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header Host            $host;
    proxy_set_header X-Real-IP       $remote_addr;

    client_max_body_size  100k; # default is 1M

    proxy_connect_timeout 10m;
    proxy_send_timeout    10m;
    proxy_read_timeout    10m;
    send_timeout          10m;

    proxy_pass http://backend;
  }

  location / {
    try_files /dev/null @api;
  }

  location = /api/v1/videos/upload-resumable {
    client_max_body_size    0;
    proxy_request_buffering off;

    try_files /dev/null @api;
  }

  location = /api/v1/videos/upload {
    limit_except POST HEAD { deny all; }

    # This is the maximum upload size, which roughly matches the maximum size of a video file.
    # Note that temporary space is needed equal to the total size of all concurrent uploads.
    # This data gets stored in /var/lib/nginx by default, so you may want to put this directory
    # on a dedicated filesystem.
    client_max_body_size                      12G; # default is 1M
    add_header            X-File-Maximum-Size 8G always; # inform backend of the set value in bytes before mime-encoding (x * 1.4 >= client_max_body_size)

    try_files /dev/null @api;
  }

  location ~ ^/api/v1/(videos|video-playlists|video-channels|users/me) {
    client_max_body_size                      3M; # default is 1M
    add_header            X-File-Maximum-Size 2M always; # inform backend of the set value in bytes before mime-encoding (x * 1.4 >= client_max_body_size)

    try_files /dev/null @api;
  }

  ##
  # Websocket
  ##

  location @api_websocket {
    proxy_http_version 1.1;
    proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header   Host            $host;
    proxy_set_header   X-Real-IP       $remote_addr;
    proxy_set_header   Upgrade         $http_upgrade;
    proxy_set_header   Connection      "upgrade";

    proxy_pass http://backend;
  }

  location /socket.io {
    try_files /dev/null @api_websocket;
  }

  location /tracker/socket {
    # Peers send a message to the tracker every 15 minutes
    # Don't close the websocket before then
    proxy_read_timeout 15m; # default is 60s

    try_files /dev/null @api_websocket;
  }

  ##
  # Performance optimizations
  # For extra performance please refer to https://github.com/denji/nginx-tuning
  ##

  root /var/www/peertube/storage;

  # Enable compression for JS/CSS/HTML, for improved client load times.
  # It might be nice to compress JSON/XML as returned by the API, but
  # leaving that out to protect against potential BREACH attack.
  gzip              on;
  gzip_vary         on;
  gzip_types        # text/html is always compressed by HttpGzipModule
                    text/css
                    application/javascript
                    font/truetype
                    font/opentype
                    application/vnd.ms-fontobject
                    image/svg+xml;
  gzip_min_length   1000; # default is 20 bytes
  gzip_buffers      16 8k;
  gzip_comp_level   2; # default is 1

  client_body_timeout       30s; # default is 60
  client_header_timeout     10s; # default is 60
  send_timeout              10s; # default is 60
  keepalive_timeout         10s; # default is 75
  resolver_timeout          10s; # default is 30
  reset_timedout_connection on;
  proxy_ignore_client_abort on;

  tcp_nopush                on; # send headers in one piece
  tcp_nodelay               on; # don't buffer data sent, good for small data bursts in real time

  # If you have a small /var/lib partition, it could be interesting to store temp nginx uploads in a different place
  # See https://nginx.org/en/docs/http/ngx_http_core_module.html#client_body_temp_path
  #client_body_temp_path /var/www/peertube/storage/nginx/;

  # Bypass PeerTube for performance reasons. Optional.
  # Should be consistent with client-overrides assets list in /server/controllers/client.ts
  location ~ ^/client/(assets/images/(icons/icon-36x36\.png|icons/icon-48x48\.png|icons/icon-72x72\.png|icons/icon-96x96\.png|icons/icon-144x144\.png|icons/icon-192x192\.png|icons/icon-512x512\.png|logo\.svg|favicon\.png))$ {
    add_header Cache-Control "public, max-age=31536000, immutable"; # Cache 1 year

    root /var/www/peertube;

    try_files /storage/client-overrides/$1 /peertube-latest/client/dist/$1 @api;
  }

  # Bypass PeerTube for performance reasons. Optional.
  location ~ ^/client/(.*\.(js|css|png|svg|woff2|otf|ttf|woff|eot))$ {
    add_header Cache-Control "public, max-age=31536000, immutable"; # Cache 1 year

    alias /var/www/peertube/peertube-latest/client/dist/$1;
  }

  # Bypass PeerTube for performance reasons. Optional.
  location ~ ^/static/(thumbnails|avatars)/ {
    if ($request_method = 'OPTIONS') {
      add_header Access-Control-Allow-Origin  '*';
      add_header Access-Control-Allow-Methods 'GET, OPTIONS';
      add_header Access-Control-Allow-Headers 'Range,DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type';
      add_header Access-Control-Max-Age       1728000; # Preflight request can be cached 20 days
      add_header Content-Type                 'text/plain charset=UTF-8';
      add_header Content-Length               0;
      return 204;
    }

    add_header Access-Control-Allow-Origin    '*';
    add_header Access-Control-Allow-Methods   'GET, OPTIONS';
    add_header Access-Control-Allow-Headers   'Range,DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type';
    add_header Cache-Control                  "public, max-age=7200"; # Cache response 2 hours

    rewrite ^/static/(.*)$ /$1 break;

    try_files $uri @api;
  }

  # Bypass PeerTube for performance reasons. Optional.
  location ~ ^/static/(webseed|redundancy|streaming-playlists)/ {
    limit_rate_after            5M;

    # Clients usually have 4 simultaneous webseed connections, so the real limit is 3MB/s per client
    set $peertube_limit_rate    800k;

    # Increase rate limit in HLS mode, because we don't have multiple simultaneous connections
    if ($request_uri ~ -fragmented.mp4$) {
      set $peertube_limit_rate  5M;
    }

    # Use this line with nginx >= 1.17.0
    #limit_rate $peertube_limit_rate;
    # Or this line if your nginx < 1.17.0
    set $limit_rate $peertube_limit_rate;

    if ($request_method = 'OPTIONS') {
      add_header Access-Control-Allow-Origin  '*';
      add_header Access-Control-Allow-Methods 'GET, OPTIONS';
      add_header Access-Control-Allow-Headers 'Range,DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type';
      add_header Access-Control-Max-Age       1728000; # Preflight request can be cached 20 days
      add_header Content-Type                 'text/plain charset=UTF-8';
      add_header Content-Length               0;
      return 204;
    }

    if ($request_method = 'GET') {
      add_header Access-Control-Allow-Origin  '*';
      add_header Access-Control-Allow-Methods 'GET, OPTIONS';
      add_header Access-Control-Allow-Headers 'Range,DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type';

      # Don't spam access log file with byte range requests
      access_log off;
    }

    # Enabling the sendfile directive eliminates the step of copying the data into the buffer
    # and enables direct copying data from one file descriptor to another.
    sendfile on;
    sendfile_max_chunk 1M; # prevent one fast connection from entirely occupying the worker process. should be > 800k.
    aio threads;

    # Use this in tandem with fuse-mounting i.e. https://docs.joinpeertube.org/admin-remote-storage
    # to serve files directly from a public bucket without proxying.
    # Assumes you have buckets named after the storage subdirectories, i.e. 'videos', 'redundancy', etc.
    #set $cdn <your S3-compatiable bucket public url mounted via fuse>;
    #rewrite ^/static/webseed/(.*)$ $cdn/videos/$1 redirect;
    #rewrite ^/static/(.*)$         $cdn/$1        redirect;
    rewrite ^/static/webseed/(.*)$ /videos/$1 break;
    rewrite ^/static/(.*)$         /$1        break;

    try_files $uri @api;
  }
}
```

I cannot necessarily rule out a typo during my attempts to edit the above nginx conf, but to the best of my knowledge this resulted in the error described above.

**Comment by Chocobozzz** [comment]
Hello,

Please use the updated nginx config and paste errors from browser logs/server logs logged at the time you accessed your website (because you pasted logs that seem unrelated to your issue).

**Comment by rigelk** [comment]
@ChanoSan I see what caused errors on both your configs. You cannot just add the `upload-resumable` block to the old config, as it calls the `@api` alias, which we only define in the more recent config files.

However, no need to keep you old config, as there is really only one thing causing your error in the new config: you replaced the `PEERTUBE_HOST` with the same value as `WEBSERVER_HOST`. The former should hold the internal adress of your running PeerTube service (likely `localhost:9000`), while the latter holds your domain.

```diff
upstream backend {
-  server peertube.anon-kenkai.com;
+  server localhost:9000;
}
```

**Comment by ChanoSan** [comment]
I used the updated nginx config, reloaded nginx, and restarted PeerTube. As before, Firefox was unable to resolve the page (screenshot below)
![firefox_error](https://user-images.githubusercontent.com/48997871/121142016-894aaa00-c876-11eb-9ab3-a415773a6b3f.png)

Both peertube and nginx service are running without error. Journalctl also shows no errors from peertube.

Below are the contents of peertube.anon-kenkai.com.error.log in /var/log/nginx/

```
2021/06/08 00:01:46 [error] 2722#2722: *37413 open() "/var/www/peertube/peertube-latest/client/dist/en-us/common.da31b8306a27ee10172c.js" failed (2: No such file or directory), client: 207.46.13.43, server: peertube.anon-kenkai.com, request: "GET /client/en-us/common.da31b8306a27ee10172c.js HTTP/2.0", host: "peertube.anon-kenkai.com"
2021/06/08 03:10:31 [error] 2722#2722: *50549 upstream prematurely closed connection while reading response header from upstream, client: 66.249.76.93, server: peertube.anon-kenkai.com, request: "GET /lazy-static/previews/7293218f-8471-4392-a310-afda9e02668c.jpg HTTP/1.1", upstream: "http://127.0.0.1:9000/lazy-static/previews/7293218f-8471-4392-a310-afda9e02668c.jpg", host: "peertube.anon-kenkai.com"
2021/06/08 04:11:32 [error] 2722#2722: *54329 open() "/var/www/peertube/peertube-latest/client/dist/en-US/client/assets/images/favicon.png" failed (2: No such file or directory), client: 2600:3c00::f03c:92ff:fe46:1f57, server: peertube.anon-kenkai.com, request: "GET /client/en-US/client/assets/images/favicon.png?8ba48259f84655698edce22c123c03ea9fdadd0a HTTP/2.0", host: "peertube.anon-kenkai.com"
2021/06/08 04:43:01 [error] 2722#2722: *56136 open() "/var/www/peertube/peertube-latest/client/dist/en-us/7.99f13a0d3aa2c8fa23e9.js" failed (2: No such file or directory), client: 207.46.13.27, server: peertube.anon-kenkai.com, request: "GET /client/en-us/7.99f13a0d3aa2c8fa23e9.js HTTP/2.0", host: "peertube.anon-kenkai.com"
2021/06/08 05:07:15 [error] 2722#2722: *57129 upstream prematurely closed connection while reading response header from upstream, client: 117.95.164.223, server: peertube.anon-kenkai.com, request: "GET /lazy-static/previews/cc732287-e6ed-4168-973d-578c715d3a05.jpg HTTP/1.1", upstream: "http://127.0.0.1:9000/lazy-static/previews/cc732287-e6ed-4168-973d-578c715d3a05.jpg", host: "peertube.anon-kenkai.com"
2021/06/08 07:05:10 [error] 2722#2722: *62272 upstream prematurely closed connection while reading response header from upstream, client: 66.249.76.94, server: peertube.anon-kenkai.com, request: "GET /lazy-static/previews/2fb65f23-cd85-443d-bb0f-6cfdce34648c.jpg HTTP/1.1", upstream: "http://127.0.0.1:9000/lazy-static/previews/2fb65f23-cd85-443d-bb0f-6cfdce34648c.jpg", host: "peertube.anon-kenkai.com"
2021/06/08 07:14:44 [error] 2722#2722: *62751 open() "/var/www/peertube/peertube-latest/client/dist/en-us/main.5add5f19a3e9ceb8d549.js" failed (2: No such file or directory), client: 40.77.167.13, server: peertube.anon-kenkai.com, request: "GET /client/en-us/main.5add5f19a3e9ceb8d549.js HTTP/2.0", host: "peertube.anon-kenkai.com"

```

There are other error logs that show older timestamps, but I'm not certain if they're relevant. Can provide them if requested.

**Comment by ChanoSan** [comment]
> @ChanoSan I see what caused errors on both your configs...

Oh goodness, that was silly of me...
I just made the fix, it all works as normal as again. Thanks again for the assistance.

Should I be copying over the example nginx config and updating on every version upgrade, then?
This wasn't stipulated in the upgrade instructions, but I'm somewhat new at this so perhaps it was assumed.
