### ISSUE TITLE
Uppercase extensions are not recognized. 

### ISSUE THREAD

**Issue by JohnXLivingston** [Chocobozzz/PeerTube#4200]
**Describe the current behavior**

I just saw this error log on my instance:
```
error[20/06/2021 à 11:02:48] Error in controller.

{
  "err": "SequelizeValidationError: Validation error: \".MOV\" is not a valid extname.\n    at InstanceValidator._validate (/var/www/peertube/versions/peertube-v3.2.1/node_modules/sequelize/lib/instance-validator.js:78:13)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (internal/process/task_queues.js:97:5)\n    at async InstanceValidator._validateAndRunHooks (/var/www/peertube/versions/peertube-v3.2.1/node_modules/sequelize/lib/instance-validator.js:111:7)\n    at async InstanceValidator.validate (/var/www/peertube/versions/peertube-v3.2.1/node_modules/sequelize/lib/instance-validator.js:93:12)\n    at async VideoFileModel.save (/var/www/peertube/versions/peertube-v3.2.1/node_modules/sequelize/lib/model.js:3877:7)"
}
```

I think this is because the file extension is in uppercase.

**Steps to reproduce:**

1. Try to upload a file with .MOV extenstion

**Describe the expected behavior**

File extension should be case insensitive.

**Additional information**

* PeerTube instance:
  * URL: https://www.yiny.org
  * version: 3.2.1
  * NodeJS version: 12
  * Ffmpeg version:

**Comment by tcitworld** [comment]
Duplicate from https://github.com/Chocobozzz/PeerTube/issues/4152

**Comment by JohnXLivingston** [comment]
Sorry for the duplicate.
