### ISSUE TITLE
Unable to configure PeerTube for reverse proxy

### ISSUE THREAD

**Issue by taiBsu** [Chocobozzz/PeerTube#4211]
I am installing PeerTube via [docker-compose](https://hub.docker.com/r/chocobozzz/peertube). After downloading the default `docker-compose.yml` and `.env` file, I first deleted the webserver and certbot sections from the `docker-compose.yml` file since I have an Apache2 instance running on my server.

For the Apache2 instance, I have set up a reverse proxy:
```
ProxyPass /peer http://peertube:9000
ProxyPassReverse /peer http://peertube:9000
```

In my docker-compose.yml file, I set up everything to be suitable for the proxy:
```
// ...
  ports:
    - "9000:9000"
  networks:
    - mynetwork

// ...
# make sure the peertube instance is reachable from my webserver
networks:
  mynetwork:
    external: true
```

Then, I had a look at my `.env` file, where there are some entries I'm not completely sure if they're correct:

```
# ...

# does this have to be mydomain.com or mydomain.com/peer?
PEERTUBE_WEBSERVER_HOSTNAME=mydomain.com
# ...

# do I have to use 80 or 443 here? As you can see, my Apache reverse proxy config is set via http but I'm opening mydomain.com/peer via https.
PEERTUBE_WEBSERVER_PORT=443
PEERTUBE_WEBSERVER_HTTPS=true
PEERTUBE_TRUST_PROXY=["127.0.0.1", "loopback", "172.18.0.0/16"]
```

Now, I can open the peertube interface via my local network on `http://myserverhostname:9000/`, however I'm getting an error in the lower right corner:
```
Fehler
Referenzen des OAuth-Clients können nicht abgerufen werden: undefined. Stellen Sie sicher, dass PeerTube korrekt konfiguriert ist (Ordner config/), speziell der Abschnitt "webserver".

``` 
Trying to open PeerTube via `mydomain.com/peer` just gives me a blank page. Opening the chrome dev console shows me some resource failure errors:

```
GET https://mydomain.com/client/de-DE/styles.67b145d7647a702b2937.css net::ERR_ABORTED 404 (Not Found)
peer:88 GET https://mydomain.com/client/de-DE/runtime.f945b94d39838d536162.js net::ERR_ABORTED 404 (Not Found)
peer:88 GET https://mydomain.com/client/de-DE/main.863751cd38df15662e51.js net::ERR_ABORTED 404 (Not Found)
peer:88 GET https://mydomain.com/client/de-DE/polyfills.408ee4470981084fd5d0.js net::ERR_ABORTED 404 (Not Found)
peer:88 GET https://mydomain.com/client/de-DE/runtime.f945b94d39838d536162.js net::ERR_ABORTED 404 (Not Found)
favicon.png:1 GET https://mydomain.com/client/assets/images/favicon.png?34726c60092549a6759c3c294eafa76b322f5f3b 404 (Not Found)
manifest.webmanifest:1 GET https://mydomain.com/manifest.webmanifest?b0883429ff8620684c7ac5145f29a617775cadb1 404 (Not Found)
manifest.webmanifest:1 Manifest: Line: 1, column: 1, Syntax error.
```

Looking at this, it feels like there is some context / web root variable not yet defined, is that possible? If so, where can I set it?

When trying to open the `Administration page`, I keep getting an `invalid client: client is invalid` error. `docker-compose logs` output:

```
peertube    | [mydomain.com:443] 2021-06-28 14:48:33.374 warn: Login error {
peertube    |   "err": {
peertube    |     "statusCode": 400,
peertube    |     "status": 400,
peertube    |     "code": 400,
peertube    |     "message": "Invalid client: client is invalid",
peertube    |     "name": "invalid_client",
peertube    |     "stack": "invalid_client: Invalid client: client is invalid\n    at new InvalidClientError (/app/node_modules/oauth2-server/lib/errors/invalid-client-error.js:26:14)\n    at Object.<anonymous> (/app/dist/server/lib/auth/oauth.js:31:19)\n    at Generator.next (<anonymous>)\n    at fulfilled (/app/node_modules/tslib/tslib.js:114:62)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (internal/process/task_queues.js:97:5)"
peertube    |   }
peertube    | }
```

**Additional information**

* PeerTube instance:
  * version: 3.2.1 (production-buster)
  * NodeJS version: docker version
  * Ffmpeg version: docker version
  * Redis version: docker version
  * PostgreSQL version: docker version

Thanks a lot in advance.

**Comment by taiBsu** [comment]
I solved it. I had misconfigured my apache2.
