### ISSUE TITLE
Cannot execute migration 0640

### ISSUE THREAD

**Issue by Vitriia** [Chocobozzz/PeerTube#4220]
**Describe the current behavior**
Peertube is restarting continuously because of database issue after upgrading to current version (3.2.1~ynh2). 
It's the Yunohost flavor but i haven't found any documentation on both of repo (here and yunohost flavor one)

**Describe the expected behavior**
I think peertube is expected to do a migration about "unique keys" but it fail at a moment and just restart to fail again. I don't know if it's an yunohost migration or a peertube one that's why i'm asking here in a second time (yunohost issue [here](https://github.com/YunoHost-Apps/peertube_ynh/issues/246))

```
journalctl:
[…]
  - Jun 18 01:09:08 peertube__2[25390]: [peertube.domain.tld:443] 2021-06-18 01:09:08.023 info: Begin migrations.
  - Jun 18 01:09:08 peertube__2[25390]: [peertube.domain.tld:443] 2021-06-18 01:09:08.028 info: Executing 0640-unique-keys.js migration script.
  - Jun 18 01:09:44 peertube__2[25390]: [peertube.domain.tld:443] 2021-06-18 01:09:44.780 error: Cannot execute migration 0640. {
  - Jun 18 01:09:44 peertube__2[25390]:   "err": {
  - Jun 18 01:09:44 peertube__2[25390]:     "stack": "SequelizeForeignKeyConstraintError: update or delete on table \"videoChannel\" violates foreign key constraint \"video_channelId_fkey\" on table \"video\"\n    at Query.formatError (/var/www/peertube__2/node_modules/sequelize/lib/dialects/postgres/query.js:315:16)\n    at Query.run (/var/www/peertube__2/node_modules/sequelize/lib/dialects/postgres/query.js:87:18)\n    at processTicksAndRejections (internal/process/task_queues.js:95:5)\n    at async /var/www/peertube__2/node_modules/sequelize/lib/sequelize.js:619:16",
  - Jun 18 01:09:44 peertube__2[25390]:     "message": "update or delete on table \"videoChannel\" violates foreign key constraint \"video_channelId_fkey\" on table \"video\"",
  - Jun 18 01:09:44 peertube__2[25390]:     "name": "SequelizeForeignKeyConstraintError",
  - Jun 18 01:09:44 peertube__2[25390]:     "parent": {
  - Jun 18 01:09:44 peertube__2[25390]:       "stack": "error: update or delete on table \"videoChannel\" violates foreign key constraint \"video_channelId_fkey\" on table \"video\"\n    at Parser.parseErrorMessage (/var/www/peertube__2/node_modules/pg-protocol/dist/parser.js:287:98)\n    at Parser.handlePacket (/var/www/peertube__2/node_modules/pg-protocol/dist/parser.js:126:29)\n    at Parser.parse (/var/www/peertube__2/node_modules/pg-protocol/dist/parser.js:39:38)\n    at Socket.<anonymous> (/var/www/peertube__2/node_modules/pg-protocol/dist/index.js:11:42)\n    at Socket.emit (events.js:375:28)\n    at Socket.emit (domain.js:470:12)\n    at addChunk (internal/streams/readable.js:290:12)\n    at readableAddChunk (internal/streams/readable.js:265:9)\n    at Socket.Readable.push (internal/streams/readable.js:204:10)\n    at TCP.onStreamRead (internal/stream_base_commons.js:188:23)",
  - Jun 18 01:09:44 peertube__2[25390]:       "message": "update or delete on table \"videoChannel\" violates foreign key constraint \"video_channelId_fkey\" on table \"video\"",
  - Jun 18 01:09:44 peertube__2[25390]:       "length": 275,
  - Jun 18 01:09:44 peertube__2[25390]:       "name": "error",
  - Jun 18 01:09:44 peertube__2[25390]:       "severity": "ERROR",
  - Jun 18 01:09:44 peertube__2[25390]:       "code": "23503",
  - Jun 18 01:09:44 peertube__2[25390]:       "detail": "Key (id)=(6650) is still referenced from table \"video\".",
  - Jun 18 01:09:44 peertube__2[25390]:       "schema": "public",
  - Jun 18 01:09:44 systemd[1]: peertube__2.service: Main process exited, code=exited, status=255/EXCEPTION
  - Jun 18 01:09:45 peertube__2[25390]:       "table": "video",
  - Jun 18 01:09:45 peertube__2[25390]:       "constraint": "video_channelId_fkey",
  - Jun 18 01:09:45 peertube__2[25390]:       "file": "ri_triggers.c",
  - Jun 18 01:09:45 peertube__2[25390]:       "line": "2797",
  - Jun 18 01:09:45 peertube__2[25390]:       "routine": "ri_ReportViolation",
  - Jun 18 01:09:45 peertube__2[25390]:       "sql": "DELETE FROM \"actor\" v1 USING (SELECT MIN(id) as id, \"preferredUsername\", \"serverId\" FROM \"actor\" GROUP BY \"preferredUsername\", \"serverId\" HAVING COUNT(*) > 1 AND \"serverId\" IS NOT NULL) v2 WHERE v1.\"preferredUsername\" = v2.\"preferredUsername\" AND v1.\"serverId\" = v2.\"serverId\" AND v1.id <> v2.id"
  - Jun 18 01:09:45 peertube__2[25390]:     },
  - Jun 18 01:09:45 peertube__2[25390]:     "sql": "DELETE FROM \"actor\" v1 USING (SELECT MIN(id) as id, \"preferredUsername\", \"serverId\" FROM \"actor\" GROUP BY \"preferredUsername\", \"serverId\" HAVING COUNT(*) > 1 AND \"serverId\" IS NOT NULL) v2 WHERE v1.\"preferredUsername\" = v2.\"preferredUsername\" AND v1.\"serverId\" = v2.\"serverId\" AND v1.id <> v2.id",
  - Jun 18 01:09:45 peertube__2[25390]:     "fields": null,
  - Jun 18 01:09:45 peertube__2[25390]:     "table": "videoChannel",
  - Jun 18 01:09:45 peertube__2[25390]:     "index": "video_channelId_fkey"
  - Jun 18 01:09:45 peertube__2[25390]:   }
  - Jun 18 01:09:45 peertube__2[25390]: }
  - Jun 18 01:09:44 systemd[1]: peertube__2.service: Failed with result 'exit-code'.
  - Jun 18 01:09:44 systemd[1]: peertube__2.service: Service RestartSec=100ms expired, scheduling restart.
  - Jun 18 01:09:44 systemd[1]: peertube__2.service: Scheduled restart job, restart counter is at 2624.
  - Jun 18 01:09:44 systemd[1]: Stopped PeerTube daemon.
  - Jun 18 01:09:44 systemd[1]: Started PeerTube daemon.

```

Thx for your help

**Comment by Chocobozzz** [comment]
Could you use `psql` and run `\d "videoChannel"` please?

**Comment by Vitriia** [comment]
Done, the answer :
`Did not find any relation named ""videoChannel"".`

**Comment by Chocobozzz** [comment]
Have you executed `sudo -u postgres psql peertube_prod` (`peertube_prod` should be your database name)

**Comment by Vitriia** [comment]
Nope (i'm really bad with databases)
Here is the result
```
# \d "videoChannel"
                                        Table "public.videoChannel"
   Column    |           Type           | Collation | Nullable |                  Default                   
-------------+--------------------------+-----------+----------+--------------------------------------------
 id          | integer                  |           | not null | nextval('"videoChannel_id_seq"'::regclass)
 name        | character varying(255)   |           | not null | 
 description | character varying(1000)  |           |          | NULL::character varying
 support     | character varying(1000)  |           |          | NULL::character varying
 actorId     | integer                  |           |          | 
 accountId   | integer                  |           | not null | 
 createdAt   | timestamp with time zone |           | not null | 
 updatedAt   | timestamp with time zone |           | not null | 
Indexes:
    "videoChannel_pkey" PRIMARY KEY, btree (id)
    "video_channel_account_id" btree ("accountId")
    "video_channel_actor_id" btree ("actorId")
    "video_channel_name_trigram" gin (lower(immutable_unaccent(name::text)) gin_trgm_ops)
Foreign-key constraints:
    "videoChannel_accountId_fkey" FOREIGN KEY ("accountId") REFERENCES account(id) ON UPDATE CASCADE ON DELETE CASCADE
    "videoChannel_actorId_fkey" FOREIGN KEY ("actorId") REFERENCES actor(id) ON UPDATE CASCADE ON DELETE CASCADE
Referenced by:
    TABLE ""videoPlaylist"" CONSTRAINT "videoPlaylist_videoChannelId_fkey" FOREIGN KEY ("videoChannelId") REFERENCES "videoChannel"(id) ON UPDATE CASCADE ON DELETE CASCADE
    TABLE "video" CONSTRAINT "video_channelId_fkey" FOREIGN KEY ("channelId") REFERENCES "videoChannel"(id) ON UPDATE CASCADE
```

**Comment by Chocobozzz** [comment]
Thanks, please try `alter table "video" drop constraint "video_channelId_fkey", add constraint "video_channelId_fkey" foreign key ("channelId") REFERENCES "videoChannel"(id) ON UPDATE CASCADE ON DELETE CASCADE;` and restart peertube

**Comment by Vitriia** [comment]
It works !
(Thx)
