### ISSUE TITLE
"File upload disabled." randomly appeared

### ISSUE THREAD

**Issue by taiBsu** [Chocobozzz/PeerTube#4243]
I'm using the docker version of PeerTube, version 3.2.1.
After installing and configuring the container, I was able to upload a video. Then, I stepped aside the application for a couple of days. Now I wanted to upload another video, but I keep getting the message "File upload disabled." for whatever reason.

I looked into the logs, which showed me quite a lot of error messages:

```
error[9.7.2021, 10:54:59] Error in job queue activitypub-http-unicast.
{
  "err": {
    "stack": "ReplyError: MISCONF Redis is configured to save RDB snapshots, but it is currently not able to persist on disk. Commands that may modify the data set are disabled, because this instance is configured to report errors during writes if RDB snapshotting fails (stop-writes-on-bgsave-error option). Please check the Redis logs for details about the RDB error.\n    at parseError (/app/node_modules/redis-parser/lib/parser.js:179:12)\n    at parseType (/app/node_modules/redis-parser/lib/parser.js:302:14)",
    "message": "MISCONF Redis is configured to save RDB snapshots, but it is currently not able to persist on disk. Commands that may modify the data set are disabled, because this instance is configured to report errors during writes if RDB snapshotting fails (stop-writes-on-bgsave-error option). Please check the Redis logs for details about the RDB error.",
    "command": {
      "name": "brpoplpush",
      "args": [
        "bull-peer.example.org:activitypub-http-unicast:wait",
        "bull-peer.example.org:activitypub-http-unicast:active",
        "5"
      ]
    }
  }
}
error[9.7.2021, 10:54:59] Error in job queue activitypub-http-unicast.
{
  "err": {
    "stack": "ReplyError: MISCONF Redis is configured to save RDB snapshots, but it is currently not able to persist on disk. Commands that may modify the data set are disabled, because this instance is configured to report errors during writes if RDB snapshotting fails (stop-writes-on-bgsave-error option). Please check the Redis logs for details about the RDB error.\n    at parseError (/app/node_modules/redis-parser/lib/parser.js:179:12)\n    at parseType (/app/node_modules/redis-parser/lib/parser.js:302:14)",
    "message": "MISCONF Redis is configured to save RDB snapshots, but it is currently not able to persist on disk. Commands that may modify the data set are disabled, because this instance is configured to report errors during writes if RDB snapshotting fails (stop-writes-on-bgsave-error option). Please check the Redis logs for details about the RDB error.",
    "command": {
      "name": "brpoplpush",
      "args": [
        "bull-peer.example.org:activitypub-http-unicast:wait",
        "bull-peer.example.org:activitypub-http-unicast:active",
        "5"
      ]
    }
  }
}
```

(this list goes on for quite a while)

Can someone relate to this problem? I'm not aware of anything I could have changed on the container. Restarting (or docker-compose down && docker-compose up -d) didn't help.

Thanks in advance.

**Comment by Chocobozzz** [comment]
Hello, 

Please paste the URL of your instance so I can check the config/console log.

**Comment by taiBsu** [comment]
Hi,
thanks for getting back. Turned out that "file upload disabled" only shows up when my peertube theme is set to `pacerip`. When changing to the default theme, everything works fine again. However, my instance URL is peer.taibsu.net.

**Comment by Chocobozzz** [comment]
I also reproduced this error using `pacerip` theme. Then you should report the bug on their bug tracker :)
