### ISSUE TITLE
Error fetching remote video without precision

### ISSUE THREAD

**Issue by rhaamo** [Chocobozzz/PeerTube#426]
* **PeerTube version or URL: v1.0.0-beta.2**
* **NodeJS version: v9.8.0**

* **What is the expected behaviour?**
Error message with precise error of what happened

* **What do you see instead?**
Error message without any precision

* **Server log if useful (Gist/Pastebin...):**

from ```peertube.log```:
```
{"level":"info","message":"Receiving inbox requests for 1 activities by https://thinkerview.video/accounts/peertube.","splat":[1,"https://thinkerview.video/accounts/peertube"],"timestamp":"2018-03-28T08:05:26.629Z","label":"tube.otter.sh:443"}
{"level":"info","message":"Fetching remote video https://thinkerview.video/videos/watch/df5471eb-0a8c-46ab-a3e6-0dee3e3845cd.","splat":["https://thinkerview.video/videos/watch/df5471eb-0a8c-46ab-a3e6-0dee3e3845cd"],"timestamp":"2018-03-28T08:05:26.694Z","label":"tube.otter.sh:443"}
{"level":"warn","message":"Cannot process activity Create.","splat":["Create"],"meta":{"error":"Error: Cannot fetch remote video with url: https://thinkerview.video/videos/watch/df5471eb-0a8c-46ab-a3e6-0dee3e3845cd\n    at Object.<anonymous> (/var/www/peertube/versions/peertube-master/dist/server/lib/activitypub/videos.js:181:23)\n    at Generator.next (<anonymous>)\n    at fulfilled (/var/www/peertube/versions/peertube-master/dist/server/lib/activitypub/videos.js:4:58)\n    at <anonymous>"},"timestamp":"2018-03-28T08:05:26.873Z","label":"tube.otter.sh:443"}
```

How to know what really happened ? Network issue ? Bug in peertube ?

**Comment by Chocobozzz** [comment]
It's because the remote activity is not valid (description issue). Should be fixed with https://github.com/Chocobozzz/PeerTube/commit/c73e83da283c6d4eb094e384d59c4f8eb221507d

Thanks for the issue @rhaamo

**Comment by rhaamo** [comment]
Thanks! Looks fixed I don't see anymore errors.
