### ISSUE TITLE
Error (core dumped) when creating administrator [Docker-alpine] 

### ISSUE THREAD

**Issue by MikaXII** [Chocobozzz/PeerTube#427]
I can't launch any container with alpine linux, I didn't try with stretch.
On branch 1.0.0-beta.2

Logs first launch :
```
> peertube@1.0.0-beta.2 start /app
> node dist/server

[peertube.geekael.fr:443] 2018-03-28 10:05:47.026 info: Database peertube is ready.
[peertube.geekael.fr:443] 2018-03-28 10:05:49.950 info: Creating Application table.
[peertube.geekael.fr:443] 2018-03-28 10:05:49.951 info: Creating application account.
[peertube.geekael.fr:443] 2018-03-28 10:05:50.038 info: Generating a RSA key...
[peertube.geekael.fr:443] 2018-03-28 10:05:50.159 info: Creating a default OAuth Client.
[peertube.geekael.fr:443] 2018-03-28 10:05:50.189 info: Client id: iwjyq9paqxo4ghng3pkp12elgm5ntijq
[peertube.geekael.fr:443] 2018-03-28 10:05:50.189 info: Client secret: 7BfCsCwW1CKppscLmFhhZYJtj3UYQPm5
[peertube.geekael.fr:443] 2018-03-28 10:05:50.198 info: Creating the administrator.
Segmentation fault (core dumped)
npm ERR! code ELIFECYCLE
npm ERR! errno 139
npm ERR! peertube@1.0.0-beta.2 start: `node dist/server`
npm ERR! Exit status 139
npm ERR! 
npm ERR! Failed at the peertube@1.0.0-beta.2 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/peertube/.npm/_logs/2018-03-28T10_05_51_170Z-debug.log
```
Logs after each restart : 
```
[peertube.geekael.fr:443] 2018-03-28 10:05:59.205 info: Database peertube is ready.
[peertube.geekael.fr:443] 2018-03-28 10:05:59.380 info: Creating the administrator.
Segmentation fault (core dumped)
npm ERR! code ELIFECYCLE
npm ERR! errno 139
npm ERR! peertube@1.0.0-beta.2 start: `node dist/server`
npm ERR! Exit status 139
npm ERR! 
npm ERR! Failed at the peertube@1.0.0-beta.2 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/peertube/.npm/_logs/2018-03-28T10_06_00_387Z-debug.log

```

npm logs : 
```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'start' ]
2 info using npm@5.6.0
3 info using node@v8.10.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle peertube@1.0.0-beta.2~prestart: peertube@1.0.0-beta.2
6 info lifecycle peertube@1.0.0-beta.2~start: peertube@1.0.0-beta.2
7 verbose lifecycle peertube@1.0.0-beta.2~start: unsafe-perm in lifecycle true
8 verbose lifecycle peertube@1.0.0-beta.2~start: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/app/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
9 verbose lifecycle peertube@1.0.0-beta.2~start: CWD: /app
10 silly lifecycle peertube@1.0.0-beta.2~start: Args: [ '-c', 'node dist/server' ]
11 silly lifecycle peertube@1.0.0-beta.2~start: Returned: code: 139  signal: null
12 info lifecycle peertube@1.0.0-beta.2~start: Failed to exec start script
13 verbose stack Error: peertube@1.0.0-beta.2 start: `node dist/server`
13 verbose stack Exit status 139
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:285:16)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at EventEmitter.emit (events.js:214:7)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at ChildProcess.emit (events.js:214:7)
13 verbose stack     at maybeClose (internal/child_process.js:925:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
14 verbose pkgid peertube@1.0.0-beta.2
15 verbose cwd /app
16 verbose Linux 4.15.10-1-ARCH
17 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
18 verbose node v8.10.0
19 verbose npm  v5.6.0
20 error code ELIFECYCLE
21 error errno 139
22 error peertube@1.0.0-beta.2 start: `node dist/server`
22 error Exit status 139
23 error Failed at the peertube@1.0.0-beta.2 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 139, true ]
```

**Comment by Chocobozzz** [comment]
It's a segfault in a native JS library (to generate keys I think). I think we should just remove the alpine image.

ping @bnjbvr @Angristan

**Comment by Angristan** [comment]
Seems to be a know issue: https://github.com/sass/node-sass/issues/2031

We should probably keep the Debain image for now.

**Comment by unteem** [comment]
hi i'm also getting an error when trying to build either the alpine or debian image. It does not seem to be the same though...

``npm ERR! code ELIFECYCLE
npm ERR! errno 137
npm ERR! peertube@1.0.0-beta.2 tsc: `tsc`
npm ERR! Exit status 137
npm ERR! 
npm ERR! Failed at the peertube@1.0.0-beta.2 tsc script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/peertube/.npm/_logs/2018-03-28T10_07_15_896Z-debug.log

**Comment by unteem** [comment]
npm logs:
```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'run', 'tsc' ]
2 info using npm@5.6.0
3 info using node@v8.10.0
4 verbose run-script [ 'pretsc', 'tsc', 'posttsc' ]
5 info lifecycle peertube@1.0.0-beta.2~pretsc: peertube@1.0.0-beta.2
6 info lifecycle peertube@1.0.0-beta.2~tsc: peertube@1.0.0-beta.2
7 verbose lifecycle peertube@1.0.0-beta.2~tsc: unsafe-perm in lifecycle true
8 verbose lifecycle peertube@1.0.0-beta.2~tsc: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/app/node_modules/.bin:/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/app/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
9 verbose lifecycle peertube@1.0.0-beta.2~tsc: CWD: /app
10 silly lifecycle peertube@1.0.0-beta.2~tsc: Args: [ '-c', 'tsc' ]
11 silly lifecycle peertube@1.0.0-beta.2~tsc: Returned: code: 137  signal: null
12 info lifecycle peertube@1.0.0-beta.2~tsc: Failed to exec tsc script
13 verbose stack Error: peertube@1.0.0-beta.2 tsc: `tsc`
13 verbose stack Exit status 137
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:285:16)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at EventEmitter.emit (events.js:214:7)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at ChildProcess.emit (events.js:214:7)
13 verbose stack     at maybeClose (internal/child_process.js:925:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
14 verbose pkgid peertube@1.0.0-beta.2
15 verbose cwd /app
16 verbose Linux 4.9.0-6-amd64
17 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "tsc"
18 verbose node v8.10.0
19 verbose npm  v5.6.0
20 error code ELIFECYCLE
21 error errno 137
22 error peertube@1.0.0-beta.2 tsc: `tsc`
22 error Exit status 137
23 error Failed at the peertube@1.0.0-beta.2 tsc script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 137, true ]

**Comment by Chocobozzz** [comment]
I removed the alpine image for now: https://github.com/Chocobozzz/PeerTube/commit/45cd28b679d3472392ed5d77dcfd8f442d1565bf

@unteem Use `chocobozzz/peertube:stretch` from docker hub

**Comment by MikaXII** [comment]
It's annoying because Alpine are really smaller :).
I'll keep watching for alpine image, I try to upgrade node-sass version or use a patched image but that didn't fix this issue :/.
