### ISSUE TITLE
upload-resumable: Cannot read property 'previewfile' of undefined

### ISSUE THREAD

**Issue by jeantoulza** [Chocobozzz/PeerTube#4297]
**Describe the current behavior**
POST to /api/v1/videos/upload-resumable returns HTTP 500 with error:
```
b'{"type":"https://docs.joinpeertube.org/api-rest-reference.html#section/Errors/TypeError","detail":"Cannot read property \'previewfile\' of undefined","status":500,"docs":"https://docs.joinpeertube.org/api-rest-reference.html#operation/uploadResumableInit","code":"TypeError","error":"Cannot read property \'previewfile\' of undefined"}'
```

Debug logs:
```
error[8/2/2021, 5:05:10 PM] Error in controller.

{
  "err": "TypeError: Cannot read property 'previewfile' of undefined\n    at /var/www/peertube/versions/peertube-v3.3.0/dist/server/middlewares/validators/videos/videos.js:127:22\n    at Generator.next (<anonymous>)\n    at fulfilled (/var/www/peertube/versions/peertube-v3.3.0/node_modules/tslib/tslib.js:114:62)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (internal/process/task_queues.js:97:5)"
}
```

**Steps to reproduce:**

1. Generate a client_id and client_secret with api/v1/oauth-clients/local
2. Obtain an access token with api/v1/users/token
3. POST to /v1/videos/upload-resumable

**Describe the expected behavior**
The endpoint should return 201 with Location including upload_id

**Additional information**
Code I used:
```python
def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("video")
    parser.add_argument("name")

    args = parser.parse_args()
    if not os.path.exists(args.video):
        raise Exception("File not found")

    video_mime = mimetypes.guess_type(args.video)[0]
    total_file_size = os.stat(args.video).st_size

    token = generate_token(USERNAME, PASSWORD)  # generates and returns an access token

    r = requests.post(BASE_API + "/v1/videos/upload-resumable",
                      headers={
                          "Authorization": f"Bearer {token}",
                          "X-Upload-Content-Length": str(total_file_size),
                          "X-Upload-Content-Type": video_mime,
                          "Content-Type": "application/json"
                      },
                      json={
                          "channelId": CHANNEL_ID,
                          "filename": os.path.basename(args.video),
                          "name": args.name
                      })
    if r.status_code != 201:
        # --> FAILS HERE WITH HTTP 500 <---
        print(r.content)
        raise Exception("create_upload: HTTP %s", r.status_code)

    url = r.headers["Location"]

    total_sent_bytes = 0
    while total_sent_bytes < total_file_size:
        bytes_sent = send_chunk(args.video, url, token, total_sent_bytes)
        total_sent_bytes += bytes_sent

    print("Done!")
```

* PeerTube instance:
  * URL: https://peer.hipstercat.fr
  * version: 3.3.0
  * NodeJS version: v12.22.1
  * Ffmpeg version: ffmpeg version 4.1.6-1~deb10u1

* Browser name, version and platforms on which you could reproduce the bug: Python3 + requests 2.26.0
* Link to browser console log if relevant: n/a
* Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`): included in issue

**Comment by Chocobozzz** [comment]
Thanks, should be fixed by https://github.com/Chocobozzz/PeerTube/commit/45570e93974fd8902a724c24f5a10aea747350e0
