### ISSUE TITLE
Peertube doesn't post videos at Mastodon

### ISSUE THREAD

**Issue by AnonymousWebHacker** [Chocobozzz/PeerTube#4305]
Peertube v: 3.3.0

Previously, everything was fine, I have a Peertube instance that is federated to the Mastodon. (The videos uploaded to PeerTube, are published in Mastodon, the comments ..etc, all good)

Until yesterday I decided to upgrade the peertube instance.
Shut down the nginx and peertube service, and proceeded to upgrade.

When I turned on the Peertube instance again, it is no longer federating the videos well.

Now the videos published on peertube are not being published on Mastodon. I check the list of [system / jobs] and I get
[activitypub-http-broadcast WAITING / DELAYED / FAILED]

## [FAILED]
```


Job: 161961 Type: activitypub-http-broadcast Processed on Aug 4, 2021, 7:46:41 PM Finished on Aug 4, 2021, 7:46:51 PM
--
{   "uris": [     "https://mastodon.azeroth.website/inbox"   ],   "signatureActorId": 1,   "body": {     "id": "https://peertube.azeroth.website/accounts/peertube/views/videos/2601/2021-08-04T23:19:18.231Z",     "type": "View",     "actor": "https://peertube.azeroth.website/accounts/peertube",     "object": "https://peertube.azeroth.website/videos/watch/b37f8848-9497-458f-b9d5-0e7dd86658ce",     "to": [       "https://www.w3.org/ns/activitystreams#Public",       "https://peertube.azeroth.website/video-channels/coreanoloco/followers",       "https://peertube.azeroth.website/accounts/peertube/followers",       "https://peertube.azeroth.website/accounts/peertubebot/followers"     ],     "cc": []   },   "contextType": "View" }
jsonld.InvalidUrl: Dereferencing a URL did not result in a valid JSON-LD object. Possible causes are an inaccessible URL perhaps due to a same-origin policy (ensure the server uses CORS if you are using client-side JavaScript), too many redirects, a non-JSON response, or more than one HTTP Link Header was provided for a remote context.     at ContextResolver._fetchContext (/var/www/peertube/versions/peertube-v3.3.0/node_modules/jsonld/lib/ContextResolver.js:173:13)     at runMicrotasks (<anonymous>)     at processTicksAndRejections (internal/process/task_queues.js:97:5)

```

## [DELAYED]

```
Job: 161982 Type: activitypub-http-broadcast Processed on Aug 4, 2021, 8:10:55 PM Finished on -
--
{   "uris": [     "https://mastodon.azeroth.website/inbox"   ],   "signatureActorId": 519,   "body": {     "id": "https://peertube.azeroth.website/accounts/christopher/likes/2609",     "type": "Like",     "actor": "https://peertube.azeroth.website/accounts/christopher",     "object": "https://peertube.azeroth.website/videos/watch/4254f59d-5eb1-40a9-9698-e58c47c6fc4e",     "to": [       "https://www.w3.org/ns/activitystreams#Public",       "https://peertube.azeroth.website/video-channels/miniseries/followers",       "https://peertube.azeroth.website/accounts/peertube/followers",       "https://mastodon.azeroth.website/users/AnonymousWebHacker/followers",       "https://peertube.azeroth.website/accounts/peertubebot/followers"     ],     "cc": []   } }
jsonld.InvalidUrl: Dereferencing a URL did not result in a valid JSON-LD object. Possible causes are an inaccessible URL perhaps due to a same-origin policy (ensure the server uses CORS if you are using client-side JavaScript), too many redirects, a non-JSON response, or more than one HTTP Link Header was provided for a remote context.     at ContextResolver._fetchContext (/var/www/peertube/versions/peertube-v3.3.0/node_modules/jsonld/lib/ContextResolver.js:173:13)     at runMicrotasks (<anonymous>)     at processTicksAndRejections (internal/process/task_queues.js:97:5)

```

## [WAITING]

```
Job: 161993 Type: activitypub-http-broadcast Processed on Aug 4, 2021, 8:06:14 PM Finished on -
--
{   "uris": [     "https://mastodon.azeroth.website/inbox"   ],   "signatureActorId": 12,   "body": {     "type": "Create",     "id": "https://peertube.azeroth.website/videos/watch/b37f8848-9497-458f-b9d5-0e7dd86658ce/comments/5452/activity",     "actor": "https://peertube.azeroth.website/accounts/peertubebot",     "object": {       "type": "Note",       "id": "https://peertube.azeroth.website/videos/watch/b37f8848-9497-458f-b9d5-0e7dd86658ce/comments/5452",       "content": "@kalimist Si hubieras buscado , lo encontrabas aca <br />https://peertube.azeroth.website/w/nuifQivJeNWhQdYrBiJm4z",       "inReplyTo": "https://peertube.azeroth.website/videos/watch/b37f8848-9497-458f-b9d5-0e7dd86658ce/comments/5450",       "updated": "2021-08-04T23:50:32.308Z",       "published": "2021-08-04T23:50:32.306Z",       "url": "https://peertube.azeroth.website/videos/watch/b37f8848-9497-458f-b9d5-0e7dd86658ce/comments/5452",       "attributedTo": "https://peertube.azeroth.website/accounts/peertubebot",       "tag": [         {           "type": "Mention",           "href": "https://peertube.azeroth.website/accounts/kalimist",           "name": "@kalimist@peertube.azeroth.website"         }       ],       "to": [         "https://www.w3.org/ns/activitystreams#Public"       ],       "cc": [         "https://peertube.azeroth.website/accounts/peertubebot/followers",         "https://peertube.azeroth.website/accounts/kalimist",         "https://peertube.azeroth.website/video-channels/coreanoloco/followers",         "https://peertube.azeroth.website/accounts/peertube/followers",         "https://peertube.azeroth.website/accounts/peertubebot/followers",         "https://peertube.azeroth.website/accounts/peertubebot/followers"       ]     },     "to": [       "https://www.w3.org/ns/activitystreams#Public"     ],     "cc": [       "https://peertube.azeroth.website/accounts/peertubebot/followers",       "https://peertube.azeroth.website/accounts/kalimist",       "https://peertube.azeroth.website/video-channels/coreanoloco/followers",       "https://peertube.azeroth.website/accounts/peertube/followers",       "https://peertube.azeroth.website/accounts/peertubebot/followers",       "https://peertube.azeroth.website/accounts/peertubebot/followers"     ]   } }
jsonld.InvalidUrl: Dereferencing a URL did not result in a valid JSON-LD object. Possible causes are an inaccessible URL perhaps due to a same-origin policy (ensure the server uses CORS if you are using client-side JavaScript), too many redirects, a non-JSON response, or more than one HTTP Link Header was provided for a remote context.     at ContextResolver._fetchContext (/var/www/peertube/versions/peertube-v3.3.0/node_modules/jsonld/lib/ContextResolver.js:173:13)     at runMicrotasks (<anonymous>)     at processTicksAndRejections (internal/process/task_queues.js:97:5)

```

NOTE: 
- Both servers are located in a SNET (they cannot access them)
- The Mastodon instance, yes it exists and is functional
- Neither of them (Peertube, nor Mastodon) have internet access

 below I leave my nginx conf (which could be the problem)

[vhost.txt](https://github.com/Chocobozzz/PeerTube/files/6935119/vhost.txt)

**Comment by AnonymousWebHacker** [comment]
![Captura de pantalla de 2021-08-04 20-45-12](https://user-images.githubusercontent.com/43164089/128273742-a274c663-ed91-4546-a94c-486b26944dcd.png)
![Captura de pantalla de 2021-08-04 20-44-39](https://user-images.githubusercontent.com/43164089/128273748-de27526b-c420-4474-86df-15a85d91fc6a.png)

**Comment by AnonymousWebHacker** [comment]
![Captura de pantalla de 2021-08-04 20-45-12](https://user-images.githubusercontent.com/43164089/128273742-a274c663-ed91-4546-a94c-486b26944dcd.png)
![Captura de pantalla de 2021-08-04 20-44-39](https://user-images.githubusercontent.com/43164089/128273748-de27526b-c420-4474-86df-15a85d91fc6a.png)

**Comment by AnonymousWebHacker** [comment]
I have to be going to Peertube, copy the URL of the video, and look In the search box, put the URL so that when the video comes out, it will appear in the public list, so that then, it will appear in the list of federated videos

![Captura de pantalla de 2021-08-04 21-11-37](https://user-images.githubusercontent.com/43164089/128275719-fd2bbab0-98cb-476a-9bb1-250190804291.png)
![Captura de pantalla de 2021-08-04 21-11-04](https://user-images.githubusercontent.com/43164089/128275731-cf919bd7-0fdf-4516-9cf5-a5617df65888.png)

**Comment by AnonymousWebHacker** [comment]
The above message solved me, since the new videos that were uploaded have already started to be published automatically

![Captura de pantalla de 2021-08-04 21-31-44](https://user-images.githubusercontent.com/43164089/128280083-f14da91c-b089-49cc-a4fd-4bfcd9e66c8f.png)
@Chocobozzz I'm going to leave the inssuse open, until you can read it

**Comment by Chocobozzz** [comment]
Hello,

It can happen when context URLs we use in our JSON LD object are not responding. It should be very rare, because we use a cache and only fetch these URLs once.

**Comment by AnonymousWebHacker** [comment]
@Chocobozzz This has happened to me before, it is not the first time.

So what do you recommend?

That the server where I have the instance, give it access to the internet all the time, so that it finds the URLs of the json ?

**Comment by AnonymousWebHacker** [comment]
@Chocobozzz I noticed that every time the peertube, server ..etc is restarted, if the peertube instance does not have internet access to connect to  https://www.w3.org/ns/activitystreams#Public , the federacion stops working
