### ISSUE TITLE
peertube-import-videos.js fails when a youtube video has no tags

### ISSUE THREAD

**Issue by mostfunkyduck** [Chocobozzz/PeerTube#4323]
**Describe the current behavior**
I am trying to download https://www.youtube.com/watch?v=HNpa1-z2gQI and every time I do, I get this error:
```
.field(name, val) val can not be empty
```
I added some logging to dump the full backtrace of the exception and I see this (with the actual path of the repo replaced with '/path/to'):
```
Error: .field(name, val) val can not be empty
    at Test.RequestBase.field (/path/to/PeerTube/node_modules/superagent/lib/request-base.js:463:11)
    at buildFields (/path/to/PeerTube/dist/shared/extra-utils/requests/requests.js:123:17)
    at Object.makeUploadRequest (/path/to/PeerTube/dist/shared/extra-utils/requests/requests.js:48:5)
    at VideosCommand.postUploadRequest (/path/to/PeerTube/dist/shared/extra-utils/shared/abstract-command.js:39:27)
    at VideosCommand.<anonymous> (/path/to/PeerTube/dist/shared/extra-utils/videos/videos-command.js:156:47)
    at Generator.next (<anonymous>)
    at /path/to/PeerTube/node_modules/tslib/tslib.js:117:75
    at new Promise (<anonymous>)
    at Object.__awaiter (/path/to//PeerTube/node_modules/tslib/tslib.js:113:16)
    at VideosCommand.buildLegacyUpload (/path/to/PeerTube/dist/shared/extra-utils/videos/videos-command.js:154:24)
```
I added logging in superagent and the tag that it's complaining about is `tags`. I got around this by hardcoding the tags using the tags argument
**Steps to reproduce:**
1. node dist/server/tools/peertube-import-videos.js  -u <your url> -U <user> -p <password> --target-url https://www.youtube.com/watch?v=HNpa1-z2gQI

**Describe the expected behavior**
Video uploads

**Additional information**
This is all done via uploads from my local laptop to a home server.  The home server is, unfortunately, only available over my internal network.
* PeerTube instance:
  * URL: Private instance, not accessible over the internet
  * version: 3.3.0
  * NodeJS version: 14.17.5 locally, server is using the official container which is saying that it's on 12.22.3
  * Ffmpeg version: 4.3.2 locally, 4.1.6 in the container

* Browser name, version and platforms on which you could reproduce the bug:
The server is running the [official docker image](https://hub.docker.com/r/chocobozzz/peertube) on ubuntu 20.04
The laptop is running ubuntu 21.04
* Link to browser console log if relevant:
Not relevant
* Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`):
Not relevant, this is a client-side bug in the peertube import script

**Comment by Chocobozzz** [comment]
Thanks psyduck, should be fixed by https://github.com/Chocobozzz/PeerTube/commit/63436fc5eadc3f58a047fe87be9c4afa84a7a9ca
