### ISSUE TITLE
Error: Cannot fetch remote video with url

### ISSUE THREAD

**Issue by roere** [Chocobozzz/PeerTube#4338]
**Describe the current behavior**
Some Videos from followed Instances are not fetched:

warn[17.8.2021, 21:10:44] Cannot process activity View.

{
  "err": {
    "stack": "Error: Cannot fetch remote video with url: https://piraten.space/videos/watch/97a77b4d-7259-4b58-8540-b4c39868fcd9\n    at Object.<anonymous> (/var/www/peertube/versions/peertube-v3.3.0/dist/server/lib/activitypub/videos/get.js:26:19)\n    at Generator.next (<anonymous>)\n    at fulfilled (/var/www/peertube/versions/peertube-v3.3.0/node_modules/tslib/tslib.js:114:62)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (internal/process/task_queues.js:97:5)",
    "message": "Cannot fetch remote video with url: https://piraten.space/videos/watch/97a77b4d-7259-4b58-8540-b4c39868fcd9"
  }
}

**Steps to reproduce:**

The unfetchable video URL can be loaded in the browser:
https://piraten.space/videos/watch/97a77b4d-7259-4b58-8540-b4c39868fcd9

* PeerTube instance:
  * URL: widemus.de / fetching from: piraten.space
  * all versions: 3.3.0

**Comment by Chocobozzz** [comment]
> Does the error stack trace tell you something?

No, but you can try to enable debug logs to see if https://github.com/Chocobozzz/PeerTube/blob/893f0f2f0f9c8f5b9f829e48691b0a236e229868/server/lib/activitypub/videos/shared/url-to-object.ts#L15 is printed

**Comment by roere** [comment]
It is printed for another video, yes:

 

>debug[30.8.2021, 23:49:36] Remote video JSON is not valid.
>
>{
>  "body": "",
>  "tags": [
>    "ap",
>    "video",
>    "https://tube.querdenken-711.de/videos/watch/aa128383-907a-4a3c-b91a-a334ae93d385"
>  ]
>}

**Comment by Chocobozzz** [comment]
Are you able to fetch these URLs from the server using curl? (`curl -L -H 'Accept: application/ld+json; profile="https://www.w3.org/ns/activitystreams"' $url`)

**Comment by roere** [comment]
Tried it: yes, I can fetch it from the server console using curl.
