### ISSUE TITLE
Object storage multipart upload in v3.4.0 does not work

### ISSUE THREAD

**Issue by jeantoulza** [Chocobozzz/PeerTube#4388]
**Describe the current behavior**
Uploading a file that is > max_upload_part starts a multipart upload that fails. Not sure if misconfiguration on the object storage or not.
Relevant logs below.

**Steps to reproduce:**
1. Upload a video bigger than max_upload_part
2. Wait for error to show up in logs
3. Video is not uploaded

**Describe the expected behavior**
Video should be uploaded without error

**Additional information**
I'm using Scaleway object storage.
Relevant configuration:
```
object_storage:
    enabled: true
    max_upload_part: 10MB
    endpoint: s3.fr-par.scw.cloud
    streaming_playlists:
      bucket_name: REDACTED
      prefix: 'objstoragebranch/streaming_playlists'
      base_url: ''
    videos:
      bucket_name: REDACTED
      prefix: 'objstoragebranch/videos'
      base_url: ''
    region: 'fr-par'

    credentials:
      # You can also use AWS_ACCESS_KEY_ID env variable
      access_key_id: 'REDACTED'
      # You can also use AWS_SECRET_ACCESS_KEY env variable
      secret_access_key: 'REDACTED'
```

* PeerTube instance:
  * URL: https://peer.hipstercat.fr
  * version: 3.4.0-rc
  * NodeJS version: v12.22.1
  * Ffmpeg version: 4.1.6-1~deb10u1

* Browser name, version and platforms on which you could reproduce the bug: Linux Firefox 91.0.2 
* Link to browser console log if relevant: n/a
* Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`):
```
Sep 08 11:28:22 peertube peertube[1057]: [peer.hipstercat.fr:443] 2021-09-08 11:28:22.664 debug: Uploading file /var/www/peertube/storage/streaming-playlists/hls/d283abae-5de3-4be7-bf4c-8a58713c10c5/a14b3fab-2e3f-4a03-9969-7b13c1d69fa7-720.m3u8 to objstoragebranch/streaming_playlistshls/d283abae-5de3-4be7-bf4c-8a58713c10c5/a14b3fab-2e3f-4a03-9969-7b13c1d69fa7-720.m3u8 in bucket REDACTED
Sep 08 11:28:23 peertube peertube[1057]: [peer.hipstercat.fr:443] 2021-09-08 11:28:23.178 debug: Uploading file /var/www/peertube/storage/streaming-playlists/hls/d283abae-5de3-4be7-bf4c-8a58713c10c5/a14b3fab-2e3f-4a03-9969-7b13c1d69fa7-720-fragmented.mp4 to objstoragebranch/streaming_playlistshls/d283abae-5de3-4be7-bf4c-8a58713c10c5/a14b3fab-2e3f-4a03-9969-7b13c1d69fa7-720-fragmented.mp4 in bucket REDACTED
Sep 08 11:28:23 peertube peertube[1057]: [peer.hipstercat.fr:443] 2021-09-08 11:28:23.477 debug: Uploading part 1 of file to objstoragebranch/streaming_playlistshls/d283abae-5de3-4be7-bf4c-8a58713c10c5/a14b3fab-2e3f-4a03-9969-7b13c1d69fa7-720-fragmented.mp4 in bucket REDACTED
Sep 08 11:28:46 peertube peertube[1057]: [peer.hipstercat.fr:443] 2021-09-08 11:28:46.820 debug: Uploading part 2 of file to objstoragebranch/streaming_playlistshls/d283abae-5de3-4be7-bf4c-8a58713c10c5/a14b3fab-2e3f-4a03-9969-7b13c1d69fa7-720-fragmented.mp4 in bucket REDACTED
Sep 08 11:29:10 peertube peertube[1057]: [peer.hipstercat.fr:443] 2021-09-08 11:29:10.351 debug: Uploading part 3 of file to objstoragebranch/streaming_playlistshls/d283abae-5de3-4be7-bf4c-8a58713c10c5/a14b3fab-2e3f-4a03-9969-7b13c1d69fa7-720-fragmented.mp4 in bucket REDACTED
Sep 08 11:29:33 peertube peertube[1057]: [peer.hipstercat.fr:443] 2021-09-08 11:29:33.868 debug: Uploading part 4 of file to objstoragebranch/streaming_playlistshls/d283abae-5de3-4be7-bf4c-8a58713c10c5/a14b3fab-2e3f-4a03-9969-7b13c1d69fa7-720-fragmented.mp4 in bucket REDACTED
Sep 08 11:29:57 peertube peertube[1057]: [peer.hipstercat.fr:443] 2021-09-08 11:29:57.313 debug: Uploading part 5 of file to objstoragebranch/streaming_playlistshls/d283abae-5de3-4be7-bf4c-8a58713c10c5/a14b3fab-2e3f-4a03-9969-7b13c1d69fa7-720-fragmented.mp4 in bucket REDACTED
Sep 08 11:30:02 peertube peertube[1057]: [peer.hipstercat.fr:443] 2021-09-08 11:30:02.796 error: Cannot execute job 24 in queue move-to-object-storage. {
Sep 08 11:30:02 peertube peertube[1057]:   "payload": {
Sep 08 11:30:02 peertube peertube[1057]:     "videoUUID": "d283abae-5de3-4be7-bf4c-8a58713c10c5",
Sep 08 11:30:02 peertube peertube[1057]:     "isNewVideo": true
Sep 08 11:30:02 peertube peertube[1057]:   },
Sep 08 11:30:02 peertube peertube[1057]:   "err": {
Sep 08 11:30:02 peertube peertube[1057]:     "stack": "NoSuchUpload: The specified multipart upload does not exist. The upload ID might be invalid, or the multipart upload might have been aborted or completed.\n    at deserializeAws_restXmlCompleteMultipartUploadCommandError (/var/www/peertube/versions/peertube-v3.4.0-rc.1/node_modules/@aws-sdk/client-s3/dist/cjs/protocols/Aws_restXml.js:4391:41)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (internal/process/task_queues.js:97:5)\n    at async /var/www/peertube/versions/peertube-v3.4.0-rc.1/node_modules/@aws-sdk/middleware-serde/dist/cjs/deserializerMiddleware.js:6:20\n    at async /var/www/peertube/versions/peertube-v3.4.0-rc.1/node_modules/@aws-sdk/middleware-signing/dist/cjs/middleware.js:11:20\n    at async StandardRetryStrategy.retry (/var/www/peertube/versions/peertube-v3.4.0-rc.1/node_modules/@aws-sdk/middleware-retry/dist/cjs/StandardRetryStrategy.js:51:46)\n    at async /var/www/peertube/versions/peertube-v3.4.0-rc.1/node_modules/@aws-sdk/middleware-logger/dist/cjs/loggerMiddleware.js:6:22",
Sep 08 11:30:02 peertube peertube[1057]:     "message": "The specified multipart upload does not exist. The upload ID might be invalid, or the multipart upload might have been aborted or completed.",
Sep 08 11:30:02 peertube peertube[1057]:     "Code": "NoSuchUpload",
Sep 08 11:30:02 peertube peertube[1057]:     "RequestId": "tx918c868594ee4e17a8054-0061389eba",
Sep 08 11:30:02 peertube peertube[1057]:     "UploadId": "YTg3ZTg0NmQtZjQ4Ny00ZGMxLWI1MjctYjU3OTlmNTk3YTUx",
Sep 08 11:30:02 peertube peertube[1057]:     "name": "NoSuchUpload",
Sep 08 11:30:02 peertube peertube[1057]:     "$fault": "client",
Sep 08 11:30:02 peertube peertube[1057]:     "$metadata": {
Sep 08 11:30:02 peertube peertube[1057]:       "httpStatusCode": 400,
Sep 08 11:30:02 peertube peertube[1057]:       "extendedRequestId": "tx918c868594ee4e17a8054-0061389eba",
Sep 08 11:30:02 peertube peertube[1057]:       "attempts": 1,
Sep 08 11:30:02 peertube peertube[1057]:       "totalRetryDelay": 0
Sep 08 11:30:02 peertube peertube[1057]:     }
Sep 08 11:30:02 peertube peertube[1057]:   }
Sep 08 11:30:02 peertube peertube[1057]: }
```

**Comment by kukhariev** [comment]
https://github.com/Chocobozzz/PeerTube/blob/8a7abfef88b5fc69f8809dcbb511e923597a0163/server/lib/object-storage/shared/object-storage-helpers.ts#L217-L223
There's a typo here
```ts
...
   Bucket: bucketInfo.BUCKET_NAME, 
   Key: key, 
   UploadId: createResponse.UploadId,
...
```

**Comment by Chocobozzz** [comment]
Thanks, and there's also a typo in aws lib... Should be fixed by https://github.com/Chocobozzz/PeerTube/commit/1c93ad0778d9bde1ba4caf87f24ecef27a8346a9
