### ISSUE TITLE
upload.js (v1.0.0-b3) - privacy must be set

### ISSUE THREAD

**Issue by MikaXII** [Chocobozzz/PeerTube#441]
```
TypeError: Cannot read property 'toString' of undefined
    at Object.<anonymous> (/home/mikaxii/github/PeerTube/dist/server/tests/utils/videos/videos.js:241:50)
    at Generator.next (<anonymous>)
    at fulfilled (/home/mikaxii/github/PeerTube/dist/server/tests/utils/videos/videos.js:5:58)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:118:7)
```

After checking code the privacy parameter must be set.

**Comment by Chocobozzz** [comment]
Thanks, it should be fixed: https://github.com/Chocobozzz/PeerTube/commit/72de91cb109b091fff607fbb0c6968bb8a1c97f3
