### ISSUE TITLE
Can not update from 3.3.0 to 3.4.0 via docker

### ISSUE THREAD

**Issue by r6fans** [Chocobozzz/PeerTube#4410]
**Describe the current behavior**
I use AWS ECS service to build a peertube environment. An error occurred when I upgrade docker image from v3.3.0-buster to v3.4.0-buster.

**Steps to reproduce:**

1. upgrade docker image from v3.3.0-buster to v3.4.0-buster
2. docker run

**Describe the expected behavior**
I found no problems when I use a fresh database. But I have a lot data in my old database. I would like to know there is any  way to solve this problem except compare this two database structure.

**Additional information**

* PeerTube instance:
  * URL:
  * version: 3.3.0 -> 3.4.0
  * NodeJS version: 12.22.6
  * Postgres version: 13.3

* Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`):
```json
{
    "level": "debug",
    "message": "Checking NodeJS version v12.22.6.",
    "label": "",
    "timestamp": "2021-09-13T08:03:51.611Z"
}
{
    "level": "info",
    "message": "Using proxy ",
    "label": "",
    "timestamp": "2021-09-13T08:03:53.733Z"
}
{
    "sql": "Executing (default): SELECT 1+1 AS result",
    "tags": [
        "sql"
    ],
    "level": "debug",
    "message": "Executed SQL request",
    "label": "",
    "timestamp": "2021-09-13T08:03:55.847Z"
}
{
    "sql": "Executing (default): SELECT table_name FROM information_schema.tables WHERE table_schema = 'public' AND table_type LIKE '%TABLE' AND table_name != 'spatial_ref_sys';",
    "tags": [
        "sql"
    ],
    "level": "debug",
    "message": "Executed SQL request",
    "label": "",
    "timestamp": "2021-09-13T08:03:55.848Z"
}
{
    "message": "Connection to PostgreSQL has been established successfully.",
    "level": "debug",
    "label": "",
    "timestamp": "2021-09-13T08:03:55.850Z"
}{
    "sql": "Executing (default): SELECT \"migrationVersion\" FROM \"application\"",
    "tags": [
        "sql"
    ],
    "level": "debug",
    "message": "Executed SQL request",
    "label": "",
    "timestamp": "2021-09-13T08:03:55.858Z"
}
{
    "message": "Begin migrations.",
    "level": "info",
    "label": "",
    "timestamp": "2021-09-13T08:03:55.860Z"
}
{
    "level": "info",
    "message": "Executing 0665-no-account-warning-modal.js migration script.",
    "label": "",
    "timestamp": "2021-09-13T08:03:55.864Z"
}{
    "sql": "Executing (73368155-d1d6-4676-85d8-ea933adc156f): START TRANSACTION;",
    "tags": [
        "sql"
    ],
    "level": "debug",
    "message": "Executed SQL request",
    "label": "",
    "timestamp": "2021-09-13T08:03:55.869Z"
}{
    "sql": "Executing (73368155-d1d6-4676-85d8-ea933adc156f): SET TRANSACTION ISOLATION LEVEL SERIALIZABLE;",
    "tags": [
        "sql"
    ],
    "level": "debug",
    "message": "Executed SQL request",
    "label": "",
    "timestamp": "2021-09-13T08:03:55.875Z"
}{
    "sql": "Executing (default): ALTER TABLE \"public\".\"user\" ADD COLUMN \"noAccountSetupWarningModal\" BOOLEAN NOT NULL DEFAULT false;",
    "tags": [
        "sql"
    ],
    "level": "debug",
    "message": "Executed SQL request",
    "label": "",
    "timestamp": "2021-09-13T08:03:55.880Z"
}{
    "sql": "Executing (73368155-d1d6-4676-85d8-ea933adc156f): UPDATE \"application\" SET \"migrationVersion\" = 665",
    "tags": [
        "sql"
    ],
    "level": "debug",
    "message": "Executed SQL request",
    "label": "",
    "timestamp": "2021-09-13T08:03:55.893Z"
}{
    "sql": "Executing (73368155-d1d6-4676-85d8-ea933adc156f): COMMIT;",
    "tags": [
        "sql"
    ],
    "level": "debug",
    "message": "Executed SQL request",
    "label": "",
    "timestamp": "2021-09-13T08:03:55.896Z"
}{
    "level": "info",
    "message": "Executing 0670-pending-job-default.js migration script.",
    "label": "",
    "timestamp": "2021-09-13T08:03:55.901Z"
}{
    "sql": "Executing (a92a6ad2-0140-4cf2-9c69-6c5652d42081): START TRANSACTION;",
    "tags": [
        "sql"
    ],
    "level": "debug",
    "message": "Executed SQL request",
    "label": "",
    "timestamp": "2021-09-13T08:03:55.904Z"
}{
    "sql": "Executing (a92a6ad2-0140-4cf2-9c69-6c5652d42081): SET TRANSACTION ISOLATION LEVEL SERIALIZABLE;",
    "tags": [
        "sql"
    ],
    "level": "debug",
    "message": "Executed SQL request",
    "label": "",
    "timestamp": "2021-09-13T08:03:55.906Z"
}{
    "sql": "Executing (default): ALTER TABLE \"videoJobInfo\" ALTER COLUMN \"pendingMove\" SET NOT NULL;ALTER TABLE \"videoJobInfo\" ALTER COLUMN \"pendingMove\" SET DEFAULT 0;ALTER TABLE \"videoJobInfo\" ALTER COLUMN \"pendingMove\" TYPE INTEGER;",
    "tags": [
        "sql"
    ],
    "level": "debug",
    "message": "Executed SQL request",
    "label": "",
    "timestamp": "2021-09-13T08:03:55.910Z"
}{
    "sql": "Executing (a92a6ad2-0140-4cf2-9c69-6c5652d42081): ROLLBACK;",
    "tags": [
        "sql"
    ],
    "level": "debug",
    "message": "Executed SQL request",
    "label": "",
    "timestamp": "2021-09-13T08:03:55.914Z"
}{
    "level": "error",
    "message": "Cannot execute migration 0670.",
    "label": "",
    "err": {
        "stack": "SequelizeDatabaseError: relation \"videoJobInfo\" does not exist\n    at Query.formatError (/app/node_modules/sequelize/lib/dialects/postgres/query.js:386:16)\n    at Query.run (/app/node_modules/sequelize/lib/dialects/postgres/query.js:87:18)\n    at processTicksAndRejections (internal/process/task_queues.js:97:5)",
        "message": "relation \"videoJobInfo\" does not exist",
        "name": "SequelizeDatabaseError",
        "parent": {
            "stack": "error: relation \"videoJobInfo\" does not exist\n    at Parser.parseErrorMessage (/app/node_modules/pg-protocol/dist/parser.js:287:98)\n    at Parser.handlePacket (/app/node_modules/pg-protocol/dist/parser.js:126:29)\n    at Parser.parse (/app/node_modules/pg-protocol/dist/parser.js:39:38)\n    at Socket.<anonymous> (/app/node_modules/pg-protocol/dist/index.js:11:42)\n    at Socket.emit (events.js:314:20)\n    at Socket.EventEmitter.emit (domain.js:483:12)\n    at addChunk (_stream_readable.js:297:12)\n    at readableAddChunk (_stream_readable.js:272:9)\n    at Socket.Readable.push (_stream_readable.js:213:10)\n    at TCP.onStreamRead (internal/stream_base_commons.js:188:23)",
            "message": "relation \"videoJobInfo\" does not exist",
            "length": 110,
            "name": "error",
            "severity": "ERROR",
            "code": "42P01",
            "file": "namespace.c",
            "line": "437",
            "routine": "RangeVarGetRelidExtended",
            "sql": "ALTER TABLE \"videoJobInfo\" ALTER COLUMN \"pendingMove\"SET NOT NULL;ALTER TABLE \"videoJobInfo\" ALTER COLUMN \"pendingMove\" SET DEFAULT 0;ALTER TABLE \"videoJobInfo\" ALTER COLUMN \"pendingMove\" TYPE INTEGER;"
        },
        "sql": "ALTER TABLE \"videoJobInfo\" ALTER COLUMN \"pendingMove\" SET NOT NULL;ALTER TABLE \"videoJobInfo\" ALTER COLUMN \"pendingMove\" SET DEFAULT 0;ALTER TABLE \"videoJobInfo\" ALTER COLUMN \"pendingMove\" TYPE INTEGER;"
    },
    "timestamp": "2021-09-13T08:03:55.916Z"
}
```

**Comment by Chocobozzz** [comment]
Hello,

Do you have previous logs regarding migration `0660-object-storage`?  It should have created this table.

**Comment by r6fans** [comment]
@Chocobozzz 
Sorry, I can't find logs  regarding migration `0660-object-storage`. Because my logs are only kept for seven days. I think this migration may have happened last month when I deployed the nightly version.

However, after I changed the column `migrationVersion` in the `application` table to 650, it ran successfully.

Am I do the right thing? 
Will this have any bad effect on peertube?

**Comment by Chocobozzz** [comment]
If peertube correctly migrated the database I think it's fine
