### ISSUE TITLE
Can't install CLI - Cannot find module '@shared/extra-utils'

### ISSUE THREAD

**Issue by masscream** [Chocobozzz/PeerTube#4420]
Trying to install CLI Wrapper tool, after cloning the new git folder and successful process of both install commands, I can't run the tool with the following error:

```
$ cd && node ~/versions/peertube-v3.4.0_cli/dist/server/tools/peertube.js
internal/modules/cjs/loader.js:818
  throw err;
  ^

Error: Cannot find module '@shared/extra-utils'
Require stack:
- /media/Storage/PeerTube/versions/peertube-v3.4.0_cli/dist/server/tools/cli.js
- /media/Storage/PeerTube/versions/peertube-v3.4.0_cli/dist/server/tools/peertube.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
    at Function.Module._resolveFilename (/media/Storage/PeerTube/versions/peertube-v3.4.0_cli/node_modules/tsconfig-paths/lib/register.js:75:40)
    at Function.Module._load (internal/modules/cjs/loader.js:667:27)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/media/Storage/PeerTube/versions/peertube-v3.4.0_cli/dist/server/tools/cli.js:7:23)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/media/Storage/PeerTube/versions/peertube-v3.4.0_cli/dist/server/tools/cli.js',
    '/media/Storage/PeerTube/versions/peertube-v3.4.0_cli/dist/server/tools/peertube.js'
  ]
}
$ npm install @shared/extra-utils
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@shared%2fextra-utils - Not found
npm ERR! 404 
npm ERR! 404  '@shared/extra-utils@latest' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
npm ERR!     /media/Storage/PeerTube/.npm/_logs/2021-09-18T15_03_12_394Z-debug.log
```

To be sure, I repeated the process with one of my common user profile, installing the git repo folder into his home folder. The result was the same.

**Steps to reproduce:**

1. Follow the tutorial howto install the CLI Wrapper tool at https://docs.joinpeertube.org/maintain-tools?id=cli-wrapper
2. Try to run it. It does not matter whether you setup your alias or you run the tool by a command at its full length
3. It won't run

**Describe the expected behavior**
It should run.

**Additional information**

* PeerTube instance:
  * version: 3.4.0
  * NodeJS version: node --version v12.22.3, npm --version 6.14.13
  * Ffmpeg version: 4.2.4

* Red Hat Enterprise Linux release 8.4 (Ootpa)

**Comment by masscream** [comment]
While crickets in the air, I tried to analyze the problem myself and so far, this is what I've found. I fixed the issue myself. The problem was in the extra modules path definition. In every file I got the error for (by the time I was going through) I discovered, that the path is defined by the char "@" which should probably mean the path of the homefolder of the peertube cli instance itself, however mine was not understood that way - I don't know why, it may be my system misconfiguration, PT incompatibility with RHEL or any other bug in the PT itself. I've fixed that by defining the path manually.

For example @shared/models/ replacing with ../../shared/models or ../../../shared/models, depending where the error came from.
I had to fix it in all of these files.

```
peertube-v3.4.0_cli/dist/server/tools/cli.js
peertube-v3.4.0_cli/dist/shared/extra-utils/bulk/bulk-command.js
peertube-v3.4.0_cli/dist/shared/extra-utils/requests/requests.js
peertube-v3.4.0_cli/dist/shared/extra-utils/custom-pages/custom-pages-command.js
peertube-v3.4.0_cli/dist/shared/extra-utils/feeds/feeds-command.js
peertube-v3.4.0_cli/dist/shared/extra-utils/logs/logs-command.js
peertube-v3.4.0_cli/dist/shared/extra-utils/miscs/checks.js
peertube-v3.4.0_cli/dist/shared/extra-utils/requests/check-api-params.js
peertube-v3.4.0_cli/dist/shared/extra-utils/miscs/generate.js
peertube-v3.4.0_cli/dist/server/helpers/ffprobe-utils.js
peertube-v3.4.0_cli/dist/shared/extra-utils/mock-servers/mock-email.js
peertube-v3.4.0_cli/dist/shared/extra-utils/mock-servers/mock-instances-index.js
peertube-v3.4.0_cli/dist/shared/extra-utils/mock-servers/mock-joinpeertube-versions.js
peertube-v3.4.0_cli/dist/shared/extra-utils/mock-servers/mock-plugin-blocklist.js
peertube-v3.4.0_cli/dist/shared/extra-utils/mock-servers/mock-object-storage.js
peertube-v3.4.0_cli/dist/shared/extra-utils/server/config-command.js
peertube-v3.4.0_cli/dist/shared/extra-utils/server/contact-form-command.js
peertube-v3.4.0_cli/dist/shared/extra-utils/server/debug-command.js
peertube-v3.4.0_cli/dist/shared/extra-utils/server/directories.js
peertube-v3.4.0_cli/dist/shared/extra-utils/server/follows-command.js
peertube-v3.4.0_cli/dist/shared/extra-utils/server/jobs-command.js
peertube-v3.4.0_cli/dist/shared/extra-utils/server/object-storage-command.js
peertube-v3.4.0_cli/dist/shared/extra-utils/server/plugins-command.js
peertube-v3.4.0_cli/dist/shared/extra-utils/server/redundancy-command.js
peertube-v3.4.0_cli/dist/shared/extra-utils/server/server.js
peertube-v3.4.0_cli/dist/shared/extra-utils/moderation/abuses-command.js
peertube-v3.4.0_cli/dist/shared/extra-utils/overviews/overviews-command.js
peertube-v3.4.0_cli/dist/shared/extra-utils/search/search-command.js
peertube-v3.4.0_cli/dist/shared/extra-utils/users/accounts-command.js
peertube-v3.4.0_cli/dist/shared/extra-utils/users/actors.js
peertube-v3.4.0_cli/dist/shared/extra-utils/users/blocklist-command.js
peertube-v3.4.0_cli/dist/shared/extra-utils/users/login-command.js
peertube-v3.4.0_cli/dist/shared/extra-utils/users/notifications-command.js
peertube-v3.4.0_cli/dist/shared/extra-utils/users/subscriptions-command.js
peertube-v3.4.0_cli/dist/shared/extra-utils/users/users-command.js
peertube-v3.4.0_cli/dist/shared/extra-utils/videos/blacklist-command.js
peertube-v3.4.0_cli/dist/shared/extra-utils/videos/captions-command.js
peertube-v3.4.0_cli/dist/shared/extra-utils/videos/captions.js
peertube-v3.4.0_cli/dist/shared/extra-utils/videos/change-ownership-command.js
peertube-v3.4.0_cli/dist/shared/extra-utils/videos/channels-command.js
peertube-v3.4.0_cli/dist/shared/extra-utils/videos/comments-command.js
peertube-v3.4.0_cli/dist/shared/extra-utils/videos/history-command.js
peertube-v3.4.0_cli/dist/shared/extra-utils/videos/imports-command.js
peertube-v3.4.0_cli/dist/shared/extra-utils/videos/live-command.js
peertube-v3.4.0_cli/dist/shared/extra-utils/videos/playlists-command.js
peertube-v3.4.0_cli/dist/shared/extra-utils/videos/services-command.js
peertube-v3.4.0_cli/dist/shared/extra-utils/videos/streaming-playlists-command.js
peertube-v3.4.0_cli/dist/shared/extra-utils/videos/streaming-playlists.js
peertube-v3.4.0_cli/dist/shared/extra-utils/videos/videos-command.js
peertube-v3.4.0_cli/dist/shared/extra-utils/videos/videos.js
peertube-v3.4.0_cli/dist/shared/extra-utils/server/servers-command.js
peertube-v3.4.0_cli/dist/shared/extra-utils/server/stats-command.js
peertube-v3.4.0_cli/dist/shared/extra-utils/server/tracker.js
```

for all of these modules:

```
@shared/extra-utils/
@shared/models/
@server/helpers/core-utils
@server/helpers/ffprobe-utils
@shared/core-utils
```

and now it's working. The remaining question is what is the cause, and why possibly anyone other has not met this situation yet too. And the answer should define the way of the fix. Currently, I can write mine for my purposes (Find&replace bash script).
