### ISSUE TITLE
Error applying migration 0200-video-published-at.js

### ISSUE THREAD

**Issue by rhaamo** [Chocobozzz/PeerTube#443]
* **PeerTube version or URL: current master (2922e048de95738b3319054ce0778f873a34a0ee)**
* **NodeJS version: 9.something**

* **What is the expected behaviour?**
No error
* **What do you see instead?**
An error about SQL

TL;DR: ```SequelizeDatabaseError: column "publishedAt" contains null values```

```ADD COLUMN \"publishedAt\" TIMESTAMP WITH TIME ZONE NOT NULL``` may need a DEFAULT value even if backfill after migration ?
It would migrate from an empty DB but fails with already inserted elements.

* **Server log if useful (Gist/Pastebin...):**
```
mars 30 13:54:55 scw-d5bf90-peertube peertube[27513]: [tube.otter.sh:443] 2018-03-30 13:54:55.200 info: Begin migrations.
mars 30 13:54:55 scw-d5bf90-peertube peertube[27513]: [tube.otter.sh:443] 2018-03-30 13:54:55.212 info: Executing 0200-video-published-at.js migration script.
mars 30 13:54:55 scw-d5bf90-peertube peertube[27513]: [tube.otter.sh:443] 2018-03-30 13:54:55.261 error: Cannot execute migration 0200. {
mars 30 13:54:55 scw-d5bf90-peertube peertube[27513]:   "meta": {
mars 30 13:54:55 scw-d5bf90-peertube peertube[27513]:     "err": "SequelizeDatabaseError: column \"publishedAt\" contains null values\n
    at Query.formatError (/var/www/peertube/versions/peertube-master/node_modules/sequelize/lib/dialects/postgres/query.js:363:16)\n
    at query.catch.err (/var/www/peertube/versions/peertube-master/node_modules/sequelize/lib/dialects/postgres/query.js:86:18)\n
    at tryCatcher (/var/www/peertube/versions/peertube-master/node_modules/bluebird/js/release/util.js:16:23)\n
    at Promise._settlePromiseFromHandler (/var/www/peertube/versions/peertube-master/node_modules/bluebird/js/release/promise.js:512:31)\n
    at Promise._settlePromise (/var/www/peertube/versions/peertube-master/node_modules/bluebird/js/release/promise.js:569:18)\n
    at Promise._settlePromise0 (/var/www/peertube/versions/peertube-master/node_modules/bluebird/js/release/promise.js:614:10)\n
    at Promise._settlePromises (/var/www/peertube/versions/peertube-master/node_modules/bluebird/js/release/promise.js:689:18)\n
    at Async._drainQueue (/var/www/peertube/versions/peertube-master/node_modules/bluebird/js/release/async.js:133:16)\n
    at Async._drainQueues (/var/www/peertube/versions/peertube-master/node_modules/bluebird/js/release/async.js:143:10)\n
    at Immediate.Async.drainQueues [as _onImmediate] (/var/www/peertube/versions/peertube-master/node_modules/bluebird/js/release/async.js:17:14)\n
    at runCallback (timers.js:763:18)\n
    at tryOnImmediate (timers.js:734:5)\n
    at processImmediate (timers.js:716:5)"
mars 30 13:54:55 scw-d5bf90-peertube peertube[27513]:   }
mars 30 13:54:55 scw-d5bf90-peertube peertube[27513]: }
```

From peertube.log:
```json
{"message":"Begin migrations.","level":"info","timestamp":"2018-03-30T12:05:57.559Z","label":"tube.otter.sh:443"}
{"level":"info","message":"Executing 0200-video-published-at.js migration script.","splat":["0200-video-published-at.js"],"timestamp":"2018-03-30T12:05:57.575Z","label":"tube.otter.sh:443"}
{"level":"error","message":"Cannot execute migration 0200.","splat":["0200"],"meta":{"err":{"name":"SequelizeDatabaseError","parent":{"name":"error","length":132,"severity":"ERROR","code":"23502","schema":"public","table":"video","column":"publishedAt","file":"tablecmds.c","line":"4558","routine":"ATRewriteTable","sql":"ALTER TABLE \"public\".\"video\" ADD COLUMN \"publishedAt\" TIMESTAMP WITH TIME ZONE NOT NULL;"},"original":{"name":"error","length":132,"severity":"ERROR","code":"23502","schema":"public","table":"video","column":"publishedAt","file":"tablecmds.c","line":"4558","routine":"ATRewriteTable","sql":"ALTER TABLE \"public\".\"video\" ADD COLUMN \"publishedAt\" TIMESTAMP WITH TIME ZONE NOT NULL;"},"sql":"ALTER TABLE \"public\".\"video\" ADD COLUMN \"publishedAt\" TIMESTAMP WITH TIME ZONE NOT NULL;"}},"timestamp":"2018-03-30T12:05:57.660Z","label":"tube.otter.sh:443"}
```

**Comment by Chocobozzz** [comment]
Fixed: https://github.com/Chocobozzz/PeerTube/commit/79d28db3f916d53a6c22509ecef77588b1930be6

Thanks for the issue.
