### ISSUE TITLE
Migration Instance - Issue with PG_RESTORE - Unique Key

### ISSUE THREAD

**Issue by warnerbryce** [Chocobozzz/PeerTube#4441]
**Following the Migration Instance Documentation don't work as expected**

**Steps to reproduce:**

1. Follow this https://docs.joinpeertube.org/maintain-migration
2. Stop the Old Worling PeerTube Instance / Dump the Database / Transfert the Dump / Import the Dump
3. Start the New PeerTube, not working

**Describe the expected behavior**
Having a working PeerTube service starting

**Additional information**

* PeerTube instance: 3.4.0 on both OLD and NEW instance
  
Here is the log of the pg_restore command : 
`
sudo -u postgres pg_restore -c -C -d postgres /tmp/peertube_prod-dump.db
pg_restore: while PROCESSING TOC:
pg_restore: from TOC entry 3700; 1262 16385 DATABASE peertube_prod peertube
pg_restore: error: could not execute query: ERROR:  database "peertube_prod" does not exist
Command was: DROP DATABASE peertube_prod;
pg_restore: from TOC entry 5; 2615 2200 SCHEMA public postgres
pg_restore: error: could not execute query: ERROR:  schema "public" already exists
Command was: CREATE SCHEMA public;

pg_restore: from TOC entry 3242; 1259 16638 INDEX tag_name peertube
pg_restore: error: could not execute query: ERROR:  could not create unique index "tag_name"
DETAIL:  Key (name)=(autocensure) is duplicated.
Command was: CREATE UNIQUE INDEX tag_name ON public.tag USING btree (name);

pg_restore: warning: errors ignored on restore: 3
`

And then when you try to start PeerTube : 
`Sep 28 12:51:06 ubuntu peertube[24525]: [peertube.DOMAIN.fr:443] 2021-09-28 12:51:06.775 info: Database peertube_prod is ready.
Sep 28 12:51:06 ubuntu peertube[24525]: [peertube.DOMAIN.fr:443] 2021-09-28 12:51:06.960 error: Cannot install application. {
Sep 28 12:51:06 ubuntu peertube[24525]:   "err": {
Sep 28 12:51:06 ubuntu peertube[24525]:     "stack": "SequelizeUniqueConstraintError: Validation error\n    at Query.formatError (/var/www/peertube/versions/peertube-v3.4.0/node_modules/sequelize/lib/dialects/postgres/query.js:344:18)\n    at Query.run (/var/www/peertube/versions/peertube-v3.4.0/node_modules/sequelize/lib/dialects/postgres/query.js:87:18)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async /var/www/peertube/versions/peertube-v3.4.0/node_modules/sequelize/lib/sequelize.js:619:16\n    at async PostgresQueryInterface.addIndex (/var/www/peertube/versions/peertube-v3.4.0/node_modules/sequelize/lib/dialects/abstract/query-interface.js:541:12)\n    at async Function.sync (/var/www/peertube/versions/peertube-v3.4.0/node_modules/sequelize/lib/model.js:1367:7)\n    at async Sequelize.sync (/var/www/peertube/versions/peertube-v3.4.0/node_modules/sequelize/lib/sequelize.js:793:35)\n    at async Promise.all (index 0)",
Sep 28 12:51:06 ubuntu peertube[24525]:     "message": "Validation error",
Sep 28 12:51:06 ubuntu peertube[24525]:     "name": "SequelizeUniqueConstraintError",
Sep 28 12:51:06 ubuntu peertube[24525]:     "errors": [
Sep 28 12:51:06 ubuntu peertube[24525]:       {
Sep 28 12:51:06 ubuntu peertube[24525]:         "message": "name must be unique",
Sep 28 12:51:06 ubuntu peertube[24525]:         "type": "unique violation",
Sep 28 12:51:06 ubuntu peertube[24525]:         "path": "name",
Sep 28 12:51:06 ubuntu peertube[24525]:         "value": "autocensure",
Sep 28 12:51:06 ubuntu peertube[24525]:         "origin": "DB",
Sep 28 12:51:06 ubuntu peertube[24525]:         "instance": null,
Sep 28 12:51:06 ubuntu peertube[24525]:         "validatorKey": "not_unique",
Sep 28 12:51:06 ubuntu peertube[24525]:         "validatorName": null,
Sep 28 12:51:06 ubuntu peertube[24525]:         "validatorArgs": []
Sep 28 12:51:06 ubuntu peertube[24525]:       }
Sep 28 12:51:06 ubuntu peertube[24525]:     ],
Sep 28 12:51:06 ubuntu peertube[24525]:     "fields": {
Sep 28 12:51:06 ubuntu peertube[24525]:       "name": "autocensure"
Sep 28 12:51:06 ubuntu peertube[24525]:     },
Sep 28 12:51:06 ubuntu peertube[24525]:     "parent": {
Sep 28 12:51:06 ubuntu peertube[24525]:       "stack": "error: could not create unique index \"tag_name\"\n    at Parser.parseErrorMessage (/var/www/peertube/versions/peertube-v3.4.0/node_modules/pg-protocol/dist/parser.js:287:98)\n    at Parser.handlePacket (/var/www/peertube/versions/peertube-v3.4.0/node_modules/pg-protocol/dist/parser.js:126:29)\n    at Parser.parse (/var/www/peertube/versions/peertube-v3.4.0/node_modules/pg-protocol/dist/parser.js:39:38)\n    at Socket.<anonymous> (/var/www/peertube/versions/peertube-v3.4.0/node_modules/pg-protocol/dist/index.js:11:42)\n    at Socket.emit (node:events:390:28)\n    at Socket.emit (node:domain:475:12)\n    at addChunk (node:internal/streams/readable:315:12)\n    at readableAddChunk (node:internal/streams/readable:289:9)\n    at Socket.Readable.push (node:internal/streams/readable:228:10)\n    at TCP.onStreamRead (node:internal/stream_base_commons:199:23)",
Sep 28 12:51:06 ubuntu peertube[24525]:       "message": "could not create unique index \"tag_name\"",
Sep 28 12:51:06 ubuntu peertube[24525]:       "length": 175,
Sep 28 12:51:06 ubuntu peertube[24525]:       "name": "error",
Sep 28 12:51:06 ubuntu peertube[24525]:       "severity": "ERROR",
Sep 28 12:51:06 ubuntu peertube[24525]:       "code": "23505",
Sep 28 12:51:06 ubuntu peertube[24525]:       "detail": "Key (name)=(autocensure) is duplicated.",
Sep 28 12:51:06 ubuntu peertube[24525]:       "schema": "public",
Sep 28 12:51:06 ubuntu peertube[24525]:       "table": "tag",
Sep 28 12:51:06 ubuntu peertube[24525]:       "constraint": "tag_name",
Sep 28 12:51:06 ubuntu peertube[24525]:       "file": "tuplesort.c",
Sep 28 12:51:06 ubuntu peertube[24525]:       "line": "4049",
Sep 28 12:51:06 ubuntu peertube[24525]:       "routine": "comparetup_index_btree",
Sep 28 12:51:06 ubuntu peertube[24525]:       "sql": "CREATE UNIQUE INDEX \"tag_name\" ON \"tag\" (\"name\")"
Sep 28 12:51:06 ubuntu peertube[24525]:     },
Sep 28 12:51:06 ubuntu peertube[24525]:     "sql": "CREATE UNIQUE INDEX \"tag_name\" ON \"tag\" (\"name\")"
Sep 28 12:51:06 ubuntu peertube[24525]:   }
Sep 28 12:51:06 ubuntu peertube[24525]: }
`

**Comment by warnerbryce** [comment]
@Chocobozzz i made an uncompressed dump of my database and found something strange. 
i get a lot of tag_name twice or more while normally tag_name must be unique. 
i get a lot of FreeSoftware / Free Software and stopcovid or autocensure

so i changed some tag_name for being unique like Free Software 1 / 2 / 3 and so on. 
now i can import without problem but does it will affect my instance. What is the better way to do ?
