### ISSUE TITLE
Remote Storage: SignatureDoesNotMatch on move-to-object-storage job

### ISSUE THREAD

**Issue by DeadSuperHero** [Chocobozzz/PeerTube#4452]
I'm in the process of trying to migrate over from the [old way](https://docs.joinpeertube.org/admin-remote-storage?id=old-object-storage-method) of using S3-compatible integration with FUSE, in favor of the new "native" way that comes with PeerTube 3.4.0.

Following [the documentation](https://docs.joinpeertube.org/admin-remote-storage?id=native-object-storage) and [the config file example](https://github.com/Chocobozzz/PeerTube/blob/develop/config/production.yaml.example#L96), I managed to port over all of the values from my old integration.

Following that, I uploaded a test video with a "Private" setting, and after encoding, the video just displays a message of "this video is being moved to a different server. Things may not work correctly", and unfortunately that message never disappeared.

ONE PIECE OF INFO OMITTED EARLIER: I'm using Linode Object Storage, which is S3-compatible.

Looking into the logs, I get this error for my video:

```


Job: 10 Type: move-to-object-storage 
Processed on Oct 4, 2021, 5:43:19 PM 
Finished on Oct 4, 2021, 5:43:19 PM
--
{   "videoUUID": "8b52f0f5-7689-40c4-9edf-3ffca8982f0e",
   "isNewVideo": true }

SignatureDoesNotMatch: SignatureDoesNotMatch
     at deserializeAws_restXmlPutObjectCommandError (/var/www/peertube/versions/peertube-v3.4.0/node_modules/@aws-sdk/client-s3/dist/cjs/protocols/Aws_restXml.js:8254:41)
     at runMicrotasks (<anonymous>)
     at processTicksAndRejections (internal/process/task_queues.js:94:5)
     at async /var/www/peertube/versions/peertube-v3.4.0/node_modules/@aws-sdk/middleware-serde/dist/cjs/deserializerMiddleware.js:6:20
     at async /var/www/peertube/versions/peertube-v3.4.0/node_modules/@aws-sdk/middleware-signing/dist/cjs/middleware.js:11:20
     at async StandardRetryStrategy.retry (/var/www/peertube/versions/peertube-v3.4.0/node_modules/@aws-sdk/middleware-retry/dist/cjs/StandardRetryStrategy.js:51:46)
     at async /var/www/peertube/versions/peertube-v3.4.0/node_modules/@aws-sdk/middleware-logger/dist/cjs/loggerMiddleware.js:6:22

```

From the looks of it, the file never actually arrives in my Object Storage bucket. I'm not really sure why this is the case? The credentials and details should all match my old configuration. How do I work around this?
FWIW: I've tried both using the AWS values in the config, and then switched to having it in a .aws file like the documentation recommended, but I have yet to make any further progress here. I'm now working to revert back to the old integration for the time being, but I'd really love to figure out a way forward!

**Additional information**

* PeerTube instance:
  * URL: https://spectra.video
  * version: 3.4.0
  * NodeJS version: v12.14.1
  * Ffmpeg version: ffmpeg version 4.3.1-4ubuntu1

**Comment by DeadSuperHero** [comment]
I've figured it out!

It turns out that Linode Object Storage has [[an undocumented piece of behavior](https://www.linode.com/community/questions/19536/object-storage-upload-problem#answer-71909) in client calls. Basically, you have to set the `region` parameter to a value of `default`, rather than the expected region. Your `endpoint` parameter basically contains the region in it! (Example: mine is `https://us-east-1.linodeobjects.com`)
