### ISSUE TITLE
Ошибка ночной сборки

### ISSUE THREAD

**Issue by Alterak** [Chocobozzz/PeerTube#4466]
Nightly builds don't work, versions
`peertube-nightly-2021-10-13.tar.xz`
and
`peertube-nightly-2021-10-14.tar.xz`

At startup, it gives an error

```
окт 14 08:17:52 media systemd[1]: Started PeerTube daemon.
окт 14 08:17:52 media peertube[34520]: /var/www/peertube/versions/peertube-nightly-2021-10-14/node_modules/config/lib/config.js:182
окт 14 08:17:52 media peertube[34520]:     throw new Error('Configuration property "' + property + '" is not defined');
окт 14 08:17:52 media peertube[34520]:     ^
окт 14 08:17:52 media peertube[34520]: Error: Configuration property "webadmin.configuration.edit.allowed" is not defined
окт 14 08:17:52 media peertube[34520]:     at Config.get (/var/www/peertube/versions/peertube-nightly-2021-10-14/node_modules/config/lib/config.js:182:11)
окт 14 08:17:52 media peertube[34520]:     at Object.<anonymous> (/var/www/peertube/versions/peertube-nightly-2021-10-14/dist/server/initializers/config.js:202:33)
окт 14 08:17:52 media peertube[34520]:     at Module._compile (internal/modules/cjs/loader.js:1085:14)
окт 14 08:17:52 media peertube[34520]:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
окт 14 08:17:52 media peertube[34520]:     at Module.load (internal/modules/cjs/loader.js:950:32)
окт 14 08:17:52 media peertube[34520]:     at Function.Module._load (internal/modules/cjs/loader.js:790:12)
окт 14 08:17:52 media peertube[34520]:     at Module.require (internal/modules/cjs/loader.js:974:19)
окт 14 08:17:52 media peertube[34520]:     at require (internal/modules/cjs/helpers.js:93:18)
окт 14 08:17:52 media peertube[34520]:     at Object.<anonymous> (/var/www/peertube/versions/peertube-nightly-2021-10-14/dist/server/helpers/logger.js:10:18)
окт 14 08:17:52 media peertube[34520]:     at Module._compile (internal/modules/cjs/loader.js:1085:14)
окт 14 08:17:52 media systemd[1]: peertube.service: Main process exited, code=exited, status=1/FAILURE
окт 14 08:17:52 media systemd[1]: peertube.service: Failed with result 'exit-code'.
окт 14 08:17:52 media systemd[1]: peertube.service: Scheduled restart job, restart counter is at 1.
окт 14 08:17:52 media systemd[1]: Stopped PeerTube daemon.
окт 14 08:17:52 media systemd[1]: Started PeerTube daemon.
окт 14 08:17:53 media peertube[34531]: /var/www/peertube/versions/peertube-nightly-2021-10-14/node_modules/config/lib/config.js:182
окт 14 08:17:53 media peertube[34531]:     throw new Error('Configuration property "' + property + '" is not defined');
окт 14 08:17:53 media peertube[34531]:     ^
окт 14 08:17:53 media peertube[34531]: Error: Configuration property "webadmin.configuration.edit.allowed" is not defined
окт 14 08:17:53 media peertube[34531]:     at Config.get (/var/www/peertube/versions/peertube-nightly-2021-10-14/node_modules/config/lib/config.js:182:11)
окт 14 08:17:53 media peertube[34531]:     at Object.<anonymous> (/var/www/peertube/versions/peertube-nightly-2021-10-14/dist/server/initializers/config.js:202:33)
окт 14 08:17:53 media peertube[34531]:     at Module._compile (internal/modules/cjs/loader.js:1085:14)
окт 14 08:17:53 media peertube[34531]:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
окт 14 08:17:53 media peertube[34531]:     at Module.load (internal/modules/cjs/loader.js:950:32)
окт 14 08:17:53 media peertube[34531]:     at Function.Module._load (internal/modules/cjs/loader.js:790:12)
окт 14 08:17:53 media peertube[34531]:     at Module.require (internal/modules/cjs/loader.js:974:19)
окт 14 08:17:53 media peertube[34531]:     at require (internal/modules/cjs/helpers.js:93:18)
окт 14 08:17:53 media peertube[34531]:     at Object.<anonymous> (/var/www/peertube/versions/peertube-nightly-2021-10-14/dist/server/helpers/logger.js:10:18)
окт 14 08:17:53 media peertube[34531]:     at Module._compile (internal/modules/cjs/loader.js:1085:14)
окт 14 08:17:53 media systemd[1]: peertube.service: Main process exited, code=exited, status=1/FAILURE
окт 14 08:17:53 media systemd[1]: peertube.service: Failed with result 'exit-code'.
окт 14 08:17:53 media systemd[1]: peertube.service: Scheduled restart job, restart counter is at 2.
окт 14 08:17:53 media systemd[1]: Stopped PeerTube daemon.
окт 14 08:17:53 media systemd[1]: Started PeerTube daemon.
окт 14 08:17:53 media peertube[34542]: /var/www/peertube/versions/peertube-nightly-2021-10-14/node_modules/config/lib/config.js:182
окт 14 08:17:53 media peertube[34542]:     throw new Error('Configuration property "' + property + '" is not defined');
окт 14 08:17:53 media peertube[34542]:     ^
окт 14 08:17:53 media peertube[34542]: Error: Configuration property "webadmin.configuration.edit.allowed" is not defined
окт 14 08:17:53 media peertube[34542]:     at Config.get (/var/www/peertube/versions/peertube-nightly-2021-10-14/node_modules/config/lib/config.js:182:11)
окт 14 08:17:53 media peertube[34542]:     at Object.<anonymous> (/var/www/peertube/versions/peertube-nightly-2021-10-14/dist/server/initializers/config.js:202:33)
окт 14 08:17:53 media peertube[34542]:     at Module._compile (internal/modules/cjs/loader.js:1085:14)
окт 14 08:17:53 media peertube[34542]:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
окт 14 08:17:53 media peertube[34542]:     at Module.load (internal/modules/cjs/loader.js:950:32)
окт 14 08:17:53 media peertube[34542]:     at Function.Module._load (internal/modules/cjs/loader.js:790:12)
окт 14 08:17:53 media peertube[34542]:     at Module.require (internal/modules/cjs/loader.js:974:19)
окт 14 08:17:53 media peertube[34542]:     at require (internal/modules/cjs/helpers.js:93:18)
окт 14 08:17:53 media peertube[34542]:     at Object.<anonymous> (/var/www/peertube/versions/peertube-nightly-2021-10-14/dist/server/helpers/logger.js:10:18)
окт 14 08:17:53 media peertube[34542]:     at Module._compile (internal/modules/cjs/loader.js:1085:14)
окт 14 08:17:53 media systemd[1]: peertube.service: Main process exited, code=exited, status=1/FAILURE
окт 14 08:17:53 media systemd[1]: peertube.service: Failed with result 'exit-code'.
окт 14 08:17:53 media systemd[1]: peertube.service: Scheduled restart job, restart counter is at 3.
окт 14 08:17:53 media systemd[1]: Stopped PeerTube daemon.
окт 14 08:17:53 media systemd[1]: Started PeerTube daemon.
окт 14 08:17:54 media peertube[34553]: /var/www/peertube/versions/peertube-nightly-2021-10-14/node_modules/config/lib/config.js:182
окт 14 08:17:54 media peertube[34553]:     throw new Error('Configuration property "' + property + '" is not defined');
окт 14 08:17:54 media peertube[34553]:     ^
окт 14 08:17:54 media peertube[34553]: Error: Configuration property "webadmin.configuration.edit.allowed" is not defined
окт 14 08:17:54 media peertube[34553]:     at Config.get (/var/www/peertube/versions/peertube-nightly-2021-10-14/node_modules/config/lib/config.js:182:11)
окт 14 08:17:54 media peertube[34553]:     at Object.<anonymous> (/var/www/peertube/versions/peertube-nightly-2021-10-14/dist/server/initializers/config.js:202:33)
окт 14 08:17:54 media peertube[34553]:     at Module._compile (internal/modules/cjs/loader.js:1085:14)
окт 14 08:17:54 media peertube[34553]:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
окт 14 08:17:54 media peertube[34553]:     at Module.load (internal/modules/cjs/loader.js:950:32)
окт 14 08:17:54 media peertube[34553]:     at Function.Module._load (internal/modules/cjs/loader.js:790:12)
окт 14 08:17:54 media peertube[34553]:     at Module.require (internal/modules/cjs/loader.js:974:19)
окт 14 08:17:54 media peertube[34553]:     at require (internal/modules/cjs/helpers.js:93:18)
окт 14 08:17:54 media peertube[34553]:     at Object.<anonymous> (/var/www/peertube/versions/peertube-nightly-2021-10-14/dist/server/helpers/logger.js:10:18)
окт 14 08:17:54 media peertube[34553]:     at Module._compile (internal/modules/cjs/loader.js:1085:14)
окт 14 08:17:54 media systemd[1]: peertube.service: Main process exited, code=exited, status=1/FAILURE
окт 14 08:17:54 media systemd[1]: peertube.service: Failed with result 'exit-code'.
окт 14 08:17:54 media systemd[1]: peertube.service: Scheduled restart job, restart counter is at 4.
окт 14 08:17:54 media systemd[1]: Stopped PeerTube daemon.
окт 14 08:17:54 media systemd[1]: Started PeerTube daemon.
окт 14 08:17:54 media peertube[34564]: /var/www/peertube/versions/peertube-nightly-2021-10-14/node_modules/config/lib/config.js:182
окт 14 08:17:54 media peertube[34564]:     throw new Error('Configuration property "' + property + '" is not defined');
окт 14 08:17:54 media peertube[34564]:     ^
окт 14 08:17:54 media peertube[34564]: Error: Configuration property "webadmin.configuration.edit.allowed" is not defined
окт 14 08:17:54 media peertube[34564]:     at Config.get (/var/www/peertube/versions/peertube-nightly-2021-10-14/node_modules/config/lib/config.js:182:11)
окт 14 08:17:54 media peertube[34564]:     at Object.<anonymous> (/var/www/peertube/versions/peertube-nightly-2021-10-14/dist/server/initializers/config.js:202:33)
окт 14 08:17:54 media peertube[34564]:     at Module._compile (internal/modules/cjs/loader.js:1085:14)
окт 14 08:17:54 media peertube[34564]:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
окт 14 08:17:54 media peertube[34564]:     at Module.load (internal/modules/cjs/loader.js:950:32)
окт 14 08:17:54 media peertube[34564]:     at Function.Module._load (internal/modules/cjs/loader.js:790:12)
окт 14 08:17:54 media peertube[34564]:     at Module.require (internal/modules/cjs/loader.js:974:19)
окт 14 08:17:54 media peertube[34564]:     at require (internal/modules/cjs/helpers.js:93:18)
окт 14 08:17:54 media peertube[34564]:     at Object.<anonymous> (/var/www/peertube/versions/peertube-nightly-2021-10-14/dist/server/helpers/logger.js:10:18)
окт 14 08:17:54 media peertube[34564]:     at Module._compile (internal/modules/cjs/loader.js:1085:14)
окт 14 08:17:54 media systemd[1]: peertube.service: Main process exited, code=exited, status=1/FAILURE
окт 14 08:17:54 media systemd[1]: peertube.service: Failed with result 'exit-code'.
окт 14 08:17:54 media systemd[1]: peertube.service: Scheduled restart job, restart counter is at 5.
окт 14 08:17:54 media systemd[1]: Stopped PeerTube daemon.
окт 14 08:17:54 media systemd[1]: peertube.service: Start request repeated too quickly.
окт 14 08:17:54 media systemd[1]: peertube.service: Failed with result 'exit-code'.
окт 14 08:17:54 media systemd[1]: Failed to start PeerTube daemon.
```

**Comment by Chocobozzz** [comment]
Thanks, please try to upgrade your config file (https://github.com/Chocobozzz/PeerTube/commit/e89392d74aabddbee1c43dcb7e1b40d3d7eec1ed)

**Comment by Alterak** [comment]
> Thanks, please try to upgrade your config file ([e89392d](https://github.com/Chocobozzz/PeerTube/commit/e89392d74aabddbee1c43dcb7e1b40d3d7eec1ed))

Everything works fine now. But I immediately found another problem ... In the admin panel, I cannot edit any messages or descriptions-))
I have a nightly build **3.4.1-nightly-2021-10-14**

![Screenshot_1](https://user-images.githubusercontent.com/11453567/137277730-e9ecae58-49c5-4631-b7e8-4d2287e29291.png)
)
