### ISSUE TITLE
Impossible to finish a CLI transcode

### ISSUE THREAD

**Issue by warnerbryce** [Chocobozzz/PeerTube#4472]
**Describe the current behavior**
I've uploaded a video on my instance, but I forgot to configure the desired resolution before in the config panel.
So as I have already done that in the past, I went to my PeerTube server in SSH and as "peertube" user created a job for converting my video from 1080 to 720.
The job works well except that at 100% I get an error : 

{   "type": "new-resolution-to-hls",  
 "videoUUID": "84669a33-97d4-451e-950a-2aa90c6cb3c2",   
"resolution": "720",   
"copyCodecs": true,   
"isMaxQuality": false,   
"isNewVideo": false }

TypeError: Cannot read properties of undefined (reading 'getVideoOrStreamingPlaylist')     
at /var/www/peertube/versions/peertube-v3.4.1/dist/server/lib/job-queue/handlers/video-transcoding.js:48:57 
at Generator.next (<anonymous>)     
at /var/www/peertube/versions/peertube-v3.4.1/node_modules/tslib/tslib.js:117:75     
at new Promise (<anonymous>)     
at Object.__awaiter (/var/www/peertube/versions/peertube-v3.4.1/node_modules/tslib/tslib.js:113:16)     
at handleHLSJob (/var/www/peertube/versions/peertube-v3.4.1/dist/server/lib/job-queue/handlers/video-transcoding.js:43:20)
at Queue.<anonymous> (/var/www/peertube/versions/peertube-v3.4.1/dist/server/lib/job-queue/handlers/video-transcoding.js:37:15)     
at Generator.next (<anonymous>)     
at fulfilled (/var/www/peertube/versions/peertube-v3.4.1/node_modules/tslib/tslib.js:114:62)     
at runMicrotasks (<anonymous>)     at processTicksAndRejections (node:internal/process/task_queues:96:5)

I've restart several time this process, same problem. 
getVideoOrStreamingPlaylist is really odd because this video isn't part of any of my Playlist, just a vidéo in my channel.

**Comment by Chocobozzz** [comment]
Fixed by https://github.com/Chocobozzz/PeerTube/commit/8aad7ae413e58ae2ef847c5e12419c45f4ff55be
