### ISSUE TITLE
upload.js: Invalid config source

### ISSUE THREAD

**Issue by andzdroid** [Chocobozzz/PeerTube#448]
* **PeerTube version or URL:** develop branch, commit f209b32afaffbb8b93c265525ebde182ab66c37a
* **Browser name/version:**
* **NodeJS version:** 8.11.1

* **What is the expected behaviour?**
Print the help message from upload.js
* **What do you see instead?**
Error and stack trace

* **Browser console log if useful (Gist/Pastebin...):**
* **Server log if useful (Gist/Pastebin...):**

```
node upload.js --help
WARNING: No configurations found in configuration directory:/home/andz/PeerTube/dist/server/tools/config
WARNING: To disable this warning set SUPPRESS_NO_CONFIG_WARNING in the environment.
/home/andz/PeerTube/dist/server/initializers/constants.js:433
        throw new Error('Invalid config source.');
        ^

Error: Invalid config source.
    at getLocalConfigFilePath (/home/andz/PeerTube/dist/server/initializers/constants.js:433:15)
    at Object.<anonymous> (/home/andz/PeerTube/dist/server/initializers/constants.js:81:18)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/andz/PeerTube/dist/server/initializers/index.js:7:10)
```

**Comment by Chocobozzz** [comment]
As specified in [the documentation](https://github.com/Chocobozzz/PeerTube/blob/develop/support/doc/tools.md#uploadjs), it's `node dist/server/tools/upload.js --help` at the root of the cloned repository.

**Comment by andzdroid** [comment]
Thanks.

Can I ask why it needs the config folder? I expected that since it gets passed the host url and user login, it would be able to run independently, and even upload to any peertube instance. It would be nice if these utilities could be downloaded without needing to clone the project or run any kind of build process.
