### ISSUE TITLE
Peertube appears to be blocked by youtube

### ISSUE THREAD

**Issue by SimplyCorbett** [Chocobozzz/PeerTube#4550]
Youtube-dl and yt-dlp do not import on the latest git version. On this version there are no errors. A few days ago the same issue occurred but the error was 404 forbidden.

It's entirely possible youtube is blocking my peertube instance, however yt-dlp when used directly downloads the video correctly from the same machine.

To replicate:
Import any video (my test video was https://www.youtube.com/watch?v=JfVOs4VSpmA)

* PeerTube instance:
  * URL: private
  * version: GIT 04868c1
  * NodeJS version: 16.10.1
  * Ffmpeg version: 4.4.1

**Comment by SimplyCorbett** [comment]
Ah yeah, okay it is a youtube specific issue. Not sure if they are blocking me or if they are blocking peertube itself. Again directly using yt-dlp works.

**Comment by SimplyCorbett** [comment]
Yeah, they're blocking peertube. I can watch youtube on the node from firefox along with direct download of yt-dlp.

```
Error: Command failed with exit code 1: python /mnt/raid/peertube/storage/bin/yt-dlp --force-ipv4 -f bestvideo[vcodec^=avc1][height=1080]+bestaudio[ext=m4a]/bestvideo[vcodec!*=av01][vcodec!*=vp9.2][height=1080]+bestaudio/bestvideo[vcodec^=avc1][height<=1080]+bestaudio[ext=m4a]/bestvideo[vcodec!*=av01][vcodec!*=vp9.2]+bestaudio/best[vcodec!*=av01][vcodec!*=vp9.2]/best -o /mnt/raid/peertube/storage/tmp/479172a9d6d5da6abd61cfc6de07e040205ec2a99f0e597b36bf13d42eecec2f-import https://www.youtube.com/watch?v=fXx8xTM2U0s
ERROR: unable to download video data: HTTP Error 403: Forbidden
[youtube] fXx8xTM2U0s: Downloading webpage
    at makeError (/mnt/raid/peertube/versions/peertube-develop/node_modules/execa/lib/error.js:60:11)
    at handlePromise (/mnt/raid/peertube/versions/peertube-develop/node_modules/execa/index.js:118:26)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

**Comment by SimplyCorbett** [comment]
Nope, nevermind. It's a yt-dlp issue. youtube-dl works but it's heavily rate limited and takes forever to finish. Not surprising given how outdated it is.

**Comment by SimplyCorbett** [comment]
Hmm. I'm going to say this is my problem and not peertubes. I'll close this unless I have something more conclusive.
