### ISSUE TITLE
FreeBSD: Cannot find module /napi-v3/bcrypt_lib.node

### ISSUE THREAD

**Issue by lpvm** [Chocobozzz/PeerTube#4566]
I'm installing Peertube in a FreeBSD 13.0-RELEASE jail.
I've followed the steps described and issued a command:
`sudo -H -u peertube yarn install --production --pure-lockfile`

This creates the `node_modules` directory and populates it with circa 137MB of packages.

When starting `peertube`, as `node dist/server`:

```
[localhost:9000] 2021-11-25 14:14:05.812 error: uncaughtException: Cannot find module '/var/www/peertube/versions/peertube-v3.4.1/node_modules/bcrypt/lib/binding/napi-v3/bcrypt_lib.node'
Require stack:
- /var/www/peertube/versions/peertube-v3.4.1/node_modules/bcrypt/bcrypt.js
- /var/www/peertube/versions/peertube-v3.4.1/dist/server/helpers/peertube-crypto.js
- /var/www/peertube/versions/peertube-v3.4.1/dist/server/models/user/user.js
- /var/www/peertube/versions/peertube-v3.4.1/dist/server/initializers/checker-after-init.js
- /var/www/peertube/versions/peertube-v3.4.1/dist/server.js
Error: Cannot find module '/var/www/peertube/versions/peertube-v3.4.1/node_modules/bcrypt/lib/binding/napi-v3/bcrypt_lib.node'
```
Bcrypt is installed.  From the jail:
```
# find / -name '*bcrypt*'
/sharedfs/usr/lib/libcrypt.a
/sharedfs/usr/lib/libcrypt.so
/sharedfs/usr/lib/libcrypto.a
/sharedfs/usr/lib/libcrypt_p.a
/sharedfs/usr/lib/libcrypto_p.a
/sharedfs/usr/lib/libcrypto.so
/sharedfs/lib/libcrypto.so.111
/sharedfs/lib/libcrypt.so.5
```

I've already run that `yarn` command several times, already deleted the `node_modules` directory and the problem keeps showing up.

* PeerTube instance:
  * version: 3.4.1
  * NodeJS version: 14.18.1
  * Ffmpeg version: 4.4.1
  * Redis version: 6.2.6
  * PostgreSQL version: 14.0

Why is this happening?  What to do?

**Comment by Chocobozzz** [comment]
Please paste the output of `sudo -H -u peertube yarn install --production --pure-lockfile`

**Comment by lpvm** [comment]
Hi @Chocobozzz,
Starting from a context where the installation was done previously, the output of that command is:
```
# sudo -H -u peertube yarn install --production --pure-lockfile
yarn install v1.22.11
info No lockfile found.
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
Done in 0.37s.
```
Thank you.

**Comment by Chocobozzz** [comment]
There is something wrong: `No lockfile found.`. Ensure you run this command in `/var/www/peertube/versions/peertube-v3.4.1`. If you do, then reinstall peertube

**Comment by lpvm** [comment]
When I ran the new yarn command I removed the lock file.
As suggested, I've performed a new installation.
The output of the command `cd ./peertube-latest && sudo -H -u peertube yarn install --production --pure-lockfile` is:
```
/var/www/peertube # cd ./peertube-latest && sudo -H -u peertube yarn install --production --pure-lockfile
/var/www/peertube/peertube-latest
yarn install v1.22.11
[1/5] Validating package.json...
[2/5] Resolving packages...
[3/5] Fetching packages...
info fsevents@2.3.2: The platform "freebsd" is incompatible with this module.
info "fsevents@2.3.2" is an optional dependency and failed compatibility check. Excluding it from installation.
[4/5] Linking dependencies...
warning " > @typescript-eslint/eslint-plugin@4.29.3" has unmet peer dependency "@typescript-eslint/parser@^4.0.0".
warning " > marked-man@0.7.0" has incorrect peer dependency "marked@^0.7.0".
warning "swagger-cli > @apidevtools/swagger-cli > @apidevtools/swagger-parser@10.0.3" has unmet peer dependency "openapi-types@>=7".
[5/5] Building fresh packages...
[1/5] ⡀ bcrypt
[2/5] ⡀ bufferutil
[3/5] ⡀ utf-8-validate
[4/5] ⡀ utp-native
error /var/www/peertube/versions/peertube-v3.4.1/node_modules/youtube-dl: Command failed.
Exit code: 127
Command: npm run check && npm run download
Arguments:




warning Error running install script for optional dependency: "/var/www/peertube/versions/peertube-v3.4.1/node_modules/bufferutil: Command failed.
Exit code: 1
Command: node-gyp-build
Arguments:
Directory: /var/www/peertube/versions/peertube-v3.4.1/node_modules/bufferutil
Output:
events.js:377
      throw er; // Unhandled 'error' event
      ^

Error: spawn node-gyp ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:274:19)
    at onErrorNT (internal/child_process.js:469:16)
    at processTicksAndRejections (internal/process/task_queues.js:82:21)
Emitted 'error' event on ChildProcess instance at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:280:12)
    at onErrorNT (internal/child_process.js:469:16)
    at processTicksAndRejections (internal/process/task_queues.js:82:21) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'spawn node-gyp',
  path: 'node-gyp',
  spawnargs: [ 'rebuild' ]
}"
info This module is OPTIONAL, you can safely ignore this error
warning Error running install script for optional dependency: "/var/www/peertube/versions/peertube-v3.4.1/node_modules/utp-native: Command failed.
Exit code: 1
Command: node-gyp-build
Arguments:
Directory: /var/www/peertube/versions/peertube-v3.4.1/node_modules/utp-native
Output:
events.js:377
      throw er; // Unhandled 'error' event
      ^

Error: spawn node-gyp ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:274:19)
    at onErrorNT (internal/child_process.js:469:16)
    at processTicksAndRejections (internal/process/task_queues.js:82:21)
Emitted 'error' event on ChildProcess instance at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:280:12)
    at onErrorNT (internal/child_process.js:469:16)
    at processTicksAndRejections (internal/process/task_queues.js:82:21) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'spawn node-gyp',
  path: 'node-gyp',
  spawnargs: [ 'rebuild' ]
}"
info This module is OPTIONAL, you can safely ignore this error
warning Error running install script for optional dependency: "/var/www/peertube/versions/peertube-v3.4.1/node_modules/utf-8-validate: Command failed.
Exit code: 1
Command: node-gyp-build
Arguments:
Directory: /var/www/peertube/versions/peertube-v3.4.1/node_modules/utf-8-validate
Output:
events.js:377
      throw er; // Unhandled 'error' event
      ^

Error: spawn node-gyp ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:274:19)
    at onErrorNT (internal/child_process.js:469:16)
    at processTicksAndRejections (internal/process/task_queues.js:82:21)
Emitted 'error' event on ChildProcess instance at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:280:12)
    at onErrorNT (internal/child_process.js:469:16)
    at processTicksAndRejections (internal/process/task_queues.js:82:21) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'spawn node-gyp',
  path: 'node-gyp',
  spawnargs: [ 'rebuild' ]
}"
info This module is OPTIONAL, you can safely ignore this error
```

**Comment by Chocobozzz** [comment]
Hello,

There is something wrong in your installation: you need `node-gyp` command.

**Comment by lpvm** [comment]
Hi @Chocobozzz!

For any other FreeBSD user, ``git-lite` and `python` have to be installed.
Make sure that there's a `/usr/local/bin/python`.  Otherwise, just create the symlink as `ln -s /usr/local/bin/python3.8 /usr/local/bin/python`, for python3.8.

And then `npm install -g node-gyp`.  Maybe a local installation could also work, but I used the `-g` switch.

This issue is closed,  thank you very much for your support.
