### ISSUE TITLE
"Cannot retrieve OAuth Client credentials" after briefly turning off swap in ubuntu

### ISSUE THREAD

**Issue by SamoLaser** [Chocobozzz/PeerTube#4576]
Hi,
I'm running an instance on Ubuntu server 20.04 and encountered a problem when I momentarily disabled swap memory. When I visit a page, it throws an error:

`Cannot retrieve OAuth Client credentials: undefined. Ensure you have correctly configured PeerTube (config/ directory), in particular the "webserver" section.`

My logs say this:
`warn[11/28/2021, 12:05:28 PM] It seems PeerTube was started (and created some data) with another domain name. This means you will not be able to federate! Please use NODE_CONFIG_DIR=/var/www/peertube/config NODE_ENV=production npm run update-host to fix this. `

I checked to make sure the config files still had the correct data and then restarted peertube and nginx. I still get the error when visiting the page. Other issues mention this, and they seem to be related to port configuration. 

I ran the above command and received the message:

```
npm ERR! code ENOENT
npm ERR! syscall open
npm ERR! path /home/XYZ/package.json
npm ERR! errno -2
npm ERR! enoent ENOENT: no such file or directory, open '/home/XYZ/package.json'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/XYZ/.npm/_logs/2021-11-28T17_34_38_567Z-debug.log
```
(where I replaced by user name with XYZ)

In another thread, I saw that it was recommended that this command be run in `peertube-latest` directory. After doing so, I got more errors:

```
> peertube@3.4.1 update-host /var/www/peertube/versions/peertube-v3.4.1
> node ./dist/scripts/update-host.js

Updating actors.
Updating actor https://XYZ/video-channels/root_channel
ValidationError [SequelizeValidationError]: Validation error: "https://localhost/video-channels/root_channel" is not a valid url.,
Validation error: "https://localhost/video-channels/root_channel/inbox" is not a valid inbox url.,
Validation error: "https://localhost/video-channels/root_channel/outbox" is not a valid outbox url.,
Validation error: "https://localhost/inbox" is not a valid shared inbox url.,
Validation error: "https://localhost/video-channels/root_channel/followers" is not a valid followers url.,
Validation error: "https://localhost/video-channels/root_channel/following" is not a valid following url.
    at InstanceValidator._validate (/var/www/peertube/versions/peertube-v3.4.1/node_modules/sequelize/lib/instance-validator.js:78:13)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async InstanceValidator._validateAndRunHooks (/var/www/peertube/versions/peertube-v3.4.1/node_modules/sequelize/lib/instance-validator.js:111:7)
    at async InstanceValidator.validate (/var/www/peertube/versions/peertube-v3.4.1/node_modules/sequelize/lib/instance-validator.js:93:12)
    at async self.save (/var/www/peertube/versions/peertube-v3.4.1/node_modules/sequelize/lib/model.js:3877:7) {
  errors: [
    ValidationErrorItem {
      message: '"https://localhost/video-channels/root_channel" is not a valid url.',
      type: 'Validation error',
      path: 'url',
      value: 'https://localhost/video-channels/root_channel',
      origin: 'FUNCTION',
      instance: [ActorModel],
      validatorKey: 'isActorUrl',
      validatorName: null,
      validatorArgs: [],
      original: Error: "https://localhost/video-channels/root_channel" is not a valid url.
          at Object.throwIfNotValid (/var/www/peertube/versions/peertube-v3.4.1/dist/server/models/utils.js:102:15)
          at self.<anonymous> (/var/www/peertube/versions/peertube-v3.4.1/dist/server/models/actor/actor.js:383:60)
          at InstanceValidator._invokeCustomValidator (/var/www/peertube/versions/peertube-v3.4.1/node_modules/sequelize/lib/instance-validator.js:277:30)
          at /var/www/peertube/versions/peertube-v3.4.1/node_modules/sequelize/lib/instance-validator.js:213:30
          at /var/www/peertube/versions/peertube-v3.4.1/node_modules/lodash/lodash.js:4967:15
          at Function.forIn (/var/www/peertube/versions/peertube-v3.4.1/node_modules/lodash/lodash.js:13018:11)
          at InstanceValidator._singleAttrValidate (/var/www/peertube/versions/peertube-v3.4.1/node_modules/sequelize/lib/instance-validator.js:198:7)
          at /var/www/peertube/versions/peertube-v3.4.1/node_modules/sequelize/lib/instance-validator.js:148:30
          at /var/www/peertube/versions/peertube-v3.4.1/node_modules/lodash/lodash.js:4967:15
          at Function.forIn (/var/www/peertube/versions/peertube-v3.4.1/node_modules/lodash/lodash.js:13018:11)
          at InstanceValidator._perAttributeValidators (/var/www/peertube/versions/peertube-v3.4.1/node_modules/sequelize/lib/instance-validator.js:131:7)
          at InstanceValidator._validate (/var/www/peertube/versions/peertube-v3.4.1/node_modules/sequelize/lib/instance-validator.js:73:12)
          at InstanceValidator._validateAndRunHooks (/var/www/peertube/versions/peertube-v3.4.1/node_modules/sequelize/lib/instance-validator.js:111:18)
          at processTicksAndRejections (internal/process/task_queues.js:95:5)
          at async InstanceValidator.validate (/var/www/peertube/versions/peertube-v3.4.1/node_modules/sequelize/lib/instance-validator.js:93:12)
    },
    ValidationErrorItem {
      message: '"https://localhost/video-channels/root_channel/inbox" is not a valid inbox url.',                                                                               
      type: 'Validation error',
      path: 'inboxUrl',
      value: 'https://localhost/video-channels/root_channel/inbox',
      origin: 'FUNCTION',
      instance: [ActorModel],
      validatorKey: 'isActorInboxUrl',
      validatorName: null,
      validatorArgs: [],
      original: Error: "https://localhost/video-channels/root_channel/inbox" is not a valid inbox url.
          at Object.throwIfNotValid (/var/www/peertube/versions/peertube-v3.4.1/dist/server/models/utils.js:102:15)
          at self.<anonymous> (/var/www/peertube/versions/peertube-v3.4.1/dist/server/models/actor/actor.js:413:65)
          at InstanceValidator._invokeCustomValidator (/var/www/peertube/versions/peertube-v3.4.1/node_modules/sequelize/lib/instance-validator.js:277:30)
          at /var/www/peertube/versions/peertube-v3.4.1/node_modules/sequelize/lib/instance-validator.js:213:30
          at /var/www/peertube/versions/peertube-v3.4.1/node_modules/lodash/lodash.js:4967:15
          at Function.forIn (/var/www/peertube/versions/peertube-v3.4.1/node_modules/lodash/lodash.js:13018:11)
          at InstanceValidator._singleAttrValidate (/var/www/peertube/versions/peertube-v3.4.1/node_modules/sequelize/lib/instance-validator.js:198:7)
          at /var/www/peertube/versions/peertube-v3.4.1/node_modules/sequelize/lib/instance-validator.js:148:30
          at /var/www/peertube/versions/peertube-v3.4.1/node_modules/lodash/lodash.js:4967:15
          at Function.forIn (/var/www/peertube/versions/peertube-v3.4.1/node_modules/lodash/lodash.js:13018:11)
          at InstanceValidator._perAttributeValidators (/var/www/peertube/versions/peertube-v3.4.1/node_modules/sequelize/lib/instance-validator.js:131:7)
          at InstanceValidator._validate (/var/www/peertube/versions/peertube-v3.4.1/node_modules/sequelize/lib/instance-validator.js:73:12)
          at InstanceValidator._validateAndRunHooks (/var/www/peertube/versions/peertube-v3.4.1/node_modules/sequelize/lib/instance-validator.js:111:18)
          at processTicksAndRejections (internal/process/task_queues.js:95:5)
          at async InstanceValidator.validate (/var/www/peertube/versions/peertube-v3.4.1/node_modules/sequelize/lib/instance-validator.js:93:12)
    },
    ValidationErrorItem {
      message: '"https://localhost/video-channels/root_channel/outbox" is not a valid outbox url.',                                                                             
      type: 'Validation error',
      path: 'outboxUrl',
      value: 'https://localhost/video-channels/root_channel/outbox',
      origin: 'FUNCTION',
      instance: [ActorModel],
      validatorKey: 'isActorOutboxUrl',
      validatorName: null,
      validatorArgs: [],
      original: Error: "https://localhost/video-channels/root_channel/outbox" is not a valid outbox url.
          at Object.throwIfNotValid (/var/www/peertube/versions/peertube-v3.4.1/dist/server/models/utils.js:102:15)
          at self.<anonymous> (/var/www/peertube/versions/peertube-v3.4.1/dist/server/models/actor/actor.js:419:66)
          at InstanceValidator._invokeCustomValidator (/var/www/peertube/versions/peertube-v3.4.1/node_modules/sequelize/lib/instance-validator.js:277:30)
          at /var/www/peertube/versions/peertube-v3.4.1/node_modules/sequelize/lib/instance-validator.js:213:30
          at /var/www/peertube/versions/peertube-v3.4.1/node_modules/lodash/lodash.js:4967:15
          at Function.forIn (/var/www/peertube/versions/peertube-v3.4.1/node_modules/lodash/lodash.js:13018:11)
          at InstanceValidator._singleAttrValidate (/var/www/peertube/versions/peertube-v3.4.1/node_modules/sequelize/lib/instance-validator.js:198:7)
          at /var/www/peertube/versions/peertube-v3.4.1/node_modules/sequelize/lib/instance-validator.js:148:30
          at /var/www/peertube/versions/peertube-v3.4.1/node_modules/lodash/lodash.js:4967:15
          at Function.forIn (/var/www/peertube/versions/peertube-v3.4.1/node_modules/lodash/lodash.js:13018:11)
          at InstanceValidator._perAttributeValidators (/var/www/peertube/versions/peertube-v3.4.1/node_modules/sequelize/lib/instance-validator.js:131:7)
          at InstanceValidator._validate (/var/www/peertube/versions/peertube-v3.4.1/node_modules/sequelize/lib/instance-validator.js:73:12)
          at InstanceValidator._validateAndRunHooks (/var/www/peertube/versions/peertube-v3.4.1/node_modules/sequelize/lib/instance-validator.js:111:18)
          at processTicksAndRejections (internal/process/task_queues.js:95:5)
          at async InstanceValidator.validate (/var/www/peertube/versions/peertube-v3.4.1/node_modules/sequelize/lib/instance-validator.js:93:12)
    },
    ValidationErrorItem {
      message: '"https://localhost/inbox" is not a valid shared inbox url.',
      type: 'Validation error',
      path: 'sharedInboxUrl',
      value: 'https://localhost/inbox',
      origin: 'FUNCTION',
      instance: [ActorModel],
      validatorKey: 'isActorSharedInboxUrl',
      validatorName: null,
      validatorArgs: [],
      original: Error: "https://localhost/inbox" is not a valid shared inbox url.
          at Object.throwIfNotValid (/var/www/peertube/versions/peertube-v3.4.1/dist/server/models/utils.js:102:15)
          at self.<anonymous> (/var/www/peertube/versions/peertube-v3.4.1/dist/server/models/actor/actor.js:425:71)
          at InstanceValidator._invokeCustomValidator (/var/www/peertube/versions/peertube-v3.4.1/node_modules/sequelize/lib/instance-validator.js:277:30)
          at /var/www/peertube/versions/peertube-v3.4.1/node_modules/sequelize/lib/instance-validator.js:213:30
          at /var/www/peertube/versions/peertube-v3.4.1/node_modules/lodash/lodash.js:4967:15
          at Function.forIn (/var/www/peertube/versions/peertube-v3.4.1/node_modules/lodash/lodash.js:13018:11)
          at InstanceValidator._singleAttrValidate (/var/www/peertube/versions/peertube-v3.4.1/node_modules/sequelize/lib/instance-validator.js:198:7)
          at /var/www/peertube/versions/peertube-v3.4.1/node_modules/sequelize/lib/instance-validator.js:148:30
          at /var/www/peertube/versions/peertube-v3.4.1/node_modules/lodash/lodash.js:4967:15
          at Function.forIn (/var/www/peertube/versions/peertube-v3.4.1/node_modules/lodash/lodash.js:13018:11)
          at InstanceValidator._perAttributeValidators (/var/www/peertube/versions/peertube-v3.4.1/node_modules/sequelize/lib/instance-validator.js:131:7)
          at InstanceValidator._validate (/var/www/peertube/versions/peertube-v3.4.1/node_modules/sequelize/lib/instance-validator.js:73:12)
          at InstanceValidator._validateAndRunHooks (/var/www/peertube/versions/peertube-v3.4.1/node_modules/sequelize/lib/instance-validator.js:111:18)
          at processTicksAndRejections (internal/process/task_queues.js:95:5)
          at async InstanceValidator.validate (/var/www/peertube/versions/peertube-v3.4.1/node_modules/sequelize/lib/instance-validator.js:93:12)
    },
    ValidationErrorItem {
      message: '"https://localhost/video-channels/root_channel/followers" is not a valid followers url.',                                                                       
      type: 'Validation error',
      path: 'followersUrl',
      value: 'https://localhost/video-channels/root_channel/followers',
      origin: 'FUNCTION',
      instance: [ActorModel],
      validatorKey: 'isActorFollowersUrl',
      validatorName: null,
      validatorArgs: [],
      original: Error: "https://localhost/video-channels/root_channel/followers" is not a valid followers url.
          at Object.throwIfNotValid (/var/www/peertube/versions/peertube-v3.4.1/dist/server/models/utils.js:102:15)
          at self.<anonymous> (/var/www/peertube/versions/peertube-v3.4.1/dist/server/models/actor/actor.js:431:69)
          at InstanceValidator._invokeCustomValidator (/var/www/peertube/versions/peertube-v3.4.1/node_modules/sequelize/lib/instance-validator.js:277:30)
          at /var/www/peertube/versions/peertube-v3.4.1/node_modules/sequelize/lib/instance-validator.js:213:30
          at /var/www/peertube/versions/peertube-v3.4.1/node_modules/lodash/lodash.js:4967:15
          at Function.forIn (/var/www/peertube/versions/peertube-v3.4.1/node_modules/lodash/lodash.js:13018:11)
          at InstanceValidator._singleAttrValidate (/var/www/peertube/versions/peertube-v3.4.1/node_modules/sequelize/lib/instance-validator.js:198:7)
          at /var/www/peertube/versions/peertube-v3.4.1/node_modules/sequelize/lib/instance-validator.js:148:30
          at /var/www/peertube/versions/peertube-v3.4.1/node_modules/lodash/lodash.js:4967:15
          at Function.forIn (/var/www/peertube/versions/peertube-v3.4.1/node_modules/lodash/lodash.js:13018:11)
          at InstanceValidator._perAttributeValidators (/var/www/peertube/versions/peertube-v3.4.1/node_modules/sequelize/lib/instance-validator.js:131:7)
          at InstanceValidator._validate (/var/www/peertube/versions/peertube-v3.4.1/node_modules/sequelize/lib/instance-validator.js:73:12)
          at InstanceValidator._validateAndRunHooks (/var/www/peertube/versions/peertube-v3.4.1/node_modules/sequelize/lib/instance-validator.js:111:18)
          at processTicksAndRejections (internal/process/task_queues.js:95:5)
          at async InstanceValidator.validate (/var/www/peertube/versions/peertube-v3.4.1/node_modules/sequelize/lib/instance-validator.js:93:12)
    },
    ValidationErrorItem {
      message: '"https://localhost/video-channels/root_channel/following" is not a valid following url.',                                                                       
      type: 'Validation error',
      path: 'followingUrl',
      value: 'https://localhost/video-channels/root_channel/following',
      origin: 'FUNCTION',
      instance: [ActorModel],
      validatorKey: 'isActorFollowingUrl',
      validatorName: null,
      validatorArgs: [],
      original: Error: "https://localhost/video-channels/root_channel/following" is not a valid following url.
          at Object.throwIfNotValid (/var/www/peertube/versions/peertube-v3.4.1/dist/server/models/utils.js:102:15)
          at self.<anonymous> (/var/www/peertube/versions/peertube-v3.4.1/dist/server/models/actor/actor.js:437:69)
          at InstanceValidator._invokeCustomValidator (/var/www/peertube/versions/peertube-v3.4.1/node_modules/sequelize/lib/instance-validator.js:277:30)
          at /var/www/peertube/versions/peertube-v3.4.1/node_modules/sequelize/lib/instance-validator.js:213:30
          at /var/www/peertube/versions/peertube-v3.4.1/node_modules/lodash/lodash.js:4967:15
          at Function.forIn (/var/www/peertube/versions/peertube-v3.4.1/node_modules/lodash/lodash.js:13018:11)
          at InstanceValidator._singleAttrValidate (/var/www/peertube/versions/peertube-v3.4.1/node_modules/sequelize/lib/instance-validator.js:198:7)
          at /var/www/peertube/versions/peertube-v3.4.1/node_modules/sequelize/lib/instance-validator.js:148:30
          at /var/www/peertube/versions/peertube-v3.4.1/node_modules/lodash/lodash.js:4967:15
          at Function.forIn (/var/www/peertube/versions/peertube-v3.4.1/node_modules/lodash/lodash.js:13018:11)
          at InstanceValidator._perAttributeValidators (/var/www/peertube/versions/peertube-v3.4.1/node_modules/sequelize/lib/instance-validator.js:131:7)
          at InstanceValidator._validate (/var/www/peertube/versions/peertube-v3.4.1/node_modules/sequelize/lib/instance-validator.js:73:12)
          at InstanceValidator._validateAndRunHooks (/var/www/peertube/versions/peertube-v3.4.1/node_modules/sequelize/lib/instance-validator.js:111:18)
          at processTicksAndRejections (internal/process/task_queues.js:95:5)
          at async InstanceValidator.validate (/var/www/peertube/versions/peertube-v3.4.1/node_modules/sequelize/lib/instance-validator.js:93:12)
    }
  ]
}
npm ERR! code ELIFECYCLE
npm ERR! errno 255
npm ERR! peertube@3.4.1 update-host: `node ./dist/scripts/update-host.js`
npm ERR! Exit status 255
npm ERR! 
npm ERR! Failed at the peertube@3.4.1 update-host script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-11-28T17_43_08_945Z-debug.log
```

How do I resolve this? I don't want to break it any more than I have already (I have a very recent backup if needed)

**Comment by SimplyCorbett** [comment]
Crack open your database and see if it's corrupted. My guess is when you disabled the (in use) swap memory you corrupted the postgresql database.

**Comment by SimplyCorbett** [comment]
It's possible there was other damage as well. Disabling in use swap memory on a running system is not going to do anything good.

**Comment by Chocobozzz** [comment]
Hello,

Please use https://docs.joinpeertube.org/maintain-tools?id=update-hostjs

**Comment by SamoLaser** [comment]
I will have to restore the full system from a backup. 

For reference, I have a separate backup of just postgres. I tested to see if this could be fixed by just restoring the db.
Upon running the update-hosts command linked to above, I got this error message:

```
> peertube@3.4.1 update-host /var/www/peertube/versions/peertube-v3.4.1
> node ./dist/scripts/update-host.js

Error: You need to enable pg_trgm extension in PostgreSQL. You can do so by running 'CREATE EXTENSION pg_trgm;' as a PostgreSQL super user in peertube_prod database.
    at /var/www/peertube/versions/peertube-v3.4.1/dist/server/initializers/database.js:179:23
    at Generator.throw (<anonymous>)
    at rejected (/var/www/peertube/versions/peertube-v3.4.1/node_modules/tslib/tslib.js:115:69)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
npm ERR! code ELIFECYCLE
npm ERR! errno 255
npm ERR! peertube@3.4.1 update-host: `node ./dist/scripts/update-host.js`
npm ERR! Exit status 255
npm ERR! 
npm ERR! Failed at the peertube@3.4.1 update-host script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /var/www/peertube/.npm/_logs/2021-11-29T14_04_34_297Z-debug.log
```

The additional logs are:
```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'run', 'update-host' ]
2 info using npm@6.14.15
3 info using node@v14.18.1
4 verbose run-script [ 'preupdate-host', 'update-host', 'postupdate-host' ]
5 info lifecycle peertube@3.4.1~preupdate-host: peertube@3.4.1
6 info lifecycle peertube@3.4.1~update-host: peertube@3.4.1
7 verbose lifecycle peertube@3.4.1~update-host: unsafe-perm in lifecycle true
8 verbose lifecycle peertube@3.4.1~update-host: PATH: /usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/var/www/peertube/versions/peertube->
9 verbose lifecycle peertube@3.4.1~update-host: CWD: /var/www/peertube/versions/peertube-v3.4.1
10 silly lifecycle peertube@3.4.1~update-host: Args: [ '-c', 'node ./dist/scripts/update-host.js' ]
11 silly lifecycle peertube@3.4.1~update-host: Returned: code: 255  signal: null
12 info lifecycle peertube@3.4.1~update-host: Failed to exec update-host script
13 verbose stack Error: peertube@3.4.1 update-host: `node ./dist/scripts/update-host.js`
13 verbose stack Exit status 255
13 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:400:28)
13 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:400:28)
13 verbose stack     at maybeClose (internal/child_process.js:1058:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:293:5)
14 verbose pkgid peertube@3.4.1
15 verbose cwd /var/www/peertube/versions/peertube-v3.4.1
16 verbose Linux 5.4.0-89-generic
17 verbose argv "/usr/bin/node" "/usr/bin/npm" "run" "update-host"
18 verbose node v14.18.1
19 verbose npm  v6.14.15
20 error code ELIFECYCLE
21 error errno 255
22 error peertube@3.4.1 update-host: `node ./dist/scripts/update-host.js`
22 error Exit status 255
23 error Failed at the peertube@3.4.1 update-host script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 255, true ]
```

I'm unable to `CREATE EXTENSION` because my permissions for postgres have been corrupted as well, so it will always say my authentication failed even though I'm the admin.

**Comment by SimplyCorbett** [comment]
I would fully reinstall the system and restore from your backup.

**Comment by SamoLaser** [comment]
@SimplyCorbett 
That's what the plan is. I have no idea of knowing what else I broke through troubleshooting and the backup is only 2 days old anyway.
