### ISSUE TITLE
PeerTube crashes while youtube-dl imports from a certain URL

### ISSUE THREAD

**Issue by wiz** [Chocobozzz/PeerTube#4584]
### Version

ebe9b6b3f32d8432980854a51d28a8fb88fe62e5

### How to Reproduce

Unknown

### Crash log

```
[bitcointv.com:443] 2021-11-30 10:06:42.448 error: uncaughtException: Cannot read properties of undefined (reading 'length')
TypeError: Cannot read properties of undefined (reading 'length')
    at /usr/local/www/peertube/versions/BitcoinTV.com-v3.4.1-develop/node_modules/youtube-dl/lib/youtube-dl.js:298:32
    at done (/usr/local/www/peertube/versions/BitcoinTV.com-v3.4.1-develop/node_modules/youtube-dl/lib/youtube-dl.js:29:12)
    at /usr/local/www/peertube/versions/BitcoinTV.com-v3.4.1-develop/node_modules/universalify/index.js:22:54
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  "error": {
    "stack": "TypeError: Cannot read properties of undefined (reading 'length')\n    at /usr/local/www/peertube/versions/BitcoinTV.com-v3.4.1-develop/node_modules/youtube-dl/lib/youtube-dl.js:298:32\n    at done (/usr/local/www/peertube/versions/BitcoinTV.com-v3.4.1-develop/node_modules/youtube-dl/lib/youtube-dl.js:29:12)\n    at /usr/local/www/peertube/versions/BitcoinTV.com-v3.4.1-develop/node_modules/universalify/index.js:22:54\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)",
    "message": "Cannot read properties of undefined (reading 'length')"
  },
  "stack": "TypeError: Cannot read properties of undefined (reading 'length')\n    at /usr/local/www/peertube/versions/BitcoinTV.com-v3.4.1-develop/node_modules/youtube-dl/lib/youtube-dl.js:298:32\n    at done (/usr/local/www/peertube/versions/BitcoinTV.com-v3.4.1-develop/node_modules/youtube-dl/lib/youtube-dl.js:29:12)\n    at /usr/local/www/peertube/versions/BitcoinTV.com-v3.4.1-develop/node_modules/universalify/index.js:22:54\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)",
  "exception": true,
  "date": "Tue Nov 30 2021 10:06:42 GMT+0000 (Coordinated Universal Time)",
  "process": {
    "pid": 48365,
    "uid": 1338,
    "gid": 1338,
    "cwd": "/usr/local/www/peertube/versions/BitcoinTV.com-v3.4.1-develop",
    "execPath": "/usr/local/bin/node",
    "version": "v16.10.0",
    "argv": [
      "/usr/local/bin/node",
      "/usr/local/www/peertube/versions/BitcoinTV.com-v3.4.1-develop/dist/server"
    ],
    "memoryUsage": {
      "rss": 493953024,
      "heapTotal": 104718336,
      "heapUsed": 94290664,
      "external": 2392644,
      "arrayBuffers": 718097
    }
  },
  "os": {
    "loadavg": [
      0.080078125,
      0.09716796875,
      0.55908203125
    ],
    "uptime": 4087010
  },
  "trace": [
    {
      "column": 32,
      "file": "/usr/local/www/peertube/versions/BitcoinTV.com-v3.4.1-develop/node_modules/youtube-dl/lib/youtube-dl.js",
      "function": null,
      "line": 298,
      "method": null,
      "native": false
    },
    {
      "column": 12,
      "file": "/usr/local/www/peertube/versions/BitcoinTV.com-v3.4.1-develop/node_modules/youtube-dl/lib/youtube-dl.js",
      "function": "done",
      "line": 29,
      "method": null,
      "native": false
    },
    {
      "column": 54,
      "file": "/usr/local/www/peertube/versions/BitcoinTV.com-v3.4.1-develop/node_modules/universalify/index.js",
      "function": null,
      "line": 22,
      "method": null,
      "native": false
    },
    {
      "column": null,
      "file": null,
      "function": "runMicrotasks",
      "line": null,
      "method": null,
      "native": false
    },
    {
      "column": 5,
      "file": "node:internal/process/task_queues",
      "function": "processTicksAndRejections",
      "line": 96,
      "method": null,
      "native": false
    }
  ]
}
[bitcointv.com:443 peertube-plugin-matomo] 2021-11-30 10:06:42.449 error: uncaughtException: Cannot read properties of undefined (reading 'length')
TypeError: Cannot read properties of undefined (reading 'length')
    at /usr/local/www/peertube/versions/BitcoinTV.com-v3.4.1-develop/node_modules/youtube-dl/lib/youtube-dl.js:298:32
    at done (/usr/local/www/peertube/versions/BitcoinTV.com-v3.4.1-develop/node_modules/youtube-dl/lib/youtube-dl.js:29:12)
    at /usr/local/www/peertube/versions/BitcoinTV.com-v3.4.1-develop/node_modules/universalify/index.js:22:54
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  "error": {
    "stack": "TypeError: Cannot read properties of undefined (reading 'length')\n    at /usr/local/www/peertube/versions/BitcoinTV.com-v3.4.1-develop/node_modules/youtube-dl/lib/youtube-dl.js:298:32\n    at done (/usr/local/www/peertube/versions/BitcoinTV.com-v3.4.1-develop/node_modules/youtube-dl/lib/youtube-dl.js:29:12)\n    at /usr/local/www/peertube/versions/BitcoinTV.com-v3.4.1-develop/node_modules/universalify/index.js:22:54\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)",
    "message": "Cannot read properties of undefined (reading 'length')"
  },
  "stack": "TypeError: Cannot read properties of undefined (reading 'length')\n    at /usr/local/www/peertube/versions/BitcoinTV.com-v3.4.1-develop/node_modules/youtube-dl/lib/youtube-dl.js:298:32\n    at done (/usr/local/www/peertube/versions/BitcoinTV.com-v3.4.1-develop/node_modules/youtube-dl/lib/youtube-dl.js:29:12)\n    at /usr/local/www/peertube/versions/BitcoinTV.com-v3.4.1-develop/node_modules/universalify/index.js:22:54\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)",
  "exception": true,
  "date": "Tue Nov 30 2021 10:06:42 GMT+0000 (Coordinated Universal Time)",
  "process": {
    "pid": 48365,
    "uid": 1338,
    "gid": 1338,
    "cwd": "/usr/local/www/peertube/versions/BitcoinTV.com-v3.4.1-develop",
    "execPath": "/usr/local/bin/node",
    "version": "v16.10.0",
    "argv": [
      "/usr/local/bin/node",
      "/usr/local/www/peertube/versions/BitcoinTV.com-v3.4.1-develop/dist/server"
    ],
    "memoryUsage": {
      "rss": 493993984,
      "heapTotal": 104718336,
      "heapUsed": 94371592,
      "external": 2400900,
      "arrayBuffers": 726313
    }
  },
  "os": {
    "loadavg": [
      0.080078125,
      0.09716796875,
      0.55908203125
    ],
    "uptime": 4087010
  },
  "trace": [
    {
      "column": 32,
      "file": "/usr/local/www/peertube/versions/BitcoinTV.com-v3.4.1-develop/node_modules/youtube-dl/lib/youtube-dl.js",
      "function": null,
      "line": 298,
      "method": null,
      "native": false
    },
    {
      "column": 12,
      "file": "/usr/local/www/peertube/versions/BitcoinTV.com-v3.4.1-develop/node_modules/youtube-dl/lib/youtube-dl.js",
      "function": "done",
      "line": 29,
      "method": null,
      "native": false
    },
    {
      "column": 54,
      "file": "/usr/local/www/peertube/versions/BitcoinTV.com-v3.4.1-develop/node_modules/universalify/index.js",
      "function": null,
      "line": 22,
      "method": null,
      "native": false
    },
    {
      "column": null,
      "file": null,
      "function": "runMicrotasks",
      "line": null,
      "method": null,
      "native": false
    },
    {
      "column": 5,
      "file": "node:internal/process/task_queues",
      "function": "processTicksAndRejections",
      "line": 96,
      "method": null,
      "native": false
    }
  ]
}
```

**Comment by SimplyCorbett** [comment]
Replace youtube-dl with yt-dlp. Refer to my comment in https://github.com/Chocobozzz/PeerTube/issues/4568 about how to do this.

**Comment by Chocobozzz** [comment]
Hello,

Please try v4

**Comment by Chocobozzz** [comment]
Closing as we completely changed how youtube-dl works in v4. Don't hesitate to comment if you have issues with the new system once you've updated to v4
