### ISSUE TITLE
Unable to run the tests properly

### ISSUE THREAD

**Issue by dedesite** [Chocobozzz/PeerTube#460]
Hello,

I start working on a bug, but as a good test driven developer, I want to write a test before fixing it.

My problem is that I can't run `npm run test` without errors.

Here are the npm logs : 

```bash
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'run', 'test' ]
2 info using npm@5.6.0
3 info using node@v8.11.1
4 verbose run-script [ 'pretest', 'test', 'posttest' ]
5 info lifecycle peertube@1.0.0-beta.3~pretest: peertube@1.0.0-beta.3
6 info lifecycle peertube@1.0.0-beta.3~test: peertube@1.0.0-beta.3
7 verbose lifecycle peertube@1.0.0-beta.3~test: unsafe-perm in lifecycle true
8 verbose lifecycle peertube@1.0.0-beta.3~test: PATH: /usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/dede/Projects/PeerTubeTest/node_modules/.bin:/home/dede/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/home/dede/.rvm/bin:/home/dede/.rvm/bin:/home/dede/bin/Sencha/Cmd:/home/dede/.config/composer/vendor/bin
9 verbose lifecycle peertube@1.0.0-beta.3~test: CWD: /home/dede/Projects/PeerTubeTest
10 silly lifecycle peertube@1.0.0-beta.3~test: Args: [ '-c', 'scripty' ]
11 silly lifecycle peertube@1.0.0-beta.3~test: Returned: code: 1  signal: null
12 info lifecycle peertube@1.0.0-beta.3~test: Failed to exec test script
13 verbose stack Error: peertube@1.0.0-beta.3 test: `scripty`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:285:16)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at EventEmitter.emit (events.js:214:7)
13 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at ChildProcess.emit (events.js:214:7)
13 verbose stack     at maybeClose (internal/child_process.js:925:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
14 verbose pkgid peertube@1.0.0-beta.3
15 verbose cwd /home/dede/Projects/PeerTubeTest
16 verbose Linux 4.4.0-93-generic
17 verbose argv "/usr/bin/node" "/usr/bin/npm" "run" "test"
18 verbose node v8.11.1
19 verbose npm  v5.6.0
20 error code ELIFECYCLE
21 error errno 1
22 error peertube@1.0.0-beta.3 test: `scripty`
22 error Exit status 1
23 error Failed at the peertube@1.0.0-beta.3 test script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

It hangs on first test : 
```bash
  1) Test a client controllers
       Should have valid Open Graph tags on the watch page with video id:
     Error: expected 200 "OK", got 500 "Internal Server Error"
      at Test._assertStatus (node_modules/supertest/lib/test.js:266:12)
      at Test._assertFunction (node_modules/supertest/lib/test.js:281:11)
      at Test.assert (node_modules/supertest/lib/test.js:171:18)
      at assert (node_modules/supertest/lib/test.js:131:12)
      at /home/dede/Projects/PeerTubeTest/node_modules/supertest/lib/test.js:128:5
      at Test.Request.callback (node_modules/superagent/lib/node/index.js:718:3)
      at IncomingMessage.parser (node_modules/superagent/lib/node/index.js:906:18)
      at endReadableNT (_stream_readable.js:1064:12)
      at _combinedTickCallback (internal/process/next_tick.js:138:11)
      at process._tickCallback (internal/process/next_tick.js:180:9)

```

The application run fine with `npm run dev:client` and I can't see any info on how to run the tests, maybe there is a doc somewhere ?

Note that I had to change `scripts/clean/server/test.sh` and add `sudo -u postgres ` before `dropdb` and `createdb` in order to make it work, am I missing something in the configuration ?

I just ran a `yarn install --pure-lockfile` without problem.

Thank you,
Andréas

**Comment by Chocobozzz** [comment]
Hi @dedesite, thanks for the issue! I tried to improve the contributing guide. Does it help you? https://github.com/Chocobozzz/PeerTube/blob/develop/.github/CONTRIBUTING.md#unit-tests

**Comment by dedesite** [comment]
Thanks @Chocobozzz, I manage to get the tests running with yours instructions !

I must have wrongly create my tests databases.

I had to modify `script/clean/server/tests.sh` to specify `peertube` user on database creation :

`sudo -u postgres createdb -O peertube "peertube_test$i"`

There must be a way to avoid that ?

Thanks for your help.

**Comment by Chocobozzz** [comment]
@dedesite Try to create a PostgreSQL user with the same name as your GNU/Linux username:

```
$ sudo -u postgres createuser you_username --createdb
```

This way, you'll be able to create databases without using the *postgres* user.

**Comment by Chocobozzz** [comment]
Yep, I added this yesterday :) https://github.com/Chocobozzz/PeerTube/commit/a9ab599e53b6cc9a51dc4ac490edffce706393ed
