### ISSUE TITLE
IE11 Shows no Videos

### ISSUE THREAD

**Issue by iamdoubz** [Chocobozzz/PeerTube#464]
* **PeerTube version or URL: BETA 3**
* **Browser name/version: Internet Explorer 11 (Win 7 version was 11.0.9600.18954; Win 10 version was 11.966.15063.0**
* **NodeJS version: 8.10.0**

* **What is the expected behaviour?**
That any video should show up in IE11 as it does in Edge, Chrome, Firefox, and others.
* **What do you see instead?**
Take a look if you have IE11: https://vidz.dou.bet/videos/trending

* **Browser console log if useful (Gist/Pastebin...):**
`ERROR TypeError: Object doesn't support property or method 'values'
   "ERROR"
   {
      [functions]: ,
      __proto__: {
         [functions]: ,
         __proto__: { },
         message: "",
         name: "TypeError"
      },
      description: "Object doesn't support property or method 'values'",
      message: "Object doesn't support property or method 'values'",
      name: "TypeError",
      number: -2146827850,
      stack: "TypeError: Object doesn't support property or method 'values'
   at t.prototype.buildVideoPages (https://vidz.dou.bet/client/main.908ca68382b7d1a0b9a3.bundle.js.pagespeed.ce.ynL0zjY-pj.js:1:707358)
   at t.prototype.calcPageSizes (https://vidz.dou.bet/client/main.908ca68382b7d1a0b9a3.bundle.js.pagespeed.ce.ynL0zjY-pj.js:1:708514)
   at t.prototype.ngOnInit (https://vidz.dou.bet/client/main.908ca68382b7d1a0b9a3.bundle.js.pagespeed.ce.ynL0zjY-pj.js:1:705466)
   at e.prototype.ngOnInit (https://vidz.dou.bet/client/main.908ca68382b7d1a0b9a3.bundle.js.pagespeed.ce.ynL0zjY-pj.js:1:777974)
   at Anonymous function (https://vidz.dou.bet/client/main.908ca68382b7d1a0b9a3.bundle.js.pagespeed.ce.ynL0zjY-pj.js:1:410168)
   at Anonymous function (https://vidz.dou.bet/client/main.908ca68382b7d1a0b9a3.bundle.js.pagespeed.ce.ynL0zjY-pj.js:1:410056)
   at ta (https://vidz.dou.bet/client/main.908ca68382b7d1a0b9a3.bundle.js.pagespeed.ce.ynL0zjY-pj.js:1:408948)
   at Sa (https://vidz.dou.bet/client/main.908ca68382b7d1a0b9a3.bundl"
   }`
* **Server log if useful (Gist/Pastebin...):**
Nothing very useful here...

**Comment by Chocobozzz** [comment]
I'm sorry but we don't want to support Internet Explorer.
