### ISSUE TITLE
Two videos won't move to object storage

### ISSUE THREAD

**Issue by SharkyRawr** [Chocobozzz/PeerTube#4644]
**Describe the current behavior**
Job is created and fails with this error:

```
Job: 55 
Type: move-to-object-storage
Processed on Dec 16, 2021, 3:07:28 PM
Finished on -

{
  "videoUUID": "5466e901-e10d-4f83-a348-2115c3ab379b",
  "isNewVideo": false
}

TypeError: Cannot read property 'replace' of null
    at removeFragmentedMP4Ext (/app/dist/shared/core-utils/common/regexp.js:6:17)
    at getHlsResolutionPlaylistFilename (/app/dist/server/lib/paths.js:31:52)
    at /app/dist/server/lib/job-queue/handlers/move-to-object-storage.js:58:87
    at Generator.next (<anonymous>)
    at /app/node_modules/tslib/tslib.js:117:75
    at new Promise (<anonymous>)
    at __awaiter (/app/node_modules/tslib/tslib.js:113:16)
    at moveHLSFiles (/app/dist/server/lib/job-queue/handlers/move-to-object-storage.js:52:34)
    at Queue.<anonymous> (/app/dist/server/lib/job-queue/handlers/move-to-object-storage.js:29:19)
    at Generator.next (<anonymous>)
    at fulfilled (/app/node_modules/tslib/tslib.js:114:62)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

```
Job: 5
Type: move-to-object-storage
Processed on Dec 16, 2021, 3:07:28 PM
Finished on -

{
  "videoUUID": "21e186eb-ffd5-4371-959a-f9b6feb3197c",
  "isNewVideo": false
}

TypeError: Cannot read property 'replace' of null
    at removeFragmentedMP4Ext (/app/dist/shared/core-utils/common/regexp.js:6:17)
    at getHlsResolutionPlaylistFilename (/app/dist/server/lib/paths.js:31:52)
    at /app/dist/server/lib/job-queue/handlers/move-to-object-storage.js:58:87
    at Generator.next (<anonymous>)
    at /app/node_modules/tslib/tslib.js:117:75
    at new Promise (<anonymous>)
    at __awaiter (/app/node_modules/tslib/tslib.js:113:16)
    at moveHLSFiles (/app/dist/server/lib/job-queue/handlers/move-to-object-storage.js:52:34)
    at Queue.<anonymous> (/app/dist/server/lib/job-queue/handlers/move-to-object-storage.js:29:19)
    at Generator.next (<anonymous>)
    at fulfilled (/app/node_modules/tslib/tslib.js:114:62)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

**Steps to reproduce:**

1. docker-compose exec -u peertube peertube npm run create-move-video-storage-job -- --to-object-storage -a
2. wait for jobs to process
3.

**Describe the expected behavior**

Videos are moved to S3 (minio) object storage.

**Additional information**

* PeerTube instance:
  * URL: https://video.catgirl.biz
  * version: 4.0.0 (docker peertube-bullseye)
  * NodeJS version: _not sure, included in docker image_
  * Ffmpeg version: _not sure, included in docker image_

* Browser name, version and platforms on which you could reproduce the bug: Brave, Chrome, Firefox
* Link to browser console log if relevant:
* Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`):

```
{
   "level":"info",
   "message":"Moving video 21e186eb-ffd5-4371-959a-f9b6feb3197c in job 5.",
   "label":"video.catgirl.biz:443",
   "timestamp":"2021-12-16T14:10:28.646Z"
}
{
   "level":"error",
   "message":"Cannot execute job 5 in queue move-to-object-storage.",
   "label":"video.catgirl.biz:443",
   "payload":{
      "videoUUID":"21e186eb-ffd5-4371-959a-f9b6feb3197c",
      "isNewVideo":false
   },
   "err":{
      "stack":"TypeError: Cannot read property 'replace' of null\n    at removeFragmentedMP4Ext (/app/dist/shared/core-utils/common/regexp.js:6:17)\n    at getHlsResolutionPlaylistFilename (/app/dist/server/lib/paths.js:31:52)\n    at /app/dist/server/lib/job-queue/handlers/move-to-object-storage.js:58:87\n    at Generator.next (<anonymous>)\n    at /app/node_modules/tslib/tslib.js:117:75\n    at new Promise (<anonymous>)\n    at __awaiter (/app/node_modules/tslib/tslib.js:113:16)\n    at moveHLSFiles (/app/dist/server/lib/job-queue/handlers/move-to-object-storage.js:52:34)\n    at Queue.<anonymous> (/app/dist/server/lib/job-queue/handlers/move-to-object-storage.js:29:19)\n    at Generator.next (<anonymous>)\n    at fulfilled (/app/node_modules/tslib/tslib.js:114:62)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (internal/process/task_queues.js:97:5)",
      "message":"Cannot read property 'replace' of null"
   },
   "timestamp":"2021-12-16T14:10:28.659Z"
}
{
   "level":"info",
   "message":"Moving video 5466e901-e10d-4f83-a348-2115c3ab379b in job 55.",
   "label":"video.catgirl.biz:443",
   "timestamp":"2021-12-16T14:10:28.660Z"
}
{
   "level":"error",
   "message":"Cannot execute job 55 in queue move-to-object-storage.",
   "label":"video.catgirl.biz:443",
   "payload":{
      "videoUUID":"5466e901-e10d-4f83-a348-2115c3ab379b",
      "isNewVideo":false
   },
   "err":{
      "stack":"TypeError: Cannot read property 'replace' of null\n    at removeFragmentedMP4Ext (/app/dist/shared/core-utils/common/regexp.js:6:17)\n    at getHlsResolutionPlaylistFilename (/app/dist/server/lib/paths.js:31:52)\n    at /app/dist/server/lib/job-queue/handlers/move-to-object-storage.js:58:87\n    at Generator.next (<anonymous>)\n    at /app/node_modules/tslib/tslib.js:117:75\n    at new Promise (<anonymous>)\n    at __awaiter (/app/node_modules/tslib/tslib.js:113:16)\n    at moveHLSFiles (/app/dist/server/lib/job-queue/handlers/move-to-object-storage.js:52:34)\n    at Queue.<anonymous> (/app/dist/server/lib/job-queue/handlers/move-to-object-storage.js:29:19)\n    at Generator.next (<anonymous>)\n    at fulfilled (/app/node_modules/tslib/tslib.js:114:62)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (internal/process/task_queues.js:97:5)",
      "message":"Cannot read property 'replace' of null"
   },
   "timestamp":"2021-12-16T14:10:28.665Z"
}
```

**Comment by Chocobozzz** [comment]
Hello,

Did you follow https://github.com/Chocobozzz/PeerTube/blob/develop/CHANGELOG.md#important-notes after v4 upgrade?

**Comment by SharkyRawr** [comment]
Yes, I ran the `migrations/peertube-4.0.js` script and updated my config files for the changed log variables.

**Comment by Chocobozzz** [comment]
Could you run it again and paste the output?

**Comment by SharkyRawr** [comment]
It seems that they are live streams:

```
> peertube@4.0.0 create-move-video-storage-job /app
> node ./dist/scripts/create-move-video-storage-job.js "--to-object-storage" "-v" "21e186eb-ffd5-4371-959a-f9b6feb3197c"

Processing video Luna Live.
Error: Cannot use same state 6
    at VideoModel.<anonymous> (/app/dist/server/models/video/video.js:902:23)
    at Generator.next (<anonymous>)
    at /app/node_modules/tslib/tslib.js:117:75
    at new Promise (<anonymous>)
    at __awaiter (/app/node_modules/tslib/tslib.js:113:16)
    at VideoModel.setNewState (/app/dist/server/models/video/video.js:900:38)
    at /app/dist/server/lib/video-state.js:53:21
    at Generator.next (<anonymous>)
    at fulfilled (/app/node_modules/tslib/tslib.js:114:62)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

```
> peertube@4.0.0 create-move-video-storage-job /app
> node ./dist/scripts/create-move-video-storage-job.js "--to-object-storage" "-v" "5466e901-e10d-4f83-a348-2115c3ab379b"

Processing video Live.
Error: Cannot use same state 6
    at VideoModel.<anonymous> (/app/dist/server/models/video/video.js:902:23)
    at Generator.next (<anonymous>)
    at /app/node_modules/tslib/tslib.js:117:75
    at new Promise (<anonymous>)
    at __awaiter (/app/node_modules/tslib/tslib.js:113:16)
    at VideoModel.setNewState (/app/dist/server/models/video/video.js:900:38)
    at /app/dist/server/lib/video-state.js:53:21
    at Generator.next (<anonymous>)
    at fulfilled (/app/node_modules/tslib/tslib.js:114:62)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

This command never returns and just hangs.

**Comment by Chocobozzz** [comment]
I'm sorry I meant run `migrations/peertube-4.0.js` script again :)

**Comment by SharkyRawr** [comment]
It echoed: 
```
Migrate old HLS paths to new format.
Migration finished!
```
But nothing else changed. Still the same error with the live streams. They are just live "channels" and not a recording or anything.

**Comment by Chocobozzz** [comment]
Okay thanks.

I just noticed that `5466e901-e10d-4f83-a348-2115c3ab379b` and `21e186eb-ffd5-4371-959a-f9b6feb3197c` were live videos (not replay but real lives). Lives cannot be moved on object storage. I added a check in https://github.com/Chocobozzz/PeerTube/commit/709565486f86ce9ee553e2e45372ce8226a782fb
