### ISSUE TITLE
Can't mirror video - Premature close & Exceeding download limit

### ISSUE THREAD

**Issue by thorstenkirsch** [Chocobozzz/PeerTube#4645]
**Describe the current behavior**
Hi, I have two instances. I tried to mirror a 1 GB HLS video manually. 
Sometimes, after setting up a new secondary instance, it works, sometimes it does not.

**Steps to reproduce:**

1. Set up two instances
2. Upload a 1080p 1 GB video with HLS enabled
3. Follow each other instance and try to mirror

* PeerTube instance:
  * URL: on request
  * version: 4.0.0
  * NodeJS version: 8.3.0
  * Ffmpeg version: 4.2.4

Dec 16 18:48:28 PAR-339855 peertube[32709]: [myinstance.org:443] 2021-12-16 18:48:28.273 warn: Exceeded the download limit of 44992983.750000015 B
Dec 16 18:48:28 PAR-339855 peertube[32709]: [myinstance.org:443] 2021-12-16 18:48:28.318 error: Cannot execute job 32 in queue video-redundancy. {
Dec 16 18:48:28 PAR-339855 peertube[32709]:   "payload": {
Dec 16 18:48:28 PAR-339855 peertube[32709]:     "videoId": 123
Dec 16 18:48:28 PAR-339855 peertube[32709]:   },
Dec 16 18:48:28 PAR-339855 peertube[32709]:   "err": {
Dec 16 18:48:28 PAR-339855 peertube[32709]:     "stack": "Error [ERR_STREAM_PREMATURE_CLOSE]: Premature close\n    at new NodeError (internal/errors.js:322:7)\n    at Request.onclose (internal/streams/end-of-stream.js:117:38)\n    at Request.emit (events.js:412:35)\n    at Request.emit (domain.js:475:12)\n    at emitCloseNT (internal/streams/destroy.js:87:10)\n    at processTicksAndRejections (internal/process/task_queues.js:81:21)",
Dec 16 18:48:28 PAR-339855 peertube[32709]:     "message": "Premature close",
Dec 16 18:48:28 PAR-339855 peertube[32709]:     "name": "Error"
Dec 16 18:48:28 PAR-339855 peertube[32709]:   }
Dec 16 18:48:28 PAR-339855 peertube[32709]: }

**Comment by thorstenkirsch** [comment]
I sent you the whole excerpt via mail.

**Comment by thorstenkirsch** [comment]
I forgot to mention that I created the 720p resolution manually with the command from the documentation.
