### ISSUE TITLE
Cannot fetch remote information of this URL.

### ISSUE THREAD

**Issue by tio-trom** [Chocobozzz/PeerTube#4682]
I have read past issues opened about this issue but cannot find a solution. This happened after the latest upgrade to peertube 4. 

* PeerTube instance: https://videos.trom.tf
  * URL: https://videos.trom.tf
  * version: 4.0.0
  * NodeJS version:
  * Ffmpeg version:

* Browser name, version and platforms on which you could reproduce the bug: Firefox
```

info[1/2/2022, 4:59:52 PM] Cannot fetch information from import for URL https://www.youtube.com/watch?v=AsPmJdlrBiI.

{
  "err": {
    "stack": "Error: Command failed with exit code 1: python /home/yunohost.app/peertube/storage/bin/yt-dlp --dump-json -f bestvideo[vcodec^=avc1][height=2160]+bestaudio[ext=m4a]/bestvideo[vcodec!*=av01][vcodec!*=vp9.2][height=2160]+bestaudio/bestvideo[vcodec^=avc1][height<=2160]+bestaudio[ext=m4a]/bestvideo[vcodec!*=av01][vcodec!*=vp9.2]+bestaudio/best[vcodec!*=av01][vcodec!*=vp9.2]/best https://www.youtube.com/watch?v=AsPmJdlrBiI\nTraceback (most recent call last):\n  File \"/usr/lib/python2.7/runpy.py\", line 174, in _run_module_as_main\n    \"__main__\", fname, loader, pkg_name)\n  File \"/usr/lib/python2.7/runpy.py\", line 72, in _run_code\n    exec code in run_globals\n  File \"/home/yunohost.app/peertube/storage/bin/yt-dlp/__main__.py\", line 16, in <module>\n  File \"/home/yunohost.app/peertube/storage/bin/yt-dlp/yt_dlp/__init__.py\", line 4\n    f'You are using an unsupported version of Python. Only Python versions 3.6 and above are supported by yt-dlp'  # noqa: F541\n                                                                                                                ^\nSyntaxError: invalid syntax\n    at makeError (/var/www/peertube/node_modules/execa/lib/error.js:60:11)\n    at handlePromise (/var/www/peertube/node_modules/execa/index.js:118:26)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)",
    "message": "Command failed with exit code 1: python /home/yunohost.app/peertube/storage/bin/yt-dlp --dump-json -f bestvideo[vcodec^=avc1][height=2160]+bestaudio[ext=m4a]/bestvideo[vcodec!*=av01][vcodec!*=vp9.2][height=2160]+bestaudio/bestvideo[vcodec^=avc1][height<=2160]+bestaudio[ext=m4a]/bestvideo[vcodec!*=av01][vcodec!*=vp9.2]+bestaudio/best[vcodec!*=av01][vcodec!*=vp9.2]/best https://www.youtube.com/watch?v=AsPmJdlrBiI\nTraceback (most recent call last):\n  File \"/usr/lib/python2.7/runpy.py\", line 174, in _run_module_as_main\n    \"__main__\", fname, loader, pkg_name)\n  File \"/usr/lib/python2.7/runpy.py\", line 72, in _run_code\n    exec code in run_globals\n  File \"/home/yunohost.app/peertube/storage/bin/yt-dlp/__main__.py\", line 16, in <module>\n  File \"/home/yunohost.app/peertube/storage/bin/yt-dlp/yt_dlp/__init__.py\", line 4\n    f'You are using an unsupported version of Python. Only Python versions 3.6 and above are supported by yt-dlp'  # noqa: F541\n                                                                                                                ^\nSyntaxError: invalid syntax",
    "shortMessage": "Command failed with exit code 1: python /home/yunohost.app/peertube/storage/bin/yt-dlp --dump-json -f bestvideo[vcodec^=avc1][height=2160]+bestaudio[ext=m4a]/bestvideo[vcodec!*=av01][vcodec!*=vp9.2][height=2160]+bestaudio/bestvideo[vcodec^=avc1][height<=2160]+bestaudio[ext=m4a]/bestvideo[vcodec!*=av01][vcodec!*=vp9.2]+bestaudio/best[vcodec!*=av01][vcodec!*=vp9.2]/best https://www.youtube.com/watch?v=AsPmJdlrBiI",
    "command": "python /home/yunohost.app/peertube/storage/bin/yt-dlp --dump-json -f bestvideo[vcodec^=avc1][height=2160]+bestaudio[ext=m4a]/bestvideo[vcodec!*=av01][vcodec!*=vp9.2][height=2160]+bestaudio/bestvideo[vcodec^=avc1][height<=2160]+bestaudio[ext=m4a]/bestvideo[vcodec!*=av01][vcodec!*=vp9.2]+bestaudio/best[vcodec!*=av01][vcodec!*=vp9.2]/best https://www.youtube.com/watch?v=AsPmJdlrBiI",
    "escapedCommand": "python \"/home/yunohost.app/peertube/storage/bin/yt-dlp\" --dump-json -f \"bestvideo[vcodec^=avc1][height=2160]+bestaudio[ext=m4a]/bestvideo[vcodec!*=av01][vcodec!*=vp9.2][height=2160]+bestaudio/bestvideo[vcodec^=avc1][height<=2160]+bestaudio[ext=m4a]/bestvideo[vcodec!*=av01][vcodec!*=vp9.2]+bestaudio/best[vcodec!*=av01][vcodec!*=vp9.2]/best\" \"https://www.youtube.com/watch?v=AsPmJdlrBiI\"",
    "exitCode": 1,
    "stdout": "",
    "stderr": "Traceback (most recent call last):\n  File \"/usr/lib/python2.7/runpy.py\", line 174, in _run_module_as_main\n    \"__main__\", fname, loader, pkg_name)\n  File \"/usr/lib/python2.7/runpy.py\", line 72, in _run_code\n    exec code in run_globals\n  File \"/home/yunohost.app/peertube/storage/bin/yt-dlp/__main__.py\", line 16, in <module>\n  File \"/home/yunohost.app/peertube/storage/bin/yt-dlp/yt_dlp/__init__.py\", line 4\n    f'You are using an unsupported version of Python. Only Python versions 3.6 and above are supported by yt-dlp'  # noqa: F541\n                                                                                                                ^\nSyntaxError: invalid syntax",
    "failed": true,
    "timedOut": false,
    "isCanceled": false,
    "killed": false
  }
}
```

I have tried with multiple video sources not only youtube so probably this is not youtube banning our IP. The error is instant so I am sure there are no connection issues.

**Comment by Chocobozzz** [comment]
Hello,

Please check the error message:

```
You are using an unsupported version of Python. Only Python versions 3.6 and above are supported by yt-dlp
```

**Comment by tio-trom** [comment]
Ah ok thank you!

**Comment by h3ndrik** [comment]
The reason is, the default python version on these kind of systems is python2.7 YunoHost is still based on the old stable version of debian. However python 3.7.3 is available.

We could simply invoke `python3` instead. That would work and run the correct python version. But im not sure if this will break on other distributions.

https://github.com/Chocobozzz/PeerTube/blob/37a5d6318b8ce9a3784234751a74b7f15095d5c6/server/helpers/youtube-dl/youtube-dl-cli.ts#L156

Related issue for YunoHost: https://github.com/YunoHost-Apps/peertube_ynh/issues/295

**Comment by fflorent** [comment]
Shouldn't the path to the python binary be in the config file? It would be more convenient for Debian oldstable (whose python binary still points to python2)

**Comment by Chocobozzz** [comment]
Yes we can do that but AFAIK youtube-dl is also compatible with python2

**Comment by AkselRocks** [comment]
To avoid misunderstandings: 
"youtube-dl is a command-line program to download videos from YouTube.com and a few more sites. It requires the Python interpreter, version 2.6, 2.7, or 3.2+, and it is not platform specific." [https://github.com/ytdl-org/youtube-dl](url)

**Comment by fflorent** [comment]
> To avoid misunderstandings: "youtube-dl is a command-line program to download videos from YouTube.com and a few more sites. It requires the Python interpreter, version 2.6, 2.7, or 3.2+, and it is not platform specific." [https://github.com/ytdl-org/youtube-dl](url)

Sure. But the issue here occurs with yt-dlp, not youtube-dl :)
