### ISSUE TITLE
activity pub forbidden

### ISSUE THREAD

**Issue by 01123581321345589144233** [Chocobozzz/PeerTube#4684]
Afte i have installed a new server clean on ubuntu
the main server is tv1 and the backup is tv2
i try to send a follow from tv2 to tv1

error[2.1.2022, 20:03:19] Cannot execute job 16 in queue activitypub-http-unicast.

{
  "payload": {
    "uri": "https://tv1.gomntu.space/accounts/peertube/inbox",
    "signatureActorId": 1,
    "body": {
      "type": "Follow",
      "id": "https://tv2.gomntu.space/accounts/peertube/follows/4",
      "actor": "https://tv2.gomntu.space/accounts/peertube",
      "object": "https://tv1.gomntu.space/accounts/peertube"
    }
  },
  "err": {
    "stack": "HTTPError: Response code 403 (Forbidden)\n    at Request.<anonymous> (/var/www/peertube/versions/peertube-v4.0.0/node_modules/got/dist/source/as-promise/index.js:117:42)\n    at processTicksAndRejections (internal/process/task_queues.js:97:5)",
    "message": "Response code 403 (Forbidden)",
    "name": "HTTPError",
    "responseBody": "{\"type\":\"about:blank\",\"title\":\"Forbidden\",\"detail\":\"Invalid signature\",\"status\":403,\"actorUrl\":\"https://tv2.gomntu.space/accounts/peertube\",\"error\":\"Invalid signature\"}",
    "responseHeaders": {
      "server": "nginx/1.14.0 (Ubuntu)",
      "date": "Sun, 02 Jan 2022 19:03:19 GMT",
      "content-type": "application/problem+json; charset=utf-8",
      "content-length": "168",
      "connection": "close",
      "x-frame-options": "DENY",
      "tk": "N",
      "etag": "W/\"a8-AZGRyk65ykqsyK2vzapQ/olIDEE\""
    },
    "statusCode": 403
  }
}

**Describe the expected behavior**

**Additional information**

* PeerTube instance:
  * URL: tv2.gomntu.space
  * version:4
  * NodeJS version:12
  * Ffmpeg version:4.3

**Comment by 01123581321345589144233** [comment]
on the tv1 i have this:

warn[2.1.2022, 20:03:19] Signature from https://tv2.gomntu.space/accounts/peertube is invalid

{
  "parsed": {
    "scheme": "Signature",
    "params": {
      "keyId": "https://tv2.gomntu.space/accounts/peertube",
      "algorithm": "rsa-sha256",
      "headers": [
        "(request-target)",
        "host",
        "date",
        "digest"
      ],
      "signature": "DNoC2oFDj0Xt9W9ryM+08SnoUM80szZKRuOXi/GTzQSjlJWIFclHkeWJsPab8vUcpCuMnmyvgamiz4I/zcgJNB6byAb6yahIiCcOWc4v6RQgzWVKbaUKO84XdjWglb2OXfJB4E8R3btSoPVpuQbFO7TlxEaUnGrl5Mx+k0WmsicDvkdzvU+jZyc8FUpThpXd/zj3zAqUM3Ios205RfKNEteAEm0mpIGtj7cVsXXFTyZJ8nz/C3hpTua5uh8wYnYXehFhmc4xk2UpTg+On/kvFsggzo0p54lJ1kSxTwEzbXzLyY58prbNLAZ0T1W19WU78eXEifxH01X05eJm8iINgQ=="
    },
    "signingString": "(request-target): post /accounts/peertube/inbox\nhost: tv1.gomntu.space\ndate: Sun, 02 Jan 2022 19:03:19 GMT\ndigest: SHA-256=YViGkr4/8k9rMVDVcXMtKc9WTd0K+k7dIQwMorw9rGE=",
    "algorithm": "RSA-SHA256",
    "keyId": "https://tv2.gomntu.space/accounts/peertube"
  }
}

**Comment by Chocobozzz** [comment]
Could you run `date` command on `tv1` and `tv2`?

**Comment by 01123581321345589144233** [comment]
do you think the linux date command? yes i can

**Comment by 01123581321345589144233** [comment]
i have send a follow from tv1 to tv2 it works

**Comment by Chocobozzz** [comment]
> yes i can

Please paste the output of this command

> i have send a follow from tv1 to tv2 it works

And you still have a 403 when tv2 follows tv1?

**Comment by 01123581321345589144233** [comment]
root@tv2:~# date
Do 6. Jan 14:08:46 CET 2022
root@tv2:~#

**Comment by 01123581321345589144233** [comment]
its working again
