### ISSUE TITLE
Video views count did not work/show in v4.0.0 after ugrade from v3.4.1 in cs-CZ language

### ISSUE THREAD

**Issue by Lachim06** [Chocobozzz/PeerTube#4705]
**Describe the current behavior**
When I checked the video views count under the video title in English language of site - all is ok - I could see the view count e.g. "1 month ago • 49 views"
but when I changed the language if site to the Czech language (Čeština) - can see only: "1 month ago • " - video views count is missing
Looks like video view count did not change after watching whole video in cs-CZ language

**Steps to reproduce:**
1. Change in the web browser language of peertube instance to the Czech language (Čeština) - cs-CZ 
e.g. from "Interface: English" to "Interface: Čeština"
2. Check the video count
3. Watch the video in Czech language of insance
4. Check if count changed in EN language

**Describe the expected behavior**
Could see the video views count in cs-CZ language
Video view count will change after watching in cs-CZ language of web site

**Additional information**
Issue appear after upgrade to v4.0.0 from v3.4.1
+ new errors in log which did not in v3.4.1:
#########################################
warn[1/8/2022, 10:49:38 PM] Warning in tracker.
{
  "err": {
    "stack": "Error: no peer with that `to_peer_id`\n    at /var/www/peertube/versions/peertube-v4.0.0/node_modules/bittorrent-tracker/server.js:554:41\n    at /var/www/peertube/versions/peertube-v4.0.0/node_modules/bittorrent-tracker/server.js:364:7\n    at processTicksAndRejections (internal/process/task_queues.js:77:11)",
    "message": "no peer with that `to_peer_id`"
  }
}
#########################################

* PeerTube instance:
  * URL: https://suptube.cz/
  * version: I had to downgrade back to v3.4.1 :(
  * NodeJS version: v14.18.1
  * Ffmpeg version: version 4.3.3-0+deb11u1

* Browser name, version and platforms on which you could reproduce the bug: osx (safari), win (chrome, firefox), ios (safari) 
* Link to browser console log if relevant:
* Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`):

**Comment by Lachim06** [comment]
Not sure if it is relevant, but after after upgrade to v4.0.0 from v3.4.1 I could see in the log:
This peertube instance was recently installed in version v3.4.1 - no domain name was changed. 

###########################
warn[1/8/2022, 9:13:13 PM] It seems PeerTube was started (and created some data) with another domain name. This means you will not be able to federate! Please use NODE_CONFIG_DIR=/var/www/peertube/config NODE_ENV=production npm run update-host to fix this.

warn[1/8/2022, 9:40:40 PM] It seems PeerTube was started (and created some data) with another domain name. This means you will not be able to federate! Please use NODE_CONFIG_DIR=/var/www/peertube/config NODE_ENV=production npm run update-host to fix this.

warn[1/8/2022, 9:44:09 PM] Login error

{
  "err": {
    "statusCode": 400,
    "status": 400,
    "code": 400,
    "message": "Invalid grant: user credentials are invalid",
    "name": "invalid_grant",
    "stack": "invalid_grant: Invalid grant: user credentials are invalid\n    at new InvalidGrantError (/var/www/peertube/versions/peertube-v4.0.0/node_modules/oauth2-server/lib/errors/invalid-grant-error.js:27:14)\n    at /var/www/peertube/versions/peertube-v4.0.0/dist/server/lib/auth/oauth.js:76:19\n    at Generator.next (<anonymous>)\n    at fulfilled (/var/www/peertube/versions/peertube-v4.0.0/node_modules/tslib/tslib.js:114:62)"
  }
}
###########################

**Comment by Chocobozzz** [comment]
Hello,

I'm sorry but I can't reproduce. Is your IP correctly displayed in https://suptube.cz//admin/system/debug?

**Comment by Lachim06** [comment]
hello @Chocobozzz 
yes, my web browser public IP of is correct.
But as I have mentioned - I had to downgrade back to v3.4.1, because the peertube instance is using Czech cs-CZ language.
The issue appear only on v4.0.0 - you can reproduced issue on any public v4.0.0 peertube instance.
I could not keep my peertube instance on v4.0.0 because of bug.

**Comment by Chocobozzz** [comment]
It seems to be already fixed on latest develop (available on https://peertube2.cpy.re/videos/local) so I think I can close this issue.

**Comment by Lachim06** [comment]
Does it mean I have to wait for a next release?

**Comment by Chocobozzz** [comment]
Yes or you can use a nightly build: https://builds.joinpeertube.org/nightly/
