### ISSUE TITLE
Impossible to upload file with Nginx proxy manager

### ISSUE THREAD

**Issue by JamesDAdams** [Chocobozzz/PeerTube#4800]
**Describe the current behavior**
Impossible to upload a video withe Nginx proxy manager like a reverse proxy
**Steps to reproduce:**

1. Use Peertube with Nginx proxy manager
2. Try to upload file
3. When the file are upload at 100% i have this error : 

![image](https://user-images.githubusercontent.com/20860324/154677554-f16b93b1-1891-41b8-8348-d4f82276c6e7.png)

**Describe the expected behavior**

**Additional information**

* PeerTube instance:
  * URL: https://peertube.jamesserver.ovh/
  * version: Docker johnxlivingston/peertubelivechat:production-buster
  * NodeJS version: Docker
  * Ffmpeg version: Docker

* Browser name, version and platforms on which you could reproduce the bug: Chrome
* Link to browser console log if relevant: 
![image](https://user-images.githubusercontent.com/20860324/154677837-0b0e8762-9f89-4a4e-bfce-f0313dbe4726.png)

* Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`):

```
[peertube.jamesserver.ovh:443] 2022-02-18 12:47:23.940 [31merror[39m: Error in controller. {

"err": "SequelizeDatabaseError: null value in column \"storage\" of relation \"videoFile\" violates not-null constraint\n at Query.formatError (/app/node_modules/sequelize/lib/dialects/postgres/query.js:386:16)\n at Query.run (/app/node_modules/sequelize/lib/dialects/postgres/query.js:87:18)\n at runMicrotasks (<anonymous>)\n at processTicksAndRejections (internal/process/task_queues.js:97:5)"
} - INSERT INTO "videoFile" ("id","resolution","size","extname","fps","metadata","filename","videoId","videoStreamingPlaylistId","createdAt","updatedAt") VALUES (DEFAULT,$1,$2,$3,$4,$5,$6,$7,$8,$9,$10) RETURNING "id","resolution","size","extname","infoHash","fps","metadata","metadataUrl","fileUrl","filename","torrentUrl","torrentFilename","videoId","videoStreamingPlaylistId","createdAt","updatedAt";
[peertube.jamesserver.ovh:443] 2022-02-18 12:47:23.942 [32minfo[39m: 141.101.68.30 - - [18/Feb/2022:11:47:23 +0000] "PUT /api/v1/videos/upload-resumable?upload_id=51b4cbce293c1b880624b71f75f93bf4 HTTP/1.1" 500 - "https://peertube.jamesserver.ovh/videos/upload" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.110 Safari/537.36"
```

**Comment by JamesDAdams** [comment]
up

**Comment by Chocobozzz** [comment]
Hello,

It should be fixed by https://github.com/Chocobozzz/PeerTube/commit/5301e7762b340367323cbb76d68953c35b909634

**Comment by lukaprincic** [comment]
I'm getting something similar on a fresh install of 4.1.0 (non docker):

in `journalctl -feu peertube` I can see:
```
Mar 05 14:16:29 pina peertube[729]: [vid.pretok.tv:443] 2022-03-05 14:16:29.514 info: 89.212.0.0 - - [05/Mar/2022:14:16:29 +0000] "POST /api/v1/videos/upload-resumable HTTP/1.0" 201 - "https://vid.pretok.tv/videos/upload" "Firefox"
Mar 05 14:16:29 pina peertube[729]: [vid.pretok.tv:443] 2022-03-05 14:16:29.812 info: 89.212.0.0 - - [05/Mar/2022:14:16:29 +0000] "PUT /api/v1/videos/upload-resumable?upload_id=310ca263-dae71238-80b58a95-9a09b306 HTTP/1.0" 308 - "https://vid.pretok.tv/videos/upload" "Firefox"
Mar 05 14:16:35 pina peertube[729]: [vid.pretok.tv:443] 2022-03-05 14:16:35.049 error: Error in controller. {
Mar 05 14:16:35 pina peertube[729]:   "err": "Error\n    at Query.run (/var/www/peertube/versions/peertube-v4.1.0/node_modules/sequelize/dist/lib/dialects/postgres/query.js:50:25)\n    at /var/www/peertube/versions/peertube-v4.1.0/node_modules/sequelize/dist/lib/sequelize.js:313:28\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async PostgresQueryInterface.insert (/var/www/peertube/versions/peertube-v4.1.0/node_modules/sequelize/dist/lib/dialects/abstract/query-interface.js:297:21)\n    at async VideoModel.save (/var/www/peertube/versions/peertube-v4.1.0/node_modules/sequelize/dist/lib/model.js:2417:35)"
Mar 05 14:16:35 pina peertube[729]: } - INSERT INTO "video" ("id","uuid","name","category","licence","language","privacy","nsfw","description","support","duration","views","likes","dislikes","remote","isLive","url","commentsEnabled","downloadEnabled","waitTranscoding","state","publishedAt","originallyPublishedAt","channelId","createdAt","updatedAt") VALUES (DEFAULT,$1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17,$18,$19,$20,$21,$22,$23,$24,$25) RETURNING "id","uuid","name","category","licence","language","privacy","nsfw","description","support","duration","views","likes","dislikes","remote","isLive","url","commentsEnabled","downloadEnabled","waitTranscoding","state","publishedAt","originallyPublishedAt","channelId","createdAt","updatedAt";
Mar 05 14:16:35 pina peertube[729]: [vid.pretok.tv:443] 2022-03-05 14:16:35.053 info: 89.212.0.0 - - [05/Mar/2022:14:16:35 +0000] "PUT /api/v1/videos/upload-resumable?upload_id=310ca263-dae71238-80b58a95-9a09b306 HTTP/1.0" 500 355 "https://vid.pretok.tv/videos/upload" "Firefox"
```

and in logs in the peertube interface:
```
error[3/5/2022, 3:16:35 PM] Error in controller.

{
  "err": "Error\n    at Query.run (/var/www/peertube/versions/peertube-v4.1.0/node_modules/sequelize/dist/lib/dialects/postgres/query.js:50:25)\n    at /var/www/peertube/versions/peertube-v4.1.0/node_modules/sequelize/dist/lib/sequelize.js:313:28\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async PostgresQueryInterface.insert (/var/www/peertube/versions/peertube-v4.1.0/node_modules/sequelize/dist/lib/dialects/abstract/query-interface.js:297:21)\n    at async VideoModel.save (/var/www/peertube/versions/peertube-v4.1.0/node_modules/sequelize/dist/lib/model.js:2417:35)",
  "sql": "INSERT INTO \"video\" (\"id\",\"uuid\",\"name\",\"category\",\"licence\",\"language\",\"privacy\",\"nsfw\",\"description\",\"support\",\"duration\",\"views\",\"likes\",\"dislikes\",\"remote\",\"isLive\",\"url\",\"commentsEnabled\",\"downloadEnabled\",\"waitTranscoding\",\"state\",\"publishedAt\",\"originallyPublishedAt\",\"channelId\",\"createdAt\",\"updatedAt\") VALUES (DEFAULT,$1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17,$18,$19,$20,$21,$22,$23,$24,$25) RETURNING \"id\",\"uuid\",\"name\",\"category\",\"licence\",\"language\",\"privacy\",\"nsfw\",\"description\",\"support\",\"duration\",\"views\",\"likes\",\"dislikes\",\"remote\",\"isLive\",\"url\",\"commentsEnabled\",\"downloadEnabled\",\"waitTranscoding\",\"state\",\"publishedAt\",\"originallyPublishedAt\",\"channelId\",\"createdAt\",\"updatedAt\";"
}
```

is this related or another error? sory to post in the closed bug.
