### ISSUE TITLE
Plugin index unavailable. Please retry later (fresh v4.0.0)

### ISSUE THREAD

**Issue by PabloCastellano** [Chocobozzz/PeerTube#4801]
**Describe the current behavior**

v4.0.0 in a fresh install doesn't show list of plugins/themes

**Steps to reproduce:**

1. Install a fresh new v4.0.0 instance
2. Go to `/admin/plugins/search?pluginType=1` (plugins) or `/admin/plugins/search?pluginType=2` (themes)
3. An error message is shown 

```
$ http "https://creemoseducacioninclusiva.uma.es/api/v1/plugins/available?start=0&count=10&sort=-popularity&pluginType=1" "Authorization: Bearer [REDACTED]"
HTTP/1.1 503 Service Unavailable
Access-Control-Allow-Credentials: true
Access-Control-Allow-Origin: *
Access-Control-Expose-Headers: Retry-After
Content-Length: 269
Content-Type: application/problem+json; charset=utf-8
Date: Fri, 18 Feb 2022 12:49:22 GMT
ETag: W/"10d-2HzURH0SXb4TEBRa2acazdqgjd8"
Server: nginx/1.18.0 (Ubuntu)
Tk: N
X-Frame-Options: DENY
X-RateLimit-Limit: 50
X-RateLimit-Remaining: 49
X-RateLimit-Reset: 1645188569

{
    "detail": "Plugin index unavailable. Please retry later",
    "docs": "https://docs.joinpeertube.org/api-rest-reference.html#operation/getAvailablePlugins",
    "error": "Plugin index unavailable. Please retry later",
    "status": 503,
    "title": "Service Unavailable",
    "type": "about:blank"
}
```

**Describe the expected behavior**

![image](https://user-images.githubusercontent.com/73274/154685487-65f38c87-cc62-4f37-ae0e-23182c19255e.png)

**Additional information**

Not sure if related, but all outgoing requests have to go through a http proxy in this scenario. `HTTP_PROXY` and `HTTPS_PROXY` environment variables are defined.

* PeerTube instance:
  * URL: https://creemoseducacioninclusiva.uma.es/
  * version: 4.0.0
  * NodeJS version: v14.0.0
  * Ffmpeg version:  4.2.4-1ubuntu0.1

* Browser name, version and platforms on which you could reproduce the bug:
* Link to browser console log if relevant:
* Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`):

```json
{
  "level": "error",
  "message": "Cannot list available plugins from index https://packages.joinpeertube.org/api/v1/plugins.",
  "label": "creemoseducacioninclusiva.uma.es:443",
  "err": {
    "stack": "TypeError: result.data is not iterable\n    at addInstanceInformation (/var/www/peertube/versions/peertube-v4.0.0/dist/server/lib/plugins/plugin-index.js:38:28)\n    at /var/www/peertube/versions/peertube-v4.0.0/dist/server/lib/plugins/plugin-index.js:27:13\n    at Generator.next (<anonymous>)\n    at fulfilled (/var/www/peertube/versions/peertube-v4.0.0/node_modules/tslib/tslib.js:114:62)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (internal/process/task_queues.js:97:5)",
    "message": "result.data is not iterable"
  },
  "timestamp": "2022-02-18T12:52:49.565Z"
}
```

**Comment by Chocobozzz** [comment]
Hello,

Could you check your proxy logs to see if it does correctly the request to the plugin index?

**Comment by PabloCastellano** [comment]
@Chocobozzz I don't have access to the proxy server. Is there any other way I can provide debug information?

**Comment by Chocobozzz** [comment]
You can enable debug logs in peertube configuration that should display the request result

**Comment by PabloCastellano** [comment]
@Chocobozzz Thanks for the advice! I've done that and this is what I got:

```
debug[3/2/2022, 4:06:10 PM] Got result from PeerTube index.

{
  "body": ""
}
```

I've also added some extra debug traces to check the value of `result` in `addInstanceInformation()`. In my case, `result` is empty and `result.data` is `undefined`.

I can fetch `https://packages.joinpeertube.org/api/v1/plugins` using curl and the http proxy without problems though

**Comment by Chocobozzz** [comment]
What happens when you explicitly don't set `HTTPS_PROXY` for PeerTube and try the request?

You can also try to log the entire request:

```
 const result = await doJSONRequest<any>(uri, { searchParams })
 logger.info('my log', { result })
```

**Comment by PabloCastellano** [comment]
> What happens when you explicitly don't set HTTPS_PROXY for PeerTube and try the request?

@Chocobozzz nothing changed

**Comment by Chocobozzz** [comment]
Do you see in PeerTube info logs `Using proxy ...`?

**Comment by PabloCastellano** [comment]
> Do you see in PeerTube info logs `Using proxy ...`?

@Chocobozzz I don't, and I'm a beginner with typescript but I did some debugging and I don't understand why I can't see it

I have added some extra logging:

```
function getAgent() {
    logger_1.logger.info('getAgent');
    if (!(0, proxy_1.isProxyEnabled)())
        logger_1.logger.info('NOT using proxy.');
        return {};
    logger_1.logger.info('getAgent2');
    const proxy = (0, proxy_1.getProxy)();
    logger_1.logger.info('Using proxy %s.', proxy, lTags());
    const proxyAgentOptions = {
        keepAlive: true,
        keepAliveMsecs: 1000,
        maxSockets: 256,
        maxFreeSockets: 256,
        scheduling: 'lifo',
        proxy
    };
    return {
        agent: {
            http: new hpagent_1.HttpProxyAgent(proxyAgentOptions),
            https: new hpagent_1.HttpsProxyAgent(proxyAgentOptions)
        }
    };
}
```

After that I restart peertube and get the following logs:

without HTTP_PROXY env var:

```
mar 15 22:23:19 creemoseducacioninclusiva.uma.es systemd[1]: Started PeerTube daemon.                                                                                                                                                         
mar 15 22:23:23 creemoseducacioninclusiva.uma.es peertube[250873]: [creemoseducacioninclusiva.uma.es:443] 2022-03-15 22:23:23.056 info: getAgent                                           
mar 15 22:23:23 creemoseducacioninclusiva.uma.es peertube[250873]: [creemoseducacioninclusiva.uma.es:443] 2022-03-15 22:23:23.061 info: NOT using proxy.                                     
```

However with HTTP_PROXY defined, I get the following full log. Note that it does not print "Using proxy" which I find pretty weird, but I'm not an experienced typescript developer. How is that possible?

```
mar 15 22:13:59 creemoseducacioninclusiva.uma.es systemd[1]: Started PeerTube daemon.                                                                                                                                                         
mar 15 22:14:03 creemoseducacioninclusiva.uma.es peertube[250701]: [creemoseducacioninclusiva.uma.es:443] 2022-03-15 22:14:03.024 info: getAgent
mar 15 22:14:05 creemoseducacioninclusiva.uma.es peertube[250701]: [creemoseducacioninclusiva.uma.es:443] 2022-03-15 22:14:05.692 info: Database peertube_prod is ready.
mar 15 22:14:06 creemoseducacioninclusiva.uma.es peertube[250701]: [creemoseducacioninclusiva.uma.es:443] 2022-03-15 22:14:06.015 info: Using ssl0.ovh.net:465 as SMTP server.                                                                
mar 15 22:14:06 creemoseducacioninclusiva.uma.es peertube[250701]: [creemoseducacioninclusiva.uma.es:443] 2022-03-15 22:14:06.019 info: Testing SMTP server...                                                                                
mar 15 22:14:06 creemoseducacioninclusiva.uma.es peertube[250701]: [creemoseducacioninclusiva.uma.es:443] 2022-03-15 22:14:06.121 error: getaddrinfo EAI_AGAIN ssl0.ovh.net {
mar 15 22:14:06 creemoseducacioninclusiva.uma.es peertube[250701]:   "component": "smtp-connection",
mar 15 22:14:06 creemoseducacioninclusiva.uma.es peertube[250701]:   "sid": "j2cSfeZGErA"
mar 15 22:14:06 creemoseducacioninclusiva.uma.es peertube[250701]: }
mar 15 22:14:06 creemoseducacioninclusiva.uma.es peertube[250701]: [creemoseducacioninclusiva.uma.es:443] 2022-03-15 22:14:06.123 error: Failed to connect to SMTP ssl0.ovh.net:465. {
mar 15 22:14:06 creemoseducacioninclusiva.uma.es peertube[250701]:   "err": {
mar 15 22:14:06 creemoseducacioninclusiva.uma.es peertube[250701]:     "stack": "Error: getaddrinfo EAI_AGAIN ssl0.ovh.net\n    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:66:26)",
mar 15 22:14:06 creemoseducacioninclusiva.uma.es peertube[250701]:     "message": "getaddrinfo EAI_AGAIN ssl0.ovh.net",                                                 
mar 15 22:14:06 creemoseducacioninclusiva.uma.es peertube[250701]:     "errno": -3001,                                                                                                                                                        
mar 15 22:14:06 creemoseducacioninclusiva.uma.es peertube[250701]:     "code": "EDNS",                                                                                                                                                        
mar 15 22:14:06 creemoseducacioninclusiva.uma.es peertube[250701]:     "syscall": "getaddrinfo",                                                                                                                                              
mar 15 22:14:06 creemoseducacioninclusiva.uma.es peertube[250701]:     "hostname": "ssl0.ovh.net",  
mar 15 22:14:06 creemoseducacioninclusiva.uma.es peertube[250701]:     "command": "CONN" 
mar 15 22:14:06 creemoseducacioninclusiva.uma.es peertube[250701]:   }
mar 15 22:14:06 creemoseducacioninclusiva.uma.es peertube[250701]: }                                                                                                                                                                          
mar 15 22:14:06 creemoseducacioninclusiva.uma.es peertube[250701]: [creemoseducacioninclusiva.uma.es:443] 2022-03-15 22:14:06.133 info: Running RTMP server on port 1935
mar 15 22:14:06 creemoseducacioninclusiva.uma.es peertube[250701]: [creemoseducacioninclusiva.uma.es:443] 2022-03-15 22:14:06.154 info: Cleaning HTML cache.                                   
mar 15 22:14:06 creemoseducacioninclusiva.uma.es peertube[250701]: [creemoseducacioninclusiva.uma.es:443] 2022-03-15 22:14:06.210 info: Registering plugin or theme peertube-theme-background-red.
mar 15 22:14:06 creemoseducacioninclusiva.uma.es peertube[250701]: [creemoseducacioninclusiva.uma.es:443] 2022-03-15 22:14:06.245 info: Registering plugin or theme peertube-theme-dark.
mar 15 22:14:06 creemoseducacioninclusiva.uma.es peertube[250701]: [creemoseducacioninclusiva.uma.es:443] 2022-03-15 22:14:06.255 info: Registering plugin or theme peertube-theme-framasoft.
mar 15 22:14:06 creemoseducacioninclusiva.uma.es peertube[250701]: [creemoseducacioninclusiva.uma.es:443] 2022-03-15 22:14:06.257 info: Registering plugin or theme peertube-plugin-matomo.
mar 15 22:14:06 creemoseducacioninclusiva.uma.es peertube[250701]: [creemoseducacioninclusiva.uma.es:443] 2022-03-15 22:14:06.268 info: Add plugin peertube-plugin-matomo CSS to global file.
mar 15 22:14:06 creemoseducacioninclusiva.uma.es peertube[250701]: [creemoseducacioninclusiva.uma.es:443] 2022-03-15 22:14:06.269 info: Cleaning HTML cache.
mar 15 22:14:06 creemoseducacioninclusiva.uma.es peertube[250701]: [creemoseducacioninclusiva.uma.es:443] 2022-03-15 22:14:06.269 info: HTTP server listening on localhost:9000
mar 15 22:14:06 creemoseducacioninclusiva.uma.es peertube[250701]: [creemoseducacioninclusiva.uma.es:443] 2022-03-15 22:14:06.270 info: Web server: https://creemoseducacioninclusiva.uma.es
```

**Comment by Chocobozzz** [comment]
You function is incorrect, try

```js
function getAgent() {
    logger_1.logger.info('getAgent');
    if (!(0, proxy_1.isProxyEnabled)()) { // was missing
        logger_1.logger.info('NOT using proxy.');
        return {};
    } // was missing
    logger_1.logger.info('getAgent2');
    const proxy = (0, proxy_1.getProxy)();
    logger_1.logger.info('Using proxy %s.', proxy, lTags());
    const proxyAgentOptions = {
        keepAlive: true,
        keepAliveMsecs: 1000,
        maxSockets: 256,
        maxFreeSockets: 256,
        scheduling: 'lifo',
        proxy
    };
    return {
        agent: {
            http: new hpagent_1.HttpProxyAgent(proxyAgentOptions),
            https: new hpagent_1.HttpsProxyAgent(proxyAgentOptions)
        }
    };
}

```

**Comment by PabloCastellano** [comment]
@Chocobozzz Oops, what an embarrassing mistake :sweat_smile: 

Coming back to your question, yes I can see "Using proxy" in my logs.

```
mar 16 10:27:23 creemoseducacioninclusiva.uma.es peertube[254643]: [creemoseducacioninclusiva.uma.es:443] 2022-03-16 10:27:23.121 info: getAgent                                           
mar 16 10:27:23 creemoseducacioninclusiva.uma.es peertube[254643]: [creemoseducacioninclusiva.uma.es:443] 2022-03-16 10:27:23.126 info: getAgent2                                            
mar 16 10:27:23 creemoseducacioninclusiva.uma.es peertube[254643]: [creemoseducacioninclusiva.uma.es:443] 2022-03-16 10:27:23.126 info: Using proxy http://jano8.sci.uma.es:3128.
```

**Comment by Chocobozzz** [comment]
And could you log the entire request as said in https://github.com/Chocobozzz/PeerTube/issues/4801#issuecomment-1057756457? Maybe headers can help

**Comment by PabloCastellano** [comment]
I've added some more log lines and I'm getting this:

Here you can see the headers
```
mar 16 15:15:10 creemoseducacioninclusiva.uma.es peertube[256238]: [creemoseducacioninclusiva.uma.es:443] 2022-03-16 15:15:10.380 info: doJSONRequests options {
mar 16 15:15:10 creemoseducacioninclusiva.uma.es peertube[256238]:   "gotOptions": {
mar 16 15:15:10 creemoseducacioninclusiva.uma.es peertube[256238]:     "dnsCache": true,
mar 16 15:15:10 creemoseducacioninclusiva.uma.es peertube[256238]:     "timeout": 7000,
mar 16 15:15:10 creemoseducacioninclusiva.uma.es peertube[256238]:     "searchParams": {
mar 16 15:15:10 creemoseducacioninclusiva.uma.es peertube[256238]:       "start": 0,
mar 16 15:15:10 creemoseducacioninclusiva.uma.es peertube[256238]:       "count": 10,
mar 16 15:15:10 creemoseducacioninclusiva.uma.es peertube[256238]:       "sort": "-popularity",
mar 16 15:15:10 creemoseducacioninclusiva.uma.es peertube[256238]:       "pluginType": 1,
mar 16 15:15:10 creemoseducacioninclusiva.uma.es peertube[256238]:       "currentPeerTubeEngine": "4.0.0"
mar 16 15:15:10 creemoseducacioninclusiva.uma.es peertube[256238]:     },
mar 16 15:15:10 creemoseducacioninclusiva.uma.es peertube[256238]:     "retry": 2,
mar 16 15:15:10 creemoseducacioninclusiva.uma.es peertube[256238]:     "headers": {
mar 16 15:15:10 creemoseducacioninclusiva.uma.es peertube[256238]:       "date": "Wed, 16 Mar 2022 14:15:10 GMT"
mar 16 15:15:10 creemoseducacioninclusiva.uma.es peertube[256238]:     },
mar 16 15:15:10 creemoseducacioninclusiva.uma.es peertube[256238]:     "context": {
mar 16 15:15:10 creemoseducacioninclusiva.uma.es peertube[256238]:       "bodyKBLimit": 1000
mar 16 15:15:10 creemoseducacioninclusiva.uma.es peertube[256238]:     }
mar 16 15:15:10 creemoseducacioninclusiva.uma.es peertube[256238]:   }
mar 16 15:15:10 creemoseducacioninclusiva.uma.es peertube[256238]: }
```

With HTTP_PROXY defined I get this output:

```

mar 16 15:14:21 creemoseducacioninclusiva.uma.es peertube[256184]: [creemoseducacioninclusiva.uma.es:443] 2022-03-16 15:14:21.079 info: Got result from PeerTube index. {                                                                                                       
mar 16 15:18:05 creemoseducacioninclusiva.uma.es peertube[256305]:   "body": "",
mar 16 15:18:05 creemoseducacioninclusiva.uma.es peertube[256305]:   "searchParams": {
mar 16 15:18:05 creemoseducacioninclusiva.uma.es peertube[256305]:     "start": 0,
mar 16 15:18:05 creemoseducacioninclusiva.uma.es peertube[256305]:     "count": 10,
mar 16 15:18:05 creemoseducacioninclusiva.uma.es peertube[256305]:     "sort": "-popularity",
mar 16 15:18:05 creemoseducacioninclusiva.uma.es peertube[256305]:     "pluginType": 1,
mar 16 15:18:05 creemoseducacioninclusiva.uma.es peertube[256305]:     "currentPeerTubeEngine": "4.0.0"
mar 16 15:18:05 creemoseducacioninclusiva.uma.es peertube[256305]:   }
mar 16 15:18:05 creemoseducacioninclusiva.uma.es peertube[256305]: }
mar 16 15:18:05 creemoseducacioninclusiva.uma.es peertube[256305]: [creemoseducacioninclusiva.uma.es:443] 2022-03-16 15:18:05.004 error: Cannot list available plugins from index https://packages.joinpeertube.org/api/v1/plugins. {
mar 16 15:18:05 creemoseducacioninclusiva.uma.es peertube[256305]:   "err": {
mar 16 15:18:05 creemoseducacioninclusiva.uma.es peertube[256305]:     "stack": "TypeError: result.data is not iterable\n    at addInstanceInformation (/var/www/peertube/versions/peertube-v4.0.0/dist/server/lib/plugins/plugin-index.js:38:28)\n    at /var/www/peertube/versions/peertube-v4.0.0/dist/server/lib/plugins/plugin-index.js:27:13\n    at Generator.next (<anonymous>)\n    at fulfilled (/var/www/peertube/versions/peertube-v4.0.0/node_modules/tslib/tslib.js:114:62)\n    at processTicksAndRejections (internal/process/task_queues.js:97:5)",
mar 16 15:18:05 creemoseducacioninclusiva.uma.es peertube[256305]:     "message": "result.data is not iterable"
mar 16 15:18:05 creemoseducacioninclusiva.uma.es peertube[256305]:   }
mar 16 15:18:05 creemoseducacioninclusiva.uma.es peertube[256305]: }                                                                  
```

Without HTTP_PROXY defined I get:

```
mar 16 15:15:11 creemoseducacioninclusiva.uma.es peertube[256238]: [creemoseducacioninclusiva.uma.es:443] 2022-03-16 15:15:11.476 error: Cannot list available plugins from index https://packages.joinpeertube.org/api/v1/plugins. {
mar 16 15:15:11 creemoseducacioninclusiva.uma.es peertube[256238]:   "err": {
mar 16 15:15:11 creemoseducacioninclusiva.uma.es peertube[256238]:     "stack": "RequestError: queryA EDESTRUCTION packages.joinpeertube.org\n    at ClientRequest.<anonymous> (/var/www/peertube/versions/peertube-v4.0.0/node_modules/got/dist/source/core/index.js:962:111)\n    at Object.onceWrapper (events.js:422:26)\n    at ClientRequest.emit (events.js:327:22)\n    at ClientRequest.EventEmitter.emit (domain.js:485:12)\n    at ClientRequest.origin.emit (/var/www/peertube/versions/peertube-v4.0.0/node_modules/@szmarczak/http-timer/dist/source/index.js:43:20)\n    at TLSSocket.socketErrorListener (_http_client.js:461:9)\n    at TLSSocket.emit (events.js:315:20)\n    at TLSSocket.EventEmitter.emit (domain.js:485:12)\n    at emitErrorNT (internal/streams/destroy.js:96:8)\n    at emitErrorCloseNT (internal/streams/destroy.js:68:3)\n    at processTicksAndRejections (internal/process/task_queues.js:84:21)\n    at QueryReqWrap.onresolve [as oncomplete] (internal/dns/promises.js:174:17)",
mar 16 15:15:11 creemoseducacioninclusiva.uma.es peertube[256238]:     "message": "queryA EDESTRUCTION packages.joinpeertube.org",
mar 16 15:15:11 creemoseducacioninclusiva.uma.es peertube[256238]:     "name": "RequestError"
mar 16 15:15:11 creemoseducacioninclusiva.uma.es peertube[256238]:   }
mar 16 15:15:11 creemoseducacioninclusiva.uma.es peertube[256238]: }
```

**Comment by Chocobozzz** [comment]
I'm sorry but it seems a proxy error (maybe that is blocking the request or I don't now) so we can't help you.

I'm closing this issue, but don't hesitate to comment if you notice an issue on peertube side after a further investigation.
