### ISSUE TITLE
Pluging install fail - EACCES: permission denied, open config/yarn

### ISSUE THREAD

**Issue by DoumeDuSud** [Chocobozzz/PeerTube#4836]
**All plugin installation fails because of the same access error**

**Steps to reproduce:**

1. In admin control panel I clic to install a pluging
2. 

**Additional information**

* PeerTube instance:
  * URL: https://video.cerclearistote.com
  * version: 4.1.0
  * NodeJS version: 14.19.0
  * Ffmpeg version:

- Log :

```
warn[3/6/2022, 2:50:59 AM] Cannot install plugin peertube-plugin-livechat.

{
  "err": {
    "err": {
      "stack": "Error: Command failed: yarn add peertube-plugin-livechat@5.5.0\nError: EACCES: permission denied, open '/home/PT-CercleAristote/.config/yarn'\n    at Object.openSync (fs.js:497:3)\n    at readFileSync (fs.js:393:35)\n    at /usr/lib/node_modules/yarn/lib/cli.js:101466:58\n    at Array.map (<anonymous>)\n    at parseRcPaths (/usr/lib/node_modules/yarn/lib/cli.js:101464:78)\n    at Object.findRc (/usr/lib/node_modules/yarn/lib/cli.js:101478:10)\n    at getRcConfigForCwd (/usr/lib/node_modules/yarn/lib/cli.js:56957:74)\n    at /usr/lib/node_modules/yarn/lib/cli.js:92827:56\n    at Generator.next (<anonymous>)\n    at step (/usr/lib/node_modules/yarn/lib/cli.js:310:30)\n\n    at ChildProcess.exithandler (child_process.js:383:12)\n    at ChildProcess.emit (events.js:400:28)\n    at ChildProcess.emit (domain.js:475:12)\n    at maybeClose (internal/child_process.js:1058:16)\n    at Process.ChildProcess._handle.onexit (internal/child_process.js:293:5)",
      "message": "Command failed: yarn add peertube-plugin-livechat@5.5.0\nError: EACCES: permission denied, open '/home/PT-CercleAristote/.config/yarn'\n    at Object.openSync (fs.js:497:3)\n    at readFileSync (fs.js:393:35)\n    at /usr/lib/node_modules/yarn/lib/cli.js:101466:58\n    at Array.map (<anonymous>)\n    at parseRcPaths (/usr/lib/node_modules/yarn/lib/cli.js:101464:78)\n    at Object.findRc (/usr/lib/node_modules/yarn/lib/cli.js:101478:10)\n    at getRcConfigForCwd (/usr/lib/node_modules/yarn/lib/cli.js:56957:74)\n    at /usr/lib/node_modules/yarn/lib/cli.js:92827:56\n    at Generator.next (<anonymous>)\n    at step (/usr/lib/node_modules/yarn/lib/cli.js:310:30)\n",
      "killed": false,
      "code": 1,
      "signal": null,
      "cmd": "yarn add peertube-plugin-livechat@5.5.0"
    },
    "stdout": "",
    "stderr": "Error: EACCES: permission denied, open '/home/PT-CercleAristote/.config/yarn'\n    at Object.openSync (fs.js:497:3)\n    at readFileSync (fs.js:393:35)\n    at /usr/lib/node_modules/yarn/lib/cli.js:101466:58\n    at Array.map (<anonymous>)\n    at parseRcPaths (/usr/lib/node_modules/yarn/lib/cli.js:101464:78)\n    at Object.findRc (/usr/lib/node_modules/yarn/lib/cli.js:101478:10)\n    at getRcConfigForCwd (/usr/lib/node_modules/yarn/lib/cli.js:56957:74)\n    at /usr/lib/node_modules/yarn/lib/cli.js:92827:56\n    at Generator.next (<anonymous>)\n    at step (/usr/lib/node_modules/yarn/lib/cli.js:310:30)\n"
  }
}
```

- Right on the folder 
 ```
sudo -u PT-CercleAristote ls -lah /home/PT-CercleAristote/.config/yarn
total 8.0K
drwxrwxrwx 2 PT-CercleAristote PT-CercleAristote 4.0K Feb 21 23:31 .
drwxrwxrwx 3 PT-CercleAristote PT-CercleAristote 4.0K Feb 21 23:31 ..
```

**Comment by Chocobozzz** [comment]
Can you `ps -aux | grep peertube` to be sure peertube is running with `PT-CercleAristote` user?

What OS are you running? 
You can try to remove `/home/PT-CercleAristote/.config/yarn`

**Comment by DoumeDuSud** [comment]
```
ps -aux | grep peertube
PT-Cerc+   12026  3.3  1.7 1126788 282180 ?      Ssl  Mar06  93:57 peertube
PT-Cerc+   44487  1.7  0.9 1035868 162872 ?      Ssl  Mar06  27:12 peertube
cercle-+  138863  0.0  0.0   6432   724 pts/0    S+   00:36   0:00 grep --color=auto peertube
```

 OS : 
```
 lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.4 LTS
Release:	20.04
Codename:	focal
```

Yes I have remove the folder, after that, I have to re install yarm ?

**Comment by Chocobozzz** [comment]
> Yes I have remove the folder, after that, I have to re install yarm ?

No, just try to reinstall the plugin to see if the error changed.

**Comment by DoumeDuSud** [comment]
It still not working [see log](https://zerobin.net/?b2ca1d4cb4b4183b#0GRTYV+gZfr6jQ8J+2HmPsOcPtgw/c2qBFaNc5IJlHM=)

**Comment by DoumeDuSud** [comment]
To solve the problem, I create a new user as describe in doc. 
```
sudo useradd -m -d /var/www/peertube -s /bin/bash -p peertube peertube
```
Set the proper own of all storage folder
Modify the systemd services accordingly and reload the config

Now it's working properly
