### ISSUE TITLE
403 when I try to follow another instance

### ISSUE THREAD

**Issue by Axeltherabbit** [Chocobozzz/PeerTube#4851]
**Describe the current behavior**
My instance seems unable to follow and be followed by other instances, when I do it I get a 403, when people try to follow me they get a 406 (https://old.reddit.com/r/PeerTube/comments/tba0c0/why_is_instance_following_permission_based/i080xxh/)
**Steps to reproduce:** 
try to follow or be followed by other instances
**Describe the expected behavior**
I'd excpect to be able to do it
**Additional information**

* PeerTube instance:
  * URL: peertube.wiredentrypoint.xyz
  * version: 4.1.1 (but I believe I had this problem since version 4.0.0)
  * NodeJS version: v17.7.1

* Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`):
```
error[12/03/2022, 20:07:06] Cannot execute job 516 in queue activitypub-http-unicast.
{
  "payload": {
    "uri": "https://visionon.tv/accounts/peertube/inbox",
    "signatureActorId": 1,
    "body": {
      "type": "Follow",
      "id": "https://peertube.wiredentrypoint.xyz/:443/accounts/peertube/follows/2686",
      "actor": "https://peertube.wiredentrypoint.xyz/:443/accounts/peertube",
      "object": "https://visionon.tv/accounts/peertube"
    }
  },
  "err": {
    "stack": "HTTPError: Response code 403 (Forbidden)\n    at Request.<anonymous> (/var/www/peertube/versions/peertube-v4.1.1/node_modules/got/dist/source/as-promise/index.js:117:42)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)",
    "message": "Response code 403 (Forbidden)",
    "name": "HTTPError",
    "responseBody": "{\"type\":\"about:blank\",\"title\":\"Forbidden\",\"detail\":\"ActivityPub signature could not be checked\",\"status\":403,\"error\":\"ActivityPub signature could not be checked\"}",
    "responseHeaders": {
      "server": "nginx",
      "date": "Sat, 12 Mar 2022 20:07:06 GMT",
      "content-type": "application/problem+json; charset=utf-8",
      "content-length": "162",
      "connection": "close",
      "x-frame-options": "DENY",
      "tk": "N",
      "etag": "W/\"a2-yy7C9PblzkEB+VnNU3Zr+BsuB+E\""
    },
    "statusCode": 403
  }
}
```

**Comment by Chocobozzz** [comment]
Hello,

It seems there is an issue in your configuration. Could you paste the `webserver:` section?

**Comment by Axeltherabbit** [comment]
Not sure what you are referring to, I don't have any webserver serction in the json-error, I also added "info" logs maybe it helps, thank you. 
```
info[17/03/2022, 12:58:45] 185.69.0.0 - - [17/Mar/2022:12:58:45 +0000] "POST /api/v1/server/following HTTP/1.0" 204 - "https://peertube.wiredentrypoint.xyz/admin/follows/following-list" "Chrome"
{
  "tags": [
    "http"
  ]
}
info[17/03/2022, 12:58:45] Processing ActivityPub follow in job 45.
info[17/03/2022, 12:58:45] Creating job to send follow request to https://visionon.tv/accounts/peertube.
info[17/03/2022, 12:58:45] Processing ActivityPub unicast in job 549.
info[17/03/2022, 12:58:45] 51.38.178.83 - - [17/Mar/2022:12:58:45 +0000] "GET /:443/accounts/peertube HTTP/1.0" 406 - "-" "PeerTube/3.4.1 (+https://visionon.tv)"
{
  "tags": [
    "http"
  ]
}
info[17/03/2022, 12:58:45] Updating 0 good actor follows and 1 bad actor follows scores in cache.
{
  "badInboxes": [
    "https://visionon.tv/accounts/peertube/inbox"
  ]
}
error[17/03/2022, 12:58:45] Cannot execute job 549 in queue activitypub-http-unicast.
{
  "payload": {
    "uri": "https://visionon.tv/accounts/peertube/inbox",
    "signatureActorId": 1,
    "body": {
      "type": "Follow",
      "id": "https://peertube.wiredentrypoint.xyz/:443/accounts/peertube/follows/2686",
      "actor": "https://peertube.wiredentrypoint.xyz/:443/accounts/peertube",
      "object": "https://visionon.tv/accounts/peertube"
    }
  },
  "err": {
    "stack": "HTTPError: Response code 403 (Forbidden)\n    at Request.<anonymous> (/var/www/peertube/versions/peertube-v4.1.1/node_modules/got/dist/source/as-promise/index.js:117:42)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)",
    "message": "Response code 403 (Forbidden)",
    "name": "HTTPError",
    "responseBody": "{\"type\":\"about:blank\",\"title\":\"Forbidden\",\"detail\":\"ActivityPub signature could not be checked\",\"status\":403,\"error\":\"ActivityPub signature could not be checked\"}",
    "responseHeaders": {
      "server": "nginx",
      "date": "Thu, 17 Mar 2022 12:58:45 GMT",
      "content-type": "application/problem+json; charset=utf-8",
      "content-length": "162",
      "connection": "close",
      "x-frame-options": "DENY",
      "tk": "N",
      "etag": "W/\"a2-yy7C9PblzkEB+VnNU3Zr+BsuB+E\""
    },
    "statusCode": 403
  }
}
```

One think I'm thinking could it be because I didn't set the mailserver up? but it would be strange because it's not something that should be dependent

**Comment by Axeltherabbit** [comment]
I don't think I have ever touched it

```
webserver:
  https: true
  hostname: peertube.wiredentrypoint.xyz
  port: 443
```

**Comment by Chocobozzz** [comment]
Try to run https://docs.joinpeertube.org/maintain-tools?id=update-hostjs

**Comment by Axeltherabbit** [comment]
It works, thank you!
