### ISSUE TITLE
PeerTube CLI tools Error with youtube-dl

### ISSUE THREAD

**Issue by user-tech** [Chocobozzz/PeerTube#4862]
I can't access youtube-dl. Doesn't seem that it's installed,

This is my first time using PeerTube. I'm trying to import a playlist from youtube,

Here's what I'm getting from the console.
Any help would be appreciated!

```
admin@uVODu:~/PeerTube/storage$ peertube import --target-url "https://www.youtube.com/watch?v=26lZvxwWzY0"[localhost:9000] 2022-03-15 20:09:40.673 info: Updating youtubeDL binary from https://yt-dl.org/downloads/latest/youtube-dl.
[localhost:9000] 2022-03-15 20:09:41.594 error: Cannot update youtube-dl from https://yt-dl.org/downloads/latest/youtube-dl. {
  "err": {
    "stack": "Error: ENOENT: no such file or directory, open '/home/admin/PeerTube/storage/bin/youtube-dl'",
    "message": "ENOENT: no such file or directory, open '/home/admin/PeerTube/storage/bin/youtube-dl'",
    "errno": -2,
    "code": "ENOENT",
    "syscall": "open",
    "path": "/home/admin/PeerTube/storage/bin/youtube-dl"
  }
}
Error: Command failed with exit code 2: /usr/bin/python3 /home/admin/PeerTube/storage/bin/youtube-dl -j --flat-playlist --playlist-reverse --dump-json -f bestvideo[vcodec^=avc1][height=720]+bestaudio[ext=m4a]/bestvideo[vcodec!*=av01][vcodec!*=vp9.2][height=720]+bestaudio/bestvideo[vcodec^=avc1][height<=720]+bestaudio[ext=m4a]/bestvideo[vcodec!*=av01][vcodec!*=vp9.2]+bestaudio/best[vcodec!*=av01][vcodec!*=vp9.2]/best https://www.youtube.com/watch?v=26lZvxwWzY0
/usr/bin/python3: can't open file '/home/admin/PeerTube/storage/bin/youtube-dl': [Errno 2] No such file or directory
    at makeError (/home/admin/PeerTube/node_modules/execa/lib/error.js:60:11)
    at handlePromise (/home/admin/PeerTube/node_modules/execa/index.js:118:26)
    at processTicksAndRejections (internal/process/task_queues.js:95:5) {
  shortMessage: 'Command failed with exit code 2: /usr/bin/python3 /home/admin/PeerTube/storage/bin/youtube-dl -j --flat-playlist --playlist-reverse --dump-json -f bestvideo[vcodec^=avc1][height=720]+bestaudio[ext=m4a]/bestvideo[vcodec!*=av01][vcodec!*=vp9.2][height=720]+bestaudio/bestvideo[vcodec^=avc1][height<=720]+bestaudio[ext=m4a]/bestvideo[vcodec!*=av01][vcodec!*=vp9.2]+bestaudio/best[vcodec!*=av01][vcodec!*=vp9.2]/best https://www.youtube.com/watch?v=26lZvxwWzY0',
  command: '/usr/bin/python3 /home/admin/PeerTube/storage/bin/youtube-dl -j --flat-playlist --playlist-reverse --dump-json -f bestvideo[vcodec^=avc1][height=720]+bestaudio[ext=m4a]/bestvideo[vcodec!*=av01][vcodec!*=vp9.2][height=720]+bestaudio/bestvideo[vcodec^=avc1][height<=720]+bestaudio[ext=m4a]/bestvideo[vcodec!*=av01][vcodec!*=vp9.2]+bestaudio/best[vcodec!*=av01][vcodec!*=vp9.2]/best https://www.youtube.com/watch?v=26lZvxwWzY0',
  escapedCommand: '"/usr/bin/python3" "/home/admin/PeerTube/storage/bin/youtube-dl" -j --flat-playlist --playlist-reverse --dump-json -f "bestvideo[vcodec^=avc1][height=720]+bestaudio[ext=m4a]/bestvideo[vcodec!*=av01][vcodec!*=vp9.2][height=720]+bestaudio/bestvideo[vcodec^=avc1][height<=720]+bestaudio[ext=m4a]/bestvideo[vcodec!*=av01][vcodec!*=vp9.2]+bestaudio/best[vcodec!*=av01][vcodec!*=vp9.2]/best" "https://www.youtube.com/watch?v=26lZvxwWzY0"',
  exitCode: 2,
  signal: undefined,
  signalDescription: undefined,
  stdout: '',
  stderr: "/usr/bin/python3: can't open file '/home/admin/PeerTube/storage/bin/youtube-dl': [Errno 2] No such file or directory",
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false
}
admin@uVODu:~/PeerTube$ 
```

**Comment by Chocobozzz** [comment]
Could you run `ls -l /home/admin/PeerTube/storage/bin` please?

**Comment by user-tech** [comment]
> 
`admin@uVODu:/$ ls -l /home/admin/PeerTube/storage/bin
ls: cannot access '/home/admin/PeerTube/storage/bin': No such file or directory`

**Comment by user-tech** [comment]
> Could you run `ls -l /home/admin/PeerTube/storage/bin` please?

`admin@uVODu:/$ ls -l /home/admin/PeerTube/storage/bin
ls: cannot access '/home/admin/PeerTube/storage/bin': No such file or directory`

**Comment by Chocobozzz** [comment]
Okay then try `mkdir -p /home/admin/PeerTube/storage/bin` and rerun the command

**Comment by user-tech** [comment]
Thank you that fixed everything!
