### ISSUE TITLE
Error in ffmpeg check when start service

### ISSUE THREAD

**Issue by AtaZ991** [Chocobozzz/PeerTube#4872]
Download latest version (4.1.1), unpack and install, but when start service get error.

```

мар 21 19:18:30 PeerTube peertube[8070]: [mysite.ru:443] 2022-03-21 19:18:30.841 error: Error in ffmpeg check. {

мар 21 19:18:30 PeerTube peertube[8070]:   "err": {

мар 21 19:18:30 PeerTube peertube[8070]:     "stack": "Error: Cannot find ffmpeg\n    at /mnt/111/peertubeserver/peertube-v4.1.1/node_modules/fluent-ffmpeg/lib/processor.js:136:22\n    at /mnt/111/peertubeserver/peertube-v4.1.1/node_modules/fluent-ffmpeg/lib/capabilities.js:123:9\n    at wrapper (/mnt/111/peertubeserver/peertube-v4.1.1/node_modules/async/dist/async.js:271:20)\n    at next (/mnt/111/peertubeserver/peertube-v4.1.1/node_modules/async/dist/async.js:5793:24)\n    at /mnt/111/peertubeserver/peertube-v4.1.1/node_modules/async/dist/async.js:327:20\n    at /mnt/111/peertubeserver/peertube-v4.1.1/node_modules/fluent-ffmpeg/lib/capabilities.js:116:11\n    at /mnt/111/peertubeserver/peertube-v4.1.1/node_modules/fluent-ffmpeg/lib/utils.js:223:16\n    at F (/mnt/111/peertubeserver/peertube-v4.1.1/node_modules/fluent-ffmpeg/node_modules/which/which.js:68:16)\n    at E (/mnt/111/peertubeserver/peertube-v4.1.1/node_modules/fluent-ffmpeg/node_modules/which/which.js:80:29)\n    at /mnt/111/peertubeserver/peertube-v4.1.1/node_modules/fluent-ffmpeg/node_modules/which/which.js:89:16\n    at /mnt/111/peertubeserver/peertube-v4.1.1/node_modules/isexe/index.js:42:5\n    at /mnt/111/peertubeserver/peertube-v4.1.1/node_modules/isexe/mode.js:8:5\n    at FSReqCallback.oncomplete (fs.js:191:21)",

мар 21 19:18:30 PeerTube peertube[8070]:     "message": "Cannot find ffmpeg"

мар 21 19:18:30 PeerTube peertube[8070]:   }

мар 21 19:18:30 PeerTube peertube[8070]: }
```

What I do wrong?

**Comment by kontrollanten** [comment]
What do you get when running `which ffmpeg`? If you haven't installed ffmpeg you have to do that first, how depends on which platform you're running. https://www.ffmpeg.org/download.html

**Comment by AtaZ991** [comment]
> What do you get when running `which ffmpeg`? If you haven't installed ffmpeg you have to do that first, how depends on which platform you're running. https://www.ffmpeg.org/download.html

Thanks, it work. If you can insert this in manual. Also I install redis.

**Comment by Chocobozzz** [comment]
@AtaZ991 It's already in the guide :) https://docs.joinpeertube.org/install-any-os?id=hammer-dependencies
