### ISSUE TITLE
Adjustable Upload Timeout

### ISSUE THREAD

**Issue by BieHDC** [Chocobozzz/PeerTube#4907]
**Describe the problem to be solved**

Currently Peertube has a hardcoded timeout of 2 hours when uploading a video clip through normal web upload and through torrent (did not test the url option because i do not have a resource for that, but i assume it also applies there). After 2 hours the server throws a 404 to the client, causing the client to restart the upload from zero. This is a very big issue for people like me with 80kbyte/sec upload and even worse since the web interface does not mention the timeout anywhere nor do you get a proper error after the timeout occurred. 

**Describe the solution you would like:**

1. Make the timeout value globally adjustable. (i assume it is put in place for certain attacks?)
2. Make the timeout per user overrideable. (if 1. applies, single low speed users can get an exception; like with upload contingent)
3. Display the timeout value below the video contingent bars on the upload page to make users aware.
4. If the timeout occurs, tell the user that the upload was aborted due to the timeout.

**Comment by Chocobozzz** [comment]
Hello,

I'm not aware of such timeout when using client upload form. Could you paste server/client error logs?

**Comment by cernodile** [comment]
Hello.

He's a user of my instance, I'm currently unable to dig too hard into logs, I'll be sending more detailed logs on Saturday. I did find an older log from March of the torrent issue. Promise times out as soon as 2 hours clock in. 
```
{"level":"error","message":"Cannot execute job 30 in queue video-import.","label":"[instance]:443","payload":{"type":"magnet-uri","videoImportId":30,"magnetUri":"magnet:?xt=urn:[REDACTED]"},"err":{"stack":"TimeoutError: Promise timed out after 7200000 milliseconds\n    at Timeout._onTimeout (/var/www/peertube/versions/peertube-v4.1.0/node_modules/p-timeout/index.js:34:63)\n    at listOnTimeout (internal/timers.js:557:17)\n    at processTimers (internal/timers.js:500:7)","message":"Promise timed out after 7200000 milliseconds","name":"TimeoutError"},"timestamp":"2022-03-10T23:20:57.200Z"}
```

**Comment by cernodile** [comment]
Hello again.

I had the time to test this again and managed to reproduce it with Firefox devtools network throttling with "GPRS" profile. ~1.5 hours in of the upload, the endpoint returned 404, client made a POST request and reset the upload. Client-side (image) and server-side logs as follow:
![image](https://user-images.githubusercontent.com/17257449/162565325-480eb11e-ee28-48f7-88d7-af1023be5172.png)

```
{"tags":["http"],"level":"info","message":"[redacted] - - [09/Apr/2022:08:55:41 +0000] \"PUT /api/v1/videos/upload-resumable?upload_id=340ca71c-886cbf4d-31cf028d-e9e6bbaf HTTP/1.0\" 308 - \"https://[instance]/videos/upload\" \"Mozilla/5.0 (X11; Linux x86_64; rv:98.0) Gecko/20100101 Firefox/98.0\"","label":"[instance]:443","timestamp":"2022-04-09T08:55:41.052Z"}
{"tags":["views"],"level":"info","message":"Cleaning video viewers.","label":"[instance]:443","timestamp":"2022-04-09T08:57:09.857Z"}
{"tags":["http"],"level":"info","message":"[redacted] - - [09/Apr/2022:08:57:23 +0000] \"PUT /api/v1/videos/upload-resumable?upload_id=340ca71c-886cbf4d-31cf028d-e9e6bbaf HTTP/1.0\" 308 - \"https://[instance]/videos/upload\" \"Mozilla/5.0 (X11; Linux x86_64; rv:98.0) Gecko/20100101 Firefox/98.0\"","label":"[instance]:443","timestamp":"2022-04-09T08:57:23.581Z"}
{"tags":["http"],"level":"info","message":"[redacted] - - [09/Apr/2022:08:59:06 +0000] \"PUT /api/v1/videos/upload-resumable?upload_id=340ca71c-886cbf4d-31cf028d-e9e6bbaf HTTP/1.0\" 308 - \"https://[instance]/videos/upload\" \"Mozilla/5.0 (X11; Linux x86_64; rv:98.0) Gecko/20100101 Firefox/98.0\"","label":"[instance]:443","timestamp":"2022-04-09T08:59:06.111Z"}
{"tags":["http"],"level":"info","message":"[redacted] - - [09/Apr/2022:09:00:48 +0000] \"PUT /api/v1/videos/upload-resumable?upload_id=340ca71c-886cbf4d-31cf028d-e9e6bbaf HTTP/1.0\" 308 - \"https://[instance]/videos/upload\" \"Mozilla/5.0 (X11; Linux x86_64; rv:98.0) Gecko/20100101 Firefox/98.0\"","label":"[instance]:443","timestamp":"2022-04-09T09:00:48.639Z"}
{"tags":["views"],"level":"info","message":"Cleaning video viewers.","label":"[instance]:443","timestamp":"2022-04-09T09:02:09.857Z"}
{"tags":["http"],"level":"info","message":"[redacted] - - [09/Apr/2022:09:02:31 +0000] \"PUT /api/v1/videos/upload-resumable?upload_id=340ca71c-886cbf4d-31cf028d-e9e6bbaf HTTP/1.0\" 308 - \"https://[instance]/videos/upload\" \"Mozilla/5.0 (X11; Linux x86_64; rv:98.0) Gecko/20100101 Firefox/98.0\"","label":"[instance]:443","timestamp":"2022-04-09T09:02:31.165Z"}
{"tags":["http"],"level":"info","message":"[redacted] - - [09/Apr/2022:09:04:13 +0000] \"PUT /api/v1/videos/upload-resumable?upload_id=340ca71c-886cbf4d-31cf028d-e9e6bbaf HTTP/1.0\" 308 - \"https://[instance]/videos/upload\" \"Mozilla/5.0 (X11; Linux x86_64; rv:98.0) Gecko/20100101 Firefox/98.0\"","label":"[instance]:443","timestamp":"2022-04-09T09:04:13.700Z"}
{"tags":["http"],"level":"info","message":"[redacted] - - [09/Apr/2022:09:05:56 +0000] \"PUT /api/v1/videos/upload-resumable?upload_id=340ca71c-886cbf4d-31cf028d-e9e6bbaf HTTP/1.0\" 308 - \"https://[instance]/videos/upload\" \"Mozilla/5.0 (X11; Linux x86_64; rv:98.0) Gecko/20100101 Firefox/98.0\"","label":"[instance]:443","timestamp":"2022-04-09T09:05:56.227Z"}
{"message":"Removing bad actor follows (scheduler).","level":"info","label":"[instance]:443","timestamp":"2022-04-09T09:07:07.943Z"}
{"message":"Removing old jobs in scheduler.","level":"info","label":"[instance]:443","timestamp":"2022-04-09T09:07:07.945Z"}
{"tags":["views"],"level":"info","message":"Cleaning video viewers.","label":"[instance]:443","timestamp":"2022-04-09T09:07:09.858Z"}
{"tags":["http"],"level":"info","message":"[redacted] - - [09/Apr/2022:09:07:38 +0000] \"PUT /api/v1/videos/upload-resumable?upload_id=340ca71c-886cbf4d-31cf028d-e9e6bbaf HTTP/1.0\" 404 55 \"https://[instance]/videos/upload\" \"Mozilla/5.0 (X11; Linux x86_64; rv:98.0) Gecko/20100101 Firefox/98.0\"","label":"[instance]:443","timestamp":"2022-04-09T09:07:38.754Z"}
{"tags":["http"],"level":"info","message":"[redacted] - - [09/Apr/2022:09:07:39 +0000] \"POST /api/v1/videos/upload-resumable HTTP/1.0\" 201 - \"https://[instance]/videos/upload\" \"Mozilla/5.0 (X11; Linux x86_64; rv:98.0) Gecko/20100101 Firefox/98.0\"","label":"[instance]:443","timestamp":"2022-04-09T09:07:39.419Z"}
{"tags":["http"],"level":"info","message":"[redacted] - - [09/Apr/2022:09:09:21 +0000] \"PUT /api/v1/videos/upload-resumable?upload_id=340ca71c-886cbf4d-31cf028d-e9e6bbaf HTTP/1.0\" 308 - \"https://[instance]/videos/upload\" \"Mozilla/5.0 (X11; Linux x86_64; rv:98.0) Gecko/20100101 Firefox/98.0\"","label":"[instance]:443","timestamp":"2022-04-09T09:09:21.945Z"}
{"tags":["http"],"level":"info","message":"[redacted] - - [09/Apr/2022:09:11:04 +0000] \"PUT /api/v1/videos/upload-resumable?upload_id=340ca71c-886cbf4d-31cf028d-e9e6bbaf HTTP/1.0\" 308 - \"https://[instance]/videos/upload\" \"Mozilla/5.0 (X11; Linux x86_64; rv:98.0) Gecko/20100101 Firefox/98.0\"","label":"[instance]:443","timestamp":"2022-04-09T09:11:04.472Z"}
```

**Comment by kontrollanten** [comment]
Can it be due to the `RemoveDanglingResumableUploadsScheduler` which purges uploads?

**Comment by cernodile** [comment]
I believe so. It executes `await uploadx.storage.purge(now - this.lastExecutionTimeMs)` in faith that stray uploads are being targetted, but [uploadx uses the "item.createdAt" property](https://github.com/kukhariev/node-uploadx/blob/master/packages/core/src/storages/storage.ts#L205) instead of checking if an upload has had any activity.
One temporary workaround would be to disable this scheduler altogether, but that's a tradeoff of one problem for another.

**Comment by cernodile** [comment]
Re: torrent import
It seems like the 2 hour limit is a set constant that isn't configurable by the host without editing the file directly.
Defined [here](https://github.com/Chocobozzz/PeerTube/blob/develop/server/initializers/constants.ts#L186) and the same timeout is given [here](https://github.com/Chocobozzz/PeerTube/blob/1159c4a600ce4f2b86973fe88ae8827a06f523c7/server/lib/job-queue/handlers/video-import.ts#L75). This needs to be a configurable value in my opinion and at very least disclosed. Not everyone has fast internet connection to upload a video in 2 hours. Many people still use slower DSL or 3G connections, but still want to create content for their chosen instance.

**Comment by Chocobozzz** [comment]
2 hours limit on uploads should be fixed by https://github.com/Chocobozzz/PeerTube/commit/77d0ae7b201264423d81e1019139eac3d7716536 thanks to @kukhariev

**Comment by BieHDC** [comment]
> 2 hours limit on uploads should be fixed by [77d0ae7](https://github.com/Chocobozzz/PeerTube/commit/77d0ae7b201264423d81e1019139eac3d7716536) thanks to @kukhariev

So now it only dies when there was no byte uploaded for 2 hours?

**Comment by Chocobozzz** [comment]
Implemented video import timeout config in https://github.com/Chocobozzz/PeerTube/commit/3eba7ab8154027621989cdd4814bc749d79bf0c9
