### ISSUE TITLE
Lack of a WebTorrent version of an external video is not being handled properly

### ISSUE THREAD

**Issue by Avamander** [Chocobozzz/PeerTube#4944]
**Describe the current behavior**
When trying to play a video on an instance that has WebTorrent enabled, that is from a followed instance that doesn't, the player errors silently and never plays the content.

**Steps to reproduce:**
1. Create a new instance with WebTorrent enabled
2. Start following and then try to watch content from an instance without WebTorrent enabled
3. The player might just remain loading and blank

**Describe the expected behavior**
a) Peertube should not return HTML to the client as a `.torrent` file
b) A nice error message is shown when the torrent file actually is invalid
c) PeerTube falls back to an alternative player

**Additional information**
Network tab shows that a request is made to: `https://[instance]/lazy-static/torrents/[UUID]-720.torrent`
But the response is:
```
<!DOCTYPE html><html lang="en" dir="ltr"><head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <meta name="theme-color" content="#fff">
    <meta property="og:platform" content="PeerTube">
    <!-- Web Manifest file -->
    <link rel="manifest" href="/manifest.webmanifest?19271e21497771c3fee792a4bf055b3af39b4a45">

    <link rel="icon" type="image/png" href="/client/assets/images/favicon.png?6913ee4da619f0c53fdc26754e91e68cc8dbda92">
    <link rel="apple-touch-icon" href="/client/assets/images/icons/icon-144x144.png" sizes="144x144">
    <link rel="apple-touch-icon" href="/client/assets/images/icons/icon-192x192.png" sizes="192x192">

    <!-- logo background-image -->

[truncated]
```

Browser log:
```
957.91b7dcfea1b2fb59.js:1 VIDEOJS: ERROR: TypeError: Cannot read properties of undefined (reading 'message')
    at u.handleGlobalError (957.91b7dcfea1b2fb59.js:1:248317)
    at 957.91b7dcfea1b2fb59.js:1:250197
    at X.invoke (polyfills.bc07775cf787910b.js:1:36028)
    at Object.onInvoke (main.745b984ea422442a.js:3:821649)
    at X.invoke (polyfills.bc07775cf787910b.js:1:35967)
    at dt.run (polyfills.bc07775cf787910b.js:1:31339)
    at qo.run (main.745b984ea422442a.js:3:822368)
    at a.<anonymous> (957.91b7dcfea1b2fb59.js:1:250184)
    at HTMLDivElement.Ge.i.dispatcher.i.dispatcher (957.91b7dcfea1b2fb59.js:1:296064)
    at It (957.91b7dcfea1b2fb59.js:1:297084)
33.f827bf5fa30eaea3.js:1 Error: got invalid torrent file from xs param: https://[instance]/lazy-static/torrents/[UUID]-720.torrent
    at $e (33.f827bf5fa30eaea3.js:1:294002)
    at 33.f827bf5fa30eaea3.js:1:208855
    at _.IncomingMessage.<anonymous> (33.f827bf5fa30eaea3.js:1:206908)
    at Object.M (642.e40ba58bb94e3546.js:1:17207)
    at _.IncomingMessage.E.emit (642.e40ba58bb94e3546.js:1:19313)
    at D (642.e40ba58bb94e3546.js:1:32516)
    at D.run (polyfills.bc07775cf787910b.js:1:28997)
    at b (polyfills.bc07775cf787910b.js:1:28488)
    at lt.<computed> (polyfills.bc07775cf787910b.js:1:60981)
    at X.invokeTask (polyfills.bc07775cf787910b.js:1:36647)
```

* PeerTube instance:
  * version: 4.1.1 (fresh `chocobozzz/peertube:production-bullseye`)

**Comment by Chocobozzz** [comment]
Hi,

Could you provide the URL of the two instances?
