### ISSUE TITLE
Docker install with existing Postgres and Redis DB issue

### ISSUE THREAD

**Issue by JamesM92** [Chocobozzz/PeerTube#4953]
**Describe the problem**
Trying to install peertube onto computer with shared postgres and redis databases.

but when deploying the docker compose it has an error, I'm not sure how to interpret the error.

I manually created a peertube user with full priviliges in the peertube databse on postgres.

**Provide the exact sequence of commands / steps that you executed before running into the problem**

**Additional information**
### **_Docker Compose File_**

I specify the volume locations manually as i created a directory thats part of a raid for more file space and redundancy than the default hard drive location has.

I tried deploying with its own db but they kept having conflicts with the already existing ones being called, so i'm trying to figure out how to deploy them while using the existing ones if i can.
```
version: "3.3"

networks:
  frontend:
    external:
      name: FrontEnd
  backend:
    external:
      name: BackEnd


volumes:
  assets:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /srv/dev-disk-by-label-Archive/portainer/peertube/_data/asset

  data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /srv/dev-disk-by-label-Archive/portainer/peertube/_data/data
      
  config:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /srv/dev-disk-by-label-Archive/portainer/peertube/_data/config

  log:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /srv/dev-disk-by-label-Archive/portainer/peertube/_data/log

#  redis:
#    driver: local
#    driver_opts:
#      o: bind
#      type: none
#      device: /srv/dev-disk-by-label-Archive/portainer/peertube/_data/redis

services:

  # You can comment this webserver section if you want to use another webserver/proxy
#  webserver:
#    image: chocobozzz/peertube-webserver:latest
    # If you don't want to use the official image and build one from sources:
    # build:
    #   context: .
    #   dockerfile: Dockerfile.nginx
#    env_file:
#      - .env
#    ports:
#     - "80:80"
#     - "443:443"
#    volumes:
#      - type: bind
#        # Switch sources if you downloaded the whole repository
#        #source: ../../nginx/peertube
#        source: ./docker-volume/nginx/peertube
#        target: /etc/nginx/conf.d/peertube.template
#      - assets:/var/www/peertube/peertube-latest/client/dist:ro
#      - ./docker-volume/data:/var/www/peertube/storage
#      - certbot-www:/var/www/certbot
#      - ./docker-volume/certbot/conf:/etc/letsencrypt
#    depends_on:
#      - peertube
#    restart: "always"

  # You can comment this certbot section if you want to use another webserver/proxy
#  certbot:
#    container_name: certbot
#    image: certbot/certbot
#    volumes:
#      - ./docker-volume/certbot/conf:/etc/letsencrypt
#      - certbot-www:/var/www/certbot
#    restart: unless-stopped
#    entrypoint: /bin/sh -c "trap exit TERM; while :; do certbot renew --webroot -w /var/www/certbot; sleep 12h & wait $${!}; done;"
#    depends_on:
#      - webserver

  peertube:
    # If you don't want to use the official image and build one from sources:
    # build:
    #   context: .
    #   dockerfile: ./support/docker/production/Dockerfile.bullseye
    image: chocobozzz/peertube:production-bullseye
    container_name: 21.01_peertube
    # Use a static IP for this container because nginx does not handle proxy host change without reload
    # This container could be restarted on crash or until the postgresql database is ready for connection
    networks:
      #default:
        #ipv4_address: 172.18.0.42
      - backend
      - frontend
    env_file:
      #- .env
      - stack.env
    ports:
     - "1935:1935" # If you don't want to use the live feature, you can comment this line
     - "9000:9000" # If you provide your own webserver and reverse-proxy, otherwise not suitable for production
    volumes:
      - log:/home
      - assets:/app/client/dist
      - data:/data
      - config:/config
    #depends_on:
      #- postgres
      #- redis
      #- postfix
    restart: unless-stopped

#  postgres:
#    image: postgres:13-alpine
#    env_file:
#      #- .env
#      - stack.env
#    volumes:
#      - ./docker-volume/db:/var/lib/postgresql/data
#    restart: unless-stopped

#  redis:
#    image: redis:6-alpine
#    container_name: 21.00_peertube-redis
#    volumes:
#      - redis:/data
#    restart: unless-stopped

#  postfix:
#    image: mwader/postfix-relay
#    env_file:
#      - .env
#    volumes:
#      - ./docker-volume/opendkim/keys:/etc/opendkim/keys
#    restart: "always"

#networks:
#  default:
#    ipam:
#      driver: default
#      config:
#      - subnet: 172.18.0.0/16

#volumes:
#  assets:
#  certbot-www:
```
### **_Stack.ENV file_**
_i use stack.env because i am trying to deploy this from within portainer and thats the name it uses for the .env file it creates when you add variables to its user interface._

```
POSTGRES_DB=peertube
PEERTUBE_DB_USERNAME=peertube
PEERTUBE_DB_PASSWORD=peertube
PEERTUBE_DB_SSL=false
PEERTUBE_DB_HOSTNAME=01_postgres
PEERTUBE_WEBSERVER_HOSTNAME=XXXXXXXX.club
PEERTUBE_TRUST_PROXY=["127.0.0.1", "loopback", "172.18.0.0/16","192.168.0.151"]
```

### **_Log File Error:_**
```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'start' ]
2 info using npm@6.14.16
3 info using node@v14.19.1
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle peertube@4.1.1~prestart: peertube@4.1.1
6 info lifecycle peertube@4.1.1~start: peertube@4.1.1
7 verbose lifecycle peertube@4.1.1~start: unsafe-perm in lifecycle true
8 verbose lifecycle peertube@4.1.1~start: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/app/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
9 verbose lifecycle peertube@4.1.1~start: CWD: /app
10 silly lifecycle peertube@4.1.1~start: Args: [ '-c', 'node dist/server' ]
11 silly lifecycle peertube@4.1.1~start: Returned: code: 255  signal: null
12 info lifecycle peertube@4.1.1~start: Failed to exec start script
13 verbose stack Error: peertube@4.1.1 start: `node dist/server`
13 verbose stack Exit status 255
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:400:28)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:400:28)
13 verbose stack     at maybeClose (internal/child_process.js:1058:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:293:5)
14 verbose pkgid peertube@4.1.1
15 verbose cwd /app
16 verbose Linux 5.10.0-10-amd64
17 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
18 verbose node v14.19.1
19 verbose npm  v6.14.16
20 error code ELIFECYCLE
21 error errno 255
22 error peertube@4.1.1 start: `node dist/server`
22 error Exit status 255
23 error Failed at the peertube@4.1.1 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 255, true ]
```

### **_Additional Log File Error_**

could this be because i comment out the .env settings related to email server, or is it because of some issue with the postgres server?

**Comment by Chocobozzz** [comment]
Hi,

I think you'll have better error output using `command: [ "node", "dist/server" ]` in `peertube:` section

**Comment by JamesM92** [comment]
figured it out, it wasn't an issue with the databases, it was that i omitted the email information causing it to bug out.
