### ISSUE TITLE
Invalid client Issues when trying to login.

### ISSUE THREAD

**Issue by JamesM92** [Chocobozzz/PeerTube#4960]
**Describe the problem**
peertube deploys, and can access it but when i try to login it says the client is invalid.

**Provide the exact sequence of commands / steps that you executed before running into the problem**
### **_docker-compose.yml_**
```

version: "3.3"

networks:
  frontend:
    external:
      name: FrontEnd
  backend:
    external:
      name: BackEnd


volumes:
  assets:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /srv/dev-disk-by-label-Archive/portainer/peertube/_data/asset

  data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /srv/dev-disk-by-label-Archive/portainer/peertube/_data/data
      
  config:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /srv/dev-disk-by-label-Archive/portainer/peertube/_data/config

  log:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /srv/dev-disk-by-label-Archive/portainer/peertube/_data/log



services:

  # You can comment this webserver section if you want to use another webserver/proxy
  # You can comment this certbot section if you want to use another webserver/proxy

  peertube:
    # If you don't want to use the official image and build one from sources:
    # build:
    #   context: .
    #   dockerfile: ./support/docker/production/Dockerfile.bullseye
    image: chocobozzz/peertube:production-bullseye
    container_name: 21.01_peertube
    # Use a static IP for this container because nginx does not handle proxy host change without reload
    # This container could be restarted on crash or until the postgresql database is ready for connection
    environment:
      - PT_INITIAL_ROOT_PASSWORD=pass123
      #- PEERTUBE_WEBSERVER_PORT=443
      #- PEERTUBE_WEBSERVER_HTTPS=true
      - PEERTUBE_WEBSERVER_HOSTNAME=penguinarmy.club
      #- PEERTUBE_SIGNUP_ENABLED=true
      - PEERTUBE_TRANSCODING_ENABLED=true
      #- PEERTUBE_CONTACT_FORM_ENABLED=true
      - PEERTUBE_REDIS_HOSTNAME=redis
    networks:
      #default:
        #ipv4_address: 172.18.0.42
      - backend
      - frontend
    env_file:
      #- .env
      - stack.env #stack.env is used as im deploying this inside a portainer 
    ports:
     - "1935:1935" # If you don't want to use the live feature, you can comment this line
     - "1380:9000" # If you provide your own webserver and reverse-proxy, otherwise not suitable for production
    volumes:
      - log:/home
      - assets:/app/client/dist
      - data:/data
      - config:/config
    #depends_on:
      #- postgres
      #- redis
      #- postfix
    restart: unless-stopped

```
### **_stack.env_**
```

POSTGRES_DB=peertube
PEERTUBE_DB_USERNAME=peertube
PEERTUBE_DB_PASSWORD=peertube
PEERTUBE_DB_SSL=false
PEERTUBE_DB_HOSTNAME=01_postgres
PEERTUBE_WEBSERVER_HOSTNAME=penguinarmy.club
PEERTUBE_TRUST_PROXY=["127.0.0.1", "loopback", "172.18.0.0/16","192.168.0.151"]
PEERTUBE_SMTP_HOSTNAME=03_email
PEERTUBE_SMTP_PORT=143
PEERTUBE_SMTP_FROM=no-reply@penguinarmy.club
PEERTUBE_SMTP_TLS=false
PEERTUBE_SMTP_DISABLE_STARTTLS=false
PEERTUBE_ADMIN_EMAIL=admin@penguinarmy.club
```

![image](https://user-images.githubusercontent.com/36548759/166841803-99824d5c-143f-4c71-8e29-b6472a7acd05.png)

I can navigate the different pages on the site, even go through and create a new user but i cant login using any accounts.

(ignore the email connection issue, i'm working on that as a seperate issue
```
> peertube@4.1.1 start /app
> node dist/server

[penguinarmy.club:443] 2022-05-04 23:26:16.485 info: Database peertube is ready.
[penguinarmy.club:443] 2022-05-04 23:26:16.825 info: Using 03_email:143 as SMTP server.
[penguinarmy.club:443] 2022-05-04 23:26:16.827 info: Testing SMTP server...
[penguinarmy.club:443] 2022-05-04 23:26:17.038 error: getaddrinfo ENOTFOUND 03_email {
  "component": "smtp-connection",
  "sid": "uJPtIzxqoF0"
}
[penguinarmy.club:443] 2022-05-04 23:26:17.041 error: Failed to connect to SMTP 03_email:143. {
  "err": {
    "stack": "Error: getaddrinfo ENOTFOUND 03_email\n    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:71:26)",
    "message": "getaddrinfo ENOTFOUND 03_email",
    "errno": -3008,
    "code": "EDNS",
    "syscall": "getaddrinfo",
    "hostname": "03_email",
    "command": "CONN"
  }
}
[penguinarmy.club:443] 2022-05-04 23:26:17.059 info: Connecting to redis...
[penguinarmy.club:443] 2022-05-04 23:26:17.076 info: Cleaning HTML cache.
[penguinarmy.club:443] 2022-05-04 23:26:17.079 info: Connected to redis.
[penguinarmy.club:443] 2022-05-04 23:26:17.083 info: HTTP server listening on 0.0.0.0:9000
[penguinarmy.club:443] 2022-05-04 23:26:17.083 info: Web server: https://penguinarmy.club
[penguinarmy.club:443] 2022-05-04 23:26:52.422 info: 172.19.0.1 - - [04/May/2022:23:26:52 +0000] "GET /login HTTP/1.1" 200 10879 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:99.0) Gecko/20100101 Firefox/99.0"
[penguinarmy.club:443] 2022-05-04 23:26:52.569 info: 172.19.0.1 - - [04/May/2022:23:26:52 +0000] "GET /client/en-US/runtime.fb9f3c227c38f757.js HTTP/1.1" 200 4371 "http://192.168.0.151:1380/login" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:99.0) Gecko/20100101 Firefox/99.0"
[penguinarmy.club:443] 2022-05-04 23:26:52.597 info: 172.19.0.1 - - [04/May/2022:23:26:52 +0000] "GET /client/en-US/main.745b984ea422442a.js HTTP/1.1" 304 - "http://192.168.0.151:1380/login" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:99.0) Gecko/20100101 Firefox/99.0"
[penguinarmy.club:443] 2022-05-04 23:26:52.601 info: 172.19.0.1 - - [04/May/2022:23:26:52 +0000] "GET /client/en-US/polyfills.bc07775cf787910b.js HTTP/1.1" 200 97172 "http://192.168.0.151:1380/login" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:99.0) Gecko/20100101 Firefox/99.0"
[penguinarmy.club:443] 2022-05-04 23:26:52.986 info: Getting client tokens for host 192.168.0.151:1380 is forbidden (expected penguinarmy.club).
[penguinarmy.club:443] 2022-05-04 23:26:52.993 info: 172.19.0.1 - - [04/May/2022:23:26:52 +0000] "GET /api/v1/oauth-clients/local HTTP/1.1" 403 290 "http://192.168.0.151:1380/login" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:99.0) Gecko/20100101 Firefox/99.0"
[penguinarmy.club:443] 2022-05-04 23:26:53.002 info: 172.19.0.1 - - [04/May/2022:23:26:53 +0000] "GET /api/v1/videos/languages HTTP/1.1" 200 3348 "http://192.168.0.151:1380/login" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:99.0) Gecko/20100101 Firefox/99.0"
[penguinarmy.club:443] 2022-05-04 23:26:53.046 info: 172.19.0.1 - - [04/May/2022:23:26:53 +0000] "GET /api/v1/config/ HTTP/1.1" 200 2660 "http://192.168.0.151:1380/login" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:99.0) Gecko/20100101 Firefox/99.0"
[penguinarmy.club:443] 2022-05-04 23:26:53.052 info: 172.19.0.1 - - [04/May/2022:23:26:53 +0000] "GET /client/en-US/common.31e2835a103c95c0.js HTTP/1.1" 304 - "http://192.168.0.151:1380/login" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:99.0) Gecko/20100101 Firefox/99.0"
[penguinarmy.club:443] 2022-05-04 23:26:53.057 info: 172.19.0.1 - - [04/May/2022:23:26:53 +0000] "GET /client/en-US/378.7a1c162b37761f1e.js HTTP/1.1" 304 - "http://192.168.0.151:1380/login" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:99.0) Gecko/20100101 Firefox/99.0"
[penguinarmy.club:443] 2022-05-04 23:26:53.089 info: 172.19.0.1 - - [04/May/2022:23:26:53 +0000] "GET /client/en-US/menu.f95723082925e997.svg HTTP/1.1" 304 - "http://192.168.0.151:1380/login" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:99.0) Gecko/20100101 Firefox/99.0"
[penguinarmy.club:443] 2022-05-04 23:26:53.093 info: 172.19.0.1 - - [04/May/2022:23:26:53 +0000] "GET /client/assets/images/logo.svg?9b7e2c535be4c4def251a6f92fd4f119d68f6f79 HTTP/1.1" 200 501 "http://192.168.0.151:1380/login" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:99.0) Gecko/20100101 Firefox/99.0"
[penguinarmy.club:443] 2022-05-04 23:26:53.172 info: 172.19.0.1 - - [04/May/2022:23:26:53 +0000] "GET /client/assets/images/icons/icon-192x192.png HTTP/1.1" - - "http://192.168.0.151:1380/login" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:99.0) Gecko/20100101 Firefox/99.0"
[penguinarmy.club:443] 2022-05-04 23:26:53.186 info: 172.19.0.1 - - [04/May/2022:23:26:53 +0000] "GET /client/assets/images/favicon.png?6a1db648483d5585abcfa9aff008828994bfcc2f HTTP/1.1" 200 746 "http://192.168.0.151:1380/login" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:99.0) Gecko/20100101 Firefox/99.0"
     
army.club:443] 2022-05-04 23:26:53.327 info: 172.19.0.1 - - [04/May/2022:23:26:53 +0000] "GET /api/v1/config/about HTTP/1.1" 200 417 "http://192.168.0.151:1380/login" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:99.0) Gecko/20100101 Firefox/99.0"
[penguinarmy.club:443] 2022-05-04 23:26:53.422 info: 172.19.0.1 - - [04/May/2022:23:26:53 +0000] "GET /client/en-US/826.5543dffa87ae8ccb.js HTTP/1.1" - - "http://192.168.0.151:1380/login" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:99.0) Gecko/20100101 Firefox/99.0"
[penguinarmy.club:443] 2022-05-04 23:29:15.926 warn: Login error {
  "err": {
    "statusCode": 400,
    "status": 400,
    "code": 400,
    "message": "Invalid client: client is invalid",
    "name": "invalid_client",
    "stack": "invalid_client: Invalid client: client is invalid\n    at new InvalidClientError (/app/node_modules/oauth2-server/lib/errors/invalid-client-error.js:26:14)\n    at /app/dist/server/lib/auth/oauth.js:32:19\n    at Generator.next (<anonymous>)\n    at fulfilled (/app/node_modules/tslib/tslib.js:114:62)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (internal/process/task_queues.js:95:5)"
  }
}
     
army.club:443] 2022-05-04 23:29:15.927 info: 172.19.0.1 - - [04/May/2022:23:29:15 +0000] "POST /api/v1/users/token HTTP/1.1" 400 307 "http://192.168.0.151:1380/login" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:99.0) Gecko/20100101 Firefox/99.0"

```
and when i first enter the website this error pops up 
![image](https://user-images.githubusercontent.com/36548759/166851142-7c570820-5dcb-488e-b35d-94c9e1734f9a.png)
but the config/ folder is empty

**Comment by Chocobozzz** [comment]
Hi,

What is the public URL of your instance? It should be the same host than the one defined by `PEERTUBE_WEBSERVER_HOSTNAME`

**Comment by JamesM92** [comment]
the full url is peer.penguinarmy.club, putting the full url into the hostname field seems to have resolved the issue.

I think there should be note that it should be the full url and not just the name of the host/domain. But that seems to have resolved the issue. Thank you.
