### ISSUE TITLE
HTTPError: Response code 401 (Unauthorized) from Mastodon

### ISSUE THREAD

**Issue by noellabo** [Chocobozzz/PeerTube#4971]
This change breaks federation with Mastodon.
https://github.com/Chocobozzz/PeerTube/issues/4963

I think we should Revert this commit until we find some solution. 

Here is an excerpt of the response that results in an error
```
Cannot execute job 27452 in queue activitypub-http-unicast. {
  "payload": {
    "uri": "https://mastodon.social/inbox",
    "signatureActorId": 1,
    "body": {
      "to": [
        "https://www.w3.org/ns/activitystreams#Public",
        "https://fedimovie.com/video-channels/noellabo_slstage_ch/followers",
        "https://fedimovie.com/accounts/peertube/followers",
        "https://fedimovie.com/accounts/noellabo3/followers"
      ],
      "cc": [],
      "id": "https://fedimovie.com/accounts/peertube/views/videos/21931/52f51aa9-265f-43e0-910d-0555c30f5af7",
      "type": "View",
      "actor": "https://fedimovie.com/accounts/peertube",
      "object": "https://fedimovie.com/videos/watch/82f349e6-35df-46eb-9620-fc34144528e9"
    },
    "contextType": "View"
  },
  "err": {
    "stack": "HTTPError: Response code 401 (Unauthorized)\n    at Request.<anonymous> (/var/www/peertube/versions/fedimovie-develop-20220508/node_modules/got/dist/source/as-promise/index.js:117:42)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (internal/process/task_queues.js:95:5)",
    "message": "Response code 401 (Unauthorized)",
    "name": "HTTPError",
    "responseBody": "Invalid pseudo-header (created) for rsa-sha256",
(snip...)
    },
    "statusCode": 401
  }
}
```

**Comment by Chocobozzz** [comment]
Thanks! 

Should be fixed by https://github.com/Chocobozzz/PeerTube/commit/543affef08b10cd94f42a37938f0fa17feddda77
