### ISSUE TITLE
v4.2.0-RC1: replay don't work for permanent lives

### ISSUE THREAD

**Issue by JohnXLivingston** [Chocobozzz/PeerTube#4998]
**Describe the current behavior**

I wanted to test the new feature that can save replays for permanent lives.
So, I created a new unlisted video (it's a test, I don't want it to be public), checked the «permanent live» option, and checked the «save replay» checkbox.

Then I started a live with the following command:

```bash
ffmpeg -re -f lavfi -i "aevalsrc=0 [out1]; testsrc=s=1280x720,drawtext=borderw=5:fontcolor=white:fontsize=30:text='%{localtime}/%{pts\:hms}':x=\(w-text_w\)/2:y=\(h-text_h-line_h\)/2 [out0]"  -acodec aac -vcodec h264 -strict -2 -pix_fmt yuv420p -profile:v baseline -level 3.0 -f flv rtmp://videos.john-livingston.fr:1935/live/my_live_private_key
```
After a while, I stopped the live (ctrl+c, to stop ffmpeg nicely with a «Exiting normally, received signal 2.» message).

Then I waited for the replay, and it does not come.
I saw this error log:

```log
error[24/05/2022, 16:26:43] Cannot execute job 4 in queue video-live-ending.

{
  "payload": {
    "videoId": 21313,
    "replayDirectory": "/var/www/peertube/storage/streaming-playlists/hls/87bea8e2-43af-49a0-b4cd-7a2825e84d1f/replay/2022-05-24T14:21:12.843Z",
    "liveSessionId": 1,
    "publishedAt": "2022-05-24T14:21:16.929Z"
  },
  "err": {
    "stack": "Error: ffprobe exited with code 1\nffprobe version 4.3.4-0+deb11u1 Copyright (c) 2007-2021 the FFmpeg developers\n  built with gcc 10 (Debian 10.2.1-6)\n  configuration: --prefix=/usr --extra-version=0+deb11u1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-avresample --disable-filter=resample --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libdav1d --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librabbitmq --enable-librsvg --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --enable-pocketsphinx --enable-libmfx --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared\n  libavutil      56. 51.100 / 56. 51.100\n  libavcodec     58. 91.100 / 58. 91.100\n  libavformat    58. 45.100 / 58. 45.100\n  libavdevice    58. 10.100 / 58. 10.100\n  libavfilter     7. 85.100 /  7. 85.100\n  libavresample   4.  0.  0 /  4.  0.  0\n  libswscale      5.  7.100 /  5.  7.100\n  libswresample   3.  7.100 /  3.  7.100\n  libpostproc    55.  7.100 / 55.  7.100\n/var/www/peertube/storage/streaming-playlists/hls/87bea8e2-43af-49a0-b4cd-7a2825e84d1f/replay/2022-05-24T14:21:12.843Z/concat-3.ts: No such file or directory\n\n    at ChildProcess.<anonymous> (/var/www/peertube/versions/peertube-v4.2.0-rc.1/node_modules/fluent-ffmpeg/lib/ffprobe.js:233:22)\n    at ChildProcess.emit (events.js:400:28)\n    at ChildProcess.emit (domain.js:475:12)\n    at Process.ChildProcess._handle.onexit (internal/child_process.js:282:12)",
    "message": "ffprobe exited with code 1\nffprobe version 4.3.4-0+deb11u1 Copyright (c) 2007-2021 the FFmpeg developers\n  built with gcc 10 (Debian 10.2.1-6)\n  configuration: --prefix=/usr --extra-version=0+deb11u1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-avresample --disable-filter=resample --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libdav1d --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librabbitmq --enable-librsvg --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --enable-pocketsphinx --enable-libmfx --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared\n  libavutil      56. 51.100 / 56. 51.100\n  libavcodec     58. 91.100 / 58. 91.100\n  libavformat    58. 45.100 / 58. 45.100\n  libavdevice    58. 10.100 / 58. 10.100\n  libavfilter     7. 85.100 /  7. 85.100\n  libavresample   4.  0.  0 /  4.  0.  0\n  libswscale      5.  7.100 /  5.  7.100\n  libswresample   3.  7.100 /  3.  7.100\n  libpostproc    55.  7.100 / 55.  7.100\n/var/www/peertube/storage/streaming-playlists/hls/87bea8e2-43af-49a0-b4cd-7a2825e84d1f/replay/2022-05-24T14:21:12.843Z/concat-3.ts: No such file or directory\n"
  }
}
```

I then wanted to test if it was the «unlisted video» the problem. So I made the video public. And started again the live.

A new `video-live-ending` job was created, with the following `replayDirectory`: /var/www/peertube/storage/streaming-playlists/hls/87bea8e2-43af-49a0-b4cd-7a2825e84d1f/replay/2022-05-24T14:26:48.046Z

The folder was here:

```bash
ls /var/www/peertube/storage/streaming-playlists/hls/87bea8e2-43af-49a0-b4cd-7a2825e84d1f/replay/2022-05-24T14:26:48.046Z
concat-0.ts  concat-1.ts  concat-2.ts  concat-3.ts
```

But, after a few minutes... the job failed with a new error: 
```log
Error: ENOENT: no such file or directory, scandir '/var/www/peertube/storage/streaming-playlists/hls/87bea8e2-43af-49a0-b4cd-7a2825e84d1f/replay/2022-05-24T14:26:48.046Z'
```

The same folder that was here 2 minutes ago is now missing!

Funny thing... I then made a third attempt: I made the video unlisted, tried again... and... now it worked!
https://videos.john-livingston.fr/w/vHpLzEaQWE8Aymt5cTx12U

For the 2 attempts that failed, I can see videos in my library:
![image](https://user-images.githubusercontent.com/38844060/170064351-843bf5b3-76eb-4096-bc03-403f0afb63d5.png)

Here are the 2 broken links:
https://videos.john-livingston.fr/w/2N5mKc2iAgrXLFUgQQm2Cb
https://videos.john-livingston.fr/w/3GPHEQZ8zd94mmEK8xyd9H

**Additional information**

* PeerTube instance:
  * URL: https://videos.john-livingston.fr/
  * version: 4.2.0-RC1
  * NodeJS version: v14.19.1
  * Ffmpeg version: 4.3.4-0+deb11u1

* Browser name, version and platforms on which you could reproduce the bug:
* Link to browser console log if relevant:
* Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`):

**Comment by JohnXLivingston** [comment]
In the screenshot, It seems that the broken video that should have been public is unlisted, and the unlisted one is public... That's weird.

**Comment by Chocobozzz** [comment]
Hi,

I don't think it's related to the video privacy. Could you display jobs run for this live? I suspect another live session deleted the replay directory before the `video-live-ending`  job finished its execution

**Comment by JohnXLivingston** [comment]
```
Job: 4 Type: video-live-ending Processed on May 24, 2022, 4:26:38 PM Finished on May 24, 2022, 4:26:43 PM
--
{   "videoId": 21313,   "replayDirectory": "/var/www/peertube/storage/streaming-playlists/hls/87bea8e2-43af-49a0-b4cd-7a2825e84d1f/replay/2022-05-24T14:21:12.843Z",   "liveSessionId": 1,   "publishedAt": "2022-05-24T14:21:16.929Z" }
Error: ffprobe exited with code 1 ffprobe version 4.3.4-0+deb11u1 Copyright (c) 2007-2021 the FFmpeg developers   built with gcc 10 (Debian 10.2.1-6)   configuration: --prefix=/usr --extra-version=0+deb11u1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-avresample --disable-filter=resample --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libdav1d --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librabbitmq --enable-librsvg --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --enable-pocketsphinx --enable-libmfx --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared   libavutil      56. 51.100 / 56. 51.100   libavcodec     58. 91.100 / 58. 91.100   libavformat    58. 45.100 / 58. 45.100   libavdevice    58. 10.100 / 58. 10.100   libavfilter     7. 85.100 /  7. 85.100   libavresample   4.  0.  0 /  4.  0.  0   libswscale      5.  7.100 /  5.  7.100   libswresample   3.  7.100 /  3.  7.100   libpostproc    55.  7.100 / 55.  7.100 /var/www/peertube/storage/streaming-playlists/hls/87bea8e2-43af-49a0-b4cd-7a2825e84d1f/replay/2022-05-24T14:21:12.843Z/concat-3.ts: No such file or directory      at ChildProcess.<anonymous> (/var/www/peertube/versions/peertube-v4.2.0-rc.1/node_modules/fluent-ffmpeg/lib/ffprobe.js:233:22)     at ChildProcess.emit (events.js:400:28)     at ChildProcess.emit (domain.js:475:12)     at Process.ChildProcess._handle.onexit (internal/child_process.js:282:12)

```

```


Job: 5 Type: video-live-ending Processed on May 24, 2022, 4:33:14 PM Finished on May 24, 2022, 4:33:14 PM
--
{   "videoId": 21313,   "replayDirectory": "/var/www/peertube/storage/streaming-playlists/hls/87bea8e2-43af-49a0-b4cd-7a2825e84d1f/replay/2022-05-24T14:26:48.046Z",   "liveSessionId": 2,   "publishedAt": "2022-05-24T14:26:50.467Z" }

```

The only jobs I can see between these two are activitypub broadcast jobs. And the end date for the first one is way before the start date of the second.

**Comment by JohnXLivingston** [comment]
Here are the peertube's logs:

```
info[24/05/2022, 16:26:38] Processing video live ending for 21313.

{
  "payload": {
    "videoId": 21313,
    "replayDirectory": "/var/www/peertube/storage/streaming-playlists/hls/87bea8e2-43af-49a0-b4cd-7a2825e84d1f/replay/2022-05-24T14:21:12.843Z",
    "liveSessionId": 1,
    "publishedAt": "2022-05-24T14:21:16.929Z"
  }
}


info[24/05/2022, 16:26:39] Creating torrent /var/www/peertube/storage/torrents/fe3a1669-f0fe-4a9d-8a39-60f29e61d788-480-hls.torrent.

info[24/05/2022, 16:26:41] Creating torrent /var/www/peertube/storage/torrents/866d5a52-95da-4f24-a7b4-b525a2948237-240-hls.torrent.

info[24/05/2022, 16:26:42] Creating torrent /var/www/peertube/storage/torrents/79284912-5bd0-494d-859d-97f4608b7245-144-hls.torrent.

info[24/05/2022, 16:26:43] Updating 0 good actor follows and 1 bad actor follows scores in cache.

{
  "badInboxes": [
    "https://share.peertube.support/inbox"
  ]
}

info[24/05/2022, 16:26:43] Updating 0 good actor follows and 1 bad actor follows scores in cache.

{
  "badInboxes": [
    "https://tube.chocoflan.net/inbox"
  ]
}

error[24/05/2022, 16:26:43] Cannot execute job 4 in queue video-live-ending.

{
  "payload": {
    "videoId": 21313,
    "replayDirectory": "/var/www/peertube/storage/streaming-playlists/hls/87bea8e2-43af-49a0-b4cd-7a2825e84d1f/replay/2022-05-24T14:21:12.843Z",
    "liveSessionId": 1,
    "publishedAt": "2022-05-24T14:21:16.929Z"
  },
  "err": {
    "stack": "Error: ffprobe exited with code 1\nffprobe version 4.3.4-0+deb11u1 Copyright (c) 2007-2021 the FFmpeg developers\n  built with gcc 10 (Debian 10.2.1-6)\n  configuration: --prefix=/usr --extra-version=0+deb11u1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-avresample --disable-filter=resample --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libdav1d --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librabbitmq --enable-librsvg --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --enable-pocketsphinx --enable-libmfx --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared\n  libavutil      56. 51.100 / 56. 51.100\n  libavcodec     58. 91.100 / 58. 91.100\n  libavformat    58. 45.100 / 58. 45.100\n  libavdevice    58. 10.100 / 58. 10.100\n  libavfilter     7. 85.100 /  7. 85.100\n  libavresample   4.  0.  0 /  4.  0.  0\n  libswscale      5.  7.100 /  5.  7.100\n  libswresample   3.  7.100 /  3.  7.100\n  libpostproc    55.  7.100 / 55.  7.100\n/var/www/peertube/storage/streaming-playlists/hls/87bea8e2-43af-49a0-b4cd-7a2825e84d1f/replay/2022-05-24T14:21:12.843Z/concat-3.ts: No such file or directory\n\n    at ChildProcess.<anonymous> (/var/www/peertube/versions/peertube-v4.2.0-rc.1/node_modules/fluent-ffmpeg/lib/ffprobe.js:233:22)\n    at ChildProcess.emit (events.js:400:28)\n    at ChildProcess.emit (domain.js:475:12)\n    at Process.ChildProcess._handle.onexit (internal/child_process.js:282:12)",
    "message": "ffprobe exited with code 1\nffprobe version 4.3.4-0+deb11u1 Copyright (c) 2007-2021 the FFmpeg developers\n  built with gcc 10 (Debian 10.2.1-6)\n  configuration: --prefix=/usr --extra-version=0+deb11u1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-avresample --disable-filter=resample --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libdav1d --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librabbitmq --enable-librsvg --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --enable-pocketsphinx --enable-libmfx --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared\n  libavutil      56. 51.100 / 56. 51.100\n  libavcodec     58. 91.100 / 58. 91.100\n  libavformat    58. 45.100 / 58. 45.100\n  libavdevice    58. 10.100 / 58. 10.100\n  libavfilter     7. 85.100 /  7. 85.100\n  libavresample   4.  0.  0 /  4.  0.  0\n  libswscale      5.  7.100 /  5.  7.100\n  libswresample   3.  7.100 /  3.  7.100\n  libpostproc    55.  7.100 / 55.  7.100\n/var/www/peertube/storage/streaming-playlists/hls/87bea8e2-43af-49a0-b4cd-7a2825e84d1f/replay/2022-05-24T14:21:12.843Z/concat-3.ts: No such file or directory\n"
  }
}
```

**Comment by JohnXLivingston** [comment]
I can see other logs, just after the error, that could be related:

```
info[24/05/2022, 16:26:47] rtmp://127.0.0.1:1935/live/b711baac-d346-4782-a5c6-9d917d1c3736 probing took 3762 ms (bitrate: NaN, fps: 25, resolution: 720)

{
  "tags": [
    "live",
    "Y03CJZU6",
    "87bea8e2-43af-49a0-b4cd-7a2825e84d1f"
  ]
}

info[24/05/2022, 16:26:47] Will mux/transcode live video of original resolution 720.

{
  "allResolutions": [
    480,
    240,
    144,
    720
  ],
  "tags": [
    "live",
    "Y03CJZU6",
    "87bea8e2-43af-49a0-b4cd-7a2825e84d1f"
  ]
}

info[24/05/2022, 16:26:48] Running live muxing/transcoding for 87bea8e2-43af-49a0-b4cd-7a2825e84d1f.

{
  "tags": [
    "live",
    "Y03CJZU6",
    "87bea8e2-43af-49a0-b4cd-7a2825e84d1f"
  ]
}

info[24/05/2022, 16:26:50] Will publish and federate live https://videos.john-livingston.fr/videos/watch/87bea8e2-43af-49a0-b4cd-7a2825e84d1f.

{
  "tags": [
    "live",
    "Y03CJZU6",
    "87bea8e2-43af-49a0-b4cd-7a2825e84d1f"
  ]
}

info[24/05/2022, 16:26:58] Creating job to update video https://videos.john-livingston.fr/videos/watch/87bea8e2-43af-49a0-b4cd-7a2825e84d1f. 
```

**Comment by Chocobozzz** [comment]
Okay so I think [I was right](https://github.com/Chocobozzz/PeerTube/issues/4998#issuecomment-1137022029).

You streamed again in the same session, before the live ending job completed. And we cleanup the live (including replays) before handling the live session. Could you confirm this assumption?

**Comment by JohnXLivingston** [comment]
This log:
```
info[24/05/2022, 16:26:47] rtmp://127.0.0.1:1935/live/xxxxxxxxxxxxxxxxxxxx probing took 3762 ms (bitrate: NaN, fps: 25, resolution: 720)
```

Is 4 seconds after the error. Is this log emitted at the beginning or at the end of a streaming session?

I really don't remember starting the live again before the first attempt failed. But maybe the problem is between my chair and my keyboard.
I'm going to test one more time. I'll tell you if it worked.

Does it mean that, if a permanent live is interrupted (for example a connection problem), and resumed just a few seconds later, the replay would be lost ?

**Comment by JohnXLivingston** [comment]
Ok, this time it worked. You must be right. I had to wait 5 minutes for the job to start.
Yesterday I probably thought it failed after having waited 2 or 3 minutes.

It seams every replay is in a distinct folder. Maybe these folders should not be cleaned when a live starts?

**Comment by Chocobozzz** [comment]
Should be fixed by https://github.com/Chocobozzz/PeerTube/commit/5333788c08ab6152303829d4624774b5d788ff40

Thanks again!
