### ISSUE TITLE
Error in logs during live video

### ISSUE THREAD

**Issue by Alterak** [Chocobozzz/PeerTube#5034]
**Describe the current behavior**
I created a live video and after some time of the broadcast, an error appeared, but the broadcast did not stop.

This is the PeerTube log
```
error[09.06.2022, 13:56:36] Cannot execute job 157 in queue video-live-ending.
{
  "payload": {
    "videoId": 249647,
    "replayDirectory": "/data/peervideo/storage/streaming-playlists/hls/6fd7dd14-8e9e-404d-86ba-2da37b1e35a8/replay/2022-06-09T10:25:38.722Z",
    "liveSessionId": 30,
    "publishedAt": "2022-06-09T10:25:43.653Z"
  },
  "err": {
    "stack": "Error\n    at Query.run (/var/www/peertube/versions/peertube-v4.2.0/node_modules/sequelize/lib/dialects/postgres/query.js:50:25)\n    at /var/www/peertube/versions/peertube-v4.2.0/node_modules/sequelize/lib/sequelize.js:313:28\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (internal/process/task_queues.js:95:5)\n    at async PostgresQueryInterface.insert (/var/www/peertube/versions/peertube-v4.2.0/node_modules/sequelize/lib/dialects/abstract/query-interface.js:297:21)\n    at async VideoStreamingPlaylistModel.save (/var/www/peertube/versions/peertube-v4.2.0/node_modules/sequelize/lib/model.js:2424:35)",
    "message": "INSERT или UPDATE в таблице \"videoStreamingPlaylist\" нарушает ограничение внешнего ключа \"videoStreamingPlaylist_videoId_fkey\"",
    "name": "SequelizeForeignKeyConstraintError",
    "parent": {
      "stack": "error: INSERT или UPDATE в таблице \"videoStreamingPlaylist\" нарушает ограничение внешнего ключа \"videoStreamingPlaylist_videoId_fkey\"\n    at Parser.parseErrorMessage (/var/www/peertube/versions/peertube-v4.2.0/node_modules/pg-protocol/dist/parser.js:287:98)\n    at Parser.handlePacket (/var/www/peertube/versions/peertube-v4.2.0/node_modules/pg-protocol/dist/parser.js:126:29)\n    at Parser.parse (/var/www/peertube/versions/peertube-v4.2.0/node_modules/pg-protocol/dist/parser.js:39:38)\n    at Socket.<anonymous> (/var/www/peertube/versions/peertube-v4.2.0/node_modules/pg-protocol/dist/index.js:11:42)\n    at Socket.emit (events.js:400:28)\n    at Socket.emit (domain.js:475:12)\n    at addChunk (internal/streams/readable.js:293:12)\n    at readableAddChunk (internal/streams/readable.js:267:9)\n    at Socket.Readable.push (internal/streams/readable.js:206:10)\n    at TCP.onStreamRead (internal/stream_base_commons.js:188:23)",
      "message": "INSERT или UPDATE в таблице \"videoStreamingPlaylist\" нарушает ограничение внешнего ключа \"videoStreamingPlaylist_videoId_fkey\"",
      "length": 393,
      "name": "error",
      "severity": "ОШИБКА",
      "code": "23503",
      "detail": "Ключ (videoId)=(267352) отсутствует в таблице \"video\".",
      "schema": "public",
      "table": "videoStreamingPlaylist",
      "constraint": "videoStreamingPlaylist_videoId_fkey",
      "file": "ri_triggers.c",
      "line": "2465",
      "routine": "ri_ReportViolation",
      "sql": "INSERT INTO \"videoStreamingPlaylist\" (\"id\",\"type\",\"playlistFilename\",\"p2pMediaLoaderInfohashes\",\"p2pMediaLoaderPeerVersion\",\"segmentsSha256Filename\",\"videoId\",\"storage\",\"createdAt\",\"updatedAt\") VALUES (DEFAULT,$1,$2,$3,$4,$5,$6,$7,$8,$9) RETURNING \"id\",\"type\",\"playlistFilename\",\"playlistUrl\",\"p2pMediaLoaderInfohashes\",\"p2pMediaLoaderPeerVersion\",\"segmentsSha256Filename\",\"segmentsSha256Url\",\"videoId\",\"storage\",\"createdAt\",\"updatedAt\";",
      "parameters": [
        1,
        "fcc58a11-ed85-463a-a7ce-6197055ca4d5-master.m3u8",
        [],
        2,
        "e2628a3f-a917-46f4-9704-f6932916d6a4-segments-sha256.json",
        267352,
        0,
        "2022-06-09 10:56:36.052 +00:00",
        "2022-06-09 10:56:36.052 +00:00"
      ]
    },
    "sql": "INSERT INTO \"videoStreamingPlaylist\" (\"id\",\"type\",\"playlistFilename\",\"p2pMediaLoaderInfohashes\",\"p2pMediaLoaderPeerVersion\",\"segmentsSha256Filename\",\"videoId\",\"storage\",\"createdAt\",\"updatedAt\") VALUES (DEFAULT,$1,$2,$3,$4,$5,$6,$7,$8,$9) RETURNING \"id\",\"type\",\"playlistFilename\",\"playlistUrl\",\"p2pMediaLoaderInfohashes\",\"p2pMediaLoaderPeerVersion\",\"segmentsSha256Filename\",\"segmentsSha256Url\",\"videoId\",\"storage\",\"createdAt\",\"updatedAt\";",
    "fields": null
  }
}
```

This is the log from the browser
```
zone.js:1064 Error: Connection failed.
    at d._onConnectionStateChange (index.js:699:28)
    at RTCPeerConnection._pc.onconnectionstatechange (index.js:118:12)
C.onUnhandledError @ zone.js:1064
W @ zone.js:588
Объект Promise.then (асинхронный)
q @ zone.js:561
it @ zone.js:572
scheduleTask @ zone.js:396
scheduleTask @ zone.js:221
scheduleMicroTask @ zone.js:241
(анонимная) @ zone.js:2538
Nt.S.<computed> @ zone.js:973
_destroy @ index.js:440
destroy @ index.js:431
_onConnectionStateChange @ index.js:699
_pc.onconnectionstatechange @ index.js:118
```

I do not know how serious this error is. I decided to let you know about it.

* PeerTube instance:
  * URL: https://peervideo.ru
  * version: 4.2.0
  * NodeJS version: v14.19.3
  * Ffmpeg version: 4.3.4-0+deb11u1

**Comment by Chocobozzz** [comment]
Hello,

I don't think it's important: the video may have been deleted during the save replay process
