### ISSUE TITLE
Graceful shutdown/restart (docker ?)

### ISSUE THREAD

**Issue by Tr4sK** [Chocobozzz/PeerTube#5045]
Hi,
So tonight, I had a video import job stuck for some hours. So, I decided to restart my service. And all the queuing job failed into postgres connections issue and are now mark as failed.
I still have few dozen videos to import and would like to restart those related job.

```
Job: 686 Type: video-import Processed on Jun 11, 2022, 10:18:44 PM Finished on Jun 11, 2022, 10:18:44 PM
--
{   "type": "youtube-dl",   "videoImportId": 688,   "fileExt": ".mp4" }
SequelizeHostNotFoundError: getaddrinfo ENOTFOUND postgres     at Client._connectionCallback (/app/node_modules/sequelize/dist/lib/dialects/postgres/connection-manager.js:133:24)     at Client._handleErrorWhileConnecting (/app/node_modules/pg/lib/client.js:305:19)     at Client._handleErrorEvent (/app/node_modules/pg/lib/client.js:315:19)     at Connection.emit (events.js:400:28)     at Connection.emit (domain.js:475:12)     at Socket.reportStreamError (/app/node_modules/pg/lib/connection.js:52:12)     at Socket.emit (events.js:400:28)     at Socket.emit (domain.js:475:12)     at emitErrorNT (internal/streams/destroy.js:106:8)     at emitErrorCloseNT (internal/streams/destroy.js:74:3)     at processTicksAndRejections (internal/process/task_queues.js:82:21)
```

On the user interface, jobs are marked as to import

![peertube-toimport](https://user-images.githubusercontent.com/1238195/173207205-d5379837-7ccf-43db-b040-83bbcaff7d43.png)
![import video in waiting state](https://user-images.githubusercontent.com/1238195/173207235-241cd412-fb83-475b-b41a-8b012a3dfc43.png)

My install is done via Docker
https://tube.tr4sk.me

That issue seems to relate to my situation Graceful shutdown feature #3147

**Comment by Tr4sK** [comment]
That issue seems related #4939

**Comment by Tr4sK** [comment]
I hitting the same situation as videoImport job get stuck for a really short video:

```
Job: 761
Type: video-import Processed on Jun 12, 2022, 12:54:48 PM
Finished on -
--
{   "type": "youtube-dl",   "videoImportId": 763,   "fileExt": ".mp4" }

```

Here is the situation in the database:

```
peertube=# select * from "videoImport" where "id"=761;
 id  |                  targetUrl                  | magnetUri | torrentName | state | error | userId | videoId |         createdAt          |         updatedAt          
-----+---------------------------------------------+-----------+-------------+-------+-------+--------+---------+----------------------------+----------------------------
 761 | https://www.youtube.com/watch?v=-U_oNN55cog |           |             |     2 |       |      5 |  157946 | 2022-06-12 02:03:17.306+00 | 2022-06-12 10:53:53.108+00
(1 row)
peertube=# select * from "videoJobInfo" where "videoId"=157946;
  id  | pendingMove | pendingTranscode | videoId |           createdAt           |           updatedAt           
------+-------------+------------------+---------+-------------------------------+-------------------------------
 9189 |           0 |                0 |  157946 | 2022-06-12 10:53:53.207216+00 | 2022-06-12 10:58:35.415318+00
(1 row)
```

**Comment by Tr4sK** [comment]
So, just killed the process as it seems the cleanest way to stop that non ending job.

It seems that somewhere, I got the video wrong. I assumed that the videoJobInfo.videoID was the same as the one in video table but nope.

After killing the process I got that:

```
Error: Command was killed with SIGTERM (Termination): /usr/bin/python3 /data/bin/youtube-dl -f bestvideo[vcodec^=avc1][height=1080]+bestaudio[ext=m4a]/bestvideo[vcodec!*=av01][vcodec!*=vp9.2][height=1080]+bestaudio/bestvideo[vcodec^=avc1][height<=1080]+bestaudio[ext=m4a]/bestvideo[vcodec!*=av01][vcodec!*=vp9.2]+bestaudio/best[vcodec!*=av01][vcodec!*=vp9.2]/best -o /data/tmp/0c58fbbbfd2cb51390618d72373296cdf8238aaf4f5c7d09c5ddb35ffaab6dcd-import https://www.youtube.com/watch?v=jTNQly9gYD4
[youtube] jTNQly9gYD4: Downloading webpage
[download] Destination: /data/tmp/0c58fbbbfd2cb51390618d72373296cdf8238aaf4f5c7d09c5ddb35ffaab6dcd-import.f136

[download]   0.0% of 510.60MiB at 10.15KiB/s ETA 14:18:58
[download]   0.0% of 510.60MiB at 30.33KiB/s ETA 04:47:22
[download]   0.0% of 510.60MiB at 70.50KiB/s ETA 02:03:38
[download]   0.0% of 510.60MiB at 150.32KiB/s ETA 57:59
[download]   0.0% of 510.60MiB at 104.15KiB/s ETA 01:23:40
[download]   0.0% of 510.60MiB at 92.72KiB/s ETA 01:33:58
[download]   0.0% of 510.60MiB at 89.01KiB/s ETA 01:37:53
[download]   0.0% of 510.60MiB at 83.20KiB/s ETA 01:44:42
[…]
[download]  15.1% of 510.60MiB at 84.48KiB/s ETA 01:27:34
[download]  15.1% of 510.60MiB at 84.50KiB/s ETA 01:27:32
[…]
[download]  15.3% of 510.60MiB at 84.59KiB/s ETA 01:27:16
[download]  15.3% of 510.60MiB at Unknown speed ETA Unknown ETA
[…]
[download]  88.3% of 510.60MiB at 84.44KiB/s ETA 12:05
[download]  88.3% of 510.60MiB at 84.55KiB/s ETA 12:03
    at makeError (/app/node_modules/execa/lib/error.js:60:11)
    at handlePromise (/app/node_modules/execa/index.js:118:26)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

unfortunatly it was almost the end :(
Everything seems to work well. Any way to show the import process in % in the job page ?

**Comment by Tr4sK** [comment]
Fix my slow download issue by switching to yt-dlp.

**Comment by Chocobozzz** [comment]
Hello,

job are automatically restarted on peertube restart. `youtube-dl` is very slow with youtube, it's the reason why the job could not end (and may timeout).

**Comment by Tr4sK** [comment]
Thank you for the tip.
So, as I said before, I switched to yt-dlp which fix the slow download process.

Those job crashed because I didn't properly stopped peertube via docker-compose down.
Basically, I had a quick reboot of my server and postgres decided to stop before peertube app which led to the crash in [OP](#5045#issue-1268389053)
