### ISSUE TITLE
Unable to upload video : Incorrect request parameters: channelId

### ISSUE THREAD

**Issue by nono-lqdn** [Chocobozzz/PeerTube#5049]
### Is there an existing issue for this?

- [X] I have searched existing issues

### Describe the current behavior

I am unable to select a channel to which I want to upload, because none appears in the drop-down list of channels. I do in fact have 3 channels linked to this account, which do exist and appear elsewhere in the instance.

### Steps to reproduce

1. Go to upload page
2. Select a file to upload
3. Try to select a channel from the channel list
4. You are unable to select a channel because none appear in the channel list.
5. You can proceed to the next page by clicking the Upload button
6. The upload doesn't start, because there is no channel selected

### Describe the expected behavior

I should be able to select one of the existing channels from the channel list.

### Additional information

* PeerTube instance: 
  * URL: video.lqdn.fr
  * Version: 4.2
  * NodeJS version: 
  * Ffmpeg version:

* Browser name, version and platforms on which you could reproduce the bug:
* Link to browser console log if relevant:
* Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`):

**Comment by Chocobozzz** [comment]
Hello,

Have you followed https://github.com/Chocobozzz/PeerTube/blob/develop/CHANGELOG.md important notes?

**Comment by nono-lqdn** [comment]
Hello,

Thanks for your tips, the issue has been fixed on our instance ! <3

**Comment by nono-lqdn** [comment]
For reference, the bugs was the following ;

```
Cannot process channel avatar La Quadrature du Net Error
    at Query.run (/var/www/peertube/versions/peertube-v4.2.0/node_modules/sequelize/lib/dialects/postgres/query.js:50:25)
    at /var/www/peertube/versions/peertube-v4.2.0/node_modules/sequelize/lib/sequelize.js:313:28
    at async PostgresQueryInterface.update (/var/www/peertube/versions/peertube-v4.2.0/node_modules/sequelize/lib/dialects/abstract/query-interface.js:344:12)
    at async ActorImageModel.save (/var/www/peertube/versions/peertube-v4.2.0/node_modules/sequelize/lib/model.js:2424:35) {
  name: 'SequelizeUniqueConstraintError',
  errors: [],
  parent: error: la valeur d'une clé dupliquée rompt la contrainte unique « actor_image_actor_id_type_width »
      at Parser.parseErrorMessage (/var/www/peertube/versions/peertube-v4.2.0/node_modules/pg-protocol/dist/parser.js:287:98)
      at Parser.handlePacket (/var/www/peertube/versions/peertube-v4.2.0/node_modules/pg-protocol/dist/parser.js:126:29)
      at Parser.parse (/var/www/peertube/versions/peertube-v4.2.0/node_modules/pg-protocol/dist/parser.js:39:38)
      at Socket.<anonymous> (/var/www/peertube/versions/peertube-v4.2.0/node_modules/pg-protocol/dist/index.js:11:42)
      at Socket.emit (events.js:400:28)
      at Socket.emit (domain.js:475:12)
      at addChunk (internal/streams/readable.js:293:12)
      at readableAddChunk (internal/streams/readable.js:267:9)
      at Socket.Readable.push (internal/streams/readable.js:206:10)
      at TCP.onStreamRead (internal/stream_base_commons.js:188:23) {
    length: 284,
    severity: 'ERREUR',
    code: '23505',
    detail: 'La clé « ("actorId", type, width)=(3824, 1, 120) » existe déjà.',
    hint: undefined,
    position: undefined,
    internalPosition: undefined,
    internalQuery: undefined,
    where: undefined,
    schema: 'public',
    table: 'actorImage',
    column: undefined,
    dataType: undefined,
    constraint: 'actor_image_actor_id_type_width',
    file: 'nbtinsert.c',
    line: '656',
    routine: '_bt_check_unique',
    sql: 'UPDATE "actorImage" SET "width"=$1,"height"=$2,"updatedAt"=$3 WHERE "id" = $4',
    parameters: [ 120, 120, '2022-06-14 20:00:53.982 +00:00', 6023 ]
  },
  original: error: la valeur d'une clé dupliquée rompt la contrainte unique « actor_image_actor_id_type_width »
      at Parser.parseErrorMessage (/var/www/peertube/versions/peertube-v4.2.0/node_modules/pg-protocol/dist/parser.js:287:98)
      at Parser.handlePacket (/var/www/peertube/versions/peertube-v4.2.0/node_modules/pg-protocol/dist/parser.js:126:29)
      at Parser.parse (/var/www/peertube/versions/peertube-v4.2.0/node_modules/pg-protocol/dist/parser.js:39:38)
      at Socket.<anonymous> (/var/www/peertube/versions/peertube-v4.2.0/node_modules/pg-protocol/dist/index.js:11:42)
      at Socket.emit (events.js:400:28)
      at Socket.emit (domain.js:475:12)
      at addChunk (internal/streams/readable.js:293:12)
      at readableAddChunk (internal/streams/readable.js:267:9)
      at Socket.Readable.push (internal/streams/readable.js:206:10)
      at TCP.onStreamRead (internal/stream_base_commons.js:188:23) {
    length: 284,
    severity: 'ERREUR',
    code: '23505',
    detail: 'La clé « ("actorId", type, width)=(3824, 1, 120) » existe déjà.',
    hint: undefined,
    position: undefined,
    internalPosition: undefined,
    internalQuery: undefined,
    where: undefined,
    schema: 'public',
    table: 'actorImage',
    column: undefined,
    dataType: undefined,
    constraint: 'actor_image_actor_id_type_width',
    file: 'nbtinsert.c',
    line: '656',
    routine: '_bt_check_unique',
    sql: 'UPDATE "actorImage" SET "width"=$1,"height"=$2,"updatedAt"=$3 WHERE "id" = $4',
    parameters: [ 120, 120, '2022-06-14 20:00:53.982 +00:00', 6023 ]
  },
  fields: {},
  sql: 'UPDATE "actorImage" SET "width"=$1,"height"=$2,"updatedAt"=$3 WHERE "id" = $4'
}
Filling size of avatars of technopolice.
Processing technopolice.
[video.lqdn.fr:443] 2022-06-14 22:00:54.050 info: Creating job to update actor https://video.lqdn.fr/accounts/technopolice.
Generation finished!
``
