### ISSUE TITLE
activitypub-http-broadcast views jamming up on v4.2

### ISSUE THREAD

**Issue by Master-Minder** [Chocobozzz/PeerTube#5053]
### Describe the current behavior

We recently upgraded form v4.0 to v4.2 and noticed that the activitypub-http-broadcast jobs with contextType View are jamming up when there is a lot of traffic, to a point where the entire site gets slowed down due to redis beeing jam packed > 1 Mio keys.
This issue never occured to us on v4.0 and we had no change in hardware, ISP, or viewership recently.

### Steps to reproduce

1. Many concurrent views > 10k
2. Follow job queue building up

### Describe the expected behavior

Not sure if this is a bug that now somehow creates multiple requests per view now or if it is a general max troughput issue in the code, but since it didn't happen in v4.0 a possible fix might be rolling it back to that point, or bundeling view distribution, that not for every single view a a job is created but for every 10 or so.

If it is not fixable, it would be great to get at least a MAX_COUNT_OF_JOB_TYPE setting implemented, which when exceeded simply discards new job creation of that type, since site stability is more important than view count distribution.

### Additional information

* PeerTube instance:
  * URL: https://gegenstimme.tv/
  * Version: 4.2
  * NodeJS version: 14.19.1
  * Ffmpeg version: 4.1.8-0+deb10u1

**Comment by Chocobozzz** [comment]
Hello,

> to a point where the entire site gets slowed down due to redis beeing jam packed > 1 Mio keys

I'm not sure to understand why the website is slowed down. Is it because peertube spend all its time to insert data in redis or is it redis that has some issues to insert the keys?

> Many concurrent views > 10k

For my curiosity, how do you achieve to have 10k concurrent viewers with your peertube instance that has disabled P2P? Do you use a CDN or S3?

**Comment by Master-Minder** [comment]
The frontend performance issues got reported by a couple users as well as one of the major content creators.
Additionally the access to pages is timing out e.g. admin/system/jobs becomes unaccessable or at least taking ages to load. 

What we tried yesterday is adjusting some value in /dist/server/initializers/constants.js
- LINE 145: changing the TTL for activitypub-http-broadcast from 10 minutes to 1 minute
- LINE 177: changing BROADCAST_CONCURRENCY from 30 to 100
- LINE 193: changing JOB_COMPLETED_LIFETIME from 2 days to 1 hour

This resulted at least in some lower numbers around 200k waiting at peak, which at first decreased again after peak hours, but than started increasing again over a certain threshold and did not manage to catch up again without a redis flush.

**Comment by Chocobozzz** [comment]
Can you paste some of these jobs content?

**Comment by Master-Minder** [comment]
Sure. The once building up the queue are all of contextType view.
`{
  "uris": [
    "https://peertube.ch/inbox",
    "https://serv3.wiki-tube.de/inbox",
    "https://video.ploud.jp/inbox"
  ],
  "signatureActorId": 1,
  "body": {
    "to": [
      "https://www.w3.org/ns/activitystreams#Public",
      "https://gegenstimme.tv/video-channels/auf1.tv/followers",
      "https://gegenstimme.tv/accounts/peertube/followers",
      "https://gegenstimme.tv/accounts/auf1tv/followers"
    ],
    "cc": [],
    "id": "https://gegenstimme.tv/accounts/peertube/views/videos/30901/389b6286086ebbd93b22aa9df065d7c480e4ef62315965ff3daba55b11c49a3b",
    "type": "View",
    "actor": "https://gegenstimme.tv/accounts/peertube",
    "object": "https://gegenstimme.tv/videos/watch/a1d11c77-00d6-4242-956c-e85481a9e948",
    "expires": "2022-06-16T15:43:09.416Z"
  },
  "contextType": "View"
}`

**Comment by Master-Minder** [comment]
If at hand a downgrade script to 4.1.1 or 4.0 would be great, or instructions for db adjustments so that 4.1.1 or 4.0 will run again. So we could switch back at least for the time beeing, since the issue seems to get worse and manual

**Comment by Master-Minder** [comment]
Additional we found that even now during night time, where we have close to 0 views, in the warning log there are tons of those reccutring over and over again for the same video every 5 seconds, but are not limited to only that video, but multiple videos.
`warn[16.6.2022, 22:07:17] Too much watch section to store for a viewer, skipping this one
{
  "currentTime": 2661,
  "tags": [
    "views",
    "4b7bae73-a2ca-4590-8f15-3147c6179f3e"
  ]
}`

**Comment by Chocobozzz** [comment]
Could you try https://github.com/Chocobozzz/PeerTube/commit/f27b7a750f1876632e84d594608d3d64ce974efc?

**Comment by Master-Minder** [comment]
We tried building it on our test environment, but the build:server command crashes with the error below and the build:client seems to get stuck in an infinit loop. Keept it running for approx. 6 hours.

`0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'run', 'build:server' ]
2 info using npm@6.14.17
3 info using node@v14.19.2
4 verbose run-script [ 'prebuild:server', 'build:server', 'postbuild:server' ]
5 info lifecycle peertube@4.2.0~prebuild:server: peertube@4.2.0
6 info lifecycle peertube@4.2.0~build:server: peertube@4.2.0
7 verbose lifecycle peertube@4.2.0~build:server: unsafe-perm in lifecycle true
8 verbose lifecycle peertube@4.2.0~build:server: PATH: /usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/var/www/peertube/versions/peertube-dev/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
9 verbose lifecycle peertube@4.2.0~build:server: CWD: /var/www/peertube/versions/peertube-dev
10 silly lifecycle peertube@4.2.0~build:server: Args: [ '-c', 'bash ./scripts/build/server.sh' ]
11 silly lifecycle peertube@4.2.0~build:server: Returned: code: 2  signal: null
12 info lifecycle peertube@4.2.0~build:server: Failed to exec build:server script
13 verbose stack Error: peertube@4.2.0 build:server: `bash ./scripts/build/server.sh`
13 verbose stack Exit status 2
13 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:400:28)
13 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:400:28)
13 verbose stack     at maybeClose (internal/child_process.js:1088:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:296:5)
14 verbose pkgid peertube@4.2.0
15 verbose cwd /var/www/peertube/versions/peertube-dev
16 verbose Linux 4.19.0-14-cloud-amd64
17 verbose argv "/usr/bin/node" "/usr/bin/npm" "run" "build:server"
18 verbose node v14.19.2
19 verbose npm  v6.14.17
20 error code ELIFECYCLE
21 error errno 2
22 error peertube@4.2.0 build:server: `bash ./scripts/build/server.sh`
22 error Exit status 2
23 error Failed at the peertube@4.2.0 build:server script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 2, true ]`

**Comment by Alterak** [comment]
In version 4.2.0, I also had similar errors. There are a lot of them

```
error[20.06.2022, 19:34:20] Error in controller.
{
  "err": "HTTPError: Response code 404 (Not Found)\n    at Request._onResponseBase (/var/www/peertube/versions/peertube-v4.2.0/node_modules/got/dist/source/core/index.js:905:31)\n    at Request._onResponse (/var/www/peertube/versions/peertube-v4.2.0/node_modules/got/dist/source/core/index.js:940:24)\n    at ClientRequest.<anonymous> (/var/www/peertube/versions/peertube-v4.2.0/node_modules/got/dist/source/core/index.js:954:23)\n    at Object.onceWrapper (events.js:520:26)\n    at ClientRequest.emit (events.js:412:35)\n    at ClientRequest.emit (domain.js:475:12)\n    at ClientRequest.origin.emit (/var/www/peertube/versions/peertube-v4.2.0/node_modules/@szmarczak/http-timer/dist/source/index.js:43:20)\n    at HTTPParser.parserOnIncomingClient (_http_client.js:647:27)\n    at HTTPParser.parserOnHeadersComplete (_http_common.js:127:17)\n    at TLSSocket.socketOnData (_http_client.js:515:22)\n    at TLSSocket.emit (events.js:400:28)\n    at TLSSocket.emit (domain.js:475:12)\n    at addChunk (internal/streams/readable.js:293:12)\n    at readableAddChunk (internal/streams/readable.js:267:9)\n    at TLSSocket.Readable.push (internal/streams/readable.js:206:10)\n    at TLSWrap.onStreamRead (internal/stream_base_commons.js:188:23)"
}
error[20.06.2022, 19:48:28] Error in controller.
{
  "err": "RequestError: Timeout awaiting 'request' for 30000ms\n    at ClientRequest.<anonymous> (/var/www/peertube/versions/peertube-v4.2.0/node_modules/got/dist/source/core/index.js:962:65)\n    at Object.onceWrapper (events.js:520:26)\n    at ClientRequest.emit (events.js:412:35)\n    at ClientRequest.emit (domain.js:475:12)\n    at ClientRequest.origin.emit (/var/www/peertube/versions/peertube-v4.2.0/node_modules/@szmarczak/http-timer/dist/source/index.js:43:20)\n    at TLSSocket.socketErrorListener (_http_client.js:475:9)\n    at TLSSocket.emit (events.js:400:28)\n    at TLSSocket.emit (domain.js:475:12)\n    at emitErrorNT (internal/streams/destroy.js:106:8)\n    at emitErrorCloseNT (internal/streams/destroy.js:74:3)\n    at processTicksAndRejections (internal/process/task_queues.js:82:21)\n    at Timeout.timeoutHandler [as _onTimeout] (/var/www/peertube/versions/peertube-v4.2.0/node_modules/got/dist/source/core/utils/timed-out.js:36:25)\n    at listOnTimeout (internal/timers.js:559:11)\n    at processTimers (internal/timers.js:500:7)"
}
```

There are still a lot of such mistakes

```
error[20.06.2022, 14:10:42] Cannot add shares of video 72d8ad2f-4073-4e6a-86a3-db385fec368c.
{
  "err": {
    "stack": "RequestError: Timeout awaiting 'request' for 7000ms\n    at ClientRequest.<anonymous> (/var/www/peertube/versions/peertube-v4.2.0/node_modules/got/dist/source/core/index.js:962:65)\n    at Object.onceWrapper (events.js:520:26)\n    at ClientRequest.emit (events.js:412:35)\n    at ClientRequest.emit (domain.js:475:12)\n    at ClientRequest.origin.emit (/var/www/peertube/versions/peertube-v4.2.0/node_modules/@szmarczak/http-timer/dist/source/index.js:43:20)\n    at TLSSocket.socketErrorListener (_http_client.js:475:9)\n    at TLSSocket.emit (events.js:400:28)\n    at TLSSocket.emit (domain.js:475:12)\n    at emitErrorNT (internal/streams/destroy.js:106:8)\n    at emitErrorCloseNT (internal/streams/destroy.js:74:3)\n    at processTicksAndRejections (internal/process/task_queues.js:82:21)\n    at Timeout.timeoutHandler [as _onTimeout] (/var/www/peertube/versions/peertube-v4.2.0/node_modules/got/dist/source/core/utils/timed-out.js:36:25)\n    at listOnTimeout (internal/timers.js:559:11)\n    at processTimers (internal/timers.js:500:7)",
    "message": "Timeout awaiting 'request' for 7000ms",
    "name": "TimeoutError"
  },
  "rootUrl": "https://diode.zone/videos/watch/72d8ad2f-4073-4e6a-86a3-db385fec368c/announces",
  "tags": [
    "ap",
    "video",
    "72d8ad2f-4073-4e6a-86a3-db385fec368c",
    "https://diode.zone/videos/watch/72d8ad2f-4073-4e6a-86a3-db385fec368c"
  ]
}
```

And these are

```
error[20.06.2022, 12:56:26] Cannot add comments of video 013e7fac-e4c3-4cbf-adff-aaa54776c55c.
{
  "err": {
    "stack": "RequestError: Timeout awaiting 'request' for 7000ms\n    at ClientRequest.<anonymous> (/var/www/peertube/versions/peertube-v4.2.0/node_modules/got/dist/source/core/index.js:962:65)\n    at Object.onceWrapper (events.js:520:26)\n    at ClientRequest.emit (events.js:412:35)\n    at ClientRequest.emit (domain.js:475:12)\n    at ClientRequest.origin.emit (/var/www/peertube/versions/peertube-v4.2.0/node_modules/@szmarczak/http-timer/dist/source/index.js:43:20)\n    at TLSSocket.socketErrorListener (_http_client.js:475:9)\n    at TLSSocket.emit (events.js:400:28)\n    at TLSSocket.emit (domain.js:475:12)\n    at emitErrorNT (internal/streams/destroy.js:106:8)\n    at emitErrorCloseNT (internal/streams/destroy.js:74:3)\n    at processTicksAndRejections (internal/process/task_queues.js:82:21)\n    at Timeout.timeoutHandler [as _onTimeout] (/var/www/peertube/versions/peertube-v4.2.0/node_modules/got/dist/source/core/utils/timed-out.js:36:25)\n    at listOnTimeout (internal/timers.js:559:11)\n    at processTimers (internal/timers.js:500:7)",
    "message": "Timeout awaiting 'request' for 7000ms",
    "name": "TimeoutError"
  },
  "rootUrl": "https://diode.zone/videos/watch/013e7fac-e4c3-4cbf-adff-aaa54776c55c/comments",
  "tags": [
    "ap",
    "video",
    "013e7fac-e4c3-4cbf-adff-aaa54776c55c",
    "https://diode.zone/videos/watch/013e7fac-e4c3-4cbf-adff-aaa54776c55c"
  ]
}
```

And there are also such errors

```
error[20.06.2022, 10:42:51] Error in controller.
{
  "err": "TypeError: Cannot read property 'url' of null\n    at VideoPlaylistElementModel.toActivityPubObject (/var/www/peertube/versions/peertube-v4.2.0/dist/server/models/video/video-playlist-element.js:208:29)\n    at videoPlaylistElementController (/var/www/peertube/versions/peertube-v4.2.0/dist/server/controllers/activitypub/client.js:241:39)\n    at Layer.handle [as handle_request] (/var/www/peertube/versions/peertube-v4.2.0/node_modules/express/lib/router/layer.js:95:5)\n    at next (/var/www/peertube/versions/peertube-v4.2.0/node_modules/express/lib/router/route.js:137:13)\n    at wrapper (/var/www/peertube/versions/peertube-v4.2.0/node_modules/async/dist/async.js:271:20)\n    at replenish (/var/www/peertube/versions/peertube-v4.2.0/node_modules/async/dist/async.js:441:29)\n    at iterateeCallback (/var/www/peertube/versions/peertube-v4.2.0/node_modules/async/dist/async.js:430:21)\n    at /var/www/peertube/versions/peertube-v4.2.0/node_modules/async/dist/async.js:327:20\n    at /var/www/peertube/versions/peertube-v4.2.0/dist/server/middlewares/async.js:10:52\n    at /var/www/peertube/versions/peertube-v4.2.0/dist/server/middlewares/validators/videos/video-playlists.js:216:16\n    at Generator.next (<anonymous>)\n    at fulfilled (/var/www/peertube/versions/peertube-v4.2.0/node_modules/tslib/tslib.js:114:62)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (internal/process/task_queues.js:95:5)"
}

```

**Comment by Chocobozzz** [comment]
@Master-Minder We released 4.2.1 with the fix. Could you try it?
