### ISSUE TITLE
Duplicate videoTag_pkey

### ISSUE THREAD

**Issue by diazepan** [Chocobozzz/PeerTube#5072]
### Describe the current behavior

When I import a video from youtube, most of the times there's no problem. But sometimes I have this error coming out

duplicate key violates unique constraint «videoTag_pkey»

It only happens when I import videos. If I download them with youtube-dl and upload them, I have no problem.

### Steps to reproduce

1. Choose Import with URL
2. Add video URL and click in import
3. An error message appears saying "duplicate key violates unique constraint «videoTag_pkey»"
[imagen](https://user-images.githubusercontent.com/49599198/174926817-2c722080-5a36-4dfa-b7c1-9b133c211e4f.png)

**Comment by Chocobozzz** [comment]
Hello,

Could you paste server logs please?

**Comment by Chocobozzz** [comment]
Thanks, can you paste the video you try to import?

**Comment by diazepan** [comment]
https://www.youtube.com/watch?v=ooeRA8ZhcoQ

**Comment by Chocobozzz** [comment]
Thanks! It should be fixed by https://github.com/Chocobozzz/PeerTube/commit/f2623febd8b7b818e47d995ae59f4f1d2f37961b

**Comment by drzraf** [comment]
I'm experiencing the same problem (although with a slightly distinct message) with v5.0.0 during (retried) sync of youtube channel (multiple videos failed during previous attempts)

```
2022-12-28 13:42:54.819 error: Failed to import channel it {
  "err": {
    "stack": "SequelizeUniqueConstraintError: Validation error\n    at Query.formatError (/app/node_modules/sequelize/lib/dialects/postgres/query.js:272:18)\n    at Query.run (/app/node_modules/sequelize/lib/dialects/postgres/query.js:84:20)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async /app/node_modules/sequelize/lib/sequelize.js:314:16\n    at async PostgresQueryInterface.insert (/app/node_modules/sequelize/lib/dialects/abstract/query-interface.js:308:21)\n    at async TagModel.save (/app/node_modules/sequelize/lib/model.js:2432:35)\n    at async Function.create (/app/node_modules/sequelize/lib/model.js:1344:12)\n    at async Function.findOrCreate (/app/node_modules/sequelize/lib/model.js:1404:25)\n    at async Promise.all (index 2)",
    "message": "Validation error",
    "name": "SequelizeUniqueConstraintError",
    "errors": [
      {
        "message": "name must be unique",
        "type": "unique violation",
        "path": "name",
        "value": "sacrifici animali",
        "origin": "DB",
        "instance": {
          "id": null,
          "name": "sacrifici animali"
        },
        "validatorKey": "not_unique",
        "validatorName": null,
        "validatorArgs": []
      }
    ],
    "parent": {
      "sql": "CREATE OR REPLACE FUNCTION pg_temp.testfunc(OUT response \"tag\", OUT sequelize_caught_exception text) RETURNS RECORD AS $func_c0aa0b2c86024a8b884fa4cb70ca8d87$ BEGIN INSERT INTO \"tag\" (\"id\",\"name\") VALUES (DEFAULT,'sacrifici animali') RETURNING * INTO response; EXCEPTION WHEN unique_violation THEN GET STACKED DIAGNOSTICS sequelize_caught_exception = PG_EXCEPTION_DETAIL; END $func_c0aa0b2c86024a8b884fa4cb70ca8d87$ LANGUAGE plpgsql; SELECT (testfunc.response).\"id\", (testfunc.response).\"name\", testfunc.sequelize_caught_exception FROM pg_temp.testfunc(); DROP FUNCTION IF EXISTS pg_temp.testfunc();",
      "code": "23505",
      "detail": "Key (name)=(sacrifici animali) already exists."
    },
    "fields": {
      "name": "sacrifici animali"
    },
    "sql": "CREATE OR REPLACE FUNCTION pg_temp.testfunc(OUT response \"tag\", OUT sequelize_caught_exception text) RETURNS RECORD AS $func_c0aa0b2c86024a8b884fa4cb70ca8d87$ BEGIN INSERT INTO \"tag\" (\"id\",\"name\") VALUES (DEFAULT,'sacrifici animali') RETURNING * INTO response; EXCEPTION WHEN unique_violation THEN GET STACKED DIAGNOSTICS sequelize_caught_exception = PG_EXCEPTION_DETAIL; END $func_c0aa0b2c86024a8b884fa4cb70ca8d87$ LANGUAGE plpgsql; SELECT (testfunc.response).\"id\", (testfunc.response).\"name\", testfunc.sequelize_caught_exception FROM pg_temp.testfunc(); DROP FUNCTION IF EXISTS pg_temp.testfunc();"
  }
}
```
