### ISSUE TITLE
Job queue processing stuck/crashed

### ISSUE THREAD

**Issue by emansom** [Chocobozzz/PeerTube#5213]
### Describe the current behavior

Job queues stopped processing while PeerTube was airgapped.

![Schermafdruk van 2022-08-23 19-06-41](https://user-images.githubusercontent.com/981494/186237749-d5f7b5a0-94b1-43bd-963b-5d86641d1d37.png)

![Schermafdruk van 2022-08-23 19-07-21](https://user-images.githubusercontent.com/981494/186237773-611aa3c4-39cc-45d4-a839-dd555db20c71.png)

### Steps to reproduce

1. Have a queue full of transcoding jobs, ActivityPub broadcasts etc.
2. Airgap the PeerTube instance by running it with a internal docker network.
3. Queue processing stuck/crashed.

### Describe the expected behavior

Job queues not crashing while airgapped.

### Additional information

* PeerTube instance:
  * URL: https://pcbu.nl
  * Version: 4.2.2
  * NodeJS version: v16.17.0
  * Ffmpeg version: 4.3.4-0+deb11u1

* Browser name, version and platforms on which you could reproduce the bug: Firefox
* Link to browser console log if relevant:
* Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`):
```
{
  "err": "TypeError: Cannot read properties of null (reading 'timestamp')\n    at /app/dist/server/lib/job-queue/job-queue.js:169:24\n    at Array.sort (<anonymous>)\n    at JobQueue.<anonymous> (/app/dist/server/lib/job-queue/job-queue.js:168:21)\n    at Generator.next (<anonymous>)\n    at fulfilled (/app/node_modules/tslib/tslib.js:114:62)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)"
}
```

**Comment by emansom** [comment]
There were still about 7 videos in the backlog. Visually they seem to have disappeared now.

**Comment by emansom** [comment]
Worked around it for the time being by manually adding all transcoding jobs again, using the following steps:

1. Browsed to the `In my library > Videos` page from the side panel, scrolled all the way down
2. Ctrl + F and searched for "Waiting on transcoding"
3. Opened each video in a private browser window, then copied the last path from the URL containing the ID.
4. Executed the [`create-transcoding-job` server command](https://docs.joinpeertube.org/maintain-tools?id=create-transcoding-jobjs) appending for each copied video ID.

**Comment by emansom** [comment]
ActivityPub broadcasts to other follower instances are still lost.

Videos that were published during the airgapped window are not appearing on any of the follower instances. 

Is there a way to retrigger those?

**Comment by Chocobozzz** [comment]
Hello,

I think this will be fixed by the next peertube version where we moved from https://github.com/OptimalBits/bull/ to https://github.com/taskforcesh/bullmq
