### ISSUE TITLE
CLI: Move to object storage error: Cannot use same state 6

### ISSUE THREAD

**Issue by Nalem14** [Chocobozzz/PeerTube#5295]
### Describe the current behavior

When using the CLI tool to move all videos to object storage, I get an error (always on the same video when I re-run the script)

### Steps to reproduce

1. Run $ sudo -u peertube NODE_CONFIG_DIR=/var/www/peertube/config NODE_ENV=production npm run create-move-video-storage-job -- --to-object-storage --all-videos

### Describe the expected behavior

No error. Also skip video move on error and continue moving the next video

### Additional information

* PeerTube instance:
  * URL:
  * Version: 4.3
  * NodeJS version: 16
  * Ffmpeg version:

* Browser name, version and platforms on which you could reproduce the bug:
* Link to browser console log if relevant:
* Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`):

```
Processing video Пансионат Селена - Отзыв 2022. Питание, номер, пляж, бассейн, территория.
Error: Cannot use same state 6
    at VideoModel.<anonymous> (/var/www/peertube/versions/peertube-v4.3.0/dist/server/models/video/video.js:955:23)
    at Generator.next (<anonymous>)
    at /var/www/peertube/versions/peertube-v4.3.0/node_modules/tslib/tslib.js:118:75
    at new Promise (<anonymous>)
    at Object.__awaiter (/var/www/peertube/versions/peertube-v4.3.0/node_modules/tslib/tslib.js:114:16)
    at VideoModel.setNewState (/var/www/peertube/versions/peertube-v4.3.0/dist/server/models/video/video.js:953:24)
    at /var/www/peertube/versions/peertube-v4.3.0/dist/server/lib/video-state.js:61:21
    at Generator.next (<anonymous>)
    at fulfilled (/var/www/peertube/versions/peertube-v4.3.0/node_modules/tslib/tslib.js:115:62)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
^C
```

**Comment by Nalem14** [comment]
By updating all video state from 6 to 1 in database resolved the issue.
But it would be nice if the script continue with only a warning, without crashing when this occure

**Comment by Chocobozzz** [comment]
Thanks, should be fixed by https://github.com/Chocobozzz/PeerTube/commit/690bad52e186a0111359062743d9638b911026f2
