### ISSUE TITLE
Can´t reach peertube after upgrade to v4.3.0

### ISSUE THREAD

**Issue by Stormkoopa** [Chocobozzz/PeerTube#5304]
### Describe the problem

After upgrading my peertube instance from v4.2.2 to v4.3.0 I get a HTTP 500 Error whenever I try to reach my instance. When I run journalctl -feu peertube during startup I see the following error:

Sep 26 14:54:22 gerlnxptube peertube[1030]: "stack": "Error: Command failed: yarn install --pure-lockfile\nError: EACCES: permission denied, open '/home/peertube/.config/yarn'\n at Object.openSync (node:fs:599:3)\n at readFileSync (node:fs:467:35)\n at /usr/local/lib/node_modules/yarn/lib/cli.js:97395:58\n at Array.map ()\n at parseRcPaths (/usr/local/lib/node_modules/yarn/lib/cli.js:97393:78)\n at Object.findRc (/usr/local/lib/node_modules/yarn/lib/cli.js:97407:10)\n at getRcConfigForCwd (/usr/local/lib/node_modules/yarn/lib/cli.js:56965:74)\n at /usr/local/lib/node_modules/yarn/lib/cli.js:88756:56\n at Generator.next ()\n at step (/usr/local/lib/node_modules/yarn/lib/cli.js:310:30)\n\n at ChildProcess.exithandler (node:child_process:412:12)\n at ChildProcess.emit (node:events:513:28)\n at maybeClose (node:internal/child_process:1091:16)\n at Socket. (node:internal/child_process:449:11)\n at Socket.emit (node:events:513:28)\n at Pipe. (node:net:313:12)"

But there is no such directory. I´ve only upgraded my peertube instance via the upgrade script.

### Additional information

* PeerTube instance URL: not public
* PeerTube version: 4.3.0
* NodeJS version: 18.9.1
* Ffmpeg version: 4.2.7
* Redis version: 5.0.7
* PostgreSQL version: 12.12

**Comment by Chocobozzz** [comment]
Please don't open duplicate issues: https://github.com/Chocobozzz/PeerTube/issues/5297
