### ISSUE TITLE
Playback issue in nightly builds

### ISSUE THREAD

**Issue by Alterak** [Chocobozzz/PeerTube#5379]
### Describe the current behavior

Problem started about 3 days ago, starts in nightly build **peertube-nightly-2022-10-24** but it is not exactly.

Embedded videos on sites stopped turning, but the sound turned.
A few seconds after playback starts, a reproducible error

![1](https://user-images.githubusercontent.com/11453567/198210835-c279fadc-669d-4ab2-a38d-25995efe35a9.png)

### Additional information

* PeerTube instance:
  * URL: https://peervideo.ru
  * Version: 4.3.0-nightly-2022-10-27
  * NodeJS version: v16.17.1
  * Ffmpeg version: 4.3.4-0+deb11u1

* Browser name, version and platforms on which you could reproduce the bug: Firefox v106.0.2 (64 bit)
* Link to browser console log if relevant:

![2](https://user-images.githubusercontent.com/11453567/198211892-bbfae6ee-e934-49c0-a51f-3b3842317b29.png)

* Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`):

```
warn[27.10.2022, 09:49:00] Warning in tracker.

{
  "err": {
    "stack": "Error: Unknown infoHash f58a7a04f3a086eb36d79ec73fd8db1e20524ed8 requested by ip 211.120.236.193\n    at Server.<anonymous> (/var/www/peertube/versions/peertube-nightly-2022-10-27/dist/server/controllers/tracker.js:52:20)\n    at Generator.next (<anonymous>)\n    at fulfilled (/var/www/peertube/versions/peertube-nightly-2022-10-27/node_modules/tslib/tslib.js:115:62)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)",
    "message": "Unknown infoHash f58a7a04f3a086eb36d79ec73fd8db1e20524ed8 requested by ip 211.120.236.193"
  }
}

warn[27.10.2022, 09:49:01] Client log: Hls.js is not supported in this browser!

{
  "tags": [
    "client"
  ],
  "userAgent": "Mozilla/5.0 (iPhone; CPU iPhone OS 16_0 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.0 YaBrowser/22.9.1.590.10 SA/3 Mobile/15E148 Safari/604.1",
  "url": "https://peervideo.ru/videos/embed/349d4a4f-4de3-49e0-91fa-579e4f13e736?warningTitle=0&peertubeLink=0&p2p=0"
}

warn[27.10.2022, 09:49:01] Client log: HLS.js does not seem to be supported. Try to fallback to built in HLS.

{
  "tags": [
    "client"
  ],
  "userAgent": "Mozilla/5.0 (iPhone; CPU iPhone OS 16_0 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.0 YaBrowser/22.9.1.590.10 SA/3 Mobile/15E148 Safari/604.1",
  "url": "https://peervideo.ru/videos/embed/349d4a4f-4de3-49e0-91fa-579e4f13e736?warningTitle=0&peertubeLink=0&p2p=0"
}

warn[27.10.2022, 09:49:10] Warning in tracker.

{
  "err": {
    "stack": "Error: Unknown infoHash 2cbe5fc6b79bb5c9215e7fa1fc9e3a0807ab5035 requested by ip 91.243.107.26\n    at Server.<anonymous> (/var/www/peertube/versions/peertube-nightly-2022-10-27/dist/server/controllers/tracker.js:52:20)\n    at Generator.next (<anonymous>)\n    at fulfilled (/var/www/peertube/versions/peertube-nightly-2022-10-27/node_modules/tslib/tslib.js:115:62)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)",
    "message": "Unknown infoHash 2cbe5fc6b79bb5c9215e7fa1fc9e3a0807ab5035 requested by ip 91.243.107.26"
  }
}
```

**Comment by Chocobozzz** [comment]
Thanks, should be fixed by https://github.com/Chocobozzz/PeerTube/commit/49e7e4d9ffd16cba7a721f6d3d3203decf4f4b2c
