### ISSUE TITLE
Error: Cannot compute FPS because 0 is lower than our minimum value 1

### ISSUE THREAD

**Issue by alejandrocobo** [Chocobozzz/PeerTube#5407]
### Describe the current behavior

When I try to convert to HLS only-audio clips, I get this error:

```
{   "type": "new-resolution-to-hls",   "videoUUID": "e4dc4de4-db93-4bde-a40d-3c743ef8e162",   "resolution": 2160,   "hasAudio": true,   "copyCodecs": false,   "isNewVideo": false,   "autoDeleteWebTorrentIfNeeded": false,   "isMaxQuality": false }
--
Error: Cannot compute FPS because 0 is lower than our minimum value 1     at computeFPS (.../versions/peertube-v4.3.0/dist/server/helpers/ffmpeg/ffprobe-utils.js:178:15)     at .../versions/peertube-v4.3.0/dist/server/helpers/ffmpeg/ffmpeg-vod.js:37:46     at Generator.next (<anonymous>)     at fulfilled (.../versions/peertube-v4.3.0/node_modules/tslib/tslib.js:115:62)     at runMicrotasks (<anonymous>)     at processTicksAndRejections (node:internal/process/task_queues:96:5)

```

The log about this specific job is this one:

```
error[13/11/2022, 10:33:50] Cannot execute job 1c368a59-088e-4fef-9efd-4d3c4d52fd23 in queue video-transcoding.

{
  "payload": {
    "type": "new-resolution-to-hls",
    "videoUUID": "e4dc4de4-db93-4bde-a40d-3c743ef8e162",
    "resolution": 2160,
    "hasAudio": true,
    "copyCodecs": false,
    "isNewVideo": false,
    "autoDeleteWebTorrentIfNeeded": false,
    "isMaxQuality": false
  },
  "err": {
    "stack": "Error: Cannot compute FPS because 0 is lower than our minimum value 1\n    at computeFPS (.../versions/peertube-v4.3.0/dist/server/helpers/ffmpeg/ffprobe-utils.js:178:15)\n    at .../versions/peertube-v4.3.0/dist/server/helpers/ffmpeg/ffmpeg-vod.js:37:46\n    at Generator.next (<anonymous>)\n    at fulfilled (.../versions/peertube-v4.3.0/node_modules/tslib/tslib.js:115:62)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)",
    "message": "Cannot compute FPS because 0 is lower than our minimum value 1"
  }
}
```

### Steps to reproduce

This is the faulty audio (there are several with the same issue uploaded by the same user): https://tubedu.org/w/ug7Vqokv56fLog9skxjr4h

### Describe the expected behavior

It should be able to convert to HLS.

### Additional information

* PeerTube instance:
  * Version: 4.3
  * NodeJS version: v16.15.1
  * Ffmpeg version: 4.3.4-0+deb11u1

Thanks.

**Comment by Chocobozzz** [comment]
Thanks, should be fixed by https://github.com/Chocobozzz/PeerTube/commit/44e702ded455c118f9908b70d25e7c7e5512abe9
