### ISSUE TITLE
Caprover one click app Installation Issue with iRedMail and SSL

### ISSUE THREAD

**Issue by davidleebooth** [Chocobozzz/PeerTube#5408]
### Describe the current behavior

iRedMail is the only other one click app for a mailserver in CapRover. It requires startTLS to connect. PeerTube requires the location of the CA file if it is self signed/let's encrypt and cannot connect to the mail server.

### Steps to reproduce

1. install ubuntu docker caprover
2. Install iRedMail and create an account
3. Install Peertube and use startTLS setting required by iRedMail
4. Cannot connect to mail server cannot retrieve password

### Describe the expected behavior

A field for the path to CA file if you are using iredmail in caprover app configs could be a fix? unsure of how to impalement that myself.

### Additional information

* PeerTube instance:
  * URL: video.davbot.media
  * Version: latest
  * NodeJS version: 8.10.0
  * Ffmpeg version: 4.1.8

* Browser name, version and platforms on which you could reproduce the bug:
* Link to browser console log if relevant:

2022-11-14T01:22:20.037409714Z [davbot.media:443] 2022-11-14 01:22:20.036 error: Failed to connect to SMTP mail.davbot.media:587. {
2022-11-14T01:22:20.037435589Z "err": {
2022-11-14T01:22:20.037439564Z "stack": "Error: self signed certificate\n at TLSSocket.onConnectSecure (_tls_wrap.js:1502:34)\n at TLSSocket.emit (events.js:314:20)\n at TLSSocket.EventEmitter.emit (domain.js:483:12)\n at TLSSocket._finishInit (_tls_wrap.js:937:8)\n at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:711:12)",
2022-11-14T01:22:20.037443884Z "message": "self signed certificate",
2022-11-14T01:22:20.037447304Z "code": "ESOCKET",
2022-11-14T01:22:20.037450694Z "command": "CONN"
2022-11-14T01:22:20.037454044Z }
2022-11-14T01:22:20.037457741Z }

* Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`):

**Comment by Chocobozzz** [comment]
https://github.com/Chocobozzz/PeerTube/blob/develop/config/default.yaml#L78 is not what you're looking for?

**Comment by davidleebooth** [comment]
I did manage to find that. add it to the environment variables in caprover then set the path to the mail servers CA file in /captain/...  but returned no directory. I probably did not do this correctly, or do I need to keep a copy of the mail servers CA file in the peertube container and update as needed?

**Comment by Chocobozzz** [comment]
I'm sorry but I don't know CapRover.

But if you have a peertube container, yes the file should be located in it.
