### ISSUE TITLE
Can't follow user or channel from Pleroma

### ISSUE THREAD

**Issue by davetapley** [Chocobozzz/PeerTube#5415]
### Describe the current behavior

When I try to follow a PeerTube user or channel from my Pleroma instance it stays stuck in 'Awaiting approval':

<img width="610" alt="Screen Shot 2022-11-17 at 2 51 44 PM" src="https://user-images.githubusercontent.com/48232/202567573-e95ea51e-8664-4143-9a47-4ad74ab480a4.png">

---

Also, as an aside: Is requiring approval for a follow something PeerTube even supports?
I assume not, and that whatever is happening is confusing Pleroma in to thinking that's what is happening.

### Steps to reproduce

1. Create PeerTube user / channel
2. Try to follow either from Pleroma instance
3. See 'Awaiting approval'.

### Describe the expected behavior

Don't see ''Awaiting approval'.

### Additional information

* PeerTube instance:
  * URL:
  * Version:
  * NodeJS version:
  * Ffmpeg version:

Server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`):

```
Nov 17 21:56:12 pleroma peertube[21999]: [video.nado.social:443] 2022-11-17 21:56:12.162 info: Fetching remote actor https://nado.social/users/dave.
Nov 17 21:56:12 pleroma peertube[21999]: [video.nado.social:443] 2022-11-17 21:56:12.228 warn: Cannot execute bound create with many retries. {
Nov 17 21:56:12 pleroma peertube[21999]:   "err": {
Nov 17 21:56:12 pleroma peertube[21999]:     "stack": "TypeError: Cannot read properties of undefined (reading 'name')\n    at /var/www/peertube/versions/peertube-v4.3.0/dist/server/lib/activitypub/actors/image.js:33:37\n    at Generator.next (<anonymous>)\n    at /var/www/peertube/versions/peertube-v4.3.0/node_modules/tslib/tslib.js:118:75\n    at new Promise (<anonymous>)\n    at Object.__awaiter (/var/www/peertube/versions/peertube-v4.3.0/node_modules/tslib/tslib.js:114:16)\n    at updateActorImages (/var/www/peertube/versions/peertube-v4.3.0/dist/server/lib/activitypub/actors/image.js:9:20)\n    at APActorCreator.<anonymous> (/var/www/peertube/versions/peertube-v4.3.0/dist/server/lib/activitypub/actors/shared/creator.js:64:50)\n    at Generator.next (<anonymous>)\n    at /var/www/peertube/versions/peertube-v4.3.0/node_modules/tslib/tslib.js:118:75\n    at new Promise (<anonymous>)\n    at Object.__awaiter (/var/www/peertube/versions/peertube-v4.3.0/node_modules/tslib/tslib.js:114:16)\n    at APActorCreator.setImageIfNeeded (/var/www/peertube/versions/peertube-v4.3.0/dist/server/lib/activitypub/actors/shared/creator.js:60:24)\n    at APActorCreator.<anonymous> (/var/www/peertube/versions/peertube-v4.3.0/dist/server/lib/activitypub/actors/shared/creator.js:26:28)\n    at Generator.next (<anonymous>)\n    at fulfilled (/var/www/peertube/versions/peertube-v4.3.0/node_modules/tslib/tslib.js:115:62)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)",
Nov 17 21:56:12 pleroma peertube[21999]:     "message": "Cannot read properties of undefined (reading 'name')"
Nov 17 21:56:12 pleroma peertube[21999]:   }
Nov 17 21:56:12 pleroma peertube[21999]: }
Nov 17 21:56:12 pleroma peertube[21999]: [video.nado.social:443] 2022-11-17 21:56:12.230 warn: Error in ActivityPub signature checker. {
Nov 17 21:56:12 pleroma peertube[21999]:   "err": {
Nov 17 21:56:12 pleroma peertube[21999]:     "stack": "TypeError: Cannot read properties of undefined (reading 'name')\n    at /var/www/peertube/versions/peertube-v4.3.0/dist/server/lib/activitypub/actors/image.js:33:37\n    at Generator.next (<anonymous>)\n    at /var/www/peertube/versions/peertube-v4.3.0/node_modules/tslib/tslib.js:118:75\n    at new Promise (<anonymous>)\n    at Object.__awaiter (/var/www/peertube/versions/peertube-v4.3.0/node_modules/tslib/tslib.js:114:16)\n    at updateActorImages (/var/www/peertube/versions/peertube-v4.3.0/dist/server/lib/activitypub/actors/image.js:9:20)\n    at APActorCreator.<anonymous> (/var/www/peertube/versions/peertube-v4.3.0/dist/server/lib/activitypub/actors/shared/creator.js:64:50)\n    at Generator.next (<anonymous>)\n    at /var/www/peertube/versions/peertube-v4.3.0/node_modules/tslib/tslib.js:118:75\n    at new Promise (<anonymous>)\n    at Object.__awaiter (/var/www/peertube/versions/peertube-v4.3.0/node_modules/tslib/tslib.js:114:16)\n    at APActorCreator.setImageIfNeeded (/var/www/peertube/versions/peertube-v4.3.0/dist/server/lib/activitypub/actors/shared/creator.js:60:24)\n    at APActorCreator.<anonymous> (/var/www/peertube/versions/peertube-v4.3.0/dist/server/lib/activitypub/actors/shared/creator.js:26:28)\n    at Generator.next (<anonymous>)\n    at fulfilled (/var/www/peertube/versions/peertube-v4.3.0/node_modules/tslib/tslib.js:115:62)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)",
Nov 17 21:56:12 pleroma peertube[21999]:     "message": "Cannot read properties of undefined (reading 'name')"
Nov 17 21:56:12 pleroma peertube[21999]:   }
Nov 17 21:56:12 pleroma peertube[21999]: }
Nov 17 21:56:12 pleroma peertube[21999]: [video.nado.social:443] 2022-11-17 21:56:12.231 info: 164.92.84.2 - - [17/Nov/2022:21:56:12 +0000] "POST /accounts/dave/inbox HTTP/1.0" 403 162 "-" "Pleroma 2.4.4; https://nado.social <admin@nado.social>"
```

**Comment by davetapley** [comment]
Maybe related:
- https://github.com/Chocobozzz/PeerTube/issues/1383

**Comment by Chocobozzz** [comment]
Hi,

Thanks for the issue. Seems to be a peertube bug, that should be fixed by https://github.com/Chocobozzz/PeerTube/commit/5800f354ccd4845d0b4bc212a0c53a0ff40edf82
