### ISSUE TITLE
Inspecting a task shows an SQL data binding error

### ISSUE THREAD

**Issue by emansom** [Chocobozzz/PeerTube#5419]
### Describe the current behavior

When browsing to the Admin > System > Tasks page and inspecting an individual task, this error popped up:

![afbeelding](https://user-images.githubusercontent.com/981494/202857769-f46f35b6-5ee6-4107-a963-f570d5c174e8.png)

### Steps to reproduce

1. No idea honestly. 🤷🏻 

### Describe the expected behavior

`:videoId` named replacement always being set in the SQL prepared statement?

### Additional information

* PeerTube instance:
  * URL: [pcbu.nl](https://pcbu.nl/)
  * Version: 4.3.0
  * Node.js version: v16.17.0
  * FFmpeg version: 4.3.4-0+deb11u1

* Error log:
```
Error: Named replacement ":videoId" has no entry in the replacement map.
    at injectReplacements (/app/node_modules/sequelize/lib/utils/sql.js:127:15)
    at Sequelize.query (/app/node_modules/sequelize/lib/sequelize.js:282:13)
    at VideosModelGetQuerySubBuilder.runQuery (/app/dist/server/models/shared/abstract-run-query.js:19:31)
    at VideosModelGetQuerySubBuilder.queryVideos (/app/dist/server/models/video/sql/video/video-model-get-query-builder.js:51:21)
    at VideoModelGetQueryBuilder.<anonymous> (/app/dist/server/models/video/sql/video/video-model-get-query-builder.js:20:40)
    at Generator.next (<anonymous>)
    at /app/node_modules/tslib/tslib.js:117:75
    at new Promise (<anonymous>)
    at Object.__awaiter (/app/node_modules/tslib/tslib.js:113:16)
    at VideoModelGetQueryBuilder.queryVideo (/app/dist/server/models/video/sql/video/video-model-get-query-builder.js:18:24)
    at Function.loadAndPopulateAccountAndServerAndTags (/app/dist/server/models/video/video.js:536:29)
    at Queue.<anonymous> (/app/dist/server/lib/job-queue/handlers/video-transcoding.js:28:48)
    at Generator.next (<anonymous>)
    at /app/node_modules/tslib/tslib.js:117:75
    at new Promise (<anonymous>)
    at Object.__awaiter (/app/node_modules/tslib/tslib.js:113:16)
    at Queue.processVideoTranscoding (/app/dist/server/lib/job-queue/handlers/video-transcoding.js:25:20)
    at handlers.<computed> (/app/node_modules/bull/lib/queue.js:697:42)
    at Queue.processJob (/app/node_modules/bull/lib/queue.js:1158:22)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

**Comment by emansom** [comment]
![afbeelding](https://user-images.githubusercontent.com/981494/202859604-6ee61900-be4f-4c96-af6a-28f8572d79ce.png)

Observed the same error on an active task.

**Comment by Chocobozzz** [comment]
Hello,

Please fill the `Additional information` template input, in particular the PeerTube version and instance URL questions.

**Comment by emansom** [comment]
> Hi! Are you running version 4.3.1? Is this happening for all video-transcoding jobs?

@kontrollanten 4.3.0 still.

> The function `loadAndPopulateAccountAndServerAndTags` is removed since 4.3.0, so by upgrading this may be solved.

@kontrollanten Will upgrade and report back. 👍🏻 

> Hello,
> 
> Please fill the `Additional information` template input, in particular the PeerTube version and instance URL questions.

@Chocobozzz Done.

**Comment by Chocobozzz** [comment]
It seems there is an issue with the job queue because it is said the job has been processed in November and finished in August :thinking:

**Comment by Chocobozzz** [comment]
Do you still have errors in your job queue @emansom?

**Comment by emansom** [comment]
> Do you still have errors in your job queue @emansom?

Haven't got around to updating yet.

**Comment by Chocobozzz** [comment]
Closing this issue, don't hesitate to comment if you still have it with newer PeerTube versions!
