### ISSUE TITLE
Upgrading Peertube Instance Failure

### ISSUE THREAD

**Issue by cgarwood82** [Chocobozzz/PeerTube#5422]
### Describe the problem

Following the documented upgrade steps, I cannot upgrade from peertube v4.2.0 -> v4.3.1. 

I've upgraded to Nodejs 18 and my version of redis is already 5.0.x. Kicking off the upgrade script completes successfully, but upon starting up the peertube, it continues to restart over and over again. Reviewing the logs, this looks to be the issue:

```
{
  "err": {
    "stack": "Error\n    at Query.run (/var/www/peertube/versions/peertube-v4.3.1/node_modules/sequelize/lib/dialects/postgres/query.js:50:25)\n    at /var/www/peertube/versions/peertube-v4.3.1/node_modules/sequelize/lib/sequelize.js:311:28\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async /var/www/peertube/versions/peertube-v4.3.1/node_modules/sequelize/lib/dialects/postgres/query-interface.js:117:76\n    at async PostgresQueryInterface.ensureEnums (/var/www/peertube/versions/peertube-v4.3.1/node_modules/sequelize/lib/dialects/postgres/query-interface.js:117:20)\n    at async ActorFollowModel.sync (/var/www/peertube/versions/peertube-v4.3.1/node_modules/sequelize/lib/model.js:944:7)\n    at async Sequelize.sync (/var/www/peertube/versions/peertube-v4.3.1/node_modules/sequelize/lib/sequelize.js:373:9)\n    at async Promise.all (index 0)",
    "message": "must be owner of type \"enum_actorFollow_state\"",
    "name": "SequelizeDatabaseError",
    "parent": {
      "stack": "error: must be owner of type \"enum_actorFollow_state\"\n    at Parser.parseErrorMessage (/var/www/peertube/versions/peertube-v4.3.1/node_modules/pg-protocol/dist/parser.js:287:98)\n    at Parser.handlePacket (/var/www/peertube/versions/peertube-v4.3.1/node_modules/pg-protocol/dist/parser.js:126:29)\n    at Parser.parse (/var/www/peertube/versions/peertube-v4.3.1/node_modules/pg-protocol/dist/parser.js:39:38)\n    at Socket.<anonymous> (/var/www/peertube/versions/peertube-v4.3.1/node_modules/pg-protocol/dist/index.js:11:42)\n    at Socket.emit (node:events:513:28)\n    at addChunk (node:internal/streams/readable:324:12)\n    at readableAddChunk (node:internal/streams/readable:297:9)\n    at Readable.push (node:internal/streams/readable:234:10)\n    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)",
      "message": "must be owner of type \"enum_actorFollow_state\"",
      "length": 106,
      "name": "error",
      "severity": "ERROR",
      "code": "42501",
      "file": "aclchk.c",
      "line": "3628",
      "routine": "aclcheck_error",
      "sql": "ALTER TYPE \"public\".\"enum_actorFollow_state\" ADD VALUE IF NOT EXISTS 'rejected' AFTER 'accepted'"
    },
    "original": {
      "stack": "error: must be owner of type \"enum_actorFollow_state\"\n    at Parser.parseErrorMessage (/var/www/peertube/versions/peertube-v4.3.1/node_modules/pg-protocol/dist/parser.js:287:98)\n    at Parser.handlePacket (/var/www/peertube/versions/peertube-v4.3.1/node_modules/pg-protocol/dist/parser.js:126:29)\n    at Parser.parse (/var/www/peertube/versions/peertube-v4.3.1/node_modules/pg-protocol/dist/parser.js:39:38)\n    at Socket.<anonymous> (/var/www/peertube/versions/peertube-v4.3.1/node_modules/pg-protocol/dist/index.js:11:42)\n    at Socket.emit (node:events:513:28)\n    at addChunk (node:internal/streams/readable:324:12)\n    at readableAddChunk (node:internal/streams/readable:297:9)\n    at Readable.push (node:internal/streams/readable:234:10)\n    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)",
      "message": "must be owner of type \"enum_actorFollow_state\"",
      "length": 106,
      "name": "error",
      "severity": "ERROR",
      "code": "42501",
      "file": "aclchk.c",
      "line": "3628",
      "routine": "aclcheck_error",
      "sql": "ALTER TYPE \"public\".\"enum_actorFollow_state\" ADD VALUE IF NOT EXISTS 'rejected' AFTER 'accepted'"
    },
    "sql": "ALTER TYPE \"public\".\"enum_actorFollow_state\" ADD VALUE IF NOT EXISTS 'rejected' AFTER 'accepted'",
    "parameters": {}
  },
  "level": "error",
  "message": "Cannot install application.",
  "label": "video.blender.org:443",
  "timestamp": "2022-11-22T04:03:38.000Z"
}
```

Unfortunately, it doesn't appear to be terribly actionable for me. I'm assuming this is realated to a DB migration, but I didn't see anything I needed to execute. I see that there was a[ new migration added](https://github.com/Chocobozzz/PeerTube/commit/db312c7023bb8263741255f8af1c8a6aef5f88f7), but I'm not sure how to manually run it if need be? Just looking for some guidance. 

I've since restored the database to preupgrade attempt and also restored the previous working version of peertube so I could return the instance back to operation. Would like to attemp to upgrade again, but I've need some guidance. 

I've been maintaining the blender instance for some time for the community and this is the first time an upgrade has stumped me like this :sweat_smile: 

### Additional information

* PeerTube instance URL:  https:video.blender.org
* PeerTube version: v4.2.0
* NodeJS version: v18.12.1
* Ffmpeg version: 5.0
* Redis version: 5.0.3
* PostgreSQL version: 12.13

**Comment by Chocobozzz** [comment]
Can you display the result of

```sql
SELECT typowner::regrole FROM pg_type t WHERE typname = 'enum_actorFollow_state';
```

In `psql`?

If it's not `peertube`, you can try to change the owner using https://www.postgresql.org/docs/current/sql-altertype.html

**Comment by cgarwood82** [comment]
That was it @Chocobozzz, thanks as usual. Any idea how ownership of that would have changed? Changed ownership of the data type to `peertube` and the uypgrade went as expected.
