### ISSUE TITLE
Can't install plugin beta version with CLI using --path parameter (v5.0.0-RC1)

### ISSUE THREAD

**Issue by JohnXLivingston** [Chocobozzz/PeerTube#5448]
### Describe the current behavior

When using the CLI to install a plugin from a local path (`plugins install --path '/peertube-plugin-livechat'`), if the version in the package.json is a beta version (see https://github.com/Chocobozzz/PeerTube/issues/4600), it fails with the following error:

```
[localhost:9000] 2022-12-08 10:07:30.153 warn: Cannot install plugin /peertube-plugin-livechat. {
  "err": {
    "stack": "SequelizeValidationError: Validation error: \"6.0.0-beta.1\" is not a valid version.\n    at InstanceValidator._validate (/app/node_modules/sequelize/lib/instance-validator.js:50:13)\n    at async InstanceValidator._validateAndRunHooks (/app/node_modules/sequelize/lib/instance-validator.js:60:7)\n    at async InstanceValidator.validate (/app/node_modules/sequelize/lib/instance-validator.js:54:12)\n    at async Function.upsert (/app/node_modules/sequelize/lib/model.js:1485:7)",
    "message": "Validation error: \"6.0.0-beta.1\" is not a valid version.",
    "name": "SequelizeValidationError",
    "errors": [
      {
        "message": "\"6.0.0-beta.1\" is not a valid version.",
        "type": "Validation error",
        "path": "version",
        "value": "6.0.0-beta.1",
        "origin": "FUNCTION",
        "instance": {
          "id": null,
          "name": "livechat",
          "description": "PeerTube plugin livechat: offers a way to embed a chat system into Peertube.",
          "homepage": "https://github.com/JohnXLivingston/peertube-plugin-livechat",
          "type": 1,
          "version": "6.0.0-beta.1",
          "enabled": true,
          "uninstalled": false,
          "peertubeEngine": ">=3.2.0"
        },
        "validatorKey": "isPluginVersion",
        "validatorName": null,
        "validatorArgs": [],
        "original": {
          "stack": "Error: \"6.0.0-beta.1\" is not a valid version.\n    at throwIfNotValid (/app/dist/server/models/utils.js:124:15)\n    at PluginModel.<anonymous> (/app/dist/server/models/server/plugin.js:201:90)\n    at InstanceValidator._invokeCustomValidator (/app/node_modules/sequelize/lib/instance-validator.js:156:31)\n    at /app/node_modules/sequelize/lib/instance-validator.js:115:30\n    at /app/node_modules/lodash/lodash.js:4967:15\n    at Function.forIn (/app/node_modules/lodash/lodash.js:13018:11)\n    at InstanceValidator._singleAttrValidate (/app/node_modules/sequelize/lib/instance-validator.js:104:7)\n    at /app/node_modules/sequelize/lib/instance-validator.js:82:30\n    at /app/node_modules/lodash/lodash.js:4967:15\n    at Function.forIn (/app/node_modules/lodash/lodash.js:13018:11)\n    at InstanceValidator._perAttributeValidators (/app/node_modules/sequelize/lib/instance-validator.js:70:7)\n    at InstanceValidator._validate (/app/node_modules/sequelize/lib/instance-validator.js:46:12)\n    at InstanceValidator._validateAndRunHooks (/app/node_modules/sequelize/lib/instance-validator.js:60:18)\n    at async InstanceValidator.validate (/app/node_modules/sequelize/lib/instance-validator.js:54:12)",
          "message": "\"6.0.0-beta.1\" is not a valid version."
        }
      }
    ]
  }
}
```

### Steps to reproduce

1. Download https://www.npmjs.com/package/peertube-plugin-livechat/v/6.0.0-beta.1
2. Extract the archive somewhere
3. Try to install with the CLI

### Additional information

* PeerTube instance:
  * Version: 5.0.0-RC1

**Comment by JohnXLivingston** [comment]
Sorry, I forgot I switched my dev instance back to v4.3.0 for tests reasons.
