### ISSUE TITLE
Error when uploading video with minio server as object storage

### ISSUE THREAD

**Issue by dausruddin** [Chocobozzz/PeerTube#5479]
### Describe the current behavior

After upgrading to 5.0.0, uploading a video will throw an error, when you are using minio server as object storage.

```
Sorry, but something went wrong
A header you provided implies functionality that is not implemented
```

This is what in server log
```
NotImplemented: A header you provided implies functionality that is not implemented\n    at throwDefaultError (/var/www/peertube/versions/peertube-v5.0.0/node_modules/@aws-sdk/smithy-client/dist-cjs/default-error-handler.js:8:22)\n    at deserializeAws_restXmlPutObjectAclCommandError (/var/www/peertube/versions/peertube-v5.0.0/node_modules/@aws-sdk/client-s3/dist-cjs/protocols/Aws_restXml.js:5813:51)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (internal/process/task_queues.js:95:5)\n    at async /var/www/peertube/versions/peertube-v5.0.0/node_modules/@aws-sdk/middleware-serde/dist-cjs/deserializerMiddleware.js:7:24\n    at async /var/www/peertube/versions/peertube-v5.0.0/node_modules/@aws-sdk/middleware-signing/dist-cjs/middleware.js:14:20\n    at async StandardRetryStrategy.retry (/var/www/peertube/versions/peertube-v5.0.0/node_modules/@aws-sdk/middleware-retry/dist-cjs/StandardRetryStrategy.js:51:46)\n    at async /var/www/peertube/versions/peertube-v5.0.0/node_modules/@aws-sdk/middleware-flexible-checksums/dist-cjs/flexibleChecksumsMiddleware.js:56:20\n    at async /var/www/peertube/versions/peertube-v5.0.0/node_modules/@aws-sdk/middleware-logger/dist-cjs/loggerMiddleware.js:6:22",
```

Probably because minio doesn't support ACL?
Reference: https://github.com/minio/minio/issues/8195

### Steps to reproduce

1. Use minio as object storage
2. Upgrade Peertube to 5.0.0
3. Upload a video

### Describe the expected behavior

Video should be uploaded without any issues

### Additional information

* PeerTube instance:
  * URL: N/A
  * Version: 5.0.0
  * NodeJS version: v16.19.0
  * Ffmpeg version: 4.1.10-0+deb10u1

* Browser name, version and platforms on which you could reproduce the bug: 
* Link to browser console log if relevant:
* Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`):

**Comment by Chocobozzz** [comment]
Hello,

Then you'll have to update https://github.com/Chocobozzz/PeerTube/blob/develop/config/production.yaml.example#L158

**Comment by Chocobozzz** [comment]
You need to change the setting by `public-read`

**Comment by Chocobozzz** [comment]
Regarding your comment on https://github.com/Chocobozzz/PeerTube/issues/5497#issuecomment-1374528483

Until we release a fix, your can remove the following lines (222 to line 227) from `/var/www/peertube/peertube-latest/dist/server/initializers/checker-after-init.js`:

```
        if (!config_2.CONFIG.OBJECT_STORAGE.UPLOAD_ACL.PUBLIC) {
            throw new Error('object_storage.upload_acl.public must be set');
        }
        if (!config_2.CONFIG.OBJECT_STORAGE.UPLOAD_ACL.PRIVATE) {
            throw new Error('object_storage.upload_acl.private must be set');
        }
```

Then setting `''` to https://github.com/Chocobozzz/PeerTube/blob/develop/config/production.yaml.example#L163 and https://github.com/Chocobozzz/PeerTube/blob/develop/config/production.yaml.example#L160

**Comment by Chocobozzz** [comment]
Try `null` instead of `''`?

**Comment by Chocobozzz** [comment]
Please try this patch: [file.patch.zip](https://github.com/Chocobozzz/PeerTube/files/10381032/file.patch.zip)

Copy it in `peertube-latest/` and run `patch -s -p0 < file.patch`.

**Comment by verymilan** [comment]
Hi! Since i was referred to this issue, i had updated the ACL to public accordingly (before the patch) – i then found that i still have videos not being transferred from time to time, but couldn't find errors in my log anymore. Videos are not labeled as failed but as pending.
I now have tried to dig further and added the patch, and made the acl values empty. I then applyed the patch above and tried to re-transcode HLS. Still no luck. Everything runs through, but the badge remains and playback still tries to grab the non-S3 url.

Logs i found look like this:
```
/var/log/peertube/peertube.log:{"level":"info","message":"Handling HLS transcoding job for 3b3993bc-4f28-4e04-8903-a00c98b3035e.","label":"tube.tchncs.de:443","tags":["transcoding","3b3993bc-4f28-4e04-8903-a00c98b3035e"],"timestamp":"2023-01-11T16:42:29.835Z"}
/var/log/peertube/peertube.log:{"level":"info","message":"Fetching WebTorrent file 3b3993bc-4f28-4e04-8903-a00c98b3035e-1080.mp4 from object storage to /var/www/peertube/tmp/56d84806-d6a0-47e0-9404-58180f88a3ae.mp4.","label":"tube.tchncs.de:443","tags":["object-storage"],
"timestamp":"2023-01-11T16:42:29.843Z"}
/var/log/peertube/peertube.log:{"level":"info","message":"Fetching HLS file hls/3b3993bc-4f28-4e04-8903-a00c98b3035e/3b3993bc-4f28-4e04-8903-a00c98b3035e-1080-fragmented.mp4 from object storage to /var/www/peertube/tmp/c7b1e273-4eb0-445e-9361-80935ff28158.mp4.","label":"t
ube.tchncs.de:443","tags":["object-storage"],"timestamp":"2023-01-11T16:46:34.894Z"}
/var/log/peertube/peertube.log:{"level":"info","message":"Fetching HLS file hls/3b3993bc-4f28-4e04-8903-a00c98b3035e/3b3993bc-4f28-4e04-8903-a00c98b3035e-360-fragmented.mp4 from object storage to /var/www/peertube/tmp/7112c895-1c56-404f-86b7-3fe14ce3d846.mp4.","label":"tu
be.tchncs.de:443","tags":["object-storage"],"timestamp":"2023-01-11T16:46:44.738Z"}
/var/log/peertube/peertube.log:{"level":"info","message":"Fetching HLS file hls/3b3993bc-4f28-4e04-8903-a00c98b3035e/3b3993bc-4f28-4e04-8903-a00c98b3035e-1080-fragmented.mp4 from object storage to /var/www/peertube/tmp/4e5a0c9b-d043-4611-b5ab-9e710af73135.mp4.","label":"t
ube.tchncs.de:443","tags":["object-storage"],"timestamp":"2023-01-11T16:46:48.221Z"}
/var/log/peertube/peertube.log:{"level":"info","message":"Fetching HLS file hls/3b3993bc-4f28-4e04-8903-a00c98b3035e/3b3993bc-4f28-4e04-8903-a00c98b3035e-1080.m3u8 from object storage to /var/www/peertube/tmp/8215208e-a42e-41ae-9c26-2fa7e08d8c70.m3u8.","label":"tube.tchnc
s.de:443","tags":["object-storage"],"timestamp":"2023-01-11T16:46:52.456Z"}
/var/log/peertube/peertube.log:{"level":"info","message":"Fetching HLS file hls/3b3993bc-4f28-4e04-8903-a00c98b3035e/3b3993bc-4f28-4e04-8903-a00c98b3035e-360-fragmented.mp4 from object storage to /var/www/peertube/tmp/588dc3fc-9d32-4660-89e8-174f95cbd302.mp4.","label":"tu
be.tchncs.de:443","tags":["object-storage"],"timestamp":"2023-01-11T16:46:54.143Z"}
/var/log/peertube/peertube.log:{"level":"info","message":"Fetching HLS file hls/3b3993bc-4f28-4e04-8903-a00c98b3035e/3b3993bc-4f28-4e04-8903-a00c98b3035e-360.m3u8 from object storage to /var/www/peertube/tmp/7cb10e85-a057-495a-8893-5353e1745ade.m3u8.","label":"tube.tchncs
.de:443","tags":["object-storage"],"timestamp":"2023-01-11T16:46:55.099Z"}
/var/log/peertube/peertube.log:{"level":"info","message":"HLS transcoding job for 3b3993bc-4f28-4e04-8903-a00c98b3035e ended.","label":"tube.tchncs.de:443","tags":["transcoding","3b3993bc-4f28-4e04-8903-a00c98b3035e"],"timestamp":"2023-01-11T16:46:56.709Z"}
/var/log/peertube/peertube.log:{"level":"info","message":"Processing transcoding job 14c75957-68ab-46c2-9b4b-9c24782f51f3.","label":"tube.tchncs.de:443","tags":["transcoding","3b3993bc-4f28-4e04-8903-a00c98b3035e"],"timestamp":"2023-01-11T16:46:56.737Z"}
/var/log/peertube/peertube.log:{"level":"info","message":"Handling HLS transcoding job for 3b3993bc-4f28-4e04-8903-a00c98b3035e.","label":"tube.tchncs.de:443","tags":["transcoding","3b3993bc-4f28-4e04-8903-a00c98b3035e"],"timestamp":"2023-01-11T16:46:56.763Z"}
/var/log/peertube/peertube.log:{"level":"info","message":"Fetching WebTorrent file 3b3993bc-4f28-4e04-8903-a00c98b3035e-1080.mp4 from object storage to /var/www/peertube/tmp/9358902d-a718-49c0-a8f0-91a024c819b0.mp4.","label":"tube.tchncs.de:443","tags":["object-storage"],
"timestamp":"2023-01-11T16:46:56.765Z"}
/var/log/peertube/peertube.log:{"level":"info","message":"Fetching HLS file hls/3b3993bc-4f28-4e04-8903-a00c98b3035e/3b3993bc-4f28-4e04-8903-a00c98b3035e-1080-fragmented.mp4 from object storage to /var/www/peertube/tmp/ccc4e7be-0060-4235-aed6-444cae646d70.mp4.","label":"t
ube.tchncs.de:443","tags":["object-storage"],"timestamp":"2023-01-11T16:51:29.218Z"}
/var/log/peertube/peertube.log:{"level":"info","message":"Fetching HLS file hls/3b3993bc-4f28-4e04-8903-a00c98b3035e/3b3993bc-4f28-4e04-8903-a00c98b3035e-1080-fragmented.mp4 from object storage to /var/www/peertube/tmp/7eafd6df-5535-4a84-964b-3fce2e640a67.mp4.","label":"t
ube.tchncs.de:443","tags":["object-storage"],"timestamp":"2023-01-11T16:51:38.537Z"}
/var/log/peertube/peertube.log:{"level":"info","message":"Fetching HLS file hls/3b3993bc-4f28-4e04-8903-a00c98b3035e/3b3993bc-4f28-4e04-8903-a00c98b3035e-1080.m3u8 from object storage to /var/www/peertube/tmp/94db4d18-2392-4aed-a143-75fbe6ea42d0.m3u8.","label":"tube.tchnc
s.de:443","tags":["object-storage"],"timestamp":"2023-01-11T16:51:43.752Z"}
/var/log/peertube/peertube.log:{"level":"info","message":"HLS transcoding job for 3b3993bc-4f28-4e04-8903-a00c98b3035e ended.","label":"tube.tchncs.de:443","tags":["transcoding","3b3993bc-4f28-4e04-8903-a00c98b3035e"],"timestamp":"2023-01-11T16:51:47.417Z"}
/var/log/peertube/peertube.log:{"level":"info","message":"Processing transcoding job f85c9071-ad80-45b0-a913-dd51851fec90.","label":"tube.tchncs.de:443","tags":["transcoding","3b3993bc-4f28-4e04-8903-a00c98b3035e"],"timestamp":"2023-01-11T16:51:47.449Z"}
/var/log/peertube/peertube.log:{"level":"info","message":"Handling HLS transcoding job for 3b3993bc-4f28-4e04-8903-a00c98b3035e.","label":"tube.tchncs.de:443","tags":["transcoding","3b3993bc-4f28-4e04-8903-a00c98b3035e"],"timestamp":"2023-01-11T16:51:47.469Z"}
/var/log/peertube/peertube.log:{"level":"info","message":"Fetching WebTorrent file 3b3993bc-4f28-4e04-8903-a00c98b3035e-1080.mp4 from object storage to /var/www/peertube/tmp/2512c97d-925b-4b51-99bb-c1c2944630b6.mp4.","label":"tube.tchncs.de:443","tags":["object-storage"],
"timestamp":"2023-01-11T16:51:47.471Z"}
/var/log/peertube/peertube.log:{"level":"info","message":"HLS transcoding job for 3b3993bc-4f28-4e04-8903-a00c98b3035e ended.","label":"tube.tchncs.de:443","tags":["transcoding","3b3993bc-4f28-4e04-8903-a00c98b3035e"],"timestamp":"2023-01-11T17:00:24.522Z"}


/var/log/peertube/peertube.log:{"level":"info","message":"Creating external storage move job for video 3b3993bc-4f28-4e04-8903-a00c98b3035e.","label":"tube.tchncs.de:443","tags":["3b3993bc-4f28-4e04-8903-a00c98b3035e"],"timestamp":"2023-01-11T17:00:24.602Z"}
/var/log/peertube/peertube.log:{"level":"info","message":"Moving video 3b3993bc-4f28-4e04-8903-a00c98b3035e in job 20103.","label":"tube.tchncs.de:443","timestamp":"2023-01-11T17:00:24.640Z"}
```
