### ISSUE TITLE
Error: Number contains of non-alphabetic digits

### ISSUE THREAD

**Issue by JohnXLivingston** [Chocobozzz/PeerTube#5481]
### Describe the current behavior

Looking logs on my server, I found this one multiple time:

```
error[24/12/2022 13:41:07] Error in controller.

{
  "err": "Error: Number \"ix5l9yzgcma5j6*****\" contains of non-alphabetic digits (123456789abcdefghijkmnopqrstuvwxyzABCDEFGHJKLMNPQRSTUVWXYZ)\n    at Converter.convert (/var/www/peertube/versions/peertube-v5.0.0/node_modules/any-base/src/converter.js:34:15)\n    at /var/www/peertube/versions/peertube-v5.0.0/node_modules/any-base/index.js:21:26\n    at enlargeUUID (/var/www/peertube/versions/peertube-v5.0.0/node_modules/short-uuid/index.js:44:15)\n    at Object.toUUID (/var/www/peertube/versions/peertube-v5.0.0/node_modules/short-uuid/index.js:99:30)\n    at shortToUUID (/var/www/peertube/versions/peertube-v5.0.0/dist/shared/extra-utils/uuid.js:20:23)\n    at toCompleteUUID (/var/www/peertube/versions/peertube-v5.0.0/dist/server/helpers/custom-validators/misc.js:90:46)\n    at Function.<anonymous> (/var/www/peertube/versions/peertube-v5.0.0/dist/server/lib/client-html.js:43:55)\n    at Generator.next (<anonymous>)\n    at /var/www/peertube/versions/peertube-v5.0.0/node_modules/tslib/tslib.js:118:75\n    at new Promise (<anonymous>)\n    at Object.__awaiter (/var/www/peertube/versions/peertube-v5.0.0/node_modules/tslib/tslib.js:114:16)\n    at Function.getWatchHTMLPage (/var/www/peertube/versions/peertube-v5.0.0/dist/server/lib/client-html.js:42:24)\n    at /var/www/peertube/versions/peertube-v5.0.0/dist/server/controllers/client.js:97:53\n    at Generator.next (<anonymous>)\n    at /var/www/peertube/versions/peertube-v5.0.0/node_modules/tslib/tslib.js:118:75\n    at new Promise (<anonymous>)\n    at Object.__awaiter (/var/www/peertube/versions/peertube-v5.0.0/node_modules/tslib/tslib.js:114:16)\n    at generateWatchHtmlPage (/var/www/peertube/versions/peertube-v5.0.0/dist/server/controllers/client.js:96:20)\n    at /var/www/peertube/versions/peertube-v5.0.0/dist/server/middlewares/async.js:21:32\n    at Layer.handle [as handle_request] (/var/www/peertube/versions/peertube-v5.0.0/node_modules/express/lib/router/layer.js:95:5)\n    at trim_prefix (/var/www/peertube/versions/peertube-v5.0.0/node_modules/express/lib/router/index.js:328:13)\n    at /var/www/peertube/versions/peertube-v5.0.0/node_modules/express/lib/router/index.js:286:9\n    at param (/var/www/peertube/versions/peertube-v5.0.0/node_modules/express/lib/router/index.js:365:14)\n    at param (/var/www/peertube/versions/peertube-v5.0.0/node_modules/express/lib/router/index.js:376:14)\n    at param (/var/www/peertube/versions/peertube-v5.0.0/node_modules/express/lib/router/index.js:376:14)\n    at Function.process_params (/var/www/peertube/versions/peertube-v5.0.0/node_modules/express/lib/router/index.js:421:3)\n    at next (/var/www/peertube/versions/peertube-v5.0.0/node_modules/express/lib/router/index.js:280:10)\n    at Function.handle (/var/www/peertube/versions/peertube-v5.0.0/node_modules/express/lib/router/index.js:175:3)"
}
```

Note: I replaced the end of the string by *, as I don't know if this is a private key.

I don't know what it is.
But, I see that «0» and «l» (lower case L), «I» (upper case i) are missing in the error `non-alphabetic digits (123456789abcdefghijkmnopqrstuvwxyzABCDEFGHJKLMNPQRSTUVWXYZ)`.
Perhaps these are forbidden characters because they are ambigous. But i got this error, so there might be a problem somewhere.

### Steps to reproduce

1. ???

### Additional information

* PeerTube instance:
  * Version: 5.0.0

**Comment by Chocobozzz** [comment]
Thanks, it should be fixed by https://github.com/Chocobozzz/PeerTube/commit/ded68a97600d70fb8bbadfbddac87eadb1233910

**Comment by JohnXLivingston** [comment]
Any idea of what has caused the error message?
Is there any broken functionality?
Looking at your fix, it prevents the code to crash. But why is there a value containing a forbidden char?

**Comment by Chocobozzz** [comment]
It's when the URL contains an invalid short UUID.
