### ISSUE TITLE
Video from youtube is not download

### ISSUE THREAD

**Issue by ne-vlezay80** [Chocobozzz/PeerTube#5500]
### Steps to reproduce

1. Try download video from youtube
2.
3.

### Describe the expected behavior

log:
```
Error: Command failed with exit code 1: /usr/bin/python3 /var/www/peertube/storage/bin/yt-dlp --merge-output-format mp4 -f bestvideo[vcodec!*=av01][vcodec!*=vp9.2]+bestaudio/best[vcodec!*=av01][vcodec!*=vp9.2]/bestvideo[ext=mp4]+bestaudio[ext=m4a]/best -o /var/www/peertube/storage/tmp/eafdd4ee82b6294f93a956f024a7746d3eb42fb57e735ff2ee3ed87eb3d67f69-import https://www.youtube.com/watch?v=YMSkRXfzHoU
ERROR: Postprocessing:   Stream #1:0 -> #0:1 (copy)
[youtube] YMSkRXfzHoU: Downloading webpage
[youtube] YMSkRXfzHoU: Downloading android player API JSON
[info] YMSkRXfzHoU: Downloading 1 format(s): 315+251
[download] Destination: /var/www/peertube/storage/tmp/eafdd4ee82b6294f93a956f024a7746d3eb42fb57e735ff2ee3ed87eb3d67f69-import.f315.webm

[Merger] Merging formats into "/var/www/peertube/storage/tmp/eafdd4ee82b6294f93a956f024a7746d3eb42fb57e735ff2ee3ed87eb3d67f69-import.mp4"
    at makeError (/var/www/peertube/versions/peertube-v4.3.0/node_modules/execa/lib/error.js:60:11)
    at handlePromise (/var/www/peertube/versions/peertube-v4.3.0/node_modules/execa/index.js:118:26)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
```

### Additional information

* PeerTube instance:
  * URL: http://[301:3559:2828:2843::4]/
  * Version:4.3.0
  * NodeJS version: v14.21.1
  * Ffmpeg version: 4.1.9

* Browser name, version and platforms on which you could reproduce the bug:
* Link to browser console log if relevant:
* Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`):

```
Jan 01 06:40:56 yggtube peertube[12246]:   "innerErr": {
Jan 01 06:40:56 yggtube peertube[12246]:     "stack": "Error: Cannot guess path of /var/www/peertube/storage/tmp/eafdd4ee82b6294f93a956f024a7746d3eb42fb57e735ff2ee3ed87eb3d67f69-import. Directory con
Jan 01 06:40:56 yggtube peertube[12246]:     "message": "Cannot guess path of /var/www/peertube/storage/tmp/eafdd4ee82b6294f93a956f024a7746d3eb42fb57e735ff2ee3ed87eb3d67f69-import. Directory content:
Jan 01 06:40:56 yggtube peertube[12246]:   }
Jan 01 06:40:56 yggtube peertube[12246]: }
```

**Comment by ne-vlezay80** [comment]
The ffmpeg problem.

**Comment by Chocobozzz** [comment]
Hi,

Yes it is: try to upgrade to ffmpeg 4.3 or 5.x
