### ISSUE TITLE
HLS Error: Timeout at Timeout.<anonymous> (/var/www/peertube/versions/peertube-v5.0.1/dist/shared/core-utils/common/promises.js:17:42)

### ISSUE THREAD

**Issue by Aleksey-Zhadan** [Chocobozzz/PeerTube#5519]
### Describe the current behavior

When i am trying to make video-redundancy with HLS on a big file > 4GB, i got error:

Job: 402 
Type: video-redundancy 
Processed on 08.01.23, 12:11:46,940 
Finished on 08.01.23, 15:11:46,949
--
{   "videoId": 289 }
Error: Timeout     at Timeout.<anonymous> (/var/www/peertube/versions/peertube-v5.0.1/dist/shared/core-utils/common/promises.js:17:42) 
 at listOnTimeout (node:internal/timers:564:17)
at process.processTimers (node:internal/timers:507:7)

![image](https://user-images.githubusercontent.com/87325720/211308622-1562db1a-7b50-4d01-bca6-5ec2eec7f7ca.png)

### Steps to reproduce

1.
2.
3.

### Additional information

* PeerTube instance:
  * URL:
  * Version:  5.0.1
  * NodeJS version:
  * Ffmpeg version:

* Browser name, version and platforms on which you could reproduce the bug:
* Link to browser console log if relevant:
* Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`):

**Comment by Chocobozzz** [comment]
What video do you try to mirror? The target server may have bandwidth issues?

**Comment by Aleksey-Zhadan** [comment]
No bandwidth issues, uploading time out after 3 hour ( it's to fast. Can i control it? set 24h timeout?

**Comment by Chocobozzz** [comment]
Did you change https://github.com/Chocobozzz/PeerTube/blob/develop/config/production.yaml.example#L555?
