### ISSUE TITLE
null value in column nodeVersion

### ISSUE THREAD

**Issue by mishfit** [Chocobozzz/PeerTube#5588]
### Describe the problem

Node cannot seem to get `process.version` on startup

### Additional information

* PeerTube instance URL: `https://backtothelan.tv`
* PeerTube version: `5.0.1`
* NodeJS version: (tried multiple versions using `nvm`) `v14.21.2`
* Ffmpeg version: `4.3.4-0+deb11u1`
* Redis version: `5:6.0.16-1+deb11u2`
* PostgreSQL version: `13+225`
* Logs:
```
Feb 08 14:41:04 aptenodytes systemd[1]: peertube.service: Scheduled restart job, restart counter is at 12.
Feb 08 14:41:04 aptenodytes systemd[1]: Stopped PeerTube daemon.
Feb 08 14:41:04 aptenodytes systemd[1]: peertube.service: Consumed 8.206s CPU time.
Feb 08 14:41:04 aptenodytes systemd[1]: Started PeerTube daemon.
Feb 08 14:41:04 aptenodytes peertube[2275449]: Now using node v14.21.2 (npm v6.14.17)
Feb 08 14:41:09 aptenodytes peertube[2275749]: [backtothelan.tv:443] 2023-02-08 14:41:09.933 info: Using following configuration file hierarchy: /home/federated/Websites/peertube/config/default.yaml -> /home/federated/Website>
Feb 08 14:41:10 aptenodytes peertube[2275749]: [backtothelan.tv:443] 2023-02-08 14:41:10.568 error: Cannot start application. {
Feb 08 14:41:10 aptenodytes peertube[2275749]:   "err": {
Feb 08 14:41:10 aptenodytes peertube[2275749]:     "stack": "Error\n    at Query.run (/mnt/spinning1/federated/peertube/application/node_modules/sequelize/lib/dialects/postgres/query.js:50:25)\n    at /mnt/spinning1/federated>
Feb 08 14:41:10 aptenodytes peertube[2275749]:     "message": "null value in column \"nodeVersion\" of relation \"application\" violates not-null constraint",
Feb 08 14:41:10 aptenodytes peertube[2275749]:     "name": "SequelizeDatabaseError",
Feb 08 14:41:10 aptenodytes peertube[2275749]:     "parent": {
Feb 08 14:41:10 aptenodytes peertube[2275749]:       "stack": "error: null value in column \"nodeVersion\" of relation \"application\" violates not-null constraint\n    at Parser.parseErrorMessage (/mnt/spinning1/federated/pe>
Feb 08 14:41:10 aptenodytes peertube[2275749]:       "message": "null value in column \"nodeVersion\" of relation \"application\" violates not-null constraint",
Feb 08 14:41:10 aptenodytes peertube[2275749]:       "length": 236,
Feb 08 14:41:10 aptenodytes peertube[2275749]:       "name": "error",
Feb 08 14:41:10 aptenodytes peertube[2275749]:       "severity": "ERROR",
Feb 08 14:41:10 aptenodytes peertube[2275749]:       "code": "23502",
Feb 08 14:41:10 aptenodytes peertube[2275749]:       "detail": "Failing row contains (105, 0, null, null, null).",
Feb 08 14:41:10 aptenodytes peertube[2275749]:       "schema": "public",
Feb 08 14:41:10 aptenodytes peertube[2275749]:       "table": "application",
Feb 08 14:41:10 aptenodytes peertube[2275749]:       "column": "nodeVersion",
Feb 08 14:41:10 aptenodytes peertube[2275749]:       "file": "execMain.c",
Feb 08 14:41:10 aptenodytes peertube[2275749]:       "line": "1947",
Feb 08 14:41:10 aptenodytes peertube[2275749]:       "routine": "ExecConstraints",
Feb 08 14:41:10 aptenodytes peertube[2275749]:       "sql": "INSERT INTO \"application\" (\"migrationVersion\") VALUES (0)"
Feb 08 14:41:10 aptenodytes peertube[2275749]:     },
Feb 08 14:41:10 aptenodytes peertube[2275749]:     "original": {
Feb 08 14:41:10 aptenodytes peertube[2275749]:       "stack": "error: null value in column \"nodeVersion\" of relation \"application\" violates not-null constraint\n    at Parser.parseErrorMessage (/mnt/spinning1/federated/pe>
Feb 08 14:41:10 aptenodytes peertube[2275749]:       "message": "null value in column \"nodeVersion\" of relation \"application\" violates not-null constraint",
Feb 08 14:41:10 aptenodytes peertube[2275749]:       "length": 236,
Feb 08 14:41:10 aptenodytes peertube[2275749]:       "name": "error",
Feb 08 14:41:10 aptenodytes peertube[2275749]:       "severity": "ERROR",
Feb 08 14:41:10 aptenodytes peertube[2275749]:       "code": "23502",
Feb 08 14:41:10 aptenodytes peertube[2275749]:       "detail": "Failing row contains (105, 0, null, null, null).",
Feb 08 14:41:10 aptenodytes peertube[2275749]:       "schema": "public",
Feb 08 14:41:10 aptenodytes peertube[2275749]:       "table": "application",
Feb 08 14:41:10 aptenodytes peertube[2275749]:       "column": "nodeVersion",
Feb 08 14:41:10 aptenodytes peertube[2275749]:       "file": "execMain.c",
Feb 08 14:41:10 aptenodytes peertube[2275749]:       "line": "1947",
Feb 08 14:41:10 aptenodytes peertube[2275749]:       "routine": "ExecConstraints",
Feb 08 14:41:10 aptenodytes peertube[2275749]:       "sql": "INSERT INTO \"application\" (\"migrationVersion\") VALUES (0)"
Feb 08 14:41:10 aptenodytes peertube[2275749]:     },
Feb 08 14:41:10 aptenodytes peertube[2275749]:     "sql": "INSERT INTO \"application\" (\"migrationVersion\") VALUES (0)",
Feb 08 14:41:10 aptenodytes peertube[2275749]:     "parameters": {}
Feb 08 14:41:10 aptenodytes peertube[2275749]:   }
Feb 08 14:41:10 aptenodytes peertube[2275749]: }
Feb 08 14:41:10 aptenodytes systemd[1]: peertube.service: Main process exited, code=exited, status=255/EXCEPTION
Feb 08 14:41:10 aptenodytes systemd[1]: peertube.service: Failed with result 'exit-code'.
Feb 08 14:41:10 aptenodytes systemd[1]: peertube.service: Consumed 8.217s CPU time.
Feb 08 14:41:10 aptenodytes systemd[1]: peertube.service: Scheduled restart job, restart counter is at 13.
```

**Comment by Chocobozzz** [comment]
Can you try to add a `console.log(application)` in `dist/server/models/application/application.js` line `38`? Your bug is really weird :thinking: 

Can you also display the content of `application` SQL table?

**Comment by mishfit** [comment]
The `application` table is currently empty. Here is the result of generating a create script:
```
-- Table: public.application

-- DROP TABLE public.application;

CREATE TABLE IF NOT EXISTS public.application
(
    id integer NOT NULL DEFAULT nextval('application_id_seq'::regclass),
    "migrationVersion" integer NOT NULL DEFAULT 0,
    "latestPeerTubeVersion" character varying(255) COLLATE pg_catalog."default",
    "nodeVersion" character varying(255) COLLATE pg_catalog."default" NOT NULL,
    "nodeABIVersion" integer NOT NULL,
    CONSTRAINT application_pkey PRIMARY KEY (id)
)

TABLESPACE pg_default;

ALTER TABLE public.application
    OWNER to peertube;
```

Unfortunately it never gets to line 38 in the application model.
```
starting...
checking node version
[backtothelan.tv:443] 2023-02-09 09:12:06.559 info: Using following configuration file hierarchy: /home/federated/Websites/peertube/config/default.yaml -> /home/federated/Websites/peertube/config/production.yaml.
[backtothelan.tv:443] 2023-02-09 09:12:07.113 error: Cannot start application. {
  "err": {
    "stack": "Error\n    at Query.run (/mnt/spinning1/federated/peertube/application/node_modules/sequelize/lib/dialects/postgres/query.js:50:25)\n    at /mnt/spinning1/federated/peertube/application/node_modules/sequelize/lib/sequelize.js:314:28\n    at processTicksAndRejections (internal/process/task_queues.js:95:5)",
    "message": "null value in column \"nodeVersion\" of relation \"application\" violates not-null constraint",
    "name": "SequelizeDatabaseError",
    "parent": {
      "stack": "error: null value in column \"nodeVersion\" of relation \"application\" violates not-null constraint\n    at Parser.parseErrorMessage (/mnt/spinning1/federated/peertube/application/node_modules/pg-protocol/dist/parser.js:287:98)\n    at Parser.handlePacket (/mnt/spinning1/federated/peertube/application/node_modules/pg-protocol/dist/parser.js:126:29)\n    at Parser.parse (/mnt/spinning1/federated/peertube/application/node_modules/pg-protocol/dist/parser.js:39:38)\n    at Socket.<anonymous> (/mnt/spinning1/federated/peertube/application/node_modules/pg-protocol/dist/index.js:11:42)\n    at Socket.emit (events.js:400:28)\n    at addChunk (internal/streams/readable.js:293:12)\n    at readableAddChunk (internal/streams/readable.js:267:9)\n    at Socket.Readable.push (internal/streams/readable.js:206:10)\n    at TCP.onStreamRead (internal/stream_base_commons.js:188:23)",
      "message": "null value in column \"nodeVersion\" of relation \"application\" violates not-null constraint",
      "length": 236,
      "name": "error",
      "severity": "ERROR",
      "code": "23502",
      "detail": "Failing row contains (177, 0, null, null, null).",
      "schema": "public",
      "table": "application",
      "column": "nodeVersion",
      "file": "execMain.c",
      "line": "1947",
      "routine": "ExecConstraints",
      "sql": "INSERT INTO \"application\" (\"migrationVersion\") VALUES (0)"
    },
    "original": {
      "stack": "error: null value in column \"nodeVersion\" of relation \"application\" violates not-null constraint\n    at Parser.parseErrorMessage (/mnt/spinning1/federated/peertube/application/node_modules/pg-protocol/dist/parser.js:287:98)\n    at Parser.handlePacket (/mnt/spinning1/federated/peertube/application/node_modules/pg-protocol/dist/parser.js:126:29)\n    at Parser.parse (/mnt/spinning1/federated/peertube/application/node_modules/pg-protocol/dist/parser.js:39:38)\n    at Socket.<anonymous> (/mnt/spinning1/federated/peertube/application/node_modules/pg-protocol/dist/index.js:11:42)\n    at Socket.emit (events.js:400:28)\n    at addChunk (internal/streams/readable.js:293:12)\n    at readableAddChunk (internal/streams/readable.js:267:9)\n    at Socket.Readable.push (internal/streams/readable.js:206:10)\n    at TCP.onStreamRead (internal/stream_base_commons.js:188:23)",
      "message": "null value in column \"nodeVersion\" of relation \"application\" violates not-null constraint",
      "length": 236,
      "name": "error",
      "severity": "ERROR",
      "code": "23502",
      "detail": "Failing row contains (177, 0, null, null, null).",
      "schema": "public",
      "table": "application",
      "column": "nodeVersion",
      "file": "execMain.c",
      "line": "1947",
      "routine": "ExecConstraints",
      "sql": "INSERT INTO \"application\" (\"migrationVersion\") VALUES (0)"
    },
    "sql": "INSERT INTO \"application\" (\"migrationVersion\") VALUES (0)",
    "parameters": {}
  }
}
```
It checks connection to the database and then begins migration but never gets to `updateNodeVersions` (I added console logs in `database.js` and `server.js` as well.

**Comment by Chocobozzz** [comment]
It's weird the application table is empty: has your instance existed for a long time? Or is it a first install?

**Comment by mishfit** [comment]
@Chocobozzz this is right after installation. I scripted everything using Jenkins to install the tarball (`https://github.com/Chocobozzz/PeerTube/releases/download/v5.0.1/peertube-v5.0.1.tar.xz`).

Systemd runs as a specific user a script which sets up more of the environment:
```
!/bin/bash                                                                                                                                                                                                                      
. /home/federated/.nvm/nvm.sh                                                                                                                                                                                                    
nvm use 16.19.0                                                                                                                                                                                                                  

node ./dist/server.js "$@"
```

The service is allowed access to `/home/`

**Comment by Chocobozzz** [comment]
Then please drop your database, recreate it and paste first run PeerTube output

**Comment by aeharding** [comment]
I had a similar issue running a development environment. I believe the issue was Redis wasn't running when I attempted to start the server (with a fresh db), which put the new database in a bad state.

Dropping the database, starting redis, and restarting PeerTube resolved the issue.

**Comment by mishfit** [comment]
@aeharding Redis was also my issue. authentication to be exact, I neglected to put in the auth for redis and from there the database never fully initialized.

My mistake all, sorry for the run around.

**Comment by Happyfeet01** [comment]
Hello, have the same issue suddenly. The server works fine for a year. Now i got this Message at startup.

`[tube.domain.tld:443] 2023-12-21 14:27:12.217 info: Using following configuration file hierarchy: /app/config/default.yaml -> /app/support/docker/production/config/production.yaml -> /app/support/docker/production/config/custom-environment-variables.yaml.
[tube.domain.tldl:443] 2023-12-21 14:27:12.379 error: Cannot start application. {
  "err": {
    "stack": "Error\n    at Query.run (/app/node_modules/sequelize/lib/dialects/postgres/query.js:50:25)\n    at /app/node_modules/sequelize/lib/sequelize.js:315:28\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)",
    "message": "null value in column \"nodeVersion\" of relation \"application\" violates not-null constraint",
    "name": "SequelizeDatabaseError",
    "parent": {
      "stack": "error: null value in column \"nodeVersion\" of relation \"application\" violates not-null constraint\n    at Parser.parseErrorMessage (/app/node_modules/pg-protocol/dist/parser.js:287:98)\n    at Parser.handlePacket (/app/node_modules/pg-protocol/dist/parser.js:126:29)\n    at Parser.parse (/app/node_modules/pg-protocol/dist/parser.js:39:38)\n    at Socket.<anonymous> (/app/node_modules/pg-protocol/dist/index.js:11:42)\n    at Socket.emit (node:events:513:28)\n    at addChunk (node:internal/streams/readable:315:12)\n    at readableAddChunk (node:internal/streams/readable:289:9)\n    at Socket.Readable.push (node:internal/streams/readable:228:10)\n    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)",
      "message": "null value in column \"nodeVersion\" of relation \"application\" violates not-null constraint",
      "length": 235,
      "name": "error",
      "severity": "ERROR",
      "code": "23502",
      "detail": "Failing row contains (74, 0, null, null, null).",
      "schema": "public",
      "table": "application",
      "column": "nodeVersion",
      "file": "execMain.c",
      "line": "1947",
      "routine": "ExecConstraints",
      "sql": "INSERT INTO \"application\" (\"migrationVersion\") VALUES (0)"
    },
    "sql": "INSERT INTO \"application\" (\"migrationVersion\") VALUES (0)",
    "parameters": {}
  }`
 the entry of the table application

`peertube=# \d application
                                           Table "public.application"
        Column         |          Type          | Collation | Nullable |                 Default                 
-----------------------+------------------------+-----------+----------+-----------------------------------------
 id                    | integer                |           | not null | nextval('application_id_seq'::regclass)
 migrationVersion      | integer                |           | not null | 0
 latestPeerTubeVersion | character varying(255) |           |          | 
 nodeVersion           | character varying(255) |           | not null | 
 nodeABIVersion        | integer                |           | not null | 
Indexes:
    "application_pkey" PRIMARY KEY, btree (id)
Referenced by:
    TABLE "account" CONSTRAINT "account_applicationId_fkey" FOREIGN KEY ("applicationId") REFERENCES application(id) ON UPDATE CASCADE ON DELETE CASCADE`

how can i fix it? i can´t drop the database.

**Comment by Chocobozzz** [comment]
@Happyfeet01 please create a dedicated issue by filling the bug template, and also paste the content or your `application` table
