### ISSUE TITLE
 An error occurred while importing the video

### ISSUE THREAD

**Issue by tio-trom** [Chocobozzz/PeerTube#5621]
### Describe the current behavior

This used to work but does not anymore. Did not update Peertube in that meantime. Tested with a youtube url.

### Steps to reproduce

1. Try to import via URL, say with https://www.youtube.com/watch?v=tm-dXwxPRMw
2. An error will appear in a few seconds time.

This is the log:

```
error[2/18/2023, 2:56:40 PM] An error occurred while importing the video https://www.youtube.com/watch?v=tm-dXwxPRMw.

{
  "err": {
    "stack": "Error: Command failed with exit code 1: /usr/bin/python3 /home/yunohost.app/peertube/storage/bin/yt-dlp --dump-json -f bestvideo[vcodec^=avc1][height=1080]+bestaudio[ext=m4a]/bestvideo[vcodec!*=av01][vcodec!*=vp9.2][height=1080]+bestaudio/bestvideo[vcodec^=avc1][height<=1080]+bestaudio[ext=m4a]/bestvideo[vcodec!*=av01][vcodec!*=vp9.2]+bestaudio/best[vcodec!*=av01][vcodec!*=vp9.2]/bestvideo[ext=mp4]+bestaudio[ext=m4a]/best https://www.youtube.com/watch?v=tm-dXwxPRMw\nERROR: [youtube] tm-dXwxPRMw: Unable to extract uploader id; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U\n    at makeError (/var/www/peertube/node_modules/execa/lib/error.js:60:11)\n    at handlePromise (/var/www/peertube/node_modules/execa/index.js:118:26)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)",
    "message": "Cannot fetch information from import for URL https://www.youtube.com/watch?v=tm-dXwxPRMw",
    "code": 0,
    "cause": {
      "stack": "Error: Command failed with exit code 1: /usr/bin/python3 /home/yunohost.app/peertube/storage/bin/yt-dlp --dump-json -f bestvideo[vcodec^=avc1][height=1080]+bestaudio[ext=m4a]/bestvideo[vcodec!*=av01][vcodec!*=vp9.2][height=1080]+bestaudio/bestvideo[vcodec^=avc1][height<=1080]+bestaudio[ext=m4a]/bestvideo[vcodec!*=av01][vcodec!*=vp9.2]+bestaudio/best[vcodec!*=av01][vcodec!*=vp9.2]/bestvideo[ext=mp4]+bestaudio[ext=m4a]/best https://www.youtube.com/watch?v=tm-dXwxPRMw\nERROR: [youtube] tm-dXwxPRMw: Unable to extract uploader id; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U\n    at makeError (/var/www/peertube/node_modules/execa/lib/error.js:60:11)\n    at handlePromise (/var/www/peertube/node_modules/execa/index.js:118:26)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)",
      "message": "Command failed with exit code 1: /usr/bin/python3 /home/yunohost.app/peertube/storage/bin/yt-dlp --dump-json -f bestvideo[vcodec^=avc1][height=1080]+bestaudio[ext=m4a]/bestvideo[vcodec!*=av01][vcodec!*=vp9.2][height=1080]+bestaudio/bestvideo[vcodec^=avc1][height<=1080]+bestaudio[ext=m4a]/bestvideo[vcodec!*=av01][vcodec!*=vp9.2]+bestaudio/best[vcodec!*=av01][vcodec!*=vp9.2]/bestvideo[ext=mp4]+bestaudio[ext=m4a]/best https://www.youtube.com/watch?v=tm-dXwxPRMw\nERROR: [youtube] tm-dXwxPRMw: Unable to extract uploader id; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U",
      "shortMessage": "Command failed with exit code 1: /usr/bin/python3 /home/yunohost.app/peertube/storage/bin/yt-dlp --dump-json -f bestvideo[vcodec^=avc1][height=1080]+bestaudio[ext=m4a]/bestvideo[vcodec!*=av01][vcodec!*=vp9.2][height=1080]+bestaudio/bestvideo[vcodec^=avc1][height<=1080]+bestaudio[ext=m4a]/bestvideo[vcodec!*=av01][vcodec!*=vp9.2]+bestaudio/best[vcodec!*=av01][vcodec!*=vp9.2]/bestvideo[ext=mp4]+bestaudio[ext=m4a]/best https://www.youtube.com/watch?v=tm-dXwxPRMw",
      "command": "/usr/bin/python3 /home/yunohost.app/peertube/storage/bin/yt-dlp --dump-json -f bestvideo[vcodec^=avc1][height=1080]+bestaudio[ext=m4a]/bestvideo[vcodec!*=av01][vcodec!*=vp9.2][height=1080]+bestaudio/bestvideo[vcodec^=avc1][height<=1080]+bestaudio[ext=m4a]/bestvideo[vcodec!*=av01][vcodec!*=vp9.2]+bestaudio/best[vcodec!*=av01][vcodec!*=vp9.2]/bestvideo[ext=mp4]+bestaudio[ext=m4a]/best https://www.youtube.com/watch?v=tm-dXwxPRMw",
      "escapedCommand": "\"/usr/bin/python3\" \"/home/yunohost.app/peertube/storage/bin/yt-dlp\" --dump-json -f \"bestvideo[vcodec^=avc1][height=1080]+bestaudio[ext=m4a]/bestvideo[vcodec!*=av01][vcodec!*=vp9.2][height=1080]+bestaudio/bestvideo[vcodec^=avc1][height<=1080]+bestaudio[ext=m4a]/bestvideo[vcodec!*=av01][vcodec!*=vp9.2]+bestaudio/best[vcodec!*=av01][vcodec!*=vp9.2]/bestvideo[ext=mp4]+bestaudio[ext=m4a]/best\" \"https://www.youtube.com/watch?v=tm-dXwxPRMw\"",
      "exitCode": 1,
      "stdout": "",
      "stderr": "ERROR: [youtube] tm-dXwxPRMw: Unable to extract uploader id; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U",
      "failed": true,
      "timedOut": false,
      "isCanceled": false,
      "killed": false
    }
  }
}

error[2/18/2023, 2:56:41 PM] Client log: Backend returned code 400, errorMessage is: Cannot fetch information from import for URL https://www.youtube.com/watch?v=tm-dXwxPRMw

{
  "tags": [
    "client"
  ],
  "username": "tio",
  "userAgent": "Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/110.0",
  "url": "https://videos.trom.tf/videos/upload#import-url"
}

error[2/18/2023, 2:56:41 PM] Client log: Error: Cannot fetch information from import for URL https://www.youtube.com/watch?v=tm-dXwxPRMw

{
  "tags": [
    "client"
  ],
  "username": "tio",
  "userAgent": "Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/110.0",
  "url": "https://videos.trom.tf/videos/upload#import-url"
}
```

### Describe the expected behavior

Should work.

### Additional information

* PeerTube instance:
  * URL: https://videos.trom.tf/
  * Version: 	5.0.1
  * NodeJS version:
  * Ffmpeg version:

**Comment by Chocobozzz** [comment]
Hello,

It seems to be an issue with yt-dlp

**Comment by frankstrater** [comment]
@Chocobozzz @tio-trom It's actually an issue with yt-dlp and youtube-dl as YouTube is changing the metadata (the `uploader id` field). 

Update yt-dlp to it's latest release (youtube-dl fix is not released yet). See: https://github.com/yt-dlp/yt-dlp#update

**Comment by tio-trom** [comment]
I tried to update but it says:

```
Latest version: 2023.02.17, Current version: 2023.02.17
yt-dlp is up to date (2023.02.17)
```

**Comment by tio-trom** [comment]
Ok maybe it got updated more recently. Now it works....

**Comment by frankstrater** [comment]
I forgot yt-dlp is auto-updating daily in PeerTube. No need for a manual update.
