### ISSUE TITLE
Video import does not work in the nightly build

### ISSUE THREAD

**Issue by Alterak** [Chocobozzz/PeerTube#5633]
### Describe the current behavior

When I try to import a video from Youtube, I get an error

**Cannot fetch information from import for URL https://youtu.be/OMexwXfIBD4** 

Also, users of my instance began to complain about such an error.

```
error[19.02.2023, 12:16:02] An error occurred while importing the video https://youtu.be/OMexwXfIBD4.
{
  "err": {
    "stack": "Error: Command failed with exit code 1: /usr/bin/python3 /var/www/peertube/storage/bin/yt-dlp --dump-json -f bestvideo[vcodec^=avc1][height=1440]+bestaudio[ext=m4a]/bestvideo[vcodec!*=av01][vcodec!*=vp9.2][height=1440]+bestaudio/bestvideo[vcodec^=avc1][height<=1440]+bestaudio[ext=m4a]/bestvideo[vcodec!*=av01][vcodec!*=vp9.2]+bestaudio/best[vcodec!*=av01][vcodec!*=vp9.2]/bestvideo[ext=mp4]+bestaudio[ext=m4a]/best https://youtu.be/OMexwXfIBD4\nERROR: [youtube] OMexwXfIBD4: Unable to extract uploader id; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U\n    at makeError (/var/www/peertube/versions/peertube-nightly-2023-02-19/node_modules/execa/lib/error.js:60:11)\n    at handlePromise (/var/www/peertube/versions/peertube-nightly-2023-02-19/node_modules/execa/index.js:118:26)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)",
    "message": "Cannot fetch information from import for URL https://youtu.be/OMexwXfIBD4",
    "code": 0,
    "cause": {
      "stack": "Error: Command failed with exit code 1: /usr/bin/python3 /var/www/peertube/storage/bin/yt-dlp --dump-json -f bestvideo[vcodec^=avc1][height=1440]+bestaudio[ext=m4a]/bestvideo[vcodec!*=av01][vcodec!*=vp9.2][height=1440]+bestaudio/bestvideo[vcodec^=avc1][height<=1440]+bestaudio[ext=m4a]/bestvideo[vcodec!*=av01][vcodec!*=vp9.2]+bestaudio/best[vcodec!*=av01][vcodec!*=vp9.2]/bestvideo[ext=mp4]+bestaudio[ext=m4a]/best https://youtu.be/OMexwXfIBD4\nERROR: [youtube] OMexwXfIBD4: Unable to extract uploader id; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U\n    at makeError (/var/www/peertube/versions/peertube-nightly-2023-02-19/node_modules/execa/lib/error.js:60:11)\n    at handlePromise (/var/www/peertube/versions/peertube-nightly-2023-02-19/node_modules/execa/index.js:118:26)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)",
      "message": "Command failed with exit code 1: /usr/bin/python3 /var/www/peertube/storage/bin/yt-dlp --dump-json -f bestvideo[vcodec^=avc1][height=1440]+bestaudio[ext=m4a]/bestvideo[vcodec!*=av01][vcodec!*=vp9.2][height=1440]+bestaudio/bestvideo[vcodec^=avc1][height<=1440]+bestaudio[ext=m4a]/bestvideo[vcodec!*=av01][vcodec!*=vp9.2]+bestaudio/best[vcodec!*=av01][vcodec!*=vp9.2]/bestvideo[ext=mp4]+bestaudio[ext=m4a]/best https://youtu.be/OMexwXfIBD4\nERROR: [youtube] OMexwXfIBD4: Unable to extract uploader id; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U",
      "shortMessage": "Command failed with exit code 1: /usr/bin/python3 /var/www/peertube/storage/bin/yt-dlp --dump-json -f bestvideo[vcodec^=avc1][height=1440]+bestaudio[ext=m4a]/bestvideo[vcodec!*=av01][vcodec!*=vp9.2][height=1440]+bestaudio/bestvideo[vcodec^=avc1][height<=1440]+bestaudio[ext=m4a]/bestvideo[vcodec!*=av01][vcodec!*=vp9.2]+bestaudio/best[vcodec!*=av01][vcodec!*=vp9.2]/bestvideo[ext=mp4]+bestaudio[ext=m4a]/best https://youtu.be/OMexwXfIBD4",
      "command": "/usr/bin/python3 /var/www/peertube/storage/bin/yt-dlp --dump-json -f bestvideo[vcodec^=avc1][height=1440]+bestaudio[ext=m4a]/bestvideo[vcodec!*=av01][vcodec!*=vp9.2][height=1440]+bestaudio/bestvideo[vcodec^=avc1][height<=1440]+bestaudio[ext=m4a]/bestvideo[vcodec!*=av01][vcodec!*=vp9.2]+bestaudio/best[vcodec!*=av01][vcodec!*=vp9.2]/bestvideo[ext=mp4]+bestaudio[ext=m4a]/best https://youtu.be/OMexwXfIBD4",
      "escapedCommand": "\"/usr/bin/python3\" \"/var/www/peertube/storage/bin/yt-dlp\" --dump-json -f \"bestvideo[vcodec^=avc1][height=1440]+bestaudio[ext=m4a]/bestvideo[vcodec!*=av01][vcodec!*=vp9.2][height=1440]+bestaudio/bestvideo[vcodec^=avc1][height<=1440]+bestaudio[ext=m4a]/bestvideo[vcodec!*=av01][vcodec!*=vp9.2]+bestaudio/best[vcodec!*=av01][vcodec!*=vp9.2]/bestvideo[ext=mp4]+bestaudio[ext=m4a]/best\" \"https://youtu.be/OMexwXfIBD4\"",
      "exitCode": 1,
      "stdout": "",
      "stderr": "ERROR: [youtube] OMexwXfIBD4: Unable to extract uploader id; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U",
      "failed": true,
      "timedOut": false,
      "isCanceled": false,
      "killed": false
    }
  }
}
```

### Additional information

* PeerTube instance:
  * URL: https://video.ustim.ru
  * Version: 5.0.1-nightly-2023-02-18
  * NodeJS version: v16.19.0
  * Ffmpeg version: 4.3.5-0+deb11u1

**Comment by Alterak** [comment]
I deleted the yt-dlp file from the /storage/bin/ directory, then re-imported it from Youtube - now everything works fine.
It would be nice to check the version of the yt-dlp file before importing, and if there is an updated version, then download it.
