### ISSUE TITLE
CloudFlare r2 object storage not working

### ISSUE THREAD

**Issue by aeharding** [Chocobozzz/PeerTube#5636]
### Describe the current behavior

Uploading a new video to object storage is failing with the following log:

```
Job: 12
Type: move-to-object-storage
Processed on 2/20/23, 5:21:11.784 PM
Finished on 2/20/23, 5:21:11.798 PM

{
  "videoUUID": "ff7dcfeb-a882-46e1-bdcb-e9f6947a1a2c",
  "isNewVideo": true,
  "previousVideoState": 2
}

Error: EntityTooSmall: Your proposed upload partsize [1] is smaller than the minimum allowed size [5242880] (5MB)
    at Upload.__validateInput (/var/www/peertube/versions/peertube-v5.0.1/node_modules/@aws-sdk/lib-storage/dist-cjs/Upload.js:263:19)
    at new Upload (/var/www/peertube/versions/peertube-v5.0.1/node_modules/@aws-sdk/lib-storage/dist-cjs/Upload.js:30:14)
    at /var/www/peertube/versions/peertube-v5.0.1/dist/server/lib/object-storage/shared/object-storage-helpers.js:145:34
    at Generator.next (<anonymous>)
    at /var/www/peertube/versions/peertube-v5.0.1/node_modules/tslib/tslib.js:118:75
    at new Promise (<anonymous>)
    at Object.__awaiter (/var/www/peertube/versions/peertube-v5.0.1/node_modules/tslib/tslib.js:114:16)
    at uploadToStorage (/var/www/peertube/versions/peertube-v5.0.1/dist/server/lib/object-storage/shared/object-storage-helpers.js:137:20)
    at /var/www/peertube/versions/peertube-v5.0.1/dist/server/lib/object-storage/shared/object-storage-helpers.js:37:16
    at Generator.next (<anonymous>)
    at /var/www/peertube/versions/peertube-v5.0.1/node_modules/tslib/tslib.js:118:75
    at new Promise (<anonymous>)
    at Object.__awaiter (/var/www/peertube/versions/peertube-v5.0.1/node_modules/tslib/tslib.js:114:16)
    at storeObject (/var/www/peertube/versions/peertube-v5.0.1/dist/server/lib/object-storage/shared/object-storage-helpers.js:33:20)
    at storeHLSFileFromFilename (/var/www/peertube/versions/peertube-v5.0.1/dist/server/lib/object-storage/videos.js:17:37)
    at /var/www/peertube/versions/peertube-v5.0.1/dist/server/lib/job-queue/handlers/move-to-object-storage.js:85:69
    at Generator.next (<anonymous>)
    at /var/www/peertube/versions/peertube-v5.0.1/node_modules/tslib/tslib.js:118:75
    at new Promise (<anonymous>)
    at Object.__awaiter (/var/www/peertube/versions/peertube-v5.0.1/node_modules/tslib/tslib.js:114:16)
    at moveHLSFiles (/var/www/peertube/versions/peertube-v5.0.1/dist/server/lib/job-queue/handlers/move-to-object-storage.js:78:20)
    at Object.<anonymous> (/var/www/peertube/versions/peertube-v5.0.1/dist/server/lib/job-queue/handlers/move-to-object-storage.js:35:23)
    at Generator.next (<anonymous>)
    at fulfilled (/var/www/peertube/versions/peertube-v5.0.1/node_modules/tslib/tslib.js:115:62)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

### Steps to reproduce

1. Hook up a new CloudFlare r2 bucket to a peertube instance
2. Try to upload a video
3. See it fails to move over

### Describe the expected behavior

It should succeed

**Comment by aeharding** [comment]
I figured out the problem. I changed `max_upload_part` from `100MB` to `1G` and that broke things. Adding on the "B" fixed it (I'm now using `2GB`).
