### ISSUE TITLE
Jabascript browser errors after upgrade

### ISSUE THREAD

**Issue by DevPGSV** [Chocobozzz/PeerTube#5666]
### Describe the problem

After upgrading to the latest version, the site is broken. Some basic things still work, but most of the menu buttons are not loading. The browser DevTools console displays a lot of error.

I was previously on version 4.3.0 (docker installation), and everything was working as expected.
I upgraded to 5.0.1 (`chocobozzz/peertube:production-bullseye`), executed migrations and added the required new config.
I see no errors in the server logs.
When not logged in, the site works as expected.
As soon as a user logs in, the site breaks:
![image](https://user-images.githubusercontent.com/5631093/222608651-c0e127d0-4588-4e88-9225-0484ef0562b3.png)

And the DevTools conosle gets spammed with errors (always the same error, repetaed many times):
![image](https://user-images.githubusercontent.com/5631093/222608763-bc420078-5096-4152-a529-139dcef7a76f.png)

```
ERROR TypeError: Cannot read properties of undefined (reading 'includes')
    at h (main.da8e138bdd0c64bb.js:3:573008)
    at f.hasRight (main.da8e138bdd0c64bb.js:3:24272)
    at be.getFirstAdminRightAvailable (main.da8e138bdd0c64bb.js:3:246077)
    at be.computeAdminAccess (main.da8e138bdd0c64bb.js:3:248138)
    at be.updateUserState (main.da8e138bdd0c64bb.js:3:248760)
    at be.ngOnInit (main.da8e138bdd0c64bb.js:3:244978)
    at Jo (main.da8e138bdd0c64bb.js:3:752791)
    at _r (main.da8e138bdd0c64bb.js:3:752622)
    at lo (main.da8e138bdd0c64bb.js:3:752342)
    at vc (main.da8e138bdd0c64bb.js:3:786874)
```

From what I am able to see in the DevTools, this code:
```javascript
hasRight(v) {
    return (0,
    p.k)(this.role, v)
}
```
Calls this code:
```javascript
function h(d, p) {
    const f = r[d];
    return f.includes(0) || f.includes(p)
}
```
The value of `d` is `{ "id": 0, "label": "Administrator"}`
But the array `r` contains numbers as keys: `{"0":[0],"1":[12,6,13,14,15,16,17,20,10,11,1,21],"2":[]}`
`f` end up being undefined, and then `f.includes()` gives an error.

### Additional information

* PeerTube instance URL: https://peertube.librelabucm.org/
* PeerTube version: `5.0.1` (`chocobozzz/peertube:production-bullseye`)
* NodeJS version: 
* Ffmpeg version:
* Redis version: `redis:6-alpine`
* PostgreSQL version: `postgres:13-alpine`

**Comment by Chocobozzz** [comment]
Hello,

Please follow https://docs.joinpeertube.org/install/docker#upgrade when you upgrade using Docker. In particular `docker-compose down -v`

**Comment by DevPGSV** [comment]
I have upgraded peertube several times, and for some reason this time I completely forgot to do that (with `-v`).
Sorry for starting this issue, and thank you for your help.
