### ISSUE TITLE
4.3.0 -> 5.0.1 failure

### ISSUE THREAD

**Issue by mro** [Chocobozzz/PeerTube#5668]
### Describe the problem

```sh
$ cd /var/www/peertube/peertube-latest/scripts && sudo -H -u peertube ./upgrade.sh
...
     # Create a prometheus exporter server on this port so prometheus server can scrape PeerTube metrics
     prometheus_exporter:
+      hostname: '127.0.0.1'
       port: 9091

   tracing:
@@ -567,6 +590,9 @@
     # Number of latest published videos to check and to potentially import when syncing a channel
     videos_limit_per_synchronization: 10

+    # Max number of videos to import when the user asks for full sync
+    full_sync_videos_limit: 1000
+
 auto_blacklist:
   # New videos automatically blacklisted so moderators can review before publishing
   videos:
@@ -648,7 +674,8 @@
   robots: |
     User-agent: *
     Disallow:
-  # Security.txt rules. To discourage researchers from testing your instance and disable security.txt integration, set this to an empty string
+  # /.well-known/security.txt rules. This endpoint is cached, so you may have to wait a few hours before viewing your changes
+  # To discourage researchers from testing your instance and disable security.txt integration, set this to an empty string
   securitytxt:
     '# If you would like to report a security issue\n# you may report it to:\nContact: https://github.com/Chocobozzz/PeerTube/blob/develop/SECURITY.md\nContact: mailto:'
```

After this the instance is 502, Bad Gateway.

```sh
$ tail -n 13 /var/www/peertube/versions/peertube-v5.0.1/node_modules/simple-swizzle/node_modules/is-arrayish/yarn-error.log
  Error: Command failed.
  Exit code: 1
  Command: sh
  Arguments: -c mocha --require coffeescript/register
  Directory: /src/qix-/node-is-arrayish
  Output:

      at ProcessTermError.MessageError (/Users/junon/.yarn/lib/cli.js:186:110)
      at new ProcessTermError (/Users/junon/.yarn/lib/cli.js:226:113)
      at ChildProcess.<anonymous> (/Users/junon/.yarn/lib/cli.js:30281:17)
      at ChildProcess.emit (events.js:127:13)
      at maybeClose (internal/child_process.js:933:16)
      at Process.ChildProcess._handle.onexit (internal/child_process.js:220:5)
```

https://github.com/Chocobozzz/PeerTube/issues/5454 didn't help.

How to proceed?

### Additional information

* PeerTube instance URL: https://video.qdrei.info.mro.name
* PeerTube version: 4.3.0 -> 5.0.1
* NodeJS version: v18.14.2
* Ffmpeg version: ffmpeg version 4.3.5-0+deb11u1
* Redis version:  v=6.0.16 sha=00000000:0 malloc=jemalloc-5.2.1 bits=64 build=6d95e1af3a2c082a
* PostgreSQL version: 13.9 (Debian 13.9-0+deb11u1)

**Comment by mro** [comment]
meanwhile I resorted to the 'Prefer manual upgrade?' (which I don't) and did the

> Copy new configuration defaults values and update your configuration file:

and edited the config until the diff brought only deliberately changed settings as diff.

Then

```sh
sudo systemctl restart peertube && sudo journalctl -fu peertube
```

brought PeerTube 5.0.1 up.

**Comment by mro** [comment]
A console output hint at it's end (not scrolling out of sight) would have been useful.
