### ISSUE TITLE
Video removed after upload 

### ISSUE THREAD

**Issue by kontrollanten** [Chocobozzz/PeerTube#5812]
### Describe the current behavior

Sometimes when we upload a video and click on "Publish" we're getting the following error.

Sorry, but something went wrong
Video not found

The call that's failing is `PUT /api/v1/videos/{id}`. Then the video has disappeared.

### Steps to reproduce

With object storage enabled:

1. Upload a video with privacy Private
2. Unclick "Publish when transcoding is done"
3. Click on "Publish"

### Additional information

* PeerTube instance:
  * Version: 5.1.0

* Browser name, version and platforms on which you could reproduce the bug: Latest Brave

Not sure whether this is related:

```
{
	"err": "TypeError: Expected a string but received a null
    at assertString (/var/www/peertube/versions/peertube-v5.1.0/node_modules/validator/lib/util/assertString.js:17:11)
    at Object.isInt (/var/www/peertube/versions/peertube-v5.1.0/node_modules/validator/lib/isInt.js:16:29)
    at Function.<anonymous> (/var/www/peertube/versions/peertube-v5.1.0/dist/server/lib/client-html.js:44:38)
    at Generator.next (<anonymous>)
    at /var/www/peertube/versions/peertube-v5.1.0/node_modules/tslib/tslib.js:167:75
    at new Promise (<anonymous>)
    at Object.__awaiter (/var/www/peertube/versions/peertube-v5.1.0/node_modules/tslib/tslib.js:163:16)
    at Function.getWatchHTMLPage (/var/www/peertube/versions/peertube-v5.1.0/dist/server/lib/client-html.js:42:24)
    at /var/www/peertube/versions/peertube-v5.1.0/dist/server/controllers/client.js:101:53
    at Generator.next (<anonymous>)
    at /var/www/peertube/versions/peertube-v5.1.0/node_modules/tslib/tslib.js:167:75
    at new Promise (<anonymous>)
    at Object.__awaiter (/var/www/peertube/versions/peertube-v5.1.0/node_modules/tslib/tslib.js:163:16)
    at generateWatchHtmlPage (/var/www/peertube/versions/peertube-v5.1.0/dist/server/controllers/client.js:96:20)
    at /var/www/peertube/versions/peertube-v5.1.0/dist/server/middlewares/async.js:21:32
    at Layer.handle [as handle_request] (/var/www/peertube/versions/peertube-v5.1.0/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/var/www/peertube/versions/peertube-v5.1.0/node_modules/express/lib/router/index.js:328:13)
    at /var/www/peertube/versions/peertube-v5.1.0/node_modules/express/lib/router/index.js:286:9
    at param (/var/www/peertube/versions/peertube-v5.1.0/node_modules/express/lib/router/index.js:365:14)
    at param (/var/www/peertube/versions/peertube-v5.1.0/node_modules/express/lib/router/index.js:376:14)
    at param (/var/www/peertube/versions/peertube-v5.1.0/node_modules/express/lib/router/index.js:376:14)
    at Function.process_params (/var/www/peertube/versions/peertube-v5.1.0/node_modules/express/lib/router/index.js:421:3)
    at next (/var/www/peertube/versions/peertube-v5.1.0/node_modules/express/lib/router/index.js:280:10)
    at Function.handle (/var/www/peertube/versions/peertube-v5.1.0/node_modules/express/lib/router/index.js:175:3)
    at router (/var/www/peertube/versions/peertube-v5.1.0/node_modules/express/lib/router/index.js:47:12)
    at Layer.handle [as handle_request] (/var/www/peertube/versions/peertube-v5.1.0/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/var/www/peertube/versions/peertube-v5.1.0/node_modules/express/lib/router/index.js:328:13)
    at /var/www/peertube/versions/peertube-v5.1.0/node_modules/express/lib/router/index.js:286:9",
	"level": "error",
	"message": "Error in controller.",
	"label": "",
	"timestamp": "2023-05-29T07:43:11.670Z"
}
```

**Comment by Chocobozzz** [comment]
> The call that's failing is PUT /api/v1/videos/{id}. Then the video has disappeared.

You should have an error in server, can you paste it?

> Not sure whether this is related:

Don't hesitate to create issues when you see errors in peertube logs :) Can you provide the HTTP call that led to this error?

**Comment by SventuraOscura** [comment]
Same problem here,

Issue is even when you fail to upload a video, or delete it.

If the filename is the same, it will say "unknown error" everytime, or video not found.

Where can i delete the history of uploaded videos?, i tried deleting cache, and files from server, but nothing works.

**Comment by RinCat** [comment]
I have the same issue. 
This happened when I deleted exists video, and re-upload it. It seems the program think it is a resume of old video that try to reuse deleted video metadata / ID.

**Comment by Chocobozzz** [comment]
Thanks! This bug should be fixed by https://github.com/Chocobozzz/PeerTube/commit/1fb7d094229acdc190c3f7551b43ac5445814dee, https://github.com/Chocobozzz/PeerTube/commit/926c3f2b377196af1e8c5725aa54b8077cb79061 and https://github.com/Chocobozzz/PeerTube/commit/6bd160a68dac55f61b28c7631f9985320daf7755
