### ISSUE TITLE
Error: WebSocket is not open: readyState 2 (CLOSING)

### ISSUE THREAD

**Issue by kontrollanten** [Chocobozzz/PeerTube#5823]
### Describe the current behavior

We see a lot of those warnings in our logs: `Error: WebSocket is not open: readyState 2 (CLOSING)`. Is it something broken or is it expected to happen during some circumstances? 

```
{
	"err": {
		"stack": "Error: WebSocket is not open: readyState 2 (CLOSING)\n    at sendAfterClose (/var/www/peertube/versions/peertube-v5.1.0/node_modules/ws/lib/websocket.js:1097:17)\n    at WebSocket.send (/var/www/peertube/versions/peertube-v5.1.0/node_modules/ws/lib/websocket.js:453:7)\n    at /var/www/peertube/versions/peertube-v5.1.0/node_modules/bittorrent-tracker/server.js:487:16\n    at /var/www/peertube/versions/peertube-v5.1.0/node_modules/bittorrent-tracker/server.js:643:25\n    at Server.<anonymous> (/var/www/peertube/versions/peertube-v5.1.0/dist/server/controllers/tracker.js:56:17)\n    at Generator.next (<anonymous>)\n    at fulfilled (/var/www/peertube/versions/peertube-v5.1.0/node_modules/tslib/tslib.js:164:62)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)",
		"message": "WebSocket is not open: readyState 2 (CLOSING)"
	},
	"level": "warn",
	"message": "Warning in tracker.",
	"label": "",
	"timestamp": "2023-06-06T20:03:00.343Z"
}
```

### Additional information

* PeerTube instance:
  * Version: 5.1.0

**Comment by Chocobozzz** [comment]
Hi,

I don't know when it can happen but this doesn't hurt. If you manage to find how to reproduce don't hesitate to comment so we can try to fix the log at its root

**Comment by Chocobozzz** [comment]
Closing due to inactivity. Don't hesitate to comment if you have some news :)
