### ISSUE TITLE
Cannot import youtube video

### ISSUE THREAD

**Issue by tio-trom** [Chocobozzz/PeerTube#5865]
### Describe the current behavior

I tried with some random videos I get these:

```
Error[6/30/2023, 10:51:28 PM] An error occurred while importing the video https://www.youtube.com/watch?v=8lidVXkoBPk.

{
  "err": {
    "stack": "Error: Command failed with exit code 1: /usr/bin/python3 /home/yunohost.app/peertube/storage/bin/yt-dlp --dump-json -f bestvideo[vcodec^=avc1][height=1080]+bestaudio[ext=m4a]/bestvideo[vcodec!*=av01][vcodec!*=vp9.2][height=1080]+bestaudio/bestvideo[vcodec^=avc1][height<=1080]+bestaudio[ext=m4a]/bestvideo[vcodec!*=av01][vcodec!*=vp9.2]+bestaudio/best[vcodec!*=av01][vcodec!*=vp9.2]/bestvideo[ext=mp4]+bestaudio[ext=m4a]/best https://www.youtube.com/watch?v=8lidVXkoBPk\nWARNING: [youtube] Unable to download webpage: HTTP Error 429: Too Many Requests\nWARNING: [youtube] Skipping player response from ios client (got player response for video \"M5t4UHllkUM\" instead of \"8lidVXkoBPk\"); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U\nWARNING: [youtube] Skipping player response from android client (got player response for video \"M5t4UHllkUM\" instead of \"8lidVXkoBPk\"); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U\nWARNING: [youtube] Skipping player response from web client (got player response for video \"M5t4UHllkUM\" instead of \"8lidVXkoBPk\"); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U\nWARNING: Extractor failed to obtain \"title\". Creating a generic title instead\nERROR: [youtube] 8lidVXkoBPk: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U\n    at makeError (/var/www/peertube/node_modules/execa/lib/error.js:60:11)\n    at handlePromise (/var/www/peertube/node_modules/execa/index.js:118:26)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)",
    "message": "Cannot fetch information from import for URL https://www.youtube.com/watch?v=8lidVXkoBPk",
    "code": 0,
    "cause": {
      "stack": "Error: Command failed with exit code 1: /usr/bin/python3 /home/yunohost.app/peertube/storage/bin/yt-dlp --dump-json -f bestvideo[vcodec^=avc1][height=1080]+bestaudio[ext=m4a]/bestvideo[vcodec!*=av01][vcodec!*=vp9.2][height=1080]+bestaudio/bestvideo[vcodec^=avc1][height<=1080]+bestaudio[ext=m4a]/bestvideo[vcodec!*=av01][vcodec!*=vp9.2]+bestaudio/best[vcodec!*=av01][vcodec!*=vp9.2]/bestvideo[ext=mp4]+bestaudio[ext=m4a]/best https://www.youtube.com/watch?v=8lidVXkoBPk\nWARNING: [youtube] Unable to download webpage: HTTP Error 429: Too Many Requests\nWARNING: [youtube] Skipping player response from ios client (got player response for video \"M5t4UHllkUM\" instead of \"8lidVXkoBPk\"); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U\nWARNING: [youtube] Skipping player response from android client (got player response for video \"M5t4UHllkUM\" instead of \"8lidVXkoBPk\"); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U\nWARNING: [youtube] Skipping player response from web client (got player response for video \"M5t4UHllkUM\" instead of \"8lidVXkoBPk\"); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U\nWARNING: Extractor failed to obtain \"title\". Creating a generic title instead\nERROR: [youtube] 8lidVXkoBPk: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U\n    at makeError (/var/www/peertube/node_modules/execa/lib/error.js:60:11)\n    at handlePromise (/var/www/peertube/node_modules/execa/index.js:118:26)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)",
      "message": "Command failed with exit code 1: /usr/bin/python3 /home/yunohost.app/peertube/storage/bin/yt-dlp --dump-json -f bestvideo[vcodec^=avc1][height=1080]+bestaudio[ext=m4a]/bestvideo[vcodec!*=av01][vcodec!*=vp9.2][height=1080]+bestaudio/bestvideo[vcodec^=avc1][height<=1080]+bestaudio[ext=m4a]/bestvideo[vcodec!*=av01][vcodec!*=vp9.2]+bestaudio/best[vcodec!*=av01][vcodec!*=vp9.2]/bestvideo[ext=mp4]+bestaudio[ext=m4a]/best https://www.youtube.com/watch?v=8lidVXkoBPk\nWARNING: [youtube] Unable to download webpage: HTTP Error 429: Too Many Requests\nWARNING: [youtube] Skipping player response from ios client (got player response for video \"M5t4UHllkUM\" instead of \"8lidVXkoBPk\"); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U\nWARNING: [youtube] Skipping player response from android client (got player response for video \"M5t4UHllkUM\" instead of \"8lidVXkoBPk\"); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U\nWARNING: [youtube] Skipping player response from web client (got player response for video \"M5t4UHllkUM\" instead of \"8lidVXkoBPk\"); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U\nWARNING: Extractor failed to obtain \"title\". Creating a generic title instead\nERROR: [youtube] 8lidVXkoBPk: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U",
      "shortMessage": "Command failed with exit code 1: /usr/bin/python3 /home/yunohost.app/peertube/storage/bin/yt-dlp --dump-json -f bestvideo[vcodec^=avc1][height=1080]+bestaudio[ext=m4a]/bestvideo[vcodec!*=av01][vcodec!*=vp9.2][height=1080]+bestaudio/bestvideo[vcodec^=avc1][height<=1080]+bestaudio[ext=m4a]/bestvideo[vcodec!*=av01][vcodec!*=vp9.2]+bestaudio/best[vcodec!*=av01][vcodec!*=vp9.2]/bestvideo[ext=mp4]+bestaudio[ext=m4a]/best https://www.youtube.com/watch?v=8lidVXkoBPk",
      "command": "/usr/bin/python3 /home/yunohost.app/peertube/storage/bin/yt-dlp --dump-json -f bestvideo[vcodec^=avc1][height=1080]+bestaudio[ext=m4a]/bestvideo[vcodec!*=av01][vcodec!*=vp9.2][height=1080]+bestaudio/bestvideo[vcodec^=avc1][height<=1080]+bestaudio[ext=m4a]/bestvideo[vcodec!*=av01][vcodec!*=vp9.2]+bestaudio/best[vcodec!*=av01][vcodec!*=vp9.2]/bestvideo[ext=mp4]+bestaudio[ext=m4a]/best https://www.youtube.com/watch?v=8lidVXkoBPk",
      "escapedCommand": "\"/usr/bin/python3\" \"/home/yunohost.app/peertube/storage/bin/yt-dlp\" --dump-json -f \"bestvideo[vcodec^=avc1][height=1080]+bestaudio[ext=m4a]/bestvideo[vcodec!*=av01][vcodec!*=vp9.2][height=1080]+bestaudio/bestvideo[vcodec^=avc1][height<=1080]+bestaudio[ext=m4a]/bestvideo[vcodec!*=av01][vcodec!*=vp9.2]+bestaudio/best[vcodec!*=av01][vcodec!*=vp9.2]/bestvideo[ext=mp4]+bestaudio[ext=m4a]/best\" \"https://www.youtube.com/watch?v=8lidVXkoBPk\"",
      "exitCode": 1,
      "stdout": "",
      "stderr": "WARNING: [youtube] Unable to download webpage: HTTP Error 429: Too Many Requests\nWARNING: [youtube] Skipping player response from ios client (got player response for video \"M5t4UHllkUM\" instead of \"8lidVXkoBPk\"); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U\nWARNING: [youtube] Skipping player response from android client (got player response for video \"M5t4UHllkUM\" instead of \"8lidVXkoBPk\"); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U\nWARNING: [youtube] Skipping player response from web client (got player response for video \"M5t4UHllkUM\" instead of \"8lidVXkoBPk\"); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U\nWARNING: Extractor failed to obtain \"title\". Creating a generic title instead\nERROR: [youtube] 8lidVXkoBPk: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U",
      "failed": true,
      "timedOut": false,
      "isCanceled": false,
      "killed": false
    }
  }
}

error[6/30/2023, 10:51:28 PM] Client log: Backend returned code 400, errorMessage is: Cannot fetch information from import for URL https://www.youtube.com/watch?v=8lidVXkoBPk

{
  "tags": [
    "client"
  ],
  "username": "tio",
  "userAgent": "Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/114.0",
  "url": "https://videos.trom.tf/videos/upload#import-url"
}

error[6/30/2023, 10:51:28 PM] Client log: Error: Cannot fetch information from import for URL https://www.youtube.com/watch?v=8lidVXkoBPk

{
  "tags": [
    "client"
  ],
  "username": "tio",
  "userAgent": "Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/114.0",
  "url": "https://videos.trom.tf/videos/upload#import-url"
}
```

Now, on the same server I have an Invidious instance that was recently banned by Google - so my server cannot access youtube so that the instance does not work. Do you think this can be the cause? If so how could I check?

Thanks!

### Steps to reproduce

As stated above.

### Describe the expected behavior

Be able to import.

### Additional information

* PeerTube instance:
  * URL: https://videos.trom.tf
  * Version: 5.2.0

**Comment by Booteille** [comment]
Hi!

I think it's probably the cause since the error coming from yt-dlp indicates you're rate limited. (`HTTP Error 429: Too Many Requests`)

**Comment by Chocobozzz** [comment]
Like @Bouteille said, there are some rate limits on youtube. Just retry a little bit later :)
