### ISSUE TITLE
Error: Configuration property "redis.db" is not defined

### ISSUE THREAD

**Issue by Angristan** [Chocobozzz/PeerTube#587]
Hello,

I'm trying to upgrade from beta 4 to beta 6 (in Docker).

Peertube fails to start:

```
> peertube@1.0.0-beta.6 start /app
> node dist/server

/app/node_modules/config/lib/config.js:202
    throw new Error('Configuration property "' + property + '" is not defined');
    ^

Error: Configuration property "redis.db" is not defined
    at Config.get (/app/node_modules/config/lib/config.js:202:11)
    at Object.<anonymous> (/app/dist/server/initializers/constants.js:111:20)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/app/dist/server/initializers/index.js:7:10)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/app/dist/server/helpers/custom-validators/users.js:6:24)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! peertube@1.0.0-beta.6 start: `node dist/server`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the peertube@1.0.0-beta.6 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

I looked at the changes but didn't find anything related to Redis. In what config file should I look?

Thanks for the help.

**Comment by rhaamo** [comment]
I think it's the "db" parameter in "redis" in the config file (```~/config/production.yaml```).

I usually do ```diff -Naur config/production.yaml peertube-latest/config/production.yaml.example``` when upgrading to check missing things.

**Comment by Angristan** [comment]
But where does it parameter come from? I don't see it here https://github.com/Chocobozzz/PeerTube/blob/master/support/docker/production/config/production.yaml

**Comment by rhaamo** [comment]
The docker file is not up to date, see: https://github.com/Chocobozzz/PeerTube/blob/master/config/production.yaml.example#L30

**Comment by Angristan** [comment]
Oh ok, thanks. The way the Peertube configuration works is really confusing...
