### ISSUE TITLE
Firefox on iOS can't play embedded video on WordPress - works in Safari

### ISSUE THREAD

**Issue by edent** [Chocobozzz/PeerTube#5930]
### Describe the current behavior

When trying to play an embedded PeerTube video in Firefox for iPhone, this error is displayed:

![Screenshot of error.](https://github.com/Chocobozzz/PeerTube/assets/837136/ae674869-72b3-4799-a5dc-41fcc773f8f8)

> Sorry. The player is not compatible with your web browser. Please try latest Firefox version.

### Steps to reproduce

1. Paste a PeerTube link into WordPress
2. WordPress converts it automatically to an embed.
1. Visit https://shkspr.mobi/blog/2023/08/review-egofit-walker-pro-an-under-desk-treadmill/ using Firefox on iOS.
3. Try to watch embedded video.
4. Video plays back properly if viewed directly, or in the Safari browser on iOS.

(Possibly related to https://github.com/Chocobozzz/PeerTube/issues/3646)

### Describe the expected behavior

Firefox on iOS uses Safari as its rendering engine - so there should be no technical reason why it can't play back embedded videos.

### Additional information

* PeerTube instance:
  * URL: https://tube.tchncs.de/
  * Version: 5.2.0
  * NodeJS version: ?
  * Ffmpeg version: ?

* Browser name, version and platforms on which you could reproduce the bug: Firefox iOS
* Link to browser console log if relevant: N/A
* Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`): N/A

HTML produced by WordPress is:
```html
<iframe data-lazyloaded="1"
               src="about:blank" 
               class="wp-embedded-content"  
               sandbox="allow-scripts"  
               security="restricted" title="EgoFit Walker Pro - First use"  
               width="560" height="315"  
               data-src="https://tube.tchncs.de/videos/embed/ce933734-5df3-4167-85da-a06490240e28#?secret=IgS3sbwplO" data-secret="IgS3sbwplO"  
               frameborder="0">
</iframe>
<noscript>
	<iframe  
               class="wp-embedded-content"  
               sandbox="allow-scripts"  
               security="restricted"  
               title="EgoFit Walker Pro - First use"  
               width="560" height="315"  
               src="https://tube.tchncs.de/videos/embed/ce933734-5df3-4167-85da-a06490240e28#?secret=IgS3sbwplO" data-secret="IgS3sbwplO"  
               frameborder="0">
          </iframe>
</noscript>
```

**Comment by Chocobozzz** [comment]
Hi,

Do you have the issue with chrome? If you're an admin of the peertube instance, can you search for client error logs in server logs? If not, maybe you can try https://discourse.mozilla.org/t/how-do-i-debug-firefox-on-ios/111414/2 to paste firefox console logs to see what happens

**Comment by Chocobozzz** [comment]
Ping @edent

**Comment by tio-trom** [comment]
Just happened to me on Linux and Firefox 117.0.1. And this article https://www.tiotrom.com/2023/09/the-zday-experience/

First time i see this...strange. Usually the embed Peertube videos either do not load or take some time to load. So sometimes it does, sometimes it doesn't.

I cannot see anything in the Peertube logs.

**Comment by Chocobozzz** [comment]
Can you contact your admin, that may have more clues in PeerTube logs?

**Comment by tio-trom** [comment]
Can we please reopen this? Here are some logs:

```
error[11/29/2023, 10:20:34 AM] Client log: Cannot send metrics to the server.

{
  "tags": [
    "client"
  ],
  "userAgent": "Mozilla/5.0 (Linux; Android 10; SM-G981U) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Mobile Safari/537.36",
  "stackTrace": "Failed to fetch\nTypeError: Failed to fetch\n    at https://videos.trom.tf/client/standalone/videos/957.401b8a7d0d1574a047bf.chunk.js:1:53400",
  "url": "https://videos.trom.tf/videos/embed/e76c0891-37db-4bd1-bf31-7f4b1d0f8042?title=0&warningTitle=0&peertubeLink=0&p2p=0"
}

error[11/29/2023, 10:20:49 AM] Client log: Cannot send metrics to the server.

{
  "tags": [
    "client"
  ],
  "userAgent": "Mozilla/5.0 (Linux; Android 10; SM-G981U) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Mobile Safari/537.36",
  "stackTrace": "Failed to fetch\nTypeError: Failed to fetch\n    at https://videos.trom.tf/client/standalone/videos/957.401b8a7d0d1574a047bf.chunk.js:1:53400",
  "url": "https://videos.trom.tf/videos/embed/e76c0891-37db-4bd1-bf31-7f4b1d0f8042?title=0&warningTitle=0&peertubeLink=0&p2p=0"
}

warn[11/29/2023, 10:20:56 AM] Client log: HLS.js error: mediaError - fatal: false - bufferStalledError

{
  "tags": [
    "client"
  ],
  "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36 Edg/117.0.2045.34",
  "url": "https://videos.trom.tf/videos/embed/e7677e0b-cadf-4da9-8a45-417eab697e32?title=0&warningTitle=0&peertubeLink=0&p2p=0"
}

error[11/29/2023, 10:20:58 AM] Client log: Segment https://videos.trom.tf/static/streaming-playlists/hls/1de03619-a444-474c-a5ec-e2ef314069dd/5167c45f-48f3-428b-9a04-351829b0f5ea-master.m3u8+V1+301 error.

{
  "tags": [
    "client"
  ],
  "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36 Edg/119.0.0.0",
  "meta": "{\"isTrusted\":true}",
  "url": "https://videos.trom.tf/w/4FYs5xEaieZt8VZizvmLCV"
}

warn[11/29/2023, 10:20:59 AM] Client log: Hls.js is not supported in this browser!

{
  "tags": [
    "client"
  ],
  "userAgent": "Mozilla/5.0 (iPhone; CPU iPhone OS 17_1_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.1.1 Mobile/15E148 Safari/604.1",
  "url": "https://videos.trom.tf/videos/embed/e7677e0b-cadf-4da9-8a45-417eab697e32?title=0&warningTitle=0&peertubeLink=0&p2p=0"
}

warn[11/29/2023, 10:21:05 AM] Client log: HLS.js error: mediaError - fatal: false - bufferStalledError

{
  "tags": [
    "client"
  ],
  "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36 Edg/119.0.0.0",
  "url": "https://videos.trom.tf/w/4FYs5xEaieZt8VZizvmLCV"
}

warn[11/29/2023, 10:21:05 AM] Client log: HLS.js error: mediaError - fatal: false - bufferNudgeOnStall

{
  "tags": [
    "client"
  ],
  "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36 Edg/119.0.0.0",
  "url": "https://videos.trom.tf/w/4FYs5xEaieZt8VZizvmLCV"
}

error[11/29/2023, 10:21:59 AM] Client log: HLS.js error: networkError - fatal: true - manifestLoadError

{
  "tags": [
    "client"
  ],
  "userAgent": "Mozilla/5.0 (Android 11; Mobile; rv:120.0) Gecko/120.0 Firefox/120.0",
  "url": "https://videos.trom.tf/videos/embed/739ca226-f1c3-407f-8717-9ae41bdedcaa?title=0&warningTitle=0&peertubeLink=0&p2p=0"
}

error[11/29/2023, 10:21:59 AM] Client log: Cannot get sha256 segments

{
  "tags": [
    "client"
  ],
  "userAgent": "Mozilla/5.0 (Android 11; Mobile; rv:120.0) Gecko/120.0 Firefox/120.0",
  "stackTrace": "NetworkError when attempting to fetch resource.\n",
  "url": "https://videos.trom.tf/videos/embed/739ca226-f1c3-407f-8717-9ae41bdedcaa?title=0&warningTitle=0&peertubeLink=0&p2p=0"
}

warn[11/29/2023, 10:22:23 AM] Warning in tracker.

{
  "err": {
    "stack": "Error: Unknown infoHash 80417fb89dcd619dbf1470a6b29c7e8f19c18f4e requested by ip 5.180.208.187\n    at Server.<anonymous> (/var/www/peertube/dist/server/controllers/tracker.js:56:20)\n    at Generator.next (<anonymous>)\n    at fulfilled (/var/www/peertube/node_modules/tslib/tslib.js:164:62)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)",
    "message": "Unknown infoHash 80417fb89dcd619dbf1470a6b29c7e8f19c18f4e requested by ip 5.180.208.187"
  }
}

warn[11/29/2023, 10:23:27 AM] Warning in tracker.

{
  "err": {
    "stack": "Error: Unknown infoHash 5481423dd2b9d0d40cdc3fb9c07dbc8aa3fdec99 requested by ip 73.26.244.64\n    at Server.<anonymous> (/var/www/peertube/dist/server/controllers/tracker.js:56:20)\n    at Generator.next (<anonymous>)\n    at fulfilled (/var/www/peertube/node_modules/tslib/tslib.js:164:62)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)",
    "message": "Unknown infoHash 5481423dd2b9d0d40cdc3fb9c07dbc8aa3fdec99 requested by ip 73.26.244.64"
  }
}

warn[11/29/2023, 10:26:07 AM] Cannot process activity View.

{
  "err": {
    "stack": "HTTPError: Response code 401 (Unauthorized)\n    at Request.<anonymous> (/var/www/peertube/node_modules/got/dist/source/as-promise/index.js:118:42)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)",
    "message": "Response code 401 (Unauthorized)",
    "name": "HTTPError",
    "responseBody": {
      "type": "https://docs.joinpeertube.org/api-rest-reference.html#section/Errors/unauthorized_request",
      "detail": "Token is invalid",
      "status": 401,
      "code": "unauthorized_request",
      "error": "Token is invalid"
    },
    "responseHeaders": {
      "server": "nginx/1.22.1",
      "date": "Wed, 29 Nov 2023 09:26:07 GMT",
      "content-type": "application/problem+json; charset=utf-8",
      "content-length": "198",
      "connection": "close",
      "x-powered-by": "PeerTube",
      "x-frame-options": "DENY",
      "tk": "N",
      "access-control-allow-origin": "*",
      "x-ratelimit-limit": "500",
      "x-ratelimit-remaining": "499",
      "x-ratelimit-reset": "1701249978",
      "etag": "W/\"c6-VISJGJ9CHnyoAze/BqxAlZMg+sk\"",
      "cache-control": "max-age=1"
    },
    "statusCode": 401
  }
}

error[11/29/2023, 10:26:36 AM] Client log: Cannot send metrics to the server.

{
  "tags": [
    "client"
  ],
  "userAgent": "Mozilla/5.0 (Linux; Android 10; SM-G981U) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Mobile Safari/537.36",
  "stackTrace": "Failed to fetch\nTypeError: Failed to fetch\n    at https://videos.trom.tf/client/standalone/videos/957.401b8a7d0d1574a047bf.chunk.js:1:53400",
  "url": "https://videos.trom.tf/videos/embed/739ca226-f1c3-407f-8717-9ae41bdedcaa?title=0&warningTitle=0&peertubeLink=0&p2p=0"
}

error[11/29/2023, 10:26:51 AM] Client log: Cannot send metrics to the server.

{
  "tags": [
    "client"
  ],
  "userAgent": "Mozilla/5.0 (Linux; Android 10; SM-G981U) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Mobile Safari/537.36",
  "stackTrace": "Failed to fetch\nTypeError: Failed to fetch\n    at https://videos.trom.tf/client/standalone/videos/957.401b8a7d0d1574a047bf.chunk.js:1:53400",
  "url": "https://videos.trom.tf/videos/embed/739ca226-f1c3-407f-8717-9ae41bdedcaa?title=0&warningTitle=0&peertubeLink=0&p2p=0"
}

error[11/29/2023, 10:27:07 AM] Client log: Cannot send metrics to the server.

{
  "tags": [
    "client"
  ],
  "userAgent": "Mozilla/5.0 (Linux; Android 10; SM-G981U) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Mobile Safari/537.36",
  "stackTrace": "Failed to fetch\nTypeError: Failed to fetch\n    at https://videos.trom.tf/client/standalone/videos/957.401b8a7d0d1574a047bf.chunk.js:1:53400",
  "url": "https://videos.trom.tf/videos/embed/739ca226-f1c3-407f-8717-9ae41bdedcaa?title=0&warningTitle=0&peertubeLink=0&p2p=0"
}

error[11/29/2023, 10:27:21 AM] Failed to import https://www.youtube.com/channel/UCptT6M7CuShGSX3k6F6HhPg in channel Merch.bio

{
  "err": {
    "stack": "Error: Command failed with exit code 1: /usr/bin/python3 /home/yunohost.app/peertube/storage/bin/yt-dlp --force-ipv4 --skip-download --playlist-reverse --flat-playlist --playlist-end 10 --dump-json -f bestvideo[vcodec^=avc1][height=720]+bestaudio[ext=m4a]/bestvideo[vcodec!*=av01][vcodec!*=vp9.2][height=720]+bestaudio/bestvideo[vcodec^=avc1][height<=720]+bestaudio[ext=m4a]/bestvideo[vcodec!*=av01][vcodec!*=vp9.2]+bestaudio/best[vcodec!*=av01][vcodec!*=vp9.2]/bestvideo[ext=mp4]+bestaudio[ext=m4a]/best https://www.youtube.com/channel/UCptT6M7CuShGSX3k6F6HhPg\nERROR: [youtube:tab] UCptT6M7CuShGSX3k6F6HhPg: This channel has no uploads\n    at makeError (/var/www/peertube/node_modules/execa/lib/error.js:60:11)\n    at handlePromise (/var/www/peertube/node_modules/execa/index.js:118:26)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)",
    "message": "Command failed with exit code 1: /usr/bin/python3 /home/yunohost.app/peertube/storage/bin/yt-dlp --force-ipv4 --skip-download --playlist-reverse --flat-playlist --playlist-end 10 --dump-json -f bestvideo[vcodec^=avc1][height=720]+bestaudio[ext=m4a]/bestvideo[vcodec!*=av01][vcodec!*=vp9.2][height=720]+bestaudio/bestvideo[vcodec^=avc1][height<=720]+bestaudio[ext=m4a]/bestvideo[vcodec!*=av01][vcodec!*=vp9.2]+bestaudio/best[vcodec!*=av01][vcodec!*=vp9.2]/bestvideo[ext=mp4]+bestaudio[ext=m4a]/best https://www.youtube.com/channel/UCptT6M7CuShGSX3k6F6HhPg\nERROR: [youtube:tab] UCptT6M7CuShGSX3k6F6HhPg: This channel has no uploads",
    "shortMessage": "Command failed with exit code 1: /usr/bin/python3 /home/yunohost.app/peertube/storage/bin/yt-dlp --force-ipv4 --skip-download --playlist-reverse --flat-playlist --playlist-end 10 --dump-json -f bestvideo[vcodec^=avc1][height=720]+bestaudio[ext=m4a]/bestvideo[vcodec!*=av01][vcodec!*=vp9.2][height=720]+bestaudio/bestvideo[vcodec^=avc1][height<=720]+bestaudio[ext=m4a]/bestvideo[vcodec!*=av01][vcodec!*=vp9.2]+bestaudio/best[vcodec!*=av01][vcodec!*=vp9.2]/bestvideo[ext=mp4]+bestaudio[ext=m4a]/best https://www.youtube.com/channel/UCptT6M7CuShGSX3k6F6HhPg",
    "command": "/usr/bin/python3 /home/yunohost.app/peertube/storage/bin/yt-dlp --force-ipv4 --skip-download --playlist-reverse --flat-playlist --playlist-end 10 --dump-json -f bestvideo[vcodec^=avc1][height=720]+bestaudio[ext=m4a]/bestvideo[vcodec!*=av01][vcodec!*=vp9.2][height=720]+bestaudio/bestvideo[vcodec^=avc1][height<=720]+bestaudio[ext=m4a]/bestvideo[vcodec!*=av01][vcodec!*=vp9.2]+bestaudio/best[vcodec!*=av01][vcodec!*=vp9.2]/bestvideo[ext=mp4]+bestaudio[ext=m4a]/best https://www.youtube.com/channel/UCptT6M7CuShGSX3k6F6HhPg",
    "escapedCommand": "\"/usr/bin/python3\" \"/home/yunohost.app/peertube/storage/bin/yt-dlp\" --force-ipv4 --skip-download --playlist-reverse --flat-playlist --playlist-end 10 --dump-json -f \"bestvideo[vcodec^=avc1][height=720]+bestaudio[ext=m4a]/bestvideo[vcodec!*=av01][vcodec!*=vp9.2][height=720]+bestaudio/bestvideo[vcodec^=avc1][height<=720]+bestaudio[ext=m4a]/bestvideo[vcodec!*=av01][vcodec!*=vp9.2]+bestaudio/best[vcodec!*=av01][vcodec!*=vp9.2]/bestvideo[ext=mp4]+bestaudio[ext=m4a]/best\" \"https://www.youtube.com/channel/UCptT6M7CuShGSX3k6F6HhPg\"",
    "exitCode": 1,
    "stdout": "",
    "stderr": "ERROR: [youtube:tab] UCptT6M7CuShGSX3k6F6HhPg: This channel has no uploads",
    "failed": true,
    "timedOut": false,
    "isCanceled": false,
    "killed": false
  }
}

error[11/29/2023, 10:27:22 AM] Client log: Cannot send metrics to the server.

{
  "tags": [
    "client"
  ],
  "userAgent": "Mozilla/5.0 (Linux; Android 10; SM-G981U) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Mobile Safari/537.36",
  "stackTrace": "Failed to fetch\nTypeError: Failed to fetch\n    at https://videos.trom.tf/client/standalone/videos/957.401b8a7d0d1574a047bf.chunk.js:1:53400",
  "url": "https://videos.trom.tf/videos/embed/739ca226-f1c3-407f-8717-9ae41bdedcaa?title=0&warningTitle=0&peertubeLink=0&p2p=0"
}

warn[11/29/2023, 10:27:31 AM] Warning in tracker.

{
  "err": {
    "stack": "Error: Unknown infoHash 5481423dd2b9d0d40cdc3fb9c07dbc8aa3fdec99 requested by ip 73.26.244.64\n    at Server.<anonymous> (/var/www/peertube/dist/server/controllers/tracker.js:56:20)\n    at Generator.next (<anonymous>)\n    at fulfilled (/var/www/peertube/node_modules/tslib/tslib.js:164:62)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)",
    "message": "Unknown infoHash 5481423dd2b9d0d40cdc3fb9c07dbc8aa3fdec99 requested by ip 73.26.244.64"
  }
}

warn[11/29/2023, 10:27:35 AM] Warning in tracker.

{
  "err": {
    "stack": "Error: Unknown infoHash 80417fb89dcd619dbf1470a6b29c7e8f19c18f4e requested by ip 5.180.208.187\n    at Server.<anonymous> (/var/www/peertube/dist/server/controllers/tracker.js:56:20)\n    at Generator.next (<anonymous>)\n    at fulfilled (/var/www/peertube/node_modules/tslib/tslib.js:164:62)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)",
    "message": "Unknown infoHash 80417fb89dcd619dbf1470a6b29c7e8f19c18f4e requested by ip 5.180.208.187"
  }
}

error[11/29/2023, 10:29:54 AM] Client log: Cannot send metrics to the server.

{
  "tags": [
    "client"
  ],
  "userAgent": "Mozilla/5.0 (Linux; Android 10; SM-G981U) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Mobile Safari/537.36",
  "stackTrace": "Failed to fetch\nTypeError: Failed to fetch\n    at https://videos.trom.tf/client/standalone/videos/957.401b8a7d0d1574a047bf.chunk.js:1:53400",
  "url": "https://videos.trom.tf/videos/embed/739ca226-f1c3-407f-8717-9ae41bdedcaa?title=0&warningTitle=0&peertubeLink=0&p2p=0"
}

error[11/29/2023, 10:30:50 AM] Client log: Cannot send metrics to the server.

{
  "tags": [
    "client"
  ],
  "userAgent": "Mozilla/5.0 (Linux; Android 10; SM-G981U) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Mobile Safari/537.36",
  "stackTrace": "Failed to fetch\nTypeError: Failed to fetch\n    at https://videos.trom.tf/client/standalone/videos/957.401b8a7d0d1574a047bf.chunk.js:1:53400",
  "url": "https://videos.trom.tf/videos/embed/739ca226-f1c3-407f-8717-9ae41bdedcaa?title=0&warningTitle=0&peertubeLink=0&p2p=0"
}

warn[11/29/2023, 10:31:05 AM] Cannot resolve thread https://freespeechextremist.com/objects/5339db4c-97bf-47e5-b481-890ce9c59885.

{
  "err": {
    "stack": "HTTPError: Response code 404 (Not Found)\n    at Request.<anonymous> (/var/www/peertube/node_modules/got/dist/source/as-promise/index.js:118:42)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)",
    "message": "Response code 404 (Not Found)",
    "name": "HTTPError",
    "responseBody": "Not found",
    "responseHeaders": {
      "server": "nginx/1.12.2",
      "date": "Wed, 29 Nov 2023 09:31:05 GMT",
      "content-type": "application/json; charset=utf-8",
      "content-length": "11",
      "connection": "close",
      "access-control-allow-credentials": "true",
      "access-control-allow-origin": "*",
      "access-control-expose-headers": "Link,X-RateLimit-Reset,X-RateLimit-Limit,X-RateLimit-Remaining,X-Request-Id,Idempotency-Key",
      "cache-control": "max-age=0, private, must-revalidate",
      "content-security-policy": "upgrade-insecure-requests;script-src 'self';connect-src 'self' blob: https://freespeechextremist.com wss://freespeechextremist.com;media-src 'self' https:;img-src 'self' data: blob: https:;default-src 'none';base-uri 'self';frame-ancestors 'none';style-src 'self' 'unsafe-inline';font-src 'self';manifest-src 'self';",
      "referrer-policy": "same-origin, same-origin",
      "x-content-type-options": "nosniff, nosniff",
      "x-download-options": "noopen, noopen",
      "x-frame-options": "DENY, DENY",
      "x-permitted-cross-domain-policies": "none, none",
      "x-request-id": "F5wOGkqeAQxcbfoKQ2th",
      "x-xss-protection": "1; mode=block, 1; mode=block"
    },
    "statusCode": 404
  }
}

warn[11/29/2023, 10:31:05 AM] Cannot resolve thread https://freespeechextremist.com/objects/cb445bf4-d4e0-4e18-b7f1-e852ed292102.

{
  "err": {
    "stack": "HTTPError: Response code 404 (Not Found)\n    at Request.<anonymous> (/var/www/peertube/node_modules/got/dist/source/as-promise/index.js:118:42)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)",
    "message": "Response code 404 (Not Found)",
    "name": "HTTPError",
    "responseBody": "Not found",
    "responseHeaders": {
      "server": "nginx/1.12.2",
      "date": "Wed, 29 Nov 2023 09:31:05 GMT",
      "content-type": "application/json; charset=utf-8",
      "content-length": "11",
      "connection": "close",
      "access-control-allow-credentials": "true",
      "access-control-allow-origin": "*",
      "access-control-expose-headers": "Link,X-RateLimit-Reset,X-RateLimit-Limit,X-RateLimit-Remaining,X-Request-Id,Idempotency-Key",
      "cache-control": "max-age=0, private, must-revalidate",
      "content-security-policy": "upgrade-insecure-requests;script-src 'self';connect-src 'self' blob: https://freespeechextremist.com wss://freespeechextremist.com;media-src 'self' https:;img-src 'self' data: blob: https:;default-src 'none';base-uri 'self';frame-ancestors 'none';style-src 'self' 'unsafe-inline';font-src 'self';manifest-src 'self';",
      "referrer-policy": "same-origin, same-origin",
      "x-content-type-options": "nosniff, nosniff",
      "x-download-options": "noopen, noopen",
      "x-frame-options": "DENY, DENY",
      "x-permitted-cross-domain-policies": "none, none",
      "x-request-id": "F5wOGm3tIEblWV4KQ21B",
      "x-xss-protection": "1; mode=block, 1; mode=block"
    },
    "statusCode": 404
  }
}

warn[11/29/2023, 10:31:09 AM] Cannot resolve thread https://videos.lukesmith.xyz/videos/watch/5e0eeac4-2b38-450c-aad6-eb601087686e/comments/6749.

{
  "err": {
    "stack": "HTTPError: Response code 404 (Not Found)\n    at Request.<anonymous> (/var/www/peertube/node_modules/got/dist/source/as-promise/index.js:118:42)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)",
    "message": "Response code 404 (Not Found)",
    "name": "HTTPError",
    "responseBody": "Not found",
    "responseHeaders": {
      "server": "nginx/1.12.2",
      "date": "Wed, 29 Nov 2023 09:31:09 GMT",
      "content-type": "application/json; charset=utf-8",
      "content-length": "11",
      "connection": "close",
      "access-control-allow-credentials": "true",
      "access-control-allow-origin": "*",
      "access-control-expose-headers": "Link,X-RateLimit-Reset,X-RateLimit-Limit,X-RateLimit-Remaining,X-Request-Id,Idempotency-Key",
      "cache-control": "max-age=0, private, must-revalidate",
      "content-security-policy": "upgrade-insecure-requests;script-src 'self';connect-src 'self' blob: https://freespeechextremist.com wss://freespeechextremist.com;media-src 'self' https:;img-src 'self' data: blob: https:;default-src 'none';base-uri 'self';frame-ancestors 'none';style-src 'self' 'unsafe-inline';font-src 'self';manifest-src 'self';",
      "referrer-policy": "same-origin, same-origin",
      "x-content-type-options": "nosniff, nosniff",
      "x-download-options": "noopen, noopen",
      "x-frame-options": "DENY, DENY",
      "x-permitted-cross-domain-policies": "none, none",
      "x-request-id": "F5wOGzmmR8S932YKQ3Kh",
      "x-xss-protection": "1; mode=block, 1; mode=block"
    },
    "statusCode": 404
  }
}

warn[11/29/2023, 10:31:13 AM] Warning in tracker.

{
  "err": {
    "stack": "Error: Unknown infoHash 5481423dd2b9d0d40cdc3fb9c07dbc8aa3fdec99 requested by ip 73.26.244.64\n    at Server.<anonymous> (/var/www/peertube/dist/server/controllers/tracker.js:56:20)\n    at Generator.next (<anonymous>)\n    at fulfilled (/var/www/peertube/node_modules/tslib/tslib.js:164:62)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)",
    "message": "Unknown infoHash 5481423dd2b9d0d40cdc3fb9c07dbc8aa3fdec99 requested by ip 73.26.244.64"
  }
}

error[11/29/2023, 10:31:21 AM] Client log: Cannot send metrics to the server.

{
  "tags": [
    "client"
  ],
  "userAgent": "Mozilla/5.0 (Linux; Android 10; SM-G981U) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Mobile Safari/537.36",
  "stackTrace": "Failed to fetch\nTypeError: Failed to fetch\n    at https://videos.trom.tf/client/standalone/videos/957.401b8a7d0d1574a047bf.chunk.js:1:53400",
  "url": "https://videos.trom.tf/videos/embed/739ca226-f1c3-407f-8717-9ae41bdedcaa?title=0&warningTitle=0&peertubeLink=0&p2p=0"
}

warn[11/29/2023, 10:31:43 AM] Warning in tracker.

{
  "err": {
    "stack": "Error: Unknown infoHash 9c2f77a53c92e2b7246ab21db4978f06fbaa96cd requested by ip 5.180.208.187\n    at Server.<anonymous> (/var/www/peertube/dist/server/controllers/tracker.js:56:20)\n    at Generator.next (<anonymous>)\n    at fulfilled (/var/www/peertube/node_modules/tslib/tslib.js:164:62)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)",
    "message": "Unknown infoHash 9c2f77a53c92e2b7246ab21db4978f06fbaa96cd requested by ip 5.180.208.187"
  }
}

warn[11/29/2023, 10:33:30 AM] Client log: Hls.js is not supported in this browser!

{
  "tags": [
    "client"
  ],
  "userAgent": "Mozilla/5.0 (iPhone; CPU iPhone OS 17_1_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.1.1 Mobile/15E148 Safari/604.1",
  "url": "https://videos.trom.tf/w/p/fVpfZ9VfWrWawHkggKi7Wz"
}

warn[11/29/2023, 10:34:38 AM] Warning in tracker.

{
  "err": {
    "stack": "Error: Unknown infoHash 64ba428cc297e28f2235b567346ed4fa4dd8d080 requested by ip 73.26.244.64\n    at Server.<anonymous> (/var/www/peertube/dist/server/controllers/tracker.js:56:20)\n    at Generator.next (<anonymous>)\n    at fulfilled (/var/www/peertube/node_modules/tslib/tslib.js:164:62)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)",
    "message": "Unknown infoHash 64ba428cc297e28f2235b567346ed4fa4dd8d080 requested by ip 73.26.244.64"
  }
}

warn[11/29/2023, 10:35:49 AM] Warning in tracker.

{
  "err": {
    "stack": "Error: Unknown infoHash 9c2f77a53c92e2b7246ab21db4978f06fbaa96cd requested by ip 5.180.208.187\n    at Server.<anonymous> (/var/www/peertube/dist/server/controllers/tracker.js:56:20)\n    at Generator.next (<anonymous>)\n    at fulfilled (/var/www/peertube/node_modules/tslib/tslib.js:164:62)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)",
    "message": "Unknown infoHash 9c2f77a53c92e2b7246ab21db4978f06fbaa96cd requested by ip 5.180.208.187"
  }
}

warn[11/29/2023, 10:37:54 AM] Client log: HLS.js error: mediaError - fatal: false - bufferStalledError

{
  "tags": [
    "client"
  ],
  "userAgent": "Mozilla/5.0 (Android 11; Mobile; rv:120.0) Gecko/120.0 Firefox/120.0",
  "url": "https://videos.trom.tf/videos/embed/e76c0891-37db-4bd1-bf31-7f4b1d0f8042?title=0&warningTitle=0&peertubeLink=0&p2p=0"
}

error[11/29/2023, 10:38:00 AM] Client log: Cannot lock screen to landscape.

{
  "tags": [
    "client"
  ],
  "userAgent": "Mozilla/5.0 (Android 11; Mobile; rv:120.0) Gecko/120.0 Firefox/120.0",
  "stackTrace": "The operation is insecure.\n7957/handleFullscreenRotation/<@https://videos.trom.tf/client/standalone/videos/957.401b8a7d0d1574a047bf.chunk.js:1:44999\n3654/ut/r.dispatcher@https://videos.trom.tf/client/standalone/videos/video-embed.5ade45fd9b6520a16871.bundle.js:2:79585\n",
  "url": "https://videos.trom.tf/videos/embed/e76c0891-37db-4bd1-bf31-7f4b1d0f8042?title=0&warningTitle=0&peertubeLink=0&p2p=0"
}

warn[11/29/2023, 10:38:12 AM] Warning in tracker.

{
  "err": {
    "stack": "Error: Unknown infoHash 811c0614f76f24a705b7b3903182d4d81efae7bf requested by ip 73.26.244.64\n    at Server.<anonymous> (/var/www/peertube/dist/server/controllers/tracker.js:56:20)\n    at Generator.next (<anonymous>)\n    at fulfilled (/var/www/peertube/node_modules/tslib/tslib.js:164:62)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)",
    "message": "Unknown infoHash 811c0614f76f24a705b7b3903182d4d81efae7bf requested by ip 73.26.244.64"
  }
}
```

**Comment by Chocobozzz** [comment]
@ChanoSan root cause of the issue is https://github.com/Chocobozzz/PeerTube/issues/6083
