### ISSUE TITLE
Peertube.service: Failed with result ‘exit-code’

### ISSUE THREAD

**Issue by PYU224** [Chocobozzz/PeerTube#5933]
### Describe the problem

When I try to start PeerTube and try "sudo journalctl -feu peertube", I get this message and can't access the site.
Do you know the reason?

```

Aug 10 21:23:40 ubuntu systemd[1]: peertube.service: Failed with result 'exit-code'.
Aug 10 21:23:40 ubuntu systemd[1]: peertube.service: Consumed 5.375s CPU time.
Aug 10 21:23:40 ubuntu systemd[1]: peertube.service: Scheduled restart job, restart counter is at 48.
Aug 10 21:23:40 ubuntu systemd[1]: Stopped PeerTube daemon.
Aug 10 21:23:40 ubuntu systemd[1]: peertube.service: Consumed 5.375s CPU time.
Aug 10 21:23:40 ubuntu systemd[1]: Started PeerTube daemon.
Aug 10 21:23:45 ubuntu peertube[35459]: [arcadia.video:443] 2023-08-10 21:23:45.259 info: Using following configuration file hierarchy: /var/www/peertube/config/default.yaml -> /var/www/peertube/config/production.yaml.
Aug 10 21:23:45 ubuntu peertube[35459]: [arcadia.video:443] 2023-08-10 21:23:45.263 error: Config error. {
Aug 10 21:23:45 ubuntu peertube[35459]:   "err": {
Aug 10 21:23:45 ubuntu peertube[35459]:     "stack": "Error: secrets.peertube is missing in config. Generate one using `openssl rand -hex 32`\n    at checkSecretsConfig (/var/www/peertube/versions/peertube-v5.2.0/dist/server/initializers/checker-after-init.js:88:15)\n    at checkConfig (/var/www/peertube/versions/peertube-v5.2.0/dist/server/initializers/checker-after-init.js:37:5)\n    at Object.<anonymous> (/var/www/peertube/versions/peertube-v5.2.0/dist/server.js:39:42)\n    at Module._compile (node:internal/modules/cjs/loader:1233:14)\n    at Module._extensions..js (node:internal/modules/cjs/loader:1287:10)\n    at Module.load (node:internal/modules/cjs/loader:1091:32)\n    at Module._load (node:internal/modules/cjs/loader:938:12)\n    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:83:12)\n    at node:internal/main/run_main_module:23:47",
Aug 10 21:23:45 ubuntu peertube[35459]:     "message": "secrets.peertube is missing in config. Generate one using `openssl rand -hex 32`"
Aug 10 21:23:45 ubuntu peertube[35459]:   }
Aug 10 21:23:45 ubuntu peertube[35459]: }
Aug 10 21:23:45 ubuntu systemd[1]: peertube.service: Main process exited, code=exited, status=255/EXCEPTION
Aug 10 21:23:45 ubuntu systemd[1]: peertube.service: Failed with result 'exit-code'.
Aug 10 21:23:45 ubuntu systemd[1]: peertube.service: Consumed 5.358s CPU time.
Aug 10 21:23:45 ubuntu systemd[1]: peertube.service: Scheduled restart job, restart counter is at 49.
Aug 10 21:23:45 ubuntu systemd[1]: Stopped PeerTube daemon.
Aug 10 21:23:45 ubuntu systemd[1]: peertube.service: Consumed 5.358s CPU time.
Aug 10 21:23:45 ubuntu systemd[1]: Started PeerTube daemon.
Aug 10 21:23:50 ubuntu peertube[35470]: [arcadia.video:443] 2023-08-10 21:23:50.041 info: Using following configuration file hierarchy: /var/www/peertube/config/default.yaml -> /var/www/peertube/config/production.yaml.
Aug 10 21:23:50 ubuntu peertube[35470]: [arcadia.video:443] 2023-08-10 21:23:50.046 error: Config error. {
Aug 10 21:23:50 ubuntu peertube[35470]:   "err": {
Aug 10 21:23:50 ubuntu peertube[35470]:     "stack": "Error: secrets.peertube is missing in config. Generate one using `openssl rand -hex 32`\n    at checkSecretsConfig (/var/www/peertube/versions/peertube-v5.2.0/dist/server/initializers/checker-after-init.js:88:15)\n    at checkConfig (/var/www/peertube/versions/peertube-v5.2.0/dist/server/initializers/checker-after-init.js:37:5)\n    at Object.<anonymous> (/var/www/peertube/versions/peertube-v5.2.0/dist/server.js:39:42)\n    at Module._compile (node:internal/modules/cjs/loader:1233:14)\n    at Module._extensions..js (node:internal/modules/cjs/loader:1287:10)\n    at Module.load (node:internal/modules/cjs/loader:1091:32)\n    at Module._load (node:internal/modules/cjs/loader:938:12)\n    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:83:12)\n    at node:internal/main/run_main_module:23:47",
Aug 10 21:23:50 ubuntu peertube[35470]:     "message": "secrets.peertube is missing in config. Generate one using `openssl rand -hex 32`"
Aug 10 21:23:50 ubuntu peertube[35470]:   }
Aug 10 21:23:50 ubuntu peertube[35470]: }
```

### Additional information

* PeerTube version: 5.2.0
* NodeJS version: 20.5
* Ffmpeg version: 7:4.4.2-0ubuntu0.22.04.1
* Redis version: 6.0.16 sha=00000000:0 malloc=jemalloc-5.2.1 bits=64 build=a3fdef44459b3ad6
* PostgreSQL version: Ubuntu 14.8-0ubuntu0.22.04.1)

**Comment by Chocobozzz** [comment]
Is it a new install? If yes, have you followed the documentation? In particular: https://docs.joinpeertube.org/install/any-os#peertube-configuration

**Comment by PYU224** [comment]
This is a new installation.
I didn't know how to set config/production.yaml specifically, so I just set the webserver to my domain.

**Comment by Chocobozzz** [comment]
Then you need to edit your `config/production.yaml` file :)

**Comment by PYU224** [comment]
I didn't set a secret.
Sorry for the elementary question, but what does `stack": "Error: secrets.peertube is missing in config. Generate one using `openssl rand -hex 32` mean?

**Comment by dhk2** [comment]
Enter the command at a command prompt to generate the secret like so:

        peertube@peertube:~$ openssl rand -hex 32
        aa0028db310b0a58f7e4dea25932e91823d91c67f4b58981d514ca3f4a2bf6ac
        peertube@peertube:~$

Then edit the production yaml and put that long string in for the peertube value:

        # Secrets you need to generate the first time you run PeerTube
        secrets:
          # Generate one using `openssl rand -hex 32`
          peertube: 'aa0028db310b0a58f7e4dea25932e91823d91c67f4b58981d514ca3f4a2bf6ac'

**Comment by TimMapes** [comment]
Just downloaded this image from docker hub and it will not run. So how are you supposed to fix this?

Sorry for the elementary question, but what does stack": "Error: secrets.peertube is missing in config. Generate one using openssl rand -hex 32` mean?

Where would I edit and run if I cannot start the image??

    # Secrets you need to generate the first time you run PeerTube
    secrets:
      # Generate one using `openssl rand -hex 32`
      peertube: 'aa0028db310b0a58f7e4dea25932e91823d91c67f4b58981d514ca3f4a2bf6ac'
