### ISSUE TITLE
Click on "About" button and... JS error

### ISSUE THREAD

**Issue by ROBERT-MCDOWELL** [Chocobozzz/PeerTube#5943]
### Describe the current behavior

sometimes when I click on "About" link/button the About page shows.
but sometimes not and a JS console error shows:

main.18895fd6dd4b2857.js:3 ERROR Error: Uncaught (in promise): TypeError: Cannot read properties of undefined (reading 'label')
TypeError: Cannot read properties of undefined (reading 'label')
    at main.18895fd6dd4b2857.js:3:402472
    at Array.map (<anonymous>)
    at main.18895fd6dd4b2857.js:3:402419
    at main.18895fd6dd4b2857.js:3:636444
    at m._next (main.18895fd6dd4b2857.js:3:633101)
    at m.next (main.18895fd6dd4b2857.js:3:622284)
    at m.onFinalize (main.18895fd6dd4b2857.js:3:628180)
    at m.unsubscribe (main.18895fd6dd4b2857.js:3:633500)
    at m._complete (main.18895fd6dd4b2857.js:3:633306)
    at m.complete (main.18895fd6dd4b2857.js:3:622463)
    at At (polyfills.737628ee7146c22a.js:1:78294)
    at At (polyfills.737628ee7146c22a.js:1:77822)
    at polyfills.737628ee7146c22a.js:1:79148
    at i.invokeTask (polyfills.737628ee7146c22a.js:1:69444)
    at Object.onInvokeTask (main.18895fd6dd4b2857.js:3:872082)
    at i.invokeTask (polyfills.737628ee7146c22a.js:1:69365)
    at lt.runTask (polyfills.737628ee7146c22a.js:1:64752)
    at H (polyfills.737628ee7146c22a.js:1:71489)
    at c.invokeTask [as invoke] (polyfills.737628ee7146c22a.js:1:70533)
    at T (polyfills.737628ee7146c22a.js:1:83281)

**Comment by Chocobozzz** [comment]
Please fill the [bug template](https://github.com/Chocobozzz/PeerTube/blob/develop/.github/ISSUE_TEMPLATE/00-bug-issue.md), in particular your instance URL

**Comment by ROBERT-MCDOWELL** [comment]
don't understand what you mean with the link you provided which is also broken.
I restart an issue so
