### ISSUE TITLE
Click on "About" generates a JS error

### ISSUE THREAD

**Issue by ROBERT-MCDOWELL** [Chocobozzz/PeerTube#5945]
### Describe the current behavior

sometimes when I click on "About" link/button the About page shows.

### Steps to reproduce

1. click on "about"

### Describe the expected behavior

must show the About page

### Additional information

* PeerTube instance:
  * URL: https://secure.scanovid.com
  * Version: 5.2.0
  * NodeJS version: 18.17.1
  * Ffmpeg version: 6.0

* Browser name, version and platforms on which you could reproduce the bug:
ALL

* Server log errors:
{"tags":["client"],"userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36","url":"https://secure.scanovid.com/verify-account/email?userId=585&verificationString=91e3af503068cad9fbce7e9b7ee05a0f063a5d7f4859670d919e9fcf161d83f9","level":"error","message":"Client log: Error: Invalid verification string.","label":"secure.scanovid.com:443","timestamp":"2023-08-03T04:18:07.815Z"}
{"tags":["client"],"userAgent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10.10; rv:78.0) Gecko/20100101 Firefox/78.0","stackTrace":"NetworkError when attempting to fetch resource.\n","url":"https://secure.scanovid.com/w/b28c2fe3-f34c-477f-b48d-64304b0bcbc6","level":"error","message":"Client log: Cannot send metrics to the server.","label":"secure.scanovid.com:443","timestamp":"2023-08-03T14:35:35.033Z"}
{"tags":["client"],"userAgent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10.10; rv:78.0) Gecko/20100101 Firefox/78.0","stackTrace":"NetworkError when attempting to fetch resource.\n","url":"https://secure.scanovid.com/w/b28c2fe3-f34c-477f-b48d-64304b0bcbc6","level":"error","message":"Client log: Cannot send metrics to the server.","label":"secure.scanovid.com:443","timestamp":"2023-08-03T14:35:48.621Z"}

* JS error:
main.18895fd6dd4b2857.js:3 ERROR Error: Uncaught (in promise): TypeError: Cannot read properties of undefined (reading 'label')
TypeError: Cannot read properties of undefined (reading 'label')
at main.18895fd6dd4b2857.js:3:402472
at Array.map ()
at main.18895fd6dd4b2857.js:3:402419
at main.18895fd6dd4b2857.js:3:636444
at m._next (main.18895fd6dd4b2857.js:3:633101)
at m.next (main.18895fd6dd4b2857.js:3:622284)
at m.onFinalize (main.18895fd6dd4b2857.js:3:628180)
at m.unsubscribe (main.18895fd6dd4b2857.js:3:633500)
at m._complete (main.18895fd6dd4b2857.js:3:633306)
at m.complete (main.18895fd6dd4b2857.js:3:622463)
at At (polyfills.737628ee7146c22a.js:1:78294)
at At (polyfills.737628ee7146c22a.js:1:77822)
at polyfills.737628ee7146c22a.js:1:79148
at i.invokeTask (polyfills.737628ee7146c22a.js:1:69444)
at Object.onInvokeTask (main.18895fd6dd4b2857.js:3:872082)
at i.invokeTask (polyfills.737628ee7146c22a.js:1:69365)
at lt.runTask (polyfills.737628ee7146c22a.js:1:64752)
at H (polyfills.737628ee7146c22a.js:1:71489)
at c.invokeTask [as invoke] (polyfills.737628ee7146c22a.js:1:70533)
at T (polyfills.737628ee7146c22a.js:1:83281)

**Comment by Chocobozzz** [comment]
Thanks, it should be fixed by https://github.com/Chocobozzz/PeerTube/commit/4d3ea87486e095aa7934888b66443cfce6804894

**Comment by ROBERT-MCDOWELL** [comment]
@Chocobozzz 
just updated to 5.2.1 but seems to persist :(
[1694027890887.log](https://github.com/Chocobozzz/PeerTube/files/12541582/1694027890887.log)

**Comment by Chocobozzz** [comment]
The fix will be included in v6 :)
