### ISSUE TITLE
5.2.1 incompatible with nodejs 20.6.0

### ISSUE THREAD

**Issue by vid-bin** [Chocobozzz/PeerTube#5966]
### Describe the current behavior

Please note that 5.2.1 source cannot be built with 20.6.0 nodejs.

```
peertube@gentoo ~/versions/PeerTube-5.2.1 $ npm run build

> peertube@5.2.1 build
> bash ./scripts/build/index.sh


> peertube@5.2.1 concurrently
> concurrently --raw npm run build:client npm run build:server


> peertube@5.2.1 build:server
> bash ./scripts/build/server.sh


> peertube@5.2.1 build:client
> bash ./scripts/build/client.sh


> peertube@5.2.1 tsc
> tsc -b --verbose

[2:02:14 PM] Projects in this build: 
    * shared/tsconfig.json
    * server/tsconfig.json
    * scripts/tsconfig.json
    * tsconfig.json

[2:02:14 PM] Project 'shared/tsconfig.json' is out of date because output file 'dist/shared/tsconfig.tsbuildinfo' does not exist

[2:02:14 PM] Building project '/var/www/peertube/versions/PeerTube-5.2.1/shared/tsconfig.json'...

An unhandled exception occurred: Unable to load translation file parsers. Please ensure '@angular/localize' is installed.
See "/tmp/ng-yuFudz/angular-errors.log" for further details.
/var/www/peertube/versions/PeerTube-5.2.1/client/node_modules/@babel/core/lib/index.js:7
Object.defineProperty(exports, "File", {
       ^

TypeError: Cannot redefine property: File
    at Function.defineProperty (<anonymous>)
    at Object.<anonymous> (/var/www/peertube/versions/PeerTube-5.2.1/client/node_modules/@babel/core/lib/index.js:7:8)
    at Module._compile (node:internal/modules/cjs/loader:1241:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1295:10)
    at Module.load (node:internal/modules/cjs/loader:1091:32)
    at Module._load (node:internal/modules/cjs/loader:938:12)
    at Module.require (node:internal/modules/cjs/loader:1115:19)
    at require (node:internal/modules/helpers:130:18)
    at Object.<anonymous> (/var/www/peertube/versions/PeerTube-5.2.1/client/node_modules/@babel/core/lib/config/helpers/config-api.js:16:9)
    at Module._compile (node:internal/modules/cjs/loader:1241:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1295:10)
    at Module.load (node:internal/modules/cjs/loader:1091:32)
    at Module._load (node:internal/modules/cjs/loader:938:12)
    at Module.require (node:internal/modules/cjs/loader:1115:19)
    at require (node:internal/modules/helpers:130:18)
    at Object.<anonymous> (/var/www/peertube/versions/PeerTube-5.2.1/client/node_modules/@babel/core/lib/config/files/configuration.js:48:18)

Node.js v20.6.0
[2:02:16 PM] Project 'server/tsconfig.json' is out of date because output file 'dist/server/tsconfig.tsbuildinfo' does not exist

[2:02:16 PM] Building project '/var/www/peertube/versions/PeerTube-5.2.1/server/tsconfig.json'...

[2:02:30 PM] Project 'scripts/tsconfig.json' is out of date because output file 'dist/scripts/tsconfig.tsbuildinfo' does not exist

[2:02:30 PM] Building project '/var/www/peertube/versions/PeerTube-5.2.1/scripts/tsconfig.json'...

[2:02:31 PM] Project 'tsconfig.json' is out of date because output file 'dist/tsconfig.tsbuildinfo' does not exist

[2:02:31 PM] Building project '/var/www/peertube/versions/PeerTube-5.2.1/tsconfig.json'...


> peertube@5.2.1 resolve-tspaths:server
> npm run resolve-tspaths -- --project tsconfig.json --src . --out dist


> peertube@5.2.1 resolve-tspaths
> resolve-tspaths --project tsconfig.json --src . --out dist

resolve-tspaths: changed 1012 file(s)
peertube@gentoo ~/versions/PeerTube-5.2.1 $ 
```

**Comment by vid-bin** [comment]
It can build with nodejs 20.5.1.

**Comment by wickloww** [comment]
Hi, it seems to be a node.js issue. Please upgrade to node 20.6.1 version, it should fix the problem.

**Comment by wickloww** [comment]
Hi, this seems to be a node.js issue. Please upgrade to node version 20.6.1, which should solve the problem.
