### ISSUE TITLE
Postgres database not connecting in Docker

### ISSUE THREAD

**Issue by xxwhirlpool** [Chocobozzz/PeerTube#6012]
### Describe the problem

I installed through docker compose. I'm trying to deploy the server locally for testing, but after 9 hours of work, I can't connect the postgres database to the server through the docker containers.

Here is my docker-compose.yaml file:
https://pastebin.com/raw/XLrEHz2B

My .env file:
https://pastebin.com/raw/jGLdwwk7

The error shown when entering "docker logs "peertubepls-peertube-1" in the command line:
`[192.168.1.179:9000] 2023-10-23 23:44:54.926 info: Using following configuration file hierarchy: /app/config/default.yaml -> /app/support/docker/production/config/production.yaml -> /app/support/docker/production/config/custom-environment-variables.yaml.
[192.168.1.179:9000] 2023-10-23 23:44:55.231 error: Unable to connect to PostgreSQL database. {
  "err": {
    "stack": "SequelizeConnectionRefusedError: connect ECONNREFUSED 192.168.0.3:5433\n    at Client._connectionCallback (/app/node_modules/sequelize/lib/dialects/postgres/connection-manager.js:131:24)\n    at Client._handleErrorWhileConnecting (/app/node_modules/pg/lib/client.js:327:19)\n    at Client._handleErrorEvent (/app/node_modules/pg/lib/client.js:337:19)\n    at Connection.emit (node:events:513:28)\n    at Socket.reportStreamError (/app/node_modules/pg/lib/connection.js:58:12)\n    at Socket.emit (node:events:513:28)\n    at emitErrorNT (node:internal/streams/destroy:157:8)\n    at emitErrorCloseNT (node:internal/streams/destroy:122:3)\n    at processTicksAndRejections (node:internal/process/task_queues:83:21)",
    "message": "connect ECONNREFUSED 192.168.0.3:5433",
    "name": "SequelizeConnectionRefusedError",
    "parent": {
      "stack": "Error: connect ECONNREFUSED 192.168.0.3:5433\n    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1278:16)",
      "message": "connect ECONNREFUSED 192.168.0.3:5433",
      "errno": -111,
      "code": "ECONNREFUSED",
      "syscall": "connect",
      "address": "192.168.0.3",
      "port": 5433
    }
  }
}
`

Apologies if anything is unclear or if I've done something wrong. Any help is appreciated as I've been at this for hours. Thank you.

### Additional information

* PeerTube instance URL:
* PeerTube version: 
* NodeJS version: v21.0.0
* Ffmpeg version: 4.4.2
* Redis version: 
* PostgreSQL version: 13 (?)

**Comment by xxwhirlpool** [comment]
This fixed itself (or I did something right and didn't realize), and the server seems to be running properly through docker now, but I can't seem to access it locally via the host name and port in my browser. It hangs indefinitely and curl returns an "Empty response from server" error.

Is this expected behavior? Thanks.
