### ISSUE TITLE
EACCES: permission denied, mkdir '/home/kat/peertubepls/storage/logs'

### ISSUE THREAD

**Issue by xxwhirlpool** [Chocobozzz/PeerTube#6015]
### Describe the problem

Hi, I previously posted an issue for a problem which I've since resolved. However, starting Peertube through docker compose now gives me the following permissions error:

`Error: EACCES: permission denied, mkdir '/home/kat/peertubepls/storage/logs'
     at Object.mkdirSync (node:fs:1382:3)
     at File._createLogDirIfNotExist (/app/node_modules/winston/lib/winston/transports/file.js:691:10)
     at new File (/app/node_modules/winston/lib/winston/transports/file.js:92:28)
     at buildLogger (/app/dist/server/helpers/logger.js:68:13)
     at Object.<anonymous> (/app/dist/server/helpers/logger.js:78:16)
     at Module._compile (node:internal/modules/cjs/loader:1198:14)
     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1252:10)
     at Module.load (node:internal/modules/cjs/loader:1076:32)
     at Function.Module._load (node:internal/modules/cjs/loader:911:12)
     at Module.require (node:internal/modules/cjs/loader:1100:19) {
   errno: -13,
   syscall: 'mkdir',
   code: 'EACCES',
   path: '/home/kat/peertubepls/storage/logs'
 }
`

I've given the appropriate permissions to each folder in the project folder. I've been stuck at this step for hours.

I'm not running a snap-installed docker and I have tried every solution I could find online. I asked in a docker discord and was told this is a Peertube container issue. Any help is appreciated even if it's not a Peertube problem. Thank you.

### Additional information

* PeerTube instance URL:
* PeerTube version:
* NodeJS version:
* Ffmpeg version:
* Redis version:
* PostgreSQL version:

**Comment by Chocobozzz** [comment]
Closing this issue as you opened a post on the forum: https://framacolibri.org/t/eacces-permission-denied-mkdir-home-kat-peertubepls-storage-logs/19345
