### ISSUE TITLE
Unable to Upload Videos

### ISSUE THREAD

**Issue by MattyBoombalatty** [Chocobozzz/PeerTube#6028]
### Describe the current behavior

After upgrading to 6.0.0-rc1, then downgrading back to 5.2.1, I am unable to upload videos. It looks like there's some sort of issue with one of the node modules. Please note that I have completely reinstalled PeerTube (saving only the `/storage` directory) and the issue persists.

```
Nov 13 16:20:28 ncd-peertube peertube[2803]: [nicecrew.tv:443] 2023-11-13 16:20:28.290 error: Error in controller. {
Nov 13 16:20:28 ncd-peertube peertube[2803]:   "err": "Error\n    at Query.run (/var/www/peertube/versions/peertube-v5.2.1/node_modules/sequelize/lib/dialects/postgres/query.js:50:25)\n    at /var/www/peertube/versions/peertube-v5.2.1/node_modules/sequelize/lib/sequelize.js:315:28\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async PostgresQueryInterface.insert (/var/www/peertube/versions/peertube-v5.2.1/node_modules/sequelize/lib/dialects/abstract/query-interface.js:308:21)\n    at async ThumbnailModel.save (/var/www/peertube/versions/peertube-v5.2.1/node_modules/sequelize/lib/model.js:2490:35)"
Nov 13 16:20:28 ncd-peertube peertube[2803]: } - INSERT INTO "thumbnail" ("id","filename","height","width","type","fileUrl","automaticallyGenerated","videoId","createdAt","updatedAt") VALUES (DEFAULT,$1,$2,$3,$4,$5,$6,$7,$8,$9) RETURNING "id","filename","height","width","type","fileUrl","automaticallyGenerated","videoId","videoPlaylistId","createdAt","updatedAt";
Nov 13 16:20:28 ncd-peertube peertube[2803]: [nicecrew.tv:443] 2023-11-13 16:20:28.297 info: - - [13/Nov/2023:16:20:28 +0000] "PUT /api/v1/videos/upload-resumable?upload_id=af63af4c8601a015-a77757e9212eb0a4-d8013424ae8f0219-585a3d99c76dde08 HTTP/1.0" 500 431 "https://nicecrew.tv/videos/upload" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36"
```

### Steps to reproduce

1. Upgrade PeerTube to 6.0.0-rc1
2. Downgrade to PeerTube 5.2.1
3. Try to upload videos.

### Describe the expected behavior

I should be able to upload videos.

### Additional information

* PeerTube instance:
  * URL: https://nicecrew.tv
  * Version: 5.2.1
  * NodeJS version: 18.18.2
  * Ffmpeg version: 4.4.2

* Browser name, version and platforms on which you could reproduce the bug:
* Link to browser console log if relevant:
* Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`):

**Comment by MattyBoombalatty** [comment]
Log from the database server:

```
2023-11-13 16:40:30.940 UTC [1781859] pleroma@pleroma STATEMENT:  UPDATE "users" SET "follower_address" = $1, "last_refreshed_at" = $2, "name" = $3, "nickname" = $4, "updated_at" = $5 WHERE "id" = $6
2023-11-13 16:41:08.019 UTC [1843701] peertube@peertube_prod ERROR:  null value in column "onDisk" of relation "thumbnail" violates not-null constraint
2023-11-13 16:41:08.019 UTC [1843701] peertube@peertube_prod DETAIL:  Failing row contains (12850, a4ecd71a-0f7c-4aae-8ea4-1a36df11f65b.jpg, 157, 280, 1, null, t, 6455, null, 2023-11-13 16:41:08.014+00, 2023-11-13 16:41:08.014+00, null).
2023-11-13 16:41:08.019 UTC [1843701] peertube@peertube_prod STATEMENT:  INSERT INTO "thumbnail" ("id","filename","height","width","type","fileUrl","automaticallyGenerated","videoId","createdAt","updatedAt") VALUES (DEFAULT,$1,$2,$3,$4,$5,$6,$7,$8,$9) RETURNING "id","filename","height","width","type","fileUrl","automaticallyGenerated","videoId","videoPlaylistId","createdAt","updatedAt";
2023-11-13 16:44:57.039 UTC [1643370] LOG:  checkpoint complete: wrote 5795 buffers (0.6%); 0 WAL file(s) added, 0 removed, 3 recycled; write=269.932 s, sync=0.021 s, total=269.960 s; sync files=297, longest=0.003 s, average=0.001 s; distance=51484 kB, estimate=51930 kB
```

**Comment by MattyBoombalatty** [comment]
Upon further investigation, I am going to guess that the database schema changed with the pre-release version. I'm going to try to upgrade again so I don't have to wipe my database and start new.

**Comment by MattyBoombalatty** [comment]
Updating back to `6.0.0-rc1` resolved the upload issue. For future reference: don't do what I did.

**Comment by MattyBoombalatty** [comment]
Is it possible to restore the database schema without wiping?

**Comment by Chocobozzz** [comment]
Hi,

Is there a reason why you wanted to go back to 5.2.1?

But yes, you have to restore your db backup when you want to restore a previous version of peertube: https://docs.joinpeertube.org/install/any-os#things-went-wrong

**Comment by MattyBoombalatty** [comment]
I wanted to revert to 5.2.1 since the remote runners worked then for larger uploads per the other issue I submitted, but the SQL backup was erased so I guess I'm out of luck there. Ah well. I have backups of the actual database but that would mean losing some user data.
