### ISSUE TITLE
peertube crash when update video

### ISSUE THREAD

**Issue by peshane** [Chocobozzz/PeerTube#606]
* **PeerTube version or URL:**: beta7
* **Browser name/version:**: firefox60
* **NodeJS version:** 8.11.2

* **What is the expected behaviour?**: updated video and peertube don't crash
* **What do you see instead?**: 
updated video and peertube crash
when the daemon try to restart, crash, apparently, when trying to start a job

* **Browser console log if useful (Gist/Pastebin...):** not related
* **Server log if useful (Gist/Pastebin...):**:
```
mai 30 14:12:43 peshkim2 peertube[17482]: peertube: symbol lookup error: /usr/share/webapps/peertube/node_modules/rdf-canonize/build/Release/urdna2015.node: undefined symbol: EVP_MD_CTX_create
mai 30 14:12:43 peshkim2 peertube[17482]: npm ERR! file sh
mai 30 14:12:43 peshkim2 peertube[17482]: npm ERR! code ELIFECYCLE
mai 30 14:12:43 peshkim2 peertube[17482]: npm ERR! errno ENOENT
mai 30 14:12:43 peshkim2 peertube[17482]: npm ERR! syscall spawn
mai 30 14:12:43 peshkim2 peertube[17482]: npm ERR! peertube@1.0.0-beta.7 start: `node dist/server`
mai 30 14:12:43 peshkim2 peertube[17482]: npm ERR! spawn ENOENT
mai 30 14:12:43 peshkim2 peertube[17482]: npm ERR!
mai 30 14:12:43 peshkim2 peertube[17482]: npm ERR! Failed at the peertube@1.0.0-beta.7 start script.
mai 30 14:12:43 peshkim2 peertube[17482]: npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
mai 30 14:12:43 peshkim2 peertube[17482]: npm ERR! A complete log of this run can be found in:
mai 30 14:12:43 peshkim2 peertube[17482]: npm ERR!     /var/lib/peertube/.npm/_logs/2018-05-30T12_12_43_628Z-debug.log
mai 30 14:12:43 peshkim2 systemd[1]: peertube.service: Main process exited, code=exited, status=1/FAILURE
mai 30 14:12:43 peshkim2 systemd[1]: peertube.service: Failed with result 'exit-code'.
```
and the complete log file:
```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'start' ]
2 info using npm@6.0.1
3 info using node@v8.11.2
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle peertube@1.0.0-beta.7~prestart: peertube@1.0.0-beta.7
6 info lifecycle peertube@1.0.0-beta.7~start: peertube@1.0.0-beta.7
7 verbose lifecycle peertube@1.0.0-beta.7~start: unsafe-perm in lifecycle true
8 verbose lifecycle peertube@1.0.0-beta.7~start: PATH: /usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/usr/share/webapps/peertube/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/bin
9 verbose lifecycle peertube@1.0.0-beta.7~start: CWD: /usr/share/webapps/peertube
10 silly lifecycle peertube@1.0.0-beta.7~start: Args: [ '-c', 'node dist/server' ]
11 info lifecycle peertube@1.0.0-beta.7~start: Failed to exec start script
12 verbose stack Error: peertube@1.0.0-beta.7 start: `node dist/server`
12 verbose stack spawn ENOENT
12 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:48:18)
12 verbose stack     at emitTwo (events.js:126:13)
12 verbose stack     at ChildProcess.emit (events.js:214:7)
12 verbose stack     at maybeClose (internal/child_process.js:925:16)
12 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
13 verbose pkgid peertube@1.0.0-beta.7
14 verbose cwd /usr/share/webapps/peertube
15 verbose Linux 4.16.10-1-ARCH
16 verbose argv "/usr/bin/node" "/usr/bin/npm" "start"
17 verbose node v8.11.2
18 verbose npm  v6.0.1
19 error file sh
20 error code ELIFECYCLE
21 error errno ENOENT
22 error syscall spawn
23 error peertube@1.0.0-beta.7 start: `node dist/server`
23 error spawn ENOENT
24 error Failed at the peertube@1.0.0-beta.7 start script.
24 error This is probably not a problem with npm. There is likely additional logging output above.
```

**workaround I found**: *flushdb* the redis database for peertube can be up again

**Comment by Chocobozzz** [comment]
What is your GNU/Linux distribution?

**Comment by peshane** [comment]
archlinux

**Comment by Chocobozzz** [comment]
Try to install `nodejs` instead of `nodejs-carbon-lts`, remove `node_modules` directory, `yarn install --pure-lockfile` and retry to update your video.

**Comment by peshane** [comment]
it's working well \o/
I'm currently recreating the peertube package with nodejs 10 installed, and try to reinstall it to see if it's working.
Thanks for your help :)

**Comment by peshane** [comment]
Well, it's still working with the new package build with nodejs 10
I've fallback recently to nodejs-carbon-lts because the arch package depend to it. Probably I've mistaken somewhere. Sorry for that and thanks again :+1:
