### ISSUE TITLE
New 6.01 install failing on first run

### ISSUE THREAD

**Issue by dhk2** [Chocobozzz/PeerTube#6074]
### Describe the problem

Created a new standard PeerTube instance following the normal production guide steps, everything went fine until the first start failed with:

```
Nov 30 16:29:45 root systemd[1]: Started PeerTube daemon.
Nov 30 16:29:45 root peertube[16073]: file:///var/www/peertube/versions/peertube-v6.0.1/dist/server.js:2
Nov 30 16:29:45 root peertube[16073]: await registerOpentelemetryTracing();
Nov 30 16:29:45 root peertube[16073]: ^^^^^
Nov 30 16:29:45 root peertube[16073]: SyntaxError: Unexpected reserved word
Nov 30 16:29:45 root peertube[16073]:     at Loader.moduleStrategy (internal/modules/esm/translators.js:133:18)
Nov 30 16:29:45 root peertube[16073]:     at async link (internal/modules/esm/module_job.js:42:21)
Nov 30 16:29:45 root systemd[1]: peertube.service: Main process exited, code=exited, status=1/FAILURE
Nov 30 16:29:45 root systemd[1]: peertube.service: Failed with result 'exit-code'.

```

Since the error pointed to telemetry which i had not enabled, I tried enabling either and both, and removing the telemetry section completely from production.yaml with no change in the failure to launch.

### Additional information

* PeerTube instance URL: audio.freediverse.com
* PeerTube version: 6.01
* NodeJS version:  v20.10.0
* Ffmpeg version: 4.4.2
* Redis version: 6.0.16
* PostgreSQL version:14.9

**Comment by dhk2** [comment]
Tried a different VPS with a different provider and getting the same error, If i'm doing something wrong at least I'm doing it consistently :)
