### ISSUE TITLE
Video annotations stay also for new video

### ISSUE THREAD

**Issue by xundeenergie** [Chocobozzz/PeerTube#6103]
### Describe the current behavior

I've installed the plugin video-annotation in version 0.0.7.

Since the new player annotations from the old video are still shown in a new choosen video.

### Steps to reproduce

1. Create a video annotation for video A
2. Load an view A, see the annotation.
3. Choose another video B from the suggestions below the video an view it
4. See annotations for video A even in Video B

### Describe the expected behavior

New Video, annotations should be reset.

### Additional information

You can try it here https://kino.schuerz.at/w/xumKCNiC26Y66qg7knQCjq view it and then coose another video.

* PeerTube instance:
  * URL: https://kino.schuerzat
  * Version: 6.0.1
  * NodeJS version:
  * Ffmpeg version:

* Browser name, version and platforms on which you could reproduce the bug:
* Link to browser console log if relevant:
* Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`):

**Comment by Chocobozzz** [comment]
Hi,

It should be fixed by https://framagit.org/framasoft/peertube/official-plugins/-/commit/3fbd095af3c69efc2d2561707b9b95d9092d0f77

Can you try the annotation plugin v0.0.8?

**Comment by xundeenergie** [comment]
I tried to update via web-frontent and got this error in journal

```
Dec 13 11:22:37 tube peertube[8512]: [kino.schuerz.at:443] 2023-12-13 11:22:37.234 warn: Cannot update plugin peertube-plugin-video-annotation. {
Dec 13 11:22:37 tube peertube[8512]:   "err": {
Dec 13 11:22:37 tube peertube[8512]:     "stack": "Error: Unknown plugin peertube-plugin-video-annotation to unregister\n    at PluginManager.unregister (file:///var/www/peertube/versions/peertube-v6.0.1/dist/core/lib/plugins/plugin-manager.js:198:19)\n    at PluginManager.update (file:///var/www/peertube/versions/peertube-v6.0.1/dist/core/lib/plugins/plugin-manager.js:272:20)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async updatePlugin (file:///var/www/peertube/versions/peertube-v6.0.1/dist/core/controllers/api/plugins.js:59:24)",
Dec 13 11:22:37 tube peertube[8512]:     "message": "Unknown plugin peertube-plugin-video-annotation to unregister"
Dec 13 11:22:37 tube peertube[8512]:   }
Dec 13 11:22:37 tube peertube[8512]: }
Dec 13 11:22:37 tube peertube[8512]: [kino.schuerz.at:443] 2023-12-13 11:22:37.573 error: Client log: Backend returned code 400, errorMessage is: Cannot update plugin peertube-plugin-video-annotation {
Dec 13 11:22:37 tube peertube[8512]:   "userAgent": "Mozilla/5.0 (X11; Linux x86_64; rv:120.0) Gecko/20100101 Firefox/120.0",
Dec 13 11:22:37 tube peertube[8512]:   "url": "https://kino.schuerz.at/admin/plugins/list-installed?pluginType=1"
Dec 13 11:22:37 tube peertube[8512]: }
Dec 13 11:22:37 tube peertube[8512]: [kino.schuerz.at:443] 2023-12-13 11:22:37.575 error: Client log: Fehler: Cannot update plugin peertube-plugin-video-annotation {
Dec 13 11:22:37 tube peertube[8512]:   "userAgent": "Mozilla/5.0 (X11; Linux x86_64; rv:120.0) Gecko/20100101 Firefox/120.0",
Dec 13 11:22:37 tube peertube[8512]:   "url": "https://kino.schuerz.at/admin/plugins/list-installed?pluginType=1"
Dec 13 11:22:37 tube peertube[8512]: }

```

**Comment by xundeenergie** [comment]
And de- and reinstall the plugin gives me 

```
Dec 13 11:25:48 tube peertube[8512]: [kino.schuerz.at:443] 2023-12-13 11:25:48.628 warn: Cannot install plugin peertube-plugin-video-annotation. {
Dec 13 11:25:48 tube peertube[8512]:   "err": {
Dec 13 11:25:48 tube peertube[8512]:     "err": {
Dec 13 11:25:48 tube peertube[8512]:       "stack": "Error: Command failed: yarn add peertube-plugin-video-annotation@0.0.8\nwarning package.json: No license field\nwarning package-lock.json found. Your project contains lock files generated by tools other than Yarn. It is advised not to mix package managers in order to avoid resolution inconsistencies caused by unsynchronized lock files. To clear this warning, remove package-lock.json.\nwarning No license field\nerror Couldn't find any versions for \"peertube-plugin-video-annotation\" that matches \"0.0.8\"\n\n    at ChildProcess.exithandler (node:child_process:419:12)\n    at ChildProcess.emit (node:events:513:28)\n    at maybeClose (node:internal/child_process:1091:16)\n    at ChildProcess._handle.onexit (node:internal/child_process:302:5)",
Dec 13 11:25:48 tube peertube[8512]:       "message": "Command failed: yarn add peertube-plugin-video-annotation@0.0.8\nwarning package.json: No license field\nwarning package-lock.json found. Your project contains lock files generated by tools other than Yarn. It is advised not to mix package managers in order to avoid resolution inconsistencies caused by unsynchronized lock files. To clear this warning, remove package-lock.json.\nwarning No license field\nerror Couldn't find any versions for \"peertube-plugin-video-annotation\" that matches \"0.0.8\"\n",
Dec 13 11:25:48 tube peertube[8512]:       "code": 1,
Dec 13 11:25:48 tube peertube[8512]:       "killed": false,
Dec 13 11:25:48 tube peertube[8512]:       "signal": null,
Dec 13 11:25:48 tube peertube[8512]:       "cmd": "yarn add peertube-plugin-video-annotation@0.0.8"
Dec 13 11:25:48 tube peertube[8512]:     },
Dec 13 11:25:48 tube peertube[8512]:     "stdout": "yarn add v1.22.19\n[1/4] Resolving packages...\ninfo Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.\n",
Dec 13 11:25:48 tube peertube[8512]:     "stderr": "warning package.json: No license field\nwarning package-lock.json found. Your project contains lock files generated by tools other than Yarn. It is advised not to mix package managers in order to avoid resolution inconsistencies caused by unsynchronized lock files. To clear this warning, remove package-lock.json.\nwarning No license field\nerror Couldn't find any versions for \"peertube-plugin-video-annotation\" that matches \"0.0.8\"\n"
Dec 13 11:25:48 tube peertube[8512]:   }
Dec 13 11:25:48 tube peertube[8512]: }
Dec 13 11:25:48 tube peertube[8512]: [kino.schuerz.at:443] 2023-12-13 11:25:48.696 error: Client log: Backend returned code 400, errorMessage is: Cannot install plugin peertube-plugin-video-annotation {
Dec 13 11:25:48 tube peertube[8512]:   "username": "jakob",
Dec 13 11:25:48 tube peertube[8512]:   "userAgent": "Mozilla/5.0 (X11; Linux x86_64; rv:120.0) Gecko/20100101 Firefox/120.0",
Dec 13 11:25:48 tube peertube[8512]:   "url": "https://kino.schuerz.at/admin/plugins/search?pluginType=1&search=anno"
Dec 13 11:25:48 tube peertube[8512]: }
Dec 13 11:25:48 tube peertube[8512]: [kino.schuerz.at:443] 2023-12-13 11:25:48.720 error: Client log: Fehler: Cannot install plugin peertube-plugin-video-annotation {
Dec 13 11:25:48 tube peertube[8512]:   "username": "jakob",
Dec 13 11:25:48 tube peertube[8512]:   "userAgent": "Mozilla/5.0 (X11; Linux x86_64; rv:120.0) Gecko/20100101 Firefox/120.0",
Dec 13 11:25:48 tube peertube[8512]:   "url": "https://kino.schuerz.at/admin/plugins/search?pluginType=1&search=anno"
Dec 13 11:25:48 tube peertube[8512]: }
Dec 13 11:26:12 tube peertube[8512]: [kino.schuerz.at:443] 2023-12-13 11:26:12.545 warn: Client log: HLS.js does not seem to be supported. Cannot fallback to built-in HLS {
Dec 13 11:26:12 tube peertube[8512]:   "userAgent": "Mozilla/5.0 (Linux; Android 6.0.1; Nexus 5X Build/MMB29P) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.6045.199 Mobile Safari/537.36 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)",
Dec 13 11:26:12 tube peertube[8512]:   "url": "https://kino.schuerz.at/w/0d9e8873-6451-45d7-9e6e-a7b5cc7918a7"
Dec 13 11:26:12 tube peertube[8512]: }
``

**Comment by xundeenergie** [comment]
After Upgrade to Peertube 6.0.2 i could install the new plugin again.

**Comment by xundeenergie** [comment]
And yes... now it works perfectly.
