### ISSUE TITLE
Peertube 6 stops working

### ISSUE THREAD

**Issue by sanpii** [Chocobozzz/PeerTube#6109]
### Describe the current behavior

Since the peertube 6 update my systemd service regulary stops working.

The peertube process is still active but the frontend doesn’t respond (timeout).

The systemd journal shows multiple messages like this:
```
[tube.homecomputing.fr:443 uploadx] 2023-12-13 07:13:10.619 error: uncaughtException: client is destroyed
Error: client is destroyed
    at NatAPI._upnpMap (file:///home/sanpi/public_html/peertube/v6.0.2/node_modules/@silentbot1/nat-api/index.js:312:32)
    at Timeout._onTimeout (file:///home/sanpi/public_html/peertube/v6.0.2/node_modules/@silentbot1/nat-api/index.js:335:20)
    at listOnTimeout (node:internal/timers:564:17)
    at process.processTimers (node:internal/timers:507:7) {
  "error": {
    "stack": "Error: client is destroyed\n    at NatAPI._upnpMap (file:///home/sanpi/public_html/peertube/v6.0.2/node_modules/@silentbot1/nat-api/index.js:312:32)\n    at Timeout._onTimeout (file:///home/sanpi/public_html/peertube/v6.0.2/node_modules/@silentbot1/nat-api/index.js:335:20)\n    at listOnTimeout (node:internal/timers:564:17)\n    at process.processTimers (node:internal/timers:507:7)",
    "message": "client is destroyed"
  },
  "stack": "Error: client is destroyed\n    at NatAPI._upnpMap (file:///home/sanpi/public_html/peertube/v6.0.2/node_modules/@silentbot1/nat-api/index.js:312:32)\n    at Timeout._onTimeout (file:///home/sanpi/public_html/peertube/v6.0.2/node_modules/@silentbot1/nat-api/index.js:335:20)\n    at listOnTimeout (node:internal/timers:564:17)\n    at process.processTimers (node:internal/timers:507:7)",
  "exception": true,
  "date": "Wed Dec 13 2023 07:13:10 GMT+0100 (heure normale d’Europe centrale)",
  "process": {
    "pid": 330411,
    "uid": 1000,
    "gid": 1000,
    "cwd": "/home/sanpi/public_html/peertube/v6.0.2",
    "execPath": "/usr/bin/node",
    "version": "v18.13.0",
    "argv": [
      "/usr/bin/node",
      "/home/sanpi/public_html/peertube/v6.0.2/dist/server"
    ],
    "memoryUsage": {
      "rss": 338366464,
      "heapTotal": 114544640,
      "heapUsed": 106471264,
      "external": 14729491,
      "arrayBuffers": 10372548
    }
  },
  "os": {
    "loadavg": [
      0.05,
      0.08,
      0.04
    ],
    "uptime": 164716.85
  },
  "trace": [
    {
      "column": 32,
      "file": "file:///home/sanpi/public_html/peertube/v6.0.2/node_modules/@silentbot1/nat-api/index.js",
      "function": "NatAPI._upnpMap",
      "line": 312,
      "method": "_upnpMap",
      "native": false
    },
    {
      "column": 20,
      "file": "file:///home/sanpi/public_html/peertube/v6.0.2/node_modules/@silentbot1/nat-api/index.js",
      "function": "Timeout._onTimeout",
      "line": 335,
      "method": "_onTimeout",
      "native": false
    },
    {
      "column": 17,
      "file": "node:internal/timers",
      "function": "listOnTimeout",
      "line": 564,
      "method": null,
      "native": false
    },
    {
      "column": 7,
      "file": "node:internal/timers",
      "function": "process.processTimers",
      "line": 507,
      "method": "processTimers",
      "native": false
    }
  ]
}
```

### Steps to reproduce

1. systemctl start peertube
2. wait
3. open peertube in a browser

### Describe the expected behavior

Display my peertube homepage.

### Additional information

* PeerTube instance:
  * URL: https://tube.homecomputing.fr
  * Version: `6.0.2`
  * NodeJS version: `18.13.0`
  * Ffmpeg version: `5.1.4-0+deb12u1`

**Comment by Chocobozzz** [comment]
Hi,

Thanks for the issue. Can you try this patch? https://github.com/Chocobozzz/PeerTube/commit/675f2196397fa040e911d29175a861435f4429f0

In `dist/core/helpers/webtorrent.js`, update `.default()` to:

```
  28   │     const webtorrent = new (await import('webtorrent')).default({
  29   │         natUpnp: false,
  30   │         natPmp: false
  31   │     });
```

**Comment by sanpii** [comment]
Sounds good, thank you!
