### ISSUE TITLE
Unable to follow instance

### ISSUE THREAD

**Issue by jessa0** [Chocobozzz/PeerTube#6123]
### Describe the current behavior

I am trying to follow Instance B from Instance A. The follow request does not show up on Instance B, and I can't find any requests from Instance A in the access log on Instance B's reverse proxy. The `activitypub-http-unicast` jobs on Instance A fail (where `$a` is Instance A's hostname and `$b` is Instance B's):

```
{
  "uri": "https://$b/accounts/peertube/inbox",
  "signatureActorId": 1,
  "body": {
    "type": "Follow",
    "id": "https://$a/accounts/peertube/follows/6",
    "actor": "https://$a/accounts/peertube",
    "object": "https://$b/accounts/peertube"
  },
  "contextType": "Follow"
}

jsonld.InvalidUrl: Dereferencing a URL did not result in a valid JSON-LD object. Possible causes are an inaccessible URL perhaps due to a same-origin policy (ensure the server uses CORS if you are using client-side JavaScript), too many redirects, a non-JSON response, or more than one HTTP Link Header was provided for a remote context.
    at ContextResolver._fetchContext (/app/node_modules/jsonld/lib/ContextResolver.js:173:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async ContextResolver._resolveRemoteContext (/app/node_modules/jsonld/lib/ContextResolver.js:117:34)
    at async ContextResolver.resolve (/app/node_modules/jsonld/lib/ContextResolver.js:50:22)
    at async api.process (/app/node_modules/jsonld/lib/context.js:87:20)
    at async api.expand (/app/node_modules/jsonld/lib/expand.js:214:17)
    at async jsonld.expand (/app/node_modules/jsonld/lib/jsonld.js:322:18)
    at async jsonld.toRDF (/app/node_modules/jsonld/lib/jsonld.js:687:16)
    at async jsonld.normalize.jsonld.canonize (/app/node_modules/jsonld/lib/jsonld.js:589:19)
    at async hashObject (file:///app/dist/core/helpers/peertube-jsonld.js:45:17)
```

I have confirmed I can reach the API on Instance B from Instance A:

```bash
root@$a:/app# curl -iX POST https://$b/accounts/peertube/inbox
HTTP/2 403
content-security-policy: upgrade-insecure-requests
x-powered-by: PeerTube
x-frame-options: DENY
tk: N
x-ratelimit-limit: 500
x-ratelimit-remaining: 499
date: Sun, 17 Dec 2023 22:12:44 GMT
x-ratelimit-reset: 1702851175
content-type: application/problem+json; charset=utf-8
content-length: 196
etag: W/"c4-SAHMFr5nntRGCZy0eZUAjw1VciE"
server: Apache/2.4.55 (Ubuntu)

{"type":"about:blank","title":"Forbidden","detail":"no authorization or signature header present in the request","status":403,"error":"no authorization or signature header present in the request"}
```

The 403 error is irrelevant since this is just a test that the API is reachable.

Is there maybe any debug flags I can enable to get more information about the job failure?

### Steps to reproduce

On Instance A:
1. Administration -> Following
2. Delete any pending follow request to Instance B
3. Follow -> Type Instance B's hostname

On Instance B:
1. Administration -> Followers
2. See no follow request from Instance B

### Describe the expected behavior

Follow request from Instance A should show up on Instance B.

### Additional information

* PeerTube instances A and B:
  * Version: 6.0.2
  * NodeJS version: v18.19.0
  * Ffmpeg version: 5.1.4-0+deb12u1

**Comment by Chocobozzz** [comment]
Hello,

Do you still have the issue now? If you restart PeerTube?

**Comment by jessa0** [comment]
> Do you still have the issue now? If you restart PeerTube?

Yes, today I tried stopping peertube, restarting redis, and starting peertube on both instances, and the issue still occurs.

Logs on Instance A:

```
info[12/21/2023, 11:52:11 AM] Processing ActivityPub follow in job 14.
info[12/21/2023, 11:52:11 AM] Creating job to send follow request to https://$b/accounts/peertube.
info[12/21/2023, 11:52:11 AM] Processing ActivityPub unicast in job 32.
```

Corresponding job logs on Instance A:

```
Job: 14
Type: activitypub-follow
Processed on 12/21/23, 11:52:11.167 AM
Finished on 12/21/23, 11:52:11.187 AM

{
  "host": "$b:443",
  "name": "peertube",
  "followerActorId": 1
}
```

```
Job: 32
Type: activitypub-http-unicast
Processed on 12/21/23, 11:52:11.184 AM
Finished on 12/21/23, 11:52:17.625 AM

{
  "uri": "https://$b/accounts/peertube/inbox",
  "signatureActorId": 1,
  "body": {
    "type": "Follow",
    "id": "https://$b/accounts/peertube/follows/6",
    "actor": "https://$a/accounts/peertube",
    "object": "https://$b/accounts/peertube"
  },
  "contextType": "Follow"
}

jsonld.InvalidUrl: Dereferencing a URL did not result in a valid JSON-LD object. Possible causes are an inaccessible URL perhaps due to a same-origin policy (ensure the server uses CORS if you are using client-side JavaScript), too many redirects, a non-JSON response, or more than one HTTP Link Header was provided for a remote context.
    at ContextResolver._fetchContext (/app/node_modules/jsonld/lib/ContextResolver.js:173:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async ContextResolver._resolveRemoteContext (/app/node_modules/jsonld/lib/ContextResolver.js:117:34)
    at async ContextResolver.resolve (/app/node_modules/jsonld/lib/ContextResolver.js:50:22)
    at async api.process (/app/node_modules/jsonld/lib/context.js:87:20)
    at async api.expand (/app/node_modules/jsonld/lib/expand.js:214:17)
    at async jsonld.expand (/app/node_modules/jsonld/lib/jsonld.js:322:18)
    at async jsonld.toRDF (/app/node_modules/jsonld/lib/jsonld.js:687:16)
    at async jsonld.normalize.jsonld.canonize (/app/node_modules/jsonld/lib/jsonld.js:589:19)
    at async hashObject (file:///app/dist/core/helpers/peertube-jsonld.js:45:17)
```

# Following Back

Following Instance A from Instance B half-works, but Instance A is still not able to call out to Instance B to accept the request..

Logs on Instance A:

```
info[12/21/2023, 11:53:02 AM] Receiving inbox requests for 1 activities by https://$b/accounts/peertube.
info[12/21/2023, 11:53:02 AM] 157.131.196.183 - - [21/Dec/2023:19:53:02 +0000] "POST /accounts/peertube/inbox HTTP/1.0" 204 - "-" "PeerTube/6.0.2 (+https://$b)"
{
  "tags": [
    "http"
  ]
}
info[12/21/2023, 11:53:02 AM] Actor https://$a/accounts/peertube is followed by actor https://$b/accounts/peertube.
info[12/21/2023, 11:53:02 AM] Notifying 2 administrators of new instance follower: https://$b/accounts/peertube.
info[12/21/2023, 11:53:13 AM] Creating job to accept follower https://$b/accounts/peertube.
info[12/21/2023, 11:53:13 AM] Processing ActivityPub unicast in job 33. 
```

Corresponding job logs on Instance A:

```
Job: 33
Type: activitypub-http-unicast
Processed on 12/21/23, 11:53:13.935 AM
Finished on 12/21/23, 11:53:20.505 AM

{
  "uri": "https://$b/accounts/peertube/inbox",
  "signatureActorId": 1,
  "body": {
    "type": "Accept",
    "id": "https://$a/accepts/follows/20",
    "actor": "https://$a/accounts/peertube",
    "object": {
      "type": "Follow",
      "id": "https://$b/accounts/peertube/follows/6",
      "actor": "https://$b/accounts/peertube",
      "object": "https://$a/accounts/peertube"
    }
  },
  "contextType": "Accept"
}

jsonld.InvalidUrl: Dereferencing a URL did not result in a valid JSON-LD object. Possible causes are an inaccessible URL perhaps due to a same-origin policy (ensure the server uses CORS if you are using client-side JavaScript), too many redirects, a non-JSON response, or more than one HTTP Link Header was provided for a remote context.
    at ContextResolver._fetchContext (/app/node_modules/jsonld/lib/ContextResolver.js:173:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async ContextResolver._resolveRemoteContext (/app/node_modules/jsonld/lib/ContextResolver.js:117:34)
    at async ContextResolver.resolve (/app/node_modules/jsonld/lib/ContextResolver.js:50:22)
    at async api.process (/app/node_modules/jsonld/lib/context.js:87:20)
    at async api.expand (/app/node_modules/jsonld/lib/expand.js:214:17)
    at async jsonld.expand (/app/node_modules/jsonld/lib/jsonld.js:322:18)
    at async jsonld.toRDF (/app/node_modules/jsonld/lib/jsonld.js:687:16)
    at async jsonld.normalize.jsonld.canonize (/app/node_modules/jsonld/lib/jsonld.js:589:19)
    at async hashObject (file:///app/dist/core/helpers/peertube-jsonld.js:45:17)
```

Logs on Instance B:

```
info[12/21/2023, 11:53:01 AM] Processing ActivityPub follow in job 6.
info[12/21/2023, 11:53:01 AM] Creating job to send follow request to https://$a/accounts/peertube.
info[12/21/2023, 11:53:01 AM] Processing ActivityPub unicast in job 10.
info[12/21/2023, 11:53:02 AM] Updating 1 good actor follows and 0 bad actor follows scores in cache.
{
  "badInboxes": []
}
```

Corresponding job logs on Instance B:

```
Job: 6
Type: activitypub-follow
Processed on 12/21/23, 11:53:01.482 AM
Finished on 12/21/23, 11:53:01.531 AM

{
  "host": "$a:443",
  "name": "peertube",
  "followerActorId": 1
}

Job: 10
Type: activitypub-http-unicast
Processed on 12/21/23, 11:53:01.520 AM
Finished on 12/21/23, 11:53:02.884 AM

{
  "uri": "https://$a/accounts/peertube/inbox",
  "signatureActorId": 1,
  "body": {
    "type": "Follow",
    "id": "https://$b/accounts/peertube/follows/6",
    "actor": "https://$b/accounts/peertube",
    "object": "https://$a/accounts/peertube"
  },
  "contextType": "Follow"
}
```

**Comment by Chocobozzz** [comment]
Thanks, can you replace in `peertube-latest/node_modules/jsonld/lib/ContextResolver.js` line `174`:

```
        'Dereferencing a URL did not result in a valid JSON-LD object. ' +
```

by

```
        'Dereferencing ' + url + ' did not result in a valid JSON-LD object. ' +
```

Then restarting peertube and retrying the process should help to see which URL cannot be deferenced

**Comment by jessa0** [comment]
> Then restarting peertube and retrying the process should help to see which URL cannot be deferenced

Here's the new error message:

```
jsonld.InvalidUrl: Dereferencing https://www.w3.org/ns/activitystreams did not result in a valid JSON-LD object. Possible causes are an inaccessible URL perhaps due to a same-origin policy (ensure the server uses CORS if you are using client-side JavaScript), too many redirects, a non-JSON response, or more than one HTTP Link Header was provided for a remote context.
```

**Comment by jessa0** [comment]
I found the issue. IPv6 was enabled but not routing properly on my server. I fixed the IPv6 connectivity and now the follow requests in Peertube work as intended.

You can close this issue, but in my mind, there are a couple actionable items:

1. Showing an error indicator on follow requests in the UI when they fail for whatever reason.
2. Print `error.details.cause`, recursively, like I did in the comment above, when printing errors from JSON-LD.
3. IPv4 "happy eyeballs" fallback within JSON-LD.

I'll leave it up to you if any of those items are desirable. I can file issues for any of those to save you time, just let me know!

**Comment by Chocobozzz** [comment]
I think a notification to explain a follow failed is a good idea! Don't hesitate to create an issue :)
