### ISSUE TITLE
Null Value in Column nodeVersion

### ISSUE THREAD

**Issue by Happyfeet01** [Chocobozzz/PeerTube#6137]
### Describe the current behavior

Hello, have the same issue suddenly. The server works fine for a year. Now i got this Message at startup.

```
[tube.domain.tld:443] 2023-12-21 14:27:12.217 info: Using following configuration file hierarchy: /app/config/default.yaml -> /app/support/docker/production/config/production.yaml -> /app/support/docker/production/config/custom-environment-variables.yaml.
[tube.domain.tldl:443] 2023-12-21 14:27:12.379 error: Cannot start application. {
  "err": {
    "stack": "Error\n    at Query.run (/app/node_modules/sequelize/lib/dialects/postgres/query.js:50:25)\n    at /app/node_modules/sequelize/lib/sequelize.js:315:28\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)",
    "message": "null value in column \"nodeVersion\" of relation \"application\" violates not-null constraint",
    "name": "SequelizeDatabaseError",
    "parent": {
      "stack": "error: null value in column \"nodeVersion\" of relation \"application\" violates not-null constraint\n    at Parser.parseErrorMessage (/app/node_modules/pg-protocol/dist/parser.js:287:98)\n    at Parser.handlePacket (/app/node_modules/pg-protocol/dist/parser.js:126:29)\n    at Parser.parse (/app/node_modules/pg-protocol/dist/parser.js:39:38)\n    at Socket.<anonymous> (/app/node_modules/pg-protocol/dist/index.js:11:42)\n    at Socket.emit (node:events:513:28)\n    at addChunk (node:internal/streams/readable:315:12)\n    at readableAddChunk (node:internal/streams/readable:289:9)\n    at Socket.Readable.push (node:internal/streams/readable:228:10)\n    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)",
      "message": "null value in column \"nodeVersion\" of relation \"application\" violates not-null constraint",
      "length": 235,
      "name": "error",
      "severity": "ERROR",
      "code": "23502",
      "detail": "Failing row contains (74, 0, null, null, null).",
      "schema": "public",
      "table": "application",
      "column": "nodeVersion",
      "file": "execMain.c",
      "line": "1947",
      "routine": "ExecConstraints",
      "sql": "INSERT INTO \"application\" (\"migrationVersion\") VALUES (0)"
    },
    "sql": "INSERT INTO \"application\" (\"migrationVersion\") VALUES (0)",
    "parameters": {}
  }
```

 the entry of the table application

```
peertube=# \d application
                                           Table "public.application"
        Column         |          Type          | Collation | Nullable |                 Default                 
-----------------------+------------------------+-----------+----------+-----------------------------------------
 id                    | integer                |           | not null | nextval('application_id_seq'::regclass)
 migrationVersion      | integer                |           | not null | 0
 latestPeerTubeVersion | character varying(255) |           |          | 
 nodeVersion           | character varying(255) |           | not null | 
 nodeABIVersion        | integer                |           | not null | 
Indexes:
    "application_pkey" PRIMARY KEY, btree (id)
Referenced by:
    TABLE "account" CONSTRAINT "account_applicationId_fkey" FOREIGN KEY ("applicationId") REFERENCES application(id) ON UPDATE CASCADE ON DELETE CASCADE
```

how can i fix it? i can´t drop the database.

### Steps to reproduce

Good to know 

### Describe the expected behavior

Actually, the instance should start normally, but it hasn't done so for about three weeks. Once the error has been fixed, the instance should run again

### Additional information

* PeerTube instance:
  * URL: https://tube.fulda.social
  * installed via Docker-compose
  * 

Hello, have the same issue suddenly. The server works fine for a year. Now i got this Message at startup.

```
[tube.domain.tld:443] 2023-12-21 14:27:12.217 info: Using following configuration file hierarchy: /app/config/default.yaml -> /app/support/docker/production/config/production.yaml -> /app/support/docker/production/config/custom-environment-variables.yaml.
[tube.domain.tldl:443] 2023-12-21 14:27:12.379 error: Cannot start application. {
  "err": {
    "stack": "Error\n    at Query.run (/app/node_modules/sequelize/lib/dialects/postgres/query.js:50:25)\n    at /app/node_modules/sequelize/lib/sequelize.js:315:28\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)",
    "message": "null value in column \"nodeVersion\" of relation \"application\" violates not-null constraint",
    "name": "SequelizeDatabaseError",
    "parent": {
      "stack": "error: null value in column \"nodeVersion\" of relation \"application\" violates not-null constraint\n    at Parser.parseErrorMessage (/app/node_modules/pg-protocol/dist/parser.js:287:98)\n    at Parser.handlePacket (/app/node_modules/pg-protocol/dist/parser.js:126:29)\n    at Parser.parse (/app/node_modules/pg-protocol/dist/parser.js:39:38)\n    at Socket.<anonymous> (/app/node_modules/pg-protocol/dist/index.js:11:42)\n    at Socket.emit (node:events:513:28)\n    at addChunk (node:internal/streams/readable:315:12)\n    at readableAddChunk (node:internal/streams/readable:289:9)\n    at Socket.Readable.push (node:internal/streams/readable:228:10)\n    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)",
      "message": "null value in column \"nodeVersion\" of relation \"application\" violates not-null constraint",
      "length": 235,
      "name": "error",
      "severity": "ERROR",
      "code": "23502",
      "detail": "Failing row contains (74, 0, null, null, null).",
      "schema": "public",
      "table": "application",
      "column": "nodeVersion",
      "file": "execMain.c",
      "line": "1947",
      "routine": "ExecConstraints",
      "sql": "INSERT INTO \"application\" (\"migrationVersion\") VALUES (0)"
    },
    "sql": "INSERT INTO \"application\" (\"migrationVersion\") VALUES (0)",
    "parameters": {}
  }
```

 the entry of the table application

```
peertube=# \d application
                                           Table "public.application"
        Column         |          Type          | Collation | Nullable |                 Default                 
-----------------------+------------------------+-----------+----------+-----------------------------------------
 id                    | integer                |           | not null | nextval('application_id_seq'::regclass)
 migrationVersion      | integer                |           | not null | 0
 latestPeerTubeVersion | character varying(255) |           |          | 
 nodeVersion           | character varying(255) |           | not null | 
 nodeABIVersion        | integer                |           | not null | 
Indexes:
    "application_pkey" PRIMARY KEY, btree (id)
Referenced by:
    TABLE "account" CONSTRAINT "account_applicationId_fkey" FOREIGN KEY ("applicationId") REFERENCES application(id) ON UPDATE CASCADE ON DELETE CASCADE
```

how can i fix it? i can´t drop the database.

**Comment by Chocobozzz** [comment]
Please paste the output of `select *  from application`

**Comment by Happyfeet01** [comment]
> `select * from application`

Empty 🤔

`peertube-# \dt+
                                 List of relations
 Schema |     Name     | Type  |  Owner   | Persistence |    Size    | Description 
--------+--------------+-------+----------+-------------+------------+-------------
 public | account      | table | peertube | permanent   | 8192 bytes | 
 public | actor        | table | peertube | permanent   | 8192 bytes | 
 public | actorFollow  | table | peertube | permanent   | 8192 bytes | 
 public | actorImage   | table | peertube | permanent   | 8192 bytes | 
 public | application  | table | peertube | permanent   | 8192 bytes | 
 public | oAuthClient  | table | peertube | permanent   | 8192 bytes | 
 public | oAuthToken   | table | peertube | permanent   | 8192 bytes | 
 public | server       | table | peertube | permanent   | 0 bytes    | 
 public | tag          | table | peertube | permanent   | 0 bytes    | 
 public | user         | table | peertube | permanent   | 8192 bytes | 
 public | video        | table | peertube | permanent   | 8192 bytes | 
 public | videoChannel | table | peertube | permanent   | 8192 bytes | 
(12 rows)

peertube-# select *  from application`

**Comment by Happyfeet01** [comment]
Damn it seems all tables and column are empty.

`peertube=# SELECT * FROM application;
 id | migrationVersion | latestPeerTubeVersion | nodeVersion | nodeABIVersion 
----+------------------+-----------------------+-------------+----------------
(0 rows)
`

**Comment by Chocobozzz** [comment]
Sorry for the late answer. Can you explain how you updated your docker setup?

**Comment by Chocobozzz** [comment]
Ping @Happyfeet01

**Comment by Happyfeet01** [comment]
@Chocobozzz The errors were due to the fact that I had accidentally emptied the database. That's why nothing could be wrong. I then decided, as there wasn't that much going on on the instance, to set it up completely from scratch with daily backups. So that this doesn't happen again.
