### ISSUE TITLE
plugins can not be updated or configured after upgrading to v6.02

### ISSUE THREAD

**Issue by rasos** [Chocobozzz/PeerTube#6141]
### Describe the problem

After upgrading to PeerTube v6.02 we can not configure or update plugins anymore: 

```
> Dec 27 10:23:22 bridge2 peertube[687449]: [fair.tube:443] 2023-12-27 10:23:22.375 #033[32minfo#033[39m: Updating plugin peertube-plugin-video-annotation.
> Dec 27 10:23:22 bridge2 peertube[687449]: [fair.tube:443] 2023-12-27 10:23:22.376 #033[32minfo#033[39m: Unregister plugin peertube-plugin-video-annotation.
> Dec 27 10:23:22 bridge2 peertube[687449]: [fair.tube:443] 2023-12-27 10:23:22.376 #033[33mwarn#033[39m: Cannot update plugin peertube-plugin-video-annotation. {
> Dec 27 10:23:22 bridge2 peertube[687449]:   "err": {
> Dec 27 10:23:22 bridge2 peertube[687449]:     "stack": "Error: Unknown plugin peertube-plugin-video-annotation to unregister\n    at PluginManager.unregister (file:///var/www/peertube/versions/peertube-v6.0.2/di
> st/core/lib/plugins/plugin-manager.js:198:19)\n    at PluginManager.update (file:///var/www/peertube/versions/peertube-v6.0.2/dist/core/lib/plugins/plugin-manager.js:272:20)\n    at process.processTicksAndReject
> ions (node:internal/process/task_queues:95:5)\n    at async updatePlugin (file:///var/www/peertube/versions/peertube-v6.0.2/dist/core/controllers/api/plugins.js:59:24)",
> Dec 27 10:23:22 bridge2 peertube[687449]:     "message": "Unknown plugin peertube-plugin-video-annotation to unregister"
> Dec 27 10:23:22 bridge2 peertube[687449]:   }
> Dec 27 10:23:22 bridge2 peertube[687449]: }
```

But the plugin is where it is configured with the correct user: 

```
root@bridge2 /var/www/peertube/storage/plugins # find . -name peertube-plugin-video-annotation
./data/peertube-plugin-video-annotation
./node_modules/peertube-plugin-video-annotation
```

When trying to re-install a plugin, it says it has a too new NodeJS version (we had to upgrade to 18):

```
Dec 27 10:38:45 bridge2 peertube[687449]: [fair.tube:443] 2023-12-27 10:38:45.380 #033[32minfo#033[39m: Installing plugin peertube-plugin-tv-streaming.
Dec 27 10:38:46 bridge2 peertube[687449]: [fair.tube:443] 2023-12-27 10:38:46.193 #033[31merror#033[39m: Cannot install plugin peertube-plugin-tv-streaming, removing it... {
Dec 27 10:38:46 bridge2 peertube[687449]:   "err": {
Dec 27 10:38:46 bridge2 peertube[687449]:     "err": {
Dec 27 10:38:46 bridge2 peertube[687449]:       "stack": "Error: Command failed: yarn add peertube-plugin-tv-streaming@1.1.5\nwarning package.json: No license field\nwarning No license field\nerror openid-client@5.1.9: The engine \"node\" is incompatible with this module. Expected version \"^12.19.0 || ^14.15.0 || ^16.13.0\". Got \"18.19.0\"\nerror Found incompatible module.\n\n    at ChildProcess.exithandler (node:child_process:422:12)\n    at ChildProcess.emit (node:events:517:28)\n    at maybeClose (node:internal/child_process:1098:16)\n    at ChildProcess._handle.onexit (node:internal/child_process:303:5)",
Dec 27 10:38:46 bridge2 peertube[687449]:       "message": "Command failed: yarn add peertube-plugin-tv-streaming@1.1.5\nwarning package.json: No license field\nwarning No license field\nerror openid-client@5.1.9: The engine \"node\" is incompatible with this module. Expected version \"^12.19.0 || ^14.15.0 || ^16.13.0\". Got \"18.19.0\"\nerror Found incompatible module.\n",
Dec 27 10:38:46 bridge2 peertube[687449]:       "code": 1,
Dec 27 10:38:46 bridge2 peertube[687449]:       "killed": false,
Dec 27 10:38:46 bridge2 peertube[687449]:       "signal": null,
Dec 27 10:38:46 bridge2 peertube[687449]:       "cmd": "yarn add peertube-plugin-tv-streaming@1.1.5"
Dec 27 10:38:46 bridge2 peertube[687449]:     },
Dec 27 10:38:46 bridge2 peertube[687449]:     "stdout": "yarn add v1.22.10\n[1/4] Resolving packages...\n[2/4] Fetching packages...\ninfo Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.\n",
Dec 27 10:38:46 bridge2 peertube[687449]:     "stderr": "warning package.json: No license field\nwarning No license field\nerror openid-client@5.1.9: The engine \"node\" is incompatible with this module. Expected version \"^12.19.0 || ^14.15.0 || ^16.13.0\". Got \"18.19.0\"\nerror Found incompatible module.\n"
```

### Additional information

* PeerTube instance URL: https://fair.tube
* PeerTube version: v6.02
* NodeJS version: 18.19.0

**Comment by Chocobozzz** [comment]
Please stop peertube and use https://docs.joinpeertube.org/maintain/tools#install-or-uninstall-plugins to uninstall, and then reinstall your plugins

**Comment by rasos** [comment]
Ok, it seems the openid-connect plugin blocked all others.  When uninstalling a plugin I first got 

> error openid-client@5.1.9: The engine "node" is incompatible with this module. Expected version "^12.19.0 || ^14.15.0 || ^16.13.0". Got "18.19.0"

After re-installing the `peertube-plugin-auth-openid-connect` I could access again the settings of all other plugins. 

```
sudo -u peertube NODE_CONFIG_DIR=/var/www/peertube/config NODE_ENV=production npm run plugin:uninstall -- --npm-name peertube-plugin-auth-openid-connect
sudo -u peertube NODE_CONFIG_DIR=/var/www/peertube/config NODE_ENV=production npm run plugin:install -- --npm-name peertube-plugin-video-annotation
```

I did not need to re-install all the other plugins. Also updating of a plugin now works again via web interface. Thanks!
