### ISSUE TITLE
Move to object storage intermittently failing after 6.02 upgrade

### ISSUE THREAD

**Issue by dhk2** [Chocobozzz/PeerTube#6153]
### Describe the current behavior

Some of the move to object storage jobs complete as normal, but same get a fail message. The larger the file, the more likely the fail, but even some smaller files fail. The files appear to be successfully saved to object storage, and can be retrieved from object storage, but they have an error about failing the move and will not play. They can be retranscoded, but if object storage is still enabled they will be stuck in a to move to object storage state, still unplayable. If object storage is disabled and the videos are set to retranscode in the admin interface it will download, transcode, and successfully save to local file system as playable.

![image](https://github.com/Chocobozzz/PeerTube/assets/10343429/54a0342a-7edc-4e0e-b7f2-7f29828689c2)
![image](https://github.com/Chocobozzz/PeerTube/assets/10343429/816758a1-ec0a-4837-bbdd-bd97b925338a)

[peertube log errors for move to object storage.txt](https://github.com/Chocobozzz/PeerTube/files/13819506/peertube.log.errors.for.move.to.object.storage.txt)
[log entries for retranscoding.txt](https://github.com/Chocobozzz/PeerTube/files/13819516/log.entries.for.retranscoding.txt)

### Steps to reproduce

1. Configure object storage
2. Start importing videos
3. Watch as some fail the move to object storage
4.

### Describe the expected behavior

All files to successfully transfer to object storage

### Additional information

* PeerTube instance: Several, have disabled object storage on most comics.peertube.biz is an example still using object storage
  * URL: https://comics.peertube.biz
  * Version:6.02
  * NodeJS version:20.10.0
  * Ffmpeg version: DLP specific binaries from https://github.com/yt-dlp/FFmpeg-Builds

* Browser name, version and platforms on which you could reproduce the bug: Node issue, no browser involved. 
* Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`):

**Comment by dhk2** [comment]
No messages from the SeaweedFS service logs. I'll see if I can turn on more verbose logging.

**Comment by arladmin** [comment]
Same issue as : https://github.com/Chocobozzz/PeerTube/issues/6149#issue-2060956448

**Comment by Chocobozzz** [comment]
@dhk2 can you also try https://github.com/Chocobozzz/PeerTube/issues/6149#issuecomment-1876710960?

**Comment by dhk2** [comment]
ran the command on the comics instance. Seems to be working okay, will know better after a few days worth of new videos. Have a few instances I turned off the data store on until the issue was resolved. Turned it back on and ran script to move everything to object store and one moved ~20 videos without error and the other has moved over a 100 without any errors. Looking good so far, will update with further results

**Comment by dhk2** [comment]
Still not sure if it's completely resolved the issue, 1500 videos moved with ~30 failures to move, but not sure if those are videos that had already failed in earlier testing. transitioned a few more instances back to object storage and kept better notes on current status.

One issue after the the fix is that users are seeing errors when uploading videos and clicking publish.
![image](https://github.com/Chocobozzz/PeerTube/assets/10343429/1bcb5a11-a7ef-4433-bd50-a2cb1e938a92)

Navigating away from video gives the modal "Your video was uploaded to your account and is private. But associated data (tags, description...) will be lost, are you sure you want to leave this page?"

Leave page and video has been successfully moved to object storage and is working perfectly.

```
error [1/5/2024, 12:27:21 AM] Cannot apply function on comichls-hls/2b4477ce-05ef-47a3-97cc-82b81d9c39cc prefix in bucket peertube-videos: no files listed.
{
  "response": {
    "$metadata": {
      "httpStatusCode": 200,
      "requestId": "1704443240822808147",
      "attempts": 1,
      "totalRetryDelay": 0
    }
  },
  "tags": [
    "object-storage"
  ]
}
error[1/5/2024, 12:27:21 AM] Cannot run hook action:api.video.updated of plugin podping.
{
  "err": {
    "stack": "Error: Podping - podping.cloud response: <!DOCTYPE html>\n<!--[if lt IE 7]> <html class=\"no-js ie6 oldie\" lang=\"en-US\"> <![endif]-->\n<!--[if IE 7]>    <html class=\"no-js ie7 oldie\" lang=\"en-US\"> <![endif]-->\n<!--[if IE 8]>    <html class=\"no-js ie8 oldie\" lang=\"en-US\"> <![endif]-->\n<!--[if gt IE 8]><!--> <html class=\"no-js\" lang=\"en-US\"> <!--<![endif]-->\n<head>\n\n\n<title>podping.cloud | 520: Web server is returning an unknown error</title>\n<meta charset=\"UTF-8\" />\n<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\" />\n<meta http-equiv=\"X-UA-Compatible\" content=\"IE=Edge\" />\n<meta name=\"robots\" content=\"noindex, nofollow\" />\n<meta name=\"viewport\" content=\"width=device-width,initial-scale=1\" />\n<link rel=\"stylesheet\" id=\"cf_styles-css\" href=\"/cdn-cgi/styles/main.css\" />\n\n\n</head>\n<body>\n<div id=\"cf-wrapper\">\n    <div id=\"cf-error-details\" class=\"p-0\">\n        <header class=\"mx-auto pt-10 lg:pt-6 lg:px-8 w-240 lg:w-full mb-8\">\n            <h1 class=\"inline-block sm:block sm:mb-2 font-light text-60 lg:text-4xl text-black-dark leading-tight mr-2\">\n              <span class=\"inline-block\">Web server is returning an unknown error</span>\n              <span class=\"code-label\">Error code 520</span>\n            </h1>\n            <div>\n               Visit <a href=\"https://www.cloudflare.com/5xx-error-landing?utm_source=errorcode_520&utm_campaign=podping.cloud\" target=\"_blank\" rel=\"noopener noreferrer\">cloudflare.com</a> for more information.\n            </div>\n            <div class=\"mt-3\">2024-01-05 08:27:20 UTC</div>\n        </header>\n        <div class=\"my-8 bg-gradient-gray\">\n            <div class=\"w-240 lg:w-full mx-auto\">\n                <div class=\"clearfix md:px-8\">\n                  \n<div id=\"cf-browser-status\" class=\" relative w-1/3 md:w-full py-15 md:p-0 md:py-8 md:text-left md:border-solid md:border-0 md:border-b md:border-gray-400 overflow-hidden float-left md:float-none text-center\">\n  <div class=\"relative mb-10 md:m-0\">\n    \n    <span class=\"cf-icon-browser block md:hidden h-20 bg-center bg-no-repeat\"></span>\n    <span class=\"cf-icon-ok w-12 h-12 absolute left-1/2 md:left-auto md:right-0 md:top-0 -ml-6 -bottom-4\"></span>\n    \n  </div>\n  <span class=\"md:block w-full truncate\">You</span>\n  <h3 class=\"md:inline-block mt-3 md:mt-0 text-2xl text-gray-600 font-light leading-1.3\">\n    \n    Browser\n    \n  </h3>\n  <span class=\"leading-1.3 text-2xl text-green-success\">Working</span>\n</div>\n\n<div id=\"cf-cloudflare-status\" class=\" relative w-1/3 md:w-full py-15 md:p-0 md:py-8 md:text-left md:border-solid md:border-0 md:border-b md:border-gray-400 overflow-hidden float-left md:float-none text-center\">\n  <div class=\"relative mb-10 md:m-0\">\n    <a href=\"https://www.cloudflare.com/5xx-error-landing?utm_source=errorcode_520&utm_campaign=podping.cloud\" target=\"_blank\" rel=\"noopener noreferrer\">\n    <span class=\"cf-icon-cloud block md:hidden h-20 bg-center bg-no-repeat\"></span>\n    <span class=\"cf-icon-ok w-12 h-12 absolute left-1/2 md:left-auto md:right-0 md:top-0 -ml-6 -bottom-4\"></span>\n    </a>\n  </div>\n  <span class=\"md:block w-full truncate\">Toronto</span>\n  <h3 class=\"md:inline-block mt-3 md:mt-0 text-2xl text-gray-600 font-light leading-1.3\">\n    <a href=\"https://www.cloudflare.com/5xx-error-landing?utm_source=errorcode_520&utm_campaign=podping.cloud\" target=\"_blank\" rel=\"noopener noreferrer\">\n    Cloudflare\n    </a>\n  </h3>\n  <span class=\"leading-1.3 text-2xl text-green-success\">Working</span>\n</div>\n\n<div id=\"cf-host-status\" class=\"cf-error-source relative w-1/3 md:w-full py-15 md:p-0 md:py-8 md:text-left md:border-solid md:border-0 md:border-b md:border-gray-400 overflow-hidden float-left md:float-none text-center\">\n  <div class=\"relative mb-10 md:m-0\">\n    \n    <span class=\"cf-icon-server block md:hidden h-20 bg-center bg-no-repeat\"></span>\n    <span class=\"cf-icon-error w-12 h-12 absolute left-1/2 md:left-auto md:right-0 md:top-0 -ml-6 -bottom-4\"></span>\n    \n  </div>\n  <span class=\"md:block w-full truncate\">podping.cloud</span>\n  <h3 class=\"md:inline-block mt-3 md:mt-0 text-2xl text-gray-600 font-light leading-1.3\">\n    \n    Host\n    \n  </h3>\n  <span class=\"leading-1.3 text-2xl text-red-error\">Error</span>\n</div>\n\n                </div>\n            </div>\n        </div>\n\n        <div class=\"w-240 lg:w-full mx-auto mb-8 lg:px-8\">\n            <div class=\"clearfix\">\n                <div class=\"w-1/2 md:w-full float-left pr-6 md:pb-10 md:pr-0 leading-relaxed\">\n                    <h2 class=\"text-3xl font-normal leading-1.3 mb-4\">What happened?</h2>\n                    <p>There is an unknown connection issue between Cloudflare and the origin web server. As a result, the web page can not be displayed.</p>\n                </div>\n                <div class=\"w-1/2 md:w-full float-left leading-relaxed\">\n                    <h2 class=\"text-3xl font-normal leading-1.3 mb-4\">What can I do?</h2>\n                          <h3 class=\"text-15 font-semibold mb-2\">If you are a visitor of this website:</h3>\n      <p class=\"mb-6\">Please try again in a few minutes.</p>\n\n      <h3 class=\"text-15 font-semibold mb-2\">If you are the owner of this website:</h3>\n      <p><span>There is an issue between Cloudflare's cache and your origin web server. Cloudflare monitors for these errors and automatically investigates the cause. To help support the investigation, you can pull the corresponding error log from your web server and submit it our support team.  Please include the Ray ID (which is at the bottom of this error page).</span> <a rel=\"noopener noreferrer\" href=\"https://support.cloudflare.com/hc/en-us/articles/200171936-Error-520\">Additional troubleshooting resources</a>.</p>\n                </div>\n            </div>\n        </div>\n\n        <div class=\"cf-error-footer cf-wrapper w-240 lg:w-full py-10 sm:py-4 sm:px-8 mx-auto text-center sm:text-left border-solid border-0 border-t border-gray-300\">\n  <p class=\"text-13\">\n    <span class=\"cf-footer-item sm:block sm:mb-1\">Cloudflare Ray ID: <strong class=\"font-semibold\">840a576f8b295407</strong></span>\n    <span class=\"cf-footer-separator sm:hidden\">&bull;</span>\n    <span id=\"cf-footer-item-ip\" class=\"cf-footer-item hidden sm:block sm:mb-1\">\n      Your IP:\n      <button type=\"button\" id=\"cf-footer-ip-reveal\" class=\"cf-footer-ip-reveal-btn\">Click to reveal</button>\n      <span class=\"hidden\" id=\"cf-footer-ip\">38.102.125.156</span>\n      <span class=\"cf-footer-separator sm:hidden\">&bull;</span>\n    </span>\n    <span class=\"cf-footer-item sm:block sm:mb-1\"><span>Performance &amp; security by</span> <a rel=\"noopener noreferrer\" href=\"https://www.cloudflare.com/5xx-error-landing?utm_source=errorcode_520&utm_campaign=podping.cloud\" id=\"brand_link\" target=\"_blank\">Cloudflare</a></span>\n    \n  </p>\n  <script>(function(){function d(){var b=a.getElementById(\"cf-footer-item-ip\"),c=a.getElementById(\"cf-footer-ip-reveal\");b&&\"classList\"in b&&(b.classList.remove(\"hidden\"),c.addEventListener(\"click\",function(){c.classList.add(\"hidden\");a.getElementById(\"cf-footer-ip\").classList.remove(\"hidden\")}))}var a=document;document.addEventListener&&a.addEventListener(\"DOMContentLoaded\",d)})();</script>\n</div><!-- /.error-footer -->\n\n\n    </div>\n</div>\n</body>\n</html>\n\n    at /var/www/peertube/storage/plugins/node_modules/peertube-plugin-podping/dist/server/main.js:39:15\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async handler (/var/www/peertube/storage/plugins/node_modules/peertube-plugin-podping/dist/server/main.js:101:13)",
    "message": "Podping - podping.cloud response: <!DOCTYPE html>\n<!--[if lt IE 7]> <html class=\"no-js ie6 oldie\" lang=\"en-US\"> <![endif]-->\n<!--[if IE 7]>    <html class=\"no-js ie7 oldie\" lang=\"en-US\"> <![endif]-->\n<!--[if IE 8]>    <html class=\"no-js ie8 oldie\" lang=\"en-US\"> <![endif]-->\n<!--[if gt IE 8]><!--> <html class=\"no-js\" lang=\"en-US\"> <!--<![endif]-->\n<head>\n\n\n<title>podping.cloud | 520: Web server is returning an unknown error</title>\n<meta charset=\"UTF-8\" />\n<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\" />\n<meta http-equiv=\"X-UA-Compatible\" content=\"IE=Edge\" />\n<meta name=\"robots\" content=\"noindex, nofollow\" />\n<meta name=\"viewport\" content=\"width=device-width,initial-scale=1\" />\n<link rel=\"stylesheet\" id=\"cf_styles-css\" href=\"/cdn-cgi/styles/main.css\" />\n\n\n</head>\n<body>\n<div id=\"cf-wrapper\">\n    <div id=\"cf-error-details\" class=\"p-0\">\n        <header class=\"mx-auto pt-10 lg:pt-6 lg:px-8 w-240 lg:w-full mb-8\">\n            <h1 class=\"inline-block sm:block sm:mb-2 font-light text-60 lg:text-4xl text-black-dark leading-tight mr-2\">\n              <span class=\"inline-block\">Web server is returning an unknown error</span>\n              <span class=\"code-label\">Error code 520</span>\n            </h1>\n            <div>\n               Visit <a href=\"https://www.cloudflare.com/5xx-error-landing?utm_source=errorcode_520&utm_campaign=podping.cloud\" target=\"_blank\" rel=\"noopener noreferrer\">cloudflare.com</a> for more information.\n            </div>\n            <div class=\"mt-3\">2024-01-05 08:27:20 UTC</div>\n        </header>\n        <div class=\"my-8 bg-gradient-gray\">\n            <div class=\"w-240 lg:w-full mx-auto\">\n                <div class=\"clearfix md:px-8\">\n                  \n<div id=\"cf-browser-status\" class=\" relative w-1/3 md:w-full py-15 md:p-0 md:py-8 md:text-left md:border-solid md:border-0 md:border-b md:border-gray-400 overflow-hidden float-left md:float-none text-center\">\n  <div class=\"relative mb-10 md:m-0\">\n    \n    <span class=\"cf-icon-browser block md:hidden h-20 bg-center bg-no-repeat\"></span>\n    <span class=\"cf-icon-ok w-12 h-12 absolute left-1/2 md:left-auto md:right-0 md:top-0 -ml-6 -bottom-4\"></span>\n    \n  </div>\n  <span class=\"md:block w-full truncate\">You</span>\n  <h3 class=\"md:inline-block mt-3 md:mt-0 text-2xl text-gray-600 font-light leading-1.3\">\n    \n    Browser\n    \n  </h3>\n  <span class=\"leading-1.3 text-2xl text-green-success\">Working</span>\n</div>\n\n<div id=\"cf-cloudflare-status\" class=\" relative w-1/3 md:w-full py-15 md:p-0 md:py-8 md:text-left md:border-solid md:border-0 md:border-b md:border-gray-400 overflow-hidden float-left md:float-none text-center\">\n  <div class=\"relative mb-10 md:m-0\">\n    <a href=\"https://www.cloudflare.com/5xx-error-landing?utm_source=errorcode_520&utm_campaign=podping.cloud\" target=\"_blank\" rel=\"noopener noreferrer\">\n    <span class=\"cf-icon-cloud block md:hidden h-20 bg-center bg-no-repeat\"></span>\n    <span class=\"cf-icon-ok w-12 h-12 absolute left-1/2 md:left-auto md:right-0 md:top-0 -ml-6 -bottom-4\"></span>\n    </a>\n  </div>\n  <span class=\"md:block w-full truncate\">Toronto</span>\n  <h3 class=\"md:inline-block mt-3 md:mt-0 text-2xl text-gray-600 font-light leading-1.3\">\n    <a href=\"https://www.cloudflare.com/5xx-error-landing?utm_source=errorcode_520&utm_campaign=podping.cloud\" target=\"_blank\" rel=\"noopener noreferrer\">\n    Cloudflare\n    </a>\n  </h3>\n  <span class=\"leading-1.3 text-2xl text-green-success\">Working</span>\n</div>\n\n<div id=\"cf-host-status\" class=\"cf-error-source relative w-1/3 md:w-full py-15 md:p-0 md:py-8 md:text-left md:border-solid md:border-0 md:border-b md:border-gray-400 overflow-hidden float-left md:float-none text-center\">\n  <div class=\"relative mb-10 md:m-0\">\n    \n    <span class=\"cf-icon-server block md:hidden h-20 bg-center bg-no-repeat\"></span>\n    <span class=\"cf-icon-error w-12 h-12 absolute left-1/2 md:left-auto md:right-0 md:top-0 -ml-6 -bottom-4\"></span>\n    \n  </div>\n  <span class=\"md:block w-full truncate\">podping.cloud</span>\n  <h3 class=\"md:inline-block mt-3 md:mt-0 text-2xl text-gray-600 font-light leading-1.3\">\n    \n    Host\n    \n  </h3>\n  <span class=\"leading-1.3 text-2xl text-red-error\">Error</span>\n</div>\n\n                </div>\n            </div>\n        </div>\n\n        <div class=\"w-240 lg:w-full mx-auto mb-8 lg:px-8\">\n            <div class=\"clearfix\">\n                <div class=\"w-1/2 md:w-full float-left pr-6 md:pb-10 md:pr-0 leading-relaxed\">\n                    <h2 class=\"text-3xl font-normal leading-1.3 mb-4\">What happened?</h2>\n                    <p>There is an unknown connection issue between Cloudflare and the origin web server. As a result, the web page can not be displayed.</p>\n                </div>\n                <div class=\"w-1/2 md:w-full float-left leading-relaxed\">\n                    <h2 class=\"text-3xl font-normal leading-1.3 mb-4\">What can I do?</h2>\n                          <h3 class=\"text-15 font-semibold mb-2\">If you are a visitor of this website:</h3>\n      <p class=\"mb-6\">Please try again in a few minutes.</p>\n\n      <h3 class=\"text-15 font-semibold mb-2\">If you are the owner of this website:</h3>\n      <p><span>There is an issue between Cloudflare's cache and your origin web server. Cloudflare monitors for these errors and automatically investigates the cause. To help support the investigation, you can pull the corresponding error log from your web server and submit it our support team.  Please include the Ray ID (which is at the bottom of this error page).</span> <a rel=\"noopener noreferrer\" href=\"https://support.cloudflare.com/hc/en-us/articles/200171936-Error-520\">Additional troubleshooting resources</a>.</p>\n                </div>\n            </div>\n        </div>\n\n        <div class=\"cf-error-footer cf-wrapper w-240 lg:w-full py-10 sm:py-4 sm:px-8 mx-auto text-center sm:text-left border-solid border-0 border-t border-gray-300\">\n  <p class=\"text-13\">\n    <span class=\"cf-footer-item sm:block sm:mb-1\">Cloudflare Ray ID: <strong class=\"font-semibold\">840a576f8b295407</strong></span>\n    <span class=\"cf-footer-separator sm:hidden\">&bull;</span>\n    <span id=\"cf-footer-item-ip\" class=\"cf-footer-item hidden sm:block sm:mb-1\">\n      Your IP:\n      <button type=\"button\" id=\"cf-footer-ip-reveal\" class=\"cf-footer-ip-reveal-btn\">Click to reveal</button>\n      <span class=\"hidden\" id=\"cf-footer-ip\">38.102.125.156</span>\n      <span class=\"cf-footer-separator sm:hidden\">&bull;</span>\n    </span>\n    <span class=\"cf-footer-item sm:block sm:mb-1\"><span>Performance &amp; security by</span> <a rel=\"noopener noreferrer\" href=\"https://www.cloudflare.com/5xx-error-landing?utm_source=errorcode_520&utm_campaign=podping.cloud\" id=\"brand_link\" target=\"_blank\">Cloudflare</a></span>\n    \n  </p>\n  <script>(function(){function d(){var b=a.getElementById(\"cf-footer-item-ip\"),c=a.getElementById(\"cf-footer-ip-reveal\");b&&\"classList\"in b&&(b.classList.remove(\"hidden\"),c.addEventListener(\"click\",function(){c.classList.add(\"hidden\");a.getElementById(\"cf-footer-ip\").classList.remove(\"hidden\")}))}var a=document;document.addEventListener&&a.addEventListener(\"DOMContentLoaded\",d)})();</script>\n</div><!-- /.error-footer -->\n\n\n    </div>\n</div>\n</body>\n</html>\n"
  }
}
warn[1/5/2024, 12:27:21 AM] Cannot execute updateVideo with many retries.
{
  "err": {
    "stack": "Error: Cannot apply function on comichls-hls/2b4477ce-05ef-47a3-97cc-82b81d9c39cc prefix in bucket peertube-videos: no files listed.\n    at applyOnPrefix (file:///var/www/peertube/versions/peertube-v6.0.2/dist/core/lib/object-storage/shared/object-storage-helpers.js:175:15)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async updateHLSFilesACL (file:///var/www/peertube/versions/peertube-v6.0.2/dist/core/lib/object-storage/videos.js:52:5)\n    at async moveFiles (file:///var/www/peertube/versions/peertube-v6.0.2/dist/core/lib/video-privacy.js:52:13)\n    at async moveFilesIfPrivacyChanged (file:///var/www/peertube/versions/peertube-v6.0.2/dist/core/lib/video-privacy.js:26:9)\n    at async addVideoJobsAfterUpdate (file:///var/www/peertube/versions/peertube-v6.0.2/dist/core/lib/video.js:91:29)\n    at async updateVideo (file:///var/www/peertube/versions/peertube-v6.0.2/dist/core/controllers/api/videos/update.js:112:9)",
    "message": "Cannot apply function on comichls-hls/2b4477ce-05ef-47a3-97cc-82b81d9c39cc prefix in bucket peertube-videos: no files listed."
  }
}
error[1/5/2024, 12:27:21 AM] Error in controller.
{
  "err": "Error: Cannot apply function on comichls-hls/2b4477ce-05ef-47a3-97cc-82b81d9c39cc prefix in bucket peertube-videos: no files listed.\n    at applyOnPrefix (file:///var/www/peertube/versions/peertube-v6.0.2/dist/core/lib/object-storage/shared/object-storage-helpers.js:175:15)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async updateHLSFilesACL (file:///var/www/peertube/versions/peertube-v6.0.2/dist/core/lib/object-storage/videos.js:52:5)\n    at async moveFiles (file:///var/www/peertube/versions/peertube-v6.0.2/dist/core/lib/video-privacy.js:52:13)\n    at async moveFilesIfPrivacyChanged (file:///var/www/peertube/versions/peertube-v6.0.2/dist/core/lib/video-privacy.js:26:9)\n    at async addVideoJobsAfterUpdate (file:///var/www/peertube/versions/peertube-v6.0.2/dist/core/lib/video.js:91:29)\n    at async updateVideo (file:///var/www/peertube/versions/peertube-v6.0.2/dist/core/controllers/api/videos/update.js:112:9)"
}
error[1/5/2024, 12:27:21 AM] Client log: Backend returned code 500, errorMessage is: Cannot apply function on comichls-hls/2b4477ce-05ef-47a3-97cc-82b81d9c39cc prefix in bucket peertube-videos: no files listed.
{
  "tags": [
    "client"
  ],
  "username": "errhead",
  "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36",
  "url": "https://comics.peertube.biz/videos/upload#upload"
}
error[1/5/2024, 12:27:21 AM] Client log: {"message":"Cannot apply function on comichls-hls/2b4477ce-05ef-47a3-97cc-82b81d9c39cc prefix in bucket peertube-videos: no files listed.","status":500,"body":{"type":"https://docs.joinpeertube.org/api-rest-reference.html#section/Errors/Error","detail":"Cannot apply function on comichls-hls/2b4477ce-05ef-47a3-97cc-82b81d9c39cc prefix in bucket peertube-videos: no files listed.","status":500,"docs":"https://docs.joinpeertube.org/api-rest-reference.html#operation/putVideo","code":"Error","error":"Cannot apply function on comichls-hls/2b4477ce-05ef-47a3-97cc-82b81d9c39cc prefix in bucket peertube-videos: no files listed."},"headers":{"normalizedNames":{},"lazyUpdate":null}}
{
  "tags": [
    "client"
  ],
  "username": "errhead",
  "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36",
  "url": "https://comics.peertube.biz/videos/upload#upload"
}



```

**Comment by Chocobozzz** [comment]
If you checked the bucket contains files in this prefix, then I think it's the same issue as https://framacolibri.org/t/peertube-setup-with-minio-s3-object-storage-system-cannot-delete-content-from-bucket/19722

**Comment by dhk2** [comment]
Thanks, I'll see if there's something I can do with permissions or SeaweedFS settings to fix that.

**Comment by Chocobozzz** [comment]
Any news @dhk2?

**Comment by dhk2** [comment]
Still having the original issue with longer videos, not sure if it's PeerTube or an issue with my object store. Working on building a fresh clean object store to test against this weekend.

________________________________

**Comment by dhk2** [comment]
Okay, looks like I've got it working

Fresh PeerTube and Object store
reproduce error on 300meg file reliably
run suggest command in peertube-latest, move still fails.
error message is huge, important bits seem to be

```
"message": "The specified method is not allowed against this resource."
"Resource": "/spokane1-wv-021fc7e7-e46d-40fa-923d-73d4ef360108-2160.mp4",
"path": "/spokane1-wv-021fc7e7-e46d-40fa-923d-73d4ef360108-2160.mp4?uploads=&x-id=CreateMultipartUpload"
```

Tried changing production.yaml object_storage.max_upload_part to 100GB

300m file now moves to object store successfully 
1.6g file works as well

Setting up a channel sync to to stress test a bunch of videos today because intermittent errors are tricksy, but cautiously optimistic. If it works, I'll try using the same fixes in my production object store.

**Comment by Chocobozzz** [comment]
Hi,

Then it seems to be an issue with the multipart upload: https://docs.aws.amazon.com/AmazonS3/latest/userguide/mpuoverview.html

I suggest to check seaweedfs supports this method and also host style request. If yes, please open an issue on their repository with the full error log. Unfortunately I don't think we can do anything on PeerTube side as we use the [official aws library](https://github.com/aws/aws-sdk-js-v3/tree/main/lib/lib-storage) to upload videos.

**Comment by dhk2** [comment]
The docs say they support multipart upload. I'll see about opening an issue.

I synched ~700 videos over the weekend, many in the 3 gig range, the vast majority worked perfectly, still had some intermittent errors. error messaging so far has all been saying "data is too long".

`RangeError: data is too long     at Hash.update (node:internal/crypto/hash:108:22)     at Hash.update (/var/www/peertube/versions/peertube-v6.0.2/node_modules/@smithy/hash-node/dist-cjs/index.js:15:19)     at getPayloadHash (/var/www/peertube/versions/peertube-v6.0.2/node_modules/@smithy/signature-v4/dist-cjs/getPayloadHash.js:19:18)     at SignatureV4S3Express.signRequest (/var/www/peertube/versions/peertube-v6.0.2/node_modules/@smithy/signature-v4/dist-cjs/SignatureV4.js:116:71)`
