### ISSUE TITLE
Error while restoring the database

### ISSUE THREAD

**Issue by anmol26s** [Chocobozzz/PeerTube#616]
Peertube is running well on install but when I remove it and restore the database I get  errors in tables : 
```
SET
SET
SET
SET
SET
SET
SET
SET
CREATE EXTENSION
COMMENT
SET
CREATE TYPE
ALTER TYPE
CREATE TYPE
ALTER TYPE
CREATE TYPE
ALTER TYPE
CREATE TYPE
ALTER TYPE
CREATE TYPE
ALTER TYPE
SET
SET
CREATE TABLE
ALTER TABLE
CREATE TABLE
ALTER TABLE
CREATE SEQUENCE
ALTER TABLE
ALTER SEQUENCE
CREATE SEQUENCE
ALTER TABLE
ALTER SEQUENCE
CREATE TABLE
ALTER TABLE
CREATE TABLE
ALTER TABLE
CREATE SEQUENCE
ALTER TABLE
ALTER SEQUENCE
CREATE SEQUENCE
ALTER TABLE
ALTER SEQUENCE
CREATE TABLE
ALTER TABLE
CREATE SEQUENCE
ALTER TABLE
ALTER SEQUENCE
CREATE TABLE
ALTER TABLE
CREATE SEQUENCE
ALTER TABLE
ALTER SEQUENCE
CREATE TABLE
ALTER TABLE
CREATE SEQUENCE
ALTER TABLE
ALTER SEQUENCE
CREATE TABLE
ALTER TABLE
CREATE SEQUENCE
ALTER TABLE
ALTER SEQUENCE
CREATE TABLE
ALTER TABLE
CREATE SEQUENCE
ALTER TABLE
ALTER SEQUENCE
CREATE TABLE
ALTER TABLE
CREATE SEQUENCE
ALTER TABLE
ALTER SEQUENCE
CREATE TABLE
ALTER TABLE
CREATE SEQUENCE
ALTER TABLE
ALTER SEQUENCE
CREATE TABLE
ALTER TABLE
CREATE TABLE
ALTER TABLE
CREATE SEQUENCE
ALTER TABLE
ALTER SEQUENCE
CREATE TABLE
ALTER TABLE
CREATE SEQUENCE
ALTER TABLE
ALTER SEQUENCE
CREATE TABLE
ALTER TABLE
CREATE SEQUENCE
ALTER TABLE
ALTER SEQUENCE
CREATE TABLE
ALTER TABLE
CREATE SEQUENCE
ALTER TABLE
ALTER SEQUENCE
CREATE TABLE
ALTER TABLE
CREATE SEQUENCE
ALTER TABLE
ALTER SEQUENCE
CREATE TABLE
ALTER TABLE
CREATE SEQUENCE
ALTER TABLE
ALTER SEQUENCE
CREATE TABLE
ALTER TABLE
CREATE SEQUENCE
ALTER TABLE
ALTER SEQUENCE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
Warning: ERROR:  character with byte sequence 0xf0 0x9f 0xa5 0x94 in encoding "UTF8" has no equivalent in encoding "LATIN1"
Warning: CONTEXT:  COPY account, line 5
COPY 105
 setval
--------
    157
(1 row)

 setval
--------
    148
(1 row)

COPY 175
COPY 0
 setval
--------
      1
(1 row)

 setval
--------
    175
(1 row)

COPY 1
 setval
--------
      1
(1 row)

COPY 89
 setval
--------
     89
(1 row)

COPY 1
 setval
--------
      1
(1 row)

COPY 0
 setval
--------
      1
(1 row)

COPY 60
 setval
--------
     60
(1 row)

COPY 92
 setval
--------
     92
Warning: ERROR:  character with byte sequence 0xe2 0x80 0x94 in encoding "UTF8" has no equivalent in encoding "LATIN1"
Warning: CONTEXT:  COPY video, line 11
(1 row)

COPY 1
 setval
--------
Warning: ERROR:  character with byte sequence 0xc4 0x8d in encoding "UTF8" has no equivalent in encoding "LATIN1"
Warning: CONTEXT:  COPY videoChannel, line 14
      1
(1 row)

COPY 0
 setval
--------
      1
(1 row)

Warning: ERROR:  character with byte sequence 0xf0 0x9f 0x98 0x8d in encoding "UTF8" has no equivalent in encoding "LATIN1"
Warning: CONTEXT:  COPY videoComment, line 3
COPY 0
 setval
--------
      1
(1 row)

 setval
--------
     27
(1 row)

 setval
--------
      8
(1 row)

COPY 177
 setval
--------
    177
(1 row)

COPY 75
 setval
--------
     75
(1 row)

COPY 139
 setval
--------
     46
(1 row)

ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
CREATE INDEX
CREATE INDEX
CREATE INDEX
CREATE INDEX
CREATE INDEX
CREATE INDEX
CREATE INDEX
CREATE INDEX
CREATE INDEX
CREATE INDEX
CREATE INDEX
CREATE INDEX
CREATE INDEX
CREATE INDEX
CREATE INDEX
CREATE INDEX
CREATE INDEX
CREATE INDEX
CREATE INDEX
CREATE INDEX
CREATE INDEX
CREATE INDEX
CREATE INDEX
CREATE INDEX
CREATE INDEX
CREATE INDEX
CREATE INDEX
CREATE INDEX
CREATE INDEX
CREATE INDEX
CREATE INDEX
CREATE INDEX
CREATE INDEX
CREATE INDEX
CREATE INDEX
CREATE INDEX
CREATE INDEX
CREATE INDEX
CREATE INDEX
CREATE INDEX
CREATE INDEX
Warning: ERROR:  insert or update on table "accountVideoRate" violates foreign key constraint "accountVideoRate_accountId_fkey"
Warning: DETAIL:  Key (accountId)=(5) is not present in table "account".
Warning: ERROR:  insert or update on table "accountVideoRate" violates foreign key constraint "accountVideoRate_videoId_fkey"
Warning: DETAIL:  Key (videoId)=(1) is not present in table "video".
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
Warning: ERROR:  insert or update on table "videoFile" violates foreign key constraint "videoFile_videoId_fkey"
Warning: DETAIL:  Key (videoId)=(1) is not present in table "video".
ALTER TABLE
Warning: ERROR:  insert or update on table "videoShare" violates foreign key constraint "videoShare_videoId_fkey"
Warning: DETAIL:  Key (videoId)=(2) is not present in table "video".
ALTER TABLE
Warning: ERROR:  insert or update on table "videoTag" violates foreign key constraint "videoTag_videoId_fkey"
Warning: DETAIL:  Key (videoId)=(1) is not present in table "video".
ALTER TABLE
```
Running log : 

```
 Started PeerTube daemon.
Jun 01 19:12:55 domain.tld peertube[18134]: > peertube@1.0.0-beta.7 start /var/www/peertube
Jun 01 19:12:55 domain.tld peertube[18134]: > node dist/server
Jun 01 19:12:58 domain.tld peertube[18134]: [video.domain.tld:443] 2018-06-01 19:12:58.091 info: Database peertube_peertube is ready.
Jun 01 19:12:58 domain.tld peertube[18134]: [video.domain.tld:443] 2018-06-01 19:12:58.335 info: Creating the administrator.
Jun 01 19:12:58 domain.tld peertube[18134]: [video.domain.tld:443] 2018-06-01 19:12:58.500 error: Cannot install application. {
Jun 01 19:12:58 domain.tld peertube[18134]: "err": "SequelizeUniqueConstraintError: Validation error\n    at Query.formatError (/var/www/peertube/node_modules/sequelize/lib/dialects/postgres/query.js:325:18)\n    at query.catch.err (/var/www/peertube/node_modules/sequelize/lib/dialects/postgres/query.js:86:18)\n    at tryCatcher (/var/www/peertube/node_modules/bluebird/js/release/util.js:16:23)\n    at Promise._settlePromiseFromHandler (/var/www/peertube/node_modules/bluebird/js/release/promise.js:512:31)\n    at Promise._settlePromise (/var/www/peertube/node_modules/bluebird/js/release/promise.js:569:18)\n    at Promise._settlePromise0 (/var/www/peertube/node_modules/bluebird/js/release/promise.js:614:10)\n    at Promise._settlePromises (/var/www/peertube/node_modules/bluebird/js/release/promise.js:689:18)\n    at Async._drainQueue (/var/www/peertube/node_modules/bluebird/js/release/async.js:133:16)\n    at Async._drainQueues (/var/www/peertube/node_modules/bluebird/js/release/async.js:143:10)\n    at Immediate.Async.drainQueues (/var/www/peertube/node_modules/bluebird/js/release/async.js:17:14)\n    at runCallback (timers.js:810:20)\n    at tryOnImmediate (timers.js:768:5)\n    at processImmediate [as _immediateCallback] (timers.js:745:5)"
Jun 01 19:12:58 domain.tld peertube[18134]: }
Jun 01 19:12:58 domain.tld peertube[18134]: npm ERR! code ELIFECYCLE
Jun 01 19:12:58 domain.tld peertube[18134]: npm ERR! errno 255
Jun 01 19:12:58 domain.tld peertube[18134]: npm ERR! peertube@1.0.0-beta.7 start: `node dist/server`
Jun 01 19:12:58 domain.tld peertube[18134]: npm ERR! Exit status 255
Jun 01 19:12:58 domain.tld peertube[18134]: npm ERR!
Jun 01 19:12:58 domain.tld peertube[18134]: npm ERR! Failed at the peertube@1.0.0-beta.7 start script.
Jun 01 19:12:58 domain.tld peertube[18134]: npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
Jun 01 19:12:58 domain.tld peertube[18134]: ┌────────────────────────────────────────────────────────────┐
Jun 01 19:12:58 domain.tld peertube[18134]: │                  npm update check failed                   │
Jun 01 19:12:58 domain.tld systemd[1]: peertube.service: Main process exited, code=exited, status=255/n/a
Jun 01 19:12:58 domain.tld systemd[1]: peertube.service: Unit entered failed state.
Jun 01 19:12:58 domain.tld systemd[1]: peertube.service: Failed with result 'exit-code'.
Jun 01 19:12:58 domain.tld systemd[1]: peertube.service: Service hold-off time over, scheduling restart.

```

**Comment by Chocobozzz** [comment]
What commands did you execute to dump and restore the database?

**Comment by anmol26s** [comment]
I am doing a Peertube package https://github.com/YunoHost-Apps/peertube_ynh/tree/testing for YunoHost.
All the postgres commans are called from here(installation,backup,restore): https://github.com/YunoHost-Apps/peertube_ynh/blob/testing/scripts/psql.sh

For installing: 
`sudo --login --user=postgres psql -c"CREATE USER peertube WITH PASSWORD 'random_pwd'" postgres`
`sudo --login --user=postgres psql "CREATE DATABASE peertube_peertube ENCODING 'UTF8' LC_COLLATE='C' LC_CTYPE='C' template=template0 OWNER peertube;"`
See Installation : https://github.com/YunoHost-Apps/peertube_ynh/blob/testing/scripts/install#L120

For backup:
`sudo --login --user=postgres pg_dump "peertube_peertube" > "db.sql"
`
See backup: https://github.com/YunoHost-Apps/peertube_ynh/blob/testing/scripts/backup#L63

For restore: 
`sudo --login --user=postgres psql -c"CREATE USER peertube WITH PASSWORD 'random_pwd'" postgres`
`sudo --login --user=postgres createdb --owner="peertube" "peertube_peertube"`
`sudo --login --user=postgres psql peertube_"peertube" < "db.sql"
`
See here: https://github.com/YunoHost-Apps/peertube_ynh/blob/testing/scripts/restore#L116
`

**Comment by anmol26s** [comment]
After the restore the database list show:                

                    List of databases
       Name        |     Owner      | Encoding | Collate | Ctype |   Access privileges   
-------------------+----------------+----------+---------+-------+-----------------------
peertube_peertube | peertube       | LATIN1   | en_US   | en_US | 

Should the encoding be UTF8?

**Comment by Chocobozzz** [comment]
Try a different format for pg_dump, like we do in the documentation https://github.com/Chocobozzz/PeerTube/blob/develop/support/doc/production.md#manually so you can use pg_restore instead of plain SQL commands.

**Comment by anmol26s** [comment]
Changing the encoding to UTF8 worked.
Thanks
