### ISSUE TITLE
Setup issues

### ISSUE THREAD

**Issue by Anurag1940** [Chocobozzz/PeerTube#6190]
### Describe the problem

I'm trying to setup this project on local. When i made the build with "npm run build" and run the project with "npm start" it gave me these errors please help me setup this project.
Error: Invalid config source.
    at getLocalConfigDir (file:///D:/Office_Work/React/PeerTube-develop1/dist/core/initializers/config.js:614:15)
    at getLocalConfigFilePath (file:///D:/Office_Work/React/PeerTube-develop1/dist/core/initializers/config.js:597:28)
    at file:///D:/Office_Work/React/PeerTube-develop1/dist/core/initializers/config.js:11:18
    at ModuleJob.run (node:internal/modules/esm/module_job:218:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:329:24)
    at async loadESM (node:internal/process/esm_loader:28:7)
    at async handleMainPromise (node:internal/modules/run_main:113:12)

### Additional information

* PeerTube instance URL:
* PeerTube version:
* NodeJS version:
* Ffmpeg version:
* Redis version:
* PostgreSQL version:

**Comment by Chocobozzz** [comment]
Hi,

Have you followed [this guide](https://docs.joinpeertube.org/install/unofficial) to run peertube from source?

If you want to develop on peertube you can also follow https://docs.joinpeertube.org/contribute/getting-started#develop

**Comment by Anurag1940** [comment]
The commands that are in guide for unofficial installation how can i use that? Is it for terminal ?

**Comment by Chocobozzz** [comment]
>  Is it use for terminal ?

Yes it is :) Don't hesitate to use https://framacolibri.org/c/peertube for community support to help you to install peertube from sources
