### ISSUE TITLE
error: uncaughtException: UTP_ECONNRESET

### ISSUE THREAD

**Issue by Showfom** [Chocobozzz/PeerTube#6222]
### Describe the current behavior

The peertube service was stopped suddenly and need to be manually restarted.

### Steps to reproduce

Nothing changed

### Additional information

* PeerTube instance:
  * URL:
  * Version: 6.0.3
  * NodeJS version: v18.19.0
  * Ffmpeg version: 5.1.4-0+deb12u1

* Browser name, version and platforms on which you could reproduce the bug:
* Link to browser console log if relevant:
* Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`):

```
Feb 14 14:47:50 debian peertube[710422]: [example.com:443] 2024-02-14 14:47:50.470 error: uncaughtException: UTP_ECONNRESET
Feb 14 14:47:50 debian peertube[710422]: Error: UTP_ECONNRESET
Feb 14 14:47:50 debian peertube[710422]:     at createUTPError (/var/www/peertube/versions/peertube-v6.0.3/node_modules/utp-native/lib/connection.js:238:15)
Feb 14 14:47:50 debian peertube[710422]:     at Connection._onerror (/var/www/peertube/versions/peertube-v6.0.3/node_modules/utp-native/lib/connection.js:175:16) {
Feb 14 14:47:50 debian peertube[710422]:   "error": {
Feb 14 14:47:50 debian peertube[710422]:     "stack": "Error: UTP_ECONNRESET\n    at createUTPError (/var/www/peertube/versions/peertube-v6.0.3/node_modules/utp-native/lib/connection.js:238:15)\n    at Connection._onerror (/var/www/peertube/versions/peertube-v6.0.3/node_modules/utp-native/lib/connection.js:175:16)",
Feb 14 14:47:50 debian peertube[710422]:     "message": "UTP_ECONNRESET",
Feb 14 14:47:50 debian peertube[710422]:     "code": "UTP_ECONNRESET",
Feb 14 14:47:50 debian peertube[710422]:     "errno": 1
Feb 14 14:47:50 debian peertube[710422]:   },
Feb 14 14:47:50 debian peertube[710422]:   "stack": "Error: UTP_ECONNRESET\n    at createUTPError (/var/www/peertube/versions/peertube-v6.0.3/node_modules/utp-native/lib/connection.js:238:15)\n    at Connection._onerror (/var/www/peertube/versions/peertube-v6.0.3/node_modules/utp-native/lib/connection.js:175:16)",
Feb 14 14:47:50 debian peertube[710422]:   "exception": true,
Feb 14 14:47:50 debian peertube[710422]:   "date": "Wed Feb 14 2024 14:47:50 GMT+0000 (Coordinated Universal Time)",
Feb 14 14:47:50 debian peertube[710422]:   "process": {
Feb 14 14:47:50 debian peertube[710422]:     "pid": 710422,
Feb 14 14:47:50 debian peertube[710422]:     "uid": 1001,
Feb 14 14:47:50 debian peertube[710422]:     "gid": 1001,
Feb 14 14:47:50 debian peertube[710422]:     "cwd": "/var/www/peertube/versions/peertube-v6.0.3",
Feb 14 14:47:50 debian peertube[710422]:     "execPath": "/usr/bin/node",
Feb 14 14:47:50 debian peertube[710422]:     "version": "v18.19.0",
Feb 14 14:47:50 debian peertube[710422]:     "argv": [
Feb 14 14:47:50 debian peertube[710422]:       "/usr/bin/node",
Feb 14 14:47:50 debian peertube[710422]:       "/var/www/peertube/versions/peertube-v6.0.3/dist/server"
Feb 14 14:47:50 debian peertube[710422]:     ],
Feb 14 14:47:50 debian peertube[710422]:     "memoryUsage": {
Feb 14 14:47:50 debian peertube[710422]:       "rss": 1313685504,
Feb 14 14:47:50 debian peertube[710422]:       "heapTotal": 135397376,
Feb 14 14:47:50 debian peertube[710422]:       "heapUsed": 123854792,
Feb 14 14:47:50 debian peertube[710422]:       "external": 75674417,
Feb 14 14:47:50 debian peertube[710422]:       "arrayBuffers": 72305755
Feb 14 14:47:50 debian peertube[710422]:     }
Feb 14 14:47:50 debian peertube[710422]:   },
Feb 14 14:47:50 debian peertube[710422]:   "os": {
Feb 14 14:47:50 debian peertube[710422]:     "loadavg": [
Feb 14 14:47:50 debian peertube[710422]:       10.07,
Feb 14 14:47:50 debian peertube[710422]:       9.05,
Feb 14 14:47:50 debian peertube[710422]:       6.53
Feb 14 14:47:50 debian peertube[710422]:     ],
Feb 14 14:47:50 debian peertube[710422]:     "uptime": 2595231.67
Feb 14 14:47:50 debian peertube[710422]:   },
Feb 14 14:47:50 debian peertube[710422]:   "trace": [
Feb 14 14:47:50 debian peertube[710422]:     {
Feb 14 14:47:50 debian peertube[710422]:       "column": 15,
Feb 14 14:47:50 debian peertube[710422]:       "file": "/var/www/peertube/versions/peertube-v6.0.3/node_modules/utp-native/lib/connection.js",
Feb 14 14:47:50 debian peertube[710422]:       "function": "createUTPError",
Feb 14 14:47:50 debian peertube[710422]:       "line": 238,
Feb 14 14:47:50 debian peertube[710422]:       "method": null,
Feb 14 14:47:50 debian peertube[710422]:       "native": false
Feb 14 14:47:50 debian peertube[710422]:     },
Feb 14 14:47:50 debian peertube[710422]:     {
Feb 14 14:47:50 debian peertube[710422]:       "column": 16,
Feb 14 14:47:50 debian peertube[710422]:       "file": "/var/www/peertube/versions/peertube-v6.0.3/node_modules/utp-native/lib/connection.js",
Feb 14 14:47:50 debian peertube[710422]:       "function": "Connection._onerror",
Feb 14 14:47:50 debian peertube[710422]:       "line": 175,
Feb 14 14:47:50 debian peertube[710422]:       "method": "_onerror",
Feb 14 14:47:50 debian peertube[710422]:       "native": false
Feb 14 14:47:50 debian peertube[710422]:     }
Feb 14 14:47:50 debian peertube[710422]:   ]
Feb 14 14:47:50 debian peertube[710422]: }
Feb 14 14:47:50 debian peertube[710422]: [example.com:443 uploadx] 2024-02-14 14:47:50.472 error: uncaughtException: UTP_ECONNRESET
Feb 14 14:47:50 debian peertube[710422]: Error: UTP_ECONNRESET
Feb 14 14:47:50 debian peertube[710422]:     at createUTPError (/var/www/peertube/versions/peertube-v6.0.3/node_modules/utp-native/lib/connection.js:238:15)
Feb 14 14:47:50 debian peertube[710422]:     at Connection._onerror (/var/www/peertube/versions/peertube-v6.0.3/node_modules/utp-native/lib/connection.js:175:16) {
Feb 14 14:47:50 debian peertube[710422]:   "error": {
Feb 14 14:47:50 debian peertube[710422]:     "stack": "Error: UTP_ECONNRESET\n    at createUTPError (/var/www/peertube/versions/peertube-v6.0.3/node_modules/utp-native/lib/connection.js:238:15)\n    at Connection._onerror (/var/www/peertube/versions/peertube-v6.0.3/node_modules/utp-native/lib/connection.js:175:16)",
Feb 14 14:47:50 debian peertube[710422]:     "message": "UTP_ECONNRESET",
Feb 14 14:47:50 debian peertube[710422]:     "code": "UTP_ECONNRESET",
Feb 14 14:47:50 debian peertube[710422]:     "errno": 1
Feb 14 14:47:50 debian peertube[710422]:   },
Feb 14 14:47:50 debian peertube[710422]:   "stack": "Error: UTP_ECONNRESET\n    at createUTPError (/var/www/peertube/versions/peertube-v6.0.3/node_modules/utp-native/lib/connection.js:238:15)\n    at Connection._onerror (/var/www/peertube/versions/peertube-v6.0.3/node_modules/utp-native/lib/connection.js:175:16)",
Feb 14 14:47:50 debian peertube[710422]:   "exception": true,
Feb 14 14:47:50 debian peertube[710422]:   "date": "Wed Feb 14 2024 14:47:50 GMT+0000 (Coordinated Universal Time)",
Feb 14 14:47:50 debian peertube[710422]:   "process": {
Feb 14 14:47:50 debian peertube[710422]:     "pid": 710422,
Feb 14 14:47:50 debian peertube[710422]:     "uid": 1001,
Feb 14 14:47:50 debian peertube[710422]:     "gid": 1001,
Feb 14 14:47:50 debian peertube[710422]:     "cwd": "/var/www/peertube/versions/peertube-v6.0.3",
Feb 14 14:47:50 debian peertube[710422]:     "execPath": "/usr/bin/node",
Feb 14 14:47:50 debian peertube[710422]:     "version": "v18.19.0",
Feb 14 14:47:50 debian peertube[710422]:     "argv": [
Feb 14 14:47:50 debian peertube[710422]:       "/usr/bin/node",
Feb 14 14:47:50 debian peertube[710422]:       "/var/www/peertube/versions/peertube-v6.0.3/dist/server"
Feb 14 14:47:50 debian peertube[710422]:     ],
Feb 14 14:47:50 debian peertube[710422]:     "memoryUsage": {
Feb 14 14:47:50 debian peertube[710422]:       "rss": 1312882688,
Feb 14 14:47:50 debian peertube[710422]:       "heapTotal": 135397376,
Feb 14 14:47:50 debian peertube[710422]:       "heapUsed": 123236360,
Feb 14 14:47:50 debian peertube[710422]:       "external": 75674481,
Feb 14 14:47:50 debian peertube[710422]:       "arrayBuffers": 72293196
Feb 14 14:47:50 debian peertube[710422]:     }
Feb 14 14:47:50 debian peertube[710422]:   },
Feb 14 14:47:50 debian peertube[710422]:   "os": {
Feb 14 14:47:50 debian peertube[710422]:     "loadavg": [
Feb 14 14:47:50 debian peertube[710422]:       10.07,
Feb 14 14:47:50 debian peertube[710422]:       9.05,
Feb 14 14:47:50 debian peertube[710422]:       6.53
Feb 14 14:47:50 debian peertube[710422]:     ],
Feb 14 14:47:50 debian peertube[710422]:     "uptime": 2595231.68
Feb 14 14:47:50 debian peertube[710422]:   },
Feb 14 14:47:50 debian peertube[710422]:   "trace": [
Feb 14 14:47:50 debian peertube[710422]:     {
Feb 14 14:47:50 debian peertube[710422]:       "column": 15,
Feb 14 14:47:50 debian peertube[710422]:       "file": "/var/www/peertube/versions/peertube-v6.0.3/node_modules/utp-native/lib/connection.js",
Feb 14 14:47:50 debian peertube[710422]:       "function": "createUTPError",
Feb 14 14:47:50 debian peertube[710422]:       "line": 238,
Feb 14 14:47:50 debian peertube[710422]:       "method": null,
Feb 14 14:47:50 debian peertube[710422]:       "native": false
Feb 14 14:47:50 debian peertube[710422]:     },
Feb 14 14:47:50 debian peertube[710422]:     {
Feb 14 14:47:50 debian peertube[710422]:       "column": 16,
Feb 14 14:47:50 debian peertube[710422]:       "file": "/var/www/peertube/versions/peertube-v6.0.3/node_modules/utp-native/lib/connection.js",
Feb 14 14:47:50 debian peertube[710422]:       "function": "Connection._onerror",
Feb 14 14:47:50 debian peertube[710422]:       "line": 175,
Feb 14 14:47:50 debian peertube[710422]:       "method": "_onerror",
Feb 14 14:47:50 debian peertube[710422]:       "native": false
Feb 14 14:47:50 debian peertube[710422]:     }
Feb 14 14:47:50 debian peertube[710422]:   ]
Feb 14 14:47:50 debian peertube[710422]: }
Feb 14 14:51:01 debian systemd[1]: Stopping peertube.service - PeerTube daemon...
Feb 14 14:51:01 debian systemd[1]: peertube.service: Deactivated successfully.
Feb 14 14:51:01 debian systemd[1]: Stopped peertube.service - PeerTube daemon.
Feb 14 14:51:01 debian systemd[1]: peertube.service: Consumed 2h 26min 6.304s CPU time.
Feb 14 14:51:01 debian systemd[1]: Started peertube.service - PeerTube daemon.
```

**Comment by Chocobozzz** [comment]
Hi,

Thanks for the issue. You can try this patch: https://github.com/Chocobozzz/PeerTube/commit/65e7ffba1586a934a1d5a6dea31f9368bbfe5365

Or disable redundancy until a new version of PeerTube is released
