### ISSUE TITLE
Docker image does not work

### ISSUE THREAD

**Issue by tezza1971** [Chocobozzz/PeerTube#6245]
### Describe the current behavior

```
tjk@zimaxubuntu:~$ sudo docker run chocobozzz/peertube
Starting PostgreSQL 9.4 database server: main.

> peertube@0.0.1 start /home/peertube_user/PeerTube
> node server

info: [localhost:80] Database peertube_prod is ready.
error: [localhost:80] uncaughtException: the database system is starting up 
{ date: 'Fri Feb 23 2024 21:14:02 GMT+0000 (UTC)',
  process: 
   { pid: 88,
     uid: 1000,
     gid: 1000,
     cwd: '/home/peertube_user/PeerTube',
     execPath: '/usr/bin/nodejs',
     version: 'v6.10.2',
     argv: [ '/usr/bin/nodejs', '/home/peertube_user/PeerTube/server' ],
     memoryUsage: 
      { rss: 82702336,
        heapTotal: 76206080,
        heapUsed: 48892696,
        external: 519333 } },
  os: 
   { loadavg: [ 4.40576171875, 3.83984375, 3.15576171875 ],
     uptime: 2963 },
  trace: 
   [ { column: 20,
       file: '/home/peertube_user/PeerTube/node_modules/sequelize/lib/dialects/postgres/connection-manager.js',
       function: null,
       line: 110,
       method: null,
       native: false },
     { column: 5,
       file: '/home/peertube_user/PeerTube/node_modules/pg/lib/client.js',
       function: '',
       line: 186,
       method: null,
       native: false },
     { column: 13,
       file: 'events.js',
       function: 'emitOne',
       line: 96,
       method: null,
       native: false },
     { column: 7,
       file: 'events.js',
       function: 'Connection.emit',
       line: 188,
       method: 'emit',
       native: false },
     { column: 12,
       file: '/home/peertube_user/PeerTube/node_modules/pg/lib/connection.js',
       function: '',
       line: 136,
       method: null,
       native: false },
     { column: 13,
       file: 'events.js',
       function: 'emitOne',
       line: 96,
       method: null,
       native: false },
     { column: 7,
       file: 'events.js',
       function: 'Socket.emit',
       line: 188,
       method: 'emit',
       native: false },
     { column: 18,
       file: '_stream_readable.js',
       function: 'readableAddChunk',
       line: 176,
       method: null,
       native: false },
     { column: 10,
       file: '_stream_readable.js',
       function: 'Socket.Readable.push',
       line: 134,
       method: 'Readable.push',
       native: false },
     { column: 20,
       file: 'net.js',
       function: 'TCP.onread',
       line: 551,
       method: 'onread',
       native: false } ],
  stack: 
   [ 'SequelizeConnectionError: the database system is starting up',
     '    at /home/peertube_user/PeerTube/node_modules/sequelize/lib/dialects/postgres/connection-manager.js:110:20',
     '    at Connection.<anonymous> (/home/peertube_user/PeerTube/node_modules/pg/lib/client.js:186:5)',
     '    at emitOne (events.js:96:13)',
     '    at Connection.emit (events.js:188:7)',
     '    at Socket.<anonymous> (/home/peertube_user/PeerTube/node_modules/pg/lib/connection.js:136:12)',
     '    at emitOne (events.js:96:13)',
     '    at Socket.emit (events.js:188:7)',
     '    at readableAddChunk (_stream_readable.js:176:18)',
     '    at Socket.Readable.push (_stream_readable.js:134:10)',
     '    at TCP.onread (net.js:551:20)' ] }

npm ERR! Linux 6.5.0-21-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "start"
npm ERR! node v6.10.2
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! peertube@0.0.1 start: `node server`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the peertube@0.0.1 start script 'node server'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the peertube package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node server
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs peertube
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls peertube
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/peertube_user/PeerTube/npm-debug.log

```

### Steps to reproduce

sudo docker run chocobozzz/peertube

### Describe the expected behavior

I expected the server to spin up so I could web to it.

### Additional information

Running the latest official docker engine (25.0.3 - not distro version of docker) on Ubuntu 23.10 (6.5.0-21-generic)

**Comment by Chocobozzz** [comment]
Hello,

Please follow [the docker documentation](https://docs.joinpeertube.org/install/docker) to use peertube using docker
