### ISSUE TITLE
the button "refuser" doesn't work when moderating subscriptions

### ISSUE THREAD

**Issue by vincib** [Chocobozzz/PeerTube#6339]
### Describe the current behavior

When I click on "refuse" on a user asking for registration, nothing happen (in a french peertubeà

the web console shows the following : 

```
core.mjs:7473 ERROR Error: Unable to parse ICU expression in "<x id="START_TAG_NG_CONTAINER" ctype="x-ng_container" equiv-text="&lt ;ng-container *ngIf=&quot ;isAccept()&quot ;&gt ;"/>Accepter <x id="INTERPOLATION" equiv-text="{{ registration.username }}"/> l'inscription<x id="CLOSE_TAG_NG_CONTAINER" ctype="x-ng_container" equiv-text="&lt ;/ng-container&gt ;"/><x id="START_TAG_NG_CONTAINER_1" ctype="x-ng_container_1" equiv-text="&lt ;ng-container *ngIf=&quot ;isReject()&quot ;&gt ;"/>Rejeter <x id="INTERPOLATION" equiv-text="{{ registration.username }}"/> l'inscription<x id="CLOSE_TAG_NG_CONTAINER" ctype="x-ng_container" equiv-text="&lt ;/ng-container&gt ;"/>" message.
    at fS (core.mjs:25050:31)
    at Object.s_ (core.mjs:25731:9)
    at Gi (process-registration….component.html:3:5)
    at im (core.mjs:10537:9)
    at np (core.mjs:11735:13)
    at _u (core.mjs:11803:5)
    at MM.createEmbeddedViewImpl (core.mjs:12699:31)
    at MM.createEmbeddedView (core.mjs:12693:21)
    at p._createFromTemplateRef (ng-bootstrap.mjs:7507:37)
    at p._getContentRef (ng-bootstrap.mjs:7488:25)
```

### Steps to reproduce

1. install peertube 6.1.0~rc1
2. try to register
3. as an admin, try to refuse that registration

### Describe the expected behavior

I expect to se the usual refusal form

### Additional information

Peertube 6.1.0~rc1 on debian 12, using a french chromium 122

**Comment by Chocobozzz** [comment]
Thanks, I fixed and pulled translations in https://github.com/Chocobozzz/PeerTube/commit/da949376db6dac2d52ddd25b9a47432dfc204bbc
