### ISSUE TITLE
Tokenizer Errors When Uploading Large Videos

### ISSUE THREAD

**Issue by MattyBoombalatty** [Chocobozzz/PeerTube#6342]
### Describe the current behavior

When uploading large videos (at least 2 GB), it appears that there is an issue with entering data into the database.

### Steps to reproduce

1. Upload large video
2. Watch log
3. See below

### Describe the expected behavior

Be able to upload large videos.

### Additional information

* PeerTube instance:
  * URL: https://nicecrew.tv
  * Version: 6.1.0-rc1
  * NodeJS version:
  * Ffmpeg version:

Error log:

```
Apr 18 17:28:22 nctv-r730xd peertube[210186]: Error: Parse error: Unexpected "$1,$2,$3,$" at line 1 column 154.
Apr 18 17:28:22 nctv-r730xd peertube[210186]: This likely happens because you're using the default "sql" dialect.
Apr 18 17:28:22 nctv-r730xd peertube[210186]: If possible, please select a more specific dialect (like sqlite, postgresql, etc).
Apr 18 17:28:22 nctv-r730xd peertube[210186]:     at TokenizerEngine.createParseError (file:///var/www/peertube/versions/peertube-v6.1.0-rc.1/node_modules/sql-formatter/dist/index.js:14845:12)
Apr 18 17:28:22 nctv-r730xd peertube[210186]:     at TokenizerEngine.tokenize (file:///var/www/peertube/versions/peertube-v6.1.0-rc.1/node_modules/sql-formatter/dist/index.js:14835:22)
Apr 18 17:28:22 nctv-r730xd peertube[210186]:     at Tokenizer.tokenize (file:///var/www/peertube/versions/peertube-v6.1.0-rc.1/node_modules/sql-formatter/dist/index.js:14955:65)
Apr 18 17:28:22 nctv-r730xd peertube[210186]:     at LexerAdapter.tokenize (file:///var/www/peertube/versions/peertube-v6.1.0-rc.1/node_modules/sql-formatter/dist/index.js:15792:37)
Apr 18 17:28:22 nctv-r730xd peertube[210186]:     at LexerAdapter.reset (file:///var/www/peertube/versions/peertube-v6.1.0-rc.1/node_modules/sql-formatter/dist/index.js:15327:24)
Apr 18 17:28:22 nctv-r730xd peertube[210186]:     at Parser.feed (/var/www/peertube/versions/peertube-v6.1.0-rc.1/node_modules/nearley/lib/nearley.js:281:15)
Apr 18 17:28:22 nctv-r730xd peertube[210186]:     at Object.parse (file:///var/www/peertube/versions/peertube-v6.1.0-rc.1/node_modules/sql-formatter/dist/index.js:15799:34)
Apr 18 17:28:22 nctv-r730xd peertube[210186]:     at Formatter.parse (file:///var/www/peertube/versions/peertube-v6.1.0-rc.1/node_modules/sql-formatter/dist/index.js:16508:49)
Apr 18 17:28:22 nctv-r730xd peertube[210186]:     at Formatter.format (file:///var/www/peertube/versions/peertube-v6.1.0-rc.1/node_modules/sql-formatter/dist/index.js:16503:22)
Apr 18 17:28:22 nctv-r730xd peertube[210186]:     at formatDialect (file:///var/www/peertube/versions/peertube-v6.1.0-rc.1/node_modules/sql-formatter/dist/index.js:16614:57)
Apr 18 17:28:22 nctv-r730xd peertube[210186]:     at format (file:///var/www/peertube/versions/peertube-v6.1.0-rc.1/node_modules/sql-formatter/dist/index.js:16604:10)
Apr 18 17:28:22 nctv-r730xd peertube[210186]:     at Printf.template (file:///var/www/peertube/versions/peertube-v6.1.0-rc.1/dist/core/helpers/logger.js:19:39)
Apr 18 17:28:22 nctv-r730xd peertube[210186]:     at Printf.transform (/var/www/peertube/versions/peertube-v6.1.0-rc.1/node_modules/logform/printf.js:11:26)
Apr 18 17:28:22 nctv-r730xd peertube[210186]:     at Format.transform (/var/www/peertube/versions/peertube-v6.1.0-rc.1/node_modules/logform/combine.js:20:24)
Apr 18 17:28:22 nctv-r730xd peertube[210186]:     at Console._write (/var/www/peertube/versions/peertube-v6.1.0-rc.1/node_modules/winston-transport/modern.js:91:33)
Apr 18 17:28:22 nctv-r730xd peertube[210186]:     at doWrite (/var/www/peertube/versions/peertube-v6.1.0-rc.1/node_modules/readable-stream/lib/_stream_writable.js:390:139)
Apr 18 17:28:22 nctv-r730xd peertube[210186]: [nicecrew.tv:443] 2024-04-18 17:28:22.444 error: Client log: Upload failed: The server encountered an error {
Apr 18 17:28:22 nctv-r730xd peertube[210186]:   "username": "matty",
Apr 18 17:28:22 nctv-r730xd peertube[210186]:   "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36",
Apr 18 17:28:22 nctv-r730xd peertube[210186]:   "url": "https://nicecrew.tv/videos/upload#upload"
Apr 18 17:28:22 nctv-r730xd peertube[210186]: }
```

**Comment by MattyBoombalatty** [comment]
Even after the error is thrown, the video still is "uploaded" to PeerTube without any of the settings (description, title, et cetera) and storyboard is generated, then the video is sent to the transcoding queue. I will turn off storyboard generation to see if that's the issue and report back.

![image](https://github.com/Chocobozzz/PeerTube/assets/95333219/cd9b1522-9777-479d-bede-afe459e0dd0e)

**Comment by MattyBoombalatty** [comment]
Disabling storyboard generation did not make a difference.

**Comment by MattyBoombalatty** [comment]
I was not able to figure out the Tokenizer issue lmao. I'm going to guess there's an issue with how the argument is passed into one of the Tokenizer functions, perhaps `sql` is being passed in rather than `postgresql`.

**Comment by MattyBoombalatty** [comment]
Additional log:

```sh
{
  "err": "Error\n    at Query.run (/var/www/peertube/versions/peertube-v6.1.0-rc.1/node_modules/sequelize/lib/dialects/postgres/query.js:50:25)\n    at /var/www/peertube/versions/peertube-v6.1.0-rc.1/node_modules/sequelize/lib/sequelize.js:315:28\n    at async PostgresQueryInterface.insert (/var/www/peertube/versions/peertube-v6.1.0-rc.1/node_modules/sequelize/lib/dialects/abstract/query-interface.js:308:21)\n    at async VideoSourceModel.save (/var/www/peertube/versions/peertube-v6.1.0-rc.1/node_modules/sequelize/lib/model.js:2490:35)\n    at async LocalVideoCreator.create (file:///var/www/peertube/versions/peertube-v6.1.0-rc.1/dist/core/lib/local-video-creator.js:122:13)\n    at async addVideo (file:///var/www/peertube/versions/peertube-v6.1.0-rc.1/dist/core/controllers/api/videos/upload.js:97:23)\n    at async addVideoResumable (file:///var/www/peertube/versions/peertube-v6.1.0-rc.1/dist/core/controllers/api/videos/upload.js:57:22)",
  "sql": "INSERT INTO \"videoSource\" (\"id\",\"inputFilename\",\"resolution\",\"width\",\"height\",\"fps\",\"size\",\"metadata\",\"videoId\",\"createdAt\",\"updatedAt\") VALUES (DEFAULT,$1,$2,$3,$4,$5,$6,$7,$8,$9,$10) RETURNING \"id\",\"inputFilename\",\"keptOriginalFilename\",\"resolution\",\"width\",\"height\",\"fps\",\"size\",\"metadata\",\"storage\",\"fileUrl\",\"videoId\",\"createdAt\",\"updatedAt\";"
}
```

**Comment by Chocobozzz** [comment]
Hi,

You error comes from the error logger, preventing us to view the real cause of your issue. Can you check postgresql logs to check if the error is displayed?

Can you also run using `psql` the following command? `\d "videoSource"`

**Comment by MattyBoombalatty** [comment]
Here is the postgres error log

```
2024-04-22 11:40:39.373 UTC [388841] peertube@peertube_prod ERROR:  value "2695612428" is out of range for type integer
2024-04-22 11:40:39.373 UTC [388841] peertube@peertube_prod CONTEXT:  unnamed portal parameter $6 = '...'
2024-04-22 11:40:39.373 UTC [388841] peertube@peertube_prod STATEMENT:  INSERT INTO "videoSource" ("id","inputFilename","resolution","width","height","fps","size","metadata","videoId","createdAt","updatedAt") VALUES (DEFAULT,$1,$2,$3,$4,$5,$6,$7,$8,$9,$10) RETURNING "id","inputFilename","keptOriginalFilename","resolution","width","height","fps","size","metadata","storage","fileUrl","videoId","createdAt","updatedAt";
```

**Comment by Chocobozzz** [comment]
Thanks for the details! The bug should be fixed by https://github.com/Chocobozzz/PeerTube/commit/b824480af7054a5a49ddb1788c26c769c89ccc8a

**Comment by MattyBoombalatty** [comment]
You're the man!
