### ISSUE TITLE
Peertube won't start： "permission denied for schema public"

### ISSUE THREAD

**Issue by Terence0816** [Chocobozzz/PeerTube#6417]
### Describe the problem

[localhost:9000] 2024-05-26 17:26:44.319 error: Cannot start application. {
  "err": {
    "stack": "Error\n    at Query.run (/var/www/peertube/peertube-v6.1.0/node_modules/sequelize/lib/dialects/postgres/query.js:50:25)\n    at /var/www/peertube/peertube-v6.1.0/node_modules/sequelize/lib/sequelize.js:315:28\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async initDatabaseModels (file:///var/www/peertube/peertube-v6.1.0/dist/core/initializers/database.js:173:5)",
    "message": "permission denied for schema public",
    "name": "SequelizeDatabaseError",
    "parent": {
      "stack": "error: permission denied for schema public\n    at Parser.parseErrorMessage (/var/www/peertube/peertube-v6.1.0/node_modules/pg-protocol/dist/parser.js:287:98)\n    at Parser.handlePacket (/var/www/peertube/peertube-v6.1.0/node_modules/pg-protocol/dist/parser.js:126:29)\n    at Parser.parse (/var/www/peertube/peertube-v6.1.0/node_modules/pg-protocol/dist/parser.js:39:38)\n    at Socket.<anonymous> (/var/www/peertube/peertube-v6.1.0/node_modules/pg-protocol/dist/index.js:11:42)\n    at Socket.emit (node:events:517:28)\n    at addChunk (node:internal/streams/readable:368:12)\n    at readableAddChunk (node:internal/streams/readable:341:9)\n    at Readable.push (node:internal/streams/readable:278:10)\n    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)",
      "message": "permission denied for schema public",
      "length": 95,
      "name": "error",
      "severity": "ERROR",
      "code": "42501",
      "file": "aclchk.c",
      "line": "2807",
      "routine": "aclcheck_error",
      "sql": "CREATE OR REPLACE FUNCTION immutable_unaccent(text)\n  RETURNS text AS\n$func$\nSELECT public.unaccent('public.unaccent', $1::text)\n$func$  LANGUAGE sql IMMUTABLE;"
    },
    "sql": "CREATE OR REPLACE FUNCTION immutable_unaccent(text)\n  RETURNS text AS\n$func$\nSELECT public.unaccent('public.unaccent', $1::text)\n$func$  LANGUAGE sql IMMUTABLE;",
    "parameters": {}
  }
}

### Additional information

* PeerTube instance URL:
* PeerTube version:
* NodeJS version:
* Ffmpeg version:
* Redis version:
* PostgreSQL version:

**Comment by gergob** [comment]
@Terence0816 the error message: `permission denied for schema public` shows that when Peertube wants to use the database in postgres, the user you are using to connect to the database does not have permissions to access that database or it's schema.

Ideas to fix:
1. Assign permissions to the user you configured to access postgress
2. If this is a docker setup or local setup, try temporarily the default user: postgres (?) to access the db
