### ISSUE TITLE
All transcoding jobs result in an error: Output format mp4 is not available

### ISSUE THREAD

**Issue by CorpulentBrony** [Chocobozzz/PeerTube#6426]
### Describe the current behavior

Currently, all newly uploaded videos are failing transcoding with the message, "Output format mp4 is not available."  I've attempted to do a simple re-encode and output to mp4 using ffmpeg but it does not fail, it only seems to fail when PeerTube processes them.

I was running version 6.0.1 but upgraded to version 6.1.0 hoping that would fix this issue but it did not have any effect.

```
Job: 8ce294ce-86b9-41b2-ab72-a221b1cc1868 Type: video-transcoding Processed on 5/30/24, 3:01:18.619 PM Finished on 5/30/24, 3:01:18.761 PM
--
{   "type": "new-resolution-to-hls",   "videoUUID": "388582ab-3dc0-4157-8a12-83702d0a6306",   "resolution": 360,   "fps": 25,   "copyCodecs": false,   "isNewVideo": false,   "deleteWebVideoFiles": false }
Error: Output format mp4 is not available
    at /var/www/peertube/versions/peertube-v6.1.0/node_modules/fluent-ffmpeg/lib/capabilities.js:589:21
    at nextTask (/var/www/peertube/versions/peertube-v6.1.0/node_modules/async/dist/async.js:5791:13)
    at next (/var/www/peertube/versions/peertube-v6.1.0/node_modules/async/dist/async.js:5799:13)
    at /var/www/peertube/versions/peertube-v6.1.0/node_modules/async/dist/async.js:329:20
    at proto.availableFormats.proto.getAvailableFormats (/var/www/peertube/versions/peertube-v6.1.0/node_modules/fluent-ffmpeg/lib/capabilities.js:513:14)
    at /var/www/peertube/versions/peertube-v6.1.0/node_modules/fluent-ffmpeg/lib/capabilities.js:568:14
    at nextTask (/var/www/peertube/versions/peertube-v6.1.0/node_modules/async/dist/async.js:5791:13)
    at Object.waterfall (/var/www/peertube/versions/peertube-v6.1.0/node_modules/async/dist/async.js:5802:9)
    at Object.awaitable [as waterfall] (/var/www/peertube/versions/peertube-v6.1.0/node_modules/async/dist/async.js:212:32)
    at proto._checkCapabilities (/var/www/peertube/versions/peertube-v6.1.0/node_modules/fluent-ffmpeg/lib/capabilities.js:565:11)
    at /var/www/peertube/versions/peertube-v6.1.0/node_modules/fluent-ffmpeg/lib/processor.js:298:14
    at nextTask (/var/www/peertube/versions/peertube-v6.1.0/node_modules/async/dist/async.js:5791:13)
    at Object.waterfall (/var/www/peertube/versions/peertube-v6.1.0/node_modules/async/dist/async.js:5802:9)
    at Object.awaitable [as waterfall] (/var/www/peertube/versions/peertube-v6.1.0/node_modules/async/dist/async.js:212:32)
    at proto._prepare (/var/www/peertube/versions/peertube-v6.1.0/node_modules/fluent-ffmpeg/lib/processor.js:295:11)
    at proto.exec.proto.execute.proto.run (/var/www/peertube/versions/peertube-v6.1.0/node_modules/fluent-ffmpeg/lib/processor.js:431:10)
```

### Steps to reproduce

1. Upload video
2. Transcoding fails

### Describe the expected behavior

Transcoding succeeds

### Additional information

* PeerTube instance:
  * URL: https://pony.tube/
  * Version: 6.1.0
  * NodeJS version: 18.16.0
  * Ffmpeg version: N-70079-gdf868bae23-static May 4 build (downgraded to this suspecting it was the issue, but it was not; issue also occurred in May 24 build)

* Browser name, version and platforms on which you could reproduce the bug:
* Link to browser console log if relevant:
* Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`):

**Comment by Chocobozzz** [comment]
Hi,

Can you try the latest ffmpeg  stable version instead?

**Comment by CorpulentBrony** [comment]
I downgraded to ffmpeg 4.2.7 which is the newest version in apt for the version of Ubuntu I have.

I am getting the same error message.

**Comment by Chocobozzz** [comment]
Can you enable debug logs and find the line where PeerTube dumps the ffmpeg it uses?

**Comment by CorpulentBrony** [comment]
Forgive my ignorance, but how do I enable debug logs nowadays?  I've failed finding anything in the documentation (only about parsing logs) and the logs exposed in the UI are all empty.

**Comment by Chocobozzz** [comment]
> Is it possible peertube somehow caches something to do with ffmpeg?

Yes, I think it's possible that `ffmpeg-fluent`, the library we use cached your ffmpeg capabilities (and so without the mp4 output support).
