### ISSUE TITLE
Can't find plugin dependencies

### ISSUE THREAD

**Issue by kontrollanten** [Chocobozzz/PeerTube#6436]
### Describe the current behavior

When installing peertube-plugin-premium-users@1.5.0 the installations fails with:

```
{
    "traceId": "e90c0ff8940c2e163812b68a193b1f6a",
    "spanId": "635f55f1767ea7e4",
    "traceFlags": 1,
    "level": "error",
    "message": "Cannot install plugin peertube-plugin-premium-users, removing it...",
    "err": {
        "stack": "Error: Cannot find module 'mime'
Require stack:
- /var/www/peertube/storage/plugins/node_modules/send/index.js
- /var/www/peertube/storage/plugins/node_modules/express/lib/utils.js
- /var/www/peertube/storage/plugins/node_modules/express/lib/application.js
- /var/www/peertube/storage/plugins/node_modules/express/lib/express.js
- /var/www/peertube/storage/plugins/node_modules/express/index.js
- /var/www/peertube/storage/plugins/node_modules/peertube-plugin-premium-users/dist/server/server/main.js
- /var/www/peertube/versions/peertube-v6.1.0-c1/dist/core/lib/plugins/plugin-manager.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1140:15)
    at Module._load (node:internal/modules/cjs/loader:981:27)
    at Module.require (node:internal/modules/cjs/loader:1231:19)
    at Hook._require.Module.require (/var/www/peertube/versions/peertube-v6.1.0-c1/node_modules/require-in-the-middle/index.js:167:34)
    at Hook._require.Module.require (/var/www/peertube/versions/peertube-v6.1.0-c1/node_modules/require-in-the-middle/index.js:167:34)
    at require (node:internal/modules/helpers:177:18)
    at Object.<anonymous> (/var/www/peertube/storage/plugins/node_modules/send/index.js:24:12)
    at Module._compile (node:internal/modules/cjs/loader:1364:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1422:10)
    at Module.load (node:internal/modules/cjs/loader:1203:32)
    at Module._load (node:internal/modules/cjs/loader:1019:12)
    at Module.require (node:internal/modules/cjs/loader:1231:19)
    at Hook._require.Module.require (/var/www/peertube/versions/peertube-v6.1.0-c1/node_modules/require-in-the-middle/index.js:188:39)
    at Hook._require.Module.require (/var/www/peertube/versions/peertube-v6.1.0-c1/node_modules/require-in-the-middle/index.js:188:39)
    at require (node:internal/modules/helpers:177:18)
    at Object.<anonymous> (/var/www/peertube/storage/plugins/node_modules/express/lib/utils.js:20:12)
    at Module._compile (node:internal/modules/cjs/loader:1364:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1422:10)
    at Module.load (node:internal/modules/cjs/loader:1203:32)
    at Module._load (node:internal/modules/cjs/loader:1019:12)
    at Module.require (node:internal/modules/cjs/loader:1231:19)
    at Hook._require.Module.require (/var/www/peertube/versions/peertube-v6.1.0-c1/node_modules/require-in-the-middle/index.js:188:39)",
        "message": "Cannot find module 'mime'
Require stack:
- /var/www/peertube/storage/plugins/node_modules/send/index.js
- /var/www/peertube/storage/plugins/node_modules/express/lib/utils.js
- /var/www/peertube/storage/plugins/node_modules/express/lib/application.js
- /var/www/peertube/storage/plugins/node_modules/express/lib/express.js
- /var/www/peertube/storage/plugins/node_modules/express/index.js
- /var/www/peertube/storage/plugins/node_modules/peertube-plugin-premium-users/dist/server/server/main.js
- /var/www/peertube/versions/peertube-v6.1.0-c1/dist/core/lib/plugins/plugin-manager.js",
        "code": "MODULE_NOT_FOUND",
        "requireStack": [
            "/var/www/peertube/storage/plugins/node_modules/send/index.js",
            "/var/www/peertube/storage/plugins/node_modules/express/lib/utils.js",
            "/var/www/peertube/storage/plugins/node_modules/express/lib/application.js",
            "/var/www/peertube/storage/plugins/node_modules/express/lib/express.js",
            "/var/www/peertube/storage/plugins/node_modules/express/index.js",
            "/var/www/peertube/storage/plugins/node_modules/peertube-plugin-premium-users/dist/server/server/main.js",
            "/var/www/peertube/versions/peertube-v6.1.0-c1/dist/core/lib/plugins/plugin-manager.js"
        ]
    },
    "timestamp": "2024-06-08T20:15:11.070Z"
}
```

When removing `decachePlugin` from `PluginManager` it works, so it seems to be an issue upon decaching.

### Steps to reproduce

1. Install peertube-plugin-prem-users@1.5.0
2.
3.

### Additional information

* PeerTube instance:
  * URL:
  * Version: 6.1.0
  * NodeJS version: 18 (tried 20 as well)
  * Ffmpeg version:

* Browser name, version and platforms on which you could reproduce the bug:
* Link to browser console log if relevant:
* Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`):

**Comment by Chocobozzz** [comment]
Hi,

I can't reproduce: do you have other plugins installed?

**Comment by kontrollanten** [comment]
Yes. I've tried on another instance with the same plugins installed, and it works there. I've tried to reboot the server, run yarn cache clean and yarn install. But still same issue.

**Comment by PYU224** [comment]
I can't install LiveChat even after updating and restarting PeerTube.

**Comment by JohnXLivingston** [comment]
> I can't install LiveChat even after updating and restarting PeerTube.

Could it be this issue: https://github.com/JohnXLivingston/peertube-plugin-livechat/issues/703 ?

It seems that there is another issue, due to a module I use that can't install properly with yarn 1.x...
I will try to fix it in the coming days.

**Comment by JohnXLivingston** [comment]
@PYU224 , i'm releasing a v14 with this fix: https://github.com/JohnXLivingston/peertube-plugin-livechat/pull/704
I think this should resolve your issue. If not, please open an issue on the livechat project.
Thanks.

**Comment by Chocobozzz** [comment]
Do you still have this kind of issue with the latest version of PeerTube, that moved to `pnpm`?

**Comment by kontrollanten** [comment]
It has been working for a long time now, so we can close this issue.
