### ISSUE TITLE
Can't follow from a GoToSocial account

### ISSUE THREAD

**Issue by jcarnat** [Chocobozzz/PeerTube#6462]
### Describe the current behavior

Hello,

If it try to follow my Peertube account from one of my GoToSocial account, I'm stuck in the "waiting for approval" step on the GtS side. But my Peertube account is open and accept every request.

Looking at my peertube log, I can see:
`
peertube34.log:{"level":"info","message":"Fetching remote actor https://gts.nogoo.me/users/chirp/main-key.","label":"eggflix.foolbazar.eu:443","timestamp":"2024-07-02T15:51:57.037Z"}
peertube34.log:{"err":{"stack":"Error: Cannot fetch remote actor https://gts.nogoo.me/users/chirp/main-key\n    at getOrCreateAPActor (file:///var/www/peertube/versions/peertube-v6.1.0/di
st/core/lib/activitypub/actors/get.js:18:19)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async file:///var/www/peertube/versions/peertube-v6
.1.0/dist/core/middlewares/activitypub.js:78:23\n    at async checkSignature (file:///var/www/peertube/versions/peertube-v6.1.0/dist/core/middlewares/activitypub.js:11:38)","message":"Can
not fetch remote actor https://gts.nogoo.me/users/chirp/main-key"},"level":"warn","message":"Error in ActivityPub signature checker.","label":"eggflix.foolbazar.eu:443","timestamp":"2024-
07-02T15:51:57.106Z"}
peertube35.log:{"level":"info","message":"Fetching remote actor https://gts.nogoo.me/users/chirp/main-key.","label":"eggflix.foolbazar.eu:443","timestamp":"2024-07-02T15:53:23.052Z"}
peertube35.log:{"err":{"stack":"Error: Cannot fetch remote actor https://gts.nogoo.me/users/chirp/main-key\n    at getOrCreateAPActor (file:///var/www/peertube/versions/peertube-v6.1.0/di
st/core/lib/activitypub/actors/get.js:18:19)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async file:///var/www/peertube/versions/peertube-v6
.1.0/dist/core/middlewares/activitypub.js:78:23\n    at async checkSignature (file:///var/www/peertube/versions/peertube-v6.1.0/dist/core/middlewares/activitypub.js:11:38)","message":"Can
not fetch remote actor https://gts.nogoo.me/users/chirp/main-key"},"level":"warn","message":"Error in ActivityPub signature checker.","label":"eggflix.foolbazar.eu:443","timestamp":"2024-
07-02T15:53:23.116Z"}
`

I've also tested following @chocobozzz@peertube2.cpy.re and this behaves the same.

There's an issue in GtS's Github which refers to signature too https://github.com/superseriousbusiness/gotosocial/issues/624 but there don't seem to be a solution from the GtS side.

### Steps to reproduce

1. from a GoToSocial account, search for a Peertube account
2. click the "Follow" button
3. the status is "Waiting" and never changes.

### Additional information

* PeerTube instance:
  * URL:
  * Version:
  * NodeJS version:
  * Ffmpeg version:

* Browser name, version and platforms on which you could reproduce the bug:
* Link to browser console log if relevant:
* Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`):

**Comment by MattyBoombalatty** [comment]
Try turning off or on signed fetches in your production.yaml file

**Comment by jcarnat** [comment]
> Try turning off or on signed fetches in your production.yaml file

Wether "federation: sign_federated_fetches" is set to true or false doesn't seem to change anything.

`{"level":"info","message":"Fetching remote actor https://gts.nogoo.me/users/chirp/main-key.","label":"eggflix.foolbazar.eu:443","timestamp":"2024-07-03T12:35:29.095Z"}
{"err":{"stack":"Error: Cannot fetch remote actor https://gts.nogoo.me/users/chirp/main-key\n    at getOrCreateAPActor (file:///var/www/peertube/versions/peertube-v6.1.0/dist/core/lib/activitypub/actors/get.js:18:19)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async file:///var/www/peertube/versions/peertube-v6.1.0/dist/core/middlewares/activitypub.js:78:23\n    at async checkSignature (file:///var/www/peertube/versions/peertube-v6.1.0/dist/core/middlewares/activitypub.js:11:38)","message":"Cannot fetch remote actor https://gts.nogoo.me/users/chirp/main-key"},"level":"warn","message":"Error in ActivityPub signature checker.","label":"eggflix.foolbazar.eu:443","timestamp":"2024-07-03T12:35:29.272Z"}`

**Comment by Chocobozzz** [comment]
Can you enable debug logs in PeerTube, restart the server, follow the peertube account from GTS and paste them?

**Comment by jcarnat** [comment]
> Can you enable debug logs in PeerTube, restart the server, follow the peertube account from GTS and paste them?

Here's the log attached.
I ran `grep -A 2 -B 2 gts.nogoo.me /var/www/peertube/storage/logs/peertube.log`.
[nogoome.log.gz](https://github.com/user-attachments/files/16177296/nogoome.log.gz)

**Comment by Chocobozzz** [comment]
Thanks! With the [GTS documentation](https://docs.gotosocial.org/en/latest/federation/http_signatures/) I was able to understand the issue. I'll work on this in the coming months.

**Comment by magnus919** [comment]
I'm glad there are already eyes on this. I have new instances of both platforms and quickly experienced the same issue.

**Comment by lukaprincic** [comment]
Any traction on this? Sorry to ping and push, I'm unable to follow any peertube users/channels on my gotosocial instance and it's quite a shame. I'm currently getting a 500 error when trying to load/search a peertube video.

this is error log at my GoToSocial instance running 0.18.1 trying to fetch/search url from a peerTube v.7.0.1
<details>
```
timestamp="15/03/2025 12:53:32.032" func=server.init.func2.Logger.13.1 level=INFO latency="24.400961ms" userAgent="Mozilla/5.0 (X11; Linux x86_64; rv:135.0) Gecko/20100101 Firefox/135.0" method=POST statusCode=200 path=/api/v1/markers clientIP=193.77.153.115 requestID=x3mdv6cn04000xehqmp0 msg="OK: wrote 130B"
timestamp="15/03/2025 12:53:34.569" func=httpclient.(*Client).DoOnce level=INFO method=GET url=https://v.basspistol.org/w/sUAy7uhuBdw8JfYZVt3dAH attempt="1" requestID=jfsdv6cn04000q2d9xwg pubKeyID=https://0x.trans.fail/users/prinlu/main-key msg="200 OK"
timestamp="15/03/2025 12:53:34.611" func=httpclient.(*Client).DoOnce level=INFO method=GET url=https://v.basspistol.org/w/sUAy7uhuBdw8JfYZVt3dAH attempt="1" requestID=jfsdv6cn04000q2d9xwg pubKeyID=https://0x.trans.fail/users/prinlu/main-key msg="200 OK"
timestamp="15/03/2025 12:53:34.616" func=server.init.func2.Logger.13.1 level=ERROR latency="133.422008ms" userAgent="Mozilla/5.0 (X11; Linux x86_64; rv:135.0) Gecko/20100101 Firefox/135.0" method=GET statusCode=500 path=/api/v2/search clientIP=193.77.153.115 errors="Error #01: Get: error searching by URI: byURI: error looking up https://v.basspistol.org/w/sUAy7uhuBdw8JfYZVt3dAH as status: enrichStatus: dereferenced status uri https://v.basspistol.org/videos/watch/d9e5935d-74f3-498d-8658-07a2775862ed does not match https://v.basspistol.org/w/sUAy7uhuBdw8JfYZVt3dAH\n" requestID=jfsdv6cn04000q2d9xwg msg="Internal Server Error: wrote 54B"
```
</details>

**Comment by FoundOne** [comment]
Any update on that?

**Comment by Chocobozzz** [comment]
> I've also tested following @[chocobozzz@peertube2.cpy.re](mailto:chocobozzz@peertube2.cpy.re) and this behaves the same.

Can you retry? :)

**Comment by tibequadorian** [comment]
Still the same issue on my end :/

**Comment by Chocobozzz** [comment]
Thank you, can you create an account for me on your platform and send the credentials by email (in my github profile)?

**Comment by lukaprincic** [comment]
hello,.. really happy to see movement here....

I tried to follow that account above and the follow is requested but unconfirmed. These is from the gotosocial logs:

<details>

```
timestamp="08/05/2025 13:41:38.760" func=server.init.func2.Logger.19.1 level=INFO latency="46.528µs" userAgent="Mozilla/5.0 (X11; Linux x86_64; rv:135.0) Gecko/20100101 Firefox/135.0" method=OPTIONS statusCode=204 path=/api/v1/accounts/01JNG2KS74YJQZYFAQPCFEB177/follow clientIP=178.58.178.38 requestID=91ej3c4p0400095y43q0 msg="No Content: wrote 0B"
timestamp="08/05/2025 13:41:38.822" func=workers.(*Processor).ProcessFromClientAPI level=INFO activityType=Create objectType=Follow fromAccount=prinlu msg="processing from client API"
timestamp="08/05/2025 13:41:38.822" func=server.init.func2.Logger.19.1 level=INFO latency="13.679586ms" userAgent="Mozilla/5.0 (X11; Linux x86_64; rv:135.0) Gecko/20100101 Firefox/135.0" method=POST statusCode=200 path=/api/v1/accounts/01JNG2KS74YJQZYFAQPCFEB177/follow clientIP=178.58.178.38 requestID=f5ej3c4p040015ahm290 msg="OK: wrote 179B"
timestamp="08/05/2025 13:41:38.827" func=federation.(*federatingActor).Send level=INFO msg="send activity Follow via outbox https://0x.trans.fail/users/prinlu/outbox"
timestamp="08/05/2025 13:41:38.931" func=server.init.func2.Logger.19.1 level=INFO latency="830.822µs" userAgent="PeerTube/7.1.1-nightly-2025-05-08 (+https://peertube2.cpy.re)" method=GET statusCode=200 path=/users/prinlu/main-key clientIP=178.63.240.146 pubKeyID=https://peertube2.cpy.re/accounts/peertube#main-key requestID=y9ej3c4p04000j1tn6y0 msg="OK: wrote 556B"
timestamp="08/05/2025 13:41:38.973" func=httpclient.(*Client).DoOnce level=INFO method=GET url=https://peertube2.cpy.re/accounts/peertube#main-key attempt="1" requestID=0xf23c4p04000zs3r780 pubKeyID=https://0x.trans.fail/users/prinlu/main-key msg="200 OK"
timestamp="08/05/2025 13:41:38.998" func=httpclient.(*Client).DoOnce level=INFO method=GET url=https://peertube2.cpy.re/robots.txt attempt="1" requestID=0xf23c4p04000zs3r780 pubKeyID=https://0x.trans.fail/users/prinlu/main-key msg="200 OK"
timestamp="08/05/2025 13:41:39.014" func=httpclient.(*Client).DoOnce level=INFO method=GET url=https://peertube2.cpy.re/api/v1/instance attempt="1" requestID=0xf23c4p04000zs3r780 pubKeyID=https://0x.trans.fail/users/prinlu/main-key msg="400 Bad Request"
timestamp="08/05/2025 13:41:39.033" func=httpclient.(*Client).DoOnce level=INFO method=GET url=https://peertube2.cpy.re/.well-known/nodeinfo attempt="1" requestID=0xf23c4p04000zs3r780 pubKeyID=https://0x.trans.fail/users/prinlu/main-key msg="200 OK"
timestamp="08/05/2025 13:41:39.045" func=httpclient.(*Client).DoOnce level=INFO method=GET url=https://peertube2.cpy.re/nodeinfo/2.0.json attempt="1" requestID=0xf23c4p04000zs3r780 pubKeyID=https://0x.trans.fail/users/prinlu/main-key msg="200 OK"
timestamp="08/05/2025 13:41:39.066" func=httpclient.(*Client).DoOnce level=INFO method=GET url=https://peertube2.cpy.re/accounts/peertube attempt="1" requestID=0xf23c4p04000zs3r780 pubKeyID=https://0x.trans.fail/users/prinlu/main-key msg="200 OK"
timestamp="08/05/2025 13:41:39.085" func=httpclient.(*Client).DoOnce level=INFO method=GET url=https://peertube2.cpy.re/.well-known/webfinger?resource=acct%3Apeertube%40peertube2.cpy.re attempt="1" requestID=0xf23c4p04000zs3r780 pubKeyID=https://0x.trans.fail/users/prinlu/main-key msg="200 OK"
timestamp="08/05/2025 13:41:39.101" func=httpclient.(*Client).DoOnce level=INFO method=GET url=https://peertube2.cpy.re/lazy-static/avatars/abace30f-69ad-4ff2-a954-dea06c5db6eb.png attempt="1" requestID=0xf23c4p04000zs3r780 pubKeyID=https://0x.trans.fail/users/prinlu/main-key msg="200 OK"
timestamp="08/05/2025 13:41:39.211" func=dereferencing.(*Dereferencer).GetAccountByURI.func1 level=ERROR msg="error fetching account featured collection: dereferenceCollection: error dereferencing : invalid http request: empty url host"
timestamp="08/05/2025 13:41:39.214" func=server.init.func2.Logger.19.1 level=INFO latency="263.240005ms" userAgent="PeerTube/7.1.1-nightly-2025-05-08 (+https://peertube2.cpy.re)" method=GET statusCode=200 path=/users/prinlu clientIP=178.63.240.146 pubKeyID=https://peertube2.cpy.re/accounts/peertube#main-key requestID=0xf23c4p04000zs3r780 msg="OK: wrote 1.94kiB"
timestamp="08/05/2025 13:41:39.255" func=httpclient.(*Client).DoOnce level=INFO method=GET url=https://peertube2.cpy.re/accounts/peertube/followers attempt="1" pubKeyID=https://0x.trans.fail/users/prinlu/main-key msg="200 OK"
timestamp="08/05/2025 13:41:39.268" func=server.init.func2.Logger.19.1 level=INFO latency="2.38987ms" userAgent="PeerTube/7.1.1-nightly-2025-05-08 (+https://peertube2.cpy.re)" method=GET statusCode=200 path=/users/prinlu clientIP=178.63.240.146 pubKeyID=https://peertube2.cpy.re/accounts/peertube#main-key requestID=85fj3c4p04000anmbd10 msg="OK: wrote 1.94kiB"
timestamp="08/05/2025 13:41:39.290" func=server.init.func2.Logger.19.1 level=INFO latency="3.210644ms" userAgent="PeerTube/7.1.1-nightly-2025-05-08 (+https://peertube2.cpy.re)" method=GET statusCode=200 path=/users/prinlu/followers clientIP=178.63.240.146 pubKeyID=https://peertube2.cpy.re/accounts/peertube#main-key requestID=axfj3c4p040016y2a8t0 msg="OK: wrote 157B"
timestamp="08/05/2025 13:41:39.295" func=httpclient.(*Client).DoOnce level=INFO method=GET url=https://peertube2.cpy.re/accounts/peertube/following attempt="1" pubKeyID=https://0x.trans.fail/users/prinlu/main-key msg="200 OK"
timestamp="08/05/2025 13:41:39.307" func=server.init.func2.Logger.19.1 level=INFO latency="679.583µs" userAgent="PeerTube/7.1.1-nightly-2025-05-08 (+https://peertube2.cpy.re)" method=GET statusCode=200 path=/users/prinlu/following clientIP=178.63.240.146 pubKeyID=https://peertube2.cpy.re/accounts/peertube#main-key requestID=d9fj3c4p0400174xatgg msg="OK: wrote 161B"
timestamp="08/05/2025 13:41:39.381" func=httpclient.(*Client).DoOnce level=INFO method=GET url=https://peertube2.cpy.re/accounts/peertube/outbox attempt="1" pubKeyID=https://0x.trans.fail/users/prinlu/main-key msg="200 OK"
timestamp="08/05/2025 13:41:39.516" func=httpclient.(*Client).DoOnce level=INFO method=POST url=https://peertube2.cpy.re/inbox contentType="application/ld+json; profile=\"https://www.w3.org/ns/activitystreams\"" attempt="1" pubKeyID=https://0x.trans.fail/users/prinlu/main-key msg="204 No Content"
```

</details>

**Comment by tibequadorian** [comment]
thank you @lukaprincic for the logs. the last line with `msg="204 No Content"` should read `msg="202 Accepted"` when I compare to my logs when I follow a mastodon user for example:
```
timestamp="09/05/2025 08:09:55.644" func=httpclient.(*Client).DoOnce level=INFO method=POST url=https://framapiaf.org/inbox contentType="application/ld+json; profile=\"https://www.w3.org/ns/activitystreams\"" attempt="1" pubKeyID=https://social.tbqdrn.de/users/tibs/main-key msg="202 Accepted"
```

**Comment by tibequadorian** [comment]
Thank you, hope to see a new release soon!

**Comment by Chocobozzz** [comment]
RC is planned in ~two weeks :)

**Comment by lukaprincic** [comment]
is this supposed to be working in 7.3.0? because it's not on spectra.video.

I'm trying to follow an account @compudanzas@spectra.video from my gotosocial 0.19.1 and it's possible to search and click follow but it's then waiting for confirmation indefinitely. in the meantime following from mastodon works immediately, so the account is not requiring approval.

**Comment by Chocobozzz** [comment]
Please try to follow chocobozzz_channel@peertube2.cpy.re

**Comment by lukaprincic** [comment]
it does something similar, it waits for confirmation but when i reload the profile again (the one above), it is not followed.

this is the log:
```
timestamp="19/09/2025 13:17:13.462" func=workers.(*Processor).ProcessFromClientAPI level=INFO activityType=Create objectType=Follow fromAccount=prinlu msg="processing from client API"
timestamp="19/09/2025 13:17:13.462" func=server.init.func2.Logger.19.1 level=INFO latency="2.376847ms" userAgent="Mozilla/5.0 (X11; Linux x86_64; rv:142.0) Gecko/20100101 Firefox/142.0" method=POST statusCode=200 path=/api/v1/accounts/01K5H1W53KCV1W4Y46K6X24XRB/follow clientIP=78.133.40.243 requestID=egmhyrms040003sxdpag msg="OK: wrote 178B"
timestamp="19/09/2025 13:17:13.464" func=federation.(*federatingActor).Send level=INFO msg="send activity Follow via outbox https://0x.trans.fail/users/prinlu/outbox"
timestamp="19/09/2025 13:17:13.508" func=server.init.func2.Logger.19.1 level=INFO latency="928.049µs" userAgent="PeerTube/7.3.0-nightly-2025-09-19 (+https://peertube2.cpy.re)" method=GET statusCode=200 path=/users/prinlu/main-key clientIP=178.63.240.146 pubKeyID=https://peertube2.cpy.re/accounts/peertube#main-key requestID=mcmhyrms04001qnf1apg msg="OK: wrote 556B"
timestamp="19/09/2025 13:17:13.530" func=server.init.func2.Logger.19.1 level=INFO latency="1.689122ms" userAgent="PeerTube/7.3.0-nightly-2025-09-19 (+https://peertube2.cpy.re)" method=GET statusCode=200 path=/users/prinlu clientIP=178.63.240.146 pubKeyID=https://peertube2.cpy.re/accounts/peertube#main-key requestID=q0mhyrms04000k0wky40 msg="OK: wrote 1.94kiB"
timestamp="19/09/2025 13:17:13.543" func=httpclient.(*Client).DoOnce level=INFO method=POST url=https://peertube2.cpy.re/inbox contentType="application/ld+json; profile=\"https://www.w3.org/ns/activitystreams\"" attempt="1" pubKeyID=https://0x.trans.fail/users/prinlu/main-key msg="204 No Content"
timestamp="19/09/2025 13:17:14.069" func=server.init.func2.Logger.19.1 level=INFO latency="8.041193ms" userAgent="PeerTube/7.3.0-nightly-2025-09-19 (+https://peertube2.cpy.re)" method=POST statusCode=202 path=/users/prinlu/inbox clientIP=178.63.240.146 pubKeyID=https://peertube2.cpy.re/video-channels/chocobozzz_channel#main-key requestID=smnhyrms04000g2wd320 msg="Accepted: wrote 45B"
```

https://github.com/user-attachments/assets/d50450e4-7efa-4697-bce0-8c50e4f601ad

**Comment by lukaprincic** [comment]
Weird. Now the accounts on spectra.video work. They can be followed. But yours on peertube2.cpy.re not. I guess we can leave this issue closed.

**Comment by Chocobozzz** [comment]
@lukaprincic Sorry about that, I disabled channel followers on this instance 🤦 Can you retry?

**Comment by lukaprincic** [comment]
yes, it works now

**Comment by tibequadorian** [comment]
Following works but I don't get new posts on my instance. Does anyone here experience the same?
