### ISSUE TITLE
After Upgrade, Older Videos Stopped Playing; Files Missing From Object Storage

### ISSUE THREAD

**Issue by ChanoSan** [Chocobozzz/PeerTube#6472]
### Describe the problem

After an upgrade from v6.0.1 to v6.1.0 around April this year, videos uploaded before this point are no longer playable. Attempting to play them results in an eternal load, with no activity. PeerTube logs report the following:

```
error[7/10/2024, 11:50:55 AM] Client log: HLS.js error: networkError - fatal: true - manifestLoadError

{
  "tags": [
    "client"
  ],
  "username": "XXXXX",
  "userAgent": "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:127.0) Gecko/20100101 Firefox/127.0",
  "url": "https://peertube.anon-kenkai.com/w/pSnVKiGdLHcr6F2TycZgvg"
}
```

At first I thought this was a similar issue to #4172 and attempted to go into the database as described there (although that issue is several years and versions old), but achieved no results.

I also attempted to download one of the failing videos, and received the following error in browser:

```
This XML file does not appear to have any style information associated with it. The document tree is shown below.

<Error>
<Code>NoSuchKey</Code>
<Message>The specified key does not exist.</Message>
<Resource>
/streaming-playlists/hls/c14ae3f5-b44c-4547-b3b7-7a4be1fca095/4c8f2ba5-6cdb-449e-90e1-dbb2be9c3727-240-fragmented.mp4
</Resource>
<RequestId>1720580914158197604</RequestId>
<Key>
streaming-playlists/hls/c14ae3f5-b44c-4547-b3b7-7a4be1fca095/4c8f2ba5-6cdb-449e-90e1-dbb2be9c3727-240-fragmented.mp4
</Key>
<BucketName>videos</BucketName>
</Error>
```
I then attempted to re-upload the broken files, thinking replacing the video would force things back to normal. I received this error after the upload completed:

`Cannot apply function on streaming-playlists/hls/<file string here> prefix in bucket videos: no files listed.`

Following this, I went into my remote storage (SeaweedFS using S3 buckets), and to my alarm discovered that the bucket only contained the 3 videos I uploaded **after** upgrading. Any videos uploaded to object storage before that point were no longer there.

I checked local storage (as I had uploaded directly to the server up to roughly 2022 before switching to object storage) and all files are there as expected.

After this, the video I attempted to upload now plays, but is stuck in a perpetual state of "Waiting transcoding", and loads from HTTP. I went through the filesystem both on the local PeerTube server and the remote S3 bucket, but I'm not sure where the file is currently being stored.

I've resigned myself to the data being gone from the bucket (and I blame myself for not being more thorough with backups), but I would like to know why this happened so I can avoid it in future.

Thanks for any assistance.

### Additional information

* PeerTube instance URL: https://peertube.anon-kenkai.com
* PeerTube version: 6.1.0
* NodeJS version: 20.3.1
* Ffmpeg version: 4.4.4-0ubuntu1~20.04.sav2.1
* Redis version: 7.2.5
* PostgreSQL version: 12.19

**Comment by ChanoSan** [comment]
Update: I attempted to force HLS transcoding via the Administration interface, with success. However, the subsequent move to object storage failed. 

Peertube job list shows it as DELAYED, rather than FAILED. The Admin panel fir the video shows the following info:

```
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received null at new NodeError (node:internal/errors:405:5) at validateString (node:internal/validators:162:11) at join (node:path:1175:7) at updateTorrentMetadata (file:///var/www/peertube/versions/peertube-v6.1.0/dist/core/helpers/webtorrent.js:101:28) at onFileMoved (file:///var/www/peertube/versions/peertube-v6.1.0/dist/core/lib/job-queue/handlers/move-to-object-storage.js:62:11) at moveWebVideoFiles (file:///var/www/peertube/versions/peertube-v6.1.0/dist/core/lib/job-queue/handlers/move-to-object-storage.js:41:15) at process.processTicksAndRejections (node:internal/process/task_queues:95:5) at async moveToJob (file:///var/www/peertube/versions/peertube-v6.1.0/dist/core/lib/job-queue/handlers/shared/move-video.js:19:13) at async Object.processMoveToObjectStorage [as move-to-object-storage] (file:///var/www/peertube/versions/peertube-v6.1.0/dist/core/lib/job-queue/handlers/move-to-object-storage.js:16:5) at async Object.wrapPromiseFun (file:///var/www/peertube/versions/peertube-v6.1.0/dist/core/lib/plugins/hooks.js:8:24) at async Worker.processJob (/var/www/peertube/versions/peertube-v6.1.0/node_modules/bullmq/dist/cjs/classes/worker.js:395:28) at async Worker.retryIfFailed (/var/www/peertube/versions/peertube-v6.1.0/node_modules/bullmq/dist/cjs/classes/worker.js:584:24)

```

**Comment by Chocobozzz** [comment]
Hi,

Can you paste a video URL example?

**Comment by ChanoSan** [comment]
The following is a video that I forced HLS Transcode, but which failed moving to object storage:

https://peertube.anon-kenkai.com/w/pSnVKiGdLHcr6F2TycZgvg

This is another video stuck on Awaiting Transcoding: 

https://peertube.anon-kenkai.com/w/ornoFWrVpFiZXcocyjHkrT

Here is a video that I haven't done anything to, it just won't play (and appears not to exist in object storage):

https://peertube.anon-kenkai.com/w/sJqeUW79rkYFx5ubLbatPm

...for reference, this is a video uploaded after upgrading to 6.1.0 which plays normally and exists in object storage:

https://peertube.anon-kenkai.com/w/4FpqkEbGtWJSYWdX1oYMYy

...and lastly here's an old video stored locally on the PeerTube server which also plays normally:

https://peertube.anon-kenkai.com/w/sjN7JJmuT6c7N7Cs2RYZGK

**Comment by ChanoSan** [comment]
As an addendum, I tried using CLI commands from /var/www/peertube/peertube-latest as described in the [docs here](https://docs.joinpeertube.org/maintain/tools#server-tools), but it only recreated the job which failed again with the same error.

Right now, I'm in the odd position where two videos on my server are perfectly playable, but they don't count as "Published", and as such don't appear in the Local Videos or Channels view. They seem to be stuck in limbo, either "Awaiting Transcoding" that never comes, or else being stuck at "Move to Object Storage Failed", and thus not counting as published either.

I do wonder if disabling object storage in production.yaml and then replacing the video files might force the transcoded videos to be stored locally and published, at which point I could re-enable object storage and use the CLI to move them back over. I hope it doesn't come to that, but I can do it if I have to.

**Comment by ChanoSan** [comment]
Further followup: After seeing [this comment](https://github.com/Chocobozzz/PeerTube/issues/4659#issuecomment-1000194078) from @Chocobozzz in #4659 , I was able to go into the database and revert videos stuck in "Move to External Storage Failed" to local storage and the video now displays in Local Videos without issue. Later today, I'll be attempting to move it to object storage via the CLI and see if it produces the same error as before.

**Comment by Chocobozzz** [comment]
From what I see in your [videos metadata](https://peertube.anon-kenkai.com/api/v1/videos/pSnVKiGdLHcr6F2TycZgvg) the web video is missing a torrent file (this situation should not happen, it's the reason of the error).

This case should now be correctly handled by https://github.com/Chocobozzz/PeerTube/commit/c5fa9fe70ef04d70311ffc609381b1a3614ea2c9

To fix your issue, try to run HLS transcoding **and** web video transcoding on all your videos. If you don't need/want the web video version, then just run HLS transcoding and remove the web video version from the web interface

**Comment by ChanoSan** [comment]
> From what I see in your [videos metadata](https://peertube.anon-kenkai.com/api/v1/videos/pSnVKiGdLHcr6F2TycZgvg) the web video is missing a torrent file (this situation should not happen, it's the reason of the error).
> 
> This case should now be correctly handled by [c5fa9fe](https://github.com/Chocobozzz/PeerTube/commit/c5fa9fe70ef04d70311ffc609381b1a3614ea2c9)
> 
> To fix your issue, try to run HLS transcoding **and** web video transcoding on all your videos. If you don't need/want the web video version, then just run HLS transcoding and remove the web video version from the web interface

Thankfully, this seems to work, though it seems very finicky about the order of operations. If I do HLS transcoding without doing web video first, the move to object storage encounters errors again.

For anybody experiencing my bizarre edge case in future, the best course of action seems to be:

1. Enable video re-uploads in settings
2. Edit the video, and use "Replace video file" to reupload a backup of the original. Ignore the error it throws up when the download completes
3. Go to Administration > Overview > Videos and find the video in question
4. Choose "Run web video transcoding" and let it finish.
5. Then "Run HLS Transcoding"
6. Videos should upload to object storage as expected without error
7. Optionally, delete Web videos when it's all done.

Thank you @Chocobozzz for the assist. The mystery of why the files vanished from object storage in the first place remains unsolved and will haunt me to the day I die, but at least I can fix things now.
