### ISSUE TITLE
Error password authentication failed for create-transcoding-job script

### ISSUE THREAD

**Issue by DavidLibeau** [Chocobozzz/PeerTube#649]
* **PeerTube version or URL:** beta.8
* **NodeJS version:** 5.6.0

* **What is the expected behaviour?**
Run `create-transcoding-job`
* **What do you see instead?**
Error `password authentication failed for user "peertube"`

* **Server log:**

```
~/peertube-latest$ npm run create-transcoding-job -- -v a9232118-1436-403c-a6e8-ff5cbe4e1017

> peertube@1.0.0-beta.8 create-transcoding-job /var/www/peertube/versions/peertube-v1.0.0-beta.8
> node ./dist/scripts/create-transcoding-job.js "-v" "a9232118-1436-403c-a6e8-ff5cbe4e1017"

{ SequelizeConnectionError: password authentication failed for user "peertube"
    at connection.connect.err (/var/www/peertube/versions/peertube-v1.0.0-beta.8/node_modules/sequelize/lib/dialects/postgres/connection-manager.js:128:24)
    at Connection.connectingErrorHandler (/var/www/peertube/versions/peertube-v1.0.0-beta.8/node_modules/pg/lib/client.js:123:14)
    at emitOne (events.js:116:13)
    at Connection.emit (events.js:211:7)
    at Socket.<anonymous> (/var/www/peertube/versions/peertube-v1.0.0-beta.8/node_modules/pg/lib/connection.js:123:12)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at TCP.onread (net.js:597:20)
  name: 'SequelizeConnectionError',
  parent: 
   { error: password authentication failed for user "peertube"
    at Connection.parseE (/var/www/peertube/versions/peertube-v1.0.0-beta.8/node_modules/pg/lib/connection.js:553:11)
    at Connection.parseMessage (/var/www/peertube/versions/peertube-v1.0.0-beta.8/node_modules/pg/lib/connection.js:378:19)
    at Socket.<anonymous> (/var/www/peertube/versions/peertube-v1.0.0-beta.8/node_modules/pg/lib/connection.js:119:22)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at TCP.onread (net.js:597:20)
     name: 'error',
     length: 104,
     severity: 'FATAL',
     code: '28P01',
     detail: undefined,
     hint: undefined,
     position: undefined,
     internalPosition: undefined,
     internalQuery: undefined,
     where: undefined,
     schema: undefined,
     table: undefined,
     column: undefined,
     dataType: undefined,
     constraint: undefined,
     file: 'auth.c',
     line: '307',
     routine: 'auth_failed' },
  original: 
   { error: password authentication failed for user "peertube"
    at Connection.parseE (/var/www/peertube/versions/peertube-v1.0.0-beta.8/node_modules/pg/lib/connection.js:553:11)
    at Connection.parseMessage (/var/www/peertube/versions/peertube-v1.0.0-beta.8/node_modules/pg/lib/connection.js:378:19)
    at Socket.<anonymous> (/var/www/peertube/versions/peertube-v1.0.0-beta.8/node_modules/pg/lib/connection.js:119:22)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at TCP.onread (net.js:597:20)
     name: 'error',
     length: 104,
     severity: 'FATAL',
     code: '28P01',
     detail: undefined,
     hint: undefined,
     position: undefined,
     internalPosition: undefined,
     internalQuery: undefined,
     where: undefined,
     schema: undefined,
     table: undefined,
     column: undefined,
     dataType: undefined,
     constraint: undefined,
     file: 'auth.c',
     line: '307',
     routine: 'auth_failed' } }
npm ERR! code ELIFECYCLE
npm ERR! errno 255
npm ERR! peertube@1.0.0-beta.8 create-transcoding-job: `node ./dist/scripts/create-transcoding-job.js "-v" "a9232118-1436-403c-a6e8-ff5cbe4e1017"`
npm ERR! Exit status 255
npm ERR! 
npm ERR! Failed at the peertube@1.0.0-beta.8 create-transcoding-job script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /var/www/peertube/.npm/_logs/2018-06-11T13_01_22_337Z-debug.log
```

**Comment by Chocobozzz** [comment]
Try 

```
$ NODE_CONFIG_DIR=/var/www/peertube/config NODE_ENV=production npm run create-transcoding-job -- -v a9232118-1436-403c-a6e8-ff5cbe4e1017
```

**Comment by DavidLibeau** [comment]
That's working
