### ISSUE TITLE
ENOENT calling whisper on remote runners

### ISSUE THREAD

**Issue by rknightion** [Chocobozzz/PeerTube#6511]
### Describe the current behavior

On a clean install of remote runner following the docs, whisper fails to spawn.
It is installed correctly and is available in the prunner users path (I can run the commands in the log output successfully on the cached media).

Only transcription is impacted for us. Video transcoding is not impacted by this. Transcription does however work fine on the main peertube node. 

### Additional information

* PeerTube instance:
  * Version: 6.2.0
  * Runner version: 0.0.18
  * NodeJS version: v18.20.4
  * Ffmpeg version: 6.1.1-3ubuntu5 
  * whisper-ctranslate2: 0.4.5

```
prunner@ip-10-0-1-184:~$ which whisper-ctranslate2
/srv/prunner/.local/bin/whisper-ctranslate2
```

Config:
```
[jobs]
concurrency = 2

[ffmpeg]
threads = 2
nice = 20

[transcription]
engine = "whisper-ctranslate2"
model = "large-v3"

[[registeredInstances]]
```

(have also tried with small model and the distil models to no avail. Also tried putting in the direct path with engine_path = "/srv/prunner/.local/bin/whisper-ctranslate2" but no dice).

Logs:
```
ac-f241-4868-b6a2-728114af94df/max-quality for job ptrjt-0f8b6ef5-2b34-488d-8122-d96dd27b4bf6. Running transcription.
Jul 24 15:30:10 ip-10-0-1-184 prunner[2180]: [15:30:10.323] ERROR (2180): Command failed with ENOENT: whisper-ctranslate2 /srv/prunner/.cache/peertube-runner-nodejs/default/transcoding/f1b730e3-8f9f-40ae-a60c-1694b631f8ac --model large-v3 --word_timestamps True --vad_filter true --output_format all --output_dir /srv/prunner/.cache/peertube-runner-nodejs/default/transcription/n4k4e97dmS34HPbT749WDT
Jul 24 15:30:10 ip-10-0-1-184 prunner[2180]:     type: "error"
Jul 24 15:30:10 ip-10-0-1-184 prunner[2180]:     escapedCommand: "whisper-ctranslate2 /srv/prunner/.cache/peertube-runner-nodejs/default/transcoding/f1b730e3-8f9f-40ae-a60c-1694b631f8ac --model large-v3 --word_timestamps True --vad_filter true --output_format all --output_dir /srv/prunner/.cache/peertube-runner-nodejs/default/transcription/n4k4e97dmS34HPbT749WDT"
Jul 24 15:30:10 ip-10-0-1-184 prunner[2180]:     commandId: "1"
Jul 24 15:30:10 ip-10-0-1-184 prunner[2180]:     piped: false
Jul 24 15:30:10 ip-10-0-1-184 prunner[2180]:     result: {
Jul 24 15:30:10 ip-10-0-1-184 prunner[2180]:       "shortMessage": "Command failed with ENOENT: whisper-ctranslate2 /srv/prunner/.cache/peertube-runner-nodejs/default/transcoding/f1b730e3-8f9f-40ae-a60c-1694b631f8ac --model large-v3 --word_timestamps True --vad_filter true --output_format all --output_dir /srv/prunner/.cache/peertube-runner-nodejs/default/transcription/n4k4e97dmS34HPbT749WDT\nspawnwhisper-ctranslate2 ENOENT",
Jul 24 15:30:10 ip-10-0-1-184 prunner[2180]:       "originalMessage": "spawn whisper-ctranslate2 ENOENT",
Jul 24 15:30:10 ip-10-0-1-184 prunner[2180]:       "command": "whisper-ctranslate2 /srv/prunner/.cache/peertube-runner-nodejs/default/transcoding/f1b730e3-8f9f-40ae-a60c-1694b631f8ac --model large-v3 --word_timestamps True --vad_filter true --output_format all --output_dir /srv/prunner/.cache/peertube-runner-nodejs/default/transcription/n4k4e97dmS34HPbT749WDT",
Jul 24 15:30:10 ip-10-0-1-184 prunner[2180]:       "escapedCommand": "whisper-ctranslate2 /srv/prunner/.cache/peertube-runner-nodejs/default/transcoding/f1b730e3-8f9f-40ae-a60c-1694b631f8ac --model large-v3 --word_timestamps True --vad_filter true --output_format all --output_dir /srv/prunner/.cache/peertube-runner-nodejs/default/transcription/n4k4e97dmS34HPbT749WDT",
Jul 24 15:30:10 ip-10-0-1-184 prunner[2180]:       "cwd": "/srv/prunner",
Jul 24 15:30:10 ip-10-0-1-184 prunner[2180]:       "durationMs": 8.710257,
Jul 24 15:30:10 ip-10-0-1-184 prunner[2180]:       "failed": true,
Jul 24 15:30:10 ip-10-0-1-184 prunner[2180]:       "timedOut": false,
Jul 24 15:30:10 ip-10-0-1-184 prunner[2180]:       "isCanceled": false,
Jul 24 15:30:10 ip-10-0-1-184 prunner[2180]:       "isGracefullyCanceled": false,
Jul 24 15:30:10 ip-10-0-1-184 prunner[2180]:       "isTerminated": false,
Jul 24 15:30:10 ip-10-0-1-184 prunner[2180]:       "isMaxBuffer": false,
Jul 24 15:30:10 ip-10-0-1-184 prunner[2180]:       "isForcefullyTerminated": false,
Jul 24 15:30:10 ip-10-0-1-184 prunner[2180]:       "code": "ENOENT",
Jul 24 15:30:10 ip-10-0-1-184 prunner[2180]:       "stdout": "",
Jul 24 15:30:10 ip-10-0-1-184 prunner[2180]:       "stderr": "",
Jul 24 15:30:10 ip-10-0-1-184 prunner[2180]:       "stdio": [
Jul 24 15:30:10 ip-10-0-1-184 prunner[2180]:         null,
Jul 24 15:30:10 ip-10-0-1-184 prunner[2180]:         "",
Jul 24 15:30:10 ip-10-0-1-184 prunner[2180]:         ""
Jul 24 15:30:10 ip-10-0-1-184 prunner[2180]:       ],
Jul 24 15:30:10 ip-10-0-1-184 prunner[2180]:       "ipcOutput": [],
Jul 24 15:30:10 ip-10-0-1-184 prunner[2180]:       "pipedFrom": []
Jul 24 15:30:10 ip-10-0-1-184 prunner[2180]:     }
Jul 24 15:30:10 ip-10-0-1-184 prunner[2180]:     options: {
Jul 24 15:30:10 ip-10-0-1-184 prunner[2180]:       "stdin": "inherit",
Jul 24 15:30:10 ip-10-0-1-184 prunner[2180]:       "preferLocal": true
Jul 24 15:30:10 ip-10-0-1-184 prunner[2180]:     }
Jul 24 15:30:10 ip-10-0-1-184 prunner[2180]: [15:30:10.324] ERROR (2180): spawn whisper-ctranslate2 ENOENT
Jul 24 15:30:10 ip-10-0-1-184 prunner[2180]:     type: "error"
Jul 24 15:30:10 ip-10-0-1-184 prunner[2180]:     escapedCommand: "whisper-ctranslate2 /srv/prunner/.cache/peertube-runner-nodejs/default/transcoding/f1b730e3-8f9f-40ae-a60c-1694b631f8ac --model large-v3 --word_timestamps True --vad_filter true --output_format all --output_dir /srv/prunner/.cache/peertube-runner-nodejs/default/transcription/n4k4e97dmS34HPbT749WDT"
Jul 24 15:30:10 ip-10-0-1-184 prunner[2180]:     commandId: "1"
Jul 24 15:30:10 ip-10-0-1-184 prunner[2180]:     piped: false
Jul 24 15:30:10 ip-10-0-1-184 prunner[2180]:     result: {
Jul 24 15:30:10 ip-10-0-1-184 prunner[2180]:       "shortMessage": "Command failed with ENOENT: whisper-ctranslate2 /srv/prunner/.cache/peertube-runner-nodejs/default/transcoding/f1b730e3-8f9f-40ae-a60c-1694b631f8ac --model large-v3 --word_timestamps True --vad_filter true --output_format all --output_dir /srv/prunner/.cache/peertube-runner-nodejs/default/transcription/n4k4e97dmS34HPbT749WDT\nspawnwhisper-ctranslate2 ENOENT",
Jul 24 15:30:10 ip-10-0-1-184 prunner[2180]:       "originalMessage": "spawn whisper-ctranslate2 ENOENT",
Jul 24 15:30:10 ip-10-0-1-184 prunner[2180]:       "command": "whisper-ctranslate2 /srv/prunner/.cache/peertube-runner-nodejs/default/transcoding/f1b730e3-8f9f-40ae-a60c-1694b631f8ac --model large-v3 --word_timestamps True --vad_filter true --output_format all --output_dir /srv/prunner/.cache/peertube-runner-nodejs/default/transcription/n4k4e97dmS34HPbT749WDT",
Jul 24 15:30:10 ip-10-0-1-184 prunner[2180]:       "escapedCommand": "whisper-ctranslate2 /srv/prunner/.cache/peertube-runner-nodejs/default/transcoding/f1b730e3-8f9f-40ae-a60c-1694b631f8ac --model large-v3 --word_timestamps True --vad_filter true --output_format all --output_dir /srv/prunner/.cache/peertube-runner-nodejs/default/transcription/n4k4e97dmS34HPbT749WDT",
Jul 24 15:30:10 ip-10-0-1-184 prunner[2180]:       "cwd": "/srv/prunner",
Jul 24 15:30:10 ip-10-0-1-184 prunner[2180]:       "durationMs": 8.710257,
Jul 24 15:30:10 ip-10-0-1-184 prunner[2180]:       "failed": true,
Jul 24 15:30:10 ip-10-0-1-184 prunner[2180]:       "timedOut": false,
Jul 24 15:30:10 ip-10-0-1-184 prunner[2180]:       "isCanceled": false,
Jul 24 15:30:10 ip-10-0-1-184 prunner[2180]:       "isGracefullyCanceled": false,
Jul 24 15:30:10 ip-10-0-1-184 prunner[2180]:       "isTerminated": false,
Jul 24 15:30:10 ip-10-0-1-184 prunner[2180]:       "isMaxBuffer": false,
Jul 24 15:30:10 ip-10-0-1-184 prunner[2180]:       "isForcefullyTerminated": false,
Jul 24 15:30:10 ip-10-0-1-184 prunner[2180]:       "code": "ENOENT",
Jul 24 15:30:10 ip-10-0-1-184 prunner[2180]:       "stdout": "",
Jul 24 15:30:10 ip-10-0-1-184 prunner[2180]:       "stderr": "",
Jul 24 15:30:10 ip-10-0-1-184 prunner[2180]:       "stdio": [
Jul 24 15:30:10 ip-10-0-1-184 prunner[2180]:         null,
Jul 24 15:30:10 ip-10-0-1-184 prunner[2180]:         "",
Jul 24 15:30:10 ip-10-0-1-184 prunner[2180]:         ""
Jul 24 15:30:10 ip-10-0-1-184 prunner[2180]:       ],
Jul 24 15:30:10 ip-10-0-1-184 prunner[2180]:       "ipcOutput": [],
Jul 24 15:30:10 ip-10-0-1-184 prunner[2180]:       "pipedFrom": []
Jul 24 15:30:10 ip-10-0-1-184 prunner[2180]:     }
Jul 24 15:30:10 ip-10-0-1-184 prunner[2180]:     options: {
Jul 24 15:30:10 ip-10-0-1-184 prunner[2180]:       "stdin": "inherit",
Jul 24 15:30:10 ip-10-0-1-184 prunner[2180]:       "preferLocal": true
Jul 24 15:30:10 ip-10-0-1-184 prunner[2180]:     }
Jul 24 15:30:10 ip-10-0-1-184 prunner[2180]: [15:30:10.327] ERROR (2180): Cannot process job
Jul 24 15:30:10 ip-10-0-1-184 prunner[2180]:     err: {
Jul 24 15:30:10 ip-10-0-1-184 prunner[2180]:       "type": "ExecaError",
Jul 24 15:30:10 ip-10-0-1-184 prunner[2180]:       "message": "Command failed with ENOENT: whisper-ctranslate2 /srv/prunner/.cache/peertube-runner-nodejs/default/transcoding/f1b730e3-8f9f-40ae-a60c-1694b631f8ac --model large-v3 --word_timestamps True --vad_filter true --output_format all --output_dir /srv/prunner/.cache/peertube-runner-nodejs/default/transcription/n4k4e97dmS34HPbT749WDT\nspawn whisper-ctranslate2 ENOENT: spawn whisper-ctranslate2 ENOENT",
Jul 24 15:30:10 ip-10-0-1-184 prunner[2180]:       "stack":
Jul 24 15:30:10 ip-10-0-1-184 prunner[2180]:           ExecaError: Command failed with ENOENT: whisper-ctranslate2 /srv/prunner/.cache/peertube-runner-nodejs/default/transcoding/f1b730e3-8f9f-40ae-a60c-1694b631f8ac --model large-v3 --word_timestamps True --vad_filter true --output_format all --output_dir /srv/prunner/.cache/peertube-runner-nodejs/default/transcription/n4k4e97dmS34HPbT749WDT
Jul 24 15:30:10 ip-10-0-1-184 prunner[2180]:           spawn whisper-ctranslate2 ENOENT
Jul 24 15:30:10 ip-10-0-1-184 prunner[2180]:               at getFinalError (file:///usr/lib/node_modules/@peertube/peertube-runner/dist/peertube-runner.js:87546:10)
Jul 24 15:30:10 ip-10-0-1-184 prunner[2180]:               at makeError (file:///usr/lib/node_modules/@peertube/peertube-runner/dist/peertube-runner.js:89573:17)
Jul 24 15:30:10 ip-10-0-1-184 prunner[2180]:               at getAsyncResult (file:///usr/lib/node_modules/@peertube/peertube-runner/dist/peertube-runner.js:93234:165)
Jul 24 15:30:10 ip-10-0-1-184 prunner[2180]:               at handlePromise (file:///usr/lib/node_modules/@peertube/peertube-runner/dist/peertube-runner.js:93219:18)
Jul 24 15:30:10 ip-10-0-1-184 prunner[2180]:               at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
Jul 24 15:30:10 ip-10-0-1-184 prunner[2180]:               at async Ctranslate2Transcriber.transcribe (file:///usr/lib/node_modules/@peertube/peertube-runner/dist/peertube-runner.js:93526:5)
Jul 24 15:30:10 ip-10-0-1-184 prunner[2180]:               at async processVideoTranscription (file:///usr/lib/node_modules/@peertube/peertube-runner/dist/peertube-runner.js:93644:28)
Jul 24 15:30:10 ip-10-0-1-184 prunner[2180]:               at async processJob (file:///usr/lib/node_modules/@peertube/peertube-runner/dist/peertube-runner.js:93688:7)
Jul 24 15:30:10 ip-10-0-1-184 prunner[2180]:           caused by: Error: spawn whisper-ctranslate2 ENOENT
Jul 24 15:30:10 ip-10-0-1-184 prunner[2180]:               at ChildProcess._handle.onexit (node:internal/child_process:284:19)
Jul 24 15:30:10 ip-10-0-1-184 prunner[2180]:               at onErrorNT (node:internal/child_process:477:16)
Jul 24 15:30:10 ip-10-0-1-184 prunner[2180]:               at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
Jul 24 15:30:10 ip-10-0-1-184 prunner[2180]:       "shortMessage": "Command failed with ENOENT: whisper-ctranslate2 /srv/prunner/.cache/peertube-runner-nodejs/default/transcoding/f1b730e3-8f9f-40ae-a60c-1694b631f8ac --model large-v3 --word_timestamps True --vad_filter true --output_format all --output_dir /srv/prunner/.cache/peertube-runner-nodejs/default/transcription/n4k4e97dmS34HPbT749WDT\nspawnwhisper-ctranslate2 ENOENT",
Jul 24 15:30:10 ip-10-0-1-184 prunner[2180]:       "originalMessage": "spawn whisper-ctranslate2 ENOENT",
Jul 24 15:30:10 ip-10-0-1-184 prunner[2180]:       "command": "whisper-ctranslate2 /srv/prunner/.cache/peertube-runner-nodejs/default/transcoding/f1b730e3-8f9f-40ae-a60c-1694b631f8ac --model large-v3 --word_timestamps True --vad_filter true --output_format all --output_dir /srv/prunner/.cache/peertube-runner-nodejs/default/transcription/n4k4e97dmS34HPbT749WDT",
Jul 24 15:30:10 ip-10-0-1-184 prunner[2180]:       "escapedCommand": "whisper-ctranslate2 /srv/prunner/.cache/peertube-runner-nodejs/default/transcoding/f1b730e3-8f9f-40ae-a60c-1694b631f8ac --model large-v3 --word_timestamps True --vad_filter true --output_format all --output_dir /srv/prunner/.cache/peertube-runner-nodejs/default/transcription/n4k4e97dmS34HPbT749WDT",
Jul 24 15:30:10 ip-10-0-1-184 prunner[2180]:       "cwd": "/srv/prunner",
Jul 24 15:30:10 ip-10-0-1-184 prunner[2180]:       "durationMs": 8.710257,
Jul 24 15:30:10 ip-10-0-1-184 prunner[2180]:       "failed": true,
Jul 24 15:30:10 ip-10-0-1-184 prunner[2180]:       "timedOut": false,
Jul 24 15:30:10 ip-10-0-1-184 prunner[2180]:       "isCanceled": false,
Jul 24 15:30:10 ip-10-0-1-184 prunner[2180]:       "isGracefullyCanceled": false,
Jul 24 15:30:10 ip-10-0-1-184 prunner[2180]:       "isTerminated": false,
Jul 24 15:30:10 ip-10-0-1-184 prunner[2180]:       "isMaxBuffer": false,
Jul 24 15:30:10 ip-10-0-1-184 prunner[2180]:       "isForcefullyTerminated": false,
Jul 24 15:30:10 ip-10-0-1-184 prunner[2180]:       "code": "ENOENT",
Jul 24 15:30:10 ip-10-0-1-184 prunner[2180]:       "stdout": "",
Jul 24 15:30:10 ip-10-0-1-184 prunner[2180]:       "stderr": "",
Jul 24 15:30:10 ip-10-0-1-184 prunner[2180]:       "stdio": [
Jul 24 15:30:10 ip-10-0-1-184 prunner[2180]:         null,
Jul 24 15:30:10 ip-10-0-1-184 prunner[2180]:         "",
Jul 24 15:30:10 ip-10-0-1-184 prunner[2180]:         ""
Jul 24 15:30:10 ip-10-0-1-184 prunner[2180]:       ],
Jul 24 15:30:10 ip-10-0-1-184 prunner[2180]:       "ipcOutput": [],
Jul 24 15:30:10 ip-10-0-1-184 prunner[2180]:       "pipedFrom": []
Jul 24 15:30:10 ip-10-0-1-184 prunner[2180]:     }
```

**Comment by ssddanbrown** [comment]
I had some trouble with this when it was installed via xpip, and I resolved it by specifically adding the relevant PATH location for the systemd service, for example:

```ini
[Service]
Environment=PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/srv/prunner/.local/bin
```

Remember to daemon-reload systemd and restart the service afterwards.

**Comment by Chocobozzz** [comment]
You can also provide the `enginePath` in the runner configuration:

```
[transcription]
engine = "whisper-ctranslate2"
enginePath = "/var/peertube-runner/.local/pipx/venvs/whisper-ctranslate2/bin/whisper-ctranslate2"
model = "large-v2"
```

I'll improve the runner documentation

**Comment by ROBERT-MCDOWELL** [comment]
@Chocobozzz 
please thank you. because for now, I cannot see any transcripting from each import nor channel sync...

**Comment by Chocobozzz** [comment]
Runner documentation improved in https://github.com/Chocobozzz/PeerTube/commit/417ddb34047e370ec290dffc1efc6191041beae8
