### ISSUE TITLE
[Error] Upload.js 413 "Payload Too Large" (beta-1.0.8)

### ISSUE THREAD

**Issue by MikaXII** [Chocobozzz/PeerTube#658]
* **PeerTube version or URL: 1.0.8-beta**
* **NodeJS version:v9.11.1**

EDIT - server setup : docker with kubernetes [helm charts](https://github.com/MikaXII/helm-charts/tree/master/peertube), but I haven't error in server side because the request aren't send to my peertube instance due to the 413 error. I try with a lower size media and that work fine.

I'll too update a video throught the upload.js tool but I got a 413, the concerned media is around 560Mo.

```
Error: expected 200 "OK", got 413 "Payload Too Large"
    at Test._assertStatus (/home/mikaxii/github/PeerTube/node_modules/supertest/lib/test.js:266:12)
    at Test._assertFunction (/home/mikaxii/github/PeerTube/node_modules/supertest/lib/test.js:281:11)
    at Test.assert (/home/mikaxii/github/PeerTube/node_modules/supertest/lib/test.js:171:18)
    at assert (/home/mikaxii/github/PeerTube/node_modules/supertest/lib/test.js:131:12)
    at /home/mikaxii/github/PeerTube/node_modules/supertest/lib/test.js:128:5
    at Test.Request.callback (/home/mikaxii/github/PeerTube/node_modules/superagent/lib/node/index.js:718:3)
    at IncomingMessage.parser (/home/mikaxii/github/PeerTube/node_modules/superagent/lib/node/index.js:906:18)
    at IncomingMessage.emit (events.js:185:15)
    at endReadableNT (_stream_readable.js:1106:12)
    at process._tickCallback (internal/process/next_tick.js:178:19)
```

**Comment by Chocobozzz** [comment]
Please, fill the template or describe at least your server setup.

**Comment by Chocobozzz** [comment]
Closing due to inactivity. Feel free to comment! :)

**Comment by MikaXII** [comment]
But I've updating the description :(.
Anyway I've plan to work on a cli tools to use the api :)

**Comment by Chocobozzz** [comment]
I think the issue is the reverse proxy that does not accept this big request. Try to increase max body size or something like that

**Comment by MikaXII** [comment]
Ho god.... The default value for ingress in k8s is 1m... 
https://github.com/nginxinc/kubernetes-ingress/tree/master/examples/customization
I should check this doc before open this issue sorry about that...

**Comment by MikaXII** [comment]
Solution for Kubernetes cluster (by rancher v2.16) : 
Add annotation in the ingress.yaml : 
`nginx.ingress.kubernetes.io/proxy-body-size: <size>` size 0 = unlimited

**Comment by poka-IT** [comment]
Same problem here with Peertube 1.0 (last stable) on my own server, ever set nginx at:
`client_max_body_size 4G;`

My file size is only 130M. Don't understand ...

**Comment by MikaXII** [comment]
Did you try to replace `4G` by `0` ?

**Comment by poka-IT** [comment]
Yes same problem with `client_max_body_size 0;`
![capture du 2018-11-02 22-57-16](https://user-images.githubusercontent.com/4574805/47942599-c8f8ca80-def2-11e8-9ab0-11fce86ada38.png)

**Comment by poka-IT** [comment]
Ok the problem was my file encoding...
I used VLC to transform mp3 to mp4 H.264 file, it's working find but Peertube don't like it and indicate it by this way.

I use FFMPEG now in progress and I think that should be ok.

**Comment by jimgroom** [comment]
> I think the issue is the reverse proxy that does not accept this big request. Try to increase max body size or something like that

Hi, I am running the Peertube Docker image without any changes, and I am getting the following error:
expected 200 “OK”, got 413 “Payload Too Large”

I definitely think you are right about the reverse proxy based on what I read here about maxrequestbodybytes in traefik:
https://doc.traefik.io/traefik/middlewares/buffering/#maxrequestbodybytes

Is there anyway to change this setting in the existing Traefik container with the standard Docker image? We tried a couple of things  but have not been able to get the changes accepted.
