### ISSUE TITLE
Version 6.3.0 migration script fails

### ISSUE THREAD

**Issue by M-Stenzel** [Chocobozzz/PeerTube#6592]
### Describe the problem

Upgrade to version 6.3.0 of the software (non-docker).
The migration scripft fails:

```
cd /var/www/peertube/peertube-latest && sudo -u peertube NODE_CONFIG_DIR=/var/www/peertube/config NODE_ENV=production node18 dist/scripts/migrations/peertube-6.3.js
/mnt/volume-hel1-2/var/www/peertube/versions/peertube-v6.3.0/node_modules/config/lib/config.js:854
    throw new Error("Cannot parse config file: '" + fullFilename + "': " + e3);
          ^

Error: Cannot parse config file: '/var/www/peertube/config/production.yaml': YAMLException: can not read a block mapping entry; a multiline key may not be an implicit key (606:7)

 603 | 
 604 |   resolutions: # Only created if the  ...
 605 | <<<<<<< config/production.yaml
 606 |     0p: true # audio-only (creates mp ...
-------------^
 607 | =======
 608 |     0p: false # audio-only (creates m ...
    at util.parseFile (/mnt/volume-hel1-2/var/www/peertube/versions/peertube-v6.3.0/node_modules/config/lib/config.js:854:11)
    at /mnt/volume-hel1-2/var/www/peertube/versions/peertube-v6.3.0/node_modules/config/lib/config.js:650:28
    at Array.forEach (<anonymous>)
    at util.loadFileConfigs (/mnt/volume-hel1-2/var/www/peertube/versions/peertube-v6.3.0/node_modules/config/lib/config.js:649:16)
    at new Config (/mnt/volume-hel1-2/var/www/peertube/versions/peertube-v6.3.0/node_modules/config/lib/config.js:115:27)
    at Object.<anonymous> (/mnt/volume-hel1-2/var/www/peertube/versions/peertube-v6.3.0/node_modules/config/lib/config.js:1514:33)
    at Module._compile (node:internal/modules/cjs/loader:1364:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1422:10)
    at Module.load (node:internal/modules/cjs/loader:1203:32)
    at Module._load (node:internal/modules/cjs/loader:1019:12)

Node.js v18.20.4

```

### Additional information

* OS: x86_64 Linux
* PeerTube instance URL: tube.xy-space.de
* PeerTube version: 6.3.0 (previously 6.2.0)
* NodeJS version: 18.20.4
* Ffmpeg version: 6.1.1
* Redis version: 7.0.8
* PostgreSQL version:

**Comment by MattyBoombalatty** [comment]
You need to go through your `production.yaml` file and remove all of the merge conflicts that begin with ` <<<<<<<`

**Comment by M-Stenzel** [comment]
That was quick, thank you - I did what you suggested. But now I receive:

```
## Updating "formatFlags" column for web videos in "videoFile" table in database ##

Error
    at Query.run (/mnt/volume-hel1-2/var/www/peertube/versions/peertube-v6.3.0/node_modules/sequelize/lib/dialects/postgres/query.js:50:25)
    at /mnt/volume-hel1-2/var/www/peertube/versions/peertube-v6.3.0/node_modules/sequelize/lib/sequelize.js:315:28
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async run (file:///mnt/volume-hel1-2/var/www/peertube/versions/peertube-v6.3.0/dist/scripts/migrations/peertube-6.3.js:22:21) {
  name: 'SequelizeDatabaseError',
  parent: error: column "formatFlags" does not exist
      at Parser.parseErrorMessage (/mnt/volume-hel1-2/var/www/peertube/versions/peertube-v6.3.0/node_modules/pg-protocol/dist/parser.js:283:98)
      at Parser.handlePacket (/mnt/volume-hel1-2/var/www/peertube/versions/peertube-v6.3.0/node_modules/pg-protocol/dist/parser.js:122:29)
      at Parser.parse (/mnt/volume-hel1-2/var/www/peertube/versions/peertube-v6.3.0/node_modules/pg-protocol/dist/parser.js:35:38)
      at Socket.<anonymous> (/mnt/volume-hel1-2/var/www/peertube/versions/peertube-v6.3.0/node_modules/pg-protocol/dist/index.js:11:42)
      at Socket.emit (node:events:517:28)
      at addChunk (node:internal/streams/readable:368:12)
      at readableAddChunk (node:internal/streams/readable:341:9)
      at Readable.push (node:internal/streams/readable:278:10)
      at TCP.onStreamRead (node:internal/stream_base_commons:190:23) {
    length: 111,
    severity: 'ERROR',
    code: '42703',
    detail: undefined,
    hint: undefined,
    position: '77',
    internalPosition: undefined,
    internalQuery: undefined,
    where: undefined,
    schema: undefined,
    table: undefined,
    column: undefined,
    dataType: undefined,
    constraint: undefined,
    file: 'parse_relation.c',
    line: '3333',
    routine: 'errorMissingColumn',
    sql: 'SELECT COUNT(*) AS "total" FROM "videoFile" WHERE "videoId" IS NOT NULL AND "formatFlags" != 1',
    parameters: undefined
  },
  original: error: column "formatFlags" does not exist
      at Parser.parseErrorMessage (/mnt/volume-hel1-2/var/www/peertube/versions/peertube-v6.3.0/node_modules/pg-protocol/dist/parser.js:283:98)
      at Parser.handlePacket (/mnt/volume-hel1-2/var/www/peertube/versions/peertube-v6.3.0/node_modules/pg-protocol/dist/parser.js:122:29)
      at Parser.parse (/mnt/volume-hel1-2/var/www/peertube/versions/peertube-v6.3.0/node_modules/pg-protocol/dist/parser.js:35:38)
      at Socket.<anonymous> (/mnt/volume-hel1-2/var/www/peertube/versions/peertube-v6.3.0/node_modules/pg-protocol/dist/index.js:11:42)
      at Socket.emit (node:events:517:28)
      at addChunk (node:internal/streams/readable:368:12)
      at readableAddChunk (node:internal/streams/readable:341:9)
      at Readable.push (node:internal/streams/readable:278:10)
      at TCP.onStreamRead (node:internal/stream_base_commons:190:23) {
    length: 111,
    severity: 'ERROR',
    code: '42703',
    detail: undefined,
    hint: undefined,
    position: '77',
    internalPosition: undefined,
    internalQuery: undefined,
    where: undefined,
    schema: undefined,
    table: undefined,
    column: undefined,
    dataType: undefined,
    constraint: undefined,
    file: 'parse_relation.c',
    line: '3333',
    routine: 'errorMissingColumn',
    sql: 'SELECT COUNT(*) AS "total" FROM "videoFile" WHERE "videoId" IS NOT NULL AND "formatFlags" != 1',
    parameters: undefined
  },
  sql: 'SELECT COUNT(*) AS "total" FROM "videoFile" WHERE "videoId" IS NOT NULL AND "formatFlags" != 1',
  parameters: {}
}
```

**Comment by MattyBoombalatty** [comment]
Try this

1. Stop the PeerTube service
2. Re-run the upgrade script
3. Start the PeerTube service
4. Run the migration script as referenced in the latest release notes

**Comment by M-Stenzel** [comment]
Thank you again! Migration script needs to be run while peertube is running (as to the documentation). I did not make sure that _indeed_ it was running. After making sure this prerequisite could be check marked the script ran without any issues.
Thank you for quiding me in the right direction!
