### ISSUE TITLE
migration script 6.3.0 error

### ISSUE THREAD

**Issue by ROBERT-MCDOWELL** [Chocobozzz/PeerTube#6602]
### Describe the current behavior

migration update script error, missing columns... 
## Updating "formatFlags" column for web videos in "videoFile" table in database ##

Error
    at Query.run (/home/PEERTUBE/mypt/versions/peertube-v6.3.0/node_modules/sequelize/lib/dialects/postgres/query.js:50:25)
    at /home/PEERTUBE/mypt/versions/peertube-v6.3.0/node_modules/sequelize/lib/sequelize.js:315:28
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async run (file:///home/PEERTUBE/mypt/versions/peertube-v6.3.0/dist/scripts/migrations/peertube-6.3.js:22:21) {
  name: 'SequelizeDatabaseError',
  parent: error: column "formatFlags" does not exist
      at Parser.parseErrorMessage (/home/PEERTUBE/mypt/versions/peertube-v6.3.0/node_modules/pg-protocol/dist/parser.js:283:98)
      at Parser.handlePacket (/home/PEERTUBE/mypt/versions/peertube-v6.3.0/node_modules/pg-protocol/dist/parser.js:122:29)
      at Parser.parse (/home/PEERTUBE/mypt/versions/peertube-v6.3.0/node_modules/pg-protocol/dist/parser.js:35:38)
      at Socket.<anonymous> (/home/PEERTUBE/mypt/versions/peertube-v6.3.0/node_modules/pg-protocol/dist/index.js:11:42)
      at Socket.emit (node:events:518:28)
      at addChunk (node:internal/streams/readable:559:12)
      at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)
      at Readable.push (node:internal/streams/readable:390:5)
      at TCP.onStreamRead (node:internal/stream_base_commons:190:23) {
    length: 111,
    severity: 'ERROR',
    code: '42703',
    detail: undefined,
    hint: undefined,
    position: '77',
    internalPosition: undefined,
    internalQuery: undefined,
    where: undefined,
    schema: undefined,
    table: undefined,
    column: undefined,
    dataType: undefined,
    constraint: undefined,
    file: 'parse_relation.c',
    line: '3722',
    routine: 'errorMissingColumn',
    sql: 'SELECT COUNT(*) AS "total" FROM "videoFile" WHERE "videoId" IS NOT NULL AND "formatFlags" != 1',
    parameters: undefined
  },
  original: error: column "formatFlags" does not exist
      at Parser.parseErrorMessage (/home/PEERTUBE/mypt/versions/peertube-v6.3.0/node_modules/pg-protocol/dist/parser.js:283:98)
      at Parser.handlePacket (/home/PEERTUBE/mypt/versions/peertube-v6.3.0/node_modules/pg-protocol/dist/parser.js:122:29)
      at Parser.parse (/home/PEERTUBE/mypt/versions/peertube-v6.3.0/node_modules/pg-protocol/dist/parser.js:35:38)
      at Socket.<anonymous> (/home/PEERTUBE/mypt/versions/peertube-v6.3.0/node_modules/pg-protocol/dist/index.js:11:42)
      at Socket.emit (node:events:518:28)
      at addChunk (node:internal/streams/readable:559:12)
      at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)
      at Readable.push (node:internal/streams/readable:390:5)
      at TCP.onStreamRead (node:internal/stream_base_commons:190:23) {
    length: 111,
    severity: 'ERROR',
    code: '42703',
    detail: undefined,
    hint: undefined,
    position: '77',
    internalPosition: undefined,
    internalQuery: undefined,
    where: undefined,
    schema: undefined,
    table: undefined,
    column: undefined,
    dataType: undefined,
    constraint: undefined,
    file: 'parse_relation.c',
    line: '3722',
    routine: 'errorMissingColumn',
    sql: 'SELECT COUNT(*) AS "total" FROM "videoFile" WHERE "videoId" IS NOT NULL AND "formatFlags" != 1',
    parameters: undefined
  },
  sql: 'SELECT COUNT(*) AS "total" FROM "videoFile" WHERE "videoId" IS NOT NULL AND "formatFlags" != 1',
  parameters: {}
}

### Steps to reproduce

run the the update
cd /home/PEERTUBE/mypt/peertube-latest/dist/scripts && sudo -H -u peertube ./upgrade.sh /home/PEERTUBE/mypt

the run the migration script
cd /home/PEERTUBE/mypt/peertube-latest && sudo -u peertube NODE_CONFIG_DIR=/home/PEERTUBE/mypt/config NODE_ENV=production node dist/scripts/migrations/peertube-6.3.js

### Additional information

* PeerTube instance: 6.3.0

**Comment by Chocobozzz** [comment]
Hi,

You need to wait for PeerTube DB migrations before running this script :) See the Important notes in the changelog: https://github.com/Chocobozzz/PeerTube/releases/tag/v6.3.0

**Comment by ROBERT-MCDOWELL** [comment]
ok thanks, but how to see the progression of the db migration since the update script finishes asynchronously?

**Comment by Chocobozzz** [comment]
Unfortunately you can't, the migration adds a new column that may take time if you have a big table.

**Comment by poka-IT** [comment]
You can see the database upgrading in process names, `ps -aux | grep peertube`:

`postgres: peertube peertubeprod 172.18.0.42(58038) UPDATE`

---

In my case `REINDEX (VERBOSE) DATABASE peertubeprod;` fixed the issue.
