### ISSUE TITLE
video Imported ok, but transcoding/transcripting failed… then?

### ISSUE THREAD

**Issue by ROBERT-MCDOWELL** [Chocobozzz/PeerTube#6620]
### Describe the current behavior

I can see hundreds of videos which are imported well with yt-dlp or manual url import, but sometimes for X reason the transcription/transcoding failed. The issue here is some videos are imported since months but PT does not try to transcode/transcript again. Is PT really tries to do it or am I missing something?

### Describe the expected behavior

PT should have (or have already?) a timer to check all imported videos that failed to transcode or transcribe and try again for ever. For now the only solution is to go to the video page and do it manually for each video which is impossible to manage if thousands of videos have this issue.

**Comment by Chocobozzz** [comment]
Transcription should be retried, it's not the case?

And can you see why transcription/transcoding jobs fail?

**Comment by MattyBoombalatty** [comment]
I believe my issue is related. Long-form videos with transcription enabled will fail to publish after transcoding. I have the 480p and original resolution transcoded. In the admin panel, all the resolutions are there plus the audio only file, but it stays on "waiting for transcode". When the transcoding job is forced, this is the error:

```

{
  "type": "new-resolution-to-web-video",
  "videoUUID": "8554f991-4152-48cd-97ff-e3aaf38bd9fb",
  "isNewVideo": false,
  "resolution": 480,
  "fps": 30,
  "hasChildren": false
}
TypeError: Cannot read properties of undefined (reading 'toActivityPubObject')
    at file:///var/www/peertube/versions/peertube-v6.3.0/dist/core/models/video/formatter/video-activity-pub-format.js:176:21
    at Array.map (<anonymous>)
    at buildIcon (file:///var/www/peertube/versions/peertube-v6.3.0/dist/core/models/video/formatter/video-activity-pub-format.js:176:10)
    at videoModelToActivityPubObject (file:///var/www/peertube/versions/peertube-v6.3.0/dist/core/models/video/formatter/video-activity-pub-format.js:38:317)
    at VideoModel.toActivityPubObject (file:///var/www/peertube/versions/peertube-v6.3.0/dist/core/models/video/video.js:881:33)
    at sendUpdateVideo (file:///var/www/peertube/versions/peertube-v6.3.0/dist/core/lib/activitypub/send/send-update.js:19:37)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async federateVideoIfNeeded (file:///var/www/peertube/versions/peertube-v6.3.0/dist/core/lib/activitypub/videos/federate.js:18:9)
    at async moveToPublishedState (file:///var/www/peertube/versions/peertube-v6.3.0/dist/core/lib/video-state.js:107:5)
    at async /var/www/peertube/versions/peertube-v6.3.0/node_modules/sequelize/lib/sequelize.js:507:18

```

**Comment by Chocobozzz** [comment]
@MattyBoombalatty Please create a dedicated issue (and paste the URL of the video please)

**Comment by MattyBoombalatty** [comment]
Sure thing.

**Comment by ROBERT-MCDOWELL** [comment]
@Chocobozzz 
well, for many various reason external to PT it can fail, like reboot, a system update breaking some libraries, a timeout, etc...
PT indeed does not retry to transcode/transcript as I can see on the video list some imports made more than 6 months ago....

**Comment by Chocobozzz** [comment]
Merging this issue in https://github.com/Chocobozzz/PeerTube/issues/4771
