### ISSUE TITLE
Front-end error changing video thumbnail: Cannot read properties of undefined (reading 'getImageDataUrl')

### ISSUE THREAD

**Issue by dougluce** [Chocobozzz/PeerTube#6670]
### Describe the current behavior

From `https://vids.horph.com/videos/update/{videoId}`, I'll scrub forward a bit to select a new thumbnail frame and hit "Use this frame." No visible response in the front end (button does nothing) and this error on the console:

```
core.mjs:7181 ERROR TypeError: Cannot read properties of undefined (reading 'getImageDataUrl')
    at i.<anonymous> (thumbnail-manager.component.ts:134:47)
    at Generator.next (<anonymous>)
    at chunk-B6QLNCNA.js:1:1399
    at new R (zone.js:2594:23)
    at F (chunk-B6QLNCNA.js:1:1219)
    at i.selectFrame (thumbnail-manager.component.ts:133:20)
    at thumbnail-manager.component.html:18:86
    at Ix (core.mjs:25834:12)
```

This is on a private instance running v6.3.1 under nodejs v20.15.1. Browser is Chromium (Thorium) 124.0.6367.218 (Official Build) (x86_64) on macOS.

**Comment by Chocobozzz** [comment]
Hi,

You don't have other errors above this one? Can you also try with another web browser? I can't reproduce :thinking:
