### ISSUE TITLE
Transcriptions not possible with latest version of peertube

### ISSUE THREAD

**Issue by M-Stenzel** [Chocobozzz/PeerTube#6678]
### Describe the problem

Transcriptions are not possible since programs for transcription are missing from standard peertube package

### Additional information

* PeerTube instance URL: https://tube.xy-space.de
* PeerTube version: 6.3.2 - non docker

This is in the error logs
`
"shortMessage": "Command failed with ENOENT: /var/www/peertube/storage/bin/pip/bin/whisper-ctranslate2 /var/www/peertube/storage/web-videos/private/10b4de75-353a-41c3-800c-dc188ebce882-1080.mp4 --model medium --word_timestamps True --vad_filter true --vad_min_silence_duration_ms 5000 --output_format all --output_dir
`

I further investigated and found the problem
Both **whisper-ctranslate2** and **openai-whisper** programs are NOT included in the 6.3.2 (and 6.3.0) version package, and yes, there are NOWHERE in the package,

Martin.

**Comment by Chocobozzz** [comment]
Hello,

PeerTube installs whisper on the fly using `pip`. Is `pip` installed on your system? Can you check errors in your logs?

**Comment by M-Stenzel** [comment]
> Hello,
> 
> PeerTube installs whisper on the fly using `pip`. Is `pip` installed on your system? Can you check errors in your logs?

This is what I have found

```

{"type":"error","escapedCommand":"pip3 install -U -t /var/www/peertube/storage/bin/pip 'whisper-ctranslate2==0.4.4'","commandId":"0","timestamp":"2024-07-30T19:33:42.414Z","piped":false,"result":{"stack":"ExecaError: Command failed with exit code 1: pip3 install -U -t /var/www/peertube/storage/bin/pip 'whisper-ctranslate2==0.4.4'\n\nERROR: Could not find a version that satisfies the requirement faster-whisper>=1.0.2 (from whisper-ctranslate2==0.4.4) (from versions: none)\nERROR: No matching distribution found for faster-whisper>=1.0.2 (from whisper-ctranslate2==0.4.4)\n\nCollecting whisper-ctranslate2==0.4.4\n  Downloading whisper_ctranslate2-0.4.4-py3-none-any.whl (24 kB)\n    at getFinalError (file:///mnt/volume-hel1-2/var/www/peertube/versions/peertube-v6.2.0/node_modules/execa/lib/return/final-error.js:6:9)\n    at makeError (file:///mnt/volume-hel1-2/var/www/peertube/versions/peertube-v6.2.0/node_modules/execa/lib/return/result.js:108:16)\n    at getAsyncResult (file:///mnt/volume-hel1-2/var/www/peertube/versions/peertube-v6.2.0/node_modules/execa/lib/methods/main-async.js:167:4)\n    at handlePromise (file:///mnt/volume-hel1-2/var/www/peertube/versions/peertube-v6.2.0/node_modules/execa/lib/methods/main-async.js:150:17)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async Ctranslate2Transcriber.install (file:///mnt/volume-hel1-2/var/www/peertube/versions/peertube-v6.2.0/packages/transcription/dist/whisper/transcriber/ctranslate2-transcriber.js:45:9)\n    at async generateSubtitle (file:///mnt/volume-hel1-2/var/www/peertube/versions/peertube-v6.2.0/dist/core/lib/video-captions.js:63:17)\n    at async Object.wrapPromiseFun (file:///mnt/volume-hel1-2/var/www/peertube/versions/peertube-v6.2.0/dist/core/lib/plugins/hooks.js:8:24)\n    at async Worker.processJob (/mnt/volume-hel1-2/var/www/peertube/versions/peertube-v6.2.0/node_modules/bullmq/dist/cjs/classes/worker.js:440:28)\n    at async Worker.retryIfFailed (/mnt/volume-hel1-2/var/www/peertube/versions/peertube-v6.2.0/node_modules/bullmq/dist/cjs/classes/worker.js:629:24)","message":"Command failed with exit code 1: pip3 install -U -t /var/www/peertube/storage/bin/pip 'whisper-ctranslate2==0.4.4'\n\nERROR: Could not find a version that satisfies the requirement faster-whisper>=1.0.2 (from whisper-ctranslate2==0.4.4) (from versions: none)\nERROR: No matching distribution found for faster-whisper>=1.0.2 (from whisper-ctranslate2==0.4.4)\n\nCollecting whisper-ctranslate2==0.4.4\n  Downloading whisper_ctranslate2-0.4.4-py3-none-any.whl (24 kB)","shortMessage":"Command failed with exit code 1: pip3 install -U -t /var/www/peertube/storage/bin/pip 'whisper-ctranslate2==0.4.4'","command":"pip3 install -U -t /var/www/peertube/storage/bin/pip whisper-ctranslate2==0.4.4","escapedCommand":"pip3 install -U -t /var/www/peertube/storage/bin/pip 'whisper-ctranslate2==0.4.4'","cwd":"/mnt/volume-hel1-2/var/www/peertube/versions/peertube-v6.2.0","durationMs":3295.541543,"failed":true,"timedOut":false,"isCanceled":false,"isGracefullyCanceled":false,"isTerminated":false,"isMaxBuffer":false,"isForcefullyTerminated":false,"exitCode":1,"stdout":"Collecting whisper-ctranslate2==0.4.4\n  Downloading whisper_ctranslate2-0.4.4-py3-none-any.whl (24 kB)","stderr":"ERROR: Could not find a version that satisfies the requirement faster-whisper>=1.0.2 (from whisper-ctranslate2==0.4.4) (from versions: none)\nERROR: No matching distribution found for faster-whisper>=1.0.2 (from whisper-ctranslate2==0.4.4)","stdio":[null,"Collecting whisper-ctranslate2==0.4.4\n  Downloading whisper_ctranslate2-0.4.4-py3-none-any.whl (24 kB)","ERROR: Could not find a version that satisfies the requirement faster-whisper>=1.0.2 (from whisper-ctranslate2==0.4.4) (from versions: none)\nERROR: No matching distribution found for faster-whisper>=1.0.2 (from whisper-ctranslate2==0.4.4)"],"ipcOutput":[],"pipedFrom":[]},"options":{"stdin":"inherit","preferLocal":true},"level":"error","message":"Command failed with exit code 1: pip3 install -U -t /var/www/peertube/storage/bin/pip 'whisper-ctranslate2==0.4.4'","label":"tube.xy-space.de:443"}
{"level":"error","message":"Cannot execute job 1 in queue video-transcription.","label":"tube.xy-space.de:443","payload":{"videoUUID":"be13d4cb-c130-4ce2-a985-ebedd7c530ad"},"err":{"stack":"ExecaError: Command failed with exit code 1: pip3 install -U -t /var/www/peertube/storage/bin/pip 'whisper-ctranslate2==0.4.4'\n\nERROR: Could not find a version that satisfies the requirement faster-whisper>=1.0.2 (from whisper-ctranslate2==0.4.4) (from versions: none)\nERROR: No matching distribution found for faster-whisper>=1.0.2 (from whisper-ctranslate2==0.4.4)\n\nCollecting whisper-ctranslate2==0.4.4\n  Downloading whisper_ctranslate2-0.4.4-py3-none-any.whl (24 kB)\n    at getFinalError (file:///mnt/volume-hel1-2/var/www/peertube/versions/peertube-v6.2.0/node_modules/execa/lib/return/final-error.js:6:9)\n    at makeError (file:///mnt/volume-hel1-2/var/www/peertube/versions/peertube-v6.2.0/node_modules/execa/lib/return/result.js:108:16)\n    at getAsyncResult (file:///mnt/volume-hel1-2/var/www/peertube/versions/peertube-v6.2.0/node_modules/execa/lib/methods/main-async.js:167:4)\n    at handlePromise (file:///mnt/volume-hel1-2/var/www/peertube/versions/peertube-v6.2.0/node_modules/execa/lib/methods/main-async.js:150:17)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async Ctranslate2Transcriber.install (file:///mnt/volume-hel1-2/var/www/peertube/versions/peertube-v6.2.0/packages/transcription/dist/whisper/transcriber/ctranslate2-transcriber.js:45:9)\n    at async generateSubtitle (file:///mnt/volume-hel1-2/var/www/peertube/versions/peertube-v6.2.0/dist/core/lib/video-captions.js:63:17)\n    at async Object.wrapPromiseFun (file:///mnt/volume-hel1-2/var/www/peertube/versions/peertube-v6.2.0/dist/core/lib/plugins/hooks.js:8:24)\n    at async Worker.processJob (/mnt/volume-hel1-2/var/www/peertube/versions/peertube-v6.2.0/node_modules/bullmq/dist/cjs/classes/worker.js:440:28)\n    at async Worker.retryIfFailed (/mnt/volume-hel1-2/var/www/peertube/versions/peertube-v6.2.0/node_modules/bullmq/dist/cjs/classes/worker.js:629:24)","message":"Command failed with exit code 1: pip3 install -U -t /var/www/peertube/storage/bin/pip 'whisper-ctranslate2==0.4.4'\n\nERROR: Could not find a version that satisfies the requirement faster-whisper>=1.0.2 (from whisper-ctranslate2==0.4.4) (from versions: none)\nERROR: No matching distribution found for faster-whisper>=1.0.2 (from whisper-ctranslate2==0.4.4)\n\nCollecting whisper-ctranslate2==0.4.4\n  Downloading whisper_ctranslate2-0.4.4-py3-none-any.whl (24 kB)","shortMessage":"Command failed with exit code 1: pip3 install -U -t /var/www/peertube/storage/bin/pip 'whisper-ctranslate2==0.4.4'","command":"pip3 install -U -t /var/www/peertube/storage/bin/pip whisper-ctranslate2==0.4.4","escapedCommand":"pip3 install -U -t /var/www/peertube/storage/bin/pip 'whisper-ctranslate2==0.4.4'","cwd":"/mnt/volume-hel1-2/var/www/peertube/versions/peertube-v6.2.0","durationMs":3295.541543,"failed":true,"timedOut":false,"isCanceled":false,"isGracefullyCanceled":false,"isTerminated":false,"isMaxBuffer":false,"isForcefullyTerminated":false,"exitCode":1,"stdout":"Collecting whisper-ctranslate2==0.4.4\n  Downloading whisper_ctranslate2-0.4.4-py3-none-any.whl (24 kB)","stderr":"ERROR: Could not find a version that satisfies the requirement faster-whisper>=1.0.2 (from whisper-ctranslate2==0.4.4) (from versions: none)\nERROR: No matching distribution found for faster-whisper>=1.0.2 (from whisper-ctranslate2==0.4.4)","stdio":[null,"Collecting whisper-ctranslate2==0.4.4\n  Downloading whisper_ctranslate2-0.4.4-py3-none-any.whl (24 kB)","ERROR: Could not find a version that satisfies the requirement faster-whisper>=1.0.2 (from whisper-ctranslate2==0.4.4) (from versions: none)\nERROR: No matching distribution found for faster-whisper>=1.0.2 (from whisper-ctranslate2==0.4.4)"],"ipcOutput":[],"pipedFrom":[]},"timestamp":"2024-07-30T19:33:42.518Z"}

```

To circumvent the problem I install whisper by hand, that worked...

Martin.

**Comment by Chocobozzz** [comment]
Can you check your `python3` version?

**Comment by M-Stenzel** [comment]
Well, for user "peertube" it is still 3.6, and I guess that was the problem.

**Comment by Chocobozzz** [comment]
Yes it is, it seems whisper ctranslate needs python >= 3.8. I'll update the dependencies guide
