### ISSUE TITLE
API playlist creation failure

### ISSUE THREAD

**Issue by dougluce** [Chocobozzz/PeerTube#6702]
### Describe the current behavior

When attempting to create a playlist via the API, the response is an error:

    {"type":"https://docs.joinpeertube.org/api-rest-reference.html#section/Errors/TypeError","detail":"Cannot read properties of undefined (reading 'thumbnailfile')","status":500,"code":"TypeError","error":"Cannot read properties of undefined (reading 'thumbnailfile')"}

The logs echo this:

```
{"err":{"stack":"TypeError: Cannot read properties of undefined (reading 'thumbnailfile')\n    at createVideoPlaylist (file:///var/www/peertube/versions/peertube-v6.3.1/dist/core/controllers/api/video-p
laylist.js:73:37)\n    at file:///var/www/peertube/versions/peertube-v6.3.1/dist/core/helpers/database-utils.js:7:25\n    at retryAttempt (/var/www/peertube/versions/peertube-v6.3.1/node_modules/async/r
etry.js:132:9)\n    at retry (/var/www/peertube/versions/peertube-v6.3.1/node_modules/async/retry.js:142:5)\n    at file:///var/www/peertube/versions/peertube-v6.3.1/dist/core/helpers/database-utils.js:
18:9\n    at new Promise (<anonymous>)\n    at transactionRetryer (file:///var/www/peertube/versions/peertube-v6.3.1/dist/core/helpers/database-utils.js:17:12)\n    at retryTransactionWrapper (file:///v
ar/www/peertube/versions/peertube-v6.3.1/dist/core/helpers/database-utils.js:6:12)\n    at file:///var/www/peertube/versions/peertube-v6.3.1/dist/core/middlewares/async.js:27:32\n    at Layer.handle [as
 handle_request] (/var/www/peertube/versions/peertube-v6.3.1/node_modules/express/lib/router/layer.js:95:5)\n    at next (/var/www/peertube/versions/peertube-v6.3.1/node_modules/express/lib/router/route
.js:149:13)\n    at file:///var/www/peertube/versions/peertube-v6.3.1/dist/core/middlewares/async.js:18:13\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)","message":"
Cannot read properties of undefined (reading 'thumbnailfile')"},"level":"warn","message":"Cannot execute createVideoPlaylist with many retries.","label":"vids.horph.com:443","timestamp":"2024-10-28T20:5
7:12.320Z"}
{"err":"TypeError: Cannot read properties of undefined (reading 'thumbnailfile')\n    at createVideoPlaylist (file:///var/www/peertube/versions/peertube-v6.3.1/dist/core/controllers/api/video-playlist.j
s:73:37)\n    at file:///var/www/peertube/versions/peertube-v6.3.1/dist/core/helpers/database-utils.js:7:25\n    at retryAttempt (/var/www/peertube/versions/peertube-v6.3.1/node_modules/async/retry.js:1
32:9)\n    at retry (/var/www/peertube/versions/peertube-v6.3.1/node_modules/async/retry.js:142:5)\n    at file:///var/www/peertube/versions/peertube-v6.3.1/dist/core/helpers/database-utils.js:18:9\n
 at new Promise (<anonymous>)\n    at transactionRetryer (file:///var/www/peertube/versions/peertube-v6.3.1/dist/core/helpers/database-utils.js:17:12)\n    at retryTransactionWrapper (file:///var/www/pe
ertube/versions/peertube-v6.3.1/dist/core/helpers/database-utils.js:6:12)\n    at file:///var/www/peertube/versions/peertube-v6.3.1/dist/core/middlewares/async.js:27:32\n    at Layer.handle [as handle_r
equest] (/var/www/peertube/versions/peertube-v6.3.1/node_modules/express/lib/router/layer.js:95:5)\n    at next (/var/www/peertube/versions/peertube-v6.3.1/node_modules/express/lib/router/route.js:149:1
3)\n    at file:///var/www/peertube/versions/peertube-v6.3.1/dist/core/middlewares/async.js:18:13\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)","level":"error","mes
sage":"Error in controller.","label":"vids.horph.com:443","timestamp":"2024-10-28T20:57:12.321Z"}
{"tags":["http"],"level":"info","message":"127.0.0.1 - - [28/Oct/2024:20:57:12 +0000] \"POST /api/v1/video-playlists HTTP/1.0\" 500 266 \"-\" \"curl/8.9.1\"","label":"vids.horph.com:443","timestamp":"20
24-10-28T20:57:12.324Z"}
```

### Steps to reproduce

    curl -s -H "Authorization:Bearer $AUTH_TOKEN" -H "Accept:application/json" -X POST --data-urlencode 'displayName=Longer raw video files' "https://${PEERTUBEHOST}/api/v1/video-playlists"

### Describe the expected behavior

I expect to get an answer of this form:

    {"videoPlaylist":{"id":112,"shortUUID":"3SBTGHKet53eeN7x5Wj5un","uuid":"174395ae-4385-42a6-bc97-979d5abc6e6d"}}

### Additional information

PeerTube version v6.3.1 under nodejs v20.15.1

**Comment by Chocobozzz** [comment]
Thanks! It should be fixed by https://github.com/Chocobozzz/PeerTube/commit/18d9858109590325c3173ad8a05e0ef76bc446aa

**Comment by dougluce** [comment]
Sounds good! I was waiting to add a test before finalizing a PR. 

Is there an easy way to transcode and run a single test file? `api/videos/video-playlists.ts` in this case..

**Comment by Chocobozzz** [comment]
Yes using `npm run mocha -- --exit --bail packages/tests/src/your-test.ts`. See https://docs.joinpeertube.org/support/doc/development/tests#test

**Comment by dougluce** [comment]
I'm guessing I don't have something set up properly:
```
❯ npm run mocha -- --timeout 30000 --no-config -c --exit --bail ./packages/tests/src/api/videos/video-playlists.ts

> peertube@6.1.0 mocha
> mocha --timeout 30000 --no-config -c --exit --bail ./packages/tests/src/api/videos/video-playlists.ts


TypeError [ERR_UNKNOWN_FILE_EXTENSION]: Unknown file extension ".ts" for /usr/home/doug/src/PeerTube/packages/tests/src/api/videos/video-playlists.ts
```

**Comment by Chocobozzz** [comment]
Use only the options specified in the documentation: `npm run mocha -- --exit --bail ./packages/tests/src/api/videos/video-playlists.ts`

**Comment by dougluce** [comment]
Thanks! Guess I should have actually read what you wrote...
