### ISSUE TITLE
Inability to Federate Instances

### ISSUE THREAD

**Issue by SamuDifferent** [Chocobozzz/PeerTube#6720]
### Describe the current behavior

When trying to federate an instance (Manually or Automatically), the new instance isn't added on the federation list, not even as pending.

### Steps to reproduce

1. Login as root and go to the federation Dashboard
2. Click "Follow"
3. Enter Url and Click Follow 
![image](https://github.com/user-attachments/assets/d49a95e5-15d7-4e68-a53b-92d66d77703a)
4. New Url doesn't appear on followed list
![image](https://github.com/user-attachments/assets/83401544-e740-43bb-b951-eb6d39b7ca9f)

### Describe the expected behavior

Urls should appear in the Followed list.

### Additional information

* PeerTube instance:
  * URL: peertube.cif.su
  * Version: 6.3.3
  * NodeJS version: v18.19.1
  * Ffmpeg version: 6.1.1-3ubuntu5
* Browser name, version and platforms on which you could reproduce the bug: Librewolf (v130.0.1-1), Chromium (v140.0.6723.91), Firefox (v132.0.1),
* Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`):

**Comment by Chocobozzz** [comment]
Can you try with peertube2.cpy.re?

**Comment by SamuDifferent** [comment]
Exactly the same outcome

**Comment by Chocobozzz** [comment]
Please paste your server logs

**Comment by SamuDifferent** [comment]
```

Federation
Moderation
Configuration
Plugins/Themes
System

Standard logs
Last hour (11:50:15 AM -
now
)
⬤
error
Filter logs by tags
Refresh
error[2024/11/13, 12:52:09] Cannot execute job 10 in queue activitypub-follow.
{
  "payload": {
    "host": "peertube2.cpy.re:443",
    "followerActorId": 1
  },
  "err": {
    "stack": "SequelizeValidationError: Validation error: \"http://localhost:9000/accounts/peertube/follows/4138\" is not a valid url.\n    at InstanceValidator._validate (/var/www/peertube/versions/peertube-v6.3.3/node_modules/sequelize/lib/instance-validator.js:50:13)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async InstanceValidator._validateAndRunHooks (/var/www/peertube/versions/peertube-v6.3.3/node_modules/sequelize/lib/instance-validator.js:60:7)\n    at async InstanceValidator.validate (/var/www/peertube/versions/peertube-v6.3.3/node_modules/sequelize/lib/instance-validator.js:54:12)\n    at async ActorFollowModel.save (/var/www/peertube/versions/peertube-v6.3.3/node_modules/sequelize/lib/model.js:2426:7)\n    at async ActorFollowModel.create (/var/www/peertube/versions/peertube-v6.3.3/node_modules/sequelize/lib/model.js:1362:12)\n    at async ActorFollowModel.findOrCreateCustom (file:///var/www/peertube/versions/peertube-v6.3.3/dist/core/models/actor/actor-follow.js:52:27)\n    at async file:///var/www/peertube/versions/peertube-v6.3.3/dist/core/lib/job-queue/handlers/activitypub-follow.js:59:31\n    at async /var/www/peertube/versions/peertube-v6.3.3/node_modules/sequelize/lib/sequelize.js:507:18\n    at async follow (file:///var/www/peertube/versions/peertube-v6.3.3/dist/core/lib/job-queue/handlers/activitypub-follow.js:58:25)",
    "message": "Validation error: \"http://localhost:9000/accounts/peertube/follows/4138\" is not a valid url.",
    "name": "SequelizeValidationError",
    "errors": [
      {
        "message": "\"http://localhost:9000/accounts/peertube/follows/4138\" is not a valid url.",
        "type": "Validation error",
        "path": "url",
        "value": "http://localhost:9000/accounts/peertube/follows/4138",
        "origin": "FUNCTION",
        "instance": {
          "score": 1000,
          "id": null,
          "actorId": 1,
          "targetActorId": 4138,
          "url": "http://localhost:9000/accounts/peertube/follows/4138",
          "state": "pending",
          "updatedAt": "2024-11-13T11:52:09.529Z",
          "createdAt": "2024-11-13T11:52:09.529Z"
        },
        "validatorKey": "isActorFollowUrl",
        "validatorName": null,
        "validatorArgs": [],
        "original": {
          "stack": "Error: \"http://localhost:9000/accounts/peertube/follows/4138\" is not a valid url.\n    at throwIfNotValid (file:///var/www/peertube/versions/peertube-v6.3.3/dist/core/models/shared/sequelize-helpers.js:15:15)\n    at ActorFollowModel.<anonymous> (file:///var/www/peertube/versions/peertube-v6.3.3/dist/core/models/actor/actor-follow.js:537:35)\n    at InstanceValidator._invokeCustomValidator (/var/www/peertube/versions/peertube-v6.3.3/node_modules/sequelize/lib/instance-validator.js:156:31)\n    at /var/www/peertube/versions/peertube-v6.3.3/node_modules/sequelize/lib/instance-validator.js:115:30\n    at /var/www/peertube/versions/peertube-v6.3.3/node_modules/lodash/lodash.js:4967:15\n    at Function.forIn (/var/www/peertube/versions/peertube-v6.3.3/node_modules/lodash/lodash.js:13018:11)\n    at InstanceValidator._singleAttrValidate (/var/www/peertube/versions/peertube-v6.3.3/node_modules/sequelize/lib/instance-validator.js:104:7)\n    at /var/www/peertube/versions/peertube-v6.3.3/node_modules/sequelize/lib/instance-validator.js:82:30\n    at /var/www/peertube/versions/peertube-v6.3.3/node_modules/lodash/lodash.js:4967:15\n    at Function.forIn (/var/www/peertube/versions/peertube-v6.3.3/node_modules/lodash/lodash.js:13018:11)\n    at InstanceValidator._perAttributeValidators (/var/www/peertube/versions/peertube-v6.3.3/node_modules/sequelize/lib/instance-validator.js:70:7)\n    at InstanceValidator._validate (/var/www/peertube/versions/peertube-v6.3.3/node_modules/sequelize/lib/instance-validator.js:46:12)\n    at InstanceValidator._validateAndRunHooks (/var/www/peertube/versions/peertube-v6.3.3/node_modules/sequelize/lib/instance-validator.js:60:18)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async InstanceValidator.validate (/var/www/peertube/versions/peertube-v6.3.3/node_modules/sequelize/lib/instance-validator.js:54:12)",
          "message": "\"http://localhost:9000/accounts/peertube/follows/4138\" is not a valid url."
        }
      }
    ]
  }
}
error[2024/11/13, 12:53:09] Cannot execute job 10 in queue activitypub-follow.
{
  "payload": {
    "host": "peertube2.cpy.re:443",
    "followerActorId": 1
  },
  "err": {
    "stack": "SequelizeValidationError: Validation error: \"http://localhost:9000/accounts/peertube/follows/4138\" is not a valid url.\n    at InstanceValidator._validate (/var/www/peertube/versions/peertube-v6.3.3/node_modules/sequelize/lib/instance-validator.js:50:13)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async InstanceValidator._validateAndRunHooks (/var/www/peertube/versions/peertube-v6.3.3/node_modules/sequelize/lib/instance-validator.js:60:7)\n    at async InstanceValidator.validate (/var/www/peertube/versions/peertube-v6.3.3/node_modules/sequelize/lib/instance-validator.js:54:12)\n    at async ActorFollowModel.save (/var/www/peertube/versions/peertube-v6.3.3/node_modules/sequelize/lib/model.js:2426:7)\n    at async ActorFollowModel.create (/var/www/peertube/versions/peertube-v6.3.3/node_modules/sequelize/lib/model.js:1362:12)\n    at async ActorFollowModel.findOrCreateCustom (file:///var/www/peertube/versions/peertube-v6.3.3/dist/core/models/actor/actor-follow.js:52:27)\n    at async file:///var/www/peertube/versions/peertube-v6.3.3/dist/core/lib/job-queue/handlers/activitypub-follow.js:59:31\n    at async /var/www/peertube/versions/peertube-v6.3.3/node_modules/sequelize/lib/sequelize.js:507:18\n    at async follow (file:///var/www/peertube/versions/peertube-v6.3.3/dist/core/lib/job-queue/handlers/activitypub-follow.js:58:25)",
    "message": "Validation error: \"http://localhost:9000/accounts/peertube/follows/4138\" is not a valid url.",
    "name": "SequelizeValidationError",
    "errors": [
      {
        "message": "\"http://localhost:9000/accounts/peertube/follows/4138\" is not a valid url.",
        "type": "Validation error",
        "path": "url",
        "value": "http://localhost:9000/accounts/peertube/follows/4138",
        "origin": "FUNCTION",
        "instance": {
          "score": 1000,
          "id": null,
          "actorId": 1,
          "targetActorId": 4138,
          "url": "http://localhost:9000/accounts/peertube/follows/4138",
          "state": "pending",
          "updatedAt": "2024-11-13T11:53:09.799Z",
          "createdAt": "2024-11-13T11:53:09.799Z"
        },
        "validatorKey": "isActorFollowUrl",
        "validatorName": null,
        "validatorArgs": [],
        "original": {
          "stack": "Error: \"http://localhost:9000/accounts/peertube/follows/4138\" is not a valid url.\n    at throwIfNotValid (file:///var/www/peertube/versions/peertube-v6.3.3/dist/core/models/shared/sequelize-helpers.js:15:15)\n    at ActorFollowModel.<anonymous> (file:///var/www/peertube/versions/peertube-v6.3.3/dist/core/models/actor/actor-follow.js:537:35)\n    at InstanceValidator._invokeCustomValidator (/var/www/peertube/versions/peertube-v6.3.3/node_modules/sequelize/lib/instance-validator.js:156:31)\n    at /var/www/peertube/versions/peertube-v6.3.3/node_modules/sequelize/lib/instance-validator.js:115:30\n    at /var/www/peertube/versions/peertube-v6.3.3/node_modules/lodash/lodash.js:4967:15\n    at Function.forIn (/var/www/peertube/versions/peertube-v6.3.3/node_modules/lodash/lodash.js:13018:11)\n    at InstanceValidator._singleAttrValidate (/var/www/peertube/versions/peertube-v6.3.3/node_modules/sequelize/lib/instance-validator.js:104:7)\n    at /var/www/peertube/versions/peertube-v6.3.3/node_modules/sequelize/lib/instance-validator.js:82:30\n    at /var/www/peertube/versions/peertube-v6.3.3/node_modules/lodash/lodash.js:4967:15\n    at Function.forIn (/var/www/peertube/versions/peertube-v6.3.3/node_modules/lodash/lodash.js:13018:11)\n    at InstanceValidator._perAttributeValidators (/var/www/peertube/versions/peertube-v6.3.3/node_modules/sequelize/lib/instance-validator.js:70:7)\n    at InstanceValidator._validate (/var/www/peertube/versions/peertube-v6.3.3/node_modules/sequelize/lib/instance-validator.js:46:12)\n    at InstanceValidator._validateAndRunHooks (/var/www/peertube/versions/peertube-v6.3.3/node_modules/sequelize/lib/instance-validator.js:60:18)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async InstanceValidator.validate (/var/www/peertube/versions/peertube-v6.3.3/node_modules/sequelize/lib/instance-validator.js:54:12)",
          "message": "\"http://localhost:9000/accounts/peertube/follows/4138\" is not a valid url."
        }
      }
    ]
  }
}
```

**Comment by Chocobozzz** [comment]
Run the script to fix your internal URLs: https://docs.joinpeertube.org/maintain/tools#update-peertube-instance-domain-name

**Comment by SamuDifferent** [comment]
The Problem still persists, even after running the script, restarting peertube and even rebooting the whole server.

**Comment by Chocobozzz** [comment]
> The Problem still persists, even after running the script, restarting peertube and even rebooting the whole server.

I can see the URLs are fixed. Can you try to follow another server, like peertube.cpy.re and display your server logs?
