### ISSUE TITLE
SequelizeConnectionAcquireTimeoutError: Operation timeout

### ISSUE THREAD

**Issue by bestperson-free** [Chocobozzz/PeerTube#6723]
### Describe the current behavior

Greetings, errors like this occur from time to time, especially in version 6.3.3. I reinstalled the server again, I thought maybe something was wrong, today I got the same thing again. In Postgres there is nothing suspicious in the logs, Nginx gives errors 500
Log peertube
```
{"tags":["http"],"level":"info","message":"95.153.0.0 - - [14/Nov/2024:06:34:50 +0000] \"GET /static/streaming-playlists/hls/private/209e9a11-2c14-4849-adbd-8864f2b68c2e/38c67011-9be7-4a67-86d1-f9262423103a-720-fragmented.mp4 HTTP/1.0\" 206 1080343 \"https://angeltales.angellive.ru/w/52Cc55xCGb3tv3qoHmMNpq\" \"Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Mobile Safari/537.36\"","label":"angeltales.angellive.ru:443","timestamp":"2024-11-14T06:34:50.952Z"}
{"err":"SequelizeConnectionAcquireTimeoutError: Operation timeout\n    at ConnectionManager.getConnection (/var/www/peertube/versions/peertube-v6.3.3/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:206:15)\n    at async /var/www/peertube/versions/peertube-v6.3.3/node_modules/sequelize/lib/sequelize.js:305:26\n    at async PostgresQueryInterface.upsert (/var/www/peertube/versions/peertube-v6.3.3/node_modules/sequelize/lib/dialects/abstract/query-interface.js:341:12)\n    at async UserVideoHistoryModel.upsert (/var/www/peertube/versions/peertube-v6.3.3/node_modules/sequelize/lib/model.js:1533:20)\n    at async updateUserHistoryIfNeeded (file:///var/www/peertube/versions/peertube-v6.3.3/dist/core/controllers/api/videos/view.js:34:5)\n    at async viewVideo (file:///var/www/peertube/versions/peertube-v6.3.3/dist/core/controllers/api/videos/view.js:24:5)","level":"error","message":"Error in controller.","label":"angeltales.angellive.ru:443","timestamp":"2024-11-14T06:35:50.993Z"}
{"err":"SequelizeConnectionAcquireTimeoutError: Operation timeout\n    at ConnectionManager.getConnection (/var/www/peertube/versions/peertube-v6.3.3/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:206:15)\n    at runNextTicks (node:internal/process/task_queues:60:5)\n    at listOnTimeout (node:internal/timers:545:9)\n    at process.processTimers (node:internal/timers:519:7)\n    at async /var/www/peertube/versions/peertube-v6.3.3/node_modules/sequelize/lib/sequelize.js:305:26\n    at async PostgresQueryInterface.upsert (/var/www/peertube/versions/peertube-v6.3.3/node_modules/sequelize/lib/dialects/abstract/query-interface.js:341:12)\n    at async UserVideoHistoryModel.upsert (/var/www/peertube/versions/peertube-v6.3.3/node_modules/sequelize/lib/model.js:1533:20)\n    at async updateUserHistoryIfNeeded (file:///var/www/peertube/versions/peertube-v6.3.3/dist/core/controllers/api/videos/view.js:34:5)\n    at async viewVideo (file:///var/www/peertube/versions/peertube-v6.3.3/dist/core/controllers/api/videos/view.js:24:5)","level":"error","message":"Error in controller.","label":"angeltales.angellive.ru:443","timestamp":"2024-11-14T06:35:51.003Z"}
{"err":"SequelizeConnectionAcquireTimeoutError: Operation timeout\n    at ConnectionManager.getConnection (/var/www/peertube/versions/peertube-v6.3.3/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:206:15)\n    at async /var/www/peertube/versions/peertube-v6.3.3/node_modules/sequelize/lib/sequelize.js:305:26\n    at async PostgresQueryInterface.upsert (/var/www/peertube/versions/peertube-v6.3.3/node_modules/sequelize/lib/dialects/abstract/query-interface.js:341:12)\n    at async UserVideoHistoryModel.upsert (/var/www/peertube/versions/peertube-v6.3.3/node_modules/sequelize/lib/model.js:1533:20)\n    at async updateUserHistoryIfNeeded (file:///var/www/peertube/versions/peertube-v6.3.3/dist/core/controllers/api/videos/view.js:34:5)\n    at async viewVideo (file:///var/www/peertube/versions/peertube-v6.3.3/dist/core/controllers/api/videos/view.js:24:5)","level":"error","message":"Error in controller.","label":"angeltales.angellive.ru:443","timestamp":"2024-11-14T06:35:51.004Z"}
{"tags":["http"],"level":"info","message":"95.153.0.0 - - [14/Nov/2024:06:35:51 +0000] \"POST /api/v1/videos/209e9a11-2c14-4849-adbd-8864f2b68c2e/views HTTP/1.0\" 500 317 \"https://angeltales.angellive.ru/w/52Cc55xCGb3tv3qoHmMNpq\" \"Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Mobile Safari/537.36\"","label":"angeltales.angellive.ru:443","timestamp":"2024-11-14T06:35:51.008Z"}
{"err":"SequelizeConnectionAcquireTimeoutError: Operation timeout\n    at ConnectionManager.getConnection (/var/www/peertube/versions/peertube-v6.3.3/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:206:15)\n    at runNextTicks (node:internal/process/task_queues:60:5)\n    at listOnTimeout (node:internal/timers:545:9)\n    at process.processTimers (node:internal/timers:519:7)\n    at async /var/www/peertube/versions/peertube-v6.3.3/node_modules/sequelize/lib/sequelize.js:305:26\n    at async PostgresQueryInterface.upsert (/var/www/peertube/versions/peertube-v6.3.3/node_modules/sequelize/lib/dialects/abstract/query-interface.js:341:12)\n    at async UserVideoHistoryModel.upsert (/var/www/peertube/versions/peertube-v6.3.3/node_modules/sequelize/lib/model.js:1533:20)\n    at async updateUserHistoryIfNeeded (file:///var/www/peertube/versions/peertube-v6.3.3/dist/core/controllers/api/videos/view.js:34:5)\n    at async viewVideo (file:///var/www/peertube/versions/peertube-v6.3.3/dist/core/controllers/api/videos/view.js:24:5)","level":"error","message":"Error in controller.","label":"angeltales.angellive.ru:443","timestamp":"2024-11-14T06:35:51.013Z"}
{"tags":["http"],"level":"info","message":"95.153.0.0 - - [14/Nov/2024:06:35:51 +0000] \"POST /api/v1/videos/209e9a11-2c14-4849-adbd-8864f2b68c2e/views HTTP/1.0\" 500 317 \"https://angeltales.angellive.ru/w/52Cc55xCGb3tv3qoHmMNpq\" \"Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Mobile Safari/537.36\"","label":"angeltales.angellive.ru:443","timestamp":"2024-11-14T06:35:51.015Z"}
{"err":"SequelizeConnectionAcquireTimeoutError: Operation timeout\n    at ConnectionManager.getConnection (/var/www/peertube/versions/peertube-v6.3.3/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:206:15)\n    at runNextTicks (node:internal/process/task_queues:60:5)\n    at listOnTimeout (node:internal/timers:545:9)\n    at process.processTimers (node:internal/timers:519:7)\n    at async /var/www/peertube/versions/peertube-v6.3.3/node_modules/sequelize/lib/sequelize.js:305:26\n    at async PostgresQueryInterface.upsert (/var/www/peertube/versions/peertube-v6.3.3/node_modules/sequelize/lib/dialects/abstract/query-interface.js:341:12)\n    at async UserVideoHistoryModel.upsert (/var/www/peertube/versions/peertube-v6.3.3/node_modules/sequelize/lib/model.js:1533:20)\n    at async updateUserHistoryIfNeeded (file:///var/www/peertube/versions/peertube-v6.3.3/dist/core/controllers/api/videos/view.js:34:5)\n    at async viewVideo (file:///var/www/peertube/versions/peertube-v6.3.3/dist/core/controllers/api/videos/view.js:24:5)","level":"error","message":"Error in controller.","label":"angeltales.angellive.ru:443","timestamp":"2024-11-14T06:35:51.015Z"}
{"tags":["http"],"level":"info","message":"95.153.0.0 - - [14/Nov/2024:06:35:51 +0000] \"POST /api/v1/videos/209e9a11-2c14-4849-adbd-8864f2b68c2e/views HTTP/1.0\" 500 317 \"https://angeltales.angellive.ru/w/52Cc55xCGb3tv3qoHmMNpq\" \"Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Mobile Safari/537.36\"","label":"angeltales.angellive.ru:443","timestamp":"2024-11-14T06:35:51.018Z"}
{"err":"SequelizeConnectionAcquireTimeoutError: Operation timeout\n    at ConnectionManager.getConnection (/var/www/peertube/versions/peertube-v6.3.3/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:206:15)\n    at runNextTicks (node:internal/process/task_queues:60:5)\n    at listOnTimeout (node:internal/timers:545:9)\n    at process.processTimers (node:internal/timers:519:7)\n    at async /var/www/peertube/versions/peertube-v6.3.3/node_modules/sequelize/lib/sequelize.js:305:26\n    at async PostgresQueryInterface.upsert (/var/www/peertube/versions/peertube-v6.3.3/node_modules/sequelize/lib/dialects/abstract/query-interface.js:341:12)\n    at async UserVideoHistoryModel.upsert (/var/www/peertube/versions/peertube-v6.3.3/node_modules/sequelize/lib/model.js:1533:20)\n    at async updateUserHistoryIfNeeded (file:///var/www/peertube/versions/peertube-v6.3.3/dist/core/controllers/api/videos/view.js:34:5)\n    at async viewVideo (file:///var/www/peertube/versions/peertube-v6.3.3/dist/core/controllers/api/videos/view.js:24:5)","level":"error","message":"Error in controller.","label":"angeltales.angellive.ru:443","timestamp":"2024-11-14T06:35:51.019Z"}
{"tags":["http"],"level":"info","message":"95.153.0.0 - - [14/Nov/2024:06:35:51 +0000] \"POST /api/v1/videos/209e9a11-2c14-4849-adbd-8864f2b68c2e/views HTTP/1.0\" 500 317 \"https://angeltales.angellive.ru/w/52Cc55xCGb3tv3qoHmMNpq\" \"Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Mobile Safari/537.36\"","label":"angeltales.angellive.ru:443","timestamp":"2024-11-14T06:35:51.023Z"}
{"err":"SequelizeConnectionAcquireTimeoutError: Operation timeout\n    at ConnectionManager.getConnection (/var/www/peertube/versions/peertube-v6.3.3/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:206:15)\n    at async /var/www/peertube/versions/peertube-v6.3.3/node_modules/sequelize/lib/sequelize.js:305:26\n    at async PostgresQueryInterface.upsert (/var/www/peertube/versions/peertube-v6.3.3/node_modules/sequelize/lib/dialects/abstract/query-interface.js:341:12)\n    at async UserVideoHistoryModel.upsert (/var/www/peertube/versions/peertube-v6.3.3/node_modules/sequelize/lib/model.js:1533:20)\n    at async updateUserHistoryIfNeeded (file:///var/www/peertube/versions/peertube-v6.3.3/dist/core/controllers/api/videos/view.js:34:5)\n    at async viewVideo (file:///var/www/peertube/versions/peertube-v6.3.3/dist/core/controllers/api/videos/view.js:24:5)","level":"error","message":"Error in controller.","label":"angeltales.angellive.ru:443","timestamp":"2024-11-14T06:35:51.025Z"}
{"tags":["http"],"level":"info","message":"95.153.0.0 - - [14/Nov/2024:06:35:51 +0000] \"POST /api/v1/videos/209e9a11-2c14-4849-adbd-8864f2b68c2e/views HTTP/1.0\" 500 317 \"https://angeltales.angellive.ru/w/52Cc55xCGb3tv3qoHmMNpq\" \"Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Mobile Safari/537.36\"","label":"angeltales.angellive.ru:443","timestamp":"2024-11-14T06:35:51.028Z"}
{"err":"SequelizeConnectionAcquireTimeoutError: Operation timeout\n    at ConnectionManager.getConnection (/var/www/peertube/versions/peertube-v6.3.3/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:206:15)\n    at async /var/www/peertube/versions/peertube-v6.3.3/node_modules/sequelize/lib/sequelize.js:305:26\n    at async PostgresQueryInterface.upsert (/var/www/peertube/versions/peertube-v6.3.3/node_modules/sequelize/lib/dialects/abstract/query-interface.js:341:12)\n    at async UserVideoHistoryModel.upsert (/var/www/peertube/versions/peertube-v6.3.3/node_modules/sequelize/lib/model.js:1533:20)\n    at async updateUserHistoryIfNeeded (file:///var/www/peertube/versions/peertube-v6.3.3/dist/core/controllers/api/videos/view.js:34:5)\n    at async viewVideo (file:///var/www/peertube/versions/peertube-v6.3.3/dist/core/controllers/api/videos/view.js:24:5)","level":"error","message":"Error in controller.","label":"angeltales.angellive.ru:443","timestamp":"2024-11-14T06:35:51.033Z"}
{"tags":["http"],"level":"info","message":"95.153.0.0 - - [14/Nov/2024:06:35:51 +0000] \"POST /api/v1/videos/209e9a11-2c14-4849-adbd-8864f2b68c2e/views HTTP/1.0\" 500 317 \"https://angeltales.angellive.ru/w/52Cc55xCGb3tv3qoHmMNpq\" \"Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Mobile Safari/537.36\"","label":"angeltales.angellive.ru:443","timestamp":"2024-11-14T06:35:51.034Z"}
{"err":"SequelizeConnectionAcquireTimeoutError: Operation timeout\n    at ConnectionManager.getConnection (/var/www/peertube/versions/peertube-v6.3.3/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:206:15)\n    at runNextTicks (node:internal/process/task_queues:60:5)\n    at listOnTimeout (node:internal/timers:545:9)\n    at process.processTimers (node:internal/timers:519:7)\n    at async /var/www/peertube/versions/peertube-v6.3.3/node_modules/sequelize/lib/sequelize.js:305:26\n    at async PostgresQueryInterface.upsert (/var/www/peertube/versions/peertube-v6.3.3/node_modules/sequelize/lib/dialects/abstract/query-interface.js:341:12)\n    at async UserVideoHistoryModel.upsert (/var/www/peertube/versions/peertube-v6.3.3/node_modules/sequelize/lib/model.js:1533:20)\n    at async updateUserHistoryIfNeeded (file:///var/www/peertube/versions/peertube-v6.3.3/dist/core/controllers/api/videos/view.js:34:5)\n    at async viewVideo (file:///var/www/peertube/versions/peertube-v6.3.3/dist/core/controllers/api/videos/view.js:24:5)","level":"error","message":"Error in controller.","label":"angeltales.angellive.ru:443","timestamp":"2024-11-14T06:35:51.035Z"}
{"tags":["http"],"level":"info","message":"95.153.0.0 - - [14/Nov/2024:06:35:51 +0000] \"POST /api/v1/videos/209e9a11-2c14-4849-adbd-8864f2b68c2e/views HTTP/1.0\" 500 317 \"https://angeltales.angellive.ru/w/52Cc55xCGb3tv3qoHmMNpq\" \"Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Mobile Safari/537.36\"","label":"angeltales.angellive.ru:443","timestamp":"2024-11-14T06:35:51.043Z"}
{"err":"SequelizeConnectionAcquireTimeoutError: Operation timeout\n    at ConnectionManager.getConnection (/var/www/peertube/versions/peertube-v6.3.3/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:206:15)\n    at async /var/www/peertube/versions/peertube-v6.3.3/node_modules/sequelize/lib/sequelize.js:305:26\n    at async PostgresQueryInterface.upsert (/var/www/peertube/versions/peertube-v6.3.3/node_modules/sequelize/lib/dialects/abstract/query-interface.js:341:12)\n    at async UserVideoHistoryModel.upsert (/var/www/peertube/versions/peertube-v6.3.3/node_modules/sequelize/lib/model.js:1533:20)\n    at async updateUserHistoryIfNeeded (file:///var/www/peertube/versions/peertube-v6.3.3/dist/core/controllers/api/videos/view.js:34:5)\n    at async viewVideo (file:///var/www/peertube/versions/peertube-v6.3.3/dist/core/controllers/api/videos/view.js:24:5)","level":"error","message":"Error in controller.","label":"angeltales.angellive.ru:443","timestamp":"2024-11-14T06:35:51.043Z"}
{"tags":["http"],"level":"info","message":"95.153.0.0 - - [14/Nov/2024:06:35:51 +0000] \"POST /api/v1/videos/209e9a11-2c14-4849-adbd-8864f2b68c2e/views HTTP/1.0\" 500 317 \"https://angeltales.angellive.ru/w/52Cc55xCGb3tv3qoHmMNpq\" \"Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Mobile Safari/537.36\"","label":"angeltales.angellive.ru:443","timestamp":"2024-11-14T06:35:51.044Z"}
{"level":"error","message":"Cannot execute RunnerJobWatchDogScheduler scheduler.","label":"angeltales.angellive.ru:443","err":{"stack":"SequelizeConnectionAcquireTimeoutError: Operation timeout\n    at ConnectionManager.getConnection (/var/www/peertube/versions/peertube-v6.3.3/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:206:15)\n    at async /var/www/peertube/versions/peertube-v6.3.3/node_modules/sequelize/lib/sequelize.js:305:26\n    at async PostgresQueryInterface.select (/var/www/peertube/versions/peertube-v6.3.3/node_modules/sequelize/lib/dialects/abstract/query-interface.js:407:12)\n    at async RunnerJobModel.findAll (/var/www/peertube/versions/peertube-v6.3.3/node_modules/sequelize/lib/model.js:1140:21)\n    at async RunnerJobWatchDogScheduler.internalExecute (file:///var/www/peertube/versions/peertube-v6.3.3/dist/core/lib/schedulers/runner-job-watch-dog-scheduler.js:14:32)\n    at async RunnerJobWatchDogScheduler.execute (file:///var/www/peertube/versions/peertube-v6.3.3/dist/core/lib/schedulers/abstract-scheduler.js:19:13)","message":"Operation timeout","name":"SequelizeConnectionAcquireTimeoutError","parent":{"stack":"Error: Operation timeout\n    at Timeout.<anonymous> (/var/www/peertube/versions/peertube-v6.3.3/node_modules/sequelize-pool/lib/Deferred.js:17:25)\n    at listOnTimeout (node:internal/timers:581:17)\n    at process.processTimers (node:internal/timers:519:7)","message":"Operation timeout"}},"timestamp":"2024-11-14T06:35:55.130Z"}
```
Log Nginx
```
1.1.1.1. - - [14/Nov/2024:06:34:39 +0000] "GET /socket.io/?accessToken=79788056ea2d1edd537c45427951b91bd49cf781&EIO=4&transport=websocket&sid=S8VFe2URgPxbBOpgAAAR HTTP/1.1" 101 54 "-" "Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Mobile Safari/537.36"
1.1.1.1. - - [14/Nov/2024:06:34:50 +0000] "GET /static/streaming-playlists/hls/private/209e9a11-2c14-4849-adbd-8864f2b68c2e/38c67011-9be7-4a67-86d1-f9262423103a-720-fragmented.mp4 HTTP/2.0" 206 0 "https://angeltales.angellive.ru/w/52Cc55xCGb3tv3qoHmMNpq" "Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Mobile Safari/537.36"
1.1.1.1. - - [14/Nov/2024:06:35:51 +0000] "POST /api/v1/videos/209e9a11-2c14-4849-adbd-8864f2b68c2e/views HTTP/2.0" 500 0 "https://angeltales.angellive.ru/w/52Cc55xCGb3tv3qoHmMNpq" "Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Mobile Safari/537.36"
1.1.1.1. - - [14/Nov/2024:06:35:51 +0000] "POST /api/v1/videos/209e9a11-2c14-4849-adbd-8864f2b68c2e/views HTTP/2.0" 500 0 "https://angeltales.angellive.ru/w/52Cc55xCGb3tv3qoHmMNpq" "Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Mobile Safari/537.36"
1.1.1.1. - - [14/Nov/2024:06:35:51 +0000] "POST /api/v1/videos/209e9a11-2c14-4849-adbd-8864f2b68c2e/views HTTP/2.0" 500 0 "https://angeltales.angellive.ru/w/52Cc55xCGb3tv3qoHmMNpq" "Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Mobile Safari/537.36"
1.1.1.1. - - [14/Nov/2024:06:35:51 +0000] "POST /api/v1/videos/209e9a11-2c14-4849-adbd-8864f2b68c2e/views HTTP/2.0" 500 0 "https://angeltales.angellive.ru/w/52Cc55xCGb3tv3qoHmMNpq" "Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Mobile Safari/537.36"
1.1.1.1. - - [14/Nov/2024:06:35:51 +0000] "POST /api/v1/videos/209e9a11-2c14-4849-adbd-8864f2b68c2e/views HTTP/2.0" 500 0 "https://angeltales.angellive.ru/w/52Cc55xCGb3tv3qoHmMNpq" "Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Mobile Safari/537.36"
1.1.1.1. - - [14/Nov/2024:06:35:51 +0000] "POST /api/v1/videos/209e9a11-2c14-4849-adbd-8864f2b68c2e/views HTTP/2.0" 500 0 "https://angeltales.angellive.ru/w/52Cc55xCGb3tv3qoHmMNpq" "Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Mobile Safari/537.36"
1.1.1.1. - - [14/Nov/2024:06:35:51 +0000] "POST /api/v1/videos/209e9a11-2c14-4849-adbd-8864f2b68c2e/views HTTP/2.0" 500 0 "https://angeltales.angellive.ru/w/52Cc55xCGb3tv3qoHmMNpq" "Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Mobile Safari/537.36"
1.1.1.1. - - [14/Nov/2024:06:35:51 +0000] "POST /api/v1/videos/209e9a11-2c14-4849-adbd-8864f2b68c2e/views HTTP/2.0" 500 0 "https://angeltales.angellive.ru/w/52Cc55xCGb3tv3qoHmMNpq" "Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Mobile Safari/537.36"
66.249.73.14 - - [14/Nov/2024:06:41:54 +0000] "GET /robots.txt HTTP/1.1" 200 24 "-" "Mozilla/5.0 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)"
66.249.73.15 - - [14/Nov/2024:06:41:55 +0000] "GET /lazy-static/avatars/223bf081-60b1-4997-ab5c-a0902effd837.jpg HTTP/1.1" 200 66022 "-" "Googlebot-Image/1.0"
159.203.17.77 - - [14/Nov/2024:06:58:05 +0000] "GET /.env HTTP/1.1" 400 255 "-" "Mozilla/5.0 Keydrop"
1.1.1.1. - - [14/Nov/2024:07:06:29 +0000] "GET / HTTP/3.0" 304 0 "-" "Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Mobile Safari/537.36"
66.249.73.15 - - [14/Nov/2024:08:20:45 +0000] "GET /lazy-static/avatars/f04ab44b-f2de-4534-a1c8-245d48edd664.jpg HTTP/1.1" 200 233716 "-" "Googlebot-Image/1.0"
178.215.238.11 - - [14/Nov/2024:08:27:43 +0000] "GET / HTTP/1.1" 200 18008 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36"
```
Log Postgres
```
2024-11-14 05:06:38.238 UTC [653] LOG:  checkpoint starting: time
2024-11-14 05:06:39.469 UTC [653] LOG:  checkpoint complete: wrote 11 buffers (0.1%); 0 WAL file(s) added, 0 removed, 0 recycled; write=1.012 s, sync=0.021 s, total=1.232 s; sync files=9, longest=0.019 s, average=0.003 s; distance=39 kB, estimate=119 kB; lsn=0/2C54CE0, redo lsn=0/2C54CA8
2024-11-14 06:11:39.466 UTC [653] LOG:  checkpoint starting: time
2024-11-14 06:11:41.386 UTC [653] LOG:  checkpoint complete: wrote 16 buffers (0.1%); 0 WAL file(s) added, 0 removed, 0 recycled; write=1.546 s, sync=0.081 s, total=1.920 s; sync files=12, longest=0.066 s, average=0.007 s; distance=60 kB, estimate=113 kB; lsn=0/2C63D80, redo lsn=0/2C63D48
2024-11-14 06:31:39.608 UTC [653] LOG:  checkpoint starting: time
2024-11-14 06:31:41.651 UTC [653] LOG:  checkpoint complete: wrote 20 buffers (0.1%); 0 WAL file(s) added, 0 removed, 0 recycled; write=1.919 s, sync=0.045 s, total=2.044 s; sync files=19, longest=0.027 s, average=0.003 s; distance=48 kB, estimate=107 kB; lsn=0/2C700A0, redo lsn=0/2C70068
2024-11-14 06:36:39.731 UTC [653] LOG:  checkpoint starting: time
2024-11-14 06:36:40.053 UTC [653] LOG:  checkpoint complete: wrote 3 buffers (0.0%); 0 WAL file(s) added, 0 removed, 0 recycled; write=0.210 s, sync=0.042 s, total=0.322 s; sync files=3, longest=0.041 s, average=0.014 s; distance=9 kB, estimate=97 kB; lsn=0/2C72638, redo lsn=0/2C72600
2024-11-14 06:41:39.129 UTC [653] LOG:  checkpoint starting: time
2024-11-14 06:41:40.887 UTC [653] LOG:  checkpoint complete: wrote 17 buffers (0.1%); 0 WAL file(s) added, 0 removed, 0 recycled; write=1.615 s, sync=0.087 s, total=1.758 s; sync files=16, longest=0.084 s, average=0.006 s; distance=83 kB, estimate=96 kB; lsn=0/2C87460, redo lsn=0/2C87428
2024-11-14 07:06:40.239 UTC [653] LOG:  checkpoint starting: time
2024-11-14 07:06:40.999 UTC [653] LOG:  checkpoint complete: wrote 8 buffers (0.0%); 0 WAL file(s) added, 0 removed, 0 recycled; write=0.708 s, sync=0.026 s, total=0.761 s; sync files=8, longest=0.019 s, average=0.004 s; distance=23 kB, estimate=88 kB; lsn=0/2C8D3E8, redo lsn=0/2C8D3B0
2024-11-14 08:11:41.798 UTC [653] LOG:  checkpoint starting: time
2024-11-14 08:11:42.885 UTC [653] LOG:  checkpoint complete: wrote 11 buffers (0.1%); 0 WAL file(s) added, 0 removed, 0 recycled; write=1.014 s, sync=0.029 s, total=1.088 s; sync files=11, longest=0.027 s, average=0.003 s; distance=36 kB, estimate=83 kB; lsn=0/2C964C0, redo lsn=0/2C96488
```

### Steps to reproduce

1.I don't know why this happens
2.
3.

### Describe the expected behavior

No errors

### Additional information

* PeerTube instance:
  * URL: https://angeltales.angellive.ru/
  * Version: 6.3.3
  * NodeJS version: v20.18.0
  * Ffmpeg version: ffmpeg version 6.1.1-3ubuntu5
  * Nginx 1.27
  * Postgres Ubuntu 16.4-0ubuntu0.24.04.2

* Browser name, version and platforms on which you could reproduce the bug:
* Link to browser console log if relevant:
* Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`):

**Comment by bestperson-free** [comment]
Greetings, this is all very strange, I did the following, reinstalled PeerTube, with Postgres 17 (latest version), at the moment there are no errors, I will follow further. In version 16 2 servers had the same serialization errors

**Comment by Chocobozzz** [comment]
Can you provide the exact postgresql version? And do you reproduce if you roll back to the previous postgresql version?

**Comment by bestperson-free** [comment]
mmmm the latest version was the one that is now in the Ubuntu repository 24.04, 16...., I have not tried to roll back since version 17.

**Comment by Chocobozzz** [comment]
Closing this issue then, but don't hesitate to comment if you experience this issue again.
