### ISSUE TITLE
Transcoding failed "Output format mp4 is not available" on NixOS 24.11

### ISSUE THREAD

**Issue by gianmarcogg03** [Chocobozzz/PeerTube#6748]
### Describe the current behavior

After upgrading my server to NixOS 24.05 to 24.11, Peertube now no longer transcodes videos. It fails with this error at every transcoding job:

```
error[12/1/2024, 8:00:15 PM] Cannot execute job b428e54f-cca4-4af4-84cd-15be16af90d3 in queue video-transcoding.

{
  "payload": {
    "type": "new-resolution-to-hls",
    "videoUUID": "49504a52-c62d-4ee7-82ca-f0bb37341abe",
    "resolution": 1440,
    "fps": 30,
    "copyCodecs": false,
    "isNewVideo": false,
    "deleteWebVideoFiles": false
  },
  "err": {
    "stack": "Error: Output format mp4 is not available\n    at /nix/store/cw2bvc33bpbhwqdf6zab69wixlva0p9a-peertube-6.0.4/node_modules/fluent-ffmpeg/lib/capabilities.js:589:21\n    at nextTask (/nix/store/cw2bvc33bpbhwqdf6zab69wixlva0p9a-peertube-6.0.4/node_modules/async/dist/async.js:5789:13)\n    at next (/nix/store/cw2bvc33bpbhwqdf6zab69wixlva0p9a-peertube-6.0.4/node_modules/async/dist/async.js:5797:13)\n    at /nix/store/cw2bvc33bpbhwqdf6zab69wixlva0p9a-peertube-6.0.4/node_modules/async/dist/async.js:327:20\n    at proto.availableFormats.proto.getAvailableFormats (/nix/store/cw2bvc33bpbhwqdf6zab69wixlva0p9a-peertube-6.0.4/node_modules/fluent-ffmpeg/lib/capabilities.js:513:14)\n    at /nix/store/cw2bvc33bpbhwqdf6zab69wixlva0p9a-peertube-6.0.4/node_modules/fluent-ffmpeg/lib/capabilities.js:568:14\n    at nextTask (/nix/store/cw2bvc33bpbhwqdf6zab69wixlva0p9a-peertube-6.0.4/node_modules/async/dist/async.js:5789:13)\n    at Object.waterfall (/nix/store/cw2bvc33bpbhwqdf6zab69wixlva0p9a-peertube-6.0.4/node_modules/async/dist/async.js:5800:9)\n    at Object.awaitable [as waterfall] (/nix/store/cw2bvc33bpbhwqdf6zab69wixlva0p9a-peertube-6.0.4/node_modules/async/dist/async.js:211:32)\n    at proto._checkCapabilities (/nix/store/cw2bvc33bpbhwqdf6zab69wixlva0p9a-peertube-6.0.4/node_modules/fluent-ffmpeg/lib/capabilities.js:565:11)\n    at /nix/store/cw2bvc33bpbhwqdf6zab69wixlva0p9a-peertube-6.0.4/node_modules/fluent-ffmpeg/lib/processor.js:298:14\n    at nextTask (/nix/store/cw2bvc33bpbhwqdf6zab69wixlva0p9a-peertube-6.0.4/node_modules/async/dist/async.js:5789:13)\n    at Object.waterfall (/nix/store/cw2bvc33bpbhwqdf6zab69wixlva0p9a-peertube-6.0.4/node_modules/async/dist/async.js:5800:9)\n    at Object.awaitable [as waterfall] (/nix/store/cw2bvc33bpbhwqdf6zab69wixlva0p9a-peertube-6.0.4/node_modules/async/dist/async.js:211:32)\n    at proto._prepare (/nix/store/cw2bvc33bpbhwqdf6zab69wixlva0p9a-peertube-6.0.4/node_modules/fluent-ffmpeg/lib/processor.js:295:11)\n    at proto.exec.proto.execute.proto.run (/nix/store/cw2bvc33bpbhwqdf6zab69wixlva0p9a-peertube-6.0.4/node_modules/fluent-ffmpeg/lib/processor.js:431:10)\n    at file:///nix/store/cw2bvc33bpbhwqdf6zab69wixlva0p9a-peertube-6.0.4/packages/ffmpeg/dist/ffmpeg-command-wrapper.js:73:26\n    at new Promise (<anonymous>)\n    at FFmpegCommandWrapper.runCommand (file:///nix/store/cw2bvc33bpbhwqdf6zab69wixlva0p9a-peertube-6.0.4/packages/ffmpeg/dist/ffmpeg-command-wrapper.js:45:16)\n    at FFmpegVOD.transcode (file:///nix/store/cw2bvc33bpbhwqdf6zab69wixlva0p9a-peertube-6.0.4/packages/ffmpeg/dist/ffmpeg-vod.js:33:35)\n    at async generateHlsPlaylistCommon (file:///nix/store/cw2bvc33bpbhwqdf6zab69wixlva0p9a-peertube-6.0.4/dist/core/lib/transcoding/hls-transcoding.js:90:5)\n    at async VideoPathManager.makeAvailableFactory (file:///nix/store/cw2bvc33bpbhwqdf6zab69wixlva0p9a-peertube-6.0.4/dist/core/lib/video-path-manager.js:84:22)\n    at async handleHLSJob (file:///nix/store/cw2bvc33bpbhwqdf6zab69wixlva0p9a-peertube-6.0.4/dist/core/lib/job-queue/handlers/video-transcoding.js:72:9)\n    at async Object.processVideoTranscoding [as video-transcoding] (file:///nix/store/cw2bvc33bpbhwqdf6zab69wixlva0p9a-peertube-6.0.4/dist/core/lib/job-queue/handlers/video-transcoding.js:34:9)\n    at async Object.wrapPromiseFun (file:///nix/store/cw2bvc33bpbhwqdf6zab69wixlva0p9a-peertube-6.0.4/dist/core/lib/plugins/hooks.js:8:24)\n    at async Worker.processJob (/nix/store/cw2bvc33bpbhwqdf6zab69wixlva0p9a-peertube-6.0.4/node_modules/bullmq/dist/cjs/classes/worker.js:350:28)\n    at async Worker.retryIfFailed (/nix/store/cw2bvc33bpbhwqdf6zab69wixlva0p9a-peertube-6.0.4/node_modules/bullmq/dist/cjs/classes/worker.js:535:24)",
    "message": "Output format mp4 is not available"
  }
}
```

### Steps to reproduce

1. Update from NixOS 24.05 to 24.11
2. Transcode a video

### Describe the expected behavior

Transcoding should work.

### Additional information

* PeerTube instance:
  * URL: https://videos.gianmarco.gg
  * Version: 6.0.4
  * Ffmpeg version: 7.1

**Comment by gianmarcogg03** [comment]
Doing `ffmpeg -formats | grep mp4` says I've got it, it's `ffmpeg-full`.

**Comment by Chocobozzz** [comment]
Sorry, I didn't see your peertube version. Upgrading to latest (6.3) will fix your issue
