### ISSUE TITLE
uncaughtException: self-signed certificate

### ISSUE THREAD

**Issue by polykit** [Chocobozzz/PeerTube#6779]
### Describe the current behavior

The site is crashing with error message `uncaughtException: self-signed certificate`. I had this before but now it happens quite regularly. I disabled all plugins but the problem still exists.
I added some debug logging. The exception is at the end of the logs to add some context of the error.

### Steps to reproduce

1. Start Peertube
2. Wait for some time
3. Peertube exits with exception error

### Describe the expected behavior

Error is validated or exception caught.

### Additional information

* PeerTube instance:
  * URL: https://makertube.net
  * Version: v6.3.3
  * NodeJS version: v18.20.4
  * Ffmpeg version:

* Browser name, version and platforms on which you could reproduce the bug: Upstream docker image
* Link to browser console log if relevant:

**Comment by Chocobozzz** [comment]
Hi,

Seems related to object storage, but it's weird :thinking: 
Do you use an out proxy (``HTTP_PROXY`/`HTTPS_PROXY` env) ?

**Comment by polykit** [comment]
Hi @Chocobozzz ,
thanks for the reply! Good pointer, I'm using a local proxy especially for Youtube synchronization. Maybe traffic gets somehow messed up there.

**Comment by polykit** [comment]
I removed the proxy env vars and it's still crashing.

**Comment by Chocobozzz** [comment]
With the exact same error?

**Comment by polykit** [comment]
Now there is an error related to the object storage:
```
[makertube.net:443] 2025-01-10 15:19:58.755 error: uncaughtException: char '4' is not expected.:1:1
  Deserialization error: to see the raw response, inspect the hidden field {error}.$response on this object.
Error: char '4' is not expected.:1:1
  Deserialization error: to see the raw response, inspect the hidden field {error}.$response on this object.
    at XMLParser.parse (/app/node_modules/fast-xml-parser/src/xmlparser/XMLParser.js:30:21)
    at /app/node_modules/@aws-sdk/core/dist-cjs/submodules/protocols/index.js:177:26
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async parseXmlErrorBody (/app/node_modules/@aws-sdk/core/dist-cjs/submodules/protocols/index.js:198:17)
    at async de_CommandError (/app/node_modules/@aws-sdk/client-s3/dist-cjs/index.js:4716:11)
    at async /app/node_modules/@smithy/middleware-serde/dist-cjs/index.js:35:20
    at async /app/node_modules/@aws-sdk/middleware-sdk-s3/dist-cjs/index.js:482:18
    at async /app/node_modules/@smithy/middleware-retry/dist-cjs/index.js:320:38
    at async /app/node_modules/@aws-sdk/middleware-sdk-s3/dist-cjs/index.js:110:22
    at async /app/node_modules/@aws-sdk/middleware-sdk-s3/dist-cjs/index.js:138:14
    at async /app/node_modules/@aws-sdk/middleware-logger/dist-cjs/index.js:34:22
    at async _Upload.__doConcurrentUpload (/app/node_modules/@aws-sdk/lib-storage/dist-cjs/index.js:313:30)
    at async Promise.all (index 0)
    at async _Upload.__doMultipartUpload (/app/node_modules/@aws-sdk/lib-storage/dist-cjs/index.js:395:5)
    at async _Upload.done (/app/node_modules/@aws-sdk/lib-storage/dist-cjs/index.js:213:12)
    at async uploadToStorage (file:///app/dist/core/lib/object-storage/object-storage-helpers.js:173:22) {
  "error": {
    "stack": "Error: char '4' is not expected.:1:1\n  Deserialization error: to see the raw response, inspect the hidden field {error}.$response on this object.\n    at XMLParser.parse (/app/node_modules/fast-xml-parser/src/xmlparser/XMLParser.js:30:21)\n    at /app/node_modules/@aws-sdk/core/dist-cjs/submodules/protocols/index.js:177:26\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async parseXmlErrorBody (/app/node_modules/@aws-sdk/core/dist-cjs/submodules/protocols/index.js:198:17)\n    at async de_CommandError (/app/node_modules/@aws-sdk/client-s3/dist-cjs/index.js:4716:11)\n    at async /app/node_modules/@smithy/middleware-serde/dist-cjs/index.js:35:20\n    at async /app/node_modules/@aws-sdk/middleware-sdk-s3/dist-cjs/index.js:482:18\n    at async /app/node_modules/@smithy/middleware-retry/dist-cjs/index.js:320:38\n    at async /app/node_modules/@aws-sdk/middleware-sdk-s3/dist-cjs/index.js:110:22\n    at async /app/node_modules/@aws-sdk/middleware-sdk-s3/dist-cjs/index.js:138:14\n    at async /app/node_modules/@aws-sdk/middleware-logger/dist-cjs/index.js:34:22\n    at async _Upload.__doConcurrentUpload (/app/node_modules/@aws-sdk/lib-storage/dist-cjs/index.js:313:30)\n    at async Promise.all (index 0)\n    at async _Upload.__doMultipartUpload (/app/node_modules/@aws-sdk/lib-storage/dist-cjs/index.js:395:5)\n    at async _Upload.done (/app/node_modules/@aws-sdk/lib-storage/dist-cjs/index.js:213:12)\n    at async uploadToStorage (file:///app/dist/core/lib/object-storage/object-storage-helpers.js:173:22)",
    "message": "char '4' is not expected.:1:1\n  Deserialization error: to see the raw response, inspect the hidden field {error}.$response on this object.",
    "$responseBodyText": "404 page not found\n",
    "$response": {
      "statusCode": 404,
      "reason": "Not Found",
      "headers": {
        "content-type": "text/plain; charset=utf-8",
        "x-content-type-options": "nosniff",
        "date": "Fri, 10 Jan 2025 15:19:47 GMT",
        "content-length": "19"
      },
      "body": "404 page not found\n"
    },
    "$metadata": {
      "attempts": 1,
      "totalRetryDelay": 0
    }
  },
  "stack": "Error: char '4' is not expected.:1:1\n  Deserialization error: to see the raw response, inspect the hidden field {error}.$response on this object.\n    at XMLParser.parse (/app/node_modules/fast-xml-parser/src/xmlparser/XMLParser.js:30:21)\n    at /app/node_modules/@aws-sdk/core/dist-cjs/submodules/protocols/index.js:177:26\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async parseXmlErrorBody (/app/node_modules/@aws-sdk/core/dist-cjs/submodules/protocols/index.js:198:17)\n    at async de_CommandError (/app/node_modules/@aws-sdk/client-s3/dist-cjs/index.js:4716:11)\n    at async /app/node_modules/@smithy/middleware-serde/dist-cjs/index.js:35:20\n    at async /app/node_modules/@aws-sdk/middleware-sdk-s3/dist-cjs/index.js:482:18\n    at async /app/node_modules/@smithy/middleware-retry/dist-cjs/index.js:320:38\n    at async /app/node_modules/@aws-sdk/middleware-sdk-s3/dist-cjs/index.js:110:22\n    at async /app/node_modules/@aws-sdk/middleware-sdk-s3/dist-cjs/index.js:138:14\n    at async /app/node_modules/@aws-sdk/middleware-logger/dist-cjs/index.js:34:22\n    at async _Upload.__doConcurrentUpload (/app/node_modules/@aws-sdk/lib-storage/dist-cjs/index.js:313:30)\n    at async Promise.all (index 0)\n    at async _Upload.__doMultipartUpload (/app/node_modules/@aws-sdk/lib-storage/dist-cjs/index.js:395:5)\n    at async _Upload.done (/app/node_modules/@aws-sdk/lib-storage/dist-cjs/index.js:213:12)\n    at async uploadToStorage (file:///app/dist/core/lib/object-storage/object-storage-helpers.js:173:22)",
  "exception": true,
  "date": "Fri Jan 10 2025 15:19:58 GMT+0000 (Coordinated Universal Time)",
  "process": {
    "pid": 1,
    "uid": 999,
    "gid": 999,
    "cwd": "/app",
    "execPath": "/usr/local/bin/node",
    "version": "v18.20.4",
    "argv": [
      "/usr/local/bin/node",
      "/app/dist/server"
    ],
    "memoryUsage": {
      "rss": 937050112,
      "heapTotal": 166834176,
      "heapUsed": 119354000,
      "external": 546281074,
      "arrayBuffers": 526110613
    }
  },
  "os": {
    "loadavg": [
      1.82,
      2.01,
      2.04
    ],
    "uptime": 7156572.69
  },
  "trace": [
    {
      "column": 21,
      "file": "/app/node_modules/fast-xml-parser/src/xmlparser/XMLParser.js",
      "function": "XMLParser.parse",
      "line": 30,
      "method": "parse",
      "native": false
    },
    {
      "column": 26,
      "file": "/app/node_modules/@aws-sdk/core/dist-cjs/submodules/protocols/index.js",
      "function": null,
      "line": 177,
      "method": null,
      "native": false
    },
    {
      "column": 5,
      "file": "node:internal/process/task_queues",
      "function": "process.processTicksAndRejections",
      "line": 95,
      "method": "processTicksAndRejections",
      "native": false
    },
    {
      "column": 17,
      "file": "/app/node_modules/@aws-sdk/core/dist-cjs/submodules/protocols/index.js",
      "function": "async parseXmlErrorBody",
      "line": 198,
      "method": null,
      "native": false
    },
    {
      "column": 11,
      "file": "/app/node_modules/@aws-sdk/client-s3/dist-cjs/index.js",
      "function": "async de_CommandError",
      "line": 4716,
      "method": null,
      "native": false
    },
    {
      "column": 20,
      "file": "async /app/node_modules/@smithy/middleware-serde/dist-cjs/index.js",
      "function": null,
      "line": 35,
      "method": null,
      "native": false
    },
    {
      "column": 18,
      "file": "async /app/node_modules/@aws-sdk/middleware-sdk-s3/dist-cjs/index.js",
      "function": null,
      "line": 482,
      "method": null,
      "native": false
    },
    {
      "column": 38,
      "file": "async /app/node_modules/@smithy/middleware-retry/dist-cjs/index.js",
      "function": null,
      "line": 320,
      "method": null,
      "native": false
    },
    {
      "column": 22,
      "file": "async /app/node_modules/@aws-sdk/middleware-sdk-s3/dist-cjs/index.js",
      "function": null,
      "line": 110,
      "method": null,
      "native": false
    },
    {
      "column": 14,
      "file": "async /app/node_modules/@aws-sdk/middleware-sdk-s3/dist-cjs/index.js",
      "function": null,
      "line": 138,
      "method": null,
      "native": false
    },
    {
      "column": 22,
      "file": "async /app/node_modules/@aws-sdk/middleware-logger/dist-cjs/index.js",
      "function": null,
      "line": 34,
      "method": null,
      "native": false
    },
    {
      "column": 30,
      "file": "/app/node_modules/@aws-sdk/lib-storage/dist-cjs/index.js",
      "function": "async _Upload.__doConcurrentUpload",
      "line": 313,
      "method": "__doConcurrentUpload",
      "native": false
    },
    {
      "column": null,
      "file": null,
      "function": "async Promise.all",
      "line": null,
      "method": "all",
      "native": false
    },
    {
      "column": 5,
      "file": "/app/node_modules/@aws-sdk/lib-storage/dist-cjs/index.js",
      "function": "async _Upload.__doMultipartUpload",
      "line": 395,
      "method": "__doMultipartUpload",
      "native": false
    },
    {
      "column": 12,
      "file": "/app/node_modules/@aws-sdk/lib-storage/dist-cjs/index.js",
      "function": "async _Upload.done",
      "line": 213,
      "method": "done",
      "native": false
    },
    {
      "column": 22,
      "file": "file:///app/dist/core/lib/object-storage/object-storage-helpers.js",
      "function": "async uploadToStorage",
      "line": 173,
      "method": null,
      "native": false
    }
  ]
}
```

**Comment by Chocobozzz** [comment]
Can you paste logs above the error so I can get more context?

**Comment by polykit** [comment]
If have the original problem with the self-signed certificate error again. It seems that it occurs when someone is requesting an export archive on their account.

**Comment by Chocobozzz** [comment]
Ping @polykit :)
