### ISSUE TITLE
Federation IPv6

### ISSUE THREAD

**Issue by RJGhugo** [Chocobozzz/PeerTube#6794]
### Describe the current behavior

Peertube 7.x does not federate with IPv4 only instances. IPv6 instances are working. NAT64 activated.

### Steps to reproduce

ACTIVITYPUB-HTTP-UNICAST - FAILED

### Describe the expected behavior

`Job: 1`
`Type: activitypub-http-unicast`
`Processed on 23.12.24, 10:03:55,795`
`Finished on 23.12.24, 10:03:57,298`
``
`{`
`  "uri": "https://tilvids.com/video-channels/thelinuxexperiment_channel/inbox",`
`  "signatureActorId": 1,`
`  "body": {`
`    "type": "Follow",`
`    "id": "https://peertube.xxxx.xxx/accounts/peertube/follows/192",`
`    "actor": "https://peertube.xxxx.xxx/accounts/peertube",`
`    "object": "https://tilvids.com/video-channels/thelinuxexperiment_channel"`
`  },`
`  "contextType": "Follow"`
`}`
``
`HTTPError: Response code 403 (Forbidden)`
`    at Request.<anonymous> (file:///app/node_modules/got/dist/source/as-promise/index.js:86:42)`
`    at Object.onceWrapper (node:events:632:26)`
`    at Request.emit (node:events:529:35)`
`    at Request._onResponseBase (file:///app/node_modules/got/dist/source/core/index.js:726:22)`
`    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)`
`    at async Request._onResponse (file:///app/node_modules/got/dist/source/core/index.js:768:13)`
``
`---`    
``    
`Job: 37`
`Type: activitypub-http-unicast`
`Processed on 28.12.24, 03:06:20,401`
`Finished on 28.12.24, 03:06:27,421`
``
`{`
`  "uri": "https://tilvids.com/video-channels/thelinuxexperiment_channel/inbox",`
`  "signatureActorId": 6,`
`  "body": {`
`    "type": "Follow",`
`    "id": "https://peertube.xxxx.xxx/accounts/benutzer/follows/192",`
`    "actor": "https://peertube.xxxx.xxx/accounts/benutzer",`
`    "object": "https://tilvids.com/video-channels/thelinuxexperiment_channel"`
`  },`
`  "contextType": "Follow"`
`}`
``
`RequestError: Timeout awaiting 'request' for 7000ms`
`    at ClientRequest.<anonymous> (file:///app/node_modules/got/dist/source/core/index.js:792:61)`
`    at Object.onceWrapper (node:events:632:26)`
`    at ClientRequest.emit (node:events:529:35)`
`    at TLSSocket.socketErrorListener (node:_http_client:501:9)`
`    at TLSSocket.emit (node:events:517:28)`
`    at emitErrorNT (node:internal/streams/destroy:151:8)`
`    at emitErrorCloseNT (node:internal/streams/destroy:116:3)`
`    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)`
`    at Timeout.timeoutHandler [as _onTimeout] (file:///app/node_modules/got/dist/source/core/timed-out.js:42:25)`
`    at listOnTimeout (node:internal/timers:571:11)`
`    at process.processTimers (node:internal/timers:512:7)`
``    
`---`
``
`Job: 34`
`Type: activitypub-http-fetcher`
`Processed on 28.12.24, 03:06:27,878`
`Finished on 28.12.24, 03:06:36,830`
``
`{`
`  "uri": "https://tilvids.com/video-channels/thelinuxexperiment_channel/outbox",`
`  "type": "activity"`
`}`

### Additional information

Peertube 7.x

**Comment by Chocobozzz** [comment]
Hello,

I think it's a network issue on your peertube instance with `NAT64` because I can't reproduce :thinking:

**Comment by RJGhugo** [comment]
Thanks for responding.

Mastodon needs the following configuration: **ALLOWED_PRIVATE_ADDRESSES: 64:ff9b::/96** to allow NAT64...

**Comment by Chocobozzz** [comment]
Please create a topic on the forum https://framacolibri.org/c/peertube so we can try to debug this :)

**Comment by RJGhugo** [comment]
Thanks @Chocobozzz ,

It works now!

1. deleted every federation
2. add every federation again

https://framacolibri.org/t/federation-ipv6/24166
