### ISSUE TITLE
Help installing Peertube with docker-compose

### ISSUE THREAD

**Issue by usbsnowcrash** [Chocobozzz/PeerTube#688]
* **PeerTube version or URL:**
1.0-beta-8
* **What is the expected behaviour?**
I am trying to install peertube but for some reason it will not start. All it tells me is that it cannot start application.  I have attached my .env, my docker-compose and the logs in the following gist
https://gist.github.com/usbsnowcrash/85f8b6be38c3eb01021fa356858c09e9

```
peertube_1  | 2018-06-20T23:57:45.901923455Z [betamax.video:443] 2018-06-20 23:57:45.899 info: Database peertube is ready.
peertube_1  | 2018-06-20T23:57:46.118692777Z [betamax.video:443] 2018-06-20 23:57:46.118 info: Creating the administrator.
peertube_1  | 2018-06-20T23:57:46.146014736Z [betamax.video:443] 2018-06-20 23:57:46.145 error: Cannot install application. {
peertube_1  | 2018-06-20T23:57:46.146094411Z   "err": "SequelizeValidationError: notNull Violation: UserModel.email cannot be null\n    at Promise.all.then (/app/node_modules/sequelize/lib/instance-validator.js:77:15)\n    at tryCatcher (/app/node_modules/bluebird/js/release/util.js:16:23)\n    at Promise._settlePromiseFromHandler (/app/node_modules/bluebird/js/release/promise.js:512:31)\n    at Promise._settlePromise (/app/node_modules/bluebird/js/release/promise.js:569:18)\n    at Promise._settlePromise0 (/app/node_modules/bluebird/js/release/promise.js:614:10)\n    at Promise._settlePromises (/app/node_modules/bluebird/js/release/promise.js:693:18)\n    at Promise._fulfill (/app/node_modules/bluebird/js/release/promise.js:638:18)\n    at PromiseArray._resolve (/app/node_modules/bluebird/js/release/promise_array.js:126:19)\n    at PromiseArray._promiseFulfilled (/app/node_modules/bluebird/js/release/promise_array.js:144:14)\n    at Promise._settlePromise (/app/node_modules/bluebird/js/release/promise.js:574:26)\n    at Promise._settlePromise0 (/app/node_modules/bluebird/js/release/promise.js:614:10)\n    at Promise._settlePromises (/app/node_modules/bluebird/js/release/promise.js:693:18)\n    at Promise._fulfill (/app/node_modules/bluebird/js/release/promise.js:638:18)\n    at Promise._resolveCallback (/app/node_modules/bluebird/js/release/promise.js:432:57)\n    at Promise._settlePromiseFromHandler (/app/node_modules/bluebird/js/release/promise.js:524:17)\n    at Promise._settlePromise (/app/node_modules/bluebird/js/release/promise.js:569:18)\n    at Promise._settlePromise0 (/app/node_modules/bluebird/js/release/promise.js:614:10)\n    at Promise._settlePromises (/app/node_modules/bluebird/js/release/promise.js:693:18)\n    at Promise._fulfill (/app/node_modules/bluebird/js/release/promise.js:638:18)\n    at PromiseArray._resolve (/app/node_modules/bluebird/js/release/promise_array.js:126:19)\n    at PromiseArray._promiseFulfilled (/app/node_modules/bluebird/js/release/promise_array.js:144:14)\n    at Promise._settlePromise (/app/node_modules/bluebird/js/release/promise.js:574:26)\n    at Promise._settlePromise0 (/app/node_modules/bluebird/js/release/promise.js:614:10)\n    at Promise._settlePromises (/app/node_modules/bluebird/js/release/promise.js:693:18)\n    at Promise._fulfill (/app/node_modules/bluebird/js/release/promise.js:638:18)\n    at Promise._resolveCallback (/app/node_modules/bluebird/js/release/promise.js:432:57)\n    at Promise._settlePromiseFromHandler (/app/node_modules/bluebird/js/release/promise.js:524:17)\n    at Promise._settlePromise (/app/node_modules/bluebird/js/release/promise.js:569:18)\n    at Promise._settlePromise0 (/app/node_modules/bluebird/js/release/promise.js:614:10)\n    at Promise._settlePromises (/app/node_modules/bluebird/js/release/promise.js:693:18)\n    at Promise._fulfill (/app/node_modules/bluebird/js/release/promise.js:638:18)\n    at Promise._resolveCallback (/app/node_modules/bluebird/js/release/promise.js:432:57)\n    at Promise._settlePromiseFromHandler (/app/node_modules/bluebird/js/release/promise.js:524:17)\n    at Promise._settlePromise (/app/node_modules/bluebird/js/release/promise.js:569:18)\n    at Promise._settlePromise0 (/app/node_modules/bluebird/js/release/promise.js:614:10)\n    at Promise._settlePromises (/app/node_modules/bluebird/js/release/promise.js:693:18)\n    at Promise._fulfill (/app/node_modules/bluebird/js/release/promise.js:638:18)\n    at PromiseArray._resolve (/app/node_modules/bluebird/js/release/promise_array.js:126:19)\n    at PromiseArray._promiseFulfilled (/app/node_modules/bluebird/js/release/promise_array.js:144:14)\n    at Promise._settlePromise (/app/node_modules/bluebird/js/release/promise.js:574:26)"
peertube_1  | 2018-06-20T23:57:46.146153775Z }
peertube_1  | 2018-06-20T23:57:46.166220105Z npm ERR! code ELIFECYCLE
peertube_1  | 2018-06-20T23:57:46.166567389Z npm ERR! errno 255
peertube_1  | 2018-06-20T23:57:46.169020296Z npm ERR! peertube@1.0.0-beta.8 start: `node dist/server`
peertube_1  | 2018-06-20T23:57:46.169149063Z npm ERR! Exit status 255
peertube_1  | 2018-06-20T23:57:46.169353605Z npm ERR!
peertube_1  | 2018-06-20T23:57:46.169466389Z npm ERR! Failed at the peertube@1.0.0-beta.8 start script.
peertube_1  | 2018-06-20T23:57:46.169567503Z npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```
I am building my own docker-image from source (using this tag v1.0.0-beta.8).  I am at a loss as to how to debug this and I followed the docker guide to the best of my ability.  Please help!

**Comment by Chocobozzz** [comment]
Sorry! Please try this patch: https://github.com/Chocobozzz/PeerTube/commit/6387f320bf10f6b6c90b338bded8d7392dead18a

**Comment by usbsnowcrash** [comment]
@Chocobozzz This fixed my issue!  Thanks for the quick help!
