### ISSUE TITLE
There are troubles when upgrade to newest version

### ISSUE THREAD

**Issue by imtube** [Chocobozzz/PeerTube#69]
Hello,
I met errors when I upgraded to newest version, the version I'm using now is before Jan 13. the nodejs version I'm using is 8.0.0

the errors I met are :
```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'run',
1 verbose cli   'webpack',
1 verbose cli   '--',
1 verbose cli   '--config',
1 verbose cli   'config/webpack.prod.js',
1 verbose cli   '--progress',
1 verbose cli   '--profile',
1 verbose cli   '--bail' ]
2 info using npm@5.0.0
3 info using node@v8.0.0
4 verbose run-script [ 'prewebpack', 'webpack', 'postwebpack' ]
5 info lifecycle peertube-client@0.0.1~prewebpack: peertube-client@0.0.1
6 silly lifecycle peertube-client@0.0.1~prewebpack: no script for prewebpack, continuing
7 info lifecycle peertube-client@0.0.1~webpack: peertube-client@0.0.1
8 verbose lifecycle peertube-client@0.0.1~webpack: unsafe-perm in lifecycle true
9 verbose lifecycle peertube-client@0.0.1~webpack: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/home/peertube/PeerTube/client/node_modules/.bin:/usr/local/lib/node_modules/npm/bin/node-gyp-bin:/home/peertube/PeerTube/node_modules/.bin:/usr/local/lib/node_modules/npm/bin/node-gyp-bin:/home/peertube/PeerTube/node_modules/.bin:/usr/local/lib/node_modules/npm/bin/node-gyp-bin:/home/peertube/PeerTube/node_modules/.bin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games
10 verbose lifecycle peertube-client@0.0.1~webpack: CWD: /home/peertube/PeerTube/client
11 silly lifecycle peertube-client@0.0.1~webpack: Args: [ '-c',
11 silly lifecycle   'webpack "--config" "config/webpack.prod.js" "--progress" "--profile" "--bail"' ]
12 silly lifecycle peertube-client@0.0.1~webpack: Returned: code: 2  signal: null
13 info lifecycle peertube-client@0.0.1~webpack: Failed to exec webpack script
14 verbose stack Error: peertube-client@0.0.1 webpack: `webpack "--config" "config/webpack.prod.js" "--progress" "--profile" "--bail"`
14 verbose stack Exit status 2
14 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:283:16)
14 verbose stack     at emitTwo (events.js:125:13)
14 verbose stack     at EventEmitter.emit (events.js:213:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:125:13)
14 verbose stack     at ChildProcess.emit (events.js:213:7)
14 verbose stack     at maybeClose (internal/child_process.js:887:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:208:5)
15 verbose pkgid peertube-client@0.0.1
16 verbose cwd /home/peertube/PeerTube/client
17 verbose Linux 4.9.0-040900rc8-generic
18 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "webpack" "--" "--config" "config/webpack.prod.js" "--progress" "--profile" "--bail"
19 verbose node v8.0.0
20 verbose npm  v5.0.0
21 error code ELIFECYCLE
22 error errno 2
23 error peertube-client@0.0.1 webpack: `webpack "--config" "config/webpack.prod.js" "--progress" "--profile" "--bail"`
23 error Exit status 2
24 error Failed at the peertube-client@0.0.1 webpack script.
24 error This is probably not a problem with npm. There is likely additional logging output above.
25 verbose exit [ 2, true ]
```

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'run', 'build' ]
2 info using npm@5.0.0
3 info using node@v8.0.0
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle peertube@0.0.1~prebuild: peertube@0.0.1
6 silly lifecycle peertube@0.0.1~prebuild: no script for prebuild, continuing
7 info lifecycle peertube@0.0.1~build: peertube@0.0.1
8 verbose lifecycle peertube@0.0.1~build: unsafe-perm in lifecycle true
9 verbose lifecycle peertube@0.0.1~build: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/home/peertube/PeerTube/node_modules/.bin:/usr/local/lib/node_modules/npm/bin/node-gyp-bin:/home/peertube/PeerTube/node_modules/.bin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games
10 verbose lifecycle peertube@0.0.1~build: CWD: /home/peertube/PeerTube
11 silly lifecycle peertube@0.0.1~build: Args: [ '-c', 'npm run build:client:prod' ]
12 silly lifecycle peertube@0.0.1~build: Returned: code: 1  signal: null
13 info lifecycle peertube@0.0.1~build: Failed to exec build script
14 verbose stack Error: peertube@0.0.1 build: `npm run build:client:prod`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:283:16)
14 verbose stack     at emitTwo (events.js:125:13)
14 verbose stack     at EventEmitter.emit (events.js:213:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:125:13)
14 verbose stack     at ChildProcess.emit (events.js:213:7)
14 verbose stack     at maybeClose (internal/child_process.js:887:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:208:5)
15 verbose pkgid peertube@0.0.1
16 verbose cwd /home/peertube/PeerTube
17 verbose Linux 4.9.0-040900rc8-generic
18 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "build"
19 verbose node v8.0.0
20 verbose npm  v5.0.0
21 error code ELIFECYCLE
22 error errno 1
23 error peertube@0.0.1 build: `npm run build:client:prod`
23 error Exit status 1
24 error Failed at the peertube@0.0.1 build script.
24 error This is probably not a problem with npm. There is likely additional logging output above.
25 verbose exit [ 1, true ]
```

**Comment by imtube** [comment]
I tried to install the newest version as your wiki guide, and met some errors too

My nginx configuration file is in directory "/usr/local/nginx/conf/vhost", so I didn't do the webserver part.

The error is:
```

~# systemd daemon-reload
Excess arguments.
~# systemctl start peertube
~# journalctl -feu peertube
-- Logs begin at Wed 2017-06-07 08:08:58 CST. --
Jun 08 00:07:28 xxx.com systemd[1]: Starting PeerTube daemon...
Jun 08 00:07:28 xxx.com systemd[1]: Started PeerTube daemon.
Jun 08 00:07:28 xxx.com systemd[1]: peertube.service: main process exited, c                                                                                                                                                             ode=exited, status=217/USER
Jun 08 00:07:28 xxx.com systemd[1]: Unit peertube.service entered failed sta                                                                                                                                                             te.
Jun 08 00:07:28 xxx.com systemd[1]: peertube.service holdoff time over, sche                                                                                                                                                             duling restart.
Jun 08 00:07:28 xxx.com systemd[1]: Stopping PeerTube daemon...
Jun 08 00:07:28 xxx.com systemd[1]: Starting PeerTube daemon...
Jun 08 00:07:28 xxx.com systemd[1]: Started PeerTube daemon.
Jun 08 00:07:28 xxx.com systemd[1]: peertube.service: main process exited, c                                                                                                                                                             ode=exited, status=217/USER
Jun 08 00:07:28 xxx.com systemd[1]: Unit peertube.service entered failed sta                                                                                                                                                             te.
Jun 08 00:07:28 xxx.com systemd[1]: peertube.service holdoff time over, sche                                                                                                                                                             duling restart.
Jun 08 00:07:28 xxx.com systemd[1]: Stopping PeerTube daemon...
Jun 08 00:07:28 xxx.com systemd[1]: Starting PeerTube daemon...
Jun 08 00:07:28 xxx.com systemd[1]: Started PeerTube daemon.
Jun 08 00:07:28 xxx.com systemd[1]: peertube.service: main process exited, c                                                                                                                                                             ode=exited, status=217/USER
Jun 08 00:07:28 xxx.com systemd[1]: Unit peertube.service entered failed sta                                                                                                                                                             te.
Jun 08 00:07:28 xxx.com systemd[1]: peertube.service holdoff time over, sche                                                                                                                                                             duling restart.
Jun 08 00:07:28 xxx.com systemd[1]: Stopping PeerTube daemon...
Jun 08 00:07:28 xxx.com systemd[1]: Starting PeerTube daemon...
Jun 08 00:07:28 xxx.com systemd[1]: Started PeerTube daemon.
Jun 08 00:07:28 xxx.com systemd[1]: peertube.service: main process exited, c                                                                                                                                                             ode=exited, status=217/USER
Jun 08 00:07:28 xxx.com systemd[1]: Unit peertube.service entered failed sta                                                                                                                                                             te.
Jun 08 00:07:29 xxx.com systemd[1]: peertube.service holdoff time over, sche                                                                                                                                                             duling restart.
Jun 08 00:07:29 xxx.com systemd[1]: Stopping PeerTube daemon...
Jun 08 00:07:29 xxx.com systemd[1]: Starting PeerTube daemon...
Jun 08 00:07:29 xxx.com systemd[1]: Started PeerTube daemon.
Jun 08 00:07:29 xxx.com systemd[1]: peertube.service: main process exited, c                                                                                                                                                             ode=exited, status=217/USER
Jun 08 00:07:29 xxx.com systemd[1]: Unit peertube.service entered failed sta                                                                                                                                                             te.
Jun 08 00:07:29 xxx.com systemd[1]: peertube.service holdoff time over, sche                                                                                                                                                             duling restart.
Jun 08 00:07:29 xxx.com systemd[1]: Stopping PeerTube daemon...
Jun 08 00:07:29 xxx.com systemd[1]: Starting PeerTube daemon...
Jun 08 00:07:29 xxx.com systemd[1]: peertube.service start request repeated                                                                                                                                                              too quickly, refusing to start.
Jun 08 00:07:29 xxx.com systemd[1]: Failed to start PeerTube daemon.
Jun 08 00:07:29 xxx.com systemd[1]: Unit peertube.service entered failed sta                                                                                                                                                             te.

```

**Comment by imtube** [comment]
I didn't use the command `journalctl -feu peertube`
I used the command `NODE_ENV=production npm start`
First time , it worked, but after I rebooted my server, it can't work, when I run command `NODE_ENV=production npm start`, it shows some errors:
```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'start' ]
2 info using npm@5.0.0
3 info using node@v8.0.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle peertube@0.0.1~prestart: peertube@0.0.1
6 silly lifecycle peertube@0.0.1~prestart: no script for prestart, continuing
7 info lifecycle peertube@0.0.1~start: peertube@0.0.1
8 verbose lifecycle peertube@0.0.1~start: unsafe-perm in lifecycle true
9 verbose lifecycle peertube@0.0.1~start: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/home/peertube/PeerTube/node_modules/.bin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games
10 verbose lifecycle peertube@0.0.1~start: CWD: /home/peertube/PeerTube
11 silly lifecycle peertube@0.0.1~start: Args: [ '-c', 'node server' ]
12 silly lifecycle peertube@0.0.1~start: Returned: code: 1  signal: null
13 info lifecycle peertube@0.0.1~start: Failed to exec start script
14 verbose stack Error: peertube@0.0.1 start: `node server`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:283:16)
14 verbose stack     at emitTwo (events.js:125:13)
14 verbose stack     at EventEmitter.emit (events.js:213:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:125:13)
14 verbose stack     at ChildProcess.emit (events.js:213:7)
14 verbose stack     at maybeClose (internal/child_process.js:887:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:208:5)
15 verbose pkgid peertube@0.0.1
16 verbose cwd /home/peertube/PeerTube
17 verbose Linux 4.9.0-040900rc8-generic
18 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
19 verbose node v8.0.0
20 verbose npm  v5.0.0
21 error code ELIFECYCLE
22 error errno 1
23 error peertube@0.0.1 start: `node server`
23 error Exit status 1
24 error Failed at the peertube@0.0.1 start script.
24 error This is probably not a problem with npm. There is likely additional logging output above.
25 verbose exit [ 1, true ]

```
