### ISSUE TITLE
Missing sharp module after upgrade to peertube beta 8

### ISSUE THREAD

**Issue by jocelynj** [Chocobozzz/PeerTube#696]
* **PeerTube version or URL:** peertube-v1.0.0-beta.8
* **Server distribution:** Debian GNU/Linux 9.4 (stretch)
* **NodeJS version:** v9.11.2 
* **NPM version:** 5.6.0

I can't start peertube since I've upgraded to version beta 8.
```
Jun 21 18:59:18 osm155 systemd[1]: Started PeerTube daemon.
Jun 21 18:59:18 osm155 peertube[732675]: > peertube@1.0.0-beta.8 start /data/project/peertube/versions/peertube-v1.0.0-beta.8
Jun 21 18:59:18 osm155 peertube[732675]: > node dist/server
Jun 21 18:59:19 osm155 peertube[732675]: [peertube.openstreetmap.fr:443] 2018-06-21 18:59:19.485 #033[31merror#033[39m: uncaughtException: Cannot find module '../build/Release/sharp.node'
Jun 21 18:59:19 osm155 peertube[732675]: Error: Cannot find module '../build/Release/sharp.node'
Jun 21 18:59:19 osm155 peertube[732675]:     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:548:15)
Jun 21 18:59:19 osm155 peertube[732675]:     at Function.Module._load (internal/modules/cjs/loader.js:475:25)
```

I've launched the following commands already:
```
yarn install --production --pure-lockfile
NODE_CONFIG_DIR=/data/project/peertube/config/ NODE_ENV=production npm install
```

Is it a new dependency that I should install ?

**Comment by Chocobozzz** [comment]
Hi,

Remove node_modules, and retry:

```
$ yarn install --production --pure-lockfile
```

Please keep the output of the yarn command, maybe sharp has building issues

**Comment by jocelynj** [comment]
sharp did compile correctly, after launching the following commands:
```
cd peertube-latest
yarn install --production --pure-lockfile
NODE_CONFIG_DIR=/data/project/peertube/config/ NODE_ENV=production npm install
```

Now, starting peertube gives another error:
```
/usr/bin/npm start
npm ERR! code ELIFECYCLE
npm ERR! errno 255
npm ERR! peertube@1.0.0-beta.8 start: `node dist/server`
npm ERR! Exit status 255
```

Manually launching `node dist/server` also give $?=255. Is there any log or debug option to add to investigate the issue ?

**Comment by Chocobozzz** [comment]
You must not use npm install, you just have to use yarn.

You don't use systemd? I would need the logs to investigate. And it's NODE_CONFIG_DIR=/data/project/peertube/config/ NODE_ENV=production npm start to run peertube
