### ISSUE TITLE
PeerTube won't work with fullchain certificate from Let's Encrypt

### ISSUE THREAD

**Issue by KRtekTM** [Chocobozzz/PeerTube#786]
* **PeerTube version or URL:** v1.0.0-beta.9
* **Browser name/version:** Waterfox 56.2.0
* **NodeJS version:** 8.11.3

* **What is the expected behaviour?** Let's Encrypt fullchain certificate can be used with PeerTube so the instance is reachable for https://instances.joinpeertube.org/instances or other instances.
* **What do you see instead?** "Invalid token" shown after fullchain certificate is selected. When only server certificate is attached, instance is working but can't be added to Instances list (due to issue with first certificate) and maybe because of that - magnet torrent is not working (download via torrent file works ok).

* **Browser console log if useful (Gist/Pastebin...):**
* **Server log if useful (Gist/Pastebin...):** something like this:
{"message":"184.91.69.131 - - [07/Jul/2018:22:00:49 +0000] \"POST /accounts/peertube/inbox HTTP/1.1\" 403 9 \"-\" \"-\"\n","level":"info","timestamp":"2018-07-07T22:00:49.286Z","label":"pirtube.cz:443"}
{"willRetry":false,"err":"TimeoutError: ResourceRequest timed out\n    at ResourceRequest._fireTimeout (/var/www/peertube/versions/peertube-v1.0.0-beta.9/node_modules/generic-pool/lib/ResourceRequest.js:62:17)\n    at Timeout.bound (/var/www/peertube/versions/peertube-v1.0.0-beta.9/node_modules/generic-pool/lib/ResourceRequest.js:8:15)\n    at ontimeout (timers.js:498:11)\n    at tryOnTimeout (timers.js:323:5)\n    at Timer.listOnTimeout (timers.js:290:5)","level":"debug","message":"Maybe retrying the transaction function.","timestamp":"2018-07-07T22:01:07.319Z","label":"pirtube.cz:443"}
{"level":"error","message":"Cannot execute function () { [native code] } with many retries.","splat":["function () { [native code] }"],"meta":{"err":{"name":"TimeoutError"}},"timestamp":"2018-07-07T22:01:07.320Z","label":"pirtube.cz:443"}
{"err":"TimeoutError: ResourceRequest timed out\n    at ResourceRequest._fireTimeout (/var/www/peertube/versions/peertube-v1.0.0-beta.9/node_modules/generic-pool/lib/ResourceRequest.js:62:17)\n    at Timeout.bound (/var/www/peertube/versions/peertube-v1.0.0-beta.9/node_modules/generic-pool/lib/ResourceRequest.js:8:15)\n    at ontimeout (timers.js:498:11)\n    at tryOnTimeout (timers.js:323:5)\n    at Timer.listOnTimeout (timers.js:290:5)","level":"error","message":"Cannot execute update videos scheduler.","timestamp":"2018-07-07T22:01:07.321Z","label":"pirtube.cz:443"}
{"willRetry":false,"err":"TimeoutError: ResourceRequest timed out\n    at ResourceRequest._fireTimeout (/var/www/peertube/versions/peertube-v1.0.0-beta.9/node_modules/generic-pool/lib/ResourceRequest.js:62:17)\n    at Timeout.bound (/var/www/peertube/versions/peertube-v1.0.0-beta.9/node_modules/generic-pool/lib/ResourceRequest.js:8:15)\n    at ontimeout (timers.js:498:11)\n    at tryOnTimeout (timers.js:323:5)\n    at Timer.listOnTimeout (timers.js:290:5)","level":"debug","message":"Maybe retrying the transaction function.","timestamp":"2018-07-07T22:02:07.321Z","label":"pirtube.cz:443"}
{"level":"error","message":"Cannot execute function () { [native code] } with many retries.","splat":["function () { [native code] }"],"meta":{"err":{"name":"TimeoutError"}},"timestamp":"2018-07-07T22:02:07.322Z","label":"pirtube.cz:443"}
{"err":"TimeoutError: ResourceRequest timed out\n    at ResourceRequest._fireTimeout (/var/www/peertube/versions/peertube-v1.0.0-beta.9/node_modules/generic-pool/lib/ResourceRequest.js:62:17)\n    at Timeout.bound (/var/www/peertube/versions/peertube-v1.0.0-beta.9/node_modules/generic-pool/lib/ResourceRequest.js:8:15)\n    at ontimeout (timers.js:498:11)\n    at tryOnTimeout (timers.js:323:5)\n    at Timer.listOnTimeout (timers.js:290:5)","level":"error","message":"Cannot execute update videos scheduler.","timestamp":"2018-07-07T22:02:07.323Z","label":"pirtube.cz:443"}
{"parameters":{"signature":{"type":"RsaSignature2017","created":"2018-07-07T22:02:10Z","creator":"https://peertube.nsa.ovh/accounts/peertube","signatureValue":"eyJhbGciOiJSUzI1NiIsImI2NCI6ZmFsc2UsImNyaXQiOlsiYjY0Il19..UASxNEymgOIUgssphvc2OU-yp59OdxI7WDwdZLitoMXWYD-4cu0Sot85L1BI8Dr7cT9FCS2fa93rRz75T7Ghy3b7DzN-NkVwKSfM7mU28FDdjvxM3t5LI3jXsN1qoMom_Bbsz4byReUTCvucsDUNZd5uvoLxOFoonO78BgyMrfzzJCkMkMr9Ms0Wq49eDmJopTT-dcPzj2o2X0wb4I0m4IiLH9sIQIKFM3KaEPvW4-P0fvp_m4J6oc8UQeyPLqbGrnJb0ydmrmKs1arQvGNXSOsetPudgtlnMnUvZ30XOWI4vJT7uvP1SZIe2_GNqndIUvdH5mogdDURQWaeX5dmeQ"}},"level":"debug","message":"Checking activitypub signature parameter","timestamp":"2018-07-07T22:02:10.503Z","label":"pirtube.cz:443"}
{"level":"debug","message":"Checking signature of actor https://peertube.nsa.ovh/accounts/peertube...","splat":["https://peertube.nsa.ovh/accounts/peertube"],"timestamp":"2018-07-07T22:02:10.504Z","label":"pirtube.cz:443"}
{"parameters":{"signature":{"type":"RsaSignature2017","created":"2018-07-07T22:02:11Z","creator":"https://peertube.waifus.eu/accounts/peertube","signatureValue":"eyJhbGciOiJSUzI1NiIsImI2NCI6ZmFsc2UsImNyaXQiOlsiYjY0Il19..kWjT_MUOUlOOtD_GS5wjYKamJeQvVZVdJZbZum1L2fVwyhbvNDH8sMADVxOZPkGuDjpCVZ1_xAIlI1h2jCkIjUnO74HCdEyrfu317QZ-tR24mMJNZp2j5nL6ea9Qu-uaeak7k244kzRU1U05T3-gSaKufH1Fy6ROsqMg0GroquLChPgBqow-PVwwgmNwoyxOaSgCqVzRe3jwXuWYtNy59trPh3-82cEtsx35TROcu_YCnHbovHR7EaQKIuqNPQ2Ypf11sio8xCErYCxdcTct9iH_GQBAen7WYkQaaredjDmDJp-fhT8wchYg-IqIdMBw_7qerIcGdFLlRq3JFFD-pg"}},"level":"debug","message":"Checking activitypub signature parameter","timestamp":"2018-07-07T22:02:11.569Z","label":"pirtube.cz:443"}
{"level":"debug","message":"Checking signature of actor https://peertube.waifus.eu/accounts/peertube...","splat":["https://peertube.waifus.eu/accounts/peertube"],"timestamp":"2018-07-07T22:02:11.570Z","label":"pirtube.cz:443"}
{"parameters":{"signature":{"type":"RsaSignature2017","created":"2018-07-07T22:02:11Z","creator":"https://meilleurtube.delire.party/accounts/peertube","signatureValue":"eyJhbGciOiJSUzI1NiIsImI2NCI6ZmFsc2UsImNyaXQiOlsiYjY0Il19..OoBISNUGwSG8MKy7Gn_i0vpTiZGykcVLRSEFtiQbXgrSaR9nDQyElKbxt8RXULLjm2CPb-6GxhK-6YxbIkwAUR1Zvv9ZfWAG5qHbEuJuct5Dztr3rYJC7VuF-GQKK_VW-265Rx5XGNT2wMM5CcAy3kF_J8N_pHEopdp5VyirwhF1emak44emugGIbs0A9e8N7Wsin9pyjYOTwMReITzcLPIXh4sgTCDq8uN3e_yPWG7uockmjLOZto9X_CLYn8W-yKoY-6NvKXNiojAl766u_BHGe-RzckaxQ9RAhTM2-AVzRf3Mk4s9VqVM5GLgNsPzB0nVU8HEr76LM0SR1hE4TA"}},"level":"debug","message":"Checking activitypub signature parameter","timestamp":"2018-07-07T22:02:12.120Z","label":"pirtube.cz:443"}
{"level":"debug","message":"Checking signature of actor https://meilleurtube.delire.party/accounts/peertube...","splat":["https://meilleurtube.delire.party/accounts/peertube"],"timestamp":"2018-07-07T22:02:12.121Z","label":"pirtube.cz:443"}
{"parameters":{"signature":{"type":"RsaSignature2017","created":"2018-07-07T22:02:12Z","creator":"https://video.4ray.co/accounts/peertube","signatureValue":"eyJhbGciOiJSUzI1NiIsImI2NCI6ZmFsc2UsImNyaXQiOlsiYjY0Il19..UtKvnsJWE2XndkQo54Be9xAL9KgQ0BMD9N1uqU_Vxp_ju8XNBq1PXOkQADtfRS_LRCqeijvDch536vmidq8-2FGHAA69NvM_abd6im_n_d-SItRhuxCOcreq015-iU9oChJrQrcQj38Y-jMbbs6hDix8WTzFpu9l9DBHZ1AS8-_SGez_UQ705nMAQ1LSRfn0OIhSuC4UG0jyFCHHzIEPRL-o-rx_hiHoEIsJ8t9Z-M__BIc6PUmc7nZxpOzJLYgoNUybjxtvFljPrkL16L6dKW_NK_EUsXjwtyOYYySA0lRQned8cSRoUf_K-moqqsUQZLcgoGU2DL0tHvX14yFfkg"}},"level":"debug","message":"Checking activitypub signature parameter","timestamp":"2018-07-07T22:02:13.865Z","label":"pirtube.cz:443"}
{"level":"debug","message":"Checking signature of actor https://video.4ray.co/accounts/peertube...","splat":["https://video.4ray.co/accounts/peertube"],"timestamp":"2018-07-07T22:02:13.866Z","label":"pirtube.cz:443"}
{"err":"TimeoutError: ResourceRequest timed out\n    at ResourceRequest._fireTimeout (/var/www/peertube/versions/peertube-v1.0.0-beta.9/node_modules/generic-pool/lib/ResourceRequest.js:62:17)\n    at Timeout.bound (/var/www/peertube/versions/peertube-v1.0.0-beta.9/node_modules/generic-pool/lib/ResourceRequest.js:8:15)\n    at ontimeout (timers.js:498:11)\n    at tryOnTimeout (timers.js:323:5)\n    at Timer.listOnTimeout (timers.js:290:5)","level":"error","message":"Cannot create remote actor and check signature.","timestamp":"2018-07-07T22:02:20.514Z","label":"pirtube.cz:443"}
{"message":"195.154.171.158 - - [07/Jul/2018:22:02:20 +0000] \"POST /accounts/peertube/inbox HTTP/1.1\" 403 9 \"-\" \"-\"\n","level":"info","timestamp":"2018-07-07T22:02:20.516Z","label":"pirtube.cz:443"}
{"err":"TimeoutError: ResourceRequest timed out\n    at ResourceRequest._fireTimeout (/var/www/peertube/versions/peertube-v1.0.0-beta.9/node_modules/generic-pool/lib/ResourceRequest.js:62:17)\n    at Timeout.bound (/var/www/peertube/versions/peertube-v1.0.0-beta.9/node_modules/generic-pool/lib/ResourceRequest.js:8:15)\n    at ontimeout (timers.js:498:11)\n    at tryOnTimeout (timers.js:323:5)\n    at Timer.listOnTimeout (timers.js:290:5)","level":"error","message":"Cannot create remote actor and check signature.","timestamp":"2018-07-07T22:02:21.579Z","label":"pirtube.cz:443"}
{"message":"5.9.245.84 - - [07/Jul/2018:22:02:21 +0000] \"POST /accounts/peertube/inbox HTTP/1.1\" 403 9 \"-\" \"-\"\n","level":"info","timestamp":"2018-07-07T22:02:21.584Z","label":"pirtube.cz:443"}
{"err":"TimeoutError: ResourceRequest timed out\n    at ResourceRequest._fireTimeout (/var/www/peertube/versions/peertube-v1.0.0-beta.9/node_modules/generic-pool/lib/ResourceRequest.js:62:17)\n    at Timeout.bound (/var/www/peertube/versions/peertube-v1.0.0-beta.9/node_modules/generic-pool/lib/ResourceRequest.js:8:15)\n    at ontimeout (timers.js:498:11)\n    at tryOnTimeout (timers.js:323:5)\n    at Timer.listOnTimeout (timers.js:290:5)","level":"error","message":"Cannot create remote actor and check signature.","timestamp":"2018-07-07T22:02:22.127Z","label":"pirtube.cz:443"}
{"message":"91.121.89.131 - - [07/Jul/2018:22:02:22 +0000] \"POST /accounts/peertube/inbox HTTP/1.1\" 403 9 \"-\" \"-\"\n","level":"info","timestamp":"2018-07-07T22:02:22.130Z","label":"pirtube.cz:443"}
{"err":"TimeoutError: ResourceRequest timed out\n    at ResourceRequest._fireTimeout (/var/www/peertube/versions/peertube-v1.0.0-beta.9/node_modules/generic-pool/lib/ResourceRequest.js:62:17)\n    at Timeout.bound (/var/www/peertube/versions/peertube-v1.0.0-beta.9/node_modules/generic-pool/lib/ResourceRequest.js:8:15)\n    at ontimeout (timers.js:498:11)\n    at tryOnTimeout (timers.js:323:5)\n    at Timer.listOnTimeout (timers.js:290:5)","level":"error","message":"Cannot create remote actor and check signature.","timestamp":"2018-07-07T22:02:23.874Z","label":"pirtube.cz:443"}
{"message":"184.91.69.131 - - [07/Jul/2018:22:02:23 +0000] \"POST /accounts/peertube/inbox HTTP/1.1\" 403 9 \"-\" \"-\"\n","level":"info","timestamp":"2018-07-07T22:02:23.876Z","label":"pirtube.cz:443"}

**Comment by Chocobozzz** [comment]
Hi,

Please copy/paste your nginx configuration

**Comment by KRtekTM** [comment]
server {
  listen 80;
#  listen [::]:80;
  server_name pirtube.cz;

  access_log /var/log/nginx/pirtube.access.log;
  error_log /var/log/nginx/pirtube.error.log;

  location /.well-known/acme-challenge/ {
    default_type "text/plain";
    root /var/www/certbot;
  }
  location / { return 301 https://$host$request_uri; }
}

server {
  listen 443 ssl http2;
  listen [::]:443 ssl http2;
  server_name pirtube.cz;

  # For example with certbot (you need a certificate to run https)
  ssl_certificate      /etc/letsencrypt/live/pirtube.cz/fullchain.pem;
#  ssl_certificate      /etc/letsencrypt/live/pirtube.cz/cert.pem;
  ssl_certificate_key  /etc/letsencrypt/live/pirtube.cz/privkey.pem;

  # Security hardening (as of 11/02/2018)
  ssl_protocols TLSv1.2; # TLSv1.3, TLSv1.2 if nginx >= 1.13.0
  ssl_prefer_server_ciphers on;
  ssl_ciphers 'ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA256';
  #ssl_ecdh_curve secp384r1; # Requires nginx >= 1.1.0, not compatible with import-videos script
  ssl_session_timeout  10m;
  ssl_session_cache shared:SSL:10m;
  ssl_session_tickets off; # Requires nginx >= 1.5.9
  ssl_stapling on; # Requires nginx >= 1.3.7
  ssl_stapling_verify on; # Requires nginx => 1.3.7

  # Configure with your resolvers
  # resolver $DNS-IP-1 $DNS-IP-2 valid=300s;
  # resolver_timeout 5s;

  add_header Strict-Transport-Security "max-age=63072000; includeSubDomains; preload";
  add_header X-Content-Type-Options nosniff;
  add_header X-XSS-Protection "1; mode=block";
  add_header X-Robots-Tag none;

  access_log /var/log/nginx/pirtube.access.log;
  error_log /var/log/nginx/pirtube.error.log;

  location ^~ '/.well-known/acme-challenge' {
    default_type "text/plain";
    root /var/www/certbot;
  }

  location ~ ^/client/(.*\.(js|css|woff2|otf|ttf|woff|eot))$ {
    add_header Cache-Control "public, max-age=31536000, immutable";

    alias /var/www/peertube/peertube-latest/client/dist/$1;
  }

  location ~ ^/static/(thumbnails|avatars)/(.*)$ {
    add_header Cache-Control "public, max-age=31536000, immutable";

    alias /var/www/peertube/storage/$1/$2;
  }

  location / {
    proxy_pass http://localhost:9000;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header Host $host;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

    # Hard limit, PeerTube does not support videos > 4GB
    client_max_body_size 4G;
    proxy_connect_timeout       600;
    proxy_send_timeout          600;
    proxy_read_timeout          600;
    send_timeout                600;
  }

  # Bypass PeerTube webseed route for better performances
  location /static/webseed {
    # Clients usually have 4 simultaneous webseed connections, so the real limit is 3MB/s per client
    limit_rate 800k;

    if ($request_method = 'OPTIONS') {
      add_header 'Access-Control-Allow-Origin' '*';
      add_header 'Access-Control-Allow-Methods' 'GET, OPTIONS';
      add_header 'Access-Control-Allow-Headers' 'Range,DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type';
      add_header 'Access-Control-Max-Age' 1728000;
      add_header 'Content-Type' 'text/plain charset=UTF-8';
      add_header 'Content-Length' 0;
      return 204;
    }

    if ($request_method = 'GET') {
      add_header 'Access-Control-Allow-Origin' '*';
      add_header 'Access-Control-Allow-Methods' 'GET, OPTIONS';
      add_header 'Access-Control-Allow-Headers' 'Range,DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type';

      # Don't spam access log file with byte range requests
      access_log off;
    }

    alias /var/www/peertube/storage/videos;
  }

  # Websocket tracker
  location /tracker/socket {
    # Peers send a message to the tracker every 15 minutes
    # Don't close the websocket before this time
    proxy_read_timeout 1200s;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "Upgrade";
    proxy_http_version 1.1;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header Host $host;
    proxy_pass http://localhost:9000;
  }
}

**Comment by KRtekTM** [comment]
I want to also mention that the PeerTube is not working with the nginx configuration copied above in case:
- the PeerTube server is just behind router and ports 80 and 443 are forwarded
- the PeerTube server is behind another server with Apache reverse proxy running, the apache server is behind router

My default approach was to use the Apache's reverse proxy as I have few more services on other domains hosted by the Apache and some other services behind its proxy.

As I said, I tried to connect the PeerTube nginx server directly behind the router and still with the Fullchain certificate no luck.
I tried also to follow the configuration for running PeerTube in BSD jail (of course modified to follow my Apache/Nginx infrastructure), installed another server with NGinx to server as reverse proxy (and get rid of apache's proxy), tried different certificates - issue still present :(

**Comment by Chocobozzz** [comment]
Try (without apache)

```
  ssl_certificate      /etc/letsencrypt/live/pirtube.cz/fullchain.pem;
  ssl_certificate_key  /etc/letsencrypt/live/pirtube.cz/privkey.pem;
  ssl_trusted_certificate /etc/letsencrypt/live/pirtube.cz/chain.pem;
```

**Comment by rigelk** [comment]
Otherwise there is still the possibility to only Apache… with the following config: https://gist.github.com/rigelk/07a0b8963fa4fc1ad756374c28479bc7

**Comment by KRtekTM** [comment]
Chocobozzz: unfortunately no change. Token is invalid
rigelk: Yes, I followed your config to set the reverse proxy on Apache. Fullchain or even adding chain with SSLCertificateChainFile leads to invalid token issue.

**Comment by Chocobozzz** [comment]
@KRtekTM I think your invalid token is another issue. I tried to register on your instance (`test_choco` as username you can remove), login and it works. Maybe your password is invalid?

For the SSL part, note than curl cannot access to your instance:

```
curl https://pirtube.cz
curl: (60) SSL certificate problem: unable to get local issuer certificate
More details here: https://curl.haxx.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
```

**Comment by KRtekTM** [comment]
You can't curl my server as it does not provide fullchain certificate now.
Yes, you can register and use my instance, but can't do federation or register to instances list.

You visited my server when just cert.pem was used so the certificate chain is incomplete and curl and other devices then can't verify the certificate.

**Comment by KRtekTM** [comment]
I am sure that my password is right - the invalid token appears just after I uncomment fullchain.pem and comment cert.pem in my nginx configuration, restart nginx and peertube services and then wait 1 minute.

After each restart of peertube service or postgresql service, it's working for a while.


Now my server is accessible because fullchain certificate is not applied as I need to have peertube running (even it's not mirroring correctly other instances).

**Comment by rezonant** [comment]
Have you tried to serve a static website without PeerTube involved? I'm almost certain you will have the same problem without PeerTube being involved at all

**Comment by KRtekTM** [comment]
Looks like I solved the issue.

I changed my configuration of PostgreSQL to contains this:
<pre>
tcp_keepalives_idle = 30                # TCP_KEEPIDLE, in seconds;
                                        # 0 selects the system default
tcp_keepalives_interval = 30            # TCP_KEEPINTVL, in seconds;
                                        # 0 selects the system default
tcp_keepalives_count = 0                # TCP_KEEPCNT;
                                        # 0 selects the system default
</pre>

and it works also behind reverse proxy.


Thanks to rezonant for his time spent on IRC with me.

**Comment by KRtekTM** [comment]
Unfortunately it only looks like it's solved.

Now, I have those values set to 1 second and still getting this in peertube.log:

<pre>
Jul 14 20:18:21 pirtube peertube: [pirtube.cz:443] 2018-07-14 20:18:21.315 #033[32minfo#033[39m: 94.130.180.133 - - [15/Jul/2018:00:18:21 +0000] "POST /accounts/peertube/inbox HTTP/1.0" - - "-" "-"
Jul 14 20:18:28 pirtube peertube: [pirtube.cz:443] 2018-07-14 20:18:28.435 #033[34mdebug#033[39m: Executing (c77ca136-264f-4e5b-9895-1b74c8fad53b): ROLLBACK;
Jul 14 20:18:28 pirtube peertube: [pirtube.cz:443] 2018-07-14 20:18:28.439 #033[34mdebug#033[39m: Maybe retrying the transaction function. {
Jul 14 20:18:28 pirtube peertube: "willRetry": false,
Jul 14 20:18:28 pirtube peertube: "err": "TimeoutError: ResourceRequest timed out\n    at ResourceRequest._fireTimeout (/var/www/peertube/versions/dev/PeerTube/node_modules/generic-pool/lib/ResourceRequest.js:62:17)\n    at Timeout.bound (/var/www/peertube/versions/dev/PeerTube/node_modules/generic-pool/lib/ResourceRequest.js:8:15)\n    at ontimeout (timers.js:498:11)\n    at tryOnTimeout (timers.js:323:5)\n    at Timer.listOnTimeout (timers.js:290:5)"
Jul 14 20:18:28 pirtube peertube: }
Jul 14 20:18:28 pirtube peertube: [pirtube.cz:443] 2018-07-14 20:18:28.440 #033[31merror#033[39m: Cannot execute processFollow with many retries. {
Jul 14 20:18:28 pirtube peertube: "err": "TimeoutError: ResourceRequest timed out\n    at ResourceRequest._fireTimeout (/var/www/peertube/versions/dev/PeerTube/node_modules/generic-pool/lib/ResourceRequest.js:62:17)\n    at Timeout.bound (/var/www/peertube/versions/dev/PeerTube/node_modules/generic-pool/lib/ResourceRequest.js:8:15)\n    at ontimeout (timers.js:498:11)\n    at tryOnTimeout (timers.js:323:5)\n    at Timer.listOnTimeout (timers.js:290:5)"
Jul 14 20:18:28 pirtube peertube: }
Jul 14 20:18:28 pirtube peertube: [pirtube.cz:443] 2018-07-14 20:18:28.441 #033[33mwarn#033[39m: Cannot process activity Follow.
</pre>

**Comment by rezonant** [comment]
Could it be that the servers being follow are what's failing, not the follow(ing) server? Or perhaps something is misformatted in the URL for the server you've set to follow or something. :-S

**Comment by KRtekTM** [comment]
Now I upgraded postgresql from 9.2.8 to 10.2 and inspecting.

**Comment by KRtekTM** [comment]
So after upgrade to postgresql 10.2, the fullchain certificate works.

**Comment by federicosanchez18** [comment]
hi i have 
![captura de pantalla de 2018-11-29 19-22-42](https://user-images.githubusercontent.com/19497827/49259306-a1285400-f417-11e8-93b3-abf81134af63.png)
a problem whit certicated 
this is my problem
