### ISSUE TITLE
Bull have problems with redis and crashing in loop

### ISSUE THREAD

**Issue by Jorropo** [Chocobozzz/PeerTube#883]
* **PeerTube version or URL:**
1.0.0.beta.10.pre.2
* **NodeJS version:**
v8.11.3

* **What is the expected behaviour?**
Running the node
* **What do you see instead?**
My node try to start then crash then service manager restart it and the run in a infinite loop.
All working fine when I go to sleep and that happend durring the night

* **Server log if useful (Gist/Pastebin...):**
[https://gist.github.com/Jorropo/64aea2dcafa428e3669a8bbb2fa1ecdd](https://gist.github.com/Jorropo/64aea2dcafa428e3669a8bbb2fa1ecdd)

**Comment by Jorropo** [comment]
Bug semi-fixed purging redis database solved the problem (cause the problem was in jobs list), but the bug still here and a node maybe can crash randomly

**Comment by Jorropo** [comment]
@rigelk reproduced (and I have better log right now) (I just let my node running with an purged db)
```
Jul 29 12:50:49 peertubeVPS peertube[29127]:   command:
Jul 29 12:50:49 peertubeVPS peertube[29127]:    { name: 'brpoplpush',
Jul 29 12:50:49 peertubeVPS peertube[29127]:      args:
Jul 29 12:50:49 peertubeVPS peertube[29127]:       [ 'bull-peertube.jorropo.ovh:activitypub-http-unicast:wait',
Jul 29 12:50:49 peertubeVPS peertube[29127]:         'bull-peertube.jorropo.ovh:activitypub-http-unicast:active',
Jul 29 12:50:49 peertubeVPS peertube[29127]:         '5' ] } }
Jul 29 12:50:49 peertubeVPS peertube[29127]: BRPOPLPUSH { ReplyError: MISCONF Redis is configured to save RDB snapshots, but is currently not able to persist on disk. Commands that may modify the data set are disabled. Please check Redis logs for details about the error.
Jul 29 12:50:49 peertubeVPS peertube[29127]:     at JavascriptRedisParser.returnError (/var/www/peertube/versions/peertube-v1.0.0-beta.10.pre.2/node_modules/ioredis/lib/redis/parser.js:24:25)
Jul 29 12:50:49 peertubeVPS peertube[29127]:     at JavascriptRedisParser.execute (/var/www/peertube/versions/peertube-v1.0.0-beta.10.pre.2/node_modules/redis-parser/lib/parser.js:572:12)
Jul 29 12:50:49 peertubeVPS peertube[29127]:     at Socket.<anonymous> (/var/www/peertube/versions/peertube-v1.0.0-beta.10.pre.2/node_modules/ioredis/lib/redis/event_handler.js:107:22)
Jul 29 12:50:49 peertubeVPS peertube[29127]:     at emitOne (events.js:116:13)
Jul 29 12:50:49 peertubeVPS peertube[29127]:     at Socket.emit (events.js:211:7)
Jul 29 12:50:49 peertubeVPS peertube[29127]:     at addChunk (_stream_readable.js:263:12)
Jul 29 12:50:49 peertubeVPS peertube[29127]:     at readableAddChunk (_stream_readable.js:250:11)
Jul 29 12:50:49 peertubeVPS peertube[29127]:     at Socket.Readable.push (_stream_readable.js:208:10)
Jul 29 12:50:49 peertubeVPS peertube[29127]:     at TCP.onread (net.js:597:20)
Jul 29 12:50:49 peertubeVPS peertube[29127]:   name: 'ReplyError',
Jul 29 12:50:49 peertubeVPS peertube[29127]:   message: 'MISCONF Redis is configured to save RDB snapshots, but is currently not able to persist on disk. Commands that may modify the data set are disabled. Please check Redis logs for details about the error.',
```

**Comment by Jorropo** [comment]
And, this times I touched to nothings and after 11 crash/restart it restarted by there own

**Comment by rigelk** [comment]
Could you provide the redis logs?

**Comment by Jorropo** [comment]
@rigelk
```
29100:M 29 Jul 12:50:47.089 * 10 changes in 300 seconds. Saving...
29100:M 29 Jul 12:50:47.089 # Can't save in background: fork: Cannot allocate memory
29100:M 29 Jul 12:50:53.101 * 10 changes in 300 seconds. Saving...
29100:M 29 Jul 12:50:53.101 # Can't save in background: fork: Cannot allocate memory
29100:M 29 Jul 12:50:59.008 * 10 changes in 300 seconds. Saving...
29100:M 29 Jul 12:50:59.008 # Can't save in background: fork: Cannot allocate memory
764:M 29 Jul 14:12:50.014 * 1 changes in 900 seconds. Saving...
764:M 29 Jul 14:12:50.014 # Can't save in background: fork: Cannot allocate memory
```
The problem is my node use 900 M of memory for os/other, peertube ~ 50 M max and there is 1G of free space

**Comment by rigelk** [comment]
So this looks more like a lack of resources than a configuration problem, right?

**Comment by Jorropo** [comment]
@rigelk I found were is the problem, in fact all memory is been used by file caching, but my kernel is configuration to not overwrite file caching (that should be activated normaly).
```sh
sysctl vm.overcommit_memory=1
```
