### ISSUE TITLE
update from beta9 to beta10: peertube don't start, exit status 255

### ISSUE THREAD

**Issue by lfuentes-lbn** [Chocobozzz/PeerTube#913]
* **PeerTube version or URL:** trying update from beta9 to beta10
* **NodeJS version:** v10.8.0

Running under archlinux with npm v6.3.0 and yarn v1.9.4.

After upgrading to beta10 (database extensions are installed), I cannot start peertube anymore.

There is the daemon log:
```
août 08 17:53:56 peshkim2 systemd[1]: Started PeerTube daemon.
août 08 17:53:56 peshkim2 peertube[28568]: > peertube@1.0.0-beta.10 start /usr/share/webapps/peertube
août 08 17:53:56 peshkim2 peertube[28568]: > node dist/server
août 08 17:53:58 peshkim2 peertube[28568]: [peertube.peshane.net:443] 2018-08-08 17:53:58.584 info: Database peertube_prod is ready.
août 08 17:53:58 peshkim2 peertube[28568]: [peertube.peshane.net:443] 2018-08-08 17:53:58.823 info: Using localhost:25 as SMTP server.
août 08 17:53:58 peshkim2 peertube[28568]: [peertube.peshane.net:443] 2018-08-08 17:53:58.826 info: Testing SMTP server...
août 08 17:53:58 peshkim2 peertube[28568]: [peertube.peshane.net:443] 2018-08-08 17:53:58.836 info: Connection established to 127.0.0.1:25 {
août 08 17:53:58 peshkim2 peertube[28568]:   "component": "smtp-connection",
août 08 17:53:58 peshkim2 peertube[28568]:   "sid": "cEUz11yQcE",
août 08 17:53:58 peshkim2 peertube[28568]:   "tnx": "network",
août 08 17:53:58 peshkim2 peertube[28568]:   "localAddress": "127.0.0.1",
août 08 17:53:58 peshkim2 peertube[28568]:   "localPort": 44656,
août 08 17:53:58 peshkim2 peertube[28568]:   "remoteAddress": "127.0.0.1",
août 08 17:53:58 peshkim2 peertube[28568]:   "remotePort": 25
août 08 17:53:58 peshkim2 peertube[28568]: }
août 08 17:53:58 peshkim2 peertube[28568]: [peertube.peshane.net:443] 2018-08-08 17:53:58.861 info: Successfully connected to SMTP server.
août 08 17:53:58 peshkim2 peertube[28568]: [peertube.peshane.net:443] 2018-08-08 17:53:58.877 error: Cannot start application.
août 08 17:53:58 peshkim2 peertube[28568]: npm ERR! code ELIFECYCLE
août 08 17:53:58 peshkim2 peertube[28568]: npm ERR! errno 255
août 08 17:53:58 peshkim2 peertube[28568]: npm ERR! peertube@1.0.0-beta.10 start: `node dist/server`
août 08 17:53:58 peshkim2 peertube[28568]: npm ERR! Exit status 255
août 08 17:53:58 peshkim2 peertube[28568]: npm ERR!
août 08 17:53:58 peshkim2 peertube[28568]: npm ERR! Failed at the peertube@1.0.0-beta.10 start script.
août 08 17:53:58 peshkim2 peertube[28568]: npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
août 08 17:53:58 peshkim2 peertube[28568]: npm ERR! A complete log of this run can be found in:
août 08 17:53:58 peshkim2 peertube[28568]: npm ERR!     /var/lib/peertube/.npm/_logs/2018-08-08T15_53_58_898Z-debug.log
août 08 17:53:58 peshkim2 systemd[1]: peertube.service: Main process exited, code=exited, status=255/n/a
août 08 17:53:58 peshkim2 systemd[1]: peertube.service: Failed with result 'exit-code'.
août 08 17:53:59 peshkim2 systemd[1]: peertube.service: Service RestartSec=100ms expired, scheduling restart.
août 08 17:53:59 peshkim2 systemd[1]: peertube.service: Scheduled restart job, restart counter is at 1.
août 08 17:53:59 peshkim2 systemd[1]: Stopped PeerTube daemon.
```

and the npm debug log:
```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'start' ]
2 info using npm@6.3.0
3 info using node@v10.8.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle peertube@1.0.0-beta.10~prestart: peertube@1.0.0-beta.10
6 info lifecycle peertube@1.0.0-beta.10~start: peertube@1.0.0-beta.10
7 verbose lifecycle peertube@1.0.0-beta.10~start: unsafe-perm in lifecycle true
8 verbose lifecycle peertube@1.0.0-beta.10~start: PATH: /usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/usr/share/webapps/peertube/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/bin
9 verbose lifecycle peertube@1.0.0-beta.10~start: CWD: /usr/share/webapps/peertube
10 silly lifecycle peertube@1.0.0-beta.10~start: Args: [ '-c', 'node dist/server' ]
11 silly lifecycle peertube@1.0.0-beta.10~start: Returned: code: 255  signal: null
12 info lifecycle peertube@1.0.0-beta.10~start: Failed to exec start script
13 verbose stack Error: peertube@1.0.0-beta.10 start: `node dist/server`
13 verbose stack Exit status 255
13 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:304:16)
13 verbose stack     at EventEmitter.emit (events.js:182:13)
13 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:182:13)
13 verbose stack     at maybeClose (internal/child_process.js:962:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:249:5)
14 verbose pkgid peertube@1.0.0-beta.10
15 verbose cwd /usr/share/webapps/peertube
16 verbose Linux 4.17.12-arch1-1-ARCH
17 verbose argv "/usr/bin/node" "/usr/bin/npm" "start"
18 verbose node v10.8.0
19 verbose npm  v6.3.0
20 error code ELIFECYCLE
21 error errno 255
22 error peertube@1.0.0-beta.10 start: `node dist/server`
22 error Exit status 255
23 error Failed at the peertube@1.0.0-beta.10 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 255, true ]
```

I try to remove the `node_modules` dir and `yarn instann --production --pure-lockfile` but that do not change anything.

Does anyone can help me on this ? :sweat_smile:

**Comment by Chocobozzz** [comment]
Please copy/paste the file log (`storage/logs`)

**Comment by Chocobozzz** [comment]
We have a logger bug in this beta. Please add a console.log(err) in dist/server.js in the "cannot start application" block to see what is the error.

**Comment by lfuentes-lbn** [comment]
Allright !

I missed that a *captions size* must be set in conf file :confused: : 
```
août 08 18:50:45 peshkim2 peertube[6666]: [peertube.peshane.net:443] 2018-08-08 18:50:45.497 error: Cannot start application.                                
août 08 18:50:45 peshkim2 peertube[6666]: Error: Configuration property "cache.captions.size" is not defined                                                 
août 08 18:50:45 peshkim2 peertube[6666]:     at Config.get (/usr/share/webapps/peertube/node_modules/config/lib/config.js:202:11)                           
août 08 18:50:45 peshkim2 peertube[6666]:     at Object.get SIZE [as SIZE] (/usr/share/webapps/peertube/dist/server/initializers/constants.js:193:40)        
août 08 18:50:45 peshkim2 peertube[6666]:     at /usr/share/webapps/peertube/dist/server.js:147:105                                                          août 08 18:50:45 peshkim2 peertube[6666]:     at Generator.next (<anonymous>)                                                                                août 08 18:50:45 peshkim2 peertube[6666]:     at fulfilled (/usr/share/webapps/peertube/dist/server.js:4:58)                                                 
août 08 18:50:45 peshkim2 peertube[6666]:     at process._tickCallback (internal/process/next_tick.js:68:7)         
```
(real PID :smiling_imp: )

It's all ok now, thanks to you and the `console.log(err)` trick !
