### ISSUE TITLE
Node import video fails

### ISSUE THREAD

**Issue by hellomotow** [Chocobozzz/PeerTube#927]
BETA 10
Chrome
v8.11.4

I get the following error when trying to import videos now after upgrading.

```
root@ubuntu:~# CLONE="$(pwd)/PeerTube"
root@ubuntu:~# cd ${CLONE}
root@ubuntu:~/PeerTube# cd ${CLONE}
root@ubuntu:~/PeerTube# node dist/server/tools/import-videos.js -u "https://peertube.url.com" -U "root" --password "rootpassword" -t "https://videolink.mp4"
Will download and upload 1 videos.

(node:1626) UnhandledPromiseRejectionWarning: Error: expected 200 "OK", got 400 "Bad Request"
    at Test._assertStatus (/root/PeerTube/node_modules/supertest/lib/test.js:268:12)
    at Test._assertFunction (/root/PeerTube/node_modules/supertest/lib/test.js:283:11)
    at Test.assert (/root/PeerTube/node_modules/supertest/lib/test.js:173:18)
    at assert (/root/PeerTube/node_modules/supertest/lib/test.js:131:12)
    at /root/PeerTube/node_modules/supertest/lib/test.js:128:5
    at Test.Request.callback (/root/PeerTube/node_modules/superagent/lib/node/index.js:718:3)
    at parser (/root/PeerTube/node_modules/superagent/lib/node/index.js:906:18)
    at IncomingMessage.res.on (/root/PeerTube/node_modules/superagent/lib/node/parsers/json.js:19:7)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
(node:1626) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:1626) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

```

**Comment by rigelk** [comment]
The link to your video seems to answer 404 ; check for a valid URL.

**Comment by hellomotow** [comment]
@rigelk In my example above? It is edited. I am able to download the video link with wget

**Comment by hellomotow** [comment]
Converting back to beta-9 fixed this. Issue is with 10.

**Comment by Chocobozzz** [comment]
@hellomotow You mean https://videolink.mp4?

**Comment by hellomotow** [comment]
@Chocobozzz That url was just an example. I edited the working video link for privacy.

**Comment by Chocobozzz** [comment]
@hellomotow I can't reproduce on latest dev branch and without the target URL nor peertube debug logs it's difficult to resolve this issue.
