### ISSUE TITLE
Peertube beta 11 not starting

### ISSUE THREAD

**Issue by Jorropo** [Chocobozzz/PeerTube#935]
* **PeerTube version or URL:**
v1 beta 11, [peertube.jorropo.ovh](https://peertube.jorropo.ovh/)
* **NodeJS version:**
v8.11.4

* **What is the expected behaviour?**
The peertube instances normaly start and work
* **What do you see instead?**
Crash at start

* **Server log if useful (Gist/Pastebin...):**
```sh
root@vps568921:/var/www/peertube# journalctl -fu peertube
Aug 21 09:50:16 vps568921 systemd[1]: Started PeerTube daemon.
Aug 21 09:50:17 vps568921 peertube[6272]: > peertube@1.0.0-beta.11 start /var/www/peertube/versions/peertube-v1.0.0-beta.11
Aug 21 09:50:17 vps568921 peertube[6272]: > node dist/server
Aug 21 09:50:17 vps568921 peertube[6272]: /var/www/peertube/versions/peertube-v1.0.0-beta.11/node_modules/config/lib/config.js:203
Aug 21 09:50:17 vps568921 peertube[6272]:     throw new Error('Configuration property "' + property + '" is not defined');
Aug 21 09:50:17 vps568921 peertube[6272]:     ^
Aug 21 09:50:17 vps568921 peertube[6272]: Error: Configuration property "database.pool.max" is not defined
Aug 21 09:50:17 vps568921 peertube[6272]:     at Config.get (/var/www/peertube/versions/peertube-v1.0.0-beta.11/node_modules/config/lib/config.js:203:11)
Aug 21 09:50:17 vps568921 peertube[6272]:     at Object.<anonymous> (/var/www/peertube/versions/peertube-v1.0.0-beta.11/dist/server/initializers/constants.js:136:25)
Aug 21 09:50:17 vps568921 peertube[6272]:     at Module._compile (module.js:652:30)
Aug 21 09:50:17 vps568921 peertube[6272]:     at Object.Module._extensions..js (module.js:663:10)
Aug 21 09:50:17 vps568921 peertube[6272]:     at Module.load (module.js:565:32)
Aug 21 09:50:17 vps568921 peertube[6272]:     at tryModuleLoad (module.js:505:12)
Aug 21 09:50:17 vps568921 peertube[6272]:     at Function.Module._load (module.js:497:3)
Aug 21 09:50:17 vps568921 peertube[6272]:     at Module.require (module.js:596:17)
Aug 21 09:50:17 vps568921 peertube[6272]:     at require (internal/module.js:11:18)
Aug 21 09:50:17 vps568921 peertube[6272]:     at Object.<anonymous> (/var/www/peertube/versions/peertube-v1.0.0-beta.11/dist/server/initializers/index.js:7:10)
Aug 21 09:50:17 vps568921 peertube[6272]: npm ERR! code ELIFECYCLE
Aug 21 09:50:17 vps568921 peertube[6272]: npm ERR! errno 1
Aug 21 09:50:17 vps568921 peertube[6272]: npm ERR! peertube@1.0.0-beta.11 start: `node dist/server`
Aug 21 09:50:17 vps568921 peertube[6272]: npm ERR! Exit status 1
Aug 21 09:50:17 vps568921 peertube[6272]: npm ERR!
Aug 21 09:50:17 vps568921 peertube[6272]: npm ERR! Failed at the peertube@1.0.0-beta.11 start script.
Aug 21 09:50:17 vps568921 peertube[6272]: npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
Aug 21 09:50:17 vps568921 peertube[6272]: npm ERR! A complete log of this run can be found in:
Aug 21 09:50:17 vps568921 peertube[6272]: npm ERR!     /var/www/peertube/.npm/_logs/2018-08-21T07_50_17_580Z-debug.log
root@vps568921:/var/www/peertube# cat /var/www/peertube/.npm/_logs/2018-08-21T07_40_27_563Z-debug.log
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'start' ]
2 info using npm@5.6.0
3 info using node@v8.11.4
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle peertube@1.0.0-beta.11~prestart: peertube@1.0.0-beta.11
6 info lifecycle peertube@1.0.0-beta.11~start: peertube@1.0.0-beta.11
7 verbose lifecycle peertube@1.0.0-beta.11~start: unsafe-perm in lifecycle true
8 verbose lifecycle peertube@1.0.0-beta.11~start: PATH: /usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/var/www/peertube/versions/peertube-v1.0.0-beta.11/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
9 verbose lifecycle peertube@1.0.0-beta.11~start: CWD: /var/www/peertube/versions/peertube-v1.0.0-beta.11
10 silly lifecycle peertube@1.0.0-beta.11~start: Args: [ '-c', 'node dist/server' ]
11 silly lifecycle peertube@1.0.0-beta.11~start: Returned: code: 1  signal: null
12 info lifecycle peertube@1.0.0-beta.11~start: Failed to exec start script
13 verbose stack Error: peertube@1.0.0-beta.11 start: `node dist/server`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:285:16)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at EventEmitter.emit (events.js:214:7)
13 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at ChildProcess.emit (events.js:214:7)
13 verbose stack     at maybeClose (internal/child_process.js:925:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
14 verbose pkgid peertube@1.0.0-beta.11
15 verbose cwd /var/www/peertube/versions/peertube-v1.0.0-beta.11
16 verbose Linux 4.9.0-8-amd64
17 verbose argv "/usr/bin/node" "/usr/bin/npm" "start"
18 verbose node v8.11.4
19 verbose npm  v5.6.0
20 error code ELIFECYCLE
21 error errno 1
22 error peertube@1.0.0-beta.11 start: `node dist/server`
22 error Exit status 1
23 error Failed at the peertube@1.0.0-beta.11 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```
All logs in storage/logs came from beta.10

**Comment by Jorropo** [comment]
Updated : 
I find better log

**Comment by Jorropo** [comment]
Solved

**Comment by Chocobozzz** [comment]
Please follow the [production upgrade guide](https://github.com/Chocobozzz/PeerTube/blob/develop/support/doc/production.md#upgrade).

You should do the **Copy new configuration defaults values and update your configuration file:** commands.

**Comment by Jorropo** [comment]
@Chocobozzz why peertube don't use peertube-latest/config/default.yaml ?

**Comment by Chocobozzz** [comment]
Because we cannot specify multiple configuration directories in [node-config](https://github.com/lorenwest/node-config) module.
