### ISSUE TITLE
Rate limit WS and API for DoS mitigation

### ISSUE THREAD

**Issue by scanlime** [Chocobozzz/PeerTube#949]
I'm happy to see the rate limits in the default configuration for nginx, when reading bulk video resources! And that inspired me to check what happens when a client spams the websocket endpoint.

There's no rate limit, which is an opportunity for improvement I think.

I also noticed that the server will log errors generated by socket clients, and those log messages 1) aren't rate limited either, and 2) don't seem to identify the IP of the offending client.

Here's a sample log, I think I was doing something like "xxd /dev/urandom | ws wss://my-server/tracker/socket"

```
==> peertube5.log <==
{"err":{"stack":"SyntaxError: Unexpected number in JSON at position 1\n    at JSON.parse (<anonymous>)\n    at parseWebSocketRequest (/var/www/peertube/versions/peertube-v1.0.0-beta.10/node_modules/bittorrent-tracker/lib/server/parse-websocket.js:7:17)\n    at Server._onWebSocketRequest (/var/www/peertube/versions/peertube-v1.0.0-beta.10/node_modules/bittorrent-tracker/server.js:486:14)\n    at WebSocket.socket.onMessageBound (/var/www/peertube/versions/peertube-v1.0.0-beta.10/node_modules/bittorrent-tracker/server.js:467:10)\n    at emitOne (events.js:116:13)\n    at WebSocket.emit (events.js:211:7)\n    at Receiver.receiverOnMessage (/var/www/peertube/versions/peertube-v1.0.0-beta.10/node_modules/ws/lib/websocket.js:720:20)\n    at emitOne (events.js:116:13)\n    at Receiver.emit (events.js:211:7)\n    at Receiver.dataMessage (/var/www/peertube/versions/peertube-v1.0.0-beta.10/node_modules/ws/lib/receiver.js:414:14)\n    at Receiver.getData (/var/www/peertube/versions/peertube-v1.0.0-beta.10/node_modules/ws/lib/receiver.js:346:17)\n    at Receiver.startLoop (/var/www/peertube/versions/peertube-v1.0.0-beta.10/node_modules/ws/lib/receiver.js:133:22)\n    at Receiver._write (/var/www/peertube/versions/peertube-v1.0.0-beta.10/node_modules/ws/lib/receiver.js:69:10)\n    at doWrite (_stream_writable.js:397:12)\n    at writeOrBuffer (_stream_writable.js:383:5)\n    at Receiver.Writable.write (_stream_writable.js:290:11)\n    at Socket.socketOnData (/var/www/peertube/versions/peertube-v1.0.0-beta.10/node_modules/ws/lib/websocket.js:795:35)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at addChunk (_stream_readable.js:263:12)\n    at readableAddChunk (_stream_readable.js:250:11)\n    at Socket.Readable.push (_stream_readable.js:208:10)\n    at TCP.onread (net.js:597:20)","message":"Unexpected number in JSON at position 1"},"level":"warn","message":"Warning in tracker.","label":"diode.zone:443","timestamp":"2018-08-21T18:18:00.175Z"}
{"err":{"stack":"SyntaxError: Unexpected number in JSON at position 1\n    at JSON.parse (<anonymous>)\n    at parseWebSocketRequest (/var/www/peertube/versions/peertube-v1.0.0-beta.10/node_modules/bittorrent-tracker/lib/server/parse-websocket.js:7:17)\n    at Server._onWebSocketRequest (/var/www/peertube/versions/peertube-v1.0.0-beta.10/node_modules/bittorrent-tracker/server.js:486:14)\n    at WebSocket.socket.onMessageBound (/var/www/peertube/versions/peertube-v1.0.0-beta.10/node_modules/bittorrent-tracker/server.js:467:10)\n    at emitOne (events.js:116:13)\n    at WebSocket.emit (events.js:211:7)\n    at Receiver.receiverOnMessage (/var/www/peertube/versions/peertube-v1.0.0-beta.10/node_modules/ws/lib/websocket.js:720:20)\n    at emitOne (events.js:116:13)\n    at Receiver.emit (events.js:211:7)\n    at Receiver.dataMessage (/var/www/peertube/versions/peertube-v1.0.0-beta.10/node_modules/ws/lib/receiver.js:414:14)\n    at Receiver.getData (/var/www/peertube/versions/peertube-v1.0.0-beta.10/node_modules/ws/lib/receiver.js:346:17)\n    at Receiver.startLoop (/var/www/peertube/versions/peertube-v1.0.0-beta.10/node_modules/ws/lib/receiver.js:133:22)\n    at Receiver._write (/var/www/peertube/versions/peertube-v1.0.0-beta.10/node_modules/ws/lib/receiver.js:69:10)\n    at doWrite (_stream_writable.js:397:12)\n    at writeOrBuffer (_stream_writable.js:383:5)\n    at Receiver.Writable.write (_stream_writable.js:290:11)\n    at Socket.socketOnData (/var/www/peertube/versions/peertube-v1.0.0-beta.10/node_modules/ws/lib/websocket.js:795:35)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at addChunk (_stream_readable.js:263:12)\n    at readableAddChunk (_stream_readable.js:250:11)\n    at Socket.Readable.push (_stream_readable.js:208:10)\n    at TCP.onread (net.js:597:20)","message":"Unexpected number in JSON at position 1"},"level":"warn","message":"Warning in tracker.","label":"diode.zone:443","timestamp":"2018-08-21T18:18:00.175Z"}
{"err":{"stack":"SyntaxError: Unexpected number in JSON at position 1\n    at JSON.parse (<anonymous>)\n    at parseWebSocketRequest (/var/www/peertube/versions/peertube-v1.0.0-beta.10/node_modules/bittorrent-tracker/lib/server/parse-websocket.js:7:17)\n    at Server._onWebSocketRequest (/var/www/peertube/versions/peertube-v1.0.0-beta.10/node_modules/bittorrent-tracker/server.js:486:14)\n    at WebSocket.socket.onMessageBound (/var/www/peertube/versions/peertube-v1.0.0-beta.10/node_modules/bittorrent-tracker/server.js:467:10)\n    at emitOne (events.js:116:13)\n    at WebSocket.emit (events.js
...
```

**Comment by Jorropo** [comment]
:+1: 
please use code block (```) for your logs

**Comment by Chocobozzz** [comment]
Renamed the issue. The whole API (and tracker too) should have a rate limiter. But you known, a small application like peertube on an average server is difficult to protect against DDOS.

**Comment by scanlime** [comment]
If we could do some built-in rate limiting in peertube, and send failures to a log file that fail2ban can read, that might be about the best we can do without additional hardware or network services.

**Comment by Chocobozzz** [comment]
We already use a rate limiter module (for login) https://github.com/Chocobozzz/PeerTube/blob/develop/server/controllers/api/users.ts#L55

**Comment by rigelk** [comment]
But now, what's a good rate for each service we want to rate-limit? Do we need something dynamic or is something fixed good enough?

**Comment by scanlime** [comment]
can we limit per-connection bandwidth, just like we do for webseeds? at that level it seems like there'd be a clear difference between normal and flood traffic.

(doing it at the nginx level may even be enough, though we may have less opportunity to log and ban offenders)

**Comment by Chocobozzz** [comment]
API rate limit implemented in https://github.com/Chocobozzz/PeerTube/commit/c1340a6ac35f924161e6ec2a1d728e20c89e55c8
